sonic-net/sonic-mgmt

tests/platform_tests/test_memory_exhaustion.py
Single ASIC linecards have more available memory than other platforms so the total available memory takes longer to exhaust. Increase the timeout accordingly.
The test case is currently failing because the currently specified timeout is insufficient to exhaust the available memory on a single ASIC linecard.
I increased the timeout by 2 minutes which ensures that the memory is fully exhausted and thus the linecard reboot gets triggered.
I ran the test manually on a device with a single ASIC linecard.
=> Increase SSH shutdown timeout for memory exhaustion test

ansible/roles/test/files/ptftests/fib_test.py, ansible/roles/test/files/ptftests/py3/hash_test.py
Since Cherry-picking to 202205 failed from master for PR#10365. Opening this PR just for 202205 branch
In case of chassis-packet switch type, when src port of the traffic is on the same DUT and same asic as destination port, it sends out traffic only on the ports that belong to the same asic. Currently both fib_test and hash_test was set to send out on ports that belonged to different asic causing the balancing test to fail. THis change pertains only to chassis-packet switch type
Summary:
Fix balancing test for chassis packet switch type
=> 202205:Select only ports belonging to same asic - chassis-packet

tests/telemetry/conftest.py, tests/telemetry/test_events.py
Summary:
Fixes # (issue)25860806
I am changing the order of the testcases in test_events because eventd heartbeat testcase should be used as a preliminary test before all testcases since it is testing that a critical part of eventd which is heartbeat is working correctly. It is also good that it is executed first because we can use it to drain the eventd cache in case there were any published events missed due to cache overflow.
Code change
Manual testing/pipeline
=> Reorder eventd heartbeat testcase as first testcase

tests/override_config_table/test_override_config_table.py, tests/override_config_table/test_override_config_table_masic.py
SUP fail at that time after config reload when check for pfcwd here:            
[` pytest_assert(wait_until(300, 20, 0, chk_for_pfc_wd, sonic_host),`](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/config_reload.py#L147)
This check_for_pfc_wd always return false because 
https://github.com/sonic-net/sonic-mgmt/blob/ef2836ff720a51b5d97611bfb5eed47b40d3c465/tests/configlet/util/common.py#L186 
here SUP has no frontend asics(all fabric)
This PR use fixture `enum_rand_one_per_hwsku_frontend_hostname` which ensure the random dut from chassis is not supervisor.
https://github.com/sonic-net/sonic-mgmt/blob/ef2836ff720a51b5d97611bfb5eed47b40d3c465/tests/common/helpers/dut_utils.py#L30
Summary:
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/11010
=> [Override config table] exclude supervisor from override config tests

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/ecmp/test_ecmp_sai_value.py
…ue is correct
Summary:
It's a new test script test_ecmp_sai_value.py to verify if HASH_SEED and OFFSET_ECMP value is correct after 20230531.10 image on Broadcom T1 testbed.
Cover the changes in https://github.com/sonic-net/sonic-buildimage/pull/17505.
It's a new test script test_ecmp_sai_value.py to verify if HASH_SEED and OFFSET_ECMP value is correct after 20230531.10 image on Broadcom T1 testbed.
Check Broadcom register values via bcmcmd.
Also cover syncd restart and config reload scenarios.
run ecmp/test_ecmp_sai_value.py
=> [test gap] Add test script to verify if HASH_SEED and OFFSET_ECMP value is correct

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
`port attribute ID: 17` is `SAI_PORT_ATTR_SUPPORTED_MEDIA_TYPE`, used to get supported media type. Broadcom SAI does not implement it, so should ignore related logs in loganalyzer.
`port attribute ID: 17` is `SAI_PORT_ATTR_SUPPORTED_MEDIA_TYPE`, used to get supported media type. Broadcom SAI does not implement it, so should ignore related logs in loganalyzer.
Update `loganalyzer_common_ignore.txt`.
Verified by running testcase `vlan/test_autostate_disabled.py` on Celestica-E1031 testbed.
=> Ignore unimplemented Broadcom SAI in loganalyzer

tests/saitests/py3/sai_qos_tests.py
@XuChen-MSFT : As requested, moving get_multiple_flows() calls to only cisco-8000.
Thanks,
rraghav
=> Move get_multiple_flows calls to cisco-8000 only.

tests/pfcwd/test_pfcwd_function.py
Porting 10198 to 202205:
The tests in test_pfcwd_function.py are failing since the reverse path is using the source port's MAC address instead of the dest port's mac address. This PR is to dynamically pass the correct mac address for the reverse path test.
=> Adding dynamic MAC reading in test_pfcwd_function.py

tests/pfcwd/test_pfcwd_function.py, tests/qos/test_qos_sai.py
Porting PR:10198 to 202305.
The tests in test_pfcwd_function.py are failing since the reverse path is using the source port's MAC address instead of the dest port's mac address. This PR is to dynamically pass the correct mac address for the reverse path test.
=> Porting 10198 to 202305. dynamic mac reading for pfcwd_function_test.

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Backport #11028 
port attribute ID: 17 is SAI_PORT_ATTR_SUPPORTED_MEDIA_TYPE, used to get supported media type. Broadcom SAI does not implement it, so should ignore related logs in loganalyzer.
Update loganalyzer_common_ignore.txt.
Verified by running testcase vlan/test_autostate_disabled.py on Celestica-E1031 testbed.
Summary:
=> [202305][E1031] Ignore implemented Broadcom SAI in loganalyzer (#11028)

.azure-pipelines/upgrade_image.py, ansible/devutil/devices/sonic.py, ansible/library/reduce_and_add_sonic_images.py
Summary:
Cherry-pick #10856 to 202205 branch.
The customized module reduce_and_add_sonic_images looks like a blackbox with too few messages for debugging when it failed. When upgrade image failed, we usually do not have enough information for debugging
This change enhanced module reduce_and_add_sonic_images to return more meaningful debug messages. This change also improved the upgrade_image.py script to have better log messages. The check of reachability before image upgrading is also enhanced.
Tested run on physical devices.
=> [202205] Improve debuggability of sonic image upgrading (#10856)

.azure-pipelines/upgrade_image.py, ansible/devutil/devices/sonic.py, ansible/library/reduce_and_add_sonic_images.py
Summary:
Cherry-pick #10856 to 202012 branch.
The customized module `reduce_and_add_sonic_images` looks like a blackbox with too few messages for debugging when it failed. When upgrade image failed, we usually do not have enough information for debugging
This change enhanced module `reduce_and_add_sonic_images` to return more meaningful debug messages.
This change also improved the `upgrade_image.py` script to have better log messages. The check of reachability before image upgrading is also enhanced.
Tested run on physical devices.
=> [202012] Improve debuggability of sonic image upgrading (#10856)

ansible/TestbedProcessing.py
This MUT is a manual cherry-pick of PR #9126 to 202205, which fixes merge conflicts against 202205.
Various bug fixes and improvements to the TestbedProcessing script, mostly for T2 chassis testing:
- Add SlotId column to sonic_lab_links.csv.
- Quote string variables in lab INI output, since in T2 these can be a list that will otherwise not be parsed correctly by ansible.
- Add SwitchIds for fabric ASICs.
- Add model, serial, and base_mac fields for linecards.
- Fix hostvar filename to correctly match the case of the hostname in the inventory.
This PR makes bug fixes and improvements to the TestbedProcessing script that are needed for T2 chassis testing.
These changes have been used internally at Arista for all sonic-mgmt testing
=> [PR:9126] TestbedProcessing script fixes and improvements

tests/platform_tests/conftest.py
Summary:
This is to skip testing SFP interfaces on Arista-7050QX-32S-S4Q31. They were skipped by RJ45 setting (https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/conftest.py#L70) by the hwsku.json (https://github.com/sonic-net/sonic-buildimage/pull/15251/files#diff-d66b493f5f334902184958f8afcbc387645e4033fe147bf1c0a1ac103d643d0bL5). But for some conflicts on port index setting of different breakout modes, hwsku.json would be deleted to use port_config.ini for the correct port index (https://github.com/sonic-net/sonic-buildimage/pull/17253). The change here is to skip SFP interfaces of Arista-7050QX-32S-S4Q31 in the test code.
=> [Arista] skip testing sfp interfaces on Arista-7050QX-32S-S4Q31

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
orchagent has two threads, one of the threads is receiving messages to remove members from VLAN and the other thread is receiving FDB events (LEARN, AGE etc.) from syncd/SAI.
There can be a race condition where FDB events were already in flight for a member which was getting removed from the VLAN. If orchagent processes the request to remove the member from VLAN first and then processes the FDB event, it will not find the port since bridge port ID is not valid any more. Because of this, we see an error message like ' ERR swss#orchagent: :- update: FdbOrch MOVE notification: Failed to get port by bridge port ID' in syslogs
This error is completely harmless and does not affect the functionality.
Adding a line 'r, ". *ERR swss#orchagent: :- update: FdbOrch MOVE notification: Failed to get …
=> Ignoring loganalyzer error 'Failed to get port by bridge port ID'

tests/qos/qos_sai_base.py
Using uplink ports for qossai testing for O8c48 hwsku PR for 202205. This has been already merged to master branch using PR 9924.
Summary:
Only uplink port is able to change speed between 400G and 100G for o8c48. Hence get uplink port info to run test_qos_sai script.
- [ x] 202205
Ran the TestQosSai::testQosSaiPfcXoffLimit[single_asic-xoff_1]
O8C48 churchill testbed
=> Raising PR for 202205 branch for using uplink ports for qossai testing for O8c48 hwsku

tests/platform_tests/link_flap/test_cont_link_flap.py, tests/platform_tests/link_flap/test_link_flap.py
Summary:
Redis memory used would increase an restore in M0/MX devices periodically (about 7% per 400+s), it would case they fail in this case sometimes.
Increase threshold for them.
Run tests.
=> [link_flap] Increase redis memory threshold for m0 and mx

tests/ecmp/test_ecmp_sai_value.py
Summary:
Fix incorrect topo mark format. Currently, this case is skipped on T1 testbed.
Add T1 into pytest.mark.topology
` pytest.mark.topology('t0', 't1'),`
Run `tests/ecmp/test_ecmp_sai_value.py` on T1 testbed
=> Modify incorrect pytest.mark.topology format

tests/platform_tests/link_flap/test_cont_link_flap.py, tests/platform_tests/link_flap/test_link_flap.py
Summary:
Manually cheery-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/11045
Redis memory used would increase an restore in M0/MX devices periodically (about 7% per 400+s), it would case they fail in this case sometimes.
Increase threshold for them.
Run tests.
=> [202205][link_flap] Increase redis memory threshold for m0 and mx (#11045)

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
To run test_fast_reboot_from_other_vendor will crash orchagent and leave DUT in a bad status to fail later cases. 
To skip this test case till the issue get fixed.
Add to skip list.
Manual test.
=> [conditional mark] skip test_fast_reboot_from_other_vendor

ansible/library/conn_graph_facts.py, ansible/roles/mcx/tasks/main.yml, ansible/roles/mcx/templates/incremental_mcx_config.j2, ansible/roles/mcx/templates/mcx_config.j2
Summary:
After modifications with conn_graph_facts, which changes from listing all connections from both ends of console connection to listing only its managing console server, mcx playbook fails to work because it cannot retrieve information on the devices that it manages. The playbook is adjusted to loop through all console links, and filter out the devices managed by the target mcx to create the config.
mcx playbook no longer works.
Loop through all console links and filter out the target console server.
Deployed mcx with the playbook.
=> [ansible] fix mcx ansible playbook

ansible/devutil/devices/ansible_hosts.py
Summary:
While running the upgrade_image.py script to upgrade image during nightly tests, there is high probability that this script failed with "Timeout (2s) waiting for privilege escalation prompt".
This issue is related with the upgrading of ansible to 6.7.0.
When ansible tries to connect to target device by SSH, the SSH connection plugin tries to get a timeout from PlayContext as ConnectTimeout argument value. According to the original intention, the default timeout of PlayContext is DEFAULT_TIMEOUT. It's value is taken from "timeout" in ansible.cfg file.
Actually, timeout of play_context gets its default value from base class of PlayContext. In base class of PlayContext, timeout defaults to TASK_TIMEOUT. The default value of TASK_TIMEOUT is 0.
Consequently, the SSH …
=> Fix timeout waiting for escalation prompt issue

tests/common/platform/device_utils.py, tests/sub_port_interfaces/sub_ports_helpers.py
Summary:
Some tests of 202012 branch raise NameError for "re" and "Dot1Q".
This PR is to fix these issues.
1. Add missing import of "re" module.
2. Reference "Dot1Q" and "Ether" with package scapy.all
=> [202012] Fix NameError for "re" and "Dot1Q"

tests/pc/test_po_update.py
Summary:
- For PC tests '_test_po_update.py_', seen the following LogAnalyzer mismatch related messages being reported as errors.
- Issues seen in PC tests running on chassis with topo t2 multi-asic.
`
E               Nov 11 20:41:16.136440 ixre-egl-board3 ERR syncd0#syncd: :- process_on_fdb_event: invalid OIDs in fdb notifications, NOT translating and NOT storing in ASIC DB
E               Nov 11 20:41:16.136471 ixre-egl-board3 ERR syncd0#syncd: :- process_on_fdb_event: FDB notification was not sent since it contain invalid OIDs, bug?
`
-  Loganalyzer mismatch errors seen during PC test suites for test_po_update.py tests w.r.t syncd container messages per asic as shown above.
-  Fix the existing regex to support syncd …
=> Loganalyzer regex correction for test_po_update

tests/process_monitoring/test_critical_process_monitoring.py
Summary:
test_monitoring_critical_processes sometimes fails due to
`Failed: Program 'lldp-syncd' in container 'lldp' is in the 'EXITED' state, expected 'RUNNING'`
check syslog at failed time, lldp-syncd tried to do source update, run  `/usr/sbin/lldpcli -f json show chassis` to get chassis name, but at this time, lldpd was killed, it wouldn't be able to run this command, that's why llpd-syncd is EXITED.
lldpd-syncd syncs data every 10s, that's why sometimes, it shows RUNNING right after killing lldpd, but if it hits the time of running lldpctl command, lldpd-syncd will throw exception and exit.
lldp-syncd is dependable for lldpd, so, it's unfair to kill lldpd then check the status of lldp-syncd.
test_monitoring_critical_processes checks if critical  process could be killed …
=> Fix flakiness of test_monitoring_critical_processes

tests/platform_tests/counterpoll/test_counterpoll_watermark.py
Summary:
Fixes missing import in test_counterpoll_watermark 
PR #10987 cannot be merged due to missing import time.
Add import time.
Run test_counterpoll_watermark with physical testbed.
=> Add missing import time in test_counterpoll_watermark

tests/platform_tests/test_power_budget_info.py
There is an extra space in the linecard name in `mod_name` which prevents the linecard name from matching that in the module skip list. This PR removes the extra whitespace from `mod_name` so the linecard name correctly matches.
Summary:
Fixes #10885
This PR fixes a bug which causes a spurious test failure in `test_power_budget_info.py`.
Remove the spurious whitespace that caused the linecard name to not match the value in the skip list.
Manually running `test_power_budget_info.py` on a device in our testbed with an extra linecard that should be skipped during the test.
=> platform_tests: Fix skip_modules check in test_power_budget_info.py

tests/syslog/test_syslog_rate_limit.py, tests/test_pretest.py
Depending on https://github.com/sonic-net/sonic-buildimage/pull/17458
Feature syslog rate limit has been disabled by default to avoid consume CPU cycles during warm / fast reboot. There are  new CLIs to enable/disable it. The PR is to automatically enable it before syslog rate limit test and disable it after.
**Summary:**
In fixture "restore_rate_limit", enable the feature at beginning, disable the feature at the end.
[ ] Bug fix
[ ] Testbed and Framework(new/improvement)
[x] Test case(new/improvement)
[ ] 201911
[ ] 202012
[ ] 202205
[x] 202305
**Approach**
In fixture "restore_rate_limit", enable the feature at beginning, disable the feature at the end.
Align test code with production …
=> [syslog] enable/disable syslog rate limit feature in fixture

tests/generic_config_updater/conftest.py, tests/generic_config_updater/test_incremental_qos.py, tests/generic_config_updater/test_mmu_dynamic_threshold_config_update.py
Move fixture skip_when_buffer_is_dynamic_model to conftest file 
Use this fixture in mmu dynamic threshold case
Use this fixture in incremental qos case
When buffer_model is dynamic type, test_incremental_qos.py and test_mmu_dynamic_threshold_config_update.py are not supported.
Summary:
Skip the test_mmu_dynamic_threshold_config_update.py when switch buffer_model is dynamic type.
Use a fixture to indicate whether buffer_model is dynamic type.
Test is in internel regression
No
=> Move fixture skip_when_buffer_is_dynamic_model to conftest file

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Skip test_custom_acl_table.py on dualtor setup
test_custom_acl_table.py is not supported to run at dualtor setup
Summary:
test_custom_acl_table.py is not supported to run at dualtor setup
Skip it
Verified it in interal regression
No
=> Add skip for test_custom_acl_table.py

tests/test_pktgen.py
Summary:
encounter pktgen failure in nightly:
symptom:
```
cpu_before = duthost.shell("show proc cpu --verbose | sed '1,/CPU/d' | awk '{print $9}'")["stdout_lines"]
for entry in cpu_before:
>           pytest_assert(
float(entry) > cpu_threshold,
"Cpu util was above threshold {} for atleast 1 process"
"before sending pktgen traffic".format(cpu_threshold))
E           Failed: Cpu util was above threshold 70 for atleast 1 processbefore sending pktgen traffic
cpu_before = ['37.5', '18.8', '6.2', '6.2', '0.0', '0.0', ...]
cpu_threshold = 70
```
RCA:
"float(entry) > cpu_threshold" is incorrect assert condition, should be "float(entry) < cpu_threshold,"
modify according above RCA
=> fix pktgen cpu utilization checking

tests/qos/files/qos_params.td3.yaml
Summary:
7050 dualtor 's pcbb xoff testcase fail, because of threshold is incorrect
qos_param_generator.py don't support test_tunnel_qos_remap.py yet.
so directly update threshold , like previous PR https://github.com/sonic-net/sonic-mgmt/pull/8624
=> update pcbb xoff test threshold for 7050 dualtor

tests/platform_tests/test_platform_info.py
Summary:
- [x ] 202305
In Dual-TOR testbed, the test test_turn_on_off_psu_and_check_psustatus()
1. Randomly selects a DUT 
2. Randomly selects the PDU controller for one of the DUT
The PDU controller selected at Step2 may not match with the DUT randomly selected at Step1.
This can result in the test case failing intermittently on multiple runs.
Explicitly select the PDU controller for the randomly selected DUT in dual-TOR testbed
Run sonic-mgmt test multiple time and ensure the test_turn_on_off_psu_and_check_psustatus passes on dual-TOR testbed
=> Select the right PDU controller in Dual-TOR testbed

ansible/group_vars/sonic/variables, tests/qos/qos_sai_base.py
Summary:
This PR is to update `ansible/group_vars/sonic/variables` and `tests/qos/qos_sai_base.py` to support new HWSKU `Mellanox-SN2700-A1`, `Mellanox-SN4700-O8V48` and new topology `t0-56-o8v48`.
This PR is to update `ansible/group_vars/sonic/variables` and `tests/qos/qos_sai_base.py` to support new HWSKU `Mellanox-SN2700-A1`, `Mellanox-SN4700-O8V48` and new topology `t0-56-o8v48`.
The change is verified by running `testParameters`.
No.
=> Support new HWSKU and topology for SN4700 and SN2700A1

tests/fdb/utils.py
In some sonic-mgmt test FDB runs, CRM CLI output returns NULL output causing script to fail.
Summary:
Add delay of 2 seconds and retry few times to get the valid CRM output.
- By adding a delay and retry when CRM output is empty.
- Verified in single and dual-tor setups.
=> Add delay when CRM output returns NULL

ansible/library/reduce_and_add_sonic_images.py
Summary:
Update images failed sometimes on low-memory devices.
Check memory and disk space before installing image.
If no enough space of memory or disk, abort.
Upgrade the images on low memory and small disk devices several times. no issue.
=> checking disk and memory space before installing image

.azure-pipelines/recover_testbed/common.py, .azure-pipelines/recover_testbed/dut_connection.py, .azure-pipelines/recover_testbed/recover_testbed.py, .azure-pipelines/recover_testbed/testbed_status.py
There are lots of unhealthy testbeds in our pool, which needed to be recovered. But some of them lost their management ip, and could not be connected via ssh. So we need another method to access these devices and recover them. In this PR, we connect to devices via console, and try to recover it via console. 
In this first period, the script can be used to recover unhealthy testbeds using onie and aboot. And other types of testbeds will be supported in next period. 
Summary:
There are lots of unhealthy testbeds in our pool, which needed to be recovered. But some of them lost their management ip, and could not be connected via ssh. So we need another method to access these devices and recover them. In this PR, we connect to devices via console, and try to recover it via …
=> Recover testbed via console. 

tests/common/reboot.py, tests/platform_tests/test_kdump.py
Summary:
Add test_kdump.py to platform_tests.
Add automation test for kdump functionality.
Induce kernel panic thru sysrq-trigger.
For platform with kdump enabled, trigger kernel panic, and check for reboot-cause on subsequent bootup.
Validated on Cisco-8000 platforms thru internal sonic-mgmt test.
N/A
Any platform with kdump enabled, else test will be skipped.
=> Add platform test for kdump

tests/platform_tests/test_power_off_reboot.py
https://github.com/sonic-net/sonic-mgmt/pull/8646 made a change in fixture 'pdu_controller' to always choose supervisor if device is chassis, for non-chassis it'll choose a random dut. PR 8646 will work in the same way for single-dut, but for dualtor, the randomly chosen dut could be different dut than the one under testing.
This PR call 'get_pdu_controller' to ensure pdu_controller is getting on the same dut.
There is no generic fix for this scenario that use "enum_supervisor_dut_hostname" for both tests and fixture `pdu_controller`, because platform_tests/conftest.py have a autouse fixture skip_on_simx that makes all platform tests use rand_one_dut_hostname.
Summary:
=> [dualtor] use 'get_pdu_controller' to ensure same dut in test_power_off_reboot

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/ecmp/test_ecmp_sai_value.py
Summary:
Skip test_ecmp_sai_value script for 7050 T1 platform.
The count of 0xa for ecmp offset on 7060 T1 platform is 33, not 67. 
Modify conditional mark accordingly.
Use hwsku to check which ecmp offset value is correct instead of asic type.
Run ecmp/test_ecmp_sai_value.py on 70609 T1 testbed and 7050cx1 T1 testbed.
=> Modify ecmp offset value for 7060 T1 hwsku

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Fixes
Remove xfail marks on warm-reboot cases since Broadcom has fix for it.
Enable warm-reboot cases.
Workitem: 26255229
Remove xfail conditional mark on:
- pfcwd/test_pfcwd_warm_reboot.py
- platform_tests/test_cont_warm_reboot.py
- arp/test_wr_arp.py
=> [Conditional mark] Remove xfail mark of warm reboot cases

tests/bgp/test_bgp_authentication.py
Summary:
- The 'test_bgp_authentication' tests fail with the following errors, when the test runs 'vtysh' command on t2 DUT.
>       assert bgp_facts['bgp_neighbors'][setup['neigh_ip_v4']]['state'] != 'established'
E       AssertionError
cmd        = 'vtysh -n None -c "config" -c "router bgp 65100" -c "neighbor PEER_V4 password badpassword" -c "neighbor PEER_V6 password badpassword"           -c "end"'
command_output = {'stderr_lines': [u'/usr/bin/vtysh: line 23: [: None: integer expression expec...: [], u'start': u'2023-12-09 09:40:16.664728', u'msg': u'non-zero return code'}
- This PR fixes issue the above issue for 'test_bgp_authentication' test case.
- Fix the following errors on '_test_bgp_authentication_' test cases on t2-chassis.
>       assert …
=> Modify DUT vtysh commands with right dut asic-index

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
There are some test cases being skipped or running on `x86_64-mlnx_msn2700-r0` platform. This PR is to update the `tests_mark_conditions.yaml` to apply the same operation to new platform `x86_64-mlnx_msn2700a1-r0`.
Skipped test cases:
- ecmp/inner_hashing/test_inner_hashing.py
- ecmp/inner_hashing/test_inner_hashing_lag.py
- ecmp/inner_hashing/test_wr_inner_hashing.py
- ecmp/inner_hashing/test_wr_inner_hashing_lag.py
- ecmp/inner_hashing/test_fgnhg_inner_hashing_internal.py
- ecmp/test_fgnhg.py
Test cases run on the new platform:
- vxlan/test_vxlan_ecmp.py
- vxlan/test_vxlan_crm.py
This PR is to update `tests_mark_conditions.yaml`  to apply the same operations to the new platform `x86_64-mlnx_msn2700a1-r0`.
Update [tests_mark_conditions.yaml](https://github.com/sonic-net/sonic-mgm …
=> Skip test cases on x86_64-mlnx_msn2700a1-r0 platform

tests/qos/qos_sai_base.py, tests/saitests/py3/sai_qos_tests.py
Cherry-pick from master PR #8936 
To make sure we have enough credit on the destination port, executing the populateArp test before executing the qos test will maintain enough credit and not let the PortChannel flap during test.
Below changes are made:
1.Adding new ArpTest for T2 broadcom-dnx Chassis to run before each test
2.Sending Arp packets to a static dest_ip is not relevant to T2. Hence skipping this for T2
4.Adding ping to all destination neighbor 's ip's of the testport's with network namespace
Summary:
=> [Cherry-pick] Adding populateArpEntries_T2 function to run for T2 Broadcom-dnx chassis in qos_sai_base #8936

tests/platform_tests/cli/test_show_platform.py
**Summary**
This PR adds the `test_platform_serial_no` test case that can help identifing the serial no. mismatching issue.
**Approach**
Use `decode-syseeprom -s` to compare with modeled inventory information.
We were hitting complains that prod devices had mismatch serial number, later, we have this [fix](https://github.com/sonic-net/sonic-buildimage/pull/17440), now we need align this gap by adding this test case.
Compare `decode-syseeprom -s` output with inventory data.
Ran the test in multiple platform lab devices, which shows passed.
**Any platform specific information?**
This is common test issue.
Signed-off-by: Xincun Li …
=> Add Serial Number check test case.

ansible/roles/vm_set/library/sonic_kickstart.py
Summary:
When a new SONiC VM comes up, but the IP address assigned to it was used by something else before, there may be traffic issues until the ARP entry for that IP address expires on the router/switch connected to the management port. In some cases, there may be routers/switches that do not properly send ARP requests for whatever reason, when that IP address expires.
To fix this issue, send a gratuitous ARP reply packet after the management IP address is configred in sonic_kickstart.py. This makes sure traffic is working, at least.
Tested by running add-topo for a KVM setup and making sure there were gratuitous ARP packets sent.
=> Send gratuitous ARP packet when bringing up SONiC VM

tests/dhcp_relay/test_dhcp_relay.py
Summary:
DHCPv4 Relay is not supported when dhcp_server is enabled, hence we need to skip related tests.
Skip dhcp_relay tests when dhcp_server is enabled.
Run tests.
```
collected 13 items                                                                                                                                                                                                                                                                      
dhcp_relay/test_dhcp_relay.py::test_interface_binding SKIPPED (DHCPv4 relay is not supported when dhcp_server is enabled)                                                                                                                                                         [  7%] …
```
=> [dhcp_relay] Skip DHCPv4 relay test when dhcp_server is enabled

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: xfail the syslog rate limit test and raise issue to track the progress
Fixes # (issue) Tracking issue https://github.com/sonic-net/sonic-mgmt/issues/11181
The syslog rate limit test will fail when randonly pick acms or syncd to test. After investigation, raise the issue to check with mellanox team.
xfail the test
E2E
=> [syslog] xfail syslog rate limit test and raise issue to track

ansible/library/reduce_and_add_sonic_images.py
Summary:
26322283
Below PR enhanced the upgrade sonic image, and would check memory and disk usage before installing the image.
But not calculate SWAP memory into the total available memory space.
https://github.com/sonic-net/sonic-mgmt/pull/11151
Add swap free memory into total available memory.
2024-01-04 07:13:09,640 DEBUG #47: *** cmd: free -m ***
2024-01-04 07:13:09,736 DEBUG #49: *** rc: 0, out:                total        used        free      shared  buff/cache   available
Mem:            1948        1359          86          27         502         419
Swap:           2047         586        1461
, err:  ***
2024-01-04 07:13:09,736 DEBUG #43: Available memory 1880, no need to free up memory space
=> add swap memory into return available memory in reduce_and_add_sonic_images

ansible/config_sonic_basedon_testbed.yml, ansible/library/topo_facts.py, ansible/templates/minigraph_meta.j2
Summary:
enable Compute-AI deployment for 8111 T1 device
run "deploy-mg" command on below device, check if ai deployment is enabled:
|Topo      |     HWSKU        |  result                 |
|----------|------------------|-------------------------|
|t1-64-lag | Cisco-8111-O64   |  pass, w/ ai deployment |
|t1-56-lag | Cisco-8101-O8C48 |  pass, w/o ai deploy    |
|t0-64     | Cisco-8111-O64   |  pass, w/o ai deploy    |
=> enable compute-ai for 8111-t1

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
- During multiple tests teardown, seen the following LogAnalyzer match for kdump related messages being reported as errors.
- Issues seen in tests running on chassis with topo t2_2lc_36-masic.
- And also observed similar errors seen during dut reboot and config reload as well.
The issue is reported as #10384 
Example error message,
`Oct 15 08:06:10.491683 ixre-egl-board28 INFO kdump-tools[873]: no crashkernel= parameter in the kernel cmdline ...`
- During multiple tests teardown, seen the following LogAnalyzer match for kdump related messages being reported as errors.
- Issues seen in tests running on chassis with topo t2_2lc_36-masic.
- Since these messages are not errors but pointing to missing info when loading kdump config on DUT which is not supporting kdump. …
=> Ignore kdump-tools log message from loganalyzer

tests/system_health/mellanox/mellanox_device_mocker.py
For Nvidia/Mellanox switch, when the hardware management version is lower or larger than 7.0030.2003, the thermal psu related system files are different.
This script code change is adapt it.
Summary:
Adapt different psu thermal system file for Nvidia/Mellanox switch.
Choose psu thermal system file according to hardware management version.
Validate it in internal regression.
No
=> [Nvidia] Choose psu temp threshold file according to hw management version

tests/pc/test_po_update.py
**Cherry-Pick** PR for 202205 from master https://github.com/sonic-net/sonic-mgmt/pull/10860
Summary:
- For PC tests 'test_po_update.py', seen the following LogAnalyzer mismatch related messages being reported as errors.
- Issues seen in PC tests running on chassis with topo t2 multi-asic.
`E               Match Messages: E               Nov 11 20:41:16.136440 ixre-egl-board3 ERR syncd0#syncd: :- process_on_fdb_event: invalid OIDs in fdb notifications, NOT translating and NOT storing in ASIC DB E                E               Nov 11 20:41:16.136471 ixre-egl-board3 ERR syncd0#syncd: :- process_on_fdb_event: FDB notification was not sent since it contain invalid OIDs, bug?`
- Loganalyzer mismatch errors seen during PC test suites for test_po_update.py tests w.r.t syncd …
=> [cherry-pick] [PR:10860] Loganalyzer regex correction for test_po_update

ansible/devutils
Summary:
After the changes in https://github.com/sonic-net/sonic-mgmt/pull/10087, some PDUs(such as APC controller rPDU) don't have MIB OID for power. There will be TypeError if get output_watts directly.
before fix:
```
zhaohuisun@sonic-mgmt-zhaohuisun2:/data/sonic-mgmt-int/ansible$ ./devutils -l str3-msn4600c-acs-05 -i str3 -a pdu_status -j
File "./devutils", line 509, in <module>
main()
File "./devutils", line 505, in main
action_dispatcher(parameters)
File "./devutils", line 388, in action_dispatcher
parameters['action'](parameters)
File "./devutils", line 345, in action_pdu_status
show_data_output(header, data, parameters['json'], parameters['out'])
File "./devutils", line 192, in show_data_output
output_content = …
```
=> [devutils]Fix output error for pdu_status in devutils

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Fixes error skip condition introduced by #10599 
7260CX3 with test_decap should be skipped now
Add skip condition
=> Fix wrong skip condition in test_decap on 7260CX3

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
To skip test_bgp_suppress_fib for 202305 and 202311, this feature is not supported in 202305 and 202311 branch.
Add skip case to tests_mark_conditions.yaml
N/A
=> [skip test] skip test_bgp_suppress_fib before 202405

tests/system_health/test_watchdog.py
Improve orchagent watchdog UT to handle orchagent not pause case.
Summary:
Improve orchagent watchdog UT to handle orchagent not pause case.
system_health/test_watchdog.py::test_orchagent_watchdog randomly failed on some device because orchagent does not paused by UT.
Still not found reason, add debug information also improve code.
Improve get orchagent PID code, only get orchagent running by root user.
Add debug log when orchageent pause failed.
Pass all UT
=> Improve orchagent watchdog UT to handle orchagent not pause case.

tests/tacacs/test_accounting.py, tests/tacacs/utils.py
[TACACS] Improve TACACS UT test_accounting_tacacs_only_some_tacacs_server_down
Summary:
Fixes test_accounting_tacacs_only_some_tacacs_server_down randomly failed issue.
test_accounting_tacacs_only_some_tacacs_server_down randomly failed because TACACS config reload syslog not found.
Which is because multiple TACACS config command in short time will only trigger one TACAACS config reload, and UT code does not handle this case.
Improve UT code to handle multiple TACACS config command case.
Pass all UT
=> [TACACS] Improve TACACS UT test_accounting_tacacs_only_some_tacacs_server_down

ansible/group_vars/sonic/variables, tests/qos/qos_sai_base.py
Summary:
This PR is to update `ansible/group_vars/sonic/variables` and `tests/qos/qos_sai_base.py` to support new HWSKU `Mellanox-SN2700-A1`, `Mellanox-SN4700-O8V48` and new topology `t0-56-o8v48`.
This PR is to cherry-pick #11146 into `202305` branch.
This PR is to update `ansible/group_vars/sonic/variables` and `tests/qos/qos_sai_base.py` to support new HWSKU `Mellanox-SN2700-A1`, `Mellanox-SN4700-O8V48` and new topology `t0-56-o8v48`.
The change is verified by running `testParameters`.
No.
=> [202305][cherry-pick] Support new HWSKU and topology for SN4700 and SN2700A1

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Skipping arp/test_unknown_mac.py for Innovium(Marvell) platform
Summary:
Behavior on Innovium(Marvell) platform for unknown MAC is flooding rather than DROP, hence skipping.
- [*] 202205
- [*] 202305
Skipping unsupported test case on Innovium(Marvell) platform
=> Skipping arp/test_unknown_mac.py for Innovium(Marvell) platform

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Skip test_memory_exhaustion on 6100 platforms.
ADO:17449251
add skip section for 6100
run test_memory_exhaustion on 6100 testbeds
=> Skip test_memory_exhaustion on 6100 platform

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/generic_config_updater/test_eth_interface.py
Summary:
ADO 26158280
KVM StateDB has no restrictions on port speed. This PR updates GCU test_eth_interface.py::test_update_speed to reflect this.
=> [GCU E2E Testing] Fix test_eth_interface.py::test_update_speed KVM speed selection

tests/copp/test_copp.py
We've noticed that copp test_trap_config_save_after_reboot fails occasionally due to not enough time waiting for the trap to be installed after reboot.
Summary:
Address occasional test fail seen in our sonic-mgmt runs.
Applied the timeout increase in our internal sonic-mgmt testing and observed the test passed reliably.
=> Increase timeout for copp test_trap_config_save_after_reboot

tests/telemetry/test_events.py
Summary:
Fixes # (issue)26281324
In baseline test we are seeing that in some runs, config may be missing such that gnmi server is running on default port 8080. Adding setup fixture to the testcase such that gnmi environment and config is setup for the test
Added setup fixture to test_cache
Pipeline/manual testing
=> Add setup_streaming_telemetry fixture to cache tests

tests/ecmp/test_ecmp_sai_value.py
Summary:
Fix the incorrect count of ports for 7050qx, it's 362, not 392.
=> [ecmp offset] Fix the incorrect count of ports for 7050qx

tests/bgp/test_bgp_bbr.py
Summary:
Config bbr status by using GCU cmd since we enable YANG model for bbr in https://github.com/sonic-net/sonic-buildimage/pull/17622.
Config bbr status by GCU cmd.
Config bbr status use cmd ```config apply-patch <json-patch>``` instead of ```sonic-cfggen```
Run bgp/test_bgp_bbr.py case on dut manually and passed.
=> Config bgp bbr by GCU cmd in test_bgp_bbr test

tests/acl/test_stress_acl.py
The goal of test_stress_acl.py is to add/delete acl entries frequently. Refer: https://github.com/sonic-net/sonic-mgmt/pull/6903
test_stress_acl.py is adding new acl table and it will fail if the TCAM space is not available. As done in other acl tests, removing DATAACL to free TCAM resources to run test_stress_acl.py.
Summary:
- [*] 202305
=> Remove DATAACL to free TCAM resources for test_stress_acl.py

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
…et, set xfail flag
Summary:
Most test_pfc_watermark_extra_lossless cases had failed on broadcom platform, since Cisco introduced it in https://github.com/sonic-net/sonic-mgmt/pull/9318 at Sep/15 in an attempt to replace test_pfc_pause_extra_lossless_standby and test_pfc_pause_extra_lossless_active.
need to tuning and enhance case for broadcom platform.
xfail first till most cases can pass
=> xfail test_pfc_watermark_extra_lossless for brcm platform

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
… case yet
Summary:
Most test_pfc_watermark_extra_lossless cases had failed on broadcom platform, since Cisco introduced it in https://github.com/sonic-net/sonic-mgmt/pull/9318 at Sep/15 in an attempt to replace test_pfc_pause_extra_lossless_standby and test_pfc_pause_extra_lossless_active.
need to tuning and enhance case for broadcom platform.
xfail first till most cases can pass
=> [202205] xfail test_pfc_watermark_extra_lossless for brcm platform

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
… case yet
Summary:
- [] 202205
Most test_pfc_watermark_extra_lossless cases had failed on broadcom platform, since Cisco introduced it in https://github.com/sonic-net/sonic-mgmt/pull/9318 at Sep/15 in an attempt to replace test_pfc_pause_extra_lossless_standby and test_pfc_pause_extra_lossless_active.
need to tuning and enhance case for broadcom platform.
xfail first till most cases can pass
=> [202305] xfail test_pfc_watermark_extra_lossless for brcm platform

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
MSFT requested to skip below testcases for 8111 platform
dhcp_relay/test_dhcp_relay.py
dhcp_relay/test_dhcpv6_relay.py
generic_config_updater/test_dhcp_relay.py
This PR makes the changes required for skipping above testcases for 8111 platform
The testcases are skipped by adding skip condition in below mentioned file tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Ran the required testcases are making changes to tests_mark_conditions.yaml file. Made sure that the testcases got skipped.
Test case(new/improvement)
202305
=> skipping dhcp_relay testcases for 8111 platform

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Remove xfail mark on test_advanced_reboot case since Broadcom has fix for it.
Enable test_advanced_reboot case.
Remove xfail conditional mark on test_advanced_reboot.py.
=> [Conditional mark] Remove xfail mark for test_advanced_reboot

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Fix conditional mark for unsupported testcases on M0/Mx.
Fix conditional mark for unsupported testcases on M0/Mx
Specify `conditions_logical_operator: "OR"` in conditional mark.
Verified by running testcase `generic_config_updater/test_pfcwd_status.py` on M0 testbed:
```
generic_config_updater/test_pfcwd_status.py::test_stop_pfcwd[single] SKIPPED (This test is not run on this topo type or version currently)                              [ 25%]
generic_config_updater/test_pfcwd_status.py::test_stop_pfcwd[all] SKIPPED (This test is not run on this topo type or version currently)                                 [ 50%]
generic_config_updater/test_pfcwd_status.py::test_start_pfcwd[single] SKIPPED (This test is not run on this topo type or version currently) …
```
=> Fix conditional mark for unsupported testcases on M0/Mx

tests/common/devices/sonic.py, tests/common/dualtor/tunnel_traffic_utils.py
Summary:
Fixes # (https://github.com/sonic-net/sonic-mgmt/issues/9624)
On Nvidia platforms, when the inner/outer DSCPs are 2/2 or 6/6, the tunnel packet is not mapped based on the mapping configuration to queue 1 (they will be mapped to queue 2 and 6).
And we have confirmed with MSFT that such packets are not expected in production.
So, skip the queue check for them.
Fix test issue (https://github.com/sonic-net/sonic-mgmt/issues/9624)
Skip the queue check in tunnel monitor on Nvidia platforms when dscp is 2/2 or 6/6
Run test on 4600C dualtor setup, passed.
Only for Nvidia platforms.
=> [Mellanox][Dual-Tor][DSCP remapping]Fix a test issue for the dualtor tunnel monitor for Nvidia platforms

tests/qos/test_tunnel_qos_remap.py
Summary:
For Nvidia platforms, the inner dscp 2 and 6 are considered invalid use cases, skip the test. 
The dscp 2 and 6 are reserved only for the outer dscp after the remapping and encapsulation.
We have another similar issue fixed by PR #9625.
Fix the test failure of test_tunnel_decap_dscp_to_queue_mapping on Nvidia platforms.
Skip the test for dscp 2 and 6
Run the test case on 4600c dualtor testbed, passed
=> [Nvidia] [DualTor] Skip dscp 2 and 6 in test case test_tunnel_decap_dscp_to_queue_mapping

tests/common/dualtor/dual_tor_utils.py, tests/dualtor/test_orchagent_active_tor_downstream.py
What I did:
changed test_downstream_ecmp_nexthops to check if packets being sent are funneled towards a single mux neighbor or portchannel
Why I did it:
test_downstream_ecmp_nexthops fails due to swss change which programs a single active mux nexthop or a single tunnel route for a given route
How to test:
run sonic-mgmt dualtor/test_orchagent_active_tor_downstream.py test on t0 topo.
Summary:
=> [202205][dualtor] fixing test_downstream_ecmp_nexthops

tests/qos/files/qos_params.gb.yaml
Both  WRR and WRR_Change send packets in bulk(500 packets as of now), and expect all packets back in bulk. When the PTF is not able to handle all packets the tests fail. We have seen this before, and had reduced the packets from 1000 to 500. But in recent MS runs, we observe that the PTF is not handling even the 500 packets. This PR addresses this by reducing the total number of packets to 300.
Summary:
Fixes the test fail issue due to PTF in @XuChen-MSFT 's  runs. 
This PR reduces the total number of packets used by WRR and WRR_change tests. This is to allow the PTF to handle all the packets.
Updated the qos.yaml parameters.
Ran the test:
=============================================================================================== PASSES …
=> Reducing the number of packets for WRR and WRR_Change from 500 to 300.

tests/dualtor/test_tor_ecn.py
Summary:
Fix import error introduced in #10104.
`NameError: name 'is_tunnel_qos_remap_enabled' is not defined`
NameError: name 'is_tunnel_qos_remap_enabled' is not defined`
add removed import for is_tunnel_qos_remap_enabled
run `dualtor/test_tor_ecn.py`
=> Fix "NameError: name 'is_tunnel_qos_remap_enabled' is not defined" in test_tor_ecn

ansible/library/dut_basic_facts.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Currently, release is unknown for internal image, if we use release in condition mark file to check internal, it doesn't work.
Change to use build_version instead.
Also skip it on 202311 image which doesn't have this fix.
Currently, release is unknown for internal image, if we use release in condition mark file to check internal, it doesn't work.
Change to use build_version instead.
Also skip it on 202311 image which doesn't have this fix.
Change to use build_version instead.
Add 202311 in skipped list
run ecmp/test_ecmp_sai_value.py
=> Skip test_ecmp_sai_value on internal and 202311 image

.azure-pipelines/recover_testbed/interfaces.j2, .azure-pipelines/recover_testbed/recover_testbed.py, .azure-pipelines/recover_testbed/testbed_status.py
In PR #10806 , we support auto recovery of testbeds via console. After power cycle, we will add ip and route information on device. And in this PR, we will add these information into file `/etc/network/interface` to avoid losing management ip again after reboot. 
Summary:
In PR #10806 , we support auto recovery of testbeds via console. After power cycle, we will add ip and route information on device. And in this PR, we will add these information into file `/etc/network/interface` to avoid losing management ip again after reboot. 
Give the template of `/etc/network/interface` and after power cycle, fill in this template and set it on device. 
When the scripts finish running, reboot the device, and it will not lose management ip.
=> Add ip information into `/etc/network/interface` after testbed is recovered via console. 

tests/voq/test_voq_chassis_app_db_consistency.py
All 3 testcases in `test_voq_chassis_app_db_consistency.py` were failing due to not waiting long enough after config reload or reboot on T2 topologies.
This PR increases the timeout amount to 600s, which seemed sufficient for all 3 test cases on multiple T2 setups.
E.G.
`config_reload_with_config_save & config_reload_no_config_save`
```
11/01/2024 01:45:37 utilities.wait_until                     L0143 DEBUG  | check_db_consistency is False, wait 30 seconds and check again
11/01/2024 01:46:07 utilities.wait_until                     L0125 DEBUG  | Time elapsed: 262.709992 seconds
11/01/2024 01:46:10 utilities.wait_until                     L0143 DEBUG  | check_db_consistency is False, wait 30 seconds and check again
11/01/2024 01:46:40 utilities.wait_until                     L0125 DEBUG …
```
=> test_voq_chassis_app_db_consistency.py: Increase timeout of config reload and reboot

tests/route/test_default_route.py
Add IPV6 default route test.
Add IPV6 default route test.
- Microsoft ADO: 25798732
Add IPV6 default route test.
Add IPV6 default route test.
Pass all UT
=> Add IPV6 default route test

tests/pc/test_lag_member.py
Summary:
test_lag_member_traffic would sometimes fail due to PTF response wrong ARP packet. This PR is to fix this issue.
Use arp_responder in ptf to reply arp request.
Run tests.
=> [portchannel] Fix arp issue in test_lag_member_traffic

.github/PULL_REQUEST_TEMPLATE.md
Summary:
Update PR template.
Add 202311 backport option in template.
=> [github] Add 202311 back port option list to PR template

tests/pc/test_lag_member.py
Summary:
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/11316
test_lag_member_traffic would sometimes fail due to PTF response wrong ARP packet. This PR is to fix this issue.
Use arp_responder in ptf to reply arp request.
Run tests.
=> [202205][portchannel] Fix arp issue in test_lag_member_traffic (#11316)

tests/platform_tests/reboot_timing_constants.py, tests/platform_tests/templates/expect_boot_messages
Summary:
Update regex for detecting a MAC jump for Broadcom platforms, so that the warm reboot mac jump test case will match the correct log messages.
Tested by running the test_warm_reboot_mac_jump test case on a Broadcom platform and verify that it passes.
Applies only to Broadcom platforms
=> Update regex for detecting a MAC jump for Broadcom platforms

ansible/roles/test/files/ptftests/advanced-reboot.py, ansible/roles/test/files/ptftests/sonic.py
Summary:
This is a backport of #10107. This fixes the LAG downtime calculation of warmboot with SONiC neighbors so that there are no false positives seen when looking for LAG flaps. This also makes the code that reads output from the VMs a bit more robust, and adds a bit of error handling.
Tested by doing a warm reboot on KVM with 202305 image.
=> [202305] Fix LAG downtime calculation with SONiC neighbors

.azure-pipelines/recover_testbed/common.py, .azure-pipelines/recover_testbed/constants.py, .azure-pipelines/recover_testbed/recover_testbed.py
In PR #10806, we support auto recovery of testbeds via console. But at that time, we didn't support nokia testbeds. 
In Nokia testbeds, they first enter into `u-boot`, and we can enter into `ONIE` through `u-boot`. So in this PR, we enhance the function which will do recover in ONIE to cover this sistuation. 
Summary:
In PR #10806, we support auto recovery of testbeds via console. But at that time, we didn't support nokia testbeds. 
In Nokia testbeds, they first enter into `u-boot`, and we can enter into `ONIE` through `u-boot`. So in this PR, we enhance the function which will do recover in ONIE to cover this sistuation. 
Enhance the function which will do recover in ONIE to cover Nokia testbeds. If the type of testbeds is Nokia, enter into ONIE through u-boot, and then, …
=> Support recovering Nokia devices via console

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/tacacs/test_authorization.py
Fix TACACS authorization issue: user can run rejected command when enable local authorization as fallback.
Fix TACACS authorization issue: user can run rejected command when enable local authorization as fallback.
- Microsoft ADO: 26399545
per-command authorization found a code bug: When set per-command authorization to "tacacs+, local", user command blocked by server side but has local permission should failed. but currently it can success.
The UT code changed by this PR is testing and protect this incorrect behavior.
Create issue: https://github.com/sonic-net/sonic-mgmt/issues/11349
Fix UT and ignore it temporarily by this issue.
Pass all UT
=> [TACACS] Fix TACACS authorization issue: user can run rejected command when enable local authorization as fallback.

tests/qos/test_tunnel_qos_remap.py
Summary:
encounter test_encap_dscp_rewrite failure related to ptf
increase timeout of verify_packet_any_port in test_encap_dscp_rewrite.
since cannot manually reproduce this failure,
manually trigger nightly using test branch to verify changes, pass the nightly test
=> increase timeout for test_encap_dscp_rewrite

ansible/library/announce_routes.py, tests/route/test_route_consistency.py
Summary:
Fixes # Intermittent test_route_withdraw_advertise() failure on T2 topology
Fixes # Intermittent test_route_withdraw_advertise() failure on T2 topology
Based on debugging, it was found that for some of the exabgp processes, routes adv/withdrawal post message takes longer than 90 seconds(due to high route scale in t2 topology)
Fix:
1. Increase the timeout value to allow more time for requests.post.
2. Provide additional sleep after withdraw/advertise for all peers to effectively advertise/withdraw and DUT has enough time to process them and install them in ASIC Db
3. Due to try, except block of the testcase, if the exception is hit (due to assertion or otherwise), the testcase was not marked as failed. Fix is to re raise the exception
1. rerun the testcase locally.
2. Rerun the …
=> Fix T2 advertise_withdraw test failure

tests/common/helpers/gnmi_utils.py, tests/gnmi/helper.py
Summary:
Microsoft ADO: 26460000
GNMI test failed on two testbeds.
I found TCP port is used by supervisor-proc-exit-listener on one testbed.
And there's no information for other testbed.
Stop all program in gnmi container, and add more debug for gnmi connection issue.
=> Improve gnmi test for connection issue

tests/copp/test_copp.py
Summary:
timing issue caused test_copp test failure on cisco platform in nightly
increase timeout value for copp test
pass local test and nightly test
=> Extend timeout after reboot in copp

.azure-pipelines/recover_testbed/common.py
Termios is a python lib to set something about terminal which should be used in terminal. While doing recovering, Elastictest will not directly using a terminal, which will generate an Exception `(25, 'Inappropriate ioctl for device')`. Here, we don't need to set terminal, so in this PR, I remove the related code to avoid exception. 
Summary:
Termios is a python lib to set something about terminal which should be used in terminal. While doing recovering, Elastictest will not directly using a terminal, which will generate an Exception `(25, 'Inappropriate ioctl for device')`. Here, we don't need to set terminal, so in this PR, I remove the related code to avoid exception. 
Remove related code to set terminal. 
Use Elastictest to run a testplan, and the Exception will not …
=> Remove termios settings while recovering testbeds. 

tests/passw_hardening/passw_hardening_utils.py, tests/show_techsupport/test_techsupport.py
Summary:
test_techsupport_commands failed due to the following TypeError.
```
File "/var/src/sonic-mgmt_vms64-t1-7260-14_65040f002185a20e72689ccf/tests/show_techsupport/test_techsupport.py", line 532, in test_techsupport_commands
pytest_assert(len(cmd_not_found) == 0, cmd_not_found)
File "/var/src/sonic-mgmt_vms64-t1-7260-14_65040f002185a20e72689ccf/tests/common/helpers/assertions.py", line 7, in pytest_assert
pytest.fail(message)
File "/usr/local/lib/python3.8/dist-packages/_pytest/outcomes.py", line 198, in fail
raise Failed(msg=reason, pytrace=pytrace)
File "/usr/local/lib/python3.8/dist-packages/_pytest/outcomes.py", line 38, in __init__
raise TypeError(error_msg.format(type(self).__name__, type(msg).__name__))
TypeError: Failed expected string as 'msg' parameter, got …
```
=> Fix TypeError in pytest_assert in test_techsupport and passw_hardening

tests/route/test_route_flap.py
Update the logic to get dev_port.
old logic will always break for 1st iteration, which will result in dev_port to be empty, at the end of function, if the first route we find is an internal route. 
new logic in this PR will break only if dev_port is non-empty or the for loop ended.
Summary:
before:
```
>       pytest_assert(dev_port, "dev_port not exist")
E       Failed: dev_port not exist
asic       = <SonicAsic 1>
asichost   = <SonicAsic 0>
cmd        = ' -c "show ip route 192.170.49.0/25 json"'
dev        = {'192.170.49.0/25': [{'destSelected': True, 'distance': 20, 'installed': True, 'installedNexthopGroupId': 69657, ...}]}
dev_port   = None
dst_prefix = routes(route=u'192.170.49.0/25', aspath=u'65503')
dst_prefix_set = set([routes(route=u'192.168.0.0/25', …
```
=> [route flap] Update logic to get dev_port

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/voq/test_fabric_cli_and_db.py
Summary: Add mgmt test for testing fabric link isolation cli commands.
This change adds a test for the fabric link isolation command.
The test iterates over the fabric links on a linecard. It isolates and unisolates fabric links. Each time the state of the link is changed the state is checked in both CONFIG_DB and APPL_DB. The values in CONFIG_DB are updated by the fabric CLI commands and the values in APPL_DB are updated by the fabric manager  daemon.  The test check if the 2 major part work as expected. 
need to wait https://github.com/sonic-net/sonic-buildimage/pull/17473
=> Add mgmt test for testing fabric link isolation cli commands.

tests/saitests/py3/sai_qos_tests.py
Summary:
encounter testQosSaiLossyQueue  failure for 6100
it caused by leakout, so compensate leakout using existing funciotn
t1:
```
qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueue[single_asic] PASSED [ 33%]
... omitted ...
SKIPPED [1] qos/qos_sai_base.py:604: Did not find any frontend node that is multi-asic - so can't run single_dut_multi_asic tests
SKIPPED [1] qos/qos_sai_base.py:611: multi-dut is not supported on T1 topologies
============= 1 passed, 2 skipped, 1 warning in 974.02s (0:16:14) ==============
```
t0:
```
qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueue[single_asic] PASSED [ 33%]
... omitted ... …
```
=> fix 6100 testQosSaiLossyQueue failure caused by leakout

tests/qos/qos_sai_base.py, tests/saitests/py3/sai_qos_tests.py
Summary: Adding multi_asic check for arp_populate qos test for T2 topology.
The arp_populate fails for the t2 topology with single_asic devices.
This is improvement on PR #8936 & PR #10408 
Fixes # (issue) This is to resolve the issue - https://github.com/sonic-net/sonic-mgmt/issues/11236
The arp_populate  fails for the t2 topology with single_asic devices.
Since namespace is not supported in single_asic  cards, adding multi_asic check along with topo type as t2 to run arp test.
This is to resolve the issue - https://github.com/sonic-net/sonic-mgmt/issues/11236
Execute qos tests for t2 & verify the results.
=> Mutli_asic check for T2_arppopulate qos_test

tests/tacacs/test_authorization.py
Add UT to simulate device config failed because load minigraph restart BGP service and cause network not reachable.
Add UT to simulate device config failed because load minigraph restart BGP service and cause network not reachable.
- Microsoft ADO: 26371616
Device will lose BGP session after load minigraph, on management device this will cause per-command authorization failed.
To fix this issue, per-command authorization need set to "tacacs+,local" on management  device.
Add new PR to simulate this scenario and protect code.
Add UT to simulate device config failed because load minigraph restart BGP service and cause network not reachable.
Pass all UT
=> [TACACS] Add UT to simulate device config failed because load minigraph restart BGP service and cause network not reachable.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Disable iface_loopback_action tests on Broadcom switches.
=> Disable iface_loopback_action tests on Broadcom switches

tests/vlan/test_autostate_disabled.py
Add ignore loganalyzer error to autostate-disabled test
Summary:
Ignore potential error that is expected to pass test_autostate_disabled.
Add ignore loganalyzer error
Run test manually
=> [vlan] add ignore loganalyzer error to autostate-disabled test

.azure-pipelines/recover_testbed/dut_connection.py
If ManagementIP in inventory file contains "/", it will fail when connecting to console session while recovering testbeds. 
Reference: #11281 
Summary:
If ManagementIP in inventory file contains "/", it will fail when connecting to console session while recovering testbeds. 
Add support for "/" in ManagementIP.
=> [Recover testbed] Fix format issue in common function duthost_console

ansible/library/reduce_and_add_sonic_images.py
Summary:
Fix no "utcnow" attribute issue of reduce_and_add_sonic_images
Recent PR #10856 improved debugability of the customzied ansible module reduce_and_add_sonic_images.
However, this module ran into issue below issue on 202205 branch:
AttributeError(\"module 'datetime' has no attribute 'utcnow'\")
The reason is related with the notorious datetime.datetime issue. Packate datetime has module with same name datetime. If some module imported the datetime package using:
import datetime
Then below statement for importing the datetime module may be skipped because in imported cache, there is already "datetime".
from datetime import datetime
Consequently, `datetime.utcnow()` may fail with AttributeError.
To avoid the mess of such issue, this PR updated the module to use the …
=> Fix no "utcnow" attribute issue of reduce_and_add_sonic_images

ansible/library/reduce_and_add_sonic_images.py
Summary:
The "sonic_installer list" command may fail and output nothing. Consequently variable "curr_image" may be referenced before assignment.
This change enhanced the robustness of code to ignore failure of command "sonic_installer list". Then the code can try to run "sonic_installer install" anyway without reduce installed image.
This fix is still not good enough. The reason is that if "sonic_installer list" fail, most likely "sonic_installer install" would fail too. What's more, if old image is not reduced, try to install new image would also fail on devices with small flash disk.
Run on physical testbed
=> Ignore "sonic_installer list" failure during image upgrade

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
There is a new dualtor topo dualtor-64, need to skip test_cacl_application_nondualtor for this topo as well.
Add dualtor-64 into conditions in tests_mark_conditions.yaml file
Run test_cacl_application_nondualtor case on dualtor-64 testbed.
=> Skip test_cacl_application_nondualtor for dualtor-64

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/qos/test_qos_sai.py
1. Skip testIPIPQosSaiDscpToPgMapping, Because for DSCP to PG mapping on IPinIP traffic , mellanox device has different behavior to community. For mellanox device, testQosSaiDscpToPgMapping can cover the scenarios, because for common traffic and IPinIP traffic, mellanox device has the same behavior.
2. Enable TestQosSaiDscpToPgMapping on mellanox device
Summary:
Enable TestQosSaiDscpToPgMapping on Mellanox device
Skip testIPIPQosSaiDscpToPgMapping on  Mellanox device
Change TestQosSaiDscpToPgMapping to enable it on Mellanox device.
Skip testIPIPQosSaiDscpToPgMapping for Mellanox device
Run the two tests on Mellanox device
Mellanox
t0, t1, ptf32
=> [Mellanox] Enable TestQosSaiDscpToPgMapping  and skip testIPIPQosSaiDscpToPgMapping

tests/iface_loopback_action/iface_loopback_action_helper.py, tests/iface_loopback_action/test_iface_loopback_action.py
Summary:
The rif counters are checked in the test  test_loopback_action_reload after reload/reboot.
But the counters will not be available right after the reload/reboot, need to wait for the initialization.
1. Add a wait_until for the rif counters.
2. Combine the codes of checking interface status after reload/reboot into one.
Run the test in regression, all passed.
=> Fix loopback action reload test

ansible/library/reduce_and_add_sonic_images.py, tests/upgrade_path/test_upgrade_path.py
Summary:
Ignore the package migration error in upgrade path test when downgrading to the from image.
When downgrading from a newer version to an older one via sonic-installer, there could be package migration error because the older version doesn't contain some new packages.
We need to ignore this kind of errors in the upgrade path test.
```
tests.common.devices.base:base.py:104 /root/mars/workspace/sonic-mgmt/tests/upgrade_path/upgrade_helpers.py::install_sonic#89: [r-tigon-04] AnsibleModule::reduce_and_add_sonic_images Result => {"failed": true, "msg": "Image installation failed: rc=1, out=efi not supported - exiting without verification
Installing image SONiC-OS-202205_3_rc.13-a8586b250_Internal and setting it as default...
Command: bash /host/downloaded-sonic-image
Verifying image …
```
=> Ignore the migration error in upgrade path test when downgrading to the from_image

ansible/roles/test/files/ptftests/py3/hash_test.py
Update hash_test.py to fix issue #10961. Now both hash tests are passing
SKIPPED [2] common/helpers/assertions.py:14: The test case runs on T1 topology
PASSED fib/test_fib.py::test_basic_fib[True-True-1514]
PASSED fib/test_fib.py::test_hash[ipv4]
PASSED fib/test_fib.py::test_hash[ipv6]
PASSED fib/test_fib.py::test_ipinip_hash_negative[ipv4]
PASSED fib/test_fib.py::test_ipinip_hash_negative[ipv6]
============= 5 passed, 2 skipped, 1 warning in 7461.40s (2:04:21) =============
Summary:
Update hash_test.py to fix issue #10961. Now both hash tests are passing
Validated on T2 profile
=> Update hash_test.py to fix issue #10961

tests/common/fixtures/fib_utils.py
Update fib_utils.py to fix issue due to TypeError: 'dict_keys' object is not subscriptable. The code was working fine on 202205 branch but was failing on 202305 branch as
decap/test_decap.py::test_decap[ttl=pipe, dscp=uniform, vxlan=disable]
-------------------------------- live log setup --------------------------------
08:39:25 __init__._fixture_func_decorator         L0073 ERROR  |
TypeError("'dict_keys' object is not subscriptable")
File "/data/tests/common/plugins/log_section_start/__init__.py", line 71, in _fixture_func_decorator
return fixture_func(*args, **kargs)
File "/data/tests/common/fixtures/fib_utils.py", line 304, in fib_info_files
fib_info = get_t2_fib_info(duthosts, duts_config_facts, duts_minigraph_facts)
File …
=> Fix issue due to TypeError: 'dict_keys' object is not subscriptable

ansible/dualtor/nic_simulator/nic_simulator.py, tests/common/dualtor/dual_tor_io.py
Summary:
On Ubuntu 20.04 server, it has a newer ovs-vswitch installed(2.13.8). The newer versions(>=2.10) uses selection method dp_hash instead of hash on select group by default. And this change break the packet trace command. Two issues:
1. hash behavior difference for dualtor-aa testbeds between Ubuntu 18.04 and 20.04 server.
2. the packet trace command fails to predict the packet forwarding, which result in nightly failure.
So, two improvements:
1. On Ubuntu 20.04 server, use OpenFlow15 and set explicitly with hash selection method as hash.
2. in the packet prediction function, loop for at most 100 times.
Run `nic_simulator` on both Ubuntu 18.04 and 20.04.
=> [dualtor-aa] Fix OpenFlow select method change on Ubuntu 20.04

tests/conftest.py
Summary:
For devices with small disk or small memory, sometimes it would output a memory/disk usage warning alarm.
Add a log before and after the case, providing more clues to debug the disk/memory usage warning issue.
Run case in local, could find the log.
=> output disk and memory usage info before/after test

tests/common/devices/sonic.py, tests/generic_config_updater/test_pfcwd_status.py
Summary: 
Ignore certain log errors after the test generic_config_updater/test_pfcwd_status on TD2 platforms
The test failed in the log checking stage for the errors below:
Jan  4 22:44:30.824770 ck304 ERR syncd#syncd: [none] SAI_API_QUEUE:_brcm_sai_cosq_stat_get:1972 cosq stat get failed with error Invalid parameter (0xfffffffc).
Jan  4 22:44:30.824919 ck304 ERR syncd#syncd: [none] SAI_API_SWITCH:sai_bulk_object_get_stats:670 get bulk queue stats failed with error -5.
The error is from running checkBulkCapability(https://github.com/sonic-net/sonic-sairedis/blob/master/syncd/FlexCounter.cpp#L463), the program can continue even returning false as it will use the none-bulk way to create counters thereafter. We could safely ignore the log. We are told that the …
=> Ignore log error related to sai_bulk_object_get_stats in test_pfcwd_status for TD2 platforms

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: Skip the TestEverflowV4EgressAclEgressMirror on t0-120 topo on Mellanox platform due to HW resource limitation
=> [Mellanox]Add skip for some Everflow test

ansible/roles/sonic/tasks/vsonic.yml, ansible/roles/vm_set/tasks/add_topo.yml
Summary:
By default, don't push the docker-ptf.tar container image to the neighbor devices and load it. On setups where the neighbor VMs are running on a different server and/or there are many neighbors, this can save a good amount of time.
Check for an option `ptf_on_neighbor`. Copy and load the PTF container on the neighbor SONiC VMs only if this option is set to true.
Loaded a kvm-t0-64-32 topo with SONiC neighbors with and without this option.
Command to deploy the PTF container on the neighbor device: `./testbed-cli.sh -t vtestbed.yaml -m veos_vtb -k vsonic add-topo vms-kvm-t0-64-32 password.txt -e ptf_on_neighbor=true`
The `-e ptf_on_neighbor=true` sets the `ptf_on_neighbor` option to true. With this set to false, or without this option specified, it will not be …
=> [vsonic]: Don't push and load the PTF container on neighbors by default

tests/common/fixtures/advanced_reboot.py
Summary:
It looks like the downtime during warm reboot on KVM is, sometimes, hitting the 200-second limit. It appears to be going up to 5-10 seconds higher than the 200-second limit.
For now, bump up the limit by 15 seconds to 215 seconds.
KVM warm reboot only
=> Bump up the KVM downtime limit to 215 seconds

tests/platform_tests/conftest.py, tests/platform_tests/templates/expect_boot_messages
Summary:
The "Rebooting with /sbin/kexec" log regex has changed with Bookworm. Instead of using the `admin` user, the `root` user is used instead. Update the regex message to match that.
Verified on KVM running master branch image.
=> Update kexec regex for Bookworm

ansible/plugins/connection/switch.py, ansible/roles/vm_set/tasks/announce_routes.yml
Summary:
Fix add topo code issue when running with py3only sonic-mgmt-docer
Two issues are found when add topo with py3only docker
1. regex didn't work
2. Ansible constants didn't have ANSIBLE_SSH_ARGS attribute.
Code change.
With PY3 only sonic-mgmt-docker, manually run remove topo/add topo on physical testbed.
With PY2 and PY3 sonic-mgmt-docker, manually run remove topo/add topo on physical testbed.
=> Fix add topo code issue when running with py3only sonic-mgmt-docker

tests/dhcp_relay/test_dhcp_relay.py
Summary: 
Make dhcpmon counter loganalyzer regex compatible with dual tor
Fix dhcpmon counter test failure on dualtor
On single tor, REQUEST count is 3 because verify_dhcp_relay_pkt_with_no_padding sends two extra requests
Set dualtor REQUEST count to 1
Ran dhcp test suite
=> Make dhcpmon counter test compatible with dual tor

.azure-pipelines/recover_testbed/testbed_status.py
After recovery from console and get ssh session back, we need to upgrade image. But we notice that, during upgradation, while reboot, we will lose management ip again and casue the failure. In this PR, we write management ip into config_db.json to avoid the loss of management ip. 
Summary:
After recovery from console and get ssh session back, we need to upgrade image. But we notice that, during upgradation, while reboot, we will lose management ip again and casue the failure. In this PR, we write management ip into config_db.json to avoid the loss of management ip. 
After adding ip on device, re-generate config_db.json to save management ip. 
After re-generating config_db.json, do upgradation, and it won't lose management ip.
=> Save management ip into config_db.json after recovery via console. 

ansible/roles/test/files/ptftests/py3/copp_tests.py
…copp_tests.py
This PR fixes [Issue#11434](https://github.com/sonic-net/sonic-mgmt/issues/11434) which caused failure in test_copp.py::test_add_new_trap and test_remove_trap. The test uninstalls trap as first step in test and sends traffic to verify uninstallation of the trap. Since trap is disabled, no packets are expected from DUT to PTF, so rx_pps will be 0. 
But, in [PR#8199](https://github.com/sonic-net/sonic-mgmt/pull/8199), BGPTest was has policer limit and was changed to PolicyTest and it does not have the condition to check for trap status, thus failing test_copp.py when trap is disabled
Summary:
Fixes Issue#11434
- [x ] Bug fix
To fix copp tests failure caused by missing condition to check trap status 
Added conditon to check trap status and compare packet rate …
=> [CoPP] Enhancing ptftests/py3/copp_tests.py testcase to handle no trap condition

ansible/library/testbed_vm_info.py
Summary:
Fix DataLoader cannot be imported with py3only sonic-mgmt-docker
Fix DataLoader cannot be imported with py3only sonic-mgmt-docker
Ansible is upgraded in py3only docker.
If DataLoader cannot be imported, use yaml module to load the file.
With PY2 and PY3 sonic-mgmt-docker, manually run deploy-mg with physical testbed.
With PY3only sonic-mgmt-docker, manually run deploy-mg with physical testbed.
=> Fix DataLoader cannot be imported with py3only sonic-mgmt-docker

.github/workflows/automerge_scan.yml
Summary:
We are using Github workflows to automatically create PRs for cherry-picking. These auto created PRs are labeled with "automerge". Another workflow periodically scans the PRs with "automerge" label and merges them if all checks passed.
The problem is that the branch of these auto created PRs are not deleted after the PRs are merged. Consequently, the mssonicbld/sonic-mgmt repo has too many branches left over now. We'll manually do some cleanup.
Meanwhile, we also need to delete corresponding branch after PR is auto merged.
This changed added option "--delete-branch" to the Github cli for merging PRs. With this change, branches will be automatically deleted when automerge PR is merged.
=> [Github] Delete branch after "automerge" PRs are merged by workflow

tests/tacacs/test_authorization.py
Summary:
26638180
For slim images, telemetry has been disabled due to memory limitation.
"show feature status telemetry" is not supported.
Check the docker status, if telemetry is not running, but gnmi is running, then modify the cmd to "show feature status gnmi"
Run case locally
DUT which running slim image
=> enhance test_authorization_tacacs_only case since slim image has no telemetry

tests/platform_tests/cli/test_show_platform.py
Signed-off-by: Anand Mehra anamehra@cisco.com
On Chassis Supervisor, show platform summary displays number of asic present based on the number of Fabric Cards inserted. This number could less than max asics supported by the Chassis supervisor.
In show_platorm_summary test, this number is checked against the num_asics var from dut_vars which represents max asics supported on DUT. When Chassis is not fully populated with max FC cards, this test fails.
Fix: Get the number of asics expected from asics_present car from dut_vars and use that to validate the show platform summary output
Summary:
Fixes # [(issue)](https://github.com/sonic-net/sonic-buildimage/issues/17819)
test_show_platform::test_show_platform_summary  test case failure for Chassis SUpervisor when the chassis has less then max …
=> [chassis] Fixed expected_num_asics for Supervisor in test_show_platform

tests/common/snappi_tests/traffic_generation.py, tests/snappi_tests/pfc/files/helper.py
Summary: When verifying pause frames being generated/transmitted and received by the DUT during PFC tests, the way in which received pause frames are counted for lossy test cases or when the pause is not expected to be paused is incorrect. All PFC tests receive PFC frames from the traffic generator to congest the DUT's egress port, hence the check to ensure if this number is 0 is incorrect. 
Bug fix for test failures
Remove illogical check
Tested on lab devices
=> [Snappi] Update pause frame counting logic for DUT

tests/iface_namingmode/test_iface_namingmode.py
The `iface_namingmode` test attempts to verify that the original interface name is not present in counters output when alias mode is requested, but it winds up matching if the original interface name is a substring of an alias name (e.g., Ethernet1 would match Ethernet12 in the output and cause the test to fail).
This PR fixes a bug where the test mistakenly matches a substring of an interface name when looking for the original name of another interface (e.g., Ethernet12 matches Ethernet1)
I isolated the interface names from the CLI output and matched against the whole interface name, instead of doing a substring match on the entire output.
I ran the test manually against a DUT which was affected.
=> Fix iface_namingmode alias check

tests/snappi_tests/multidut/pfc/files/multidut_helper.py, tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
Summary: This PR is to fix the issue faced while running the latest master branch due to changes in traffic_generator.py 
This PR is to accommodate the latest changes that went into the traffic_generation.py file
Instead of passing the parameters as arguments for the fixtures that were used for creating traffic flows, the parameters were defined on snappi_extra_params object and there by reducing the arguments on the flow creation fixtures, this made the code significantly compact and scalable
After the changes the scripts were rerun on Arista DUT and ensured the cases run fine
T1 and T2
AzDevOps@5158df942848:~/sonic-mgmt/tests$ py.test --inventory ../ansible/snappi-sonic --host-pattern sonic-s6100-dut --testbed vms-snappi-sonic --testbed_file ../ansible/testbed.csv …
=> [Fix]:PFC multidut helper fix for latest traffic_generator.py

ansible/group_vars/sonic/variables, tests/qos/qos_sai_base.py
Porting the PR: #9713 to 202205, since there is a conflict in cherrypicking.
enable qos-sai scripts for cisco 8800-LC-48H-C48 platform
Summary:
Enables support for a new asic and new card using that asic
Type of change
Bug fix
Testbed and Framework(new/improvement)
Test case(new/improvement)
Back port request
201911
202012
202205
Approach
enable qos-sai scripts for cisco 8800-LC-48H-C48 platform
On local system, patched the change and tested with test qos sai XOFF test
=> [T2]:Porting 9713 to 202205: Enable qos-sai for 8800-LC-48H-C48

tests/saitests/py3/sai_qos_tests.py
Porting PR: #9655 to 202205:
Addressed in this PR:
1. Cisco-8000/Q100 platform doesn't add the headroom drops to the rx-drop counters (as this are not per port), so that particular check is being skipped in the PFCXoff testcase.
2. The print messages encounter this problem: https://github.com/sonic-net/sonic-mgmt/issues/9652. This PR addresses the formatting.
=> [T2]: Porting PR:9655 to 202205: Cisco-8000: Modifications to Xoff for Cisco-Q100 platform.

tests/saitests/py3/sai_qos_tests.py
Cherry-pick #11043 to 202205 branch.
@XuChen-MSFT : As requested, moving get_multiple_flows() calls to only cisco-8000.
This is for 202205.
Thanks,
rraghav
=> [202205] Move get_multiple_flows calls to cisco-8000 only

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/tacacs/test_authorization.py
Fix TACACS authorization issue: user can run rejected command when enable local authorization as fallback.
This is a cherry-pick PR for https://github.com/sonic-net/sonic-mgmt/pull/11261
Fix TACACS authorization issue: user can run rejected command when enable local authorization as fallback.
- Microsoft ADO: 26399545
per-command authorization found a code bug: When set per-command authorization to "tacacs+, local", user command blocked by server side but has local permission should failed. but currently it can success.
The UT code changed by this PR is testing and protect this incorrect behavior.
Create issue: https://github.com/sonic-net/sonic-mgmt/issues/11349
Fix UT and ignore it temporarily by this issue.
Pass all UT
=> [202205] [TACACS] Fix TACACS authorization issue: user can run rejected command when enable local authorization as fallback.

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
https://github.com/sonic-net/sonic-mgmt/pull/11289 was a cast to 202205 but the last quote `"` was accidentally removed.
Adding it back.
=> Fixing missing quote from PR11289

tests/run_tests.sh
Summary:
Currently in run_tests.sh, pretest and posttest are running separately with other scripts, but when we gathering other pytest scripts, pretest and posttest would be collected, so they would run twice, which would waste time
when gathering pytest scripts without specific testcases, remove pretest and posttest from all test scripts
=> Remove pretest and posttest from all run tests scripts

tests/pfcwd/test_pfcwd_function.py
The pfcwd_function test uses platform type to check if the DUT platform is HBM or not. This might not work all the time. This PR changes it to use the cable length as the way to verify if HBM is enabled or not.
@alpeshspatel , @abdosi : Pls review.
=> [T2]:Change the hbm-check condition to check the cable length.

tests/platform_tests/test_cpu_memory_usage.py
Summary:
We saw `test_cpu_memory_usage` is flaky on Mellanox-SN3800 testbed because the memory usage exceeds the threshold (60%) slightly.
```
E       AssertionError:  Memory {0: {'total': 8024224.0, 'free': 2997364.0, 'used': 4554004.0, 'used_percent': 62.6}, 1: {'total': 8024224.0, 'free': 2997184.0, 'used': 4554184.0, 'used_percent': 62.6}, 2: {'total': 8024224.0, 'free': 2996908.0, 'used': 4554456.0, 'used_percent': 62.7}, 3: {'total': 8024224.0, 'free': 2997212.0, 'used': 4554156.0, 'used_percent': 62.6}, 4: {'total': 8024224.0, 'free': 2997188.0, 'used': 4554180.0, 'used_percent': 62.6}, 5: {'total': 8024224.0, 'free': 2997456.0, 'used': 4553912.0, 'used_percent': 62.6}, 6: {'total': 8024224.0, 'free': 2997448.0, 'used': 4553920.0, 'used_percent': 62.6}, 7: {'total': 8024224.0, …
```
=> Adjust the memory check threshold for Mellanox-SN3800

tests/saitests/py3/sai_qos_tests.py
Summary:
This PR is to fix a syntax error in `TunnelDscpToPgMapping`.
The error message is as below.
```
"ERROR: sai_qos_tests.TunnelDscpToPgMapping", "----------------------------------------------------------------------", "Traceback (most recent call last):", "  File "saitests/py3/sai_qos_tests.py", line 1192, in runTest", "    self.client, asic_type, port_list['src'][src_port_id])", "AttributeError: 'TunnelDscpToPgMapping' object has no attribute 'client'", "", "----------------------------------------------------------------------", "Ran 1 test in 20.752s", "", "FAILED (errors=1)"], "stdout": "Using packet manipulation module: ptf.packet_scapy\n\n******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!
The following tests errored:
TunnelDscpToPgMapping …
```
=> Fix syntax issue in TunnelDscpToPgMapping

tests/common/plugins/loganalyzer/loganalyzer.py
Summary:
when running testcase with log analyzer, would get error:
E     File "/data/sonic-mgmt-int/tests/common/plugins/loganalyzer/loganalyzer.py", line 167
E       file_path = os.path.join(tmp_folder, f"log_error_{self.marker_prefix}_{cur_time}.json")
E                                                                                            ^
E   SyntaxError: invalid syntax
use .format() instead of f""
=> Fix invalid syntax in log analyzer

ansible/roles/vm_set/templates/cleanup.sh.j2
Summary: 
When I try run the script to clean up domains. will got error:
```
error: Failed to undefine domain vlab-01
error: Requested operation is not valid: cannot undefine transient domain
```
That's because the domain was not destroyed properly.
Fix the typo to destroy the domain.
=> [Bug_Fix] Fix cleanup.sh.j2 template doesn't destroy domain properly

tests/qos/test_qos_sai.py
The testcase: qos/test_qos_sai.py::TestQosSai::testQosSaiLosslessVoq uses an internal logic to find the required src and dst ports. This conflicts with the qos-sai-base.py, which returns a correctly calculated set of ports. This causes the test to fail in the case of O8C48, which contains 2 different set of ports with different port-speeds. This PR adjusts that test to use the ports from the qos-sai-base itself.
To fix the failure of losslessvoq in O8C48 platform.
Changed the test to use the ports from the base code.
Ran it on my O8C48 Testbed:
=============================================================================================== PASSES =============================================================================================== …
=> Change the losslessvoq ports to use the ones coming from qos-sai-base.

tests/qos/test_qos_sai.py
Porting 10381 to master, along with some more mods to fix precommit errors:
Addressing the test fails when they use uplink ports. Forcing the script to use downlink ports only.
=> Cisco: Qos-sai: Change the tests to use only downlink ports. 

azure-pipelines.yml
disable DPU test in 202311, because DPU image will not be applied to 202311. 
Summary:
disable DPU test in 202311, because DPU image will not be applied to 202311.
=> [202311, PR Test] deprecate dpu

ansible/roles/test/files/ptftests/py3/copp_tests.py
Reverts sonic-net/sonic-mgmt#11444
This change caused failure:
```
{
"changed": true,
"cmd": "/root/env-python3/bin/ptf --test-dir ptftests/py3 copp_tests.BGPTest --qlen=100000 --platform nn -t 'verbose=False;target_port=30;myip='\"'\"'10.0.0.39'\"'\"';peerip='\"'\"'10.0.0.38'\"'\"';send_rate_limit=2000;has_trap=False;hw_sku='\"'\"'Arista-7260CX3-D108C8'\"'\"'' --device-socket 0-30@tcp://127.0.0.1:10900  --device-socket 1-30@tcp://10.64.247.10:10900",
"delta": "0:00:55.442306",
"end": "2024-02-05 07:22:28.710549",
"failed": true,
"msg": "non-zero return code",
"rc": 1,
"start": "2024-02-05 07:21:33.268243",
"stderr": "/root/env-python3/bin/ptf:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import …
```
=> Revert "[CoPP] Enhancing ptftests/py3/copp_tests.py testcase to handle no trap condition"

tests/container_hardening/test_container_hardening.py
Summary: Add more containers to container hardening test case
=> [container hardening] include more containers to test case

.azure-pipelines/recover_testbed/common.py
When recovering testbeds whose hwsku are `arista`, we use A-boot to re-install image. In our previously code, we download image in `~` directory and the set-up file `boot-config` is in the directory `/mnt/flash`, which will cause error `flash:{{image_name}} not found or not a file`. So in this PR, we change into the /mnt/flash directory first and download image. 
Summary:
When recovering testbeds whose hwsku are `arista`, we use A-boot to re-install image. In our previously code, we download image in `~` directory and the set-up file `boot-config` is in the directory `/mnt/flash`, which will cause error `flash:{{image_name}} not found or not a file`. So in this PR, we change into the /mnt/flash directory first and download image. 
Change directory in A-boot first.
=> [Recover via console] Change into the /mnt/flash directory while installing image in aboot.

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
- Following platform errors are seen during random test runs, for example platform_tests/test_link_down.py,
```python
2023-12-04T18:08:59.9763391Z E               Dec  4 11:26:05.669304 svcstr-7250-sup-1 ERR kernel: [    2.733534] ccp 0000:09:00.2: firmware: failed to load amd/amd_sev_fam17h_model01h.sbin (-2)
2023-12-04T18:08:59.9764672Z E               
2023-12-04T18:08:59.9766037Z E               Dec  4 11:26:05.669305 svcstr-7250-sup-1 ERR kernel: [    2.743058] firmware_class: See https://wiki.debian.org/Firmware for information about missing firmware
2023-12-04T18:08:59.9767355Z E               
2023-12-04T18:08:59.9768464Z E               Dec  4 11:26:05.669323 svcstr-7250-sup-1 ERR kernel: [    2.948445] snd_hda_intel 0000:0a:00.3: no codecs found! …
```
=> Ignore firmware failed to load ERR messages

tests/voq/test_voq_ipfwd.py
Summary:
- This PR fixes '_test_voq_ipfwd.py::TestTableValidation::test_host_route_table_nbr_lb_addr_' test when the test checks for '_RegionalHub_' T3 peers loopback0 route entries.
- If there is a T3 peer of type '_RegionalHub_' and if it is present in the minigraph file or config under _DEVICE_NEIGHBOR_METADATA_, its loopback0 route entry presence check fails.
- This is because the routemaps for that '_RegionalHub_' type filter the loopback  routes advertised to SONiC T2.
- '_test_voq_ipfwd.py::TestTableValidation::test_host_route_table_nbr_lb_addr_' test fails when the test checks for '_RegionalHub_' T3 peers loopback0 route entries.
- routemaps for that '_RegionalHub_' type filter the loopback routes advertised to SONiC T2.
- Added a fix to use non _RegionalHub_ T3 …
=> Fix to use non RegionalHub peers to test route entry presence

tests/system_health/test_watchdog.py
Fix pause_orchagent fixture stop wrong orchagent on dualtor issue.
Fix pause_orchagent fixture stop wrong orchagent on dualtor issue.
- Microsoft ADO: 26458455
Orchagent watchdog UT failed on DualTor device because pause_orchagent pause orchagent on one tor but UT run on another tor.
Fix pause_orchagent fixture, use enum_rand_one_per_hwsku_hostname as parameter to stop orchagent on correct tor.
Pass all UT
=> Fix pause_orchagent fixture stop wrong orchagent on dualtor issue

tests/saitests/py3/sai_qos_tests.py
This is the same issue as solved in https://github.com/sonic-net/sonic-mgmt/pull/8990 but fixing a couple other lines in the same file.
Without this change we only format the 2nd line:
```
{}:
recv_counters {}
recv_counters_base {}
xmit_counters after send a few packets to trigger drop
xmit_counters_base [0, 1, 0, 0, 0, 118382, 0, 0, 0, 0, 8457920, 279, 0, 0, 56257, 8, 9, 0]
```
With this change both lines are formatted correctly:
```
after send a few packets to trigger drop:
recv_counters [0, 35, 0, 0, 0, 492567, 0, 0, 0, 0, 32405952, 283, 0, 0, 227941, 3253, 9, 0]
recv_counters_base [0, 35, 0, 0, 0, 457145, 0, 0, 0, 0, 30138944, 283, 0, 0, 227740, 3253, 9, 0]
xmit_counters [0, 63, 0, 0, 0, 0, 0, 0, 0, 0, 12546615, 168250, 0, 0, 0, 4366, 2188, 0]
xmit_counters_base [0, 62, 0, 0, 0, 0, 0, …
```
=> [202205] fix qos test prints on multiple lines

tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py
1, testQosSaiLosslessVoq requires split-voq or fair-voq, skip vanguard(cisco Q200 longlink) since it uses default-voq.
2. testQosSaiSharedReservationSize, skip gibraltar(cisco Q200 linecard) since not enough ports.
Skip shared_res_size_2 for pacific(cisco Q100 linecard) since on pacific, SQG thresholds have no impact on XOFF thresholds.
Summary:
Vanguard:
---------------------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiLosslessVoq_2024-02-03-00-37-06.xml -----------------------------
--------------------------------------------------------------------- live log sessionfinish ---------------------------------------------------------------------
00:40:50 …
=> update skip condition for cisco T2

tests/ecmp/test_fgnhg.py
Summary:
TypeError: slice indices must be integers or None or have an __index__ method
It is because python2 allow int as index of array but python3 don't. The code was from python2
Make "//" instead of "/" to make the result with integer.
Testbed verified.
=> fix py2 to py3 issue on ecmp

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: Skip the TestEverflowV4EgressAclEgressMirror on t0-120 topo on Mellanox platform due to HW resource limitation
=> Add skip for Everflow test

tests/pc/test_lag_member.py
Summary:
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/11657
Add arp check to make sure arp info is correct before test.
Add arp check to make sure arp info is correct before test.
Run tests.
=> [202205][pc] Fix test_lag_member_traffic arp issue

.azure-pipelines/recover_testbed/recover_testbed.py
In PR #10806, we support auto recovery of testbeds via console. But at that time, we didn't support Celestica testbeds at that time. Celestica testbeds use ONIE so we directly add Celestica into the branch which will be recoverd by ONIE.
Summary:
In PR #10806, we support auto recovery of testbeds via console. But at that time, we didn't support Celestica testbeds at that time. Celestica testbeds use ONIE so we directly add Celestica into the branch which will be recoverd by ONIE.
Add Celestica into the branch which will be recoverd by ONIE
=> [Recover via console] Support recovering Celestica devices via console

.azure-pipelines/recover_testbed/common.py
When recovering testbeds whose hwsku are Arista, we need to re-install image in Aboot. But the previous downloaded image will not be deleted in Aboot, and if we download the same image again, it will case `File exists` error in Aboot. We can either remove or rename the existing image on device, but rename image may cause error `free memory or disk space size is not enough`. So in this PR, we will remove the same image in Aboot. 
Summary:
When recovering testbeds whose hwsku are Arista, we need to re-install image in Aboot. But the previous downloaded image will not be deleted in Aboot, and if we download the same image again, it will case `File exists` error in Aboot. We can either remove or rename the existing image on device, but rename image may cause error `free memory …
=> [Recover via console] Remove image to avoid "File exists" error.

tests/common/snappi_tests/traffic_generation.py
Summary: PR #11400 introduced a logical regression for the unset_cev test whereby in the test, we send invalid PFC pause frames from the TGEN which we do not expect the DUT to be counting. This PR introduces a specific check for this scenario which was missing from the previous PR.
Bug fix for nightly triage
Added test specific logic
Ran on lab device
=> [Snappi] Bug fix for PFC class enable vector test

ansible/roles/test/vars/testcases.yml
Add support of t0-56-o8v48 to continuous_reboot test
Add support of t0-56-o8v48 to continuous_reboot test
Summary:
Add support of topology t0-56-o8v48 to continuous_reboot test
Add support of topology t0-56-o8v48 to continuous_reboot test
=> Add support of t0-56-o8v48 to continuous_reboot test

tests/qos/qos_sai_base.py
Update qos_sai_base.py to support dualtor-64 topology
Summary:
There was no support for dualtor-64 when preparing parameters used in test_qos_sai.py, which would lead to all cases failure.
Add support for dualtor-64 topology
=> Update qos_sai_base.py to support dualtor-64 topology

tests/generic_config_updater/test_pg_headroom_update.py
When buffer mode is dynamic type, the dut would not support updating qos configuration.
Base on the fact, I add a check to validate if the buffer mode is dynamic and skip test if it is.
Summary:
Make the script more stable.
Add a check
=> Update test_pg_headroom_update to check buffer mode before running

tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
thermal updater is a thread which will update ASIC/module thermal sysfs nodes periodically. Currently, there is no way to stop thermal updater. So, there is no easy way to mock thermal sysfs value if thermal updater is there (thermal updater will always override mocked values). 
- Microsoft ADO **(number only)**:
Ignore ASIC/module thermal mock test if thermal updater is present
Manual test
sonic-mgmt regression test
=> [Mellanox] Ignore checking ASIC/module temperature if thermal updater is there

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Due to late issues found BGP suppress fib pending related to FRR feature is no longer supported on 202305 and 202311. Based on the decision, the test script need to be skipped at 202305 and 202311.
Summary:
According to support status of bgp suppress fib pending function.
Skip test script of bgp suppress fib pending at 202305 and future 202311 branch.
Skip it in internal regression
=> Update skip condition for bgp suppress fib test

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Skip dualtor/test_tunnel_memory_leak.py by github issue #11403 on dualtor-64 topology
Skip dualtor/test_tunnel_memory_leak.py by github issue #11403 on dualtor-64 topology
Summary:
Script dualtor/test_tunnel_memory_leak.py not stable on dualtor-64 topology. 
Skip dualtor/test_tunnel_memory_leak.py by github issue #11403 on dualtor-64 topology
No
=> Update skip condition for test_tunnel_memory_leak

tests/ptf_runner.py
Before change, it took about 15 minutes to copy a 400M pcap file from ptf to sonic-mgmt. After change, the 400M pcap file can be compressed to 4M, and the copy takes 2 seconds.
Summary:
Copy large file from ptf to sonic-mgmt takes long time.
- Before change, it took about 15 minutes to copy a 400M pcap file from ptf to sonic-mgmt.
- After change, the 400M pcap file can be compressed to 4M, and the copy takes 2 seconds.
Compress pcap file before copying it from pft to sonic-mgmt
Run same test case, pass
No
=> Compress pcap files before copying it from pft to sonic-mgmt

tests/syslog/syslog_utils.py, tests/syslog/test_syslog_source_ip.py
Add a vrf create status check function to make sure portchannel bind with a created vrf.
It would make the script more stable
Summary:
Add a validation step for vrf creation
Test it in internal regression
No
=> Update script test_syslog_source_ip for stablization

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
…
This PR is to temporarily white-list the error log below:
```
ERR pmon#CCmisApi: :- checkReplyType: Expected to get redis type 0 got type 3, err: NON-STRING-REPLY
```
This error does not cause any functional impact on ycabled
There is an image fix going to be applied to this once we converge on a possible workaround. 
Summary:
=> [LogAnalyzer] white-list checkReplyType: Expected to get redis type error message

tests/qos/files/qos_params.jr2.yaml
The J2c+ qos params for 100_120K was updated in https://github.com/sonic-net/sonic-mgmt/pull/10146 but it wasn't updated for J2.
This has caused failures on `testQosSaiPfcXoffLimit` because we aren't sending sufficient packets to fill up the headroom so packets aren't being dropped.
I confirmed on a J2 system with these new values we end up filling up the headroom and drop packets.
=> Update J2 100_120k qos profile to match J2c

tests/common/snappi_tests/snappi_helpers.py, tests/common/snappi_tests/traffic_generation.py, tests/snappi_tests/pfc/files/helper.py
Summary: The current devices used in RDMA testing recently migrated to a L1 switch setup resulting in longer cables (5x) and forwarding lag that allows for the storage of greater frames in the cable. This lag is not accounted for in the tolerance threshold of 5%. As a result, the code has been modified to poll the TGEN counters at verification time after all traffic flows have been paused to allow for additional frames in the cable + buffer to propagate to the receiving port. There is also a bit of code cleanup done.
Bug fix for nightly test failure
Polled TGEN device at end of test (at verification time) as done with DUT polling
=> [Snappi] Bug fix for checking counters to account for forwarding lag

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
This PR is to skip service warm restart test on Mellanox platform as it's not required.
This PR is to skip service warm restart test on Mellanox platform as it's not required.
Update `tests_mark_conditions_platform_tests.yaml`
The change is verified by yaml file syntax check.
Mellanox platform specific.
=> Skip service warm restart test on Mellanox platform

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
The Mellanox 2700 T1 devices do not support sending BGP packets on queue 7. This test is being disabled.
Summary:
ADO 25587938
=> Disable test_bgp_queue mlnx 2700 T1

tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py
Use overflow_egress() to generate pkts_num_egr_mem in runtime if src and dst's asic types are different.
The pkts_num_egr_mem varies too much in different combinations. The qos params are based on ingress (Q100), so the pkts_num_egr_mem is 5915, but in Q100->Q200, pkts_num_egr_mem is 7536, 7536-5915 = 1621. It will cost too much time to send packets one by one for 1621 iterations.
With this, pg watermark case had to be skipped if src and dst asic-type are different. Because with using overflow_egress, it sends some extra packets, and that makes pg watermark increasing which fails the case. The case expects pg watermark to be 0 at the beginning. We can unskip it after thrift rpc api supports watermark clear.
In PFCXon case, overflow_egress() is called for all of 3 flows to get …
=> [T2] Generate pkts_num_egr_mem in runtime

tests/dns/static_dns/test_static_dns.py
fix #11681
When do the dhclient, if not specify the management port, it will also do dhclient other port,and may cause some error msg. To avoid this, need to specify the management port when do the dhclient, and kill the deamon after the test finish.
Summary: To make the test could pass without any err msg
=> Update the static dns test case

.azure-pipelines/recover_testbed/common.py
After getting the string "ONIE: Starting ONIE Service Discovery", we need to send an enter to get the prompt `ONIE#`. So that  we can continually send other strings we want. Previously code doesn't send this enter, so in this PR, we add it after getting the string "ONIE: Starting ONIE Service Discovery" in ONIE.
Summary:
After getting the string "ONIE: Starting ONIE Service Discovery", we need to send an enter to get the prompt `ONIE#`. So that  we can continually send other strings we want. Previously code doesn't send this enter, so in this PR, we add it after getting the string "ONIE: Starting ONIE Service Discovery" in ONIE.
Send enter after getting string "ONIE: Starting ONIE Service Discovery" in ONIE.
=> [Recover via console]  Send enter when getting the string "ONIE: Starting ONIE Service Discovery"

.azure-pipelines/recover_testbed/interfaces.j2, .azure-pipelines/recover_testbed/recover_testbed.py
After re-install in ONIE/Aboot etc. , we notice that the management ip is temporarily. After reboot, it will loss again. In this PR, we write management ip in `/etc/network/interfaces` to keep management ip static. 
Summary:
After re-install in ONIE/Aboot etc. , we notice that the management ip is temporarily. After reboot, it will loss again. In this PR, we write management ip in `/etc/network/interfaces` to keep management ip static. 
Re-format the file `interfaces.j2` and write management ip in `/etc/network/interfaces` to keep management ip static.
=> [Recover via console] Persistent management IP across reboot

.azure-pipelines/recover_testbed/testbed_status.py
We need to add ip configurations on SONIC at the end of recovery. In this PR, after adding ip configuration, we add a pause to wait for SONiC initialization.
Summary:
We need to add ip configurations on SONIC at the end of recovery. In this PR, after adding ip configuration, we add a pause to wait for SONiC initialization.
=> [Recover via console]  Add pause to wait for SONiC initialization.

tests/route/test_forced_mgmt_route.py
Add forced mgmt route test case.
Add forced mgmt route test case:
1. forced mgmt route add/del by port status.
1. forced mgmt route add/del will generate interfaces and route automatically.
- Microsoft ADO: 24719238
Check and protect forced mgmt route feature: 
1. forced mgmt route add/del by port status.
1. forced mgmt route add/del will generate interfaces and route automatically.
Add forced mgmt route test case:
1. forced mgmt route add/del by port status.
1. forced mgmt route add/del will generate interfaces and route automatically.
Pass all UT
=> Add forced mgmt route test case.

ansible/roles/vm_set/tasks/main.yml
Summary:
On testbed server, the IPv6 route cache may be full. When the issue is hit, we can observe messages like below in dmesg:
[2615625.047483] Route cache is full: consider increasing sysctl net.ipv[4|6].route.max_size.
[2615625.967008] Route cache is full: consider increasing sysctl net.ipv[4|6].route.max_size.
The impact is that static IPv6 configured on testbed server interface may stop working. Just ping the IP would get "Network is unreachable".
Reason:
The current SONiC testbed design needs to create many bridges on test server. Each bridge may consume some IPv6 route cache. When multiple testbeds are deployed on single server, the default route cache size 4096 may be hit.
The fix is to increase IPv6 route cache size on test server from default 4096 to 16384 …
=> [add-topo] Increase server IPv6 route cache size from default 4096 to 16384

.azure-pipelines/recover_testbed/common.py
While recovering via console, we need to re-install sonic image in boot loader. When installing in Aboot, we need to download the image file from a HTTP or TFTP server, and then use the boot command to load and boot the image. The installation process may take some time depending on the network speed and the image size. Previous waiting time is not enough for some situation, so in this PR, I add the waiting time while downloading image. 
Summary:
While recovering via console, we need to re-install sonic image in boot loader. When installing in Aboot, we need to download the image file from a HTTP or TFTP server, and then use the boot command to load and boot the image. The installation process may take some time depending on the network speed and the image size. Previous …
=> [Recover via console] Extend waiting time of installing sonic image.

tests/common/helpers/platform_api/sfp.py, tests/platform_tests/api/test_sfp.py
Since we are now planning to remove "active_firmware" and "inactive_firmware" version fields from TRANSCEIVER_INFO and are replacing it with TRANSCEIVER_FIRMWARE_INFO, we need to add a testcase for get_transceiver_info_firmware_versions API.
Also, we need to remove these fields from the existing testcase for https://github.com/sonic-net/sonic-mgmt/blob/aba8a1c001706e5117b028d43aa3041cba70722c/tests/platform_tests/api/test_sfp.py#L373
MSFT ADO - 26818128
Summary:
This issue should be merged along with https://github.com/sonic-net/sonic-platform-daemons/pull/435 and https://github.com/sonic-net/sonic-platform-common/pull/440
Ensured that platform_tests/api/test_sfp.py::TestSfpApi::test_get_transceiver_info testcase passes for a CMIS supported transceiver.
=> Modify test_get_transceiver_info to handle get_transceiver_info_firmware_versions API

tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py
Summary:
PR #10382 caused below two KeyError:
```
@pytest.fixture(scope="function", autouse=False)
def skip_pacific_dst_asic(self, dutConfig):
>       if dutConfig['dstDutAsic'] == "pac":
E       KeyError: 'dstDutAsic'
```
```
if "wm_pg_shared_lossless" in pgProfile:
pktsNumFillShared = qosConfig[pgProfile]["pkts_num_trig_pfc"]
elif "wm_pg_shared_lossy" in pgProfile:
>           if dutConfig['dstDutAsic'] == "pac":
E           KeyError: 'dstDutAsic'
```
and remove duplicated code in PR #11553 and PR #10838, it will cause pre-commit failure
```
@pytest.fixture(scope="function", autouse=False)
def skip_longlink(self, dutQosConfig):
portSpeedCableLength = dutQosConfig["portSpeedCableLength"]
match = re.search("_([0-9]*)m", portSpeedCableLength)
if match and …
```
=> fix keyerror of PR #10382

tests/ptf_runner.py
Summary:
in some corner case, qos sai test generated big pcap file, and spend much time to upload these pcap files.
somehow, it spend more than 10 hours to upload a single pcap file. as below:
when ptf cmd execution result is 0 (success), we need to skip collecting pcap file to scale down entire test time.
=> skip collecting pcap file when ptf cmd executes successfully

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Add community test skip condition due to github issue https://github.com/sonic-net/sonic-mgmt/issues/11404
Add community test skip condition due to github test issue https://github.com/sonic-net/sonic-mgmt/issues/11404
Summary:
Add community test skip condition due to github test issue [11404 ](https://github.com/sonic-net/sonic-mgmt/issues/11404) for case dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default
Add community skip condition
No
=> Add community skip condition due to github issue 11404

test_reporting/README.md
Summary:
The packages required by test report uploader have been built into the sonic-mgmt image. If run test report uploading inside sonic-mgmt container, activating python3 virtual environment is no longer needed.
This change improved the README.md under test_reporting folder accordingly.
=> Improve the venv content in README of test_reporting

tests/platform_tests/conftest.py
Summary:
Sometimes, after fast reboot, there is a random number of PORT_READY messages that occur; it could be 0, it could be the number of ports that are up, it could be some number in between. The reasoning for this is a bit unclear to me. However, considering the logic here prior to my changes had a relaxed check here, restore that behavior.
=> Relax the check on the number of PORT_READY messages

.azure-pipelines/recover_testbed/recover_testbed.py
During our recovery process, it may be necessary to reinstall the sonic image in the boot loader. This may result in a `.swi` file being left on the device. To prevent excessive disk usage on low-memory devices, we will delete this image file after the testbeds have been recovered.
Summary:
During our recovery process, it may be necessary to reinstall the sonic image in the boot loader. This may result in a `.swi` file being left on the device. To prevent excessive disk usage on low-memory devices, we will delete this image file after the testbeds have been recovered.
Delete the image file after the testbeds have been recovered from boot loader.
=> Clean up image file after recover testbeds from boot loader. 

.azure-pipelines/recover_testbed/constants.py
Previously, in order to install the sonic image in ONIE, we would catch the word "Discovery" in the string "ONIE: Starting ONIE Service Discovery" as the symbol. However, in the Celestica scenario, we cannot catch the whole word "Discovery," no matter how we adjust the buffer we set. Therefore, in this PR, we shorten the symbol to fit the Celestica scenario.
Summary:
ONIE Service Discovery" as the symbol. However, in the Celestica scenario, we cannot catch the whole word "Discovery," no matter how we adjust the buffer we set. Therefore, in this PR, we shorten the symbol to fit the Celestica scenario.
Shorten the symbol to fit the Celestica scenario.
=> [Recover via console] Shorten the constant ONIE_START_TO_DISCOVERY to fit for Celestica.

tests/telemetry/events/swss_events.py
Summary:
Skip `telemetry.swss_events` test on MGFX topologies because Queue OID is not supported on MGFX devices.
Skip `telemetry.swss_events` test on MGFX topologies because Queue OID is not supported on MGFX devices.
Function `test_event` in [telemetry/events/swss_events.py](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/telemetry/events/swss_events.py) is called by [telemetry/test_telemetry.py](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/telemetry/test_telemetry.py) instead of pytest framework. Hence conditional mark or pytest.skip doesn't work. The only way to skip this testcase is check the DUT topology and return for MGFX.
=> [MGFX] Skip telemetry.swss_events test on MGFX topologies

tests/dash/conftest.py, tests/dash/packets.py, tests/dash/test_dash_vnet.py
Summary:
Enhance the dash vnet test to support tcp and icmp packets.
Currently the dash vnet test only uses udp for data plane validation, we want to also cover icmp and tcp in the test.
Enhance the dash vnet test to support tcp and icmp packets.
Use a parameterized fixture inner_packet_type to generate a parameter from ['udp', 'tcp', 'echo_request', 'echo_reply'] for dash vnet test. 
Run the test on DPU setup and manually checked the packets sent and received, the types are as expected.
Only for dpu.
=> [Dash] Enhance the dash vnet test to support tcp and icmp packets

tests/stress/conftest.py, tests/stress/test_stress_routes.py
Summary:
26638188
test_stress_routes case would create so much swss logs which would cause /var/log file system full.
Since test_stress_routes is the stress case, it should be a very low chance to hit the isssue in production.
And for syslog file system full issue, log rotate would delete the old logs to fix the issue. 
In production, Syslog would sync to the kusto which could make sure no syslog lost in production.
Run case locally.
small disk and low memory device
=> ignore rsyslog ERR message in test_stress_routes

tests/vlan/test_autostate_disabled.py
Summary:
In PR #11383, we try to ignore `autoneg` related error logs in loganalyzer.
However, some logs with below format are not marched by previous regex.
```
Feb 17 11:39:40.131019 e1031-1 ERR swss#orchagent: message repeated 2 times: [ :- doPortTask: Ethernet52: autoneg is not supported (cap=0)]
```
In current PR, I updated the regex to ignore above logs.
Update loganalyzer regex in `test_autostate_disabled` to ensure all the `autoneg` related error logs are ignored on Celestica-E1031 platform.
Updated regex in testcase.
Verified on Celestica-E1031 M0 testbed with SONiC.202305 image.
 
This PR only for Celestica-E1031 platform.
=> [E1031] Update loganalyzer regex in test_autostate_disabled

tests/route/test_route_flap.py
Summary:
-  This PR fixes issue #11460 
- For T2 Chassis(topo-t2), route/test_route_flap works fine, if the selected duthost has upstream T3 neighbors.
- Similarly, if the selected duthost has downstream T1 neighbors and if there is only one dut with T1 neighbors, test works fine too.
- But if the selected duthost has downstream T1 neighbors and if there are more than one dut with downstream neighbors, route/test_route_flap fails.
- Fetch the 'neighbor type' (_LeafRouter/SpineRouter/AZNGhub_) based on the chosen _dev_port_ from _get_dev_port_and_route_
- Get all the neighbors of same neighbor type and fetch the ptf receiving ports list based on the retrieved neighbors list.
- Pass the received ptf ports list to send_recv_ping_packet method for further testing. 
- Ran …
=> [test_route_flap] Route flap multi-dut fix if the selected duthost has downstream neighbors

tests/arp/test_arp_extended.py
Summary:
The proxy_arp test is flaky for IPv6. Add debug logging to provide more info into failures. The test has been inconsistently failing on KVM testbeds when the expect NA packet is not received.
Add debug logging during the IPv6 proxy NDP test case to capture relevant DUT state/ndppd state and configs.
=> Add debug logging to proxy_arp test

tests/tacacs/utils.py
Fix TACACS accounting UT issue caused by auditd log rotate
Fix TACACS accounting UT issue caused by auditd log rotate
- Microsoft ADO: 26710599
Fix TACACS accounting UT issue caused by auditd log rotate.
There are 2 code issue:
1. when auditd log rotate, some auditd log will missing from output of 'service auditd status'
1. duthost.command() can only run 1 command, so can't handle piping output to grep
show auditd log with 'sudo journalctl -u auditd --boot' and run command with duthost.shell() to support grep.
Pass all UT
=> [TACACS] Fix TACACS accounting UT issue caused by auditd log rotate.

.azure-pipelines/recover_testbed/common.py
We use `onie-nos-install` to get sonic image from image server, download it and install it previously. But in bjw, it will cost some time to connect to the image server which cause timeout error in `onie-nos-install` itself. To avoid this error, we change the method of downloading sonic image in ONIE. First, we will use `wget` to get sonic image from image server and download it, which will not result in timeout issue. And then, we will use `onie-nos-install` to just install the image on device. 
Summary:
We use `onie-nos-install` to get sonic image from image server, download it and install it previously. But in bjw, it will cost some time to connect to the image server which cause timeout error in `onie-nos-install` itself. To avoid this error, we change the method of …
=> [Recover via console] Change the method of downloading sonic image in ONIE.

tests/qos/qos_sai_base.py, tests/saitests/py3/sai_qos_tests.py
The check - if the chassis is multi_asic , should be verified with the num_asic count on the dut.
Adding the correct method to verify multi_asic chassis in sai_qos_tests 
In continuation to PR #11282 
Summary:
For verifying the chassis is multi_asic ,the num_asic count on the dut should be greater than 1.
Found issue -
https://github.com/sonic-net/sonic-mgmt/issues/11236
Executed qos  tests on t2 chassis & verified.
=> Mutli_asic check for T2_arppopulate qos_test_corrected

tests/generic_config_updater/test_incremental_qos.py
ADO 26611267
Summary:
`replace` is only expected to succeed on devices where the field already exists, failure expected on other devices For some devices, BUFFER_POOL table does not include `xoff` field. For example, 
"BUFFER_POOL": {
"egress_lossless_pool": {
"mode": "dynamic",
"size": "34287552",
"type": "egress"
},
"egress_lossy_pool": {
"mode": "dynamic",
"size": "13924352",
"type": "egress"
},
"ingress_lossless_pool": {
"mode": "dynamic",
"size": "13924352",
"type": "ingress"
},
"ingress_lossy_pool": {
"mode": "dynamic",
"size": "13924352",
"type": "ingress"
},
"ingress_zero_pool": {
"mode": "static",
"size": "0",
"type": "ingress"
}
},
generic_config_updater/test_incremental_qos.py::test_incremental_qos_config_updates[replace-ingress_lossless_pool/xoff] SKIPPED (Skip …
=> [GCU E2E Testing] Consider `replace` test_incremental_qos.py test when field does not already exist

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Only run test_iface_loopback_action on Mellanox platform since it's the only platform it supports.
Skip test_iface_loopback_action except for Mellanox platform.
Case only supported on Mellanox platform.
=> [Conditional Mark] Only run test_iface_loopback_action.py on Mellanox

tests/qos/test_qos_sai.py, tests/qos/test_qos_sai.py.rej
Porting #11384 to 202205.
The testcase: qos/test_qos_sai.py::TestQosSai::testQosSaiLosslessVoq uses an internal logic to find the required src and dst ports. This conflicts with the qos-sai-base.py, which returns a correctly calculated set of ports. This causes the test to fail in the case of O8C48, which contains 2 different set of ports with different port-speeds. This PR adjusts that test to use the ports from the qos-sai-base itself.
Type of change
Bug fix
Testbed and Framework(new/improvement)
Test case(new/improvement)
Back port request
201911
202012
202205
202305
202311
Approach
To fix the failure of losslessvoq in O8C48 platform.
Changed the test to use the ports from the base code.
=> [202205]: Change the losslessvoq ports to use the ones coming from qos-sai-base.

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
This is **cherry-pick** PR for 202205 branch. Original PR #10468 
- During multiple tests teardown, seen the following LogAnalyzer match for kdump related messages being reported as errors.
- Issues seen in tests running on chassis with topo t2_2lc_36-masic.
- And also observed similar errors seen during dut reboot and config reload as well.
The issue is reported as https://github.com/sonic-net/sonic-mgmt/issues/10384
Example error message,
`Oct 15 08:06:10.491683 ixre-egl-board28 INFO kdump-tools[873]: no crashkernel= parameter in the kernel cmdline ...`
- During multiple tests teardown, seen the following LogAnalyzer match for kdump related messages being reported as errors.
- Issues seen in tests running on chassis with topo t2_2lc_36-masic.
- Since these …
=> [cherry-pick] Ignore kdump-tools log message from loganalyzer

tests/snmp/test_snmp_memory.py
Snmp memory load test has very unstable result on small memory device. Small differences can be significant when they are converted to percentage. So skip this test for small memory devices after getting snmp memory. This way we can still make sure snmp memory still returns result, but skip checking for the value.
Summary:
Fix snmp_memory_load
Skip test for small mem device.
Run test manually.
=> [snmp] skip snmp mem load for small mem device

tests/dash/conftest.py, tests/dash/dash_acl.py, tests/dash/test_dash_vnet.py
Align the existing dash tests to support DPU with one single port.
1.  For DPU with 2 ports, we have 2 neighbors, the first one is local PA, and the second one is remote PA. But for DPU with only one single port, we just have one neighbor (neighbor 1). So, we take neighbor 1 as the local PA. For the remote PA, we take the original neighbor 2's IP  as the remote PA IP,  and the original neighbor 2's network as the remote PA network. Take the mac of neighbor 1's mac as the mac of remote PA, because the BGP route to neighbor 1 is the default route, and only the mac of neighbor 1 exists in the arp table.  The remote ptf intf will take the value of neighbor 1 because the packet to remote PA will be forwarded to the ptf port corresponding to neighbor 1.
2.  Since some hwskus have the default …
=> Align dash tests to support DPU with one single port

tests/dhcp_relay/test_dhcp_relay.py
Summary:
There has been failed test runs where DHCP REQUEST count in dhcpmon debug syslog and state db counter is 100-140, when the expected count is 144. 
Ran tests manually and original test case passes most of the time, failed cases had a slight under count in REQUEST.
Checked packet capture in ptf and there are always 144 REQUEST packets, which indicates dhcpmon terminated early.
After increasing timeout, count is always 144.
After dhcp relay default ptf test, which doesn't wait for all 144 REQUEST packet. Checking dhcpmon counter immediately after may not have the most up to date output
Increase timeout after dhcp relay default ptf test
Ran test a dozen times on a device that had a failed run prior to timeout increase and test passed
=> [dhcp_relay] Increase timeout in dhcpmon loganalyzer check

.azure-pipelines/recover_testbed/common.py, .azure-pipelines/recover_testbed/constants.py, .azure-pipelines/recover_testbed/recover_testbed.py
This PR addresses the issue of celestica testbeds getting stuck during ONIE booting. We found that sending an enter to the terminal can prevent this problem. Therefore, we added a step to send an enter while recovering celestica testbeds in ONIE mode. 
Summary:
This PR addresses the issue of celestica testbeds getting stuck during ONIE booting. We found that sending an enter to the terminal can prevent this problem. Therefore, we added a step to send an enter while recovering celestica testbeds in ONIE mode.
Add a step to send an enter while recovering celestica testbeds in ONIE mode.
=> [Recover via console] Send `enter` while booting ONIE on celestica testbeds

tests/common/helpers/assertions.py
Summary:
In python3 environment, current pytest version is 7.4.0. Comparing
with old pytest version in python2 environment, this pytest version
expect string type message argument passed to the pytest.fail function.
Some tests scripts may pass non-string error message to the pytest_assert
function which calls pytest.fail under the hood. In this case, pytest
will throw exception TypeError.
Example traceback:
pytest.fail(message)
File "/usr/local/lib/python3.8/dist-packages/_pytest/outcomes.py", line 198, in fail
raise Failed(msg=reason, pytrace=pytrace)
File "/usr/local/lib/python3.8/dist-packages/_pytest/outcomes.py", line 38, in __init__
raise TypeError(error_msg.format(type(self).__name__, type(msg).__name__))
TypeError: Failed expected string as 'msg' parameter, got …
=> Fix TypeError when assertion message is not string

tests/macsec/__init__.py
Summary:
Got the following error:
```
def filter(interface, neighbor, mg_facts, tbinfo):
if self.downstream_neighbor(tbinfo, neighbor):
port = mg_facts["minigraph_neighbors"][interface]["port"]
links[interface] = {
"name": neighbor["name"],
>               "ptf_port_id": mg_facts["minigraph_ptf_indices"][interface],
"port": port
}
E           KeyError: '['
interface  = '['
links      = defaultdict(<class 'dict'>, {})
mg_facts   = {'deployment_id': '1', 'dhcp_servers': ['192.0.0.1', '192.0.0.2', '192.0.0.3', '192.0.0.4'], 'dhcpv6_servers': ['fc02:2000::1', 'fc02:2000::2', 'fc02:2000::3', 'fc02:2000::4'], 'forced_mgmt_routes': ['172.17.0.1/24'], ...}
neighbor   = {'name': 'Servers524', 'namespace': '', 'port': 'eth0'}
port       = 'eth0'
self       = …
```
=> [macsec]: Fix minigraph_ptf_indices key error

tests/platform_tests/fwutil/conftest.py
Change-Id: I62486e8265c0f90791d79dc72a37305c2e93c33b
Summary:
Fixes `AttributeError: 'list' object has no attribute 'keys'` error by replacing `.get()` default value to be dict instead of list in `random_component` fwutil fixture
Avoid AttributeError when dict has no expected key
Use dict as default value instead of a list
Run TC, no error is raised
=> set get() default value to dict in order to avoid keys() error

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
**Summary:**
Xfail or Skip below testcases on Celestica-E1031 due to sonic-net/sonic-buildimage#18229:
- platform_tests/api/test_chassis.py::TestChassisApi::test_get_revision
- platform_tests/api/test_psu.py::TestPsuApi::test_fans
- platform_tests/api/test_psu.py::TestPsuApi::test_get_revision
- platform_tests/api/test_sfp.py::TestSfpApi::test_get_error_description
Xfail below testcase on Celestica-E1031 due to sonic-net/sonic-buildimage#18231:
- platform_tests/test_xcvr_info_in_db.py::test_xcvr_info_in_db
Xfail or Skip testcases on Celestica-E1031 due to known issue.
Verified on Celestica-E1031 M0 testbed.
```
=========================================================================== short test summary info …
```
=> [E1031] Xfail or Skip some platform testcases on Celestica-E1031 due to known issue

.azure-pipelines/recover_testbed/common.py, .azure-pipelines/recover_testbed/constants.py
We observed a misalignment issue on 4600c dualtor testbeds, where the first line of each screen was not consistent. When we tried to select ONIE mode, it would go into ONIE Rescue mode with our previous code. To fix this, we added a condition to check if the output string contained "Rescue", and if so, we would send the arrow key "UP" to enter into ONIE Install mode.
Summary:
We observed a misalignment issue on 4600c dualtor testbeds, where the first line of each screen was not consistent. When we tried to select ONIE mode, it would go into ONIE Rescue mode with our previous code. To fix this, we added a condition to check if the output string contained "Rescue", and if so, we would send the arrow key "UP" to enter into ONIE Install mode.
To fix this, we added a condition …
=> [Recover via console] Avoid entering into rescue model of ONIE. 

.azure-pipelines/recover_testbed/recover_testbed.py
In PR #10806, we support auto recovery of testbeds via console. But at that time, we didn't support Force10-S6100 testbeds at that time. Force10-S6100 testbeds use ONIE as boot loader so we directly add Force10-S6100 into the branch which will be recoverd by ONIE.
Summary:
In PR #10806, we support auto recovery of testbeds via console. But at that time, we didn't support Force10-S6100 testbeds at that time. Force10-S6100 testbeds use ONIE as boot loader so we directly add Force10-S6100 into the branch which will be recoverd by ONIE.
Add Force10-S6100 into the branch which will be recoverd by ONIE.
=> [Recover via console] Support recovering `Force10-S6100` devices via console

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Backport #11815 
Xfail or Skip below testcases on Celestica-E1031 due to sonic-net/sonic-buildimage#18229:
- platform_tests/api/test_chassis.py::TestChassisApi::test_get_revision 
- platform_tests/api/test_psu.py::TestPsuApi::test_fans 
- platform_tests/api/test_psu.py::TestPsuApi::test_get_revision 
- platform_tests/api/test_sfp.py::TestSfpApi::test_get_error_description 
Xfail below testcase on Celestica-E1031 due to sonic-net/sonic-buildimage#18231:
- platform_tests/test_xcvr_info_in_db.py::test_xcvr_info_in_db
Summary:
=> [202311][E1031] Xfail/Skip some platform tests due to API not implemented (#11815)

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Backport #11815 
Xfail or Skip below testcases on Celestica-E1031 due to sonic-net/sonic-buildimage#18229:
- platform_tests/api/test_chassis.py::TestChassisApi::test_get_revision 
- platform_tests/api/test_psu.py::TestPsuApi::test_fans 
- platform_tests/api/test_psu.py::TestPsuApi::test_get_revision 
- platform_tests/api/test_sfp.py::TestSfpApi::test_get_error_description 
Xfail below testcase on Celestica-E1031 due to sonic-net/sonic-buildimage#18231:
- platform_tests/test_xcvr_info_in_db.py::test_xcvr_info_in_db
Summary:
=> [202305][E1031] Xfail/Skip some platform tests due to API not implemented (#11815)

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
This is a cherry-pick of #11767
Only run test_iface_loopback_action on Mellanox platform since it's the only platform it supports.
Skip test_iface_loopback_action except for Mellanox platform.
Case only supported on Mellanox platform.
=> [202305] Only run test_iface_loopback_action.py on Mellanox

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
orchagent has two threads, one of the threads is receiving messages to remove members from VLAN and the other thread is receiving FDB events (LEARN, AGE etc.) from syncd/SAI. There can be a race condition where FDB events were already in flight for a member which was getting removed from the VLAN. If orchagent processes the request to remove the member from VLAN first and then processes the FDB event, it will not find the port since bridge port ID is not valid any more. Because of this, we see an error message like ' ERR swss#orchagent: :- update: FdbOrch MOVE notification: Failed to get port by bridge port ID' in syslogs This error is completely harmless and does not affect the functionality.
This PR ignores above error message so that it does not cause the testcase to fail.
The error …
=> Ignoring error Failed to get port by bridge port ID

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
- This is **cherry-pick** PR for _202305_ branch. Original PR #11227 
- Following platform errors are seen during random test runs, for example platform_tests/test_link_down.py,
```python
2023-12-04T18:08:59.9763391Z E               Dec  4 11:26:05.669304 svcstr-7250-sup-1 ERR kernel: [    2.733534] ccp 0000:09:00.2: firmware: failed to load amd/amd_sev_fam17h_model01h.sbin (-2)
2023-12-04T18:08:59.9764672Z E               
2023-12-04T18:08:59.9766037Z E               Dec  4 11:26:05.669305 svcstr-7250-sup-1 ERR kernel: [    2.743058] firmware_class: See https://wiki.debian.org/Firmware for information about missing firmware
2023-12-04T18:08:59.9767355Z E               
2023-12-04T18:08:59.9768464Z E               Dec  4 11:26:05.669323 svcstr-7250-sup-1 ERR …
```
=> [cherry-pick] Ignore firmware failed to load ERR messages (#11227)

tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py
Summary:
double commit PR #11722
PR https://github.com/sonic-net/sonic-mgmt/pull/10382 caused below two KeyError:
```
@pytest.fixture(scope="function", autouse=False)
def skip_pacific_dst_asic(self, dutConfig):
>       if dutConfig['dstDutAsic'] == "pac":
E       KeyError: 'dstDutAsic'
```
```
if "wm_pg_shared_lossless" in pgProfile:
pktsNumFillShared = qosConfig[pgProfile]["pkts_num_trig_pfc"]
elif "wm_pg_shared_lossy" in pgProfile:
>           if dutConfig['dstDutAsic'] == "pac":
E           KeyError: 'dstDutAsic'
```
fix keyerror
=> [202205] fix keyerror of PR #10382

tests/platform_tests/test_reload_config.py
Fix issue:https://github.com/sonic-net/sonic-mgmt/issues/11654
1. Revert PR: https://github.com/sonic-net/sonic-mgmt/pull/7289/, because the relevant issue has been fixed by PR:https://github.com/sonic-net/sonic-buildimage/pull/15080
2. Remove  wait_until(60, 1, 0, check_interfaces_config_service_status, duthost) in PR: https://github.com/sonic-net/sonic-mgmt/pull/7953 due to the above same reason
Summary:
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/11654
Fix issue:https://github.com/sonic-net/sonic-mgmt/issues/11654
1. Revert PR: https://github.com/sonic-net/sonic-mgmt/pull/7289/, because the relevant issue has been fixed by PR:https://github.com/sonic-net/sonic-buildimage/pull/15080
2. Remove  wait_until(60, 1, 0, check_interfaces_config_service_status, duthost) in PR: …
=> Fix test_reload_config issue

tests/pfcwd/test_pfcwd_function.py
Porting both 10245 and 10481 to 202205.
**PR: 10245:**
Update the tests in tests/pfcwd/test_pfcwd_function.py to use static_th for profiles which use static_th. The default handling was for profiles using dynamic_th.
**Approach**
For interfaces using long links, cisco-8000 enabled static buffer pool and the profiles using this pool has static_th.
The pfcwd tests were developed for profiles with dynamic_th where the alpha was changed in the test case.
This was not applicable to static profiles and enhanced the test to handle the updated pool and profile types.
Verified on cisco-8000 system, on interfaces with long links (120km) that use static_th for profiles and static buffer pool.
A related change to update mmuconfig …
=> Cherrypick 10245 and 10481 to 202205.

ansible/group_vars/sonic/variables, ansible/plugins/connection/multi_passwd_ssh.py
Summary:
The existing multi_passwd_ssh plugin supports specifying single alternate password in ansible variable or command line.
This change enhanced the plugin to support a list of alternate passwords.
New ansible variable introduced by this change:
ansible_altpasswords
ansible_ssh_altpasswords
For backward compatibility, the existing "ansible_altpassword" variable is till kept.
Two ways to use this new variable:
1. From ansible variable files, for example in ansible/group_vars/sonic/variables: 
```
ansible_altpasswords:
- fakepassword1
- fakepassword2
```
2. From ansible-playbook cli:
```
ansible-playbook -i <inv_file> -l <target_host> <playbook_file.yml> --extra-vars='{"ansible_altpasswords": ["fakepassword1"]}'
```
Tested on VS setup.
=> Enhance multi_passwd_ssh plugin to support list of alternate passwords

ansible/devutils
Summary:
The devutils tool may raise exception like below if the output_watts of PDU is empty string `''`:
ValueError("invalid literal for int() with base 10: \'\'")
This change improved the code of parsing output_watts. Another issue is that a temporary variable named `status` conflicts with another variable. This change also fixed that.
Verified by trying to get pdu status using the devutils tool.
=> [devutils] Fix issue of parsing output_watts of PDU

tests/common/devices/onyx.py
The speed support list for onyx is like '1G 10G 25G 40G 50Gx1 50Gx2 100Gx2 100Gx4 200Gx4'. When the fanout is onyx, we need to set the speed according to the speed support list.
For example, when dut and fanout all support 50G, if the support speed list of fanout just includes 50Gx1 not includes 50G, we need to set the speed with 50Gx1 instead of 50G, otherwise, the port can not be up.
Summary:
Improve the setting speed function for onyx fanout
Select the match speed from the support speed list
Run testQosSaiDwrr with onyx fanout
Any
=> [Mellanox] Improve the setting speed function for onyx fanout

ansible/templates/minigraph_dpg.j2, ansible/vars/topo_t0.yml
Modified the test to suit the secondary subnets scenario, the dhcp related changes are in the PR: https://github.com/sonic-net/sonic-buildimage/pull/17012
Summary:
Fixes # (issue): NA
This is to test the changes included in the HLD: https://github.com/sonic-net/SONiC/pull/1470
Added a new secondary subnets entry in the topology file and added parsing logic for the same
The existing test cases of dhcp_relay
NA
=> Modify dhcp_relay test case in two vlan scenario to have secondary subnets 

tests/bgp/test_bgp_dual_asn.py
Summary:
During the teardown for `bgp/test_bgp_dual_asn.py::test_bgp_dual_asn_v4`, the PTF interface used for the test is flushed of all IPv4 and IPv6 addresses, including the IPv6 link local address. As a result, NDP and other IPv6 functionality is broken for the flushed interface.
Specify 'global' scope when flushing the PTF interface to avoid removing IPv6 link local addresses.
Run the test, verify that all PTF addresses still have an IPv6 link local address after the test is finished.
=> [bgp]: Don't flush link-local addr during teardown

.azure-pipelines/recover_testbed/recover_testbed.py
The argument `output` is redundant in script `recover_testbed.py`. To keep the clean of the code, we remove this argument in script. 
Summary:
The argument `output` is redundant in script `recover_testbed.py`. To keep the clean of the code, we remove this argument in script. 
Remove redundant argument `output` in script `recover_testbed.py`
=> Remove redundant argument `output` in script `recover_testbed.py`

tests/cacl/test_cacl_application.py
…case
Summary:
On latest master image, test_cacl_application_dualtor case could fail due to the following reason:
`Failed: Missing expected iptables rules: {'-A DHCP -m mark --mark 0x67005 -j DROP'}`
This is caused by the oscillation logic: https://github.com/sonic-net/sonic-linkmgrd/pull/221
As there is no icmp_responder running, the mux will start flap, if it flaps betrween expected_dhcp_rules_for_standby fixture and 
the real iptables check, there could be some unexpected dhcp iptables which will cause case failure.
Fix Unexpected DHCP iptables rules for test_cacl_application_dualtor
test_cacl_application_dualtor is used to verify dhcp iptables on dualtor, not oscillation.
Before dualtor case, set mux mode to manual
`sudo config mux mode manual all`
in test teardown, …
=> Fix Unexpected DHCP iptables rules for test_cacl_application_dualtor

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Skip test_kdump on Nokia-7215 platform. Kernel dump is not supported on Nokia-7215 yet.
Skip test_kdump on Nokia-7215 platform. Kernel dump is not supported on Nokia-7215 yet.
Updated conditional mark file.
Verified on Nokia-7215 testbed.
```
=============================================== short test summary info ================================================
SKIPPED [1] platform_tests/test_kdump.py: Not supported on Nokia-7215 platform
```
This PR for Nokia-7215 only.
=> Skip test_kdump on Nokia-7215 platform

tests/cacl/test_ebtables_application.py
Summary:
After change in https://github.com/sonic-net/sonic-buildimage/pull/18064, need to update expected rules for ebtables
Fix the following failure
```
>       pytest_assert(len(unexpected_ebtables_rules) == 0, "Unexpected ebtables rules: {}"
.format(repr(unexpected_ebtables_rules)))
E       Failed: Unexpected ebtables rules: {'-d Multicast -j DROP'}
```
Add -d Multicast -j DROP in expected rule;
Run test_ebtables_application against master/202305/202311 image.
=> Add expected "-d Multicast -j DROP" rule in test_ebtables_application

tests/telemetry/events/bgp_events.py
Summary:
Fixes # (issue) 26963525
We should use configured holdtime timer value from bgp neighbor instead of predetermined value, as config may be overwritten.
Fetch value bgpTimerConfiguredHoldTimeMsecs from bgp neighbor 
Manual test/pipeline
=> Use configured bgp neighbor info for holdtime timer

ansible/dualtor/config_simulated_y_cable.yml
Summary:
PR #11804 accidentally left hardcoded arguments for testing purpose in committed code.
This caused mux server address is always "172.17.0.1" in /etc/sonic/mux_simulator.json after deploy-mg is executed on dualtor testbeds.
This change updated the hardcoded arguments to variables.
Tested on physical dualtor testbed.
=> Fix hard coded arguments in config_simulated_y_cable.yml

tests/common/devices/eos.py, tests/common/devices/fanout.py
Catch eos fanout host unreachable in pretest by running show command.
Catch eos fanout host unreachable in pretest by running show command.
Run show version command after eos fanout host initializing to check reachability.
Test pretest on reachable&unreachable eos fanout host, both results are as expected.
=> Catch eos fanout host unreachable in pretest by running show command

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/qos/files/cisco/qos_param_generator.py, tests/qos/files/qos_params.gb.yaml, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py
Double commit https://github.com/sonic-net/sonic-mgmt/pull/10838
1, Add a new case to test lossy fair-voq.
2, Add lossy_queue_voq_2 and lossy_queue_voq_3 to qos_param_generator.py.
Default-voq and fair-voq will pass lossy_queue_voq_2, fair-voq and split-voq will pass lossy_queue_voq_3.
Summary:
The verification had been done in https://github.com/sonic-net/sonic-mgmt/pull/10838
Case testQosSaiLossyQueueVoqMultiSrc
vanguard(Q200 longlink, default voq) skipped:
```
-------------------------------------------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueueVoqMultiSrc.xml --------------------------------------------------
------------------------------------------------------------- …
```
=> [202305] [T2] Add case to test lossy fair-voq

tests/acl/custom_acl_table/acl_rules.json, tests/acl/custom_acl_table/test_custom_acl_table.py
In Active-Active DUAL TOR setup, we have the following two important constraints to maintain link state of TORs:
1. gRPC communication between TORs and gRPC server (nic_simualtor).
2. Heartbeat between TORs and server (icmp_responder).
Issue-1 with the failing testcases in test_custom_acl_table.py is, it is fundamentally verifying the INGRESS ACL functionality and the ACLs being used in the test case are not aware of the above 2 points. The moment we apply the INGRESS ACL, it starts blocking the above-mentioned control packets. This results in links in randomly selected TORs going in STANDBY mode, causing test case failure.
Issue-2 with the failing test case in test_custom_acl_table.py is, it does not consider the possibility of test pkts going to unselected ToR  in A/A setup
As a fix, …
=> custom acl table test failure in dualtor-aa fix

ansible/library/show_ipv6_interface.py, docs/api_wiki/ansible_methods/show_ipv6_interface.md, tests/common/devices/sonic.py, tests/common/devices/sonic_asic.py, tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py
Summary:
This change introduces an IPv6 test for TC to queue mapping in the QoS suite alongside the infrastructure needed to construct this test. Resolves #10939
There is a missing test gap for IPv6 DSCP to TC queue mapping. This change introduces a test to fill this test gap by modifying an existing test DscpToQueueMapping which previously tested DSCP to TC queue mapping on IPv4 to also test it for IPv6.
Modified existing `testQosSaiDscpQueueMapping` to also test for IPv6, and added changes to `active_ip_interfaces` to also fetch IPv6 addresses to be used in this test. 
Ran the test manually and it passed.
=> Add IPv6 TC to queue mapping test

tests/dns/static_dns/test_static_dns.py
Need to check if the dhclient pid exist or not on the dut host. 
Summary:
=> [Static DNS]fix static dns issue

tests/saitests/py3/sai_qos_tests.py
Summary:
Since testQosHeadroomPoolsize test takes more than one source port as input, even after tx disable, the packets could still hash from the other ports. Hence tx_disable has to be applied on all ports in the destination lag to block all the traffic during tx_disable.   
Since testQosHeadroomPoolsize test takes more than one source port as input, even after tx disable, the packets could still hash from the other ports. Hence tx_disable has to be applied on all ports in the destination lag to block all the traffic during tx_disable.  
This was achieved by
-Collecting all the dst_port_ids ports associated with the  src_port_ids
-Sending all the dst_port_ids  in a list, instead of sending a single dst_port_id  in tx_disable
Intermitted failure of testQosHdrmPoolsize …
=> QoSHdrmPoolsize _tx_disable_enable for all destination ports in lag

tests/arp/test_stress_arp.py
We optimize this script from two sides:
1. We sent ipv6 ND_NS packets with fake source IP addresses to DUT. DUT could not establish a connection with them because of the fake IP. However, our test objective was to add the entries on DUT regardless of their status. Therefore, in this PR, we remove the function wait_until to reduce the test execution time.
2. We removed the unnecessary step of assigning a fake IP address to the eth1 of ptf and deleting it after sending the packet. This step was not required for sending the packet to DUT. Each command in this step took about one second, which increased the execution time significantly. Therefore, we optimized the code by eliminating these commands.
Summary:
We optimize this script from two sides:
1. We sent ipv6 ND_NS packets …
=> Remove unnecessary steps in script `test_stress_arp.py` to save running time. 

ansible/roles/test/files/ptftests/py3/copp_tests.py, tests/copp/copp_utils.py, tests/copp/test_copp.py
This PR fixes the copp_utils.py to uninstall ip2me traps that captured packets after bgp trap uninstall and lead to unexpected delivery of packets to PTF
Also,
this PR brings back the PR[11444 ](https://github.com/sonic-net/sonic-mgmt/pull/11444) that added a condition to check trap presence status with added accurate log messages
Summary:
[11434](https://github.com/sonic-net/sonic-mgmt/issues/11434)
To fix copp testcase failure due to IP2ME trap capturing packets after bgp trap uninstall and missing condition to check trap status
Added ip2me and bgp trap to be uninstalled in copp_utils.py
Ran copp suite on M0/MX topology
=> Copp Testcase fix for no BGP trap scenario

docs/testplan/IPv4-Port-Based-DHCP-Server-test-plan.md
Summary:
Add test plan for dhcp_server
=> [dhcp_server] Add test plan for dhcp_server

tests/platform_tests/test_reboot.py
Interfaces_wait_time can be a custom value, but in function the old value was used, because the function default value is initialized when custom value is applied. Fix the bug.
Summary:
Fix bug to make interfaces_wait_time as expected.
Run tests
=> [platform_tests] fix interfaces_wait_time not expected problem

ansible/roles/test/files/ptftests/advanced-reboot.py
Summary:
Because of #10960 needing to be cherry-picked to 202305, there was some Python 3-only syntax present that caused failures on 202305, since the advanced-reboot script is run on the PTF container under Python 2. Specifically, `subprocess.wait` doesn't recognize the `timeout` argument.
Work around that by starting a timer where a kill signal is sent to the process if it hasn't terminated in 5 seconds. This probably won't be actually needed, though.
=> advanced-reboot: Fix timeout not being present in Python 2

ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py, tests/dhcp_relay/test_dhcp_relay.py
Summary:
DHCP broadcast flooding was resolved by this PR: https://github.com/sonic-net/sonic-buildimage/pull/18064. Hence interfaces under Vlan would not received broadcast flooding packets. Remove this verification.
Removed verification of receiving of DHCP broadcast flooding packets in other_client_ports.
Run tests.
=> [dhcp_relay] Fix faillure in test_dhcp_relay_default[single]

tests/common/config_reload.py
Signed-off-by: Anand Mehra anamehra@cisco.com
Added support for multi-asic to generate the correct running_golden_config file list for 'config reload -l' command for multi-asic systems
Summary:
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/11945
During sonic-mgmgt tests, if sanity precheck fails, the scripts try to recover the setup by executing ‘config reload’ with running_golden_config files saved.
the command executed is 'config reload -f -l /etc/sonic/running_golden_config.json'
This command works fine on single asic systems but does not work on multi-asic cards.
For multi asic cards, the config reload expects one global config file and one namespace config file for each namespace:
e.g: for 2 asic LC:
config reload -f -l …
=> Add multi-asic support for config_reload running_golden_config

ansible/roles/fanout/tasks/sonic/fanout_sonic_202012.yml
Summary:
Fixes 9332 fanout TX_DROP which causes TestQosSai::testQosSaiDwrr failure
When running qos/test_qos_sai.py::TestQosSai::testQosSaiDwrr,
If the fanout is 9332, there will be TX_DROP on interface to root fanout.
The reason is the 9332 QoS configuration is empty after deploy the fanout.
Add "config qos reload" when deploying 9332 fanout, if fanout sonic version is 202012.
1. Manually run: ansible-playbook fanout.yml -i str2 --limit str2-z9332f-03 -b --vault-password-file group_vars/all/secrets.json
2. After running the testcase(testQosSaiDwrr), the TX_DROP is 0.
3.
Before change:
```
admin@str2-z9332f-05:~$ show queue watermark unicast                                                                                                     
COUNTERS_BUFFER_POOL_NAME_MAP is empty!
``` …
=> Fix 9332 fanout TX_DROP which causes TestQosSai::testQosSaiDwrr failure

ansible/plugins/connection/multi_passwd_ssh.py, tests/common/devices/duthosts.py, tests/common/fixtures/duthost_utils.py, tests/ip/test_mgmt_ipv6_only.py
1. Add a fixture to convert the DUT to IPv6 only(only mgmt-ip)
2. Enhance the connection plugin to re-connect with the IPv6 address if the IPv4 address is unavailable
3. Add a new test module with examples to test the IPv6-only scenario.
Summary:
Support test mgmt-ip IPv6 only scenario.
Remove the IPv4 mgmt address before the test module starts, and restore after the test module is finished.
Enhance the connection plugging to first connect with the IPv4 address, and retry with the IPv6 address if IPv4 is unavailable.
Add a new test module with examples to test the IPv6-only scenario.
Run on physical testbeds, with dual-stack mgmt-ip addresses testbed and only with IPv6/IPv4 mgmt-ip address testbed.
============================================================================ …
=> [IPv6 only]Fixture to convert/revert the mgmt-ip to IPv6 olny, enhance connection plugin

tests/platform_tests/test_memory_exhaustion.py
Summary:
Fixes # [11737](https://github.com/sonic-net/sonic-mgmt/issues/11737)
- [x ] Bug fix
It seems the time it takes for the kernel to raise Out of Memory condition and trigger oom_killer is not very deterministic in this test case. Once memory is exhausted in the system, the node becomes very unresponsive as no new processes can be created. Under most cases the test does complete in 10 mts,  however for some of the PIDs, the test takes 20, 30 mts or more.
It seems the issue is seen in Linux operation in other scenarios - https://unix.stackexchange.com/questions/373312/oom-killer-doesnt-work-properly-leads-to-a-frozen-os
The solution seems to be to disable the swapping so the kernel raises the OOM condition much faster. 
https://askubuntu.com/questions/1188024/how-to-test-oom-killer-fr …
=> Memory exhaustion test case takes an indeterminate amount of time to trigger Kernel panic.

tests/arp/conftest.py
Summary:
This PR is to add a cleanup at the end of test `test_proxy_arp`.
Before this change, the code only deleted the DB entry from CONFIG_DB. However, `proxy_arp` is not disabled in the Vlan, which caused some issue for the subsequent test cases.
This PR addressed the issue by calling `config vlan proxy_arp VID disabled` at the end of the fixture.
This PR is to add a cleanup at the end of test `test_proxy_arp`.
This PR addressed the issue by calling `config vlan proxy_arp VID disabled` at the end of the fixture.
```
collected 3 items …
```
=> Disable proxy_arp at the end of test_proxy_arp

tests/telemetry/events/swss_events.py
Summary:
Fixes # (issue) 27001043
There is a timing issue when toggling interface admin status such that we don't see if-state event after interface is shut down or started up. In our test, we will verify that port is up/down after starting/shutting down the interface before toggling.
Code change
Manual test/Pipeline
=> Add timing for interface to go up/down before toggling

tests/telemetry/test_telemetry.py
Summary:
Fixes # (issue) 27085944
In one test case failure, we saw that 30 second max timeout was not enough time for the on change update to come. Increasing it to 60 seconds, but we expect the notification to come <=30 seconds.
Improve thread communication via passing a callback function instead of passing a results array
Code change
Manual test / pipeline
=> Add callback for thread to call after invoking ptf command

ansible/plugins/connection/multi_passwd_ssh.py, tests/common/devices/duthosts.py, tests/common/fixtures/duthost_utils.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/ip/test_mgmt_ipv6_only.py
1. Add a fixture to convert the DUT to IPv6 only(only mgmt-ip)
2. Enhance the connection plugin to re-connect with the IPv6 address if the IPv4 address is unavailable
3. Add a new test module with examples to test the IPv6-only scenario.
4. Fix the performance issue introduced by IPv6 detecting.
Summary:
Support test mgmt-ip IPv6 only scenario.
Remove the IPv4 mgmt address before the test module starts, and restore after the test module is finished.
Enhance the connection plugging to first connect with the IPv4 address, and retry with the IPv6 address if IPv4 is unavailable.
Add a new test module with examples to test the IPv6-only scenario.
Try with IPv4 first, only when IPv4 fails with unavailable, try IPv6 addr
Run on physical testbeds, with dual-stack mgmt-ip addresses …
=> [IPv6 only]Fixture to convert DUT mgmt-ip to IPv6 only

tests/platform_tests/test_kdump.py
Fix function definition in teardown module in test_kdump.py causing below error in cases of test failure
```
failed on teardown with "TypeError: wait_lc_healthy_if_sup() missing 2 required positional arguments: 'conn_graph_facts' and 'xcvr_skip_list'"
```
Issue: https://migsonic.atlassian.net/browse/MIGSMSFT-430
Fix the function definition to pass the required arguments
Run test case with the change
=> [kdump] Fix function definition in kdump test case teardown module

.azure-pipelines/baseline_test/baseline.test.template.yml
Summary:
According to https://github.com/sonic-net/sonic-mgmt/pull/11780, need to disable dpu kvm test to support multiple databases for smartswitch
Disable dpu for now
=> [Baseline] Disable dpu test to support multiple databases for smartswitch

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Due to uninstall copp failure, the test case would be failed on broadcom platform, to xfail these cases before it is fixed on 202305 branch.
Due to uninstall copp failure, the test case would be failed on broadcom platform, to xfail these cases before it is fixed on 202305 branch.
=> [conditional mark] xfail copp for broadcom

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/telemetry/test_telemetry.py
Summary:
Fixes # (issue) 25377424
Need to make corresponding change done in https://github.com/sonic-net/sonic-gnmi/pull/190 to sonic-mgmt test case
Fix expected sonic string in test case
Pipeline
=> Fix test_telemetry:test_osbuild_version to use correct SONiC string in OS version

tests/platform_tests/test_reboot.py, tests/platform_tests/test_reload_config.py, tests/platform_tests/test_sequential_restart.py
E1031 is weak and requires more wait time in many tests
Summary:
Many tests cannot pass because wait time is not enough
Add wait time
Run tests
=> [platform_tests] add wait time for e1031 devices

ansible/roles/test/files/ptftests/advanced-reboot.py
Summary: Fix advanced-reboot ptf py2 incompatibility - Popen.args
Popen.args is not compatible with py2, where we run testing under py2 ptf container
File "ptftests/advanced-reboot.py", line 1753, in tcpdump_sniff
self.start_sniffer(capture_pcap, sniff_filter, wait)
File "ptftests/advanced-reboot.py", line 1795, in start_sniffer
self.log("Tcpdump process {} terminated".format(process.args))
AttributeError: 'Popen' object has no attribute 'args'
Replace process.args with process.command
Ran related lines of code in py2 environment and no exception was thrown
```
kellyyeh@kellyyeh:/var/src/sonic-mgmt-int/tests$ python2
Python 2.7.18 (default, Jul  1 2022, 12:27:04) 
[GCC 9.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> pcap_path = …
```
=> advanced-reboot: Fix Popen.args not being present in Python 2

.azure-pipelines/run-test-elastictest-template.yml, .azure-pipelines/test_plan.py
Summary:
There is no retry to get elastictest token, if get token fails, whole build would fail
Add a retry to get elastictest token
Since kvm dump is no longer supported, set default value to false
=> Add retry to get elastictest token

tests/macsec/test_fault_handling.py
command "ifconfig <nbr_eth_port> down/up" fails of KVM nbr.
Test case data/tests/macsec/test_fault_handling.py/test_link_flap fails with the error: 
"ifconfig eth1 down  && sleep 1 && ifconfig eth1 up" Error: Interface name is invalid. Please enter a valid interface name
We need to provide Ethernet port instead of eth port.
Summary:
Providing a valid interface (Ethernet instead of eth) to down/up the KVM neighbour's interface.
It can be down with one of the following commands. I chose number 2.
1. ifconfig Ethernet1 down && sleep 1 && ifconfig Ethernet up
2. config interface shutdown Ethernet1 && sleep 1 && config interface startup Ethernet1
Tested the code on a dut with KVM (vsonic) neighbours
=> Valid interfaces on a KVM neighbor should be Ethernet instead of eth

tests/qos/test_qos_sai.py
In qos test runs, we intermittently see- “ERR syncd1#dsserve: _ds2tty broken pipe” error.
This error occurs during ‘bcmcmd ‘executes credit-watchdog enable\disable in test run.
Logs:
Oct 15 20:51:13.890515 ixre-egl-board1 INFO syncd1#supervisord: message repeated 7 times: [ syncd sai_thrift_get_queue_stats#015]
Oct 15 20:51:13.890515 ixre-egl-board1 INFO syncd1#supervisord: syncd sai_thrift_set_port#015
Oct 15 20:51:14.143547 ixre-egl-board1 NOTICE syncd0#syncd: :- threadFunction: time span 1 ms for 'get:SAI_OBJECT_TYPE_SWITCH:oid:0x21000000000000'
Oct 15 20:51:16.850876 ixre-egl-board1 INFO syncd1#supervisord: syncd sai_thrift_get_port_stats#015
Oct 15 20:51:16.852078 ixre-egl-board1 INFO syncd1#supervisord: syncd sai_thrift_get_port_attribute#015
Oct 15 20:51:16.899319 ixre-egl-board1 …
=> Adding loganalyzer exception to ignore ERR syncd#dsserve: _ds2tty broken pipe error.

tests/voq/test_voq_fabric_status_all.py
Summary:Fix fabric status check test to pass on t2min systems
test_voq_fabric_status_all.py might failed on t2min systems if more than 2 Linecards are inserted in that system. For these systems, fabric serdes links that connect to any of the linecards on supervisor will be up and running. But t2min only init 2 linecards for testing, so those fabric links that connected to none inited  linecards by the topology will failed test. 
In this change, the test will not failed  for those links anymore.
=> Fix fabric status check test to pass on t2min systems

tests/everflow/test_everflow_testbed.py
After debug and investigation, this failure of "test_everflow_testbed" on dualtor A-A including two issues:
the mux status is standby on the selected DUT.
the test pkts are not sent to selected DUT, which has everflow rule config.
The rootcause of 1 is due to BGP shutdown. In the script, it tries to shutdown all BGP during setup, which makes T1 not reachable from the TOR. Then the DUT moves itself into standby mode. That's from the design of mux state machine.
The rootcause of 2 is similiar to the following issue:
https://github.com/sonic-net/sonic-mgmt/pull/8158
We need fall back to active-standby mode to test this scenario for
active-active ports.
Summary:
Fixes # (https://github.com/sonic-net/sonic-mgmt/issues/9983)
Type of change
Bug fix
[x ] Testbed …
=> fix the everflow testbed failure on dualtor A-A

tests/pfcwd/files/pfcwd_helper.py, tests/pfcwd/test_pfcwd_function.py
Summary:
- PFCWD test ‘_test_pfcwd_multi_port_’ is SKIPPED for T2-Chassis, with the following error.
` 'Skipped: Pfcwd multi port test needs at least 2 ports'`
- This PR addresses the above issue, unskips the multi-port test for pfcwd suite with a generic fix.
-  _pfcwd/conftest.py : setup_pfc_test:_ - the modulo logic used to pick ports from the test_ports is always false in T2 case.
- Due to which, the test gets skipped because of the number of selected ports check, which is always 1 for a T2 DUT.
`pytest_require(len(selected_ports) == 2, 'Pfcwd multi port test needs at least 2 ports'))`
- Added a generic fix based on the total number of test ports.
- Ran PFCWD suite including, _test_pfcwd_multi_port_ and made sure the test is not skipped for run.
=> Generic fix to unskip pfcwd_multi_port test from skipped list for t2

tests/saitests/py3/sai_qos_tests.py
With the new SAI image & the fix as part of PR# https://github.com/sonic-net/sonic-buildimage/pull/16254, the DscpToPgMapping  qos test needs a check on the  PG7 as well because, the control packets from CPU will now come to PG7 and may increase the packet count.
Summary:
Adding  pg7 to verification along with pg0 & pg4 as, the control packets from CPU will now come to pg7 and may increase the packet count. 
DscpToPgMapping failed in test run.
Executed the  qos test suite.
=> Adding PG7 check to DscpToPgMapping

ansible/roles/fanout/tasks/sonic/fanout_sonic_202012.yml
This reverts commit 234a7ecd24946186505886e75f60f7945653e91e.
Summary:
Original PR#11967 will cause DUT portchannel down. No workaround is found currently. No RCA.
=> Revert PR#11967 - Fix 9332 fanout TX_DROP

tests/everflow/everflow_test_utilities.py, tests/everflow/test_everflow_ipv6.py
After debug and investigation, this failure of "test_everflow_ipv6" on dualtor A-A including two issues:
1. the mux status is standby on the selected DUT.
2. the test pkts are not sent to selected DUT, which has everflow rule config.
The rootcause of 1 is due to BGP shutdown. In the script, it tries to shutdown all BGP during setup, which makes T1 not reachable from the TOR. Then the DUT moves itself into standby mode. That's from the design of mux state machine.
The rootcause of 2 is similiar to the following issue:
https://github.com/sonic-net/sonic-mgmt/pull/8158
We need fall back to active-standby mode to test this scenario for
active-active ports.
Summary:
Fixes # ([9983](https://github.com/sonic-net/sonic-mgmt/issues/9983))
Verified this fix on A-A, A-S and single T0.
=> fix the everflow ipv6 failure on dualtor A-A

docs/api_wiki/README.md, docs/api_wiki/sonichost_methods/add_acl_table.md, docs/api_wiki/sonichost_methods/get_intf_link_local_ipv6_addr.md, tests/common/devices/sonic.py, tests/common/utilities.py, tests/dhcp_relay/acl/dhcpv6_pkt_recv_multicast_accept.json, tests/dhcp_relay/test_dhcp_pkt_recv.py
Summary:
To make sure DHCPv6 multicast packets can be received by device, we add a test to send DHCPv6 multicast packet with specific transaction ID from server to device, and check if `tcpdump` can capture the packet.
We need to make sure DHCPv6 multicast packets can be received by device.
We add a test to send DHCPv6 multicast packet with specific transaction ID from server to device, and check if `tcpdump` can capture the packet.
For mx topo, verified on Nokia-7215 testbed with 202305 image and 202205 image.
=> [dhcp_relay] Validate DHCPv6 multicast packets can be trapped to CPU

tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py, tests/saitests/py3/switch.py
Summary:
Adding support to read and verify the VOQ counters in LossyQueueTest for the dnx platform.
Below are the changes made to achieve this:
- Collect all the system ports associated with the destination port of the DUT (qos_sai_base.py)
- Get the voq_id for all for the corresponding system ports and read the voq_counters( switch.py)
- Read & verify the voq_counters in Test (sai_qos_tests.py) 
Below are the changes made to support voq counters in LossyQueueTest:
- Collect all the system ports associated with the destination port of the DUT (qos_sai_base.py)
- Get the voq_id for all for the corresponding system ports and read the voq_counters( switch.py)
- Read & verify the voq_counters in Test (sai_qos_tests.py)     
Executed the Qos tests
=>  [QoS]Adding support to read and verify the VOQ counters in LossyQueueTest

tests/route/test_forced_mgmt_route.py
[ROUTE] Improve test_forced_mgmt_route UT failed because interface change delay.
[ROUTE] Improve test_forced_mgmt_route UT failed because interface change delay.
- Microsoft ADO: 27024909
route.test_forced_mgmt_route randomly failed on hardware and KVM caused by a delay between interface-config service finish and interface change take effect.
Add retry code to wait untill interface change take effect.
Pass all UT
=> [ROUTE] Improve test_forced_mgmt_route UT failed because interface change delay.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
dhcpv6 relay packets verify test cases are not supported in dualtor-aa currently.
Skip test.
Run tests.
```
collected 5 items                                                                                                                                                                                                                                          
dhcp_relay/test_dhcpv6_relay.py::test_interface_binding PASSED                                                                                                                                                                                       [ 20%]
dhcp_relay/test_dhcpv6_relay.py::test_dhcpv6_relay_counter SKIPPED (Test is not supported in dualtor-aa) …
```
=> [dhcp_relay] Skip test_dhcpv6_relay ffor dualtor-aa

ansible/roles/test/files/ptftests/py3/dhcpv6_relay_test.py
Summary:
The dst ip address of packets come from upstream in dualtor should be loopback ip rather than vlan ip.
Use loopback ip as dst ip in dualtor
Run tests
=> [dhcp_relay] Update dhcpv6_relay_test for dualtor

tests/telemetry/events/swss_events.py
In the test file : telemetry/events/swss_events.py
in the function generate_pfc_storm, in the line
queue_oid = duthost.get_queue_oid(PFC_STORM_TEST_PORT, PFC_STORM_TEST_QUEUE)
The PFC_STORM_TEST_PORT - the port chosen to test the PFC storm on - is assigned a fixed value of “Ethernet4”, whereas, some DUTs don't have a port Ethernet4 associated with it’s ASIC instance. Therefore this test is passing when assigning a value of Ethernet8 or Ethernet16 which are valid ports.
Changing fixed assigned value, replacing it with a dynamically selected port from the list of ports that have both open and admin status as "UP"
Want to ensure that telemetry/test_events.py test case passes - and that when selecting a port to do a PFC storm on, we are chasing a valid port, instead of a fixed one. …
=> Dynamic PORT selection for PFC storm testing

.azure-pipelines/recover_testbed/recover_testbed.py
When an error occurs during recovery, the previous script would simply log the error and return, which Elastictest interprets as a successful operation. However, in this PR, we have implemented a change where if the script encounters a failure, it will now raise an Exception instead.
Summary:
When an error occurs during recovery, the previous script would simply log the error and return, which Elastictest interprets as a successful operation. However, in this PR, we have implemented a change where if the script encounters a failure, it will now raise an Exception instead.
Raise an exception instead of simply log the error
=> [Recover via console] Raise exception when something error happened during recovering. 

ansible/roles/test/files/ptftests/py3/vxlan-decap.py, tests/vxlan/test_vxlan_decap.py
vxaln decaptTest adaptation for DToR A/A topology
Summary:
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/11683
vxlan/test_vxlan_decap.py failure on DToR AA with below error
```
FAIL\n\n==================================================================      ====\nFAIL: vxlan-decap.Vxlan\n----------------------------------------------------------------------\nTraceback (most recen      t call last):\n  File \"ptftests/py3/vxlan-decap.py\", line 424, in runTest\n    self.warmup()\n  File \"ptftests/py3/vxlan-      decap.py\", line 358, in warmup\n    raise AssertionError(\"Warmup failed\")\nAssertionError: Warmup failed\n\n-------------      ---------------------------------------------------------\nRan 1 test in 87.954s\n\nFAILED (failures=1)", "rc": 1, "invocati      on": …
```
=> Fix for vxlan_decap test failure on dualtor-aa

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
unexpectedly skip HeadoomPoolSize test for Arista-7060CX-32S-D48C8
enable HeadoomPoolSize test for Arista-7060CX-32S-D48C8 in mark condition definition
=> not skip HeadoomPoolSize test for Arista-7060CX-32S-D48C8

tests/common/helpers/gnmi_utils.py
Summary:
The gnmi/test_gnmi_condifgb.py tests are failing stating that the right process (telemetry) is not running based on the supervisorctl status. The issues is caused because of generate_telemetry_config function checking the wrong container (gnmi) instead of telemetry for either gnmi-native, or telemetry processes. 
Changed the container generate_telemetry_config function was checking to telemetry instead of gnmi which was the wrong  container. 
[gnmi/test_gnmi_configdb.py - gnmi_utils_results.log](https://github.com/sonic-net/sonic-mgmt/files/14249347/gnmi_utilg_results.log)
gnmi/test_gnmi_configdb.py
Cherry pick to master branch PR - https://github.com/sonic-net/sonic-mgmt/pull/11943
=> Fix telemetry container in generate_telemetry_config

tests/ecmp/test_ecmp_sai_value.py
Summary:
Fix unexpected OFFSET_ECMP value for Arista-7050-QX-32S
Fix incorrect expected OFFSET_ECMP for Arista-7050-QX-32S.
The expected 0xa OFFSET_ECMP for Arista-7050-QX-32S is 33, not 67.
Add safe check for reboot, if not all critical services are booting up, will not check OFFSET_ECMP value,
ensure the failed summary is accurate.
Change Arista-7050-QX-32S's expected number of 0xa OFFSET_ECMP to 33.
Add safe_reboot=True for reboot
Run tests/ecmp/test_ecmp_sai_value.py on 7050qx and other testbeds.
=> Fix incorrect expected OFFSET_ECMP for Arista-7050-QX-32S and add safe_reboot

tests/saitests/py3/sai_qos_tests.py
Summary:
For single asic we are adding some leakout packets to account for case where packets might have leaked out of VOQ to OQ even though port tx has been disable.
For multi-asic case leakout packets is already accounted as part of overflow_egress calculation so we don;t need to add again.
- [] 202205
PGDrop test fails in single-asic mode due to calling dynamic fill of egr mem in single asic mode.
Skip the dynamic fill-mem.
Ran the test.
Specific to cisco-8000 only.
=> cisco-8000:Skip compensating leakout for multi-asic.

tests/lldp/test_lldp.py, tests/pc/test_lag_2.py, tests/voq/test_voq_nbr.py, tests/voq/voq_helpers.py
Added support for running T2 applicable tests using vsonic(KVM) for neighbors
Summary:
To add support for vsonic/KVM commands on neighbors, as the commands are different from Eo
Fix for test_lldp testcase:
KVM neighbors do not advertise port ifname. They instead advertise 'descr'. We will use ifname for EosHost and descr for KVM
Fix for voq tests
BGP:
- Use vtysh for BGP configuration on vsonic
Interface up/down:
- Use shut/no shut commands
voq_helper
Interface name and numbering:
Neighbors interface name is difference on vsonic vs Eos.
On Eos, inerfaces are named 'eth' (Ex. eth1) and portchannels are named po (Ex. po1).
On vsonic, interfaces are named Ethernet (Ex. Ethernet1) and portchannels are named PortChannel …
=> Cherry-picked from PR 6022: Added support for running T2 vsonic(KVM)

tests/bgp/test_traffic_shift.py
Summary:
-  This PR fixes issue #11266.
- In _bgp/test_traffic_shift.py_ tests, whenever '_parse_routes_on_vsonic_' method is called on neighbor host VMs, the method returns empty value instead of the routes received on neighbor host VMs.
- Due to this issue, test always returns false positive.
- _parse_routes_on_vsonic_ method should return all the routes parsed on all neighbor host VMs.
-  Instead, it always returns empty value.
- Tests always passes with false positive result.
- all_routes dictionary is not used as expected. Corrected the same.
- Ran some test cases which invokes method and verified it actually returns the expected routes.
_bgp/test_traffic_shift.py::test_TSA 
bgp/test_traffic_shift.py::test_TSA_TSB_with_config_reload …
=> Fix for parse_routes_on_vsonic for test_traffic_shift.py

tests/bgp/test_bgp_fact.py, tests/ip/test_mgmt_ipv6_only.py, tests/syslog/test_syslog.py, tests/test_features.py
Summary: Add ipv6 only mgmt syslog test case
Add ipv6 only mgmt syslog test case
Run tests
=> Add ipv6 only mgmt syslog test case

tests/gnmi/test_gnmi_configdb.py
Summary:
Fix gnmi test for DUT which all interfaces are routed.
Microsoft ADO: 27150366
GNMI test failed on DUT which all interfaces are routed.
Some DUT do not have portchannel and all the interface type are "routed".
I was using "routed" as key to detect portchannel, but this logic does not work for t1 backend topology.
I use lanes to detect portchannel, if lanes is "N/A", this is portchannel or other unwanted port.
=> Update gnmi test to support DUT which all interfaces are routed

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
topo was used instead of topo_type which was causing the condition to fail.
Summary:
topo was used instead of topo_type which was causing the condition to fail.
used topo_type instead of topo
Verified for T2 profile
=> Fixing topo issue in Copp skip test

tests/snmp/test_snmp_cpu.py
Moved the killall yes process to finally section so that the process will always get killed at the end of the testcase. We were seeing cases wherein they were left behind.
Summary:
In some cases we were seeing the yes process being left behind causing other testcases to fail due to high CPU.
=> Kill process causing CPU spike

tests/qos/qos_sai_base.py
This reverts commit 66751e52d2a59c3bae6cc00d1b8150ed543f9617.
Summary:
#11934  caused SNMP critical process crash issue in qos test
```
11:15:47 __init__._fixture_generator_decorator    L0081 INFO   | -------------------- fixture swapSyncd_on_selected_duts setup starts --------------------
11:16:43 sonic.is_container_running               L0450 INFO   | container syncd is not running
11:16:43 sonic.is_container_running               L0450 INFO   | container swss is not running
11:17:32 docker.swap_syncd                        L0169 INFO   | Reloading config and restarting swss...
11:17:32 config_reload.config_reload              L0092 INFO   | reloading config_db
11:19:13 processes_utils.wait_critical_processes  L0070 INFO   | Wait until all critical processes are healthy …
```
=> Revert "Fix qos/test_qos_sai.py teardown. (#11934)"

tests/qos/files/cisco/qos_param_generator.py
Summary:
in corner case,  cisco qos param calculating code hit syntax error:
```
11:50:04 __init__._fixture_generator_decorator    L0081 INFO   | -------------------- fixture dutQosConfig setup starts --------------------
11:50:04 qos_sai_base.dutQosConfig                L1369 INFO   | Lossless Buffer profile selected is BUFFER_PROFILE_TABLE:pg_lossless_100000_300m_profile
11:50:04 qos_sai_base.dutArpProxyConfig           L1317 INFO   | Failed to read vlan interface config. Excpetion Expecting value: line 1 column 1 (char 0)
11:50:07 __init__._fixture_generator_decorator    L0088 ERROR  | 
TypeError("unsupported operand type(s) for >>: 'float' and 'int'")
File "/var/src/sonic-mgmt-int/tests/common/plugins/log_section_start/__init__.py", …
```
=> cisco qos param calc hardening

tests/everflow/everflow_test_utilities.py, tests/everflow/test_everflow_ipv6.py
Reverts sonic-net/sonic-mgmt#10228
The TTL change caused some test regression.
=> Revert "fix the everflow ipv6 failure on dualtor A-A"

tests/common/plugins/loganalyzer/__init__.py, tests/conftest.py
Summary:
Add mark file for mgmt test.
Microsoft ADO: 24657445
We need a flag to mark that DUT is under end to end test.
https://github.com/sonic-net/sonic-utilities/pull/3102
db migrator needs to detect DUT is running in end to end test.
Create /etc/sonic/mgmt_test_mark with fixture.
Run end to end test, and check /etc/sonic/mgmt_test_mark.
=> Add mark file for end to end test

tests/dhcp_relay/test_dhcp_relay.py
Summary:
Add wait until for route check in dhcp_relay test
Add wait until for route check in dhcp_relay test
Run tests
=> [dhcp_relay] Add time wait for route check

tests/platform_tests/test_platform_info.py
Increase delay between PDU state change and reading PSU details to 10 seconds (previously 5).
5 second delay between PDU state change and accessing PSU details is not always enough. The time needed depends on PDU hardware, psud update interval, and PSU hardware. psud update interval of 3s only allows 2s for the PDU to change the power state, which may not always be enough. Increasing to 10 seconds allows at least 7 seconds for the PDU to apply a state change and PSU to reflect it, which MSFT has found sufficient.
Increase post-PDU state change delays to 10 seconds (previously 5 seconds)
MSFT verified by setting the delay to 10 seconds since Cisco was unable to reproduce with our PDU hardware.
=> Increase post-PDU state change delay to allow all PSUs to react

docs/api_wiki/README.md, docs/api_wiki/sonichost_methods/add_acl_table.md, docs/api_wiki/sonichost_methods/get_intf_link_local_ipv6_addr.md, tests/common/devices/sonic.py, tests/common/utilities.py, tests/dhcp_relay/acl/dhcpv6_pkt_recv_multicast_accept.json, tests/dhcp_relay/test_dhcp_pkt_recv.py
Summary:
To make sure DHCPv6 multicast packets can be received by device, we add a test to send DHCPv6 multicast packet with specific transaction ID from server to device, and check if tcpdump can capture the packet.
We need to make sure DHCPv6 multicast packets can be received by device.
We add a test to send DHCPv6 multicast packet with specific transaction ID from server to device, and check if tcpdump can capture the packet.
For mx topo, verified on Nokia-7215 testbed with 202305 image and 202205 image.
=> [PR:11978] [dhcp_relay] Validate DHCPv6 multicast packets can be trapped to CPU

tests/conftest.py, tests/test_posttest.py
Summary:
In posttest, dump files are packaged into .tar.gz archives, which include syslog data. In Elastictest, we aim to make it easier for users to read both dump and syslog files. Therefore, we need to decompress and distinguish between the dump and syslog files.
1. Add a param testbed_idx mark different testbed
2. Extract dump and syslog file into folder with testbed_idx
=> Extract dump and syslog file into folder with testbed_idx in posttest

tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Summary:
Fixes snmp_pdu_controolers.py cannot handle outlet power null string
Testcase will fail if outlet power string is null.
Do NOT return output_watts if outlet power string is null.
By running devutils, if the PDU cannot provide watts value, snmp_pdu_controllers.py return items without output_watts.
```
[
{
"Host": "strtk5-s6100-acs-5",
"PSU status": {
"PSU1": {
"power_on": true,
"output_watts": "N/A"
},
"PSU2": {
"power_on": true,
"output_watts": "N/A"
}
},
"PDU status": [
{
"outlet_id": ".1.1.37",
"outlet_on": true,
"pdu_name": "pdu-229",
"psu_name": "PSU1",
"feed_name": "N/A"
},
{
"outlet_id": ".1.1.36",
"outlet_on": true,
"pdu_name": "pdu-230",
"psu_name": "PSU2",
"feed_name": "N/A"
}
],
"Summary": [],
"Action": "status"
}
]
```
=> Fix snmp_pdu_controllers.py cannot handle outlet power null string

ansible/config_sonic_basedon_testbed.yml
Summary:
SONiC currently does not support NTP long jump. In case there is a big difference between RTC and NTP server's time, the NTP service may long time to have system time synched with NTP server.
During deploy-mg, there are steps to force sync DUT's system time to NTP server. However, during tests, the DUT may be power-cycled. After power cycle, RTC time will be used as system time. In case the difference between RTC and NTP server is too big, the system time of DUT may be inaccurate because NTP long jump is not supported yet.
This change added a step to set system time to RTC after system time is force synched with NTP server during deploy minigraph.
With this change, the time difference between DUT and NTP server won't be too big after DUT is power-cycled.
=> Set the RTC from the system time after NTP sync during deploy-mg

tests/common/fixtures/duthost_utils.py, tests/ip/test_mgmt_ipv6_only.py
Summary:
For dualtor duts, we set up mux simulator on the servers,
but if the server doesn't have IPv6 addr, the mux simulator is unavailable,
Then y cable issue is reported, since the IPv6 test only focus on the mgmt plane,
we can ignore this error log
Fix the error when dualtor testbed runs into the mgmt IPv6 test module.
Ignore the error log.
Run on physical testbeds, and it passed.
=> Refine IPv6 conversion comment, enhance IPv6 test to ignore mux error

tests/conftest.py, tests/test_posttest.py
Summary:
In PR https://github.com/sonic-net/sonic-mgmt/pull/11993, dump file would be extracted in posttest, but the behavior of extract should not be included in a testcase
Rename and extract in elastictest
=> Revert changes of rename and extract dump file in posttest

tests/conftest.py, tests/test_posttest.py
Summary:
In PR https://github.com/sonic-net/sonic-mgmt/pull/12193, dump file would be extracted in posttest, but the behavior of extract should not be included in a testcase
Rename and extract in elastictest
=> Revert rename and extract dump in posttest in 202012

tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py
The PR is to fix `testQosSaiHeadroomPoolSize` on Mellanox T1 in dualtor deployment.
The test was failing because the 4 lossless pgs/queues are enabled on Mellanox-SN4600 T1 platform, but the test is still running in 2 lossless pgs/queues mode as `qos_dual_tor` option is set.
To workaroud, we checked the `tunnel_qos_remap` flag in the DUT, and enable 4 loss_less pgs/queues test on Mellanox T1 platform.  
Summary:
Fixes  `testQosSaiHeadroomPoolSize` on Mellanox T1 in dualtor deployment.
The PR is to fix `testQosSaiHeadroomPoolSize` on Mellanox T1 in dualtor deployment.
Check the `tunnel_qos_remap` flag in the DUT, and enable 4 loss_less pgs/queues test on Mellanox T1 platform.  
Verified on a physical testbed, with `tunnel_qos_remap` enabled.
```
collecting 3 items …
```
=> [202305] Fix testQosSaiHeadroomPoolSize on Mellanox T1 in dualtor deployment

tests/qos/qos_sai_base.py
Summary:
This function was removed due to a duplicate definition in 202205 branch. This duplicate was not present in the master branch. Due to this the only existing definition of the function in master got removed when I ported the diff from 202205 to master. This PR reintroduces the function skip_longlink in master.
- [] 202311
See description. This caused a single test failure.
=> Reintroduce skip_longlink.

tests/qos/files/qos_params.th.yaml
Summary:
testQosSaiPfcXonLimit case fail on "th" platform for t1-64-lag topology
Failed test log indicate cannot find out the actual dst port in phase of running get_rx_port(). as below,  flush on many port:
and the incorrect test ports are:
```
dst_port_2_id=16;
dst_port_3_id=20;
dst_port_id=0;
src_port_id=4;
```
compare with other working platform using same topology t1-64-lag:
the correct test ports are:
```
dst_port_2_id=53;
dst_port_3_id=54;
dst_port_id=52;
src_port_id=20;
```
assign correct test ports in "tests/qos/files/qos_params.th.yaml::qos_params::th::topo-t1-64-lag"
```
index da942b387..b4444527d 100644
--- a/tests/qos/files/qos_params.th.yaml
+++ b/tests/qos/files/qos_params.th.yaml
@@ -1,5 +1,260 @@
qos_params:
th:
+        topo-t1-64-lag:
+ …
```
=> assign correct test ports for th platflorm's t1-64-lag topology

tests/dhcp_relay/test_dhcp_relay.py
Summary: Fix dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default for dualtor.
Fixes # (issue): https://github.com/aristanetworks/sonic-qual.msft/issues/64
dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default  fails on dualtor/dualtor-aa
```
Expected Messages that are missing:
.dhcp_relay#dhcpmon[[0-9]+]: [\sAgg-Vlan1000\s*-[\sA-Za-z0-9]+\s*rx/tx] Discover: +0/ +0, Offer: +0/ +0, Request: +0/ +0, ACK: +0/ +0+
```
First issue is that packets go to unselected ToR in case of dualtor-aa which is being addressed by #11921.
Second issue is related to dualtor which is addressed in this pull request and is as follows -
The y-cable duplicates all the northbound traffic to both ToRs. The data plane traffic is dropped by the standby ToR through MUX-ACL, but the control plane traffic still ends …
=> Fix dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default for dualtor.

ansible/roles/test/vars/testcases.yml
Summary:
Add t1-28-lag topology for the ansible continuous_reboot test
Add t1-28-lag topology for the ansible continuous_reboot test
Add the topo to ansible/roles/test/vars/testcases.yml
Run test.
=> Add t1-28-lag topology for the ansible continuous_reboot test

tests/ip/test_mgmt_ipv6_only.py
ADO 27109592
Summary: Add ipv6 only mgmt TACACS test case
=> Add ipv6 only mgmt TACACS test case

tests/drop_packets/test_configurable_drop_counters.py
Summary:
Some test cases involving creating/deleting debug counters fail the log analyzer due to the below message:
```
ERR syncd#syncd: :- collectData: Failed to get stats of Port Debug Counter 0x100000001: -1
```
This is because there is a short transient period (1-2 sec) after the counter is deleted where the device is still trying to get the counter stats. Once the system becomes stable again the error messages stop.
See ADO 26161007
Add this message to the loganalyzer common ignore list
=> Ignore error messages when querying debug counter

tests/common/utilities.py, tests/conftest.py
In this PR, we provide a common function to connect DUT via paramiko
Summary:
=> Add a common function to connect DUT using paramiko.

tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py
Summary:
Regarding to 7050qx's  QoS SAI test for topo t0:
test port select result is as below:
testPortIds={0: {0:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]}};
and  1,2,3 are low speed breakout port. as below:
admin@bjw-can-7050qx-3:~$ show int st                                                                
Interface            Lanes    Speed    MTU    FEC         Alias            Vlan    Oper    Admin                                      Type    Asym PFC
--------------  ---------------  -------  -----  -----  ------------  --------------  ------  -------  ----------------------------------------  ----------
Ethernet0                9      10G   9100    N/A     Ethernet1          routed      up     down …
=> remove low speed port from test port list for breakout test scenario

tests/qos/test_pfc_pause.py
The PR is to fix `IndexError` in test case `test_no_pfc`.
The error is because the fixture `lossless_prio_dscp_map` always selects the first port in `PORT_QOS_MAP` table as the testing port, and selects the first profile in `DSCP_TO_TC_MAP` to get the DSCP to TC map. So on some particular topo, we saw the `IndexError` because the selected profile is not applied to the testing port.
```
>           traffic_params = {'dscp': dscp[0], 'dscp_bg': dscp_bg}
E           IndexError: list index out of range
```
This PR fixed the issue by checking the lossless priority and `lossless_prio_dscp_map` as well. The test case will be skipped if the extra lossless queue is not enabled on this port or the map `lossless_prio_dscp_map` for a particular priority is empty.
Summary:
Fixes `IndexError` in test …
=> Fix IndexError in test_no_pfc

tests/ip/test_mgmt_ipv6_only.py
configuration
Summary:
MSFT ADO: 26660281
Add test case to verify SNMP Over mgmt IPv6 with IPv6 only configuration.
Get SNMP result over mgmt IPv6 address and verify if the expected result is obtained for sysDescr OID.
Verified on 202305 OS version.
=> Add test case to verify snmp over mgmt IPv6 with ipv6 only config

ansible/plugins/action/current_password.py, ansible/plugins/connection/multi_passwd_ssh.py
Summary:
The multi_password_ssh plugin enhanced the ansible ssh plugin to support trying multiple passwords.
In case we need to know which password is used, some enhancement is required.
This change enhanced the multi_password_ssh plugin to store the hash of current password in its options. 
A new action plugin "current_password" is added to run a command module and try to get the stored hash 
of current password. The hash of current password will be added to the module's result.
Tested with playbook like below:
```
- hosts: sonic
gather_facts: no
tasks:
- name: Run command
action: current_password
args:
argv: ["whoami"]
```
=> [multi-password] Add action plugin to get the hash of currently used password

ansible/lab, ansible/veos_vtb, tests/common/devices/base.py, tests/ip/test_mgmt_ipv6_only.py, tests/ntp/test_ntp.py
Microsoft ADO 26660282
Summary:
Add support for testing NTP over IPv6. Additionally, test NTP when running with an IPv6-only network.
Also, this fixes the IPv6 address assignment for vlab-02 and makes sure it's given an address on the same subnet as the PTF container.
Tested on KVM and physical DUT with IPv6-only mgmt address.
=> Add IPv6-only test case for NTP

tests/saitests/py3/sai_qos_tests.py
Summary:
lossy queue failure on 7050cx dualtor
```
sai_qos_tests.LossyQueueTest ... dst_port_id: 1, src_port_id: 2 src_port_vlan: None
actual dst_port_id: 1
Compensate 31 packets to port 2, and retry 1 times
FAIL
FAIL: sai_qos_tests.LossyQueueTest
File \"saitests/py3/sai_qos_tests.py\", line 3639, in runTest
assert (xmit_counters[cntr] == xmit_counters_base[cntr])
AssertionError
Ran 1 test in 29.268s
FAILED (failures=1)",
```
RCA:
7050 support dynamically leakout compensation.
but still execute some manually leakout compensation …
=> fix 7050cx lossyqueue failure

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Skip `test_ssh_default_password.py `because the default password test is no longer appropriate after password rotation during the process of `deploy-mg` or `recover_by_console`. So that this test is unnecessary now. Skipping is acceptable.
=> Skip test_ssh_default_password.py due to password rotation

tests/common/utilities.py, tests/ip/test_mgmt_ipv6_only.py, tests/telemetry/conftest.py, tests/telemetry/test_events.py, tests/telemetry/test_telemetry.py
Summary:
Fixes # (issue) 26660292
Add testcase for telemetry using mgmt ipv6
Use ipv6 mgmt port for target ip with fixture to make dut ipv6 only
=> Add IPV6 only testcase for telemetry

tests/configlet/util/common.py
Summary: Skip comparison of two new fields that introduced by swss update
The swss introduce flap count and last flap time. The test fail because the two new fields mismatch. But these two fields are not affect the correctness of configlet test.  https://github.com/sonic-net/sonic-swss/pull/3052
Add two fields to skip val.
E2E test using the sonic-swss updated image.
02:31:34 helpers.log_msg                          L0060 INFO   | /var/src/sonic-mgmt-int/tests/configlet/util/common.py:359:02:31:34 patch_rm: compared dump state-db mismatch_cnt=0 msg=
02:31:34 helpers.log_msg                          L0060 INFO   | /var/src/sonic-mgmt-int/tests/configlet/util/common.py:385:02:31:34 patch_rm: generic_patch_rm_t0: Succeeded to compare
02:31:34 helpers.log_msg …
=> [tests/configlet] Update configlet test to align with swss update

tests/common/utilities.py, tests/ssh/test_ssh_limit.py, tests/tacacs/test_accounting.py, tests/tacacs/test_authorization.py
Fix the issue in `test_ssh_limit.py` due to password rotation
In this PR, we provide a public function connecting to device through paramiko. It can try either several potential passwords or a single password. We will use this new function to connect device. 
Summary:
Fix the issue in `test_ssh_limit.py` due to password rotation
In this PR, we provide a public function connecting to device through paramiko. It can try either several potential passwords or a single password. We will use this new function to connect device.
=> Fix the issue in `test_ssh_limit.py` due to password rotation

tests/common/fixtures/advanced_reboot.py, tests/platform_tests/args/advanced_reboot_args.py, tests/upgrade_path/test_upgrade_path.py, tests/upgrade_path/upgrade_helpers.py
Summary:
Currently, the upgrade path tests (of which there are two defined) only support a single warm upgrade. Also, there is duplicated code between the two test definitions, and doesn't include some checks that ideally should be done. This makes adding support for a double-upgrade test a bit harder.
In addition, there is duplicated code between the current update path code and internal upgrade scripts. This is because there are some pre/post upgrade checks/steps that need to be added, and the current code doesn't make it easy to extend it from another file.
Refactor the existing code to move the duplicated code into a helper function. Add support for running pre-upgrade and post-upgrade hooks (which are already provided in the `AdvancedReboot` class). Add checks for …
=> Refactor upgrade path tests

tests/tacacs/test_accounting.py
Ignore ansible log message when check TACACS accounting syslog.
Every ansible command will generate a syslog, when check TACACS accounting with sed command, the sed query will match the ansible log, this will make test case can't find regression. 
- Microsoft ADO: 25270078
Ignore ansible log message when check TACACS accounting syslog.
Fix TACACS accounting test case to prevent regression.
will updated with this PR image later.
- [] SONiC.master-16482.360728-2c8b4066f
Ignore ansible log message when check TACACS accounting syslog.
=> Ignore ansible log message when check TACACS accounting syslog.

tests/acl/templates/acltb_test_rules.j2, tests/acl/templates/acltb_test_rules_part_1.j2, tests/acl/templates/acltb_test_rules_part_2.j2, tests/acl/test_acl.py
Reverts sonic-net/sonic-mgmt#11892
This test uses acl templates at tests/acl/templates/acltb_test_rules.j2, this change adds “dualtor” in this template, test_techsupport.py does not have this “dualtor”, and then this test is broken.
=> Revert "ACL testcases in A/A setup need additional rules to ALLOW the ICMP keepalives to ensure both TORs don't go in STANDBY mode"

tests/common/utilities.py, tests/conftest.py
Summary:
Some testcases failed for ptf can't login ssh dut due to password rotation
Get dut current password and overwrite default one in creds
=> Fix ptf can't ssh dut issue due to password rotation

tests/common/fixtures/duthost_utils.py
1. Fix the ipv6 fixture to handle SNMP_AGENT_ADDRESS_CONFIG in config.
2. Revise the assert_addr_in_ifconfig to assert_addr_in_output to make it more reusable.
Summary:
Fix feature interaction issue between [sonic-net/SONiC#12010:https://github.com/sonic-net/SONiC/pull/12010] and [sonic-net/SONiC#17045:https://github.com/sonic-net/SONiC/pull/17045]
current convert_and_restore_config_db_to_ipv6_only() fixture - removes the IPv4 mgmt address, but the IPV4 mgmt address continues to be in SNMP_AGENT_ADDRESS_CONFIG table. Upon config reload when snmpd comes up, it sees ipv4 and ipv6 mgmt addresses in SNMP_AGENT_ADDRESS_CONFIG table and snmpd fails to come up as mgmt interface does not have ipv4 address assigned to the interface.
Fixture will check all IPs in the SNMP_AGENT_ADDRESS_CONFIG table …
=> [IPv6 only] Fix ipv6_only fixture to remove ipv4 from snmp agent address

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/vxlan/test_vxlan_bfd_tsa.py
Summary:
This PR addesthe tests for the feature added in 
https://github.com/sonic-net/sonic-swss/pull/2926
These tests set up vnet routes with multiple endpoints and BFD monitors and then apply TSA/TSB in differnet variations to test the behaviour. These tests ensure that while the device is ni TSA the BFD sessions are kept down.
=> tests for BFD session bringdown during TSA.

tests/platform_tests/cli/util.py
When using the TestbedProcessing script to generate the inventory files, the `skip_modules` variable under the `devices` section is ignored. We can instead use the `host_vars` section which adds the variable to the `host_vars/${host}.yml` file, but this file is ignored by InventoryManager, which the tests use to query the `skip_modules` variable.
This can be fixed by using VariableManager instead, which considers all sources of inventory, including the `host_vars` and `group_vars` directories.
With this change, the following config works:
```
host_vars:
cmp210:
skip_modules:
'line-cards': ['LINE-CARD3']
```
Tested by applying this patch during our internal sonic-mgmt runs and verifying that the requested skipped modules are actually skipped.
=> platform_tests: Use VariableManager for skip modules

tests/platform_tests/daemon/test_chassisd.py
Summary: Sort keys in data_dict in test_chassisd.py
The list of keys is taken unsorted from redis and is thus subject to potential re-ordering based on how the keys are inserted during chassisd startup. Ultimately it should not matter what order the keys are in as long as all are present, so sort the list so that we can compare them correctly.
I sorted the list of keys in data_dict that `collect_data` returns.
The sonic-mgmt suite was run multiple times with this patch applied and the test failure was not observed.
N/A
N/A
=> platform: daemon: chassisd: Sort keys in data_dict

tests/tacacs/test_authorization.py
Fix TACACS authorization test case random failure.
Fix TACACS authorization test case random failure.
- Microsoft ADO: 27322278
Test case test_stop_request_next_server_after_reject randomly failed with some test device.
This is because test case test_tacacs_authorization_wildcard doesn't not set TACACS authorization config back and test_stop_request_next_server_after_reject continue use it config. however on some test device the first test take too much time and make the ansible connection drop, and the TACACS authorization config blocked the ansible login again.
Reset TACACS authorization config to local after every test case.
Pass all test cases
=> [TACACS] Fix TACACS authorization test case random failure.

.azure-pipelines/testbed_health_check.py
[Fix] Catch no mgmt-ipv4 in testbed health check.
If a device lacks a management IPv4 address but has an enabled management IPv6, Ansible's reachability check may still pass. However, users will not be able to access the device using its management IPv4 address, potentially blocking certain tests. 
This PR introduces an extra check within the `testbed_health_check` script to detect the absence of a management IPv4 address. If a device does not have a management IPv4, it will be marked as Unhealthy to avoid confusion.
If a device lacks a management IPv4 address but has an enabled management IPv6, Ansible's reachability check may still pass. However, users will not be able to access the device using its management IPv4 address, potentially blocking certain tests. 
This PR introduces an …
=> [Fix] Catch no mgmt-ipv4 in testbed health check

tests/common/utilities.py, tests/conftest.py, tests/ssh/test_ssh_ciphers.py, tests/ssh/test_ssh_limit.py
This PR is a combination of #12253, #12255 and #12264
Summary:
This PR is a combination of #12253, #12255 and #12264
=> [202311] Fix issues due to password rotation

tests/common/utilities.py, tests/conftest.py, tests/ssh/test_ssh_ciphers.py, tests/ssh/test_ssh_limit.py
This PR is a combination of #12253, #12255 and #12264
Summary:
This PR is a combination of #12253, #12255 and #12264
=> [202205] Fix issues due to password rotation

tests/common/utilities.py, tests/conftest.py, tests/ssh/test_ssh_ciphers.py
This PR is a combination of #12253, #12255 and #12264
Summary:
This PR is a combination of #12253, #12255 and #12264
=> [202012] Fix issues due to password rotation

tests/common/platform/processes_utils.py
Summary:
For some testcase (e.g., `platform_tests/test_sequential_restart.py::test_restart_swss`), we cannot easily determine which process is exited when check critical process status failed. So I add log for exited critical process in common function `get_critical_processes_status`.
Add log for exited critical process in common function `get_critical_processes_status`
Add log for exited critical process in common function `get_critical_processes_status`
Verified by run testcase `platform_tests/test_sequential_restart.py::test_restart_swss` on physical testbed. I can see below message in the log file:
```
08/04/2024 08:23:44 processes_utils.get_critical_processes_s L0035 INFO   | The status of checking process in container 'swss' is: False
08/04/2024 08:23:44 …
```
=> Add log for exited critical process in common function `get_critical_processes_status`

ansible/roles/test/files/ptftests/device_connection.py, tests/arp/test_wr_arp.py, tests/common/fixtures/advanced_reboot.py, tests/vxlan/test_vxlan_decap.py
Summary:
Currently, DeviceConnection only accepts one alternate passwords. It's possible to have some scenario where multiple alternate passwords need to be present (such as multiple sources of images, or multiple environments).
Modify the class to use multiple alternate passwords. Also, modify the calling code to use sonic_default_passwords instead, which does have both of the default passwords that may be present in a SONiC image.
From the t0-sonic run, for testing warm reboot:
```
09/04/2024 01:35:26 base._run                                L0071 DEBUG  | /var/src/sonic-mgmt/tests/ptf_runner.py::ptf_runner#95: [ptf-01] AnsibleModule::shell, args=["/root/env-python3/bin/ptf --test-dir ptftests/py3 advanced-reboot.ReloadTest --platform-dir ptftests --qlen=1000 --platform …
```
=> Modify DeviceConnection to accept multiple passwords

ansible/ansible.cfg
Summary:
Some test cases use `ptf_runner` to run a script on the PTF container and then get the results. Those scripts may take an extended amount of time to run, and may also have no output generated for some time. This means that there would be no packets sent by either side during this time.
Depending on the network setup, if there is some NAT happening or some firewall configuration between the sonic-mgmt container and the PTF container, that extended period of time with no output may result in NAT/firewall thinking the connection has been dropped/closed, removing the connection entry, and thus causing packets from the PTF back to the sonic-mgmt container to get dropped. (Our internal lab connectivity is one such setup.)
To fix this, in ansible.cfg, enable SSH …
=> Enable SSH keep-alive when connecting via Ansible

docs/testbed/README.testbed.Overview.md
- Testbed configuration for `t1-lag` mentions number of T2 VM instances as 16 while the actual value must have been 8.
Summary:
Fix a minor error in the README documentation.
Fix typo.
Not applicable
Not applicable.
Not applicable.
Updated README.
=> [docs/testbed]: Fix typo in VM instances

ansible/plugins/connection/switch.py
Summary:
27364287
Case failed with error message "msg": "Establish connection to server failed after tried 3 times."
Ansible uses the option "'ControlPersist=60s'" for SSH connection, it would allow the master connection to remain open after the initial SSH session has been established. This option helps to speed up subsequent SSH connections to the same host by reusing the existing connection. 
But in the current script, the code always waits for the '[Pp]assword:' prompt, causing a timeout in passwordless login.
Break if the prompt is " '>', '#'" to handle the passwordless logdin
Run the original case.
=> Enhance the "switch" connection plugin to hand Passwordless Login

tests/dhcp_relay/test_dhcp_relay.py
Reverts sonic-net/sonic-mgmt#12074
The standby ToR should have no counter increase:
https://github.com/sonic-net/sonic-dhcpmon/blob/22a7467a8ab3e26c3d20e959a0702380f0d4b5ae/src/dhcp_device.cpp#L315-L320
```
dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default[dual] PASSED                                                                                                                                                                                                    [100%]
```
=> Revert "Fix dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default for dualtor."

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
27318019
test_snmp_loopback Not supported topology backend
Skip the case on backend device
Run the case
=> Skip test_snmp_loopback on backend device, it not supported topology backend

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
As part of T2-VS Support changes(https://github.com/sonic-net/sonic-buildimage/pull/18512), sonic_platform package will be available now on VS platforms. 
sfputil script was getting exited earlier due to module not found. But now, the module will be found, and next it invokes load_platform_chassis(). For non-chassis VS platforms, the metadata file will not be present, and hence it throws an exception with a syslog.
ERR sfputil: Failed to instantiate Chassis due to FileNotFoundError('Metadata file /etc/sonic/vs_chassis_metadata.json not found')
The sonic-mgmt tests on VS which invoke sfputil commands are failing with loganalyzer caching this message.
Fix: Adding the above to loganalyzer ignore messages. 
As part of T2-VS Support changes, sonic_platform package will be available …
=> T2-VOQ-VS: Add command to loganalyzer ignore

tests/qos/qos_sai_base.py
Summary: Port indexing error was occurring on backend T0 devices since the test port IDs (based off of regular VLAN ports) are set before the port IPs which are vlan subinterfaces. Therefore, the port IDs need to be updated after the appropriate port IPs are set.
bugfix for qos sai backend t0 test
update the correct port IDs to match port IPs
tested on backend + frontend testbed
=> [Bugfix][QoS] Add port index fix for t0 backend

tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py
…leshooting capability
Summary:
consistently hit LossyQueueVoq failure on cisco platform
```
dst_port_id=0;
dst_port_ip="10.0.0.33";     >>>>> wrong ptf parameter: dst port id 0's IP is 10.0.0.1 instead of 10.0.0.33
... omitted ...
src_port_id=4;
src_port_ip="10.0.0.5";
... omitted ... 
uplink_port_ids=[0, 4, 16, 20];
downlink_port_ids=[34, 36, 37, 38, 39, 42, 44, 45, 46, 47, 50, 52, 53, 54, 55, 58, 60, 61, 62, 63];
... omitted ...
testPortIps={0: {0: {
0: {"peer_addr": "10.0.0.1"},    >>>>> here, dutconfig's parameter is correct instead.
4: {"peer_addr": "10.0.0.5"}, 
16: {"peer_addr": "10.0.0.9"}, 
20: {"peer_addr": "10.0.0.13"}, 
34: {"peer_addr": "10.0.0.33"}, 
... omitted ...
```
```
... omittd ....
dst_port_id=0;
dst_port_ip="10.0.0.1";
... omitted ...
src_port_id=4; …
```
=> fix cisco lossyQueueVoq failure

tests/platform_tests/test_sequential_restart.py
Summary:
On Celestica-E1031 platform, issue `sudo systemctl restart swss` sometimes cause orchagent process exited with below error:
```
Apr  8 08:21:54.574827 e1031-1 NOTICE swss#orchagent: :- allocateNewSwitchObjectId: created SWITCH VID oid:0x21000000000000 for hwinfo: ''
Apr  8 08:22:54.655366 e1031-1 ERR swss#orchagent: :- wait: SELECT operation result: TIMEOUT on getresponse
Apr  8 08:22:54.655843 e1031-1 ERR swss#orchagent: :- wait: failed to get response for getresponse
Apr  8 08:22:54.659878 e1031-1 ERR swss#orchagent: :- create: create status: SAI_STATUS_FAILURE
Apr  8 08:22:54.666990 e1031-1 ERR swss#orchagent: :- main: Failed to create a switch, rv:-1
Apr  8 08:22:57.939530 e1031-1 INFO swss#supervisord 2024-04-08 08:22:57,929 INFO exited: orchagent (terminated by SIGABRT …
```
=> [E1031] Update the command for restart swss/syncd container in testcase

tests/voq/test_voq_chassis_app_db_consistency.py
Fix the test fail with NoneType in test_voq_chassis_app_db_consistency. This test used to fail with error 
```
/azp/_work/8/s/tests/common/helpers/sonic_db.py::dump#169: [svcstr-xxxx-sup-1] AnsibleModule::command, args=["sonic-db-dump -n CHASSIS_APP_DB -y -k *SYSTEM_LAG_ID_SET*"], kwargs={}
12/01/2024 21:22:18 base._run                                L0082 DEBUG  | /azp/_work/8/s/tests/common/helpers/sonic_db.py::dump#169: [svcstr-xxxx-sup-1] AnsibleModule::command Result => {"stderr_lines": [], "cmd": ["sonic-db-dump", "-n", "CHASSIS_APP_DB", "-y", "-k", "*SYSTEM_LAG_ID_SET*"], "end": "2024-01-12 21:22:19.633679", "_ansible_no_log": false, "stdout": "{\n  \"SYSTEM_LAG_ID_SET\": {\n    \"expireat\": 1705094539.5715408,\n    \"ttl\": -0.001,\n    \"type\": \"set\",\n    \"value\": [\n …
```
=> Fix the test fail with NoneType in test_voq_chassis_app_db_consistency

tests/bgp/test_bgpmon_v6.py
Update bgpmon test for t2 to be able to run on any Linecard. Currently it can be run only on uplink linecard connected to T3 devices
Summary:
Update bgpmon test for t2 to be able to run on any Linecard. Currently it can be run only on uplink linecard connected to T3 devices
The following changes are made
1. Added a new API get_all_uplink_ptf_recv_ports() which will get the ptf interfaces and the corresponding local dut port interfaces where the T3 neighbors are connected to
2. Add a new API get_uplink_route_mac() to get the router mac based on the interface. In case of multi-asic device the router-macs's could be different between asics
3. Based on the recv_ptf port, get the corresponding local dut port using local_ports[rcvd_port_index]
4. Use this router mac to configure …
=> Update bgpmon test for t2 to be able to run on any Linecard

tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Summary:
Fixes snmp_pdu_controller cannot handle secrets vars in snmp_rwcommunity
snmp_pdu_controller cannot handle SNMP rwcommunity is stored as secrets vars.
Use jinja2 to render snmp secret if it is a secret vars.
Test with physical testbed with following cases:
platform_tests/test_power_off_reboot.py::test_power_off_reboot
```
05:41:07 reboot.check_reboot_cause_history        L0435 INFO   | index:  4, reboot cause: Power Loss, reboot cause from DUT: Power Loss
05:41:07 reboot.check_reboot_cause_history        L0435 INFO   | index:  5, reboot cause: Power Loss, reboot cause from DUT: Power Loss
05:41:07 reboot.check_reboot_cause_history        L0435 INFO   | index:  6, reboot cause: Power Loss, reboot cause from DUT: Power Loss
05:41:07 reboot.check_reboot_cause_history        L0435 …
```
=> Fix snmp_pdu_controller cannot handle secrets vars in snmp_rwcommunity

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
6100 T1's headroom pool test fail
For 6100, T0 and T1 have same buffer configuration, and T1's failure is related to lag keepalive.
xfail test for 6100's T1 topology.
and 6100's headroom pool test is covered by T0.
set xfail for 6100 T1's headroom pool testcase
=> skip headroom pool test for Force10-S6100 T1 topo

tests/common/dualtor/mux_simulator_control.py
Summary:
Improve the toggle fixture check by validate toggle outcome on both ToRs.
Validate the ports are all in standby on the peer side.
```
dualtor_io/test_normal_op.py::test_normal_op_upstream[active-standby] PASSED                                                                                                                                                                                           [ 50%]
dualtor_io/test_normal_op.py::test_normal_op_upstream[active-active] SKIPPED (Skip as no mux ports of 'active-active' cable type)
```
=> [dualtor][active-standby] Improve the toggle by checking on both sides

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
There was an extra space left as part of PR https://github.com/sonic-net/sonic-mgmt/pull/12345. Fixed that
Summary:
As part of T2-VS Support changes, sonic_platform package will be available now on VS platforms. 
sfputil script was getting exited earlier due to module not found. But now, the module will be found, and next it invokes load_platform_chassis(). For non-chassis VS platforms, the metadata file will not be present, and hence it throws an exception with a syslog.
ERR sfputil: Failed to instantiate Chassis due to FileNotFoundError('Metadata file /etc/sonic/vs_chassis_metadata.json not found')
=> Fix extra space issue in loganalyzer regex

ansible/lab, ansible/veos_vtb, tests/common/devices/base.py, tests/ip/test_mgmt_ipv6_only.py, tests/ntp/test_ntp.py
Backport of #12258
Summary:
Add support for testing NTP over IPv6. Additionally, test NTP when running with an IPv6-only network.
Also, this fixes the IPv6 address assignment for vlab-02 and makes sure it's given an address on the same subnet as the PTF container.
Tested on KVM and physical DUT with IPv6-only mgmt address.
=> [202305] Add IPv6-only test case for NTP (#12258)

tests/bgp/test_traffic_shift_sup.py
bgp/test_traffic_shift_sup.py harcoded for admin user, does not work for non admin sonic_admin_user
client.expect(["admin@{}'s password:".format(self.dutip)]) <<<<< hardcoded as admin
client.sendline(self.dutpass)
client.expect("admin*") <<<<< hardcoded as admin
client.sendline(cmd)
client.expect("Password .*")
client.sendline(self.dutpass)
Summary:
Fixes # 12195
Fix is to use sonic_admin_user creds in expect expression match.
Fix is failing sonic-mgmt tests where user is not admin.
Ran sonic-mgmt test  bgp/test_traffic_shift_sup.py  to validate
No
N/A
=> fixing bgp/test_traffic_shift_sup.py harcoded for admin user. issue#12195

ansible/testbed_add_vm_topology.yml, ansible/testbed_connect_topo.yml, ansible/testbed_connect_vms.yml, ansible/testbed_disconnect_vms.yml, ansible/testbed_remove_vm_topology.yml, ansible/testbed_renumber_vm_topology.yml
Summary:
In ansible's conditional statements, jinja2 templating delimiters should not be used. Otherwise ansible will give warnings.
This fix removed the jinja2 templating delimiters to avoid warnings.
Test run the updated playbooks.
=> Fix jinja2 templating delimiters in ansible conditional statements

ansible/roles/fanout/tasks/rootfanout_connect.yml
Summary:
The task for changing root fanout port vlan must be executed over "switch" connection instead of other ansible connection plugins.
However, when we set "ansible_connection" variable to "multi_passwd_ssh" for lab server, somehow the "connection: switch" for the "Change root fanout port vlan" task is not working. Consequently this task is not executed over the "switch" connection plugin and fails.
To workaround this issue, we can explicitly set "ansible_connection" variable to "switch" in previous steps. This will force the subsequent tasks to use the "switch" connection plugin.
Tested add-topo/remove-topo.
=> Force root fanout task to use connection "switch"

tests/vlan/test_vlan_ping.py
Summary:
Make test_vlan_ping stable
test_vlan_ping is not stable due to ptf not receiving packet.
Change from receiving packet for 5 times to receiving packet for 1 time.
Run with t0-8111 physical testbed.
```
03:41:22 conftest.rand_one_dut_hostname           L0393 INFO   | Randomly select dut str3-8111-04 for testing
03:41:22 __init__._fixture_generator_decorator    L0081 INFO   | -------------------- fixture vlan_ping_setup setup starts --------------------
03:41:22 facts_cache.read                         L0092 INFO   | Load cache file "/var/src/sonic-mgmt-int/tests/_cache/str3-8111-04/mg_facts.pickle" failed with exception: FileNotFoundError(2, 'No such file or directory')
03:41:23 facts_cache.write                        L0120 INFO   | Cached facts "str3-8111-04.mg_facts" to …
```
=> Make test_vlan_ping stable

tests/pc/test_po_cleanup.py
Summary:
For test_po_cleanup and test_po_cleanup_after_reload, do a safe reload and wait for BGP to come up. This makes sure that the next test case that runs gets the testbed in a good, stable state.
This is particularly needed on slow-CPU devices where a proper config reload will take some time to run.
Verified that two runs of `pc/test_po_cleanup.py` on MSN2700 passed. This doesn't necessarily guarantee it won't ever fail because of this error, though, since it seems to be somewhat flaky.
=> [test_po_cleanup] Do a safe config reload

tests/tacacs/conftest.py, tests/tacacs/test_ro_disk.py, tests/tacacs/utils.py
Improve IPV6 debug information for debug reachability issue.
Cherry-pick PR https://github.com/sonic-net/sonic-mgmt/pull/12426
Why I did it
There are random IPV6 ptfhost address unreachable issue, need add debug information for investigation.
Work item tracking
Microsoft ADO: 26544335
How I did it
Improve IPV6 debug information for debug reachability issue.
How to verify it
Summary:
=> [202305] Improve IPV6 debug information for debug reachability issue (#12426)

tests/arp/test_neighbor_mac.py, tests/generic_config_updater/test_bgp_prefix.py, tests/platform_tests/test_cpu_memory_usage.py, tests/test_vs_chassis_setup.py
In our pytest, it's crucial to have proper markers for different test topologies to ensure that tests are run in the correct testbeds. It seems that some modules, despite having passed the PR tests, lack the necessary topology markers. In this PR, we add the missing markers, which will enhance the clarity and efficiency of the testing process and ensure that each module is tested on the appropriate testbeds. 
Summary:
In our pytest, it's crucial to have proper markers for different test topologies to ensure that tests are run in the correct testbeds. It seems that some modules, despite having passed the PR tests, lack the necessary topology markers. In this PR, we add the missing markers, which will enhance the clarity and efficiency of the testing process and ensure that …
=> Add topology mark in the module already in PR test

.azure-pipelines/recover_testbed/dut_connection.py, .azure-pipelines/recover_testbed/recover_testbed.py, .azure-pipelines/recover_testbed/testbed_status.py, ansible/devutil/devices/ansible_hosts.py, ansible/devutil/inv_helpers.py, ansible/files/sonic_lab_console_links.csv
In this PR, we streamlined the process of retrieving console usernames by consolidating the source to a single location: the group vars. This change simplifies our codebase and enhances maintainability. The field 'proxy'  in console link CSV under the ansible/files folder is no longer in use for this purpose.
Summary:
In this PR, we streamlined the process of retrieving console usernames by consolidating the source to a single location: the group vars. This change simplifies our codebase and enhances maintainability. The field 'proxy'  in console link CSV under the ansible/files folder is no longer in use for this purpose.
Streamlined the process of retrieving console usernames by consolidating the source to a single location: the group vars.
=> Unify console access to use account from group vars

ansible/TestbedProcessing.py
Summary:
Fixes deprecation of yaml.load. In python3 yaml.load is deprecated and requires a new Loader parameter. In python2 this script was able to run and just printed a deprecation warning.
Fix is to switch to use yaml.safe_load.
In python3 yaml.load is deprecated and requires a new Loader parameter. In python2 this script was able to run and just printed a deprecation warning.
Fix is to switch to use yaml.safe_load.
Ran full test runs internally with this fix applied
NA
NA
=> sonic-mgmt: Use yaml.safe_load

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
test_route_flap will fail on the  t0-56-po2vlan and dualtor-64 topology, need to skip it based on the github test issue radv.test_radv_ipv6_ra#test_unsolicited_router_advertisement_with_m_flag and radv.test_radv_ipv6_ra#test_solicited_router_advertisement_with_m_flag will fail on the dualtor-64 topology due to the github test issue
Skip the tests before the test issue resolved.
Summary:
The test should be skipped on the relavent topology
=> Add skip for route flap and radv test for some topology

tests/bgp/test_bgp_update_timer.py
Summary:
The test uses the time in sonic-mgmt container as the base time and calculate the bgp withdraw interval against the bgp update packet timestamp which is got from the switch, there are 2 issues in this logic:
1.  There could be time drift in dut or test server.
2.  The time consumed by the ansible path is not calculated. 
To fix this, we can take the end time(which is the ansible command end time form dut) in ansible result as the base time.
Fix test issue in test_bgp_update_timer_session_down
Take the end time(which is the ansible command end time form dut) in ansible result as the base time.
Run the test on multiple testbeds, all passed.
=> Fix test issue in test_bgp_update_timer_session_down

tests/bgp/test_bgp_update_timer.py
Summary:
Increase the check threshold in test_bgp_update_time
- [] Bug fix
The change is to increase the check threshold, because our tests randomly failed with measurements like 2.1 and the original value looks to be arbitrary set in https://github.com/sonic-net/sonic-mgmt/pull/7907
Increase the threshold from 2 to 2.5
The test can reliably pass after the change
Arista 7260
=> Fix test_bgp_update_time by increasing threshold

tests/acl/test_acl.py
Summary:
Acl test support for t1-28-lag
In the t1-28-lag topo, the downstream links are physical ports, the upstream links are portchannels.
Need this change to add the links to the acl_table_ports.
To support acl test on t1-28-lag topology.
Add "t1-28-lag" to the tuple.
Run the test
=> Acl test support for t1-28-lag

tests/platform_tests/fwutil/fwutil_common.py
In fwutil tests, it will always revert the component version to the version at index 0, 
since this index is expected to be the latest version.
This is based on the assumption that the firmware.json file is maintained with the same structure.
The JSON file will list 2 versions per FW component (i.e, ONIE/BIOS/CPLD),
The 2 versions are always listed in the same order which is:
1. The first version is the newer version
2. The second version is the older version
Summary:
1. Giving index 0 a meaningful name will help the user better understand the JSON structure and test flow
2. Help debug and avoid file errors
3. better coding practice since we remove the use of magic numbers.
1. Giving index 0 a meaningful name will help the user better understand the JSON structure and test flow
2. Help …
=> update component version index in fwutil common

tests/saitests/py3/sai_qos_tests.py
Without this PR the Qos tests would fail on testQosSaiPfcXonLimit, because step 1 of the tests, which disable TX for dst_port_id, dst_port_2_id, dst_port_3_id is getting incorrect DST ports
Test was broken by: https://github.com/sonic-net/sonic-mgmt/pull/9780
With my fix:
step 1: disable TX for dst_port_id, dst_port_2_id, dst_port_3_id
[dst_port_id, dst_port_2_id, dst_port_3_id] = [1, 3, 4]
Without my fix:
step 1: disable TX for dst_port_id, dst_port_2_id, dst_port_3_id
[dst_port_id, dst_port_2_id, dst_port_3_id] = [1, 1, 1]
Run the tests to find the root cause of the failure
Run the tests with my fix to see that the tests are passing 
tests only failed on SN2700 with t0 topology
and SN4700 with t0-56-o8v48/t1-28-lag
=> Fix Qos Xon Test

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Added new skips to tests/common/plugins/conditional_mark/tests_mark_conditions.yaml.
Add new skips to .yml file.
=> [Mellanox] Skip LPM and SFP reset in Nvidia Bluefield platform

tests/qos/test_qos_sai.py
Summary:
This ignore is due to https://github.com/sonic-net/sonic-buildimage/issues/13265.
LLDP related errors should be ignored because LLDP is disabled in the qos sai test.
Add an error to ignore in qos test to avoid loganalyzer failures.
Add ".*ERR lldp#lldpmgrd.*Command failed.*lldpcli.*configure.*ports.*unable to connect to socket.*" to the ignore_regex.
Run test on multiple testbeds, all passed.
=> [Qos] Add an error to ignore in qos test

tests/common/helpers/enable-dynamic-buffer.py
The reason why dynamic buffers are not enabled on **ACS-SN**5600 is because on deploy minigraph, the script that enables dynamic buffers, has this condition:
if 'ACS-MSN' not in metadata['hwsku']:
print("Don't enable dynamic buffer calculation for non-default SKUs")
exit(0)
Instead, it should be this condition:
if 'ACS-MSN' not in metadata['hwsku'] and '**ACS-SN**' not in metadata['hwsku']:
Summary:
For generic SKUs, we always use dynamic buffer model
fixed the condition and tested dynamic buffer model enabled on ACS-SN5600 hwsku
run deploy with the change
ACS-SN5600
no
=> Update script to enable dynamic buffer on all generic SKU

tests/qos/files/qos_params.spc3.yaml
Update qos_params.spc3.yaml to support 400000_40m for dualtor pcbb xoff test on Nvidia platform
Summary:
Support 400000_40m for dualtor pcbb xoff test on Nvidia platform
Compute and set proper values for 400000_40m 
Add coverage for x86_64-mlnx_msn4700-r0
=> [Mellanox] Update qos_params.spc3.yaml to support 400000_40m for dualtor pcbb xoff test on Nvidia platform

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
This PR is to skip service warm restart test on Mellanox platform as it's not required.
This PR is to skip service warm restart test on Mellanox platform as it's not required.
Update `tests_mark_conditions_platform_tests.yaml`
The change is verified by yaml file syntax check.
Mellanox platform specific.
=> [cherry-pick] [202311]Skip service warm restart test on Mellanox platform

tests/snmp/test_snmp_queue_counters.py
This test is checking that buffer queue counters inside snmp docker are inline when using create_only_config_db_counters optimization.
Summary:
Accompanies "Fix SNMP dropping some of the queue counter when create_only_config_db_buffers is set to true" (https://github.com/sonic-net/sonic-snmpagent/pull/303) which fixes the issue: "The feature "polling only configured ports buffer queue" will break SNMP" (https://github.com/sonic-net/sonic-buildimage/issues/17448).
To enhance the bug fix mentioned above, solving an issue with buffer queue counters optimization.
- Set "create_only_config_db_buffers" to true in config db, to create only relevant counters
- Remove one of the buffer queues, Ethernet0|3-4 is chosen arbitrary
- Using snmpwalk compare number of queue counters on Ethernet0, …
=> Test polling only configured buffer queue counters

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
warmboot on dualtor is currently broken, before the feature is fixed, skipping the test case for now. 
```
SKIPPED [1] platform_tests/test_reboot.py: Warm reboot is broken on dualtor topology. Skipping for now.
======================== 1 skipped, 1 warning in 48.85s ========================
```
=> [dualtor][warmboot] skip `test_reboot.py` warmboot case on dualtor

ansible/roles/test/files/ptftests/py3/vxlan-decap.py
Introduce one sec delay between vxlan decap test iterations.
Summary:
In some testbed topologies like t0-116 where vxlan_decap test validate decap across all the ports, test fails for some ports. To avoid the failure, adding a second delay between vxlan decap test iterations.
Improvement of current test.
Improving the current test by adding a one second delay between vxlan decap test iterations.
Validated on t0-116
=> Introduce delay in vxlan-decap tests

.azure-pipelines/pr_test_scripts.yaml
Summary:
Elastictest performs well in distribute running PR test in multiple KVMs, which support us to add more test scripts to PR checker
Add 16 data plane test to T0 PR checker and sort from A to Z
=> Add 16 data plane test to T0 PR checker

tests/platform_tests/cli/test_show_platform.py
This patch adds a 60-second window to the psustatus tests to allow time for the relevant daemons to reach the RUNNING state, should they be found in the STARTING state when the daemon status check occurs.
Summary:
Encountered an instance where the psustatus tests failed because the pmon daemon status check caught the applicable daemons in the STARTING state as opposed to the RUNNING state. This was seen one time; despite a few dozen attempts, have not been able to recreate the issue. This change will help guard against such potential race conditions.
Added a 60 second wait (5 second interval, 0 delay) on `check_pmon_daemon_status` in each of the psustatus tests.
Ran the tests with the fixes applied and they passed.
=> [platform][cli] PSU Status Tests: Permit Daemons Some Time to enter RUNNING State

tests/macsec/test_fault_handling.py
Summary:
Fixes # (issue) 27459603
There is a flaky failure on the macsec_test_fault_handling. It's due to the lag of DUT exceeding MKA_TIMEOUT that triggers a rekey.
To mitigate this, retry the test after a while with a few seconds of idle time.
Check Azp
=> [macsec]: Add a sleep at the link flap retry for the flaky failure

tests/qos/qos_sai_base.py
Summary: Backport #12334 to 202311
Regression introduced by https://github.com/sonic-net/sonic-mgmt/pull/12088
`qos/test_qos_sai.py` fails with the following traceback -
```
14:44:01 __init__._fixture_generator_decorator    L0088 ERROR  | 
KeyError('peer_addr_ipv6')
File "/var/src/sonic-mgmt_vms21-t0-2700_646f1402735219c3e5444094/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
res = next(it)
File "/var/src/sonic-mgmt_vms21-t0-2700_646f1402735219c3e5444094/tests/qos/qos_sai_base.py", line 1089, in dutConfig
testPorts = self.__buildTestPorts(request, testPortIds, testPortIps,
File "/var/src/sonic-mgmt_vms21-t0-2700_646f1402735219c3e5444094/tests/qos/qos_sai_base.py", line 766, in …
```
=> Backport PR12334 to 202311

tests/stress/test_stress_routes.py
* In dual TOR testbeds, loganalyzer analyzes both DUTs for errors, so errors need to be ignored on both or else it can cause tests to error out.
* Fix regex expression for routeCheck failures as the current regex still doesn't ignore loganalyzer failures
Summary:
Fix log analyzer errors on dualtor testbeds
By making sure loganalyzer ignore_regex is ignored for all DUTs in duthosts
By running the test locally and via nightly test pipeline
=> [tests/stress]: Fix loganalyzer checks for stress test

tests/common/platform/device_utils.py, tests/platform_tests/cli/test_show_platform.py
Summary:
Test cases `test_show_platform.py::test_show_platform_psustatus` and `test_show_platform.py::test_show_platform_psustatus_json` are expecting PSU LED state to be red/green/amber/off even if PSU is not present. Fix is required to expect “N/A” also which is appropriate if PSU is not present.
Verified with running the testcases in the case of PSUs not present on certain locations. 
```
$ show plat psustatus
PSU    Model            Serial       HW Rev    Voltage (V)    Current (A)    Power (W)    Status       LED
-----  ---------------  -----------  --------  -------------  -------------  -----------  -----------  -----
PSU 1  PSU6.3KW-20A-HV  DTM25030246  1.0       54.582         15.259         834.008      OK           green
PSU 2  PSU6.3KW-20A-HV  DTM245200J4  1.0       54.426 …
```
=> test_show_platform.py: match 'N/A' for led_status in show platform psustatus

.azure-pipelines/pr_test_scripts.yaml
Due to the image change [#16957](https://github.com/sonic-net/sonic-buildimage/pull/16957), it will cause failure of gnmi cases. And it will block all the test stage of buildimage. So remove the cases under the folder `gnmi` temporarily to unblock the pipeline. After fixing the issue caused by  [#16957](https://github.com/sonic-net/sonic-buildimage/pull/16957), we will add the test cases back. 
Summary:
Due to the image change [#16957](https://github.com/sonic-net/sonic-buildimage/pull/16957), it will cause failure of gnmi cases. And it will block all the test stage of buildimage. So remove the cases under the folder `gnmi` temporarily to unblock the pipeline. After fixing the issue caused by  [#16957](https://github.com/sonic-net/sonic-buildimage/pull/16957), we will add …
=> Remove gnmi cases temporarily in PR test.

tests/ip/test_mgmt_ipv6_only.py
Summary:
Microsoft ADO 27674068
Somehow, the import for `setup_ntp` got missed. Add it in.
Verified on physical device
=> Fix IPv6 NTP test case missing an import

tests/tacacs/test_authorization.py
Fix TACACS authorization test case random failure.
Fix TACACS authorization test case random failure.
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/12256 from master branch.
- Microsoft ADO: 27322278
Test case test_stop_request_next_server_after_reject randomly failed with some test device.
This is because test case test_tacacs_authorization_wildcard doesn't not set TACACS authorization config back and test_stop_request_next_server_after_reject continue use it config. however on some test device the first test take too much time and make the ansible connection drop, and the TACACS authorization config blocked the ansible login again.
Reset TACACS authorization config to local after every test case.
Pass all test cases
=> [202305] [TACACS] Fix TACACS authorization test case random failure.

tests/platform_tests/test_auto_negotiation.py
Added support for port speed config with reboot
Summary:
- Change the interface speed to 40G and do config reload
- Verify the  speed should be configured and  no crash.
Added new testcase
The motivation for this PR is to verify device behaviour on reboot  with 40G port speed.
Automated new testcase "test_verify_portspeed_configuration_across_reboot"  in script 
platform_tests/test_auto_negotiation.py
deployed T0 topology
./run_tests.sh -n vms-sn2700-t0 -d <device name> -c platform_tests/test_auto_negotiation.py::test_verify_portspeed_configuration_across_reboot
-t t0,any -i ../ansible/inventory -l info -u -e --skip_sanity
any
=>  test_auto_negotiation.py: Added test coverage for port speed change with reboot.

tests/common/utilities.py, tests/ip/test_mgmt_ipv6_only.py, tests/telemetry/conftest.py, tests/telemetry/test_events.py, tests/telemetry/test_telemetry.py
Add testcase for telemetry using mgmt ipv6
Use ipv6 mgmt port for target ip with fixture to make dut ipv6 only
Summary:
Fixes # (issue) Fixes # (issue) 26660292
=> Add IPV6 only testcase for telemetry (#12268)

ansible/library/reduce_and_add_sonic_images.py
When the image path is not url, it will fail to download image. need to support the save_as as previously 
Summary: When the image path is not url, it will fail to download image. need to support the save_as as previously 
if the image is downloaded already before run the reduce_and_add_sonic_images.py, use the downloaded image. 
After the fix, run the test case with image path specified as not url format, test could pass
=> [upgrade test]Fix issues when the image path is not url

tests/platform_tests/sfp/test_show_intf_xcvr.py, tests/platform_tests/sfp/util.py, tests/show_techsupport/tech_support_cmds.py
ading show command "show interface transceiver lpmode"
Summary:
Added New cli  "show interface transceiver lpmode" in  tech_support_cmds.py
Added New cli  "show interface transceiver lpmode" in  tech_support_cmds.py
Verified on new to topology
=> test_show_intf_xcvr.py: Added command "show interface transceiver lpmode"  

tests/snappi_tests/lacp/files/lacp_dut_helper.py, tests/snappi_tests/lacp/files/lacp_physical_helper.py
Summary: Providing fix for AttributeError: 'LagPort' object has no attribute 'protocol' since snappi-convergence verison has been upgraded
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/12262
Providing fix for AttributeError: 'LagPort' object has no attribute 'protocol' since snappi-convergence verison has been upgraded
Modified the protocol attribute to be added to lag config object
Tested on Arista dut
=> Fixing AttributeError: 'LagPort' object has no attribute 'protocol'

.azure-pipelines/pr_test_scripts.yaml, tests/platform_tests/sfp/util.py
The module `test_sfpshow.py` will fail on kvm testbed because of the failure 
```
File "/var/src/sonic-mgmt/tests/platform_tests/sfp/util.py", line 36, in get_dev_conn
dev_conn = conn_graph_facts["device_conn"][duthost.hostname]
KeyError: 'vlab-01'
```
In this PR, we fix this issue, and add it into PR test. 
Summary:
The module `test_sfpshow.py` will fail on kvm testbed because of the failure 
```
File "/var/src/sonic-mgmt/tests/platform_tests/sfp/util.py", line 36, in get_dev_conn
dev_conn = conn_graph_facts["device_conn"][duthost.hostname]
KeyError: 'vlab-01'
```
In this PR, we fix this issue, and add it into PR test. 
Use method `get` to get the value from a python dict. And set it `{}` if there is no such key.
=> Fix the module `test_sfpshow.py` and add it in PR test. 

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/voq/test_voq_fabric_isolation.py
Summary: Add a management test for fabric link monitoring infrastructure.
This PR adds a test for the fabric link monitoring infrastructure, the main PR is at https://github.com/sonic-net/sonic-swss/pull/2988
=> Add test for fabric link monitoring structure.

tests/generic_config_updater/templates/create_secondary_forward_rules.j2, tests/generic_config_updater/test_dynamic_acl.py
Summary:
Changes test_gcu_acl_forward_rule_replacement to separate the replacement operation into two separate delete and add operations.  This is to address test failures caused by a SONiC OS bug that floods error logs after a ACL rule is directly replaced in configDB, despite ACL functionality working as intended - https://github.com/sonic-net/sonic-buildimage/issues/18719
Test working on testbed that it previously failed on:
Temporarily fix test case to get rid of errors in nightly testing suite pending bug fix in SONiC OS
Changed the replace operation into two separate delete and add operations
Tested it on a testbed that had previously been failing
=> Temporary fix for Dynamic ACL via GCU ACL rule replacement test

tests/common/helpers/gnmi_utils.py
`generate_telemetry_config()` function already establishes that the GNMI container is 'telemetry' so call docker supervisorctl status using this container name.
Summary:
Fixes # 
https://github.com/aristanetworks/sonic-qual.msft/issues/61
Ran gnmi tests with this change in our test environment.
=> [sonic-mgmt] Call docker cmd on appropriate container in generate_telemetry_config() funct

tests/generic_config_updater/test_eth_interface.py
Summary:
Add config reload at the end of test_replace_fec for platform arista_7050_qx32s
The generic_config_updater/test_eth_interface.py::test_replace_fec[fc] will change FEC to FC on 40G ports. It results in port down as expected. Then it expects to use rollback_or_reload() to revert the change of FEC, but FEC is not changed back even the rollback in rollback_or_reload() returns successfully. This result of down port will affect all the following tests, because in the setup of the following test files, it will wait for port up and only use 'shutdown/restart' to recover the down port. That doesn't work to recover FEC here; 'config reload' is needed.
Apply 'config reload' to the end of test_replace_fec for platform arista_7050_qx32s
Checked that after the test, all ports …
=> Fix the issue of port down on arista_7050_qx32s after running test_replace_fec

tests/arp/test_stress_arp.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Because of the issue [#7874](https://github.com/sonic-net/sonic-mgmt/issues/7874), we skip script `arp/test_stress_arp.py`. In PR #11922 , we fix this issue, so add this script into nightly test again. 
Summary:
Fixes #7874
Because of the issue [#7874](https://github.com/sonic-net/sonic-mgmt/issues/7874), we skip script `arp/test_stress_arp.py`. In PR #11922 , we fix this issue, so add this script into nightly test again. 
Remove the condition in `tests_mark_conditions.yaml` and add the pytest mark. 
This test is only for topology t0, because we need to get VLAN_INTERFACE in config, which is available for t0.
=> Add script `arp/test_stress_arp.py` into nightly test

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
This reverts commit dbed546b15d226daae4fc9307a2ebf0df35ad755.
Summary:
dhcpv6 relay failure in dualtor-aa was fixed by https://github.com/sonic-net/sonic-mgmt/pull/11695
Hence remove skip condition
Remove skip test_dhcpv6_relay in dualtor-aa
Run test
=> Revert "[dhcp_relay] Skip test_dhcpv6_relay for dualtor-aa (#12046)"

docs/testbed/README.testbed.VsSetup.md
Summary:
Fixes documentation for #12377 
IPv6 only test cases fails when following steps in README.testbed.VsSetup.md
Add steps in documentation to enable ipv6 in docker for KVM testbeds.
Documentation only change. 
Run local test with kvm testbed after following the steps.  There are some test case failure, but they are case related not related to ipv6 setup.
=> Add IPv6 requirements when setting up docker container (#12377)

tests/common/fixtures/duthost_utils.py, tests/ip/test_mgmt_ipv6_only.py
Add temporary eth0 interface debug logs for IPv6 tests, which could be useful for debugging the test failures in `ip/test_mgmt_ipv6_only`
Summary:
=> debug: add temporary eth0 interface debug logs

tests/qos/files/qos_params.th.yaml
Summary:
xon case failed on 6100 for t0-64 topology
RCA:
original test port ids are as below:
```
dst_port_id=6;
dst_port_2_id=8;
dst_port_3_id=9;
src_port_id=7;
```
but the three dst ports belong different pipe, as below:
```
admin@str3-s6100-acs-6:~$ bcmcmd "show pmap"  | grep -E "xe8 |xe9 |xe6 |xe7 "
pipe   logical  physical    idb mmu   ucast_Qbase/Numq  mcast_Qbase/Numq  half-pipe
xe8      1    44        53        20  74       100/10               100/10          0
xe9      1    45        55        22  75       110/10               110/10          0
xe6      2    68        65         0 128         0/10                 0/10          0
xe7      2    69        67         2 129        10/10                10/10          0
```
So it caused xon test failure.
reference other …
=> correct 6100 t0-64 test ports for xon case

tests/test_pretest.py
Summary:
Fixes #12048
Add an explicit testcase to validate that acl is loaded successfully on the backend T0 testbed. Without this case, acl load failure was determined by examining the nighly run failures on the backend testbed
Ran the test against a backend T0 testbed with the fix to load acl correctly and it passed
Ran the test against a non backend T0 testbed and it is skipped
```
test_pretest.py::test_features_state[str2-7050qx-32s-acs-02] PASSED                                                                    [  7%]
test_pretest.py::test_cleanup_testbed[str2-7050qx-32s-acs-02] PASSED                                                                   [ 14%]
test_pretest.py::test_disable_container_autorestart[str2-7050qx-32s-acs-02] PASSED …
```
=> [pretest] Testcase to validate backend acl load

tests/common/fixtures/duthost_utils.py, tests/ip/test_mgmt_ipv6_only.py
Add temporary eth0 interface debug logs for IPv6 tests, which could be useful for debugging the test failures in ip/test_mgmt_ipv6_only
Summary:
=> debug: add temporary eth0 interface debug logs (#12525)

docs/testbed/README.testbed.VsSetup.md
Summary:
Fixes #12522 
The shell command for enabling docker ipv6 in the README.testbed.VsSetup.md won't run correctly, and generated a malformed json file.
Expected json file:
```
{
"ipv6": true,
"fixed-cidr-v6": "fd00:1::1/64",
"experimental": true,
"ip6tables": true
}
```
malformed json file:
```
{
ipv6: true,
fixed-cidr-v6: fd00:1::1/64,
experimental: true,
ip6tables: true
}
```
use single quote ' to keep valid json format.
Run the command locally and restarted docker.
=> Fix the shell command when setting up ipv6 docker daemon

.azure-pipelines/pr_test_scripts.yaml
Summary:
Elastictest performs well in distribute running PR test in multiple KVMs, which support us to add more test scripts to PR checker
Add 18 data plane test to t1-lag PR checker and sort from A to Z
=> Add 18 data plane test to t1-lag PR checker

tests/disk/test_disk_exhaustion.py
Add pytest mark to test_disk_exhaustion.py, require physical device. Due to some unkown different behavior on the KVM testbed, not received expected number of packets.
=> Add pytest mark to test_disk_exhaustion.py, require physical device.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/platform_tests/test_secure_upgrade.py
Summary:
Test failed for 2 reasons:
1. When assigning value to "output_msg"(line 70), there is no "module_output" key in the err.result, the message needed in the check is in "msg", which is assigned to "err_msg"in line 71.
2. There are 2 letters should be upper case(Failure: CMS signature **V**erification **F**ailed)
(Pdb) l
69  	    except RunAnsibleModuleFail as err:
70  	        **output_msg = str(err.results._check_key("module_stdout"))**
71  	        err_msg = str(err.results._check_key("msg"))
72  	        import pdb
73  	        pdb.set_trace()
74  ->	        logger.info("Expected fail, err msg is : {}\n\noutput_msg is {}".format(err_msg, output_msg))
75  	        pytest_assert(
76  	            "Failure: CMS signature Verification Failed" in str(err_msg),
77 …
=> [Mellanox] Fix test_secure_upgrade.py and disable on systems who does not support it

tests/common/utilities.py, tests/conftest.py
Summary: Fix unreachable DUT mgmt_ip in IPv6 only test case
Microsoft ADO 27674168, 27674176
https://github.com/sonic-net/sonic-mgmt/pull/12303 introduced a bug that DUT mgmt_ipv4 is unreachable in a IPv6 only test case, causing test_rw_user_ipv6_only, test_ro_user_ipv6_only, test_snmp_ipv6_only failed with `paramiko.ssh_exception.NoValidConnectionsError` or `socket.timeout: timed out`
If mgmt_ip is unreachable, try mgmt_ipv6
Verified on internal and 202305 branch on physical DUT
=> Fix unreachable DUT mgmt_ip in IPv6 only test case

ansible/module_utils/port_utils.py
Add the `Arista-7060X6-64DE-64x400G` port alias mapping in `get_port_alias_to_name_map`
Summary:
Adding new product support
=> [Arista] Add Arista-7060X6-64DE-64x400G port alias mapping

tests/override_config_table/test_override_config_table.py
Summary: Add ASIC_SENSORS to non-user-config table
Fixes # (issue) 27192588
The ASIC_SENSORS table is not generated from minigraph but the derivative config after reload. This will cause random error if we take the screenshot before and after its occurence thus result in error of 8111 platform. 
Ignore this table in comparison.
E2E
=> [override] Add ASIC_SENSORS table to non-user config table

tests/everflow/test_everflow_ipv6.py, tests/everflow/test_everflow_testbed.py
Summary:
Fixes https://github.com/aristanetworks/sonic-qual.msft/issues/97
`everflow/test_everflow_ipv6.py` fails on active-active dualtor
```
msg        = 'Did not receive expected packet on any of ports [35] for device 0.\n========== EXPECTED ==========\nMask:\n\npacket s...0 00  ....&lt;!..IT......\n0040  00 00 FF 00 00                                   .....\n==============================\n'
self       = &lt;tests.common.plugins.ptfadapter.ptfadapter.PtfTestAdapter testMethod=runTest&gt;
```
`everflow/test_everflow_testbed.py` fails on active-active dualtor.
```
for duthost in duthosts:
&gt;           pt_assert(
wait_until(30, 5, 0, check_active_active_port_status, duthost, active_active_ports, "active"),
"Not all active-active mux ports are active on device %s" % duthost.hostname
) …
```
=> Fix everflow tests for active-active dualtor.

ansible/roles/test/files/ptftests/py3/pfcwd_background_traffic.py, tests/pfcwd/files/pfcwd_helper.py, tests/pfcwd/test_pfcwd_timer_accuracy.py
Summary:
Recently cisco-8000 pfcwd was changed to not trigger watchdog when there is no traffic. So the pfcwd_timer_accuracy script fails, since there is no watchdog triggered during the test. So in this PR a new fixture is added for cisco-8000 only, that will run a background traffic on the selected port when the timer accuracy test is run.
The pfcwd feature was updated not to trigger watchdog when no traffic is present. So we need a background traffic to make the timer accuracy script to work.
Added a background traffic fixture function, that uses supervisor in the PTF container.
Ran on T0 testbed with a sonic fanout:
`=============================================================================================== PASSES ==================================================================== …
=> Adding background traffic for pfcwd_timer_Accuracy for cisco-8000.

.azure-pipelines/baseline_test/baseline.test.mgmt.public.master.yml
Summary:
The PR test peak time changed, to save more cpu resource, need to re-schedule baseline test
Re-schedule baseline test to UTC 8:00
=> [Baseline] Re-schedule baseline test time to UTC 8:00

tests/pfcwd/test_pfcwd_all_port_storm.py
Recently cisco-8000 pfcwd was changed to not trigger watchdog when there is no traffic. So the pfcwd_timer_accuracy script fails, since there is no watchdog triggered during the test. So in this PR a new fixture is added for cisco-8000 only, that will run a background traffic on the selected port when the timer accuracy test is run.
The pfcwd feature was updated not to trigger watchdog when no traffic is present. So we need a background traffic to make the timer accuracy script to work.
Added a background traffic fixture function, that uses supervisor in the PTF container.
Ran on T0 TB with sonic fanout:
`=============================================================================================== PASSES ==================================================================================== …
=> Adding background traffic to all-port-storm.

tests/dualtor_mgmt/test_dualtor_bgp_update_delay.py
Summary:
Fix the issue that, when converting packet receive time(`Decimal`) to `datetime` object, the `Decimal` is converted to an integer first, the fraction is lost, which could result in the test failure due to insufficient bgp update delay.
```
>>> from decimal import Decimal
>>> from datetime import datetime
>>> n = 1092.898980
>>> nd = Decimal(n)
>>> datetime.fromtimestamp(n)
datetime.datetime(1970, 1, 1, 0, 18, 12, 898980)
>>> datetime.fromtimestamp(nd)
<stdin>:1: DeprecationWarning: an integer is required (got type decimal.Decimal).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
datetime.datetime(1970, 1, 1, 0, 18, 12)
```
Converting to `float` first …
=> [dualtor] Fix dualtor bgp update delay due to precision loss in conversion

.azure-pipelines/testbed_health_check.py
[Fix] Fix issue of testbed health check key error and print Exception type and message.
Fix issue of testbed health check key error and print Exception type and message.
- Use `dict.get(key, None)` method instead of direct reference `dict[key]`
- Add exception type in log
Test on both healthy and unhealthy testbeds.
=> [Fix] Fix issue of testbed health check key error and print Exception type and message

.azure-pipelines/test_plan.py
[CI/CD]Add topology and device type argument for PR test. 
If PR test, add argument `--topology=t0,any` for `t0`, `t0-64-32`, and `dualtor` topologies. And add `--topolog=t1,any` for `t1-lag` and `t1-8-lag` topologies. Add `--device_type=vs` argument for all PR test scritps.
=> [CI/CD]Add topology and device type argument for PR test

.azure-pipelines/pr_test_scripts.yaml
Summary:
test_cont_warm_reboot is blocking buildimage test, and also take too long to complete
Temporarily remove in PR test
=> Remove cont warm reboot from PR test

ansible/group_vars/sonic/variables
Add and backport k Arista SKUs for QOS tests. See PR 10997. Actually differs from PR given as reason for closing PR 10997 (PR 10720), since 10720 doesn't include certain k SKUs.
- [ X] 202205
- [ X] 202305
- [ X] 202311
=> Add k SKUs for QOS tests

tests/dhcp_relay/test_dhcp_pkt_recv.py
Summary:
When randomly choice a ptf interface, we didn't exclude disabled interfaces, so the test case may failed on connection issue.
Test case randomly failed.
Excluded disabled intefaces
Run test cases on DUT
=> [test_dhcp_pkt_recv] Exclude disabled interfaces in test case

tests/route/test_route_flap.py
Summary:
This is **cherry-pick** PR for 202205 branch. Original PR https://github.com/sonic-net/sonic-mgmt/pull/11677
This PR fixes issue https://github.com/sonic-net/sonic-mgmt/issues/11460
- For T2 Chassis(topo-t2), route/test_route_flap works fine, if the selected duthost has upstream T3 neighbors.
- Similarly, if the selected duthost has downstream T1 neighbors and if there is only one dut with T1 neighbors, test works fine too.
- But if the selected duthost has downstream T1 neighbors and if there are more than one dut with downstream neighbors, route/test_route_flap fails.
- Fetch the 'neighbor type' (LeafRouter/SpineRouter/AZNGhub) based on the chosen dev_port from get_dev_port_and_route
- Get all the neighbors of same neighbor type and fetch the ptf receiving ports …
=> [202205] [test_route_flap] Route flap multi-dut fix if the selected duthost has downstream neighbors 

ansible/roles/vm_set/tasks/add_topo.yml, ansible/roles/vm_set/tasks/renumber_topo.yml
Summary:
We are adding more data plane test scripts to PR test, but some traffic test using ptf_runner can't be tested on KVM platform, we need to test configuration and skip ptf_runner test if needed
To minimize the change on testcases, it's a better approach to get dut type in ptf_runner and use a flag to decide whether the case could be run on KVM dut, other than add if else in all testcases using ptf_runner
Store dut type to file in ptf host in add-top and restart-ptf, then we will be able to get dut type in ptf_runner
=> Store dut type to ptf host

tests/drop_packets/test_configurable_drop_counters.py
Summary:
Fixes #
1. https://github.com/aristanetworks/sonic-qual.msft/issues/95
2. https://github.com/aristanetworks/sonic-qual.msft/issues/93
Testcases fail in `drop_packets/test_configurable_drop_counters.py` fail in `dualtor-aa` because some of the traffic goes to the unselected ToR.
Similar approach is taken as in [#11921](https://github.com/sonic-net/sonic-mgmt/pull/11921)
Verified on Arista 7260 and Arista 7050 with both dualtor and dualtor-aa topology.
=> Fix drop_packets/test_configurable_drop_counters.py for active-active dualtor.

tests/arp/test_unknown_mac.py
Summary: Use wait_until to verify drop counters in the test `arp/test_unknown_mac.py`
Fixes [#103](https://github.com/aristanetworks/sonic-qual.msft/issues/103)
`arp/test_unknown_mac.py is flaky` fails occasionally with the following signature.
```
def _verifyIntfCounters(self, pretest=False):
"""
Collect counters before and after the test and verify them
Args:
pretest(bool): collect counters before or after the test run
"""
stats = self._parseCntrs()
for key, value in list(self.pkt_map.items()):
intf = value[1]
if pretest:
self.pre_rx_drops[intf] = int(stats[intf]['RX_DRP'])
else:
actual_cnt = int(stats[intf]['RX_DRP'])
exp_cnt = self.pre_rx_drops[intf] + TEST_PKT_CNT
&gt;               pytest_assert(actual_cnt &gt;= exp_cnt,
"Pkt dropped cnt incorrect for intf {}. Expected: {}, …
```
=> Address flakiness in arp/test_unknown_mac.py

tests/qos/qos_sai_base.py
Summary:
2700 t0-8-lag nightly test always failed , because of keyerror, as below:
```
18/04/2024 09:46:32 __init__._fixture_generator_decorator    L0088 ERROR  | 
KeyError(0)
File "/var/src/sonic-mgmt_tbtk5-t0-2700-4_65a9f3c0abd5cba890cf2070/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
res = next(it)
File "/var/src/sonic-mgmt_tbtk5-t0-2700-4_65a9f3c0abd5cba890cf2070/tests/qos/qos_sai_base.py", line 1059, in dutConfig
testPorts = self.__buildTestPorts(request, testPortIds, testPortIps,
File "/var/src/sonic-mgmt_tbtk5-t0-2700-4_65a9f3c0abd5cba890cf2070/tests/qos/qos_sai_base.py", line 683, in __buildTestPorts
src_dut_port_ids = testPortIds[get_src_dst_asic_and_duts['src_dut_index']] …
```
=> miss t0-8-lag topo support in qos test

tests/qos/files/qos_params.j2c.yaml, tests/qos/files/qos_params.jr2.yaml
The Qos params changes in qos.yaml is for J2C+t2 topo w.r.t. the vsq_threshold 10M change in MSFT image 55.
These params changes are specific to broadcom-dnx chassis for MSFT image 55.
Summary:
Executed qos test for t2 topo & verified.
=> Qos params changes for J2C+ t2 topo w.r.t vsq_threshold buffer_config 10M change in MSFT image 55

ansible/lab, ansible/veos_vtb, tests/common/devices/base.py, tests/ip/test_mgmt_ipv6_only.py, tests/ntp/test_ntp.py
Summary:
Backport of #12258
Add support for testing NTP over IPv6. Additionally, test NTP when running with an IPv6-only network.
Also, this fixes the IPv6 address assignment for vlab-02 and makes sure it's given an address on the same subnet as the PTF container.
Tested on KVM and physical DUT with IPv6-only mgmt address.
=> [202311] Add IPv6-only test case for NTP (#12258)

tests/common/templates/default_acl_rules.json, tests/common/utilities.py
Summary:
DATAACL does not allow IN_PORTS qualifier from 202305 and above. Hence updating the templates used for cacl test to remove the usage of input_interfaces during acl entry creation
Tested against 202305 on t0-backend which has DATAACL along with rules and it passed. Ran the test against a non-backend device which has the DATAACL table and it passed
=> [cacl] Update acl template to remove IN_PORTS

tests/dualtor_io/test_tor_failure.py
Summary:
As `loganalyzer` is disabled for tor failure dualtor IO testcases, there is no syslog for debug purpose.
Let's collect syslog to help debug.
Collect syslog in tor failure dualtor IO testcases.
```
dualtor_io/test_tor_failure.py::test_active_tor_reboot_downstream_standby[active-standby-str2-7260cx3-acs-12] PASSED                                                                                                                                                   [100%]
```
=> [dualtor-io] Collect syslog for tor failure testcases

tests/common/plugins/sanity_check/checks.py
Currently when a testcase fails due to critical process failure, it is hard to debug why. Adding the log message to make it easier for us to know which process actually fails
Summary:
=> Print critical process information in the logs

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
…sue for Cisco 8000
Summary:
test_reload_configuration_checks failed because of timing issue,
and will fix in 202311, skip in 202205 and 202305
skip reload_configuration_checks in  in 202205 and 202305
=> Skip test_reload_configuration_checks due to flaky timing issue on Cisco 8000

.azure-pipelines/test_plan.py
Reverts sonic-net/sonic-mgmt#12483 because some test scripts were skipped if no device_type mark.
=> Revert "[CI/CD]Add topology and device type argument for PR test"

tests/tacacs/conftest.py, tests/tacacs/test_ro_disk.py, tests/tacacs/utils.py
Improve IPV6 debug information for debug reachability issue.
There are random IPV6 ptfhost address unreachable issue, need add debug information for investigation.
- Microsoft ADO: 26544335
Improve IPV6 debug information for debug reachability issue.
Improve IPV6 debug information for debug reachability issue.
=> [202311] Improve IPV6 debug information for debug reachability issue (#12426)

ansible/roles/test/files/ptftests/py3/vnet_vxlan.py, tests/vxlan/test_vnet_vxlan.py
In an effort to move/convert PTF test scripts from Python 2 to 3, this PR converts vnet_vxlan.py.
* Convert vnet_vxlan.py to Python 3 and move it to py3 directory
* Update ptf_runner to pass is_python3 flag.
Signed-off-by: [sagummaraj@microsoft.com](mailto:sagummaraj@microsoft.com)
Summary:
Move remaining Python 2 PTF script to Python 3.
Use 2to3.
VXLAN (vnet_vxlan and vnet_route_leak) tests are skipped due to issue #8374; However, migrating script to Python 3 does not impact the test case.
Mellanox, Barefoot
Not applicable
Not applicable
=> [tests/vxlan]: Convert vnet_vxlan test to Python 3

.pre-commit-config.yaml
* Flake8 4.0.1 is an old release that depends on Python >3.6 <3.8.1 and has importlib-metadata incompatabilities with Python >3.12. Hence updating Flake8 to a later release so it can be used with later Python releases.
Summary:
Git pre-commit hook uses Flake8 4.0.1 (2021 release) which works with Python >3.6 <3.8 and has specific version dependencies to importlib-metadata. The tool and pre-commit breaks when using later versions of Python (> 3.12). Hence updating pre-commit to use a later version of flake8.
Update pre-commit config
Tested it by running `pre-commit` on changed files.
None
Not applicable.
Not applicable
=> Upgrade flake8 in pre-commit from 4.0.1 to 6.0.0

tests/generic_config_updater/conftest.py
Summary:
In sonic-mgmt E2E test, there are negative cases that are expected to fail, so we just fail apply-patch and didn't record the error in log.err in negative case
But a log.error https://github.com/sonic-net/sonic-utilities/blob/master/config/main.py#L1171 was added in recent change, which cause many failures in GCU test
Ignore apply-patch in GCU test
=> Ignore apply-patch error in GCU tests

tests/generic_config_updater/conftest.py
Summary:
In sonic-mgmt E2E test, there are negative cases that are expected to fail, so we just fail apply-patch and didn't record the error in log.err in negative case
But a log.error https://github.com/sonic-net/sonic-utilities/blob/master/config/main.py#L1171 was added in recent change, which cause many failures in GCU test
Cherry pick of PR https://github.com/sonic-net/sonic-mgmt/pull/12656
Ignore apply-patch in GCU test
=> [202205] Ignore apply pathch error in gcu test

tests/common/reboot.py
Implement a clear method to determine conclusively whether the device has been rebooted.
Summary:
Enhance reboot test
To confirm that the device has been rebooted without encountering any platform or PDU controller issues.
Created a test file in RAM filesystem, which should be deleted after the device is rebooted successfully.
Verified all the tests in tests/platform_tests/test_reboot.py in the lab testbed.
=> Enhance the reboot method

tests/bgp/test_bgp_dual_asn.py, tests/common/utilities.py
Summary: increase check bgp session timeout; handle failed tcp connection
Previously we used the default value for the timeout equal to 30s. While running this test I faced errors because of small timeout occurs rarely, so it was decided to double it(30s -> 60s).
To handle failed TCP connections and adjust bgp session timeout
=> Increase check bgp session timeout; handle failed tcp connection

.azure-pipelines/pr_test_scripts.yaml, tests/ip/test_mgmt_ipv6_only.py, tests/ntp/test_ntp.py
Summary:
1. Add `ip/test_mgmt_ipv6_only.py` into PR pipeline testing.
2. Rearrange fixture order for two test cases: `ip/test_mgmt_ipv6_only.py::test_rw_user_ipv6_only` and `ip/test_mgmt_ipv6_only.py::test_ro_user_ipv6_only`.
3. Workaround pytest fixture teardown bug affecting `setup_ntp` when run the `ip/test_mgmt_ipv6_only.py` tests.
```
$ ./run_tests.sh -n vms-kvm-t0 -d vlab-01 -f vtestbed.yaml -i ../ansible/veos_vtb -u -c ip/test_mgmt_ipv6_only.py::test_ro_user_ipv6_only
......
ip/test_mgmt_ipv6_only.py::test_ro_user_ipv6_only[vlab-01] FAILED                                                                                                                  [100%]
......
ip/test_mgmt_ipv6_only.py:138: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
=> Adding ipv6_mgmt_only test case into PR testing and fix fixture errors

ansible/veos_vtb, docs/testbed/README.testbed.VsSetup.md
Add T2 VMs to `veos_vtb` file to avoid having the following error when running `deploy-mg` for T2 KVM Testbed.
```
TASK [create new minigraph file for SONiC device] ********************************
fatal: [vlab-t2-sup]: FAILED! => {"changed": false, "msg": "Ansible Undefined Variable: 'syslog_servers' is undefined"}
fatal: [vlab-t2-01]: FAILED! => {"changed": false, "msg": "Ansible Undefined Variable: 'syslog_servers' is undefined"}
fatal: [vlab-t2-02]: FAILED! => {"changed": false, "msg": "Ansible Undefined Variable: 'syslog_servers' is undefined"}
```
Besides, this PR also includes a small improvement to the `docs/testbed/README.testbed.VsSetup.md` wording.
Summary:
=> fix: add t2 VMs to veos_vtb

ansible/veos_vtb, docs/testbed/README.testbed.VsSetup.md
Add T2 VMs to veos_vtb file to avoid having the following error when running deploy-mg for T2 KVM Testbed.
```bash
TASK [create new minigraph file for SONiC device] ******************************** 
fatal: [vlab-t2-sup]: FAILED! => {"changed": false, "msg": "Ansible Undefined Variable: 'syslog_servers' is undefined"} 
fatal: [vlab-t2-01]: FAILED! => {"changed": false, "msg": "Ansible Undefined Variable: 'syslog_servers' is undefined"} 
fatal: [vlab-t2-02]: FAILED! => {"changed": false, "msg": "Ansible Undefined Variable: 'syslog_servers' is undefined"} 
```
Besides, this PR also includes a small improvement to the docs/testbed/README.testbed.VsSetup.md wording.
Summary:
=> fix: add t2 VMs to veos_vtb 

ansible/library/port_alias.py
In https://github.com/sonic-net/sonic-buildimage/pull/18704 the header of port_config.ini was changed:
```
- # name              lanes     alias               index  role   speed    asic_port_name     coreId     corePortId     numVoq
+ # name              lanes     alias               index  role   speed    asic_port_name     core_id     core_port_id     num_voq
```
But port_alias.py depends on the header names and wasn't updated:
```
ALLOWED_HEADER = ['name', 'lanes', 'alias', 'index', 'asic_port_name', 'role', 'speed',
'coreid', 'coreportid', 'numvoq']
```
This PR updates port_alias.py to account for the port_config.ini change.
Summary:
Fixes #12718 
[x] Bug fix
=> port_alias.py: Handle port_config.ini header change

tests/generic_config_updater/test_dynamic_acl.py
Fixes an issue with Dynamic ACL ARP tests where an overlap of the test ip address with the VLAN caused the test to occasionally fail.
Fix a bug in the nightly testing suite
Changed the increment of the ARP test IP addresses
Verified on a testbed the test previously failed on
=> Fix ARP bug in Dynamic ACL GCU tests

tests/common/helpers/portchannel_to_vlan.py
Summary:
This PR contains the following changes
* skip testcases that use the po2vlan scenario since that is not applicable to backend 
* modify the acl usage to account for the fact that IN_PORTs qualifier is no longer applicable from 202305 and above
Ran all the testcases with 'pytest.mark.po2vlan' on 202305 and verified that they passed with the existing scenarios
```
collected 13 items                                                                                                                           
arp/test_tagged_arp.py::test_tagged_arp_pkt[str2-7050qx-32s-acs-02] PASSED                                                             [  7%]
fdb/test_fdb.py::test_fdb[ethernet-str2-7050qx-32s-acs-02] PASSED …
```
=> [backend] Skip po2vlan scenarios and modify acl usage for backend

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Skip test_crm_route on mellanox device due to the bug of https://github.com/sonic-net/sonic-mgmt/issues/12725
Summary:
Skip test_crm_route on mellanox device 
Add skip statement
Run the test on mellanox device
Mellanox
Any
=> [mellanox ] Skip test_crm_route on mellanox device 

tests/platform_tests/api/test_sfp.py, tests/platform_tests/sfp/test_sfputil.py
Summary:
When Software control module is enabled in sai.profile, when call SFP API for getting error description or using sfputil tool "Not supported" will be returned
Updates covers this scenario and print warning.
Make TC passing
Added handler for "Not supported" 
Run TC, TC passed
=> Updated SFP error description test cases to skip SFP which return 'Not supported' message

tests/platform_tests/fwutil/conftest.py
Summary:
In some lab environment, when the bgp is running, the url of the components is not accessible from the dut.
Add this option so we can shutdown bgp when necessary.
By default, the bgp is not shutdown, same as the current flow.
Please see the description.
Add a pytest option.
Run the test with/without the option set, all passed.
=> Add an option to shutdown bgp in fwutil test

tests/arp/test_tagged_arp.py
1. There is a module level autoused fixture setup_po2vlan, it is invoked in tests/arp/test_tagged_arp.py. It would created a lag interface at PTF called bond1.
2. The lag interface bond1 have 2 members, eth0 and eth5. And it shared the same ipv6 address with eth0:
```
bond1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 192.168.8.2  netmask 255.255.255.0  broadcast 0.0.0.0
inet6 fe80::1e34:daff:fe73:8000  prefixlen 64  scopeid 0x20<link>
ether 1c:34:da:73:80:00  txqueuelen 1000  (Ethernet)
RX packets 15  bytes 3008 (2.9 KiB)
RX errors 0  dropped 0  overruns 0  frame 0
TX packets 11  bytes 866 (866.0 B)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet6 fe80::1e34:daff:fe73:8000  prefixlen 64  scopeid …
```
=> Update test_tagged_arp script to do a PTF interface reset after test

sdn_tests/pins_ondatra/.gitignore, sdn_tests/pins_ondatra/BUILD, sdn_tests/pins_ondatra/README.md, sdn_tests/pins_ondatra/WORKSPACE.bazel, sdn_tests/pins_ondatra/bazel/patches/ghodss_yaml.patch, sdn_tests/pins_ondatra/bazel/patches/gnmi-001-fix_virtual_proto_import.patch, sdn_tests/pins_ondatra/bazel/patches/gnmi.patch, sdn_tests/pins_ondatra/bazel/patches/gnoi.patch, sdn_tests/pins_ondatra/bazel/patches/gnoigo.patch, sdn_tests/pins_ondatra/bazel/patches/gnsi.patch, sdn_tests/pins_ondatra/bazel/patches/gribi.patch, sdn_tests/pins_ondatra/bazel/patches/grpc-001-fix_file_watcher_race_condition.patch, sdn_tests/pins_ondatra/bazel/patches/grpc-003-fix_go_gazelle_register_toolchain.patch, sdn_tests/pins_ondatra/bazel/patches/ondatra.patch, sdn_tests/pins_ondatra/bazel/patches/p4lang.patch, sdn_tests/pins_ondatra/bazel/patches/rules_proto_grpc.patch, sdn_tests/pins_ondatra/bazel/patches/snappi.patch, sdn_tests/pins_ondatra/bazel/patches/ygnmi.patch, sdn_tests/pins_ondatra/bazel/patches/ygot.patch, sdn_tests/pins_ondatra/infra_deps.bzl, sdn_tests/pins_ondatra/pins_deps.bzl
[sdn_tests]: Adding Build support for pins_ondatra.
Summary:
- Adding Build support for pins_ondatra.
Build Result:
INFO: Analyzed 0 targets (1 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 0.746s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
=> [sdn_tests]: Adding Build support for pins_ondatra.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/pfcwd/test_pfcwd_function.py
Recently cisco-8000 PFCWD behaviour was modified - to not trigger the WD when there is no traffic, even when there is a PFC storm. The current tests in pfcwd_function don't cover this case, so we are adding a new test to cover this case.
Summary:
Fixes test gap, where there is no traffic but there is a pfc storm, and WD is not triggered.
The new behaviour of pfcwd in cisco-8000 requires a new test.
Added a new test, which verifies that the WD is not triggered, and no syslog is present when there is no traffic.
Ran it on my testbed:
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_actions[mth-t0-64] PASSED                                                                          [ 20%]
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_multi_port[mth-t0-64] PASSED …
=> Adding new pfcwd test with no traffic, no WD.

tests/platform_tests/api/test_module.py
Failing testcase test_get_system_eeprom_info[str2-xxxx-lc2-1], where the eeprom serial number was having a '-' in the string.
So now the 
Updated the REGEX_SERIAL_NUMBER  in test_module.py. There was a similar definition of REGEX_SERIAL_NUMBER in test_chassis.py which is correct.
Verified the test passes
```
jujoseph@c0248bf93d0e:/var/src/sonic-mgmt-int/tests$ ./run_tests.sh -c platform_tests/api/test_module.py::TestModuleApi::test_get_system_eeprom_info    -d str2-xxxx-lc2-1   -i '../ansible/str2,../ansible/veos' -n vms29-t2-xxxx-1  -t 't2,any' -u -e "--skip_sanity --disable_loganalyzer"
=== Running tests in groups ===
Running: python2 -m pytest platform_tests/api/test_module.py::TestModuleApi::test_get_system_eeprom_info --inventory ../ansible/str2,../ansible/veos --host-pattern …
```
=> Fix in regex to accomodate serial number with '-'

.azure-pipelines/pr_test_scripts.yaml
Summary:
voq test was added to t1-lag PR test because 100% success rate in master image, but recently we found it would 100% fail in internal image PR test
Remove voq test from t1-lag PR test
=> Remove voq test from t1-lag PR test

tests/common/utilities.py, tests/dhcp_server/conftest.py, tests/dhcp_server/test_dhcp_server.py
Summary:
This PR is part of [test plan](https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/IPv4-Port-Based-DHCP-Server-test-plan.md) #11348 implementation
To make sure dhcp server has the capability for usage.
In this PR,
first, we write common function to construct DHCP packet, parse VLAN configuration, parse port mapping and send packet and verify packet.
second, we add cases for ip assignment with single ip configuration.
last, we add case for ip assignment with range ip configuration.
Run tests on Arista-720DT-G48S4 and Nokia-7215 mx topo.
=> [dhcp_server] test ip assignment with single and range ip configuration

tests/dut_console/test_console_baud_rate.py
Summary:
In this test case, dut passwd/username are used to login console, which is incorrect.
Use console admin/passwd to login console.
Run tests.
```
collected 3 items                                                                                                                                                                                                                                          
dut_console/test_console_baud_rate.py::test_console_baud_rate_config PASSED                                                                                                                                                                          [ 33%]
dut_console/test_console_baud_rate.py::test_baud_rate_sonic_connect PASSED …
```
=> [dut_console] Fix test_console_baud_rate use dut passwd/admin to login console

tests/gnmi/conftest.py
Summary:
We received a lots of tickets for gnmi end to end test failure, and the root cause is NTP issue and system time is wrong.
We received a lots of tickets for gnmi end to end test failure, and the root cause is NTP issue and system time is wrong.
Add fixture to check DUT time, and then we don't need to spend time to identify NTP issue.
Run GNMI end to end test.
=> Add fixture to detect NTP issue

tests/telemetry/events/swss_events.py
Summary:
Move logic that chooses PFC_STORM_TEST_PORT dynamically from 202311 to 202305
In 202305's `tests/telemetry/events/swss_events.py`, `PFC_STORM_TEST_PORT` is hardcoded to use `Ethernet4`, which may not be available for testing on some configurations.
There already is logic on 202305 and master that dynamically selects the port for testing. Backporting that logic back to 202305.
Test machine without `Ethernet4` can now continue running the test.
=> Change hardcoded PFC_STORM_TEST_PORT to choose from available interfaces

tests/override_config_table/test_override_config_table.py
ADO: 27963882
Summary: Extend support for backend test
override test fail in backend testbed for ACL_TABLE comparison failure. This is because DATAACL ports are in random order.
[sonic-buildimage/src/sonic-config-engine/minigraph.py at master · sonic-net/sonic-buildimage (github.com)](https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-config-engine/minigraph.py#L1344)
Compare the set of ports in ACL_TABLE
E2E test in backend testbed
```
PASSED                                                                                                                                                                                               [100%]
-------------------------------------------------------------------------------------------- live log teardown …
```
=> [override] Extend support for backend testbed

tests/common/fixtures/duthost_utils.py
Summary:
test_warm_upgrade_sad_path fails in teardown because it is unable to restore config_db. This is because in the event of an upgrade, config_db backup is deleted if stored in /etc/sonic/.
Instead of storing config_db backup in /etc/sonic/, store in /host instead.
Ran test_warm_upgrade_sad_path and verified it passes
=> Fix _backup_and_restore_config_db to properly restore config_db.json after upgrade

tests/dhcp_relay/test_dhcp_relay.py
Summary:
Packets go to unselected ToR in case of active-active links or forwarded by the unselected ToR in case of active-standby links.
Set mux to active-standby
Run tests
=> [dhcp_relay] Fix test_dhcp_relay_counter in dualtor-aa

tests/common/dualtor/mux_simulator_control.py
Summary:
Fix  the following `test_link_drop` issue on `dualtor-aa`:
```
def _recover_directions_all():
"""
Function to recover all traffic on all directions on a certain port
Args:
interface_name: a str, the name of interface to control
Returns:
None.
"""
server_url = url(action=OUTPUT)
data = {"out_sides": [UPPER_TOR, LOWER_TOR, NIC]}
>       pytest_assert(_post(server_url, data),
"Failed to set output on all directions for all interfaces")
```
As there is no active-standby mux ports on `dualtor-aa`, the drop helper fixture for active-standby mux ports `set_drop_all` is never called. So let's skip the recovery step in `set_drop_all` if `set_drop_all` is not called.
``` …
```
=> [dualtor-aa] Fix set_drop issue with mux_simulator

tests/common/dualtor/mux_simulator_control.py, tests/dualtor/test_switchover_failure.py
Summary:
Adapting `test_mac_move_during_switchover` to dualtor_aa topology.
sign-off: zhangjing@microsoft.com
1. skip `mux_simulator` actions if this is dualtor-aa topo
2. remove `verify_tor_states` in recover step, to avoid flakiness
3. recover mux config after test completes
tested on dualtor-aa topology
```
---------------------------- live log sessionfinish ----------------------------
20:31:29 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs
SKIPPED [2] dualtor/test_switchover_failure.py:152: Skip as no mux ports of 'active-standby' cable type
============= 2 passed, 2 skipped, 2 warnings in 398.90s (0:06:38) =============
```
=> [dualtor] adapting `test_mac_move_during_switchover` to dualtor_aa

tests/crm/test_crm.py
* Some topologies like backend T0s have 2 default ACL rules which cause test failures due to available ACL counters mismatch 
before and after the test. To avoid this, delete the default ACL rules and restore them back at the end of the test.
Summary:
Fixes # 27963693
To fix test_acl_counter failures on backend T0 testbeds due to available acl counter mismatch
Delete default DATAACLs before the test and restore them at the end of the test
By running the test locally on various testbeds with different topologies
=> Fix CRM tests to handle default ACL rules

tests/crm/test_crm.py
* Per a recent release note by Nvidia, CRM available entries for a specific object reflect the momentarily availability and may 
change even if no entries of that object are created / removed due to the background computation done by the internal 
processes, therefore skip available route counter checks which cause crm test failures.
Summary:
Fixes # 27685893
To avoid CRM test failures due to available counter mismatch
Skip available counter verification for CRM route test.
By running the test locally on mellanox testbeds
Mellanox-specific change
=> Skip available route check for mellanox platforms

tests/drop_packets/test_drop_counters.py
Summary:
- Backend has tagged members in vlan and this results in double tagged packets sent from the ptf for some cases where vlan tagged packets are sent from the ptf. Hence regular interface mode will ensure that packets are not sent out of subintf.
- Also the default acl on backend will not allow proper testing of functionality since certain testcases expect rx drops but that will get accounted as acl drops. To avoid that, the default acl is cleaned up before the testing begins and restored back at the end.
Ran the test on 202305 against t0-backend and it passed
```
collected 102 items                                                                                                                          
drop_packets/test_drop_counters.py::test_equal_smac_dmac_drop[por …
```
=> [backend] Use regular interfaces on ptf for backend and handle default acl

tests/run_tests.sh
Summary:
Currently in run_tests.sh, pretest and posttest are running separately with other scripts, but when we gathering other pytest scripts, pretest and posttest would be collected, so they would run twice, which would waste time
Cherry pick of PR https://github.com/sonic-net/sonic-mgmt/pull/11497
when gathering pytest scripts without specific testcases, remove pretest and posttest from all test scripts
=> [202205] Remove pretest and posttest from all run tests scripts

tests/run_tests.sh
Summary:
Currently in run_tests.sh, pretest and posttest are running separately with other scripts, but when we gathering other pytest scripts, pretest and posttest would be collected, so they would run twice, which would waste time
Cherry pick of PR https://github.com/sonic-net/sonic-mgmt/pull/11497
when gathering pytest scripts without specific testcases, remove pretest and posttest from all test scripts
=> [202012] Remove pretest and posttest from all run tests scripts

.azure-pipelines/pr_test_scripts.yaml, tests/common/plugins/pdu_controller/__init__.py
To adapt to kvm testbed, there are two isssues in previous pdu_controller __init__.py script:
- conn_graph_facts is None on kvm testbed, and it will generate KeyError when trying to get the value using method `conn_graph_facts["xxx"]`. 
- inv_mgr has no function called `get_host_list`
So in this PR, I fix these issues 
- Use method `get` to get the value in dict `conn_graph_facts` to avoid KeyError and set it `{}` if the key not exists in the dict. 
- The code in branch `if hostname not in device_pdu_links or hostname not in device_pdu_info` is unnecessary here. Because, we use conn_graph_facts to get pdu links and pdu info first. if the hostname not in device_pdu_links or hostname not in device_pdu_info here means the host doesn't not exist in the csv file, so we don't have to get info …
=> Add module `platform_tests/test_kdump.py` into PR test

tests/pfcwd/test_pfcwd_function.py, tests/pfcwd/test_pfcwd_warm_reboot.py
Modifying rx_action to forward for Marvell(innovium) chip type in PFCWD tests.
With changes done in ingress zero buffer pool/profile, need to add rx_action to forward for Marvell(innovium) chip type to pass PFCWD cases
Summary:
- [*] 202205
- [*] 202305
- [*] 202311
=> Adding Marvell(innovium) specific change for PFCWD tests

.azure-pipelines/pr_test_scripts.yaml, tests/ip/test_mgmt_ipv6_only.py, tests/ntp/test_ntp.py
original PR (#12393). cherry-pick to 202305
Summary:
1. Add `ip/test_mgmt_ipv6_only.py` into PR pipeline testing.
2. Rearrange fixture order for two test cases: `ip/test_mgmt_ipv6_only.py::test_rw_user_ipv6_only` and `ip/test_mgmt_ipv6_only.py::test_ro_user_ipv6_only`.
3. Workaround pytest fixture teardown bug affecting `setup_ntp` when run the `ip/test_mgmt_ipv6_only.py` tests.
Summary:
=> [PR:12393] Adding ipv6_mgmt_only test case into PR testing and fix fixture errors

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip `test_dynamic_acl` on Nokia-7215 platform. This feature cannot be supported on Nokia-7215 before 202411 branch cut-over.
Skip `test_dynamic_acl` on Nokia-7215 platform. This feature cannot be supported on Nokia-7215 before 202411 branch cut-over.
Use conditional mark.
```
=============================================== short test summary info ================================================
SKIPPED [18] generic_config_updater/test_dynamic_acl.py: Skip on unsupported platforms
SKIPPED [4] generic_config_updater/test_dynamic_acl.py:1166: Skip on unsupported platforms
=========================================== 22 skipped, 3 warnings in 45.82s ===========================================
```
Nokia-7215 platform specific.
=> [Nokia-7215] Skip test_dynamic_acl on Nokia-7215 platform

.azure-pipelines/pr_test_scripts.yaml
In PR #12387, we add the module autorestart/test_container_autorestart.py into PR test. Although it passed in master, it will fail in internal due to the container restapi. In this PR, we comment this module temporarily to unblock internal branch code sync. 
Summary:
In PR #12387, we add the module autorestart/test_container_autorestart.py into PR test. Although it passed in master, it will fail in internal due to the container restapi. In this PR, we comment this module temporarily to unblock internal branch code sync.
=> Remove module autorestart/test_container_autorestart.py in PR test. 

tests/generic_config_updater/test_cacl.py
ADO: 27980127
Summary: Improve debug print for cacl test as requested
Improve debug print
Show more print
E2E test
```
07:46:39 __init__._fixture_generator_decorator    L0093 INFO   | -------------------- fixture setup_env teardown starts --------------------
......
07:46:51 test_cacl.setup_env                      L0066 INFO   | original iptable rules: ['-P INPUT ACCEPT', '-P FORWARD ACCEPT', '-P OUTPUT ACCEPT', '-A INPUT -s 127.0.0.1/32 -i lo -j ACCEPT', '-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT', '-A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT', '-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT', '-A INPUT -p icmp -m icmp --icmp-type 3 -j ACCEPT', '-A INPUT -p icmp -m icmp --icmp-type 11 -j ACCEPT', '-A INPUT -p udp -m udp --dport 67:68 -j …
```
=> [GCU] Improve debug print for cacl test

tests/bfd/test_bfd.py
Summary:
This PR introduces a new test case in the existing [BFD test plan](https://github.com/sonic-net/sonic-mgmt/pull/11898)  focused on testing the existing BFD echo-mode feature. By testing BFD echo-mode functionality, I aim to ensure its reliability and effectiveness in real-world scenarios. 
Enabling BFD Echo-mode provides an additional layer of fault detection in network environments. This proactive approach helps to minimize network downtime and improve overall network reliability.
Enabling BFD echo-mode across all neighbors in the topology.
I verified the test by running the command:
- show bfd peer 
which will show all the details about bfd neighbors.
=> Test case for BFD echo-mode

sdn_tests/pins_ondatra/.gitignore, sdn_tests/pins_ondatra/BUILD, sdn_tests/pins_ondatra/README.md, sdn_tests/pins_ondatra/WORKSPACE.bazel, sdn_tests/pins_ondatra/bazel/patches/ghodss_yaml.patch, sdn_tests/pins_ondatra/bazel/patches/gnmi-001-fix_virtual_proto_import.patch, sdn_tests/pins_ondatra/bazel/patches/gnmi.patch, sdn_tests/pins_ondatra/bazel/patches/gnoi.patch, sdn_tests/pins_ondatra/bazel/patches/gnoigo.patch, sdn_tests/pins_ondatra/bazel/patches/gnsi.patch, sdn_tests/pins_ondatra/bazel/patches/gribi.patch, sdn_tests/pins_ondatra/bazel/patches/grpc-001-fix_file_watcher_race_condition.patch, sdn_tests/pins_ondatra/bazel/patches/grpc-003-fix_go_gazelle_register_toolchain.patch, sdn_tests/pins_ondatra/bazel/patches/ondatra.patch, sdn_tests/pins_ondatra/bazel/patches/p4lang.patch, sdn_tests/pins_ondatra/bazel/patches/rules_proto_grpc.patch, sdn_tests/pins_ondatra/bazel/patches/snappi.patch, sdn_tests/pins_ondatra/bazel/patches/ygnmi.patch, sdn_tests/pins_ondatra/bazel/patches/ygot.patch, sdn_tests/pins_ondatra/infra_deps.bzl, sdn_tests/pins_ondatra/infrastructure/binding/BUILD.bazel, sdn_tests/pins_ondatra/infrastructure/binding/binding_backend.go, sdn_tests/pins_ondatra/infrastructure/binding/pins_backend.go, sdn_tests/pins_ondatra/infrastructure/binding/pins_binding.go, sdn_tests/pins_ondatra/pins_deps.bzl
- [sdn_tests]: Adding binding infra to pins_ondatra.
Summary:
- Adding binding infra to pins_ondatra.
Build Results:
github.com/openconfig/gnsi/pathz/authorization.proto:43:1: warning: Import 
github.com/openconfig/gnsi/version/version.proto is unused.
github.com/openconfig/gnsi/pathz/pathz.proto:25:1:
INFO: Elapsed time: 625.193s, Critical Path: 105.81s
INFO: 882 processes: 251 internal, 631 linux-sandbox.
INFO: Build completed successfully, 882 total actions
=> [sdn_tests]: Adding binding infra to pins_ondatra.

tests/platform_tests/conftest.py
This is a sister PR to the image change PR [18099](https://github.com/sonic-net/sonic-buildimage/pull/18099) that introduces the current year to all logs.
Summary:
Fixes Microsoft ADO 26907533
The motivation for this PR is to ensure that the sonic-mgmt tests keep up with the updated log template that is introduced by sonic-buildimage PR [18099](https://github.com/sonic-net/sonic-buildimage/pull/18099) that introduces the current year to all logs.
Modified FMT template in conftest.py to match the new syslog format with current year
**Test 1 : Standard format - Standard Test**
```
admin@str-s6100-acs-1:~$ show ver
SONiC Software Version: SONiC.20230531.26
SONiC OS Version: 11
Distribution: Debian 11.8
Kernel: 5.10.0-23-2-amd64
Build commit: a899d082be
Build date: Tue Apr 23 11:26:32 UTC …
```
=> Added year to FMT time template

tests/qos/test_qos_sai.py
Summary: Skip 
Fixes [#118](https://github.com/aristanetworks/sonic-qual.msft/issues/118)
IPV6 variant of the test fails 
```
qos/test_qos_sai.py::TestQosSai::testQosSaiDscpQueueMapping[single_asic-ipv6]
---------------------------------------------------------------------------------------- live log call ----------------------------------------------------------------------------------------
06:25:52 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 493, in __call__
return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
File …
```
=> Skip IPV6 variant of testQosSaiDscpQueueMapping if IPV6 is not configured.

tests/ip/test_mgmt_ipv6_only.py, tests/tacacs/conftest.py, tests/telemetry/conftest.py
This PR is to address the fixture setup sequence issue, and teardown out of sequence issue.
In convert_and_restore_config_db_to_ipv6_only, it will do a "config reload -y" during fixture setup or teardown.
For feature test cases where config is not saved into config_db.json, this reload needs to be done before feature fixture setup and after feature teardown, such as: tacacs_v6, setup_streaming_telemetry, or setup_ntp.
According to https://docs.pytest.org/en/latest/reference/fixtures.html#reference-fixtures, it only considers the following when deciding the fixture orders:
* scope
* dependencies
* autouse
We shouldn't use autouse in this test module. So only two options to let convert_and_restore_config_db_to_ipv6_only runs before other fixtures:
1. define other fixtures in 'function' …
=> fix fixture order issue in ipv6_mgmt tacacs and telemetry cases

tests/platform_tests/test_reboot.py
Summary:
Fixes test_reboot.py::test_continous_reboot more stable on Cisco platform
The testcase is flakey on Cisco platform because Cisco router reboot time > 300s
Increase wait_for_startup timeout value from 300 to 600
Run with Cisco 8111 router.
No impact to other platform.
=> Make test_reboot.py more stable

tests/platform_tests/link_flap/test_link_flap.py
The module `test_link_flap.py` can support physical testbeds only， and it uses `pytest.mark.platform('physical')` before to identify. But usually, we use mark `pytest.mark.device_type('physical')` to identify, and in Elastictest, we will also use the mark `device_type` to collect and filter cases. So in this PR, we change this mark. 
Summary:
The module `test_link_flap.py` can support physical testbeds only， and it uses `pytest.mark.platform('physical')` before to identify. But usually, we use mark `pytest.mark.device_type('physical')` to identify, and in Elastictest, we will also use the mark `device_type` to collect and filter cases. So in this PR, we change this mark. 
Change the mark `pytest.mark.platform('physical')` to `pytest.mark.device_type('physical')`
=> Change the mark in module `test_link_flap.py`. 

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
This is a cherry-pick of PR https://github.com/sonic-net/sonic-mgmt/pull/12738
The test case `test_bgp_queues` is failing on Mellanox platform with t1-lag topology because of known issue on router interface.
Earlier there was a PR https://github.com/sonic-net/sonic-mgmt/pull/11705 to skip it, but that didn't work as expected as `topo_type` was used, which should be `topo_name`.
The test case `test_bgp_queues` is failing on Mellanox platform with t1-lag topology. 
Update `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml`
The change is verified by running on a Mellanox testbed with t1-lag topo.
``` …
```
=> [cherry-pick] [202311] Skip test_bgp_queues test on Mellanox platform with t1-lag topology

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
The test case `test_bgp_queues` is failing on Mellanox platform with t1-lag topology because of known issue on router interface.
Earlier there was a PR https://github.com/sonic-net/sonic-mgmt/pull/11705 to skip it, but that didn't work as expected as `topo_type` was used, which should be `topo_name`.
The test case `test_bgp_queues` is failing on Mellanox platform with t1-lag topology. 
Update `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml`
The change is verified by running on a Mellanox testbed with t1-lag topo.
``` …
```
=> Skip test_bgp_queues test on Mellanox platform with t1-lag topology

tests/saitests/py3/sai_qos_tests.py
* Qos newSAI change_adding queue7 to DscpToPGMapping
* QoS_DscpToPgMapping_platform_asic check added
Summary: master PR #9859 
=> [Cherry-pick] Adding PG7 check to DscpToPgMapping (#9859)

tests/tacacs/test_ro_disk.py
Handle log rotate failed issue
sonic test_ro_disk test case failed because log rotate command failed.
- Microsoft ADO: 27929530
Ignore log rotate failed because log already rotating
Handle log rotate failed issue
=> [TACACS] Handle log rotate failed issue

tests/conftest.py
Fix module level fixture rand_one_dut_hostname run multiple times in same test module issue.
rand_one_dut_hostname run multiple times in same module cause acl/test_acl.py run long time
- Microsoft ADO: 27997617
Store random DUT name in global variable, remove parameterization code.
Fix module level fixture rand_one_dut_hostname run multiple times in same test module issue.
=> Fix module level fixture rand_one_dut_hostname run multiple times in same test module issue.

tests/generic_config_updater/conftest.py
Summary:
Test case `test_k8s_config_patch_apply` is error out because error logs in syslog. The error message is expected as DUT doesn't have public DNS access.
```
E               May 11 13:35:04.494371 sonic ERR ctrmgrd.py: Refer file /tmp/tmp8apufdr7kube_hints_ for troubleshooting tips
E               May 11 13:35:04.495918 sonic ctrmgrd.py: Join failed: HTTPSConnectionPool(host='k8svip.ap.gbl', port=6443): Max retries exceeded with url: /api/v1/namespaces/default/configmaps/kube-root-ca.crt (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdd64a9a250>: Failed to resolve 'k8svip.ap.gbl' ([Errno -2] Name or service not known)"))
```
This PR addressed the issue by ignoring the error log.
This PR is to ignore error log from ctrmgrd in …
=> Ignore error log from ctrmgrd in test_k8s_config_patch_apply

tests/ip/test_mgmt_ipv6_only.py, tests/tacacs/conftest.py, tests/telemetry/conftest.py
Cherry-pick  (https://github.com/sonic-net/sonic-mgmt/pull/12825) into 202305 branch.
This PR is to address the fixture setup sequence issue, and teardown out of sequence issue.
In convert_and_restore_config_db_to_ipv6_only, it will do a "config reload -y" during fixture setup or teardown.
For feature test cases where config is not saved into config_db.json, this reload needs to be done before feature fixture setup and after feature teardown, such as: tacacs_v6, setup_streaming_telemetry, or setup_ntp.
According to https://docs.pytest.org/en/latest/reference/fixtures.html#reference-fixtures, it only considers the following when deciding the fixture orders:
* scope
* dependencies
* autouse
We shouldn't use autouse in this test module. So only two options to let …
=>  [PR:12825] 202305 fix fixture order issue in ipv6_mgmt tacacs and telemetry cases

tests/ip/test_mgmt_ipv6_only.py, tests/tacacs/conftest.py, tests/telemetry/conftest.py
Cherry-pick (https://github.com/sonic-net/sonic-mgmt/pull/12825) into 202311 branch.
This PR is to address the fixture setup sequence issue, and teardown out of sequence issue.
In convert_and_restore_config_db_to_ipv6_only, it will do a "config reload -y" during fixture setup or teardown.
For feature test cases where config is not saved into config_db.json, this reload needs to be done before feature fixture setup and after feature teardown, such as: tacacs_v6, setup_streaming_telemetry, or setup_ntp.
According to https://docs.pytest.org/en/latest/reference/fixtures.html#reference-fixtures, it only considers the following when deciding the fixture orders:
* scope
* dependencies
* autouse
We shouldn't use autouse in this test module. So only two options to let …
=> [PR:12825] fix fixture order issue in ipv6_mgmt tacacs and telemetry cases 202311

tests/saitests/py3/sai_qos_tests.py
Cherry-pick from PR #8775 
Summary:
=> [Cherry-pick] Optimizing testQosSaiHeadroomPoolSize runtime #8775

ansible/plugins/connection/switch.py
Summary:
Fixes [#116](https://github.com/aristanetworks/sonic-qual.msft/issues/116)
Tests using tests/scripts/exec_template.yml fail when fanout has a password set. 
Regression introduced by: https://github.com/sonic-net/sonic-mgmt/pull/12318
There is a retry logic in switch.py for different passwords a fanout switch can have in the lab: https://github.com/sonic-net/sonic-mgmt/blob/202305/ansible/group_vars/all/labinfo.json#L21-L25. The issue here is that if the first attenpt fails the value of i being returned is 2 which in the second iteration is being wrongly interpreted as ssh connection being established: https://github.com/sonic-net/sonic-mgmt/blob/202305/ansible/plugins/connection/switch.py#L99-L102. This later results in error when the script tries to run CLI commands on the …
=> Fix switch.py for password based login

tests/platform_tests/api/test_fan_drawer_fans.py
Summary:  Fix flaky test platform_tests/api/test_fan_drawer_fans.py
Fixes # [aristanetworks/sonic-qual.msft#106](https://github.com/aristanetworks/sonic-qual.msft/issues/106)
`setup` fixture in the test class has `duthost` parameter which always points to first ToR device. Thus `stop_thermal_control_daemon(duthost)` which needs for test to pass, is always stopping `thermalctld` for the first ToR device and thus leads to flakiness of the test when runs on second ToR.
Fix: Derive the duthost name based on the test selected ToR (duthosts[enum_rand_one_per_hwsku_hostname]).
Test is consistently passing with the fix (verified on Arista-7260CX3-C64).
=> Fix platform_tests/api/test_fan_drawer_fans.py

.azure-pipelines/pr_test_scripts.yaml, tests/ip/test_mgmt_ipv6_only.py, tests/ntp/test_ntp.py
Summary:
Original PR: https://github.com/sonic-net/sonic-mgmt/pull/12393
Summary:
1. Add `ip/test_mgmt_ipv6_only.py` into PR pipeline testing.
2. Rearrange fixture order for two test cases: `ip/test_mgmt_ipv6_only.py::test_rw_user_ipv6_only` and `ip/test_mgmt_ipv6_only.py::test_ro_user_ipv6_only`.
3. Workaround pytest fixture teardown bug affecting `setup_ntp` when run the `ip/test_mgmt_ipv6_only.py` tests.
=> [PR:12393]  Adding ipv6_mgmt_only test case into PR testing and fix ntp fixture errors

ansible/roles/test/files/ptftests/py3/pfc_wd_background_traffic.py, tests/pfcwd/files/pfcwd_helper.py, tests/pfcwd/test_pfcwd_all_port_storm.py, tests/pfcwd/test_pfcwd_function.py, tests/pfcwd/test_pfcwd_timer_accuracy.py, tests/pfcwd/test_pfcwd_warm_reboot.py, tests/ptf_runner.py
Update the pfcwd test cases according to the new implement of the pfcwd
After the feature is completed, it criteria to trigger the pfcwd is much more strict than previous on Nvidia platform, So adjust the test case to properly trigger the pfcwd. The solution is to send background traffic during the pfc frame is sent from the fanout.
Summary:
To make the pfcwd test case could pass after the new implement of the pfcwd.
Add the logic of sending the background traffic to make the test case could pass after the new implement of the pfcwd
All pfcwd test case could pass
=> Update the pfcwd test cases according to the new implement of the pfcwd.

tests/platform_tests/test_intf_fec.py
sonic-mgmt: Adding a test case to verify FEC mode is valid for all the interfaces with link is "UP".
Also adding a test case to configure FEC mode and verify the FEC operation mode after that.
Summary:
Add new test cases.
1. Check FEC operational mode from "show interfaces fec status".
2. Configure FEC mode using "sudo config interface fec <interface> <fec mode>
Verified in the lab device on Mellanox 2700, Mellanox 4700, Cisco 8101 and Cisco 8111 devices with latest 202311 SONiC version.
Additionally, verified a negative test case of SONiC version 202305 on Mellanox 4700 platform.
=> sonic-mgmt: Add FEC check test case.

tests/bgp/test_startup_tsa_tsb_service.py, tests/common/reboot.py, tests/test_posttest.py, tests/test_pretest.py
Summary:
- This PR has tests to verify the changes introduced as part of #[18496](https://github.com/sonic-net/sonic-buildimage/pull/18496)
- Basically, this PR has 5 test cases to verify start and stop of the new service '_startup_tsa_tsb.service_' added by #[18496](https://github.com/sonic-net/sonic-buildimage/pull/18496) including other checks.
- To verify code changes introduced as part of the PR #[18496](https://github.com/sonic-net/sonic-buildimage/pull/18496)
- Added 5 test cases as mentioned below to verify the changes. 
- Attaching test cases' description document here for further reference and details.
[BGP-TSA-TSB-Service-TestCases.txt](https://github.com/sonic-net/sonic-mgmt/files/14808766/BGP-TSA-TSB-Service-TestCases.txt)
1. …
=> Tests to verify 'startup_tsa_tsb.service' during linecard bring up - PR#18496

tests/acl/test_acl.py
There are a few ACL tests which are expecting the wrong ACL rule to be hit:
`test_l4_dport_match_forwarded - Expects 5, Actual 9`
```
def test_l4_dport_match_forwarded(self, setup, direction, ptfadapter, counters_sanity_check, ip_version):
"""Verify that we can match and forward on L4 destination port."""
pkt = self.tcp_packet(setup, direction, ptfadapter, ip_version, dport=0x1217)
DATA_INGRESS_IPV4_TEST  RULE_5        9995        FORWARD   ETHER_TYPE: 2048              Active
IP_PROTOCOL: 126
DATA_INGRESS_IPV4_TEST  RULE_9        9991        FORWARD   ETHER_TYPE: 2048              Active
L4_DST_PORT: 4631
```
`test_l4_sport_match_dropped - Expects 10, Actual 17`
```
def test_l4_sport_match_dropped(self, setup, direction, ptfadapter, counters_sanity_check, ip_version):
"""Verify that we …
```
=> Fixing a few ACL tests which expect the wrong rule to be hit for counters_sanity_check

ansible/devutil/devices/ansible_hosts.py, ansible/devutil/devices/chassis_utils.py, ansible/devutil/devices/sonic.py
Summary:
Enhance upgrade image script to support chassis device.
For chassis device, we need to firstly upgrade the image for supervisor cards, then upgrade the image for line cards.
Enhance the upgrade_image script to support chassis devices.
1. Upgrade image on the supervisor cards, then wait 900s for the supervisor card to be ready.
2. Upgrade image on the line cards, then wait 300s for the line cards to be ready.
3. The sonichosts defautly run commands on all supervisor cards and line cards at the same time, enhance the framework to be able to upgrade specific hosts.
Run upgrade image script on the chassis device and pizzbox device, both of them works well
=> [Feat] Enhance upgrade image script to support chassis devices

tests/saitests/py3/sai_qos_tests.py
Summary: Fix qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit.
Fixes [#111](https://github.com/aristanetworks/sonic-qual.msft/issues/111)
Regression introduced by [#9780](https://github.com/sonic-net/sonic-mgmt/pull/9780)
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit fails with 
```qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit.```
Qos tests would fail on testQosSaiPfcXonLimit, because step 1 of the tests, which disable TX for dst_port_id, dst_port_2_id, dst_port_3_id is getting incorrect DST ports.
Due to this the tx is disabled on a port but never enabled and switch keeps on sending PFC packets and all the subsequent testcases in the module fail.
Cherry picked [#12151](https://github.com/sonic-net/sonic-mgmt/pull/12151) to 202311 with additional fix mentioned in …
=> Fix qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit. 

tests/tacacs/test_ro_user.py, tests/tacacs/test_rw_user.py, tests/tacacs/utils.py
Improve TACACS run command on IPV6 failed issue.
Tacplus server crash when receive authorization request from IPV6 address.
- Microsoft ADO: 27895362
Check TACACS server status after run command with IPV6 address.
Improve TACACS run command on IPV6 failed issue.
=> [TACACS] Improve TACACS run command on IPV6 failed issue.

tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py, tests/saitests/py3/texttable.py
Summary:
improve qos log readability and troubleshoot capability
implement:
All the messages were outputted to PTF logging by default, and can set flag to output to stderr of PTF console for specific message.
so it can avoid lots of message flush on console and "test summary", easy to identify failure when triage.
and also can check PTF logging which include all the message when rootcause failure.
provide general interface for counter collecting, comparing, and displaying.
so far, we can read 8 kinds of counter:
port_counter, queue_counter_counter, queue_share_wm_counter, pg_share_wm_counter, pg_headroom_wm_counter, pg_counter_couner, pg_drop_counter and ptf_tx_rx_counter
Although CounterCollector provides a common API to collect, compare and display these counters, if you …
=> imporve qos log readability

tests/cacl/test_cacl_application.py, tests/generic_config_updater/test_cacl.py
GCU test_cacl case failed on dualtor testbed randomly.
The failed message:
`failed on teardown with "Failed: iptable rules are not suppose to change after test. diff: ['+ -A DHCP -m mark --mark 0x67008 -j DROP', '+ -A DHCP -m mark --mark 0x67024 -j DROP', '+ -A DHCP -m mark --mark 0x67022 -j DROP', '+ -A DHCP -m mark --mark 0x67018 -j DROP', '+ -A DHCP -m mark --mark 0x67014 -j DROP', '+ -A DHCP -m mark --mark 0x67013 -j DROP', '+ -A DHCP -m mark --mark 0x67010 -j DROP', '+ -A DHCP -m mark --mark 0x67009 -j DROP', '+ -A DHCP -m mark --mark 0x67004 -j DROP', '+ -A DHCP -m mark --mark 0x67007 -j DROP', '+ -A DHCP -m mark --mark 0x67006 -j DROP', '+ -A DHCP -m mark --mark 0x67002 -j DROP', '+ -A DHCP -m mark --mark 0x67001 -j DROP', '+ -A DHCP -m mark --mark 0x67005 -j DROP']"`
Summary: …
=> Set mux mode to manual to disable port toggle in cacl scripts on dualtor testbed

tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py, tests/saitests/py3/texttable.py
Log message wrapper:
All the messages were outputted to PTF logging by default, and can set flag to output to stderr of PTF console for specific message. so it can avoid lots of message flush on console and "test summary", easy to identify failure when triage. and also can check PTF logging which include all the message when rootcause failure.
CounterCollector Class
provide general interface for counter collecting, comparing, and displaying.
Diagnostic Counter Wrapper
so far, we can read 8 kinds of counter:
port_counter, queue_counter_counter, queue_share_wm_counter, pg_share_wm_counter, pg_headroom_wm_counter, pg_counter_couner, pg_drop_counter and ptf_tx_rx_counter
Although CounterCollector provides a common API to collect, compare and display these counters, if you use countercollect …
=> [202311] improve qos log readability (#12526)

.azure-pipelines/pr_test_scripts.yaml, tests/platform_tests/test_power_off_reboot.py, tests/platform_tests/test_reboot.py, tests/platform_tests/test_reload_config.py, tests/platform_tests/test_sequential_restart.py, tests/platform_tests/test_xcvr_info_in_db.py
To adapt to kvm testbed, we need to fix the issue -- `conn_graph_fact` is none in VS set-up. 
In this PR, we use method `get` of a dict to get the value instead of `[]` to avoid key error when getting value from an empty dict `conn_graph_fact`. 
Also, in this PR, after fixing this issue, we can add three platform tests into PR test. 
Summary:
To adapt to kvm testbed, we need to fix the issue -- `conn_graph_fact` is none in VS set-up. 
In this PR, we use method `get` of a dict to get the value instead of `[]` to avoid key error when getting value from an empty dict `conn_graph_fact`. 
Also, in this PR, after fixing this issue, we can add three platform tests into PR test.
=> Fix the Keyerror issue caused by none `conn_graph_fact` in VS set-up

sdn_tests/pins_ondatra/infra_deps.bzl, sdn_tests/pins_ondatra/tests/BUILD.bazel, sdn_tests/pins_ondatra/tests/ethcounter_sw_dual_switch_test.go
- [sdn_tests]:Adding Dual switch EthernetCounter Test to pins_ondatra.
Build results:
INFO: Elapsed time: 746.156s, Critical Path: 210.48s
Summary:
- Added Dual switch EthernetCounter Test to pins_ondatra.
=> [sdn_tests]:Adding Dual switch EthernetCounter Test to pins_ondatra.

sdn_tests/pins_ondatra/infra_deps.bzl, sdn_tests/pins_ondatra/tests/BUILD.bazel, sdn_tests/pins_ondatra/tests/ethcounter_sw_dual_switch_test.go, sdn_tests/pins_ondatra/tests/gnmi_long_stress_test.go
- [sdn_tests]: Adding GNMI long Stress Test to pins_ondatra.
Summary:
- Added GNMI long Stress Test to pins_ondatra.
Build results:
github.com/openconfig/gnsi/acctz/acctz.proto:36:1:
INFO: Elapsed time: 567.405s, Critical Path: 187.23s
=> [sdn_tests]: Adding GNMI long Stress Test to pins_ondatra.

.azure-pipelines/baseline_test/baseline.test.mgmt.public.master.yml
Summary:
Baseline test is to run PR tests multiple times to surface flaky issues.
The pre-test step is to find out if there is any importing dependency issue
between test scripts. This dependency issue only could happen with new
PRs. During baseline test, the dependency issue won't happen. It is unnecessary
for baseline test.
The GIT_SECRETS variable is not really used by baseline tests. This change also
deleted the reference to GIT_SECRETS variable group.
* Removed the pre-test stage.
* Removed reference to GIT_SECRETS variable group
=> Remove pre-test and GIT_SECRETS from baseline test

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Test is no longer supported on mellanox asic because asic temperature is read from sdk sysfs rather than /run/hw-management/thermal/asic. TC will be updated and skip removed.
TC has to be temporary skipped until TC will be updated
Add skip 
Run TC, TC skipped
=> Added temporary skip to system health TC for MLX platforms

tests/tacacs/test_ro_disk.py
Fix ro disk test case generate garbled syslog and break loganalyzer issue.
Log rotate during ro disk may cause syslog file contains garbled characters.
These characters will break loganalyzer, to fix this issue, rotate again to cleanup syslog file.
- Microsoft ADO: 28149282
log rotate again after ro disk test case finish,
Fix ro disk test case generate garbled syslog and break loganalyzer issue.
=> Fix ro disk test case generate garbled syslog and break loganalyzer issue.

sdn_tests/pins_ondatra/tests/lacp_timeout_test.go, sdn_tests/pins_ondatra/tests/ondatra_test.bzl
- [sdn_tests]: Adding LACP time-out test to pins_ondatra.
Summary:
- Added LACP time-out test to pins_ondatra.
Build results:
INFO: Elapsed time: 845.904s, Critical Path: 216.33s
=> [sdn_tests]: Adding LACP time-out test to pins_ondatra.

sdn_tests/pins_ondatra/tests/lacp_timeout_test.go, sdn_tests/pins_ondatra/tests/link_event_damping_test.go, sdn_tests/pins_ondatra/tests/ondatra_test.bzl, sdn_tests/pins_ondatra/tests/port_debug_data_test.go
- [sdn_tests]: Adding port debug data test to pins_ondatra.
Summary:
- Added port debug data test to pins_ondatra.
Build result:
INFO: Elapsed time: 566.778s, Critical Path: 165.45s
=> [sdn_tests]: Adding port debug data test to pins_ondatra

sdn_tests/pins_ondatra/tests/BUILD.bazel, sdn_tests/pins_ondatra/tests/lacp_timeout_test.go, sdn_tests/pins_ondatra/tests/link_event_damping_test.go, sdn_tests/pins_ondatra/tests/module_reset_test.go, sdn_tests/pins_ondatra/tests/ondatra_test.bzl, sdn_tests/pins_ondatra/tests/port_debug_data_test.go
- [sdn_tests]: Adding module reset test to pins_ondatra.
Summary:
- Added module reset test to pins_ondatra.
Build result:
INFO: Elapsed time: 553.095s, Critical Path: 169.32s
=> [sdn_tests]: Adding module reset test to pins_ondatra.

ansible/roles/vm_set/tasks/docker.yml
Short-term workaround to avoid issue where testbed-cli.sh ... add-topo errored out with 'Not supported URL scheme http+docker' due to the update of the transitive dependency python requests through docker-py.
Summary:
=> Pin requests to version 2.31.0

tests/generic_config_updater/gu_utils.py, tests/generic_config_updater/test_dynamic_acl.py
Fixes a bug in GCU Dynamic ACL test where dualtor tests would periodically fail if the active DUT swapped to standby in the middle of test.  Applies ACL Rules on both TORs regardless of whether it is active-standby or active-active, causing packets to not get dropped.
Tested on a dualtor testbed that it was previously failed on, observed success.
=> Fix bug on Dualtor testbeds caused by muxcable switching from standby to active

sdn_tests/pins_ondatra/tests/installation_test.go
- [sdn_tests]: Adding Installation test to pins_ondatra.
Summary:
- Added Installation test to pins_ondatra.
Build results:
INFO: Elapsed time: 848.985s, Critical Path: 191.63s
=> [sdn_tests]: Adding Installation test to pins_ondatra.

sdn_tests/pins_ondatra/tests/inband_sw_interface_dual_switch_test.go, sdn_tests/pins_ondatra/tests/installation_test.go
- [sdn_tests]: Adding inband sw interface dual switch test to pins_ondatra.
Summary:
- Added inband sw interface dual switch test to pins_ondatra.
Build Result:
INFO: Elapsed time: 556.537s, Critical Path: 173.20s
=> [sdn_tests]: Adding inband sw interface dual switch test to pins_ondatra.

tests/tacacs/test_accounting.py
Increase check local log wait time and print debug info.
test_accounting failed because local log does not exist.
- Microsoft ADO: 27895350
Increase check local log wait time and print debug info.
Increase check local log wait time and print debug info.
=> [TACACS] Increase check local log wait time and print debug info.

tests/autorestart/test_container_autorestart.py
Summary:
We need to test if dhcp_server container auto restart will work, however the dhcp_server feature is disabled by default, we need to enable it before the test.
We need to test if dhcp_server container auto restart will work.
Enable dhcp_server feature before the test.
Run test on mx topo
=> [dhcp_server_test] support dhcp server container auto restarted test on mx topo

ansible/config_sonic_basedon_testbed.yml
Summary:
If any topology without any VMs, e.g. no T1s for T0 topology, the testbed-cli deploy-mg will fail, due to error below:
```text
TASK [find all interface names] *****************************************************************************************************************************************************************************
task path: /var/src/mgmt-int/ansible/config_sonic_basedon_testbed.yml:273
Sunday 19 May 2024  18:06:26 +0000 (0:00:00.021)       0:00:16.756 ************
fatal: [str3-7060x6-64pe-1]: FAILED! => {
"msg": "'interface_to_vms' is undefined"
}
```
This change is to fix the error above, when VM list is empty.
The fix is straightforward - to give it a default value that is an empty list when enumerating.
The change is run locally with topology with empty VMs, …
=> Fix sonic-mgmt testbed-cli interface_to_vms undefined failure.

ansible/roles/vm_set/library/vm_topology.py, ansible/templates/minigraph_dpg.j2
Summary:
When deploying any topology without the VM list as below, we will running into a few errors. And this PR is to fix these issues:
There are 2 issues are hitting, when deploying any topology without the VM list:
- Ansible Bind topology to VMs task task will fail, because the vm list is empty, but it is checking the VM base in the VM list.
- The generated minigraph will fail to load, because minigraph.py is not expecting any ACL interface with empty attached to list.
This change fixes both issue with adding the empty list checks in these 2 places.
Run the add-topo and deploy-mg locally, both works.
No.
N/A
N/A
=> Fix add-topo failure when deploying topology with empty VM list.

sdn_tests/pins_ondatra/tests/inband_sw_interface_dual_switch_test.go, sdn_tests/pins_ondatra/tests/installation_test.go
- [sdn_tests]: Adding GNMI inband sw interface dual switch LoopbackInCnts test.
Summary:
- Added GNMI inband sw interface dual switch LoopbackInCnts test.
Build results:
INFO: Elapsed time: 537.245s, Critical Path: 166.67s
=> [sdn_tests]: Adding GNMI inband sw interface dual switch LoopbackInCnts test.

tests/arp/files/ferret.conf.j2, tests/arp/files/ferret.py
In an effort to move/migrate test scripts from Python 2 to 3 this PR migrates the warm reboot management plane script `ferret.py` and `ferret.conf.j2` to Python 3. The configuration refers to the `python3` in the virtual environment.
Summary:
Fixes N/A
The warm reboot test scripts have been migrated to Python 3. The ferret script still runs in Python 2 environment. This PR migrates that to Py3.
- Run 2to3
- Modified script as struct packing handles bytes instead of str.
- Modified other affected parts to handle bytes directly
Ran warm reboot and warm reboot advanced tests on Dell S6100. Tests have passed successfully.
None
Existing test case.
Not applicable.
=> [tests/wr_arp] Migrate warm reboot management plane script ferret to py3

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
28150848
Many cases failed during teardown due to loganalyzer with below FRR related error messages.
The failure only happen on the device which runs slim image.
```
bgp#zebra[36]: [SHWNK-NWT5S][EC 100663304] No such command on config line 10: no fpm use-next-hop-groups
bgp#zebra[36]: [SHWNK-NWT5S][EC 100663304] No such command on config line 12: fpm address 127.0.0.1
ERR bgp#bgpd[50]: [P3GYW-PBKQG][EC 33554466] XXX [FSM] unexpected packet received in state OpenSent
ERR bgp#bgpd[50]: [MVZKX-EG443][EC 33554452] bgp_process_packet: BGP OPEN receipt failed for peer: XXX
ERR bgp#bgpd[50]: [P3GYW-PBKQG][EC 33554466] XXX [FSM] unexpected packet received in state OpenSent
ERR bgp#bgpd[50]: [P3GYW-PBKQG][EC 33554466] XXX [FSM] unexpected packet received in state OpenSent …
```
=> ignore FRR error messages on 202311 branch

ansible/roles/vm_set/tasks/docker.yml, ansible/roles/vm_set/tasks/main.yml
Summary:
In latest requests python package, would got error in some steps like add-topo and restart-ptf with message 'Not supported URL scheme http+docker'
We already have fix PR https://github.com/sonic-net/sonic-mgmt/pull/12910  in master branch to install stable requests version in docker.yml, but  once package_installation was set to false like restart-ptf, docker.yml would skip and report error again
Install stable requests version in main.yml after executing docker.yml to cover all scenario
=> Pin requests to version 2.31.0 in main.yml

tests/dualtor/test_ipinip.py
Summary:
Fixes #11744 
`test_encap_with_mirror_session` would invoke fixture `setup_mirror_session`, and it would invoke fixture `setup_uplink`. There are steps in fixture `setup_uplink`, which could restart teamd docker, it would lead `swss` and `syncd` docker exits.
If the autorestart is disabled in `test_pretest.py`, then `swss` and `syncd` will fail to restart, and then leads to test failure.
This PR fixed the issue by adding a fixture to enable container autorestart before the test running.
This PR is to enable feature autorestart before `test_encap_with_mirror_session`.
This PR fixed the issue by adding a fixture to enable container autorestart before the test running.
The change is verified by running `test_encap_with_mirror_session` after `test_disable_container_autorestart`.
``` …
```
=> Enable feature autorestart before test_encap_with_mirror_session

tests/qos/test_pfc_pause.py
Summary: Fix qos/test_pfc_pause.py for dualtor-aa
Fixes: [#100](https://github.com/aristanetworks/sonic-qual.msft/issues/100)
`qos/test_pfc_pause.py` fails on dualtor-aa
```
errors = dict()
for intf in results:
if len(results[intf]) != 2:
continue
pass_count = results[intf][0]
total_count = results[intf][1]
if total_count == 0:
continue
if pass_count &lt; total_count * PTF_PASS_RATIO_THRESH:
errors[intf] = results[intf]
if len(errors) &gt; 0:
test_errors += "Dscp: {}, Background Dscp: {}, errors occured: {}\n"\
.format(dscp, dscp_bg, " ".join(["{}:{}".format(k, v) for k, v in list(errors.items())]))
&gt;       pytest_assert(len(test_errors) == 0, test_errors)
E       Failed: Dscp: [3], Background Dscp: 4, errors occured: Ethernet12:[0, 20]
E       Dscp: [3], Background Dscp: 0, errors …
```
=> Fix qos/test_pfc_pause.py for dualtor-aa

tests/acl/test_acl.py
Summary:
`test_acl.py` is failing on `t1-32-lag` because the port selection mechanism is not correct. All portchannels should be selected as testing port as all ports are in LAG in this topology.
```
{"changed": true, "cmd": ["config", "acl", "add", "table", "DATA_INGRESS_IPV4_TEST", "L3", "-s", "ingress", "-p", "Ethernet104,Ethernet112,Ethernet120,Ethernet128,Ethernet136,Ethernet144,Ethernet152,Ethernet160"], "delta": "0:00:00.492203", "end": "2024-05-13 20:35:37.842050", "failed": true, "msg": "non-zero return code", "rc": 2, "start": "2024-05-13 20:35:37.349847", "stderr": "Usage: config acl add table [OPTIONS] <table_name> <table_type>\nTry \"config acl add table -h\" for help.\n\nError: Failed to parse ACL table config: exception=Cannot bind ACL to specified port Ethernet160", …
```
=> Support new topology t1-32-lag in acl test

ansible/roles/test/files/helpers/remove_ip.sh, tests/bgp/conftest.py, tests/scripts/remove_ip.sh, tests/vrf/test_vrf.py
Summary:
Applying the fix in https://github.com/sonic-net/sonic-mgmt/pull/11779 to all tests
=> Limit IP addr flushes to global scope IPs

tests/common/fixtures/advanced_reboot.py
This allows the ptf exception to be reported in the Summary field of the V2TestCases table in Kusto.
ADO: 28078972
Summary:
Surface more information in our test reporting infrastructure to aid in debugging
Added more information to a pytest assertion.
Artificially added an exception to the try-except block and saw that it was printed out in the pytest assertions.
=> Include advanced-reboot ptf exception in pytest assertion

sdn_tests/pins_ondatra/tests/BUILD.bazel, sdn_tests/pins_ondatra/tests/inband_sw_interface_dual_switch_test.go, sdn_tests/pins_ondatra/tests/installation_test.go
- [sdn_tests]: Adding GNMI inband sw interface dual switch LoopbackOutCnts test.
Summary:
- Added GNMI inband sw interface dual switch LoopbackOutCnts test.
Build results:
INFO: Elapsed time: 534.447s, Critical Path: 161.66s
=> [sdn_tests]: Adding GNMI inband sw interface dual switch LoopbackOutCnts test.

.azure-pipelines/run-test-elastictest-template.yml
Summary:
Baseline test will run a batch of PR tests, and in baseline test, test plan in same platform will run in 1 test job in azure devops.
In current logic, once a test plan fails, the test job would catch the sys.exit code and cancel following steps, but we want it only cancel following steps when all test plans fail in the test job
Use set -o to continue bash command when fails, get the return code of polling test plan status, if all polling results fail, raise exit code to cancel following steps
=> [Baseline] Fix 1 test plan fail may cancel others issue

tests/ssh/test_ssh_limit.py
Summary:
Current failure summary is `Failed: None` for test_ssh_limit, it doesn't give us useful information about why it fails.
Add detailed reason for assert failure in pytest_assert.
Add useful information about failed reason.
Add the message parameter in pytest_assert
Run ssh.test_ssh_limit.
=> Add detailed and meaningful reason for assert failure in test_ssh_limit

sdn_tests/pins_ondatra/tests/gnmi_get_modes_test.go
- [sdn_tests]:Adding GNMI Get Modes test to pins_ondatra.
Summary:
- Added GNMI Get Modes test to pins_ondatra.
> INFO: Elapsed time: 527.504s, Critical Path: 140.75s
> INFO: 975 …
=> [sdn_tests]:Adding GNMI Get Modes test to pins_ondatra.

sdn_tests/pins_ondatra/tests/inband_sw_interface_test.go
- [sdn_tests]: Adding inband sw interface test to pins_ondatra.
Summary:
- Added inband sw interface test to pins_ondatra.
Build Result:
```
INFO: Elapsed time: 875.973s, Critical Path: 212.94s
```
=> [sdn_tests]: Adding inband sw interface test to pins_ondatra.

tests/route/test_forced_mgmt_route.py
Fix test_update_forced_mgmt failed because check interfaces-config status with systemctl take too much time.
Check interfaces-config status with systemctl some times take 45 seconds, however the wait timeout is 10 seconds, which cause test case break:
13/05/2024 23:01:03 base._run                                L0071 DEBUG  | /var/src/sonic-mgmt_vms21-t0-2700_646f1402735219c3e5444094/tests/common/devices/multi_asic.py::_run_on_asics#128: [] AnsibleModule::command, args=["sudo systemctl show --no-pager interfaces-config -p ExecMainExitTimestamp --value"], kwargs={}
13/05/2024 23:01:45 base._run                                L0108 DEBUG  | /var/src/sonic-mgmt_vms21-t0-2700_646f1402735219c3e5444094/tests/common/devices/multi_asic.py::_run_on_asics#128: [] AnsibleModule::command Result => …
=> Fix test_update_forced_mgmt failed because check interfaces-config status with systemctl take 45 seconds.

tests/common/helpers/portchannel_to_vlan.py
Summary:
Microsoft ADO: 28179425
show_techsupport test failed for ACL issue.
If we run po2vlan test before show_techsupport, ACL rule configuration will be broken.
"config replace" is not reliable, so I use config_reload to recover configuration.
Run po2vlan end2end test and show_techsupport end2end test.
=> Use config reload to recover po2vlan config

ansible/library/announce_routes.py
There is a flaky issue in testcase `test_stress_routes.py` `ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))` in baseline test. 
Regarding to some articles
[https://stackoverflow.com/questions/383738/104-connection-reset-by-peer-socket-error-or-when-does-closing-a-socket-resu](https://stackoverflow.com/questions/383738/104-connection-reset-by-peer-socket-error-or-when-does-closing-a-socket-resu)
[https://stackoverflow.com/questions/52051989/requests-exceptions-connectionerror-connection-aborted-connectionreseterro](https://stackoverflow.com/questions/52051989/requests-exceptions-connectionerror-connection-aborted-connectionreseterro)
Adding sleep time may fix this issue. This PR is just to have a try. 
Summary: …
=> Fix 104 connection issue in testcase `test_stress_routes.py`. 

ansible/roles/test/tasks/pfc_wd/functional_test/timer_test.yml, tests/bgp/test_bgp_peer_shutdown.py, tests/pfcwd/test_pfcwd_timer_accuracy.py
In the recent PR https://github.com/sonic-net/sonic-buildimage/pull/18099 in `sonic-buildimage`, we changed the timestamp format of the syslog message (`ActionFileDefaultTemplate`) for latest and some previous SONiC image versions. More specifically, we added the "year" field at the front of each syslog message:
**Before**
```bash
admin@str3-dut:~$ sudo tail -f /var/log/syslog
May 29 02:47:40.345257 str3-dut INFO acms#start.py: start: check_bootstrap_status: Checking bootstrap status
May 29 02:47:40.345257 str3-dut INFO acms#start.py: start: check_bootstrap_status: /var/opt/msft/client/dsms.conf file not found!
May 29 02:47:40.346080 str3-dut INFO acms#start.py: start: main: acms_secrets.ini copied to /var/opt/msft/client
May 29 02:47:40.346236 str3-dut INFO acms#start.py: start: main: …
```
=> fix: update syslog timestamp parsing logic

tests/ip/test_mgmt_ipv6_only.py
Summary:
Fixes TACACS failures in test_mgmt_ipv6_only module.
It's observed that tacacs_plus process may crash when receiving ipv6 tacacs requests. Need a way to workaround it.
Similar issue in tacacs/test_ro_user has been fixed in https://github.com/sonic-net/sonic-mgmt/pull/12819
Using the similar method to restart tacacs_plus process if it fails.
Verified in both virtual testbed and physical testbed. Not seeing tacacs failures anymore.
=> [TACACS] Improve IPv6 TACACS cases to workaround tacacs_plus server crash issue

tests/generic_config_updater/test_dynamic_acl.py
Summary:
Clear PTFhost before running GCU Dynamic ACL tests
Fixing an error that seems to only appear when tested as a part of nightly testing suite due to stale ptfconfig
Added fixture to remove ip addresses from ptfhost at start of test
Manually ran on testbed and observed test pass
=> Fix GCU Dynamic ACL ARP bug caused by stale ip config in PTFhost

ansible/roles/vm_set/library/vm_topology.py
Summary:
This PR is intended to add flow rules for OSPF and BFD traffic from an external interface to a VM and a PTF container
To allow OSPF and BFD traffic between DUT and the neighboring devices in t0 or t1 topology by adding flow rules.
By adding flow rules to sonic-mgmt/ansible/roles/vm_set/library/vm_topology.py file.
=> Added flow rules for OSPF and BFD

docs/tests/pytest.run.md, tests/run_tests.sh
Summary:
This change added a "-C" command option to support filtering the test cases by test case name.
When test failed, it is fairly frequently to only rerun one of the failed test cases for deep analysis. However, our current run_tests.sh only support filtering tests cases on file level, not test case level.
This change adds a "-C" command operation to filter the test cases by name. It leverages the "-k" option in pytest to achieve the filtering.
To add the filter, here is an example:
```bash
./run_tests.sh -i ../ansible/<inv>,../ansible/veos -n <testbed> -u -m individual -a False -l debug -c qos/test_qos_sai.py -C "testParameter[single_asic]"
```
Have run the test locally, and correctly filtered out the test cases.
N/A
N/A
both run_tests.sh help and doc are updated.
=> Add test filter in run_tests.sh.

tests/qos/tunnel_qos_remap_base.py
Summary: Fix string to integer type casting issue in qos/tunnel_qos_remap_base.py::check_queue_counter
Fixes # [aristanetworks/sonic-qual.msft#131](https://github.com/aristanetworks/sonic-qual.msft/issues/131)
In `qos/tunnel_qos_remap_base.py::check_queue_counter` method, we are trying to convert string counter value to an integer, but the string can contain a comma (for numbers > 999, Ex: "1,000"), which will lead to error `invalid literal for int() with base 10`.
Remove commas (if any) in the counter (string) before trying to convert it to integer.
Ran the test `qos/test_tunnel_qos_remap.py` and verified there is no breakage with the fix.
=> Remove comma from counter string before type casting to integer

sdn_tests/pins_ondatra/tests/gnoi_reboot_test.go
- [sdn_tests]: Adding Gnoi Reboot tests to pins_ondatra.
Summary:
- Added Gnoi Reboot tests to pins_ondatra.
Build Results:
```
INFO: Elapsed time: 576.563s, Critical Path: 188.60s
INFO: …
```
=> [sdn_tests]: Adding Gnoi Reboot tests to pins_ondatra.

sdn_tests/pins_ondatra/tests/gnmi_subscribe_modes_test.go
- [sdn_tests]:Adding GNMI subscribe modes test to pins_ondatra.
Summary:
- Adding GNMI subscribe modes test to pins_ondatra.
github.com/openconfig/gnsi/acctz/acctz.proto:36:1: warning: Import github.com/openconfig/gnsi/version/version.proto is …
=> [sdn_tests]:Adding GNMI subscribe modes test to pins_ondatra.

tests/common/helpers/portchannel_to_vlan.py
This PR helps add Nokia-7215-A1 support for test_fdb.py testcases 
This PR helps add support for Nokia-7215-A1 in test_fdb.py testcases. Currently it is skipped as there is no support.
Added arm64-nokia_ixs7215_52xb-r0 in setup_po2vlan in portchannel_to_vlan.py.
Ran the entire fdb suite to see it is not skipped.
NA
NA
=> added Nokia-7215-A1 support for fdb testcases

tests/platform_tests/api/test_watchdog.py, tests/platform_tests/api/watchdog.yml
This PR is for adding Nokia-7215-A1 platform support for test_watchdog.py testcases.
- [] 202305
Currently, there is no support for platform_tests/api/test_watchdog.py testcases for Nokia-7215-A1 platform. This PR helps add support for these testcases.
Added platform specific condition for arm64-nokia_ixs7215_52xb-r0 in test_watchdog.py to arm/disarm watchdog.
Ran test_watchdog.py testcases and verified that all the testcases pass
NA
NA
=> Add Nokia-7215-A1 platform support for watchdog api testcases

tests/common/helpers/portchannel_to_vlan.py
Summary:
Microsoft ADO: 28179425
Backport https://github.com/sonic-net/sonic-mgmt/pull/12998
show_techsupport test failed for ACL issue.
If we run po2vlan test before show_techsupport, ACL rule configuration will be broken.
"config replace" is not reliable, so I use config_reload to recover configuration.
Run po2vlan end2end test and show_techsupport end2end test.
=> [202205] Use config reload to recover po2vlan config

tests/common/plugins/sanity_check/checks.py
Summary:
If a topology doesn't have any VMs, e.g. T0 without any uplinks, it is not using BGP sessions in the setup. However, the current pytests will always think the BGP is used, hence checking the BGP status.
This PR is trying to address this issue, by checking the topology setup before running the BGP status sanity checks.
If a topology doesn't have any VMs, e.g. T0 without any uplinks, it is not using BGP sessions in the setup. However, the current pytests will always think the BGP is used, hence checking the BGP status.
This will cause all tests failing for this type of topologies, because of sanity check is failing.
This PR adds a topology check before the BGP sanity checks. If this type of topology is detected, we skip the BGP status checks.
Have run tests with existing non-BGP …
=> Fix BGP status sanity check failure when topology doesn't have any VMs.

.azure-pipelines/pr_test_scripts.yaml, tests/database/test_db_config.py, tests/kvmtest.sh
Add a test script to check that the redis config for the save setting, database count, and unix socket are correct. This can be extended to check for other config options.
Summary:
This is in response to sonic-net/sonic-buildimage#18979 and sonic-net/sonic-buildimage#18108, where with the database container upgrade to Bookworm, redis DB was configured to save to disk by default. This then caused issues in multi-ASIC setups.
Tested on T0 KVM with sonic-net/sonic-buildimage#18979 applied.
=> Add some tests to verify Redis DB configuration

sdn_tests/pins_ondatra/tests/ethcounter_sw_single_switch_test.go, sdn_tests/pins_ondatra/tests/gnmi_subscribe_modes_test.go
- [sdn_tests]:Adding single switch Ethernet Counter test to pins_ondatra.
Summary:
- Adding single switch Ethernet Counter test to pins_ondatra.
INFO: Elapsed time: 317.554s, Critical …
=> [sdn_tests]:Adding single switch Ethernet Counter test to pins_ondatra.

sdn_tests/pins_ondatra/tests/lacp_test.go
- [sdn_tests]:Adding LACP port channel test.
Summary:
- Added LACP port channel test.
Build results:
```
INFO: Elapsed time: 856.833s, Critical Path: 194.10s …
```
=> [sdn_tests]:Adding LACP port channel test.

sdn_tests/pins_ondatra/tests/gnmi_get_modes_test.go
- [sdn_tests]:Adding gNMI Get test for Data Type for paths when 'non-empty and empty subtree is returned' to pins_ondatra.
Summary:
- Added gNMI Get test for Data Type for paths when 'non-empty and empty subtree is returned' to pins_ondatra.
> …
=> [sdn_tests]:Adding gNMI Get test for Data Type for paths when 'non-empty and empty subtree is returned' to pins_ondatra.

ansible/devutil/device_inventory.py, ansible/devutil/testbed.py, ansible/ssh_session_gen.py
Summary:
Currently, the SSH repo generator will only generate the session files for DUT and PTF in testbeds, but not all the other devices, such as fanout switches and servers.
This change is to add this support in it.
Currently, the SSH repo generator will only generate the session files for DUT and PTF in testbeds, but not all the other devices, such as fanout switches and servers.
This change updates the ssh_session_gen.py to parse the device inventory csv files, so we can generate all sessions for it.
Run it locally, and it outputs the session files as below. Besides the testbeds, now we also outputs the devices folder:
No.
N/A.
No changes on how to use it. N/A.
=> Make SSH session generator support generating session files for all devices, like fanout switches.

tests/gnmi/conftest.py
Summary:
Improve GNMI fixture for NTP check.
Remove assert, and generate warning instead.
=> Generate warning for NTP issue

sdn_tests/pins_ondatra/tests/ethcounter_sw_single_switch_test.go
- [sdn_tests]:Adding Ethernet Counter subinterface index and unicast out-packets test to pins_ondatra.
Summary:
- Added Ethernet Counter subinterface index and unicast out-packets test to pins_ondatra.
> github.com/openconfig/gnsi/pathz/pathz.proto:25:1: warning: Import …
=> [sdn_tests]:Adding Ethernet Counter subinterface index and unicast out-packets test to pins_ondatra.

tests/common/dualtor/dual_tor_utils.py, tests/conftest.py
Summary:
We need to disable `icmp_responder` for qos tests.
-> Hence dualtor testbed will always be unhealthy. 
-> Per design timed oscillation is triggered.
-> It causes some tests to be flaky. 
Adding a fixture to disable the oscillation knob as a workaround. 
Ran a random test case again the testbed, no more toggle after the fixture is called. 
```
May 29 17:00:57.019500 NOTICE mux#linkmgrd: DbInterface.cpp:238 handlePostSwitchCause: Ethernet68: post last switch cause Timed_Oscillation
May 29 17:11:04.324339 NOTICE mux#linkmgrd: DbInterface.cpp:238 handlePostSwitchCause: Ethernet68: post last switch cause Timed_Oscillation
May 29 17:21:11.458202 NOTICE mux#linkmgrd: DbInterface.cpp:238 handlePostSwitchCause: Ethernet68: post …
```
=> [dualtor][active-standby] disable timed oscillation 

tests/configlet/util/common.py
Summary:
This PR is to skip comparing keys in table `TUNNEL_DECAP_TERM_TABLE` in `test_add_rack`.
The keys need to be skipped because the test shutdown a port on the device, and then reload it. Then the entry in table ``TUNNEL_DECAP_TERM_TABLE` for this particular admin down port is lost. 
The error message is 
```
11:18:00 helpers.log_msg                          L0060 ERROR  | /var/src/sonic-mgmt/tests/configlet/util/common.py:318:11:18:00 patch_add: app-db.json: Missing key: TUNNEL_DECAP_TERM_TABLE:IPINIP_V6_TUNNEL:fc00::41
11:18:00 helpers.log_msg                          L0060 ERROR  | /var/src/sonic-mgmt/tests/configlet/util/common.py:318:11:18:00 patch_add: app-db.json: Missing key: TUNNEL_DECAP_TERM_TABLE:IPINIP_TUNNEL:10.0.0.32
``` 
Related PR …
=> Skip keys in table TUNNEL_DECAP_TERM_TABLE for db_cmp 

tests/clock/conftest.py
Summary:
This PR is to skip test modules in `tests/clock` if `ntp_server` is not provided.
The test is consistently failing in nightly test because `ntp_server` is not specified for this particular test case.
```
UsageError: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: the following arguments are required: --ntp_serve
``` 
This PR is to skip test modules in `tests/clock` if `ntp_server` is not provided.
1. Change `ntp_server` to optional argument
2. Skip the test if `net_server` is not provided. This is aligned with the comment.
The change is verified on a physical testbed. The test cases are skipped.
```
collected 3 items …
```
=> Skip test_clock if ntp_server is not provided

sdn_tests/pins_ondatra/tests/lacp_test.go
- [sdn_tests]: Adding LACP tests [add/remove interface into port channel] to pins_ondatra.
Summary:
- Added LACP tests [add/remove interface into port channel] to pins_ondatra.
```
INFO: …
```
=> [sdn_tests]: Adding LACP tests [add/remove interface into port channel] to pins_ondatra.

ansible/group_vars/sonic/variables
Summary: Add the Arista BTHD (Arista-7060DX5-32) and CTD (Arista-7060DX5-64S) HWSKUs to TH4 ansible variables list.
Add the missing HWSKUs for Arista BTHD and CTD platforms.
Built the image and installed it on the product.
Arista-7060DX5-32 and Arista-7060DX5-64S.
=> [Arista] Add BTHD and CTD HW SKUs

tests/common/fixtures/duthost_utils.py, tests/system_health/test_system_health.py
For mellanox device, skip asic mock, because the asic soft link has been moved to sdk sysfs, and there is no way to mock asic.
Summary:
Skip asic mock on mellanox device
Skip asic mock when device is mellanox
Run test on mellanox device
Mellanox
Any
=> [Mellanox] Skip asic mock in test_device_checker for mellanox device

tests/iface_loopback_action/conftest.py
Summary:
The test cases in `test_iface_loopback_action.py` is failing consistently on some testbed when the leaf-fanout is Mellanox and running SONiC. This is because the test sends packets with Vlan tag for testing, while TPID is not supported on Mellanox if running SONiC OS.
So the test needs to be skipped in the above setup.
This PR is to skip  `test_iface_loopback_action.py` if the leaf-fanout is Mellanox and running SONiC. 
Add a fixture to check OS and ASIC of leaf-fanout switch.
```
collected 3 items …
```
=> Skip iface loopback test if Leaf-fanout switch is running SONiC and Mellanox ASIC 

tests/qos/qos_sai_base.py
Summary:
Fix the qos/test_qos_sai.py test, where it is missing the new topo_t1-32-lag T1 topo
Make the tests more inclusive.
Adding the topo name to the topo list.
Tested it on hardware to verify.
=> Fix qos/test_qos_sai.py test for new T1 topo

tests/qos/test_pfc_pause.py
Summary:
28179409
case failure due to below error message.
"  File \"/root/ptftests/py3/pfc_wd_background_traffic.py\", line 40",
"    print(f\"traffic from {src_port} to {dst_port}: {queue} \")",
The case use CMD ptf to run the script. The default python version in ptf is python2, which is not support f string.
then cause the issue.
Better to call "ptf_runner" function and use the input parameter is_python3=True.
But in this case, it needs to check the output of the cmd ptf, could not call the "ptf_runner" function directly.
add a workaround to check the ptf in python3 first, if exist, call ptf in python3.
Run the original case.
=> use python3 ptf cmd for case test_no_pfc

tests/telemetry/test_telemetry.py
This test is checking that the number of buffer queue counters from telemetry point of view is inline when using create_only_config_db_counters optimization.
Summary:
Accompanies "Fix SNMP dropping some of the queue counter when create_only_config_db_buffers is set to true" (https://github.com/sonic-net/sonic-snmpagent/pull/303) which fixes the issue: "The feature "polling only configured ports buffer queue" will break SNMP" (https://github.com/sonic-net/sonic-buildimage/issues/17448).
Accompanies "Test polling only configured buffer queue counters" https://github.com/sonic-net/sonic-mgmt/pull/11941
To enhance the bug fix mentioned above, solving an issue with buffer queue counters optimization.
- Set "create_only_config_db_buffers" to true in config db, to create only relevant counters
- …
=> Add buffer queue counters test case to telemetry test

tests/pc/test_lag_2.py
For chassis, link-up after after shutdown/no shutdown on lag member often takes longer than the test timeout resulting in failure.  Fix by increasing the link-up timeout to 3x original value.
Summary:
Run test in our internal environment and confirm increased timeout is required.
=> [sonic-mgmt] Increase link-up timeout for test_lag_2 test_lag_db_status()

tests/conftest.py
Summary: All ixia chassis are getting defaulted to eos OS, thereby setting up fanouthosts which is not true in the case of traffic generator testbeds. This is a bugfix to ignore the setup of fanouthost objects for the ixia chassis.
Bugfix for running tgen tests
Skip setup of fanouthosts when ixia chassis is involved
Tested on lab testbed
=> [Snappi] Bugfix to ignore ixia chassis for setting up fanouthosts

tests/common/snappi_tests/traffic_generation.py, tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py, tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py, tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py, tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py, tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py, tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py, tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py, tests/snappi_tests/multidut/pfc/test_lossless_response_to_external_pause_storms.py, tests/snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py, tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless.py, tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless_lossy.py, tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossy.py
Summary: Removing flawed config_reload and fixing the verify_m2o_oversubscribtion_results fixture from the traffic_generator.py
1.Removing flawed config_reload from ecn and pfc cases as handle by `conftest.py`
2. Modifying oversubscription verification from the multidut rdma cases inorder to incorporate the latest change
3. Fixed the handling of API `run_traffic`
Removed the config reload fixture and added extra value to unpack from run_traffic() fixture from traffic_generator.py
=> Fixing Oversubscription verification and removing config_reload from ecn

ansible/group_vars/sonic/variables
Summary: Add the Arista Quicksilver HWSKUs (Arista-7060X6-64DE and Arista-7060X6-64PE and related variants) to the new TH5 ansible variables list.
Add the missing HWSKUs for Arista Quicksilver platforms.
Built the image and installed it on the product.
Arista-7060X6-64DE
Arista-7060X6-64DE-64x400G
Arista-7060X6-64DE-256x200G
Arista-7060X6-64PE
Arista-7060X6-64PE-64x400G
Arista-7060X6-64PE-128x400G
Arista-7060X6-64PE-256x200G
=> [Arista] Add Quicksilver HW SKUs

tests/drop_packets/test_configurable_drop_counters.py
Summary:
Fixes [#133](https://github.com/aristanetworks/sonic-qual.msft/issues/133)
Fix the failure of the test 'drop_packets/test_configurable_drop_counters.py' on dualtor testbeds
Toggled all mux simulator ports to the selected tor before sending traffic
Tested on Arista-7050 and Arista-7260 platforms
=> Fix 'drop_packets/test_configurable_drop_counters.py' on dualtor

tests/route/test_forced_mgmt_route.py
Summary: Fix route/test_forced_mgmt_route.py failures during teardown
Fixes # [aristanetworks/sonic-qual.msft#113](https://github.com/aristanetworks/sonic-qual.msft/issues/113)
Test is tampering the running config of the duthost and leaving the config in this state. This is causing failures during teardown `core_dump_and_config_check` is failing during `config_db_check`. 
Also seeing loganalyzer failures with symptom similar to ` ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:449 Invalid sai_api_t 50 passed to sai_api_query ...` (mostly due to config changes)
Perform "config_reload" with the backup config as part of fixture teardown (`backup_restore_config`).
Test is passing consistently with the fix (verified on Arista-7260CX3-C64), verified on 202305 and 202311 branches.
=> Fix route/test_forced_mgmt_route.py

sdn_tests/pins_ondatra/tests/ethcounter_sw_single_switch_test.go
- [sdn_tests]: Adding Ethernet Counter SubInterface IPV6 In-PKTs test to pins_ondatra.
Summary:
- Added Ethernet Counter SubInterface IPV6 In-PKTs test to pins_ondatra.
> INFO: …
=> [sdn_tests]: Adding Ethernet Counter SubInterface IPV6 In-PKTs test to pins_ondatra.

sdn_tests/pins_ondatra/tests/lacp_test.go
- [sdn_tests]: Adding LACP tests [port down event & if members are partially configured] to pins_ondatra.
Summary:
- Added LACP tests [port down event & if members are partially configured] to pins_ondatra.
> github.com/openconfig/gnsi/pathz/pathz.proto:25:1: warning: Import …
=> [sdn_tests]: Adding LACP tests [port down event & if members are partially configured] to pins_ondatra.

ansible/roles/fanout/tasks/fanout_sonic.yml, ansible/roles/fanout/tasks/sonic/fanout_sonic_202311.yml, ansible/roles/fanout/templates/sonic_deploy_202311.j2
Enable TPID feature to allow Nvidia Switches to become fanouts.
1. Update password of SONiC fanout switch
2. Add fanout deploy jinja file
3. Add fanout deploy operations
Summary:
Support work as SONiC fanout switch for mellanox switch.
Add ansible playbook and j2 files.
Run it in internal regression for weeks.
It is tested on SN4700, SN4600C, SN4600
=> [Mellanox] Add SONiC as fanout switch

ansible/roles/test/files/tools/loganalyzer/loganalyzer.py
Summary:
Loganalyzer takes an unusally long time to test syslog messages to see if they match some expected regex. This is because of using `findall` (search anywhere in the string for all instances) instead of `match` (search from the starting of the string). The time it takes to search for different starting positions of a match appears to be expensive.
Most of our match strings have a `.*` at the beginning anyways, and we're not returning the exact matching substrings (only whether or not the regex matches), so change to using `match`.
=> Optimize loganalyzer regex matching by using match() instead of findall()

tests/iface_loopback_action/conftest.py
Summary:
This PR is to fix an issue brought by PR https://github.com/sonic-net/sonic-mgmt/pull/12931.
```
>       raise AttributeError(
"'%s' object has no attribute '%s'" % (self.__class__, module_name)
)
E       AttributeError: '<class 'tests.common.devices.eos.EosHost'>' object has no attribute 'facts'
```
The issue is because if the leaf fanout is not running SONiC, then the host has no attribute `facts`.
This PR addressed the issue by checking OS first and the ASIC check is bypassed if OS is not SONiC.
This PR is to fix an issue caused by PR https://github.com/sonic-net/sonic-mgmt/pull/12931.
This PR addressed the issue by checking OS first and the ASIC check is bypassed if OS is not SONiC.
The change is verified on a physical testbed **without** leaf fanout running SONiC.
``` …
```
=> Fix ASIC check on Non-SONiC leaf fanout

tests/tacacs/utils.py
Summary:
We are seeing unstable test result in `test_ro_user_ipv6_only` with below error.
```
failed on setup with "tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{"changed": true, "cmd": "ping 2603:x -c 1 -W 3", "delta": "0:00:03.016826", "end": "2024-06-05 21:51:23.791447", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2024-06-05 21:51:20.774621", "stderr": "", "stderr_lines": [], "stdout": "PING 2603:x(2603:x) 56 data bytes\n\n--- 2603:x ping statistics ---\n1 packets transmitted, 0 received, 100% packet loss, time 0ms", "stdout_lines": ["PING 2603:x(2603:x) 56 data bytes", "", "--- 2603:x ping statistics ---", "1 packets transmitted, 0 received, 100% packet loss, time 0ms"]}"
```
It's because the random packet drop between DUT …
=> Stabilize setup_tacacs_client

ansible/group_vars/sonic/variables, ansible/module_utils/port_utils.py
Summary: Add port definition for Arista 7060X6 HwSkus in port_utils
Allow add-topo to properly generate a minigraph on these new 7060X6 HwSku
Also register these HwSku into the `broadcom_<asic>_hwskus` to allow some tests to pass.
Added the definitions of the 7060X6 HwSkus in the `port_utils.py` and `variables` files
Ran t0 and t1 topologies on these HwSkus
Specific to Arista 7060X6
=> [Arista] Add port definitions for 7060X6 HwSkus in port_utils

sdn_tests/pins_ondatra/infrastructure/testhelper/gnmi.go, sdn_tests/pins_ondatra/infrastructure/testhelper/gnoi.go, sdn_tests/pins_ondatra/infrastructure/testhelper/lacp.go, sdn_tests/pins_ondatra/infrastructure/testhelper/p4rt.go, sdn_tests/pins_ondatra/tests/BUILD.bazel, sdn_tests/pins_ondatra/tests/gnmi_get_modes_test.go, sdn_tests/pins_ondatra/tests/gnmi_set_get_test.go, sdn_tests/pins_ondatra/tests/lacp_timeout_test.go, sdn_tests/pins_ondatra/tests/link_event_damping_test.go, sdn_tests/pins_ondatra/tests/platforms_hardware_component_test.go, sdn_tests/pins_ondatra/tests/port_debug_data_test.go
- [sdn_tests]:Fix for build failures.
Summary:
Fixes # Fix for build failures.
- [-] Bug fix
- HLD - SDN Test framework for SONiC - https://github.com/sonic-net/sonic-mgmt/pull/11771
=> [sdn_tests]:Fix for build failures.

sdn_tests/pins_ondatra/tests/gnmi_helper.go
- [sdn_tests]:Adding GNMI Stress Helper to Pins_ondatra.
Summary:
- Added GNMI Stress Helper to Pins_ondatra.
Build Result:
```
INFO: From Generating Descriptor Set proto_library …
```
=> [sdn_tests]:Adding GNMI Stress Helper to Pins_ondatra.

sdn_tests/pins_ondatra/tests/ethcounter_sw_single_switch_test.go
- [sdn_tests]: Adding Ethernet Counter In-Discards Check test to pins_ondatra.
Summary:
- Added Ethernet Counter In-Discards Check test to pins_ondatra.
> INFO: Elapsed time: …
=> [sdn_tests]: Adding Ethernet Counter In-Discards Check test to pins_ondatra.

sdn_tests/pins_ondatra/tests/gnmi_wildcard_subscription_test.go
- [sdn_tests]: Adding WCOnChangeAdminStatus to pins_ondatra.
Summary:
- Added WCOnChangeAdminStatus to pins_ondatra.
Build Results:
```
INFO: Elapsed time: 805.401s, Critical Path: 179.83s
INFO: 975 processes: …
```
=> [sdn_tests]: Adding WCOnChangeAdminStatus to pins_ondatra.

sdn_tests/pins_ondatra/tests/mgmt_interface_test.go
- [sdn_tests]:Adding mgmt_interface tests to pins_ondatra.
Summary:
- Added mgmt_interface tests to pins_ondatra.
Build Result:
```
INFO: From Generating Descriptor Set proto_library …
```
=> [sdn_tests]:Adding mgmt_interface tests to pins_ondatra.

sdn_tests/pins_ondatra/tests/gnmi_set_get_test.go
- [sdn_tests]: Adding GNMI set delete multiple/invalid leaf tests and delete replace order test in pins-ondatra.
Summary:
- Added GNMI set delete multiple/invalid leaf tests and delete replace order test in pins-ondatra.
> github.com/openconfig/gnsi/certz/certz.proto:22:1: warning: Import …
=> [sdn_tests]: Adding GNMI set delete multiple/invalid leaf tests and delete replace order test in pins-ondatra.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skipped the VoQ test modules on Cisco8800 platform
Skip VoQ test cases on Cisco 8800
=============================================================================== short test summary info ================================================================================
SKIPPED [17] voq/test_voq_ipfwd.py: Cisco 8800 doesn't support voq tests
SKIPPED [16] voq/test_voq_ipfwd.py:614: Cisco 8800 doesn't support voq tests
SKIPPED [16] voq/test_voq_ipfwd.py:645: Cisco 8800 doesn't support voq tests
SKIPPED [16] voq/test_voq_ipfwd.py:682: Cisco 8800 doesn't support voq tests
SKIPPED [16] voq/test_voq_ipfwd.py:720: Cisco 8800 doesn't support voq tests
SKIPPED [16] voq/test_voq_ipfwd.py:764: Cisco 8800 doesn't support voq tests
SKIPPED [12] voq/test_voq_ipfwd.py:881: Cisco …
=> Skip VoQ test cases on Cisco 8800

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Skipped the VoQ test modules on Cisco8800 platform
Summary:
Skipped the VoQ test modules on Cisco8800 platform
=============================================================================== short test summary info ================================================================================
SKIPPED [17] voq/test_voq_ipfwd.py: Cisco 8800 doesn't support voq tests
SKIPPED [16] voq/test_voq_ipfwd.py:614: Cisco 8800 doesn't support voq tests
SKIPPED [16] voq/test_voq_ipfwd.py:645: Cisco 8800 doesn't support voq tests
SKIPPED [16] voq/test_voq_ipfwd.py:682: Cisco 8800 doesn't support voq tests
SKIPPED [16] voq/test_voq_ipfwd.py:720: Cisco 8800 doesn't support voq tests
SKIPPED [16] voq/test_voq_ipfwd.py:764: Cisco 8800 doesn't support voq tests
SKIPPED [12] …
=> [202305]Skip voq test cases on Cisco 8800 (#13197)

sdn_tests/pins_ondatra/tests/system_paths_test.go
- [sdn_tests]: Adding System paths test to pins-ondatra.
Summary:
- Added System paths test to pins-ondatra.
> INFO: Elapsed time: 315.808s, Critical Path: 118.76s
> INFO: 975 …
=> [sdn_tests]: Adding System paths test to pins-ondatra.

sdn_tests/pins_ondatra/tests/gnmi_stress_test.go, sdn_tests/pins_ondatra/tests/platforms_hardware_component_test.go
- [sdn_tests]:Adding GNMI stress test to pins_ondatra.
Summary:
- Added GNMI stress test to pins_ondatra.
Build Result:
```
github.com/openconfig/gnsi/pathz/authorization.proto:43:1: warning: Import github.com/openconfig/gnsi/version/version.proto …
```
=> [sdn_tests]:Adding GNMI stress test to pins_ondatra.

sdn_tests/pins_ondatra/tests/gnmi_set_get_test.go, sdn_tests/pins_ondatra/tests/system_paths_test.go
- [sdn_tests]:Adding system paths tests to pins_ondatra.
Summary:
- Added system paths tests to pins_ondatra.
Build Result:
```
~/JUNE-10-3/sonic-mgmt/sdn_tests/pins_ondatra$ bazel build tests:system_paths_test 
INFO: Analyzed target //tests:system_paths_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tests:system_paths_test up-to-date:
bazel-bin/tests/system_paths_test_/system_paths_test
INFO: Elapsed time: 32.757s, Critical Path: 32.19s
INFO: 9 processes: 1 internal, 8 linux-sandbox.
INFO: Build completed successfully, 9 total actions
~/JUNE-10-3/sonic-mgmt/sdn_tests/pins_ondatra$ bazel build tests:system_paths_test 
INFO: Analyzed target //tests:system_paths_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target …
```
=> [sdn_tests]:Adding system paths tests to pins_ondatra.

tests/common/devices/multi_asic.py
Summary:
The global variable` _DEFAULT_SERVICES` will affect any future `MultiAsicSonicHost` instances for the test; this means that if this runs for the supervisor instance first then lldp gets incorrectly added for the linecard instances.
Fix this by just modifying the local `service_list` that we're making anyways.
Tested manually on 202405 on Arista hardware and verified that the pre-sanity check does not fail because the lldp service is not running.
=> Fix multi-asic lldp fix

sdn_tests/pins_ondatra/tests/gnmi_set_get_test.go
- [sdn_tests]: Adding GNMI set get [delete update order valid/invalid] test in pins-ondatra.
Summary:
- Added GNMI set get [delete update order valid/invalid] test in pins-ondatra.
> github.com/openconfig/gnsi/certz/certz.proto:22:1: warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
> INFO: From …
=> [sdn_tests]: Adding GNMI set get [delete update order valid/invalid] test in pins-ondatra.

tests/dhcp_relay/test_dhcp_pkt_recv.py
Summary:
dhcp_relay was enable on t0 and m0 topo, and copp would trap dhcp packet to cpu, test_dhcp_pkt_recv.py could be run on T0 and m0 platform
Add t0 and m0 mark to test_dhcp_pkt_recv.py
Tested on PR test
=> Add t0 and m0 mark to tests/dhcp_relay/test_dhcp_pkt_recv.py

.azure-pipelines/pr_test_scripts.yaml, azure-pipelines.yml
Summary:
Elastictest performs well in distribute running PR test in multiple KVMs, which support us to add more test scripts to PR checker
Add vlan test to t0-2vlans test job
=> Add vlan test to t0-2vlans test job

.azure-pipelines/pr_test_scripts.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Some dualtor only test scripts would be executed in single tor and xfail
Add conditonal mark to skip dualtor io tests on single tors
Verified on both dualtor and single tor
=> Add conditonal mark to skip dualtor io tests on single tors

tests/gnmi/conftest.py, tests/gnmi/helper.py, tests/gnmi/test_gnmi_appldb.py, tests/gnmi/test_gnmi_configdb.py
Summary:
Microsoft ADO: 28273229
GNMI end to end test is broken.
The root cause is:
GNMI end to end test copies gnmi client from gnmi container to sonic-mgmt container. We have upgraded gnmi container to bookworm, and then gnmi client is not compatible with sonic-mgmt container.
Run gnmi_cli_py in ptf container to support GNMI set request and get request.
Run gnmi_cli in gnmi container to support GNMI capability request.
Run gnoi_client in gnmi container to support GNOI request. 
=> Fix gnmi client compatible issue

tests/pfcwd/conftest.py
Summary:
Add t1-28-lag to the supported T1 topo of pfcwd test
The member ports of the portchannels in t1 topologies will not be selected for the pfcwd test if the topo is not in the supported list. This causes no enough ports for the multi port test case.
Add topo t1-28-lag to the list.
Run the pfcwd test on t1-28-lag testbed, all cases passed.
=> Add t1-28-lag to the supported T1 topo of pfcwd test

sdn_tests/pins_ondatra/tests/gnmi_wildcard_subscription_test.go
- [sdn_tests]:Adding Wild card on change tests to pins_ondatra.
Summary:
- Added Wild card on change tests to pins_ondatra.
Build result:
```
INFO: From Generating Descriptor Set proto_library …
```
=> [sdn_tests]:Adding Wild card on change tests to pins_ondatra.

tests/common/helpers/ptf_tests_helper.py, tests/qos/test_qos_dscp_mapping.py
Summary: Fix qos/test_qos_dscp_mapping.py failures
Fixes # [aristanetworks/sonic-qual.msft#132](https://github.com/aristanetworks/sonic-qual.msft/issues/132)
This test is mainly failing due to:
- Sending 10K packets at once on a ptf interface is sometimes causing nnpy socket to be non-functional for a moment and connection is getting timedout (logic to timeout is introduced by https://github.com/p4lang/ptf/pull/183).
- Sometimes egress_queue_count on queue 7 is way greater than no of packets being sent and the queue_count is not within the TOLERANCE, this could be due to protocol packets.
- Test is not enhanced to be run on dualtor topologies (packets are going to unexpected ToR).
- Fixtures "upstream_links" and "downstream_links" are always referring to upper ToR, thus return values of …
=> Fix qos/test_qos_dscp_mapping.py

tests/common/fixtures/duthost_utils.py
Summary:
Fixes MSFT ADO 28332318
Fix case error with the following error message:
` failed on setup with "Failed: <ipv6 address> not appeared in xxx netstat"`
On some physical testbed, the snmpd process took around 3 minutes to come up.
Current convert_and_restore_config_db_to_ipv6_only needs to check all process to be up before proceeding with SNMP checking.
wait_critical_processes() checks for the critical process which includes snmpd.
Tested it locally.
=>  ipv6_fixture needs to wait for all services to be up

tests/common/fixtures/duthost_utils.py
Summary:
Fixes MSFT ADO 28332318
Fix case error with the following error message:
` failed on setup with "Failed: <ipv6 address> not appeared in xxx netstat"`
On some physical testbed, the snmpd process took around 3 minutes to come up.
Current convert_and_restore_config_db_to_ipv6_only needs to check all process to be up before proceeding with SNMP checking.
wait_critical_processes() checks for the critical process which includes snmpd.
Tested it locally.
=> [202311] [PR:13213] ipv6_fixture needs to wait for all services to be up

tests/common/fixtures/duthost_utils.py
Summary:
Fixes MSFT ADO 28332318
Fix case error with the following error message:
` failed on setup with "Failed: <ipv6 address> not appeared in xxx netstat"`
On some physical testbed, the snmpd process took around 3 minutes to come up.
Current convert_and_restore_config_db_to_ipv6_only needs to check all process to be up before proceeding with SNMP checking.
wait_critical_processes() checks for the critical process which includes snmpd.
Tested it locally.
=> [202305] [PR:13213] ipv6_fixture needs to wait for all services to be up

tests/common/snappi_tests/snappi_fixtures.py, tests/snappi_tests/multidut/pfc/files/multidut_helper.py
Summary: Fixing the collateral caused by https://github.com/sonic-net/sonic-mgmt/pull/11400 and the speed mode typecasting to int
Fixing the collateral caused by https://github.com/sonic-net/sonic-mgmt/pull/11400 and the speed mode typecasting to int
added the global_pause attribute to verify_pause_frame_count_dut fixture in multidut_helper file
=> Fixing global_pause attribute and speed typecasting

tests/bfd/conftest.py, tests/bfd/test_bfd_static_route.py
Add completeness level config option to `test_bfd_static_route.py`, so we can dynamically adjust the iterations for `test_bfd_flap`
Summary:
Fixes # (issue) Microsoft ADO 28210614
I ran the `test_bfd_flap()` test case on a T2 chassis with a `--completeness_level` config option and can confirm it's working as expected.
=> feat: add completeness level to BFD static route tests

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml, tests/platform_tests/test_reboot.py
Summary:
Skip soft-reboot test on all the platforms except Dell s6100 platform.
Soft-reboot is only supported on Dell s6100 platform
Skip the soft-reboot test if platform is not s6100
==================================================================== short test summary info =====================================================================
SKIPPED [1] platform_tests/test_reboot.py: Skip test_soft_reboot for m0/mx and test is supported only on S6100 hwsku
================================================================= 1 skipped, 1 warning in 40.04s =================================================================
=> Skip soft-reboot on all platforms except Dell s6100 platform

tests/qos/qos_sai_base.py
The TH5 ASIC type is being added to the qos base test file here so it can be properly identified during testing,
such as in the case of test_qos_sai.py.
Summary:
Fixes https://github.com/aristanetworks/sonic-qual.msft/issues/137
Proper identification of the TH5 ASIC for qos tests.
Verified that the error "Cannot identify DUT ASIC type" no longer occurs when running test_qos_sai.py (the test advances beyond this point of failure now).
=> Add TH5 ASIC type for QoS Tests

tests/platform_tests/sfp/test_show_intf_xcvr.py, tests/platform_tests/sfp/util.py
The test_check_show_lpmode testcase is failing for all platforms and needs to be fixed.
MSFT ADO - 27894685
Summary:
The test_check_show_lpmode testcase is failing for all platforms and needs to be fixed.
The failure is due to a day-1 issue in the testcase definition. Following are the details
1. The function validate_transceiver_lpmode is called by passing a dict (sfp_lpmode) instead of passing a string.
2. Also, the expected header string has 1 less empty space than the actual command output
3. print is being used to log errors instead of using logging.error.
1. Passing a string to validate_transceiver_lpmode function
2. Corrected the expected header
3. Modified print to logging.error
Ran the test_check_show_lpmode testcase manually and ensured it passes.
``` …
```
=> Fix test_check_show_lpmode testcase failure

tests/copp/test_copp.py
Summary:
Fixes test_copp.py::TestCOPP::test_remove_trap stuck in Cisco platform
test_copp.py::TestCOPP::test_remove_trap stuck in Cisco platform. It will make whole pipeline stall.
Add sleep 120 seconds at the beginning of the test case.
Manually run the testcase for 10 times. All pass.
Run the entire pipeline for 3 times. All pass.
=> Fix the issue where test_copp.py::TestCOPP::test_remove_trap is stuck on Cisco platform

tests/common/plugins/sanity_check/__init__.py
Summary:
If the `--skip_sanity` option has been given, then don't call expensive fixtures and get the values of those fixtures just to end up not using them. Instead, have a small function that only gets the request fixture, and if sanity checks are not skipped, then call the full function that gets all fixtures.
This saves about 20-30 seconds of time.
Verified with repeated runs of advanced reboot test case, to see that it actually does save time.
=> Don't call expensive fixtures if skipping sanity

tests/pc/test_lag_member.py
Summary:
For the t0-8-lag topology, there are only 15 interfaces in the VLAN that will be up. This means that for topos where we want to test 16-member LAGs, this will be impossible.
As a general fix, if there's not enough members in the VLAN, skip the test case. This was already being done in one place, but that line of code just needed to be copied to another fixture.
=> [pc]: Skip if there's not enough members in the VLAN

tests/common/dualtor/mux_simulator_control.py
Summary:
Fix the `ValueError` for mux simulator utilities:
```
08:21:52 mux_simulator_control._post              L0196 WARNING| POST http://10.64.*.*:8082/mux/vms21-6 with data {'active_side': 'lower_tor'} failed, err: ValueError('Function has keyword-only parameters or annotations, use inspect.signature() API which can support them')
```
Use `inspect.signature` instead.
Run over dualtor testbed.
=> Fix mux simulator post

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
add the aa dualtor topo to skip list.
Run `bgp/test_bgp_slb.py` on `dualtor-aa` testbed.
=> [dualtor] Skip advanced reboot cases on dualtor-aa
