sonic-net/sonic-mgmt

spytest/apis/system/ssh.py

Summary:
added new SSH  APIs
local feature and regression tests

upstream changes in API ssh.py

---

spytest/apis/system/rest.py

Summary:
added new REST related APIs

upstream changes in API rest.py

---

spytest/apis/system/ntp.py

Summary:
added few NTP related APIs

upstream changes in API ntp.py

---

spytest/apis/system/gnmi.py

upstream changes in API gnmi

---

spytest/apis/system/config_replace.py

Summary:
added APIs for config replace feature
validated as part of feature testing

upstream changes in config_replace.py

---

spytest/apis/routing/ip_bgp.py

Summary:
removed unnecessary spaces

changes to upstream API ip_bgp

---

spytest/apis/routing/ip_name_server.py

Summary:
removed unnecessary if conditions

changes to upstream API ip_name_server

---

spytest/apis/routing/ip.py

Summary:
added new feature APIs

changes to upstream API ip.py

---

spytest/apis/security/radius.py

Summary:
added APIs for new features

changes to upstream API radius.py

---

spytest/apis/security/user.py

Summary:
added APIs for new feature

changes to upstream API user.py

---

spytest/apis/switching/mac.py

Summary:
added APIs for new feature

changes to upstream API mac.py

---

spytest/apis/switching/portchannel.py

Summary:
new APIs to support gnmi

changes to upstream API portchannel.py

---

spytest/apis/switching/pvst.py

Summary:
added MSTP APIs
local MSTP suites

upstream changes in API pvst.py

---

spytest/apis/switching/vlan.py

Summary:
added QinQ related APIs
tested the APIs along with Feature test

upstream changes in API vlan.py

---

spytest/apis/security/rbac.py

Summary:
added APIs for new features

changes to upstream API rbac.py

---

tests/pc/test_lag_member.py

Summary:
Add arp check to make sure arp info is correct before test.
Add arp check to make sure arp info is correct before test.
Run tests.

[pc] Fix test_lag_member_traffic arp issue

---

tests/sflow/test_sflow.py

Update sflow test to check sflow config installation status
On CPU weak switch, there would be seconds of time when orchagent process all the configs of sflow. As a result, the output of 'show sflow interface' would be not ready after all the docker recovery after a reboot.
Summary:
The output of 'show sflow interface' would be not ready after all the docker recovery after a reboot.
Check Sflow related SAI table generated
Internal regression.

Update sflow test to check sflow config installation status

---

ansible/group_vars/sonic/variables

Summary: Add new HwSku for Mellanox SPC1 platform: Mellanox-SN2700-A1-D48C8, 'Mellanox-SN2700-D40C8S8'

[Mellanox]Add new Mellanox HwSku

---

tests/passw_hardening/conftest.py
tests/passw_hardening/passw_hardening_utils.py
tests/passw_hardening/sample/passw_hardening_digits/common-password
tests/passw_hardening/sample/passw_hardening_enable/common-password
tests/passw_hardening/sample/passw_hardening_history/common-password
tests/passw_hardening/sample/passw_hardening_lower_letter/common-password
tests/passw_hardening/sample/passw_hardening_min_len/common-password
tests/passw_hardening/sample/passw_hardening_reject_user_passw_match/common-password
tests/passw_hardening/sample/passw_hardening_special_letter/common-password
tests/passw_hardening/sample/passw_hardening_upper_letter/common-password
tests/passw_hardening/test_passw_hardening.py

PR#10614 modified to support Debian 12. But sonic 202311 version still uses Debian 11, so revert this change on 202311 branch
Summary:
Fixes # PR #10614 modified to support Debian 12. But sonic 202311 version still uses Debian 11, so revert this change on 202311 branch

Revert PR #10614 on 202311 branch

---

tests/common/helpers/constants.py
tests/common/plugins/allure_server/__init__.py
tests/common/plugins/random_seed/__init__.py
tests/conftest.py

1. To reproduce the tests based on random parameters easily, add one function to set the seed for random, so for the specified seed, the test random parameter will be the same.
2. Add the seed info into the test logs and allure report
Summary:
To reproduce the tests based on random parameters easily
Set random seed 
run test based on random parameters
Any

Set random seed for tests

---

ansible/config_sonic_basedon_testbed.yml
ansible/templates/minigraph_meta.j2

Summary:
Change "Compute-AI" to "ComputeAI"
Change "Compute-AI" to "ComputeAI"
Change "Compute-AI" to "ComputeAI"
Verifiy on physical testbed and pilot env.

Change "Compute-AI" to "ComputeAI"

---

ansible/config_sonic_basedon_testbed.yml
ansible/templates/minigraph_meta.j2

Summary:
Manually cherry-pick Change "Compute-AI" to "ComputeAI" #11720
Manually cherry-pick Change "Compute-AI" to "ComputeAI" #11720
Manually cherry-pick Change "Compute-AI" to "ComputeAI" #11720
N/A

[202311]Manually cherry-pick Change "Compute-AI" to "ComputeAI" #11720

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Temporarily skip test_iface_loopback_action on Marvell platforms until confirm this can be supported.
Temporarily skip test_iface_loopback_action on Marvell platforms until confirm this can be supported.
This PR is only for Marvell platform.

[Marvell] Temporarily skip test_iface_loopback_action on Marvell platforms

---

ansible/library/acl_capabilities_facts.py

Add multi asic system check before calling SonicDBConfig.load_sonic_global_db_config()
Summary:
There should be a multi asic system check before invoking SonicDBConfig.load_sonic_global_db_config()
Add a multi asic system check 
No

Add multi asic system check before a call of SonicDBConfig.load_sonic_global_db_config()

---

ansible/example_ixia
ansible/lab
ansible/t2_lab
ansible/templates/minigraph_dpg.j2
ansible/templates/minigraph_dpg_asic.j2
ansible/testbed-new.yaml
ansible/veos_vtb

Summary:
Support dynamicl IPv6 netmask

[Feat] Support dynamic IPv6 netmask

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
This is a cherry-pick of #11767
Only run test_iface_loopback_action on Mellanox platform since it's the only platform it supports.
Skip test_iface_loopback_action except for Mellanox platform.
Case only supported on Mellanox platform.

[202311] Only run test_iface_loopback_action.py on Mellanox

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
test_pktgen still have some issue, such as: checking unnecessary process cpu utilization.
skip it before resolve these issue.
skip test_pktgen

skip test_pktgen

---

.azure-pipelines/recover_testbed/README.md
.azure-pipelines/recover_testbed/recover_testbed.py

We support the ability of recovering unhealthy testbeds via console. This PR is the design document of it. 
Summary:
We support the ability of recovering unhealthy testbeds via console. This PR is the design document of it.

Design document of automatically recover unhealthy testbeds via console. 

---

tests/dualtor_mgmt/test_dualtor_bgp_update_delay.py

Summary:
`test_dualtor_bgp_update_delay` is failing consistently on dualtor-aa testbed due to no pcap file present after shutting down tcpdump.
Let's add a check after starting tcpdump to ensure tcpdump is running as expected.
```
dualtor_mgmt/test_dualtor_bgp_update_delay.py::test_dualtor_bgp_update_delay[ipv4] PASSED                                                                                                                                                                              [ 100%]
```

[dualtor] Fix `test_dualtor_bgp_update_delay`

---

docs/testplan/BGP-Suppress-FIB-Pending-test-plan.md
tests/bgp/bgp_helpers.py
tests/bgp/conftest.py
tests/bgp/test_bgp_suppress_fib.py
tests/common/helpers/tcpdump_sniff_helper.py

1. Check route propagate at T2 VM
2. Announce route and test at all T0 VMs according to completeness level 
3. Do continuous boot according to completeness level 
4. Add auto generate routes and traffic data function 
5. Add stress and performance test cases
6. Add tcpdump sniffer helper
Summary:
MSFT requirements of enhance bgp suppress fib pending script
Do the enhancement as required/

Enhance bgp suppress fib pending script

---

ansible/config_sonic_basedon_testbed.yml
ansible/roles/vm_set/library/sonic_kickstart.py
ansible/roles/vm_set/tasks/kickstart_vm.yml
ansible/roles/vm_set/tasks/start_sonic_vm.yml
ansible/testbed-cli.sh
tests/scripts/sai_qualify/DUTScript/tests/mlnx-saiserver-files/usr/lib/systemd/system/saiserver.service
tests/scripts/sai_qualify/DUTScript/tests/mlnx-syncd-files/usr/lib/systemd/system/syncd.service

Summary:
We need to remove UpdateGraphService feature from sonic image. So we need to update sonic-mgmt to remove updategraph related code.
- Microsoft ADO **(number only)**: 24868353
We need to remove UpdateGraphService feature from sonic image. So we need to update sonic-mgmt to remove updategraph related code.
I have modified ansible and tests to remove updategraph related code.
Run sonic-mgmt test.

Remove updategraph related code

---

.azure-pipelines/recover_testbed/dut_connection.py

Remove a log in dut console function
Summary:
Remove a log in dut console function
Remove a log in dut console function

Remove a log in dut console function

---

docs/testplan/WoL-test-plan.md

**Summary:**
Add testplan for WoL.
WoL HLD: https://github.com/sonic-net/SONiC/blob/master/doc/wol/Wake-on-LAN-HLD.md
Add testplan for WoL.

[Doc] Add testplan for WoL feature

---

azure-pipelines.yml

Summary:
Enable DPU test in PR checker
I need to update sonic-buildimage and sonic-mgmt to support new GNMI schema, and I disabled dpu test in PR checker to merge related PR.
This PR will enable dpu test in PR checker.
Update azurepipeline.yml to enable dpu test.
Verify PR checker.

Enable dpu test in PR checker

---

ansible/plugins/connection/multi_passwd_ssh.py

Summary:
Refine the IPv6 retry logic, only retry on certain IPv4 addr unavailable scenarios.
Refine the IPv6 retry logic, only retry on certain IPv4 addr unavailable scenarios.
Check the Exception type and the message.
Run on different labs, the it works well

Restrict the scope of retry IPv6

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Skip IPv6-Only testcases on M0/Mx testbeds due to **MGMT devices don't use MGMT port**.
Skip IPv6-Only testcases on M0/Mx testbeds due to MGMT devices don't use MGMT port.
Updated conditional mark file.
Verified on Nokia-7215 Mx testbed:
```
ip/test_mgmt_ipv6_only.py::test_bgp_facts_ipv6_only[7215-11-None] SKIPPED (Skipping mgmt ipv6 test for mgmt topo)                                     [ 33%]
ip/test_mgmt_ipv6_only.py::test_show_features_ipv6_only[7215-11] SKIPPED (Skipping mgmt ipv6 test for mgmt topo)                                      [ 66%]
ip/test_mgmt_ipv6_only.py::test_image_download_ipv6_only[7215-11] SKIPPED (Skipping mgmt ipv6 test for mgmt topo)                                     [100%]
====================================================================== short …
```

Skip IPv6-Only testcases on M0/Mx testbeds

---

.azure-pipelines/baseline_test/baseline.test.template.yml

Summary:
Regarding PR https://github.com/sonic-net/sonic-mgmt/pull/12016, dpu test was enable in PR checker, need to enable in baseline test
Enable dpu test in baseline test

Enable dpu test in baseline test

---

tests/conftest.py
tests/test_posttest.py

Summary:
Cherry-pick for PR https://github.com/sonic-net/sonic-mgmt/pull/11993

[202012] Extract dump and syslog file into folder with testbed_idx in posttest

---

tests/gnmi/helper.py

Summary:
Collect more information to debug GNMI end to end test
Microsoft ADO: 27322007
GNMI end to end test failed occasionally, but I can't reproduce it.
And then I need more information to debug.
If gnmi client failed, check gnmi process, check system time and verify tcp connection with ssh.
Run GNMI end to end test

Add debug for gnmi test

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Link for the generic issue:https://github.com/sonic-net/sonic-mgmt/issues/9642
Summary:

Skip test_vlan_ping on Cisco-8000 due to generic issue

---

tests/dash/dash_acl.py

Add one checker for acl_fields_test:  after removing dash_acl_out_table and dash_acl_in_table, the relevant dash table should be removed from appl db
Summary:

Add one checker for acl_fields_test

---

tests/dualtor/test_ipinip.py

This PR is to improve test case `test_encap_with_mirror_session` to support DualToR Active-Active mode.
The test is to verify the bounced back traffic from standby side to active side is as expected, so we need to configure the DUT to work in Active-Standby mode in order to generate the bounced back traffic.
The change is to add a new fixture which runs on Active-Active DualToR testbed to configure the testbed into Active-Standby mode. 
Summary:
Improve test case `test_encap_with_mirror_session` to support DualToR Active-Active mode.
This PR is to improve test case `test_encap_with_mirror_session` to support DualToR Active-Active mode.
Add a new fixture which runs on Active-Active DualToR testbed to configure the testbed into Active-Standby mode. 
The change is verified on …

Improve test case test_encap_with_mirror_session to support Active-Active DualToR

---

tests/ssh/test_ssh_ciphers.py

Fix issues in `test_ssh_ciphers.py` caused by password rotation 
Summary:

Fix issues in `test_ssh_ciphers.py` caused by password rotation 

---

tests/pfcwd/test_pfcwd_function.py

Summary:
27317514
NameError: global name 'six' is not defined
porting to 202205 by below commit, seems missed import six
https://github.com/sonic-net/sonic-mgmt/commit/9b2f462d2d43522b57211992a64a9332673092e4
add import six
Run case

[202205] add import six in 202205 branch

---

tests/common/utilities.py
tests/conftest.py
tests/ssh/test_ssh_ciphers.py
tests/ssh/test_ssh_limit.py

This PR is a combination of #12253, #12255 and #12264 
Summary:
This PR is a combination of #12253, #12255 and #12264

[202305] Fix issues due to password rotation.

---

tests/arp/test_stress_arp.py

In script `arp/test_stress_arp.py`, we want to test the maximum number of entries that can be supported by the DUT, and to ensure that the addition and removal of these entries are handled correctly. In this PR, we adjust the code to consider both the available IPv6 neighbor entries and the FDB available entries, which will provide a more comprehensive understanding of the DUT's capabilities and limitations.
Summary:
In script `arp/test_stress_arp.py`, we want to test the maximum number of entries that can be supported by the DUT, and to ensure that the addition and removal of these entries are handled correctly. In this PR, we adjust the code to consider both the available IPv6 neighbor entries and the FDB available entries, which will provide a more comprehensive …

Adjust the number of ipv6 nd in script `arp/test_stress_arp.py`.

---

tests/show_techsupport/test_techsupport.py

1. Add test_techsupport_on_dpu for dpu.
2. Skip the existing tests regarding dpu running on the switch for dpu.
Summary:
1. Add test_techsupport_on_dpu for dpu.
2. Skip existing tests running on the switch for dpu.
1. Add test_techsupport_on_dpu for dpu.
2. Skip existing tests running on the switch for dpu.
Run the tests on dpu and switch 
DPU
Any

Add test_techsupport_on_dpu for dpu

---

tests/bgp/test_bgp_update_timer.py

Summary:
bgp/test_bgp_update_timer.py::test_bgp_update_timer_single_route run into failure with backend routers. The test doesn't support the backend router before, it will take the wrong neighbor type, which would apply wrong route-map when set up the bgp sessions. 
To fix the issue for bgp/test_bgp_update_timer.py::test_bgp_update_timer_single_route on backend router.
Add type for BackEndToRRouter. 
Besides this one, two more enhancements
1. add several shell command for debug purpose. 
2. remove pcap file if some test left over before, which could cause tcpdump can't be start issue and fail the test. 
Reformat the file for line length.
Run local test.
only failed on BackEndToRRouter

[test_bgp_update_timer] to support backend tor router

---

ansible/group_vars/lab/lab.yml
tests/common/fixtures/tacacs.py
tests/conftest.py
tests/tacacs/conftest.py
tests/tacacs/tac_plus.conf.j2
tests/tacacs/test_ro_disk.py
tests/tacacs/utils.py

Enable TACACS on test cases.
Enable TACACS on test cases.
- Microsoft ADO: 26156377
Improve SONiC command TACACS test coverage, need enable TACACS on all SONiC test cases.
Add setup_tacacsv fixture, also enable tacacs on 1 module for test.
Pass all test cases

Enable TACACS on test cases.

---

tests/bgp/test_bgp_update_timer.py

Summary:
cherry pick 
https://github.com/sonic-net/sonic-mgmt/pull/12394

[202305 cherry pick] [test_bgp_update_timer] to support backend tor router

---

.azure-pipelines/testbed_health_check.py

[Fix] Fix issue of testbed_health_check.py, check host reachability first.
If the host was reachable, the command run on the host would return a valid result. 
To avoid JSON DecoderError, check if stdout was not empty first.
If the host was reachable, the command run on the host would return a valid result. 
To avoid JSON DecoderError, check if stdout was not empty first.
Check host reachability first before verify mgmt-ipv4 exsits.
After running command of get MGMT_INTERFACE from config_db.json, verify stdout first.
Test locally.

[Fix] Fix issue of testbed_health_check.py, check host reachability first

---

tests/common/utilities.py
tests/ip/test_mgmt_ipv6_only.py
tests/telemetry/conftest.py
tests/telemetry/test_events.py
tests/telemetry/test_telemetry.py

Summary:
Fixes # (issue) 26660292
Backport
https://github.com/sonic-net/sonic-mgmt/pull/12268
https://github.com/sonic-net/sonic-mgmt/pull/12420
backport to 202305
Manual test

Add IPV6 only telemetry test case

---

azure-pipelines.yml

Summary:
It does not make sense to run PR testing for document only changes. 
This PR updated the PR testing azure pipeline yaml to exclude the `docs` folder.

Skip PR testing for docs only change

---

tests/platform_tests/broadcom/files/ser_injector.py
tests/platform_tests/broadcom/test_ser.py

modify ser_injector.py run as async mode
Summary:
26161013
Sometimes the case "test_ser" failed due to reporting the DUT as host unreachable. 
However, checked the DUT status during that time, DUT should be fine.
Suspect related to the ansible callback not getting the function's callback and still waitting it until timeout.
Update the script to invoke the ser_injector.py using async mode.
Record the ser_injector.py script log into a log file and polling the log file to check the result instead of checking the script's return value.
Run the case manually and using pipeline

[test_ser] modify ser_injector.py run as async mode

---

.azure-pipelines/pr_test_scripts.yaml

Add around 70 control plane test cases in PR test in this PR. 
Summary:
Add around 70 control plane test cases in PR test in this PR.

Add around 70 control plane test cases in PR test.

---

.azure-pipelines/testbed_health_check.py

[Fix] Fix word spelling error

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary: Skip the test_nbr_health by:  https://github.com/sonic-net/sonic-mgmt/issues/7883

Add skip for test_nbr_health test by github issue

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary: Add skip for ecmp test on some mellanox msn2 platform by github issue: https://github.com/sonic-net/sonic-mgmt/issues/6558

Add skip for ecmp test on some mellanox platform by github issue

---

tests/route/conftest.py
tests/route/test_route_perf.py
tests/route/utils.py

Reverts sonic-net/sonic-mgmt#12460
Revert the change to unblock PR test

Revert "[Enhancement] Test route perf enhancement for backend testbeds"

---

tests/fdb/test_fdb_mac_move.py

Summary:
27553975
Exception: start-LogAnalyzer-test_fdb_mac_move.2024-02-25-07:03:31 was not found in /var/log
Sometimes, the case failed because the log analyzer cannot locate the log.
The log analyzer records the timestamp at the beginning of the case and analyzes the syslogs to check any error message generated during the case process.
However, some devices with a small disk, have a limitation for the /var/log size.
So during the log rotation, the previous syslog would be deleted, leading to the log analyzer failed to locate the log and return error.
In this case, the swss logs consume a large space of /var/log. However, the output messages are expected and necessary for debugging in production. and log flooding is typically not a common occurrence in production.
To fix …

[test_fdb_mac_move] Only output error level message into syslog if /var/log size limitation 

---

tests/generic_config_updater/test_dynamic_acl.py

Summary:
Fixes a bug in scale test for Dynamic ACL via GCU caused by large number of ports leading to a resource constraint creating drop rules.
Fix a bug that was causing test failures in nightly testing suite
Tested on a Arista 7260 testbed and saw success

Fix bug in scale test for Dynamic ACL via GCU on Arista 7260 devices

---

tests/route/conftest.py
tests/route/test_route_perf.py
tests/route/utils.py

Summary: Test enhancement for test_route_perf to accommodate backend testbeds. This is a fix since #12460 was reverted due to a PR test checker failure that was added after the original PR was merged. 
Test enhancement to support backend testbeds. This test currently fails to run on a backend testbed.
Added valid DUT and PTF port settings in case of backend testbed
Test passes on both backend testbed and non-backend testbed
```========== 2 passed, 71 warnings in 415.82s (0:06:55) ========```

[Enhancement] Test route perf enhancement for backend testbeds

---

ansible/roles/test/files/ptftests/sad_path.py

When the vm neighbor number is larger than 4, the bgp route changing time would be too long.
That leads function "do_inboot_oper" waste too much time, then the script would miss the time window of checking warm reboot finalizer activating state. 
So when the vm neighbor number is larger than 4, randomly choose 4 vms from the neighbors in modify_routes function。
```
def modify_routes(self):
self.log = []
if self.bp_ip:
if len(self.neigh_vms) <= 4:
neigh_vms = self.neigh_vms
else:
neigh_vms = random.sample(self.neigh_vms, 4)
for vm in neigh_vms:
if 'routing_add' in self.oper_type:
self.log.append('Adding %d routes from VM %s' %
(2 * self.ip_cnt, vm))
self.vm_handles[vm].change_bgp_route(self.route_cfg)
else:
self.log.append('Removing %d routes from VM %s' %
(2 * self.ip_cnt, vm)) …
```

Update warm-reboot sad in_boot test

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Add community skip condition due to github issue 11404
Change-Id: I742fa8c5393ff315d4188d52ddb3ff41f2580b48
Add community test skip condition due to github test issue https://github.com/sonic-net/sonic-mgmt/issues/11404
Summary:
Add community test skip condition due to github test issue https://github.com/sonic-net/sonic-mgmt/issues/11404for case dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default
Add community skip condition
No

[202205] Add community skip condition due to github issue (#11404)

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary: Add skip for generic_config_updater/test_eth_interface.py::test_update_speed by github issue:  https://github.com/sonic-net/sonic-buildimage/issues/13267, https://github.com/sonic-net/sonic-mgmt/issues/8143

Add skip for some GCU test by github issue

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
manually double commit PR https://github.com/sonic-net/sonic-mgmt/pull/12266 for 202305 branch,  to resolve conflict
fix conflict

[202305] skip headroom pool test for Force10-S6100 T1 topo

---

tests/saitests/py3/sai_qos_tests.py

Summary:
manually double commit PR  https://github.com/sonic-net/sonic-mgmt/pull/11365  for 202205 branch to fix conflict
fix conflict

[202205] fix 6100 testQosSaiLossyQueue failure caused by leakout

---

tests/container_checker/test_container_checker.py

Summary:
Cherry Pick PR https://github.com/sonic-net/sonic-mgmt/pull/11397 to 2205
Refer: Issue https://github.com/sonic-net/sonic-mgmt/issues/10475 
In the resolution process, we verify the status of the container under test to ensure it is running. If the container is found to be in exited stated, we initiate a config_reload to guarantee its running state before proceeding with the test case. To maintain accurate logging post config_reload, an additional 10-second delay is introduced for the log analyzer, compensating for the reset of the monit rc timer.
In certain scenarios, the auto-restart feature may inadvertently get enabled due to other test cases, which contradicts the prerequisite of having it disabled for the current test case. Consequently, a corrective measure has been …

[202205][Container checker] Check if the container is in running state before stopping it

---

tests/iface_namingmode/test_iface_namingmode.py

This is a cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/10892 as requested to 202205. 
The `iface_namingmode` test attempts to verify that the original interface name is not present in counters output when alias mode is requested, but it winds up matching if the original interface name is a substring of an alias name (e.g., Ethernet1 would match Ethernet12 in the output and cause the test to fail).
This is a requested cherry-pick to 202205 to resolve conflicts.

[202205] Fix iface_namingmode alias check (cherry-pick)

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
cherry pick PR #12070 
manually fix conflict and cherry pick

[202311] not skip HeadoomPoolSize test for Arista-7060CX-32S-D48C8

---

tests/system_health/test_watchdog.py

Signed-off-by: Anand Mehra anamehra@cisco.com
Summary:
https://github.com/sonic-net/sonic-buildimage/issues/18471
system_health.test_watchdog#test_orchagent_watchdog  test case fails on multi-asic system
Added support to use namespace on multi-asic system
Run test via sonic-mgmt on single asic and multi-asic DUTs

Added multi-asic support to system_health/test_watchdog.py

---

tests/sub_port_interfaces/conftest.py

Summary:
Backend acl no longer includes IN_PORTS qualifier for 202305 and above . This script was initially modified to match on interfaces and apply the correct acl rules for each testcase. That logic no longer works.
This change includes the following
- remove the use of acl rules per testcase. 
- changed the scope of the acl related fixtures to 'class' to avoid errors in the loganalyzer due to the table not being bound to ports before the rules are applied.
Tested on t0-backend with 202305 image. These tests are skipped on all other topos

[sub_port] Modify test setup to accomodate the backend acl

---

.azure-pipelines/pr_test_scripts.yaml
tests/generic_config_updater/test_bgp_prefix.py

Summary: Correct the topo that was misconfigured in previous PR
Correct topo
Change topo back
E2E

Correct test_bgp_prefix topo

---

.azure-pipelines/pr_test_scripts.yaml
tests/generic_config_updater/test_bgp_prefix.py

Summary: resolve 202305 conflict  https://github.com/sonic-net/sonic-mgmt/pull/12740

[202305 cherry pick] Correct test_bgp_prefix topo

---

.azure-pipelines/pr_test_scripts.yaml
tests/generic_config_updater/test_bgp_prefix.py

Summary: resolve 202311 conflict https://github.com/sonic-net/sonic-mgmt/pull/12740

[202311 cherry pick] Correct test_bgp_prefix topo

---

tests/dash/dash_acl.py
tests/dash/packets.py
tests/dash/test_dash_acl.py

Add test_acl_tcp_rst for Mellanox dpu.
This case is to verify the two following scenarios when CT miss for TCP packet on Mellanox dpu
1. CT miss +  No SYN packet(ACK) + ACL permit
2. CT miss +  No SYN packet(ACK) + ACL deny
Test steps:
1. Configure ACL permit for src:11.1.1.1/32, dst:20.2.2.2/32, src_port: 24563, dst_port: 80, protocol: tcp
2. Configure ACL deny for src:20.2.2.2/32, dst:11.1.1.1/32, src_port: 80, dst_port: 24563, protocol: tcp
3. Send no SYN packet(ACK) matching ACL permit
4. Check the TCP packet will be forwarded to the correct port
5. Send no SYN packet(ACK) matching ACL Deny
6. Check the TCP packet will be dropped, and the RST packet will be sent to the two ends
Summary:
Add test_acl_tcp_rst for Mellanox dpu 
Add test_acl_tcp_rst
Run the test on …

[Mellanox] Add dash tcp rst test

---

docs/testplan/Generic-Hash-test-plan.md

Enhance generic hash testplan
Enhance generic hash testplan:
Add 6 new supported fields
Support algorithm configuration
Summary:
Add testplan for new generic hash implementation
Add test plan for new 6 new supported fields and algorithm configuration

Generic hash test plan enhancement

---

.azure-pipelines/pr_test_scripts.yaml
azure-pipelines.yml

We are going to onboard a batch of test cases into PR test recently. To achieve this without disrupting the existing PR test processes, we add a separate non-blocking PR checker for onboarding new tests.
Summary:
We are going to onboard a batch of test cases into PR test recently. To achieve this without disrupting the existing PR test processes, we add a separate non-blocking PR checker for onboarding new tests.
Add a separate non-blocking PR checker for onboarding new tests

Add a separate non-blocking PR check for onboarding new tests(T0).

---

.azure-pipelines/pr_test_scripts.yaml

In PR #12387, I deleted the case `platform_tests/test_advanced_reboot.py::test_warm_reboot` by mistake. So in this PR, add this case back into PR test. 
Summary:
In PR #12387, I deleted the case `platform_tests/test_advanced_reboot.py::test_warm_reboot` by mistake. So in this PR, add this case back into PR test.

Add case `platform_tests/test_advanced_reboot.py::test_warm_reboot` back into PR test. 

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
Many cases failed on 202311 branch with the below issue
https://github.com/sonic-net/sonic-buildimage/issues/18887
Ignore the error message before the issue fixed
Re-run nightly pipeline
Broadcom

ignore bgp#zebra.*zfpm_build_route_updates: Encoding Prefix

---

tests/run_tests.sh

Summary:
Regarding comments in PR https://github.com/sonic-net/sonic-mgmt/pull/12748, it's a better way to skip pre and post after gathering all scripts
Skip pre and post after gathering all scripts

Skip pre and post after gathering all scripts

---

tests/qos/test_ecn_config.py

Summary:
Need a case to Validate the ECN configuration 
- ECN and WRED is enabled on all lossless queue 
- The drop probability for green packet should not be zero 
- The drop threshold for the green packet has the right value
Added Cisco specific ECN marking config verification test
Cisco specific

Added Cisco specific ECN marking config verification test

---

tests/platform_tests/api/test_chassis.py
tests/platform_tests/api/test_sfp.py
tests/platform_tests/conftest.py
tests/platform_tests/mellanox/test_check_sfp_presence.py

Because for smartswitch, the internal ports are not sfp ports, so platfform tests related to sfp should be skipped on these ports. This is the relevant PR:https://github.com/sonic-net/sonic-buildimage/pull/18465
Summary:
Update platform tests related to sfp due to the PR: https://github.com/sonic-net/sonic-buildimage/pull/18465
When port is dpu npu port, skip the tests related to sfp
Run platform sfp tests on smartswitch
smartswitch 
Any

Update platform tests related to sfp for dpu npu port

---

sdn_tests/pins_ondatra/.gitignore
sdn_tests/pins_ondatra/BUILD
sdn_tests/pins_ondatra/README.md
sdn_tests/pins_ondatra/WORKSPACE.bazel
sdn_tests/pins_ondatra/bazel/patches/ghodss_yaml.patch
sdn_tests/pins_ondatra/bazel/patches/gnmi-001-fix_virtual_proto_import.patch
sdn_tests/pins_ondatra/bazel/patches/gnmi.patch
sdn_tests/pins_ondatra/bazel/patches/gnoi.patch
sdn_tests/pins_ondatra/bazel/patches/gnoigo.patch
sdn_tests/pins_ondatra/bazel/patches/gnsi.patch
sdn_tests/pins_ondatra/bazel/patches/gribi.patch
sdn_tests/pins_ondatra/bazel/patches/grpc-001-fix_file_watcher_race_condition.patch
sdn_tests/pins_ondatra/bazel/patches/grpc-003-fix_go_gazelle_register_toolchain.patch
sdn_tests/pins_ondatra/bazel/patches/ondatra.patch
sdn_tests/pins_ondatra/bazel/patches/p4lang.patch
sdn_tests/pins_ondatra/bazel/patches/rules_proto_grpc.patch
sdn_tests/pins_ondatra/bazel/patches/snappi.patch
sdn_tests/pins_ondatra/bazel/patches/ygnmi.patch
sdn_tests/pins_ondatra/bazel/patches/ygot.patch
sdn_tests/pins_ondatra/infra_deps.bzl
sdn_tests/pins_ondatra/infrastructure/binding/BUILD.bazel
sdn_tests/pins_ondatra/infrastructure/binding/binding_backend.go
sdn_tests/pins_ondatra/infrastructure/binding/pins_backend.go
sdn_tests/pins_ondatra/infrastructure/binding/pins_binding.go
sdn_tests/pins_ondatra/infrastructure/certs/BUILD.bazel
sdn_tests/pins_ondatra/infrastructure/certs/crt_gen.sh
sdn_tests/pins_ondatra/pins_deps.bzl

- [sdn_tests]: Adding cert generation script and certs folder to pins_ondatra.
Summary:
- Adding cert generation script and certs folder to pins_ondatra.
Build Result:
$ bazel build ...
INFO: Elapsed time: 392.027s, Critical Path: 82.05s
INFO: 882 processes: 251 internal, 631 linux-sandbox.
INFO: Build completed successfully, 882 total actions

[sdn_tests]: Adding cert generation script and certs folder to pins_ondatra.

---

tests/common/plugins/conditional_mark/credentials.yaml
tests/common/plugins/conditional_mark/issue.py

In conditional mark, we may need to query the status of github issue. We use personal github authentication token to do this before. But per to the official document, "This endpoint can be used without authentication or the aforementioned permissions if only public resources are requested." So due to the security, we remove the github authentication here.
Summary:
In conditional mark, we may need to query the status of github issue. We use personal github authentication token to do this before. But per to the official document, "This endpoint can be used without authentication or the aforementioned permissions if only public resources are requested." So due to the security, we remove the github authentication here.
Remove the github authentication when querying the status …

Get the status of github issue without github authentication. 

---

ansible/allocate_device_ip.py

Summary:
Add tools for allocating IP for devices.
When the number of devices increases, it becomes very hard to find an available IP by simply looking at the device list file. 
To help with this IP allocation process, this change adds a new python scripts that read all IPs from the specified device list files and find any available IPs in a specific IP range.
It also provides a ping option, so we can filter out the IPs that is reachable, which means they are used already.
I have it run locally and successfully get IP allocated and the IP that is not allocated but used by other devices filtered out.
None.
Simply run `./allocate_device_ip.py --help` will produce the doc with examples:
```text
$ ./allocate_device_ip.py --help
Usage: allocate_device_ip.py [OPTIONS] [FILE_PATTERN]
Get …
```

Add tools for allocating IP for devices.

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
TC is not being skip for 202311 and above, make skip condition more common
Make skip more transparent for all sonic-mgmt branches 
Update skip condition
Run TC, TC skipped

Updated skip condition for test_check_sfp_using_ethtool at MLX platforms

---

tests/bgp/bgp_helpers.py
tests/bgp/conftest.py
tests/bgp/test_bgp_peer_shutdown.py
tests/bgp/test_bgp_update_timer.py
tests/common/helpers/bgp.py

Add a new test case to 
1. analyze the cease message when DUT's neighbor shuts down the BGP session
2. confirm the bgp session is properly closed
3. confirm the announced route is cleared
Summary:
Fixes #7059

feat: add bgp shutdown test

---

tests/qos/test_qos_dscp_mapping.py

Increase sleep time for packet sending/receiving.
Summary:
Fix case intermittent failures.
Increase sleep time for packet sending/receiving.
Verified it on T1 testbed.
Before fix, some failures since queue counter < 10000, looks like packet drop, but actually it is the sleep time not enough.
```
21:26:07 test_qos_dscp_mapping._run_test          L0318 INFO   | DSCP to queue mapping test results:
Inner Packet DSCP Value    Expected Egress Queue    Egress Queue Count  Result                        Actual Egress Queue
-------------------------  -----------------------  --------------------  --------------------------  ---------------------
0                        1                 10000  SUCCESS                                         1
1                        1 …
```

Increase sleep time for packet send/receive in test_qos_dscp_mapping.py

---

tests/bgp/test_bgp_peer_shutdown.py

Add topology mark for `test_bgp_peer_shutdown.py` so it won't get skipped
Summary:

fix: add topology mark for test_bgp_peer_shutdown.py

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
This PR is to update `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml` to skip `testIPIPQosSaiDscpToPgMapping` and `test_dscp_to_queue_mapping_pipe_mode` as the configuration is modified by these test cases but not recovered. It caused test failure for other test cases.
Issue https://github.com/sonic-net/sonic-mgmt/issues/12906
This PR is to update `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml` to skip `testIPIPQosSaiDscpToPgMapping` and `test_dscp_to_queue_mapping_pipe_mode`.
Update `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml`.
The change is verified by static syntax check as it only involves configuration change. 
No.

Skip testIPIPQosSaiDscpToPgMapping and test_dscp_to_queue_mapping_pipe_mode

---

sdn_tests/pins_ondatra/tests/lacp_timeout_test.go
sdn_tests/pins_ondatra/tests/link_event_damping_test.go
sdn_tests/pins_ondatra/tests/ondatra_test.bzl

- [sdn_tests]: Adding Link event damping test to pins_ondatra.
Summary:
- Added Link event damping test to pins_ondatra.
Build results:
INFO: Elapsed time: 567.277s, Critical Path: 183.34s

[sdn_tests]: Adding Link event damping test to pins_ondatra.

---

.azure-pipelines/run-test-elastictest-template.yml

[CI/CD] Update elastictest pr test template file, use long term maintained token instead of personal access token.
Compatibility update, in order to ensure that all PRtests that use this template file can transition smoothly.

[CI/CD] Update elastictest pr test template file, use long term maintained token instead of personal access token

---

.pre-commit-config.yaml

- [sonic-mgmt]: Skipping pre-commit checks for pins_ondatra patches.
Summary:
- Skipped pre-commit checks for pins_ondatra patches.
pre-commit results:
```
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...............................................................Passed
check for added large files..............................................Passed
check python ast.....................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
check conditional mark sort..............................................Passed
``` …

[sonic-mgmt]: Skipping pre-commit checks for pins_ondatra patches.

---

tests/bfd/bfd_base.py
tests/bfd/bfd_helpers.py
tests/bfd/conftest.py
tests/bfd/test_bfd_static_route.py

Summary:
Add fixes and improvements to `bfd/test_bfd_static_route.py`.
To prevent this PR from being too large, it only contains initial fixes/optimizations to `bfd/test_bfd_static_route.py`. I will create another PR later to include things like parametrizing IPv4 and IPv6 for each test, moving fixtures and static methods out of `BfdBase` class and etc.
To make sure `bfd/test_bfd_static_route.py` can run effectively on all T2 devices
I have run all test cases in this file in a T2 chassis device and can confirm they all passed.

fix: fix bfd static route tests

---

sdn_tests/pins_ondatra/tests/platforms_software_component_test.go

- [sdn_tests]: Adding Software Platform Components Tests to pins_ondatra.
Summary:
- Added Software Platform Components Tests to pins_ondatra.
Build Result: 
```
INFO: Elapsed time: 814.095s, Critical Path: 192.17s
```

[sdn_tests]: Adding Software Platform Components Tests to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/transceiver_test.go

- [sdn_tests]: Adding Transceiver test to pins_ondatra.
Summary:
- Added Transceiver test to pins_ondatra.
Build Result:
```
INFO: Elapsed time: 748.558s, Critical Path: 170.00s
```

[sdn_tests]: Adding Transceiver test to pins_ondatra.

---

tests/iface_loopback_action/test_iface_loopback_action.py

Summary:
This PR is to disable LogAnalyzer in `test_loopback_action_reload`.
The test fails with below error
```
E               {"changed": false, "failed": true, "msg": "Traceback (most recent call last):
File \"/tmp/ansible_extract_log_payload_vre9l4j6/ansible_extract_log_payload.zip/ansible/modules/extract_log.py\", line 306, in main
File \"/tmp/ansible_extract_log_payload_vre9l4j6/ansible_extract_log_payload.zip/ansible/modules/extract_log.py\", line 275, in extract_log
File \"/tmp/ansible_extract_log_payload_vre9l4j6/ansible_extract_log_payload.zip/ansible/modules/extract_log.py\", line 226, in extract_latest_line_with_string\nException: start-LogAnalyzer-test_loopback_action_reload.2024-04-16-18:25:20 was not found in /var/log"}
```
It's because the log file is lost after reboot if …

Disable LogAnalyzer in test_loopback_action_reload

---

sdn_tests/pins_ondatra/tests/cpu_sw_single_switch_test.go

- [sdn_tests]: Adding CPU single switch tests to pins_ondatra.
Summary:
- Added CPU single switch tests to pins_ondatra.
Build results:
```
github.com/openconfig/gnsi/pathz/authorization.proto:43:1: warning: Import …
```

[sdn_tests]: Adding CPU single switch tests to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/gnmi_set_get_test.go

- [sdn_tests]:Adding Gnmi set get tests to pins_ondatra.
Summary:
- Added Gnmi set get tests to pins_ondatra.
Build Results:
```
github.com/openconfig/gnsi/acctz/acctz.proto:36:1: warning: Import github.com/openconfig/gnsi/version/version.proto is …
```

[sdn_tests]:Adding Gnmi set get tests to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/BUILD.bazel
sdn_tests/pins_ondatra/tests/lacp_test.go

- [sdn_tests]: Adding LACP tests to pins_ondatra.
Summary:
- Added LACP tests to pins_ondatra.
Build Results:
``` …
```

[sdn_tests]: Adding LACP tests to pins_ondatra.

---

azure-pipelines.yml

[ci] Migrate agent pool.

---

tests/copp/copp_utils.py

Summary:
Update the CoPP test case code to add support for Bookworm syncd containers. The main change with the Bullseye installation code is that nanomsg isn't compiled (instead, a precompiled package is used), and some development tools are uninstalled afterwards to reduce space usage.
Tested by running copp/test_copp.py on a Dell S6100 running a master branch image. All tests except for `copp/test_copp.py::TestCOPP::test_add_new_trap` passed.

Update CoPP test case for Bookworm syncd container

---

sdn_tests/pins_ondatra/tests/gnoi_reboot_test.go

- [sdn_tests]:Adding GNOI reboot schedule tests.
Summary:
- Added GNOI reboot schedule tests.
Build Results:
``` …
```

[sdn_tests]:Adding GNOI reboot schedule tests.

---

sdn_tests/pins_ondatra/tests/cpu_sw_single_switch_test.go

- [sdn_tests]:Adding CPU parent paths Test to pins_ondatra.
Summary:
- Added CPU parent paths Test to pins_ondatra.
Build Result:
```
INFO: Elapsed time: 819.470s, Critical Path: 195.96s
INFO: 975 processes: 251 …
```

[sdn_tests]:Adding CPU parent paths Test to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/gnmi_set_get_test.go

- [sdn_tests]:Adding GNMI set update leaf tests.
Summary:
- Added GNMI set update leaf tests.
Build results:
```
INFO: Elapsed time: 832.597s, Critical Path: 192.77s
INFO: 975 processes: 251 internal, 724 …
```

[sdn_tests]:Adding GNMI set update leaf tests.

---

tests/bgp/test_seq_idf_isolation.py
tests/bgp/test_traffic_shift.py

Summary:
Test cases to validate sequential IDF isolation/un-isolation on T2 Chassis
Validate sequential IDF isolation functionality on T2
Add new test cases to validate configuration and persistence of sequential IDF isolation feature on T2 Chassis
Run test_seq_idf_isolation.py on T2 Chassis
Only runs on T2 with atleast 1 linecard connected to T1 neighbors

Test cases for Sequential IDF isolation

---

ansible/roles/vm_set/library/vm_topology.py

Summary:
Allow ssh traffic between DUT and VM
Allow ssh traffic between DUT and VM
Capture packets to verify

[ansible][ovs] Allow ssh traffic between DUT and VM

---

.azure-pipelines/baseline_test/baseline.test.template.yml

Summary:
Due to security and quota limitation, update the baseline pipeline to use new agent pool 'sonic-ubuntu-1c'.
Updated the pipeline yaml to use new agent pool 'sonic-ubuntu-1c'

Update baseline test to use new agent pool

---

sdn_tests/pins_ondatra/tests/gnoi_reboot_test.go

- [sdn_tests]: Adding GNOI Active reboot schedule tests.
Summary:
- Added GNOI Active reboot schedule tests.
> INFO: Elapsed time: 326.637s, Critical Path: 122.48s
> INFO: 975 …

[sdn_tests]: Adding GNOI Active reboot schedule tests.

---

tests/bgp/test_bgp_update_timer.py

Summary:
Fix bgp update timer to get the bgp shudown time from DUT
Fix bgp update timer to get the bgp shudown time from DUT
Us the time from the DUT so that the  difference is what we expect. There could be time different between the time in test server and time set on the DUThost
Extract the time from the results 
tests/bgp/test_bgp_update_timer.py passes 
<TO add logs of test passing>

Fix bgp update timer to get the bgp shudown time from DUT

---

sdn_tests/pins_ondatra/tests/cpu_sw_single_switch_test.go

- [sdn_tests]: Adding CPU In-Discards test to pins_ondatra.
Summary:
- Added CPU In-Discards test to pins_ondatra.
> INFO: Elapsed time: 898.177s, Critical Path: 126.77s
> INFO: …

[sdn_tests]: Adding CPU In-Discards test to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/gnmi_set_get_test.go

- [sdn_tests]: Adding GNMI set replace leaf tests.
Summary:
- Added GNMI set replace leaf tests.
```
INFO: Elapsed time: 332.605s, Critical Path: 128.69s
INFO: 975 processes: 251 internal, …
```

[sdn_tests]: Adding GNMI set replace leaf tests.

---

sdn_tests/pins_ondatra/tests/ethcounter_sw_single_switch_test.go

- [sdn_tests]: Adding multicast out-packets test in Ethernet counter.
Summary:
- Added multicast out-packets test in Ethernet counter.
```
INFO: Elapsed time: 558.905s, Critical Path: 173.37s
```

[sdn_tests]: Adding multicast out-packets test in Ethernet counter.

---

sdn_tests/pins_ondatra/tests/platforms_hardware_component_test.go

- [sdn_tests]: Adding platforms hardware component test to pins ondatra.
Summary:
- Added platforms hardware component test to pins ondatra.
```
github.com/openconfig/gnsi/acctz/acctz.proto:36:1: warning: Import …
```

[sdn_tests]: Adding platforms hardware component test to pins ondatra.

---

sdn_tests/pins_ondatra/tests/gnmi_get_modes_test.go

- [sdn_tests]: Adding GNMI Get test to check the Req at leaf and subtree level in pins_ondatra.
Summary:
- Added GNMI Get test to check the Req at leaf and subtree level in pins_ondatra.
```
github.com/openconfig/gnsi/pathz/pathz.proto:25:1: warning: Import github.com/openconfig/gnsi/version/version.proto is …
```

[sdn_tests]: Adding GNMI Get test to check the Req at leaf and subtree level in pins_ondatra.

---

sdn_tests/pins_ondatra/tests/gnmi_subscribe_modes_test.go

- [sdn_tests]: Adding GNMI subscribe modes test [sub Mode Update/Suppress/Sample/Once tests] in pins ondatra.
Summary:
- Added GNMI subscribe modes test [sub Mode Update/Suppress/Sample/Once tests] in pins ondatra.
```
INFO: Elapsed time: 328.004s, Critical Path: 122.55s
```

[sdn_tests]: Adding GNMI subscribe modes test [sub Mode Update/Suppress/Sample/Once tests] in pins ondatra.

---

sdn_tests/pins_ondatra/tests/ethcounter_sw_single_switch_test.go

- [sdn_tests]: Adding in-packets and Broadcast out-packets test in Ethernet counter.
Summary:
- Added in-packets and Broadcast out-packets test in Ethernet counter.
```
INFO: Elapsed time: …
```

[sdn_tests]: Adding in-packets and Broadcast out-packets test in Ethernet counter.

---

sdn_tests/pins_ondatra/tests/BUILD.bazel
sdn_tests/pins_ondatra/tests/platforms_hardware_component_test.go

- [sdn_tests]: Adding platforms hardware component [get/set info] test to pins ondatra.
Summary:
- Added platforms hardware component [get/set info] test to pins ondatra.
```
INFO: Elapsed …
```

[sdn_tests]: Adding platforms hardware component [get/set info] test to pins ondatra.

---

sdn_tests/pins_ondatra/tests/gnmi_get_modes_test.go

- [sdn_tests]: Adding gNMI Get test [check all GNMI Get Modes] to pins_ondatra.
Summary:
- Added gNMI Get test [check all GNMI Get Modes] to pins_ondatra.
```
INFO: Elapsed time: 315.380s, …
```

[sdn_tests]: Adding gNMI Get test [check all GNMI Get Modes] to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/platforms_hardware_component_test.go

- [sdn_tests]: Adding platform hardware component tests [Temperature/FPGA info] to pins_ondatra.
Summary:
- Added platform hardware component tests [Temperature/FPGA info] to pins_ondatra.
```
github.com/openconfig/gnsi/pathz/pathz.proto:25:1: warning: Import github.com/openconfig/gnsi/version/version.proto is …
```

[sdn_tests]: Adding platform hardware component tests [Temperature/FPGA info] to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/gnmi_subscribe_modes_test.go

- [sdn_tests]: Adding GNMI subscribe modes test [Delete/Poll/Root test] to pins_ondatra.
Summary:
- Added GNMI subscribe modes test [Delete/Poll/Root test] to pins_ondatra.
``` …
```

[sdn_tests]: Adding GNMI subscribe modes test [Delete/Poll/Root test] to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/gnmi_get_modes_test.go

- [sdn_tests]: Adding gNMI Get all Missing and InvalidTypes test to pins_ondatra.
Summary:
- Added gNMI Get all Missing and InvalidTypes test to pins_ondatra.
```
github.com/openconfig/gnsi/credentialz/credentialz.proto:21:1: warning: …
```

[sdn_tests]: Adding gNMI Get all Missing and InvalidTypes test to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/ethcounter_sw_single_switch_test.go

- [sdn_tests]: Adding Ethernet Counter SubInterface IPV4 In-PKTs test to pins_ondatra.
Summary:
- Added Ethernet Counter SubInterface IPV4 In-PKTs test to pins_ondatra.
> INFO: …

[sdn_tests]: Adding Ethernet Counter SubInterface IPV4 In-PKTs test to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/gnmi_subscribe_modes_test.go

- [sdn_tests]: Adding GNMI subscribe modes test [collectResponse/buildRequest test] to pins_ondatra.
Summary:
- Added GNMI subscribe modes test [collectResponse/buildRequest test] to pins_ondatra.
> github.com/openconfig/gnsi/certz/certz.proto:22:1: warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
> …

[sdn_tests]: Adding GNMI subscribe modes test [collectResponse/buildRequest test] to pins_ondatra.

---

tests/common/plugins/custom_markers/__init__.py

[Fix] if test case not specify device_type explicitly, by default run on all devices

---

tests/platform_tests/sfp/test_sfputil.py

Replace the assert for no interfaces down in test_sfputil.py to a wait_until on all the interfaces to be up.  This addresses the issue where the interfaces are not up by the time we get to the assert, but will be up shortly after.
Summary:

[sonic-mgmt] Add retry mechanism to checking intfs in test_sfputil

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Reverts sonic-net/sonic-mgmt#13076

Revert "skip bgp/test_bgp_slb::test_bgp_slb_neighbor_persistence_across_advanced_reboot on SN4700"

---

tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_basic_helper.py

Summary: Adding warm-up traffic for multidut pfcwd case since the feature was missing from the testcase, due to which the case was failing
During our regression run we found the  warm-up traffic feature for multidut pfcwd case was missing,  due to which the case was failing
Added the warm-up traffic item along with PFC pause traffic 
Added the warm-up traffic item along with PFC pause traffic and ran the test

Adding warm-up traffic for multidut pfcwd case

---

ansible/lab
ansible/testbed.csv
ansible/testbed.yaml
docs/testbed/README.new.testbed.Configuration.md
docs/testbed/sai_quality/DeploySAITestTopologyWithSONiC-MGMT.md

Summary:
Add inventory file setup introduction in testbed.Configration.md
Add inventory file setup introduction for lab testbed setup

Add inventory file setup introduction in testbed.Configration.md

---

sdn_tests/pins_ondatra/tests/gnmi_set_get_test.go

- [sdn_tests]: Adding GNMI set replace multiple leaf tests and delete single leaf test in pins-ondatra.
Summary:
- Added GNMI set replace multiple leaf tests and delete single leaf test in pins-ondatra.
> github.com/openconfig/gnsi/certz/certz.proto:22:1: warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
> INFO: From Generating Descriptor Set proto_library @com_github_openconfig_gnsi//authz:authz_proto:
> github.com/openconfig/gnsi/authz/authz.proto:23:1: warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
> INFO: From Generating Descriptor Set proto_library @com_github_openconfig_gnsi//acctz:acctz_proto:
> …

[sdn_tests]: Adding GNMI set replace multiple leaf tests and delete single leaf test in pins-ondatra.

---

sdn_tests/pins_ondatra/tests/platforms_hardware_component_test.go

- [sdn_tests]: Adding platform hardware component tests [Device Info/Smart Info] to pins_ondatra.
Summary:
- Added platform hardware component tests [Device Info/Smart Info] to pins_ondatra.
```
github.com/openconfig/gnsi/pathz/pathz.proto:25:1: warning: Import github.com/openconfig/gnsi/version/version.proto is …
```

[sdn_tests]: Adding platform hardware component tests [Device Info/Smart Info] to pins_ondatra.

---

.github/PULL_REQUEST_TEMPLATE.md

Summary:
This PR is to update PR template.
- Remove backport to 201911
- Added backport to 202405

Add backport option for 202405 branch

---

tests/tacacs/utils.py

Summary:
This PR is to cherry-pick #13174 into `202311` branch.
We are seeing unstable test result in `test_ro_user_ipv6_only` with below error.
```
failed on setup with "tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{"changed": true, "cmd": "ping 2603:x -c 1 -W 3", "delta": "0:00:03.016826", "end": "2024-06-05 21:51:23.791447", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2024-06-05 21:51:20.774621", "stderr": "", "stderr_lines": [], "stdout": "PING 2603:x(2603:x) 56 data bytes\n\n--- 2603:x ping statistics ---\n1 packets transmitted, 0 received, 100% packet loss, time 0ms", "stdout_lines": ["PING 2603:x(2603:x) 56 data bytes", "", "--- 2603:x ping statistics ---", "1 packets transmitted, 0 received, 100% packet loss, time …
```

[cherry-pick] [202311] Stabilize setup_tacacs_client

---

sdn_tests/pins_ondatra/tests/gnmi_stress_test.go

- [sdn_tests]: Adding GNMI Stress Test to pins-ondatra.
Summary:
- Added GNMI Stress Test to pins-ondatra.
> github.com/openconfig/gnsi/certz/certz.proto:22:1: warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
> github.com/openconfig/gnsi/pathz/authorization.proto:43:1: warning: Import …

[sdn_tests]: Adding GNMI Stress Test to pins-ondatra.

---

sdn_tests/pins_ondatra/tests/platforms_hardware_component_test.go

- [sdn_tests]:Adding Hardware Fan and PCIE tests to pins_ondatra.
Summary:
- Added Hardware Fan and PCIE tests to pins_ondatra.
Build Result:
```
INFO: From Generating Descriptor Set …
```

[sdn_tests]:Adding Hardware Fan and PCIE tests to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/gnmi_helper.go

- [sdn_tests]:Adding Gnmi Stress test helper to pins_ondatra.
Summary:
- Added Gnmi Stress test helper to pins_ondatra.
Build Result:
```
~/JUNE-0906-1/sonic-mgmt/sdn_tests/pins_ondatra$ bazel build ...
INFO: Analyzed 8 targets (23 packages loaded, 102 targets configured).
INFO: Found 8 targets...
INFO: Elapsed time: 3.820s, Critical Path: 1.16s
INFO: 24 processes: 1 internal, 23 linux-sandbox.
INFO: Build completed successfully, 24 total actions
~/JUNE-0906-1/sonic-mgmt/sdn_tests/pins_ondatra$ bazel build tests:gnmi_stress_helper 
INFO: Analyzed target //tests:gnmi_stress_helper (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tests:gnmi_stress_helper up-to-date:
bazel-bin/tests/gnmi_stress_helper.a
INFO: Elapsed time: 0.372s, Critical Path: 0.00s
INFO: 1 …
```

[sdn_tests]:Adding Gnmi Stress test helper to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/gnmi_wildcard_subscription_test.go

- [sdn_tests]:Adding Wild card OnChangePortSpeed test to pins_ondatra.
Summary:
- Added Wild card OnChangePortSpeed test to pins_ondatra.
Build Results:
```
INFO: Elapsed time: 805.401s, Critical Path: 179.83s …
```

[sdn_tests]:Adding Wild card OnChangePortSpeed test to pins_ondatra.

---

sdn_tests/pins_ondatra/tests/ethcounter_sw_single_switch_test.go

- [sdn_tests]: Adding Ethernet Counter Ipv6-Discards Check test to pins_ondatra.
Summary:
- Added Ethernet Counter Ipv6-Discards Check test to pins_ondatra.
> INFO: Elapsed time: …

[sdn_tests]: Adding Ethernet Counter Ipv6-Discards Check test to pins_ondatra.

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary: Skip SNMP link local test in 202311 branch.
ADO: 27684613
Skip SNMP link local test in 202311 branch.
Add 202311 branch in skip condition.
Remove Git issue from condition check as this test case will be skipped in those release branches and no plan to merge fix.

Skip SNMP link local test in 202311 branch

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
Microsoft ADO: 28273229
We have fixed gnmi end to end test, and we need to add gnmi in PR checker to prevent future error.
I updated pr_test_scripts.yaml to enable gnmi end to end test.
Run pipeline to check result.

Add gnmi case in PR test

---

.github/ISSUE_TEMPLATE/02-testgap.yml

Summary:
Add a issue template for test gap.
To add an issue template for the test gap issue using the "Test gap" label.

[Issue Template] Add test gap issue template

---

tests/common/helpers/gnmi_utils.py

202311 version of [PR#11552](https://github.com/sonic-net/sonic-mgmt/pull/11552)
Summary:

[sonic-mgmt] Call docker cmd on appropriate container in generate_telemetry_config() funct (202311)

---

sdn_tests/pins_ondatra/tests/gnmi_wildcard_subscription_test.go

- [sdn_tests]:Adding Wild Card tests to pins_ondatra.
Summary:
- Added Wild Card tests to pins_ondatra.
Build Result:
```
github.com/openconfig/gnsi/pathz/authorization.proto:43:1: warning: Import …
```

[sdn_tests]:Adding Wild Card tests to pins_ondatra.

---

azure-pipelines.yml

Summary:
For 202405 branch PR testing, branch "202405" instead of "master" should be used.

Fix the branch in pipeline yaml for 202405 PR testing

---

sdn_tests/pins_ondatra/tests/gnmi_set_get_test.go
sdn_tests/pins_ondatra/tests/lacp_test.go

- [sdn_tests]: Adding GNMI set get [module path/root path/encoding get] test in pins-ondatra.
Summary:
- Added GNMI set get [module path/root path/encoding get] test in pins-ondatra.
> github.com/openconfig/gnsi/pathz/pathz.proto:25:1: warning: Import github.com/openconfig/gnsi/version/version.proto is …

[sdn_tests]: Adding GNMI set get [module path/root path/encoding get] test in pins-ondatra.

---

docs/testbed/README.new.testbed.Configuration.md
docs/testbed/README.testbed.QosRpc.md

Summary:
add additional setup and image building guide to support qos sai test
add relevant documentation in doc folder
review

additional setup and image build for qos sai test

---

ansible/module_utils/port_utils.py

Update the list of 7800R3 SKUs that we match against in port_utils.py to reflect the SKUs that we currently support.

Fix Arista 7800R3 SKU names in port_utils.py

---

tests/syslog/test_syslog_source_ip.py

Fix Test_syslog_source_ip issue: https://github.com/sonic-net/sonic-mgmt/issues/6479
In MSFT env, ssh dut by hostname doesn't work, so update it with mgmt_ip
Summary:
Fix issue: https://github.com/sonic-net/sonic-mgmt/issues/6479
Replace duthost.hostname it with duthost.mgmt_ip
Run Test_syslog_source_ip
Any

Fix Test_syslog_source_ip issue

---

.azure-pipelines/testscripts_analyse/constant.py

In PR [#13079](https://github.com/sonic-net/sonic-mgmt/pull/13079), we add a script to caculate how many scripts are included in PR checker. But the scripts in sets "onboarding_" should not be included, as this set is just for test, the scripts in these sets may not success. After the scripts in sets "onboarding_" are stable, we will move them to corresponding topology set.
Summary:
In PR [#13079](https://github.com/sonic-net/sonic-mgmt/pull/13079), we add a script to caculate how many scripts are included in PR checker. But the scripts in sets "onboarding_" should not be included, as this set is just for test, the scripts in these sets may not success. After the scripts in sets "onboarding_" are stable, we will move them to corresponding topology set.

Exclude scripts under "onboarding_" while counting PR checker coverage

---

.azure-pipelines/testscripts_analyse/constant.py

In script `.azure-pipelines/testscripts_analyse/constant.py`, we will distinguish if a feature belongs to data plane or control plane.  The feature `pfcwd` should belong to data plane, we add it into data plane in this PR. 
Summary:
In script `.azure-pipelines/testscripts_analyse/constant.py`, we will distinguish if a feature belongs to data plane or control plane.  The feature `pfcwd` should belong to data plane, we add it into data plane in this PR.

Add pfcwd into dataplane features. 

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml
.azure-pipelines/testscripts_analyse/analyse_testscripts.py
.azure-pipelines/testscripts_analyse/requirements.txt
.azure-pipelines/testscripts_analyse/testscripts.collection.yml

In PR [#13079](https://github.com/sonic-net/sonic-mgmt/pull/13079), we enhance a script to trace the number of scripts included in PR checker. In this PR, we enable the pipeline to automatically run this script once a day. At the same time, we consider the skipped scripts as `included`. 
Summary:
In PR [#13079](https://github.com/sonic-net/sonic-mgmt/pull/13079), we enhance a script to trace the number of scripts included in PR checker. In this PR, we enable the pipeline to automatically run this script once a day. At the same time, we consider the skipped scripts as `included`.

Enable the pipeline to automatically cacualte the scripts included in PR checker. 

---

tests/scripts/getbuild.py

Summary:
Cherry-pick #13323 to 202205 branch.
The getbuild.py tool was indeed using Azure DevOps PAT for downloading artifacts. We need to deprecate using PAT. 
This change updated the getbuild.py to support using bearer access_token. With this change, both PAT and bearer access_token are supported. However, bearer access_token has higher priority.

[202205] Update getbuild.py to support both PAT and access_token (#13323)

---

tests/scripts/getbuild.py

Summary:
Cherry-pick #13323 to 202012 branch.
The getbuild.py tool was indeed using Azure DevOps PAT for downloading artifacts. We need to deprecate using PAT. 
This change updated the getbuild.py to support using bearer access_token. With this change, both PAT and bearer access_token are supported. However, bearer access_token has higher priority.

[202012] Update getbuild.py to support both PAT and access_token

---

.azure-pipelines/testscripts_analyse/testscripts.collection.yml

This is a bugfix of PR [#13321](https://github.com/sonic-net/sonic-mgmt/pull/13321). Previously, we set the wrong branch. The pipeline will run on public repo, so we will use master branch instead of internal. 
Summary:
This is a bugfix of PR [#13321](https://github.com/sonic-net/sonic-mgmt/pull/13321). Previously, we set the wrong branch. The pipeline will run on public repo, so we will use master branch instead of internal.

[Bugfix] Change check out branch  in pipeline TestscriptsCollection. 

---

tests/syslog/test_logrotate.py

Multi-asic support for sonic-mgmt  tests/syslog/test_logrotate.py  
Summary:
The test cases in test_logrotate were failing for t2 multi-asic. 
Added multi-asic supporting features to the test cases. 
Executed test cases for multi-asic and verify the results.

Multi_asic support for sonic-mgmt syslog test_logrotate.py

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Updated skip reasons to skips that were added in https://github.com/sonic-net/sonic-mgmt/pull/12183.
Update skip reasons in .yaml file.

Updated skip reasons on Mellanox platforms

---

docs/testbed/README.new.testbed.Configuration.md

Summary:
Add more explanation for sonic DUT fields, including iface_speed and syseeprom, if they are missing or incorrect, some cases may fail.
Explain some sonic DUT fields for example inventory file.
It can help others to setup testbed smoothly.

Add field explanation for example inventory file

---

.azure-pipelines/run-test-elastictest-template.yml

Summary:
Fix reference of variable for PR testing template

Fix reference of variable for PR testing template

---

sdn_tests/pins_ondatra/tests/BUILD.bazel
sdn_tests/pins_ondatra/tests/mgmt_interface_test.go

- [sdn_tests]:Adding MGMT Interface Test to pins_ondatra.
Summary:
- Added MGMT Interface Test to pins_ondatra.
Build Result:
```
sonic-mgmt/sdn_tests$ ./key.sh pins_ondatra
Keyword check Passed.
sonic-mgmt/sdn_tests/pins_ondatra$bazel build ...
github.com/openconfig/gnsi/acctz/acctz.proto:36:1: warning: Import …
```

[sdn_tests]:Adding MGMT Interface Test to pins_ondatra.

---

azure-pipelines.yml

Summary:
To simplify code change for PR testing template, we are using the same template from branch for all older release branches like 202012, 202205, 202305.
For later release branches like 202311 and 202405, we need to use the same strategy.
This change updated 202311 branch PR testing to use common template from master branch.

[202405] Use common PR test template from master branch

---

azure-pipelines.yml

Summary:
To simplify code change for PR testing template, we are using the same template from branch for all older release branches like 202012, 202205, 202305.
For later release branches like 202311 and 202405, we need to use the same strategy.
This change updated 202311 branch PR testing to use common template from master branch.

[202311] Use common PR test template from master branch

---

tests/platform_tests/sfp/test_show_intf_xcvr.py

In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. In this PR, we fix the failed test script `platform_tests/sfp/test_show_intf_xcvr.py` and let it run successfully in T0 PR checker. 
Summary:
In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. In this PR, we fix the failed test script `platform_tests/sfp/test_show_intf_xcvr.py` and let it run successfully in T0 PR checker. 
```
------------------------------------------------------------------ live log sessionfinish ------------------------------------------------------------------
08:22:25 …
```

Add `platform_tests/sfp/test_show_intf_xcvr.py` into T0 PR checker.

---

ansible/roles/test/files/ptftests/py3/generic_hash_test.py
tests/common/devices/sonic.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/hash/conftest.py
tests/hash/generic_hash_helper.py
tests/hash/test_generic_hash.py

Enhance Generic Hash test to cover 6 new supported fields and algorithm configuration.
Related test plan: https://github.com/sonic-net/sonic-mgmt/pull/11823
Summary:
1. Add support for 6 new fields
2. Update show parse function
3. Add algorithm configure and validate test
4. Adapt on dualtor setup
5. Skip cases on SPC1 due to hardware limitation
6. Add list support for option --algorithm and --hash_field according to community review request 
7. Update dynamic supported algorithm check
Enhance Generic Hash test to cover 6 new supported fields and algorithm configuration.
Add related test functions.
No
T0 and T1 topology.

Enhance generic hash test cases

---

tests/platform_tests/mellanox/check_sysfs.py

Summary:
Modify a comment based on a suggestion in PR: https://github.com/sonic-net/sonic-mgmt/pull/13309

check_sysfs.py: Modify a comment

---

.azure-pipelines/testscripts_analyse/report_data_storage.py

Summary:
Fix incorrect authentication function

Fix incorrect authentication function

---

docs/testplan/DHCP-relay-stress-test.md

Summary:
The DHCP Relay Stress Test Plan is to evaluate the performance of the DHCP relay service under maximum load conditions. This test is to ensure the service can handle under a high traffic condition and verify the CPU utilisation.
test description: https://github.com/sonic-net/sonic-mgmt/issues/3614

DHCP Relay Stress Test v1

---

ansible/vars/topo_t2-ixia-2lc-4.yml
ansible/vars/topo_t2-ixia-3lc-4.yml

Summary:
Add two new topology for T2 ixia testing.
topo_t2-ixia-2lc-4.yml  --> topology used for ixia testing.
topo_t2-ixia-3lc-4.yml  --> topology used for deploy-mg
New topology which are needed for T2 ixia testing.
Add two new topology for T2 ixia testing.  topo_t2-ixia-2lc-4.yml and topo_t2-ixia-3lc-4.yml
Manual testing was done successfully.

new T2 ixia topology files

---

tests/common/plugins/allure_server/__init__.py

Allure report could not display 'Version', 'Platform' and 'HwSKU' values for dualtor setup. Previuosly we cannot get all dut information by testbed for dualtor setup, currently we get the dut information from ansible_host_pattern.
Summary:
Fix allure report issue
Get the dut information from ansible_host_pattern.
run it on dualtor or non-dualtor setup
any
any

Fix allure report issue that doesn't display 'Version', 'Platform' and 'HwSKU' values for dualtor setup

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml

In PR #13220, we add a batch of control plane test scripts into onboarding t0 PR checker. After one week's running, some of them are stable enough, so move them to t0 PR checker. And some of them are skipped due to different reasons, and move them to the script `.azure-pipelines/pr_test_skip_scripts.yaml`. 
Summary:
In PR #13220, we add a batch of control plane test scripts into onboarding t0 PR checker. After one week's running, some of them are stable enough, so move them to t0 PR checker. And some of them are skipped due to different reasons, and move them to the script `.azure-pipelines/pr_test_skip_scripts.yaml`.

Move some stable test scripts to t0 PR checker. 

---

tests/syslog/test_syslog_rate_limit.py

Summary:
syslog rate limit test failed on multi asic chasssis. The reason is that test code does not have support for multi asic. In multi asic scenario the container can be either global (pmon, snmp etc) or per asic scope (macsec0, macsec1, swss0 etc). In multi asic scenario for all per asci scope features the service name is different with container name.
Add check for each feature, get the running config facts for feature. If has_per_asic_scope is true will randomly choose one container (macsec0 for example) to test rate limit. Add code to handle container name in this scenario.
Test failed
Add check for each feature, get the running config facts for feature. If has_per_asic_scope is true will randomly choose one container (macsec0 for example) to test rate limit. Add …

Add multi-asic support for syslog rate limit test

---

tests/qos/test_ecn_config.py

Summary:
Needed to uplift the  case to Validate the ECN configuration 
- To avoid assuming lossless PG as 3 and 4
- Check for and skip interfaces not having pfc_enable
Summary:
1) read PORT_QOS_MAP and check for interfaces and pfc_enable configuration 
2) Skip verification if pfc_enable is not set
3) Verify for each PG present in pfc_enable and remove assumption of 3 and 4 as lossless PG
the existing script was verifying marking configuration for only lossless 3 and 4.
Uplifted to make it generic by reading the configuration for lossless PGs.
Verified it on Cisco box 
1) By having interfaces with no PFC configuration
2) Having interfaces with selected PFC configuration

Enhanced  Cisco specific ECN marking config verification test

---

ansible/files/graph_groups.yml
ansible/files/sonic_example_ixia_devices.csv
ansible/files/sonic_example_ixia_link.csv
ansible/files/sonic_snappi-sonic_devices.csv
ansible/files/sonic_snappi-sonic_links.csv
ansible/group_vars/snappi-sonic/secrets.yml
ansible/group_vars/snappi-sonic/snappi-sonic.yml
ansible/snappi-sonic
ansible/testbed.csv
ansible/testbed.yaml
tests/snappi_tests/DockerCommands.md
tests/snappi_tests/README.md

(cherry picked from commit c8ff8c51921e4e1ba3ef302fa5d2d63e3fa9c53d)
Summary:
Cherry-pick #13245 into 202405

Adding ansible file samples for snappi-sonic (#13245) [202405]

---

.hooks/pre_commit_hooks/check_conditional_mark_sort.py

Summary:
Refine the output of conditional_mark order check.
Print more detailed information so that contributors know where to modify.
Before enhance, only tell there's mis-order, but not how to modify.
```
check conditional mark sort..............................................Failed
- hook id: check-conditional-mark-sort
- exit code: 1
The entries in tests/common/plugins/conditional_mark/tests_mark_conditions*.yaml are not sorted in alphabetic order.
```
After enhance:
```
check conditional mark sort..............................................Failed
- hook id: check-conditional-mark-sort
- exit code: 1
The entries in tests/common/plugins/conditional_mark/tests_mark_conditions*.yaml are not sorted in alphabetic order.
The entries in …
```

[pre-commit]Refine the output of conditional mark order check

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py

Summary:
This is the second part of the work for eliminating client secrets.
This change depends on merge of #13435.
This change updated the test_plan.py to get access token by az cli. For the az cli command to work, the task calling test_plan.py must be wrapped in an AzureCLI azure pipeline task.

Update test_plan.py to get token via az cli

---

tests/platform_tests/cli/test_show_platform.py

In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. In this PR, we fix the failed test script `platform_tests/cli/test_show_platform.py` and let it run successfully in T0 PR checker. 
Summary:
In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. In this PR, we fix the failed test script `platform_tests/cli/test_show_platform.py` and let it run successfully in T0 PR checker.

Add script `platform_tests/cli/test_show_platform.py` into T0 PR checker. 

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml
azure-pipelines.yml
tests/dualtor_mgmt/test_server_failure.py
tests/dualtor_mgmt/test_toggle_mux.py

In this PR, we add a new PR checker called `onboarding dualtor`. This new PR checker is for onboarding dualtor speific test scripts. Also, we modify the pytest mark from `t0` to `dualtor` of two dualtor specific scripts to make it more clear. 
Summary:
In this PR, we add a new PR checker called `onboarding dualtor`. This new PR checker is for onboarding dualtor speific test scripts. Also, we modify the pytest mark from `t0` to `dualtor` of two dualtor specific scripts to make it more clear. 
Add a new PR checker called `onboarding dualtor`. Also, we modify the pytest mark from `t0` to `dualtor` of two dualtor specific scripts to make it more clear.

Add onboarding dualtor PR checker

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Summary:
Enhance skip reason for test_warm_reboot and test_fast_reboot.

enhance skip reason for test_warm_reboot and test_fast_reboot

---

tests/platform_tests/thermal_control_test_helper.py

Summary:
Fix skip log without parameter error.

Fix log print error

---

.azure-pipelines/pr_test_scripts.yaml
tests/telemetry/telemetry_utils.py
tests/telemetry/test_telemetry_cert_rotation.py

Summary:
Fixes # (issue) 27488707
Add automation tests for verifying correct telemetry server behavior when certs are removed, changed, and added
Add testcases for
1) Process running without certs
2) Server not running after certs are deleted
3) Server running after certs are added
4) Server running after certs are changed
Pipeline/Manual

Telemetry cert rotation tests

---

ansible/module_utils/port_utils.py

Summary:
Add Marvell new hwsku port alias mapping
- [ X] 202305
- [X ] 202311
Adding new product support

Add Marvell new hwsku port alias mapping

---

.azure-pipelines/pr_test_skip_scripts.yaml
.azure-pipelines/testscripts_analyse/analyse_testscripts.py
.azure-pipelines/testscripts_analyse/constant.py

Summary:
In analyze test, we do not have tgen/snappi/ptf topo, but we have such marks in test scripts
Add tgen/snappi/ptf topo type and topo map

Add new topo type and map in analyze test

---

tests/common/plugins/sanity_check/checks.py

Summary:
Add debug info for ADO 28489716
To check the ipv6_mgmt_only failures `failed on setup with "Failed: str3-8102-01 doesn't have available IPv6 Management IP address"` in nightly test.
Add additional debugs before each test run, and check the ipv6 reachability issue.
Verified reachable, unreachable and attribute scenarios.

add ipv6_mgmt sanity check for debugging

---

.azure-pipelines/testscripts_analyse/analyse_testscripts.py

Summary:
In analyze_testscripts, when we calculate which test scripts has been manually checked with skip, we get topo keys from `pr_test_scripts.yml`, then add test scripts with keys of `pr_test_scripts.yml` in `pr_test_skip_scripts.yml`. But we will miss scripts in `pr_test_skip_scripts.yml` with keys not in `pr_test_scripts.yml` like `tgen`, so the calculation is not accurate.
Get all keys from `pr_test_scripts.yml`, if keys in `pr_test_scripts.yml`, add test scripts, if keys not in `pr_test_scripts.yml`, add keys and test scripts.
Run analyze_testscripts.py locally

Support analyze testscripts for topologies in PR test skip yml only

---

.azure-pipelines/testscripts_analyse/analyse_testscripts.py

Summary:
In PR https://github.com/sonic-net/sonic-mgmt/pull/13663, I added test scripts dict from pr_test_skip_scripts to pr_test_scripts, then used pr_test_skip_scripts for following steps, but it should be pr_test_scripts
Use pr_test_scripts dict for following steps
Run locally and checked the result

Fix typo in analyse test to use correct variable

---

tests/generic_config_updater/test_cacl.py

Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/13543 into 202311

[202311][Test Gap] Cover all cacl protocols in GCU test_cacl

---

tests/generic_config_updater/test_cacl.py

Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/13543 into 202405

[202405][Test Gap] Cover all cacl protocols in GCU test_cacl

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Reverts sonic-net/sonic-mgmt#13301

Revert "Remove skip condition for test_syslog_source_ip"

---

tests/decap/test_decap.py

Summary:
In KVM decap test, we have skipped running ptf script `IP_decap_test.py` since KVM do not support traffic test in decap, but it got some log analyzer error when deleting decap config, because some config was added by ptf script.
`
E               tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzerError: match: 4
E               expected_match: 0
E               expected_missing_match: 0
E
E               2024 Jul 16 01:00:54.945659 vlab-01 ERR swss#orchagent: :- doDecapTunnelTask: unknown decap tunnel table attribute 'dst_ip'.
E
E               2024 Jul 16 01:00:57.145830 vlab-01 ERR swss#orchagent: :- doDecapTunnelTask: unknown decap tunnel table attribute 'dst_ip'.
E
E               2024 Jul 16 01:00:57.151199 vlab-01 ERR …

Add decap loganalyzer ignore regex in KVM test

---

tests/bgp/conftest.py
tests/bgp/test_traffic_shift.py

Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/13409
Fix fixture import issue report in https://github.com/sonic-net/sonic-mgmt/issues/13409
Moved fixture to conftest and changed scope
Run test_seq_idf_isolation.py and test_traffic_shift.py to verify fixture is found while running the tests

Move traffic shift community fixture to conftest

---

tests/common/snappi_tests/snappi_fixtures.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_basic_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_burst_storm_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_multi_node_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_runtime_traffic_helper.py
tests/snappi_tests/pfcwd/files/pfcwd_basic_helper.py
tests/snappi_tests/pfcwd/files/pfcwd_burst_storm_helper.py
tests/snappi_tests/pfcwd/files/pfcwd_multi_node_helper.py
tests/snappi_tests/pfcwd/files/pfcwd_runtime_traffic_helper.py

Summary: Adding support for PFCWD  cases for pfcQueueGroupSize of 4
This PR supports pfcQueueGroupSize of 4 for pfcwd cases , currently the support is for 8

Adding support for PFCWD  cases for pfcQueueGroupSize of 4

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
Currently, test_events has some test issues with high failure rate which blocked PR testing
Temporary skip test_events in PR testing

Temporary skip test_events due to test issue with high failure rate

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
Currently, test_events has some test issues with high failure rate which blocked PR testing
Cherry-pick of PR https://github.com/sonic-net/sonic-mgmt/pull/13739
Temporary skip test_events in PR testing

[202305] Temporary skip test_events due to test issue with high failure rate

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
Currently, test_events has some test issues with high failure rate which blocked PR testing
Cherry-pick of PR https://github.com/sonic-net/sonic-mgmt/pull/13739
Temporary skip test_events in PR testing

[202311] Temporary skip test_events due to test issue with high failure rate

---

tests/common/plugins/sanity_check/checks.py

Summary:
Add more debugs for ADO 28738579
When dbmemory is over threshold, there is no output to trace what was holding the redis memory.
Add more debug info into the log

add debug for omem check

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Revert "Added temporary skip to system_health TC for MLX platfroms " https://github.com/sonic-net/sonic-mgmt/pull/12798, because there is a fix: https://github.com/sonic-net/sonic-mgmt/pull/12895
Summary:
Remove the skip condition
Remove it
Run test_device_checker 
Mellanox

Revert "Added temporary skip to system_health TC for MLX platfroms "

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Summary: Add skip for test_service_warm_restart test by github issue:  https://github.com/sonic-net/sonic-mgmt/issues/10362

Add skip for test_service_warm_restart test by github issue

---

ansible/roles/fanout/library/port_config_gen.py

Update the port_config.ini file parsing algorithm to overcome some blank lines before header
Update the port_config.ini file parsing algorithm to overcome comments in the middle or at the end
Summary:
When there are some blank lines before header line in port_config.ini, current algorithm could not handle that.
When there are comments in the middle or at the end, current algorithm could not handle that.
Find and parse header from the end line to the upper line.
Overcome comments in the middle or at the end.
Verify it in internal regression

Update port_config.ini file parsing algorithm

---

tests/gnmi/helper.py
tests/gnmi/test_gnmi_configdb.py
tests/gnmi/test_gnmi_countersdb.py

Summary:
Need new test to verify gnmi-native subscribe API.
Microsoft ADO: 25282671
Need new test to verify gnmi-native subscribe API.
Add test to verify subscribe polling mode with DEVICE_METADATA table in CONFIG_DB.
Add test to verify subscribe streaming sample mode with DEVICE_METADATA table in CONFIG_DB.
Add test to verify subscribe streaming onchange mode with DEVICE_METADATA table in CONFIG_DB.
Add test to read COUNTERS_QUEUE_NAME_MAP table in COUNTERS_DB.
Add test to read COUNTERS table in COUNTERS_DB.
Add test to verify subscribe polling mode with COUNTERS_PORT_NAME_MAP table in COUNTERS_DB.
Add test to verify subscribe streaming sample mode with COUNTERS_PORT_NAME_MAP table in COUNTERS_DB.
Add test to verify subscribe polling mode with COUNTERS table in …

Add gnmi test to verify subscribe API

---

tests/configlet/util/base_test.py

ADO: 28820713
Summary: Enhance the folder check if dir already exists
Enhancement
Add check beofre mkdir
Manual tet

[configlet] Improve test if folder already exists

---

.azure-pipelines/pr_test_scripts.yaml

In PR #13696, there is a new added module `test_gnmi_countersdb.py`. In this PR, add this new module into onboarding PR checker. If it is stable enough, we will move it to the standard PR checker. 
Summary:
In PR #13696, there is a new added module `test_gnmi_countersdb.py`. In this PR, add this new module into onboarding PR checker. If it is stable enough, we will move it to the standard PR checker. 
Add the new added module `test_gnmi_countersdb.py` into onboarding T0 and T1 PR checker.

Add new added module `test_gnmi_countersdb.py` into onboarding PR checker. 

---

ansible/roles/test/files/mlnx/docker-tests-pfcgen-asic/pfc_gen.py
tests/common/helpers/pfc_storm.py
tests/common/templates/pfc_storm_mlnx_sonic.j2
tests/common/templates/pfc_storm_stop_mlnx_sonic.j2

1. Deploy pfc_gen.py to mellanox sonic syncd container in pfc_storm helper
2. Add code to handle mellanox sonic pfc generation steps
3. Add jinja file for start and stop pfc storm at mellanox sonic fanout
4. Enhance pfc_gen.py to support asic based pfc storm generation for mellanox sonic as well as onyx fanout a. Add label port to logical port mapping
Summary:
To support generate asic based pfc strom on Mellanox SONiC fanout switch
1. Deploy pfc_gen.py to mellanox sonic syncd container in pfc_storm helper
2. Add code to handle mellanox sonic pfc generation steps
3. Add jinja file for start and stop pfc storm at mellanox sonic fanout
4. Enhance pfc_gen.py to support asic based pfc storm generation for mellanox sonic as well as onyx fanout 
a. Add label port to logical port …

Add asic based pfc generation function for mellanox sonic fanout

---

.azure-pipelines/pr_test_scripts.yaml
tests/platform_tests/test_link_down.py

In this PR, we add the module `test_link_down.py` into onboarding PR checker. 
Summary:
In this PR, we add the module `test_link_down.py` into onboarding PR checker.

Add test_link_down.py into onboarding PR checker. 

---

.azure-pipelines/test_plan.py

Summary:
The `az login` issue is not fully resolved. Running `az account get-access-token` is still failing. Need to add some log for debugging.
This change added code to log successful `az login` and `az account get-access-token` events.

Add log for successful az login and az account get-access-token

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Script `test_pktgen.py` has a known issue, and will skip on all testbeds using conditional marks. Previously, there is only the reason in condition marks. In this PR, we add an issue as the condition, and when the issue is closed, this script will not be skipped. Also, we add this script into PR checkers. 
Summary:
Script `test_pktgen.py` has a known issue, and will skip on all testbeds using conditional marks. Previously, there is only the reason in condition marks. In this PR, we add an issue as the condition, and when the issue is closed, this script will not be skipped. Also, we add this script into PR checkers. 
- Add an issue as the condition in conditional marks. 
- Add script `test_pktgen.py` into PR checkers.

Add the script `test_pktgen.py` into PR checkers. 

---

tests/syslog/test_logrotate.py

…3795)
Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/13451
On a chatty device, when the file size reaches 0.9 times the threshold, it quickly exceeds the limit, causing a false positive error by triggering log rotation.
Create a temporary file at half the threshold size to ensure ample space is available before the actual log rotation occurs.
Verified the test Mellanox 4700 testbed

 [PR:13795] Reduce the temp file size to verify logrotate for small_size

---

tests/syslog/test_logrotate.py

Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/13451
On a chatty device, when the file size reaches 0.9 times the threshold, it quickly exceeds the limit, causing a false positive error by triggering log rotation.
Create a temporary file at half the threshold size to ensure ample space is available before the actual log rotation occurs.
Verified the test Mellanox 4700 testbed

[PR:13795] Reduce the temp file size to verify logrotate for small_size

---

.azure-pipelines/testscripts_analyse/analyse_testscripts.py

In PR #13079, we validate and trace the test scripts in PR checker. The pretest and posttest phases are deemed as "covered" in the PR checker, despite not being listed in the file `pr_test_scripts.yaml`. To acknowledge this coverage, the current PR hardcode this detail.
Summary:
In PR #13079, we validate and trace the test scripts in PR checker. The pretest and posttest phases are deemed as "covered" in the PR checker, despite not being listed in the file `pr_test_scripts.yaml`. To acknowledge this coverage, the current PR hardcode this detail.
Hardcode the pretest and posttest as covered in PR checker.

Set posttest and pretest as covered in test scripts calculation. 

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Include cacl/test_cacl_application.py back in pr_test_scripts.yml
Include cacl/test_cacl_application.py back in pr_test_scripts.yml

Add cacl/test_cacl_application.py back in pr_test_scripts

---

.azure-pipelines/testscripts_analyse/analyse_testscripts.py

This is a bugfix of #13859, we should use the key `testscript` to get the script name and do determination. 
Summary:
This is a bugfix of #13859, we should use the key `testscript` to get the script name and do determination.

[Bugfix] Set posttest and pretest as covered in test scripts calculation.

---

.azure-pipelines/testscripts_analyse/analyse_testscripts.py
.azure-pipelines/testscripts_analyse/setup.kql

We already have the script to validate and trace the test scripts in PR checker. In this PR, we enhance this script, add a field to indicate if this script is recorded in our skip list. 
Summary:
We already have the script to validate and trace the test scripts in PR checker. In this PR, we enhance this script, add a field to indicate if this script is recorded in our skip list. 
Add a filed to indicate if the script is recorded in our skip list.

Add a field `IsSkipped` to indicate if a script is skipped in PR checker. 

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

We get the error `Failed: Arp info for portchannel is not correct` while running test script `test_lag_member.py` on T0 kvm testbed. So in this PR, although we add this case into T0 PR checker, we use conditional mark to skip it temporarily. After the issue being fixed, this script can run in PR checker successfully. 
Summary:
We get the error `Failed: Arp info for portchannel is not correct` while running test script `test_lag_member.py` on T0 kvm testbed. So in this PR, although we add this case into T0 PR checker, we use conditional mark to skip it temporarily. After the issue being fixed, this script can run in PR checker successfully. 
Add the script `test_lag_member.py` into T0 PR checker and use conditional mark to skip it temporarily.

Add test_lag_member.py into T0 PR checker

---

tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
tests/snappi_tests/multidut/pfc/files/multidut_helper.py

Summary:
Fixes duthost port mapping issue in multidut PFC test cases. 
PFCWD and ECN test cases were fixed in #13541 . This PR is to finish the change for PFC test cases too.
Fixes duthost port mapping issue in multidut PFC test cases. 
Same method as #13541
manually tested it locally.

[Snappi] change duthost/port mapping for multidut PFC test cases.

---

tests/platform_tests/test_reload_config.py

Summary:
For Nokia-7215, 120 seconds is not enough for `config reload` command. Extend the time to 180s to make testcase stable.
For Nokia-7215, 120 seconds is not enough for `config reload` command. Extend the time to 180s to make testcase stable.
Set `config reload` timeout to 180s for Nokia-7215.
Verified on Nokia-7215 Mx testbed.

[Nokia-7215] Set timeout = 180s for config reload cmd

---

tests/scripts/getbuild.py

Summary:
When the getbuild.py tool fail with downloading artifacts, it is not easy to quickly root cause.
This change updated the code to log full URL for downloading artifacts. Then when this tool failed, we can quickly do a manual check to find out if the issue is with the URL, server, or permission.

Log full url in the getbuild.py tool

---

.azure-pipelines/run-test-elastictest-template.yml

Summary:
The nightly test pipeline always get cancelled regardless the checking of ${{ parameters.TEST_PLAN_TYPE }}.
This change updated the code to explicity assign the parameter to a variable. Then compare variable with expected value. Also added a echo for debugging purpose.

Fix nightly test always get cancelled issue

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

the issue is fixed by a new SDK 4000
Change-Id: I8644f90a887044df2ae7b5224103b973999fdaa9
Summary:

remove skip of bgp/test_bgp_queue.py on Mellanox platform

---

tests/snmp/test_snmp_fdb.py

Summary:
In some scenario that this case would fail because dummy MAC count miss portchannel data. Hence add time wait
Add time wait for portchannel up
Run test on t0 and m0. passed

[snmp] Add wait portchannel up in test_snmp_fdb

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Script `test_snmp_queue_counters.py` will get an KeyError while running on kvm testbed due to no buffer queue `Ethernet0|3-4` on kvm testbed. So in this PR, we use conditional mark to skip this script temporarily and add it into T0 PR checker. After the issue being fixed, it will run into the T0 PR checker. 
Summary:
Script `test_snmp_queue_counters.py` will get an KeyError while running on kvm testbed due to no buffer queue `Ethernet0|3-4` on kvm testbed. So in this PR, we use conditional mark to skip this script temporarily and add it into T0 PR checker. After the issue being fixed, it will run into the T0 PR checker. 
Use conditional mark to skip this script temporarily and add it into T0 PR checker.

Add snmp queue counters into T0 PR checker. 

---

.azure-pipelines/pr_test_scripts.yaml

The script `test_reboot.py` was fixed in PR #13979, and recently, it is stable enough. So, move it from onboarding T0 PR checker to standard PR checker. 
Summary:
The script `test_reboot.py` was fixed in PR #13979, and recently, it is stable enough. So, move it from onboarding T0 PR checker to standard PR checker. 
Move the script `test_reboot.py` from onboarding T0 PR checker to standard PR checker. 
vms-kvm-t0 | platform_tests/test_reboot.py | 2024-08-11 00:00:00.0000000 | 18 | 0 | 18 | 1
vms-kvm-t0 | platform_tests/test_reboot.py | 2024-08-10 00:00:00.0000000 | 6 | 0 | 6 | 1
vms-kvm-t0 | platform_tests/test_reboot.py | 2024-08-09 00:00:00.0000000 | …

Move test_reboot.py from onboarding PR checker to standard PR checker. 

---

tests/arp/test_stress_arp.py

Cherry pick conflict #13861
Summary:
Cherry pick conflict #13861

[202311] Tolerate hash collision when adding entries in test_stress_arp.py

---

tests/arp/test_stress_arp.py

Cherry pick conflict #13861 
Summary:
Cherry pick conflict #13861

[202405] Tolerate hash collision when adding entries in test_stress_arp.py

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
There is a new test which failed on platform other than Mellanox, opened an issue to track the issue and set it as xfail in master branch.
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/14109

[hash/test_generic_hash] xfail new case which failed on other platforms

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
test_add_rack.py has a high failure rate for PortChannel missing after patch, and is blocking PR test, after check, it's image issue https://github.com/sonic-net/sonic-buildimage/issues/19942
xfail test_add_rack.py with issue https://github.com/sonic-net/sonic-buildimage/issues/19942

xfail test_add_rack.py for image issue

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py

[CI]Enhance elastictest pipeline, print test summary and error message for better review
test results:
https://dev.azure.com/mssonic/build/_build/results?buildId=618060&view=logs&jobId=0cb31af1-9c12-5e3c-148e-856fdcff3a02&j=d8871267-39af-5540-59d2-ff1a86c185cf&t=52b17f45-d1f6-564e-f9ec-44e26c8905ba

[CI]Enhance elastictest pipeline, print test summary and error message for better review

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
`bgp/test_bgp_stress_link_flap.py` is a newly added test script, but it have chance to get stuck for unknown reason:
https://elastictest.org/scheduler/testplan/66beb14c279305ddb0527383?leftSideViewMode=detail&prop=end_time&order=descending&testcase=bgp%2Ftest_bgp_stress_link_flap.py&type=console
Move to onboarding test job, if stable, in 1 week, will move back to PR test set

Move bgp/test_bgp_stress_link_flap.py to onboarding test job

---

ansible/group_vars/sonic/sku-sensors-data.yml
tests/common/mellanox_data.py

1. Add platform data for x86_64-nvidia_sn4280-r0
2. Add sensors data for x86_64-nvidia_sn4280-r0
Summary:
Add platform data and sensors data for x86_64-nvidia_sn4280-r0
Add relevant data
Run sensors and platform tests on x86_64-nvidia_sn4280-r0
x86_64-nvidia_sn4280-r0
Any

[Mellanox] Add platform data and sensors data for x86_64-nvidia_sn4280-r0

---

tests/common/helpers/pfc_gen.py
tests/common/templates/pfc_storm_stop_eos.j2
tests/pfcwd/files/pfcwd_helper.py

Summary:
This PR is to enhance pfc_gen script to support multi-processing to generate more PFC pause frames.
The current pfc_gen script is single thread. We saw some PFCWD test is flay because it can't generate enough PFC pause frames to trigger PFC srorm on DUT.
This PR enhanced the script to support multi-processing to reduce flakiness in test. 
Change list
1. Enhance pfc_gen.py to support multi-processing
2. Update [pfc_storm_stop_eos.j2](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:pfc_gen_mp?expand=1#diff-454591a1010b66cbe0da38fa9cf1d25bb084e9445802d74ec6cc6035f17c5e2f) to support the multi-processing script (remove sudo in the command pattern as subprocess doesn't have sudo)
3. Send more back ground traffic.
This PR is to enhance pfc_gen script to support …

Enhance pfc_gen script to support multi-processing

---

.azure-pipelines/pr_test_scripts.yaml

Add script `show_techsupport/test_auto_techsupport.py` into T1 PR checker. 
Summary:
Add script `show_techsupport/test_auto_techsupport.py` into T1 PR checker. 
Move script `show_techsupport/test_auto_techsupport.py` from onboarding T1 PR checker to T1 PR checker.
vms-kvm-t1-lag | show_techsupport/test_auto_techsupport.py | 2024-08-18 00:00:00.0000000 | 25 | 0 | 25 | 1
vms-kvm-t1-lag | show_techsupport/test_auto_techsupport.py | 2024-08-17 00:00:00.0000000 | 40 | 0 | 40 | 1
vms-kvm-t1-lag | show_techsupport/test_auto_techsupport.py | 2024-08-16 00:00:00.0000000 | 165 | 1 | 166 | 0.994
vms-kvm-t1-lag | show_techsupport/test_auto_techsupport.py | …

Add test_auto_techsupport.py into T1 PR checker. 

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Update skip condition for test_tunnel_memory_leak
Skip dualtor/test_tunnel_memory_leak.py by github issue https://github.com/sonic-net/sonic-mgmt/issues/11403 on dualtor-64 topology
Summary:
Script dualtor/test_tunnel_memory_leak.py not stable on dualtor-64 topology.
Skip dualtor/test_tunnel_memory_leak.py by github issue https://github.com/sonic-net/sonic-mgmt/issues/11403 on dualtor-64 topology
No

Update skip condition for test_tunnel_memory_leak

---

ansible/roles/test/files/ptftests/py3/pfc_wd_background_traffic.py

Summary:
This PR is to enhance `pfc_wd_background_traffic.py` to use random src/dst udp port to ensure the traffic has sufficient entropy to be hashed to different egress ports.
The change is required because when the Egress port is a LAG and there are more than 1 port in the LAG, the background traffic is only egressed from 1 port. In order to trigger PFC watchdog, the background traffic is required.
This PR is to enhance `pfc_wd_background_traffic.py` to use random src/dst udp port to ensure the traffic has sufficient entropy to be hashed to different egress ports.
1. Change the IP packet to UDP packet
2. Use random src and dst UDP ports for background traffic. 
The change is verified on a physical testbed. The background traffic is distributed to different ports.
Mellanox platform.
Not …

Use random sport/dport in background traffic for PFCWD test

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Command `show suppress-fib-pending` doesn't support on image before release 202405. So we skip this script on master image and add this script into PR checker. 
Summary:
Command `show suppress-fib-pending` doesn't support on image before release 202405. So we skip this script on master image and add this script into PR checker. 
Skip this script on master image.

Skip script bgp/test_bgp_suppress_fib.py on master image. 

---

tests/common/dualtor/mux_simulator_control.py

Summary:
Fix the toggle failures.
Let's enable the mux probe in the consistency check for faster recovery.
Run with dualtor testbed.

[dualtor] Improve the toggle fixture

---

.pre-commit-config.yaml
pyproject.toml

Summary:
PR https://github.com/sonic-net/sonic-mgmt/pull/13544 has refined the output of check-conditional-mark-sort hook in pre-commit check. Would print more detailed information so that contributors know where to modify. So needs to update pre-commit version.
Add a new tag 1.0.1+pre_commit of sonic-mgmt, then update the version in code
Checked in local env

Update pre-commit version to 1.0.1+pre_commit

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
`test_events.py` is flaky in PR test, would block some PRs, the root cause should be image issue
Create image issue https://github.com/sonic-net/sonic-buildimage/issues/19943 and xfail `test_events.py` in PR test

xfail flaky test script `test_events.py` for image issue

---

docs/testbed/README.testbed.VsSetup.md
docs/testbed/README.testbed.WANSetup.md

Summary:
The cEOS image downloading has been improved in PR #13840. This change updated the document accordingly.
Improved the cEOS downloading documentation.

Improve the document for cEOS image downloading

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
This is a stress test, sometime cause hung issue
create a github issue and skip it in nightly test at this moment.
NA

skip test_bgp_stress_link_flap

---

docs/testplan/dash/Dash-Relaxed-Match-Support.md
tests/dash/conftest.py
tests/dash/packets.py
tests/dash/test_dash_vnet.py
tests/dash/test_relaxed_match_negative.py

Summary:
This is the manual cherry-pick of PR(#11630) to 202405 for conflict resolving.

[202405] [Dash] Relaxed match support (cherry-pick #11630)

---

tests/platform_tests/link_flap/test_cont_link_flap.py

Summary:
This is to cover the BGP memory leak test gap.
Previously we have an issue in FRR(https://github.com/FRRouting/frr/issues/15459), which caused memory leak.
This is to cover the BGP memory leak test gap.
I added a checker for the FRR daemons(bgpd and zebra) used memory in the test test_cont_link_flap.py. The reason why I added the checker in test_cont_link_flap.py but not the stress route test, is because we already have some memory and cpu checkers in the link flap test. And the link flap also causes routes announce/withdraw like what we have in the stress route test.
Run the test and it passed.

[BGP Memory Leak] Add FRR memory checker in the continuous link flap test

---

tests/route/test_route_flow_counter.py
tests/stress/utils.py

The typo "neighbhor" ip bgp summary is fixed in the https://github.com/sonic-net/sonic-utilities/pull/3375, need to align the test case. 
Summary:

Align the sonic-mgmt code based on the typo  "neighbhor"  fix in the image

---

tests/conftest.py

Summary:
The initialization of fixture nbrhosts costs a long time, especially on the testbeds that with lots of neighbors, like t1-lag or t2, convert it to multi-thread way to enhance the performance.
Use multi-thread pool to initialize the neighbor ansible_hosts
Run test_nbr_health.py on both T1-lag and T2 physical testbeds, both of them passed.

[Feat] Initialize neighbor ansible_hosts with multi thread way

---

tests/common/snappi_tests/snappi_helpers.py

Summary:Adding support for breakout links
This PR supports the addition of breakout ports 
Instead of mentioning Card info , we can dirently mention the fanout port info in the ansible/links file example Port1.1, Port1.2 and so on

[Snappi]: Adding support for breakout links

---

.azure-pipelines/pr_test_scripts.yaml

Add script test_bgp_suppress_fib.py into T1 PR checker 
Summary:
Add script test_bgp_suppress_fib.py into T1 PR checker 
vms-kvm-t1-lag | bgp/test_bgp_suppress_fib.py | 2024-08-26 00:00:00.0000000 | 7 | 0 | 7 | 1
vms-kvm-t1-lag | bgp/test_bgp_suppress_fib.py | 2024-08-25 00:00:00.0000000 | 28 | 0 | 28 | 1
vms-kvm-t1-lag | bgp/test_bgp_suppress_fib.py | 2024-08-24 00:00:00.0000000 | 42 | 0 | 42 | 1
vms-kvm-t1-lag | bgp/test_bgp_suppress_fib.py | 2024-08-23 00:00:00.0000000 | 168 | 0 | 168 | 1
vms-kvm-t1-lag | bgp/test_bgp_suppress_fib.py | 2024-08-22 00:00:00.0000000 | 189 | 0 | 189 | 1

Add test_bgp_suppress_fib.py to T1 PR checker

---

tests/bfd/conftest.py

As discussed in the last chassis meeting, we want to temporarily disable orchagent CPU check for BFD tests as it is not stable at the moment.
Summary:
Fixes # (issue) Microsoft ADO 29191540
I ran the updated BFD tests and confirmed that orchagent check is disabled

chore: temporarily disable orchagent check for BFD test

---

tests/common/plugins/sanity_check/checks.py

As discussed in the last chassis meeting, we want to add an orchagent usage check in sanity check to confirm if the orchagent is behaving well in T2 Nightly runs. All other Nightly runs can also benefit from this change.
Summary:
Fixes # (issue) Microsoft ADO 29191540
We saw the orchagent usage is being very high in the middle of the chassis test, so we wanted to add orchagent usage check to the sanity check so we can see how it behaves in each test.
I ran some tests with the updated sanity check to confirm it's working.

feat: add orchagent usage check in sanity check

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
test_events.py is flaky in PR test, would block some PRs, the root cause should be image issue
Create image issue https://github.com/sonic-net/sonic-buildimage/issues/19943 and xfail test_events.py in PR test

[202405] xfail flaky test script test_events.py for image issue

---

tests/common/utilities.py
tests/wol/conftest.py
tests/wol/test_wol.py

Summary:
Implement wol test plan: https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/WoL-test-plan.md
We need to qualify the wol
Implement tests in test plan
Run tests on DUT with mx topo.

[wol_test] implement tests for wol

---

tests/common/config_reload.py
tests/common/devices/sonic.py
tests/common/port_toggle.py
tests/common/str_utils.py
tests/platform_tests/test_thermal_state_db.py
tests/qos/test_qos_sai.py
tests/snmp/test_snmp_lldp.py

Summary:
In mg_facts, the field "modular_chassis" should be bool value but it's string type: 'True', 'False'
Convert it to bool on the assignment to reduce duplicated conversion works.
In mg_facts, the field "modular_chassis" should be bool value but it's string type: 'True', 'False'
Convert it to bool on the assignment to reduce duplicated conversion works.
Test locally

[Refine] convert modular_chassis to bool type from str type

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Reverts sonic-net/sonic-mgmt#14227
Fix PR (https://github.com/sonic-net/sonic-mgmt/pull/14163) merged

Revert "skip test_bgp_stress_link_flap"

---

ansible/roles/vm_set/tasks/add_ceos_list.yml
docs/testbed/README.testbed.WANSetup.md

In PR #14200, it updated the file path of `ceos.yml`. But in our code, there still exists some references to the file which are not be updated to the new path. In this PR, we update these references to the new path. 
Summary:
In PR #14200, it updated the file path of `ceos.yml`. But in our code, there still exists some references to the file which are not be updated to the new path. In this PR, we update these references to the new path. 
Update some references of `ceos.yml` to the new path.

Update some references of `ceos.yml` to the new path.

---

test_reporting/report_uploader.py

Summary:
Modified the regex to upload upgrade and reboot JSON logs to a more general case to better match the logs being uploaded.
Certain generated upgrade and reboot JSON logs were not being matched by the current regex.
Modified the regex.
Tested uploads manually.

Update report uploader upgrade and reboot JSON logs regex

---

tests/arp/test_stress_arp.py

There are 3 issues with arp/test_stress_arp.py:
1. It is doing a redundant subtraction.
In both variants, it calculates space available as (available - used)
instead of (total size - used), giving an incorrect value for available
space.
2. Not enough allowance/wiggle room for hash collision.
In both variants, it expects only 100 hash collisions which is very
little. For specific SKUs, there may be a further performance impact as
some hash functions is not as performant for incremental values, which
is what is used for this test.
3. The test will crash if cleanup fails.
Sometimes arp cache cleanup will fail if it is done too often. Allowing the
test to continue after the failure as the failure is unrelated to the test and
being unable to clean implies it is clean.
This patch fixes these 3 …

Fix arp/test_stress_arp.py bad checks and make cleanup failure a warning

---

tests/common/cache/facts_cache.py
tests/common/devices/sonic.py
tests/common/devices/sonic_asic.py
tests/common/helpers/cache_utils.py

Summary:
Enhance and use cache in the test module preparation.
The preparation of chassis test module takes long time because of the multi-duthosts * multi-asics.
Use cache to speed up the preparation.
1. Enhance cache framework.
2. Enable cache decorator on more functions.
Test on the physical chassis, reduces around  1m50s (4m42s -> 2m57s)

[Feature] Use cache to speed up test module preparation

---

tests/golden_config_infra/test_config_reload_with_rendered_golden_config.py

Summary: Default Config was changed during config_reload process. Need to backup and restore config.
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/14327
Fix config change issue. Remove t2 topo as it is not designed.
Backup and restore
E2E test

[golden_config_infra] Backup and Restore config before test

---

ansible/group_vars/sonic/variables

Summary:
To support a new hardware SKU 'cisco-8122-O64' and ensure that the Cisco 8122 devices can be fully supported.
Add the 'cisco-8122-O64' hwsku in the code.
No errors in Cisco 8122 devices.
cisco 8122 devices

add hwsku cisco-8122-O64

---

tests/bfd/bfd_helpers.py

In the script `bfd_helpers.py`, there was an import from the `platform_tests` folder. To avoid importing from other folders within our code, this PR removes that dependency.
Summary:
In the script `bfd_helpers.py`, there was an import from the `platform_tests` folder. To avoid importing from other folders within our code, this PR removes that dependency.
Rewrite the function in the script `bfd_helpers.py` and remove dependency.

Remove dependence in script `bfd_helpers.py`. 

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml
.azure-pipelines/testscripts_analyse/analyse_testscripts.py
.azure-pipelines/testscripts_analyse/constant.py

Our PR checker supports various topologies. In this PR, we are combining certain topologies, such as `mx` and `m0`, under the `t0` topology type. Additionally, since there are no PR checkers for `t2` and `wan`, we have moved scripts specific to these topologies to the skip list and removed the t2 and wan categories from pr_test_scripts.yaml.
Summary:
Our PR checker supports various topologies. In this PR, we are combining certain topologies, such as `mx` and `m0`, under the `t0` topology type. Additionally, since there are no PR checkers for `t2` and `wan`, we have moved scripts specific to these topologies to the skip list and removed the t2 and wan categories from pr_test_scripts.yaml.

Consolidate topologies and remove unused categories in test scripts validation. 

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

There are several closed issues in conditional marks. For our evaluation, we consider the closed issue as False. So in this PR, we remove the conditions associated with closed issue. 
Summary:
There are several closed issues in conditional marks. For our evaluation, we consider the closed issue as False. So in this PR, we remove the conditions associated with closed issue. 
Remove the conditions associated with closed issue

Remove the conditions associated with closed issue

---

tests/common/dualtor/dual_tor_utils.py

Summary: Make oscillation fix persistent across reboots.
Fixes [#226](https://github.com/aristanetworks/sonic-qual.msft/issues/226)
https://github.com/sonic-net/sonic-mgmt/pull/13004, introduces a fix to disable oscillations at the session level for dualtor.
The fix however is not persistent across reboots and config reload.
During the sanity checks that run in the beginning of the tests, https://github.com/sonic-net/sonic-mgmt/blob/master/tests/conftest.py#L77, if it is found that any interfaces or BGP sessions is/are down (which could be due to a test that run before the current test and contaminated the testbed), a config_reload and then further a reboot is issued, which clears off this config to disable oscillation, resulting in a flakiness when the test runs or a sanity check failure …

Make oscillation fix persistent across reboots and config reload

---

ansible/TestbedProcessing.py

Summary: Improve TestbedProcessing.py
Fixes [#237](https://github.com/aristanetworks/sonic-qual.msft/issues/237)
TestbedProcessing.py doesn't populate all the fields related to fanouts and IPV6 for the devices.
Made changes the support the above mentioned gaps.

Improve TestbedProcessing.py

---

tests/configlet/util/common.py

ADO: 29416611
Summary:  Skip comparison of unwanted new fields that introduced in swss
The swss update introduce last flap time. Those value are expected to be differenet. Thus skip it.
Add two fields to skip val.
E2E test

[tests/configlet] Update configlet test to align with swss update

---

tests/common/reboot.py

Summary:
Prolong wait/timeout for chassis in reboot
Prolong wait/timeout for chassis in reboot
Test with test_acl which executes quite a lot reboots on physical devices

Prolong wait/timeout for chassis in reboot

---

ansible/library/generate_golden_config_db.py

Summary:
Currently, we generate golden_config_db for mx, and it only contains FEATURE table, and will load this golden_config_db in deploy-mg stage. But recently there is change made for GCU, which requires all dependent table should be appeared
This PR is to add all dependent tables (PORT table) in to golden_config_db
Add all dependent tables(PORT table) in to golden_config_db
Deploy minigraph

[mx][deploy-mg] Add dependent tables in golden_config_db for mx in deploy-mg

---

tests/everflow/test_everflow_ipv6.py
tests/everflow/test_everflow_testbed.py

Summary:
Ref: https://github.com/sonic-net/sonic-mgmt/issues/13505
A New Test Case is added to verify other background traffic is not getting mirrored.
Ref: https://github.com/sonic-net/sonic-mgmt/issues/13505
Added a New Test Case to ensure the background traffic is not getting mirrored
Tested on T2 VOQ Chassis
No Changes to existing use case

Reg: Everflow New TC bkg traffic https://github.com/sonic-net/sonic-mgmt/issues/13505

---

ansible/library/generate_golden_config_db.py

Summary:
Manually cherry-pick of this PR: https://github.com/sonic-net/sonic-mgmt/pull/14566
Enabling dhcp_server feature for mx in deploy-mg is removed by mistake from this PR: https://github.com/sonic-net/sonic-mgmt/pull/14553. Current PR is to add it back
Enable dhcp_server feature for mx in deploy-mg
Manually deploy minigraph

[202311][mx] Enable dhcp_server feature for mx in deploy-mg

---

tests/bgp/constants.py
tests/bgp/route_checker.py
tests/bgp/test_seq_idf_isolation.py
tests/bgp/test_startup_tsa_tsb_service.py
tests/bgp/test_traffic_shift.py
tests/bgp/test_traffic_shift_sup.py
tests/bgp/traffic_checker.py

The test script `test_traffic_shift.py` contained shared functions that were being imported by other modules. To minimize cross-module dependencies, we refactor these shared functions into common files.
Summary:
The test script `test_traffic_shift.py` contained shared functions that were being imported by other modules. To minimize cross-module dependencies, we refactor these shared functions into common files.
Refactor shared functions into common files.

Refactor shared functions from `test_traffic_shift.py` to common

---

tests/pfcwd/files/pfcwd_helper.py
tests/pfcwd/test_pfcwd_function.py
tests/pfcwd/test_pfcwd_warm_reboot.py

Solve conflicts in the PR https://github.com/sonic-net/sonic-mgmt/pull/14041
Summary:
Solve conflicts in the PR #14041 
Manually cherry-picked it and solved conflicts.
str3-7060x6-64pe-1
t0-standalone-32

Solve 202311 branch conflicts in the PR#14041

---

tests/container_checker/test_container_checker.py

Summary:
Microsoft ADO: 29386874
test_container_checker_telemetry failed, and root cause is swss and syncd containers are not running.
Run "config reload" to recover all the containers.

Recover container for test_container_checker_telemetry

---

tests/common/platform/device_utils.py
tests/ipfwd/test_nhop_group.py
tests/platform_tests/link_flap/link_flap_utils.py
tests/platform_tests/link_flap/test_cont_link_flap.py
tests/platform_tests/link_flap/test_link_flap.py

To minimize cross-module dependencies, we move some shared functions to `tests/common/platform/device_utils.py`.
Summary:
To minimize cross-module dependencies, we move some shared functions to `tests/common/platform/device_utils.py`.
To minimize cross-module dependencies, we move some shared functions to `tests/common/platform/device_utils.py`.

Optimise some scripts under folder tests/ipfwd

---

docs/testplan/LLDP-syncd-test-plan.md

Summary:
Address https://github.com/sonic-net/sonic-mgmt/issues/13937
Test gap implementation: https://github.com/sonic-net/sonic-mgmt/pull/14216
ADO: 28941599
testplan of verification of LLDP_ENTRY_TABLE in SONiC APPL_DB

Test Plan: Verification of LLDP_ENTRY_TABLE in SONiC APPL_DB

---

tests/pfcwd/files/pfcwd_helper.py
tests/pfcwd/test_pfcwd_function.py
tests/pfcwd/test_pfcwd_warm_reboot.py

Solve conflicts in the PR https://github.com/sonic-net/sonic-mgmt/pull/14041
Summary:
Solve conflicts in the PR #14041 
Manually cherry-picked it and solved conflicts.
str3-7060x6-64pe-1
t0-standalone-32

Solve 202405 branch conflicts in the PR #14041

---

ansible/roles/test/files/ptftests/sonic.py

Summary:
Current processing involves iterating through sonic logs (which can be large) from the beginning, which is unnecessary since only log lines starting from a particular timestamp are relevant. 
Optimize this processing by doing it in reverse and stopping after the last relevant timestamp.
Ran test_upgrade_path with SONiC neighbors, verified in warm-reboot.log that SSH threads no longer hang unnecessarily long due to log processing

Enhance log processing for sonic neighbors

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skip CRC algorithm test on INNER_IP_PROTOCOL field
Skip the test combination due to hw limitation
Summary:
HW limitation
Skip specific cases
Run the script in internal regression
No

Skip CRC algorithm test on INNER_IP_PROTOCOL field

---

tests/common/snappi_tests/snappi_fixtures.py
tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_burst_storm_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_m2o_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
tests/snappi_tests/test_multidut_snappi.py
tests/snappi_tests/variables.py

Summary: Accomodating the infra change for multidut ECN and PFCWD cases
https://github.com/sonic-net/sonic-mgmt/issues/13389
https://github.com/sonic-net/sonic-mgmt/issues/13769
To accomodate the infra change from PR 14127 
Added a pytest fixture called get_snappi_ports and get_snappi_ports_for_rdma whcih selects the ports from the information provided in MULTIDUT_PORT_INFO in variables.py

[Fix] Accomodating the infra change for multidut ECN and PFCWD cases

---

tests/common/helpers/dut_utils.py
tests/lldp/test_lldp.py

New test coverage for the existing test gap recorded in issue#6560
Summary:
New test coverage for the existing test gap recorded in issue#6560 https://github.com/sonic-net/sonic-mgmt/issues/6560
Reboot orchagent, then check if lldp neighbors are in good state
Fill the test gap
write new test coverage
run the test on vs

Check lldp neighbors post orchagent reboot

---

ansible/module_utils/port_utils.py

Adding port utils change for Marvell platform sku
Summary:
Modified port_utils file to support new Marvell sku

Adding port utils change for Marvell platform sku

---

ansible/config_sonic_basedon_testbed.yml

Double commit https://github.com/sonic-net/sonic-mgmt/pull/14204
Summary:

[202305] Enable ComputeAI deployment for hwsku Cisco-8111-O32

---

tests/tacacs/test_accounting.py
tests/tacacs/test_authorization.py
tests/tacacs/test_jit_user.py
tests/tacacs/test_ro_disk.py
tests/tacacs/test_rw_user.py
tests/tacacs/utils.py

Several test scripts in the `tacacs` folder import shared functions from other scripts. To reduce cross-module dependencies, we have relocated these shared functions to `tacacs/utils.py`.
.
Summary:
Several test scripts in the `tacacs` folder import shared functions from other scripts. To reduce cross-module dependencies, we have relocated these shared functions to `tacacs/utils.py`.

Remove dependencies across modules under folder `tacacs`. 

---

tests/generic_config_updater/test_pfcwd_status.py

ensure flex_db counters match expected number on setup of pfcwd_status tests
move number of flex_db counters per port to FLEXDB_COUNTERS_PER_PORT
Change-Id: I0d63e2c4de5de424dd7ba993706e0569a5a9f6d4
Summary:
To fix a case when we read the initial number of counters in flex_db at the moment they are added partially.
Call check_config_update method in ensure_dut_readiness to ensure that actual number of counters is the same as expected at the test beginning
Run test_stop_pfcwd/test_start_pfcwd in a loop

ensure flex_db counters match expected number on setup of pfcwd_status tests

---

tests/common/helpers/sonic_db.py
tests/lldp/test_lldp_syncd.py

Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/14216 into 202405

[202405]Test gap for lldp APPL_DB data consistency

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
Check-in https://github.com/sonic-net/sonic-mgmt/pull/14641 for pr test
Check-in https://github.com/sonic-net/sonic-mgmt/pull/14641 for pr test
By pr test

[dhcp][pr_test] Check-in dhcp_relay stress test in pr test

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py
azure-pipelines.yml

Raised draft PR to test. https://github.com/sonic-net/sonic-mgmt/pull/14531
1.pass `PTF_IMAGE_TAG` succeeded. 
2.not pass `PTF_IMAGE_TAG` succeeded.(not affect other normal test plans)

[CI]Add ptf image tag when creating test plans from pipelines

---

ansible/roles/test/files/ptftests/py3/dhcp_relay_stress_test.py
ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/dhcp_relay/conftest.py
tests/dhcp_relay/dhcp_relay_utils.py
tests/dhcp_relay/test_dhcp_relay.py
tests/dhcp_relay/test_dhcp_relay_stress.py

Summary:
Manually cherry-pick these 2 pr because conflicts
https://github.com/sonic-net/sonic-mgmt/pull/14012
https://github.com/sonic-net/sonic-mgmt/pull/14641
Manually cherry-pick these 2 pr because conflicts
https://github.com/sonic-net/sonic-mgmt/pull/14012
https://github.com/sonic-net/sonic-mgmt/pull/14641
PR tests

[202311][dhcp_relay] Cherry-pick dhcp_relay changes

---

ansible/devutil/device_inventory.py
ansible/devutil/inv_helpers.py
ansible/devutil/ssh_session_repo.py
ansible/ssh_session_gen.py

Summary:
For devices, generate console connection entries if this information is available. This allows people to connect to those devices via console if regular SSH access is not working.
Also, place arguments to the script into multiple groups, for readability purposes, and make the SSH config syntax checker be validated at argument validation time instead of later.

Generate console connection information for devices

---

.azure-pipelines/pr_test_scripts.yaml

In this PR, we move test script `test_cont_warm_reboot.py` to PR test. 
Summary:
In this PR, we move test script `test_cont_warm_reboot.py` to PR test. 
vms-kvm-t0 | platform_tests/test_cont_warm_reboot.py | 2024-09-27 00:00:00.0000000 | 5 | 0 | 5 | 1
vms-kvm-t0 | platform_tests/test_cont_warm_reboot.py | 2024-09-26 00:00:00.0000000 | 34 | 0 | 34 | 1

Move test_cont_warm_reboot.py to PR test. 

---

tests/common/devices/duthosts.py
tests/common/helpers/parallel_utils.py
tests/common/plugins/sanity_check/__init__.py
tests/conftest.py
tests/test_parallel_modes.json

Currently, our Nightly runs for multi-DUT testbeds (e.g., T2 chassis) are taking an exceptionally long time. To address this, we propose introducing parallel execution to our test infrastructure. By implementing this, we can select the test modules that take a long time to finish and run the test cases in them in parallel, thereby reducing the overall running time.
At this stage, this implementation is compatible only with Microsoft’s internal Nightly tool. We plan to introduce it to the community once we have confirmed its effectiveness internally.
Summary:
Fixes # (issue) Microsoft ADO 29061962
Reduce the Nightly running time for multi-DUT testbeds

feat: add support for parallel run

---

tests/bfd/bfd_helpers.py
tests/bfd/conftest.py
tests/bfd/test_bfd_static_route.py

Refactor the interfaces toggling in BFD static route to batch toggling to get a better performance.
Summary:
Fixes # (issue) Microsoft ADO 29473566
Currently, we are toggling the interfaces in `bfd/test_bfd_static_route.py` in a loop, causing long running time. We wanted to batch toggle the interfaces to improve the overall performance. 
Convert the `for` loop toggling into a batch toggling and batch waiting.
I ran the updated code in T2 chassis and can confirm it passed.

refactor: batch control interfaces in BFD

---

tests/common/devices/sonic.py
tests/test_pretest.py

Update pretest script to provide asic type value in metadata json file
It would provide asic type value for generic hash test script https://github.com/sonic-net/sonic-mgmt/pull/12564
Summary:
Provide asic type value in metadata json file
Collect asic type value during pre test script
No

Update pretest script to provide asic type value for generic hash test script

---

tests/dut_console/test_console_baud_rate.py

* Configure expected baudrate for test_console_baud_rate_config using hostvars in the inventory files
BugLink: https://github.com/sonic-net/sonic-mgmt/issues/14874
Allows configuring the expected baudrate using `console_baudrate` hostvar / inventory file value.
If the value is not there, the testcase will default to 9600 (existing behaviour)
Summary:
Fixes # 14874
- [x ] Testbed and Framework(new/improvement)
- [ x] 202405
To allow the decoupling of baudrate values to the testcase
Ran on platform and ensured the correctly specified baudrate is picked up
Vendors / users of the framework will need to update their inventory files if they have platforms with baudrates not 9600

[dut_console/test_console_baud_rate] Configure expected baudrate in inventory files

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
The case was revert by https://github.com/sonic-net/sonic-mgmt/pull/14145
Add the case back to PR test
vms-kvm-t0	bgp/test_bgp_stress_link_flap.py	test_bgp_stress_link_flap[dut]	154	0	154	1
vms-kvm-t0	bgp/test_bgp_stress_link_flap.py	test_bgp_stress_link_flap[fanout]	154	0	154	1
vms-kvm-t0	bgp/test_bgp_stress_link_flap.py	test_bgp_stress_link_flap[neighbor]	154	0	154	1
vms-kvm-t0	bgp/test_bgp_stress_link_flap.py	test_bgp_stress_link_flap[all]	154	0	154	1
vms-kvm-t1-lag	bgp/test_bgp_stress_link_flap.py	test_bgp_stress_link_flap[dut]	154	0	154	1
vms-kvm-t1-lag	bgp/test_bgp_stress_link_flap.py	test_bgp_stress_link_flap[fanout]	154	0	154	1
vms-kvm-t1-lag	bgp/test_bgp_stress_link_flap.py	test_bgp_stress_link_flap[neighbor]	154	0	154	1
vms-kvm-t1-lag …

add back test_bgp_stress_link_flap into PR test

---

tests/generic_config_updater/gu_utils.py

Summary: conflict resolve for https://github.com/sonic-net/sonic-mgmt/pull/14881

[202305][conflict]Add GCU timeout for qualification

---

tests/generic_config_updater/gu_utils.py

Summary: conflict resolve for https://github.com/sonic-net/sonic-mgmt/pull/14881

[202405][conflict]Add GCU timeout for qualification

---

tests/generic_config_updater/gu_utils.py

Summary: conflict resolve for https://github.com/sonic-net/sonic-mgmt/pull/14881

[202311][conflict]Add GCU timeout for qualification

---

tests/qos/qos_sai_base.py

Summary:
In production scenarios, there is no traffic pattern from longlink to longlink.
Select shorlink linecard to run single_asic and single_dut_multi_asic.
Verified on T2 and T0 testbeds.
```
T2 test result:
single_asic: 
src_dut_index=2;src_asic_index=0;dst_dut_index=2;dst_asic_index=0;
single_dut_multi_asic: 
src_dut_index=2;src_asic_index=0;dst_dut_index=2;dst_asic_index=1;
multi_dut:
src_dut_index=0;src_asic_index=0;dst_dut_index=1;dst_asic_index=0; //longlink to shortlink
src_dut_index=1;src_asic_index=0;dst_dut_index=2;dst_asic_index=0; //shortlink to shortlink
src_dut_index=1;src_asic_index=0;dst_dut_index=0;dst_asic_index=0; //shortlink to longlink
------------------------------------ generated xml file: …
```

select shortlink linecard to run single_asic and single_dut_multi_asic

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Cherry pick #14433 to 202405
Summary:

[202405][PR: 14433] Remove the conditions associated with closed issue

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Cherry pick #14912 to 202405
Summary:

[202405][PR: 14912][Bugfix]Adding conditions to longer matching entries in conditional marks

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

In PR #14912, we added conditions to longer matching entries in conditional marks. We got some mistakes while adding conditions into some longer entries. In this PR, we fix these mistakes. 
Summary:
In PR #14912, we added conditions to longer matching entries in conditional marks. We got some mistakes while adding conditions into some longer entries. In this PR, we fix these mistakes.

[Bugfix] Fix incorrect conditions added in longer entries

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Cherry pick #14433 to 202311
Summary:

[202311][PR: 14433] Remove the conditions associated with closed issue

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
Script tests/generic_config_updater/test_ipv6.py was renamed to tests/generic_config_updater/test_ip_bgp.py in PR #13650
Need to update file name in pr_test_scripts.yaml to ensure that renamed script is covered by PR testing.

Add renamed script test_ip_bgp.py to PR test

---

ansible/roles/fanout/lookup_plugins/cisco_8101_port_convert.py

fix bug with cisco-8101 fanout deployment script
Summary:
Fix a typo with cisco 8101 fanout deployment script
Fix typo
Deploy 8101 fanout

[Cisco-8101] fix bug with cisco-8101 fanout deployment script

---

.azure-pipelines/pr_test_scripts.yaml

Script tests/generic_config_updater/test_ipv6.py was renamed to tests/generic_config_updater/test_ip_bgp.py in PR #13650
Need to update file name in pr_test_scripts.yaml to ensure that renamed script is covered by PR testing.
Summary:
Script tests/generic_config_updater/test_ipv6.py was renamed to tests/generic_config_updater/test_ip_bgp.py in PR #13650
Need to update file name in pr_test_scripts.yaml to ensure that renamed script is covered by PR testing.
Rename script name from `generic_config_updater/test_ipv6.py` to `generic_config_updater/test_ip_bgp.py`

Add renamed script test_ip_bgp.py to t0 PR test

---

.azure-pipelines/pr_test_scripts.yaml
azure-pipelines.yml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

We have created an issue of test script `test_dualtor_bgp_update_delay.py` and used conditional mark to xfail this script. So it can be moved from onboarding dualtor PR checker to dualtor PR checker. As there is no scripts in onboarding dualtor PR checker, so we comment out this checker.
Summary:
We have created an issue of test script `test_dualtor_bgp_update_delay.py` and used conditional mark to xfail this script. So it can be moved from onboarding dualtor PR checker to dualtor PR checker. As there is no scripts in onboarding dualtor PR checker, so we comment out this checker.

Move test_dualtor_bgp_update_delay.py to dualtor PR checker 

---

tests/common/devices/duthosts.py
tests/common/helpers/parallel_utils.py
tests/common/plugins/sanity_check/__init__.py

Create `prepare_parallel_run` fixture to manage the parallel run state and error handling.
Summary:
Fixes # (issue) Microsoft ADO 29807927 & 29787171
Currently, we are having logic in different places to manage parallel run state change and error handling, which makes the code less concise and more error-prone. Therefore, We decided to create a separate fixture to manage the state change and error handling. 
I ran the updated code and can make sure it's working as expected.

refactor: switch to use fixture for error handling

---

tests/gnmi/helper.py

Summary:
Microsoft ADO: 29869466
GNMI client timeout is not enough for some hwsku
Increase dbus timeout to support all possible hwsku
Run end2end test

Update gnmi client timeout

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py

Enhance test plan poll status, fix 24h token expiration issue by requesting no-auth API.
Raised draft PR https://github.com/sonic-net/sonic-mgmt/pull/14970 to verify the fix.

[CI]Enhance test plan poll status, fix 24h token expiration issue

---

tests/qos/test_buffer.py

Update dynamic buffer test due to the algorithm calculating headroom is changed  according to the relevant PR: https://github.com/sonic-net/sonic-swss/pull/3235
Summary:
Updatea dynamic buffer tests for Mellanox device
update headromm calculation algorithm according to the https://github.com/sonic-net/sonic-swss/pull/3235
run dynamic buffer case on Mellanox device
mellanox
Any

[Mellanox] update dynamic buffer test

---

tests/platform_tests/daemon/test_fancontrol.py

This is similar to the PR that I raised previously for fixing the PSU test handling in this PR:
https://github.com/sonic-net/sonic-mgmt/pull/5421
Summary:

Update test_fancontrol.py to support Chassis which needs to run on Supervisor and not just random module

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

There are some issues with running the test script `test_snmp_link_local.py` on the KVM testbed. In this PR, we have marked the script as 'xfail' and removed it from the onboarding PR checker.
Summary:
There are some issues with running the test script `test_snmp_link_local.py` on the KVM testbed. In this PR, we have marked the script as 'xfail' and removed it from the onboarding PR checker.
In this PR, we have marked the script as 'xfail' and removed it from the onboarding PR checker.

Xfail test script test_snmp_link_local.py on kvm testbed. 

---

tests/common/plugins/conditional_mark/README.md
tests/common/plugins/conditional_mark/__init__.py

Cherry pick #14395 #14515 to 202405
Summary:

[202405][PR: 14395][PR: 14515] Cherry pick new matching rule of conditional marks to 202405. 

---

tests/vxlan/test_vxlan_ecmp_switchover.py

Summary:
This is a manual cherry-pick of PR(#14008) to 202405 for conflict resolving.

[Cherry-pick][PR#14008] Update loganalyzer ignore in test_vxlan_ecmp_switchover.py

---

tests/acl/test_stress_acl.py

Summary:
MX failed to fetch acl port due to DATAACL table in running config is removed by this PR: https://github.com/sonic-net/sonic-mgmt/pull/11250
Fetch acl port from mg_facts
Run test

[acl] Fix test_stress_acl failed in mx

---

tests/common/helpers/portchannel_to_vlan.py

Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/15163 and https://github.com/sonic-net/sonic-mgmt/pull/15176

[202311] Add same speed ports into one portchannel in setup_dut_ptf

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/testscripts_analyse/analyse_testscripts.py

In PR #15162, we introduced three new topology marks for certain subtype topologies. To support this change, we are adding these marks to the script that analyzes all test scripts.
Summary:
In PR #15162, we introduced three new topology marks for certain subtype topologies. To support this change, we are adding these marks to the script that analyzes all test scripts.
We are adding these new introduced marks to the script that analyzes all test scripts.

Add new topology marks to test analysis script

---

.azure-pipelines/pr_test_scripts.yaml

In PR #9268, a test script named `test_snmp_link_local.py` was introduced, but it was incorrectly listed as `snmp/test_snmp_link_local_ip.py` in `.azure-pipelines/pr_test_scripts.yaml`. This PR corrects the entry in `.azure-pipelines/pr_test_scripts.yaml` to resolve the mismatch.
Summary:
In PR #9268, a test script named `test_snmp_link_local.py` was introduced, but it was incorrectly listed as `snmp/test_snmp_link_local_ip.py` in `.azure-pipelines/pr_test_scripts.yaml`. This PR corrects the entry in `.azure-pipelines/pr_test_scripts.yaml` to resolve the mismatch.
This PR corrects the entry in `.azure-pipelines/pr_test_scripts.yaml` to resolve the mismatch.

Fix mismatch of `snmp/test_snmp_link_local.py` in `.azure-pipelines/pr_test_scripts.yaml`

---

tests/common/helpers/portchannel_to_vlan.py

Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/15163 and https://github.com/sonic-net/sonic-mgmt/pull/15176

[202405]Add same speed ports into one portchannel in setup_dut_ptf

---

tests/qos/test_pfc_counters.py

Summary:
Adapt PFC counter behavior for Cisco hwskus. 
Verified against:
- Cisco-8111 T1
- Cisco-8122 T0
- Cisco T2 Lancer single asic
Cisco-only modification of expectations, but common code is being revised to clarify assertions and failures.

Adapt Cisco PFC counters

---

tests/telemetry/events/event_utils.py
tests/telemetry/events/host_events.py
tests/telemetry/events/run_events_test.py
tests/telemetry/telemetry_utils.py
tests/telemetry/test_events.py

Summary:
Fixes # (issue) 28728116
This PR will
1) Add test_events back to PR checker
2) Fix event_down container test flakiness
3) Remove unneeded test_events_cache test as our tests already use cache for testing
Code change
Lab test and Pipeline

Fix test_events flakiness (#14140)

---

ansible/roles/test/files/ptftests/py3/copp_tests.py
tests/copp/copp_utils.py
tests/copp/scripts/update_copp_config.py
tests/copp/test_copp.py

Summary:
Double commit https://github.com/sonic-net/sonic-mgmt/pull/14459
MIGSMSFT-614 [81xx] test_copp.py::test_policer failed with LLDP
Test result in https://github.com/sonic-net/sonic-mgmt/pull/14459
Verified on 8111 T1, 8102 T0 and 8101 T0.

[202305] Update policer rate for cisco-8000

---

tests/common/helpers/sonic_db.py
tests/voq/test_voq_ipfwd.py

Summary:
- [x ] Bug fix
The test was failing due to a Runtime Error caused by modifying the dictionary during iteration.
To resolve this, introduced a separate list to store the keys of the items that need to be removed. After the iteration completes, the keys are removed from the dictionary, preventing the error.
After running this on different duts

Fix for test_voq_ip_fwd

---

tests/conftest.py

Add port status check for config reload action in function __dut_reload
Avoid following script failed due to port not recover
Summary:
Avoid following script failed due to port not recover
Add port status check for config reload action in function __dut_reload

Add port status check for config reload in function __dut_reload

---

tests/common/fixtures/advanced_reboot.py
tests/platform_tests/conftest.py

Summary:
Note this is a backport, please see the original for details: https://github.com/sonic-net/sonic-mgmt/pull/14980

Capture logs before reboot (cherry-pick 202405)

---

tests/syslog/test_syslog.py

Summary:
Fixes # (issue) #15137 conflict resolve
Hi @yejianquan @yutongzhang-microsoft , personally I think we should bring the changes in https://github.com/sonic-net/sonic-mgmt/pull/14551 since now it introduce a mismatches in files for these tests.
Especially for test_mgmt_ipv6_only, the fixture now is not in the test_syslog anymore and in the syslog_helper file. Everytime we modify the syslog_helper file we will need to duplicate the same changes here.

202405 #15137 conflict resolve

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py

Reverts sonic-net/sonic-mgmt#15300
Creating test plan failed.

Revert "[CI] Enhance elastictest template, use bash script instead of azcli task"

---

.azure-pipelines/pytest-collect-only.yml
azure-pipelines.yml

Summary:
Currently pytest-collect-only.yml check only support running on self branch, but in some scenarios we need to use it in target branch.
Add a new parameter mgmt_branch in pytest-collect-only.yml to support running on target branch

Add mgmt branch parameter in pytest-collect-only.yml

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py
azure-pipelines.yml

[CI] Enhance elastictest template and test_plan.py, fix az token issue
Re-submit PR and improve it: https://github.com/sonic-net/sonic-mgmt/pull/15339
[CI] Enhance elastictest template and test_plan.py, fix az token issue
- Use bash script instead azcli task to fix s360 task.
- Enhance azlogin and get token logic to fix token expiration issue.
- Derectly specify MGMT_BRANCH to "master" to avoid download test_plan.py from master branch.
- Other Code readability optimization.
Can be vefied in this PR. Need pass.

[CI] Enhance elastictest template and test_plan.py, fix az token issue

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py
azure-pipelines.yml

Reverts sonic-net/sonic-mgmt#15342

Revert "[CI] Enhance elastictest template and test_plan.py, fix az token issue"

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Queue related tests are not expected to run in M0/MX topos
Skip those cases in M0/MX
Run tests

[m0][mx] Skip queue related tests for m0/mx

---

tests/dash/dash_acl.py

1. For receiver and sender, tcp rst packet will have no payload.
2. Remove some fields ignore to check them, because they are expected same as the sent packet.
Summary:
update test_acl_tcp_rst 
1. update rst packet lenght due to there is no payload.
2. Remove some fields ignore to check them, because they are expected same as the sent packet.
Run test_acl_tcp_rst  on mellanox dpu 
Mellanox dpu

[Mellanox] update for test_acl_tcp_rst due to design change

---

tests/bfd/bfd_base.py
tests/bfd/bfd_helpers.py
tests/bfd/test_bfd_static_route.py
tests/bfd/test_bfd_traffic.py

Optimize BFD tests to reduce the running time.
Summary:
The `bfd/test_bfd_static_route.py` and `bfd/test_bfd_traffic.py` are taking a very long time to finish. We can optimize them by multithreading and enabling safe reload and safe reboot. After the optimization, the running time of `bfd/test_bfd_static_route.py` will decrease by 1.5 to 2 hours, and the running time of `bfd/test_bfd_traffic.py` will decrease by 1 to 1.5 hours.
Using multithreading and enabling safe reload and safe reboot to optimize the BFD tests.
I ran the updated code and can confirm that they can still run properly.
T2

refactor: optimize BFD test

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/devices/multi_asic.py
tests/common/devices/sonic.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/telemetry/telemetry_utils.py
tests/telemetry/test_telemetry.py

Fix conflict and cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/14982
Add multi-asic support for telemetry test. This does not include multi-asic support for events (bgp, swss etc) as there are issues with multi-asic support on server side. A different PR #13826 will handle telemetry event multi-asic support on mgmt.
Approach
Multi-asic support for telemetry test
Whole telemetry OC testd pass with the changes (exclude events test).
Summary:

[202405 conflict]Multi-asic Support for Telemetry Test (#14982)

---

tests/common/gu_utils.py

Summary:Extend timeout to 600(10min) for dynamic acl case
update timeout introduced in https://github.com/sonic-net/sonic-mgmt/pull/14881
increase 
E2E

[GCU] Extend timeout to 10min

---

tests/generic_config_updater/gu_utils.py

Summary: resolve conf of https://github.com/sonic-net/sonic-mgmt/pull/15434

[202305][conflict][GCU]Extend timeout to 10min

---

tests/generic_config_updater/gu_utils.py

Summary: resolve conf of https://github.com/sonic-net/sonic-mgmt/pull/15434

[202311][conflict][GCU]Extend timeout to 10min

---

tests/generic_config_updater/gu_utils.py

Summary: resolve conf of https://github.com/sonic-net/sonic-mgmt/pull/15434

[202405][conflict][GCU]Extend timeout to 10min

---

ansible/module_utils/port_utils.py

Summary:
Add Cisco-8122-O128 definition in the ‘port_utils.py’ file.
Using port_config.ini to update the ‘port_utils.py’ file
The 'port_utils.py' file was consistent with the 'port_config.ini' on the device.

add hwsku definition Cisco-8122-O128

---

tests/common/gu_utils.py
tests/generic_config_updater/test_incremental_qos.py

Summary:
Fixes # (issue) ADO: 28886361
This is an improvement for `replace` case in a [GCU E2E Testing](https://github.com/sonic-net/sonic-mgmt/pull/11739)
If the op is replace, then just check expected failure, no need do further steps.

Fix replace ingress_lossless_pool

---

tests/fdb/test_fdb_mac_learning.py

Increase the sleep time after change the interface status

---

ansible/roles/fanout/tasks/fanout_sonic.yml
ansible/roles/fanout/tasks/sonic/fanout_sonic_202405.yml

Update fanout deploy yaml file to support using 2024 image in fanout switch
Summary:
Use 2024 image in sonic fanout
Update the fanout_sonic.yml

Update fanout deploy yaml file to support using 2024 image

---

tests/bfd/bfd_base.py
tests/bfd/conftest.py
tests/bfd/test_bfd_traffic.py

Optimize the BFD traffic test to reduce the running time.
Summary:
There are unnecessary setup steps in the BFD traffic test, which can be removed to reduce the running time. The running time will be decreased by at least 35 min after this change.
I ran the updated code and can confirm it's working well.

refactor: optimize BFD traffic test

---

tests/pfcwd/test_pfcwd_function.py

Summary:
Fixes # (issue) 30115858
From the original PR #10198 these changes were left out. After adding it back in it passed all the tests
@rraghav-cisco @abdosi could you please review?

fix TestPfcwdFunc::test_pfcwd_multi_port t2

---

ansible/setup-management-network.sh
docs/testbed/README.testbed.Setup.md
docs/testbed/README.testbed.VsSetup.md
setup-container.sh

Reverts sonic-net/sonic-mgmt#15600

Revert "Update j2cli to jinjanator."

---

tests/bgp/bgp_helpers.py
tests/bgp/test_bgp_bbr.py
tests/bgp/test_bgp_sentinel.py
tests/bgp/test_bgp_speaker.py
tests/bgp/test_bgp_suppress_fib.py
tests/common/helpers/bgp.py
tests/route/test_route_flap.py

Summary: Resolves conflict for https://github.com/sonic-net/sonic-mgmt/pull/15067 into 202405

[202405][conflict] Disable proxy for POST requests to PTF

---

tests/conftest.py

Summary: Fix "enum_dut_lossy_prio_with_completeness_level" fixture collection failure
Fixes # https://github.com/aristanetworks/sonic-qual.msft/issues/324
https://github.com/sonic-net/sonic-mgmt/pull/15057/ has introduced logic to select dut queue priority list based on the completeness_level. If completeness_level is "debug", we are selecting one queue priority randomly from the dut priority list which can be empty also, and this is causing `ValueError: Sample larger than population or is negative`.
(Reason for dut priority list can be empty: In `tests/pretest.py` we have `collect_dut_all_prio` method which is generating `tests/priority/<testbed>-all.json` see https://github.com/sonic-net/sonic-mgmt/blob/202405/tests/test_pretest.py#L220, where we are not populating dut priority list if …

[sonic-mgmt] Fix "enum_dut_lossy_prio_with_completeness_level" collection failure

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py
azure-pipelines.yml

[CI]Add new parameter retry_cases_include and retry_cases_exclude to template for Elastictest specific retry.
[CI]Add new parameter `retry_cases_include` and `retry_cases_exclude` to template for Elastictest specific retry.
Add new parameters `retry_cases_include` and `retry_cases_exclude` and set default value.
Add new parameters wouldn't block current normal runnings. This PR test need passed.

[CI]Add new parameter retry_cases_include and retry_cases_exclude to template for Elastictest specific retry

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Cherry pick #15563
Summary:
Cherry pick #15563

[202405][PR: 15563] [Bugfix] Add missing conditions for extended entries in qos/test_qos_sai.py::TestQosSai

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py

Add parallel run toggle to pipeline definition
Summary:
Fixes # (issue) Microsoft ADO 29843837
We want to enable parallel run via pipeline, so we need to add the parallel run toggle to the pipeline definition

feat: add parallel run toggle to pipeline

---

.azure-pipelines/dependency-check.yml
.azure-pipelines/dependency_check/dependency_check.py
azure-pipelines.yml

In PR #15559, we introduced a checker to identify cross-feature dependencies within our repository. At the time, since some dependencies still existed, the checker was configured to only run the script without enforcing any pipeline failures. Now that all cross-feature dependencies have been eliminated, we’ve updated the checker to capture the script's return value and trigger a pipeline failure if any cross-feature dependencies are detected.
Summary:
In PR #15559, we introduced a checker to identify cross-feature dependencies within our repository. At the time, since some dependencies still existed, the checker was configured to only run the script without enforcing any pipeline failures. Now that all cross-feature dependencies have been eliminated, we’ve updated the …

Enforce cross-feature dependency checker in pipeline

---

tests/common/snappi_tests/common_helpers.py
tests/snappi_tests/files/helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py

Summary:
This PR attempts to fix the fixture-not-found error and KeyError that you are seeing in the snappi_test multidut runs.

Porting PR:15524 to 202405.

---

tests/srv6/common_utils.py
tests/srv6/srv6_utils.py
tests/srv6/test_srv6_basic_sanity.py

This PR is to add some SRv6 test cases listed in https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/srv6/SRv6-phoenixwing-ptf-testplan.md. These test cases are running on the 7 node testbed. 
The infra changes are in https://github.com/sonic-net/sonic-mgmt/pull/15349 
Summary:
Add couple SRv6 Test cases listed in https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/srv6/SRv6-phoenixwing-ptf-testplan.md. 
Add 5 more test cases, including ptf traffic test and link flapping test cases. 
Via daily jenkins run
The test log could be found at http://phoenixwing.com.cn/vsonic
Only on 7 node vsonic testbed.
https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/srv6/SRv6-phoenixwing-ptf-testplan.md

Add SRv6 test cases on 7 nodes testbed

---

tests/common/helpers/enable-dynamic-buffer.py

Before stopping buffermgrd, need to make sure buffermgrd is running, Otherwise it might cause some side-effect timing issue.  For example: after loading minigraph, buffermgrd will restart, if we run command to stop buffermgrd when buffermgrd is not running, the buffermgrd will not be stopped really, and the consequence is the command starting buffermgrd triggered by loading minigraph in the queue will be executed in the later. Therefore, when the subsequent starting buffermgrd happens between time changing the config db with the dynamic buffer config and setting the buffer model to dynamic, it will raise some error by sai, because dynamic buffer config will be applied to traditional model.
Summary:
Fix enable-dynamic-buffer issue
Before stopping buffermgrd, check if it is …

[Dynamic buffer] Fix enable-dynamic-buffer.py issue

---

tests/platform_tests/sfp/test_show_intf_xcvr.py
tests/platform_tests/sfp/util.py

Summary: Fix test_check_show_lpmode case
Fixes # PR #15062 fix the test_check_show_lpmode case and merge in **master** branch, but conflicts with **202405** branch. So create this PR to submit the code to **202405** branch

Fix test_check_show_lpmode case

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
Fixes https://github.com/sonic-net/sonic-buildimage/issues/20815
The error message from SAI has changed in SAI 11.x Update the loganalyser to whitelist this error
Add the regrex for new error in `ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt`
Qos test on T2 chassis

[Chassis][Voq] Whitelist SAI errors seen during qos tests

---

tests/lldp/test_lldp_syncd.py

Summary:
On some testbeds, lldp_rem_man_addr for eth0 is a string `'lldp_rem_man_addr': '240.127.1.1,fe80::804:73ff:fe21:54d2'`
```
admin@svcstr-7050-acs-3:~$ sonic-db-cli APPL_DB hgetall LLDP_ENTRY_TABLE:eth0
{'lldp_rem_port_id_subtype': '7', 'lldp_rem_index': '5', 'lldp_rem_sys_cap_enabled': '28 00', 'lldp_rem_port_id': 'etp26', 'lldp_rem_chassis_id': '00:e0:ec:84:70:51', 'lldp_rem_sys_cap_supported': '28 00', 'lldp_rem_time_mark': '34015', 'lldp_rem_man_addr': '240.127.1.1,fe80::804:73ff:fe21:54d2', 'lldp_rem_sys_desc': 'Debian GNU/Linux 8 (jessie) Linux 4.9.0-14-amd64 #1 SMP Debian 4.9.246-2 (2020-12-17) x86_64', 'lldp_rem_sys_name': 'svcstr-e1031-acs-1', 'lldp_rem_chassis_id_subtype': '4', 'lldp_rem_port_desc': 'Ethernet25'}
```
But the mgmt-ip in lldpctl is a list, …

Fix different formats for mgmt ip of eth0 in test_lldp_syncd

---

tests/restapi/test_restapi_vxlan_ecmp.py

Summary:
add more info to improve debug clarity.
include the counter idx and missing route

add log info for testcase test_vxlan_ecmp_multirequest

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Update test_dhcp_relay_stress Testcase: Add XFail Conditions for dualtor

---

ansible/vars/configdb_jsons/7nodes_cisco/PE1.json
ansible/vars/configdb_jsons/7nodes_cisco/PE2.json
ansible/vars/configdb_jsons/7nodes_cisco/PE3.json

update the config of srv6 locator for 7nodes test cases to fit the change in this pr :  https://github.com/sonic-net/sonic-buildimage/pull/20954
Via daily jenkins run
The test log could be found at http://phoenixwing.com.cn/vsonic

sonic-mgmt: update srv6 7nodes locator config

---

tests/platform_tests/daemon/test_psud.py

We're getting `KeyError: 'led_status', error:'led_status'` for everytime the wait_until function runs. This is expected since the information was not populated on the database at the time of checking. When testing manually, it's expected around 1 minute for T2 Supervisor to have data in its database.
Summary:
Fixes # (issue) 30114182
This PR changes the behaviour that we update the logic to check the key in the dictionary before getting it to avoid KeyError. And also we update the wait to 90 seconds.

fix: psu key error

---

tests/conftest.py

Summary:
Added missed OS type of "ONYX" to fanouthosts fixture
Stabilize regression
Added missed argument to fuxture
Executed on setup with ONYX OS on fanout

[fanout] added missed fanout OS type - ONYX

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Add skip for
test_generic_hash - github issue [#15340](https://github.com/sonic-net/sonic-mgmt/issues/15340)
Summary:
Add skip for
test_generic_hash - github issue [#15340](https://github.com/sonic-net/sonic-mgmt/issues/15340)
A a skip condition

Update skip list for generic hash at dualtor aa setup

---

tests/span/conftest.py

Add a mirror session check after mirror session created then start packet validation
Summary:
Mirror case failure due to traffic loss form time to time.
Mirror case failure due to traffic loss form time to time.
Add a mirror session check after mirror session created then start packet validation.

Add a mirror session check

---

tests/common/flow_counter/flow_counter_utils.py

Summary:
We have observed counter check failure in the static route test within the RouteFlowCounterTestContext.
The root cause was the counters were not updated when they were checked due the counter update interval was not completely elapsed.
So we need to wait for the interval before checking the counters.
Please see the summary.
Please see the summary.
Run the static route test in a loop, no more counter failures.

Add a delay for counter update interval in RouteFlowCounterTestContext

---

tests/route/test_route_perf.py

Add a crm resource pre check in order to make sure crm resource is ready before test
Summary:
CRM resource may not ready at the beginning of route performance test
Add a crm resource pre check in order to make sure crm resource is ready before test

Enhance route performance test | Add a crm resource pre check before test

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Fixes # (https://github.com/sonic-net/sonic-mgmt/issues/10955)
Removed xfail for test continuous link flap  as https://github.com/sonic-net/sonic-mgmt/issues/10955 closed
Remove xfail as issue has been fixed
Remove xfail
Run test, test passed

Removed xfail for test_cont_link_flap

---

ansible/roles/test/files/ptftests/py3/advanced-reboot.py

Summary:
Avoid error during performing a reboot from the 202205 image.
Despite reboot help command cli output contains retry count flags, they are not implemented
Run reboot command without retry count flags for 202205 image

Ignore retry count when rebooting from 202205 image in advanced-reboot

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
tests/tacacs/test_accounting.py

Summary: cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/15759

[202405] [tacacs] increase timeout value for accounting test and ignore loganalyzer

---

tests/dhcp_server/dhcp_server_test_common.py

Summary:
Add support for verify_discover_and_request_then_release to verify cutomized options
Add support for verify_discover_and_request_then_release to verify cutomized options
Run tests

[dhcp_server] Add support for verify_discover_and_request_then_release to verify cutomized options

---

tests/gnmi/test_gnoi_killprocess.py

In PR #12478, a new test script was introduced without the required `pytest.mark.topology` marker to specify the topology it supports. This PR resolves the issue by adding the missing marker to the script.
Summary:
In PR #12478, a new test script was introduced without the required `pytest.mark.topology` marker to specify the topology it supports. This PR resolves the issue by adding the missing marker to the script.
This PR resolves the issue by adding the missing marker to the script.

Add topology mark into test_gnoi_killprocess.py

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary: Update the skip based on the skip description 

Update the skip condition for test_vlan_subnet_decap

---

.azure-pipelines/run-test-elastictest-template.yml

- [CI]Fix retry_cases_include and retry_cases_exclude not passing down. It was caused by my another PR: https://github.com/sonic-net/sonic-mgmt/pull/15618
- Remove unused param.

[CI]Fix retry_cases_include and retry_cases_exclude not passing down

---

ansible/config_sonic_basedon_testbed.yml
ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py

Summary:
Introduce Cisco 8122 new SKU: Cisco-8122-O64S2
Introduce Cisco 8122 new SKU: Cisco-8122-O64S2

Introduce Cisco 8122 new SKU: Cisco-8122-O64S2

---

.azure-pipelines/dependency-check.yml
.azure-pipelines/dependency_check/dependency_check.py

In PR #15692, we introduced a cross-feature dependency checker in the pipeline. However, there were issues preventing the checker from failing the pipeline and blocking the merge when dependencies were detected. In this PR, we resolve those issues, ensuring that the pipeline fails if any cross-feature dependencies are identified.
Summary:
In PR #15692, we introduced a cross-feature dependency checker in the pipeline. However, there were issues preventing the checker from failing the pipeline and blocking the merge when dependencies were detected. In this PR, we resolve those issues, ensuring that the pipeline fails if any cross-feature dependencies are identified.
In this PR, we resolve those issues, ensuring that the pipeline fails if any cross-feature dependencies are …

[Bugfix] Enforce cross-feature dependency checker in pipeline

---

ansible/config_sonic_basedon_testbed.yml
ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py

Summary:
Manually cherry-pick PR #15954  - Introduce Cisco 8122 new SKU: Cisco-8122-O64S2

Manually cherry-pick PR15954 - Introduce Cisco 8122 new SKU: Cisco-8122-O64S2

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
This PR is to cherry-pick #14731 to `20311` branch.

[202311] Skip error message due to missing feature (#14731)

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
Add a new error pattern into the ignore list for SN4280. 
This error should be ignored by the known issue(https://github.com/sonic-net/sonic-buildimage/issues/17683), but there is a slight difference in the error pattern comparing the existing pattern. So we need to add a new pattern.
Ignore an error based on a known issue.
Add a new pattern to the file ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt.
Run regression, the error is not observed anymore.

[SN4280] Add an error into the ignore list for SN4280

---

tests/qos/test_qos_sai.py

Summary:
Double commit https://github.com/sonic-net/sonic-mgmt/pull/15352

[202405] Update skip conditions for watermark cases

---

.azure-pipelines/testbed_health_check.py
ansible/library/dut_basic_facts.py

Add T2 device health check support. **The health check functionality on T2 will still be skipped/disabled by default after this PR**. We will enable it after completing the T2 device auto recovery.
Summary:
Fixes # (issue) Microsoft ADO 30293537
We wanted to support T2 device health check, like what we have for T0 and T1.

feat: add T2 device health check support

---

tests/pfcwd/test_pfcwd_cli.py

Fix the issue on Cisco platform
Remove forward action
Run the test on Cisco platform
Summary:

Correct the pfcwd action on Cisco platform

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
tests/pc/test_po_cleanup.py

Summary:
Fix the testcase on Cisco
test_reload_configuration_checks: skip for cisco-8000 202405
test_po_cleanup_after_reload: extend wait time
Run the test on Cisco platform

update testcase test_reload_configuration_checks and test_po_cleanup_after_reload

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Skip test_dhcp_relay for Cisco 8122 BE deployment and fix a typo in previous commit.
Skip test_dhcp_relay for Cisco 8122 BE deployment

Skip test_dhcp_relay for Cisco 8122 BE deployment

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x100G_Nokia-IXR7250E-SUP-10_LC1.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x100G_Nokia-IXR7250E-SUP-10_LC2.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x100G_Nokia-IXR7250E-SUP-10_LC3.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x100G_Nokia-IXR7250E-SUP-10_LC4.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x100G_Nokia-IXR7250E-SUP-10_LC5.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x100G_Nokia-IXR7250E-SUP-10_LC6.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x100G_Nokia-IXR7250E-SUP-10_LC7.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x100G_Nokia-IXR7250E-SUP-10_LC8.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x400G_Nokia-IXR7250E-SUP-10_LC1.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x400G_Nokia-IXR7250E-SUP-10_LC2.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x400G_Nokia-IXR7250E-SUP-10_LC3.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x400G_Nokia-IXR7250E-SUP-10_LC4.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x400G_Nokia-IXR7250E-SUP-10_LC5.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x400G_Nokia-IXR7250E-SUP-10_LC6.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x400G_Nokia-IXR7250E-SUP-10_LC7.yaml
tests/voq/fabric_data/Nokia-IXR7250E-36x400G_Nokia-IXR7250E-SUP-10_LC8.yaml
tests/voq/fabric_data/Nokia-IXR7250E-SUP-10.yaml

Summary:
Adding support to run voq fabric tests on Nokia Hwsku. Added files for Nokia hwsku and added Nokia platform 
to conditional 
- [ x] 202205
- [x ] 202405
The voq fabric tests were skipped for Nokia platform due to missing files and conditional mark did not have Nokia platform.
Added relavent files and added Nokia platform so test is not skipped.
Ran test on t2 platform
Nokia Chassis ixre_7250e

Adding support to run voq fabric tests on Nokia Hwsku

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
tests/platform_tests/api/test_chassis.py
tests/platform_tests/api/test_chassis_fans.py
tests/platform_tests/api/test_component.py
tests/platform_tests/api/test_fan_drawer.py
tests/platform_tests/api/test_fan_drawer_fans.py
tests/platform_tests/api/test_module.py
tests/platform_tests/api/test_psu.py
tests/platform_tests/api/test_psu_fans.py
tests/platform_tests/api/test_sfp.py
tests/platform_tests/api/test_thermal.py
tests/platform_tests/daemon/test_fancontrol.py
tests/platform_tests/daemon/test_ledd.py
tests/platform_tests/daemon/test_pcied.py
tests/platform_tests/daemon/test_psud.py
tests/platform_tests/daemon/test_syseepromd.py
tests/route/test_route_flow_counter.py

Previously, we used the `pr_test_skip_scripts.yaml` file to maintain a list of test scripts that were temporarily excluded from PR testing. In the new PR testing model, we are moving away from hardcoded scripts and will instead use conditional markers to skip tests as needed. Since there are numerous scripts to address, we will handle them incrementally by dividing them across different PRs based on their respective topologies.
Summary:
Previously, we used the `pr_test_skip_scripts.yaml` file to maintain a list of test scripts that were temporarily excluded from PR testing. In the new PR testing model, we are moving away from hardcoded scripts and will instead use conditional markers to skip tests as needed. Since there are numerous scripts to address, we will handle them …

Transite to conditional marks for skipping T0 test scripts

---

tests/common/helpers/dut_utils.py
tests/common/reboot.py
tests/conftest.py

1. Add function to collect console log from starting reboot to dut up
2. When dut is not up, check if dut is pingable and collect the mgmt interface config
Summary:
Enhance the debugability for reboot fucntion
1. Add function to collect console log from starting reboot to dut up
2. When dut is not up, check if dut is pingable and collect the mgmt interface config
Run reboot cases
Any

Add debuggability for reboot function

---

tests/show_techsupport/tech_support_cmds.py

Summary:
This PR should be followed by https://github.com/sonic-net/sonic-mgmt/pull/15466.
There is a circular dependency where the sonic-utilities submodule after this change https://github.com/sonic-net/sonic-utilities/pull/3605 will not get update unless show techsupport test pass. However the test cannot pass until we have sonic-utilities submodule updated.
To overcome this create a temporary PR to remove the techsupport commands that create this dependency. After the submodule update is done  https://github.com/sonic-net/sonic-mgmt/pull/15466 can be merged

Removing bpg commands to resolve circular dependency

---

tests/route/test_route_flap.py

Add support to handle multi-asic platforms for route flap script

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
test_cacl_application is skipped in 202405 branch, that's because the 202405 branch was branch out before the following PR got merged:
https://github.com/sonic-net/sonic-mgmt/pull/13877
Remove skip condition for test_cacl_application
https://github.com/sonic-net/sonic-mgmt/issues/13805 was closed and remove skip condition to make condition mark file clean.
Run test_cacl_application in 202405

[202405] Remove test_cacl_application skip condition

---

ansible/golden_config_db/smartswitch_t1-28-lag.json
ansible/library/generate_golden_config_db.py

Summary: Update SmartSwitch Golden Config for dhcp and gnmi
More config table need to be updated for SmartSwitch
Update SmartSwitch Golden Config for dhcp and gnmi
E2E

[smartswitch] Update smartswitch golden config

---

tests/acl/test_acl_outer_vlan.py
tests/common/helpers/portchannel_to_vlan.py

Add cisco-8000 in the qinq fanout support list

---

tests/wol/conftest.py
tests/wol/test_wol.py

Add tests related to wake on lan with udp.
Summary:
Add new tests for wake on lan udp.
Run wol command and check is valid packets are received.
Run tests on 720dt mx devices.

[wol] add test for wol udp

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Skip vxlan bfd tsa testcases 4/5/6 due to issue(https://github.com/sonic-net/sonic-mgmt/issues/15728) 
Skip vxlan bfd tsa testcases 4/5/6 due to issue(https://github.com/sonic-net/sonic-mgmt/issues/15728) 
Skip file on github issue
Rerun the test and see it is skipped
All

Skip vxlan bfd tsa testcase4/5/6 due to issue#15728

---

azure-pipelines.yml

Summary:
For 202411 branch PR testing, branch "202411" instead of "master" should be used.

Fix the branch in pipeline yaml for 202411 PR testing

---

.azure-pipelines/pr_test_scripts.yaml

Some newly added control plane test scripts were not included in the PR checker. In this PR, we incorporate them into the onboarding PR checkers.
Summary:
Some newly added control plane test scripts were not included in the PR checker. In this PR, we incorporate them into the onboarding PR checkers.
In this PR, we incorporate the newly added control plane test scripts into the onboarding PR checkers.

Add remain control plane test scripts into onboarding PR checkers. 

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

An issue has been identified with `test_gnoi_killprocess.py` on the KVM testbed, and we have raised issue #16238 to track it. In this PR, we temporarily skip this script in PR testing by using the conditional mark.
Summary:
An issue has been identified with `test_gnoi_killprocess.py` on the KVM testbed, and we have raised issue #16238 to track it. In this PR, we temporarily skip this script in PR testing by using the conditional mark.

Skip `test_gnoi_killprocess.py` temporarily in PR testing due to the issue. 

---

tests/voq/fabric_data/Arista-7800R3A-36D2-C36_Arista-7804R3-FM_LC3.yaml
tests/voq/fabric_data/Arista-7800R3A-36D2-C36_Arista-7804R3-FM_LC4.yaml
tests/voq/fabric_data/Arista-7800R3A-36D2-C36_Arista-7804R3-FM_LC5.yaml
tests/voq/fabric_data/Arista-7800R3A-36D2-C36_Arista-7804R3-FM_LC6.yaml
tests/voq/fabric_data/Arista-7800R3A-36D2-C72_Arista-7804R3-FM_LC3.yaml
tests/voq/fabric_data/Arista-7800R3A-36D2-C72_Arista-7804R3-FM_LC4.yaml
tests/voq/fabric_data/Arista-7800R3A-36D2-C72_Arista-7804R3-FM_LC5.yaml
tests/voq/fabric_data/Arista-7800R3A-36D2-C72_Arista-7804R3-FM_LC6.yaml
tests/voq/fabric_data/Arista-7800R3A-36D2-D36_Arista-7804R3-FM_LC3.yaml
tests/voq/fabric_data/Arista-7800R3A-36D2-D36_Arista-7804R3-FM_LC4.yaml
tests/voq/fabric_data/Arista-7800R3A-36D2-D36_Arista-7804R3-FM_LC5.yaml
tests/voq/fabric_data/Arista-7800R3A-36D2-D36_Arista-7804R3-FM_LC6.yaml
tests/voq/fabric_data/Arista-7800R3A-36DM2-C72_Arista-7804R3-FM_LC3.yaml
tests/voq/fabric_data/Arista-7800R3A-36DM2-C72_Arista-7804R3-FM_LC4.yaml
tests/voq/fabric_data/Arista-7800R3A-36DM2-C72_Arista-7804R3-FM_LC5.yaml
tests/voq/fabric_data/Arista-7800R3A-36DM2-C72_Arista-7804R3-FM_LC6.yaml
tests/voq/fabric_data/Arista-7800R3A-36DM2-D36_Arista-7804R3-FM_LC3.yaml
tests/voq/fabric_data/Arista-7800R3A-36DM2-D36_Arista-7804R3-FM_LC4.yaml
tests/voq/fabric_data/Arista-7800R3A-36DM2-D36_Arista-7804R3-FM_LC5.yaml
tests/voq/fabric_data/Arista-7800R3A-36DM2-D36_Arista-7804R3-FM_LC6.yaml
tests/voq/fabric_data/Arista-7800R3AK-36DM2-C72_Arista-7804R3-FM_LC3.yaml
tests/voq/fabric_data/Arista-7800R3AK-36DM2-C72_Arista-7804R3-FM_LC4.yaml
tests/voq/fabric_data/Arista-7800R3AK-36DM2-C72_Arista-7804R3-FM_LC5.yaml
tests/voq/fabric_data/Arista-7800R3AK-36DM2-C72_Arista-7804R3-FM_LC6.yaml
tests/voq/fabric_data/Arista-7800R3AK-36DM2-D36_Arista-7804R3-FM_LC3.yaml
tests/voq/fabric_data/Arista-7800R3AK-36DM2-D36_Arista-7804R3-FM_LC4.yaml
tests/voq/fabric_data/Arista-7800R3AK-36DM2-D36_Arista-7804R3-FM_LC5.yaml
tests/voq/fabric_data/Arista-7800R3AK-36DM2-D36_Arista-7804R3-FM_LC6.yaml

Add fabric test data for 4 slot chassis 
Summary: Add fabric test data for 4 slot arista chassis 

Add new fabric test data for 4 slot chassis

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/voq/test_voq_fabric_capacity.py

Summary: Add test_voq_fabric_capacity.py to test fabric capacity monitoring and related CLI.

Add test_voq_fabric_capacity.py

---

.azure-pipelines/impacted_area_testing/get-impacted-area.yml

In the Impacted Area Based PR testing, we identify the modified feature folders for the changes in a PR. Previously, the code retrieved the same feature folder multiple times if multiple modified scripts were located within it. However, we only need to retrieve each feature folder once. This PR optimizes the process to eliminate redundant retrievals.
Summary:
In the Impacted Area Based PR testing, we identify the modified feature folders for the changes in a PR. Previously, the code retrieved the same feature folder multiple times if multiple modified scripts were located within it. However, we only need to retrieve each feature folder once. This PR optimizes the process to eliminate redundant retrievals.
Implement a check to skip retrieval if the feature folder has …

Optimize feature folder retrieval in Impacted Area Based PR Testing

---

.github/PULL_REQUEST_TEMPLATE.md

Add back port option for 202411 branch.
Summary:

chore: add back port option for 202411 branch

---

tests/generic_config_updater/test_lo_interface.py

Summary: conflict resolve for https://github.com/sonic-net/sonic-mgmt/pull/16084

[202311][GCU] Reload after lo test to recover default route

---

tests/generic_config_updater/test_lo_interface.py

Summary: conflict resolve for https://github.com/sonic-net/sonic-mgmt/pull/16084

[202405][GCU] Reload after lo test to recover default route

---

.github/PULL_REQUEST_TEMPLATE.md

Summary:
Add a reminder for submitter when adding new test case.
Help submitter pay attention on supported platforms and skip it for non-supported platforms correctly.
Make sure new added script/case is skipped properly and new ownership is added.
Add a reminder for submitter when adding new test case.
Help submitter pay attention on supported platforms and skip it for non-supported platforms correctly.
Make sure new added script/case is skipped properly and new ownership is added.

Modify PR template

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
For the following err msg it could be ignored:
ERR syncd#SDK: [SAI_UTILS.ERR] ./src/mlnx_sai_utils.c[2057]- get_dispatch_attribs_handler: Failed Get #0, INGRESS_SAMPLE_MIRROR_SESSION, key:PORT [OID:0x1] [log_port:0x0]
ERR syncd#SDK: [SAI_UTILS.ERR] ./src/mlnx_sai_utils.c[2057]- get_dispatch_attribs_handler: Failed Get #0, EGRESS_SAMPLE_MIRROR_SESSION, key:PORT [OID:0x1] [log_port:0x0]
Skip the ignorable err msg.

Update the err msg ignore list

---

tests/arp/test_stress_arp.py

Summary:
Manually cherry-pick PR #15842

[Manually cherry-pick #15842]Choose ARP scale based on available NH entries for CISCO 8000

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
Due to known issue https://github.com/sonic-net/sonic-buildimage/issues/21319
PR #16301 doesn't ignore all the pmon iSmart binary format ERR log. Update the regex to ignore all of below ERR logs:
```
/var/log/syslog.3.gz:2025 Jan  9 20:42:05.687373 7215-5 ERR pmon#SsdUtil[55]: [Errno 8] Exec format error: 'iSmart'
/var/log/syslog.3.gz:2025 Jan  9 20:42:07.744397 7215-5 ERR pmon#StorageCommon[55]: [Errno 8] Exec format error: 'iSmart'
/var/log/syslog.5.gz:2025 Jan  9 19:37:33.855554 7215-5 ERR pmon#SsdUtil[49]: [Errno 8] Exec format error: 'iSmart'
/var/log/syslog.5.gz:2025 Jan  9 19:37:35.261567 7215-5 ERR pmon#StorageCommon[49]: [Errno 8] Exec format error: 'iSmart'
```
PR #16301 doesn't ignore all the pmon iSmart binary format ERR log. Update the regex to ignore all of below …

[loganalyzer] Ignore pmon iSmart binary format ERR log

---

.azure-pipelines/pr_test_scripts.yaml

Script `bgp/test_bgp_bbr_default_state.py` is stable enough in onboarding t1 PR checker, so we move it to standard PR checker. 
Summary:
Script `bgp/test_bgp_bbr_default_state.py` is stable enough in onboarding t1 PR checker, so we move it to standard PR checker. 
Move script  `bgp/test_bgp_bbr_default_state.py` to standard PR checker. 
vms-kvm-t1-lag | bgp/test_bgp_bbr_default_state.py | 2025-01-10 00:00:00.0000000 | 25 | 0 | 25 | 1
vms-kvm-t1-lag | bgp/test_bgp_bbr_default_state.py | 2025-01-09 00:00:00.0000000 | 53 | 0 | 53 | 1
vms-kvm-t1-lag | bgp/test_bgp_bbr_default_state.py | 2025-01-08 00:00:00.0000000 | 32 | 0 | 32 | 1
vms-kvm-t1-lag | …

Move some stable test scripts to standard PR checkers. 

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
Manually cherry-pick PR #16347

[Cherry-pick #16347]Ignore leap second file expiration syslog error

---

tests/platform_tests/test_intf_fec.py

For sonic versions which does not have support for port FEC BER, skip the test instead of failing the test. 
This fixes the PR https://github.com/sonic-net/sonic-mgmt/pull/15481
Summary:

Do the skip instead of failing test for FEC-BER unsupported interfaces

---

tests/qos/qos_sai_base.py

Optimize the `qos/test_qos_sai.py` test to reduce the running time.
Summary:
The running time of the `qos/test_qos_sai.py` test is too long (~9h) on T2 chassis so we wanted to reduce the running time. With this implementation, the running time will be reduced to (~7.5h)
I ran the updated code and can confirm it's working well on T2 chassis: Elastictest [link](https://elastictest.org/scheduler/testplan/67802e043dd5199fbee9dcbc?leftSideViewMode=detail&testcase=qos%2Ftest_qos_sai.py&type=console). The 2 DWRR failures are expected, which will be fixed after #16199 
I also ran a T1 regression test to confirm: Elastictest [link](https://elastictest.org/scheduler/testplan/67806217745d47c6b42e53b9?leftSideViewMode=detail&testcase=qos%2Ftest_qos_sai.py&type=co …

[manual] [PR:16428] refactor: optimize qos sai test

---

.github/PULL_REQUEST_TEMPLATE.md

Summary:
To avoid causing confusion for community, remove ownership TSG in PR template

Remove ownership TSG in PR template

---

tests/pfcwd/test_pfcwd_timer_accuracy.py

Summary:
https://github.com/sonic-net/sonic-mgmt/pull/16446/files
PR merge conflict
manually merge

[202411] backport PR 16446 [test_pfcwd_timer_accuracy] handle exception during grep log

---

tests/pfcwd/files/pfcwd_helper.py
tests/pfcwd/test_pfcwd_warm_reboot.py

Script log Analyzer timestamp is 2025-01-07 13:26:55.978427 while the real detect timestamp in syslog is Jan 7 13:27:18.132683. Need delay more time to grep the syslog
2025 Jan  7 13:26:55.996909 bjw2-can-7260-2 DEBUG extract_log combine_logs from file /var/log/syslog create time 2025-01-07 13:26:55.978427, size 4236007
syslog:23447:2025 Jan  7 13:27:18.132683 bjw2-can-7260-2 NOTICE swss#orchagent: :- report_pfc_storm: PFC Watchdog detected PFC storm on port Ethernet24, queue index 3, queue id 0x1500000000014d and port id 0x1000000000001
Increase the delay time and add some debug log in script
Use elastic to run the case on 7060 and 2700, passed. https://elastictest.org/scheduler/testplan/67808a9a572c09d3aa4 …

[202405] backport (#16445) [test_pfcwd_wb] increase delay time for detecting pfcwd storm

---

ansible/roles/vm_set/files/mux_simulator.py

Summary:
Use thread-pool to parallel run the mux toggles.
This code is from PR: https://github.com/sonic-net/sonic-mgmt/pull/16164, which is reverted.
Let's have the change here.
Run on dualtor/dualtor-120 testbed.

[infra][mux simulaotr] Improve mux simulator toggle performance

---

.azure-pipelines/impacted_area_testing/calculate-instance-numbers.yml
.azure-pipelines/impacted_area_testing/constant.py
.azure-pipelines/impacted_area_testing/get_test_scripts.py
azure-pipelines.yml

To prevent error handling in the Azure pipeline YAML, we avoid using overlapping PR checker names by adding a suffix for the T0 and T1 PR checkers. However, we continue using the topology name to filter test scripts, which no longer matches the PR checker name. To resolve this issue and standardize the approach, we apply the suffix to all PR checkers and filter the scripts using the `topology_{suffix}` format.
Summary:
To prevent error handling in the Azure pipeline YAML, we avoid using overlapping PR checker names by adding a suffix for the T0 and T1 PR checkers. However, we continue using the topology name to filter test scripts, which no longer matches the PR checker name. To resolve this issue and standardize the approach, we apply the suffix to all PR checkers and …

[Impacted Area Based PR testing] Improve PR checker naming and script filtering consistency.

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py
tests/qos/qos_sai_base.py

Support new hwsku Cisco-8101-O8V48

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py
tests/qos/qos_sai_base.py

Support hwsku Cisco-8101-O8V48

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Script `srv6/test_srv6_static_config.py` was added in PR #16516, and it fails to run on kvm testbed. We temporarily skip this test in PR testing using conditional mark. 
Summary:
Script `srv6/test_srv6_static_config.py` was added in PR #16516, and it fails to run on kvm testbed. We temporarily skip this test in PR testing using conditional mark. 
We temporarily skip this test in PR testing using conditional mark. 
Test by pipeline itself to see if this script can be skipped on kvm testbed.

Skip test_srv6_static_config.py in PR testing. 

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Add some err msg to common ignore, since it is safe to ignore. 
Summary:

Add err msg ignore

---

tests/qos/test_qos_sai.py

In continuation of the PR #14469, adding the fixture to few more tests in test_qos_sai.
Summary:

[Qos] Adding change_lag_lacp_timer fixture to few more tests

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

This PR is to cherry-pick #16635 to 202405 branch.
Add some err msg to common ignore, since it is safe to ignore. 
Summary:

[202405][cherry-pick] Add some err msg to common ignore, since it is safe to ignore. (#16635)

---

.azure-pipelines/test_plan.py

To enable PR testing in the msft repo, we need to ensure support for checking out its code. This PR introduces the way to enable code checkout for the msft repo.
Summary:
To enable PR testing in the msft repo, we need to ensure support for checking out its code. This PR introduces the way to enable code checkout for the msft repo.
If repo_name contains msft, we will check out msft test repo. 
Test by pipeline.

Support checking out msft repo. 

---

tests/bgp/bgp_helpers.py
tests/bgp/test_startup_tsa_tsb_service.py
tests/conftest.py

Optimize the startup tsa tsb test to reduce the running time on T2 topo.
Summary:
The running time of `bgp/test_startup_tsa_tsb_service.py` on T2 topo is extremely long (~7.6 hours). Therefore, we wanted to optimize this test module by Python multithreading to reduce the running time. After the optimization, the running time will be reduced to ~4.9 hours. 
Use multithreading to optimize the logic.
I ran the updated code and can confirm it's working well: Elastictest [link](https://elastictest.org/scheduler/testplan/6790768ebf99d5a9384d592d?leftSideViewMode=detail).
Besides, this PR also includes a minor refactoring to the `generate_params_hostname_rand_per_hwsku()` function, which is used by the `enum_rand_one_per_hwsku_hostname` fixture and …

refactor: optimize startup tsa tsb test

---

tests/srv6/test_srv6_static_config.py

Summary: The previous test implementation required the latency of APPL_DB MY_SID entries programming to be very low. However, this may not be true in physical device. So, I revise the test case to make it more tolerant.

Make test_srv6_static_config more tolerant to APPL_DB programming delay

---

.azure-pipelines/impacted_area_testing/calculate-instance-numbers.yml

Fix bug in command to extract test scripts in impact area testing.
Summary:
Fix issue in CI
Fix bash command syntax
TBD
No
NA
NA

Fix command to extract test scripts

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Set `test_multiasic_idf.py` and `test_multiasic_linkcrc.py` to run only in multi asic system.
Add skip for test_multiasic_idf.py and test_multiasic_linkcrc.py in yaml file.
The original multiasic incremental config update test [PR](https://github.com/sonic-net/sonic-mgmt/pull/13210) will fail if the device was single asic. 
Skip non multi asic system.

Mark IDF and LinkCRC test as MULTI ASIC only.

---

.azure-pipelines/impacted_area_testing/calculate-instance-numbers.yml

Fix intermittent failures in CI with impacted area testing when TEST_SCRIPTS is very long. The PR refactors processing of TEST_SCRIPT variable.
Summary:
Fix intermittent failures in CI with impacted area testing when TEST_SCRIPTS is very long. The PR refactors processing of TEST_SCRIPT variable.
Refactor processing of TEST_SCRIPT variable
Verified via DEBUG PR.
No
NA
NA

Fix intermittent failures in CI with impacted area testing

---

tests/qos/test_qos_sai.py

The  test_qos_sai ignore_regex  list is added only to loganalyzer ignore_list  of the DUT which is selected as a src_dut/dst_dut.
Adding the error  "SAI_API_SWITCH:brcm_sai_set_switch_attribute:5089 updating switch mac addr failed with error -2" to all the front-end nodes irrespective of the selected DUT for  qos run.
Summary:
Lately saw this error (above) got delayed logging into syslog by 5 mins. In the meantime, the test run moved to new test  and started with a different front-end node due to random selection of dut. In this case the ignore_regex got added to loganalyzer  ignore_list of a different dut  than the previous one. But the error logged later got caught by loganalyzer for the previous dut.
Adding this error regex to all the dut's loganalyzer ignore_list to …

[Qos]Loganalyser ignore_regex update for all nodes in test_qos

---

tests/bgp/test_traffic_shift_sup.py

Optimize the traffic shift sup test with Python multithreading.
Summary:
We wanted to optimize the traffic shift sup test to reduce its running time. After the optimization, the running time will decrease from ~56 min to ~25 min. 
I ran the updated code and can confirm it's working well. Elastictest: https://elastictest.org/scheduler/testplan/67a2197635bede1798502580?leftSideViewMode=detail

refactor: optimize traffic shift sup test

---

tests/platform_tests/test_reload_config.py

Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/16085 into 202411

[202411] Fix unexpected exception in wait_for while executing reboot

---

tests/common/helpers/dut_utils.py

Summary:
Fixes # (issue) 30545289
Add console_password as the password for console login as some devices might use this during setup.
Add console_password as the password for console login as some devices might use this during setup.

chore: fix console password

---

tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py
tests/snappi_tests/variables.py

Summary:
T2-Route Conv: Process Crash TC: Updated the test to accomodate new changes in the process crash scenario
To fix the issue https://github.com/sonic-net/sonic-buildimage/issues/21586 new change is introduced as part of PR https://github.com/sonic-net/sonic-buildimage/pull/21587
This change is to accommodate the new changes in the process crash testcase
Execute TSB after process crash to make sure traffic is back before validation stage
Ran the testcase with the new changes and verified the results
NA
NA

T2-Snappi-Route-Conv: Update process crash Testcase

---

tests/crm/test_crm.py

Summary: Dynamically update neighbors being added for cisco asics instead of hardcoded value to avoid scale issues if an asic doesn't have the support to handle 3000 nexthops
test_crm.py::test_crm_neighbor TC failed on some asics due to exhaustion of resources as the hardcoded 3000 neighbors is past the supported nexthop amount on (some) cisco asics. This change is to allow for test to dynamically add neighbors based on the scale nexthop amount that is supported on cisco devices.
resource exhaustion causing errors on asics that don't support at least the hardcoded 3k neighbors set in script
calling supported nexthop amount for asic and setting it to neighbor amount to be added (for cisco devices)
tested with change

Fix test_crm.py::test_crm_neighbor neighbor resource issues to update dynamically

---

tests/route/test_default_route.py

Summary:
Microsoft ADO id: 27588923
Added performance test for bmp feature, since after bmp feature switch is enabled it will introduce some impact into below two processes:
/usr/lib/frr/bgpd -A 127.0.0.1 -P 0 -M snmp -M bmp
/usr/bin/openbmpd -f -l /var/log/openbmpd.log -c /etc/bmp/openbmpd.conf
This PR aims at adding some memory monitoring measurement during test_default_route_with_bgp_flap() execution, given this case will introduce bgp flapping which is under extreme condition, and impact bgpd/openbmpd potentially.
Add some memory monitoring measurement during test_default_route_with_bgp_flap() execution, given this case will introduce bgp flapping which is under extreme condition, and impact bgpd/openbmpd potentially.
Before test_default_route_with_bgp_flap() is …

Add memory consumption check for bgpd/openbmpd during test_default_route_with_bgp_flap stress test

---

tests/common/helpers/dut_utils.py
tests/common/reboot.py
tests/conftest.py

Summary:
Fixes # (issue) Fix conflict bot PR #16815

[Conflict] [#16815] Add debuggability for reboot function (#15868)

---

.azure-pipelines/baseline_test/baseline.test.template.yml

In this PR, we transition the Baseline test to impacted area-based test, enabling automatic selection of test scripts using pytest marks.
Summary:
In this PR, we transition the Baseline test to impacted area-based test, enabling automatic selection of test scripts using pytest marks.
Change the yaml file `baseline.test.template.yml` to use impacted area-based PR testing.
For test, you can refer to https://dev.azure.com/mssonic/build/_build/results?buildId=765364&view=results

Transition Baseline test to Impacted Area-Based Test

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary: Add some err msg to common ignore, since it is safe to ignore. This is to handler conflict of 202411 for https://github.com/sonic-net/sonic-mgmt/pull/16635, 

Add some err msg to common ignore, since it is safe to ignore.

---

tests/common/helpers/dut_utils.py

Summary: fix conflict for https://github.com/sonic-net/sonic-mgmt/pull/16626
Summary:
Fixes # (issue) 30545289
Add console_password as the password for console login as some devices might use this during setup.
Add console_password as the password for console login as some devices might use this during setup.
-->

fix conflict #16626

---

tests/platform_tests/daemon/test_psud.py

Summary:
We need to recall collect_data again to update the stale state of wait_until.
recall the same collect_data function

fix test_psud collect_data bug

---

tests/srv6/test_srv6_static_config.py

Summary: The previous test scripts did not present any messages when an assertion error is triggered, which makes it difficult for people who are not familiar with the SRv6 stack to triage the error. I added several assertion error messages to help people understand the errors.

add assertion error messages

---

tests/ipfwd/test_nhop_group.py

Summary:
Fix incorrect function call from previous PR. Fix is present on master but not 202411. Backporting from:
https://github.com/sonic-net/sonic-mgmt/pull/16387/
Backport missing fix from master to 202411.

Cast fix for ipfwd/test_nhop_group.py from master

---

tests/drop_packets/drop_packets.py
tests/drop_packets/test_drop_counters.py

Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/10634
Additionally, a few extra small fixes from master have been migrated to this branch manually (which were too difficult to cherry pick properly due to newer commits having been cherry picked to this branch already).

[202012] Fix drop counter test (#10634)

---

.github/ISSUE_TEMPLATE/01-testcase.yml
.github/workflows/apply-label.yml

Modify issue template for bug, enhancement, test gap. Add workflow to label/tag a newly opened issue with this template.
Summary:
Enhance issue template
Add github workflow
https://github.com/opcoder0/sonic-mgmt-issue
None
NA
NA

[Issue Template] Modify issue template for bug, enhancement, test gap

---

tests/srv6/test_srv6_dataplane.py

Summary: 1) change the way of getting neighbor mac in test_srv6_uN_forwarding; 2) set up proper values in TC and TTL fields for testing in test_srv6_uN_decap_pipe_mode.

Improve test_srv6_dataplane.py

---

tests/common/helpers/drop_counters/drop_counters.py
tests/drop_packets/test_drop_counters.py

Optimize drop counters test with Python multithreading to reduce its running time.
Summary:
We wanted to reduce the running time of `drop_packets/test_drop_counters.py`. After the optimization, the running time will decrease from ~180 min to ~140 min.
I ran the updated code and can confirm it's working well. Elastictest [link](https://elastictest.org/scheduler/testplan/67a29b10f5b8ddd54706fc9e?testcase=drop_packets%2Ftest_drop_counters.py&type=console&leftSideViewMode=detail).
T0 & T1 regression tests: 
- T0: Elastictest [link](https://elastictest.org/scheduler/testplan/67b7a7e76d2a9cb6b2c91160?testcase=drop_packets%2Ftest_drop_counters.py&type=console)
- T1: Elastictest [link](https://elastictest.org/scheduler/testplan/67b7a7a540469cdb6db51241?testca …

refactor: optimize drop counters test

---

.github/ISSUE_TEMPLATE/01-testcase.yml

The issue template does not load/activate without a title. This PR fixes the issue. Change issue template name and set title.
Summary:
Fix the issue template name and set title
Modify issue template
NA
NA
NA
NA

Fix: set title and change name

---

.azure-pipelines/run-test-elastictest-template.yml

Previously, the `Download Pr Script` step in PR testing did not support the Azure/sonic-buildimage-msft repository. This PR resolves the issue by adding the repository name to the if condition.
Summary:
Previously, the `Download Pr Script` step in PR testing did not support the Azure/sonic-buildimage-msft repository. This PR resolves the issue by adding the repository name to the if condition.
This PR resolves the issue by adding the repository name to the if condition.

Add support for Azure/sonic-buildimage-msft in PR Testing.

---

tests/common/dualtor/data_plane_utils.py
tests/common/dualtor/dual_tor_io.py

Summary:
Two improvements:
1. force replace the dst arp responder config.
2. add show arp and neighbor check in I/O utility to help debug.
```
dualtor_io/test_tor_failure.py::test_active_tor_reboot_downstream[active-active] PASSED                                                                                                                                                                                [100%]
```

[dualtor-io] Improve dualtor-io utility

---

tests/stress/test_stress_routes.py

Summary: Fixed casting issue
Fixes #  #16801
Fix a failed test
Added int casting to value before math actions
test passed after changes

[stress routes] fix casting issue #16801

---

ansible/roles/eos/templates/t1-smartswitch-ha-spine.j2
ansible/roles/eos/templates/t1-smartswitch-ha-tor.j2

Summary:
In the topology definition, only one member link is added for each port channel. So the min-links should be 1. 
Removed the symbolic link to `t1-tag-spine.j2`, `t1-tag-tor.j2` and created new files.  

Update j2 template of `t1-smartswitch-ha` topo's neighbor

---

tests/kvmtest.sh

Summary: Add gnmi test to kvm test suite.
gnmi test is not included in the kvm test suite.
Add the test to kvm test suite.
Run test on kvm machine.

Add gnmi test to kvm suite

---

ansible/library/generate_golden_config_db.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Fix version check logic, just disable feature less than 202411
Fix version check logic, just disable feature less than 202411
Refactor the version check logic
verified via mgmt test
N/A
N/A

Fix version check logic, just disable feature less than 202411

---

tests/common/connections/base_console_conn.py

**what**
[Fix] Fix init BaseConsoleConn got unexpected param console_device
**why**
The PR(https://github.com/sonic-net/sonic-mgmt/pull/16686) introduce a param `console_device` but not remove before BaseConsoleConn passing to parent class. 
failure example: 
```
File "/var/src/sonic-mgmt/tests/common/connections/console_host.py", line 47, in ConsoleHost
return ConsoleTypeMapper[console_type](**params)
File "/var/src/sonic-mgmt/tests/common/connections/ssh_console_conn.py", line 35, in __init__
super(SSHConsoleConn, self).__init__(**kwargs)
File "/var/src/sonic-mgmt/tests/common/connections/base_console_conn.py", line 51, in __init__
super(BaseConsoleConn, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'console_device'
```
**how**
Remove param …

Fix init BaseConsoleConn got unexpected param console_device

---

ansible/roles/vm_set/templates/sonic.xml.j2

Change dualToR KVM memory to 6G

Update dualtor memory to 6G

---

.azure-pipelines/baseline_test/baseline.test.mgmt.public.master.yml
.azure-pipelines/baseline_test/baseline.test.template.yml

Summary:
We are preparing to deploy impact area PR testing in 202411 branch, which won't always test all test sets, which means some test may not be test for a long time and if it's flaky, we are not able to find out. So baseline test is needed to find out flaky tests in 202411.
Deploy baseline test in 202411

Support baseline test in 202411 branch

---

tests/common/devices/multi_asic.py
tests/common/devices/sonic.py

Summary: The current infrastructure does not consider the situation of virtual chassis. So, we need to change some APIs to facilitate the GA of virtual chassis

Pave testing infrastructure for virtual chassis

---

tests/vlan/test_vlan_ping.py

Update vlan ping test for t0-isolated-d16u16s1
Summary:
Update vlan ping test for t0-isolated-d16u16s1
1. Update the ceos command to handle non port-channel interface
2. Update ifaces_list when there is no port-channel interface
Run it in internal testbed

Adapt vlan ping test on topology t0-isolated-d16u16s1

---

ansible/vars/configdb_jsons/7nodes_cisco/PE1.json
ansible/vars/configdb_jsons/7nodes_cisco/PE2.json
ansible/vars/configdb_jsons/7nodes_cisco/PE3.json

update bgp srv6 locator config in srv6 test to fit srv6 locator changes in https://github.com/BYGX-wcr/SONiC/blob/srv6_static_config_hld/doc/srv6/srv6_static_config_hld.md 
Summary:
Tested on daily jenkins job

test(srv6): update bgp locator config in config_db json file

---

tests/platform_tests/api/watchdog.yml

Add watchdog test data for x86_64-nvidia_sn4280-r0
Summary:
Add watchdog test data for x86_64-nvidia_sn4280-r0
Add watchdog test data for x86_64-nvidia_sn4280-r0 
Run test_watchdog.py
x86_64-nvidia_sn4280-r0

[Mellanox] Add watchdog test data for x86_64-nvidia_sn4280-r0

---

tests/common/plugins/sanity_check/__init__.py

Optimize the `print_logs()` method in `plugins/sanity_check/__init__.py` by Python multithreading.
Summary:
Fixes # (issue) Microsoft ADO 30849826
We wanted to reduce the preparation time for multi-DUT devices (e.g. T2 devices) by optimizing the `print_logs()` method in `plugins/sanity_check/__init__.py`.
I ran the updated code and can make sure it's working well.

refactor: optimize print logs by multithreading

---

.github/workflows/automerge_scan.yml

Summary:
automerge PRs are pending to be merged.
The workflow only list latest 30 PRs to automerge. Increase the list to 100.

[action] Increase automerge PR list length.

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Reverts sonic-net/sonic-mgmt#17435

Revert "[action] [PR:15978] Skip vxlan bfd tsa testcase4/5/6 due to issue#15728"

---

tests/common/devices/sonic.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/gnmi/test_gnoi_killprocess.py

Summary: Resolve conflicts in the PR #16303 
Resolve conflicts when merging into 202411, 202412
Manually cherry-picked it and solved conflicts.
str4-sn5600-1
t0-isolated-u16d16s1

Solve conflicts - Fix multiple failures in KillProcess test on KVM.

---

tests/test_posttest.py

Summary:
Sanity check in posttest was disabled by https://github.com/sonic-net/sonic-mgmt/pull/2166, but current posttest will restore container autorestart, which rely on container health.
Enable sanity check in posttest

Enable sanity check in posttest

---

tests/crm/test_crm.py

Summary:
porting change from https://github.com/sonic-net/sonic-mgmt/pull/16621 manually to handle conflict issue
resource exhaustion causing errors on asics that don't support at least the hardcoded 3k neighbors set in script
calling supported nexthop amount for asic and setting it to neighbor amount to be added (for cisco devices)
tested with change

Fix test_crm.py::test_crm_neighbor neighbor resource issues to update dynamically (port to 202405)

---

tests/container_checker/test_container_checker.py

Summary:
Fixes #17113
Fix test failures in `test_container_checker.py` caused by config reload being successive in teardown.
Change config reload from successive to parallel
Tested on platform that was previously failing due to bug
N/A
N/A

[T2] Make config_reload_after_tests fixture parallel instead of successive in test_container_checker.py

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Double commit https://github.com/sonic-net/sonic-mgmt/pull/15403

[202411] skip test_pfcwd_warm_reboot.py on cisco-8000 platform

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
tests/platform_tests/api/test_chassis.py
tests/platform_tests/api/test_chassis_fans.py
tests/platform_tests/api/test_component.py
tests/platform_tests/api/test_fan_drawer.py
tests/platform_tests/api/test_fan_drawer_fans.py
tests/platform_tests/api/test_module.py
tests/platform_tests/api/test_psu.py
tests/platform_tests/api/test_psu_fans.py
tests/platform_tests/api/test_sfp.py
tests/platform_tests/api/test_thermal.py
tests/platform_tests/daemon/test_fancontrol.py
tests/platform_tests/daemon/test_ledd.py
tests/platform_tests/daemon/test_pcied.py
tests/platform_tests/daemon/test_psud.py
tests/platform_tests/daemon/test_syseepromd.py
tests/route/test_route_flow_counter.py

[202411][PR: 16083] Transite to conditional marks for skipping T0 test scripts.

---

tests/decap/test_decap.py

Summary: Disable the `IPv4inIPv6` and `IPv6inIPv4` for the Cisco `G200` based platforms
Cisco `G200` based platforms doesn't support the `IPv4inIPv6` and `IPv6inIPv4` decap test-cases.
Skip the `IPv4inIPv6` and `IPv6inIPv4` test-cases for Cisco `G200` based platforms.
Run the `decap/test_decap.py`

[cisco][decap] Disable IPv4inIPv6 and IPv6inIPv4 for the Cisco G200 based platforms

---

tests/common/plugins/sanity_check/checks.py

Add wait until to BFD sanity check to make it more stable.
Summary:
Fixes # (issue) Microsoft ADO 31694571
We wanted to add a wait until timeout to the BFD sanity check because sometimes the BFD might need some extra time to come up after a test module. 
I ran the updated code and can confirm it's working well. Elastcitest link: https://elastictest.org/scheduler/testplan/67d79e1606bd43461b9eecb2

refactor: add wait until to BFD sanity check

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Update skip condition for  test_check_sfp_eeprom.py because SN is a value not a variable, we need quote it with quote symbol.
Summary:
Update skip condition for test_check_sfp_eeprom.py because SN4 and SN5 are the values, not variables; we need to quote it with a quote symbol.
Add quote symbol to SN4 and SN5
Run  test_check_sfp_eeprom.py 
Mellanox

[202405|Mellanox] Update skip condition for test_check_sfp_eeprom.py

---

.github/ISSUE_TEMPLATE/01-bug.yml
.github/ISSUE_TEMPLATE/02-enhancement.yml
.github/ISSUE_TEMPLATE/03-testgap.yml
.github/ISSUE_TEMPLATE/04-regression.yml
.github/ISSUE_TEMPLATE/config.yml
.github/config.yml

Fix issue template -
- Fix Bug label
- Move config.yml to ISSUE_TEMPLATE
- Disable blank template
- Specify forum URL in contact
Summary:

Fix issue template

---

tests/snmp/memory.py

Summary:
snmp memory load failure on KVM
```
18/03/2025 21:56:12 test_snmp_memory.test_snmp_memory_load   L0154 INFO   | SNMP Free Memory: 145144
18/03/2025 21:56:12 test_snmp_memory.test_snmp_memory_load   L0155 INFO   | DUT Free Memory: 127512
18/03/2025 21:56:12 test_snmp_memory.test_snmp_memory_load   L0156 INFO   | Difference: 12.147935843024857% (threshold: 8%)
```
Modify the memory.py script to avoid memory usage
Local test

update snmp memory script

---

tests/generic_config_updater/test_dynamic_acl.py

This PR fixes generic_config_updater/test_dynamic_acl.py tests for isolated topologies without portchannels
Summary:
Manually tested

Fix generic_config_updater/test_dynamic_acl.py on isolated topologies

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
'isolated' topology doesn't support warm/fast reboot. skip the test case.
'isolated' topology doesn't support warm/fast reboot. skip the test case.
skip it.
verified on physical testbed.

skip test_bgp_slb advanced reboot for isolated topo

---

tests/run_tests.sh

Fixing the issue of 
https://github.com/sonic-net/sonic-mgmt/issues/17588

syntax error fix

---

tests/common/plugins/conditional_mark/__init__.py

Previously, when condition evaluation failed due to a syntax error, we only logged an error message, making it difficult to identify such regressions. In this PR, we improve the code by ensuring that any syntax error in the condition will cause the test to fail, providing a clear and actionable error message.
Summary:
Previously, when condition evaluation failed due to a syntax error, we only logged an error message, making it difficult to identify such regressions. In this PR, we improve the code by ensuring that any syntax error in the condition will cause the test to fail, providing a clear and actionable error message.
In this PR, we improve the code by ensuring that any syntax error in the condition will cause the test to fail, providing a clear and actionable error …

Fail the test on condition evaluation syntax errors 

---

tests/ipfwd/test_nhop_group.py

Fixes ipfwd/test_nhop_group.py failures for th5
Summary:

Add th5 to test_nhop_group.py

---

tests/dualtor/test_standalone_tunnel_route.py

Summary:
SONiC setups zero-mac neighbor/tunnel for both `INCOMPLETE`/`FAILED` neighbors.
https://github.com/sonic-net/sonic-swss/blob/d35c1c776acdbc6deb0c6cc3cc4baead823cde2a/neighsyncd/neighsync.cpp#L128-L140
This PR is to correct the neighbor state check.
Check the neighbor is either in `INCOMPLETE` or `FAILED`
```
dualtor/test_standalone_tunnel_route.py::test_standalone_tunnel_route[active-standby] PASSED                     [ 50%]
dualtor/test_standalone_tunnel_route.py::test_standalone_tunnel_route[active-active] SKIPPED (Skip cable type
'active-active')                                                                                                 [100%]
=================================================== warnings …
```

[test_standalone_tunnel_route] Correct the expected neighbor states

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/qos/files/cisco/qos_param_generator.py
tests/qos/test_qos_sai.py
tests/saitests/py3/sai_qos_tests.py

Summary:
Double commit https://github.com/sonic-net/sonic-mgmt/pull/13262

[202411] Add testcase testQosSaiXonHysteresis for cisco platform

---

tests/qos/files/cisco/qos_param_generator.py
tests/qos/files/qos_params.gb.yaml
tests/qos/qos_helpers.py
tests/qos/qos_sai_base.py
tests/qos/tunnel_qos_remap_base.py

Summary:
This is do manually cherry-pick for PR #17009

[202411] Cherry-pick PR 17009 - Cisco PCBB use param gen

---

ansible/library/generate_golden_config_db.py

Summary: The previous PR #17024 changed the image version checking for BMP feature and provided a new API for overwriting features config in golden_config_db.json. However, the implementation was problematic and broke the setup for multi-asic virtual chassis.

Fix the generate_golden_config_db for multi-asic devices

---

tests/common/helpers/pfc_storm.py
tests/common/helpers/pfcwd_helper.py
tests/pfcwd/test_pfcwd_all_port_storm.py
tests/pfcwd/test_pfcwd_cli.py
tests/pfcwd/test_pfcwd_function.py
tests/pfcwd/test_pfcwd_timer_accuracy.py
tests/pfcwd/test_pfcwd_warm_reboot.py

Cherry pick #15980
Summary:
Cherry pick #15980

[202411][PR: 15980]Support pfcwd tests on KVM with partial configuration coverage

---

.azure-pipelines/pr_test_skip_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml
tests/qos/test_ecn_config.py
tests/qos/test_pfc_counters.py
tests/qos/test_qos_dscp_mapping.py
tests/qos/test_tunnel_qos_remap.py

[202411][PR: 16157] Support qos test in KVM testbed and skip fanout config and traffic test

---

tests/snappi_tests/ecn/test_dequeue_ecn_with_snappi.py
tests/snappi_tests/ecn/test_red_accuracy_with_snappi.py
tests/snappi_tests/pfc/test_global_pause_with_snappi.py
tests/snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py
tests/snappi_tests/pfcwd/test_pfcwd_burst_storm_with_snappi.py
tests/snappi_tests/pfcwd/test_pfcwd_m2o_with_snappi.py
tests/snappi_tests/pfcwd/test_pfcwd_runtime_traffic_with_snappi.py

Summary:
Fixes # (issue) Cherry-pick #17472 as conflict

[202411][Cherry-pick] Conflict resolve 17472

---

tests/auditd/test_auditd.py

Summary: fix compatibility curl issue in 202311 OSVersion
`"stderr_lines": ["curl: option --fail-with-body: is unknown"`
fix compatibility curl issue in 202311 OSVersion
`"stderr_lines": ["curl: option --fail-with-body: is unknown"`
Remove the `--fail-with-body`

auditd: fix curl command

---

tests/common/plugins/sanity_check/__init__.py

Summary:
This PR is to accelerate the sanity_check by calling nbrhosts lazily.
Fixture `nbrhosts` is called in each `sanity_check`, which connect all neighbors and save the instances in a list. 
However, the instances are not used until there is `sanity_check` failure.
So, making the connection is useless for most scenarios.
- Before this change, `test_bgp_facts` costs around `469.76` seconds to finish on a T1-LAG platform.
- After this change, `test_bgp_facts` costs around `184.69` seconds to finish on a T1-LAG platform.
So, it's a 60% improvement!
This PR is to accelerate the sanity_check by calling nbrhosts lazily.
Calling `nbrhosts` lazily.
The change is verified by running `test_bgp_facts.py` on a T1-LAG platform.
No.

[SONiCMgmtBoost] Improve sanity_check by calling nbrhosts lazily

---

ansible/library/reduce_and_add_sonic_images.py

Summary:
Monitor image size 
Get image size during installing image
// SONiC-OS-20220531.52
"dockerfs": 353373269,
"downloaded_image_version": "SONiC-OS-20220531.52",
"image_size": 968080035,
"squashfs": 575938560
// SONiC-OS-20230531.40
"docker_dir": 973835329,
"downloaded_image_version": "SONiC-OS-20230531.40",
"image_size": 664367842,
"squashfs": 349605888

[reduce_and_add_sonic_images] get image size during installing image

---

tests/common/cache/facts_cache.py
tests/common/devices/duthosts.py
tests/common/devices/sonic.py
tests/common/dualtor/__init__.py
tests/common/dualtor/data_plane_utils.py
tests/common/dualtor/dual_tor_mock.py
tests/common/dualtor/dual_tor_utils.py
tests/common/dualtor/icmp_responder_control.py
tests/common/dualtor/mux_simulator_control.py
tests/common/dualtor/nic_simulator_control.py
tests/common/fixtures/advanced_reboot.py
tests/common/fixtures/duthost_utils.py
tests/common/fixtures/fib_utils.py
tests/common/fixtures/ptfhost_utils.py
tests/common/gu_utils.py
tests/common/helpers/dut_utils.py
tests/common/helpers/portchannel_to_vlan.py
tests/common/helpers/tacacs/tacacs_helper.py
tests/common/ixia/ixia_fixtures.py
tests/common/multibranch/cli/auto_techsupport.py
tests/common/pkt_filter/filter_pkt_in_buffer.py
tests/common/plugins/custom_fixtures/__init__.py
tests/common/plugins/memory_utilization/memory_utilization.py
tests/common/plugins/sanity_check/checks.py
tests/common/snappi_tests/snappi_fixtures.py
tests/conftest.py

Summary:
In pre-commit, we were using # noqa to ignore failures/errors/warnings in our code, but once we use # noqa, it will ignore all pre-commit errors in this line, the correct solution is using # noqa: so only specific failures/errors/warnings would be ignored.
Replace # noqa with # noqa: in tests common files

[pre-commit] Use correct comment format # noqa: not # noqa in tests common files

---

tests/platform_tests/cli/test_show_chassis_module.py

Summary:
Verifies the scenario when the `show chassis module` output is not the same after the `systemctl restart docker` command on the supervisor node of T2 topology.
To verify if the chassis module status remains сonsistent after docker restart
Implement new TC.
Run the `platform_tests/cli/test_show_chassis_module.py::test_show_chassis_module_status_after_docker_restart` TC.
```
platform_tests/cli/test_show_chassis_module.py::test_show_chassis_module_status_after_docker_restart
------------------------------------------------------------------------------------ live log setup ------------------------------------------------------------------------------------
15:52:58 test_show_chassis_module.test_show_chass L0112 INFO   | Get initial chassis module status on the …
```

[t2][chassis] Add new TC to verify if the chassis module status remains сonsistent after docker restart

---

tests/dualtor_io/test_link_failure.py
tests/dualtor_io/test_tor_failure.py

Summary:
Let's collect the syslog for the reload/reboot cases.
Run `loganalyzer` without analyze.
Run on dualtor testbed.

[dualtor_io] Collect syslog to debug

---

tests/bgp/test_startup_tsa_tsb_service.py

Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/17128
Issue details in https://github.com/sonic-net/sonic-mgmt/issues/17128
Wrote a testcase to catch such issue in future
Restart the startup_tsa_tsb service multiple times with varying intervals and validate its behavior at each step. 
Execute the new testcase on a multi-asic linecard setup
NA
T2

TSA-TSB Multi-Asic LC Race Condition: New testcase

---

tests/auditd/test_auditd.py

Summary: change from port 8080 to port 50058

auditd: fix http port

---

.azure-pipelines/run-test-elastictest-template.yml
azure-pipelines.yml

Summary:
In current PR test, we are using hard code "master" for MGMT_BRANCH param, it would increase difficulty when we create a new release branch. For example, in current 202411 branch, the MGMT_BRANCH param was set to "master", which is incorrect.
1.Set MGMT_BRANCH to $(BUILD_BRANCH) in PR test, then request cherry-pick to 202411 branch.
2.Add blank space in SPECIFIC_PARAM to resolve vs code yaml format extension error.
3.Do not use system defined if condition to get MGMT_BRANCH

Set mgmt branch to build branch in PR test

---

.azure-pipelines/run-test-elastictest-template.yml
azure-pipelines.yml

Summary:
In current PR test, we are using hard code "master" for MGMT_BRANCH param, it would increase difficulty when we create a new release branch. For example, in current 202411 branch, the MGMT_BRANCH param was set to "master", which is incorrect.
1.Set MGMT_BRANCH to $(BUILD_BRANCH) in PR test, then request cherry-pick to 202411 branch.
2..Do not use system defined if condition to get MGMT_BRANCH

[202411] Set mgmt branch to build branch in PR test

---

tests/common/helpers/dut_utils.py
tests/show_techsupport/test_auto_techsupport.py
tests/srv6/conftest.py
tests/srv6/srv6_utils.py
tests/srv6/test_srv6_dataplane.py

Test coverage:
1.Cover DIP shift function
2.Cover uSID container copy and segment left reduce function 
3.Cover USD function including pipe mode 
4.Cover Config reload / cold reboot
5.Cover SAI SDK dump validation
After synced with Changrong Wu, we agreed to merge this script into the tests/srv6/test_srv6_dataplane.py
Summary:
Implement the data plane test script for SRv6 function
Implement the data plane test script for SRv6 function and merge with the tests/srv6/test_srv6_dataplane.py.

Add SRv6 data plane test script

---

ansible/testbed_renumber_vm_topology.yml

Add an inventory check for DUT in restart-ptf case

---

tests/bfd/test_bfd.py

Reverts sonic-net/sonic-mgmt#12642 to resolve issue https://github.com/sonic-net/sonic-mgmt/issues/14087

Revert "Test case for BFD echo-mode"

---

tests/common/helpers/dut_utils.py

Remove a redundant blank space introduced by  https://github.com/sonic-net/sonic-mgmt/pull/15868
Summary:
Remove a blank space introdcued by PR: https://github.com/sonic-net/sonic-mgmt/pull/15868
Remove the blank space
Run CRM tests
Any

Remove a redundant blank space in dut_utils.py

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Summary:
test_ser is not supported in 720DT
Skip it without checking issue status
Run test

[720DT] Skip test_ser for 720DT

---

tests/common/helpers/dut_utils.py

Summary:
Fix a bug that was involved by the PR: https://github.com/sonic-net/sonic-mgmt/pull/15868
```
failed on setup with "tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
failed = True
changed = True
rc = 1
cmd = docker cp syncd: /tmp/sai_sdk_dump_before_shutdown_vlan_ports  /tmp/sai_sdk_dump_before_shutdown_vlan_ports
start = 2025-03-31 05:16:11.844772
end = 2025-03-31 05:16:11.859875
delta = 0:00:00.015103
msg = non-zero return code
invocation = {'module_args': {'_raw_params': 'docker cp syncd: /tmp/sai_sdk_dump_before_shutdown_vlan_ports  /tmp/sai_sdk_dump_before_shutdown_vlan_ports', '_uses_shell': True, 'warn': False, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'chdir': None, 'executable': None, 'creates': …
```

[Fixbug]: Remove an extra space during docker cp syncd

---

tests/generic_config_updater/test_eth_interface.py
tests/generic_config_updater/test_portchannel_interface.py

Summary:
Conflict resolution for PR https://github.com/sonic-net/sonic-mgmt/pull/16642 so that can allow this change to be added in 202411.
Cherry-picked commits e46739d, 92b2b3d.
Ran in vs-kvm t0 the affected suites. All tests passed.

[202411] Conflict resolution for Replacing hardcoded values for GCU suites with dynamic calculated

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py

Summary:
Add hwsku Arista-7060X6-64PE-B-C512S2 and Arista-7060X6-64PE-B-C448O16 into sonic-mgmt 
Fix couldn't find interface error during add-topo:
Run add-topo on physical testbed, not seeing interface errors anymore.

Add hwsku Arista-7060X6-64PE-B-C512S2 and Arista-7060X6-64PE-B-C448O16 in sonic-mgmt

---

tests/container_upgrade/container_upgrade_helper.py
tests/container_upgrade/parameters.json
tests/container_upgrade/testcases.json

Summary:
We need to verify gnmi feature after container upgrade
And gnmi and gnmi_watchdog to container upgrade
Run container upgrade pipeline

[KubeSonic] Add gnmi to container_upgrade

---

tests/common/utilities.py
tests/performance_meter/config/sample_test_config
tests/performance_meter/config/sample_test_reboot_by_cmd
tests/performance_meter/conftest.py
tests/performance_meter/success_criteria.py
tests/performance_meter/test_performance.py

Add checking for swss create switch criteria for performance_meter tests
Summary:
Need check for checking time spent in swss create switch
Add new success criteria to check for occurrence of swss create switch start and end
Run test on 7215 devices

[performance_meter] add swss create time criteria

---

ansible/roles/mcx/templates/incremental_mcx_config.j2
ansible/roles/mcx/templates/mcx_config.j2

Fix small bug with mcx templates. iteritems used to work and now it does not. 
Summary:
Fix a none working mcx deployment script.
Fix iteritems
Deploy mcx with new script

[mcx] fix bug with mcx deployment script

---

tests/qos/files/cisco/qos_param_generator.py

Summary:
Separated VOQ'ing is enabled on specific Cisco-8000 hwskus. 
Encode test to expect these platforms. 
Fixes several cases where GB asics are expecting the wrong configuration. 
Alternative solution here would be to auto-detect which platform is running separate vs shared voq'ing, however this would take away some of the value of the test since the configuration could be swapped incorrectly and the test would just adapt to match rather than flagging an issue. 
Validated on Platform/hwsku:
- x86_64-8101_32fh_o-r0/Cisco-8101-32FH-O (shared VOQ)
- x86_64-8101_32fh_o-r0/Cisco-8101-O8C48 (separate VOQ)
Cisco-specific test case.

Cisco update to lossy queue voq test expectations

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Reverts sonic-net/sonic-mgmt#17776

Revert "Skip test_vnet_decap on Cisco-8000 with 202411"

---

ansible/module_utils/port_utils.py

Summary:
Add new hwsku Cisco-8101-V64
The 'port_utils.py' file was consistent with the 'port_config.ini' on the device.

add hwsku Cisco-8101-V64

---

tests/qos/qos_sai_base.py

Update QoS sai test accoding to the PR:  https://github.com/sonic-net/sonic-buildimage/pull/22067
Summary:
Update qos for SN56xx buffer configuration alignment 
Update qos sai test 
Run Qos sai tests on SN56xx platform
SN56xx

[Mellanox] Update qos sai test for SN56xx buffer configuration alignment 

---

sdn_tests/pins_ondatra/.bazelrc
sdn_tests/pins_ondatra/bazel/BUILD.gmp.bazel
sdn_tests/pins_ondatra/bazel/BUILD.jsoncpp.bazel
sdn_tests/pins_ondatra/bazel/BUILD.libprotobuf_mutator.bazel
sdn_tests/pins_ondatra/bazel/BUILD.otg-models.bazel
sdn_tests/pins_ondatra/bazel/BUILD.z3.bazel
sdn_tests/pins_ondatra/bazel/patches/gnmi.patch
sdn_tests/pins_ondatra/bazel/patches/ondatra.patch
sdn_tests/pins_ondatra/infrastructure/thinkit/BUILD.bazel
sdn_tests/pins_ondatra/infrastructure/thinkit/ondatra_generic_testbed.h
sdn_tests/pins_ondatra/infrastructure/thinkit/ondatra_generic_testbed_fixture.cc
sdn_tests/pins_ondatra/infrastructure/thinkit/ondatra_generic_testbed_fixture.h
sdn_tests/pins_ondatra/infrastructure/thinkit/ondatra_generic_testbed_fixture_test.cc
sdn_tests/pins_ondatra/infrastructure/thinkit/ondatra_mirror_testbed.h
sdn_tests/pins_ondatra/infrastructure/thinkit/ondatra_mirror_testbed_fixture.cc
sdn_tests/pins_ondatra/infrastructure/thinkit/ondatra_mirror_testbed_fixture.h
sdn_tests/pins_ondatra/infrastructure/thinkit/ondatra_params.cc
sdn_tests/pins_ondatra/infrastructure/thinkit/ondatra_params.h
sdn_tests/pins_ondatra/infrastructure/thinkit/thinkit.cc
sdn_tests/pins_ondatra/infrastructure/thinkit/thinkit.go
sdn_tests/pins_ondatra/infrastructure/thinkit/thinkit.h
sdn_tests/pins_ondatra/pins_deps.bzl
sdn_tests/pins_ondatra/tests/thinkit/BUILD.bazel
sdn_tests/pins_ondatra/tests/thinkit/arbitration_test.cc
sdn_tests/pins_ondatra/tests/thinkit/arriba_test.cc
sdn_tests/pins_ondatra/tests/thinkit/configure_mirror_testbed_test.cc
sdn_tests/pins_ondatra/tests/thinkit/random_blackbox_events_test.cc

Keyword Check:
/sonic-mgmt/sdn_tests/pins_ondatra$ ~/tools/keyword_checks.sh .
Keyword check Passed.
Build result:
/sonic-mgmt/sdn_tests/pins_ondatra$ bazel build ...
INFO: Analyzed 19 targets (5 packages loaded, 13 targets configured).
INFO: Found 19 targets...
INFO: Elapsed time: 2.422s, Critical Path: 0.15s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action

[ondatra] Add ThinKit-on-Ondatra support/tests.

---

tests/snmp/test_snmp_interfaces.py

Optimize the `snmp/test_snmp_interfaces.py` test to reduce the running time on multi-asic devices.
Summary:
Fixes # (issue) Microsoft ADO 32181200
The running time of the `snmp/test_snmp_interfaces.py` test is too long on multi-asic devices (~130 min on a T2 device). The reason is that it will call `get_snmp_facts()` to get `snmp_facts` multiple times if it's a multi-asic device due to the `enum_asic_index` fixture. This is unnecessary because we only care about `snmp_facts["snmp_interfaces"]` and its value won't change in the entire test. Therefore, we can simply call it once and use it for all ASICs. 
I ran the updated code on T2 topo and can confirm it's working well: https://elastictest.org/scheduler/testplan/67fc8b281b14df63e35b863a. The running time has decreased from ~130 min to …

refactor: optimize snmp intf test for multi-asic

---

tests/iface_namingmode/test_iface_namingmode.py

Summary:
Fixes #17595
test_show_lldp_table sometimes fails because of missing lldp entry from interface flapped in test_config_interface_state
Add an assert wait_until for lldp neighbor coming back before proceeding in test_config_interface_State
T0: [Test plan 67da932be946313de56c8bd5: ifacenamingmode changes regression test T0 - Elastictest (elastictest.org)](https://elastictest.org/scheduler/testplan/67da932be946313de56c8bd5)
T1: [Test plan 67db4c7f2d7dcfaa9d43f859: ifacenamingmode changes regression test T1 - Elastictest (elastictest.org)](https://elastictest.org/scheduler/testplan/67db4c7f2d7dcfaa9d43f859)
T2: [Test plan 67da9530e3ea980065c43a91: ifacenamingmode changes regression test T2 - Elastictest (elastictest.org)](https://elastictest.org/scheduler/testplan/67da9530e3ea980065c43 …

test_iface_namingmode - Ensure LLDP neighbor comes back after link flap

---

.azure-pipelines/test_plan.py

Summary:
Due to historical reason, test plan type is designed to either nightly or pr. But there are other types of test plan, baseline, recover and custom test.
But from az pipline, there are only 3 type: nightly, pr or baseline. This PR fill trigger type by the test plan type and build reason.
This will help to categorize the test plan.
- Add trigger type.
- Add repo name and branch name to PR test plan
New filed is already ready but always null, no impact.
New pipeline will fill the filed.
Manually set build reason to simulate baseline test.
https://dev.azure.com/mssonic/build/_build/results?buildId=813692&view=logs&j=c4781836-bf04-5f60-aed4-f5b1830934f2&t=0a02131c-cb1d-58ae-2efd-7b654448dcb1

[CI]Add trigger type for test plan creation, add source repo and branch to test plan name

---

tests/bgp/test_bgp_queue.py

Summary:
- Split the original PR https://github.com/sonic-net/sonic-mgmt/pull/17130 into individual PRs for each test.
- Skip internal neighbors for both VOQ single dut multi-asic as well as multi-dut multi-asic.

[PR#17130] - BGP Queue - Changes for VOQ single-dut multi-asic

---

tests/dash/configs/privatelink_config.py
tests/dash/proto_utils.py
tests/dash/test_dash_privatelink.py

Summary:
Add meter class, policy, rule config to Dash PrivateLink tests
Test case improvement
Add additional configurations to test cases to cover metering in Dash Privatelink scenario
Smartswitch testbed only

Add Dash meter class, policy, rule config to PL tests

---

docs/testplan/srv6/SRv6-static-ptf-testplan.md

Summary: This is a joint proposal from Microsoft and Nvidia to present a test plan for static SRv6 functionality in SONiC. The HLD doc for static SRv6 can be found in https://github.com/sonic-net/SONiC/blob/master/doc/srv6/srv6_static_config_hld.md.

[Test Plan]Static SRv6 test plan

---

tests/common/helpers/upgrade_helpers.py
tests/common/platform/device_utils.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/upgrade_path/test_multi_hop_upgrade_path.py
tests/upgrade_path/test_upgrade_path.py

Summary:
Fixes #17078
Create testcase for cold upgrade for T2
Add test_upgrade_path_t2 testcase to test_upgrade_path.py based on previous upgrade path tests
Ran on multiple T2 devices, also ran on T1 warm upgrade to make sure it's not breaking
N/A
N/A
Please run using variables:
- --upgrade_type=cold
- --base_image_list=<FROM IMAGE URL> 
- --target_image_list=<TO IMAGE URL>
e.g.
```
sudo ./run_tests.sh -i <INV FILE> -n <TB NAME> -m individual -l INFO -e '--showlocals --assert plain -rav --enable_cpa --upgrade_type=cold --skip_sanity --base_image_list=<FROM IMAGE URL> --target_image_list=<TO IMAGE URL>' -u -c upgrade_path/test_upgrade_path.py::test_upgrade_path_t2
```

Test upgrade path t2

---

ansible/config_l1_testbed.yml
ansible/config_sonic_basedon_testbed.yml
ansible/l1_port_mapper.py

Summary: Testbed feature ask -> Add an L1 switch port allocator on dynamic testbeds. Automates dynamic port shuffling between traffic generators and switch ports to accommodate limited traffic generator interfaces during test runs. This adds an Ansible script and supporting Python utility to parse link mappings and reconfigure L1 switch connections based on testbed inputs. Helps streamline automated test workflows by programmatically managing port connectivity.
Example csv template:
```
StartDevice,StartPort,EndDevice,EndPort,BandWidth
switch1,Ethernet1,l1-switch,P1,100000
switch1,Ethernet2,l1-switch,P2,100000
...
StartDevice,StartPort,EndDevice,EndPort,BandWidth
tgen1,P1,l1-switch,P3,100000
tgen1,P2,l1-switch,P4,100000
...
StartDevice,StartPort,EndDevice,EndPort,BandWidth,VlanID,VlanMode …
```

[L1] L1 switch port allocator on dynamic testbeds

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/generic_config_updater/test_multiasic_addcluster.py
tests/generic_config_updater/util/generate_patch.py

Summary:
This PR updates the test_add_cluster logic to ensure it is skipped for platforms that are not multi-ASIC and have a non-Nokia HWSKU. Previously, the test was only skipped for Nokia HWSKUs, which was not correct.
Enhanced verification for applied configurations. This change introduces checks for additional database tables and implements a comparison of the configuration state before and after changes are applied.
1. Add correct condition to skip unverified platform and hwsku.
2. Enhanced verification
1. Skip test_add_cluster when the platform is not multi-ASIC and the HWSKU is not Nokia.
2. Enhanced verification.
1. Fix Skip Condition
2. Enhanced verification

Fix Add Cluster Skip condition and add everflow check.

---

tests/container_upgrade/container_upgrade_helper.py
tests/container_upgrade/parameters.json
tests/gnmi/helper.py

Summary:
Current container_upgrade test does not support existing containers.
Add new steps:
1. Disable feature.
2. Download docker images and run docker.
Run container_upgrade test and check test result.

Support upgrading existing containers

---

.azure-pipelines/impacted_area_testing/calculate_instance_number.py
.azure-pipelines/impacted_area_testing/constant.py
azure-pipelines.yml

Previously, we capped the maximum number of instances for each PR checker at 25. However, due to increased demand and other factors, this limit has become insufficient, leading to run times exceeding 3 hours. This PR raises the limit to 40 instances to address the issue.
Summary:
Previously, we capped the maximum number of instances for each PR checker at 25. However, due to increased demand and other factors, this limit has become insufficient, leading to run times exceeding 3 hours. This PR raises the limit to 40 instances to address the issue.
This PR raises the limit to 40 instances to address the issue.

Increase instance limit to reduce PR checker running time. 

---

docs/tests/add-new-PR-checkers.md

In this PR, we add a doc to introduce the steps to add a new PR checker. 
Summary:

Add a doc to introduce the steps to add a new PR checker. 

---

tests/telemetry/telemetry_utils.py
tests/telemetry/test_telemetry_poll.py

Summary:
MS# 32227981
Add test case for fix done for APPL_DB poll mode change in https://github.com/sonic-net/sonic-gnmi/pull/375
Add poll mode testcases for APPL_DB including default route test
Ran sonic-mgmt testcase

Add telemetry APPL_DB POLL mode tests

---

tests/common/fixtures/advanced_reboot.py
tests/common/fixtures/consistency_checker/consistency_checker.py
tests/common/fixtures/consistency_checker/constants.py
tests/common/fixtures/consistency_checker/query-asic/parser.py
tests/common/fixtures/consistency_checker/query-asic/query-asic.py
tests/platform_tests/args/advanced_reboot_args.py
tests/platform_tests/test_advanced_reboot.py
tests/upgrade_path/test_upgrade_path.py

Summary:
This is a manual backport of the consistency-checker utility from master at commit f2cadae6. This includes the following two PR's:
- https://github.com/sonic-net/sonic-mgmt/pull/14402
- https://github.com/sonic-net/sonic-mgmt/pull/16877
Manually backported due to conflicts.
There were conflicts in creating cherry-pick backport PR's hence this manual approach.
Cherry-picked the changes from the two PR's and resolved conflicts.
Ran test_upgrade_path and test_advanced_reboot.py on this branch. The feature in general has also been tested thoroughly on master.

Port consistency checker to 202305 (f2cadae6)

---

tests/common/dualtor/data_plane_utils.py
tests/common/dualtor/dual_tor_io.py
tests/dualtor_io/test_link_failure.py

Reverts sonic-net/sonic-mgmt#17909

Revert "[dualtor_io] Allow duplications for link down downstream I/O"

---

tests/acl/test_stress_acl.py

In the test case, the selected destination ports are uplink ports, and the dst ip for the test is using the "10.0.0.1", in the t1-isolated-d28u1, the 10.0.0.1 is the ip of the downlink, so the test will fail since it expect the traffic could be received on the uplink.
Summary:

Align stress acl test for the t1-isolated-d28u1 topo

---

tests/voq/test_voq_ipfwd.py

This PR fixes https://github.com/sonic-net/sonic-mgmt/issues/18166 .
Summary:
https://github.com/sonic-net/sonic-mgmt/issues/18166
- [ x] Bug fix

Fix IndexError seen in voq/test_voq_ipfwd

---

ansible/vars/configdb_jsons/7nodes_cisco/PE1.json
ansible/vars/configdb_jsons/7nodes_cisco/PE2.json
ansible/vars/configdb_jsons/7nodes_cisco/PE3.json

Add SRV6_MY_SOURCE config for srv6 vpn tests
Summary:

Add SRV6 tunnel source config for srv6 tests

---

tests/auditd/test_auditd.py

Summary:
This is for change Non NOKIA SKU's auditd rules checksum since we introduced two rules change
1. https://github.com/sonic-net/sonic-buildimage/pull/22395
1. https://github.com/sonic-net/sonic-buildimage/pull/22455

Modify auditd rules checksum

---

tests/dash/configs/privatelink_config.py

Fix IP version in the DASH meter test

Fix DASH meter test IP version

---

ansible/library/sensors_facts.py

Summary: 
Handles invalid data format in sensors files.
Handles cases when a device has no sensors. For example, 
```
...
PMIC-2 VDD_T1 Rail Curr (out2):
curr3_input: 12.750
curr3_max: 32.000
curr3_lcrit: 1.000
curr3_crit: 36.000
curr3_alarm: 0.000
00000400400-mdio-4
mp2891-i2c-5-6c
PMIC-10 PSU 13V5 Rail (in1):
in1_input: 12.594
in1_lcrit: 0.000
in1_crit: 16.000
in1_alarm: 0.000
...
```
where `00000400400-mdio-4` has no sensors
Add missing handling for invalid senors files format and missing sensors
Check values for None
Add try/except during cast values to float
Run sensors test with missing sensors/invalid data in files

fix for missing sensors in sensors_facts.py

---

tests/container_upgrade/container_upgrade_helper.py

Summary:
fix k8s integration issue
add missed bmp container mapping
changed internal branch manually and verified via container_upgrade pipeline
N/A
N/A

fix k8s integration issue

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/qos/test_qos_sai.py

Summary: Support Arista-7050CX3-32S-C28S4 in sonic-mgmt
Support Arista-7050CX3-32S-C28S4 in sonic-mgmt
The changes are from extending Arista-7050CX3-32S-C32

Support Arista-7050CX3-32S-C28S4 in sonic-mgmt

---

tests/acl/test_acl.py
tests/acl/test_stress_acl.py

noqa replaced with noqa: in /test/acl folder with precommit changes

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
adding these 6 TCs in hash/test_generic_hash.py as skip in test_condition_mark.yaml
hash/test_generic_hash.py::test_lag_member_flap[CRC-IP_PROTOCOL-ipv4-None-None]
hash/test_generic_hash.py::test_lag_member_flap[CRC_CCITT-IP_PROTOCOL-ipv4-None-None]
hash/test_generic_hash.py::test_lag_member_remove_add[CRC-IP_PROTOCOL-ipv4-None-None]
hash/test_generic_hash.py::test_lag_member_remove_add[CRC_CCITT-IP_PROTOCOL-ipv4-None-None]
hash/test_generic_hash.py::test_reboot[CRC-IP_PROTOCOL-ipv4-None-None-cold]
hash/test_generic_hash.py::test_reboot[CRC_CCITT-IP_PROTOCOL-ipv4-None-None-cold]
to skip mentioned testcases in hash/test_generic_hash.py, reason being : With IP Protocol alone, we don't have enough entropy to distribute the packets evenly
adding skip reasons and conditions for six …

skip 6 TCs for test_generic_hash.py for cisco-8000 (IP_PROTOCOL entropy)

---

tests/templates/dual_tor_sniffer.conf.j2

Summary:
Use `python3` explicitly for `dual_tor_sniffer`
Run dualtor io test.

[dualtor][sniffer] Use python3

---

ansible/library/announce_routes.py

Summary:
This PR adds support for announcing routes from LT2 to FT2.
- LT2 announces default route to FT2
- The total number of routes on FT2 is 16K IPv4 + 16K IPv6
This PR is to add support for announcing routes from LT2 to FT2.
Update `announce_routes` script.
The change is verified by running `announce-routes` with command  ` ./testbed-cli.sh announce-routes testbed_name password.txt`.
```
=============================================================================== 
Configure exabgp processes for IPv4 on PTF ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 18.65s
configure exabgp processes for IPv6 on PTF …
```

Support announcing routes from LT2 to FT2

---

tests/snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py

Summary:
Added explanation to the PFCWD all-to-all testcase. 
@vmittal-msft , @rawal01 , @yatishkoul , @sdszhang for viz.
Fixes #18216 
There was one line description of the test case and needed more explanation about the what the testcase intended to do.
Added documentation.
No verification needed as this is added as comments in the test-case description.

[Snappi][Documentation] : Added test documentation for snappi-pfcwd all-to-all testcase

---

tests/route/test_route_flap.py

Fixes: https://github.com/sonic-net/sonic-mgmt/issues/18356
`test_route_flap.py` checks for routes to be announced and withdrawn after waiting for 1 sec, which makes it fail intermittently when route announcement/withdrawal takes more than 1 sec. I found that if we give a little more time, the waiting condition gets satisfied (i.e. route gets correctly announced). Replacing the 1 sec sleep with a wait_until condition with 20 sec timeout.
Summary:
Fix `test_route_flap.py` by calling `check_route` in `wait_until` instead of a hard-coded 1 sec sleep
Failure earlier:
```
=============================================================================================================================== warnings summary ================================================================= …
```

Make test_route_flap.py call check_route in wait_until instead of 1 sec sleep

---

tests/route/test_route_perf.py

Summary:
This change enhances the `check_config` fixture in test_route_perf.py to support TH5 platforms in Broadcom (e.g., x86_64-arista_7060x6_64pe and x86_64-arista_7060x6_64pe_b) where the `l3_alpm_template` value is configured in the config.bcm file instead of being queried via `bcmcmd`.
TH5 devices manage ALPM configuration through config.bcm, and bcmcmd does not reflect runtime ALPM mode (l3_alpm_template) for them. Test case route/test_route_perf.py::test_perf_add_remove_routes would failed on TH5 platforms because it didn't support get ALPM configuration from bcm shell.
- Added `get_l3_alpm_template_from_config_bcm()` helper to locate and copy the config.bcm file to /tmp and parse and retrieve the value of `l3_alpm_template`.
- Update the `check_config` fixture to …

[route/test_route_perf] Support reading l3_alpm_template from config.bcm for TH5 platforms

---

ansible/library/announce_routes.py

Summary: Added support for announce routes LT2 layers. Announcing 16000 routes each IP type for T1 layers. 
Fixes # (issue) 32508563
Support announce route for LT2. We want to announce 16000 IPv4 and 16000 IPv6. For UT2 we want to announce the default route
Update the script to announce the routes based on the topology type
Tested on physical testbed LT2, will announce 16170 (147 x 110T1) IPv4 and 16170 IPv6 (147 x 110T1). Default route for both ipv4 and ipv6 is announced on UT2
No

Add lt2 announce route

---

docs/testplan/BGP-Dynamic-Peer-Range-Modify.md

This PR outlines the test plan for dynamic peer IP range modification feature.
Summary:

Testplan for dynamic peer ip range modification

---

tests/sflow/test_sflow.py

…channel
Summary: On some t0 topo, such as the t0-isolated-u16d16s1, it does not has portchannel, in such case, we need to have the get the upstream ports for the test

Update the sflow test to pass on the t0 topo which does not have portchannel

---

tests/common/dualtor/data_plane_utils.py
tests/common/dualtor/dual_tor_io.py
tests/dualtor_io/test_link_failure.py

Summary:
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/18287 into 202411

[dualtor io][202411] Allow link down duplications on MLNX/Cisco

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
`generic_config_updater/test_bgp_prefix.py::test_bgp_prefix_tc1_suite` test has low success rate in PR test
Skip test in PR test with issue https://github.com/sonic-net/sonic-mgmt/issues/18445

[gcu] Temprorily skip test_bgp_prefix_tc1_suite due to low success rate in PR test

---

tests/crm/conftest.py

Summary:
In some cases, the CRM info is not available immediately after the test startup, need to wait for some time before read it, otherwise, the test case could run into failure with. 
>           pytest.fail(f"Resource '{resource_name}' not found in CRM resources output on platform '{hwsku}'.")
E           Failed: Resource 'nexthop_group' not found in CRM resources output on platform 'force10-s6000'. 
To fix the flaky of the case due to timing issue. 
To add wait_until when read the CRM info from DUT.
Run test on platform. 
N/A
N/A

[CRM_AVAILABLE] To add delay when read the CRM info

---

tests/snappi_tests/test_multidut_snappi.py

Summary:
Update test_snappi_multidut.py to adopt the new snappi version.
To support new snappi model changes
use new API to start/stop traffic.
verified on physical testbed.

fix test_snappi_multidut.py

---

tests/copp/test_copp.py
tests/crm/test_crm.py

Changed noqa to noqa: in the files tests/copp and tests/crm

Pre-commit changes for noqa in tests/Crm and tests/copp

---

tests/dash/proto_utils.py
tests/decap/test_decap.py
tests/decap/test_subnet_decap.py

noqa replaced with noqa: in the files under tests/dash and tests/decap and pre-commit changes too.

noqa replaces with noqa: in files tests/dash and tests/decap

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
In PR https://github.com/sonic-net/sonic-mgmt/pull/18447, `generic_config_updater/test_bgp_prefix.py::test_bgp_prefix_tc1_suite` was planned to skip in vs, but PR didn't add conditions_logical_operator: "OR" so it's not actually working.
Add conditions_logical_operator: "OR" in `generic_config_updater/test_bgp_prefix.py::test_bgp_prefix_tc1_suite`

Fix gcu test_bgp_prefix conditional mark condition logical operator incorrect issue

---

ansible/roles/test/files/ptftests/py3/copp_tests.py

Adding condition check in copp for marvell-teralynx to pass test_add_new_trap case

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR template for 202505 branch
Summary:
32912687
Update PR template for 202505 branch
Update PR template for 202505 branch

[202505] Update PR template

---

azure-pipelines.yml

Summary:
Enable PR test for 202??? branches.
This won't affect master branch PR test, but when a feature branch is branched out from master branch, the PR test will be auto enabled.
Enable PR test for feature(202???) branches.
This won't affect master branch PR test, but when a feature branch is branched out from the master branch, the PR test will be auto enabled.
With this change, the PR test is enabled: https://github.com/sonic-net/sonic-mgmt/pull/18499

[PR test] Enable PR test for feature branches

---

.azure-pipelines/impacted_area_testing/get-impacted-area.yml
azure-pipelines.yml

Previously, we hardcoded `origin/master` to determine the differences between the base branch and the current branch. This approach was sufficient when the impacted area logic was only used on the master branch. However, as we now plan to support impacted area detection on additional branches, we need to replace this hardcoded reference with the actual target build branch.
Summary:
Previously, we hardcoded `origin/master` to determine the differences between the base branch and the current branch. This approach was sufficient when the impacted area logic was only used on the master branch. However, as we now plan to support impacted area detection on additional branches, we need to replace this hardcoded reference with the actual target build branch.
Change this hardcode …

Make impacted area logic branch-aware

---

tests/everflow/everflow_test_utilities.py

Summary:
- Split the original PR #17130 into individual PRs for each test.
- If T2 topo, decide based on the number of Duts.

[PR#17130] - Everflow - Changes for VOQ single-dut multi-asic

---

ansible/module_utils/port_utils.py

Summary:
update sonic-mgmt to match with the new naming convention after https://github.com/sonic-net/sonic-buildimage/pull/22577
update sonic-mgmt to match with the new naming convention after https://github.com/sonic-net/sonic-buildimage/pull/22577

update quicksilver TH5-512 port name

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py
tests/platform_tests/test_intf_fec.py

Adding support for NH-4010 platform 
Summary:
Fixes #18677 
To add support for 4010 platform
These changes were verified on Nexthops' internal sonic-mgmt testbeds.
NH-4010 is a TH5 based platform

Add support for NH-4010 platform

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py
ansible/roles/test/vars/testcases.yml
ansible/veos
ansible/veos_vtb

Changes to support new 4280 hwksus and t1-48-lag topo in sonic-mgmt

---

tests/wol/test_wol.py

WOL test error log is not very clear, difficult to identify what is expected and what is not
Summary:
Test error log is not clear
Add more to error log
Test wol test

[wol] refine test logs

---

tests/bgp/test_ipv6_bgp_scale.py

Summary:
1. The bgp scale test need to advertise/withdrawn routes on ptfhost, however currently it only support single server testbed, this PR is to make it work both on single server testbed and multiple servers testbed.
2. When send packet we should route packet to ptf_nn_agent by port index to support multi-servers testbed with multiple ptf nn agent
1. The bgp scale test need to advertise/withdrawn routes on ptfhost, however currently it only support single server testbed, this PR is to make it work both on single server testbed and multiple servers testbed.
2. When send packet we should route packet to ptf_nn_agent by port index to support multi-servers testbed with multiple ptf nn agent
Announce routes on all ptfhosts,  route packet to ptf_nn_agent by port index to …

[test case] Support multiple servers testbed in bgp scale test

---

tests/acl/test_acl.py

Adapt ACL test on M1 topo.
Verified on Arista-7050CX3 M1-48 testbed.
Summary:
Backport #18514

[202505][M1] Adapt ACL test for M1 topo (#18514)

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/http/stop_http_server.py
tests/http/test_http_copy.py

Summary:
This test was disabled due to an issue with temporary scripts being copied to the ptf container and never being cleaned up. This is resolved by adding a setup/teardown fixture that will remove those files from the ptf when the test finishes.
This issue is tracked in community here: https://github.com/sonic-net/sonic-mgmt/issues/3901
There was a proposed fix (https://github.com/sonic-net/sonic-mgmt/pull/3896) that seems to have been abandoned (review comment never got addressed and it died). I cribbed that change as the basis for this one, and added the use of tempfile.NamedTemporaryFile for a little more robust tempfile handling.
Fixes #3901
Increase test coverage.
Added a pytest fixture to handle removing the temporary files …

Issue #3901: Re-enable http/test_http_copy.py

---

tests/dualtor/conftest.py
tests/dualtor/test_ipinip.py
tests/dualtor/test_mux_port_iptables_entries.py
tests/dualtor/test_orch_stress.py
tests/dualtor/test_orchagent_active_tor_downstream.py
tests/dualtor/test_orchagent_mac_move.py
tests/dualtor/test_orchagent_slb.py
tests/dualtor/test_orchagent_standby_tor_downstream.py
tests/dualtor/test_standalone_tunnel_route.py
tests/dualtor/test_standby_tor_upstream_mux_toggle.py
tests/dualtor/test_switchover_failure.py
tests/dualtor/test_switchover_faulty_ycable.py
tests/dualtor/test_tor_ecn.py
tests/dualtor/test_tunnel_memory_leak.py

Changes made in tests/dualtor files.
1. Noqa replaced with noqa:
2. Pre-commit errors

Pre-commit errors fixed and Replaced noqa with noqa: in tests/dualtor

---

tests/dualtor_mgmt/conftest.py
tests/dualtor_mgmt/test_egress_drop_nvidia.py
tests/dualtor_mgmt/test_grpc_periodical_sync.py
tests/dualtor_mgmt/test_ingress_drop.py
tests/dualtor_mgmt/test_server_failure.py

Changes made in tests/dualtor and tests/dualtor_mgmt files.
Noqa replaced with noqa:
Pre-commit errors like Spacing issues have been fixed

Pre-commit errors fixed and Replaced noqa with noqa: in tests/dualtor_mgmt

---

ansible/module_utils/port_utils.py

Fix port mapping for new 4280 hwskus
Summary:
Fix port mapping in sonic-mgmt as per port_config.ini for these hwskus

Fix port mapping for new 4280 hwskus

---

tests/pfcwd/test_pfcwd_cli.py

Summary:
Fixes # (issue) #18279
Fix typo in log message in test_pfcwd_cli.py. 
Fixing the typo in log message, which gives wrong failure message.
Issue identified by code-walk.

Fix typo in log message in test_pfcwd_cli.py

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

DSCP Mode as UNIFORM is supported by Marvell Teralynx device, this PR aims to remove the skip condition added for marvell-teralynx and enable Decap PTF cases to validate Decap functionality in uniform mode.
To validate uniform Tunnel DSCP mode on Marvell-teralynx platform
skip condition added generic conditional markers of SONIC-mgmt is invalid and marvell-teralyx is now removed from unsupported asic-type for following two test cases,
1. decap.test_decap -> test_decap[ttl=pipe, dscp=uniform, vxlan=disable]
2. decap.test_decap -> test_decap[ttl=pipe, dscp=uniform, vxlan=set_unset]
Test Cases
with this the following 2 cases from test_decap is successful now,
1.decap.test_decap -> test_decap[ttl=pipe, dscp=uniform, vxlan=disable] :: SUCCESS
2.decap.test_decap -> test_decap[ttl=pipe, …

[Marvell-Teralynx] Enable test_decap by removing conditional markers

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
There are two two test cases failure during the internal build repo pr merge.

Remove two tests from pr checker

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
route/test_route_perf.py test has high failure rate in PR test, need to xfail with issue to unblock PR test and triage later.
Success rate change:
Xfail test with issue https://github.com/sonic-net/sonic-mgmt/issues/18893 in PR test

Xfail route perf test with issue for high failure rate in PR test

---

tests/common/plugins/memory_utilization/__init__.py
tests/common/plugins/memory_utilization/memory_utilization.py

Summary:
32970405
The memory utilization plugin operates at per test case level, it uses a pytest hook to collect the memory usage before and after each test case.
It then calculates the memory diff and compares it against a predefined threshold, if the difference exceeds the threshold, a pytest failure will be triggered.
Since "@pytest.hookimpl(tryfirst=True)", the hook will execute before all the teardown fixtures. 
This means that if the memory check fails, the hook will return failure directly, and cause an exception immediately, interrupting the tear down process, as a result, it will cause the next test case failure with following error message.
AssertionError: previous item was not torn down properly
Do not raise the failure in hook directly.
Instead, save all the …

fix memory_utilization teardown failure

---

tests/route/test_route_perf.py

Summary:
route perf test has high failure rate in PR test recently, and it was xfailed by https://github.com/sonic-net/sonic-mgmt/pull/18894#event-18070345266, the log shows current routes may not match expected routes number, but the code just continued with they are matched.
```
09/06/2025 17:00:58 test_route_perf.exec_routes              L0222 INFO   | Current 27413 expected 52999 delayed 160.126856 will delay 5.1172
09/06/2025 17:01:03 base._run                                L0071 DEBUG  | /var/src/sonic-mgmt/tests/common/devices/sonic_asic.py::shell#580: [vlab-03] AnsibleModule::shell, args=["sonic-db-cli  ASIC_DB eval \"return #redis.call('keys', 'ASIC_STATE:SAI_OBJECT_TYPE_ROUTE_ENTRY*')\" 0"], kwargs={"module_ignore_errors": true}
09/06/2025 17:01:04 base._run …
```

Add log to route perf test to address failure

---

tests/snappi_tests/test_snappi.py

Summary: Fix snappi_tests/test_snappi.py failure
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/18896
Test is failing with
```
============================================================================================== short test summary info ===============================================================================================
FAILED snappi_tests/test_snappi.py::test_snappi - AttributeError: 'Api' object has no attribute 'transmit_state'
====================================================================================== 1 failed, 1 warning in 595.57s (0:09:55) ==================================================================
```
Updating test to adopt to newer version of snappi introduced by https://github.com/sonic-net/sonic-buildimage/pull/22345 and fix is …

[sonic-mgmt] Fix snappi_tests/test_snappi.py failure

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Xfail based at  https://github.com/sonic-net/sonic-mgmt/issues/18304. Test fib_hash and test_fib_nvgre_hash are failing due to those issue.
Xfail TC until issue https://github.com/sonic-net/sonic-mgmt/issues/18304 resolved
Add xfail
Run test suite - fib hash xfailed

XFail fib hash/nvgre_hash tests based at issue 18304

---

ansible/roles/test/files/ptftests/fib_test.py
ansible/roles/test/files/ptftests/py3/hash_test.py
tests/common/helpers/ntp_helper.py
tests/gnmi/test_gnmi_appldb.py

Consolidated PR with all changes required for docker-ptf Bookworm based image. Based on these PRs for `master` -
https://github.com/sonic-net/sonic-mgmt/pull/18544
https://github.com/sonic-net/sonic-mgmt/pull/18627
https://github.com/sonic-net/sonic-mgmt/pull/18584
https://github.com/sonic-net/sonic-mgmt/pull/18583
Summary:
This change is backward compatible and is required to support running tests in docker-ptf Bookworm image.
See description
NA
NA
NA
NA

[202505] Consolidated changes for docker-ptf Bookworm based image

---

tests/route/test_duplicate_route.py

* Following changes in https://github.com/sonic-net/sonic-swss/pull/3587, test_duplicate_route.py needs to be updated accordingly.
Summary:
To unblock pipeline issues due to failed test case
By adding expected new error log
By running the same test case via pipeline and verifying that they pass
route/test_duplicate_route.py::test_duplicate_routes[4-Loopback-vlab-01-None] PASSED [ 25%]
route/test_duplicate_route.py::test_duplicate_routes[4-Vlan-vlab-01-None] PASSED [ 50%]
route/test_duplicate_route.py::test_duplicate_routes[6-Loopback-vlab-01-None] PASSED [ 75%]
route/test_duplicate_route.py::test_duplicate_routes[6-Vlan-vlab-01-None] PASSED [100%]

Fix test_duplicate_route.py as per new orchagent crash handling changes

---

tests/generic_config_updater/test_srv6.py

Summary: Add a new test case to verify that GCU update works fine for SRV6 related tables in CONFIG_DB.
Verify that GCU can applied configuration patches to CONFIG_DB on SRv6 configurations.
Add one test case to verify that GCU can be used to add/update existing SRv6 configurations in CONFIG_DB.
Add one test case to verify that GCU can be used to remove existing SRv6 configurations in CONFIG_DB.
Run on virtual/physical testbed with 202412 images.

Add a new test case for GCU update SRv6 config

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

…rnel syslog
Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/19110/ into 202411
1. `2025 Jun 14 02:28:46.206949 str2-8101-05 ERR kernel: [17800.425621] audit: rate limit exceeded`
This syslog was caused by setting rate limit and many audit syslog exceed the rate limit. Due to security, we enable audit syslog, but in some sonic-mgmt cases, it enables rate limit, so many audit syslogs could exceed the rate limit and it will print out this error. 
Confirmed with feature owner, we can ignore this error syslog to avoid teardown error for many cases.
3. `2025 Jun 12 05:51:29.810090 str2-7050cx3-acs-01 NOTICE kernel: [16041.304670] audit: type=1300 audit(1749707485.287:111698): arch=c000003e syscall=59 success=yes exit=0 a0=7f11c7911010 a1=560342061e40 …

[202411]Ignore audit rate limit exceeded syslog and avoid false alert for kernel syslog

---

tests/hash/test_generic_hash.py
tests/ip/test_mgmt_ipv6_only.py

Pre-commit Changes made in tests/hash and tests/ip.
Noqa replaced with noqa:
Pre-commit errors like Spacing issues have been fixed

Pre-commit errors fixed and Replaced noqa with noqa: in tests/hash and tests/ip

---

tests/ipfwd/test_dip_sip.py
tests/ipfwd/test_dir_bcast.py
tests/ipfwd/test_mtu.py
tests/ixia/ecn/files/helper.py
tests/ixia/ecn/test_dequeue_ecn.py
tests/ixia/ecn/test_red_accuracy.py
tests/ixia/ixanvl/test_bgp_conformance.py
tests/ixia/pfc/test_global_pause.py
tests/ixia/pfc/test_pfc_pause_lossy.py
tests/ixia/pfcwd/files/pfcwd_basic_helper.py
tests/ixia/pfcwd/files/pfcwd_multi_node_helper.py
tests/ixia/pfcwd/files/pfcwd_runtime_traffic_helper.py
tests/ixia/pfcwd/test_pfcwd_a2a.py
tests/ixia/pfcwd/test_pfcwd_basic.py
tests/ixia/pfcwd/test_pfcwd_burst_storm.py
tests/ixia/pfcwd/test_pfcwd_m2o.py
tests/ixia/pfcwd/test_pfcwd_runtime_traffic.py
tests/ixia/test_ixia_traffic.py
tests/ixia/test_tgen.py

Pre-commit Changes made in tests/ixia and tests/ipfwd.
Noqa replaced with noqa:
Pre-commit errors like Spacing issues have been fixed

Pre-commit errors fixed and Replaced noqa with noqa: in tests/ipfwd and tests/ixia

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Fixes #18848 
Skip test_traffic_shift_sup.py on t2_single_node topo
Add the skip into test_mark_conditional.yaml
Tried to run the test, making sure it skipped.
N/A
N/A
N/A

Skip test_traffic_shift_sup.py on t2_single_node topo

---

tests/ip/test_mgmt_ipv6_only.py

Summary:
Microsoft ADO: 33257886
We will enable user_auth by default, and then telemetry test will be blocked.
Set user_auth as none and restart gnmi server before the telemetry test, and recover user_auth after the telemetry test.
Run ip/test_mgmt_ipv6_only.py

Update user_auth and restart gnmi server

---

ansible/veos

Summary:
Add topo t1-isolated-d510u2 in veos
Add topo t1-isolated-d510u2 in veos
Add topo t1-isolated-d510u2 in veos
Verified by deploy topo.

[T1] Add topo t1-isolated-d510u2 in veos

---

docs/testplan/dhcp_relay/DHCP-relay-stress-test.md
docs/testplan/dhcp_relay/DHCPv4-relay-per-interface-counter-test-plan.md

Summary:
Add test plan for DHCPv4 per-interface counter

[testplan][dhcp] Add test plan for dhcpv4 per-interface counter

---

tests/common/helpers/constants.py

Summary: Fix everflow test for LT2 to works with its downstream neighbor
Fixes # (issue) 33486533
Add missing neighbors mapping for LT2 for everflow to run

[LT2] Fix everflow tests

---

ansible/module_utils/port_utils.py

Summary: 33493893
Fixes # (issue) Update Arista 7060x6 port utils based on https://github.com/sonic-net/sonic-buildimage/pull/22955/files
Update arista 7060x6 ports utils

[DT2] Update Arista 7060x6 port utils

---

tests/ipfwd/test_nhop_group.py

Summary:
Added ability to run test_nhop_group at SPC5 devices
Run test_nhop_group at SPC5
Added spc5 info block
Run test, test passed

Added spc5 to test_nhop_group

---

tests/route/test_static_route.py

Summary:
Fix test_static_route.py failure on topology with PT0 neighbor.
In topology with peer T0 neighbors, only routes matching 0.0.0.0/0 are permitted in, all other routes are denied. So the test case for verifying BGP route redistribution was failing.
Skip checking PT0 neighbor when checking route redistribution in test_static_route.py by filtering out BGP neighbors whose neighborname contains "PT0".
Run test on t0-d18u8s4 topo and all passed.
```
route/test_static_route.py::test_static_route[str4-7050cx3-c28s4-1] PASSED                                                                                                                                                                               [ 25%]
route/test_static_route.py::test_static_route_ecmp[str4-7050cx3-c28s4-1] …
```

[test_static_route] Skip PT0 neighbor when checking route redistribution

---

ansible/module_utils/port_utils.py
tests/common/helpers/constants.py

Cherry-pick the following:
- https://github.com/sonic-net/sonic-mgmt/pull/19178
- https://github.com/sonic-net/sonic-mgmt/pull/19179

[202505] cherry pick 19179 19178

---

tests/acl/templates/acltb_multi_binding_acl_table.json
tests/acl/test_acl.py

1.Add custom acl type to override default drop rule 
2.Add nic simulator toggle class level fixture
3.Apply multi binding acl at active tor tunnel rif 
4.Send packets from standby tor upstream ptf ports 
5.Validate multi binding acl counter at active tor 
6.Add condition check and skip codes for non dualtor setup 
7.Add condition check and skip codes for non multi binding acl enabled setup
Summary:
Add test coverage for multi-binding-acl function
Add the test for multi-binding-acl function

Add multi binding acl test case for dualtor topology

---

ansible/module_utils/port_utils.py

Summary:
Update the port mapping alias for Arista-7060X6-64PE-P64

feat: update port mapping for Arista-7060X6-64PE-P64

---

ansible/generate_topo.py
ansible/vars/topo_t0-isolated-d256u256s2.yml
ansible/vars/topo_t0-isolated-v6-d256u256s2.yml
ansible/vars/topo_t1-isolated-d448u15-lag.yml
ansible/vars/topo_t1-isolated-v6-d448u15-lag.yml
ansible/veos
tests/acl/test_stress_acl.py
tests/qos/qos_sai_base.py

Summary:
Update full topology for both C512S2 and C448O16 hwsku.
Update the t0-isolated-xx and t1-isolated-xx full topo
generated the topo again.

update full isolated topo for C512S2 and C448O16

---

tests/common/helpers/bgp.py
tests/gnmi/test_gnmi.py
tests/platform_tests/cli/test_show_chassis_module.py

**Summary:**
I updated the assertion statements in the following test files to include …

Added detailed reason for assert failure for bgp,gnmi,chassis_module

---

tests/bgp/test_bgp_queue.py
tests/bmp/test_bmp_statedb.py
tests/dualtor/test_orchagent_slb.py

**Summary:**
I updated the assertion statements in the following test files to include …

Added detailed reason for assert failure for bgp,bmp,dualtor

---

setup-container.sh
tests/common/plugins/conditional_mark/issue.py

[202505]manual cherry pick PR 19116 to Fix github api rate limit issue
https://github.com/sonic-net/sonic-mgmt/pull/19116

[202505]manual cherry pick PR 19116 to Fix github api rate limit issue

---

setup-container.sh
tests/common/plugins/conditional_mark/issue.py

[202411]manual cherry pick PR 19116 to Fix github api rate limit issue
https://github.com/sonic-net/sonic-mgmt/pull/19116

[202411]manual cherry pick PR 19116 to Fix github api rate limit issue

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Unskip testQosSaiHeadroomPoolWatermark on t0-d18u8s4 topology.

Unskip testQosSaiHeadroomPoolWatermark on t0-d18u8s4

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

This is a manual cherry-pick of #19287 
Unskip testQosSaiHeadroomPoolWatermark on t0-d18u8s4 topology.

[Cherry-pick][202505] Unskip testQosSaiHeadroomPoolWatermark on t0-d18u8s4

---

tests/common/mellanox_data.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/qos/qos_sai_base.py

* There are tests that are skipped on these topologies when they shouldn't be.
Summary:

Enable new tests for Nvidia smartswitch

---

ansible/roles/vm_set/templates/sonic.xml.j2

Summary: In my previous PR #19239, I incorrectly removed the CPU and memory settings for the sonic-vpp VM. Now, we should recover it.

Recover cpu and memory settings for sonic-vpp VM

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

This is a manual cherry-pick of #19287 
Unskip testQosSaiHeadroomPoolWatermark on t0-d18u8s4 topology.

[Cherry-pick][202411] Unskip testQosSaiHeadroomPoolWatermark on t0-d18u8s4 (#19287)

---

.gitignore

Summary:
There are many generated files in sai_validation folder which messes up the vscode git changes panel:
Updating the .gitignore file to make the diff clean.
Locally tested.

Update .gitignore to ignore generated sai_validation files.

---

ansible/devutil/testbed.py
ansible/ssh_session_gen.py

Summary:
With network under test (NUT) testbed being supported, the current testbed generation tool doesn't support the new type of testbed.
NUT testbed HLD: https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testbed/README.testbed.NUT.md
This PR improves the testbed session generator tool to support the new type of testbed.
Run locally and it works.

Update testbed generator to support generating NUT testbeds.

---

docs/testplan/ECMP-Balance-test-plan.md

Summary:
test plan doc for ECMP balance test, PR https://github.com/sonic-net/sonic-mgmt/pull/18255
test plan doc for ECMP balance test, PR https://github.com/sonic-net/sonic-mgmt/pull/18255

[test gap] Test plan for ECMP balance test

---

azure-pipelines.yml

Summary:
Support for release 202205 has ended. This PR disables PR pipeline triggers for the 202205 branch.
Set PR trigger to "none" in pipeline yaml file.
Verify that PR testing is not triggered for this PR.

Disable PR testing for 202205 branch

---

azure-pipelines.yml

Summary:
Support for release 202305 has ended. This PR disables PR pipeline triggers for the 202305 branch.
Set PR trigger to "none" in pipeline yaml file.
Verify that PR testing is not triggered for this PR.

Disable PR testing for 202305 branch

---

ansible/group_vars/sonic/variables

Summary:
Fix testcase failure on M1: `ipfwd/test_nhop_group.py::test_nhop_group_member_order_capability`
Fix testcase failure on M1: `ipfwd/test_nhop_group.py::test_nhop_group_member_order_capability`
Add 7050CX3 M1 HwSKU in TD3 list
Verified by testcase `ipfwd/test_nhop_group.py::test_nhop_group_member_order_capability` on M1.

[M1] Add 7050CX3 M1 HwSKU in TD3 list

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/19442 into 202505.

[dualtor] Skip warm/fast reboot cases on dualtor

---

tests/voq/test_voq_init.py

Summary:
This PR fixes issue #[372](https://github.com/Azure/sonic-mgmt.msft/issues/372)
- With the latest changes in the minigraph templates, '_speed_' information for 100G links are still showing 400G under SYSTEM_PORT configuration for config_db files.
- Topo :  T2 single node max
-  Due to which, 'test_voq_system_port_create' test under test_voq_init suite fails with the following error related to speed,
`>                   pytest_assert(dev_ports[cfg_port]['speed'] == port_data[
'speed'], "switch IDs do not match for port: %s" % portkey)
E                   Failed: switch IDs do not match for port: ASIC_STATE:SAI_OBJECT_TYPE_SYSTEM_PORT:oid:0x5d000000000024`
-  To fix 'test_voq_system_port_create' test under test_voq_init suite for the following error w.r.t speed,
`> …

[T2] [single-node-max] Fix for test_voq_system_port_create speed verification

---

ansible/group_vars/sonic/variables

Fix testcase failure on M1: ipfwd/test_nhop_group.py::test_nhop_group_member_order_capability
Add 7050CX3 M1 HwSKU in TD3 list
Verified by testcase ipfwd/test_nhop_group.py::test_nhop_group_member_order_capability on M1.
Summary:

[202505][M1] Add 7050CX3 M1 HwSKU in TD3 list (#19422)

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py

Summary:
New platform support.
- Added new hwsku to the platform variable
- Added platform specific port alias to name mapping.

[Arista] LodogaPrime platform support

---

ansible/roles/vm_set/tasks/add_ceos_list.yml
ansible/roles/vm_set/tasks/remove_topo.yml

When deploying the large topology with 256 neighbors, we observed that the process can take over three hours, which is impractical. Upon analyzing the playbook execution time, we found that certain tasks—particularly creation and deletion steps—were executed serially, causing unnecessary delays as each task waited for the previous one to complete. This PR optimizes the workflow by parallelizing these tasks. Instead of waiting, each task is now triggered in the background, allowing subsequent tasks to start immediately. This significantly reduces the overall deployment time, now the time can be shorten to one hour.
Summary:
When deploying the large topology with 256 neighbors, we observed that the process can take over three hours, which is impractical. Upon analyzing the …

Optimize large topology deployment by parallelizing serial tasks

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

When run this test case, it will always fail, and opened github ticket opened for it: https://github.com/sonic-net/sonic-mgmt/issues/18594
Summary:
Skip the test case before the issue fixed.

Add skip condition for https://github.com/sonic-net/sonic-mgmt/issues/18594

---

tests/snappi_tests/pfc/files/mixed_speed_multidut_helper.py

Calculating the egress rate based on the total packets received for lossy and lossless streams.
Some tests were failing with error "Egress speed beyond tolerance range"
On debugging it was found that tests case queries the egress rate from ixia, which keeps fluctuating. Depending upon when test case took the stats, it can affect the test case result. So to avoid this if the test fails based on ixia egress rate stats one more check is introduced to calculate the egress rate based on the total packets received and time traffic was sent and then check if the Egress rate is within the tolerance limit.
Summary:
Fixes # https://migsonic.atlassian.net/browse/MIGSMSFT-1029
- [ x] Bug fix
- [x ] 202405
Test case was failing
Added the another check to calculate the Egress rate base on total …

MIGSMSFT-1029

---

tests/generic_config_updater/test_lo_interface.py

Summary: Extend t1 topo for lo_intf test
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/19214
Extend range for lo_intf test
Add t1 topo
PR check

[GCU] Add t1 topo for lo_intf test

---

ansible/library/generate_golden_config_db.py
ansible/library/load_extra_dpu_config.py
ansible/module_utils/smartswitch_utils.py

Summary:
Update the smartswitch golden config logic to config IP addresses for the NPU-DPU data plane interfaces when deploying minigraph for Mellanox SN4280.
1. Update the logic to calculate the port and interface name/address for the port name like "Ethernet224" in ansible/library/generate_golden_config_db.py
2. Stabilize the DPU config reload step by using force reload in ansible/library/load_extra_dpu_config.py. It's possible that when doing the reload, the DPU system is not fully ready.
3. Add interface_key for Mellanox-SN4280-O28 in ansible/module_utils/smartswitch_utils.py
Update the smartswitch golden config logic to config IP addresses for the NPU-DPU data plane interfaces when deploying minigraph for Mellanox SN4280.
Run regression with this and no issues found.
Change is for …

[Smartswitch][Mellanox] Update the smartswitch golden config for SN4280 platform

---

ansible/group_vars/sonic/variables

Summary: Add DT2 hwsku in th5 groups
Add DT2 hwsku in th5 groups to enable some tests

chore: add supported hwsku for th5

---

ansible/allocate_device_ip.py

Summary:
The current IP allocation script is missing the IPs in ansible inventory and testbed.yaml, but only handled the devices in the CSV file. This is not enough and should be updated.
This PR updates the allocate device ip script to add the ansible inventory and testbed YAML files too.
Tested locally.
No

Update IP allocation script to handle the Ansible inventory and testbed.yaml files.

---

tests/platform_tests/test_intf_fec.py

Added NVIDIA platform to supported platforms on test_intf_fec
Manual Cherry pick of https://github.com/sonic-net/sonic-mgmt/pull/16946
Summary:
Enable test on NVIDIA platforms.
Added to the supported list
Ran the test

Add Nvidia to supported platforms on intf_fec test

---

tests/container_checker/test_container_checker.py

Summary:
33740254
The cases failed during teardown caused by the memory alarm.
Based script log, it should be related to the timing, when memory utilization collected the memory, some dockers were not up, so the memory before the test is much lower than normal, and caused memory alarm.
Try to wait all critical processes up and bgp up after tests to ensure the memory information is correct.
However, based on the test result, the waiting time is much longer than expected since this is the case for docker restart.
So plan to disable the memory checker in this case test_container_checker, since 
1: This case is for docker check, only do the stop_service then check the docker status. memory checker is not necessary.
2: If we want to wait all process up and bgp up, it would take …

[test_container_checker] disable_memory_utilization 

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py

[CI]add new param "skip_restart_ptf" for test plan pipeline

[CI]add new param "skip_restart_ptf" for test plan pipeline

---

.azure-pipelines/common2/scripts/get-changed-python-files.sh
.azure-pipelines/common2/steps/run-black.yml
.azure-pipelines/common2/steps/run-mypy.yml
.azure-pipelines/common2/steps/run-precommit.yml
.azure-pipelines/common2/steps/run-pylint.yml
.azure-pipelines/common2/steps/run-unit-test.yml
.azure-pipelines/pre-commit-check.yml
azure-pipelines.yml
pylintrc
tests/common2/INSTALL.md
tests/common2/requirements.txt
tests/common2/setup_environment.sh

- Update setup/install instructions for `tests/common2`.
- Update pipeline to install pre-requisites used by `pylint`
Summary:
Update user documentation and required for pre-commit hooks to run for changes under tests/common2.
NA
Manually
NA
NA
NA

[common2] Update README and pipeline

---

tests/show_techsupport/conftest.py

Summary: Temporarily skip err msg to skip list for the techsupport test case. after the issue fixed, will revert this PR

Temporarily skip err msg to skip list for the techsupport test case.

---

ansible/group_vars/sonic/sku-sensors-data.yml

Add sensors data for arm64-nvda_bf-bf3comdpu
Summary:
Add sensors data for arm64-nvda_bf-bf3comdpu
Add sensors data in ansible/group_vars/sonic/sku-sensors-data.yml
Run test_sensros tests
Smartswitch DPU
Any

[Mellanox]  Add sensors data for arm64-nvda_bf-bf3comdpu

---

tests/generic_config_updater/test_bgp_prefix.py

Make sure update updater of bgp prefix replace working even at low power CPU platform
Summary:
Case bgp_prefix_tc1_replace would be failed at the platform with low power CPU. It need time to handle after apply the config patch.
Add retry on bgp prefix installation validation.
Run it in local setup.

Update test test_bgp_prefix_tc1_suite

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Summary: Add test skip based on the github issue: https://github.com/sonic-net/sonic-mgmt/issues/6794

Add test skip based on the github issue: #6794

---

tests/platform_tests/link_flap/test_link_flap.py
tests/qos/test_pfc_counters.py

**Summary:**
The motivation is to improve test debuggability by adding detailed failure reasons in assertions for selected test cases. This enhancement makes it easier to identify the root cause of test failures in logs, thereby reducing triage time and simplifying test maintenance
I updated the assertion statements in the following test files to include descriptive error messages: …

Added detailed reason for assert failure for qos

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
Many test cases run into teardown failure due to SAI error log SAI_API_SWITCH:sai_query_stats_capability:874. This log doesn't indicate any functional impact but fail the test cases. 
Open issue and ignore this error log, we can remove it when the issue get addressed.
https://github.com/sonic-net/sonic-mgmt/issues/19790
N/A
Broadcom platform
N/A

Ignore SAI error log SAI_API_SWITCH:sai_query_stats_capability:874

---

ansible/testbed.nut.yaml
docs/testbed/README.testbed.NUT.md
tests/common/plugins/conditional_mark/__init__.py
tests/common/snappi_tests/snappi_fixtures.py
tests/common/testbed.py
tests/conftest.py
tests/test_pretest.py

Summary:
With the support of network under test (NUT) testbed being added, we need to update the tools for running the tests. 
Since the only difference between these 2 testbeds is the testbed definition, and the ixia tests uses very minimum set fields, we can easily create some adapting code to make the existing tool supporting the new type of testbeds.
Running test locally.
No.

Update tools for running test on NUT testbeds.

---

ansible/vars/topo_ptp-64.yml
ansible/vars/topo_ptp-66.yml

Add ptp-64 topology.
Summary:
Ran sonic-mgmt testbed deployment with PTP-64 and saw that the topology is recognized

Add ptp-64 topology.

---

docs/testplan/snappi/switch-packet-drop-threshold-tests.md

Summary:
We need a test case to assess the switch forwarding capability.
Add test case to determine the maximum traffic rate that results in 0% packet loss across different packet sizes.
Test plan only
None.
Topology: https://github.com/sonic-net/sonic-mgmt/pull/18630

[Test plan] Snappi-based packet drop threshold test plan

---

tests/gnmi/test_mimic_hwproxy_cert_rotation.py

Summary:
Fixes # ([708](https://github.com/aristanetworks/sonic-qual.msft/issues/708))
The expression had an error and did not correctly match the feature status of telemetry/gnmi, leading it to incorrectly infer it as "Failed: Internal image has neither gnmi nor telemetry feature enabled"
Fixing the expression to match for gnmi or telemetry under show feature status correctly
Tested it on Arista-7050CX3 devices and verified that it works
Not platform specific

[202505][sonic-mgmt]Fix for gnmi/test_mimic_hwproxy_cert_rotation.py failure

---

ansible/module_utils/port_utils.py

Summary:
Add Moby hwsku support into sonic-mgmt

add moby port alias

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
Fix the regex issue introduced by https://github.com/sonic-net/sonic-mgmt/pull/19791, which we should have a '\' before [ and ], and other mistakes. 
N/A
N/A
broadcom

[Log analyzer] Refine the regex to match the error log

---

tests/dash/packets.py

Update PL inbound gre key  because the inbound gre packet should have the same gre key as what is present in the DASH_ROUTING_TYPE_TABLE.
Summary:
Update PL inbound gre key according to the design change.
Update PL inbound gre key with int(pl.ENCAP_VNI) << 8
Run PL case on smartswitch
Smartswtich

Update PL inbound gre key

---

tests/bgp/test_ipv6_bgp_scale.py

Summary: Fix spelling error in test_ipv6_bgp_scale.py
Fixes # Fix spelling error in test_ipv6_bgp_scale.py

Fix spelling error in test_ipv6_bgp_scale.py

---

ansible/module_utils/port_utils.py
ansible/module_utils/smartswitch_utils.py
tests/qos/qos_sai_base.py

Summary:
Update 8102 smartswitch hwsku, otherwise `gen-mg` and `deploy-mg` won't work. 
Ran testbed-cli.

[ssw] update 8102 smartswitch hwsku

---

tests/platform_tests/test_platform_info.py

Summary:
Add an expected log error to PSU test
This test case is testing turning on/off PSU, from the syslog, we can see that while it's turning off one of the PSU, the psud is accessing some the sysfs attributes of the PSU, and read error happened, following are the adjacent three lines of logs, the first line is reported by psud which complaining that some PSU attribute is missing, the second line is from the kernel which indicating deleting some PSU related kernel device, the third line is from hw-mgmt, indicating that received some attribute delete event related to the PSU.
This error message is expected in this test as it's turning off the PSU., The error ignore list for this test should be updated to include this message.
Skip expected error in log
Added the regex to the skip
Ran …

Add an expected log error to PSU test

---

ansible/library/generate_golden_config_db.py

Summary:
Fixes #20038 
There's an issue that multi-asic device's configuration can't be refreshed after deploy-mg.
Limit the golden configuration generation to only contains key "FEATURE", then other configuration won't be written into golden configuration, the configuration can be refreshed.
Fixes #20038 
There's an issue that multi-asic device's configuration can't be refreshed after deploy-mg.
Limit the golden configuration generation to only contains key "FEATURE", then other configuration won't be written into golden configuration, the configuration can be refreshed.
Limit the golden configuration generation to only contains key "FEATURE", then other configuration won't be written into golden configuration, the configuration can be refreshed.
Test on physical Cisco chassis(multi-asic …

Fix bug: In master/202505, multi-asic device's configuration can't be refreshed after deploy-mg

---

tests/ipfwd/test_nhop_group.py

Replaced the fixed 180-second sleep in `test_nhop_group_interface_flap` with a conditional wait based on the number of eBGP v4/v6 routes on the DUT.
- Retrieves eBGP v4 and v6 route counts via `get_ip_route_summary()`.
- Sleeps for:
- **180 seconds** if v4 or v6 eBGP route count exceeds 10,000.
- **20 seconds** otherwise.
Summary:
The current implementation applies a fixed time.sleep(180) only for chassis systems.
However, during nightly runs on disagg-T2 devices, we observed that they also require an increased timeout for route programming, similar to chassis platforms.
Enhance the time.sleep logic to support additional platforms beyond chassis systems.
Retrieve eBGP v4 and v6 route counts using get_ip_route_summary().
If either count exceeds 10,000, apply a 180-second …

[test_nhop_group.py::test_nhop_group_interface_flap] Use conditional sleep based on route scale

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Some tests from restapi test suite skipped due to community isuue #(https://github.com/sonic-net/sonic-mgmt/issues/17997)
Skip tests that are failing due to community issue 
Added skip to conditional marks
Run test suite. Tests are skipped

Added xfail for test restapi based at issue 17797

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
- Added further cases to skip as requested in [19308](https://github.com/sonic-net/sonic-mgmt/pull/19308)
- The original issue that requires these cases to be skipped is being tracked in [627](https://github.com/aristanetworks/sonic-qual.msft/issues/627) and public issue [19096]( https://github.com/sonic-net/sonic-mgmt/issues/19096)

[sonic-mgmt][master]Skip IPv6 everflow cases under test_everflow_testbed.py for Arista-7060CX

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py

[CI] Support add new param commit hash of sonic-mgmt repo to check out
[CI] Support add new param commit hash of sonic-mgmt repo to check out, could be serviced by baseline test to detect image/test regressions.
Add new param `commit_hash` of `sonic-mgmt`
Raise draft PR to use a fixed commit hash of sonic-mgmt to test.
https://github.com/sonic-net/sonic-mgmt/pull/20089

[CI] Support add new param commit hash of sonic-mgmt repo to check out

---

tests/common/plugins/conditional_mark/tests_mark_conditions_vs_t2.yaml

Summary: There are 18 test cases that failed on VS T2 with probablity > 5%. We want to skip them for now.

Add test cases that are flaky in the mark condition list of vs t2

---

ansible/roles/vm_set/library/vm_topology.py

In PR #19334, we parallelized several tasks to optimize deployment time. While this high concurrency may introduce occasional timing issues, these errors can be safely disregarded since the ports are already in place.
Summary:
In PR #19334, we parallelized several tasks to optimize deployment time. While this high concurrency may introduce occasional timing issues, these errors can be safely disregarded since the ports are already in place.
Ignore the errors.

Ignore timing issues introduced by parallelization in `vm_topology.py`

---

ansible/group_vars/sonic/variables

Add 8101C01 to the hwsku list

---

tests/telemetry/cli_helpers.py
tests/telemetry/cli_paths.json
tests/telemetry/conftest.py
tests/telemetry/test_telemetry_show_cli.py

Summary:
MS ADO: 33734620
SHOW reboot-cause and SHOW reboot-cause history e2e tests. Provided easier way to add new testcases by updating cli_paths.json and cli_helpers.py
Skipped for non container upgrade test
Run test and container upgrade test infra

Show reboot cause telemetry test

---

tests/qos/test_tunnel_qos_remap.py

Enhance the qos_remap test case with flushing the buffer 

---

.azure-pipelines/pr_test_template.yml

Summary:
For other repos, if they want to import pr_test_template.yml, need add a step to checkout sonic-mgmt code.
Add checkout step in pr test template if in other repo.

Add checkout step in pr test template if in other repo

---

ansible/group_vars/sonic/variables

Fix merge conflicts

---

ansible/module_utils/graph_utils.py

PR https://github.com/sonic-net/sonic-mgmt/pull/19720 introduced graph_utils.py which broke devutils import. Wrap the import line in try catch.
Summary:
Fix devutils so powercycle can be done
Wrap import in try catch.
Run pdu test with run_test and also manually use devutils tool

[devutils] fix graph_utils broke devutils

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Add log errors to common ignore list by the following issues:
https://github.com/sonic-net/sonic-buildimage/issues/22795
https://github.com/sonic-net/sonic-buildimage/issues/23199
Summary:
- [] 202205
Add log errors to common ignore list by the following issues:
Add log errors to common ignore list by the following issues:
Run tests, and not fail due to the log errors
Any

Add log errors to common ignore list by the ticket 22795 and 23199

---

tests/bgp/test_traffic_shift.py
tests/bgp/test_traffic_shift_lc.py

Optimize the `bgp/test_traffic_shift.py` test for T2 devices by adding a separate `bgp/test_traffic_shift_lc.py` test and skipping the existing `bgp/test_traffic_shift.py` test for T2.
Summary:
Fixes # (issue) Microsoft ADO 33757271
On T2 devices, `bgp/test_traffic_shift.py` takes ~100 minutes to run. We found that it only executes on T2 line cards, includes a `bgpmon_setup_teardown` fixture that isn’t used on T2, and requires all line cards to be in the same TSA/TSB state simultaneously. To reduce runtime, we introduced `bgp/test_traffic_shift_lc.py`, a T2 line-card–only variant that preserves the original logic with targeted changes to reduce the running time. The original `bgp/test_traffic_shift.py` is now skipped on T2 in favor of the new test.
Along with the existing …

refactor: optimize traffic shift test for T2

---

.azure-pipelines/pr_test_template.yml

Summary:
PR https://github.com/sonic-net/sonic-mgmt/pull/20002 refined PR test template, but forgot to pass build branch param to get impact area yaml, which led to impact area not working
Pass build branch to impact area yaml
Before:
+ DIFF_FOLDERS=
After:
+ DIFF_FOLDERS='.azure-pipelines '

Fix get impact area parameter missing issue

---

sdn_tests/pins_ondatra/tests/BUILD.bazel
sdn_tests/pins_ondatra/tests/gnoi_factory_reset_test.go

```
==========[Building test: gnoi_factory_reset_test]==========
INFO: Analyzed target //tests:gnoi_factory_reset_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tests:gnoi_factory_reset_test up-to-date:
bazel-bin/tests/gnoi_factory_reset_test_/gnoi_factory_reset_test
INFO: Elapsed time: 0.239s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
==========[Build Complete: gnoi_factory_reset_test]==========
```
```
=== RUN   TestGnoiFactoryResetReturnsResetError
gnoi_factory_Reset_test.go:22: DUT name: 10.250.0.101
gnoi_factory_Reset_test.go:25: 
*** Fetching gNOI clients for 10.250.0.101...
--- PASS: TestGnoiFactoryResetReturnsResetError (0.03s)
=== RUN   TestGnoiFactoryResetZeroFill …
```

[sdn_tests]: Adding Tests for gNOI FacotryReset Service.

---

tests/container_hardening/test_container_hardening.py

Summary: database and swss have been privileged hardened. remove unprivileged containers for test_container_hardening

remove unprivileged container for test_container_hardening

---

ansible/module_utils/port_utils.py

This commit reintroduces the same functionality that was originally implemented in PR#20373 on the master branch. It ensures that 202411 also reflects the intended changes, as per our standard process.
Summary:
- [ X] Testbed and Framework(new/improvement)

Applied changes from PR#20373 to 202411 branch

---

tests/disk/test_disk_exhaustion.py

Fix bug:
`"echo 'sleep 60' >> {MOUNT_POINT}/test.sh",`
this line misses "f" in the beginning of the line, otherwise there's error like "/bin/sh: 1: cannot create {MOUNT_POINT}/test.sh: Directory nonexistent".
Fix bug:
`"echo 'sleep 60' >> {MOUNT_POINT}/test.sh",`
this line misses "f" in the beginning of the line, otherwise there's error like "/bin/sh: 1: cannot create {MOUNT_POINT}/test.sh: Directory nonexistent".
Add the missed `f`.
Test locally.

Fix bug test_disk_exhaustion.py

---

tests/common/helpers/voq_helpers.py
tests/voq/test_voq_nbr.py

Summary:
This PR refactors current code to retrieve and modify router MAC of port on
a EOS host using EOS CLI rather than using bash.
Switches from bash to EOS CLI for retrieving and modifying router port MAC
addresses. This eliminates dependence on shell interface names, which may
not always match the router's interface names.
Tested internally.

test_voq_nbr: Retrieve and modify router mac of front panel port using EOS CLI

---

tests/telemetry/events/swss_events.py

Summary:
Skips swss events in m1 topology
Add new topology in skip case
Pipeline

Skip m1 topology for test_events swss_events

---

tests/common/devices/sonic_asic.py
tests/ospf/conftest.py
tests/ospf/test_ospf_bfd.py

Summary:
Update the current ospf test case for t2-multiasic compatible. Also the following imporvement
- Remove functions call that requires TTY (needed for ansible compatibilty)
- Refactor to re-use sonic_asic function
- Added Copp trap for physical device to capture ospf
- adjusted some logic that suited more generic topology
Fixes # (issue) 32718386
Update the current ospf test case for t2-multiasic compatible. Also the following imporvement
- Remove functions call that requires TTY (needed for ansible compatibilty)
- Refactor to re-use sonic_asic function
- Added Copp trap for physical device to capture ospf
- adjusted some logic that suited more generic topology
Tested on physical T2

feat: update test_ospf_bfd for t2 support

---

ansible/roles/vm_set/templates/sonic.xml.j2
tests/common/plugins/conditional_mark/tests_mark_conditions_vs_t2.yaml

Summary: Currently there is an increasing number of test cases being flaky or takes a long time to finish on t2 pr checker. To make T2 pr checker become mandatory ASAP, we decided to keep the set of running test cases on t2 pr checker small and make it stable.

Add more test cases to the skip list for t2 pr checker

---

tests/snappi_tests/bgp/conftest.py
tests/snappi_tests/bgp/files/bgp_outbound_helper.py
tests/snappi_tests/bgp/test_bgp_outbound_downlink_port_flap.py
tests/snappi_tests/bgp/test_bgp_outbound_downlink_process_crash.py
tests/snappi_tests/bgp/test_bgp_outbound_tsa.py
tests/snappi_tests/bgp/test_bgp_outbound_ungraceful_restart.py
tests/snappi_tests/bgp/test_bgp_outbound_uplink_multi_po_flap.py
tests/snappi_tests/bgp/test_bgp_outbound_uplink_po_flap.py
tests/snappi_tests/bgp/test_bgp_outbound_uplink_po_member_flap.py
tests/snappi_tests/bgp/test_bgp_outbound_uplink_process_crash.py

Summary: Add record_property for bgp convergence 
Fixes # (issue) 34417012
Add record_property so that we can have it logged to kusto

feat: add record-property for bgp convergence

---

tests/conftest.py

Summary: T0/t1 snappi-dynamic-ports were disabled before due to some issue. With the latest code this can run now. We can re-enable it
Fixes # (issue) 33819813
Closes https://github.com/sonic-net/sonic-mgmt/issues/19461
Re-enable snappi-dynamic-ports option for t0 t1

[Snappi] Enable t0/t1 snappi-dynamic-ports

---

tests/bgp/test_bgp_peer_shutdown.py
tests/bgp/test_bgp_session.py
tests/bgp/test_bgp_session_flap.py
tests/bgp/test_bgp_stress_link_flap.py
tests/pfcwd/test_pfcwd_cli.py

Summary: Enable some of the test gap for dt2
Fixes # (issue) 32921768
test_bgp_session_flap
ft2
lt2 
test_bgp_session
ft2
lt2
test_bgp_stress_link_flap
ft2
lt2
test_bgp_peer_shutdown
ft2
Log analyzer 
```
SAI_API_SWITCH:sai_object_type_get_availability:1002 availablity my_sid failed with error -2.
```
lt2

chore: enable some dt2 tests-gap

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
https://msazure.visualstudio.com/One/_workitems/edit/34709614/?view=edit
This is a manual cherry-pick PR#18792 to 202411 branch.

manual cherry-pick PR#18792 to 202411

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
There is a typo introduced by https://github.com/sonic-net/sonic-mgmt/pull/20161

A quotation mark is missing in loganalyzer ignore list

---

.code-owners/contributors.yaml
.code-owners/folder_presets.yaml
.code-owners/run.sh
CODEOWNERS

Summary:
Added the yaml index of the contributors. And the proposed CODEOWNERS file
Improve the code review workflow.
Generated the files using code-owners script
https://github.com/sonic-net/sonic-pipelines/tree/main/scripts/code-owners
N/A
N/A
N/A
https://github.com/sonic-net/sonic-pipelines/blob/main/scripts/code-owners/HLD-WORKFLOW.md

Added code-owners infrastructure and result file

---

tests/common/config_reload.py
tests/common/helpers/parallel_utils.py
tests/common/plugins/sanity_check/__init__.py
tests/common/reboot.py
tests/conftest.py

Support parallel run for config reload and reboot
Summary:
Fixes # (issue) Microsoft ADO 34332526
We want to enhance our current [parallel run infrastructure](https://github.com/sonic-net/sonic-mgmt/blob/master/docs/tests/parallel_run/Parallel%20Run%20Infra%20for%20sonic-mgmt.md) to parallelize config reload and reboot as well. By doing this, we can enable parallel run for more test modules running on T2 and dual-tor that call `config_reload()` or `reboot()` for more than one hosts.
Put a waiting point before and after config reload/reboot to synchronize the status across different hosts.

feat: support parallel run for reload and reboot

---

tests/dhcp_relay/test_dhcpv6_relay.py

Summary: To resolve client LLA, ping to multicast address has been added.
It is observed in some cases  "dhcp_relay/test_dhcpv6_relay.py::TestDhcpv6RelayWithMultipleVlan::test_dhcp_relay_default" fails if the neighbor entry for client LLA is not present.
To make sure client address is resolved before we start the PTF test,
ping to a multicast address has been done so that we discover all the LLAs
in the segment.
Ran TestDhcpv6RelayWithMultipleVlan::test_dhcp_relay_default multiple times to make sure it passes.

[DHCPv6_Relay]: Ensuring Client Reachability

---

tests/common/plugins/memory_utilization/memory_utilization.py

Summary:
34787890
Same root cause with https://github.com/sonic-net/sonic-mgmt/pull/20555
update frr memory check
https://elastictest.org/scheduler/testplan/68c900cb4190d4cdef35774a

[memory_utilization] update frr memory check 

---

tests/platform_tests/test_cpu_memory_usage.py

Summary:
34016064
https://github.com/sonic-net/sonic-mgmt/pull/19541 updated the memory threshold
Need also to update the threshold for case test_cpu_memory_usage
Update the memory threshold for x86_64-mlnx_msn4600c-r0 in test_cpu_memory_usage
https://elastictest.org/scheduler/testplan/68bfcfd9e0cefb79533fa783

[test_cpu_memory_usage] update threshold for x86_64-mlnx_msn4600c-r0

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Summary:
N/A
Manual pick of https://github.com/sonic-net/sonic-mgmt/pull/20497

Update test_ser skip conditions for Arista-7060X6 SKUs

---

tests/common/snappi_tests/port.py
tests/common/snappi_tests/traffic_generation.py

Summary: Allow for multiple port selections in the base config. Base config currently only allows for one tx and rx port; change that to allow multiple tx ports for now to support packet trimming tests.

[Snappi] Refactor multiple tx port selection

---

ansible/roles/vm_set/library/vm_topology.py

When deploying neighbors in parallel, ip address add may fail with `RTNETLINK answers: File exists` if the same IP is added concurrently. Switching to `ip address replace` makes the operation idempotent: it will add the address if missing or update it if present, avoiding conflicts under high parallelism.
Summary:
When deploying neighbors in parallel, ip address add may fail with `RTNETLINK answers: File exists` if the same IP is added concurrently. Switching to `ip address replace` makes the operation idempotent: it will add the address if missing or update it if present, avoiding conflicts under high parallelism.
Switching to `ip address replace` makes the operation idempotent: it will add the address if missing or update it if present, avoiding conflicts under high …

Use `ip address replace` instead of `ip address add` during topology deployment.

---

tests/common/snappi_tests/snappi_fixtures.py

Summary: Disable pfc enablement on tgen if the switch doesn't have any lossless port config. Moreover, check link settings like fec and link training and set accordingly.
For purely lossy configs, disable PFC on the tgen. Enhance link settings based on switch config too.
Modify fixtures.
Tested on switch.

[Snappi] Disable pfc enablement on tgen if not needed + check link settings

---

ansible/library/announce_routes.py
tests/conftest.py

Summary:
Fix bugs:
1. Routes are not resturn from function after conversion.
2. When iterating routes, the code should use dictionary keys.
3. When generate routes for multiple servers testbed, need to iterate routes instead of replacement.
Fix bugs:
1. Routes are not resturn from function after conversion.
2. When iterating routes, the code should use dictionary keys.
3. When generate routes for multiple servers testbed, need to iterate routes instead of replacement.
1. return routes at last in function
2. use dictionary keys in iteration
3. iterate routes and update one by one instead of replacement.
run test in on testbed

Fix topogoly routes generation bug 

---

tests/common/fixtures/fib_utils.py

Align the FIB related tests for smartswitch. When getting fib info, skip the the dpu-npu port.
Summary:
1. https://github.com/sonic-net/sonic-mgmt/issues/20599
Align the FIB related tests for smartswitch.
When getting fib info, skip the the dpu-npu port.
Run the  on smartswitch
smartswitch

Align the FIB related tests for smartswitch

---

ansible/roles/vm_set/library/vm_topology.py
ansible/roles/vm_set/tasks/add_ceos_list.yml
ansible/roles/vm_set/tasks/add_topo.yml
ansible/roles/vm_set/tasks/main.yml
ansible/roles/vm_set/tasks/remove_topo.yml

Some deployment tasks such as VM network create/destroy and topology bind/unbind were previously executed in serial, which caused long deployment time when the neighbor number is large. This PR introduces parallel execution for these
time-consuming tasks using ansible async, reducing overall deployment time.
To enable this async mode, we can add `-e enable_async=true` after the cli
eg: `./testbed-cli.sh add-topo <testbed_name> password.txt -e enable_async=true`.
Summary:
Some deployment tasks such as VM network create/destroy and topology bind/unbind were previously executed in serial, which caused long deployment time when the neighbor number is large. This PR introduces parallel execution for these
time-consuming tasks using ansible async, reducing overall deployment …

Parallelize time-cost tasks in topology deployment

---

tests/qos/test_buffer.py

Summary: Cherry-pick of #20724
```
=========== 1 passed, 4 warnings in 340.42s (0:05:40) =====
```

[202505][QoS] Fix buffer-deployment test bug
