sonic-net/sonic-mgmt

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
This PR is to skip test cases in [`inner_hashing`](https://github.com/sonic-net/sonic-mgmt/tree/master/tests/ecmp/inner_hashing) on non required platform.
At this moment, the tests are only required on `Mellanox-SN3800` and `Mellanox-SN4600`. 
This PR is to skip test cases in [`inner_hashing`](https://github.com/sonic-net/sonic-mgmt/tree/master/tests/ecmp/inner_hashing) on non required platform.
Update the `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml`
The change is verified by manually running on a physical test.
No.

Skip inner hashing test on non-required platforms

---

tests/bfd/bfd_base.py
tests/bfd/bfd_helpers.py
tests/bfd/conftest.py
tests/bfd/test_bfd_static_route.py

Cherry-pick the latest `bfd/test_bfd_static_route.py` into 202305 branch.
Summary:
Fixes # (issue) Microsoft ADO 28210614
We need this change in 202305 to run nightly
I ran `test_bfd_static_route.py` with the cherry branch in a T2 chassis and can confirm it's working

feat: cherry-pick bfd static route test to 202305

---

tests/common/fixtures/duthost_utils.py

Fix convert_and_restore_config_db_to_ipv6_only reload config failure.
convert_and_restore_config_db_to_ipv6_only fixture will delete ipv4 mgmt address by config reload.
If mgmt interface restart before config reload, the duthost class will lost connection to device and throw unreachable exception.
Ignore config reload AnsibleConnectionFailure exception.
Fix convert_and_restore_config_db_to_ipv6_only reload config failure.

Fix convert_and_restore_config_db_to_ipv6_only reload config failure

---

sdn_tests/pins_ondatra/tests/gnmi_set_get_test.go
sdn_tests/pins_ondatra/tests/platforms_software_component_test.go
sdn_tests/pins_ondatra/tests/transceiver_test.go

- [sdn_tests]: Adding GNMI set get test in pins-ondatra.
Summary:
- Added GNMI set get test in pins-ondatra.
> INFO: Elapsed time: 317.285s, Critical Path: 122.36s
> INFO: 976 …

[sdn_tests]: Adding GNMI set get test in pins-ondatra.

---

tests/platform_tests/broadcom/test_ser.py

Summary:
28179454
The test_ser case failure on 202311 image.
Error log like: SER Test timed out for memories (1): ['MMU_MTRO_CONFIG_L1_MEM_PIPE1.mmu_sed0']"
Seems caused by the address from "bcmcmd 'list MMU_MTRO_CONFIG_L1_MEM_PIPE1.mmu_sed0'" is not same with the address in the log of "SER_CORRECTION"
For memory address, need sync with Arista and Broadcom teamfirst.
Meanwhile, add these results information into assert log by this PR to track the failure more easily.
Run the case locally.
```
>       assert False, (                                                                                                                                                                                                                               
'ser_injector script failed; \n' …
```

[platform_tests.broadcom.test_ser] add failure info in assert log if script return failure

---

.azure-pipelines/pr_test_scripts.yaml
tests/acl/custom_acl_table/test_custom_acl_table.py
tests/acl/null_route/test_null_route_helper.py
tests/acl/test_acl.py
tests/acl/test_acl_outer_vlan.py
tests/acl/test_stress_acl.py
tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml

Summary:
Add acl test to optional test job and skip traffic test
run test

Add acl test to pr test and skip traffic test

---

tests/common/devices/multi_asic.py

The global variable _DEFAULT_SERVICES will affect any future MultiAsicSonicHost instances for the test; this means that if this runs for the supervisor instance first then lldp gets incorrectly added for the linecard instances.
Summary:
Cherry-pick #13190 to 202405 since it's reported conflict
The global variable _DEFAULT_SERVICES will affect any future MultiAsicSonicHost instances for the test; this means that if this runs for the supervisor instance first then lldp gets incorrectly added for the linecard instances.
Fix this by just modifying the local service_list that we're making anyways.
Tested manually on 202405 on Arista hardware and verified that the pre-sanity check does not fail because the lldp service is not running.

Fix multi-asic lldp fix (#13190)

---

tests/bgp/test_bgp_suppress_fib.py

Summary:
The test reloads config in setup stage to configure VRF. In test body it applys the suppress fib config and do random reload/reboot.
It is possible that the system is not ready for warm/fast reboot after the first reload.
Use safe reload to avoid this.
And also use safe reload in the teardown to avoid any possible affection to the next test.
Test log of such a failure:
```
INFO     test_bgp_suppress_fib:test_bgp_suppress_fib.py:625 Randomly choose fast from reload, cold, warm, fast
DEBUG    tests.common.cache.facts_cache:facts_cache.py:82 Read cached facts "arc-switch1025.host_visible_vars"
DEBUG    tests.common.devices.base:base.py:67 /root/mars/workspace/sonic-mgmt/tests/common/devices/sonic.py::get_now_time#1059: [arc-switch1025] AnsibleModule::command, args=["date +\"%Y-%m-%d …
```

[BGP suppress fib] Use safe config reload in test case test_bgp_route_with_suppress

---

tests/bgp/test_bgpmon.py

Summary:
This PR is to improve `test_bgpmon.py`.
The test was failing occasionally with below error.
```
tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{"changed": true, "cmd": "ip route add 10.1.0.32/32 dev eth13", "delta": "0:00:00.262854", "end": "2024-05-30 23:14:57.051726", "failed": true, "msg": "non-zero return code", "rc": 2, "start": "2024-05-30 23:14:56.788872", "stderr": "RTNETLINK answers: File exists", "stderr_lines": ["RTNETLINK answers: File exists"], "stdout": "", "stdout_lines": []}
```
We believe it's because some test cases running before `test_bgpmon` also configured route on the same port, but didn't cleanup.
This PR addressed the issue by using `ip route replace` instead of `ip route add`.
This PR addressed the …

Improve test_bgpmon - use `ip route replace` instead of `ip route add`

---

tests/common/helpers/drop_counters/drop_counters.py

Summary:
This PR is to stabilize drop counter test.
The test is flaky because there are unexpected RX_ERR in addition to the testing packet, which leads to increament of drop counter is larger than expected. The error message is 
```
Failed: 'RX_ERR' drop counter was not incremented on iface PortChannel1020. DUT RX_ERR == [1003]; Sent == 1000
```
This PR fixed the issue by adding tolerance to the drop counter check. The default tolerance is `10`.
This PR is to stabilize drop counter test.
This PR fixed the issue by adding tolerance to the drop counter check. 
The change is verified on a physical testbed. Test can pass if additional RX_ERR is seen.
```
collected 9 items …
```

Add error tolerance for drop counter test

---

tests/fib/test_fib.py

`test_ipinip_hash_negative` was using `ptf_runner` without passing `is_python3=True`.
This resulted in some code which did string formatting unique to Python3 to assert:
```
"Traceback (most recent call last):"
"  File \"/usr/bin/ptf\", line 522, in <module>"
"    test_modules = load_test_modules(config)"
"  File \"/usr/bin/ptf\", line 413, in load_test_modules"
"    mod = imp.load_module(modname, *imp.find_module(modname, [root]))"
"  File \"ptftests/py3/pfc_wd_background_traffic.py\", line 40"
"    print(f\"traffic from {src_port} to {dst_port}: {queue} \")"
"                                                           ^"
"SyntaxError: invalid syntax"]
```
Summary:
Fixes #13313

Use is_python3=True in test_ipinip_hash_negative ptf_runner

---

tests/scripts/getbuild.py

Summary:
The getbuild.py tool was indeed using Azure DevOps PAT for downloading artifacts. We need to deprecate using PAT. 
This change updated the getbuild.py to support using bearer access_token. With this change, both PAT and bearer access_token are supported. However, bearer access_token has higher priority.

Update getbuild.py to support both PAT and access_token

---

tests/platform_tests/broadcom/files/ser_injector.py

Summary:
28290229
1. Case platform_tests.broadcom.test_ser failed sometimes due to timeout in TD3 and TH2.
2. Get asic type failed for th
Ignore these memory items for basic test
update the output string for latest version
Run the case locally
broadcom asic td3, th2, th

[platform_tests.broadcom.test_ser] update timeout items for test ser case

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

In recent sonic-mgmt runs, some testcases are failing with loganalyzer error message like 'Mar  6 19:52:31.977493 str3-8111-05 ERR syncd#syncd#syncd: SDK_LOG|-E-HLD-0- would fail config'
Cisco team confirmed that these error messages can be ignored and do not cause any functionality impact.
Adding this message to loganalyzer Ignore list so that Testcases will not fail
Modified the file ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt to add this Ignore message
Made sure that the testcases did not fail after these errors messages are ignored.
202305
202311

Ignore message SDK_LOG|-E-HLD-0

---

tests/platform_tests/mellanox/check_sysfs.py

Summary:
Fixes # This fix will skip the assert condition for the ports that does not have transceiver plugged in.
If a transceiver is not plugged in, the `"check_sysfs"` function throws an assertion error as below, causing the reboot test cases to fail.
<mark>`AssertionError: SFP32 temp fault`</mark>
Updated the `"check_sysfs"` function to skip the temperature fault checks for `"sfp_info[temp_fault]"` if it is empty.
Test proceeds successfully after adding this fix:
21:30:23 check_sysfs.check_sysfs                  L0164 INFO   | Check SFP related sysfs
21:30:23 check_sysfs.check_sysfs                  L0166 INFO   | sfp_info[temp_fault] 0 for sfp id 1
21:30:23 check_sysfs.check_sysfs                  L0166 INFO   | sfp_info[temp_fault] 0 for sfp id 2
21:30:23 check_sysfs.check_sysfs …

Skip the temperature checks for empty SFP ports

---

tests/platform_tests/test_reload_config.py

Summary:
28387106
Case failed due to no response after execting cmd "config reload" with timeout threshold.
Ansible ssh timeout value is 60s.
```
out = duthost.shell("sudo config reload -y",
executable="/bin/bash", module_ignore_errors=True)
>       assert "Retry later" in out['stdout']
E       KeyError: 'stdout'
out        = {'failed': True, 'msg': 'Timeout (62s) waiting for privilege escalation prompt: ', '_ansible_no_log': False}
```
Using async mode to run the CMD
Run the case locally and with pipeline

[test_reload_configuration_checks] using async mode to execute config reload CMD

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Now the testcase can pass so remove skip conditional - test_decap on 8111 T0 and 8111 T1 topo
Remove skip conditional 
Test on 8111 T0 and 8111 T1 physical topo
decap/test_decap.py::test_decap[ttl=pipe, dscp=uniform, vxlan=disable]                                                                                     
--------------------------------------------------------------------- live log setup ----------------------------------------------------------------------
06:40:46 __init__.set_default                     L0053 INFO   | Completeness level not set during test execution. Setting to default level: CompletenessLe
vel.basic …

Remove skip conditional - test_decap on 8111 T0 and 8111 T1 topo

---

tests/dualtor_mgmt/test_toggle_mux.py

Summary: Fix `dualtor_mgmt/test_toggle_mux.py`
Fixes [#161](https://github.com/aristanetworks/sonic-qual.msft/issues/161)
Regression due to: https://github.com/sonic-net/sonic-mgmt/pull/13004
The test fails with key error.
After the mentioned change https://github.com/sonic-net/sonic-mgmt/pull/13004 the mux_linkmgr can never be empty as it will always contain the key `TIMED_OSCILLATION`.
The proposed fix is to make the check more specific for the key `LINK_PROBER.`
Check PR comment for debugging info.
Verified on Arista-7050 platform using dualtor topology.
```
dualtor_mgmt/test_toggle_mux.py::test_toggle_mux_from_simulator[upper_tor] PASSED                                                                                     
[ 25%] …
```

Fix dualtor_mgmt/test_toggle_mux.py

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
[Manually cherry-pick #13362] Remove skip conditional - test_decap on 8111 T0 and 8111 T1 topo
Now the testcase can pass so remove skip conditional - test_decap on 8111 T0 and 8111 T1 topo
Remove skip conditional
Test on 8111 T0 and 8111 T1 physical topo
decap/test_decap.py::test_decap[ttl=pipe, dscp=uniform, vxlan=disable]
--------------------------------------------------------------------- live log setup ----------------------------------------------------------------------
06:40:46 init.set_default L0053 INFO | Completeness level not set during test execution. Setting to default level: CompletenessLe
vel.basic
06:40:46 init.check_test_completeness L0151 INFO | Test has no defined levels. Continue without test completeness checks
06:40:48 facts_cache.read L0092 INFO | Load …

[Manually cherry-pick #13362] Remove skip conditional - test_decap on 8111 T0 and 8111 T1 topo

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Issue:
bfd/test_bfd_static_route.py assumes that config_db.json is a mulit-asic system.
If it's a single asic it will use the wrong file name.
Resolution
The test is supposed to run only on a multi-asic system and on specific cisco LC, Modified the conditional mark to skip accordingly.  This PR is a fix for Jira #12948
Summary:
PR is a fix for Jira https://github.com/sonic-net/sonic-mgmt/issues/12948
Verified that the testcase skips on single_asic system. Would request @arista-nwolfe  to confirm that it skips for them too.

Skip bfd/test_bfd_static_route.py for single_asic systems and non cisco platforms - Fix for Issue #12948

---

tests/bfd/test_bfd.py
tests/bfd/test_bfd_static_route.py

Summary:
Bfd tests needs physical testbed support, need to add a physical mark to make it more clear and better for static
Add a physical mark

Add physical mark for bfd tests

---

tests/common/helpers/dut_utils.py
tests/crm/conftest.py
tests/crm/test_crm.py

Fix test issue:https://github.com/sonic-net/sonic-mgmt/issues/12725
For mellanox device, the crm available counter is related to LPM tree. When shutdown all interfaces in vlan (e.g. vlan 1000), it will cause the route (e.g. 192.168.0.1/21 )for vlan to be removed, we have only one route for the prefix (21), after it is removed, the corresponding prefix in LPM tree will be removed too, which will lead to the LPM tree structure is changed. LPM tree change might cause available counter change dramatically, and we cannot estimate how long the change is ready. Therefore, it will lead the first case of test_crm_route fail occasionally because the expected available counter is not decreased. So, we add another route with the same prefix(21) as the vlan's so that the LPM tree is not changed. …

[Mellanox] Stabilize test_crm_route 

---

tests/crm/test_crm.py

Revert https://github.com/sonic-net/sonic-mgmt/pull/12787, because there is another fix: https://github.com/sonic-net/sonic-mgmt/pull/12882#
Summary:
Revert the PR, so the  crm test can run on mellanox device
Revert the PR
run the test_crm_route on mellanox device 
any

[Mellanox]Revert "Skip available route check for mellanox platforms (#12787)"

---

.azure-pipelines/pr_test_scripts.yaml
tests/arp/test_stress_arp.py
tests/arp/test_unknown_mac.py
tests/arp/test_wr_arp.py
tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml

Summary:
Add some arp test to pr test and skip traffic test

Add arp test to pr test and skip traffic test

---

tests/stress/conftest.py
tests/stress/test_stress_routes.py
tests/stress/utils.py

Support `test_stress_routes.py` on T2 topology.
Summary:
Fixes # (issue) Microsoft ADO 28357470
Currently, the `test_stress_routes.py` only runs on the following topologies: T0, T1, M0, MX. We wanted to support this test on T2 topology as well. 
Add T2 topology marker and make necessary changes to make the test pass on a T2 testbed.
I run the updated test on a T2 testbed and confirm it passed.

feat: support stress routes test on T2 topo

---

tests/tacacs/test_accounting.py

Fix error in accounting test case.
Accounting test case failed with RunAnsibleModuleFail error
- Microsoft ADO: 28343053
Fix command, use tail command show recent log
[TACACS] Fix error in accounting test case.

[TACACS] Fix error in accounting test case

---

tests/override_config_table/utilities.py
tests/route/test_forced_mgmt_route.py

Fix force_mgmt_route failed on some hardware because snmp agent can't bind to eth1 address issue.
force_mgmt_route test case failed on some hardware because snmp agent can't bind to eth1 address.
- Microsoft ADO: 28434014
Ignore check SNMP agent process status by use unsafe config reload.
Fix force_mgmt_route failed on some hardware because snmp agent can't bind to eth1 address issue.

Fix force_mgmt_route failed on some hardware because snmp agent can't bind to eth1 address issue.

---

sdn_tests/pins_ondatra/infrastructure/binding/BUILD.bazel
sdn_tests/pins_ondatra/infrastructure/binding/pins_backend.go
sdn_tests/pins_ondatra/tests/gnmi_wildcard_subscription_test.go

- [sdn_tests]: Adding GNMI Wild_Card tests to pins_ondatra.
Summary:
- Added GNMI Wild_Card tests to pins_ondatra.
Build result:
```
sonic-mgmt/sdn_tests$./key.sh pins_ondatra/
Keyword check Passed.
sonic-mgmt/sdn_tests/pins_ondatra$ bazel build ...
github.com/openconfig/gnsi/pathz/pathz.proto:25:1: warning: …
```

[sdn_tests]: Adding GNMI Wild_Card tests to pins_ondatra.

---

ansible/roles/fanout/templates/arista_7260cx3_deploy.j2
ansible/roles/fanout/templates/sonic_deploy_202311.j2

Summary:
Fix fanout switch config template:
1. For Arista-7260, fix the config template for breakout interface to 4x 10G.
2. For Arista-720DT, set autoneg=on for gbsyncd interface (1 <= lane <= 24). Otherwise, these interface cannot oper up.
3. For Arista-720DT and Nokia-7215, remove BUFFER_QUEUE and BUFFER_PG sections from config_db.json.
Fix fanout switch config template:
1. For Arista-7260, fix the config template for breakout interface to 4x 10G.
2. For Arista-720DT, set autoneg=on for gbsyncd interface (1 <= lane <= 24). Otherwise, these interface cannot oper up.
3. For Arista-720DT and Nokia-7215, remove BUFFER_QUEUE and BUFFER_PG sections from config_db.json.
Verified on physical fanout switch.

[Fanout] Fix fanout config template for Arista-7260 and Arista-720DT

---

tests/qos/files/cisco/qos_param_generator.py
tests/qos/files/qos_params.gb.yaml
tests/qos/files/qos_params.pac.yaml

The fix of https://migsonic.atlassian.net/browse/MIGSMSFT-388 introduces xon hysteresis, qos params in xon testcases need to be updated.
Summary:
Add pkts_num_hysteresis for new rx cgm profile.
Update qos params used in xon testcases.
Add pkts_num_hysteresis in file qos_param_generator.py, qos_params.gb.yaml and qos_params.pac.yaml.
Run it on testbed.
T1-100G
```
============================================================================ PASSES =============================================================================
______________________________________________________ TestQosSai.testQosSaiPfcXonLimit[single_asic-xon_1] ______________________________________________________
______________________________________________________ …
```

Add pkts_num_hysteresis for new rx cgm profile

---

tests/generic_config_updater/test_aaa.py

ADO: 28386083
Summary: Make TACPLUS test independent with AAA setup
Update GCU aaa test with recent setup. In recent setup, the tacacs+ is always ready in AAA|Authentication. If we remove TACPLUS passkey, it will result in YANG validation error. In this PR, we will only check TACPLUS test without AAA tacacs+ imapct.
Remove AAA table before TACPLUS test
E2E test

[GCU] Update AAA test with recent setup

---

tests/stress/conftest.py
tests/stress/test_stress_routes.py
tests/stress/utils.py

Support `test_stress_routes.py` on T2 topology.
Summary:
Fixes # (issue) Microsoft ADO 28357470
Currently, the `test_stress_routes.py` only runs on the following topologies: T0, T1, M0, MX. We wanted to support this test on T2 topology as well. 
Add T2 topology marker and make necessary changes to make the test pass on a T2 testbed.
I run the updated test on a T2 testbed and confirm it passed.

feat: support stress routes test on T2 topo (#13341)

---

tests/tacacs/test_ro_user.py

The PR fixes the test case test_ro_user.py to check if the command fails due to inadequate permissions. 
We see the following error .e.g. when the show command permission is changed to be for root user only..
root@m64-tor-0:/home/cisco# chmod 744 /usr/local/bin/show
root@m64-tor-0:/home/cisco# ls -l /usr/local/bin/show
-rwxr--r-- 1 root root 206 May 3 16:13 /usr/local/bin/show
Following is seen in the log, but the test case passes as it is looking for a different string.
21/05/2024 16:56:37 base._run L0104 DEBUG | /data/tests/tacacs/test_ro_user.py::ssh_remote_run#21: [localhost] AnsibleModule::shell Result => {"failed": true, "msg": "non-zero return code", "cmd": "sshpass -p 123456 ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null test_rouser@1.74.23.15 show version", …

Enhance the test_ro_user test case to check for user permissions errors.

---

tests/common/snappi_tests/snappi_fixtures.py
tests/common/snappi_tests/traffic_generation.py
tests/snappi_tests/variables.py

Summary: Adding support for RDMA cases for pfcQueueGroupSize of 4
This PR supports pfcQueueGroupSize of 4 , currently the support is for 8
added queue map in variables file

Adding support for RDMA cases for pfcQueueGroupSize of 4

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
These errors are found for config reload on 202311 branch on broadcom platform and safe to ignore.
These are from the change https://github.com/sonic-net/sonic-swss/pull/2598.
r, ".* ERR swss#orchagent: :- queryHashNativeHashFieldListEnumCapabilities: Failed to get attribute.*"
r, ".* ERR swss#orchagent: :- queryHashNativeHashFieldListAttrCapabilities: Failed to get attribute.*"
r, ".* ERR swss#orchagent: :- querySwitchEcmpHashAlgorithmEnumCapabilities: Failed to get attribute.*"
r, ".* ERR swss#orchagent: :- querySwitchLagHashAlgorithmEnumCapabilities: Failed to get attribute.*"
r, ".* ERR syncd\d*#syncd.*SAI_API_PORT:_brcm_sai_read_fec_stat_err_counters.* failed with error Feature unavailable.*"

Add loganalyzer_common_ignore regexs for config reload on broadcom

---

.azure-pipelines/run-test-elastictest-template.yml

Summary:
This is the fist step for eliminating client secrets. Purpose of this change is to allow test_plan.py to get access_token via service connection for accessing scheduler.
This change wrapped all test_plan.py call in AzureCLI task instead of regular Bash task.
The next step is to update test_plan.py to get access_token via service connection.

Wrap test_plan.py in AzureCLI task

---

docs/testbed/README.testbed.VsSetup.md
tests/route/test_route_flow_counter.py
tests/stress/utils.py

We have a PR https://github.com/sonic-net/sonic-utilities/pull/3375 in `sonic-utilities` that fixes the 'Neighbhor' typo of the `show [ip|ipv6] bgp summary` command. Therefore, we need to correct all the 'Neighbhor' typo references in this repo
Summary:
Fixes # (issue) Microsoft ADO 28482605
Correct the bgp summary output typo references to let it sync with the `sonic-utilities` repo

fix: correct show bgp summary output typo references

---

.azure-pipelines/run-test-elastictest-template.yml

Summary:
On some agents, the azure cli package is already installed, it's unnecessary to try installing it again.
This change improved the step for installing azure cli to check if the az command is available. If no, try to install azure-cli. If yes, skip this step.

Improve the step for installing azure-cli in template

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skip warm reboot on SN4700 t0 devices since it is currently not qualified.
Summary:
Warm reboot failed on SN4700 t0 devices.
Skip warm reboot on SN4700.
`==================================================================== short test summary info =====================================================================
SKIPPED [2] bgp/test_bgp_slb.py:68: Skip it on dual tor since it got stuck during warm reboot due to known issue on master and internal image; skip warm-reboot on SN4700 since it is not currently meant to be qualified.`

[202311]Skip warmreboot on SN4700 t0 devices since it is currently not qualified.

---

tests/pc/test_lag_2.py

Summary:
Add the routeCheck fail message to the right log analyzer exception handler
Fixes # [(issue)](https://github.com/sonic-net/sonic-mgmt/issues/10147)
Add the routeCheck fail message to the right log analyzer exception handler
Verified that the testcases pass even when syslog is present.
<TO add test pass logs here >

Update the correct loganalyzer_exceptions with routeCheck fail message

---

ansible/roles/test/files/helpers/bfd_responder.py

Change-Id: Ia75304532a975289ba1f61feef44374b769d1484
Adding support of IPv6 priority field named "tc" in bfd_responder.py
Summary:
Fix bfd tests that are running with both IPv4 and IPv6
Defined dynamical ip_priority variable equal to "tos" for IPv4 and equal to "tc" for IPv6

add support of IPv6 tc field in bfd responder

---

tests/platform_tests/sfp/test_sfputil.py

In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. In this PR, we fix the failed test script `platform_tests/sfp/test_sfputil.py` and let it run successfully in T0 PR checker. 
Summary:
In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. In this PR, we fix the failed test script `platform_tests/sfp/test_sfputil.py` and let it run successfully in T0 PR checker. 
```
platform_tests/sfp/test_sfputil.py::test_check_sfputil_presence[vlab-01-None] PASSED [ 16%]
platform_tests/sfp/test_sfputil.py::test_check_sfputil_error_status[vlab-01-None-sudo …
```

Add script `platform_tests/sfp/test_sfputil.py` into T0 PR checker. 

---

tests/tacacs/conftest.py

Add debug info for check nss config missing issue.
TACACS accounting test case randomly failed because can't login device with remote account.
According syslog, seems nss config file been deleted on device.
Add debug log to check and confirm the root cause.
Add debug info for check nss config missing issue.
Add debug info for check nss config missing issue.

[TACACS] Add debug info for check nss config missing issue.

---

tests/common/reboot.py
tests/platform_tests/sfp/test_show_intf_xcvr.py

In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. In this PR, we fix the failed test script `platform_tests/test_reboot.py` and let it run successfully in T0 PR checker. 
Summary:
In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. In this PR, we fix the failed test script `platform_tests/test_reboot.py` and let it run successfully in T0 PR checker. 
```
SKIPPED [1] platform_tests/test_reboot.py: Skip test_soft_reboot for m0/mx and test is supported only on …
```

Add script `platform_tests/test_reboot.py` into T0 PR checker. 

---

tests/platform_tests/test_platform_info.py
tests/platform_tests/thermal_control_test_helper.py

In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. In this PR, we fix the failed test script `platform_tests/test_platform_info.py` and let it run successfully in T0 PR checker. 
Summary:
In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. In this PR, we fix the failed test script `platform_tests/test_platform_info.py` and let it run successfully in T0 PR checker. 
```
SKIPPED [1] common/helpers/assertions.py:16: No PSU controller for vlab-01, skip rest of the …
```

Add script `platform_tests/test_platform_info.py` into T0 PR checker.

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml
tests/decap/test_decap.py

Summary:
Add decap to PR test and skip traffic test

Add decap test to PR test and skip traffic test

---

azure-pipelines.yml

Summary:
Onboarding test jobs are optional test jobs, we are using it in piloting, but some contributors were confused with failed onboarding jobs
Add an optional keyword to reduce confusion

Add optional keyword to onboarding test job

---

tests/common/fixtures/conn_graph_facts.py

Summary:
When we get conn_graph_facts in fanout_graph_facts function, it would return an empty dict for KVM testbed, and raise key error when we directly get dev_conn[duthost.hostname].items()
Return fanout conn graph with None when we get an empty device conn graph facts

Fix KVM get device conn graph error

---

tests/common/plugins/sanity_check/checks.py

Summary:
Fix the sanity check mux probe recovery.
Use the port name to probe instead of the port index.
Run `test_bgp_fact.py` on dualtor with inconsistent mux ports.

Fix dualtor sanity mux probe recovery

---

tests/voq/test_fabric_reach.py
tests/voq/test_voq_fabric_status_all.py

Summary:
This fixes a bug where VOQ fabric tests would raise an exception due to a missing Loader argument to yaml.load (due to new pyyaml version since the tests were written).
I switched from `yaml.load()` to `yaml.safe_load()`.
I ran the tests against a local testbed and verified that the test passed and did not raise any exception.

Fix voq fabric tests to use yaml.safe_load instead of yaml.load

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
I have added some dataplane test scripts to PR test and put into optional onboarding job to test case performance, I calculated the success rate of test scripts in recent 1 week, I think I can move high success rate test scripts to t0/t1 job now
TestbedName | ModulePath | SuccessCount | FailureCount | TotalTests | SuccessRate
-- | -- | -- | -- | -- | --
vms-kvm-t1-lag | acl.test_acl.TestAclWithPortToggle | 3989 | 0 | 3989 | 1
vms-kvm-t1-lag | acl.test_acl.TestAclWithReboot | 4013 | 2 | 4015 | 0.9995
vms-kvm-t1-lag | acl.test_acl.TestBasicAcl | 3361 | 0 | 3361 | 1
vms-kvm-t1-lag | acl.test_acl.TestIncrementalAcl | 4008 | 0 | 4008 | 1
vms-kvm-t1-lag | acl.test_stress_acl | 59 | 0 | 59 | 1
vms-kvm-t0 | acl.custom_acl_table.test_custom_acl_table | 104 | 0 | 104 | 1 …

Move stable test from onboarding job to t0/t1 job

---

.azure-pipelines/testscripts_analyse/report_data_storage.py

Summary:
Use access token to connect kusto in report_data_storage
Remove client id/client key/tenant id

Use access token to connect kusto in report_data_storage

---

tests/autorestart/test_container_autorestart.py
tests/common/utilities.py
tests/dhcp_server/conftest.py
tests/dhcp_server/dhcp_server_test_common.py
tests/dhcp_server/test_dhcp_server.py
tests/dhcp_server/test_dhcp_server_multi_vlans.py

Summary:
Backport dhcp server tests from master branch to 202311 branch for qualification
we need to qualify dhcp server on 202311 branch
backport test cases

[dhcp_server_test] backport dhcp server tests from master branch to 202311 branch for qualification

---

tests/platform_tests/daemon/test_pcied.py

Summary:
The "get_pcie_devices_tbl_key" fixture is currently invoked before the "setup" fixture. When the PCIe daemon is not running, the "get_pcie_devices_tbl_key" fixture asserts that the PCIE_DEVICES table is empty in the database and causes the test to fail. Instead, make the "get_pcie_devices_tbl_key" fixture dependent on the "setup" fixture to verify the daemon status before retrieving the PCIE_DEVICES table from the database, which skips the test if daemon is not running.
There are occasional failures with the "PCIE_DEVICES table is empty" message when running PCIe tests. This fix ensures the PCIe daemon is running before retrieving the PCIE_DEVICES table, thereby increasing test reliability.
Make the "get_pcie_devices_tbl_key" fixture dependent on the "setup" fixture to verify the …

Verify the PCIe daemon status before retrieving the PCIE_DEVICES table from the database

---

tests/common/config_reload.py

Add multi asic support when `wait_for_bgp` is True in `tests/common/config_reload.py`
Summary:
Fixes # (issue) Microsoft ADO 28459397
Currently, if `wait_for_bgp` is True [here](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/config_reload.py#L160) in `tests/common/config_reload.py`, a multi-asic Testbed might never meet the `check_bgp_session_state` check. This is due to the restrictions of the show ip bgp command. For example, we have the following output for the `show ip bgp summary -d all` command:
We can see there are multiple `3.3.3.3` neighbors in the output, and this is because `3.3.3.3` is the neighbor for each ASIC. However, when we try to get the `bgp_neighbors` [here](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/config_reload.py#L161) from …

fix: support multi asic for config reload

---

tests/common/snappi_tests/snappi_fixtures.py
tests/common/snappi_tests/snappi_helpers.py
tests/snappi_tests/variables.py

Summary:
Fixes :
1. Chose gateway MAC based on port, as the gateway MAC maybe different on packet chassis.
2. change peer_ports calculation in get_multidut_tgen_peer_port_set to cover all the dut/asic combination.
3. SnappiFanoutManager only supports Snappi chassis, so ignore other type of fanout switches during initialization.
4. change the default prefix length to /31 (ipv4), /126(ipv6). as these are the default prefix length that will be advertised in SONiC BGP for connected routes.
Fixes needed to run test_multidut_pfcwd_a2a_with_snappi.py
1. Chose gateway MAC based on port, as the gateway MAC maybe different on packet chassis.
2. change peer_ports calculation in get_multidut_tgen_peer_port_set to cover all the dut/asic combination.
3. SnappiFanoutManager only supports Snappi chassis, …

 [Snappi] Fixes for T2 ixia test cases: Traffic MAC address, peer_ports, SnappiFanout 

---

tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
tests/snappi_tests/multidut/pfc/test_lossless_response_to_external_pause_storms.py
tests/snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py
tests/snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless_lossy.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossy.py
tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_burst_storm_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_m2o_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
tests/snappi_tests/test_multidut_snappi.py

Summary:
Fixes random.sample error in multidut test cases.
```
snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py::test_multidut_pfcwd_all_to_all[linecard_configuration_set0-chassis_multi_line_card_multi_asic-False]
12:09:41 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 501, in __call__
return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 119, in _hookexec …
```

[Snappi] random.sample exception in multidut snappi test cases.

---

tests/bfd/bfd_base.py
tests/bfd/bfd_helpers.py
tests/bfd/conftest.py
tests/bfd/test_bfd_static_route.py
tests/bfd/test_bfd_traffic.py

Implement BFD PTF-based traffic test.
Summary:
Fixes # (issue) Microsoft ADO 28382949
We need to confirm the patch switching behavior when one of the backend port channels is down in a T2 chassis.
Test case 1: remote port channel shutdown
1. send 10k pkt from src PTF to dst's BGP neighbor to find the remote (dst) backend portchannel in use
2. shut down the remote backend portchannel found in step 1
3. traffic now should shift to an alternative backend portchannel
4. send 10k pkt again to verify the new traffic path is in use now
Test case 2: local port channel shutdown
1. send 10k pkt from src PTF to dst's BGP neighbor to find the local (src) backend portchannel in use
2. shut down the local backend portchannel found in step 1
3. traffic now should shift to an alternative backend …

feat: add BFD traffic test

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skip `platform_tests/test_reload_config.py::test_reload_configuration_checks` when release is 202405 on Cisco 8000
Summary:
Fixes # (issue) Microsoft ADO 28459551
Currently, the `platform_tests/test_reload_config.py::test_reload_configuration_checks` test case is skipped on Cisco 8000 when the release is in 202205, 202211 or 202305. We should also skip it for 202405 because Cisco platform has flaky timing issue.

fix: skip test_reload_configuration_checks when release is 202405

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
From 202311 onwards, since iburst isn't enabled by default, there's a chance that NTP may fail to quickly synchronize the time. Details are in sonic-net/sonic-buildimage#19425.
Add an xfail for that until it's handled.

Add xfail for NTP test case due to iburst not being enabled by default

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml
tests/everflow/everflow_test_utilities.py
tests/everflow/test_everflow_per_interface.py
tests/everflow/test_everflow_testbed.py

Summary:
Add everflow test to T0 and T1 PR test

Add everflow test to PR test

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml
tests/ecmp/inner_hashing/test_inner_hashing.py
tests/ecmp/inner_hashing/test_inner_hashing_lag.py
tests/ecmp/inner_hashing/test_wr_inner_hashing.py
tests/ecmp/inner_hashing/test_wr_inner_hashing_lag.py

Summary:
Add test to t0 job and skip traffic test

Add ecmp inner hash test to PR test

---

tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py

The existing PFCWD basic testcases have restart SWSS service testcases.
However, these testcases do not address the multi-asic environment.  The pull-request addresses this.
Summary:
The fix finds out the DUT and interfaces used in the test and based on that selects swss@0 or swss@1 to restart. The fix first verifies if the platform field exists and if yes, is set to 'broadcom-dnx' field. If this is not true, then code executes the default testcase.
To address the multi-asic environment scenario and select appropriate SWSS depending upon the DUT-interface selected for the test.
- Finding the DUT-interface used in the test. 
- For Single line card - Single ASIC, the DUT will be same and interfaces will be from same ASIC. So only single swss is selected.
- For Single line …

[Snappi] - fixing swss service restart logic for basic PFCWD testcases in multi-asic environment

---

ansible/roles/vm_set/library/vm_topology.py
ansible/roles/vm_set/tasks/remove_topo.yml

1. Remove muxy-vm related interfaces directly to handle nsenter failure
2. Do 8021q module reinstall to handle vconfig add failure
This PR is used to handle 2 issues during dual-tor setup deployment.
In a t0/t1 and dualtor shared setup, sometimes, cross deployment action would happened. Someone is deploying t0/t1 setup while other one is deploying dualtor setup. As a result, 2 issues would exist after deployment.
Summary:
1. Some muxy-vm related interfaces would be left, and it would leads to next round of dualtor deployment failure. The failure reason would be nsenter command failure in ansible playbook.
2. Vlan module stuck in abnormal state, vconfig add and even vconfig remove command could not be executed for a specific vlan. And it could not be recovered …

Handle failure during dualtor setup deployment

---

tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml

Summary:
After  # (https://github.com/sonic-net/sonic-buildimage/pull/18487) Mellanox platforms mentioned in PR won't be drop DIP/SIP IP link local address.
Note!!! Backport to 202311 has to be after https://github.com/sonic-net/sonic-buildimage/pull/18692 merged
Skip drop TC related to IP link local address
Add skip into appropriate yaml 
Run TC, TC has been skipped

Update skip conditions for drop packets DIP/SIP link local IP

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skip BFD traffic test on non-Cisco8800 devices
Summary:
Fixes # (issue) Microsoft ADO 28382949
We need to skip `bfd/test_bfd_traffic.py` on non-Cisco8800 devices
I added the skip condition

fix: add skip condition for BFD traffic test

---

ansible/roles/fanout/templates/sonic_deploy_202305.j2
ansible/roles/fanout/templates/sonic_deploy_202311.j2

Summary:
Remove unnecessary char after names in the config db for BUFFER_PORT_EGRESS_PROFILE_LIST
Adjust the ansible\roles\fanout\templates\sonic_deploy_202305.j2 and 202311.j2 file
`cat config_db.json | grep -A 5 BUFFER_PORT_EGRESS_PROFILE_LIST`
Before
```
"BUFFER_PORT_EGRESS_PROFILE_LIST": {
"Ethernet8|": {
"profile_list": "egress_lossless_profile,egress_lossy_profile"
},
"Ethernet184|": {
"profile_list": "egress_lossless_profile,egress_lossy_profile"
```
After
```
"BUFFER_PORT_EGRESS_PROFILE_LIST": {
"Ethernet0": {
"profile_list": "egress_lossy_profile"
},
"Ethernet8": {
"profile_list": "egress_lossy_profile"
```
Is for 202305 and 202311

clean up and adjust fanout deploy file

---

tests/dualtor/test_ipinip.py

Summary:
dualtor/test_ipinip.py test should be run on dualtor topo, but pytest mark is t0
Modify topo mark to dualtor in dualtor/test_ipinip.py

Modify topo mark in dualtor/test_ipinip.py

---

tests/route/test_forced_mgmt_route.py

Summary:
Fixes #169
Skip `test_forced_mgmt_route_add_and_remove_by_mgmt_port_status` in `route/test_forced_mgmt_route.py` if `eth1` does not exist or is being used. This test was failing on Arista platforms when interface `eth1` did not exist.
Added a check to see if `eth1` does not exist, and skips the test if so.
Tested on a `t0` setup on a `Arista-7260`

Skip forced mgmt route test if intf is invalid

---

tests/common/snappi_tests/traffic_generation.py
tests/snappi_tests/multidut/pfc/files/multidut_helper.py
tests/snappi_tests/pfc/files/helper.py

The PFC multi-dut testcases checks the pause frame count transmitted and received by the DUT during the test.
Testcase needed modifications to handle the multiple line card scenario.
Summary:
Issue #12887 
The PFC lossless testcases uses multidut_helper file to start the traffic and verify the results. One of the verifications involves checking the pause frames being sent and received by the DUT.
A single DUT (object duthost) was being sent to the function 'verify_pause_frame_count' to verify the sent and received pause frames. This will work fine for - Single line card single ASIC and Single line card multiple ASIC - because it is single DUT only.
However, this would fail for multiple line card scenario. Here, the PFC receiving and sending line cards are different, and …

[Snappi] Handling multi-dut scenario for verify_pause_frame_count in PFC lossless test

---

tests/bgp/test_startup_tsa_tsb_service.py

Summary:
- This PR has additional new test cases to verify the changes introduced as part of #https://github.com/sonic-net/sonic-buildimage/pull/18496.
- This PR is dependent on PR #12238
- Basically, this PR has new 4 test cases in addition to the 5 test cases added to verify start and stop of the new service 'startup_tsa_tsb.service' introduced by PR #12238 
To verify code changes introduced as part of the PR #https://github.com/sonic-net/sonic-buildimage/pull/18496
- Added 4 more new test cases as mentioned below to verify the changes.
- Attaching updated test cases' description document with all 9 test cases here for further reference and details.
[BGP-TSA-TSB-Service-TestCases.txt](https://github.com/sonic-net/sonic-mgmt/files/15264571/BGP-TSA-TSB-Service-TestCases.txt …

Additional test cases to verify 'startup_tsa_tsb.service' - PR#18496 PR#12238

---

tests/common/snappi_tests/common_helpers.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_basic_helper.py

PFCWD testcases should capture PFCWD statistics before and after the test.
The function get_pfcwd_config_attr was defined with one of the arguments as 'asic_value' but while calling the function, 'namespace' was being used.  Corrected to use 'asic_value" while calling the get_pfcwd_config_attr function.
Summary:
Github issue #12900 
Github issue #12987 
The PFCWD statistics should be captured before and after the testcases to ensure that storm detected/restored is incremented during the test. 
Similarly, the PFCWD drop counters should be also checked before and after the test to confirm the count of packets dropped during the test.
Defined a function in tests/common/snappi_tests/common_helper.py to capture PFCWD stats for a given DUT, interface and priority. The function …

[Snappi]: Corrections in calling get_pfcwd_config_attr function and new PFCWD stats function to capture PFCWD statistics.

---

tests/dns/test_dns_resolv_conf.py

Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/8242
If /etc/resolv.conf is broken in docker container, some critical service may fail to start.
Update test case to cover the validation of /etc/resolv.conf in each docker container.
Run DNS end to end test

Validate /etc/resolv.conf in each docker container

---

tests/platform_tests/cli/test_show_platform.py

…form
Summary:
Added validation of HW revision on mellanox devices in test_show_plataform.py
Following the correction of hw-revision in show platform summary command (https://github.com/sonic-net/sonic-buildimage/pull/19098), we add a validation to mellanox devices that the hw-revision is as expected.
Compare the output in show platform summary with that specified in the predefined path (VPD_DATA_FILE )

Added validation of HW revision on mellanox devices in test_show_plataform.py

---

ansible/roles/test/files/ptftests/py3/advanced-reboot.py

Attempts to process received packets that weren't sent resulted in a KeyError exception in the examine_flow disruption calculation. This commit ignores them.
Summary:
Microsoft ADO: 27806353
The platform_tests.test_advanced_reboot.test_fast_reboot test was failing due to received packets that weren't sent.
Modified the `examine_flow` function to run independently then tested the logic with a series of pcap files with various missing packets in the sequence. The cases included:
- 100 packets, happy path
- 100 packets, 0th packet receive missing
- 100 packets, 0th packet send missing
- 100 packets, 10th packet both missing, 11th packet both missing
- 100 packets, 10th packet both missing, 11th packet receive missing
- 100 packets, 10th packet both missing, 11th packet send …

Ignore received packets that weren't sent during examine_flow

---

tests/common/config_reload.py

Refactor the BGP check in `config_reload.py` to combine the single and multi asic scenarios into one.
Summary:
Fixes # (issue) Microsoft ADO 28459397
In the previous PR #13471, we added multi asic support when `wait_for_bgp` is True in `common/config_reload.py`. It turns out we don't need to differentiate the single and multi asic scenarios. For a single asic Testbed, we can also use the `sonic_host.get_bgp_neighbors_per_asic()` and `sonic_host.check_bgp_session_state_all_asics()` to confirm the BGP session status. 
One thing we need to be aware of is that `sonic_host.get_bgp_neighbors_per_asic()` will return a dictionary with `None` as the key for a single asic Testbed. This is because for a single asic Testbed, its default namespace is always `None`, but any hashable value is a valid …

refactor: combine single and multi asic bgp check

---

ansible/devutil/ssh_session_repo.py
ansible/ssh_session_gen.py

Summary:
Currently, the SSH configuration uses the IPv4 address of a device. However, devices may also have an IPv6 address available, and some tests may configure the device to only have an IPv6 address on eth0.
Modify the SSH config generation to support generating a separate entry with the IPv6 address instead of the IPv4 address. These entries will have a suffix of `-v6`.
A separate entry approach was chosen partly because OpenSSH's config doesn't support using multiple literal IP addresses.
Tested the OpenSSH config generation, and it looks file. Have not tested the SecureCRT config generation.

Generate IPv6 SSH configuration to devices with IPv6 address configured

---

tests/autorestart/test_container_autorestart.py

Summary:
test_pretest.py disables autorestart for all features, so if we want to test dhcp server autorestart we need to enable it.
test_pretest.py disables autorestart for all features, so if we want to test dhcp server autorestart we need to enable it.
Enable autorestart before test

[dhcp_server_test] Enable autorestart before test dhcp server container autorestart

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Fixes #11310 
LAG and ECMP hash offset support has merged in 202311 https://github.com/sonic-net/sonic-swss/pull/3138, remove the xfail marker of ecmp/test_ecmp_sai_value.py
After https://github.com/sonic-net/sonic-swss/pull/3138, configure hash_offset along with hash_seed attribute is enabled on 202311 onwards on Broadcom T1 platfrom.
Remove the xfail marker of ecmp/test_ecmp_sai_value.py
Run ecmp/test_ecmp_sai_values.py on 7260 T1 DUT and passed.
https://dev.azure.com/mssonic/internal/_build/results?buildId=586225&view=results

Remove xfail marker of ecmp/test_ecmp_sai_value.py

---

tests/arp/test_neighbor_mac.py

Summary:
A recent change applies this test to the topo of t1 and t1-variants:
https://github.com/sonic-net/sonic-mgmt/pull/12952
The test can pass on topo t1 without any change.
For t1-lag or t1-64-lag, the Ethernet0 to test is in portchannel, so IP address cannot be set to it. 
The fix here is to remove the intf from the portchanenl before testing it.
Skip the test if Ethernet0 is not available or down at the beginning of test
Assert Ethernet0 is in routed state after removing it from portchannel 
Run the test on t1-lag and t1-64-lag topo.
- The test can pass
- Verified in the log that removing and adding the member to PortChannel succeeded

Fix test_neighbor_mac on t1-lag and t1-64-lag

---

.azure-pipelines/pr_test_skip_scripts.yaml
tests/ixia/ixanvl/test_bgp_conformance.py
tests/ixia/test_ixia_traffic.py
tests/ixia/test_tgen.py

Summary:
Ixia test do not support on kvm testbed, and wan test do not support in PR test, need to add those test to pr test skip yml to explicitly skip in PR testing.
Add ixia/wan test to PR test skip yml, and add pytest marker in ixia test

Add ixia and wan test to pr skip yml

---

tests/conftest.py

Summary:
Ignore the linkmgrd log level key in the config checker.
Add `"LOGGER|linkmgrd"` to the ignore list.
Verify on dualtor testbed.

[config_check] Ignore linkmgrd logger key

---

tests/platform_tests/link_flap/test_link_flap.py

There is a more comprehensive function in `platform_tests/link_flap/link_flap_utils.py` to get port candidates for link flap test. In this PR, we use this common function to replace previous function. And in this PR, we also add the `pytest_require` after getting the port candidates. If there is no expected port candidates, we will skip this test. 
Summary:
There is a more comprehensive function in `platform_tests/link_flap/link_flap_utils.py` to get port candidates for link flap test. In this PR, we use this common function to replace previous function. And in this PR, we also add the `pytest_require` after getting the port candidates. If there is no expected port candidates, we will skip this test. 
Use function in `platform_tests/link_flap/link_flap_utils.py`  to …

Update link flap test to use common port candidate function. 

---

ansible/roles/fanout/templates/arista_7260cx3_deploy.j2

Summary:
Update Arista-7260CX3 leaf fanout configuration template for breakout 4x 10G interface.
Fix the template for situation that not all the 4 breakout interface are being used.
Update Arista-7260CX3 leaf fanout configuration template for breakout 4x 10G interface.
Fix the template for situation that not all the 4 breakout interface are being used.
Update the j2 template file.
Verified on physical Arista-7260CX3 fanout switch.
Snippet of generated configuration:
```
...
interface Ethernet9/1
description DUT-1-Ethernet51
speed forced 10000full
switchport access vlan 668
switchport mode dot1q-tunnel
spanning-tree portfast
!
interface Ethernet9/2
shutdown
!
interface Ethernet9/3
description DUT-2-Ethernet51
speed forced 10000full
switchport access vlan 772
switchport mode dot1q-tunnel …
```

[Fanout] Update Arista-7260CX3 leaf fanout template for breakout 4x 10G interface

---

ansible/roles/vm_set/library/vm_topology.py
ansible/roles/vm_set/tasks/remove_topo.yml

Reverts sonic-net/sonic-mgmt#12958
Thanks to @saiarcot895's finding, the re-insert of vlan kernel model will leave other testbeds on the same server in an error state.

Revert "Handle failure during dualtor setup deployment"

---

tests/common/fixtures/duthost_utils.py
tests/decap/test_decap.py
tests/everflow/everflow_test_utilities.py
tests/everflow/test_everflow_per_interface.py
tests/everflow/test_everflow_testbed.py

Summary:
Elastictest performs well in distribute running PR test in multiple KVMs, which support us to add more test scripts to PR checker. But some traffic test using ptfadapter can't be tested on KVM platform, we need to skip traffic test if needed.
Currently, we are using a fixture `skip_traffic_test` in `ptfhost_utils` and `tests_mark_conditions_skip_traffic_test.yaml` to add marker to tests, but conditional mark would only match longest prefix, so our mark in `tests_mark_conditions_skip_traffic_test.yaml` couldn't be matched.
We will support to add all markers in conditional mark in the future, the plan is: if marks are different, all marks would be matched and added, if marks are the same, only the longest prefix would be matched and added.
Before conditional mark …

Use temporary fixture in duthost_utils to skip traffic test in vs platform

---

tests/common/devices/sonic.py
tests/dhcp_server/conftest.py
tests/dhcp_server/dhcp_server_test_common.py
tests/dhcp_server/test_dhcp_server.py
tests/dhcp_server/test_dhcp_server_multi_vlans.py

Summary:
When updating config db, there are some invalid references modeled by yang model.
For example: ERR sonic_yang: Data Loading Failed:Leafref "/sonic-dhcp-server-ipv4:sonic-dhcp-server-ipv4/sonic-dhcp-server-ipv4:DHCP_SERVER_IPV4_RANGE/sonic-dhcp-server-ipv4:DHCP_SERVER_IPV4_RANGE_LIST/sonic-dhcp-server-ipv4:name" of value "range_192.168.0.91" points to a non-existing leaf.
When updating config db, there are some invalid references modeled by yang model.
we can adjust the order of applying patches to avoid invalid status.
Adjust the order of config patches
Run tests

[dhcp_server_test] Fix log errors caused by dhcp server tests

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

…g issue
Summary:
Set Xfail test_reload_configuration_checks for Cisco platform in 202311 branch.
No need for other branch.
There is a timing issue which will cause test_reload_configuration_checks fail in Cisco platform.
Set xfail to test_reload_configuration_checks for Cisco platform
Run with physical testbed

Set Xfail test_reload_configuration_checks for Cisco platform

---

tests/dash/conftest.py
tests/dash/gnmi_utils.py

Summary:
Sometimes we need to keep gnmi certificates for further testing.
Sometimes we need to keep gnmi certificates for further testing.
Add option to skip gnmi certificates cleanup.
I have manually run dash end2end test.

Add option to skip certificates cleanup

---

.azure-pipelines/pr_test_scripts.yaml
tests/generic_config_updater/test_cacl.py

Summary:
Fix the test gap https://github.com/sonic-net/sonic-mgmt/issues/12816
Original test_cacl only covers parts of SNMP or SSH protocol test, https://github.com/sonic-net/sonic-host-services/pull/9 introduce EXTERNAL_CLIENT, we have to cover it in GCU test_cacl
Enhance many functions to support different protocols and add a fixture cacl_protocol to test SSH, SNMP,NTP, EXTERNAL_CLIENT one by one.
Also add T1 topology in mark topology list.
Test steps:
TC1 cacl table:
1. Test to add a new cacl table, which should expect success
2. test add duplicated cacl table, which should expect success
3. Test replace some variable in existing cacl table, which should expect success
4. Test add invalid cacl table, which should expect failure
5. Test remove non-existed cacl table, …

[Test Gap] Cover all cacl protocols in GCU test_cacl

---

tests/platform_tests/test_link_down.py

Summary:
Fixes # (issue) [11671](https://github.com/sonic-net/sonic-mgmt/issues/11671)
This PR is used to enable the test_link_down script to test SONiC T0 and T1 devices. There was only one line of code change made to tests/platform_tests/test_link_down.py. 
Fill the test gap.
Change the test script
I tested it on T0, T1 and T2 DUTs in Microsoft's internal testbed and the new script works fine.

enable test_link_down on t0 and t1 devices

---

tests/conftest.py
tests/pc/test_retry_count.py

Summary:
For test cases where there is some configuration done on the neighbor devices, or some state is checked on the neighbor devices, if there is a test case failure, it would be useful to get the logs on that device for debugging purposes. However, there's no fixture currently that does this (there is a fixture that automatically collects techsupport on the DUT itself).
Add a fixture to collect the techsupport from neighbor VMs if they are vSONiC neighbors if the test case fails. Also, modify two test cases in `tests/pc/test_retry_count.py` to have it collect information from the neighbors if it fails. This information will be extremely helpful in debugging failures.
Modified the test function to always collect techsupport, then run it on a KVM t0-116 topo with vSONIC …

Add functionality to save techsupport on vSONiC neighbors, and use it for retry count

---

ansible/roles/test/files/acstests/everflow_policer_test.py
tests/everflow/everflow_test_utilities.py

Summary:
Adding GRE ERSPAN type-2 for Marvell platform
- [ X] Test case(new/improvement)
- [X ] 202305
- [ X] 202311
Added GRE ERSPAN type-2 for Marvell platform 
Added GRE ERSPAN type-2 for Marvell platform and changed the ethertype.
Verified on Marvell platform.
Yes

Adding GRE ERSPAN type-2 for Marvell platform

---

tests/platform_tests/test_kdump.py

The `platform_tests/test_kdump.py` test keeps failing on the supervisor card. The reason is that a supervisor card needs more time to become fully available after reboot, because most of them have many dockers that need to come up. Luckily, if we set `safe_reboot` to True, the `reboot()` function will wait for all the critical processes to be up before continuing.
Therefore, we should enable safe reboot on supervisor card as well as all other cards so we can make sure that the DUT is fully ready before running any command/task on it. 
Summary:
Fixes # (issue): Microsoft ADO 28165196
I ran the updated  `platform_tests/test_kdump.py` test on a T2 chassis and I can confirm it passed.

fix: enable safe reboot on supervisor card

---

tests/generic_config_updater/test_pfcwd_status.py

In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. For test script `generic_config_updater/test_pfcwd_status.py`, it will always have an error message `'.*ERR syncd#syncd: :- queryStatsCapability: failed to find switch oid:.* in switch state map'` in syslog, which I think is expected. So in this PR, we add this error message into ignore list. 
Summary:
In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. For test script `generic_config_updater/test_pfcwd_status.py`, it will always have an error message `'.*ERR syncd#syncd: :- …

Add script `generic_config_updater/test_pfcwd_status.py` into T0 PR checker.

---

tests/qos/test_qos_sai.py

@zhixzhu adding support for split-voq for the non-macsec linecard. This support is coming soon, so we need to update the tests as well.

Adding skip checks for split-voq for non-macsec 400G LC.

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Ignore netlink socket readData error logs in syslog that are causing some tests to fail.
 
Summary:
This message was ignored earlier, but only from FDBSyncd. But these messages are seen for PortSyncd as well. Since there is no functional impact due to these logs, these are ignored.
More details in https://github.com/sonic-net/sonic-swss/issues/353

Ignore netlink socket readData errors 

---

tests/conftest.py

Summary:
Currently compare_running_config would return True if the first key / value is equal, which is incorrect.
Sample:
pre_running_config = {
"key_a": "value_a",
"key_b": "value_b"
}
cur_running_config = {
"key_a": "value_a",
"key_b": "another_value"
}
After compare "key_a" and find that they are equal, it will return True directly rather than continue to compare "key_b"
Remove the incorrect `return`
Run tests

Fix core_dump_and_config_check in conftest

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/ecmp/test_ecmp_sai_value.py

Summary:
After code change https://github.com/sonic-net/sonic-buildimage/pull/18912 and https://github.com/sonic-net/sonic-mgmt/pull/13538, test_ecmp_sai_value is not xfailed on 202311, but test_ecmp_hash_seed_value consistently failed on 202311, since the sai_hash_seed_config_hash_offset_enable is not set in config.bcm, it's set by swss config on 202311 and later image.
1) Fix test_ecmp_hash_seed_value failure on 202311
2) fix one function mistake in case.
3) remove internal and master from skip list, internal and master should support this case now
Only check if sai_hash_seed_config_hash_offset_enable exists in config.bcm for 202305 branch, will skip this check for other branches.
run test_ecmp_sai_value against 202311.

Fix test_ecmp_hash_seed_value failure on 202311

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Remove skip condition for test_syslog_source_ip, bcause the relevant bug of  https://github.com/sonic-net/sonic-mgmt/issues/6479 has been fixed
Summary:
Remove skip condition for test_syslog_source_ip
Remove skip condition
Run test_syslog_source_ip tests
Any

Remove skip condition for test_syslog_source_ip

---

tests/gnmi/helper.py
tests/gnmi/test_gnoi_killprocess.py

Summary:
GNOI KillProcess API introduced in this PR: https://github.com/sonic-net/sonic-gnmi/pull/213 requires thorough E2E tests of supported services, and possible failure scenarios
Add E2E tests
Run E2E test on physical DUT
Confirmed passing on latest master: 
---------------------------------------------------------------------------------- live log teardown -----------------------------------------------------------------------------------
22:57:39 gu_utils.rollback                        L0247 INFO   | Commands: config rollback test_setup_checkpoint
22:58:06 conftest.core_dump_and_config_check      L2165 INFO   | Dumping Disk and Memory Space informataion after test on str3-s6100-acs-6
22:58:09 conftest.core_dump_and_config_check      L2169 INFO   | Collecting core …

[GNOI E2E Testing] Add E2E Tests for GNOI KillProcess API

---

tests/ip/test_mgmt_ipv6_only.py

Summary: Add debug unreachable ipv6 issue after fixture setup for MGMT IPv6 only
ADO: 28489789, 28451569
There're some random failures for MGMT IPv6 only TACACS test case, suspect the cause is unreachable ipv6 issue after fixture setup for MGMT IPv6 only
```
Failed: Warning: Permanently added '2a01:111:e210:3000::a03:9289' (RSA) to the list of known hosts. Permission denied, please try again.
```
Add debug log to check and confirm unreachable mgmt IPv6 issue
Failed case
```
15/07/2024 01:07:31 test_mgmt_ipv6_only.log_tacacs           L0070 DEBUG  | Checking ping_result [PING 2a01:111:e210:b000::a40:f691(2a01:111:e210:b000::a40:f691) 56 data bytes
--- 2a01:111:e210:b000::a40:f691 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms]
15/07/2024 …
```

Add debug unreachable ipv6 issue after fixture setup for MGMT IPv6 only

---

tests/bgp/test_bgp_session_flap.py

Support `bgp/test_bgp_session_flap.py` test on T2 chassis
Summary:
Fixes # (issue) Microsoft ADO 28357414
The `bgp/test_bgp_session_flap.py` test was running on T1 topology only. We wanted to run it on T2 topo as well.
I made some changes to the `setup()` function to run the test for all Line Cards on a T2 chassis.
I ran the updated test on both T1 and T2 devices and I can confirm both passed.

feat: support BGP session flap test on T2 chassis

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml

Script `sub_port_interfaces/test_sub_port_l2_forwarding.py` has two test cases
- sub_port_interfaces/test_sub_port_l2_forwarding.py::test_sub_port_l2_forwarding[port] 
- sub_port_interfaces/test_sub_port_l2_forwarding.py::test_sub_port_l2_forwarding[port_in_lag]
The first case can run on kvm testbed, and the second case will skip because of the reason `Not supported port type` marked in `tests_mark_conditions.yaml`. But in PR #13506, I added this script into T0 skip list by mistake, which will skip whole script. In this PR, I fix this issue, and the first case can run in the PR checker. 
Summary:
Script `sub_port_interfaces/test_sub_port_l2_forwarding.py` has two test cases
- sub_port_interfaces/test_sub_port_l2_forwarding.py::test_sub_port_l2_forwarding[port] 
- …

[Bugfix] Move `test_sub_port_l2_forwarding.py` from T0 skip list to onboarding list. 

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/vlan/test_vlan_ping.py

1. vlan test enhancement for dualtor.
2. Enable “vlan/test_vlan.py::test_vlan_tc7_tagged_qinq_switch_on_outer_tag” for cisco-8000
Summary:
With this PR we can run vlan ping test on dualtor topo. Also, we have enabled “vlan/test_vlan.py::test_vlan_tc7_tagged_qinq_switch_on_outer_tag” for cisco-8000
Fixes https://github.com/sonic-net/sonic-mgmt/issues/9642 and https://github.com/sonic-net/sonic-mgmt/issues/12302
vlan ping test was failing on dualtor topo.
enhanced the test case to run on dualtor topo
Verified that the tests are passing  on dualtor-aa and standalone t0
```
vlan/test_vlan.py::test_vlan_tc7_tagged_qinq_switch_on_outer_tag`
dtor-aa run log:
sonic@sonic-ucs-m5-6:/data/tests$ ./run_tests.sh -n tor40 -l debug -u -c vlan/test_vlan.py::test_vlan_tc7_tagged_qinq_switch_on_outer_tag …
```

vlan test enhancement for dualtor

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/platform_tests/test_advanced_reboot.py

…e and failures to session teardown
Skip advanced reboot on 7050 devices which has eos neighbors but no SSD due to failures of session teardown.
Summary:
Advanced reboot failed on vms20-t0-7050cx3-2 / vms28-t0-7050-13.
Skip advanced reboot on it.
Ran advanced_reboot on `vms28-t0-7050-13` test bed and result is:
`================================================ short test summary info =================================================
SKIPPED [1] platform_tests/test_advanced_reboot.py: skip test_fast_reboot_from_other_vendor due to knonw issue, if xfail it, it will block other test cases
SKIPPED [2] platform_tests/test_advanced_reboot.py:115: skip advanced reboot tests on 7050 devices without SSD`

Skip advanced reboot on vms20-t0-7050cx3-2 since failures to session teardown

---

ansible/library/announce_routes.py
tests/stress/test_stress_routes.py

We got flaky issue `ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))` in script `test_stress_routes.py` in baseline test. We can not reproduce this issue in local environment. The logs of announcing routes are stored on DUT, in order to save these logs on test server and downloaded by elastictest, we use function `config_module_logging` to achieve this. 
Summary:
We got flaky issue `ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))` in script `test_stress_routes.py` in baseline test. We can not reproduce this issue in local environment. The logs of announcing routes are stored on DUT, in order to save these logs on test server and downloaded by …

Add debug message for debugging script `test_stress_routes.py`.

---

tests/acl/test_acl.py
tests/common/plugins/conditional_mark/tests_mark_conditions_acl.yaml

Summary:
In t1-lag PR test, reboot acl test took about 2 hours to finish, which took too much time to finish, and it's not needed since traffic test are skipped in acl test, and previous setup steps are tested in t0 PR test.
Skip reboot acl test in t1-lag PR test with a pytest.skip, once conditional mark could support all matches, would switch to use conditional mark skip to save more time
Run test on t1-lag KVM

Skip reboot acl test in t1-lag PR test for test time too long

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/dualtor/dual_tor_utils.py
tests/common/dualtor/server_traffic_utils.py
tests/common/dualtor/tunnel_traffic_utils.py
tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml
tests/dualtor/conftest.py
tests/dualtor/test_orchagent_active_tor_downstream.py
tests/dualtor/test_orchagent_mac_move.py
tests/dualtor/test_orchagent_standby_tor_downstream.py
tests/dualtor/test_standby_tor_upstream_mux_toggle.py

Summary:
Add mock dualtor dataplane test to onboarding t0 job and skip traffic test
Test in KVM platform

Add mock dualtor dataplane test to onboarding t0 job

---

tests/process_monitoring/test_critical_process_monitoring.py

Summary: 
To address the issue where the `dhcp6relay` and `dhcprelayd` processes are not running as expected within `dhcp_relay`, it is necessary to ensure that the correct prefix `dhcp-relay:` is included when attempting to start these processes using `supervisorctl`. This prefix is crucial for the supervisor to recognize and manage the processes correctly. By adding a condition to include the prefix, `supervisorctl` can be used effectively to start the `dhcp6relay` and `dhcprelayd` processes as intended.
{"changed": true, "cmd": "docker exec dhcp_relay supervisorctl start dhcp6relay", "delta": "0:00:00.381158", "end": "2024-06-19 03:45:44.319270", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2024-06-19 03:45:43.938112", "stderr": "", "stderr_lines": …

Fix dhcp process name when called by supervisorctl

---

.azure-pipelines/pr_test_scripts.yaml
tests/pfcwd/conftest.py
tests/pfcwd/files/pfcwd_helper.py

Summary:
When we get conn_graph_facts in pfcwd module, it would return an empty dict for KVM testbed, and raise key error when we get neighbors by directly get conn_graph_facts['device_conn'][duthost.hostname]
Use get method to pass variables, and pass empty dict or string if conn_graph_facts is empty
Run KVM test

Add test_pfc_config.py script to t0 and t1-lag PR test set

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/copp/test_copp.py

Summary:
Enable copp test on m0-2vlan topo.
Enable copp test on m0-2vlan topo.
Update conditional mark file and copp test pytest mark.
Verified on Nokia-7215 M0-2vlan testbed.

[M0-2Vlan] Enable copp test on M0-2Vlan topo

---

tests/common/snappi_tests/snappi_fixtures.py
tests/snappi_tests/multidut/ecn/files/multidut_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_basic_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_burst_storm_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_multi_node_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_runtime_traffic_helper.py

Summary:
Fixes #13443 
Fix duthost and port mapping mismatch issue in multidut  PFCWD and ECN test cases.  PFC test cases will be changed in another PR to avoid large commit.
Add 'duthost' into get_multidut_snappi_ports, so that we can retrieve duthost based on port information.
Test it manually. all PFCWD test cases can run successfully. There are test failures but are not related to this change.

[Snappi] Fix duthost port mapping in multidut snappi tests (PFCWD, ECN)

---

docs/testbed/README.testbed.VsSetup.md
tests/route/test_route_flow_counter.py
tests/stress/utils.py

This reverts commit 4fd776d1a1598c5c5072b4604de66575ecd32984.
The https://github.com/sonic-net/sonic-utilities/pull/3375 PR has been reverted (revert PR: https://github.com/sonic-net/sonic-utilities/pull/3423) because it will impact many automation scripts that the community users may have developed for years, so we need to revert this change as well.
Summary:

Revert "fix: correct show bgp summary output typo references (#13395)"

---

tests/platform_tests/conftest.py

Summary:
On Mx topo, testbed doesn't use SFP interfaces (these ports are admin down). We need to exclude these interfaces from SFP related tests to avoid test failure when there is no cable connected on DUT.
On Mx topo, testbed doesn't use SFP interfaces (these ports are admin down). We need to exclude these interfaces from SFP related tests to avoid test failure when there is no cable connected on DUT.
Update `xcvr_skip_list`, for Nokia-7215 and Arista-720DT Mx, add `Ethernet48`, `Ethernet49`, `Ethernet50`, `Ethernet51` to skip list.
Verified by running below testcases, all passed or skipped:
* platform_tests/sfp
* platform_tests/api/test_sfp.py
* platform_tests/test_xcvr_info_in_db.py

[Mx] Update `xcvr_skip_list` for Mx topo

---

ansible/library/reduce_and_add_sonic_images.py

Summary:
Currently install image in sonic-mgmt is use default param, which would migrate sonic-extension-application package by default (dhcp_relay, macsec, dhcp_server) when install to a os version which doesn't contain them. This is un-clean install, should be fixed.
Also, there is an issue with sonic_package_manager when migrate package https://github.com/sonic-net/sonic-buildimage/issues/19633
When installing image, check whether it support skip-package-migrate, if so, skip it.
Use .azure-pipelines/upgrade_image.py to install image from os support package migrate and not support package migrate to a new version, not error

[Ansible] Skip package migrate when installing image

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
I have added some dataplane test scripts to PR test and put into optional onboarding job to test case performance, I calculated the success rate of test scripts in recent 1 week, I think I can move high success rate test scripts to t0/t1 job now
vms-kvm-t0 | acl/test_acl_outer_vlan.py | 2024-07-21 00:00:00.0000000 | 64 | 0 | 64 | 1
vms-kvm-t1-lag | decap/test_decap.py | 2024-07-21 00:00:00.0000000 | 8 | 0 | 8 | 1
vms-kvm-t0 | decap/test_decap.py | 2024-07-21 00:00:00.0000000 | 8 | 0 | 8 | 1
vms-kvm-t0 | dualtor/test_orchagent_active_tor_downstream.py | 2024-07-21 00:00:00.0000000 | 8 | 0 | 8 | 1
vms-kvm-t0 | dualtor/test_orchagent_mac_move.py …

Move stable test from onboarding test job to t0/t1-lag PR checker

---

.azure-pipelines/pr_test_skip_scripts.yaml

Summary:
We use pr_test_skip_scripts.yaml to identify scripts that should be completely skipped on different platforms during KVM tests, and store these scripts statically in .azure-pipelines/testscripts_analyse/.
However, T1 skip scripts were not being included in the calculations because of a key mismatch. In pr_test_scripts.yaml, the key used is "t1-lag," while in pr_test_skip_scripts.yaml, the key used is "t1." This inconsistency prevented the correct aggregation of the results. This pull request addresses the issue by ensuring consistent key usage across both files.
Modify the key "t1" to "t1-lag" in pr_test_skip_scripts.yaml

Fix Key Mismatch for T1 Skip Scripts in pr_test_skip_scripts.yaml and pr_test_scripts.yaml

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

**Backport #13719 and resolve conflict.**
Enable copp test on m0-2vlan topo.
Update conditional mark file and copp test pytest mark.
Verified on Nokia-7215 M0-2vlan testbed.
Summary:

[202311][M0-2Vlan] Enable copp test on M0-2Vlan topo (#13719)

---

tests/common/devices/onyx.py

revert https://github.com/sonic-net/sonic-mgmt/pull/11763
Summary:
Revert the set_speed function in https://github.com/sonic-net/sonic-mgmt/pull/11763
For onyx fanout, we don't need to specify the lane number when setting speed. It will sync with dut automatically.
In https://github.com/sonic-net/sonic-mgmt/pull/11763, It will select the smallest lane 1, but some platforms don't support the smallest lane 1, so it will cause port not up. So we should let fanout sync with dut automatically.
Revert it
Run it on setup with onyx
mellanox

[Mellanox] Revert the set_speed function in https://github.com/sonic-net/sonic-mgmt/pull/11763

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
There is known issue in test_drop_counters.py::test_acl_drop on Cisco 8111 platform
There is known issue in test_drop_counters.py::test_acl_drop on Cisco 8111 platform
Skip the testcase in 202311 branch
======================================= short test summary info =======================================
SKIPPED [3] drop_packets/drop_packets.py: Cisco 8111 platform has known issue with test_acl_drop
=================================== 3 skipped, 1 warning in 34.96s ====================================

[202311 only]Skip test_drop_counters.py::test_acl_drop on Cisco 8111 platform

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
There is known issue in test_drop_counters.py::test_acl_drop on Cisco 8111 platform
There is known issue in test_drop_counters.py::test_acl_drop on Cisco 8111 platform
Skip the testcase in 202305 branch
======================================= short test summary info =======================================
SKIPPED [3] drop_packets/drop_packets.py: Cisco 8111 platform has known issue with test_acl_drop
=================================== 3 skipped, 1 warning in 34.96s ====================================

[202305 only]Skip test_drop_counters.py::test_acl_drop on Cisco 8111 platform

---

tests/test_posttest.py

Add function to collect logs from PTF container.
Summary:
Collecting PTF logs help debug issues that have failures in the PTF container. Flaky PTF tests result in intermittent errors in PTF nn can be observed with this change.
Add a function for log collection from PTF host to post test step.
Run the post-test step individually and observed the PTF logs are collected.
This change is not platform specific.
Any
Not applicable

Add PTF logs collection to post test step

---

.azure-pipelines/pr_test_scripts.yaml

In this PR, we move some stable scripts from onboarding dualtor PR checker to dualtor PR checker. 
Summary:
In this PR, we move some stable scripts from onboarding dualtor PR checker to dualtor PR checker. 
vms-kvm-dual-t0 | dualtor_mgmt/test_grpc_periodical_sync.py | 2024-07-22 00:00:00.0000000 | 6 | 0 | 6 | 1
vms-kvm-dual-t0 | dualtor_mgmt/test_server_failure.py | 2024-07-22 00:00:00.0000000 | 6 | 0 | 6 | 1
vms-kvm-dual-t0 | dualtor_mgmt/test_toggle_mux.py | 2024-07-22 00:00:00.0000000 | 12 | 0 | 12 | 1
vms-kvm-dual-t0 | dualtor_mgmt/test_grpc_periodical_sync.py | 2024-07-21 00:00:00.0000000 | 4 | 0 | 4 | 1
vms-kvm-dual-t0 | …

Move stable test scripts from onboarding test job to dualtor PR checker

---

docs/testbed/README.testbed.Setup.md
docs/testbed/README.testbed.VsSetup.md
docs/testbed/README.testbed.WANSetup.md
docs/testbed/sai_quality/DeploySAITestTopologyWithSONiC-MGMT.md

This PR adds documentation for setting up http_proxy/https_proxy for different type of testbeds.
Summary:
Some users run into the issues when setting up the testbed because the environment is under a proxy. The current documentation does not implicitly mention how to adjust the proxy settings when running a test bed.
Verified the proxy settings on [virtual switch test bed setup](https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testbed/README.testbed.VsSetup.md)

add http_proxy/https_proxy testbed setup information

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py

Summary:
The test_plan.py may run for over 24 hours polling test plan status if the test plan is in EXECUTING.
The test_plan.py script is wrapped in AzureCLI task which takes cares of az login. However, the az login session may expire after 24 hours. In this case, the test_plan.py script will fail to get access token for accessing Elastictest API to poll test plan status.
The workaround is run "az login" every 12 hours in test_plan.py to ensure that long running tests won't fail with getting access token.
To support the az login session, need to pass some more environment variables to the test_plan.py. The run elastictest pipeline yaml has been updated accordingly.
New variable `SONIC_AUTOMATION_SERVICE_PRINCIPAL` has been added to variable group `SONiC-Elastictest` on …

Fix az login timeout issue while running test_plan.py

---

tests/pfcwd/test_pfcwd_timer_accuracy.py

Summary:
27262192
The test_pfcwd_timer_accuracy failed due to "Failed: Real detection time is greater than configured: Real detect time: 1015 Expected: 800 (wd_detect_time + wd_poll_time)"
Add more information in the log, to monitor the status if hit the issue during the nightly build.
Locally run

Add more information log in pfcwd accuracy case for further debug

---

tests/saitests/py3/sai_qos_tests.py

Summary:
This PR is to fix `testQosSaiPfcXonLimit` in 202205 branch.
Basically, this PR is to backport PR https://github.com/sonic-net/sonic-mgmt/pull/12649 and https://github.com/sonic-net/sonic-mgmt/pull/12151 into 202205 branch to fix test regression.
This PR is to fix `testQosSaiPfcXonLimit` in 202205 branch.
Backport PR https://github.com/sonic-net/sonic-mgmt/pull/12649 and https://github.com/sonic-net/sonic-mgmt/pull/12151 into 202205 branch.
The change is verified on a T0 testbed.
```
^HPASSED                                                                                                                [  8%]
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_2] PASSED …
```

Fix testQosSaiPfcXonLimit in 202205 branch

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml
tests/flow_counter/flow_counter_utils.py
tests/route/test_route_flow_counter.py

Summary:
1. Add data plane route test to t1 PR test
2. Remove route flow counter test from t0 PR test since it's always be skipped for not support on KVM platform
Verify in KVM test

Add data plane route test to t1 PR test

---

tests/acl/test_acl.py

Reverts sonic-net/sonic-mgmt#12404
Introducing paramiko SSH may cause issue with running this script on testbeds with rotated passwords.
Discussed with PR author offline, using `duthost.script` may be able to workaround the logs of `duthost.shell` populated in DUT syslog issue.

Revert "Wait for create acl table/rule message to appear in syslog"

---

tests/qos/qos_sai_base.py

https://github.com/sonic-net/sonic-mgmt/pull/11000 only can handle multi-asic linecards. This fixes the limitation foro single ASIC linecards.
Summary:
Fixes #  https://github.com/sonic-net/sonic-mgmt/issues/13676
- [ X] Bug fix

[qos/t2] support single ASIC linecards

---

tests/platform_tests/conftest.py

**Backport #13714 and resolve conflict.**
On Mx topo, testbed doesn't use SFP interfaces (these ports are admin down). We need to exclude these interfaces from SFP related tests to avoid test failure when there is no cable connected on DUT.
Update xcvr_skip_list, for Nokia-7215 and Arista-720DT Mx, add Ethernet48, Ethernet49, Ethernet50, Ethernet51 to skip list.
Verified by running below testcases, all passed or skipped:
* platform_tests/sfp
* platform_tests/api/test_sfp.py
* platform_tests/test_xcvr_info_in_db.py
Summary:

[202311][Mx] Update xcvr_skip_list for Mx topo (#13714)

---

tests/ip/test_mgmt_ipv6_only.py

Summary: Add debug forced mgmt routes after fixture setup for MGMT IPv6 only
ADO: 28489789, 28451569
There're some random failures for MGMT IPv6 only TACACS test case, suspect the cause is unreachable ipv6 issue after fixture setup for MGMT IPv6 only.
```
Failed: Warning: Permanently added '2a01:111:e210:3000::a03:9289' (RSA) to the list of known hosts. Permission denied, please try again.
```
This PR is to check the issue's root cause along with ipv6 unreachable issue.
Add debug log to check if forced mgmt routes config is missing after fixture setup
```
18/07/2024 18:05:08 base._run                                L0071 DEBUG  | /var/src/sonic-mgmt-int/tests/common/devices/multi_asic.py::_run_on_asics#128: [strtk5-msn4600c-acs-02] AnsibleModule::command, …
```

Add debug forced mgmt routes after fixture setup for MGMT IPv6 only

---

tests/cacl/test_cacl_application.py

Summary:
Network mode of dhcp_server container is bridge, but it doesn't need cacl rule between container and bridge
Fix error
Run test

[cacl][dhcp_server] Fix test_cacl_application when dhcp_server is enabled

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
Mock dualtor test are already added in t0 test job, but it was wrongly added to onboarding t0 job by PR https://github.com/sonic-net/sonic-mgmt/pull/13722/
Remove from onboarding t0 job

Remove wrongly added dualtor test in onboarding t0 job

---

tests/telemetry/conftest.py
tests/telemetry/events/event_utils.py

Summary:
Skip tests relying on eventd feature, which is disabled on slim image by https://github.com/sonic-net/sonic-buildimage/blob/202311/files/build_templates/init_cfg.json.j2#L63

Skip eventd-related testing for eventd disabled on slim image

---

.azure-pipelines/pr_test_scripts.yaml

In this PR, we move some stable test scripts from onboarding t0 PR checker to t0 PR checker. 
Summary:
In this PR, we move some stable test scripts from onboarding t0 PR checker to t0 PR checker. 
Move some stable test scripts from onboarding t0 PR checker to t0 PR checker. 
vms-kvm-t0 | bgp/test_bgp_peer_shutdown.py | 2024-07-25 00:00:00.0000000 | 1 | 0 | 1 | 1
vms-kvm-t0 | clock/test_clock.py | 2024-07-25 00:00:00.0000000 | 3 | 0 | 3 | 1
vms-kvm-t0 | generic_config_updater/test_pfcwd_status.py | 2024-07-25 00:00:00.0000000 | 4 | 0 | 4 | 1
vms-kvm-t0 | generic_config_updater/test_pg_headroom_update.py | 2024-07-25 00:00:00.0000000 | 1 | 0 | 1 | 1 …

Move some stable scripts to T0 PR checker. 

---

tests/syslog/test_logrotate.py

Summary:
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/13451
On a chatty device, when the file size reaches 0.9 times the threshold, it quickly exceeds the limit, causing a false positive error by triggering log rotation.
Create a temporary file at half the threshold size to ensure ample space is available before the actual log rotation occurs.
Verified the test Mellanox 4700 testbed

Reduce the temp file size to verify logrotate for small_size test

---

tests/drop_packets/drop_packets.py

Drop counters test is flaky in checking syslogs. The logs check keeps failing on T2 topo even though the target log was there. Adding a delay before checking syslog can prevent this from happening. (We have made similar changes to ACL test before: https://github.com/sonic-net/sonic-mgmt/pull/10271)
Summary:
Fixes # (issue) Microsoft ADO 28740493
I ran the updated test and can confirm it's passing now.

fix: add sleep interval for log check to drop counters test

---

tests/qos/qos_sai_base.py

Summary:
Fix the qos/test_qos_sai.py test, where it is missing the new topo_t1-32-lag T1 topo
Make the tests more inclusive.
Adding the topo name to the topo list.
Tested it on hardware to verify.
https://github.com/sonic-net/sonic-mgmt/pull/13048

Fix qos/test_qos_sai.py test by adding new t1-32-lag topo

---

tests/snmp/test_snmp_psu.py

In this PR, we optimize the script `test_snmp_psu.py` to support running on kvm testbed. 
- Command `psuutil numpsus` will get the expected return code 2 on kvm testbed because of no chassis. So, on kvm testbed, we will return in advance. 
- There is no snmp psu infomation of kvm testbed. So we return in advance to skip the following checks. 
Summary:
In this PR, we optimize the script `test_snmp_psu.py` to support running on kvm testbed. 
- Command `psuutil numpsus` will get the expected return code 2 on kvm testbed because of no chassis. So, on kvm testbed, we will return in advance. 
- There is no snmp psu infomation of kvm testbed. So we return in advance to skip the following checks. 
Return in advance on kvm testbed to skip following checks.

Add script `test_snmp_psu.py` into T0 PR checker

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml
tests/dualtor/test_ipinip.py
tests/dualtor/test_orchagent_slb.py
tests/dualtor/test_tor_ecn.py
tests/dualtor/test_tunnel_memory_leak.py

Summary:
Add dualtor data plane test to onboarding dualtor job and skip traffic test
Test on KVM

Add dualtor data plane test to onboarding dualtor job

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml

Summary:
Add ip/radv test to pr test yml and mclag/nat/sflow test to skip yml
Test in KVM

Add ip/radv test to pr test yml and mclag/nat/sflow test to skip yml

---

tests/platform_tests/cli/test_show_platform.py

In PR #13424, we have optimized the code to fit for kvm testbed. But I notice that, in some kvm images, it includes the module `sonic_platform`, but in other images, they doesn't include. This will generate different return code while executing some commands. In this PR, we optimize the code to cover both situations.  
Summary:
In PR #13424, we have optimized the code to fit for kvm testbed. But I notice that, in some kvm images, it includes the module `sonic_platform`, but in other images, they doesn't include. This will generate different return code while executing some commands. In this PR, we optimize the code to cover both situations.  
Optimize the code to cover different situations.

Optimize `test_platform_serial_no` to handle module sonic_platform variations. 

---

.azure-pipelines/pr_test_skip_scripts.yaml
tests/snappi_tests/bgp/test_bgp_local_link_failover.py
tests/snappi_tests/bgp/test_bgp_remote_link_failover.py
tests/snappi_tests/bgp/test_bgp_rib_in_capacity.py
tests/snappi_tests/bgp/test_bgp_rib_in_convergence.py
tests/snappi_tests/lacp/test_add_remove_link_from_dut.py
tests/snappi_tests/lacp/test_add_remove_link_physically.py
tests/snappi_tests/lacp/test_lacp_timers_effect.py
tests/snappi_tests/test_multidut_snappi.py
tests/snappi_tests/test_snappi.py

Summary:
Meanwhile, we are using `.azure-pipelines/testscripts_analyse/` to static test scripts have been added or not, if a test script need to skip in KVM test, need to add it to `.azure-pipelines/pr_test_skip_scripts.yaml` and we would mark it as checked/covered.
Based on that, tgen/snappi/ptf test could not run on KVM platform, so need to add these tests to `.azure-pipelines/pr_test_skip_scripts.yaml`
Add tgen/snappi/ptf test scripts to `.azure-pipelines/pr_test_skip_scripts.yaml`

Add tgen/snappi/ptf test scripts to PR test skip yml

---

.azure-pipelines/pr_test_scripts.yaml
tests/cacl/test_cacl_application.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
According PR https://github.com/sonic-net/sonic-host-services/pull/139, the expected iptables rules are changed.
RP test will fail after https://github.com/sonic-net/sonic-host-services/pull/139, update the case accordingly.
add expected iptable rules
run cacl/test_cacl_application.py

Fix test_cacl_application for latest change in caclmgrd

---

tests/platform_tests/sfp/test_show_intf_xcvr.py
tests/platform_tests/sfp/util.py

Modified the checking of line[0] of the output of show int transceiver lpmode
```
show int transceiver lpmode
Port         Low-power Mode
```
The number of spaces between "Port" and "Low" are not constant.
It will change depending on how many letters and numbers are in the interfaces name. 
such as Ethernet2, Ethernet20, Ethernet200 
Summary:
To remove all spaces on the first line (Port         Low-power Mode) of output of "show int transceiver lpmode". These spaces could change.
Modified the checking of line[0] since the number of spaces could change
Tested the testcase on a multi cards multi Asics chassis

Modified the checking of line[0] of the output of show int transceiver lpmode

---

tests/qos/files/qos_params.j2c.yaml

Updated qos test params for 400g and 100g port speeds for the new vsq threshold introduced in   PR #https://github.com/sonic-net/sonic-buildimage/pull/18239
Summary:
The new   MMU settings to enhance performance for RDMA traffic in production.
Hence the qos_params needs to be tweaked according to the set buffer profiles.
However, the existing sonic-mgmt LossyQueueTest  doesn't fairly verify the buffer threshold for headroom for Lossy traffic. As per the new vsq profile setting the XOFF FADT threshold/PG is way lesser than the Nominal headroom, which limits it to not utilize the headroom buffer completely and send pause frames before reaching the MAX headroom limit.
Either the test case needs to be improvised by adding more source ports or a new test case should be added to …

[QoS]qos_yaml j2C+ changes for new _vsq thresholds

---

tests/qos/test_pfc_counters.py

Summary:
Enable qos/test_pfc_counters.py for all topologies.
Enable qos/test_pfc_counters.py for other topology.
Test it the following topology in local testbed. All successful.
- t0
- t1-32-lag
- dualtor-aa-56
- t2
Logs can be found in MSFT internal ADO 28837311

enable test case "test_pfc_counters.py"  for other topology

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

This test is intened for Warm boot scenario which does not apply to T1s.
Disabling this test for T1 devices.
Summary:
ADO: 27894767

Disabled test_critical_process_monitoring.py::test_orchagent_heartbeat for T1 devices

---

ansible/group_vars/all/ceos.yml
ansible/roles/vm_set/tasks/add_ceos_list.yml
ansible/roles/vm_set/tasks/probe_ceos_image_url.yml
ansible/vars/azure_storage.yml
docs/testbed/README.testbed.VsSetup.md

Summary:
To download cEOS image, the URL has to be composed using multiple components including ceosimage_saskey. This is complicated and unnecessary.
This change simplified the configuration of URL for downloading cEOS image. Just configure variable `ceos_image_url` in `ansible/group_vars/all/ceos.yml` is enough.
This change also enhanced the code logic to support configuring `ceos_image_url` as a string or a list of strings. When it is a string, the value is considered as a single URL. When it is a list of strings, each item in the list is considered as a URL. Playbook will try the images URLs one by one until downloading is successful.
The related document is updated too.
Tested add-topo.

Deprecate ceosimage_saskey for downloading cEOS image

---

tests/dash/templates/dash_set_eni_admin_state.j2
tests/dash/test_dash_disable_enable_eni.py

Summary:
This is to cover a test gap in sonic dash.
The test is to verify that after the ENI is disabled, the corresponding traffic should be dropped by the DPU. 
And the traffic should be restored after the ENI is enabled back.
Add a new test to cover the scenario of disable/enable ENI
Add a new test file tests/dash/test_dash_disable_enable_eni.py
Run the test on Nvidia BF3 standalone DPU testbed, it passed.
Only for standalone dpu testbed.
dpu topologys

[DASH] Add a new test to cover the scenario of disable/enable ENI

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skip vxlan IPv6 tunnel related test on Mellanox Specturm-1 switches
Summary:
Vxlan ipv6 tunnel is not fully supported on mellanox spc1 due to hw limitation
Skip vxlan ipv6 tunnel relatex test on mellanox spc1
Validated by internal regression
Mellanox spc1

[Mellanox] Skip vxlan ipv6 tunnel related test on mellanox Spectrum-1 switches

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

In test script `test_show_subinterface.py`, we want to create the subinterfaces and check the status of these new created ports. While testing, we find that the new created ports will not inherit the speed of their ancestor, which is not expected. We suspect it is an image issue, so, we create an [issue](https://github.com/sonic-net/sonic-buildimage/issues/19735) and use conditional mark to skip this case on vs testbed temporarily. As this case is skipped for now, we add it into PR checker, and after the issue is fixed, the case can run in PR test successfully. 
Summary:
In test script `test_show_subinterface.py`, we want to create the subinterfaces and check the status of these new created ports. While testing, we find that the new created ports will not inherit the speed …

Add show subinterface test into PR checker. 

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml
tests/common/dualtor/data_plane_utils.py
tests/dualtor_io/test_heartbeat_failure.py
tests/dualtor_io/test_link_drop.py
tests/dualtor_io/test_link_failure.py
tests/dualtor_io/test_normal_op.py
tests/dualtor_io/test_tor_bgp_failure.py
tests/dualtor_io/test_tor_failure.py
tests/dualtor_mgmt/test_ingress_drop.py

Summary:
Add dualtor_io data plane test to onboarding dualtor job and skip traffic test

Add dualtor io dataplane test to onboarding dualtor PR test

---

tests/override_config_table/test_override_config_table.py
tests/override_config_table/test_override_config_table_masic.py

Summary:
In override config table tests, test scripts import functions and variables from `tests/override_config_table/utilities.py` with `from utilitiese import`, but it may redirect to other files with same name `utilitiese.py` in other modules
```
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
override_config_table/test_override_config_table.py:7: in <module>
from utilities import backup_config, restore_config, get_running_config,\
E   ImportError: cannot import name 'backup_config' from 'utilities' (/azp/_work/3/s/tests/***/utilities.py)
_ ERROR collecting tests/override_config_table/test_override_config_table_masic.py _
ImportError while importing test module …
```

Fix import error in override config table

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
28489671
The test case failed in 202311 nightly test, and confirmed by case owner, it should be test case issue, and still working on the solution.
xfail the test case in 202311 branch to make the nightly build stable.
Run the case

xfail test_dscp_to_queue_mapping_uniform_mode

---

tests/pfcwd/test_pfcwd_timer_accuracy.py

Summary:
28273216
The test case failed in nightly build.
Should be related to the PR https://github.com/sonic-net/sonic-mgmt/pull/12733, which decrease the detect sleep time for test_pfcwd_timer_accuracy
Enlarge the detect sleep time
Run original case

update detect time in test_pfcwd_timer_accuracy

---

.azure-pipelines/pr_test_scripts.yaml

Some scripts are stable enough after we fixing them. So in this PR, we move these stable scripts from onboarding T0 PR checker to T0 PR checker. 
Summary:
Some scripts are stable enough after we fixing them. So in this PR, we move these stable scripts from onboarding T0 PR checker to T0 PR checker. 
Move some stable test scripts from onboarding T0 PR checker to T0 PR checker. 
vms-kvm-t0 | gnmi/test_gnmi_countersdb.py | 2024-07-31 00:00:00.0000000 | 248 | 0 | 248 | 1
vms-kvm-t0 | platform_tests/cli/test_show_platform.py | 2024-07-31 00:00:00.0000000 | 310 | 0 | 310 | 1
vms-kvm-t0 | platform_tests/test_link_down.py | 2024-07-31 00:00:00.0000000 | 62 | 0 …

Move some stable test scripts into T0 PR checker. 

---

tests/fib/test_fib.py

Change fib test to use Python 3. As of 202311 Python 3 should be used. Python 2 will no longer work as files with Python 3 syntax has been included.
Note: During backport, ensure all test cases have `is_python3=True` in the `ptf_runner()` function call. i.e. in 202311, 2 of the 4 test cases do not have the argument, where on the master branch 3 of the 4 test cases has it.
https://github.com/sonic-net/sonic-mgmt/blob/0310a4d29e47adcf2f592df3c2811d5b92d59f58/tests/fib/test_fib.py#L439
Summary:
Test no longer fails on SyntaxError.

Enforcing py3 to be used for fib tests

---

test_reporting/kusto/setup.kql
test_reporting/report_data_storage.py
test_reporting/report_uploader.py
tests/platform_tests/conftest.py

Summary:
After doing a warm/fast reboot, in the post-reboot analysis, include the hostname of the device. This information will then get uploaded into Kusto as a new column. The reason for this is that in case there are some device-specific oddities that cause some things to take longer on one device compared to another device, then this will help reveal them. It also makes it easier to see what device a certain run was done on, in case there needs to be some later debugging effort.
In addition, include the external tracking ID into Kusto, so that it's easier to match it to a specific pipeline run. Add a separate column for this, to make it easier to query for that.
The two new columns do mean that existing tables will need to be modified to support this.
Verified by …

Include hostname and tracking ID when uploading warm-reboot results to Kusto

---

ansible/module_utils/port_utils.py

Summary:
The file 'port_utils.py' has duplicate definition on both the Cisco-8101-O8C48 and Cisco-8101-C64 hardware SKUs, and remove Cisco-8101-T32 and Cisco-8101-C48T8.
To address the issue of duplicate definitions in the ‘port_utils.py’ file for both the Cisco-8101-O8C48 and Cisco-8101-C64 hardware SKUs. We will ensure a single, consistent definition.
I updated the ‘port_utils.py’ file to eliminate the duplicate definitions, this was after reviewing the ‘port_config.ini’ on the device.
To verify the changes, ensure that the 'port_utils.py' file was consistent with the 'port_config.ini' on the device.
Cisco-8000
N/A

update hwsku definitions in the port_utils.py file

---

.azure-pipelines/pr_test_scripts.yaml
tests/cacl/test_cacl_application.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
According PR https://github.com/sonic-net/sonic-host-services/pull/139, the expected iptables rules are changed.
Fix PR test failure in https://github.com/sonic-net/sonic-buildimage/pull/19732
modify expected iptable rules in test_cacl_application case due to image change.
skip cacl/test_cacl_application.py for 202405 branch temporarily

[202405]Fix test_cacl_application for latest change in caclmgrd

---

tests/common/fixtures/conn_graph_facts.py
tests/common/snappi_tests/port.py
tests/common/snappi_tests/snappi_fixtures.py
tests/conftest.py
tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
tests/snappi_tests/multidut/pfc/test_lossless_response_to_external_pause_storms.py
tests/snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py
tests/snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless_lossy.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossy.py
tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_burst_storm_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_m2o_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py

Summary:
For T2 testbed definition, the testbed DUTs will have both LCs and sup card:
```
- conf-name: vms-chassis-packet-dut
......
dut:
- lab-msft-lc0-1
- lab-msft-lc1-1
- lab-msft-lc2-1
- lab-msft-sup-1
comment: Chasiss Testbed
```
However, to run multidut cases, the testbed DUTs can only have LCs defined as the following:
```
- conf-name: vms-chassis-packet-dut-ixia
......
dut:
- lab-msft-lc0-1
- lab-msft-lc1-1
- lab-msft-lc2-1
comment: Chasiss Testbed
```
So, for same testbed, we have to define two testbed DUTs in testbed.yml:
- one with supervisor card for deploy-mg
- one without supervisor card for running multidut test cases.
When running multidut cases directly for T2 testbed, it has following issues.
```
1. fanout_graph_facts may be empty if supervisor is selected. That results …
```

[Snappi] support T2 testbed definition for multidut test cases

---

tests/common/snappi_tests/common_helpers.py

Support to enable PFCWD in Forward mode.
Summary:
#13752 
Providing support to enable PFCWD in forward mode.
Added a function 'start_pfcwd_fwd' with duthost and asic_value as parameters. If asic_value is not passed, then PFCWD in forward mode will be enabled in global mode.
Function first stops the PFCWD (in whatever mode it is operating), before enabling it in FORWARD mode.
Tested with function call with and without asic_value and checked if PFCWD was enabled on the DUT. If asic_value is passed, PFCWD is enabled for the specific ASIC in forward mode.

[Snappi] Support to enable PFCWD in Forward Mode

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml
tests/vxlan/test_vnet_vxlan.py
tests/vxlan/test_vxlan_bfd_tsa.py
tests/vxlan/test_vxlan_decap.py
tests/vxlan/test_vxlan_ecmp.py
tests/vxlan/test_vxlan_ecmp_switchover.py

Summary:
Add vxlan data plane test to onboarding t0/t1 PR test
Test on KVM

Add vxlan data plane test to onboarding t0/t1 PR test

---

tests/bgp/test_bgp_peer_shutdown.py

Support `bgp/test_bgp_peer_shutdown.py` on T2 topology
Summary:
Fixes # (issue) Microsoft ADO 28837065
We want to support as more test cases as possible on T2 topology
I ran the updated test on T0, T1 & T2, and I can confirm they all passed

feat: support BGP peer shutdown test on T2

---

tests/platform_tests/api/test_chassis_fans.py

This PR handles the flakyness in the testcase platform_tests/test_set_fans_speed caused when the testcase selects a very low or very high target speeds for the fans. The current wait time of 5 seconds is not enough for the fans to reduce their speed to reach the target speed value. 
Added a check to see if the difference between the target speed and actual speed is more than a particular value (40). If the difference is large enough, then change the wait time to 10 seconds from 5.
Ran the testcase multiple times to see if the testcase passes.
N/A
N/A

Fix flaky test_set_fans_speed when target speed is low

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/qos/qos_sai_base.py

Summary:
Add Cisco GR2 hwsku, setup test markings for appropriate support
New tests supported by GR2 being unskipped in this PR:
- testQosSaiPgHeadroomWatermark
Tests that were added for prior asics that are no longer needed:
- testQosSaiLosslessVoq (Not a VOQ switch)
- testQosSaiLossyQueueVoq (Not a VOQ switch)
- testQosSaiPGDrop (Was added to analyze 64B packet behavior on earlier asics. No longer needed as all tests will use 64B packets instead of earlier asicss larger 1350B size.)
- testQosSaiSharedReservationSize (Planning support for HdrmPool size test instead)
Initial high-priority GR2 test setup files.
Further code still under development is making use of these markings. 
Specific to cisco-8000.

Add Cisco GR2 hwsku, setup test markings for appropriate support

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py

Summary:
This change is to address the "az login" timeout after 24 hours issue.
The previous fix to run az login again using System.AccessToken is not working. The reason is that the System.AccessToken has expired when "az login" is executed in test_plan.py.
This change takes advantage of the "timeout" argument of test_plan.py. If test_plan.py has been running for like 20 hours, exit early with a different return code.
In the pipeline yaml, check return code of test_plan.py. If it is 0 or 2 (polling timeout), consider it as success.
The cancel test plan step still run with condition "always()". This step is updated to check TEST_PLAN_TYPE, if it is nightly, exit early to skip cancel test plan because the test plan could still be running.
Use draft PR to verify the change.

Skip cancel test plan for "NIGHTLY" test plan type

---

tests/common/utilities.py
tests/tacacs/test_ro_disk.py

Summary:
On some platforms, DUT cannot be recovered from RO-disk state by reboot. (e.g., On Nokia-7215, we saw the reboot is blocked by systemd-journald.service) To avoid DUT stuck at RO disk state, this PR introduce power-cycle as the final approach to recover DUT.
On some platforms, DUT cannot be recovered from RO-disk state by reboot. (e.g., On Nokia-7215, we saw the reboot is blocked by systemd-journald.service) To avoid DUT stuck at RO disk state, this PR introduce power-cycle as the final approach to recover DUT.
If reboot failed to recover DUT from RO disk state, try power-cycle to recover the DUT.
Verified on Nokia-7215 M0 testbed. Get test passed with below logs:
```
tacacs/test_ro_disk.py::test_ro_disk[dut-7215-4]
------------------------------------------------------------------ …
```

[test_ro_disk] Recover DUT to RW state by power-cycle when reboot doesn't work

---

tests/dhcp_server/dhcp_server_test_common.py
tests/dhcp_server/test_dhcp_server.py

Summary:
We should wait lease to wrote in the state_db before check and we should ignore error in pattern`.*Failed to get port by bridge port.*`
The test case failed because lease was not updated to state_db, we need to wait on it.
Wait on lease to be wrote to state db
Run test on DUT

[dhcp_server_test] wait lease to be wrote in state_db before check and ignore log error

---

tests/platform_tests/test_reload_config.py

Backport PR #13922 and #13361
For Nokia-7215, 120 seconds is not enough for `config reload` command. Extend the time to 180s to make testcase stable.
Set `config reload` timeout to 180s for Nokia-7215.
Verified on Nokia-7215 Mx testbed.
Summary:

[202405][Nokia-7215] Set timeout = 180s for config reload cmd

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Add test_acl_egress_drop to skip list on Cisco 8111 platform
This is 202311 branch only
Cisco 8111 platform doesn't support egress ACL counter.
Add test_acl_egress_drop to skip list on Cisco 8111 platform
Verify with Cisco 8111 physical testbed.
Cisco 8111 platform

[202311]Add test_acl_egress_drop to skip list on Cisco 8111 platform

---

tests/hash/generic_hash_helper.py

In sciprt `hash/test_generic_hash.py`, it needs to get asic type from the dict `dut_info`. But on kvm testbed, this dict doesn't have the key `asic_type`, which will cause the KeyError. In this PR, we use the function `get` to get the value in a dict, and if the key doesn't exist, we will return an empty string. 
Summary:
In sciprt `hash/test_generic_hash.py`, it needs to get asic type from the dict `dut_info`. But on kvm testbed, this dict doesn't have the key `asic_type`, which will cause the KeyError. In this PR, we use the function `get` to get the value in a dict, and if the key doesn't exist, we will return an empty string. 
Use the function `get` to get the value in a dict, and if the key doesn't exist, we will return an empty string.

Avoid KeyError in script `test_generic_hash.py` on kvm testbed. 

---

tests/arp/test_unknown_mac.py

Summary:
Updating the test to avoid using ip address that's already assinged to NIC interface (`soc_ipv4`).
Fixes # [aristanetworks/sonic-qual.msft#184](https://github.com/aristanetworks/sonic-qual.msft/issues/184)
Currently test is picking an ip address that isn't being used for server/ptf interfaces, and assigning this ip address to the ptf interface before pinigng the dut vlan. This will cause dut ARP and MAC tables to be populated for the relevant ip. 
In case of dualtor active-active topologies we have concept of nic-simulator, where we'll have an ip address for server nic as well (`soc_ipv4` field in 'show mux config') along with ptf interface ip (`server_ipv4`). And there will be gRPC traffic flowing b/w sonic dut and nic (with soc_ipv4). 
So updating the test to skip assigning an …

[dualtor-aa] Fix flakiness of arp/test_unknown_mac.py

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py
ansible/roles/eos/templates/dualtor-64-breakout-leaf.j2
ansible/roles/eos/templates/dualtor-aa-64-breakout-leaf.j2
ansible/roles/test/vars/testcases.yml
ansible/vars/topo_dualtor-64-breakout.yml
ansible/vars/topo_dualtor-aa-64-breakout.yml
tests/qos/qos_sai_base.py

Add definition of the two new dualtor breakout topology dualtor-64-breakout and dualtor-64-aa-breakout for hwsku Mellanox-SN4700-V64 test usage
Add support into related cases in regression test
Summary:
Add new topology definition for dualtor setup
Add definition of topology dualtor-64-breakout and dualtor-aa-64-breakout
Mellanox sn4700

Add definition of topology dualtor-64-breakout and dualtor-aa-64-breakout for hwsku Mellanox-SN4700-V64

---

ansible/module_utils/port_utils.py

This PR supports adding new hwsku (Nokia-7215-A1) to port utils.
Added Nokia-7215-A1 to port utils. 
Ran the add-topo, gen-mg to see if everything is correctly working.

Added Nokia-7215-A1 hwsku to port_utils

---

tests/arp/test_stress_arp.py

In script `test_stress_arp.py`, we will add as much ipv4 arp entries and ipv6 nd entries as we can. We will get this number from crm. But in fact, there is a probability of hash collision, which means we can not add such number entries as we expected. So in this PR, we tolerate this possible and set the percentage of hash collision 1%
Summary:
In script `test_stress_arp.py`, we will add as much ipv4 arp entries and ipv6 nd entries as we can. We will get this number from crm. But in fact, there is a probability of hash collision, which means we can not add such number entries as we expected. So in this PR, we tolerate this possible and set the percentage of hash collision 1%

Tolerate hash collision when adding entries in `test_stress_arp.py`

---

ansible/roles/test/files/acstests/py3/lag_test.py
tests/pc/test_lag_2.py

Bug fix for PR - #14001 
- Fix to enable python3 for `pc/test_lag_2.py -> acstest/lag_test.py`. 
- Fix error that fails in py3 environment
Summary:
Fix bug in PR #14001 
Enable the test to run in python 3 environment, and fix an issue in `lag_test.py`
Run test on `vs` testbed.
Not applicable to the change.
Not applicable
Not applicable

Enable Py3 and fix issue for lag test

---

tests/common/plugins/pdu_controller/__init__.py
tests/common/utilities.py
tests/tacacs/test_ro_disk.py

Backport #13974 and #12732 to 202311.
On some platforms, DUT cannot be recovered from RO-disk state by reboot. (e.g., On Nokia-7215, we saw the reboot is blocked by systemd-journald.service) To avoid DUT stuck at RO disk state, this PR introduce power-cycle as the final approach to recover DUT.
If reboot failed to recover DUT from RO disk state, try power-cycle to recover the DUT.
Verified on Nokia-7215 M0 testbed. Get test passed with below logs:
```
tacacs/test_ro_disk.py::test_ro_disk[dut-7215-4]
-------------------------------------------------------------------------------- live log call --------------------------------------------------------------------------------
10:02:17 test_ro_disk.do_reboot                   L0089 ERROR  | DUT did not go down, exception: run module command …
```

[202311][test_ro_disk] Recover DUT to RW state by power-cycle when reboot doesn't work

---

tests/configlet/util/common.py

Summary:
For T1 topo on boot there are some route table entries that already exist for Ethernet128 (test_add_rack uses this intf explicitly).
test_add_rack takes a snapshot of the DB at this point and after applying patch_add.json to config. It compares the two and succeeds.
test_add_rack now applies patch_rm.json. This removes the BGP_NEIGHBOUR and /INTERFACE/Ethernet128 entries. Once this happens, APPL_DB will purge it's ROUTE table entries for Ethernet128. Fix is to skip these entries for APPL_DB comparison. We also see the same issue for NEIGH_RESOLVE_TABLE entries; @wen587 confirmed we can skip these too.
The missing entries are:
```
ROUTE_TABLE:100.1.0.17
ROUTE_TABLE:20c0:a800::/64
ROUTE_TABLE:192.168.0.128/25
ROUTE_TABLE:2064:100::11
ROUTE_TABLE:192.168.0.0/25 …
```

Skip ROUTE_TABLE and NEIGH_RESOLVE_TABLE entries for test_add_rack.py

---

tests/platform_tests/test_intf_fec.py

sonic-mgmt: Adding a test case to verify FEC stat counters are valid for all the interfaces with SFP status present.
Additionally, fail the test for non-zero uncorrectable FEC errors.
Summary:
Use the command "show interfaces counters fec-stats" command to retrieve FEC stat counters
Verified on the lab devices with HWSku Mellanox 2700 and Mellanox 4600.

Add a sonic-mgmt test case to validate FEC stat counters

---

ansible/roles/test/templates/decap_conf.j2

Summary:
Fixes [#19381](https://github.com/sonic-net/sonic-buildimage/issues/19381)
With the introduction of subnet decap, the decap related db schma is changed, adapt `test_decap` to follow the new schema.
Change the template to use the new schema.
```
decap/test_decap.py::test_decap[ttl=pipe, dscp=uniform, vxlan=disable] PASSED                                                                                                                                                                                          [100%]'
```

[decap] Fix `test_decap` by using new db schema

---

ansible/roles/test/files/ptftests/py3/vxlan_traffic.py

improvement for flakiness of following tests:
1. vxlan.test_vxlan_ecmp.Test_VxLAN_ecmp_create.test_vxlan_configure_route1_ecmp_group_a
2. vxlan.test_vxlan_ecmp.Test_VxLAN_NHG_Modify.test_vxlan_remove_route2
Summary:
With this PR we have increased the no of test pkts sent before validating that each valid endpoint address has been used.
Fixes flakiness of the aforesaid tests in the description line.
some tests in vxlan ecmp tests were flaky.
increased the no of test pkts sent
Verified that the tests are passing consistently(5/5)
```
04:59:33.728  vxlan_traffic: INFO    : Sending 10 packets from port 0 to fddd:a150:a0::a31:1
04:59:33.770  vxlan_traffic: INFO    : Loop time:out 1000 milliseconds
04:59:33.786  vxlan_traffic: INFO    : Vxlan packets received:10, loop time:0.01598 seconds …
```

fix for intermittent failures in vxlan ecmp test suite

---

tests/common/config_reload.py

…run successfully
Summary:
The motivation for this change is to address flaky issues encountered during the test_ntp_ipv6_only test case. Specifically, the test case sometimes fails during teardown with the error “host unreachable” when running the config_reload function.
By adding the sleep function, we aim to ensure that the config_reload function can run successfully.
No more flaky issues for the testcase.

Test_ntp_ipv6_only flaky issue

---

tests/common/dualtor/server_traffic_utils.py
tests/dualtor/test_orchagent_slb.py

Summary:
Stablize `test_orchagent_slb`
1. show the output of `tcpdump` for debug purpose.
2. sleep for 5 seconds to allow `tcpdump` to have sufficient time to capture the packets.
```
dualtor/test_orchagent_slb.py::test_orchagent_slb[ipv4-active-standby] PASSED                                                                                                                                                                        [ 50%]
dualtor/test_orchagent_slb.py::test_orchagent_slb[ipv4-active-active] SKIPPED (Skip cable type 'active-active')                                                                                                                                      [100%] …
```

[dualtor] Improve `test_orchagent_slb`

---

tests/common/plugins/sanity_check/checks.py

Summary:
This is to fix the following issue:
```
04:21:44 utilities.wait_until                     L0140 ERROR  | Exception caught while checking _check_mux_status_helper:Traceback (most recent call last):
File "/azp/_work/8/s/tests/common/utilities.py", line 136, in wait_until
check_result = condition(*args, **kwargs)
File "/azp/_work/8/s/tests/common/plugins/sanity_check/checks.py", line 545, in _check_mux_status_helper
dut_wrong_mux_status_ports[:] = []
TypeError: 'set' object does not support item assignment
```
`dut_wrong_mux_status_ports` should be list all the time.
Run dualtor tests with sanity check.

[sanity check] Fix dualtor sanity check issue

---

.azure-pipelines/pr_test_scripts.yaml

In PR #13992, we add a batch of scripts into T1 PR checker. Now in this PR, we move some stable scripts into standard T1 PR checker. 
Summary:
In PR #13992, we add a batch of scripts into T1 PR checker. Now in this PR, we move some stable scripts into standard T1 PR checker. 
Move some stable scripts into standard T1 PR checker. 
vms-kvm-t1-lag | autorestart/test_container_autorestart.py | 2024-08-09 00:00:00.0000000 | 36 | 0 | 36 | 1
vms-kvm-t1-lag | bgp/test_bgp_gr_helper.py | 2024-08-09 00:00:00.0000000 | 2 | 0 | 2 | 1
vms-kvm-t1-lag | bgp/test_bgp_peer_shutdown.py | 2024-08-09 00:00:00.0000000 | 2 | 0 | 2 | 1
vms-kvm-t1-lag | bgp/test_bgp_queue.py …

Add stable t1 scripts into T1 PR checker

---

tests/snmp/test_snmp_link_local.py

Summary:
Modify snmp_link_local_test to test after configuring link local snmp agent address using config snmpagentaddress cli.
Pre requisite: https://github.com/sonic-net/sonic-utilities/pull/3215
```
Manual test:
admin@host:~$ sonic-db-cli CONFIG_DB keys "*SNMP*"
ACL_TABLE|SNMP_ACL
SNMP_AGENT_ADDRESS_CONFIG|10.1.1.1|161|
SNMP_AGENT_ADDRESS_CONFIG|fc00:2::32|161|
SNMP|LOCATION
SNMP_AGENT_ADDRESS_CONFIG|10.1.0.32|161|
SNMP_AGENT_ADDRESS_CONFIG|FC00:1::32|161|
SNMP_COMMUNITY|public
sudo config snmpagentaddress add fe80:1::32%eth0
admin@host:~$ sonic-db-cli CONFIG_DB keys "*SNMP*"
ACL_TABLE|SNMP_ACL
SNMP_AGENT_ADDRESS_CONFIG|10.1.1.1|161|
SNMP_AGENT_ADDRESS_CONFIG|fc00:2::32|161|
SNMP|LOCATION
SNMP_AGENT_ADDRESS_CONFIG|10.1.0.32|161| …
```

Modify snmp link local test to use config cli

---

ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/dhcp_relay/test_dhcp_relay.py

Summary:
There is useless parameter `testbed_mode` in test_dhcp_relay. Also, skip test in test case is insufficient
1. Remove useless parameter `testbed_mode`
2. Use condition mark to skip test
Run test in T0 / Dualtor testbeds, test passed

[dhcp_relay] Refactor dhcp_relay for dualtor

---

azure-pipelines.yml

Summary:
Querying Github issue no longer requires authentication. The GIT_SECRETS variable group is not needed now.
This change removed reference of the GIT_SECRETS variable group from azure pipeline yaml

Remove variable group GIT_SECRETS from PR testing pipeline yaml

---

ansible/roles/test/files/acstests/acltb_test.py

This PR migrates the test script `ansible/roles/test/files/acstests/acltb_test.py` to Python 3. 
_Note: The script is most likely deprecated and not being invoked._
Summary:
Migrate ACS tests to Python 3
Using `2to3`
Not verified as it is not being tested through any other tests or pipelines.
Not applicable
Not applicable.
Not applicable.

[acstests] Migrate acltb_test to Python 3

---

.azure-pipelines/pr_test_scripts.yaml
azure-pipelines.yml

Summary:
Currently we are adding more control plane and data plane test to PR test in master branch, and we added onboarding test job for piloting. When we are working on this goal, 202405 branch was created with onboarding test job, but it's not needed.
Remove onboarding PR test job in 202405 branch
Verify in PR test

[202405] Remove onboarding PR test job

---

tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml
tests/drop_packets/drop_packets.py
tests/drop_packets/test_drop_counters.py

Summary:
But some traffic test using ptfadapter can't be tested on KVM platform, we need to skip traffic test if needed.
Skip traffic test to make drop_packet test compatible with VS platform
Test on KVM

Make drop_packet test compatible with VS platform

---

tests/common/plugins/custom_fixtures/check_dut_asic_type.py

Summary:
Due to https://github.com/sonic-net/sonic-mgmt/pull/12824, `rand_one_dut_hostname` is None in fixture `check_dut_asic_type`
It throws failed on `setup with "IndexError: Bad index 'None' type `" in test case `test_ecmp_hash_seed_value`
Use `rand_one_dut_front_end_hostname` in stead of `rand_one_dut_hostname`
Run PR test case and `test_ecmp_hash_seed_value`

Fix IndexError: Bad index 'None' type in fixture check_dut_asic_type

---

tests/override_config_table/utilities.py

Remove temp golden config after reload config with golden config.
test_fallback_to_local_authorization_with_config_reload test case will reload config with AAA enabled.
After this test case, the golden config file will left on device, when some other code reload config, device will enable AAA and block other login again.
- Microsoft ADO: 28871521
Remove temp golden config after reload config with golden config.
Remove temp golden config after reload config with golden config.

Remove temp golden config after reload config with golden config.

---

tests/pfcwd/files/pfcwd_helper.py
tests/pfcwd/test_pfcwd_function.py
tests/pfcwd/test_pfcwd_warm_reboot.py

Add a common helper function to check if there are neighbor devices present before executing PFCwd warm reboot tests and PFCwd function tests. 
Summary:
Skip pytest execution for a selected subset of ports if 'rx_port' or 'rx_port_id' does not exist or contains None (e.g., 'rx_port_id' being None indicates there are no ports available to receive frames for fake storm in a t0 standalone topo) during PFCwd test setup. 
Added a common helper function to check if there are neighbor devices present. If there are no neighbor devices detected, skip pytest and exit the cleanup function early. 'rx_port' and 'rx_port_id' are expected to be conjugate attributes, if one is unset or contains None, the other should be as well.
In …

Update test scripts in PFCwd 

---

tests/pfcwd/files/pfc_detect_mellanox.lua
tests/pfcwd/test_pfcwd_all_port_storm.py

Summary:
This PR is to degrade the PFC storm detection logic on Mellanox platform to workaround the performance issue of leaf-fanout switch.
The `test_pfcwd_all_port_storm.py` is failing because leaf fanout switch can't send enough PFC pause frames to trigger PFC storm after PR https://github.com/sonic-net/sonic-swss/pull/3036 .
There are different workaround method on Onyx and Mellanox-SONiC leaf-fanout, but there is no workaround for DUT that is not connected to Mellanox leaf-fanout switch.
This PR workaround the issue by copying the old `pfc_detect_mellanox.lua` to degrade the PFC storm detection logic to make PFC storm easier to be triggered. 
As the test is to verify there is no issue when PFCWD is firing on all ports, this change doesn't change the coverage of test.
This PR …

Degrade PFC storm detection in PFCWD all ports storm test

---

.azure-pipelines/pr_test_scripts.yaml
tests/bgp/test_bgp_session.py
tests/common/devices/sonic.py

Summary:
26557087
FRR issue https://github.com/sonic-net/sonic-buildimage/issues/12380
Verify the bgp sessions' status
1: check all bgp sessions are up
2: inject failure, shutdown fanout physical interface or neighbor port
4: do the test, reset bgp or swss or do the reboot
5: Verify all bgp sessions are up
Run the test case
T0,T1

[test gap] add a new test case for bgp session check

---

ansible/roles/test/files/ptftests/py3/copp_tests.py

Recently, a change was made in the test_policer testcase in copp_tests.py to retain the default value of cir/cbs for queue4_group3 (default value for mgmt is 300) instead of changing it to 600 on the DUT during the testcase run. The PR for this change is here - https://github.com/sonic-net/sonic-mgmt/pull/12836.  For marvell based platforms like Nokia-7215-T1 and Nokia-7215-A1, the cir/cbs values are supported in steps of 125. Therefore, a value of 300 in the copp_cfg.json will set it to 250 internally since 300 is not in steps of 125.  This was confirmed by Marvell - "Per talk, the policer/ traffic metering can work in packet per-second mode. The granularity is in step of 125 pps. So it’s 125, 250 …etc  Minimum is 125."
The PPS_LIMIT_MIN and PPS_LIMIT_MAX is therefore set in the testcase …

Fixed copp/test_policer testcase for DHCP, DHCP6, LLDP and UDLD scenarios for marvell based platforms

---

tests/arp/test_unknown_mac.py

The DUT will occasionally (~5 mins) send a echo request through IPv6 to the PTF container. When the PTF container replies, it populates the fdb table. This is bad because the test expects the fdb table to be empty.
~Temporarily disabling IPv6 on the PTF container during the test will eliminate the problem.~
Temporarily disabling `arp_update` on the DUT during the test will eliminate the problem.
Summary:
Fixes #
Test was flaky. Monitoring tcpdump on the PTF container and the DUT's fdb table shows IPv6 echo is causing mac addresses to be learned on the DUT even though it was previously flushed.
Disable IPv6.
Disabling IPv6 will allow the test to consistently past. If IPv6 is re-enabled during the test and packets are sent, it immediately fails.

Fix arp/test_unknown_mac by disabling arp_update

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml
tests/dualtor_io/test_tor_failure.py

Summary:
dualtor_io/test_tor_failure.py would toggle dualtor's pdu, but pdu action should not be included in KVM test
Remove dualtor_io/test_tor_failure.py from PR test set

Remove dualtor_io/test_tor_failure.py from PR test set

---

ansible/library/extract_log.py

Script `platform_tests/test_cont_warm_reboot.py` will fail due to the below error on kvm testbed. 
```
22:11:18 verify_dut_health._wrapper               L0026 ERROR  | Health check run_reboot_testcase failed with unknown error: run module extract_log failed, Ansible Results =>
{"changed": false, "failed": true, "msg": "Traceback (most recent call last):\n  File \"/tmp/ansible_extract_log_payload_00d_trvf/ansible_extract_log_payload.zip/ansible/modules/extract_log.py\", line 306, in main\n  File \"/tmp/ansible_extract_log_payload_00d_trvf/ansible_extract_log_payload.zip/ansible/modules/extract_log.py\", line 275, in extract_log\n  File \"/tmp/ansible_extract_log_payload_00d_trvf/ansible_extract_log_payload.zip/ansible/modules/extract_log.py\", line 222, in extract_latest_line_with_string\n …
```

Add cont warm reboot into onboarding T0 PR checker. 

---

setup-container.sh

The idea is to improve the error message and start the stopped container instead of erroring out. The changes include -
- If caller runs `./setup-container.sh -d /var/src -n existing_container_name` the script simply starts the existing container instead of trying to create a new one and failing
- If the caller runs `./setup-container.sh -d /var/src` without the container name the script detects if a container with the local image tag exists and prints the command to start it.
Summary:
Enhance script to start stopped container. This prevents the user from cleaning old containers on dev machines and start new ones every time.
Run the script
Logged in
Not applicable
Not applicable
Not applicable

Add option to start existing / stopped container

---

tests/common/devices/aos.py
tests/common/devices/eos.py
tests/common/devices/fanout.py
tests/common/devices/ixia.py
tests/common/devices/onyx.py
tests/common/devices/sonic.py
tests/test_pretest.py

This PR adds a pre-test check to ensure the fanout switches for the DUT have LLDP disabled on them before starting the tests.
Summary:
Fixes # N/A
There have been incidents of fanout switches having LLDP enabled on them which leads to flaky test results due to unexpected entries in neighbor tables.
Implemented checks to ensure LLDP is disabled on fanout hosts for `eos` and `sonic` OSes.
Ran the test on `eos` fanout switches for testbeds.
Supports fanout switches that run `eos` and `sonic` only.
Not applicable
Not applicable

Add `is_lldp_disabled` method for fanout devices

---

tests/common/dualtor/data_plane_utils.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
In KVM dualtor test, dualtor_io/test_link_failure.py would fail because KVM testbed do not support fanout configuration
Skip testcases using fanout configuration with conditional mark

Fix KVM dualtor test error in dualtor_io/test_link_failure.py

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml

Summary:
KVM testbed doesn't support tunnel/decap functionality, so all standby scenario I/O tests should fail
Remove dualtor_io/test_normal_op.py from PR test set for now

Remove dualtor_io/test_normal_op.py from PR test set

---

ansible/templates/minigraph_png.j2

Summary:
Set device type to BackEndToRRouter or BackEndLeafRouter if enable_compute_ai_deployment is true during minigraph .xml generation.
sonic-mgmt-internal branch PR#6352
Set device type to BackEndToRRouter or BackEndLeafRouter if enable_compute_ai_deployment is true during minigraph .xml generation.
Verify with physical testbed internally.

Set device type to BackEnd if enable_compute_ai_deployment is true

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
Some dataplane test scripts have been added to PR test and put into optional onboarding job to test case performance, I calculated the success rate of test scripts in recent 5 days, I think I can move high success rate test scripts to t0/t1/dualtor job now
vms-kvm-dual-t0 | arp/test_arp_dualtor.py | 2024-08-15 00:00:00.0000000 | 24 | 0 | 24 | 1
vms-kvm-dual-t0 | dualtor_mgmt/test_ingress_drop.py | 2024-08-15 00:00:00.0000000 | 4 | 0 | 4 | 1
vms-kvm-t0 | generic_config_updater/test_dynamic_acl.py | 2024-08-15 00:00:00.0000000 | 24 | 0 | 24 | 1
vms-kvm-t0 | hash/test_generic_hash.py | 2024-08-15 00:00:00.0000000 | 20 | 0 | 20 | 1
vms-kvm-t1-lag …

Move some stable data plane test scripts to PR checker sets

---

tests/container_checker/test_container_checker.py

Summary:
Microsoft ADO: 28480805
We have used gnmi container to replace telemetry container, and telemetry is still enabled after warm upgrade.
Need new test for telemetry container not running error.
Modify the FEATURE table to emulate a warm upgrade, and use loganalyzer to detect possible error.

Add test for telemetry container not running error

---

tests/dhcp_server/dhcp_server_test_common.py
tests/dhcp_server/test_dhcp_server.py

Summary:
When running nightly test, sometimes, there are test cases failed on verify lease in state db.
After investigation, I found that it's because when ip assigned was expired it will be appended to the last line in lease file
and dhcpservd will choice that line. When two tests randomly select the same port, and the previous test didn't release the ip, the next test may fail, because dhcpservd will only pick the last record of that mac in lease file.
To fix that, we need to release ip assigned after test.
When running nightly test, sometimes, there are test cases failed on verify lease in state db.
Release ip assigned after test.
Run tests on testbed and monitor lease file to make sure every lease was released after the test.

[dhcp_server_test] fix test failure due to lease was not updated to state db

---

tests/common/reboot.py

There is another reboot cause `Unknown (First boot of SONiC version xxx)` on kvm besides `User issued xxx' command`, which will cause error `'NoneType' object has no attribute 'groups'` based on the current code. To address this, this PR suggests a conditional check to ensure that the match object is not None before attempting to access its 'groups' attribute, thereby preventing such issue.
Summary:
Fixes # (13979
)
There is another reboot cause `Unknown (First boot of SONiC version xxx)` on kvm besides `User issued xxx' command`, which will cause error `'NoneType' object has no attribute 'groups'` based on the current code. To address this, this PR suggests a conditional check to ensure that the match object is not None before attempting to access its 'groups' attribute, thereby …

Fix an error of checking reboot type. 

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

skip test_reboot_cause.py on x86_64-nvidia_sn4280-r0, because x86_64-nvidia_sn4280-r0driver doesn't support reset_from_asic and reset_reload_bios
Summary:
skip test_reboot_cause.py on x86_64-nvidia_sn4280-r0
skip test_reboot_cause.py on x86_64-nvidia_sn4280-r0
run the test on x86_64-nvidia_sn4280-r0
x86_64-nvidia_sn4280-r0

[Mellanox] skip test_reboot_cause.py on sn4280

---

tests/copp/test_copp.py

We see that after configuring 100 pps for queue4_group3, policer test for LLDP/UDLD have started failing on Cisco platforms. This PR skips policer test for LLDP/UDLD tests on Cisco platform for 202311. Once the issue is fixed we will remove this skip.
Summary:
Skip policer test for UDLD/LLDP on Cisco platforms for 202311
Skip policer test for UDLD/LLDP on Cisco platforms for 202311
Skip policer test for UDLD/LLDP on Cisco platforms for 202311
Verified that the tests are skippd
UT:
```
- generated xml file: /run_logs/ananshar/copp/test_copp.py::TestCOPP::test_policer[croc-aaa12-dut-UDLD]_2024-08-16-13-51-30.xml -
--------------------------------------- live log sessionfinish …
```

Policer test lldp udld cisco skip 202311

---

tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
tests/drop_packets/test_drop_counters.py

Summary:
In KVM platform, `test_drop_counters.py` would fail at `test_no_egress_drop_on_down_link` test because KVM do not support fanout configuration, and in `test_ip_pkt_with_exceeded_mtu` test, log analyzer would report error log `vlab-01 ERR kernel: [ 2955.389371] e1000 0000:03:02.0 eth31: Reset adapter`
Skip `test_no_egress_drop_on_down_link` in KVM platform and ignore log analyzer error "\.\*ERR kernel\.\*Reset adapter\.\*" in KVM platform

Fix drop counter test failure in KVM platform

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml

Summary:
In `test_orchagent_slb.py`, lower tor bgp session verify always fails, because TCP packets from lower tor to server would use dualtor tunnel with encap and decap, which do not support in KVM testbed.
Skip `test_orchagent_slb.py` in PR test.

Move dualtor/test_orchagent_slb.py to PR skip yaml

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/vxlan/test_vxlan_ecmp_switchover.py

Summary:
In KVM vxlan test, `vxlan/test_vxlan_bfd_tsa.py` would fail for `config_system_checks_passed` because system health and watch service in failed status, `vxlan/test_vxlan_ecmp_switchover.py` would fail for log analyzer error
For `vxlan/test_vxlan_bfd_tsa.py`, skip testcases using `config_system_checks_passed` by conditional mark with issue link
For `vxlan/test_vxlan_ecmp_switchover.py`, skip traffic test

Fix vxlan test failure in KVM t1-lag platform

---

tests/hash/generic_hash_helper.py

This is a code align for github issue #18766
Currently, CLI/SWSS doesn't have a way to normalize the IP mask notation regardless of what was provided by user.
The code change here is to only use dotted decimal notation when removing ip address.
Summary:
Currently, CLI/SWSS doesn't have a way to normalize the IP mask notation regardless of what was provided by user.
The code change here is to only use dotted decimal notation when removing ip address.

Align the test case to use mask in dotted decimal notation

---

tests/show_techsupport/test_auto_techsupport.py

Enhance show_techsupport script to avoid conflict of manual and cron triggered log rotate.
The conflict would lead to an error log of log rotate.
`ERR systemd[1]: Failed to start Rotate log files.`
Summary:
Enhance the test case to avoid conflict of manual and cron triggered log rotate.
During manual trigger log rotate, disable the cron log rotate function.
Internal regression.
No

Enhance show_techsupport script

---

tests/dut_console/test_console_baud_rate.py

Summary:
Fix the following issue:
```
def is_sonic_console(conn_graph_facts, dut_hostname):
>       return conn_graph_facts['device_console_info'][dut_hostname]["Os"] == "sonic"
E       KeyError: 'Os'
```
Some lab device console information doesn't have the `"Os"` attribute.
Let's retrieve it with an empty string as a default.
Run on dualtor.

[dualtor] Fix `test_console_baud_rate`

---

ansible/config_sonic_basedon_testbed.yml

Images below 202111 don't support command "--override_config", we need still use `config load_minigraph -y`  to deploy minigraph for devices who has image below 202111. Add a condition here if it failed to use `config load_minigraph --override_config -y`, then switch to old command `config load_minigraph -y`.
Summary:
Devices with images below 202111 fail to deploy minigraph due to command issue.
If it failed, switch to use old command.
Test on a device with 201911 image:
```
TASK [execute cli "config load_minigraph --override_config -y" to apply new minigraph] ***
Thursday 15 August 2024  18:40:35 +0000 (0:00:00.643)       0:02:00.380 ******* 
changed: [str-msn2700-20]
TASK [Print stderr] ************************************************************
Thursday 15 August 2024 …
```

Use config load_minigraph -y command for images which does not support "--override_config"

---

tests/common/snappi_tests/common_helpers.py

Function enable_packet_aging_after_test is defined in conf_test.py to be called as test-cleanup after test execution. This function calls enable_packet_aging defined in common/snappi_tests/common_helper.py. However, it does not pass the asic_value when calling this function. There is no check in enable_packet_aging function to handle this and it crashes.
Summary:
#13654 
To fix the enable_packet_aging during the test-cleanup. There is no asic_value defined when this function is called during test-cleanup and function does not have any check to handle this.
Added check to see if the asic_value is present or not. If the asic_value is present, then default code is executed. If the asic_value is not present, then function will enable packet aging for all ASICs present on the …

[Snappi] Fix for crash in enable_packet_aging_after_test called during test cleanup

---

tests/common/snappi_tests/snappi_fixtures.py
tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
tests/snappi_tests/variables.py

Summary: This PR enhances the logic for port selection for multidut RDMA cases based on the conf-name defined in the testbed.csv / testbed.yaml file. And also a generic fixture for single and multidut topology to get the snappi ports, dut port, asic_type, asic_value information
https://github.com/sonic-net/sonic-mgmt/issues/13389
https://github.com/sonic-net/sonic-mgmt/issues/13769
For enhancing the port selection logic and a generic fixture for single and multidut topology
Added a pytest fixture called get_snappi_ports and get_snappi_ports_for_rdma whcih selects the ports from the information provided in MULTIDUT_PORT_INFO in variables.py and the testbed info as shown below in testbed.csv
```
vms-snappi-sonic,vms6-1,ptf64,docker-ptf-snappi,snappi-sonic-ptf,10.36.78.59,,Ser …
```

[Fix]: Enhancement of port selection criteria for multidut RDMA cases based on testbed informaition

---

tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
tests/drop_packets/drop_packets.py

Signed-off-by: Austin Pham austinpham@microsoft.com
This pull request enhances the clarity of skip reasons for test cases and adds new conditions for skipping tests based on topology types.
`/tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml`: Improved skip reasons and added conditions for various test cases.
`/tests/drop_packets/drop_packets.py`: Updated tx_dut_ports fixture to skip tests based on topology type.
Summary:

feat: improved wording for skipped test case

---

tests/bgp/test_bgp_sentinel.py

Flaky failure will happen in test script `test_bgp_sentinel.py`. 
```
for route in ipv4_routes + ipv6_routes:
if 'no-export' in community:
>     pytest_assert(not is_route_advertised_to_ebgp_peers(duthost, route, ibgp_sessions),
"Route {} should not be advertised to bgp peers".format(route))
E     Failed: Route 100.1.0.17/32 should not be advertised to bgp peers
```
We suspect that DUT may not receive the update routes from ptf, which causes this failure. So in this PR, we add some debug  message to check if DUT receives the specific routes announced from ptf. 
Summary:
Flaky failure will happen in test script `test_bgp_sentinel.py`. 
```
for route in ipv4_routes + ipv6_routes:
if 'no-export' in community:
>     pytest_assert(not is_route_advertised_to_ebgp_peers(duthost, …
```

Add debug message for script `test_bgp_sentinel.py`

---

tests/show_techsupport/test_techsupport.py

The testcase test_techsupport_commands check if /proc/dma is expected in show techsupport output. For marvell based platforms, we need to remove this check for /proc/dma. This has been implemented for armhf based platforms. Adding the check for arm64 based platforms as well. 
Added a check for arm64 based platforms to remove /proc/dma from commands to check list.
ran the testcase test_techsupport.py entirely to see if all the testcases pass. 
NA
NA

added arm64 platform check to skip /proc/dma command check

---

tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
tests/drop_packets/drop_packets.py

If the skip logic is in the test body, the fixture still need to be done, in this test case, even the test need to be skipped,still need to finish the teardown of configure_copp_drop_for_ttl_error, and in the fixture, it has config reload which will take 2 mins to finish, since the test case need to be skipped, no need to waste 2 mins on it.
At the same time, change the config reload to use safe reload
Summary:

Move the skip for expired ttl test case logic to the conditional yaml file

---

tests/vlan/test_vlan_ping.py

Summary: Update the dualtor condition in test_vlan_ping.py
The PR #12306 updated `tests/vlan/test_vlan_ping.py`. It used a condition to check if it is a `dualtor` setup. But the dualtor topo name not only has `dualtor` or `dualtor-aa`, it also has other names such as `dualtor-64`. So we need to use a general check condition
```python
dualtor_topo = ["dualtor", "dualtor-aa"]
if tbinfo["topo"]["name"] in dualtor_topo:
vlan_table = duthost.get_running_config_facts()['VLAN']
```
Due to PR #12306 has not merged to 202311 branch, so this fix not back port to 202311. I will merge it after PR #12306 merge to 202311

Update the dualtor condition in test_vlan_ping.py

---

tests/system_health/test_system_health.py

When test mocks fan target speed and actual speed, it will cause fan tacho err, because the actual speed is not equal to target speed. This tacho err will exists until the whole test is finished, because we don't recover the mocked fan soft links until the test is finished. Therefore, when mocking the fan dir err, there will be two tc errors, so the  the pwm will be adjusted to 100, and the speed of fan also should be adjusted to full speed accordingly. But usually the fan speed cannot be adjusted to 100 in a short time, before it is adjusted to the full speed, there will be some waring msg such as "WARNING pmon#thermalctld: Fan low speed warning: fan*".
Summary:
Stablize the test_device_checker
Split test_device_checker into two
run the two tests on Mellanox device …

[Mellanox] Split test_device_checker into to two cases

---

tests/snmp/test_snmp_lldp.py

Signed-off-by: anamehra anamehra@cisco.com
Chassis LC does not have global lldp docker. Removing check for lldpLocManAddrTable for LC lldp.
Summary:
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/13405
Fixes: https://github.com/sonic-net/sonic-mgmt/issues/13405
Removed lldpLocManAddrTable check for modular chassis.
Run test_snmp_lldp.py on Modular chassis LC

[chassis]: Update test_snmp_lldp.py: skip lldpLocManAddrTable for LC

---

ansible/config_sonic_basedon_testbed.yml

Summary:
To enable support for the `Cisco-8122-O64` and `Cisco-8122-O128` device type as a BackEndLeafRouter
By adding `Cisco-8122-O64` and `Cisco-8122-O128` to the `hwsku_list_compute_ai` in the relevant configuration files.
No orchagent crash

[8122] change device type to BackEndLeafRouter

---

.azure-pipelines/recover_testbed/recover_testbed.py

There are many unhealthy testbeds which password is not incorrcet. And our auto recovery didn't cover this sistuation before. In this PR, we optimise related code. As long as the testbed is unreachable through ssh, not matter which sistuation, we will reimage the testbed from boot loader. 
Summary:
There are many unhealthy testbeds which password is not incorrcet. And our auto recovery didn't cover this sistuation before. In this PR, we optimise related code. As long as the testbed is unreachable through ssh, not matter which sistuation, we will reimage the testbed from boot loader.

Recover testbeds which password is incorrect. 

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
`dualtor/test_switchover_failure.py` has a high failure rate around 46% in KVM test, need to skip temporary to unblock PR test
Create issue https://github.com/sonic-net/sonic-mgmt/issues/14247 and skip `dualtor/test_switchover_failure.py` in KVM platform

Skip dualtor/test_switchover_failure.py test with issue

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py
ansible/roles/eos/templates/dualtor-64-breakout-leaf.j2
ansible/roles/eos/templates/dualtor-aa-64-breakout-leaf.j2
ansible/roles/test/vars/testcases.yml
ansible/vars/topo_dualtor-64-breakout.yml
ansible/vars/topo_dualtor-aa-64-breakout.yml
tests/qos/qos_sai_base.py

Add definition of the two new dualtor breakout topology dualtor-64-breakout and dualtor-64-aa-breakout for hwsku Mellanox-SN4700-V64 test usage
Add support into related cases in regression test
It's the conflict handle of original PR #13980.
Summary:
Add new topology definition for dualtor setup
Add definition of topology dualtor-64-breakout and dualtor-aa-64-breakout
Mellanox sn4700

[202311]Add definition of topology dualtor-64-breakout and dualtor-aa-64-breakout for hwsku Mellanox-SN4700-V64

---

tests/qos/files/cisco/qos_param_generator.py

For multi flows, packet count of packet size 64B exceeds G100 packet descriptor limit.
G100 voq size is 64k buffers, compared to Q200 voq size 16k buffers.
Summary:
Increase packet size for MultiSrc case.
Fix case testQosSaiLossyQueueVoqMultiSrc failure in G100.
Increase packet size.
Verified it on 8111 testbed.
============================================================================================= PASSES ==============================================================================================
_____________________________________________________________________ TestQosSai.testQosSaiLossyQueueVoqMultiSrc[single_asic] _____________________________________________________________________
---------------------------------- generated xml file: …

Adjust packet size for testQosSaiLossyQueueVoqMultiSrc

---

tests/acl/test_acl.py
tests/common/port_toggle.py

In the last chassis sync meeting, we agreed on the following changes to `acl/test_acl.py` to make it more stable on T2 chassis:
1. Increase the reboot wait time
2. Increase the wait time for port toggle to 5 min for both up and down
3. Increase the `aclshow -a` wait time
In this PR, we have increased the reboot wait time by enabling `safe_reboot` and increased the wait time for port toggle to 5 min if it is a chassis. The `aclshow -a` wait time increase has been included in #13858.
Summary:
Fixes # (issue) Microsoft ADO 29182672
Make `acl/test_acl.py` more stable on Cisco T2 chassis
I ran the updated test on Cisco T2 chassis and made sure the changes are in-place.

fix: add extra wait time for ACL test

---

.gitignore
tests/common/helpers/inventory_utils.py
tests/common/helpers/yaml_utils.py
tests/conftest.py

Support to trim the useless topology neighbor the inv_files according to testbed to speed up ansible inventory initialization.
Summary:
Fix conflict and cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/14246
Trim the useless topology neighbor the inv_files according to testbed to speed up ansible inventory initialization.
For every test server, we pre-define ~100 ansible_hosts for the neighbors.
We put all of the ansible_hosts of test servers into one inventory file.
The inventory file contains thousands of ansible_hosts, but most of them are useless to the selected testbed,
Because the testbed only need the definition of the neighbor for its neighbor server.
During the establishment of the ansible_host, it iterate and compute the ansible_host one by one,
The useless ansible_host …

[Feat]Support to trim inventory files (#14246)

---

tests/common/helpers/portchannel_to_vlan.py
tests/vlan/test_vlan.py

Summary:
Fix failed test cases when sending packets to portchannel interfaces in a T0 standalone topology.
Added a common helper function to check if ansible_facts contain non-empty portchannel interfaces and portchannels. The test is skipped if no portchannel interfaces are detected. For example, when sending packets to an egress port with PVID 0 on a portchannel interface, the absence of portchannel interfaces means the expected destination does not exist.
In tests/vlan/test_vlan.py:
```
========================================================================================= short test summary info =========================================================================================
SKIPPED [1] vlan/test_vlan.py:168: Test skipped: No …
```

skip test when no portchannel interfaces are detected

---

tests/bgp/test_bgp_session.py

Summary:
The session turning down time is much longer on the kvm than on the physical device, on kvm need more than 60s to down while the timeout in case is 60s, then caused the failure.
kvm
https://elastictest.org/scheduler/testplan/66c75e63e97672c662eb2109?testcase=bgp%2Ftest_bgp_session.py&type=log
22/08/2024 16:21:48 utilities.wait_until                     L0125 DEBUG  | Wait until check_bgp_session_state is True, timeout is 30 seconds, checking interval is 5, delay is 0 seconds
22/08/2024 16:23:02 utilities.wait_until                     L0135 DEBUG  | Time elapsed: 62.065256 seconds
...
22/08/2024 16:23:04 utilities.wait_until                     L0150 DEBUG  | verify_bgp_session_down is True, exit early with True
Physical device …

enlarge timeout for test_bgp_session_interface_down

---

tests/ecmp/test_fgnhg.py

Summary:
Fixes # fg_ecmp tests
fg_ecmp test failed because arp and ndp tables are not cleaned before main tests
added sonic-clean commands on top of main tests
Tested the script

Added sonic-clears on beginning of stup_neighbors

---

tests/ssh/test_ssh_limit.py

Improve test_ssh_limit test case not receive EOF issue
test_ssh_limit randomly failed, according to syslog, the paramiko connection does not receive EOF after exec command.
- Microsoft ADO: 28874779
Read stdout and stderr after exec command via paramiko, and print output for debug
Improve test_ssh_limit test case not receive EOF issue

Improve test_ssh_limit test case not receive EOF issue

---

tests/tacacs/test_ro_disk.py

Improve test_ro_disk logrotate failed because auth.log missing issue.
test case  test_ro_disk failed because following error:
error: stat of /var/log/syslog failed: Bad message
du: cannot access '/var/log/auth.log': Bad message
- Microsoft ADO: 29020193
Improve test_ro_disk logrotate failed because auth.log missing issue.
Improve test_ro_disk logrotate failed because auth.log missing issue.

Improve test_ro_disk logrotate failed because auth.log missing issue.

---

ansible/roles/test/files/ptftests/arista.py
tests/platform_tests/conftest.py

Summary:
Fix platform_tests/test_advanced_reboot.py::test_warm_reboot, [Issue #11816 ](https://github.com/sonic-net/sonic-mgmt/issues/11816) where FEB29 raises ValueError exception during date parsing function strptime.
Added code to check if current year is leap year to prevent this false exception, where default year used during date parsing was year 1900, not a leap year.
Pipeline failure back in 2024 FEB 29, where tests failed during test_warm_reboot, due to default year(1900) not a leap year, which makes 1900FEB29 an invalid date to parse.
Change local time to FEB29 to check if new change can handle the day as expected.

Fix leap year FEB29 causing ValueError exception in test_warm_reboot

---

tests/generic_config_updater/test_mgmt_interface.py

Add GCU mgmt-interface test case
Need verify GCU update forced_mgmt_routes scenario.
- Microsoft ADO: 28707715
Add GCU mgmt-interface test case.
Add GCU mgmt-interface test case.

Add GCU mgmt-interface test case

---

tests/common/helpers/bgp.py

Summary:
-  This PR fixes issue on '_test_bgp_peer_shutdown_.py', when the test runs on T2 multi-asic dut.
-  Whole test operates on one of the asic but during bgp teardown session; while removing newly added neighbor config, test runs sonic-db-cli command on both asics of the dut, which creates a dummy neighbor entry on the other asic. 
- Due to this, test fails with the following reason,
```
with capture_bgp_packages_to_file(duthost, "any", bgp_pcap, n0.namespace):
n0.teardown_session()
if not wait_until(
WAIT_TIMEOUT,
5,
20,
lambda: is_neighbor_session_down(duthost, n0),
):
>                       pytest.fail("Could not tear down bgp session")
E                       Failed: Could not tear down bgp session
```
- Test creates a dummy bgp neighbor entry on the other asic, …

BGP [T2] - Update neighbor admin down only for specific asic under test

---

tests/dualtor_io/test_tor_bgp_failure.py
tests/log_fidelity/test_bgp_shutdown.py
tests/route/test_default_route.py

Summary:
Ignore unexpected logs seen in tests performing bgp shutdown.
Fixes # [aristanetworks/sonic-qual.msft#180](https://github.com/aristanetworks/sonic-qual.msft/issues/180)
Currently, tests `dualtor_io/test_tor_bgp_failure.py`, `log_fidelity/test_bgp_shutdown.py` and `route/test_default_route.py` which have testlets performing bgp shutdown are failing during teardown because of unexpected logs `SAI_API_TUNNEL:_brcm_sai_mptnl_*`.  Otherwise, these tests would be passing.
For each of the failing tests added/updated autouse fixture `ignore_expected_loganalyzer_exception` to make `log_analyzer` to ignore `SAI_API_TUNNEL:_brcm_sai_mptnl_*` logs.
Stressed the failing tests on `Arista-7260CX3-D108C8` and `Arista-7050CX3-32S-C32` skus and tests are passing with the changes.

[dualtor] Ignore syncd's SAI_API_TUNNEL:_brcm_sai_mptnl* logs

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/vlan/test_vlan_ping.py
tests/vxlan/test_vxlan_crm.py

Summary:
`vlan/test_vlan_ping.py` failed in PR test in verify traffic, which is not supported in KVM
`vxlan/test_vxlan_crm.py` has log analyzer failure for mismatch vnet routes '150.0.9.1/32' and '150.0.8.1/32' in asic db
Skip traffic test in `vlan/test_vlan_ping.py` 
Created issue https://github.com/sonic-net/sonic-mgmt/issues/14311 for vnet routes mismatch, xfail test with issue
Test in KVM

Fix vlan/test_vlan_ping.py and vxlan/test_vxlan_crm.py failure

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
In master branch, we added some data plane test to PR checker with skipping traffic test, but fixtures to skipping traffic test didn't sync to 202405, and in 202405, some vlan test has added traffic validation
202405 branch is not in our test set expand scope, , so remove vlan data plane test from PR checker in 202405, test in master branch is enough

[202405] Remove some vlan test from PR checker list

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Test cases xpassed in ntp/test_ntp.py, I found that the xfail marker was added to the NTP test cases due to iburst not being enabled by default in #13501 
Remove xfail for NTP test case as iburst option has been enabled for NTP servers in [#19424](https://github.com/sonic-net/sonic-buildimage/pull/19424)
In ntp/test_ntp.py
```
----------------------------------------------------------------------------------------- live log sessionfinish ------------------------------------------------------------------------------------------
07:34:37 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs
================================================================================ 6 passed, 1 …
```

remove xfail as iburst option has been enabled for NTP servers

---

tests/stress/conftest.py

Summary:
This is to cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/14162 into 202311
If there are neighbors left on the target device of dualtor testbed, the presence of tunnel routes of those neighbors on standby mux ports will be counted in the ipv4/ipv6 route crm counters; and if those neighbors are expired during test_stress_route, those tunnel routes will be removed, the ipv4/ipv6 route crm counters after the test will be less than those before the test.
Let's cleanup the neighbors on dualtor testbed and stop any arp-related ptf services(arp_responder and garp_service) if any.

[202311][dualtor] Fix `test_stress_route` (#14162)

---

tests/tacacs/test_accounting.py

Imporve TACACS accounting test case, add debug information
TACACS local accounting test case randomly failed
- Microsoft ADO: 28837312
Add debug information, check TACACS config file generated correctly
Imporve TACACS accounting test case, add debug information

Imporve TACACS accounting test case, add debug information

---

tests/common/plugins/sanity_check/__init__.py

Summary:
Extract the recover of sanity check failure into a single method,
enable sanity check recover in post canity test.
If the pre sanity check failed, all the test module are marked as failed.
With post sanity check, we can kick out the testbed immediately after the test module finished, rather than on the beginning of the next test module.
Extract the recover of sanity check failure into a single method,
enable sanity check recover in post canity test.
On physical testbeds, both the recover of pre/post sanity check works as expected.

[Feat] Enable recover in the post sanity check

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

This PR disables the restapi test_create_vrf for non-T1 platforms as this is not a valid use case for restapi.
Summary:
- [] 202305
The restapi create vrf scenario is not used in production for TOR devices. This test has intermittent pass rate and rakes up failure rate.

disabled test_restapi::test_create_vrf for non-t1 platforms.

---

tests/configlet/util/common.py

Summary:
For T1 topo on boot there are some route table entries that already exist for Ethernet128 (test_add_rack uses this intf explicitly).
test_add_rack takes a snapshot of the DB at this point and after applying patch_add.json to config. It compares the two and succeeds.
test_add_rack now applies patch_rm.json. This removes the BGP_NEIGHBOUR and /INTERFACE/Ethernet128 entries. Once this happens, APPL_DB will purge it's ROUTE table entries for Ethernet128. Fix is to skip these entries for APPL_DB comparison. We also see the same issue for NEIGH_RESOLVE_TABLE entries; @wen587 confirmed we can skip these too.
The missing entries are:
```
ROUTE_TABLE:100.1.0.17
ROUTE_TABLE:20c0:a800::/64
ROUTE_TABLE:192.168.0.128/25
ROUTE_TABLE:2064:100::11
ROUTE_TABLE:192.168.0.0/25 …
```

Skip ROUTE_TABLE and NEIGH_RESOLVE_TABLE entries for test_add_rack.py for 202311

---

tests/telemetry/conftest.py
tests/telemetry/events/event_utils.py

Summary:
Fixes # (issue) 28728116
Disable tests for multi asic as structured events are not fully supported for 202311
Skip multi asic
Manual

Disable test events for multi-asic

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
Some dataplane test scripts have been added to PR test and put into optional onboarding job to test case performance, I calculated the success rate of test scripts in recent 5 days, I think I can move high success rate test scripts to t0/t1/dualtor job now
TestbedName | FilePath | TestCase | SuccessCount | FailureCount | TotalTests | SuccessRate
vms-kvm-dual-t0 | dualtor_io/test_link_failure.py | test_active_link_down_upstream[active-standby] | 40 | 0 | 40 | 1
vms-kvm-dual-t0 | dualtor_io/test_link_failure.py | test_active_link_down_upstream[active-active] | 40 | 0 | 40 | 1
vms-kvm-dual-t0 | dualtor_io/test_link_failure.py | test_active_link_down_downstream_active[active-standby] | 40 | 0 | 40 | 1
vms-kvm-dual-t0 | …

Move stable data plane test to PR checker sets

---

tests/bgp/test_bgp_queue.py

Summary: only test eBGP neighbors for test_bgp_queues
Complete #11116 
T2 profile

Fix only test eBGP neighbors for test_bgp_queues

---

tests/tacacs/test_ro_disk.py

Summary:
In PR #13974, I introduced PDU reboot to recover the DUT from RO-Disk state when regular `sudo reboot` fail to do that. However, the `do_reboot` function may raise `pytest_ansible.errors.AnsibleConnectionFailure` which is not be handled. In this case, the PDU reboot part cannot be executed and DUT cannot be recovered.
In this PR, I enhance the code from below perspectives:
1. Handle `pytest_ansible.errors.AnsibleConnectionFailure` in `do_reboot` function.
2. Add `try-except` block for `do_reboot` to ensure no matter what Exception is raised, PDU reboot can always be executed to recover the DUT.
In PR #13974, I introduced PDU reboot to recover the DUT from RO-Disk state when regular `sudo reboot` fail to do that. However, the `do_reboot` function may raise …

Enhance test_ro_disk to ensure device finally be recovered by PDU reboot

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Cisco 8111 compute-ai platform does not support BBR.
Skip the testcase.
N/A

Skip test_bgp_bbr.py with Cisco 8111 compute-ai platform

---

ansible/roles/test/files/ptftests/py3/advanced-reboot.py

There is a certain probability that the script `test_cont_warm_reboot.py` fails because of the error `IO didn't come up within warm up timeout. Control plane: up, Data plane: partial`. It means data plane is not up within our specify time(300s). In this PR, we add the debug message to see how long it will take to bring up data plane. 
Summary:
There is a certain probability that the script `test_cont_warm_reboot.py` fails because of the error `IO didn't come up within warm up timeout. Control plane: up, Data plane: partial`. It means data plane is not up within our specify time(300s). In this PR, we add the debug message to see how long it will take to bring up data plane. 
Add the debug message to see how long it will take to bring up data plane.

Add debug message in script `advanced-reboot.py`

---

tests/acl/test_acl.py
tests/conftest.py

Summary:
core_dump_and_config_check will issue config_reload to the duthosts after test module finished and if there's coredump or config_db changes.
For now, it simply issues the config_reload command then returns and finishes.
For the testbeds that require more time to be ready, it possibly fails on the sanity check of the next test module.
Hence enable the readiness check of the config_reload.
Enable the readiness check.

Enable readiness check in the config_reload of the core_dump and config check

---

tests/pfcwd/test_pfcwd_warm_reboot.py

Summary:
29093771
The case is flaky, failed sometimes.
Add healthy check after warm reboot to determine whether the failed caused by warm-reboot or pfcwd
Local run the case

add healthy check after warm reboot for test_pfcwd_wb

---

tests/pfcwd/test_pfcwd_warm_reboot.py

Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/14320 conflict
merge manually.
Add healthy check after warm reboot to determine whether the failed caused by warm-reboot or pfcwd
Local run the case
Summary:

[202405] add healthy check for pfcwd wb (#14320)

---

tests/pfcwd/test_pfcwd_warm_reboot.py

Cherry-pick conflict
create this PR manually
Add healthy check after warm reboot to determine whether the failed caused by warm-reboot or pfcwd
Local run the case
Summary:

[202311] add healthy check for pfcwd wb (#14320)

---

tests/conftest.py
tests/fdb/test_fdb_mac_move.py
tests/stress/conftest.py
tests/stress/test_stress_routes.py

Summary:
The case failed sometimes due to cannot found the log.
It should be related to the small storage, since the var/log size limitation, logrotate would remove the previous syslogs during the test, then cause loganalyzer cannot find the previous log and teardown failure.
It is caused by storage resource limitation, could not fix the issue, this PR is a workaround.
Since set the syslog to error lever and update the logroate to compress log immediately during the test still failed sometimes. Create a thread to do the logrotate every 60s during the test.
https://elastictest.org/scheduler/testplan/66d1ebb7f90c6cd947f4dd3e

update rsyslog fixture to workaround /var/log size limitation

---

tests/pc/test_lag_2.py
tests/stress/test_stress_routes.py

Summary:
Fixes # 10147
There was failure in chassis with multiple linecards (multi-dut scenario) seen in test_stress_routes, test_lag_2. This was because when these tests are run on chassis and not on a specific dut, the route check ERR occurs on the other duts than the dut which is under test.
In case of a chassis system, interface/pc flap on a particular linecard (dut) will cause route churn in other linecards(duts) and hence this PR addresses this.
As explained in Summary
Add the log analyzer skip message to all duts other than supervisor.
This fix should work for single asic sonic devices as duthosts.frontend_nodes will cover those cases too.
```
stress/test_stress_routes.py::test_announce_withdraw_route[svcstr-xxxx-lc3-1-1]  PASSED …
```

Fix routeCheck failures in tests for chassis : test_stress_routes, test_lag_2

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Skip test_bgp_allow_list.py for Cisco 8111 T1 compute ai deployment
Skip test_bgp_allow_list.py for Cisco 8111 T1 compute ai deployment
Because we don't use route-map like: ALLOW_LIST_DEPLOYMENT_ID_0_V4, ALLOW_LIST_DEPLOYMENT_ID_0_V6
Skip the testcase.
N/A
Cisco 8111 T1 Compute AI deployment.

Skip test_bgp_allow_list.py for Cisco 8111 T1 compute ai deployment

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml

Summary:
While adding test scripts to PR test, found there are some existing or newly added test scripts needs to skip in PR test, and `arp/test_neighbor_mac.py` was in incorrect topo
Add voq test to skip yml for T2 is not supported in PR test
Add newly added snappi_tests/multidut/bgp test to skip yml for snappi and tgen topo are not supported in PR test
Add macsec/test_interop_wan_isis.py to skip yml for wan topo no longer supported in PR test
Add read_mac test to skip yml for test variable not supported in PR test and it's also skipped in nightly
Move `arp/test_neighbor_mac.py` to t1 PR test for it do not supported on T0
Run `arp/test_neighbor_mac.py` in T1 for multiple times in KVM platform

Add data plane test to PR test set and skip set

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/vxlan/test_vxlan_crm.py

Summary:
When running `vxlan/test_vxlan_crm.py`, there is a chance to get `missed_in_asic_db_routes` error in log analyzer for KVM
Since `missed_in_asic_db_routes` has been ignored in other test scripts in vxlan module, ignore in `vxlan/test_vxlan_crm.py` test for KVM
Remove conditional mark xfail but keep mgmt issue https://github.com/sonic-net/sonic-mgmt/issues/14311 open
Test in KVM

Ignore `missed_in_asic_db_routes` error in `vxlan/test_vxlan_crm.py` test for KVM

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py

[CI]Fix inconsistency issue of pipeline and test plan
The issue is that pipeline said the test job passed but test plan failed. It's the inconsistency issue of polling test plan status.
One example is: 
https://dev.azure.com/mssonic/build/_build/results?buildId=631446&view=logs&jobId=f1a75c01-4f64-5de9-bd52-755062a8a04a&j=f1a75c01-4f64-5de9-bd52-755062a8a04a&t=9246549a-3ee7-52ff-a097-753e4679a4f2
To fix the bug, need to check current step staus, if it's None and current test plan failed. Need to fail the pipeline step.
See description.
See description.
Raised Daft PR to vefify: https://github.com/sonic-net/sonic-mgmt/pull/14386
The expected behavior is: It failed on every test job.(Because hard-code pre-test fail). Not passed anyone any more. …

[CI]Fix inconsistency issue of status between pipeline and test plan

---

tests/common/config_reload.py
tests/common/helpers/parallel_utils.py
tests/common/plugins/sanity_check/__init__.py
tests/common/plugins/sanity_check/checks.py
tests/common/plugins/sanity_check/recover.py
tests/common/reboot.py
tests/conftest.py

Summary:
1. Extend the wait time of the readiness check for chassis devices
2. Provide a modular-chassis specific recover way, for example, if the iBGP on the LC can't be up, do config reload on the faulty LC doesn't help, the required action is to config reload on the RP. Hence for the chassis device, directly config reload all the RP/LCs
The current recover doesn't help chassis testbed well when it's in the bad state.
1. Extend the wait time of the readiness check for chassis devices
2. Provide a modular-chassis specific recover way, config reload all the devices.
In the nightly test and PR tests

[Chassis] Recover chassis by config reload all RP/LCs

---

tests/bgp/test_passive_peering.py

Summary:
- This PR fixes the DUT selection for the _bgp-passive-peering_ tests to run.
- Tests were using '_rand_one_dut_hostname_', which sometimes picks supervisor as dut for running test cases in case of T2 topo.
- Sometimes, for T2 topo, test-bgp-passive-peering selects dut as Supervisor which is not correct.
- This PR fixes the DUT selection for the _bgp-passive-peering_ tests to run.
**Tests fail with the following error:**
` bgp/test_passive_peering.py:38: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <MultiAsicSonicHost ixre-cpm-chassis19>, port = 'eth0' def get_port_asic_instance(self, port): …

Fix dut selection for bgp-passive-peering tests 

---

tests/ipfwd/test_nhop_group.py

Summary:
The Device Under Test (DUT) selection in the test case differs from that in the gather_facts fixture. Consequently, the test case might pass intermittently when both selections coincide, but it fails consistently in multi-DUT scenarios where they might differ.
The Fixture gather_facts uses the enum_rand for dut selection.
Where as the test case doesn't uses the enum_rand for dut selection
Used enum_rand_one_per_hwsku_frontend_hostname for dut selection in the test case as used in the Fixture
Tested on t2 multi asic , multi dut chassis topology

Reg:IPFWD TC test_nhop_group_interface_flap Dut Selection & Interface up time

---

tests/monit/test_monit_status.py

Since lldp docker was removed from the host on a multi ASIC chassis, stop_and_start_lldpmgrd fails for lldp.
lldp0/lldp1 should be used instead of lldp.
Summary:
To use lldp0/lldp1 instead of lldp for stop_and_start_lldpmgrd. 
Since lldp was removed from the host for multi ASICs chassis, this fails if we check lldp.
Randomly choose either lldp0 or lldp1 for stop_and_start_lldpmgrd if the chassis is a multi ASICs.
Tested on a Multi ASICs chassis

stop_and_start_lldpmgrd should be tested for lldp0/lldp1 since lldp was removed from the host

---

.azure-pipelines/test_plan.py
tests/acl/conftest.py
tests/acl/test_stress_acl.py
tests/arp/conftest.py
tests/arp/test_stress_arp.py
tests/bfd/test_bfd_static_route.py
tests/common/dualtor/dual_tor_utils.py
tests/conftest.py
tests/ecmp/inner_hashing/test_inner_hashing.py
tests/ecmp/inner_hashing/test_inner_hashing_lag.py
tests/ecmp/inner_hashing/test_wr_inner_hashing.py
tests/ecmp/inner_hashing/test_wr_inner_hashing_lag.py
tests/fdb/conftest.py
tests/fdb/test_fdb_mac_move.py
tests/route/conftest.py
tests/route/test_route_flap.py
tests/stress/conftest.py
tests/stress/test_stress_routes.py

Summary:
The `completeness_level` is used as the test level for stress tests, with "confident" indicating a high number of stress test iterations. In Elastictest, the completeness_level has been set to "confident," which results in longer test times.
Always run stress tests at the "confident" level is unnecessary. Moving forward, we can configure the test plan to run high level stress tests weekly at a scheduled time.
1. Remove `--completeness_level=confident` in Elastictest, allowing stress tests to run at their default iteration count.
2. Set default `--completeness_level=debug` in testcases
3. Fix typo `conpleteness` to `completeness`

Set default --completeness_level to debug

---

tests/common/snappi_tests/common_helpers.py

The current function returned buffer sizes for ingress lossless profile only for specific platforms and for rest, it returned buffer sizes associated with egress lossless profile. However, Nokia 7250 platform uses on ingress lossless profiles, check requires to include nokia 7250 platform to return buffer-sizes associated with ingress lossless profile.
Summary:
#13653 
The function - get_lossless_buffer_size returns buffer size associated with either ingress or egress lossless profile. However, it is checking ingress lossless profile for specific platforms and using egress lossless profiles for rest.
Need to include Nokia 7250 platform in the list of the platforms to use ingress lossless profiles.
Using device-metadata in config_facts for the host, to determine HWSKU. 
If …

[Snappi]: Support for selecting buffer-sizes associated with ingress lossless profile with Nokia7250 platform.

---

tests/pfcwd/conftest.py
tests/pfcwd/test_pfcwd_function.py

Summary:
29019744
test_pfcwd_actions case failed on dualtor sometimes due to ping CMD failure
import pause_garp_service fixture to stop garp_service during test
Local run 
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_actions[str2-7260cx3-acs-12] PASSED                                                                                                                                                              [ 20%]
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_multi_port[str2-7260cx3-acs-12] PASSED                                                                                                                                                           [ 40%]
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_mmu_change[str2-7260cx3-acs-12] PASSED …

add pause_garp_service fixture for test_pfcwd_actions

---

tests/conftest.py
tests/fdb/test_fdb_mac_move.py
tests/stress/test_stress_routes.py

cherry-pick conflict
The case failed sometimes due to cannot found the log. It should be related to the small storage, since the var/log size limitation, logrotate would remove the previous syslogs during the test, then cause loganalyzer cannot find the previous log and teardown failure.
It is caused by storage resource limitation, could not fix the issue, this PR is a workaround. Since set the syslog to error lever and update the logroate to compress log immediately during the test still failed sometimes. Create a thread to do the logrotate every 60s during the test.
https://elastictest.org/scheduler/testplan/66d1ebb7f90c6cd947f4dd3e
Summary:

[202311] update rsyslog fixture to workaround /var/log size limitation (#14331)

---

tests/common/snappi_tests/common_helpers.py

Support to pull the DUT statistics, namely interface counters, PFC counters and Queue counters. 
This support will enable users to pull the DUT statistics run-time and capture them in form of dictionary for further processing.
Summary:
#13843 
Currently, there is no one stop-place to fetch the DUT statistics and use them for verification, especially the SNAPPI testcases. There should be some way to pull the DUT statistics ( at least important ones) and use them for verification.
Clear counters:
Common function to clear interface, PFC and queue counter stats.
Interface counters:
Ability to fetch the interface counters for a given DUT and port. Returns dictionary with keys - Rx and Tx packet count, Rx and Tx failures (Error + drops + ovr), and Rx and Tx throughput in Mbps. …

[Snappi] Support for DUT statistics - Interface counters, PFC counters, and Queue counters.

---

tests/wol/test_wol.py

Summary:
Test expected failure like invalid parameters, down interface etc.
Wol has the ability to filter invalid parameters, we need to test this ability.
Run wol with invalid parameters and check the output and return code of command.
Run on testbed
Mx topo only.

[wol_test] Test expected failure like invalid parameters, down interface etc.

---

tests/common/plugins/conditional_mark/README.md
tests/common/plugins/conditional_mark/__init__.py

Previously, the matching rule of the conditional marks was based on the longest match. This meant that when a test case had multiple potential matches, we only applied the mark with the longest matching entry. In this PR, we've optimized this rule: we now consider all potential matches. If a mark is unique across these matches, it will be applied to the test case. Otherwise, we will still use the longest matching entry.
Summary:
Previously, the matching rule of the conditional marks was based on the longest match. This meant that when a test case had multiple potential matches, we only applied the mark with the longest matching entry. In this PR, we've optimized this rule: we now consider all potential matches. If a mark is unique across these matches, it will be applied …

Optimize the matching rule of conditional marks

---

tests/common/snappi_tests/common_helpers.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py

Summary:
Fix two issues:
1. errors in `test_multidut_pfc_pause_lossless_with_snappi.py`
```
snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py::test_pfc_pause_single_lossless_prio[svcstr2-8800-sup-1|4-linecard_configuration_set0-chassis_multi_line_card_multi_asic] 
15:22:32 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 501, in __call__
return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
File …
```

[Snappi] fix TypeError in multidut snappi test cases and topo maker

---

tests/arp/test_stress_arp.py

Resolve PR conflicts in https://github.com/sonic-net/sonic-mgmt/pull/14239 for 202311.
Duplicate PR message:
There are 3 issues with arp/test_stress_arp.py:
It is doing a redundant subtraction.
In both variants, it calculates space available as (available - used) instead of (total size - used), giving an incorrect value for available space.
Not enough allowance/wiggle room for hash collision. In both variants, it expects only 100 hash collisions which is very little. For specific SKUs, there may be a further performance impact as some hash functions is not as performant for incremental values, which is what is used for this test.
The test will crash if cleanup fails.
Sometimes arp cache cleanup will fail if it is done too often. Allowing the test to continue after the failure as the …

Upstream arp/test_stress_arp.py changes to 202311 branch

---

tests/arp/test_stress_arp.py

Resolve PR conflicts in https://github.com/sonic-net/sonic-mgmt/pull/14239 for 202405.
Duplicate PR message:
There are 3 issues with arp/test_stress_arp.py:
It is doing a redundant subtraction.
In both variants, it calculates space available as (available - used) instead of (total size - used), giving an incorrect value for available space.
Not enough allowance/wiggle room for hash collision. In both variants, it expects only 100 hash collisions which is very little. For specific SKUs, there may be a further performance impact as some hash functions is not as performant for incremental values, which is what is used for this test.
The test will crash if cleanup fails.
Sometimes arp cache cleanup will fail if it is done too often. Allowing the test to continue after the failure as the …

Upstream arp/test_stress_arp.py changes to 202405 branch

---

tests/generic_config_updater/test_mgmt_interface.py

Fix generic_config_updater.test_mgmt_interface test failed
generic_config_updater.test_mgmt_interface test case failed.
- Microsoft ADO: 29294578
Add brackets to fix the assert failed issue
Fix generic_config_updater.test_mgmt_interface test failed

Fix generic_config_updater.test_mgmt_interface test failed

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
https://github.com/sonic-net/sonic-mgmt/issues/14448
https://github.com/sonic-net/sonic-mgmt/issues/14449
these 2 issues block the internal sync and PR testing, skip them for now.
https://github.com/sonic-net/sonic-mgmt/issues/14448
https://github.com/sonic-net/sonic-mgmt/issues/14449
these 2 issues block the internal sync and PR testing, skip them for now.

skip cases which failed consistently

---

tests/vxlan/test_vxlan_crm.py

Summary:
When running `vxlan/test_vxlan_crm.py`, there is a chance to get `Vnet Route Mismatch reported` error in log analyzer for KVM
Since `Vnet Route Mismatch reported` has been ignored in other test scripts in vxlan module, ignore in vxlan/test_vxlan_crm.py test for KVM

Add log analyzer ignore message in `test_vxlan_crm.py`

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Some route tests do not apply to standalone
topologies and should be skipped. This patch skips such tests.
Some route tests are not applicable to t0 topos and should be skipped rather than failing unecessarily, negatively impacting pass rate.
Applied skip conditions to the applicable tests in the tests mark conditions yaml file in sonic-mgmt.
Ran the route test suite and confirmed that the desired tests are now skipped.
Verified on Arista-7060X6-64PE-256x200G.

Subject: Skip some route tests for standalone topo

---

tests/common/helpers/pfc_gen.py
tests/pfcwd/files/pfcwd_helper.py
tests/pfcwd/test_pfcwd_function.py

Summary:
This PR is to stabilize PFC watchdog test.
Changes include
1. Do not use multi-process to send PFC pause frames if there is only one interface to be paused
This is because I didn't see improvement using multiple processes to send PFC pause frames when there is only 1 port to be paused. And the multi-processing caused test flakiness in `test_pfcwd_multi_port`
2. Check PFCWD stats after triggering PFC pause on leaf fanout
Before this change, there was a hard-coded 5 seconds delay. But on some platform (e.g, Mellanox) more time is needed until PFC watchdog is triggered.
This PR is to stabilize PFC watchdog test.
1. Do not use multi-process to send PFC pause frames if there is only one interface to be paused
2. Check PFCWD stats after triggering PFC pause on leaf fanout
The change is …

Stabilize PFC watchdog test

---

tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_basic_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_burst_storm_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_multi_node_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_runtime_traffic_helper.py
tests/snappi_tests/test_multidut_snappi.py

This PR proposes to change the IPv4 traffic used in snappi_tests/multidut to UDP traffic with different src ports for every stream.
We need this change since this allows the traffic to be well load-balanced in the backplane ports of the Multi-ASIC architecture. This doesn't affect the other platforms, since they should continue to behave the same irrespective of IPv4 or UDP traffic.
@selldinesh , @kamalsahu0001 , @sdszhang : FYI.
This allows 9 extra tests passing in multi-dut.

[snappi]:Change ipv4 to random-src-port udp traffic.

---

tests/common/helpers/dut_utils.py
tests/crm/conftest.py
tests/crm/test_crm.py

Fix test issue:https://github.com/sonic-net/sonic-mgmt/issues/12725
For mellanox device, the crm available counter is related to LPM tree. When shutdown all interfaces in vlan (e.g. vlan 1000), it will cause the route (e.g. 192.168.0.1/21 )for vlan to be removed, we have only one route for the prefix (21), after it is removed, the corresponding prefix in LPM tree will be removed too, which will lead to the LPM tree structure is changed. LPM tree change might cause available counter change dramatically, and we cannot estimate how long the change is ready. Therefore, it will lead the first case of test_crm_route fail occasionally because the expected available counter is not decreased. So, we add another route with the same prefix(21) as the vlan's so that the LPM tree is not changed. …

[Mellanox|202311] Stabilize test_crm_route 

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Standalone topologies have no upstream switch or any peer switches, meaning any test that requires a peer switch shouldn't be run on this topology.
The test fails due to lack of neighbor switches, which are not present in a standalone topology, hence this test should be skipped.
Applied skip conditions to the applicable tests in the tests mark conditions yaml file in sonic-mgmt.
Ran the test and confirmed thatit is now skipped.
Verified on Arista-7060X6-64PE-256x200G.

Skip test_neighbor_mac_noptf on standalone topologies

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

There is an issue of bgp/test_bgp_suppress_fib.py which block the internal sync and PR testing as reported in #14451. In this PR, we use conditional mark to skip this script rather than move it out from `pr_test_scripts.yaml`
Summary:
There is an issue of bgp/test_bgp_suppress_fib.py which block the internal sync and PR testing as reported in #14451. In this PR, we use conditional mark to skip this script rather than move it out from `pr_test_scripts.yaml`
Use conditional mark to skip the script rather than move it out from `pr_test_scripts.yaml`

Use conditional mark to skip the script bgp/test_bgp_suppress_fib.py 

---

.azure-pipelines/testscripts_analyse/analyse_testscripts.py

In PR #14437, we consider the topologies `m0`, `mx` and `mc0` as subclassses of `t0`. Since we have scripts marked for both t0 and its subclasses, we add a condition in this PR to avoid duplication in our statistics.
Summary:
In PR #14437, we consider the topologies `m0`, `mx` and `mc0` as subclassses of `t0`. Since we have scripts marked for both t0 and its subclasses, we add a condition in this PR to avoid duplication in our statistics.
Add a condition in this PR to avoid duplication in our statistics.

Prevent duplication of topology subclasses in PR statistic

---

ansible/roles/test/files/ptftests/sonic.py

If using sonic peer, currently any lag flap will result in fail. Lag flaps are expected for fast reboot, so fix check so that it only applies for warm reboot.
Summary:
qualifying fast upgrades using sonic peers - this currently will always fail due to inevitable flaps during fast reboot.
only treat flaps during warm reboot as failures
tested on an Arista testbed with sonic peers

Fix lag flap check for sonic peer

---

tests/common/helpers/pfc_gen.py
tests/pfcwd/files/pfcwd_helper.py
tests/pfcwd/test_pfcwd_function.py

Summary:
This PR is to cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/14425 to `202311` branch.
Changes include
1. Do not use multi-process to send PFC pause frames if there is only one interface to be paused
This is because I didn't see improvement using multiple processes to send PFC pause frames when there is only 1 port to be paused. And the multi-processing caused test flakiness in `test_pfcwd_multi_port`
2. Check PFCWD stats after triggering PFC pause on leaf fanout
Before this change, there was a hard-coded 5 seconds delay. But on some platform (e.g, Mellanox) more time is needed until PFC watchdog is triggered.
This PR is to stabilize PFC watchdog test.
1. Do not use multi-process to send PFC pause frames if there is only one interface to be paused
2. Check PFCWD stats …

[202311] Stabilize PFC watchdog test

---

tests/common/helpers/pfc_gen.py
tests/pfcwd/files/pfcwd_helper.py
tests/pfcwd/test_pfcwd_function.py

Summary:
This PR is to cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/14425 to `202405` branch.
Changes include
1. Do not use multi-process to send PFC pause frames if there is only one interface to be paused
This is because I didn't see improvement using multiple processes to send PFC pause frames when there is only 1 port to be paused. And the multi-processing caused test flakiness in `test_pfcwd_multi_port`
2. Check PFCWD stats after triggering PFC pause on leaf fanout
Before this change, there was a hard-coded 5 seconds delay. But on some platform (e.g, Mellanox) more time is needed until PFC watchdog is triggered.
This PR is to stabilize PFC watchdog test.
1. Do not use multi-process to send PFC pause frames if there is only one interface to be paused
2. Check PFCWD stats …

[202405] Stabilize PFC watchdog test

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/test_pktgen.py

Summary:
Enable the 'test_pktgen.py' test to run on Cisco-8000 devices.
Modified the skip condition in test_pktgen.py.
1. Tested the 'test_pktgen.py' on a Cisco-8000 device to ensure the test runs successfully.
2. Verified that the test is still skipped on other ASIC types.

Enable test_pktgen.py for Cisco-8000 ASIC Type

---

tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml

Summary:
In KVM t1-lag PR test, `drop_packets/test_drop_counters.py` failed for log analyzer issue:
E tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzerError: match: 0
E expected_match: 0
E expected_missing_match: 1
E
E Expected Messages that are missing:
E .Port Ethernet100 oper state set from up to down.
Create an issue https://github.com/sonic-net/sonic-mgmt/issues/14512 and xfail `drop_packets/test_drop_counters.py` to unblock PR test

Xfail `drop_packets/test_drop_counters.py` for KVM t1-lag platform

---

ansible/library/exabgp.py

This PR fixes test failures in Py3 only environment (`str has no decode`). For Python 3 the output string returned by `ansible.module.run_command` is already in utf-8. The default "encoding" argument is "utf-8" to enable Py3 to return native strings. [doc](https://docs.ansible.com/ansible/latest/reference_appendices/module_utils.html)
Summary:
This is a PY3 only fix and not applicable for backport.
Tests running in PTF Py3 only image fail with error -
```
E           {"changed": false, "failed": true, "msg": "Error: (<class 'AttributeError'>, AttributeError(\"'str' object has no attribute 'decode'\"), <traceback object at 0x7f60a07fe2c0>)"}
```
Fixed to code to treat output as UTF-8 native string in Py3.
By running failed tests manually on a testbed.
None
Not …

[ansible/library/exabgp]: Output handling for PY3

---

.azure-pipelines/pr_test_scripts.yaml
tests/snmp/test_snmp_queue_counters.py

Summary:
- Added multi-asic support for the test '_test_snmp_queue_counters_' under snmp
-  Currently, 'test_snmp_queue_counters' test doesn't have multi-asic support and the test is failing for multi-asic chassis due to the lack of support.
- Added multi-asic support for test '_test_snmp_queue_counters_' and made sure the current test logic is not affected.
- Ran the above-mentioned test case on a T2 chassis and verified.

Multi-asic support for snmp_queue_counters test

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Adding and removing traps still unsupported for 7050CX3 SKUs in 202311 as well, so should continue to xfail tests.
Summary:
Fixes [# (issue)](https://github.com/aristanetworks/sonic-qual.msft/issues/200)

Xfail copp add/remove trap tests on 7050CX3 SKUs

---

.azure-pipelines/pr_test_scripts.yaml

Move some stable test scripts into PR test
Summary:
Move some stable test scripts into PR test
vms-kvm-t0 | dhcp_relay/test_dhcp_pkt_fwd.py | 2024-09-12 00:00:00.0000000 | 8 | 0 | 8 | 1
vms-kvm-t0 | dhcp_server/test_dhcp_server.py | 2024-09-12 00:00:00.0000000 | 40 | 0 | 40 | 1
vms-kvm-t0 | dhcp_server/test_dhcp_server_multi_vlans.py | 2024-09-12 00:00:00.0000000 | 4 | 0 | 4 | 1
vms-kvm-t0 | dhcp_server/test_dhcp_server_stress.py | 2024-09-12 00:00:00.0000000 | 2 | 0 | 2 | 1
vms-kvm-t0 | platform_tests/test_idle_driver.py | 2024-09-12 00:00:00.0000000 | 2 | 0 | 2 | 1
vms-kvm-t0 | test_nbr_health.py | 2024-09-12 00:00:00.0000000 | 2 | 0 | 2 | 1 …

Move some stable test scripts into PR test

---

tests/common/connections/ssh_console_conn.py

There was an issue whereby certain dut_console tests would throw an `OSError: Socket is closed` prior to the test cases being run on certain devices. 
This was caused due to the way in which, upon a successful login to the in-use console port, the device would close the connection with a `Port is in use. Closing connection...` message. 
As such, this PR adds a check during session preparation, throwing a more descriptive error in the instance a console port is blocked, so that it is easy to diagnose and resolve the issue for an affected device.
Summary:
Adds more descriptive error for a blocked console port (for dut_console tests)
dut_console/test_idle_timeout was failing due to the console port being blocked (on a specific device with a blocked port), but the error was a generic OSError. …

tests-common: Handle SSHConsoleConn being closed prematurely

---

tests/common/plugins/conditional_mark/__init__.py

We changed the matching rule of conditional mark in PR #14395. There is a bug when getting the maximum matching length. In this PR, we fix this bug. 
Summary:
We changed the matching rule of conditional mark in PR #14395. There is a bug when getting the maximum matching length. In this PR, we fix this bug.

[Bugfix] Bugfix for getting maximum matching length of conditional mark. 

---

tests/qos/files/qos_params.gb.yaml

Summary:
Q200(Gibraltar) longlink qos params update, 400G xoff threshold change from 90MB to 25MB.
Update Q200 qos params since xoff threshold changed from 90MB to 25MB.
Update file qos_params.gb.yaml.
Verified it on Q200 longlink linecard.
single-asic:
```
===================================================================================== short test summary info =====================================================================================
PASSED qos/test_qos_sai.py::TestQosSai::testParameter[single_asic]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXoffLimit[single_asic-xoff_1]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXoffLimit[single_asic-xoff_2]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_1]
PASSED …
```

Q200 longlink qos params update, xoff threshold change from 90MB to 25MB

---

tests/acl/test_acl.py
tests/common/config_reload.py
tests/common/helpers/multi_thread_utils.py
tests/common/port_toggle.py
tests/common/reboot.py

Summary:
Refactor test_acl.py to better fit for chassis test.
It reboot/config_reload the dut one by one, on Cisco Chassis, test_acl spend 12 hours.
Use multi-thread to speed up the test.
Refactor test_acl.py to better fit for chassis test.
It reboot/config_reload the dut one by one, on Cisco Chassis, test_acl spend 12 hours.
Use multi-thread to speed up the test.
Use multi-thread to speed up the test.
Run on physical testbed

Refactor test_acl.py with multi-thread for multi-dut scenario

---

tests/qos/test_pfc_counters.py

Summary:
Fixes # (issue) 29400374
From #13763, we changed the `fanout_graph_facts` to be using `rand_one_tgen_dut_hostname` instead of `rand_one_dut_hostname`.
This will cause test_pfc_counters to be flaky failing since in the test we're still using `rand_one_dut_hostname` as the testing device whereas fanout facts could completely fetching a different device with different fanout structure.
We should all use `rand_one_tgen_dut_hostname` for consistency

[bugfix] fix pfc_counter does not select the correct dut_host_name

---

tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml

Issue fixed with PR https://github.com/sonic-net/sonic-mgmt/pull/14515, revert the temporary fix

Revert "Xfail `drop_packets/test_drop_counters.py` for KVM t1-lag platform"

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Conditional mark would only match longest prefix for same maker like 'skip', PR https://github.com/sonic-net/sonic-mgmt/pull/11374 made a wrong use for conditional mark, which led to the skip condition for `vxlan/test_vxlan_crm.py` invalid
Add conditions for each testcase under `vxlan/test_vxlan_crm.py`

Fix conditional mark error for `vxlan/test_vxlan_crm.py`

---

tests/drop_packets/test_drop_counters.py

…list
Summary:
We are seeing the following log errors in syslog, after config reload, capture during sonic-mgmt runs - 
`May 29 14:37:42.975414 LVL02-0101-0835-17T1 ERR syncd#syncd#syncd: :- logEventData: op: create, key: SAI_OBJECT_TYPE_SWITCH:oid:0x21000000000000`
`May 29 14:37:42.975414 LVL02-0101-0835-17T1 ERR syncd#syncd#syncd: :- logEventData: fv:SAI_SWITCH_ATTR_INIT_SWITCH: true`
`May 29 14:37:42.975414 LVL02-0101-0835-17T1 ERR syncd#syncd#syncd: :- logEventData: fv: SAI_SWITCH_ATTR_FDB_EVENT_NOTIFY: 0x5649f8a0a650`
`May 29 14:37:42.975440 LVL02-0101-0835-17T1 ERR syncd#syncd#syncd: :- logEventData: fv: SAI_SWITCH_ATTR_PORT_STATE_CHANGE_NOTIFY: 0x5649f8a0a660`
`May 29 14:37:42.975440 LVL02-0101-0835-17T1 ERR syncd#syncd#syncd: :- logEventData: fv: …

TC-specific ignore SAI_SWITCH_ATTR, SAI_OBJECT_TYPE logs

---

tests/acl/test_acl.py
tests/common/config_reload.py
tests/common/helpers/multi_thread_utils.py
tests/common/port_toggle.py
tests/common/reboot.py

cherry-pick and fix conflict https://github.com/sonic-net/sonic-mgmt/pull/14545
Summary:
Refactor test_acl.py to better fit for chassis test. It reboot/config_reload the dut one by one, on Cisco Chassis, test_acl spend 12 hours. Use multi-thread to speed up the test.
Approach
Refactor test_acl.py to better fit for chassis test. It reboot/config_reload the dut one by one, on Cisco Chassis, test_acl spend 12 hours. Use multi-thread to speed up the test.
Use multi-thread to speed up the test.
Run on physical testbed

[202405]Refactor test_acl.py with multi-thread for multi-dut scenario (#14545)

---

tests/pfcwd/test_pfcwd_timer_accuracy.py

Summary:
This PR is to stabilize pfcwd timer accuracy test on Mellanox testbed with Non-Onyx or Non-Mellanox leaf fanout.
The test is flaky if pfc_gen script running on leaf fanout cannot guarantee continuous PFC pause frame being sent to DUT if the leaf-fanout is not Mellanox. 
This PR is to stabilize pfcwd timer accuracy test on Mellanox testbed with Non-Onyx or Non-Mellanox leaf fanout.
Before this change, the test ran 20 iterations and checked the 10th timer after sorting.
This PR added a check of DUT ASIC and leaf-fanout. If the leaf-fanout is not Mellanox, and the DUT is Mellanox, then use the 6th   timer as checkpoint.
The change is verified on a Mellanox-SN2700 testbed.
Mellanox platform specific.

Loose PFCWD timer accuracy test on Mellanox testbed with Non-Onyx or Non-Mellanox leaf fanout

---

tests/common/fixtures/conn_graph_facts.py
tests/common/snappi_tests/common_helpers.py
tests/common/snappi_tests/snappi_fixtures.py
tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py

Summary:
Infra change for #14144 #14220
This change is to add initial infra changes for current tests/snappi_tests/multidut test cases to be able to run on T0/T1 testbed.
Main changes are the following:
1. `get_snappi_ports_single_dut`:  generate port lists for T0/T1 testbed without the need to add port definition in variables.py.
2. `get_snappi_ports`: unified function to return snappi port lists for both T0/T1 and T2 testbed.
3. Add vlan and port-channel support into `snappi_dut_base_config`: make it consistent for T0/T1 testbed.
4. sample change in two test case `test_multidut_global_pause_with_snappi.py` and `test_multidut_pfc_pause_lossless_with_snappi.py`
After this change, following function can work for both T0/T1 and T2, and test case can adopt the same method to support T0/T1. …

[Snappi] Infra changes to make snappi multidut work for T0/T1 testbed

---

tests/common/snappi_tests/common_helpers.py
tests/common/snappi_tests/traffic_generation.py
tests/snappi_tests/multidut/pfc/files/multidut_helper.py

Summary:
Fix the following error when running test case `test_multidut_pfc_pause_lossless_with_snappi.py`
```
def get_pg_dropped_packets(duthost, phys_intf, prio):
"""
Get number of ingress packets dropped on a specific priority
of a physical interface
Args:
host_ans: Ansible host instance of the device
phys_intf (str): Name of physical interface ex. Ethernet4
prio (int): Priority group to check ex. 4
Returns:
total number of dropped packets (int)
"""
oid_cmd = "sonic-db-cli COUNTERS_DB HGET COUNTERS_QUEUE_NAME_MAP " + phys_intf + ":" + str(prio)
oid_out = duthost.command(oid_cmd)
>       oid_str = str(oid_out["stdout_lines"][0] or 1)
E       IndexError: list index out of range
```
Fix test case error
Add asic_value parameter for `get_pg_dropped_packets()` and …

[Snappi] fix Error in get_pg_dropped_packets for T2 testbed

---

tests/common/snappi_tests/common_helpers.py

Summary: Fixing ecnconfig command where -q was missing
https://github.com/sonic-net/sonic-mgmt/issues/14126
###OUTPUT
platform linux -- Python 3.8.10, pytest-7.4.0, pluggy-1.3.0 -- /usr/bin/python3
metadata: {'Python': '3.8.10', 'Platform': 'Linux-5.4.0-150-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '7.4.0', 'pluggy': '1.3.0'}, 'Plugins': {'allure-pytest': '2.8.22', 'ansible': '4.0.0', 'forked': '1.6.0', 'html': '4.1.0', 'metadata': '3.0.0', 'repeat': '0.9.3', 'xdist': '1.28.0'}}
ansible: 2.13.13
rootdir: /var/AzDevOps/sonic-mgmt/tests
configfile: pytest.ini
plugins: allure-pytest-2.8.22, ansible-4.0.0, forked-1.6.0, html-4.1.0, metadata-3.0.0, repeat-0.9.3, …

[Fix] Fixing ecnconfig command

---

ansible/library/generate_golden_config_db.py

Summary:
Enabling dhcp_server feature for mx in deploy-mg is removed by mistake from this PR: https://github.com/sonic-net/sonic-mgmt/pull/14553. Current PR is to add it back
Enable dhcp_server feature for mx in deploy-mg
Manually deploy minigraph

[mx] Enable dhcp_server feature for mx in deploy-mg

---

ansible/roles/test/files/ptftests/py3/generic_hash_test.py

Set the inner packet next header as TCP
In order to be compatible with the payload type
Summary:
Script enhancement
Set inner packet next header as TCP

Set inner packet next header as TCP

---

tests/common/vxlan_ecmp_utils.py
tests/hash/generic_hash_helper.py
tests/vxlan/test_vxlan_bfd_tsa.py
tests/vxlan/test_vxlan_crm.py
tests/vxlan/test_vxlan_ecmp.py
tests/vxlan/test_vxlan_ecmp_switchover.py

Several scripts import the class `Ecmp_Utils` in `vxlan_ecmp_utils.py` from the vxlan folder. To minimize cross-module dependencies, we move this script to the `tests/common` folder.
Summary:
Several scripts import the class `Ecmp_Utils` in `vxlan_ecmp_utils.py` from the vxlan folder. To minimize cross-module dependencies, we move this script to the `tests/common` folder.
Move script `vxlan_ecmp_utils.py` to the `tests/common` folder.

Relocate `vxlan_ecmp_utils.py` to `tests/common` for dependency reduction

---

tests/common/helpers/pfc_gen.py
tests/pfcwd/test_pfcwd_timer_accuracy.py

Summary:
test_pfcwd_timer_accuracy case is flaky on Arisa platform. Sometimes the detect time is larger than the config detect time.
Both the config detect time and polling time are 400ms, and most of the real detect times range between 800 ~ 1000 ms. 
Based on lua script log, in the failure loop (the detect time is larger than the config detect time), it took 3 polling durations to trigger the pfc storm, and in most of these cases, there was a little traffic in the first loop pooling duration. Suppose the timestamp for the script to send PFC frames was at the end of the first polling duration. then cause there were no enough PFC received and trigger the pfc storm in the third polling loop.
Add half of polling time as compensation for the detect config time.
Run the case …

[pfcwd] Add half of polling time as compensation for test_pfcwd_timer_accuracy

---

tests/platform_tests/test_intf_fec.py

Summary:
test_config_fec_oper_mode should be configuring the rs fec mode only on ports with speed >= 100G, otherwise the interface fails to come up.
Verified the test on a x86_64-mlnx_msn2700-r0 platform testbed.

Skip test_config_fec_oper_mode test for unsupported speeds

---

tests/common/dualtor/tunnel_traffic_utils.py

… traffic
Summary:
Fix `test_orchagent_slb`
During the tunnel traffic not-exist check, we need to explicitly match the inner packet, because there are other IPinIP tunnel packets with different inner packet from the standby to active.
```
dualtor/test_orchagent_slb.py::test_orchagent_slb[ipv4-active-standby] PASSED                                                                                                                                                                        [ 25%]
dualtor/test_orchagent_slb.py::test_orchagent_slb[ipv4-active-active] SKIPPED (Skip cable type 'active-active') …
```

[test_orchagent_slb] Fix test_orchagent_slb

---

tests/snmp/test_snmp_phy_entity.py

Summary:
Solve ```ValueError``` when parsing a string that contains null bytes (\x00). ```ast.literal_eval``` is essentially trying to compile a string into an Abstract Syntax Tree node, but it can't handle null bytes in the string. e,g., ```node_or_string = '{\'ext_identifier\': \'Power Class 8 (16.0W Max)\', \'media_lane_count\': \'N/A\', \'ma: \'2024-05-23 \x00\x00\', \'active_apsel_hostlane7\': \'N/A\'}'```
Remove any null characters before parsing string.
In snmp/test_snmp_phy_entity.py:
```
======================================================================================== short test summary info ========================================================================================
SKIPPED [1] snmp/test_snmp_phy_entity.py:367: Not supported on non supervisor …
```

Remove any null characters before parsing string in test_snmp_phy_entity

---

tests/ip/test_ip_packet.py

Summary:
Fixes #10638 
Check RX_DRP counter if destination MAC is not the router MAC on L3 interface
Send layer 3 packets with non-DUT MAC
Tested it on Cisco and broadcom platform, all passed.  
It failed on Mellanox platform. Mellanox does not log rx_drp or rx_err counter if destination MAC is not DUT MAC. We can add specific check if Mellanox is not planning to support this test case.

RX_DROP counter if destination MAC is not the router MAC on L3 interface

---

tests/platform_tests/test_intf_fec.py

Add a validation check for FEC stat counters, FEC correctable errors should be always higher than FEC symbol errors
Summary:
FEC symbol errors refer to the number of erroneous symbols detected, while FEC correctable errors count the individual bit errors within those symbols that can be corrected. Since a single symbol can contain multiple bit errors, the number of FEC correctable errors is often higher than the number of symbol errors, as FEC can correct multiple bit errors per symbol.
Fail the test if FEC symbol errors > FEC correctable errors
Verified on Mellanox-SN4600C-C64 lab testbed

Add an additional check to verify FEC stat counters

---

ansible/roles/fanout/templates/sonic_deploy_202311.j2

Summary:
Support Nokia-7215A1 in 202311 SONiC fanout template
Support Nokia-7215A1 in 202311 SONiC fanout template
Update config template: `sonic_deploy_202311.j2`
Verified by deploy Nokia-7215A1 fanout.

[Fanout] Support Nokia-7215A1 in 202311 SONiC fanout template

---

tests/qos/files/cisco/qos_param_generator.py

Summary:
MIGSMSFT-620 [sonic-mgmt] [202305] [8111] testQosSaiPfcXonLimit failure is image regression issue.
8111 hardware value of pause threshold is slightly smaller than software config, script used software value for reduced_pause_thr which is too large. At the Xon case failure point, the SQ buffer counter indicated that SQ usage below 10MB (but above 9.75MB), from hardware threshold, it need to drop below 9.75MB to trigger XON.
```
cisco@croc-aaa12-dut:~$ sudo show platform npu rx cgm_profile -t 3 -i Ethernet16
Units are in MBytes
SQG 0
Headroom buffers 2658
ft: fc trigger
fc: flow control
dy: drop yellow
dg: drop green
NOTE: Real HW RX CGM SQ thresholds are:
Bytes: [2555904, 10223616, 21233664]
MB: [2.44, 9.75, 20.25]
SQG usage > 0 …
```

Cisco-8111: adjust reduced_pause_thr to hardware value

---

tests/common/platform/interface_utils.py
tests/lldp/test_lldp.py

Summary:
The lldp test should skip the internal NPU-DPU data ports.
Fix lldp test for smart switch.
Add the internal ports to the skip_interface_pattern_list.
Run the test on smartswitch testbed, it passed.

[Smartswitch] Fix lldp test for smart switch

---

tests/qos/files/qos_params.j2c.yaml
tests/qos/files/qos_params.jr2.yaml

Since the dynamic_th-alpha changed from 0 to -4 (400g) & 100g port speed for egress lossy profile.
PR  #https://github.com/sonic-net/sonic-buildimage/pull/20132
Corresponding  changes made in J2C+ qos yaml for t2 -broadcom-dnx
Summary:
Verified the qos test case execution with the new changes.

Updating J2C+ qos yaml  for 400G and 100G profile _egress_pkt count for lossy profile

---

tests/common/snappi_tests/snappi_fixtures.py

Currently, there is no mechanism in the Snappi testcases to check for the fabric counters.
Purpose of this PR is to have support to clear the counters before test-case execution. The dut host can be supervisor card or line cards.
Second function will check for the CRC and uncorrectable FEC errors. The check should assert if the count is nonzero.
Summary:
#14095  
Currently there is no mechanism to verify the fabric counters on the DUT. The function is added to check for the CRC and uncorrectable errors on line card/s and supervisor.
Two simple functions are added. First to clear the counter and second to parse for errors. If the errors are non-zero, the test will ASSERT.
Tested on local clone.

[Snappi]: Support to clear and check fabric counters

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

1. Skip test_syslog_protocol_filter_severity by https://github.com/sonic-net/sonic-mgmt/issues/14493
2. Skip test_syslog_config_work by bugs by https://github.com/sonic-net/sonic-buildimage/issues/19638
Summary:
Skip test_syslog_protocol_filter_severity and test_syslog_config_work by bugs 
Add skip conidtion
Run the two tests to check if they are skipped
Any

Skip test_syslog_protocol_filter_severity and test_syslog_config_work by bugs

---

ansible/roles/test/files/ptftests/py3/copp_tests.py
tests/copp/test_copp.py

Summary:
COPP rate of queue4_group3 for Mgmt devices is set to 300. But in copp_test it's expected to be 100 for Arista 720DT. This PR is to fix that.
https://github.com/sonic-net/sonic-buildimage/blob/2c47e35472b1f9fd5801a884ce7993d873c07afa/files/image_config/copp/copp_cfg.j2#L37
Set expected copp rate for 720dt
Run test_copp.py in m0/t0/t1 topos, all passed

[COPP][720DT] Fix copp test failure for 720dt

---

tests/common/snappi_tests/common_helpers.py

Broadcom ASICs only supports RED threshold.  Fix helper config_wred to config RED for Broadcom ASIC.
Summary:

[snappi] Fix helper config_wred to config RED for Broadcom ASIC

---

ansible/roles/vm_set/tasks/renumber_topo.yml
ansible/roles/vm_set/tasks/start_tacacs_daily_daemon.yml
ansible/testbed.yaml

Setup TACACS server on PTF host when renumber topo.
Some test failed because loganalyzer found TACACS error log.
The error log is because TACACS enabled on DUT host but not setup TACACS server on PTF host.
Those test bed are setup PTF device with renumber_topo.yml, and the setup TACACS server step missing in this file.
- Microsoft ADO: 29386436
Setup TACACS server on PTF device when renumber topo.
Load TACACS passkey by inv_name for renumber topo scenario.
Setup TACACS server on PTF device when renumber topo.

Setup TACACS server on PTF device when renumber topo.

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Some route tests do not apply to standalone
topologies and should be skipped. This patch skips such tests.
Corresponding PR was opened, approved, and merged for master and 202405: https://github.com/sonic-net/sonic-mgmt/pull/13889
Some route tests are not applicable to t0 topos and should be skipped rather than failing unecessarily, negatively impacting pass rate.
Applied skip conditions to the applicable tests in the tests mark conditions yaml file in sonic-mgmt.
Ran the route test suite and confirmed that the desired tests are now skipped.
Verified on Arista-7060X6-64PE-256x200G.

mgmt|202311: Skip some route tests for standalone topos.

---

tests/test_pretest.py

Summary:
This PR is to add a retry mechanism in downloading python saithrift library on ptf.
The change is needed because we saw saithrift failed to be downloaded due to some transient networking issue. Missing the library will cause QoS sai test failure.
This PR is to add a retry mechanism in downloading python saithrift library on ptf.
Retry 5 times with 1 minute delay between each retry. 
No.

Add retry in downloading python saithrift library

---

tests/dualtor/test_standalone_tunnel_route.py

Summary:
To fix https://github.com/sonic-net/sonic-mgmt/issues/5017
Send downstream traffic (DIP not learnt) to the device, verify the traffic is forwarded by the IPinIP tunnel to the peer side.
```
dualtor/test_standalone_tunnel_route.py::test_standalone_tunnel_route[active-standby] PASSED                                                                                                                                                                           [ 50%]
dualtor/test_standalone_tunnel_route.py::test_standalone_tunnel_route[active-active] SKIPPED (Skip cable type 'active-active') …
```

[dualtor][test gap] Add testcase to verify standalone tunnel route

---

tests/platform_tests/test_reboot.py

Summary:
Nokia-7215 has low performance. After device reboot, it's critical processes may not be fully up at the time SSH is reachable. For this platform, I add `wait_critical_processes` at teardown stage to improve the test stability.
Improve the test_reboot stability on Nokia-7215 platform.
Add `wait_critical_processes` at teardown stage.

[Nokia-7215] Improve test_reboot stability at teardown stage

---

tests/qos/test_pfc_counters.py

Summary: for peer device has no peer fanouts. We should skip the pfc test on these peers.
We have already skipped ixia in here: https://github.com/sonic-net/sonic-mgmt/blob/master/tests/conftest.py#L700
Fixes # (issue) 29428890

fix: skip pfc test for peer-device without fanout

---

tests/crm/test_crm.py

https://github.com/sonic-net/sonic-mgmt/pull/14104 
Reverting this PR as we have fix on the platform side to take care of the CRM route resource usage related issue.
Summary:
CRM route resource fix is committed in the platform side of code. the additional delay and checks added part of the PR/14104 is no longer needed.
Revert the cisco specific change added in sonic-mgmt code.
Verified running sonic mgmt tests/test_crm.py::test_crm_route

Revert PR:12186 crm_stats_ipv6_route_available counter was not decremented, as we have a fix in platform side of code

---

ansible/roles/test/files/ptftests/py3/dhcp_relay_stress_test.py
ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py
tests/dhcp_relay/conftest.py
tests/dhcp_relay/dhcp_relay_utils.py
tests/dhcp_relay/test_dhcp_relay.py
tests/dhcp_relay/test_dhcp_relay_stress.py

Summary:
Address test gap for this change: https://github.com/sonic-net/sonic-buildimage/pull/20021
Prevously, dhcrelay would hit the issue that it wouldn't relay any packets if there are packets come when dhcrelay startup. This issue has been fixed from image side by https://github.com/sonic-net/sonic-buildimage/pull/20021. This PR is to add test for it.
Add stress test with dhcp_relay restart:
1) Keep sending DHCP packets
2) Restart dhcp_relay
3) Check socket buffer
4) Run general dhcp relay test.
Run test on m0/t0/dualtor topos, all passed

[dhcp_relay] Add stress test for restarting dhcp_relay

---

docs/testplan/BGP-BBR.md
tests/bgp/test_bgp_bbr.py

After the fix in https://github.com/sonic-net/sonic-buildimage/pull/19590, add a new test case to test the bbr behavior after config reload.
Summary:
Add a new case to verify the BBR initialized behavior.
Add the following new case under test_bgp_bbr.py
test_bbr_status_consistent_after_reload
https://dev.azure.com/mssonic/internal/_build/results?buildId=619063&view=results

Add BBR testcases

---

tests/snmp/test_snmp_phy_entity.py

This reverts commit 701e39e0b99b61a6d68ce52419049d1e6b0a936d.
Summary:
Revert #14596 as it was temporary optics
Validate it in internal setup, TRANSCEIVER_INFO|Ethernet302 in STATE_DB is empty at the moment.
str3-7060x6-64pe-1
t0-standalone-32

Revert #14596 - Remove any null characters when parsing string in test_snmp_phy_entity

---

tests/arp/test_wr_arp.py
tests/common/arp_utils.py
tests/vxlan/test_vnet_vxlan.py

In the `test_vnet_vxlan.py` script, the `TestWrArp` class is imported from `arp/test_wr_arp.py`. To minimize cross-module dependencies, we have refactored this class and moved the shared functions to a common location.
Summary:
In the `test_vnet_vxlan.py` script, the `TestWrArp` class is imported from `arp/test_wr_arp.py`. To minimize cross-module dependencies, we have refactored this class and moved the shared functions to a common location.

Minimize cross-module dependencies in `test_vnet_vxlan.py`. 

---

tests/clock/test_clock.py

Clock module test cases failing as the show clock command output format is changed.
Modifying date time pattern match as per latest sonic show clock output
Summary:
Show clock command output format has been changed in master and 202405 sonic.
In 202405 and master shows as below
`root@sonic:~# show clock
Tue Sep 17 04:47:53 PM IDT 2024`
but test case is trying to match for the below pattern that shown in earlier version of sonic
In earlier version of sonic,
`admin@sonic:~$ show clock
Tue 17 Sep 2024 01:56:33 PM UTC`
Test case pattern match need change and same is done in this PR.
- [*] Bug fix
- [*] 202405

Modifying date time pattern match to pass clock test case

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Summary:
Fixes # (issue) 29428086
This test case needs to specify `--target_image_list` to be able to run as described in the beginning of the test. However, we don't provide this information for our nightly running (https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/test_secure_upgrade.py#L9). It's currently failing / error out for all topologies. 
Ansible will fail to run the test since `src=` is undefined.

chore: skip test_secure_upgrade if --target_image_list is not specified

---

tests/platform_tests/link_flap/test_cont_link_flap.py

Currently, test_cont_link_flap is not compatible with multi-asic. It's failing on  vtysh command
```
raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{"changed": true, "cmd": "vtysh -c \"show memory bgpd\"", "delta": "0:00:00.006507", "end": "2024-09-17 00:06:50.914882", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2024-09-17 00:06:50.908375", "stderr": "Usage: /usr/bin/vtysh -n [0 to 2] [OPTION]... ", "stderr_lines": ["Usage: /usr/bin/vtysh -n [0 to 2] [OPTION]... "], "stdout": "", "stdout_lines": []}
```
This is because for multi-asic platform, we need to specify `-n`. 
Summary: add multi-asic support for test_cont_link_flap
Fixes # (issue) 2954952 …

feat: add multi-asic in test_cont_link_flap

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
tests/platform_tests/test_secure_upgrade.py

Summary: This PR revert the problematic PR #14573 and provide an alternative way to skip test_secure_upgrade.py
We can't do this approach because session object is simply not accessible in conditional mark.
> This test case needs to specify --target_image_list to be able to run as described in the beginning of the test. However, we don't provide this information for our nightly running (https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/test_secure_upgrade.py#L9). It's currently failing / error out for all topologies.
> Ansible will fail to run the test since src= is undefined.
Verified on VMS25-t2-8800

Skip test secure upgrade if image not specified fix

---

tests/common/platform/device_utils.py

In PR #14672, we moved some functions from `platform_tests/verify_dut_health.py` to `common/platform/device_utils.py`, but forgot to move the defination of variable `test_report`, which will cause an NameError. In this PR, we define this variable in `common/platform/device_utils.py` to fix this issue. 
Summary:
Fixes #14672
In PR #14672, we moved some functions from `platform_tests/verify_dut_health.py` to `common/platform/device_utils.py`, but forgot to move the defination of variable `test_report`, which will cause an NameError. In this PR, we define this variable in `common/platform/device_utils.py` to fix this issue. 
Define the variable in `common/platform/device_utils.py` to fix this issue.

[Bugfix] Fix NameError imported by PR #14672

---

tests/common/helpers/pfc_gen.py
tests/common/helpers/pfc_storm.py
tests/common/templates/pfc_storm_eos.j2
tests/common/templates/pfc_storm_sonic.j2
tests/common/templates/pfc_storm_stop_eos.j2
tests/common/templates/pfc_storm_stop_sonic.j2

Summary:
Using multiple process to enhance the fanout sending package performance to reduce the failure rate for pfcwd cases.
With this enhancement, some pfcwd related cases on broadcom platform would failure sometimes.
Add an option "-m" for multiple process for pfc_gen.py.
mellanox:
https://elastictest.org/scheduler/testplan/66f27ab91e021eb2510aba07
broadcom:
https://elastictest.org/scheduler/testplan/66f278da4216a91fd43d97cd
cisco:
https://elastictest.org/scheduler/testplan/66f278920369ccd340b3ea7f

Add multiple process option for pfc_gen.py

---

tests/platform_tests/fwutil/fwutil_common.py

**Issue：**
The following code should not be placed in the midle of test body, because it has done some fwtuil operation. For instance, when upgrading the cpld, if we don't do power cycle due to pdu_ctrl is not ready. Later if we do power cycle, the cpld veresion will change to the tested cpld version, It will cause some confusion.
```
if pdu_ctrl is None:
pytest.skip("No PSU controller for %s, skipping" % duthost.hostname)
```
**Fix solution:**
1. Move the code checking pdu_ctrl ready before doing any fwtuil operation
2. When pdu_ctr is not ready, fail test
Summary:

Fix fwutil test issue when pdu_ctrl is not ready

---

tests/tacacs/test_authorization.py

Restrict the list of commands in `test_authorization_tacacs_only` when run on chassis supervisor to avoid commands that currently fail or require authentication prompt.
Summary:
Fixes # [(issue)](https://github.com/sonic-net/sonic-mgmt/issues/14506)
This is a proposed fix to https://github.com/sonic-net/sonic-mgmt/issues/14506

Restrict list of commands to run on chassis supervisor in test_authorization_tacacs_only

---

tests/snmp/test_snmp_phy_entity.py

`test_snmp_phy_entity.py` queries `STATE_DB` in only the default namespace.
Some of the test require access to entries that are only present in the asic namespaces on multi-asic systems.
E.G. `test_transceiver_info` queries for the `TRANSCEIVER_INFO` in the default namespace but they only exist in the asic namespace:
```
root@cmp214-6:~# sonic-db-cli STATE_DB keys \* | grep -i "TRANSCEIVER_INFO" | wc -l
0
root@cmp214-6:~# sonic-db-cli -n asic0 STATE_DB keys \* | grep -i "TRANSCEIVER_INFO" | wc -l
13
root@cmp214-6:~# sonic-db-cli -n asic1 STATE_DB keys \* | grep -i "TRANSCEIVER_INFO" | wc -l
14
```
It's for that reason that the test is being skipped on multi-asic LCs:
```
keys = redis_get_keys(duthost, STATE_DB, XCVR_KEY_TEMPLATE.format('*'))
if not keys:
pytest.skip('Transceiver …
```

Add `multi-asic` support to `test_snmp_phy_entity.py`

---

tests/platform_tests/test_secure_upgrade.py

Conflict resolve for #14712 
---
Extract from orignal PR:
Summary: This PR revert the problematic PR #14573 and provide an alternative way to skip test_secure_upgrade.py
We can't do this approach because session object is simply not accessible in conditional mark.
This test case needs to specify --target_image_list to be able to run as described in the beginning of the test. However, we don't provide this information for our nightly running (https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/test_secure_upgrade.py#L9). It's currently failing / error out for all topologies.
Ansible will fail to run the test since src= is undefined.
Approach
Verified on VMS25-t2-8800 …

Conflict resolve 202405 branch cherry-pick #14712

---

tests/acl/test_acl.py

On T2, the syslog messages from acl deletes can also take longer to appear, causing a few fails in acl tests.
Extend the changes from https://github.com/sonic-net/sonic-mgmt/pull/14255 to also wait for the syslog messages when the acl rules and table are deleted.
Summary:
Reduce flakiness in acl tests
Ran acl tests on single-asic T2 DUT

Wait for acl delete rule/table message in syslog

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml
tests/decap/test_subnet_decap.py

Summary:
In Azure network, Netscan uses IP-decap to check for route blackholes, but servers do not support decapsulation, making it impossible to perform server-to-server checks. To address this, we developed the subnet decap feature to detect if the link between the server and T0 is functioning properly. Additionally, new test cases are required to ensure the functionality of subnet decap is working as expected.
Add new test to verify IPinIP packet targeting at VLAN subnet is decapsulated (T0 only)
Ref test gap issue: https://github.com/sonic-net/sonic-mgmt/issues/13120
Ref test plan: https://github.com/sonic-net/sonic-mgmt/pull/12990
Test on broadcom td3 asic and KVM

Add new test for vlan subnet decap

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/qos/files/cisco/qos_param_generator.py
tests/qos/files/qos_params.gb.yaml
tests/qos/test_qos_sai.py
tests/saitests/py3/sai_qos_tests.py

Double commit https://github.com/sonic-net/sonic-mgmt/pull/10838
Summary:

[202311] Add case to test lossy fair-voq

---

.azure-pipelines/testscripts_analyse/constant.py

In PR #14437, we removed the mapping for the `wan-pub` topology name during test script validation, as there is no WAN checker in our PR test. However, this removal resulted in skipped scripts for that topology not being collected. In this PR, we are restoring the mapping to address this issue.
Summary:
In PR #14437, we removed the mapping for the `wan-pub` topology name during test script validation, as there is no WAN checker in our PR test. However, this removal resulted in skipped scripts for that topology not being collected. In this PR, we are restoring the mapping to address this issue.
Restore the mapping.

[Bugfix] Restoring wan-pub topology mapping in test scripts validation. 

---

tests/common/helpers/pfcwd_helper.py
tests/pfcwd/test_pfcwd_cli.py
tests/pfcwd/test_pfcwd_function.py

Summary:
https://github.com/sonic-net/sonic-mgmt/issues/11169
Add a new test case to cover "pfcwd show stats" cmd
1. Trigger PFC storm with action drop or forward
2. send_tx_egress and send_rx_ingress
3. execute CMD 'show pfcwd stat' and ensure the output is expected
https://elastictest.org/scheduler/testplan/66f268ae4216a91fd43d97b6
https://elastictest.org/scheduler/testplan/66f268880369ccd340b3ea60

add test case for cli show pfcwd stat

---

ansible/roles/vm_set/templates/sonic.xml.j2
ansible/vtestbed.yaml
docs/testbed/README.testbed.VsSetup.md

Summary:
Raising this PR as the phase one of smart switch sand box.
1. Add a no-lag t1 kvm testbed 
2. Update sonic vm template to allow nested virtualization 
3. Add link to sonic-vpp build instructions
Tried to deploy a t1 kvm testbed on Azure VM with sonic-vpp image. Was able to get bgp sessions up.

Add sonic-vpp image download instructions and `t1` vtestbed topology

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary: Skip ```pfcwd/test_pfcwd_all_port_storm.py``` test on Arista-7060X6-64PE-256x200G, the pfc generation function on the Arista fanout device need to be improved by Arista.
Currently, the test uses the python script to send the PFC frames, but the performance does not meet the requirements, and sometimes fails to trigger the PFC storm immediately. Slow pfc generation rate on 7060x6 200Gb. 
To address this, waiting for Arista to to improve the pfc generation function on the Arista fanout device. It would be better to use an Asic based pfc generation function.
```
======================================================================================== short test summary info ========================================================================================= …
```

Skip pfcwd_all_port_storm test on Arista-7060X6-64PE-256x200G

---

tests/bgp/test_bgp_command.py

Summary:
Address test gap https://github.com/sonic-net/sonic-mgmt/issues/5069
To address test gap https://github.com/sonic-net/sonic-mgmt/issues/5069
1. Compare the output of show ip bgp network and docker exec -i bgp vtysh -c "show bgp ipv4 all"
2. Compare the routes and total path value is equal or not for both command
3. Both cover ipv4 and ipv6 command.
Run `bgp/test_bgp_command.py`
All platforms
All topologies

[Test Gap] Add a test script to cover show ip bgp nettwork

---

tests/drop_packets/test_drop_counters.py

Extract from orignal PR:
Ignore below expected xcvrd errors that gets logged when using copper cables.
```
Jul  3 15:24:06.737771 str3-8101-02 ERR pmon#xcvrd[30]: CMIS: Ethernet36: no suitable app for the port appl 0 host_lane_count 4 host_speed 100000
```
Summary:
Ignore below expected xcvrd errors when using copper cables.
Fixes # 
These errors expected when using copper cables and should be ignored.
Added this error in ignore list.
Verification with different speed/lane is work in progress
NA
NA
NA

Conflict resolve 202311 branch cherry-pick #14458

---

tests/drop_packets/test_drop_counters.py

Extract from orignal PR:
Ignore below expected xcvrd errors that gets logged when using copper cables.
```
Jul  3 15:24:06.737771 str3-8101-02 ERR pmon#xcvrd[30]: CMIS: Ethernet36: no suitable app for the port appl 0 host_lane_count 4 host_speed 100000
```
Summary:
Ignore below expected xcvrd errors when using copper cables.
Fixes # 
These errors expected when using copper cables and should be ignored.
Added this error in ignore list.
Verification with different speed/lane is work in progress
NA
NA
NA

Conflict resolve 202405 branch cherry-pick #14458

---

ansible/roles/test/files/ptftests/py3/fdb_mac_learning_test.py
tests/fdb/test_fdb_mac_learning.py
tests/fdb/utils.py

When the DUT performs MAC Learning, a situation may arise such that even if the interface is shutdown, 'show mac' will show previously learnt MAC addresses on the 'Down' interfaces. These stale entries will persist even after doing 'sonic-clear fdb all'
This Testcase covers this scenario and makes sure that stale entries are removed
Followed below steps to recreate the scenario
-shut down all ports
-config save
-config reload
-bring up 1 port. populate fdb
-bring up 3 more ports. populate fdb.
-shut down 3 ports added in last step
-verify that MAC entries connected to shutdown ports are gone from MAC table
-sonic-clear fdb all
-populate fdb for the UP port
-verify that the MAC entries connected to shutdown ports don't show up …

Adding a new testcase to check if mac learning happens correctly

---

tests/tacacs/test_ro_disk.py

The testcase only waits for 5 mins after Supervisor reboot, this is not enough in case of modular chassis. This causes all testcases to fail after this test stating that Host is unavailable.
Summary:
Wait time of 5 minutes is not enough for supervisor node. Especially in this testcase where ssh check is disabled.
Increased the time for supervisor node.
Validated on modular chassis with T2 profile
No

tacacs/test_ro_disk.py: Increase wait time for modular chassis after reboot

---

tests/common/plugins/sanity_check/__init__.py
tests/conftest.py

Expand custom message feature to find potentially risky tests and modify existing custom message to be expandable for future use.
Expand custom message feature to find potentially risky tests and modify existing custom message to be expandable for future use.
Summary:
Add custom message for pre/post sanity check results
To enhance debugging by adding extra information into customMsg we already have, and also make it expandable so others can add debugging information to be utlised in ADE

Add custom message for pre/post sanity check results

---

tests/platform_tests/counterpoll/test_counterpoll_watermark.py

* Select only frontend hwskus for counterpoll_queue_watermark_pg_drop test
* Assert if waiting for COUNTER_DB to be populated fails
BugLink: https://github.com/sonic-net/sonic-mgmt/issues/14721
Summary:
Fixes #14721
platform test test_counterpoll_watermark_pg_drop runs and fails on the sup cards, where it should only be running on linecards. Test case fixture needs to be modified to only select frontend cards. Additionally, the test should fail if it fails to wait on the COUNTER_DB on becoming populated
Run on testbed - successfully skips supervisor, and asserts properly if the counter_db is not populated

[platform_tests/counterpoll]: Don't run counterpoll_watermark test on supervisor

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Fixes #14722 (issue)
Stop tests in test_vs_chassis_setup from running and failing on non vs_chassis.
Add skip condition for test if asic type is not 'vs' in tests_mark_conditions.yaml
Ran test on physical T2 testbed to verify it skips.
N/A
N/A
N/A

Add skip for test_vs_chassis_setup.py on non-vs testbeds

---

tests/common/plugins/sanity_check/__init__.py

New feature delivered recently, add customMsg for sanity check failures, was causing unexpected sanity_check results. This was due to premature cache key reset of pre_sanity_check_failed and post_sanity_check_failed. Removed those two keys from getting reset before sessionfinish to resolve the issue
Important cache keys, used to determine session exit status:
pre_sanity_check_failed & post_sanity_check_failed => These combination of keys will return exit status 10, 11, 12
10 = PRE_SANITY_CHECK_FAILED_RC
11 = POST_SANITY_CHECK_FAILED_RC
12 = SANITY_CHECK_FAILED_RC
duthosts_fixture_failed => If this is true, we return exit status code 15
15 = DUTHOSTS_FIXTURE_FAILED_RC
Summary:
New feature delivered recently, add customMsg for sanity check failures, was causing unexpected sanity_check …

Fix customMsg from unexpected sanity failure

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/override_config_table/test_override_config_table.py

Move the multi-asic skip condition in `override_config_table/test_override_config_table.py` to `test_mark_conditions.yaml` to speed up the skip process. 
Summary:
Currently, it takes 1 ~ 2 hours to skip the `override_config_table/test_override_config_table.py` test on T2 chassis because there's some unnecessary setup steps before it reaches multi-asic `pytest.skip()` condition. We can improve this by moving the skip condition to `test_mark_conditions.yaml`.
I ran the updated code in T2 chassis and it only took ~1 min to skip the test. Meanwhile, I can confirm that this test is running as normal in single-asic Testbeds.

refactor: move skip condition to tests mark

---

tests/test_posttest.py

PTFHost can be None in some cases (eg. ixia) and this was not handled correctly in test_collect_ptf_logs. Add ptfhost check to prevent error caused by None value.
Summary:
PTFHost can be None in some cases (eg. ixia) and this was not handled correctly in test_collect_ptf_logs. Add ptfhost check to prevent error caused by None value.
Resolve unexpected error during log collection
check for None value

add ptfhost check to prevent failure on test_posttest.py

---

tests/qos/files/cisco/qos_param_generator.py
tests/qos/qos_sai_base.py

Error seen when running on T2 testbed.
```
21:32:22 base._run                                L0118 DEBUG  | /data/tests/common/devices/sonic.py::get_running_config_facts#1774: [sfd-lt2-lc0] AnsibleModule::config_facts done, is_failed=False, rc=None
21:32:22 __init__._fixture_generator_decorator    L0088 ERROR  | 
KeyError('DSCP_TO_TC_MAP')
File "/data/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
res = next(it)
File "/data/tests/qos/qos_sai_base.py", line 1671, in dutQosConfig
qpm = qos_param_generator.QosParamCisco(
File "/data/tests/qos/files/cisco/qos_param_generator.py", line 87, in __init__
self.dscp_queue0 = self.get_one_dscp_from_queue(0)
File "/data/tests/qos/files/cisco/qos_param_generator.py", …
```

Fix error in qos_param_generator

---

tests/cacl/test_cacl_application.py

This PR addresses the test gap for verifying that control ACL rules loaded into a DUT through acl-loader and a given acl.json.
Addresses #10516:
-  Introduces a test to verify cacl rules are correct after acl-loader loads rules from an acl.json file
Currently, there is no test to cover verification that cacl rules are correct after acl-loader loads rules from an acl.json file.
This PR intends to address that by adding one.
Introduced a test, which loads dummy cacl rules from a generated acl.json file, and then validates that the applied rules are the same as is defined in the generated acl.json (i.e. the expected configuration).
Ran the test on a number of testbeds, confirming that the test correctly reports success in loading and verifying the supplied acl rules.
``` …
```

[tests-cacl] Add acl-loader test and validation function

---

tests/common/fixtures/advanced_reboot.py

Summary:
In event of an exception in runRebootTest, postboot_setup may not run. 
Move the call to the finally block to ensure it is always run.
Verified running test_upgrade_path on Arista device.

Always run postboot_setup in runRebootTest

---

tests/qos/qos_sai_base.py

Summary:
Fixes [MIGSMSFT-647](https://migsonic.atlassian.net/browse/MIGSMSFT-647)
Have different combinations of longlink and shortlink in test_qos_sai.py.
Extend params in select_src_dst_dut_and_asic.
Verified on T2 testbed which has 3 linecards, 1st linecard longlink, 2nd linecard shortlink, 3rd linecard shortlink.
```
---------------------------------------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testParameter_2024-09-25-20-41-38.xml -----------------------------------------------
----------------------------------------------------------------------------------- live log sessionfinish -----------------------------------------------------------------------------------
21:08:01 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report …
```

MIGSMSFT-647 improve qos/test_qos_sai.py to have different longlink/shortlink combinations

---

tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_burst_storm_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_m2o_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
tests/snappi_tests/test_multidut_snappi.py
tests/snappi_tests/variables.py

Cherry-pick (#14305) into 202405.
Summary: Accomodating the infra change for multidut ECN and PFCWD cases Fixes # (issue)
#13389
#13769
Approach
To accomodate the infra change from PR 14127
Added a pytest fixture called get_snappi_ports and get_snappi_ports_for_rdma whcih selects the ports from the information provided in MULTIDUT_PORT_INFO in variables.py
(cherry picked from commit 83553f62e44b3085529736c00de60df6a0e25baf)
Summary:

[202405][PR: 14305][Snappi] Accomodating the infra change for multidut ECN and PFCWD cases

---

tests/conftest.py
tests/route/test_route_flap.py

Summary:
- With recent changes for AZNG routes on upstream LC, '_test_route_flap_' test case fails for upstream T2 line card.
- This PR fixes the above issue for T2 upstream line card.
- With recent changes for AZNG routes on upstream LC, '_test_route_flap_' test case fails for upstream T2 line card with the following issue.
```
>     def fail(self, msg=None):
"""Fail immediately, with the given message."""
raise self.failureException(msg)
E       AssertionError: Received expected packet on port 13 for device 0, but it should have arrived on one of these ports: [23, 31, 30, 21, 18, 20, 28, 7, 16, 19, 17, 6, 29, 22].
```
- This PR fixes the above issue for upstream T2 line card.
- Update the _ptf_receiving_ports_ list if the duthost is upstream T2 line card.
- Verify that …

[T2] [Chassis] Route flap fix on upstream LC for AZNG route changes

---

tests/copp/copp_utils.py

Summary:
This PR is to change package name from `python-setuptools`  to `python3-setuptools` for bookworm.
The attempt to install `python-setuptools` leads to `test_copp` failure.
The error message is
```
......
"Get:18 http://deb.debian.org/debian bookworm-backports/main amd64 Packages [247 kB]", "Get:19 http://deb.debian.org/debian bookworm-backports/non-free-firmware amd64 Packages [3852 B]", "Get:20 http://deb.debian.org/debian-security bookworm-security/contrib Sources [856 B]", "Get:21 http://deb.debian.org/debian-security bookworm-security/non-free-firmware Sources [796 B]", "Get:22 http://deb.debian.org/debian-security bookworm-security/main Sources [114 kB]", "Get:23 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [186 kB]", "Get:24 …
```

Fix python-setuptools package name for bookwork 

---

tests/conftest.py
tests/override_config_table/test_override_config_table_masic.py

Summary:
This PR fixes '_test_override_config_table_masic-test_load_minigraph_with_golden_config_' failure on upstream line card on T2 topo Chassis.
The above test fails with the following issue on _DEVICE_METADATA_ table when 'config _load_minigraph_' is done with empty golden config input. 
>    
host_current_config = get_running_config(duthost)
for table in initial_host_config:
if table in NON_USER_CONFIG_TABLES:
continue
pytest_assert(
initial_host_config[table] == host_current_config[table],
"empty input compare fail! {}".format(table)
)
E           Failed: empty input compare fail! DEVICE_METADATA
The test passes on downstream linecards.
- '_test_override_config_table_masic-test_load_minigraph_with_golden_config_' fails on upstream line card on T2 topo Chassis.
- …

[T2] [Chassis] Skip override_config_table_masic test for upstream line card

---

tests/saitests/py3/sai_qos_tests.py

Summary:
Reproduce issue where XOFF counter continues increasing in case where buffer pool is full.
Reproduce a counter issue for Cisco-8000. 
Decrease memory occupancy after filling the bufferpool to observe behavior of the XOFF TX counter. 
Verified on 8101, 8102, and 8111.

Reproduce XOFF counter increase

---

tests/common/platform/device_utils.py

Following the refactor in https://github.com/sonic-net/sonic-mgmt/pull/14672/files, the *_report.json and *_summary.json files are now being written to a different path. This causes them not to be collected in downstream log collection logic. This was a side-effect of the refactor and should be restored to the original functionality.
They were getting written to:
Report file path: sonic-mgmt/tests/common/logs/platform_tests/device-name_report.json
Summary file path: sonic-mgmt/tests/common/logs/platform_tests/device-name_summary.json
Which should have been:
Report file path: sonic-mgmt/tests/logs/platform_tests/device-name_report.json
Summary file path: sonic-mgmt/tests/logs/platform_tests/device-name_summary.json
This PR fixes it.
Summary:
Fixes #14809
Fix CI issues
Corrected a path …

Fixed report file and summary file getting written to wrong place

---

ansible/roles/test/files/ptftests/arista.py
ansible/roles/test/files/ptftests/host_device.py
ansible/roles/test/files/ptftests/py3/advanced-reboot.py
ansible/roles/test/files/ptftests/sad_path.py
ansible/roles/test/files/ptftests/sonic.py
tests/common/devices/sonic.py
tests/common/helpers/sad_path.py

Summary: Add support for SONiC peers in SAD reboot testing (test_upgrade_path, test_advanced_reboot)
Fixes #13627 
This adds sonic peer/neighbor support for SAD reboot cases (i.e. when `--neighbor_type == sonic`)
Previously the SAD reboot cases were only supported for eos peers (i.e. `--neighbor_type == eos`)
Sonic peers via vsonic testbed are required for teamd retry extension.
Update/implement the `Sonic` `HostDevice` API, much of which was previously copy pasted from the `Arista` API.
Ran `test_warm_upgrade_sad_path` on Arista 7050CX3 device using sonic peer on master, 202405, and 202311.

Add sonic peer support for SAD reboot testing

---

ansible/config_sonic_basedon_testbed.yml
ansible/module_utils/port_utils.py

Primiarly add support for various Arista 7800R3A SKUs s to port_utils.py. Also one minor tweak `config_sonic_basedon_testbed.yml` to parameterize `asic_topo_config` per slot.
Summary:
Support all 7800R3A SKU variants
Validated with sonic-mgmt runs against Arista 7800R3A linecards.
NA
NA
This is not a new feature and hence does not require a Wiki change.

Adding port mapping for new Arista Hardware SKUs

---

tests/saitests/py3/switch.py

SAI thrift call sai_thrift_read_port_counters() reads a collection of counters together, including SAI_PORT_STAT_IN_DROPPED_PKTS.  Starting from BRCM SAI 11.x,  SAI_PORT_STAT_IN_DROPPED_PKTS is not supported and retrieving the count may fail SAI call https://github.com/sonic-net/sonic-buildimage/issues/19998. In order to retrieve other counters correctly, read SAI_PORT_STAT_IN_DROPPED_PKTS in a separate SAI call.
Summary:

Fix sai_thrift_read_port_counters for DNX

---

ansible/roles/vm_set/tasks/renumber_topo.yml

Summary:
PTF container's memory limit is 16G in add-topo after the change in #7413.
But it's still 8G when doing `restart-ptf`. 
In current code base:
```
:~$ docker stats --no-stream | grep ptf
b303f551ff99   ptf_ptf-01            121.43%   1.26GiB / 16GiB     7.88%     0B / 0B   0B / 618kB        69
:~$ docker stats --no-stream | grep ptf
1c4e10810aff   ptf_ptf-01            0.09%     21.98MiB / 8GiB     0.27%     0B / 0B   0B / 0B           4
:~$ 
```
Keep the same memory limit for add-topo and restart-ptf
Tested in physical testbed.  PTF memory stays at 16G after `restart-ptf`

change ptf container memory in restart-ptf to 16G as same as add-topo

---

tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
tests/snappi_tests/multidut/pfc/test_lossless_response_to_external_pause_storms.py
tests/snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py
tests/snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless_lossy.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossy.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_burst_storm_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_m2o_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
tests/snappi_tests/test_multidut_snappi.py

This PR is to accommodate the changes in the test cases to support T0/T1 testbeds after the infra change in #14361.
Summary:
Test case changes for #14220 and #14144
Consolidate T0/T1 and T2 test cases.
Main change:
- Change the test case to use all available ports for T0/T1 test cases.
- Same change is repeated in multidut PFC/PFCWD/ECN test cases.
Minor change:
-  fix the following error:
```
>       lossless_prio = int(lossless_prio)
E       TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```
Ran it on T0/T1 and T2 testbed. failures are seen but not related to this change.

[Snappi] multidut test case changes to support T0/T1 testbed.

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

As the required SW changes are not available in 202405 we should skip test_bgp_suppress_fib for 202405
"We should not be taking this change in 202405 as we don't have the required memory enhancements that are part of master only. From 202411 we will have fib suppression feature"([Revert "Remove suppress-fib-pending CLI and make route_check.py check suppress-fib in BGP configuration" by dgsudharsan · Pull Request #3477 · sonic-net/sonic-utilities](https://github.com/sonic-net/sonic-utilities/pull/3477#issuecomment-2353123101) ).
Summary:
Fixes #https://github.com/sonic-net/sonic-mgmt/issues/14381
Skip the test as the functionality is not available in the release 202405
Skip the test for 202405 release
Test skipped
```
------ generated xml file: …
```

skip test_bgp_suppress_fib in 202405 release

---

tests/common/helpers/sonic_db.py

Summary:
Fix https://github.com/sonic-net/sonic-mgmt/issues/14816
The PR takes the implementation from PR https://github.com/sonic-net/sonic-mgmt/pull/13574
PR #13574 was reverted, but the function `hget_all` has been referenced in some other code.
This PR is to add support for `hget_all` in SonicDbCli.
Implement `hget_all` funciton.
The change is verified by running `test_lldp_syncd`.
collected 5 items                                                                                                                                                                                     
lldp/test_lldp_syncd.py::test_lldp_entry_table_keys[str-msn2700a1-03] PASSED                                                                                                                    [ 20%] …

Support hget_all in SonicDbCli

---

ansible/TestbedProcessing.py
ansible/library/conn_graph_facts.py
ansible/library/topo_facts.py
ansible/roles/fanout/templates/arista_7060_deploy.j2
ansible/templates/minigraph_link_meta.j2
ansible/templates/minigraph_meta.j2
ansible/vars/topo_t0-116.yml
ansible/vars/topo_t0.yml

These changes add a support for adding auto negotiation to specific testbed based on variables defined in ansible
Two things are required for autoneg support 
1. autoneg_enabled : True 
must be enabled in inventory files 
2. to topo file must have a port list for autoneg 
Example:
intfs : [1, 2, 3, 4, 5, 6, 7, 8]
With these changes the PR includes changes to pick the port numbering from topo file and apply minigraph parsing changes such that during deploy-mg or gen-mg the required ports have autoneg and deployment is clean with link up 
Summary:

[ansible][minigraph] add support for adding autonegotiation in minigraph templates and fanout EOS

---

tests/ip/test_mgmt_ipv6_only.py

This PR addresses a bug introduced in PR #14551. In that PR, we refactored several fixtures, but they were not imported in the `test_mgmt_ipv6_only.py` script, leading to errors.
Summary:
This PR addresses a bug introduced in PR #14551. In that PR, we refactored several fixtures, but they were not imported in the `test_mgmt_ipv6_only.py` script, leading to errors.

[Bugfix] Fix the `fixture not found` error caused by #14551

---

tests/common/reboot.py

Summary:
Fixes #14840
Changed behaviour of forcing minimum `wait` and `timeout` times for reboot on T2 devices to only trigger when `safe_reboot == True`
Tests were failing when because of the minimum 900s wait time during reboot for T2 devices, despite explicitly setting wait time.
Changed behaviour of forcing minimum `wait` and `timeout` times for reboot on T2 devices to only trigger when `safe_reboot == True`
Tested on T2 testbed to confirm that the effective priority to define `wait` and `timeout` variables would now be:
900, 600 for T2 DUT & safe reboot >
values defined in inv >
explicitly defined `wait` and `timeout` during function call >
default values in `reboot_ctrl_dict`
Platform agnostic
N/A
N/A

Change behaviour of wait and timeout assignment for T2 devices

---

tests/bgp/test_startup_tsa_tsb_service.py

Summary:
Fixes #14847
Remove unnecessary encode in `get_tsa_tsb_service_uptime` function causing test failures due to `TypeError` in `test_startup_tsa_tsb_service.py`.
To fix test failures in `test_startup_tsa_tsb_service.py`.
Remove encode causing `TestError` in `get_tsa_tsb_service_uptime` function.
Tested on T2 testbed that TypeError is no longer raised, and `get_tsa_tsb_service_uptime` continues to function as intended.
N/A
N/A
N/A

Remove cause of TypeError in get_tsa_tsb_service_uptime

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Extended the SingleHop BFD skip to other cisco platforms
Summary:
Ran sonic-mgmt to validate the change
bfd/test_bfd.py::test_bfd_basic[ipv4-dut_init_first] INFO:SectionStartLogger:==================== bfd/test_bfd.py::test_bfd_basic[ipv4-dut_init_first] setup ====================
SKIPPED (Test not supported for cisco as it doesnt support single hop BFD. Skipping the test)INFO:SectionStartLogger:==================== bfd/test_bfd.py::test_bfd_basic[ipv4-dut_init_first] teardown ====================
bfd/test_bfd.py::test_bfd_basic[ipv4-ptf_init_first] INFO:SectionStartLogger:==================== bfd/test_bfd.py::test_bfd_basic[ipv4-ptf_init_first] setup ====================
SKIPPED (Test not supported for cisco as it doesnt support single hop BFD. Skipping the …

Extended the SingleHop BFD skip to other cisco platforms

---

tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py

Summary:
Current snappi multidut tests wait 15 minutes to finish a reboot as the default waiting time is 900 seconds for chassis.
However, when using safe reload, it will finish the reboot in 10 minutes. Also, existing non multidut test cases have changed to use safe reboot as well. 
Therefore, setting multidut cases to use safe reboot.
reduce reboot time for multidut snappi cases.
Use safe reboot.
Tested on lab devices.

[Snappi] enable safe reboot for multidut snappi cases.

---

tests/memory_checker/test_memory_checker.py

Summary:
Microsoft ADO: 29720467
test_memory_checker is flaky.
This test failed to capture this message: "2024 Oct  8 11:30:39.182886 vlab-01 INFO systemd[1]: Started gnmi.service - GNMI container."
loganalyzer needs to check all the syslog in this time frame, now we wait until gnmi service is running to give loganalyzer enough time to find expected messages.
Run test_memory_checker for serveral times.

Wait for service to fix flaky memory_checker test

---

tests/common/gu_utils.py

Summary: Add timeout for GCU to check performance
Set a timeout for GCU command instead of wait forever.
Add timeout
E2E test

Add GCU timeout for qualification

---

tests/common/helpers/sonic_db.py

Summary:
Fix the following error:
```
E         File "<unknown>", line 1
E           {'lldp_rem_time_mark': '845', 'lldp_rem_sys_desc': 'Cisco Nexus Operating System (NX-OS) Software 6.0(2)U6(5c)
E                                                                                                                        ^
E       SyntaxError: EOL while scanning string literal
/usr/lib/python3.8/ast.py:47: SyntaxError
```
The output of sonic-db-cli has newline characters which caused `SyntaxError: EOL while scanning string literal`
```
admin@str2-7050cx3-acs-10:~$ sudo sonic-db-cli APPL_DB hgetall LLDP_ENTRY_TABLE:eth0
{'lldp_rem_time_mark': '61', 'lldp_rem_sys_desc': 'Cisco Nexus Operating System (NX-OS) Software 6.0(2)U6(5c)
TAC support: http://www.cisco.com/tac
Copyright (c) …
```

Fix SyntaxError for test_lldp_syncd

---

tests/ip/test_ip_packet.py

Reverts sonic-net/sonic-mgmt#14620

Revert "[action] [PR:14597] RX_DROP counter if destination MAC is not the router MAC on L3 interface"

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Resolve conflict from PR https://github.com/sonic-net/sonic-mgmt/pull/14866
Skip the generic_config_updater/test_incremental_qos.py, since it does not support dualtor. Issue link: https://github.com/sonic-net/sonic-mgmt/issues/14865
To skip a test case that does not support dualtor, so we don't waste time running it
By edited the tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
The test https://github.com/sonic-net/sonic-mgmt/blob/master/tests/generic_config_updater/test_incremental_qos.py is not ready for Dual Tor.
`generic_config_updater/test_incremental_qos.py::test_incremental_qos_config_updates[add-ingress_lossless_pool/xoff] `
As of right now, the test will error out during
```
File "/tests/generic_config_updater/test_incremental_qos.py", line 158, in …
```

Skip test incremental qos on dualtor testbed

---

tests/test_pretest.py

Summary:
This PR is to workaround issue https://github.com/opencomputeproject/SAI/issues/2086
The python_sai_thrift library is not installed to the right directory, which leads to qos_sai test failure.
This PR is to workaround `python_sai_thrift` path issue.
Copy `switch_sai_thrift` folder from `saithrift-0.9-py3.11.egg` to the parent folder.
The change is verified by running `test_update_saithrift_ptf`.
```
test_pretest.py::test_update_saithrift_ptf PASSED …
```

Workaround python_sai_thrift path issue

---

tests/dhcp_relay/conftest.py

Summary: All TCs in `test_dhcp_relay` fails for `202405` image on device with `hwsku` of `Cisco-8111-O64`. 
Fixes # (issue)  
Add `BackEndLeafRouter` in `minigraph_devices` `type` expected.
The `type` of `minigraph_devices` set in `202405` is `BackEndLeafRouter` ; whereas in `202311` it was `LeafRouter` ; TC expects `type` to be `LeafRouter` / `MgmtLeafRouter` to set `uplink_interfaces` variable, else, it doesn’t set due to which in `202405` `uplink_interfaces` are empty & when they try to obtain the mac address of uplink interface for `dhcp_relay_data`, script errors out.
Minigraph sets the `type` for the devices, In [PR : enable compute-ai for 8111-t1](https://github.com/sonic-net/sonic-mgmt/pull/11019) for `hwsku` of `Cisco-8111-O64` , `dut_type` set for `t0` , `t1` is …

Fix for test_dhcp_relay failures on hwsku of Cisco-8111-O64

---

tests/vlan/test_vlan_ping.py

Summary:
This PR is to fix code issue in `test_vlan_ping`.
The test is flaky because the incorrect indention. `port_index_list` is empty because of the early break.
```
E       AssertionError: Received expected packet on port 29 for device 0, but it should have arrived on one of these ports: [].
E       ========== RECEIVED ==========
E       0000  62 72 C3 B6 7F 81 50 6B 4B 93 96 00 08 00 45 00  br....PkK.....E.
E       0010  00 2E 00 01 00 00 3F 01 B0 E9 C0 A8 00 02 0A 00  ......?.........
E       0020  00 3B 08 00 46 4E 00 00 00 00 30 30 30 30 30 30  .;..FN....000000
E       0030  30 30 30 30 30 30 30 30 30 30 30 30              000000000000
E       ==============================
```
The issue was introduced by …

Fix test_vlan_ping

---

.azure-pipelines/recover_testbed/common.py

Summary:
Auto-Recovery failed on DUTs running 201911 and earlier images because `sonic-installer` cannot be found. (Sample ElasticTest TestPlan ID: 670534543331ab71a12f5e93) Creating this PR to resolve this issue.
Auto-Recovery failed on DUTs running 201911 and earlier images because `sonic-installer` cannot be found. (Sample ElasticTest TestPlan ID: 670534543331ab71a12f5e93) Creating this PR to resolve this issue.
Auto-Recovery failed on DUTs running 201911 and earlier images because `sonic-installer` cannot be found. (Sample ElasticTest ID: 670534543331ab71a12f5e93) Creating this PR to resolve this issue.
Verified on SN2700 with SONiC.201911 installed:
```
zhijianli@sonic-mgmt-zhijianli:~/mgmt/sonic-mgmt-int/ansible$ python3 ../.azure-pipelines/recover_testbed/recover_testbed.py -i bjw …
```

[Console Recovery] Use sonic_installer to adapt elder SONiC images

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

As part of #11968, a bugfix was introduced in the `find_longest_matches` function to identify only the longest matching entry in `tests_mark_conditions.yaml`. 
The previous bug led to incorrect behavior in finding the matching entries, deviating from our intended logic **before**:
- Our expected behavior was to retrieve **only** the longest matching entry and evaluate the conditions under this single, unique entry.
- Instead, the bug caused the function to retrieve all entries matching the test case prefix, evaluating conditions from all matching entries.
This resulted in an unintended situation where conditions from shorter matching entries which are absent in the longest one would still be considered during evaluation.
In PR #14395, we optimized the logic for finding marks in …

[Bugfix]Adding conditions to longer matching entries in conditional marks

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py

Summary: Added port configuration and th5 asic entry for Arista-7060X6-64PE-C256S2.
Support for Arista-7060X6-64PE-C256S2 HwSku.
Added port configuration and th5 asic entry for Arista-7060X6-64PE-C256S2.
Verified that a testbed can be initialized under a t0 topo and sonic-mgmt tests can be run.
Specific to the Arista-7060X6-64PE-C256S2 HwSku.

sonic-mgmt: Initial support for Arista-7060X6-64PE-C256S2

---

.github/workflows/automerge_scan.yml

Summary:
When auto cherry pick PR is closed&reopen to rerun validation. post_cherry_pick action will be skipped.
Auto-merge scaning action will not merge that PR.

[github] Fix automerge github action issue when close&reopen PR.

---

tests/dualtor/files/y_cable_simulated.py.j2
tests/dualtor/test_switchover_faulty_ycable.py

Summary:
To fix test gap: https://github.com/sonic-net/sonic-mgmt/issues/12311
To simulate a faulty ycabled, a templated `y_cable_simulated.py` is used to replace the original `ycable` driver.
With the faulty `ycable` driver, two testcases are added:
1. add `test_switchover_probe_unknown` to verify dualtor could toggle as expected even `ycabled` returns mux probe `unknown`.
2. add `test_switchover_peer_link_down` to verify dualtor could toggle as expected even `ycabled` returns peer link `down`.
```
dualtor/test_switchover_faulty_ycable.py::test_switchover_probe_unknown PASSED …
```

[dualtor][test gap] Add testcases to cover the faulty ycable

---

.github/workflows/automerge_scan.yml

Summary:
PR auto-merge always fail on 'gh pr list' step.
It is caused by query timeout. Reduce PR info size will help.

[ci] Fix gh pr list issue caused by timeout.

---

tests/dhcp_relay/conftest.py

Summary:
Skip dhcp_relay test by feature status rather than topo
Skip dhcp_relay test by feature status rather than topo
Run tests
```
collected 1 item                                                                                                                                                                                                                                                
dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default SKIPPED (dhcp_relay is not enabled)                           
```

[dhcp_relay] Skip dhcp_relay test via feature status rather than topo

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skipping EverflowV4 EgressAcl EgressMirror for Cisco-8000 as the feature is currently not fully supported. Will remove the fix once the feature is validated. 
Replacing Xfail with Skip for test mirror with policer since it is not supported on Cisco 8000 platforms. Xfail was causing the test to run and then xfail which is not desirable, since the testcase is not supported.
Summary:
For Cisco Platforms

Skipping EverflowV4 EgressAcl EgressMirror for Cisco-8000

---

tests/common/snappi_tests/traffic_generation.py
tests/snappi_tests/ecn/files/ecnhelper.py
tests/snappi_tests/ecn/test_ecn_marking_cisco8000.py

Summary:
MIGSMSFT-630 Add sonic-mgmt / IXIA test for cisco platforms to verify ECN Counter operation.
- Create two flows one for each lossless TC per Ixia port each at half of 99.98% rate 
- Inject traffic and read ECN Counters and verify it incremented.
- flap the interface state (shut, wait for 0.2 seconds, no shut the interfaces of  Ixia)
- restart the traffic streams
- verify that the ECN counters increment from the baseline value (new values read MUST NOT be zero)
Verified on M64 and Compute AI T1 profiles.

sonic-mgmt / IXIA test for cisco platforms to verify ECN Counter operation.

---

tests/bfd/bfd_helpers.py

Remove the `ip netns exec asicX` part from the link toggle command in BFD tests as the `-n` option in `config interface` takes care of the namespace.
Summary:
Fixes # (issue) Microsoft ADO 29752063
We are seeing some flaky issue when toggling the interface with `ip netns exec asicX` in the command. Cisco suggests to remove this part from the command as the `-n` option already takes care of the namespace.
I ran the updated code and can confirm it's working as expected.

chore: change link toggle command in BFD

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Extended the SingleHop BFD skip to other cisco platforms
Double commi PR# https://github.com/sonic-net/sonic-mgmt/pull/14862
Summary:
Extended the SingleHop BFD skip to other cisco platforms
Ran sonic-mgmt to validate the change
bfd/test_bfd.py::test_bfd_basic[ipv4-dut_init_first] INFO:SectionStartLogger:==================== bfd/test_bfd.py::test_bfd_basic[ipv4-dut_init_first] setup ====================
SKIPPED (Test not supported for cisco as it doesnt support single hop BFD. Skipping the test)INFO:SectionStartLogger:==================== bfd/test_bfd.py::test_bfd_basic[ipv4-dut_init_first] teardown ====================
bfd/test_bfd.py::test_bfd_basic[ipv4-ptf_init_first] INFO:SectionStartLogger:==================== bfd/test_bfd.py::test_bfd_basic[ipv4-ptf_init_first] …

Extended the SingleHop BFD skip to other cisco platforms Doublecommit#14862

---

tests/test_pretest.py

Summary:
This PR is to fix an issue in PR https://github.com/sonic-net/sonic-mgmt/pull/14886
The dst_path should be `/usr/lib/python3/dist-packages/`, not `/usr/lib/python3/dist-packages/switch_sai_thrift`
This PR is to fix an issue in PR https://github.com/sonic-net/sonic-mgmt/pull/14886
Fix the dest_path.
The change is verified by running `qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit`.
```
collected 20 items                                                                                                                                                                                    
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_1] 
------------------------------------------------------------------------------------------- live log setup …
```

Update dst_path for switch_sai_thrift library

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
This PR is to cherry-pick #14731 to `202405` branch.
This PR is to cherry-pick #14731 to `202405` branch.
Do a manual cherry-pick after resolving conflict.
No code change.
Mellanox platform specific.

[202405][Cherry-pick]Skip error message due to missing feature (#14731)

---

tests/common/dualtor/mux_simulator_control.py
tests/common/plugins/sanity_check/checks.py

Summary:
Fix the following sanity check issue:
```
check_passed, err_msg, duts_mux_status = _check_dut_mux_status(duthosts, duts_minigraph_facts, **kwargs)
if not check_passed:
logger.warning(err_msg)
results['failed'] = True
results['failed_reason'] = err_msg
results['hosts'] = [dut.hostname for dut in duthosts]
results['action'] = _recover
return results
mux_simulator_status = get_mux_status()
upper_tor_mux_status = duts_mux_status[duthosts[0].hostname]
>       for status in list(mux_simulator_status.values()):
E       AttributeError: 'NoneType' object has no attribute 'values'
```
The issue is due to that `get_mux_status` returns `None` if it fails to get mux status from mux simulator due to HTTP timeout.
Let's check if the mux status is `None`, if it is, let's restart …

[dualtor][sanity] Restart mux simulator if sanity fails to get mux status

---

tests/bgp/test_bgp_stress_link_flap.py

Fix test_bgp_stress_link_flap.py deadlocks by converting test to use asyncio instead of multi-threading as Ansible python API is not thread safe. 
This will also resolve memory issues on VM environments caused by the test spawning a large number of threads
Refactored some parts of the test to remove the memory checks (as we don't use threads anymore) and remove duplicate code.
Summary:
Fixes #14891
Reduce flakiness of test_bgp_stress_link_flap.py as it may hit deadlock issues during Ansible calls.
Converted test to use asyncio instead of multi-threading
Ran test on testbed

convert bgp stress link flap test to use asyncio

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

-->
Adding and removing traps still unsupported for 7050CX3 SKUs in 202405 as well, so should continue to xfail tests.
Same as https://github.com/sonic-net/sonic-mgmt/pull/14219 but for 202405 since tests should continue to be xfailed
Summary:
Fixes https://github.com/aristanetworks/sonic-qual.msft/issues/200

[202405] Xfail copp add/remove trap tests on 7050CX3 SKUs

---

tests/arp/test_unknown_mac.py

Summary:
Fix fixture order to eliminate flaky test 
Make the fixture ```flushArpFdb``` depend on the fixture ```dut_disable_arp_update```, so that the fixture ```populateArp``` depends on ```flushArpFdb```, which in turn depends on ```dut_disable_arp_update```. This ensures that ARP updates are disabled and tables are cleared before populating the ARP entry.
Validate it in the internal setup: arp/test_unknown_mac.py
```
-------------------------------------------------------------- generated xml file: /data/sonic-mgmt-int/tests/logs/arp/test_unknown_mac.xml ---------------------------------------------------------------
----------------------------------------------------------------------------------------- live log sessionfinish …
```

Adjust fixture order in arp test unknown mac

---

tests/common/helpers/parallel_utils.py
tests/common/plugins/sanity_check/recover.py
tests/conftest.py

Summary:
We're using multi process to reload and recover the chassis.
But the error is not caught well if the issue is happening during recover.
Use multi-thread to obtain better visibility of errors.
We're using multi process to reload and recover the chassis.
But the error is not caught well if the issue is happening during recover.
Use multi-thread to obtain better visibility of errors.
Use multi-thread instead of multi-process
Test it on physical testbed.

[Refine] Use multi-thread to recover chassis

---

tests/common/helpers/constants.py
tests/common/helpers/custom_msg_utils.py
tests/common/plugins/sanity_check/__init__.py
tests/conftest.py

Instead of fixture, log_custom_msg is now called in one of hook (pytest_runtest_makereport). This is to prevent unexpected sequence of fixture teardown observed in nightly. Calling log_custom_msg from pytest_runtest_makereport will be one of the very last hooks to be called for each test.
Summary:
Instead of fixture, log_custom_msg is now called in one of hook (pytest_runtest_makereport). This is to prevent unexpected sequence of fixture teardown observed in nightly. Calling log_custom_msg from pytest_runtest_makereport will be one of the very last hooks to be called for each test.
log_custom_msg being called before post_sanity_check
instead of fixture log_custom_msg, relocated the call to pytest_runtest_makereport
elastic-test using testplan

Relocate log_custom_msg to assure test results to be logged

---

tests/acl/test_acl.py

Summary:
`TestAclWithReboot` is flaky on some testbed with below errors
```
AssertionError: Received expected packet on port 5 for device 0, but it should have arrived on one of these ports: [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31].
========== RECEIVED ==========
0000  02 5B 4B 46 AB 7D 1C 34 DA EB C2 00 08 00 45 00  .[KF.}.4......E.
0010  00 56 00 01 00 00 3F 06 A5 FA 14 00 00 02 C0 A8  .V....?.........
0020  00 FD 43 21 00 51 00 00 00 00 00 00 00 00 50 02  ..C!.Q........P.
0030  20 00 C6 9A 00 00 74 65 73 74 5F 61 63 6C 20 74   .....test_acl t
0040  65 73 74 5F 61 63 6C 20 74 65 73 74 5F 61 63 6C  est_acl test_acl
0050  20 74 65 73 74 5F 61 63 6C 20 74 65 73 74 5F 61   test_acl test_a
0060  63 6C 20 74                                      cl t …
```

Wait BGP sessions estabilished in ACL reboot test

---

tests/qos/test_qos_sai.py
tests/saitests/py3/sai_qos_tests.py

Summary:
This PR addresses 2 fails in qos-sai runs on cisco-8000 platform. They are:
1. testQosSaiDscpToPgMapping: The script reads the base counters before starting the actual test loop. However, there is a pretest-packet that is sent before reading the counters. Since there is no delay between sending the pre-test packet and the reading of the base counters, the base counter doesn't include the pre-test packet. In this PR, we are adding a 3 second delay before reading the base counters.
2. wm_pg_shared_lossy failure: This test is not applicable to T2/multidut/multiasic variants. So the qos.yaml doesn't even have the required key for this test. So we are adding a skip in this PR for this test.
Test qos sai failures in 202405.
Pls see the description on how these issues are addressed.
Ran …

Fixing the failures in qos-sai on 202405.

---

tests/ip/test_ip_packet.py

Cherry pick #14597 into 202405, removed skip_traffic_test check as it's not available in 202405 branch.
Summary:
Fix #10638 
Check RX_DRP counter if destination MAC is not the router MAC on L3 interface
Send layer 3 packets with non-DUT MAC
Tested it on Cisco and broadcom platform, all passed.  
```
ip/test_ip_packet.py::TestIPPacket::test_drop_l3_ip_packet_non_dut_mac[xxx-7060cx-32s-xxx] PASSED [100%]
ip/test_ip_packet.py::TestIPPacket::test_drop_l3_ip_packet_non_dut_mac[xxx-8101-x] PASSED [100%]
```
It failed on Mellanox platform. Mellanox does not log rx_drp or rx_err counter if destination MAC is not DUT MAC. We can add specific check if Mellanox is not planning to support this test case.
```
ip/test_ip_packet.py::TestIPPacket::test_drop_l3_ip_packet_non_dut_mac[xxx-4600c-xx] FAILED …
```

[202405][PR:14597] RX_DROP counter if destination MAC is not the router MAC on L3 interface

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
Move dhcp_relay stress test to onboarding due to flaky
Move dhcp_relay stress test to onboarding due to flaky

[dhcp][pr_test] Move dhcp_relay stress test to onboarding

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Xfail fdb/test_fdb_mac_learning.py::TestFdbMacLearning::testARPComplete on Broadcom platforms due to known issue 
https://github.com/aristanetworks/sonic-qual.msft/issues/267

[202405] Xfail fdb/test_fdb_mac_learning.py::TestFdbMacLearning::testARPComplete on Broadcom platforms

---

tests/common/reboot.py
tests/platform_tests/test_reboot.py

Summary:
Fixes  https://github.com/sonic-net/sonic-mgmt/issues/13459
To validate the functionality of the determine-reboot-cause service in SONiC. This service is responsible for detecting and logging the cause of system reboots (e.g., cold reboot, warm reboot, fast reboot, etc.). Accurate identification of reboot causes is critical for troubleshooting, monitoring, and maintaining system stability, so ensuring its correctness and reliability is essential.
1. Verify the service running status:
- After each type of reboot, verify the determine-reboot-cause service status.
2. Validated Logs:
- After each reboot, validated the system logs to confirm that the correct reboot cause was captured by the determine-reboot-cause service.
- Ran unit tests to validate the logic inside the …

Check for determine-reboot-cause service status

---

tests/tacacs/test_authorization.py

Fix test authorization failed on S6000 issue by split test case.
Test authorization failed on S6000 device.
This is because S6000 have slowly CPU which make command 2-3 times slowly than other platform.
Because test authorization test case run too many commands with a new SSH session, the ansible ssh session will timeout and break.
- Microsoft ADO: 29720857
Split test case to 3 small test cases.
Manually verify the test case can pass on S6000 platform.
Fix test authorization failed on S6000 issue by split test case.

[202305] Fix test authorization failed on S6000 issue by split test case.

---

tests/scripts/getbuild.py

[CI]Fix get build 202205 failed by remove url param 'resultFilter=succeeded'

---

tests/tacacs/test_authorization.py

[202305] Fix test_tacacs_authorization_wildcard failed on S6000 issue by split test case. 
Test authorization failed on S6000 device.
This is because S6000 have slowly CPU which make command 2-3 times slowly than other platform.
Because test authorization test case run too many commands with a new SSH session, the ansible ssh session will timeout and break.
- Microsoft ADO: 29720857
Split test case to 2 small test cases.
Manually verify the test case can pass on S6000 platform.
[202305] Fix test_tacacs_authorization_wildcard failed on S6000 issue by split test case.

[202305] Fix test_tacacs_authorization_wildcard failed on S6000 issue by split test case. 

---

tests/lldp/test_lldp_syncd.py

Summary:
- In test_lldp_entry_table_after_reboot case, it will reboot DUT, syslog will lost after reboot, start mark will not be found when try to do log analysis, and there will be some ERROR or WARNING syslog during bootup, LogAnalyzer needs to be disabled for this case.
- For some DUTs, eth0 connects to some switches which `lldp_rem_sys_cap_enabled` is `20 00` instead of `28 00`, need to consider both scenarios.
Fix the failure of test_lldp_entry_table_after_reboot and the failure due to `Failed: lldp_rem_sys_cap_enabled does not match for eth0`
add `@pytest.mark.disable_loganalyzer `for `test_lldp_entry_table_after_reboot `
Consider `20 00` as valid value for eth0's `lldp_rem_sys_cap_enabled`
Run `lldp/test_lldp_syncd.py`

Disable loganalzyer for test_lldp_entry_table_after_reboot

---

ansible/roles/fanout/templates/arista_7260cx3_deploy.j2
ansible/templates/minigraph_link_meta.j2

…
This pull request introduces modifications to the `arista_7260cx3_deploy.j2` and `minigraph_link_meta.j2` templates in the sonic-mgmt repository. The changes primarily focus on handling speed and auto-negotiation configurations for devices.
- Autoneg/Forced speed setting is applied directly as 100gfull with Reed-Solomon error correction encoding.
- Adjusted the interface naming convention for devices, now consistently using the EthernetX/1 format.
Removed vendor-specific logic (Mellanox handling) to unify the approach for generating auto-negotiation metadata across devices.
Summary:

[ansible][minigraph] Enhance template for adding autonegotiation in Mellanox and add Arista 7260 template changes

---

tests/pc/test_lag_member.py

Summary:
PR #14001 moved the lag_test PTF script into the Python 3 folder, but PR #14031 missed updating this test.
Update this test to reflect that the lag_test script should be run under Python 3.
Tested it on KVM after removing the mark to skip this test case on KVM and skipping the ARP checks.

Enable Py3 for test_lag_member

---

tests/common/config_reload.py

Fix reload_config failed on M0 device because PFCWD feature does not exist
test case test_fallback_to_local_authorization_with_config_reload failed on M0 device when reload config.
It's because PFCWD feature does not exist on M0.
- Microsoft ADO: 28794363
Ignore check when PFCWD feature not enable on device.
Fix reload_config failed on M0 device because PFCWD feature does not exist

[202305] [cherry-pick] Fix reload_config failed on M0 device because PFCWD feature does not exist #14138

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/qos/qos_sai_base.py
tests/qos/test_qos_sai.py
tests/saitests/py3/sai_qos_tests.py

Summary:
ptf64 topology is used to have 64 ports of the DUT connected
to 64 PTF ports.
Ran the test on a T1 ptf-64 topology
This is a Cisco specific test case

Full Mesh Traffic Sanity verification 

---

tests/qos/qos_sai_base.py

Summary:
Add support to provide a suffix to the test case log file name.
this will be useful in test cases where there are multiple runs with different combinations 
being invoked and each run can be logged as a separate log file for easier tracking.
Added log_suffix as a dict key to testParams
Ran it as part of FullMeshTrafficSanitytestcase #11968

Add a  suffix to the testcase logfile 

---

tests/common/platform/device_utils.py

Summary:
Fix transceiver checker function for MGFX DUT
Fix transceiver checker function for MGFX DUT.
For MGFX platform, only Ethernet48 ~ Ethernet51 are transceiver interfaces. Restrict the checking on those 4 ports.
Verified by upgrade-path test.

[MGFX] Fix transceiver checker function for MGFX DUT

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Cisco-8000 doesn't support global pfc pause, it ignores it. So we need to skip the global pause test in the snappi_tests.
Fixes # [14807](https://github.com/sonic-net/sonic-mgmt/issues/14807)
Cisco-8000 doesn't support global pfc pause.
Added the skip in the common skip file.
Ran it with my TB:
```
================================================================================================================== short test summary info ===================================================================================================================
SKIPPED [2] snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py:17: Global pause is not supported in cisco-8000.
=============================================================================================================== 2 …
```

snappi: Adding a skip for global pause test in cisco-8000.

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/restapi/test_restapi_vxlan_ecmp.py

Summary:
Enabled the Test on 4600C T1.
Better test coverage.
Enabled the test.
Ran the test naually on 4600
```
$ ./run_tests.sh -n  vms18-t1-msn4600c-acs-1  -i ../ansible/str2,../ansible/veos -r -u -c restapi/test_restapi_vxlan_ecmp.py
=== Running tests in groups ===
Running: python3 -m pytest restapi/test_restapi_vxlan_ecmp.py --inventory ../ansible/str2,../ansible/veos --host-pattern str2-msn4600c-acs-01 --testbed vms18-t1-msn4600c-acs-1 --testbed_file /var/src/sonic-mgmt-int/ansible/testbed.yaml --log-cli-level warning --log-file-level debug --kube_master unset --showlocals --assert plain --show-capture no -rav --allow_recover --ignore=ptftests --ignore=acstests --ignore=saitests --ignore=scripts --ignore=k8s --ignore=sai_qualify --junit-xml=logs/tr.xml …
```

restapi_vxlan_ecmp_test on mlnx 4600 and 8000 T1

---

tests/qos/files/qos_params.spc3.yaml

Update qos parameters for hwsku Mellanox-4700-V64 and topology dualtor-aa-64-breakout
It could make sure case test_tunnel_qos_remap#test_xoff_for_pcbb could PASS at hwsku Mellanox-4700-V64 and topology dualtor-aa-64-breakout
Summary:
Make case test_tunnel_qos_remap#test_xoff_for_pcbb could PASS at hwsku Mellanox-4700-V64 and topology dualtor-aa-64-breakout
Add qos parameters
MSN4700 hwsku Mellanox-4700-V64 and topology dualtor-aa-64-breakout

Update qos parameters for hwsku Mellanox-4700-V64 and topology dualtor-aa-64-breakout

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skip CRC algorithm test on INNER_IP_PROTOCOL field
Skip the test combination due to hw limitation
Summary:
HW limitation
Skip specific cases
Run the script in internal regression

Skip CRC algorithm test on INNER_IP_PROTOCOL field

---

tests/macsec/__init__.py
tests/macsec/macsec_config_helper.py

macsec tests when run on T2 chassis fail with a runtime exception, due to tbinfo not being passed into a get_extended_minigraph_facts() call.
Also assert if the macsec links fail to be ok when bringing up the test case
Summary:
Fixes #15078
- [x ] Bug fix
- [x ] 202405

[macsec] pass tbinfo to get_extended_minigraph_facts

---

tests/hash/test_generic_hash.py

Vxlan port could not be saved in config db
So config it again after config reload in generic hash reboot test case
Summary:
Vxlan port configuration was not reserved in config db, so need to reconfig it again after config reload or reboot
Config vxlan port configuration again.

Config vxlan port after config reload

---

tests/bgp/test_traffic_shift.py

Add a loop check of loopback route after config reload for script test_traffic_shift.py.
It would loop check the loopback route after port all up in a config reload.
And it would make the test more stable.
Summary:
Under some situation, the when the ports are UP in a config reload, the bgp routes are not all ready. The loopback route check would be failed at this moment.
Add a loop check for it.

Add a loop check of loopback route after config reload for script test_traffic_shift.py

---

tests/syslog/test_logrotate.py

Increase the check option of config reload in fixture simulate_small_var_log_partition
It would leave a clean environment for test case test_orchagent_logrotate
Summary:
Fix the issue that the first loop failure of case test_orchagent_logrotate
Add check option in the config reload function of fixture simulate_small_var_log_partition.
It would leave a clean and fully recovered environment for case test_orchagent_logrotate.

Increase the check option of config reload in fixture simulate_small_var_log_partition

---

ansible/roles/fanout/tasks/sonic/fanout_sonic_202311.yml

To compatible with the latest software implementation, update some steps in fanout switch deployment:
Add pmon_daemon_control.json handle step
Add media_settings.json handle step
Add optics_si_settings.json handle step
Summary:
To compatible with the latest software implementation
Add pmon_daemon_control.json handle step
Add media_settings.json handle step
Add optics_si_settings.json handle step

Update software control module disable steps in fanout deployment

---

ansible/group_vars/sonic/variables

Update hwsku Mellanox-SN4700-O32 into mellanox_spc3_hwskus
Summary:
New hwsku validation
Add the hwsku Mellanox-SN4700-O32 into mellanox_spc3_hwskus
Mellanox SN4700
t1-32-lag

Update hwsku Mellanox-SN4700-O32 into mellanox_spc3_hwskus

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Add dualtor-64-breakout topology to support case test_cacl_application_dualtor
Summary:
Case test_cacl_application_dualtor shall run on topology dualtor-64-breakout
Update the skip condition
Run it locally

Add dualtor-64-breakout topology to support case test_cacl_application_dualtor

---

tests/pfcwd/conftest.py

Add t1-32-lag support into supported t1 topology list
Summary:
Enhance the script over t1-32-lag tolopogy.
Add t1-32-lag support
t1-32-lag

Update t1-32-lag support to pfcwd script

---

tests/hash/generic_hash_helper.py
tests/hash/test_generic_hash.py

Currently, due to the limitation of ingress port number, the hash result is not good for ingress port hash test when ecmp and lag hash at the same time.
As a result, it need to assign a specific balance deviation threshold for this scenario for Mellanox platform
Summary:
Currently, due to the limitation of ingress port number, the hash result is not good for ingress port hash test when ecmp and lag hash at the same time.
Assign a specific balance deviation threshold for this scenario for Mellanox platform

Assign a specific balance deviation threshold for ingress port hash test

---

tests/acl/test_acl_outer_vlan.py
tests/common/helpers/portchannel_to_vlan.py

Update skip condition of po2vlan test for sonic fanout
For mellanox sonic fanout switch, related cases could pass
Summary:
Update skip condition of po2vlan test for sonic fanout
For mellanox sonic fanout switch, related cases could pass
Add "mellanox" asic type to support list
No

Update skip condition of po2vlan test for sonic fanout

---

tests/qos/files/mellanox/qos_param_generator.py

The headroom_overhead and extra_margin that aligned for 400G only applicable for the SPC3, for SPC4, need to do additional alignment.
Summary:

Fix test issue of the qos for the SPC4

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary: Ignore loganalyzer error for syncd _attribute_enum_values_capability
Errors to ignore are like:
ERR syncd#syncd: [none] SAI_API_HASH:sai_query_native_hash_attribute_enum_values_capability:2462 count 11 greater than capability-count 0 
ERR syncd#syncd: [none] SAI_API_SWITCH:sai_query_switch_attribute_enum_values_capability:22146 count 6 greater than capability-count 0
The error is normal as it is printed for querying the available count first before the actual query, where capability-count is always 0. 
The API call is from https://github.com/sonic-net/sonic-swss/blob/master/orchagent/switch/switch_capabilities.cpp#L316-L324
Ignore the logs in log analyzer
Tested with "drop_packets/" which was failed the issue.

Ignore loganalyzer error for syncd _attribute_enum_values_capability

---

tests/vlan/test_vlan.py

Fix test_vlan_tc5_untagged_unicast by reverting the dst_port change in https://github.com/sonic-net/sonic-mgmt/pull/12204
Summary:
Fixes #14927 (issue)
We found error below in running the testcase test_vlan_tc5_untagged_unicast
AssertionError: Received packet that we expected not to receive on device 0, port 43
Revert the dst_port change in
https://github.com/sonic-net/sonic-mgmt/pull/12204
Tested that the test case can pass after this change.

Fix regression on test_vlan_tc5_untagged_unicast

---

tests/pfcwd/files/pfcwd_helper.py
tests/pfcwd/test_pfcwd_function.py

Summary:
This is a **cherry-pick** PR to 202311 branch for the original one #11656 
- PFCWD test ‘test_pfcwd_multi_port’ is SKIPPED for T2-Chassis, with the following error.
_'Skipped: Pfcwd multi port test needs at least 2 ports'_
- This PR addresses the above issue, unskips the multi-port test for pfcwd suite with a generic fix.
- _pfcwd/conftest.py : setup_pfc_test:_ - the modulo logic used to pick ports from the test_ports is always false in T2 case.
- Due to which, the test gets skipped because of the number of selected ports check, which is always 1 for a T2 DUT.
`pytest_require(len(selected_ports) == 2, 'Pfcwd multi port test needs at least 2 ports'))`
- Added a generic fix based on the total number of test ports.
- Ran PFCWD suite including, test_pfcwd_multi_port …

[Cherry-pick] [PR:11656] Generic fix to unskip pfcwd_multi_port test from skipped list for t2

---

tests/qos/qos_sai_base.py

Filter port with not matched speed and cable length in ptf32 topology when running qos sai dualtor test
Summary:
Test case failure on some testbed
Add test ports filter when running test at ptf32 topology

Filter port with not matched speed and cable length in ptf32 topology

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Add dualtor-64-breakout topology to support case test_cacl_application_dualtor
Summary:
Case test_cacl_application_dualtor shall run on topology dualtor-64-breakout
Update the skip condition
Run it locally

Integrate test_cacl_application_dualtor test

---

tests/configlet/util/common.py

Add 'last_down_time' into 'keys_skip_val_comp' to avoid "DB compare failed after adding T0 via generic patch updater"
Summary:
DB compare failed after adding T0 via generic patch updater
Add 'last_down_time' into 'keys_skip_val_comp'

Update last_down_time to keys_skip_val_comp in configlet test

---

tests/memory_checker/test_memory_checker.py

Summary:
Fixes # (issue):Microsoft ADO 29793270
Extend test fail timeout for weak hardware support (S6000)
Some weak hardware(S6000) needs to be support, which is slow and break test due to timeout.
Extend failure timeout.
It won't extend test time, just declare failure timeout is changed.
S6000
N/A

Extend test fail timeout for weak hardware support.

---

tests/common/platform/transceiver_utils.py
tests/platform_tests/api/test_sfp.py
tests/platform_tests/conftest.py
tests/platform_tests/mellanox/test_check_sfp_eeprom.py
tests/platform_tests/mellanox/util.py
tests/platform_tests/test_xcvr_info_in_db.py

1. Sfp eeprom with option dom is not working on Xcvrs with flat memory. There is a relevant PR:https://github.com/sonic-net/sonic-utilities/pull/3385. Therefore, skip dom check for sfp with flat memory.  Also, fix sonic mgmt issue: https://github.com/sonic-net/sonic-mgmt/issues/12981
2. Skip test ports with flat memory for test_get_transceiver_bulk_status
Summary:
Fix issue： https://github.com/sonic-net/sonic-mgmt/issues/12981
Skip dom checker for sfp with flat memory
run test_xcvr_info_in_db and test_check_sfp_eeprom_with_option_dom 
Any

[202405] Update platform sfp tests to skip dom check for sfp with flat memory

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Summary:
test_power is skipped by https://github.com/sonic-net/sonic-mgmt/pull/5409
It was an unsupported function at that time.
Not it's supported, hence remove the skip mark.
Scan and review skipped test cases on Cisco 8800 chassis.
Enable test_power.
run on physical testbeds.
platform_tests/api/test_psu.py::TestPsuApi::test_fans[***-sup-1] PASSED [ 88%]
platform_tests/api/test_psu.py::TestPsuApi::test_power[***-sup-1] PASSED [ 90%]
platform_tests/api/test_psu.py::TestPsuApi::test_temperature[***-sup-1] PASSED [ 92%]

[Cisco 8800 test gap] Remove the skip mark for platform_tests/api/test_psu.py::TestPsuApi::test_power

---

ansible/vars/topo_t0-isolated-d128u128s2.yml
ansible/veos
docs/testbed/README.testbed.Overview.md

Summary:
add a new t0 topo with 128 downstream and 128 upstream ports and 2 service ports.
For bp_interfaces IP, used continuous IP from .2 to .131 to avoid going over /24 range.

add topo t0-isolated-d128u128s2

---

tests/conftest.py

Existing log_custom_msg was called for every test cases' teardown. Update this to reduce number of customMsg per test session and only register to very last test
Summary:
Existing log_custom_msg was called for every test cases' teardown. Update this to reduce number of customMsg per test session and only register to very last test
How to use: 
import DUT_CHECK_NAMESPACE from tests.common.helpers.constants
from tests.common.helpers.custom_msg_utils import add_custom_msg
add_custom_msg(request, f"{DUT_CHECK_NAMESPACE}.{customMsgNameYouWant}", {customMsgValueYouWantToStore})
Every cache value under DUT_CHECK_NAMESPACE will be stored in a dictionary and uploaded to Data Explorer
Investigation:
pytest_sessionfinish is the very last function to be called after all test cases are done. But due …

Update when customMsg is logged

---

ansible/library/fetch_no_slurp.py
ansible/plugins/action/fetch_no_slurp.py
tests/test_posttest.py

Summary: Fix post test fetch file issue for large dump file
Fixes # (issue) 29889214
There is a huge performance impact when using ansible fetch with `become=True`. This is also documented in the ansible module documentation (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fetch_module.html) where they suggested not to use `become=True`. 
However in our case we need to use `become=True` for fetch because we're trying to fetch from `/var/dump`
The same issue was also reported in https://github.com/ansible/ansible/issues/31194. 
The solution is to create a fetch module without dependent on slurp. Doing this will improve 600 times the speed
Testing with 1.4GB file, in nightly and manual test we're expecting 4 hours to finish downloading this file using normal `fetch` …

Fix posttest fetch slow issue

---

tests/common/reboot.py
tests/platform_tests/test_kdump.py

In case of Cisco chassis, when supervisor goes for kernel panic based reboot, all LCs are rebooted and the reboot cause is due to Heartbeat loss. Changed the testcase to check the right reboot cause
Summary:
In case of Cisco chassis, when supervisor goes for kernel panic based reboot, all LCs are rebooted and the reboot cause is due to Heartbeat loss. Changed the testcase to check the right reboot cause
Validated the testcase on Cisco platform

Fixing reboot-cause for LCs during Kernel Panic testcase

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary: ECMP/LAG hash is not supported by broadcom SAI, so the tests will fail. Skip the tests for broadcom asics.
Broadcom SAI does not support ECMP/LAG hash. Therefore the tests will fail.
Testcases are skipped when `hash/test_generic_hash.py` is run.
Only skip for broadcom asics.

Skip hash/test_generic_hash.py tests for broadcom asics

---

tests/common/dualtor/dual_tor_mock.py

Summary:
Fix the t0 mock dualtor test failure due to orchagent exit during tunnel/decap term creation:
```
2024 Oct 24 02:12:57.407935 str2-7050cx3-acs-02 ERR syncd#syncd: [none] SAI_API_TUNNEL:brcm_sai_tnl_mp_create_tunnel_term_table_entry:5183 Multiple IP Tunnel Terminators with same dst ip are not supported
2024 Oct 24 02:12:57.408057 str2-7050cx3-acs-02 ERR syncd#syncd: :- sendApiResponse: api SAI_COMMON_API_CREATE failed in syncd mode: SAI_STATUS_NOT_SUPPORTED
2024 Oct 24 02:12:57.408169 str2-7050cx3-acs-02 ERR syncd#syncd: :- processQuadEvent: attr: SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_VR_ID: oid:0x3000000000023
2024 Oct 24 02:12:57.408225 str2-7050cx3-acs-02 ERR syncd#syncd: :- processQuadEvent: attr: SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_TYPE: …
```

Fix mock dualtor tunnel decap term creation failure

---

tests/common/helpers/portchannel_to_vlan.py

Summary:
Fix the following error while running test_fdb.py:
```
{
"failed": true,
"changed": true,
"stdout": "",
"stderr": "Usage: config portchannel member add [OPTIONS] <portchannel_name> <port_name>\nTry \"config portchannel member add -h\" for help.\n\nError: Port speed of Ethernet10 is different than the other members of the portchannel PortChannel1",
"rc": 2,
"cmd": "config portchannel member add PortChannel1 Ethernet10",
"start": "2024-10-17 13:46:55.652227",
"end": "2024-10-17 13:46:56.165675",
"delta": "0:00:00.513448",
"msg": "non-zero return code",
"invocation": {
"module_args": {
"_raw_params": "config portchannel member add PortChannel1 Ethernet10",
"_uses_shell": true,
"warn": false,
"stdin_add_newline": true,
"strip_empty_ends": true,
"argv": null,
"chdir": …
```

Add same speed ports into one portchannel in setup_dut_ptf

---

tests/common/helpers/portchannel_to_vlan.py

Summary:
Remove mellanox accidently in PR https://github.com/sonic-net/sonic-mgmt/pull/15163/
Add id back
Remove mellanox accidently in PR https://github.com/sonic-net/sonic-mgmt/pull/15163/
Add id back

Add mellanox back in setup_po2vlan

---

ansible/vars/topo_t0-isolated-d128u128s1.yml
ansible/veos

Summary:
Add topology with t0 role, 128 downlinks, 128 uplinks and 1 service ports to peer t0.
This is the same topo as #15050 but with only 1 service port.
new topology required for t0 isolated
verified it in the topology file.

add t0-isolated-d128u128s1 topo

---

tests/lldp/test_lldp_syncd.py

Summary:
Fix the issue: https://github.com/sonic-net/sonic-mgmt/issues/15089
Using `eth0` to check lldp table validation is not reasonable, use the last line of `show lldp table`, which is `Total entries displayed` as a checker instead and also check the lldp service status after restarting lldp process.
Update `verify_lldp_table` and check the output of `systemctl status lldp`
Run `lldp/test_lldp_syncd.py`

Update the method of checking lldp table and service in test_lldp_syncd

---

tests/lldp/test_lldp_syncd.py

test_lldp_syncd.py does not account for the possibility that `lldp_rem_sys_desc` is empty as it does for other entries it verifies like `lldp_rem_man_addr`.
On t2(min), we also require a larger timeout in the wait_until after reboot.
Summary:
Observed test fails due to empty `lldp_rem_sys_desc` value.  t2 results flaky due to short wait_until after reboot.
Confirmed test passes on our fixed and chassis systems with these changes

test_lldp_syncd.py: increase timeout after reboot and allow `lldp_rem_sys_desc` to be empty value

---

tests/dualtor/test_tunnel_memory_leak.py

… usage in test_tunnel_memory_leak
Summary:
Fix the issue https://github.com/sonic-net/sonic-mgmt/issues/11403#
To address the issue https://github.com/sonic-net/sonic-mgmt/issues/11403#
Check the memory usage of tunnel_packet_handle instead of swss memory instead in test_tunnel_memory_leak
run `dualtor/test_tunnel_memory_leak.py`

Check the memory usage of tunnel_packet_handle instead of swss memory in test_tunnel_memory_leak

---

tests/common/helpers/portchannel_to_vlan.py

test_fdb failed on t0-118, Ethernet0 and Etherent10 has different speed, Etherent0 becomes 100G, not 50G. It will have "Error: Port speed of Ethernet10 is different than the other members of the portchannel PortChannel1" if add those 2 ports into one portchannel.
Update setup_dut_ptf function to pick up same speed ports. Improve setup_dut_lag function to loop dut_ports[ATTR_PORT_BEHIND_LAG] items, no need to create a new list to get its port name. dut_ports[ATTR_PORT_BEHIND_LAG] looks like this:
port_behind_lag': {0: 'Ethernet0', 1: 'Ethernet4'}
run fdb/test_fdb.py.
Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/15163

[202305]Add same speed ports into one portchannel for test_fdb (#15163)

---

tests/conftest.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py

Summary:
Fixes #14639
After the change:
|  module | running time(T0/T1) <br> before fix (mins) | running time(T0/T1) <br> after fix (mins) | 
| --- | --- | --- |
|  test_multidut_pfcwd_basic_with_snappi.py   |  167.13  |   112.48 | 
| test_multidut_pfc_pause_lossy_with_snappi.py | 295.25 |  86.53 | 
| test_multidut_pfc_pause_lossless_with_snappi.py | 140.87  | 65.70 | 
Current snappi multidut test cases took too long to run.
1.  Use `rand_lossless_prio/rand_lossy_prio` instead of `enum_dut_lossless_prio/enum_dut_lossy_prio` in the reboot test cases. This is the same method used in the existing T0/T1 snappi test cases.
2.  Add skip warm reboot  check in `test_multidut_pfcwd_basic_with_snappi.py`
3.  Use `set()` to avoid rebooting same DUT several times.
Verified on physical testbed.

[Snappi] Change multidut reboot cases to use enum with completeness_level

---

tests/common/platform/interface_utils.py
tests/platform_tests/test_intf_fec.py

This pull request waits for the interface to come up before verifying the FEC mode after configuration. The link flaps to apply the FEC configuration, and the time required varies across different platforms and speeds.
Summary:
Verified on the Mellanox 4700 and Cisco 8101 platforms where the issue is reproduced.

Wait for the interface to come up before verifying the FEC mode after configuration

---

tests/qos/test_qos_sai.py

Updating the regex pattern for lldp error in loganalyzer ignore for multi-asic chassis.
Issue related to -https://github.com/sonic-net/sonic-buildimage/issues/13265
PR -https://github.com/sonic-net/sonic-mgmt/pull/12375
PR -https://github.com/sonic-net/sonic-mgmt/pull/11154
Summary:
The lldp error encountered during test run not getting captured for loganalyzer ignore
Enhanced the regex pattern to consider the lldp  multi-asic instance  
Executed the test run

[Qos]Updating lldp error regex for loganalyzer ignore

---

tests/qos/qos_sai_base.py

Summary:
The PR is to backport https://github.com/sonic-net/sonic-mgmt/pull/13048 to 202405 branch.
Below `KeyError` issue will be fixed.
```
KeyError(0)
File "/var/src/sonic-mgmt_vms7-t1-4700-5_663c03f52c964d8bf34904c3/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
res = next(it)
File "/var/src/sonic-mgmt_vms7-t1-4700-5_663c03f52c964d8bf34904c3/tests/qos/qos_sai_base.py", line 1222, in dutConfig
testPorts = self.__buildTestPorts(request, testPortIds, testPortIps, src_port_ids, dst_port_ids,
File "/var/src/sonic-mgmt_vms7-t1-4700-5_663c03f52c964d8bf34904c3/tests/qos/qos_sai_base.py", line 745, in __buildTestPorts
src_dut_port_ids = testPortIds[get_src_dst_asic_and_duts['src_dut_index']]
KeyError: 0
ERROR …
```

[202405] Support t1-32-lag topology in qos sai test

---

tests/telemetry/conftest.py
tests/telemetry/events/bgp_events.py
tests/telemetry/events/dhcp-relay_events.py
tests/telemetry/events/event_utils.py
tests/telemetry/events/eventd_events.py
tests/telemetry/events/host_events.py
tests/telemetry/events/run_events_test.py
tests/telemetry/events/swss_events.py
tests/telemetry/test_events.py

Cherry-pick #13504 
telemetry/test_events.py::test_events[vlab-01-False] PASSED              [ 33%]
telemetry/test_events.py::test_events_cache[vlab-01-False] PASSED        [ 66%]
telemetry/test_events.py::test_events_cache_overflow[vlab-01-False] PASSED [100%]
Test Results:
22/10/2024 00:44:06 run_events_test.run_test                 L0027 INFO   | events received:
```
([
{
"sonic-events-dhcp-relay:dhcp-relay-discard": {
"ifname": "eth4",
"timestamp": "2024-10-22T00:43:56.334060Z"
}
}
])
```
22/10/2024 00:47:47 run_events_test.run_test                 L0027 INFO   | events received:
```
([
{
"sonic-events-dhcp-relay:dhcp-relay-disparity": {
"duration": "198",
"timestamp": "2024-10-22T00:47:12.924422Z",
"vlan": "Agg-Vlan1000"
}
}
])
```
22/10/2024 00:48:26 run_events_test.run_test …

Add dhcp-relay structured events tests (#13504)

---

ansible/templates/minigraph_link_meta.j2

… (#15134)
cherry-pick #15134 
This pull request updates the Jinja2 template minigraph_link_meta.j2 by modifying the generation of the section.
Key Changes:
* The condition has been changed from simply checking if msft_an_enabled is defined to also checking if vm_topo_config.get('autoneg_interfaces') is not None.
* This ensures that the section is only included if both msft_an_enabled is defined and the autoneg_interfaces attribute in vm_topo_config exists and is not None.
This ensures if some testbeds/devices have msft_an_enabled they do not end up treated as autoneg devices unless the topo file contains the AN interface list
Summary:

[ansible][minigraph] Fix minigraph template for devices which have autoneg enabled but the topo file does not contain autoneg interfaces

---

ansible/TestbedProcessing.py
ansible/library/conn_graph_facts.py
ansible/library/topo_facts.py
ansible/roles/fanout/templates/arista_7060_deploy.j2
ansible/roles/fanout/templates/arista_7260cx3_deploy.j2
ansible/templates/minigraph_link_meta.j2
ansible/templates/minigraph_meta.j2
ansible/vars/topo_t0-116.yml
ansible/vars/topo_t0.yml

…
cherry-pick #13990 
cherry-pick #15134 
cherry-pick #15004 
These changes add a support for adding auto negotiation to specific testbed based on variables defined in ansible
Two things are required for autoneg support
1. autoneg_enabled : True must be enabled in inventory files
2. t0 topo file must have a port list for autoneg Example:
intfs : [1, 2, 3, 4, 5, 6, 7, 8]
With these changes the PR includes changes to pick the port numbering from topo file and apply minigraph parsing changes such that during deploy-mg or gen-mg the required ports have autoneg and deployment is clean with link up
Summary:

[ansible][minigraph] add support for adding autonegotiation in minigraph templates and fanout EOS (#13990)

---

ansible/TestbedProcessing.py
ansible/library/conn_graph_facts.py
ansible/library/topo_facts.py
ansible/roles/fanout/templates/arista_7060_deploy.j2
ansible/roles/fanout/templates/arista_7260cx3_deploy.j2
ansible/templates/minigraph_link_meta.j2
ansible/templates/minigraph_meta.j2
ansible/vars/topo_t0-116.yml
ansible/vars/topo_t0.yml

cherry-pick #13990 
cherry-pick #15134 
cherry-pick #15004 
These changes add a support for adding auto negotiation to specific testbed based on variables defined in ansible
Two things are required for autoneg support
1. autoneg_enabled : True must be enabled in inventory files
2. t0 topo file must have a port list for autoneg Example:
intfs : [1, 2, 3, 4, 5, 6, 7, 8]
With these changes the PR includes changes to pick the port numbering from topo file and apply minigraph parsing changes such that during deploy-mg or gen-mg the required ports have autoneg and deployment is clean with link up
Summary:

[ansible][minigraph] add support for adding autonegotiation in minigrph templates and fanout EOS (#13990)

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Updating skip condition for test_buffer_model_test.py in conditional mark as this was overriding the base test skip condition for  nokia platform 'x86_64-nokia_ixr7250e_36x400g-r0'
Summary:
Test suite was executing skipped test.
Updated the conditional mark skip condition
Executed the test and verify the results

[QoS]Test_buffer_model test skip for Nokia platform

---

tests/dhcp_relay/test_dhcp_relay.py

Summary:
Add test to verify DHCP packets are dropped by standby tor https://github.com/sonic-net/sonic-mgmt/issues/5627
Verify packet drop count by cacl
Run test on dualtor / t0 topos, all passed

[dhcp_relay][dualtor] Add test case for DHCP drop on standby tor

---

ansible/roles/test/files/ptftests/py3/dhcp_relay_stress_test.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/dhcp_relay/test_dhcp_relay_stress.py

Summary:
The purpose of this test is to conduct a DHCP stress test with CoPP policy, ensuring that the DHCP relay service can withstand the maximum load applied to the CPU
In the test, we will generate packets at a rate of 10,000 packets per second for 120 seconds to ensure the DHCP relay service can handle the maximum load without failure.
By monitoring the status of the DHCP container, resource utilization, and verify that the DHCP processes are running.

dhcp storm stress test

---

tests/snappi_tests/test_multidut_snappi.py

Summary:
Minor fixes to test_multidut_snappi.py to make it pass in cisco-8000.
There are minor issues in test_multidut_snappi.py that had caused it to fail in cisco-8000. This PR aims to fix these issues.
```
=========================================================================================================================== PASSES ===========================================================================================================================
______________________________________________________________________________________________________________ test_snappi[multidut_port_info0] 
______________________________________________________________________________________________________________
----------------------------------------------------------------------------- …
```

Fixing test_multidut_snappi.

---

tests/qos/test_qos_sai.py

Summary:
The skip for non-single-asic variant for the test:qos/test_qos_sai.py::ttestQosSaiPgSharedWatermark[wm_pg_shared_lossy] was added by https://github.com/sonic-net/sonic-mgmt/pull/14892 in the wrong location. We need to move this skip before it checks for the wm_pg_shared_lossy key.
The keyerror addressed in the PR:https://github.com/sonic-net/sonic-mgmt/pull/14892 is still occuring, since the skip was added after the Key checking code. This PR moves it up above the Keychecking code.
Moved the skip block above.
Ran it on my TB:

Move the lossy skip condition above the code checking for the lossy key.

---

tests/snmp/test_snmp_psu.py

Summary: `test_snmp_numpsu` TC fails because of change in `stdout` output, observed in `202405` & `202311`.
`stdout_lines` will be use to fetch the `numpsus` value, if the `stdout_lines` is empty / the value can't be typecasted; then in all scenarios TC wouldn't break, instead it will Error out gracefully. Sample `stdout_lines` considered -
```
1. ["PSU0: Topology teardown completed successfully upon PSU removal", "2"]
2. ["2"]
3. []
```
Observed `test_snmp_psu` failing in `202405` & `202311` images due to change in the `stdout` structure.
Earlier `stdout` output was simply getting typecasted, instead now it will use `stdout_lines` & check its length, if it has a non-zero length, then it will pick the last element & try typecasting it; `numpsus` count if exists, will …

fix for test_snmp_numpsu failure

---

tests/platform_tests/cli/test_show_platform.py

Summary:
This is a sonic-mgmt test for [sonic-buildimage issue 9407](https://github.com/sonic-net/sonic-buildimage/issues/9407), which has a fix PR raised here: https://github.com/sonic-net/sonic-utilities/pull/3399 -- the change in this PR tests that fix.
`show platform ssdhealth` fails on certain platforms such as Arista 7050qx because the sonic utility that the command calls relies on `smartctl` output, which fails on storage device of type EUSB. This PR skips the test on unsupported disk types.
Added a new field `Disk Type` to the `ssdutil` sonic-utility that the `show platform ssdhealth` calls. The test checks for a supported disk type and skips if not found.
Tested on 4 HWSKUs each with storage disk type EUSB (skip), EMMC (skip), SATA (pass) and NVME (pass). Logs are attached here: …

Modified ssdhealth test to account for currently supported disk types

---

tests/pfcwd/test_pfc_config.py
tests/pfcwd/test_pfcwd_all_port_storm.py
tests/pfcwd/test_pfcwd_timer_accuracy.py

Summary:
Fixes # (issue) 29826096, 29826079, 29808432
Currently, for PFCWD, we are setting the config_db a certain way for our test case. However, after the tear down, we do not recover the ConfigDB setting to the original which leads to config_db_check issue
This PR attempt to fix 
- test_pfcwd_all_port_storm
- test_pfcwd_timer_accuracy
- pfcwd/test_pfc_config
Since they're similar
I've verified on T2 chassis switch

Fix various pfcwd config_db check failure

---

tests/cacl/test_cacl_function.py
tests/common/helpers/snmp_helpers.py
tests/mvrf/test_mgmtvrf.py
tests/snmp/test_snmp_cpu.py
tests/snmp/test_snmp_default_route.py
tests/snmp/test_snmp_fdb.py
tests/snmp/test_snmp_interfaces.py
tests/snmp/test_snmp_link_local.py
tests/snmp/test_snmp_lldp.py
tests/snmp/test_snmp_loopback.py
tests/snmp/test_snmp_memory.py
tests/snmp/test_snmp_pfc_counters.py
tests/snmp/test_snmp_phy_entity.py
tests/snmp/test_snmp_psu.py
tests/snmp/test_snmp_queue.py
tests/snmp/test_snmp_v2mib.py

Summary: The PR contains changes to `snmp_helpers.py` which checks whether `snmp-subagent` process is up or not before proceeding in the test. Accordingly all the `snmp` tests were updated to accommodate the change. This fixes the SNMP tests failures due to information not gathered in `get_snmp_facts`.
It has been observed that without `snmp-subagent` being up, SNMP tests proceeds to execution causing TC failures because  `snmp_facts` isn't able to capture the device information.
Check was added in `snmp_helpers` ensuring that `snmp-subagent` is up before calling `snmp_facts`. All TCs were updated with the change.
Had run the changes on `202405` image installed in `T0` device & tests passed.

Fixes for SNMP Tests Flakiness

---

tests/snmp/conftest.py

Summary: The PR contains changes to `snmp/conftest.py` with logic to configure `snmp` credentials stored in `snmp.yml` for every host before running any test script. 
If credentials in `snmp.yml` isn't configured, then the changes in PR configures them before running the tests and restores the original configuration after the TC execution.
- `snmp/conftest.py` will now copy the `snmp.yml` from DUT to UCS (if DUT has `snmp.yml`) & then it will configure the SNMP credentials for every host via `sudo config snmp` command. The logic it configures is same as in `snmp_yml_to_configdb.py` script; where it checks whether the credentials in yml are configured in `config_db` or not, if the keys are configured but the values are different / the keys are not configured - then it will …

Configuring Community SNMP Credentials for SNMP TCs

---

tests/qos/qos_sai_base.py

Summary:
LosslessVoq testcase was failing on smartswitch platform due to source ports having different qos profiles.
Added smartswitch hwsku to the check in qos_sai_base to select src/dst ports similarly to Cisco-8101-O8C48.
Ran test_qos_sai.py with smartswitch DUT in T1 testbed, LosslessVoq test case passing after this fix.

Add Cisco Smartswitch hswku to select src/dst ports in qos_sai_base.py

---

tests/bgp/bgp_helpers.py
tests/bgp/route_checker.py
tests/bgp/test_reliable_tsa.py
tests/bgp/test_startup_tsa_tsb_service.py
tests/bgp/test_traffic_shift.py
tests/bgp/test_traffic_shift_sup.py

Summary:
- This PR has tests to verify the changes introduced as part of #https://github.com/sonic-net/sonic-buildimage/pull/19217. The original code PR for the feature is #https://github.com/sonic-net/sonic-buildimage/pull/18928
- HLD link for the feature: https://github.com/skeesara-nokia/SONiC/blob/master/doc/voq/Reliable_TSA.md
- Basically, this PR has 20 test cases to verify the feature functionality and also few modifications on the tests introduced as part of PR #12781 
- To verify the feature functionality and the code changes introduced as part of the PR #https://github.com/sonic-net/sonic-buildimage/pull/18928
-  Added 20 new test cases to verify feature in three sets. 
- Attaching test cases' description document here for further reference. 
- …

[T2-Chassis] - New tests for Reliable-TSA feature

---

tests/common/devices/multi_asic.py

Enhance the logic to cover the mock dualtor test on topology ptf32 
There is no mux docker running but its metadata subtype is DualToR
Double check if the mux docker should running, then add mux docker into the critical process check list
Summary:
QoS test case testQosSaiPfcXoffLimit[single_dut_multi_asic-xoff_1] would failed due to failure:
Failed: All critical services should be fully started!
Double check if the mux docker should running, then add mux docker into the critical process check list

Update the logic of adding mux to the critical process list

---

tests/platform_tests/verify_dut_health.py

Enhance function verify_no_coredumps to print core dumps
Check and print the core dump list during test
Summary:
When the case failure due to unexpected core dumps, no output of core dump details
Add check and print function to show the dump files
No

Enhance function verify_no_coredumps to print core dumps

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

test_bfd_echo_mode failed due to the test issue: https://github.com/sonic-net/sonic-mgmt/issues/14087
Summary: The test_bfd_echo_mode  is a new test adde by https://github.com/sonic-net/sonic-mgmt/pull/12642/, and the test case could not pass

Skip the bfd test case by the github issue

---

tests/generic_config_updater/test_cacl.py

After rollback_or_reload the config,  the case check if the current iptable rules equal to the original iptale rules directly. Sometimes, the iptable rules are not ready completely, so case will fail due to missing some iptable rules. Therefore, update the code to use retry mechanism to check if the current iptable rules are equal to the original ones.
Summary:
Stabilize test_cacl cases
Update the code to use retry mechanism to check if the current iptable rules are equal to the original ones.
Run test_cacl  20 times
Any

Stabilize test_cacl cases

---

tests/qos/files/mellanox/special_qos_config.yml
tests/qos/qos_sai_base.py
tests/saitests/py3/sai_qos_tests.py

1. update qos sai test for sn5400 refering to the two PRs below 
- https://github.com/sonic-net/sonic-mgmt/pull/9583
- https://github.com/sonic-net/sonic-mgmt/pull/12848
2. To stabilize testQosSaiQSharedWatermark[single_asic-wm_q_shared_lossy], update margin from 4 to 5 for spc4
Summary:
Update qos sai test for spc4 platform
1. update qos sai test for sn5400
2. To stabilize testQosSaiQSharedWatermark[single_asic-wm_q_shared_lossy], update margin from 4 to 5 for spc4
Run qos tests on spc4 platform
spc4

[Mellanox] Update qos sai tests for spc4 platform

---

tests/generic_config_updater/test_cacl.py

Summary: This test is to check the GCU function when ACL_TABLE and ACL_RULE in one patch
There are PRDO scenarios that GCU will be used for ACL_TABLE&ACL_RULE modification in one patch. We add this test to gain confident.
Add a test
Test on DUT

[GCU] Add GCU testcase for acl table&rule in one patch

---

ansible/roles/vm_set/files/mux_simulator.py

Summary:
Active-standby Dualtor is failing to talk to `mux_simulator`:
```
*   Trying 10.64.246.154:8082...
```
* on the test server, TCP syn drops are reported increasing:
```
1531500 times the listen queue of a socket overflowed
1531501 SYNs to LISTEN sockets dropped
```
* mux simulator sync queue is overflowing:
```
State                     Recv-Q                     Send-Q                                          Local Address:Port                                         Peer Address:Port
LISTEN                    129                          128                                                   0.0.0.0:8082                                              0.0.0.0:*
```
* It appeared that `mux_simulator` is stuck in the `recvfrom`:
```
strace: Process 21315 attached …
```

[dualtor][mux_simulator] Fix mux simulator stuck

---

ansible/roles/vm_set/tasks/control_mux_simulator.yml
ansible/roles/vm_set/templates/mux-simulator.service.j2

Summary:
As `mux_simulator` script differs between branches, let's copy `mux_simulator` per testbed.
Use the port number as suffix.
Run on dualtor testbeds that share the same host server, ensure `mux_simulator`s run with each owne script file.

Run mux simulator script per testbed

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Remove incorrect quotes around github issue url in tests_mark_conditions.yaml file.
Fixes # https://github.com/aristanetworks/sonic-qual.msft/issues/281
PR#https://github.com/sonic-net/sonic-mgmt/pull/14912 has introduced single quotes around github issue url and this is causing conditional mark evaluation to fail. Thus conditional mark config is not honored and couple of tests are getting scheduled even though they are supposed to be skipped. 
```
07:58:59 __init__.evaluate_condition              L0504 ERROR  | Failed to evaluate condition, raw_condition=hwsku in ['Arista-7260CX3-D108C8', 'Arista-7260CX3-Q64', 'Mellanox-SN3800-D112C8'] and 'https://github.com/sonic-net/sonic-mgmt/issues/11237', condition_str=hwsku in ['Arista-7260CX3-D108C8', 'Arista-7260CX3-Q64', …
```

[sonic-mgmt][conditional_mark] Remove incorrect quotes around github issue url

---

tests/common/plugins/loganalyzer/__init__.py

Summary:
Fixes # (issue) 29752643
Currently log rotate for supervisor takes 1 to 2 minutes with a maximum of 2 minutes on pc/test_lag_2
Since log_rotate is now running on function fixture. With all test case running, this will add up. On recent nightly run, it added up to `2:03:58` hours which slows down the test to 2 hours.
The reason for log rotating is documented in #2161 to save spaces on 7060 devices. This change for T2 device make sure that we only rotate for T2 at `module` level instead of functions.
This will optimise the time from 2 hours to 2 minutes.
Details of the stats can be seen here for pc/test_lag_2
```
{
"analyzer_logrotate_time": {
"total": "2:03:58.135243",
"average": "0:01:01.984460",
"max": "0:02:00.298079",
"min": "0:00:57.740233",
"number of runs": 120
}, …
```

feat: optimise log_rotate for modular chassis

---

tests/platform_tests/test_intf_fec.py

Summary:
String to integer conversion is not removing commas before converting to an integer.
Remove commas from stats, before converting to an integer
Verified on Mellanox-SN4700-O32 platform

Remove commas before converting to an integer

---

ansible/roles/test/tasks/common_tasks/reboot_sonic.yml

Increase the ready timeout from 180 to 540.
This is due to the flow was modified so that counter initialization happens approximately 5 minutes after the boot, which is introduced in PR - 
https://github.com/sonic-net/sonic-sairedis/pull/1362
Summary:
Due to PR https://github.com/sonic-net/sonic-sairedis/pull/1362, the ready timeout in continuous fast reboot test should be increased.
Increase the ready timeout from 180 to 540.

Increase the ready timeout for fast reboot test

---

tests/stress/test_stress_routes.py

Summary: Add memory usage checker in the stress route test

Add memory usage checker for the stress route test

---

tests/lldp/test_lldp.py

test_lldp_neighbor testcase fails since container lldp was removed form the host
admin@ixre-board7:~$ docker exec -i lldp lldpcli show chassis
Error response from daemon: No such container: lldp
for this reason, we will test either lldp0 or lldp1 based on randomly selected Asic.
Summary:
since container lldp was removed from the host, we will test on lldp0 or lldp1 to test the test_lldp_neighbor testcase.
Use enum_rand_one_frontend_asic_index to randomly select an Asic index
Use the Asic index to select either lldp0 or lldp1
Tested on a multi cards multi Asics chassis.

Use lldp0/lldp1 instead of lldp, since container lldp was removed from the host

---

tests/lldp/test_lldp_syncd.py

Various multi-asic fixes in `lldp/test_lldp_syncd.py`
* Fix helper functions `db_instance`, `get_lldp_entry_keys`, `get_lldp_entry_content`, `get_lldpctl_output` to query both namespaces
test_lldp_entry_table_after_flap
* Ignore routeCheck log errors as this test flaps ports and churns routes `ignore_expected_loganalyzer_exceptions`
* Don't skip the test if it finds `eth0` port, just continue
* Add namespace to `config interface` commands
* Increase delay from 5s to 10s as `verify_lldp_entry` was seeing the stale `LLDP_ENTRY` from before link flap and returning True
test_lldp_entry_table_after_lldp_restart
* Query the per-namespace `lldp` docker when available
test_lldp_entry_table_after_reboot
* wait until `check_intf_up_ports=True` when rebooting, otherwise the `LLDP_ENTRY` may flap …

Multi-asic fixes for `lldp/test_lldp_syncd.py`

---

ansible/files/sonic_lab_console_links.csv
ansible/library/conn_graph_facts.py
tests/common/connections/base_console_conn.py
tests/common/connections/console_host.py
tests/common/connections/ssh_console_conn.py
tests/conftest.py

Addresses https://github.com/sonic-net/sonic-mgmt/issues/15092
Summary:
This PR adds handling for the PortInUseException, which is thrown when an SSHConsoleConn is successfully established (most prominently in dut_console tests) but the console port is occupied, resulting in the connection being terminated by the host.
This PR is intended to add more resilience to the dut_console tests, as if a testbed with a blocked port was selected for a nightly test, it would cause the dut_console tests to fail during setup. This provides a method for auto-recovery for these cases.
By completing the following:
* Add connection types for each of the configuration menu types (Digi, Cisco, and Sonic) to allow for different command sequences to be accounted for
* Add function to clear a DUT's console port …

[action] [PR:15174] tests-common: Handle PortInUseException for SSHConsoleConn

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
ECMP/LAG hash is not supported by broadcom SAI, so the tests will fail. Skip the tests for broadcom asics.
Manual backport due to conflict as mentioned here: https://github.com/sonic-net/sonic-mgmt/pull/15091#issuecomment-2437065558
Broadcom SAI does not support ECMP/LAG hash. Therefore the tests will fail.
Testcases are skipped when `hash/test_generic_hash.py` is run.
Only skip for broadcom asics.

[202405] Skip hash/test_generic_hash.py tests for broadcom asics

---

tests/common/cache/facts_cache.py
tests/common/devices/duthosts.py

When parallel run is enabled, multiple processes may try to read/write the same cache file, so there will be a small chance that the file is being written by process 1 while process 2 is reading it, which will cause EOFError in process 2. In this case, we will retry reading the file in process 2. If we still get EOFError after some retry attempts, we will return NOTEXIST to overwrite the file.
In the meantime, we should also optimize how we initialize the DUT hosts when parallel run is enabled to reduce the chance of having such cache read issue. 
Summary:
Fixes # (issue) Microsoft ADO 30031372
To prevent EOFError when reading cache file when parallel run is enabled.
Add retry mechanism and optimize how DUT hosts are initialized when parallel is enabled.
I ran the updated code and can …

fix: handle EOFError for cache reading

---

tests/qos/qos_sai_base.py

Summary:
In qos-sai-base, there is a docker0 ipv6 checking function, which fails if the DUT has no ipv6 address. The failure signature is as below:
```
14:50:01 __init__._fixture_generator_decorator    L0088 ERROR  | 
IndexError('list index out of range')
File "/data/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
res = next(it)
File "/data/tests/qos/qos_sai_base.py", line 1824, in dut_disable_ipv6
duthost.shell("sudo ip -6  addr show dev docker0 | grep global" + " | awk '{print $2}'")[
IndexError: list index out of range
```
The failure of the ipv6 disabling fixture.
Check if the docker0 has ipv6 address or not.
Ran it on my TB:
```
----------------------------------------------------------------------------- …
```

Adding fixes for the docker0 ipv6 issue.

---

tests/common/config_reload.py

Signed-off-by: anamehra anamehra@cisco.com
Fixes config reload -y <running_golden_config> for chassis sup by using num_asics to populate config db file list
Summary:
During some tests, config is restored via config reload using runnin_golden config files.
config reload -y expects all n+1 config files be provided as input but sonic-mgmt script only includes the config files for present asics.
System had 10 asics but max asics could be 16. The command shows only 10+1(global) config db
Before fix:
```2024 Oct 19 09:53:32.038630 sfd-t2-sup INFO python[815457]: ansible-ansible.legacy.command Invoked with executable=/bin/bash _raw_params=config reload -y -f -l /etc/sonic/running_golden_config.json,/ee
tc/sonic/running_golden_config0.json,/etc/sonic/running_golden_config1.json,/et …
```

[chassis]: Add all running_golden_config files for multi-asics based on num_asic

---

tests/common/fixtures/advanced_reboot.py
tests/common/platform/device_utils.py

Summary:
The logs on the system before a warm-reboot were being stored on the device however weren't being transferred to the sonic-mgmt host upon the completion of the reboot. These are useful for diagnosing issues in the event of failures.
Have experienced issues in the reboot tests and were unable to diagnose due to a lack of information in the warm-reboot sequence.
Copied across the logs that were already preserved on the device across reboots.
Tested internally on A->B and multl-hop upgrade scenarios.
N/A
N/A
N/A

Capture before warm-reboot device logs

---

tests/common/helpers/syslog_helpers.py

Summary: Fixing test gap on test_mgmt_ipv6
Fixes # (issue) 28836766
Currently test_mgmt_ipv6 is having the following skipped tests:
SKIPPED [2] ip/test_mgmt_ipv6_only.py:122: DUT has no default route, skiped
SKIPPED [1] ip/test_mgmt_ipv6_only.py:192: Skipping test as no Ethernet0 frontpanel port on supervisor
"DUT has no default route, skiped" was because the ipv6 default gateway becomes stale from not using it. 
- Solution: adding a ping and check if it's still reachable after `ping`
"Skipping test as no Ethernet0 frontpanel port on supervisor" was because the test is meant to be for supervisor:
- Solution: only use the enumerate of frontend nodes. This is to avoid in the future someone else need to investigate why this one is skipped. We should only call the fixture we want to test.

Address test gap in test_mgmt_ipv6

---

tests/pfc_asym/test_pfc_asym.py

There is an error while running test case test_pfc_asym_off_rx_pause_frames, as fixture setup is defined in `tests.common.fixtures.pfc_asym`. In this PR, we import this fixture in this test script to fix this issue. 
```
def test_pfc_asym_off_rx_pause_frames(ptfhost, setup, pfc_storm_runner):
fixture 'setup' not found
```
Summary:
There is an error while running test case test_pfc_asym_off_rx_pause_frames, as fixture setup is defined in `tests.common.fixtures.pfc_asym`. In this PR, we import this fixture in this test script to fix this issue. 
```
def test_pfc_asym_off_rx_pause_frames(ptfhost, setup, pfc_storm_runner):
fixture 'setup' not found
```
In this PR, we import this fixture in this test script to fix this issue.

[Bugfix] Fix fixture not found issue in script `pfc_asym/test_pfc_asym.py`.

---

docs/testplan/BGP-Suppress-FIB-Pending-test-plan-T2-Chassis.md

**T2 Chassis - BGP FIB Suppress Pending Test Plan**
Summary:
This T2 Chassis test plan for BGP FIB suppress pending feature is an extension of the BGP Suppress FIB Pending Test Plan added for T1 DUT at [plan](https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/BGP-Suppress-FIB-Pending-test-plan.md)
The test plan is created to verify the BGP suppress FIB pending feature functionality on a T2 Chassis line card that allows BGP not to advertise routes that haven't been installed into ASIC yet.
Consistent to the existing T1 FIB suppress pending test cases, adapt the tests to verify the functionality on a T2 chassis.

T2 Chassis - BGP FIB Suppress Pending Testplan

---

tests/common/fixtures/advanced_reboot.py
tests/platform_tests/conftest.py

Summary:
Note this is a backport, please see the original for details: https://github.com/sonic-net/sonic-mgmt/pull/14980

Capture logs before reboot (cherry-pick 202311)

---

tests/arp/test_arp_update.py
tests/common/fixtures/ptfhost_utils.py

Summary:
Fixes #14525 
It is possible for kernel neighbor information to fall out of sync with the APPL_DB neighbor table.
Manually change the APPL_DB neighbor table entry, then verify that the `arp_update` script is able to flush the out of sync neighbor.

[arp_update] Verify that kernel/APPL_DB MAC mismatch is corrected

---

ansible/vars/topo_t1-isolated-d224u8.yaml
ansible/veos
docs/testbed/README.testbed.Overview.md

Summary:
Add a new T1 topology with 224 VMs simulating downstream T0 neighbors and 8 VMs simulating upstream T2 neighbors. 
Create a new topo named t1-isolated-d224u8.
t1-isolated-d224u8

Add topo t1-isolated-d224u8

---

.azure-pipelines/run-test-elastictest-template.yml
.azure-pipelines/test_plan.py

Enhance elastictest template, use bash script instead of azcli task, improve and fix azlogin and get token when requesting APIs.
Raised Draft PR and pieplines to test.
https://github.com/sonic-net/sonic-mgmt/pull/15203
https://dev.azure.com/mssonic/build/_build/results?buildId=680964&view=logs&j=f1a75c01-4f64-5de9-bd52-755062a8a04a&t=8ee9ec2e-146f-5d1e-ed12-570cadc91ea0
In another project "sandbox" also veried.
https://dev.azure.com/mssonic/sandbox/_build/results?buildId=680966&view=logs&j=f1a75c01-4f64-5de9-bd52-755062a8a04a&t=8ee9ec2e-146f-5d1e-ed12-570cadc91ea0
Enhance elastictest template, use bash script instead of azcli task, improve and fix azlogin and get token when requesting APIs.
1. Enhance elastictest template, use bash script instead of azcli task.
2. Improve and fix azlogin …

[CI] Enhance elastictest template, use bash script instead of azcli task

---

ansible/roles/vm_set/library/vm_topology.py

Summary:
If the test server is Ubuntu 22.04, SoC IP ARP flux is observed on the
DUTs for dualtor-aa testbed.
* `arping` the soc IP `192.168.0.3` on the DUT
```
ARPING 192.168.0.3
60 bytes from 8a:0e:6b:72:5f:9e (192.168.0.3): index=0 time=3.771 msec
60 bytes from 5a:ef:b2:32:64:e4 (192.168.0.3): index=1 time=4.001 msec
60 bytes from ba:88:12:db:99:d7 (192.168.0.3): index=2 time=4.012 msec
60 bytes from b6:8c:cc:28:78:ff (192.168.0.3): index=3 time=4.020 msec
60 bytes from 4e:68:db:25:b0:b9 (192.168.0.3): index=4 time=4.027 msec
60 bytes from ba:38:ee:59:d7:72 (192.168.0.3): index=5 time=4.034 msec
60 bytes from 22:f7:ce:56:48:f1 (192.168.0.3): index=6 time=4.040 msec
60 bytes from 8a:0f:a2:16:a6:58 (192.168.0.3): index=7 time=4.047 msec
60 bytes from 76:f7:26:c7:53:d1 …
```

[dualtor-aa] Fix arp flux of soc IPs

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Cisco 8122 compute AI deployment has special BGP template which does NOT have BGP allow list and BGP BBR support.
Cisco 8122 compute AI deployment has special BGP template which does NOT have BGP allow list and BGP BBR support.
Ignore the test cases.
N/A

Ignore test_bgp_allow_list and test_bgp_bbr for Cisco 8122 compute AI deployment

---

tests/platform_tests/api/watchdog.yml

Adding Cisco 8122 platforms to platform_tests/api/watchdog.yml file. This is needed for testcase platform_tests/api/test_watchdog.py
Added the details for 8122 platforms to watchdog.yml file
**Type of change** 
-Test modification
**Back port request** 
-202405
Made sure that testcase platform_tests/api/test_watchdog.py passes on 8122 platforms after adding them to watchdog.yml file

adding 8122 platforms to watchdog.yml file

---

tests/common/snappi_tests/read_pcap.py
tests/snappi_tests/pfc/files/cisco_pfc_packet.py
tests/snappi_tests/pfc/files/helper.py

Summary:
test_valid_pfc_frame_with_snappi.py fails in Cisco DUT.
The issue was due to PFC capture sampling not detecting an XOFF frame in the capture.
- As Cisco DUT generates XON frames, this causes the PFC capture sampling to not detect a XOFF frame in the capture.
Added a new pcap read logic using a custom Cisco specific function to verify a valid PFC frame in the capture.
- Further, the buffer size for capture could be small or big depending on the IXIA model's capability
Hence using continuous XOFF injection to avoid overwriting the buffer with XON frames post a XON-XOFF-XON transition
Verified on Cisco DUT
```
---------------------------------------------------------------------------------------------------- …
```

Fixed the failure of test_valid_pfc_frame_with_snappi.py in Cisco DUT 

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/qos/test_qos_sai.py
tests/saitests/py3/sai_qos_tests.py

Summary:
Changes:
- Cisco-8122 does not need to refill the queue to verify watermark behavior, so ignore the extra refill logic for 'gr2' asic. 
Fixes:
- Missing a skip marking for 8122 on testQosSaiLossyQueueVoqMultiSrc test. 
- Add a missing "-margin" to the lower check at the end of the queue watermark test. 
Verified q shared watermark test case on:
- Cisco-8122 T0
- Cisco-8101 T0

Cisco-8122 Q watermark test update

---

tests/common/errors.py

Summary:
Revises ansible error output to be custom formatted such that it prints in the following order:
1. Random fields that don't involve readable text printing, such as the command used or how long the test ran.
2. stdout_lines formatted with proper newlines. 
3. stderr_lines also formatted. 
The output is sorted with the most interesting failure information at the bottom, namely the stderr. 
Inserted an artificial error on a Cisco-8000 series device, observed below output (trimmed out the tail of the cmd and invocation  fields):
```
E           tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
E           end = 2024-10-28 15:03:26.079813
E           cmd = /root/env-python3/bin/ptf --test-dir …
```

Ansible error formatting

---

tests/common/dualtor/tunnel_traffic_utils.py
tests/common/plugins/ptfadapter/dummy_testutils.py
tests/conftest.py

Summary:
Currently we are using marker "skip_traffic_test" to decide whether to run traffic test or not. Then the marker would pass to a fixture called by each data plane testcase.
This approach is only applied in master branch, which cause a lot of code change in test scripts, and difficult to do cherry pick.
Based on the marker "skip_traffic_test", use a testcase level pytest hook to get the marker, if it exists, then setattr to a function always return for all testutils function startwith "send" or "verify", and setattr back when test finished.
Verified in KVM test

Add dummy ptf.testutils library to skip traffic test in KVM

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Fixes conflicted skipping condition for `test_pfc_asym`.
Before this change, there are two skipping conditions.
```
#######################################
#######################################
pfc_asym/test_pfc_asym.py:
skip:
reason: 'pfc_asym test skip except for on Barefoot platforms'
conditions:
- "asic_type not in ['barefoot']"
pfc_asym/test_pfc_asym.py::test_pfc_asym_off_rx_pause_frames:
skip:
reason: "skipped for Barefoot platform"
conditions:
- "asic_type in ['barefoot']"
```
This PR reomoved the second one as it has been covered by the first one.
This PR is to fix conflicted skipping condition for `test_pfc_asym`.
Remove the unused condition.
Verified by syntax check.
No.

Fix conflicted skipping condition for test_pfc_asym

---

tests/ipfwd/test_nhop_group.py

Add the static route ASIC DB validation in cases of weak switch
Summary:
For some weak CPU switch, such as Mellanox SN2700 with A0 chip type. The fixed 15 seconds is not enough to handle a bunch of BGP route add/delete and static route add/delete. So the case would failed from time to time.
Add a ASIC DB check for the static route validation.

Add static route ASIC DB check for test_nhop_group test

---

.azure-pipelines/pr_test_skip_scripts.yaml

Summary:
Meanwhile, we are using .azure-pipelines/testscripts_analyse/ to static test scripts have been added or not, if a test script need to skip in KVM test, need to add it to .azure-pipelines/pr_test_skip_scripts.yaml and we would mark it as checked/covered.
Based on that, snappi test could not run on KVM platform, so need to add these tests to .azure-pipelines/pr_test_skip_scripts.yaml
Add snappi test scripts to .azure-pipelines/pr_test_skip_scripts.yaml

Add snappi tests to PR test skip yml

---

tests/lldp/test_lldp_syncd.py

Summary:
Fix failure of "`Failed: LLDP_ENTRY_TABLE keys do not match` 'show lldp table' output" in `lldp.test_lldp_syncd.test_lldp_entry_table_after_reboot`
In `lldp.test_lldp_syncd.test_lldp_entry_table_after_reboot`, case always failed due to "`Failed: LLDP_ENTRY_TABLE keys do not match` 'show lldp table' output" 
It is caused by the systemcl restart lldp in previous case `lldp.test_lldp_syncd.test_lldp_entry_table_after_lldp_restart`.
Eth0 didn't come up after lldp restart.
Check the content of lldp table after reboot not before reboot.
run lldp/test_lldp_syncd.py

Fix mismatch between show lldp table and the content of lldp entry table

---

.azure-pipelines/test_plan.py
tests/acl/conftest.py
tests/acl/test_stress_acl.py
tests/arp/conftest.py
tests/arp/test_stress_arp.py
tests/bfd/test_bfd_static_route.py
tests/common/dualtor/dual_tor_utils.py
tests/conftest.py
tests/ecmp/inner_hashing/test_inner_hashing.py
tests/ecmp/inner_hashing/test_inner_hashing_lag.py
tests/ecmp/inner_hashing/test_wr_inner_hashing.py
tests/ecmp/inner_hashing/test_wr_inner_hashing_lag.py
tests/fdb/conftest.py
tests/fdb/test_fdb_mac_move.py
tests/route/conftest.py
tests/route/test_route_flap.py
tests/stress/conftest.py
tests/stress/test_stress_routes.py

Summary:
The completeness_level is used as the test level for stress tests, with "confident" indicating a high number of stress test iterations. In Elastictest, the completeness_level has been set to "confident," which results in longer test times.
Always run stress tests at the "confident" level is unnecessary. Moving forward, we can configure the test plan to run high level stress tests weekly at a scheduled time.
1. Remove --completeness_level=confident in Elastictest, allowing stress tests to run at their default iteration count.
2. Set default --completeness_level=debug in testcases
3. Fix typo conpleteness to completeness

[manual] [PR:14375] Set default --completeness_level to debug

---

tests/snmp/conftest.py

Summary: The PR contains changes to `snmp/conftest.py` with logic to configure `snmp` credentials stored in `snmp.yml` for every host before running any test script. 
If credentials in `snmp.yml` isn't configured, then the changes in PR configures them before running the tests and restores the original configuration after the TC execution.
- `snmp/conftest.py` will now copy the `snmp.yml` from DUT to UCS (if DUT has `snmp.yml`) & then it will configure the SNMP credentials for every host via `sudo config snmp` command. The logic it configures is same as in `snmp_yml_to_configdb.py` script; where it checks whether the credentials in yml are configured in `config_db` or not, if the keys are configured but the values are different / the keys are not configured - then it will …

[PR:14926] Configuring Community SNMP Credentials for SNMP TCs

---

tests/common/snappi_tests/traffic_generation.py
tests/snappi_tests/pfc/files/helper.py

Skip check for Rx PFC counter if multiple lossy TC bits are set. This is a cisco-8000 specific check. 
Rx counter is incremented only if a single lossy TC bit is set.
Ran snappi tests for lossy/lossless to confirm:
```
=============================================== short test summary info ================================================
PASSED snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py::test_pfc_pause_single_lossy_prio[aaa14-ixia-m64|0]
PASSED snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py::test_pfc_pause_single_lossy_prio[aaa14-ixia-m64|1]
PASSED snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py::test_pfc_pause_single_lossy_prio[aaa14-ixia-m64|2]
PASSED snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py::test_pfc_pause_single_lossy_prio[aaa14-ixia-m64|5]
PASSED …
```

Skip check for Rx PFC count if multiple lossy TC bits are set

---

tests/bgp/test_seq_idf_isolation.py

Test currently doesn't check if the bgp sessions are all up before proceeding with the tests. Adding a check to make sure they are and then proceed with the tests. With this change we are seeing all the tests pass for chassis
Summary:
Test currently doesn't check if the bgp sessions are all up before proceeding with the tests. Adding a check to make sure they are and then proceed with the tests. With this change we are seeing all the tests pass for chassis
Validated on Cisco chassis
platform linux -- Python 3.8.10, pytest-7.4.0, pluggy-1.5.0
ansible: 2.13.13
rootdir: /data/tests
configfile: pytest.ini
plugins: metadata-3.1.1, forked-1.6.0, html-4.1.1, repeat-0.9.3, xdist-1.28.0, allure-pytest-2.8.22, …

Add check to see if bgp sessions are up before proceeding with the tests

---

tests/common/config_reload.py

Summary:
pfcwd is not enabled in m0/mx, hence skip check it when config reload
Skip check pfcwd when config reload on m0/mx
Run tests

[m0][mx] Skip check pfcwd during config reload for m0/mx

---

tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml

Summary:
drop_packtes tests were skipped for MGFX by folder previously. Now it is broken by this change https://github.com/sonic-net/sonic-mgmt/pull/14395
Hence update condition mark
Update condition mark
Run tests

[drop_packets] Skip drop_packets on MGFX

---

docs/testplan/WoL-test-plan.md

Summary:
We extended wol tool to support sending magic pattern in udp paylod, and we need to add related tests into test plan.
Related PRs: https://github.com/sonic-net/SONiC/pull/1827, https://github.com/sonic-net/sonic-buildimage/pull/20523
We extended wol tool to support sending magic pattern in udp paylod, and we need to add related tests into test plan.
Add udp related tests and give some demo commands.

[wol_test] Add udp related tests into wol test plan

---

tests/pfcwd/conftest.py

Summary:
`test_pfcwd_wb` is flaky on Mellanox platform because PFCWD is not triggered as expected. The error is as below.
```
tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzerError: match: 0
expected_match: 0
expected_missing_match: 1
Expected Messages that are missing:
.* detected PFC storm .*
```
The failure is because the `pfc_gen.py` script running on leaf-fanout can't generate continuous PFC pause to trigger PFCWD on DUT. 
For each lossless queue, a separated `pfc_gen.py` will be running on leaf-fanout. If `two_queues` is true, then there will be two processes running for each port in test. Due to job schedule, it's not guaranteed that all processes can generate continuous PFC pause to trigger PFCWD.
To workaround the issue, the PR set `two_queues` to `False` for Mellanox …

Stabilize pfcwd warm-reboot test on Mellanox platform

---

tests/qos/files/qos_params.spc3.yaml

Update qos pcbb parameter for SN4600C on dualtor aa topology
Summary:
Running qos.test_tunnel_qos_remap#test_xoff_for_pcbb test on dualtor aa topology
Update the parameter file
SN4600C

Update qos pcbb parameter for SN4600C on dualtor aa topology

---

tests/saitests/py3/sai_qos_tests.py

The issue is introduced by the PR:https://github.com/sonic-net/sonic-mgmt/pull/9859. This PR should be dedicated for broadcom-dnx, it should not change the logic for the remaining platform, so restore the original logic for non-broadcom-dnx.
Summary:
Fix testQosSaiDscpToPgMapping introduced by PR:https://github.com/sonic-net/sonic-mgmt/pull/9859
For non-broadcom device, keep the original logic
Run testQosSaiDscpToPgMapping 
Any

Fix testQosSaiDscpToPgMapping issue

---

tests/generic_config_updater/test_cacl.py

After rollback_or_reload the config,  the case check if the current iptable rules equal to the original iptale rules directly. Sometimes, the iptable rules are not ready completely, so case will fail due to missing some iptable rules. Therefore, update the code to use retry mechanism to check if the current iptable rules are equal to the original ones.
Summary:
Stabilize test_cacl cases
Update the code to use retry mechanism to check if the current iptable rules are equal to the original ones.
Run test_cacl  20 times
Any

[202405] Stabilize test_cacl cases

---

azure-pipelines.yml

Summary:
Fixes the timeout issue on pytest collect only
Fixes the timeout issue on pytest collect only

[CI/CD] prolong pytest collect only time out setting

---

tests/platform_tests/test_link_down.py

Summary:
Fix the wait ssh timeout.
set_max_to_reboot is expected to set max wait time due to different duthost,
But previously it auto uses the fixture duthost, which always return the first dut in duthosts,
For example, if duthosts= [lc1,lc2,rp]
the duthost=lc.
But for test case test_link_down_on_sup_reboot, we should get the configuration for rp.
Hence update the logic, explicitly pass the target duthost to the function.
Fix the failure for chassis on test_link_down
explicitly pass the target duthost to the set_max_to_reboot .
run it locally with physical testbes

Fix the wrong reboot wait/timeout setting on test_link_down

---

tests/lldp/test_lldp.py

Resolve and cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/13172 to 202405 branch
Use lldp0/lldp1 instead of lldp, since container lldp was removed from the host
test_lldp_neighbor testcase fails since container lldp was removed form the host
admin@ixre-board7:~$ docker exec -i lldp lldpcli show chassis
Error response from daemon: No such container: lldp
for this reason, we will test either lldp0 or lldp1 based on randomly selected Asic.
Summary:
since container lldp was removed from the host, we will test on lldp0 or lldp1 to test the test_lldp_neighbor testcase.
Use enum_rand_one_frontend_asic_index to randomly select an Asic index
Use the Asic index to select either lldp0 or lldp1
Tested on a multi cards multi Asics chassis.

Use lldp0/lldp1 instead of lldp, since container lldp was removed from the host (#13172)

---

tests/bgp/test_reliable_tsa.py
tests/bgp/test_startup_tsa_tsb_service.py

We are noticing that the time diff is ranging from 120-145 secs. Hence increasing it to 160secs to be on the safer side. After increasing the time we are seeing all testcases passing with all other changes that was added in PR https://github.com/sonic-net/sonic-mgmt/pull/13290
In our case, since kdump is enabled, during abnormal reboot case, our reboot-cause is Kernel Panic. Made an appropriate change for Cisco chassis
Summary:
Check the functionality with a slight increase in time
Validated on Cisco 8808 chassis with T2 profile
PASSED bgp/test_startup_tsa_tsb_service.py::test_tsa_tsb_service_with_dut_cold_reboot[sfd-lt2-lc0]
PASSED bgp/test_startup_tsa_tsb_service.py::test_tsa_tsb_service_with …

Increase startup_tsa_tsb time based on Cisco's observation. 

---

ansible/library/exabgp.py

Re-configure ExaBGP's http-api (for Py3 only). With Python 3 only environment using ExaBGP 4 with Flask 3.x the `werkzeug` Requests max form memory is capped to 500k (https://werkzeug.palletsprojects.com/en/stable/request_data/#limiting-request-data). This breaks announce routes. This PR increases the limit.
Summary:
Fixes # NA
Backport is not applicable as it is part of new feature for Py3 only `docker-ptf`.
Fix issue.
Increase the Flask `werkzeug` request memory limit.
By running "restart-ptf" on testbeds.
None
Not applicable
Not applicable

Re-configure ExaBGP http-api (for py3 only)

---

tests/acl/custom_acl_table/test_custom_acl_table.py
tests/acl/null_route/test_null_route_helper.py
tests/acl/test_acl.py
tests/acl/test_acl_outer_vlan.py
tests/acl/test_stress_acl.py

Summary:
Currently we are using conditional mark to add marker, then use pytest hook to redirect testutils.verify function to a function always return True to skip traffic test. With this change, the skip_traffic_test fixture is no longer needed in test cases, streamlining the test code and improving clarity.
Remove skip_traffic_test in testcases

Remove skip_traffic_test fixture in acl tests

---

ansible/library/testbed_vm_info.py

In ansible/library/testbed_vm_info.py, there is a format string passed to a method without the actual formatting applied, i.e. the '{}'s are printed out rather than the desired information they're supposed to represent. This change passes the error message to the method with the correct formatting applied.
Summary:
To fix a mistake that was noticed in the printout of an error message.
Pass the format string with the appropriate formatting applied to the applicable method, as opposed to the raw format string.
Tested on 202405 against the t0-isolated-d128u128s2, topology, which at the time of this writing is known to encounter the issue that will result in this error message being printed.
Tested on Arista-7060X6-64PE-C256S2.

sonic-mgmt: fix info in testbed_vm_info.py err msg

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary: Fix skip condition for test_tunneling_between_sub_ports
test_tunneling_between_sub_ports was skipped on certain platforms. It was re-enabled by accident after the new matching rule of conditional marks. 
The change here is already on master, so it is only needed by 202405.
Skip  test_tunneling_between_sub_ports on certain conditions
Check the test is skipped

[202405] Fix skip condition for test_tunneling_between_sub_ports

---

tests/acl/test_acl.py

ACL test fix for 8122, Added Platform check to skip the Byte Accounting.
Summary:
ACL byte counters not supported in Cisco 8122 and test_acl.py tests (32 Testcases) fails due to assertion for byte counters.
Add Fix for failing testcase in test_acl.py.
Added check to skip byte accounting for Cisco 8122 Platform
Verified that all the ACL testcases are passing for Cisco 8122 Platform

ACL testcase fix for Cisco 8122 Platform

---

tests/saitests/py3/sai_qos_tests.py

Summary:
Follow up on TODO item for when the TX XOFF counter behavior changed for Cisco-8000 series devices. 
Needed in 202311 as well, as the TODO code is present there as well. 
Verified on Cisco-8111 device to reproduce the xoff !=0 assertion failure consistently, then revised test appropriately for new TX XOFF counter behavior. 
Cisco-8000 series test only.

Cisco-8000 Revise TX XOFF counter check

---

tests/platform_tests/test_chassis_reboot.py

Summary:
Fix the issue when running dut.command("reboot"), when some T2 platform running the command itself can exceed ansible timeout we defined in ansible.cfg that is 60sec.
In this case, test will error out saying "Host unreachable", but it's actually due to ansible command timeout.
Avoid testcase failure that is command runtime dependent
Thread the reboot command, so even it timeout in a single thread, main thread is fine
Before:
```
03/11/2024 12:04:25 test_chassis_reboot.chassis_cold_reboot  L0027 INFO   | Run cold reboot on <MultiAsicSonicHost 8800-lc4>
03/11/2024 12:04:25 base._run                                L0071 DEBUG  | /var/src/sonic-mgmt_8800-1_66b4a53de4614bccc2e74f8c/tests/common/devices/multi_asic.py::_run_on_asics#135: [8800-lc4] …
```

test_chassis_reboot.py apply threaded reboot to avoid ansible command timeout

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Adding log analyzer ignore messages based on Cisco Chassis. These messages are harmless messages. Adding it to loganalyzer ignore file
WARNING kernel: [55926.179286] pcieport 0000:0a:00.0:   device [10b5:8713] error status/mask=00002001/0000e000
ERR kernel: [39978.088854] cisco-fpga-p2pm-m-slot p2pm-m-slot.2: cisco_fpga_select_new_acpi_companion: searching for child status0 0x2420017a; fpga_id 0x42
ERR kernel: [    8.160032] cisco-fpga-pci 0000:5f:00.0: cisco_fpga_select_new_acpi_companion: searching for child status0 0x26100179; fpga_id 0x61 create a loganalyzer ignore
Summary:
To ignore harmless log messages that can cause testcase errors.
Adding the messages as part of log analyzer ignore file

Adding log analyzer ignore messages based on Cisco Chassis

---

tests/qos/files/qos_params.j2c.yaml

Fixing intermittent failure in lossy queue by adjusting the pkts_num_trig_egr_drp for 'broadcom-dnx' t2 chassis.
Updation on the original PR # https://github.com/sonic-net/sonic-mgmt/pull/14585
Summary:
Since the pkts_num_leakout  is more for 100G.Adjusting the count of pkt sent to trigger egress drop.
Executed the qos test and verify.

[Qos]Updating J2C+ qos yaml for 400G lossy profile

---

tests/platform_tests/api/platform_api_test_base.py
tests/platform_tests/api/test_psu.py

Summary:
If `test_psu.py::TestPsuApi::test_power`  fails on `abs(power - (voltage*current)) < power*0.1` then retry the test.  The test is repeated for a maximum of three times until it passes, else it is failed. This change is introduced to account for the stringent tolerance level of 10% and the errors that might be caused due to time differences in reading each of the parameters (current, voltage and power). 
Addresses issue: https://github.com/aristanetworks/sonic-qual.msft/issues/209 
Improve the test to account for stringent tolerance level and asymmetric reading of parameters for power calculation. 
If the test fails for the condition `abs(power - (voltage*current)) < power*0.1`, the test will collect fresh parameters (voltage, current and power) from the PSU …

Retry test_psu.py::TestPsuApi::test_power if power not within tolerance

---

tests/dut_console/test_console_baud_rate.py

Cast expected console baudrate to str so comparison works properly
Summary:
Fixes #14874
- [ x] Bug fix
- [ x] 202405
Test was failing because the types were wrong if the baudrate was specified in the inventory files as an integer rather than a string. Cast explicitly to fix this behavior

[dut_console/test_console_baud_rate]: cast expected baudrate to str

---

ansible/generate_topo.py
ansible/templates/topo_t1-isolated.j2
ansible/templates/topo_t1.j2
ansible/vars/topo_t1-isolated-d128.yml

Summary:
This PR adds a topology generator python script, which currently supports creating t1 topology with specific downlinks, uplinks and peer links.
The script provides examples in its help:
```text
$ ./generate_topo.py --help
Usage: generate_topo.py [OPTIONS]
Generate a topology file for a device:
Examples (in the ansible directory):
- ./generate_topo.py -r t1 -k isolated -t t1 -c 128
- ./generate_topo.py -r t1 -k uplink -t t1 -c 130 -u 0,1 -p 128,129
```
This PR adds the t1 isolated d128 topology to the testbed for unblocking the t1 tests with all 128 ports.
Added the topo generator and the topology.
N/A

Add topo generator and t1-isolated-d128 topo.

---

tests/qos/files/cisco/qos_param_generator.py

Summary:
Increase buffer pool watermark test margin for Cisco-8122.
Cisco-8000 series uses a base watermark. During capture of the base, it ends up being slightly higher due to background traffic. This makes the overall "new_wmk - base_wmk" slightly low, bumping against the lower bound default 2-packet margin. 
Proposed solution is to increase the margin to 8 packets, but only for 8122 series. The problem is exacerbated on 8122 since it uses small 64B packets rather than the other 8000 series larger packet sizes, making it more sensitive to tiny deviations. 
Verified on Cisco-8122 T1 device, repeated test several times to help ensure it's not flaky. 
Cisco-8122 only.

Cisco-8122 Increase buffer pool watermark test margin

---

tests/common/templates/pfc_storm_sonic_t2.j2
tests/common/templates/pfc_storm_stop_sonic_t2.j2

Summary:
Fixes # (issue) 301125860
pfc_gen_t2 is written and using python3 library format. In some switches the default `python` is not linked to `python3` and still refers to python2.7 which leads to unexpected result.
Explicitly specify to use python3

feat: fix  pfcwd storm flaky test

---

tests/common/snappi_tests/qos_fixtures.py
tests/common/snappi_tests/snappi_fixtures.py
tests/snappi_tests/files/helper.py
tests/snappi_tests/multidut/pfc/files/multidut_helper.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
tests/snappi_tests/test_multidut_snappi.py

Summary:
Snappi reboot testcases don't save the config before rebooting the DUT. This causes the DUT to loose all the config, and the test fails with "ARP is not resolved" errors.
This PR addresses this issue by saving the config before any reboot. Also this PR moves the code that is reused in multiple tests to a common code.

Porting PR:15099 to 202405: Move the common code from testcases to the fixtures.

---

tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py

Summary:
As per PR:15099, change test_multidut_pfcwd_basic_with_snappi.py  and test_multidut_pfc_pause_lossy_with_snappi.py to use the new fixtures.
Fix for: "ARP not resolved issue" in reboot cases in pause_lossy, and pfcwd_basic.
1. Moved the reboot logic to the fixture, and calling the fixture in the tests.
2. Removed the repeated code in all tests.
Ran it on my T2 TB:
```
------------------------------------------------------------------------------------------------------------------- live log sessionfinish -------------------------------------------------------------------------------------------------------------------
06:40:51 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs …
```

[T2:multidut]: Change reboot to reboot-fixture in pfcwd_basic.

---

tests/common/dualtor/dual_tor_utils.py

Summary:
In PR test, check_nexthops_single_downlink have chance to take more than 1 hour because it needs to run several rounds of traffic test, each round would take more than 20 mins, it would easily cause PR test timeout
Skip earlier in check_nexthops_single_downlink for VS platform, needn't go deep into traffic test

Skip dualtor check_nexthops_single_downlink earlier on VS platform

---

tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml

Summary:
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/15341
drop_packtes tests were skipped for MGFX by folder previously. Now it is broken by this change #14395 Hence update condition mark
Update condition mark
Run tests

[202405][drop_packets] Skip drop_packets on MGFX (#15341)

---

tests/qos/files/qos_params.j2c.yaml
tests/qos/files/qos_params.jr2.yaml

Cherry-pick PR #13069
Cherry-pick PR#14585
Cherry-pick PR#14802
Summary:

[Cherry-pick #13069,14585,14802] qos_yaml j2C+ changes for new _vsq thresholds 

---

tests/common/testbed.py

Summary:
This PR is to support topology `ptp` in function `get_testbed_type`.
The change will fix the warning message
```
23:49:33 testbed.get_testbed_type                 L0261 WARNING| Unsupported testbed type - ptp-256
23:49:33 testbed.get_testbed_type                 L0261 WARNING| Unsupported testbed type - ptp-256
```
This PR is to support topology `ptp` in function `get_testbed_type`.
Add `ptp` into the regex list.
Verified by running test on a physical testbed. The warning message doesn't show up any more.
No.

Support ptp in get_testbed_type

---

tests/common/snappi_tests/multi_dut_params.py
tests/common/snappi_tests/traffic_generation.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py

Summary:
Fixes # (issue) Az 30112879
Ingress port does not get cleared before running the test. This change will make sure both ingress and egress are cleared

feat: add support for clearing counter for ingress

---

.azure-pipelines/pr_test_scripts.yaml
tests/route/test_route_perf.py

Summary:
for multi-asic devices, when asic is broadcom, using "bcmcmd" needs to specify asic id.
TODO:
depending on type of asic, e.g. xgs/dnx, we need to confirm with broadcom if the asic supports "conf show l3_alpm_enable" command, if not, skip for that platform.

[multi-asic fix] fix new change in test_route_perf.py to support multi-asic

---

tests/platform_tests/test_advanced_reboot.py

test_advanced_reboot script failed on fixture 'advanceboot_neighbor_restore' not found, which caused by missing import advanceboot_neighbor_restore in test_advanced_reboot.py.
Summary:
test_advanced_reboot test failed due to fixture 'advanceboot_neighbor_restore' not found
Add missed fixture "advanceboot_neighbor_restore"
https://elastictest.org/scheduler/testplan/672838a18317d3b3441bd1dc?testcase=platform_tests%2ftest_advanced_reboot.py&type=console&leftSideViewMode=detail

Fix fixture 'advanceboot_neighbor_restore' not found issue

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skip Source IP is the same Dest IP test_dip_sip test in Cisco 8122 platforms
Summary:
Skip test_dip_sip test for cisco 8122 platforms, as its not supported
=============================================================================================== warnings summary ===============================================================================================
../../usr/local/lib/python3.8/dist-packages/paramiko/transport.py:236
/usr/local/lib/python3.8/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
"class": algorithms.Blowfish,
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
--------------------------------------------------------------- generated xml file: …

Skipping test_dip_sip for Cisco 8122 platforms

---

tests/bgp/test_bgpmon.py

Summary:
There has been an issue that missing exit in the FRR template that caused nht config is missed in the FRR config when vrf is configurated. After fixing the issue in https://github.com/sonic-net/sonic-buildimage/pull/19587, add a new case to verify the 'ip nht resolve-via-default' should be present in FRR config whether vrf is configurated.

Add a new case to check if 'ip nht resolve-via-default' config exists

---

tests/sub_port_interfaces/sub_ports_helpers.py
tests/sub_port_interfaces/test_sub_port_interfaces.py

Summary:
Currently we are using conditional mark to add marker, then use pytest hook to redirect testutils.verify function to a function always return True to skip traffic test. With this change, the skip_traffic_test fixture is no longer needed in test cases, streamlining the test code and improving clarity.
Remove skip_traffic_test fixture in sub_port_interfaces tests

Remove skip_traffic_test fixture in sub_port_interfaces tests

---

tests/saitests/py3/sai_qos_tests.py

Summary:
Fix for intermittent PFCXonTest failure on Cisco Smartswitch in T1 topology. 
PFCXonTest was intermittently failing for Smartswitch T1 due to a couple extra recv counters.
Update the counter check to use COUNTER_MARGIN similarly to broadcom-dnx as well as every other check later in the same test case.
Ran qos/test_qos_sai.py on T1 testbed and PFCXonTest now passes:
`====================================== 26 passed, 209 skipped, 1 warning in 3332.97s (0:55:32) ======================================`

Use COUNTER_MARGIN in PFCXonTest check.

---

ansible/devutil/device_inventory.py
ansible/devutil/ssh_session_repo.py
ansible/devutil/testbed.py
ansible/ssh_session_gen.py

Summary:
This change updates the SSH session gen to generate tmuxinator configurations. This helps us to find all relative devices for a testbed, so we can easily connect all and debug.
When debugging the testbed, we need to access related devices to find the issues, such as fanout, root, ptf and so on. However, finding these devices every time in mgmt repo and connect them one by one is tedious.
This change updates SSH session gen to load the link information as a link map. Then using BFS, we easily use the VLAN information to find all related devices.
With this, we can generate a tmuxinator configuration for each testbed, which helps us to connect to all fanout, root, ptf, and server that is related to the DUT.
Each type of the connection are put in different tmux window, while each …

Update SSH session gen to generate tmuxinator configurations

---

tests/tacacs/utils.py

Summary: Add `--no-pager` to `journalctl` to display all logs at once, allowing grep to search through the output even when there are many logs.
Test locally
```
tacacs/test_ro_disk.py::test_ro_disk[vlab-01] PASSED                                                                                                    [100%]
```

[TACACS] Add --no-pager to tacacs utils

---

tests/qos/files/qos_params.gb.yaml
tests/qos/test_qos_sai.py

Summary:
The testcase test_qos_sai.py::TestQosSai::testQosSaiQWatermarkAllPorts is failing due to much narrower margins in the lossy queue counter case. So this PR attempts to increase the margin, and also handle a case where the required qos.yml key is not present in the TC's params, but in the params for port-speed structure itself.

Fix the parameters for AllPortQueueWaterMark Testcase.

---

tests/golden_config_infra/templates/sample_golden_config_db.j2

Add portchannel check to sample_golden_config_db.j2 to resolve errors for topos (specifically mx) that do not have portchannels for `golden_config_infra/test_config_reload_with_rendered_golden_config.py` when running `sonic-cfggen -d -t /tmp/golden_config_db.j2 > /etc/sonic/golden_config_db.json`
Summary:
Fixes #15310
Fix #15310
Added portchannel check in sample_golden_config_db.j2  jinja file
Ran and tested on mx topos with no portchannels defined

fix sample_golden_config_db.j2 portchannel undefined

---

tests/common/devices/sonic.py

ASIC identification is (mostly) done by matching entire lines from the output of the lspci command. This is prone to failure over time, if the output lines change for whatever reason. A more robust approach is to match only those tokens which can
be considered reliable in identifying and distinguishing the ASICs, as opposed to matching whole lines of output. This change implements the token-based approach.
Additionally, this PR introduces the token matching for the TH4 and TH5 asics.
Summary:
`test_everflow_per_interface.py` was failing due to misidentified asic (i.e. asic was "unknown"), causing the test to execute a different code path than intended.
Updated the matching logic to compare on the pertinent information returned from the lspci command, rather than entire …

Fix asic identification

---

tests/vlan/test_vlan_ping.py

Summary:
Update test_vlan_ping for m0-2vlan topo.
Update test_vlan_ping for m0-2vlan topo.
Use `topo_type` instead of `topo_name`.
Verified on Nokia-7215 M0-2VLAN testbed.
```
vlan/test_vlan_ping.py::test_vlan_ping PASSED                                                                                   [100%]
============================================== 1 passed, 1 warning in 441.79s (0:07:21) ===============================================
```

[M0-2VLAN] Update test_vlan_ping for m0-2vlan topo

---

tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml

Summary:
Currently, route/test_route_perf.py does not support traffic tests on multi-asic KVM testbeds and has a high failure rate
Skipping traffic test in route perf test for multi-asic KVM platform

Skip traffic test in route perf test for multi-asic KVM platform

---

tests/lldp/test_lldp_syncd.py

At the start of `test_lldp_syncd.py::test_lldp_entry_table_after_reboot` the test polls and checks that LLDP_ENTRY_TABLE keys match show lldp table output.
The `eth0` port is added last so sometimes the entry keys will have it but the lldp table output will not.  From debugging, this is the case since the end of the previous test (I put a check on the keys vs lldp table output and observed the missing `eth0` at the end of `test_lldp_syncd.py::test_lldp_entry_table_after_lldp_restart`).  From our test results, this issue hits both fixed and modular, but appears to be more easily reproduced on fixed systems.
Added a wait_until at the start of `test_lldp_entry_table_after_reboot` to wait until the LLDP_ENTRY_TABLE keys match show lldp table output before the tests starts to reboot.
Summary: …

[202405] Fix intermittent issue on reboot in test_lldp_syncd

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/dualtor/tunnel_traffic_utils.py
tests/dualtor/test_switchover_faulty_ycable.py

Summary:
Add dualtor stanalone and swithover faulty ycable test to PR test

Add dualtor stanalone and swithover faulty ycable test to PR test

---

tests/conftest.py

Summary:
Fixes #14829
Fix issue where `rand_one_dut_hostname` fixture was not being properly set when the fixture is loaded dynamically, like in the case for `ecmp/test_ecmp_hash_seed_value`. The `custom_fixture` plugin will dynamically add `rand_one_dut_hostname`, but the current method of setting `rand_one_dut_hostname_var` does not account for this and so it is not set.
Set the global variable within the `rand_one_dut_hostname` fixture directly.
Ran and verified test suite

Fix conftest rand_one_dut_hostname IndexError

---

tests/saitests/py3/sai_qos_tests.py

Summary:
observed consistent headroom wartermark test failure on 7260
and it's known issue of test script, as below RCA:
RCA:
summarize test step first:
1. PTF send lots of pkt to multiple src ports to fill multiple PG's share buffer
2. PTF send one or a few pkts to multiple src ports to trigger pfc on multiple PG
3. check watermark before test headroom's watermark
4. PTF send pkt to multiple src port to consum headroom pool, and test if watermark changes as expected
after step2,
already send 20 pkts into headroom to trigger PFC on 10 src ports (20 PG)
but, so far, "upper_bound" value is static hardcode "2 * margin + 1", didn't consider headroom pool consumption in step2.
since we use dynamically threshold calculating, it can get accurate threshold value, we pretty sure …

fix 7260 headroom pool watermark test failure

---

tests/qos/qos_sai_base.py

Summary:
The search for shortlink linecard logic added in PR https://github.com/sonic-net/sonic-mgmt/pull/14925 does not verify that a DUT is multi-asic for the single_dut_multi_asic tests and incorrectly tries to access two asics on a single-asic DUT.
Add a check for multi-asic DUT in the shortlink linecard selection logic.
Fixes #15073
Run the test on out t2min chassis both with single-asic and multi-asic DUTs

Fix qos node selection for single-asic in qos_sai_base test

---

tests/ip/test_ip_packet.py

Summary:
This PR is to skip `RX_DRP` counter check on Mellanox platform in `test_drop_l3_ip_packet_non_dut_mac`.
The packets are dropped silently on Mellanox devices.
This PR is to skip `RX_DRP` counter check on Mellanox platform in `test_drop_l3_ip_packet_non_dut_mac`.
Check asic_type and skip check of `RX_DRP`.
The change is verified on a Mellanox testbed.
```
ip/test_ip_packet.py::TestIPPacket::test_drop_l3_ip_packet_non_dut_mac[str2-msn2700-spy-2] PASSED                                                                                               [100%]
```
Mellanox …

Skip RX_DRP check on Mellanox platform in test_drop_l3_ip_packet_non_dut_mac

---

tests/common/helpers/telemetry_helper.py
tests/telemetry/test_telemetry.py

Summary:
Fixes # (issue) 29949271
After config reload, other telemetry cases fail since testing telemetry config is no longer present. This causes that telemetry config will not have client_auth set to false which results in cert errors when running telemetry query.
Added disable_loganalyzer to test_telemetry_queue_buffer_cnt since we see teardown loganalyzer errors complaining about non telemetry related syncd SAI_API logs
Ensure that telemetry present after each config reload call.
Manual/Pipeline

Ensure correct testing telemetry config after config reload

---

tests/snappi_tests/multidut/bgp/test_bgp_outbound_downlink_port_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_downlink_process_crash.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_tsa.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_multi_po_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_member_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_process_crash.py

Summary:
test case fails if the testbed doesn't support snappi bgp convergence setup.
If a testbed doesn't satisfy the requirement of a test case, the test case should be skipped.
use pytest_require() instead of pytest_assert()
tested on physical testbed.

[snappi] skip multidut bgp instead of assert if testbed doesn't support.

---

tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py

Summary:
The fix in #15057 was overwritten by recent changes. This PR add it back into master. #15539 add it back into 202405.
Will open another PR for 202405 as the fix will be slight different.
1. test_pfc_pause_single_lossless_prio_reboot:
- the parameter/fixture sequence is different between master and 202405 branch. 
- this change moves the enum_dut_lossless_prio_with_completeness_level back to original position. so it will be same as 202405 branch.
2. test_pfc_pause_single_lossy_prio_reboot:
- add enum_dut_lossy_prio_with_completeness_level back in.
add PR #15057 back into master.
tested it locally.

[snappi][master only] add enum with completeness_level back in

---

tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py

Summary:
The fix in #15057 was overwritten by recent changes. This PR add it back into 202405.  #15538 added for master.
1. test_pfc_pause_single_lossless_prio_reboot:
- remove unused enum_dut_lossless_prio, keep only enum_dut_lossless_prio_with_completeness_level
2. test_pfc_pause_single_lossy_prio_reboot:
- add enum_dut_lossy_prio_with_completeness_level back in.
add PR #15057 back into 202405.
tested it locally.

[snappi][202405] add enum with completeness_level back in

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml
tests/common/vs_data.py
tests/ipfwd/test_nhop_group.py

Summary:
Add nhop group test to onboarding PR test and skip traffic test

Add nhop group test to onboarding PR test

---

tests/pfcwd/test_pfcwd_function.py

Summary: Fix flaky pfc_storm stom_restored
Fixes # (issue) 30115860
Currently we detect flaky in detecting storm restore. The reason was because the storm terminated early and restore itself before LogAnalyzer can detect restoration.
As a result, we want to keep this to be stormed long enough.
After the end of each test case, we have `stop_storm` so it would be fine.

fix: fix flaky pfc_storm

---

tests/telemetry/test_telemetry.py
tests/telemetry/test_telemetry_cert_rotation.py

Cherry-pick fixes of https://github.com/sonic-net/sonic-mgmt/pull/13905 into 202405
Summary:

Cherry-pick master PR #13905 into 202405

---

tests/bgp/test_bgp_dual_asn.py
tests/common/gu_utils.py
tests/generic_config_updater/test_bgp_speaker.py

In script `test_bgp_dual_asn.py`, there is an import from the folder `tests/generic_config_updater`. To minimize cross-module dependencies, we have refactored this function to a common location.
Summary:
In script `test_bgp_dual_asn.py`, there is an import from the folder `tests/generic_config_updater`. To minimize cross-module dependencies, we have refactored this function to a common location.

Move function `get_bgp_speaker_runningconfig` to common place.

---

tests/snmp/conftest.py

Summary: Move `yield` statement out of for loop in snmp fixture `setup_check_snmp_ready`
Fixes # https://github.com/aristanetworks/sonic-qual.msft/issues/307
https://github.com/sonic-net/sonic-mgmt/pull/15359 has introduced a "yield" statement inside the for loop of duthosts which is causing fixture teardown to fail with `Failed: fixture function has more than one 'yield'` message.
Move "yield" statement out of this for loop of duthosts and do config rollback in a seperate for loop of duthosts.
Ran tests under `snmp` folder and tests are passing on `Arista-7260CX3-D108C8` platform.

[dualtor] Fix snmp/* tests failure on fixture teardown

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

All 3 tests in test_static_route are failing on 8122.
Tests are failing because “show flowcnt-route stats“ does not show the 1 test pkt that the test has sent.
“show flowcnt-route stats“ does not show the test pkt because counter config itself failed.
Counter config failed because FLOW_COUNTER_CAPABILITY was enabled recently on ASIC/SDK side for 8122 but 'enable_forwarding_route_counter' is not enabled on SONiC/asic_cfg.json on 8122.
'enable_forwarding_route_counter' is not enabled on SONiC/asic_cfg.json on 8122 because of scale limits (cannot scale more than 50k with the current LPM profile).
As the feature is not enabled for this platform, need to skip this testcase
Added a skip condition for test_static_route for 8122 …

Skipping test_static_route on Cisco 8122
