tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
PR introduced new srv6 script, it failed on other topologies, skip it for non cisco vs topologies.
https://github.com/sonic-net/sonic-mgmt/pull/13785
skip it for non cisco vs topologies.
Run srv6/test_srv6_basic_sanity.py on t0 testbed.

Skip srv6/test_srv6_basic_sanity.py for non cisco vs topologies

---

tests/common/dualtor/data_plane_utils.py
tests/common/dualtor/dual_tor_io.py
tests/dualtor_io/test_tor_bgp_failure.py

Summary:
Let's make the packets for each server belongs to same TCP flow, SONiC will use the same route to forward it.
So any route change will forward/drop all the packets from the same server.
Use fixed IP to generate packets for a single server.
```
dualtor_io/test_tor_bgp_failure.py::test_active_tor_kill_bgpd_upstream[active-standby] PASSED                                                                                                                                                                          [100%]^
```

[dualtor-io] Support using fix source IP for upstream packets

---

tests/common/dualtor/dual_tor_mock.py

On topologies with higher number of interfaces (i.e. >100), config commands take more time to run properly.
Executing the subsequent commands too quickly may cause the config to not change properly, causing problems in the mock dualtor setup.
Adding a wait_until and delays to give more time for config changes.
Summary:
config commands on topologies with high number of interfaces (i.e. >100) need more time to execute and settle.
Add wait and delay to ensure config commands properly execute
Configs are no longer in a half-baked state on a topology with 112 interfaces.
Tested on Arista-7260CX3-D108C8.

Add wait between mock dualtor setup commands

---

tests/common/reboot.py

Summary:
Fixes #15444 
Bad regex in supervisor reboot check is causing unwarranted test failures
Remove bad regex flags in supervisor reboot checks
Ran affected tests to ensure behaviour was correct
N/A
N/A
N/A

Fix REBOOT_TYPE_SUPERVISOR "check" value

---

tests/bgp/test_bgp_session_flap.py

https://github.com/sonic-net/sonic-mgmt/pull/13662 added support for running `bgp/test_bgp_session_flap.py` on `T2` topology.
However, the condition it added to skip iBGP neighbors only works on multi-asic LCs:
`if 'asic' not in v['description'].lower():`
E.G. here is a switch which has 3 LCs (LC4 - multi-asic, LC5 - multi-asic, LC6 - single-asic)
```
root@cmp206-4:~# show ip bgp summary -d all
...
Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down      State/PfxRcd  NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.0.0.1       4  65200       4113       6364         0      0       0  01:21:00            34050  ARISTA01T3
...
10.0.0.63      4  65200       4033       6720         0 …
```

`bgp/test_bgp_session_flap.py` Fix condition intended to skip iBGP neighbors to work on single-asic

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Below test cases are skipped for hwsku in Nokia-IXR7250E-36x400G & platform asic in ['x86_64-nokia_ixr7250e_36x400g-r0']
-testQosSaiHeadroomPoolSize
-testQosSaiHeadroomPoolWatermark
Issue : https://github.com/sonic-net/sonic-mgmt/issues/13503
Summary:
set skip for hwsku in Nokia-IXR7250E-36x400G & platform asic in ['x86_64-nokia_ixr7250e_36x400g-r0']
Execute the qos test cases

Skip sonic-mgmt  HdrmPoolSizeTest for Nokia-IXR7250E hwsku

---

tests/common/fixtures/duthost_utils.py

Summary:
The PR is to add a wait in `config_reload` after changing mgmt IP to ensure BGP sessions are up.
Without this fix, `test_bgp_facts_ipv6_only` is flaky on some testbed with below errors.
```
>           assert state_fact[0] == "Established"
E           AssertionError
```
The PR is to add a wait in `config_reload` after changing mgmt IP to ensure BGP sessions are up.
Set `wait_for_bgp=True` in `config_reload`.
```
ip/test_mgmt_ipv6_only.py::test_bgp_facts_ipv6_only[bjw2-can-4600c-5-None] …
```

Wait BGP sessions after changing mgmt IP

---

.azure-pipelines/run-test-elastictest-template.yml

Summary:
PR/nightly test have a chance to fail in installing azure-cli for unable to acquire dpkg lock, which means there are 2 or more processes are running apt install at the same time
Install azure-cli step by step, and add a timeout for all apt action to acquire dpkg lock
Ref: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

Install azure-cli step by step to fix dpkg lock failure

---

tests/platform_tests/test_intf_fec.py

Summary:
Add support to the port FEC BER in sonic mgmt
These changes are require for  the new feature port FEC BER, HLD#1829
We verify it by running the sonic-mgmt test.
None
Please refer to the following HLD 
https://github.com/sonic-net/SONiC/pull/1829

Add the port FEC BER mgmt test

---

tests/snappi_tests/files/helper.py

Summary:
T0/T1 support in snappi multidut is being overwritten by recent commit. Adding it back in.
Add back T0/T1 support for multidut snappi.
Use T0/T1 specific function to get snappi ports instead of using variables.py

[Snappi] add back T0/T1 merge

---

tests/acl/test_acl.py

Summary:
We see TestAclWithReboot L3_Scenario test fail on Nokia-7215 M0 platform. The root cause is test start before BGP fully established. Update this testcase to fix M0 L3 scenario.
Fix TestAclWithReboot on M0 platforms.
Wait BGP fully establish before test start.
Verified on Nokia-7212 M0 testbed.
```
acl/test_acl.py::TestAclWithReboot::test_udp_source_ip_match_forwarded[ipv4-ingress-downlink->uplink-m0_vlan_scenario-Vlan1000] PASSED [  6%]
acl/test_acl.py::TestAclWithReboot::test_udp_source_ip_match_forwarded[ipv4-ingress-downlink->uplink-m0_l3_scenario-Vlan1000] PASSED [ 12%]
acl/test_acl.py::TestAclWithReboot::test_udp_source_ip_match_forwarded[ipv4-ingress-uplink->downlink-m0_vlan_scenario-Vlan1000] PASSED [ 18%]
acl/test_acl.py::TestAclWithReboot::test_udp_source_ip_match_forward …
```

[M0] TestAclWithReboot wait BGP fully establish after reboot

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Xfail qos/test_qos_dscp_mapping.py for Cisco-8122.
This test uses ECT bit marked packets in combination with tunnel decap. ECT bit preservation is not yet supported on Cisco-8122. 
Marking the test as xfail with strict checking, so later when the test begins passing it will be easier to see and remove the xfail. 
Verified on 8122 cisco platform that it reports an xfail. 
Cisco-8122 only.

Xfail qos/test_qos_dscp_mapping.py for Cisco-8122

---

ansible/setup-management-network.sh
docs/testbed/README.testbed.Setup.md
docs/testbed/README.testbed.VsSetup.md
setup-container.sh

Summary:
j2cli is not being maintained anymore and will start to fail to work on ubuntu 24.04, because it is trying to load the imp module, which is deprecated now.
However, [j2cli](https://github.com/kolypto/j2cli) is being archived not being maintained anymore. The author recommends using other alternatives that is actively being maintained, such as [jinjanator](https://github.com/kpfleming/jinjanator).
Hence, making this change in order to support the latest OS.
Changed j2cli to jinjanator.
In setup-container.sh, we also try to install the jinjanator if it is not found. The reason is that setup-management-network is running under root privilege, so even with `--user` the jinanator installed there will be installed under /root folder. The regular user will not have access to it.
Run on …

Update j2cli to jinjanator.

---

tests/telemetry/events/dhcp-relay_events.py

Summary:
Fixes # (issue) 30198612
isc-dhcpv4 process is not expected to run for MX topologies so skipping dhcp_relay events testing
Check for switch type BmcMgmtToRRouter
Manual test/pipeline

Skip dhcp_relay events for mx

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Ignore test_bgp_prefix.py::test_bgp_prefix_tc1_suite for Cisco 8122 backend compute ai deployment
Testcase failed:
2024 Nov 14 08:57:04.106664 str3-8122-01 ERR bgp#bgpcfgd: BGPAllowListMgr::Default action community value is not found. route-map 'ALLOW_LIST_DEPLOYMENT_ID_0_V4' entry. seq_no=65535
Cisco 8122 backend compute ai deployment uses totally different BGP teamplate. The above check is meaningless.
So, we shoud ignore test_bgp_prefix.py::test_bgp_prefix_tc1_suite.
Ignore test_bgp_prefix.py::test_bgp_prefix_tc1_suite for Cisco 8122 backend compute ai deployment

Ignore test_bgp_prefix.py::test_bgp_prefix_tc1_suite for Cisco 8122 backend compute ai deployment

---

tests/arp/test_stress_arp.py

icmpv6 connection tracking can cause conntrack table in kernel to grow rapidly
and lead to packets being dropped, making the device unresponsive to connection
requests. The signature seen when this happens is the following:
"kernel: nf_conntrack: nf_conntrack: table full, dropping packet”
An investigation on this identified that most of the entries in conntrack table were due to unreplied icmpv6 requests which ended up in the dying list.
Snippet of "conntrack -f ipv6 -L dying " on a device with the issue:
icmpv6 58 0 src=2603:10b0:105:1065::1 dst=2603:10b0:105:1065:0:3de0:f090:e3e0 type=128 code=0 id=56516 [UNREPLIED] src=2603:10b0:105:1065:0:3de0:f090:e3e0 dst=2603:10b0:105:1065::1 type=129 code=0 id=56516 mark=0 use=1
icmpv6 58 0 src=2603:10b0:105:1065::1 …

[arp] add conntrack table test for incomplete neighbor

---

tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py

Summary:
The pfcwd_basic service-restart cases keep failing due to: https://github.com/sonic-net/sonic-buildimage/issues/20637
The ask is not to restart swss multiple times without doing a config reload in between. So in this PR:
1.  we are doing config-reload for every iteration of the test 
2. The swss restart is done only once in one DUT.
3. The asic is randomly picked, and the swss of that ASIC is restarted instead of doing the restart for all asics.
4. Also added checks to make sure the services, interfaces and bgp are up before proceding with the ixia traffic.
The issue: https://github.com/sonic-net/sonic-buildimage/issues/20637
Pls see the description.
Ran it on my TB.
```
=============================================================================================================== …
```

Fixing service-restart testcases.

---

ansible/roles/test/files/helpers/bfd_responder.py

Summary:
On cisco platform, ipv4/ipv6 multihop tests are failing because BFD injected packets are not using correct queue (should be UC7 instead of UC0). The reason is because once BFD session is up, BFD responder always sends packets with P bit set. When DUT receives these packets, it punts them to control plane which injects packets with F bit set in response.
Why these packets with F bit don't go out of UC7 is a known issue which is already fixed in cisco sdk.
However, even without the sdk fix, there should gone be constant exchange of packets with P/F bits when session is UP.
BFD responder currently uses first packet it receives from DUT as template and always uses flags from that packet for subsequent packets (which has P bit set). The fix is in BFD responder to respond with F bit …

Handle p bit properly in bfd_responder

---

tests/common/config_reload.py
tests/common/devices/multi_asic.py

Summary:
Fixes # (issue) #15630: wait_for_bgp is not working in config_reload
`get_bgp_neighbors_per_asic()` only returns BGP neighbors with Established status, so the wait_until always returns directly without any wait.
I fixed the logic and made `get_bgp_neighbors_per_asic()` in `config_reload()` to return all BGP neighbors regardless of their status. Then I fixed the logic in `check_bgp_session_state_all_asics()` to check if all BGP session states are equal to the target state.
I ran the updated code and can confirm it's now checking all BGP neighbors

fix: return all BGP neighbors for config reload

---

tests/tacacs/test_ro_user.py

Test test_ro_user_ipv6 after all other tests.
When IPV6 test case failed on some IPV6 not stable device, some other test also will failed.
- Microsoft ADO: 30232468
Test test_ro_user_ipv6 after all other tests.
Test test_ro_user_ipv6 after all other tests.

Test test_ro_user_ipv6 after all other tests.

---

tests/conftest.py

Summary:
PR #14804 caused test_route_flap fail on M0/Mx with below error:
```
>       pytest.fail("Did not find a dut in duthosts that for topo type {} that has upstream nbr type {}".
format(tbinfo["topo"]["type"], upstream_nbr_type))
E       Failed: Did not find a dut in duthosts that for topo type m0 that has upstream nbr type T3
```
Creating this PR to fix.
Fix test_route_flap on M0/Mx topo.
Support upstream neighbor on M0/Mx.
Verified on Nokia-7215 M0.
Verified on Arista-720DT M0.

[M0/Mx] Fix test_route_flap

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

In PR #15563, we add the missing conditions for extended entries in `qos/test_qos_sai.py::TestQosSai`. But we add the wrong condition into case `qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark[None-wm_pg_shared_lossy]`, as it is a xfail mark, not skip. So in this PR, we fix this issue and remove this condition. 
Summary:
In PR #15563, we add the missing conditions for extended entries in `qos/test_qos_sai.py::TestQosSai`. But we add the wrong condition into case `qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark[None-wm_pg_shared_lossy]`, as it is a xfail mark, not skip. So in this PR, we fix this issue and remove this condition.

[Bugfix] Del wrong condition of case `qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark[None-wm_pg_shared_lossy]:`

---

tests/common/platform/device_utils.py
tests/platform_tests/api/conftest.py
tests/platform_tests/api/test_chassis.py
tests/platform_tests/api/test_component.py
tests/platform_tests/api/test_fan_drawer.py
tests/platform_tests/api/test_psu.py
tests/platform_tests/api/test_psu_fans.py
tests/platform_tests/api/test_watchdog.py
tests/smartswitch/common/device_utils_dpu.py
tests/smartswitch/platform_tests/test_reload_dpu.py
tests/smartswitch/platform_tests/test_show_platform_dpu.py

The `platform_api_conn` fixture is utilized by scripts in both the `smatswitch` and `platform_tests` directories. To reduce cross-feature dependencies and improve code organization, I relocated the fixture to a shared common location, making it accessible without creating unnecessary interdependencies between these feature-specific directories.
Summary:
The `platform_api_conn` fixture is utilized by scripts in both the `smatswitch` and `platform_tests` directories. To reduce cross-feature dependencies and improve code organization, I relocated the fixture to a shared common location, making it accessible without creating unnecessary interdependencies between these feature-specific directories.
I relocated the fixture `platform_api_conn` to a shared common location

Move fixture `platform_api_conn` to common place. 

---

tests/common/snappi_tests/common_helpers.py
tests/snappi_tests/files/helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py

@sdszhang : This PR attempts to fix the fixture-not-found error and KeyError that you are seeing in the snappi_test multidut runs. Pls let me know if this works for you.

Fixing the import error and KeyError in snappi_test/multidut executions.

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

In #14912, we added conditions for longer matching entries in conditional marks. However, some conditions were missed under the entry `qos/test_buffer.py:`. This PR adds these missing conditions to entries that start with and extend beyond `qos/test_buffer.py:`
Summary:
In #14912, we added conditions for longer matching entries in conditional marks. However, some conditions were missed under the entry `qos/test_buffer.py:`. This PR adds these missing conditions to entries that start with and extend beyond `qos/test_buffer.py:`
This PR adds these missing conditions to entries that start with and extend beyond `qos/test_buffer.py:`

[Bugfix] Add missing conditions for extended entries in `qos/test_buffer.py:`

---

ansible/library/snmp_facts.py

Summary:
Fixes MSFT ADO 30112399
BY default, the snmp timeout is 1s,
Cisco 8800 has lots of interfacts, this causes the high chance of the timeout of snmp.
Add timeout to tolerate the latency.
Fix the snmp timeout issues on Cisco 8800 chassis.
Enable timeout for snmp query.
Locally test on physical chassis testbed:
snmp/test_snmp_psu.py::test_snmp_numpsu[x-sup-2] PASSED                                                                                                                                                                            [ 50%]
snmp/test_snmp_psu.py::test_snmp_psu_status[x-sup-2] PASSED                                                                                                                                                                     [100%]

Add timeout for Cisco 8800 snmp

---

ansible/library/bgp_route.py

Why I did it
FRR has deprecated the code for bgpStatusCodes/bgpOriginCodes in below checkin. Hence updating the ansible library to handle this change. As FRR is being upgraded to 10.0.1 version.
https://github.com/FRRouting/frr/pull/14981
Signed-off-by: Kishore Kunal <kishore.kunal@broadcom.com>

[FRR Upgrade] Remove deprecated code for bgpStatusCodes/bgpOriginCodes

---

tests/route/test_route_perf.py

Broadcom confirmed that `l3_alpm_enable` soc property is only used in `XGS` platforms (CS00012377343)
Therefor we should skip the check for this soc property on `DNX` platforms.
Summary:
Fixes #15511

Skip l3_alpm_enable check on broadcom-dnx platforms

---

tests/gnmi/test_gnmi_configdb.py

Summary: For Multi-Asic devices, `test_gnmi_configdb_full_01` TC isn't using asic specific namespace, due to which PORT keys received from `get_interface_status` & one in `config_db` are not in sync. 
Checks whether DUT is multi-asic or not; if yes, then generates configuration based on the asic namespace which contains the PORT key returned by `get_inerface_status`
- [Issue 15407 : Multi-asic support for test_gnmi_configdb TCs](https://github.com/sonic-net/sonic-mgmt/issues/15407)
- This PR just adds the multi-asic support; but still TC would fail because Multi-Asic support for `ApplyPatchDb` API has to be provided, [Issue link](https://github.com/sonic-net/sonic-buildimage/issues/20874)
Checks whether DUT is multi-asic or not; if yes, then generates configuration based …

Added Multi-Asic Handling for test_gnmi_configdb_full_01 TC

---

tests/qos/test_buffer.py

Summary:
tests/qos/test_buffers.py is failing in mAsic platforms since the pg_profile_lookup.ini path
The script: qos/test_buffers.py is using wrong path for multi-asic platforms. It gives this error:
```
if (res.is_failed or 'exception' in res) and not module_ignore_errors:
&gt;           raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
E           tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =&gt;
E           {"changed": true, "cmd": "cat /usr/share/sonic/device/x86_64-8800_rp-r0/Cisco-8800-RP//pg_profile_lookup.ini", "delta": "0:00:00.006060", "end": "2024-10-31 14:58:57.717623", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2024-10-31 14:58:57.711563", "stderr": "cat: …
```

check pg_profile_lookup.ini in multiasic specific path.

---

tests/common/platform/reboot_timing_constants.py
tests/common/platform/templates/expect_boot_messages

Summary:  Update the regex to detect mac jump because the log level for the message changed
The log level for fdbEvent messsage to detect mac jump is changed to NOTICE, so the regex used by the test has to be updated.  
Change the regex for detecting mac jump
Check the test can pass after the change

Fix platform_tests/test_advanced_reboot.py test_warm_reboot_mac_jump for mac jump detection

---

tests/common/snappi_tests/snappi_fixtures.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py

Summary:
Fixing dut port mapping when retrieving counter. Otherwise, ingress duthost maybe used to retrieve egress counters.
In Snappi ports, the ingress dut and port maybe different for each port. 
In current code, it uses same ingress dut for both ports.
```
dut_rx_port1 = tx_port[0]['peer_port']
dut_rx_port2 = tx_port[1]['peer_port']
rx_pkts_1 = get_interface_stats(ingress_duthost, dut_rx_port1)[ingress_duthost.hostname][dut_rx_port1]['rx_ok']
rx_pkts_2 = get_interface_stats(ingress_duthost, dut_rx_port2)[ingress_duthost.hostname][dut_rx_port2]['rx_ok']
```
which results in the counter was retrieved on incorrect dut, and get the following error:
```
FAILED snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py::test_lossless_response_to_throttling_pause_storms[mu …
```

[Snappi] Fixing dut/port mapping for counters

---

tests/common/snappi_tests/traffic_generation.py
tests/snappi_tests/multidut/ecn/files/multidut_helper.py
tests/snappi_tests/multidut/ecn/test_multidut_ecn_marking_with_snappi.py

Summary:
Add ECN test for comparative marking of traffic based on flow rate
Added testcase to provide different combination of flow percent for both lossless prior
1)Injected traffic to ingress port and 1 egress port causing congestion
2) the resulting congestion results in ecn marking
3) Verify the ecn marking is happening as expected based on the flow percent
Verified on T2 Ixia setup with multi asic DUT
```
========================================== short test summary info ====================================================================================================================================
PASSED snappi_tests/multidut/ecn/test_multidut_ecn_marking_with_snappi.py::test_ecn_marking_port_toggle[multidut_port_keys=single-dut-multi-asic]
PASSED …
```

T2 ECN test: ECN comparative marking based on % of traffic 

---

tests/ip/test_ip_packet.py

Summary:
Skip RX_DRP check in test_drop_l3_ip_packet_non_dut_mac.
Skip RX_DRP check in test_drop_l3_ip_packet_non_dut_mac, current ASIC behavior can't support RX_DRP counter.
Skip RX_DRP check in test_drop_l3_ip_packet_non_dut_mac,
Verified on Nokia-7215 M0 testbed:
```
ip/test_ip_packet.py::TestIPPacket::test_drop_l3_ip_packet_non_dut_mac[7215-6] PASSED                                                [100%]
===================================================== 1 passed, 1 warning in 442.12s (0:07:22) ======================================================
```

[Marvell] Skip RX_DRP check in test_drop_l3_ip_packet_non_dut_mac

---

tests/common/devices/eos.py
tests/qos/qos_sai_base.py
tests/qos/test_qos_sai.py

Intermittently testQosSaiLossyQueue tests fails due to Port-channel flap on broadcom-dnx T2 Voq chassis.
The reason the port-channel goes down is because this test requires disabling TX on the egress port (which is a member of a port-channel)
With the huge buffer-size, it takes a longer time to send packets . This will result in the TX LACP packets to stop egressing, so after 3 LACP packets are missed (~90s) on the server side the LAG is torn down.
Issue # https://github.com/sonic-net/sonic-mgmt/issues/11682
Summary:
Intermittently testQosSaiLossyQueue tests fails due to Port-channel flap
The lacp timer multiplier on the EOS host is configurable.
By default, timeout is 30 secs with a failure tolerance of 3. 
We changed the multiplier to an increased value to hold the …

[QoS]Increasing LACP timer for lag ports for broadcom-dnx neighbor EOS host   

---

tests/snappi_tests/multidut/ecn/files/multidut_helper.py

Summary:
MIGSMSFT-630 Add sonic-mgmt / IXIA test for cisco platforms to verify ECN Counter operation.
Create two flows one for each lossless TC per Ixia port each at half of 99.98% rate
- Inject traffic and read ECN Counters and verify it incremented.
- flap the interface state (shut, wait for 0.2 seconds, no shut the interfaces of Ixia)
- restart the traffic streams
- verify that the ECN counters increment from the baseline value (new values read MUST NOT be zero)
Verified on T2 DUT setup
```
============================================================================================================================================ PASSES ========================================================================================================================================= …
```

sonic-mgmt / IXIA : T2 test  to verify ECN Counter operation pre and post port state toggle

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
The cherry-pick PR: https://github.com/sonic-net/sonic-mgmt/pull/15659 doesn't fix the skip condition for `testPfcStormWithSharedHeadroomOccupancy`.
Add the skip condition same as master branch:
https://github.com/sonic-net/sonic-mgmt/blob/64e5cad18af2b520ca800df0c903867e939e2d3c/tests/common/plugins/conditional_mark/tests_mark_conditions.yaml#L1427-L1434

[202405][dualtor] fix qos skip condition

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

This PR adds a conditional mark to skip the get_watchdog chassis API and test_watchdog API tests for the unsupported S6000 HWSKU.
Summary:
Fixes Microsoft ADO: 29921065
get_watchdog() is unsupported on the S6000 HWSKU and therefore is not a valid test.
Added a conditional mark to skip the test for S6000 platform.
Added the conditional mark and ran the sonic-mgmt test, and verified that it was skipped:
```
platform_tests/api/test_chassis.py::TestChassisApi::test_get_watchdog[sonic-s6000-device] SKIPPED (Unsupported platform API)                                                       [100%]
=================================================================================== warnings summary =================================================================================== …
```

Skip chassis watchdog API test for unsupported S6000 platform

---

tests/snappi_tests/multidut/pfc/files/multidut_helper.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py

Summary:
The test: test_pfc_pause_single_lossy_prio is resulting in flaky results. On inspecting the failed state, we find that the cisco-8000 backplane load-balancing is the cause for flakiness. It needs six streams to have higher chance of traffic being equally distributed in the backplane, and the traffic can be sent without being dropped.
Flakiness of test_pfc_pause_single_lossy_prio test.
Changed to 6 udp streams for lossy traffic.

T2-snappi: Split udp stream to 6 ports for lossy, but only one for lossless.

---

ansible/module_utils/port_utils.py

Reverts sonic-net/sonic-mgmt#15287
Get conn_graph_facts would loop all devices in inventory, once some Arista hwskus not included in the exception elif like Arista-7260CX3 with import error, read dut minigraph would always fail, so need to revert this PR

Revert "sonic-mgmt: Assert if Arista Hwsku is not found in port_utils"

---

tests/ipfwd/test_nhop_group.py

Arp eviction commands need to respect the asic namespace when being applied to multi-asic devices, as the procfs entries are for each individual asic.
Summary:
Fixes #15495
- [x ] Bug fix
- [x ] 202405
Ran on t2 multi asic and single asic LCs

[ipfwd/test_nhop_group]: Support multi-asic in interface flap test

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skip dut console connect tests for arista 7800 as the linecards do not have console ports
Summary:
Fixes #15518
- [ x] Bug fix
- [x ] 202405
Test was failing on setup due to no mgmt ip for console, as there isnt a console for the linecards
conditionally skip for 7800 chassis
ran locally, tests are skipped
arista 7800 specific

[dut_console]: conditionally skip connect tests for arista 7800 chassis

---

setup-container.sh

Summary:
Adds a check to enhance clarity of error thrown when a container created with a name that is of a length greater than 64 characters will fail to start after creation:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: sethostname: invalid argument: unknown.
```
This is due to the internal hostname of the container being set to the container's name, which has an additional 64 character limit, causing the container to fail to start consistently.
To enhance error messaging for this particular edge case, as it was previously difficult to discern why the container would be created successfully, but then consistently fail …

[setup-container] Add container length check

---

tests/fdb/utils.py

Summary: Fix "fdb/test_fdb_mac_move.py" failure with `AttributeError:  'NoneType' object has no attribute...`
Fixes # https://github.com/aristanetworks/sonic-qual.msft/issues/330
Test is relying on duthost method `get_crm_resources` method (parses info from `crm show resources all` output)  to get "fdb_entry" crm resource values. If output is empty for some reason then `duthost.get_crm_resources().get("main_resources")` will be empty and thus lead to `AttributeError: 'NoneType' object has no attribute 'get' during get_crm_resources()` failure if we try to access "fdb_entry" key.
https://github.com/sonic-net/sonic-mgmt/pull/11127 has introduced retry mechanism in case of empty output but condition is incorrect (`len(duthost.get_crm_resources())` will never be 0, as …

[sonic-mgmt] Fix "fdb/test_fdb_mac_move.py" AttributeError failure

---

tests/snmp/test_snmp_queue_counters.py

Summary: [sonic-mgmt][dualtor] Fix snmp/test_snmp_queue_counters.py teardown failure
Fixes # https://github.com/aristanetworks/sonic-qual.msft/issues/340
`teardown` fixture is trying to replace config_db.json file with the original config_db.json file on the duthost (saved by the `test_snmp_queue_counters` method before performing any config changes). But the teardown is happening on incorrect duthost (different from duthost used by the test method) and leading to `Source /etc/sonic/orig_config_db.json not found` error
Use `enum_rand_one_per_hwsku_frontend_hostname` fixture in the `teardown` fixture to derive the duthost name (similar to `test_snmp_queue_counters` method). This fixes the issue of teardown/cleanup happening in the incorrect dut.
Verified that test is passing with the fix …

[sonic-mgmt] Fix snmp/test_snmp_queue_counters.py teardown failure

---

tests/fdb/test_fdb_mac_learning.py

Summary: [dualtor-aa] Fix "fdb/test_fdb_mac_learning.py" failures
Fixes # https://github.com/aristanetworks/sonic-qual.msft/issues/329
Test is currently failing on `dualtor-aa` topologies due to
1) Packet sometimes going to unselected dut (due to active-active topology) and thus lead to mac learning failure.
2) After bringing up interfaces (from shutdown state), there is time.sleep of 30 seconds which seem to be not enough for muxcable status on duthost to become consistent with mux `server_status` (see `SERVER_STATUS` shown as `unknown` below). We need to wait for SERVER_STATUS to match with STATUS field for mac learning to happen.
```~$ show mux status Ethernet0
PORT       STATUS    SERVER_STATUS    HEALTH     HWSTATUS      LAST_SWITCHOVER_TIME
---------  --------  --------------- …
```

[sonic-mgmt][dualtor-aa] Fix fdb/test_fdb_mac_learning.py failures

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
This PR helps to skip '_mvrf_' tests for nokia chassis platform '**_x86_64-nokia_ixr7250e_36x400g-r0_**'
- '_mvrf_' feature is not supported for nokia chassis platform '_x86_64-nokia_ixr7250e_36x400g-r0_'
-  Add '_x86_64-nokia_ixr7250e_36x400g-r0_' platform in '_tests_mark_conditions.yaml_' file.
- Ran mvrf tests on T2 chassis and made sure tests are skipped as expected.

Skip mvrf tests for nokia chassis platform

---

tests/pc/test_lag_2.py

Currently, pc/test_lag_2 is having timeout in teardown with the default timeout of 300 seconds.
Since by default the thread_count = 2, which means at maximum, only 2 available thread can be used to run config_reload in DUT. Which means only 2 DUT are config_reload at a time. 
This will be slow and exceed 300 seconds.
Summary:
we should specify the `thread_count` to be the same number of duthost so that they're all config_reload in concurrent.

fix: add concurrent run for config_reload pc_test_lag

---

tests/show_techsupport/test_auto_techsupport.py

This PR mitigates sonic-buildimage issue [20950](https://github.com/sonic-net/sonic-buildimage/issues/20950)
Summary:
The `show_techsupport/test_auto_techsupport.py::TestAutoTechSupport::test_max_limit[core]` test creates huge core files. 
When `/tmp` is on tmpfs and available memory is low (as is often the case with KVMs), it crashes the device. This leads to a test failure with following signature:
```
27/11/2024 06:24:39 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 513, in __call__
return self._hookexec(self.name, …
```

Skip test_max_limit[core] test for images where "/tmp" is on tmpfs

---

tests/bgp/test_bgp_queue.py

Summary:
- In addition to skipping internal neighbors belong to peer-group "_INTERNAL_PEER_V4_", "_INTERNAL_PEER_V6_" by #14310, skip VOQ_CHASSIS peer group internal neighbors as well for testing _test_bgp_queue_
- This change can be **removed** once BRCM fixes iBGP traffic over queue 7 and as per discussion it would be available in 202411.
- '_test_bgp_queue_' tests fail for VOQ-CHASSIS, when the interface selected is 'Ethernet-IB0'.
- In addition to the current internal peer group, add 'VOQ_CHASSIS' peer groups as well for skipping internal neighbors as part of the test.
- Ran '_test_bgp_queue_' tests on T2 VOQ-Chassis and made sure the expected tests are passing.

[VOQ-Chassis] bgp-queue: skip internal nbrs for voq-chassis

---

tests/snmp/test_snmp_default_route.py
tests/snmp/test_snmp_queue_counters.py

Summary:
- This PR fixes test issue introduced as part of #[3537](https://github.com/sonic-net/sonic-utilities/pull/3537) for _test_snmp_default_route_ test, and
- General fix for _test_snmp_queue_counters_ test teardown.
- After PR #[3537](https://github.com/sonic-net/sonic-utilities/pull/3537) introduction, CLI command output for '_show ip route 0.0.0.0/0_' has been changed and a new word '_recursive_' gets added. Hence sonic-mgmt needs to be modified to support this new change. For example,  "_* 11.0.0.145 recursive via iBGP_"
- During teardown of '_test_snmp_queue_counters_' test, sometimes we see the following error while recopying the _config_db_ json file for the duthost.
```
E           tests.common.errors.RunAnsibleModuleFail: run module copy failed, Ansible …
```

Snmp fixes - test_snmp_default_route and test_snmp_queue_counters

---

tests/bfd/bfd_helpers.py
tests/bfd/conftest.py
tests/bfd/test_bfd_traffic.py

Use upstream and downstream LCs for BFD traffic test so it can cover the "port channel down but BFD not down" issue.
Summary:
Fixes # (issue) Microsoft ADO 30112186
In `bfd/test_bfd_traffic.py`, we want to pick 2 LCs, where one connected to T1 (downstream LC) and other one connected to T3 (upstream LC), because if we pick only 1 LC or pick 2 LCs but both are downstream LCs (or upstream LCs), we will not cover the issue of "port channel down but BFD not down". 
Randomly pick one upstream LC and one downstream LC.
I ran the updated code and can confirm that it works as expected.

refactor: use separate LCs for BFD traffic test

---

tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_runtime_traffic_helper.py

Summary:
https://migsonic.atlassian.net/browse/MIGSMSFT-765
https://migsonic.atlassian.net/browse/MIGSMSFT-778
Fixed udp ports selection, make test result stable.
Remove random.
Verified it on T2 ixia testbed.
```
=============================================================== PASSES ================================================================
_________________________________________ test_m2o_fluctuating_lossless[multidut_port_info0] __________________________________________
----------------------- generated xml file: /run_logs/ixia/18470/2024-11-27-01-04-55/tr_2024-11-27-01-04-55.xml -----------------------
------------------------------------------------------- live log sessionfinish …
```

MIGSMSFT-765 & MIGSMSFT-778 Sequential udp ports for different priorities

---

tests/bgp/test_4-byte_asn_community.py

Summary:
-  This PR fixes '_test_4_byte_asn_community_' test for sonic neighbors' case.
-  The above test fails when asserting '_neighbor_4byte_asn_' variable for '_show ipv6 neighbors _xxxxx_ routes_' command output.
- Test '_test_4_byte_asn_community_' fails for sonic neighbors' case when asserting '_neighbor_4byte_asn_' variable for '_show ipv6 neighbors _xxxxx_ routes_' command output with the following error.
```python
File "/data/tests/bgp/test_4-byte_asn_community.py", line 500, in run_bgp_4_byte_asn_community_sonic
assert str(neighbor_4byte_asn) in str(output.split('\n')[9].split()[5])
IndexError: list index out of range
``` 
- Assert neighbor_4byte_asn on the line numbers 9 or 10 from the output of '_show ipv6 neighbors xxxxx routes_' command.
- Because sometimes …

Fix - bgp-asn-community test for sonic nbrs

---

tests/common/snappi_tests/traffic_generation.py

Summary:
Issue #15799 
Made code changes
Verified on a Ixia run
```
------------------------------------------------------------------------------------------------------------------------------------ live log sessionfinish -------------------------------------------------------------------------------------------------------------------------------------
22:33:44 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs
==================================================================================================================================== short test summary info ====================================================================================================================================
PASSED …
```

TypeError in test_multidut_pfc_pause_lossy_with_snappi.py

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

As part of testgap task, confirmed and verified test_reload_config.py::test_reload_configuration_checks is working on Cisco8000 device with 202405 release.
Summary:
As part of testgap task, confirmed and verified test_reload_config.py::test_reload_configuration_checks is working on Cisco8000 device with 202405 release.
Original PR: https://github.com/sonic-net/sonic-mgmt/pull/15139
verified on cisco t2-8800 device
platform_tests/test_reload_config.py::test_reload_configuration[----] PASSED [ 16%]
platform_tests/test_reload_config.py::test_reload_configuration_checks[----] PASSED [ 33%]
platform_tests/test_reload_config.py::test_reload_configuration[----] PASSED [ 50%]
platform_tests/test_reload_config.py::test_reload_configuration_checks[----] PASSED [ 66%] …

[manual] [PR:15139] enable test_reload_config in T2

---

tests/platform_tests/api/test_chassis_fans.py
tests/platform_tests/api/test_fan_drawer_fans.py
tests/platform_tests/api/test_module.py
tests/platform_tests/api/test_sfp.py
tests/platform_tests/api/test_thermal.py

In PR #15605, the `platform_api_conn` fixture was relocated to a common location. However, some imports were overlooked in the scripts within the tests/platform_tests/api folder, leading to test failures. This PR addresses the issue by adding the missing imports to resolve the errors.
Summary:
In PR #15605, the `platform_api_conn` fixture was relocated to a common location. However, some imports were overlooked in the scripts within the tests/platform_tests/api folder, leading to test failures. This PR addresses the issue by adding the missing imports to resolve the errors.
This PR addresses the issue by adding the missing imports to resolve the errors.

[Bugfix] Fix missing imports for `platform_api_conn` in `tests/platform_tests/api`

---

ansible/upgrade_sonic.yml

Summary:
For devices with limit disk space, 1600 size is not available with 202405 images, it would cause install image failure.
Add required_space as 1500 for slim image, 2018, 2019 image, set default value 1600 for others.
Local verify

add required_space for upgrade image

---

tests/common/helpers/pfcwd_helper.py
tests/pfcwd/test_pfcwd_function.py

Summary:
- Revise Cisco-8000's current method of sending background traffic from an extra "verify_tx_egress" call to use the pre-existing background traffic support. The verify tx egress operation could fail if some packets leakout due to slow pfc_gen.py frames from fanout. 
- Remove the test failure catcher, as it simply rethrows an exception that is more difficult to debug. Using a simple "try-finally" pattern allows the "finally" clause to always execute even with an exception, but also continues to throw the exception without catching it, resulting in the required test failure in that case. 
#14711 is not in 202405, but is requested for the branch. Without that PR in 202405, the double commit of this PR will have a either have a merge conflict or possibly fail if it happens to not …

Cisco-8000 test pfcwd function background traffic revision

---

tests/dualtor/test_switchover_failure.py

Summary:
Fixes [#328](https://github.com/aristanetworks/sonic-qual.msft/issues/328)
dualtor/test_switchover_failure.py failure for active-active dualtor.
```
if (res.is_failed or 'exception' in res) and not module_ignore_errors:
&gt;           raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
E           tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =&gt;
E           rc = 1
E           cmd = config mux mode standby Ethernet0
E           start = 2024-11-16 00:39:44.410652
E           end = 2024-11-16 00:39:45.124954
E           delta = 0:00:00.714302
E           msg = non-zero return code
E           invocation = {'module_args': {'_raw_params': 'config mux mode standby …
```

Fix dualtor/test_switchover_failure.py

---

tests/common/platform/device_utils.py

Print core dump file list during health check failure.
https://github.com/sonic-net/sonic-mgmt/pull/15107 had been merged into 202405
Summary:
No core dump list printed during case failure
Print core dump files if health check failed

Update device_utils.py to print core dump files

---

ansible/roles/test/files/ptftests/py3/sflow_test.py

Summary: Wait for process completion for sflow script
Fixes #
Sflow reboot testcase `pytest sflow/test_sflow.py::TestReboot` might fail due to sflow packets are not received in active collector
When open the /tmp/collector0 and /tmp/collector1 files, we can see sflow packets recorded by sflow tool
```
{"datagramSourceIP":"20.1.1.1","datagramSize":"448","unixSecondsUTC":"1732083938","localtime":"2024-11-20T06:25:38+0000","datagramVersion":"5","agentSubId":"100000","agent":"20.1.1.1","packetSequenceNo":"8","sysUpTime":"50697","samplesInPacket":"3","samples":[{"sampleType_tag":"0:2","sampleType":"COUNTERSSAMPLE","sampleSequenceNo":"1","sourceId":"0:205","elements":[{"counterBlock_tag":"0:1005","ifName":"Ethernet204"},{"counterBlock_tag":"0:1","ifIndex":"205","networkType":"6","ifSpeed":"20000 …
```

Wait for process completion for sflow script

---

tests/conftest.py

When pytest command marker had been set as bsl, then skip the golden configuration restore process in order to keep the l2 mode configuration unchanged
Summary:
Golden configuration restore process would remove the L2 mode configuration 
Keep the L2 mode configuration
Add golden configuration restore skip condition for bsl

Update golden config restore skip condition for BSL test

---

tests/vlan/test_vlan_ping.py

Summary: Add populate_mac_table in test_vlan_ping case
Fixes # Need populate_mac_table before run test_vlan_ping case, otherwise the case may fail due to old mac table info

Add populate_mac_table in test_vlan_ping case

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Update generic hash skip list for ingress port hash due to hw limitation
Summary:
Update generic hash skip list for ingress port hash due to hw limitation
Add skip list for ingress port hash

Update generic hash skip list for ingress port

---

tests/common/plugins/conditional_mark/__init__.py
tests/common/utilities.py
tests/conftest.py

Summary:
This PR is to add the support for skipping tests on the smartswitch DPU.
With the change in PR(https://github.com/sonic-net/sonic-mgmt/pull/15695), we are able to run a test directly on a smartswitch DPU. But we need to also be able to skip tests on a DPU based on the conditional marks.
Add support for skipping tests on the smartswitch DPU
There are 2 main changes in this PR:
1. When getting the basic facts of the DUT in the conditional mark plugin, use the dut name in the --host-pattern parameter instead of the first dut defined in the testbed file. By this change, we will be able to get the dpu facts when running the test only on the dpu.
2. Update the cache logic to save the cache with the dut name. So that in a same regression run, we are able to save and get cache for both …

Add support for skipping tests on the smartswitch DPU

---

tests/vlan/test_vlan_ping.py

The vlan_ping_setup method was affected by [PR #14225](https://github.com/sonic-net/sonic-mgmt/pull/14225) 
The port index list of vm_host_info would be a null list 
In the end, there is no received ptf port generated, it would lead to case failure
Change-Id: I417229fb411120edb2372933106e87ab96280d0b
Summary:
The port index list of vm_host_info would be a null list 
The port index list of vm_host_info would be a null list 
Update the fixture vlan_ping_setup

Update vlan_ping_setup method to get correct vm_host_info with correct port index list

---

ansible/roles/test/files/ptftests/py3/advanced-reboot.py

1. fix the dead loop in the test
2. Increase the limit of the flooded pkt count from 150 to 250 for the fast-reboot
3. Add more logs in the code.
Summary:
Run  the dast-reboot and warm-reboot, it could pass

Fix some issue in the advanced reboot

---

tests/common/reboot.py

Add warm reboot finalizer state check for fast reboot
Summary:
Case bgp.test_bgp_slb#test_bgp_slb_neighbor_persistence_across_advanced_reboot would fail from time to time
According to the https://github.com/sonic-net/SONiC/blob/master/doc/fast-reboot/Fast-reboot_Flow_Improvements_HLD.md, the warm reboot finalizer had started to support check for fast-reboot. So I added the state check for fast-reboot.

Add warm reboot finalizer state check for fast reboot

---

tests/crm/test_crm.py

Print next hop group number
Summary:
Improve the debugbility of this test
Print next hop group number directly

Enhance crm test to print next hop group number directly

---

tests/qos/qos_sai_base.py

Add t0-56 topology to the qos test support list
Summary:
Add t0-56 topology to the qos test support list
Add t0-56 topology to the qos test support list

Add t0-56 topology to the qos test support list

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skip vlan ping test on dualtor active active topology for github issue #15061
Summary:
Skip vlan ping test on dualtor-aa setup
Add a skip condition

Skip vlan ping test on dualtor active active topology due to github issue #15061

---

tests/platform_tests/test_platform_info.py

Summary: ignore pmon#thermalctld error in test_turn_on_off_psu_and_check_psustatus, since the error is expected due to turning off psu

extend ignored logs for test_turn_on_off_psu_and_check_psustatus

---

tests/qos/test_buffer.py

Previously, when enabling SHP there is no checker even if  the accumulative headroom(shared headroom) of a port exceeds the maximum threshold. Currently, we have added the checker for mellanox device, so we update the existing case test_exceeding_headroom  to cover the scenarios enabling SHP.
The relevant PR: https://github.com/sonic-net/sonic-swss/pull/3272
Summary:
Add new case to cover new scenarios enabling SHP
Update test_exceeding_headroom
Run test_exceeding_headroom on Mellanox device
Mellanox
Any

[Mellanox] Update test_exceeding_headroom due to adding checker when enabling SHP

---

tests/clock/conftest.py
tests/clock/test_clock.py

use ntpdate instead of a temporary adding of NTP server check NTP server reachability on the setup stage
Change-Id: I78ab7bab5609ae0ecad31887225abe152f7a39e8
Summary:
The motivation is to avoid waiting for the next poll and prevent the situation when the polling interval changes after adding the NTP server
use ntpdate instead of a temporary adding of NTP server check NTP server reachability on the setup stage
Ran test_show_clock/test_config_clock_timezone/test_config_clock_date and verified datetime was restored after tests finished

update datetime restoration in clock tests

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
tests/tacacs/test_accounting.py

Summary: increase timeout value for accounting test and ignore loganalyzer

[tacacs] increase timeout value for accounting test and ignore loganalyzer

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

In Cisco platforms these error messages should be warning instead of error messages. We will be making the change but in the meanwhile, I am adding an ignore in log analyzer ignore files to avoid causing testcase failures
2024 Nov  4 10:29:37.967901 sfd-lt2-lc0 ERR syncd0#syncd: 04-11-2024 10:29:37.967 -E-HLD-0- Trap 'ETHERNET_EGRESS_EVPN_DF_BLOCK' is not supported
2024 Nov  4 10:29:37.972258 sfd-lt2-lc0 ERR syncd0#syncd: 04-11-2024 10:29:37.972 -E-HLD-0- Trap 'ETHERNET_EGRESS_EVPN_ESI_ETREE_DROP' is not supported
2024 Nov  4 10:29:37.994537 sfd-lt2-lc0 ERR syncd0#syncd: 04-11-2024 10:29:37.994 -E-HLD-0- Trap 'ETHERNET_INGRESS_EVPN_ETREE_DROP' is not supported
2024 Nov  4 10:29:38.022655 sfd-lt2-lc0 ERR syncd0#syncd: 04-11-2024 10:29:38.022 -E-HLD-0- Trap 'ETHERNET_ETM_DSP_MISMATCH' is …

Ignore trap messages that should be warnings instead of error messages

---

ansible/roles/test/files/ptftests/py3/hash_test.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/fib/test_fib.py

Add ECMP test case to validate hash_keys for Vxlan and NVGRE packet types.
Summary:
https://github.com/sonic-net/sonic-mgmt/issues/8166
To verify ECMP balancing based on different packet fields for Vxlan and Nvgre.
Validated the tests on Mellanox, Cisco and Broadcom SKUs.
All

[ECMP hash] Tests for Vxlan and Nvgre packets using different packet fields

---

tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_basic_helper.py

Summary:
https://migsonic.atlassian.net/browse/MIGSMSFT-767 [T2 IXIA] failures in test_pfcwd_basic_single_lossless_prio_reboot: Loss rate of Data Flow 2 (0.1140553129761207) should be in [0, 0]
Fix the failures of test_multidut_pfcwd_basic_with_snappi.py
Data flow 2 dropped packets. 
2 flows in default-voq used single voq, which caused tail drop before pfc pause was triggered. Decrease flow number from 2 to 1. Since backplane port's bandwidth is 200G, also decrease the traffic rate from 99.98% to 49.99%
Verified on T2 ixia testbed.
```
----------------------- generated xml file: /run_logs/ixia/18470/2024-11-28-06-00-02/tr_2024-11-28-06-00-02.xml ----------------------- …
```

MIGSMSFT-767 test_pfcwd_basic_single_lossless_prio_reboot: Loss rate of Data Flow 2 (0.1140553129761207) should be in [0, 0]

---

tests/syslog/test_logrotate.py

Summary:
This PR is to handle `KeyError` in `get_pending_entries`.
The error message is
```
File "/var/src/sonic-mgmt_vms21-t0-2700_646f1402735219c3e5444094/tests/syslog/test_logrotate.py", line 243, in get_pending_entries
pending_entries.remove(entry)
KeyError: '_ROUTE_TABLE:192.220.128.128/25'
, error:'_ROUTE_TABLE:192.220.128.128/25'
```
Before this change, only `ValueError` was handled.
This PR is to handle `KeyError` in `get_pending_entries`.
Catch `KeyError` and ignore it.
```
collected 5 items                                                                                                                                                                                     
syslog/test_logrotate.py::test_orchagent_logrotate[bjw2-can-4600c-6 …
```

Handle KeyError in get_pending_entries

---

tests/hash/test_generic_hash.py

Bug fix for https://github.com/sonic-net/sonic-mgmt/issues/15689
Disable LogAnalyzer for reboot test
Summary:
https://github.com/sonic-net/sonic-mgmt/issues/15689
Bug fix for https://github.com/sonic-net/sonic-mgmt/issues/15689
Disable LogAnalyzer for reboot test

Disable loganalyzer for reboot test in generic hash script

---

tests/bgp/test_bgp_bbr.py

Summary:
This PR is to disable LogAnalyzer in `test_bbr_status_consistent_after_reload`.
Due to the reload operation in `test_bbr_status_consistent_after_reload`, some error log shows up and causes the test to error.
These error logs can be ignored safely.
This PR is to disable LogAnalyzer in `test_bbr_status_consistent_after_reload`.
Set pytest marker for this single test.
```
collected 2 items                                                                                                                                                                                     
bgp/test_bgp_bbr.py::test_bbr_status_consistent_after_reload[enabled]  ^HPASSED …
```

Disable LogAnalyzer in test_bbr_status_consistent_after_reload

---

tests/common/devices/sonic.py

Summary:
This is for the behavior change caused by PR(https://github.com/sonic-net/sonic-buildimage/pull/18907)
The new daemon "delay" is a short life daemon which should be added to the exemptions list.
See the description
See the description
Run tests which uses method get_pmon_daemon_status, all passed.

Update get_pmon_daemon_states for PR#18907

---

tests/pc/test_po_update.py

Summary:
The Test Cases focuses on the below PR Changes of lagid allocation to portchannel and new SYSTEM_LAG_IDS_FREE_LIST 
[[lag_id] Add lagid to free_list when LC absent for 30 minutes by mlok-nokia · Pull Request #542 · sonic-net/sonic-platform-daemons (github.com)](https://github.com/sonic-net/sonic-platform-daemons/pull/542)
[[Chassis][LAG_ID] Address the same lagid been used in two different LCs issue by mlok-nokia · Pull Request #3303 · sonic-net/sonic-swss (github.com)](https://github.com/sonic-net/sonic-swss/pull/3303)
[[database-chassis][lagid] Initialize SYSTEM_LAG_IDS_FREE_LIST in CHASSIS_APP_DB by mlok-nokia · Pull Request #20369 · sonic-net/sonic-buildimage (github.com)](https://github.com/sonic-net/sonic-buildimage/pull/20369)
This PR is dependent on the above mentioned …

New TC for PC Test on higher lag ids

---

tests/generic_config_updater/test_ntp.py

ADO: 30406532
Summary: Extend ntp service check time since some hwsku take more than 10 sec to activate ntp
Fix nightly ntp test failure issue due to not long enough check time
Extend the timeout to 60 secs
Manually test

[GCU] Extend ntp check time to 60secs

---

tests/snappi_tests/multidut/pfc/files/multidut_helper.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py

Halving the traffic on test and background flow for compatibility between 400g and 200g for lossy
Summary:
Fixes # (issue) 30112807

fix: half all traffic for lossy

---

tests/fdb/test_fdb_mac_learning.py

Summary:
During fdb/test_fdb_mac_learning.py::testARPCompleted, syslog will output the following error log:
```
ERR swss#orchagent: :- update: Failed to get port by bridge port ID 0x3a00000000155c.
```
This is not an actual error, but a minor race condition - it is caused by Broadcom SAI sending a FDB AGED event after the FDB entry has been flushed, causing orchagent to check on a bridge port that does not exist. Fix by extending log ignore to the test.
Same issue as the one reoslved in
https://github.com/sonic-net/sonic-mgmt/pull/9818
Separate PR created for 202405: https://github.com/sonic-net/sonic-mgmt/pull/15798
Test no longer fails with log analyzer on Broadcom platforms.
Broadcom platforms only.

Add log ignore to account for FDB flush race condition

---

tests/route/test_route_flap.py

Summary: Changes to support DUT with  Multi-ASIC 
Packets send to DUT should have ASIC MAC has DMAC instead of DUT MAC. Fixed the same
pass all sonic mgmt tests on multi-asic systems
Ran scripts with multi-asic system as DUT and recorded the list
Ran the test_stress_arp.py script with fix and test-case passed
if all ASIC in platform share the same MAC as DUT MAC this fix is not needed

Use asichost mac when DUT is multi-asic system

---

tests/acl/test_acl.py
tests/common/utilities.py
tests/qos/tunnel_qos_remap_base.py

In PR #15619, a cross-feature dependency was introduced in `tests/acl/test_acl.py` due to the usage of the `get_iface_ip` function. To address this issue and streamline the code structure, we have refactored the function and moved it to a common location.
Summary:
In PR #15619, a cross-feature dependency was introduced in `tests/acl/test_acl.py` due to the usage of the `get_iface_ip` function. To address this issue and streamline the code structure, we have refactored the function and moved it to a common location.
To address this issue and streamline the code structure, we have refactored the function and moved it to a common location.

Refactor function `get_iface_ip` to common location

---

ansible/roles/vm_set/tasks/start_tacacs_daily_daemon.yml

Summary:
The code for setting up TACACS on PTF host has an issue of always using default password.
The original intention is to get an alternate password. If the alternate password cannot be found, then use default password.
However, the step of using default password always override the alternate password.
This change added code to store  the alternate password in variable `tacacs_user_passwd`. Then the override logic won't happen if alternate password is found.

Fix PTF TACACS always use default password issue

---

tests/vlan/test_autostate_disabled.py

Summary:
After PR 3370 for sonic-swss, a VLAN interface will not go down when all of its member ports are down. This causes `test_autostate_disabled` to fail when we only have one VLAN. Therefore, we are temporarily skipping this test so that the sonic-buildimage's swss submodule can be updated.
sonic-buildimage's swss submodule cannot be updated because `test_autostate_disabled` fails.
Temporarily skipped the test.

Temporarily skipping 'test_autostate_disabled' so that the sonic-swss submodule can be updated

---

tests/tacacs/test_ro_disk.py

Improve test_ro_disk intermittent failure issue.
test_ro_disk intermittent failed because log file does not exist or open by other process.
- Microsoft ADO: 30373889
Ignore failed command by failure message.
Improve test_ro_disk intermittent failure issue.

Improve test_ro_disk intermittent failure issue

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
Some dataplane test scripts have been added to PR test and put into optional onboarding job to test case performance, I calculated the success rate of test scripts in recent 3 days, I think I can move high success rate test scripts to t0/t1 job now
TestbedName | FilePath | TestCase | RunDate | SuccessCount | FailureCount | TotalTests | SuccessRate
-- | -- | -- | -- | -- | -- | -- | --
vms-kvm-t1-lag | ipfwd/test_nhop_group.py | test_nhop_group_member_count | 2024-11-22 00:00:00.0000000 | 17 | 0 | 17 | 1
vms-kvm-t1-lag | ipfwd/test_nhop_group.py | test_nhop_group_member_order_capability[vlab-03-None] | 2024-11-22 00:00:00.0000000 | 17 | 0 | 17 | 1
vms-kvm-t1-lag | ipfwd/test_nhop_group.py | test_nhop_group_interface_flap[vlab-03-None] | 2024-11-22 00:00:00.0000000 …

Move stable onboarding t1 tests to PR test job

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py

Summary:
Add the necessary support files for the Arista-7060X6-64DE-O128S2 and Arista-7060X6-64PE-C224O8 hwskus to sonic-mgmt.
To support sonic-mgmt testing for the Arista-7060X6-64DE-O128S2 and Arista-7060X6-64PE-C224O8 hwskus.
Added the necessary ansible variable/port util definitions for these hwskus.
Verified the testbed can be successfully configured and the sonic-mgmt suite of tests can be run against these hwskus.
This targets the Arista-7060X6-64DE-O128S2 and Arista-7060X6-64PE-C224O8 hwskus.

Add Arista-7060X6-64DE-O128S2 and Arista-7060X6-64PE-C224O8 HWSKUs

---

setup-container.sh

Cherry #15758
Summary:
Adds a check to enhance clarity of error thrown when a container created with a name that is of a length greater than 64 characters will fail to start after creation:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: sethostname: invalid argument: unknown.
```
This is due to the internal hostname of the container being set to the container's name, which has an additional 64 character limit, causing the container to fail to start consistently.
To enhance error messaging for this particular edge case, as it was previously difficult to discern why the container would be created successfully, but then …

[PR:15758] Cherry - Add container length check

---

tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py

The pfc lossless test assume pfcwd is disabled. But this test: test_pfc_pause_multi_lossless_prio is not provided the fixture: "disable_pfcwd" which is used by all other tests in the same script. This causes this test to fail since the pfcwd is triggered and packets are dropped.
this test is failing with this error:
```Failed: Total TX bytes   841563217920 should be smaller than DUT buffer size 67108864```
Disable pfcwd during the test using the fixture, that is already used by other tests in the same script.
Ran it on my TB:
@sdszhang , @auspham : FYI.

Disable pfcwd for pfc_lossless.

---

tests/common/snappi_tests/qos_fixtures.py

Summary:
https://miggbo.atlassian.net/browse/MIGSOFTWAR-19536
2024 Nov 25 20:11:42.889000 yy39top-lc4 ERR swss0#orchagent: :- createEntry: Invalid port interface Ethernet-BP384
2024 Nov 25 20:11:42.889000 yy39top-lc4 ERR swss0#orchagent: :- doTask: Failed to process PFC watchdog SET task, invalid entry
Fix issue of "createEntry: Invalid port interface" when running script snappi_tests/multidut/ecn/test_multidut_ecn_marking_with_snappi.py.
Fix the sequence of config files when doing config load.
Verified the case on T2 ixia testbed.
```
----------------------- generated xml file: /run_logs/ixia/18470/2024-12-04-00-38-12/tr_2024-12-04-00-38-12.xml ----------------------- …
```

Fix issue "createEntry: Invalid port interface"

---

ansible/devutil/devices/sonic.py

Summary:
Fixes MSFT PBI#28727277
During the code logic, we install the image on all the devices at the same time.
Then reboot the RP and wait, then reboot the LC and wait.
But on chassis, after RP rebooted, the LC rebooted automatically.
Hence remove the useless LC reboot to save the time.
About the production image upgrade, we will have upgrade path test covering it.
Remove useless LC reboot.
Tested on physical chassis and it works well.

[Chassis] Remove the useless LC reboot during upgrade image

---

ansible/roles/test/files/ptftests/py3/advanced-reboot.py
tests/arp/files/ferret.py
tests/common/fixtures/advanced_reboot.py

Summary:
During an upgrade, test to see if the VLAN gateway can be resolved with an ARP request. When CPA is enabled, we expect the VLAN gateway to be always resolvable (even when control plane of the device is down). This is done through the use of a Ferret server running on the PTF container.
Add a basic check for the functionality of that Ferret server by crafting and sending ARP requests, and report the number of ARP responses received. As of right now, this doesn't affect the final result of the warm/fast upgrade test; that will be done later.
Also mark the advanced-reboot tests as functional on KVM. Without this, the warm upgrade test will not run on PR checkers.

[advanced-reboot] Test VLAN gateway address resolvability during upgrade

---

tests/qos/qos_sai_base.py

Summary:
change swapsyncd and disable_ipv6 to module level. 
Running time on T2 reduced by around 140 minutes (from 685.08 minutes to 543.95 minutes).
Existing code will do swapSyncd for selected dut only in each iteration.  In a T2 full test, it was around 8 LC which needs to do swapsyncd, including setup and teardown for each iteration.
| select_src_dst_dut_and_asic |  selected DUT to do swapsyncd (Existing) |
| --- | --- |
| single_asic | one downstream  LC |
| single_dut_multi_asic |  one downstream LC |
| multi_dut_longlink_to_shortlink |  one upstream LC, one downstream LC |
| multi_dut_shortlink_to_shortlink |  two downstream LC |
| multi_dut_shortlink_to_longlink |  one upstream LC, one downstream LC  |
After the fix, swapsyncd will be done for all LCs at the beginning of the …

change swapsyncd to module level.

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Ignore auditd error in loganalyzer

---

tests/snappi_tests/multidut/ecn/files/multidut_helper.py
tests/snappi_tests/multidut/ecn/test_multidut_ecn_marking_with_snappi.py

Summary:
Make the test case multi Topo capable.
Add ecn marking ratio check for flow percent where both
lossless TC are >= 50 to have equal marking
Ixia testcase enhancement
On Ixia connected DUT

ECN  IXIA test for verifying equal marking due to traffic causing congestion

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
In https://github.com/sonic-net/sonic-utilities/pull/3102, the feature comparing yang model with configDB was added to sonic-utilities submodule, but feature subnet decap haven't been added to yang model, so the PR test advancing sonic-utilities to buildimage would fail in subnet decap test.
Created issue https://github.com/sonic-net/sonic-buildimage/issues/21090 and temporary skip subnet decap test until issue resolved

Temporary skip subnet decap test with issue since feature haven't been added to yang model

---

tests/dualtor/test_orch_stress.py

Summary:
`dualtor/test_orch_stress.py::test_flap_neighbor_entry_active` test would compare crm facts which do not completely supported in KVM testbed
Skip crm facts check in `dualtor/test_orch_stress.py::test_flap_neighbor_entry_active` test

Skip crm check for KVM testbed in `dualtor/test_orch_stress.py` test

---

tests/pfcwd/files/pfcwd_helper.py
tests/pfcwd/test_pfcwd_cli.py
tests/pfcwd/test_pfcwd_function.py

Summary:
Fixes # (issue) #15850 
Cherry-pick #14711 to 202405
Failure is introduced from https://github.com/sonic-net/sonic-mgmt/pull/14580/files
Currently blocking #15841
https://github.com/sonic-net/sonic-mgmt/issues/11169
Add a new test case to cover "pfcwd show stats" cmd
send_tx_egress and send_rx_ingress
execute CMD 'show pfcwd stat' and ensure the output is expected
https://elastictest.org/scheduler/testplan/66f268ae4216a91fd43d97b6
https://elastictest.org/scheduler/testplan/66f268880369ccd340b3ea60

Fix #14711 cherry pick from #15850

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Since the test scripts for `qos` and `pfcwd` are not yet included in PR testing, we have temporarily applied conditional marks to skip them. Once these scripts are integrated into PR testing, this PR can be reverted.
Summary:
Since the test scripts for `qos` and `pfcwd` are not yet included in PR testing, we have temporarily applied conditional marks to skip them. Once these scripts are integrated into PR testing, this PR can be reverted.

Temporarily skip qos and pfcwd test scripts in PR testing

---

ansible/roles/test/files/ptftests/py3/hash_test.py

When `255` is selected as the ip-protocol(v4) or next-header(v6) field I see the TCP src-port and TCP dst-port are removed from the packet causing the `fib/test_fib.py` to fail
RX packet:
```
16:39:46.124644 52:67:2c:8e:a0:09 (oui Unknown) > 94:8e:d3:1f:b0:fd (oui Unknown), ethertype IPv6 (0x86dd), length 100: 20d0:a800:: > 20d0:a800:0:1::: ip-proto-255 46
0x0000:  948e d31f b0fd 5267 2c8e a009 86dd 6000
0x0010:  0000 002e ff40 20d0 a800 0000 0000 0000
0x0020:  0000 0000 0000 20d0 a800 0000 0001 0000
0x0030:  0000 0000 0000 04d2 0050 0000 0000 0000
0x0040:  0000 5002 2000 818d 0000 4444 4444 4444
0x0050:  4444 4444 4444 4444 4444 4444 4444 4444
0x0060:  4444 4444
```
TX packet:
```
16:38:00.797992 94:8e:d3:5e:af:13 (oui Unknown) > 1e:bf:59:4c:90:6f (oui Unknown), ethertype IPv6 (0x86dd), …
```

Skip ip-proto `255` in `hash_test.py`

---

tests/voq/test_voq_fabric_isolation.py

AUTO_ISOLATED is only added to the FABRIC_PORT_TABLE once the fabric port has been isolated once, so we should treat this attribute missing from this table the same as AUTO_ISOLATED=0
Summary:
Fixes #15858

Handle AUTO_ISOLATED attribute missing from table

---

tests/common/helpers/voq_lag.py
tests/pc/test_po_voq.py

Summary:
Fixes #14984 and cleanup similar tests in file
I suggest looking at individual commits to have an easier time navigating changes
Test gap for DB states across local & remote linecards updating for PO member state changes
Added 2 testcases, one where PO went down, one where individual member went down
Tested on T2 testbed
T2 VoQ only
T2 VoQ only

[New testcase] PO & PO Member flap status sync across all DBs scenario

---

tests/test_parallel_modes.json

Disable parallel run for the `override_config_table/test_override_config_table_masic.py` test as it's not compatible with parallel run anymore. We will refactor this test to re-enable parallel run for it later.
Summary:
Fixes # (issue) Microsoft ADO 30459127
The `override_config_table/test_override_config_table_masic.py` test will not be able run in parallel after #14713 anymore because it only enumerates the upstream LC now, which is not compatible with the current parallel run implementation.

fix: temporarily disable parallel run for config test

---

tests/iface_namingmode/test_iface_namingmode.py

Some of the Line cards does not support speed change during runtime. PR https://github.com/sonic-net/sonic-mgmt/pull/15761 took care of it in the testcase but there is a blanket speed change in the teardown which causes test errors. This PR checks that capability both in testcase and teardown fixture.
Summary:
Speed change in teardown is causing testcase failures for LCs that do not support runtime speed change
Check and skip for unsupported LCs
Verified it on T2 setup
Yes

Some of the Line cards does not support speed change during runtime - check in teardown

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Testcase `dualtor_mgmt/test_toggle_mux.py` has low passing rate in KVM, which may block some PR tests.
Error message:
```
>           pytest.fail('Toggle mux from simulator test failed')
E           Failed: Toggle mux from simulator test failed
check_result = False
duthosts   = [<MultiAsicSonicHost vlab-05>, <MultiAsicSonicHost vlab-06>]
get_mux_status = <function get_mux_status.<locals>._get_mux_status at 0x7baf5e6b0550>
simulator_muxstatus = {'mbr-vms6-4-0': {'active_port': 'vlab-06-1', 'active_side': 'lower_tor', 'bridge': 'mbr-vms6-4-0', 'flap_counter': 1,...11': {'active_port': 'vlab-06-12', 'active_side': 'lower_tor', 'bridge': 'mbr-vms6-4-11', 'flap_counter': 3, ...}, ...}
```
Temporary skip with issue https://github.com/sonic-net/sonic-mgmt/issues/15958 in …

Temporary skip `dualtor_mgmt/test_toggle_mux.py` for low passing rate in KVM

---

tests/dhcp_relay/conftest.py

Summary:
Error log for default route incorrect is ambiguous
Update the log
Run test

[dhcp_relay] Update error log for dhcp server route incorrect

---

ansible/library/generate_golden_config_db.py

Summary:
default_pfcwd_status should be `disable` for m0 and mx
In golden config_db, disable pfcwd for m0 and mx
Deploy topo

[deploy-mg] Disable default_pfcwd_status for m0/mx

---

tests/common/fixtures/advanced_reboot.py
tests/common/helpers/upgrade_helpers.py
tests/common/platform/args/advanced_reboot_args.py
tests/common/platform/device_utils.py
tests/ptf_runner.py
tests/upgrade_path/conftest.py
tests/upgrade_path/test_multi_hop_upgrade_path.py
tests/upgrade_path/test_upgrade_path.py
tests/upgrade_path/utilities.py

Added a new advanced_reboot test case that verifies consecutive warm-upgrades. The upgrade path is specified through the `--multi_hop_upgrade_path` pytest option i.e. `--multi_hop_upgrade_path http://builds.test/sonic-aboot-broadcom-20181130.105.swi,http://builds.test/sonic-aboot-broadcom-20201231.97.swi,http://builds.test/sonic-aboot-broadcom-20230531.22.swi` which will cold reboot into the base image 20181130 then warm-reboot into 20201231 and finally, warm-reboot into 20230531.
To make the test easy to understand, the style, assertions, etc was kept consistent with the existing A->B test in `tests/upgrade_path/test_upgrade_path.py::test_upgrade_path`. Points to note are as follows:
- There are 3 lifecycle hooks:
- `base_image_setup` - run only once which is used to cold-boot the device …

Added multi-hop SONiC upgrade path test case

---

.azure-pipelines/pr_test_scripts.yaml
tests/gnmi/test_gnmi.py

Fix test_gnmi_authorize_failed_with_invalid_cname backport issue because gnmi_set method changed 202311.
test_gnmi_authorize_failed_with_invalid_cname  test case failed on 202311 because gnmi_set method on 202311 have different parameter and behavior.
The original cherry-pick PR to 202311 not found this issue: https://github.com/sonic-net/sonic-mgmt/pull/15678 , because he GNMI test no run enable on 202311 branch sonic-mgmt repo merge validation: https://github.com/sonic-net/sonic-mgmt/blob/202311/.azure-pipelines/pr_test_scripts.yaml
- Microsoft ADO: 30343954
Change code to pass correct parameter.
Fix test_gnmi_authorize_failed_with_invalid_cname backport issue because gnmi_set method changed on 202311.

[202311] Fix test_gnmi_authorize_failed_with_invalid_cname backport issue because gnmi_set method changed on 202311.

---

tests/common/snappi_tests/multi_dut_params.py
tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_downlink_port_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_downlink_process_crash.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_tsa.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_multi_po_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_member_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_process_crash.py
tests/snappi_tests/variables.py

Summary:
Code changes to support multiple platforms for T2 Snappi Based route convergence tests
Currently the Snappi based T2 route convergence tests can only be used with single set of duts (hardcoded in variables.py). 
Enhanced the testcases/Infra to provide support for more than one platforms. The platform is fetched at runtime based on testbed parameters.
Fetch the platform info first by comparing the DUTs passed in testcase and duts defined in variables.py.
Use this platform info through out the tests to fetch various other parameters
Ran the T2 snappi route convergance tests
None
NA

T2 Snappi Based route convergence: Code changes to support multiple platforms

---

tests/bfd/bfd_helpers.py

Bump the BFD toggle wait timeout to 450 seconds to give BFD session enough time to go up/down.
Summary:
Fixes # (issue) Microsoft ADO 30112171
We noticed that 300 seconds is not enough for BFD session to go up/down, so Cisco suggested us to bump it to 450 seconds.

chore: bump BFD toggle wait timeout

---

tests/snappi_tests/multidut/pfc/test_lossless_response_to_external_pause_storms.py
tests/snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py
tests/snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless_lossy.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossy.py

In continuation of reducing the time to run for pfc cases, this PR refactors some testcases from pfc folder to use the new fixtures: setup_ports_and_dut and disable_pfcwd. This reduces the runtime for each of these cases by 4-5 minutes, by avoiding the final config-reload from the sanity-checker-teardown kicking in.
- to reduce the runtime of the testcases.
- Reuse the code available in fixtures instead of writing same code in multiple cases.
By removing the repeat code, and using the already established fixtures.
Ran it on my TB, all of them have passed.
```
=============================================================================================== PASSES =============================================================================================== …
```

snappi_tests/multidut: Fixturize a few cases in pfc folder.

---

tests/dut_console/test_console_baud_rate.py

Summary:
Fixes # (issue)  304717824
For devices that doesnt have console port (i.e Cisco 8800 console only exists in RP), we should skip this test for this DUT. Otherwise we are going to have `KeyError: 'ManagementIp'`
We skip if the key does not exists. If key does not exists then the graph will be empty. For example:
```
"dut-lc1-1": {},
```
verified on physical testbed

test_console_baud_rate.py skip if no console port info on dut

---

tests/platform_tests/test_reload_config.py

Summary:
Fixes # (issue) 3045798
The decision was to enable this test gap in #13476 however we mentioned that we need to increase the time.
By default, the reboot time will be decided from constant variable `reboot_ctrl_dict` which will set the `REBOOT_TYPE_COLD` = 300
https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/reboot.py#L133
For T2, this time is not sufficient enough and lead to failure. We will adjust the time accordingly.
This PR will fix that
Enable plt_reboot_ctrl_overwrite if platform is T2

Adjust t2 timing in tests/platform_tests/test_reload_config.py

---

tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py

Summary:
Fixes # (issue) 30112807
Fix the typo for asic type

test_multidut_pfc_pause_lossy_with_snappi.py fix typo

---

tests/bgp/test_bgp_queue.py
tests/common/devices/sonic_asic.py

Summary:
Fixes # (issue) 30457143
Currently this is using the old method of capturing queue counters:
```
sudo ip netns exec asic1 show queue counters Ethernet128
```
This will throw an issue with some testbed and says Ethernet128 does not exists. (haven't had chance to confirm why)
However since we have new support for -n https://github.com/sonic-net/sonic-utilities/pull/2439 we should be using this instead
Tested by running manual commands
```
admin@str3-8800-lc4-1:~$ sudo ip netns exec asic1 show queue counters Ethernet128
Port doesn't exist! Ethernet128
```
```
admin@str3-8800-lc4-1:~$ show queue counters Ethernet128 -n asic1
For namespace asic1:
Port    TxQ    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes
-----------  -----  --------------  ---------------  ----------- …
```

fix: fix port does not exist error test_bgp_queue

---

tests/snappi_tests/multidut/pfc/test_lossless_response_to_external_pause_storms.py
tests/snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py
tests/snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless_lossy.py
tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossy.py

In continuation of reducing the time to run for pfc cases, this PR refactors some testcases from pfc folder to use the new fixtures: setup_ports_and_dut and disable_pfcwd. This reduces the runtime for each of these cases by 4-5 minutes, by avoiding the final config-reload from the sanity-checker-teardown kicking in.
- to reduce the runtime of the testcases.
- Reuse the code available in fixtures instead of writing same code in multiple cases.
By removing the repeat code, and using the already established fixtures.
Ran it on my TB, all of them have passed.
```
=============================================================================================== PASSES =============================================================================================== …
```

Porting 15919 to 202405.

---

tests/snappi_tests/files/helper.py
tests/snappi_tests/multidut/ecn/test_multidut_ecn_marking_with_snappi.py

Summary:
Testcase execution might fail if a previous test did a config reload
which results in delay of dshell init which is expected.
Added a pytest fixture to run along with testcase.
on Snappi based run

Cisco specific: Check debug shell status before ecn marking test

---

tests/common/snappi_tests/common_helpers.py

Previously we're using `sudo ip netns exec asic0 show queue counter` for showing the queue counter in multi-asic. However with the new apis, `-n` is supported natively in `show queue counter -n asic0`
This PR updates so that in get_egress_queue_count will use the new queue counters.
The queue counter support was added in the original PR:
- https://github.com/sonic-net/sonic-utilities/pull/2439
Cherry-pick to 202205:
- https://github.com/sonic-net/sonic-utilities/pull/2647
Summary:
Fixes # (issue) #15856 
Adjust the command to use the new format `show queue counter -n asic0`

[T2 IXIA] Update show queue counters api to use -n

---

tests/dhcp_relay/conftest.py
tests/dhcp_relay/dhcp_relay_utils.py

Summary:
There is flaky failure in this case because default route missing
1. Increase wait time for it.
2. Add log for triage
Run test

[dhcp_relay] Increase wait time for default route check in dhcp_relay test

---

tests/lldp/test_lldp_syncd.py

It's found in scaling setup (34K BGP routes) test_lldp_entry_table_after_reboot test may fail as lldp table entries in DB and from show are not in sync. Further analysis shows that after reboot, full lldp entries takes longer time to come back into DB. Entries are coming to DB one by one and takes few seconds to have full data there. 
Current test is calling reboot and check all critical services are up and all admin up ports are back to line then will begin lldp entries check. This could be too early as lldp packets are coming in one by one and lldp entries are written to DB one by one. The following few lldp queries could be out of sync in this scenario.
Solution is to take a query of how many lldp entries are in DB before reboot. After reboot will wait to check till all the lldp …

Fix an issue of all lldp entries take some time to be in DB after reboot in scaling setup.

---

tests/common/plugins/loganalyzer/__init__.py

Summary:
The duthosts could be a empty list with some special testbed, get the modular_chassis fact only when the duthosts[0] is available, otherwise it's not a modular chassis.
See the summary.
See the summary.
Run regression with this change, no issues observed.

[loganalyzer] Get the modular_chassis fact only when the duthosts[0] is available

---

ansible/roles/test/files/helpers/bfd_responder.py
tests/bfd/test_bfd.py

1.Log the error log of bfd responder when it failed to start 
2.Transfer bfd data to bytes type
Change-Id: Idef5a8fba1ef8544f410a7399b263bccf94e5926
Summary:
When bfd responder receive some bfd packet data with non-bytes values, it could lead to bfd responder start failure:
bfd_responder: ERROR (spawn error)
Bfd responder start failure:
bfd_responder: ERROR (spawn error)
1.Log the error log of bfd responder when it failed to start 
2.Transfer bfd data to bytes type

Add debug function for bfd responder start process

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Update generic hash INNER_IP_PROTOCOL skip condition due to hw capabilities
Summary:
Update skip condition for hash field INNER_IP_PROTOCOL
Add skips

[Mellanox] Update generic hash INNER_IP_PROTOCOL skip condition 

---

tests/hash/generic_hash_helper.py

All the ingress port hash test should based on the same hash range value
Summary:
All the ingress port hash test should based on the same hash range value
Remove test case filter for ingress port test

Update generic hash ingress port test

---

tests/qos/qos_sai_base.py

Update the way of shutdown bgp service in qos sai test 
In MSN2700 T0 setup, the original way of setting bgp down would be too slow 
And the bgp routes would be delay handled after several minutes, it would affect the qos buffer test result
Summary:
In MSN2700 T0 setup, the original way of setting bgp down would be too slow 
And the bgp routes would be delay handled after several minutes, it would affect the qos buffer test result
Use bgp shutdown/start to control bgp

Update the way of shutdown bgp service in qos sai test

---

ansible/roles/vm_set/tasks/main.yml

Change-Id: Ic083fe88b02cc377d7aa4380c228946ccbce6689
Summary: introduce retry for installing needed packages during the topology deployment to avoid `Failed to lock apt for exclusive operation` error
The motivation is to avoid concurrent apt lock by multiple setups

add retry for installing packages on server

---

tests/common/devices/sonic.py

Summary:
Fix the logic to parse "sudo monit status" output in get_monit_services_status()
The current logic simply checks for the keyword "status" in service_info without considering the context. If the keyword appears in 'last output' or another unintended section of the data, the logic misinterprets it.
Ensuring "status" detection is specific to the intended line. Using a stricter parsing approach to avoid unintended matches.
Ran the test_pretest.py on kvm-t0 testbed. Captured the get_monit_services_status() output
NA

Fix get_monit_services_status logic

---

tests/common/helpers/psu_helpers.py
tests/platform_tests/test_platform_info.py
tests/snmp/test_snmp_phy_entity.py

Summary:
Update test_turn_off_psu_and_check_psu_info to ensure that it handles PSUs with multilpe PDUs correctly
Update test_turn_on_off_psu_and_check_psustatus to handle PSUs with multiple PDUs correctly
* Instead of toggling one outlet/PDU, toggle a full set of PDUs connected to one PSU
* Move common PSU helpers function to new psu_helpers.py in tests/common/helpers folder
* Add try / catch block to ensure all PSUs are turned back on after the test
Prevent test from failing when toggling a PDU connected to a PSU that will stay on due to other redundant PDUs that were not toggled.
Break PDUs into sets based on PSU, make sure to toggle whole sets at once.
https://elastictest.org/scheduler/testplan/675919214fa1c38a7e20b96c <- T0/T1 regression test
Tested on T2 testbed as well (bar known …

Update test_turn_off_psu_and_check_psu_info to handle PSUs with multiple PDUs

---

tests/common/snappi_tests/traffic_generation.py
tests/snappi_tests/multidut/pfc/files/multidut_helper.py
tests/snappi_tests/pfc/files/helper.py

Summary:
The function: verify_in_flight_buffer_pkts is using the egress duthost's buffer size to verify the amount of packets that are transmitted is below the buffer size. That number is greatly influenced by the ingress buffer size when long links are in use as HBM is used with large XOFF threshold. Update this function to use the ingress DUT's buffer size.
Updated the function to take ingress_duthost and egress_duthost, instead of just duthost.
Ran it in my TB:
```
=========================================================================================================== PASSES ===========================================================================================================
___________________________________________________________________________ …
```

Change the verify_in_flight_buffer_pkts to use ingress duthost's buffer size

---

tests/common/snappi_tests/snappi_fixtures.py

Summary:
Existing snappi_dut_base_config in tests/common/snappi_tests/snappi_fixtures.py has an assert in case, mixed-speed ingress and egress interfaces are selected.
Since the interface speeds were same, the L1 configuration was done ONLY once.
With mixed-speed interfaces being used as ingress and egress, the assert needs to be removed. 
Second issue with existing snappi_multi_base_config was that speed was set to ONLY one of the interfaces being used for the test.  This was incorrect for mixed speed interfaces, causing Snappi API itself to crash.
#12966 
Existing snappi_dut_base_config asserts when ingress and egress interface speeds are different.
Furthermore, snappi framework itself did not support mixed-speed interfaces for the test and crashed (Please see issue …

[Snappi]: New base config function to accomodate mixed-speed ingress and egress tests.

---

.azure-pipelines/pr_test_skip_scripts.yaml

Summary:
Meanwhile, we are using .azure-pipelines/testscripts_analyse/ to static test scripts have been added or not, if a test script need to skip in KVM test, need to add it to .azure-pipelines/pr_test_skip_scripts.yaml and we would mark it as checked/covered.
Based on that, snappi test could not run on KVM platform, so need to add these tests to .azure-pipelines/pr_test_skip_scripts.yaml
Add snappi test scripts to .azure-pipelines/pr_test_skip_scripts.yaml

Add newly added snappi tests to PR test skip yaml

---

tests/common/helpers/psu_helpers.py
tests/platform_tests/test_platform_info.py
tests/snmp/test_snmp_phy_entity.py

Summary:
Update test_turn_off_psu_and_check_psu_info to ensure that it handles PSUs with multilpe PDUs correctly
Update test_turn_on_off_psu_and_check_psustatus to handle PSUs with multiple PDUs correctly
* Instead of toggling one outlet/PDU, toggle a full set of PDUs connected to one PSU
* Move common PSU helpers function to new psu_helpers.py in tests/common/helpers folder
* Add try / catch block to ensure all PSUs are turned back on after the test
Prevent test from failing when toggling a PDU connected to a PSU that will stay on due to other redundant PDUs that were not toggled.
Break PDUs into sets based on PSU, make sure to toggle whole sets at once.
https://elastictest.org/scheduler/testplan/675919214fa1c38a7e20b96c <- T0/T1 regression test
Tested on T2 testbed as well (bar known …

[Manual] [PR:15972] [202405] Update tests to handle PSUs with multiple PDUs

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/vxlan/test_vxlan_route_advertisement.py

Summary:
Confirmed with test case contributor, test_vxlan_route_advertisement does  not support other platforms except cisco or mnlx platforms
Skip test_vxlan_route_advertisement for platforms which is not cisco or mnlx platforms
run tests/vxlan/test_vxlan_route_advertisement.py on broadcom platform

Skip test_vxlan_route_advertisement for platforms which is not cisco or mnlx platforms

---

tests/qos/files/qos_params.j2c.yaml

When initially 400G & 100G profiles were added with cable length 12km & 2km, 400G_2km profile was skipped due to no visibility of adding 400G line card to downstream network for t2 topology.
Adding it back again, so that it can be used in future, if 400G line cards used as leafrouters  
Summary:
If 400G cards used as leafrouters , we need 400G_2k qos profile to run qos test cases
Verified qos test cases with 400G_2k profile and verify the results

Updating J2C+ qos_yaml for 400G_2k profile

---

ansible/roles/test/files/ptftests/py3/advanced-reboot.py

Summary:
In some cases, connecting to the device may fail for whatever reason. If this happens, the current code returns an empty string as the warmboot-finalizer state. There's a for-loop that exits when the warmboot-finalizer state is no longer active. An empty string being returned here breaks that.
To avoid that, don't exit this loop if we get an empty string.

Don't exit warmboot-finalizer loop early due to SSH connection issue

---

tests/route/test_route_consistency.py

Summary:
add upstream linecard check for chassis_packet, T2 Cisco device in get_route_prefix_snapshot_from_asicdb
This was to use correct num_routes_withdrawn during asserts, where we only had upstream support for 'voq' and failed for 'chassis_packet'
------------------------------------------------------ generated xml file: /var/src/sonic-mgmt-int/tests/logs/route/test_route_consistency.xml ------------------------------------------------------
============================================================================= 3 passed, 1 warning in 1482.39s (0:24:42)

add upstream linecard check for chassis_packet

---

tests/platform_tests/test_platform_info.py

Skip `platform_tests/test_platform_info.py::test_turn_on_off_psu_and_check_psustatus` for chassis LC
Summary:
Fixes # (issue) Microsoft ADO 30114143
Due to the module-level enumerate fixture `psu_test_setup_teardown` that has `enum_rand_one_per_hwsku_hostname` in this test module, we will run `platform_tests/test_platform_info.py::test_turn_on_off_psu_and_check_psustatus` multiple times when it's a T2 chassis. However, we don't need to run it multiple times because we are just toggling the PDU/PSU on the supervisor card in this test case. Therefore, we should skip the runs when the parametrization is on LCs.
Ran it on T2 and I can confirm it's only run for supervisor parametrization.

chore: skip PSU check for chassis LC

---

ansible/group_vars/sonic/sku-sensors-data.yml

Update sensor check items for SN4280, there are some unsupported sensors of SN4280 in 202405 branch.
Summary:
Sensor test case failure due to unsupported sensors
Sensor test case failure due to unsupported sensors
Update sensor check items for SN4280
SN4280

[Mellanox] Update sensor check items for SN4280

---

tests/gnmi/test_gnmi_configdb.py

Skip runs of `test_gnmi_configdb_incremental_01 ` and `test_gnmi_configdb_full_01 ` where the selected dut to host the gnmi_server is the supervisor.
This is because these tests require port data which isn't present on the supervisor.
Summary:
Fixes #15629

[gnmi] skip tests which require ports when sup is selected

---

tests/bgp/test_startup_tsa_tsb_service.py

Summary:
- This PR fixes a corner case w.r.t '_test_user_init_tsb_on_sup_while_service_run_on_dut_' test under '_test_startup_tsa_tsb_service_.py' and adds more check while fetching the '_tsa-tsb_' service status on the line cards after applying '_TSB_' on supervisor card.
- The fix makes sure if the service is '_Active_' running state and the service uptime is not the same as configured time.
- The test '_test_user_init_tsb_on_sup_while_service_run_on_dut_' fails with the following reason for one of the line card,
```python
suphost.shell('TSB')
for linecard in duthosts.frontend_nodes:
if get_tsa_tsb_service_status(linecard, 'running'):
>                   pytest_assert(TS_MAINTENANCE == get_traffic_shift_state(linecard, cmd='TSC no-stats'),
"DUT is not in maintenance …
```

[T2][Chassis] tsa-tsb: Add additional timer check before checking tsa-tsb service status

---

tests/voq/test_voq_disrupts.py

Summary:
Fixes #15916 
When an LC or a supervisor is rebooted it produces a lot of logs irrelevant to the individual testcases. This is one of the drawbacks faced by the voq disrupts tests that reboots the device and fails because of these unaccounted error logs. Following the theme seen in the below tests that call reboots, I have disabled the log analyzer in voq disrupt to make sure the test focuses more on catching the voq related failures.
- https://github.com/sonic-net/sonic-mgmt/blob/7e7dded7e51fa08e4fcff2efe1e0b0d412a3c230/tests/pfcwd/test_pfcwd_warm_reboot.py#L37
- https://github.com/sonic-net/sonic-mgmt/blob/7e7dded7e51fa08e4fcff2efe1e0b0d412a3c230/tests/platform_tests/test_power_off_reboot.py#L12
- https://github.com/sonic-net/sonic-mgmt/blob/7e7dded7e51fa08e4fcff2efe1e0b0d412a3c …

Disable loganalyzer for voq_disrupts test

---

tests/ip/test_ip_packet.py

https://github.com/sonic-net/sonic-mgmt/issues/7954 described an issue we saw on T2 platforms where `test_ip_packet.py::test_forward_ip_packet_with_0xffff_chksum_drop` would fail sporadically if sufficient control/background traffic egressed the `out_ifaces`.
https://github.com/sonic-net/sonic-mgmt/pull/8414 was created to fix this by increasing the tolerance from `100` to `200` packets. However, it seems like this wasn't sufficient tolerance as we're seeing failures on T2 devices:
```
Failed: Forwarded 276 packets in tx, not in expected range
Failed: Forwarded 275 packets in tx, not in expected range
Failed: Forwarded 264 packets in tx, not in expected range
Failed: Forwarded 295 packets in tx, not in expected range
Failed: Forwarded 316 packets in tx, not in expected range
Failed: …
```

`ip/test_ip_packet.py` Increase `tx_ok` tolerance from `200` to `400` on T2

---

tests/snmp/test_snmp_queue_counters.py

queuestat command output change fix for multi-asic
A new fix in queuestat script add extra line for multi-asic system
e.g "For namespace asic0"
Added logic to look for UC or MC string in each line and calculate counters accordingly
Summary:
- [ X] Bug fix
A new fix in queuestat script add extra line for multi-asic system
e.g "For namespace asic0"
Added logic to look for UC or MC string in each line and calculate counters accordingly

[test_snmp_queue_counters.py]: queuestat command output change fix for multi-asic

---

tests/bgp/test_bgpmon_v6.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
- Generalises BGPMON_V6 test to work with both active and pasive implementation of BGPMON_V6
- Add skip for known issue
Prevent failures where in bgp/test_bgpmon_v6.py where bgpmon_v6 may be passive
Removed check for SYN packet sent from DUT and use of information from that SYN packet following
Tested with passive bgpmon_v6 version on physical T2 device
N/A
N/A

Update BGPMON_V6 tests for both passive and active bgpmon_v6

---

ansible/roles/test/files/ptftests/py3/advanced-reboot.py
ansible/roles/test/files/ptftests/sonic.py

Summary:
This error was observed in the ptf output when running sad sub case 'neigh_lag_down:3' with sonic neighbors:
2024-11-04 01:06:10 : --------------------------------------------------
2024-11-04 01:06:10 : Fails:
2024-11-04 01:06:10 : --------------------------------------------------
2024-11-04 01:06:10 : FAILED:dut:Preboot: Lag state is not down on the DUT for PortChannel107
2024-11-04 01:06:10 : FAILED:dut:DUT is not ready for test
2024-11-04 01:06:10 : FAILED:dut:Preboot: Obtained:   107  PortChannel107  LACP(A)(Up)  Ethernet96(S)
2024-11-04 01:06:10 : FAILED:dut:Traceback (most recent call last):
File \"ptftests/py3/advanced-reboot.py\", line 1335, in runTest
self.wait_dut_to_warm_up()
File \"ptftests/py3/advanced-reboot.py\", line 2185, in wait_dut_to_warm_up
\"Actual warm up …

Fixed issue with neigbour lag not going down with sonic neighbors

---

tests/common/devices/sonic.py

Summary:
The bulk interface shutdown command is unsupported on 201911 and results in the following when sad path testing:
{
"changed": true,
"cmd": [
"sudo",
"config",
"interface",
"shutdown",
"Ethernet0,Ethernet10,Ethernet104,Ethernet106"
],
"delta": "0:00:01.058308",
"end": "2024-10-31 02:40:10.394406",
"failed": true,
"msg": "non-zero return code",
"rc": 2,
"start": "2024-10-31 02:40:09.336098",
"stderr": "Usage: config interface shutdown [OPTIONS] <interface_name>\n\nError: Interface name is invalid. Please enter a valid interface name!!",
"stderr_lines": [
"Usage: config interface shutdown [OPTIONS] <interface_name>",
"",
"Error: Interface name is invalid. Please enter a valid interface name!!"
],
"stdout": "",
"stdout_lines": []
}
This changes it to use the individual calls same as …

Change the batch shutdown call to individual call on 201911

---

tests/gnmi/helper.py
tests/gnmi/test_gnmi_smartswitch.py

Summary:
Microsoft ADO: 28940620
Add gnmi end to end test for smartswitch
Use GNMI to update the DASH_VNET_TABLE, and use redis cli to verify the DASH_VNET_TABLE in APPL_DB.
Only run test for smartswitch device.

Add gnmi test for smartswitch

---

tests/common/utilities.py

Summary:
In PR test, decap test is flaky and have a chance to fail in restart ferret in ptf for `ferret: ERROR (not running)`
Digging into the issue, I found ptf restart ferret failed because VxLan Sender IP is empty, but we don't have enough debug message to address the issue.
Add debug log in decap test to findout why VxLan Sender IP is empty.

Add debug log in decap test to address no vxlan sender IP issue

---

.azure-pipelines/pr_test_scripts.yaml
tests/restapi/test_restapi_vxlan_ecmp.py

In PR #15907, we initially added several test scripts to the onboarding PR checkers. After monitoring their performance over a few days, some of these scripts have proven to be stable. In this PR, we promote these stable scripts from the onboarding PR checkers to the standard PR checkers.
Summary:
In PR #15907, we initially added several test scripts to the onboarding PR checkers. After monitoring their performance over a few days, some of these scripts have proven to be stable. In this PR, we promote these stable scripts from the onboarding PR checkers to the standard PR checkers.
In this PR, we promote these stable scripts from the onboarding PR checkers to the standard PR checkers. …

Move some stable test scripts to standard PR checkers.

---

ansible/testbed-cli.sh
tests/conftest.py

The mgmt IP of dpus on smartswitch is private IP(169.254.200.0/24), we cannot access it directly out of the switch. To operate dpu like operating switch when impmenting the test case(**dash, platform on dup**), we add two fixtures: **dpuhost and fixture_dpuhosts**. They are same as duthost and fixture_duthosts.
Before the calling the fixtures, we need to do the steps as follows:
1.  Enable the NAT configuation on SmartSwitch by running  sonic-dpu-mgmt-traffic.sh
https://github.com/sonic-net/sonic-buildimage/pull/20635
e.g.
> sonic-dpu-mgmt-traffic.sh inbound -e --dpus all --ports 5021,5022,5023,5024
2.  Add dpu information to ansible/inventory(Notes: the **ansible_ssh_port** should be same as the above config of NAT)
e.g.
> smartswtich-01  ansible_host=10.200.100.2  sonic_version=v2 …

Add fixtures to call dpus on smartswtich directly

---

tests/route/test_route_consistency.py

Summary:
made a typo in PR16043, fix switch_type check with correct value

Fix typo on route_consistency

---

ansible/library/generate_golden_config_db.py

Summary:
Golden config db var has been changed from json like string to dict by this RP https://github.com/sonic-net/sonic-mgmt/pull/15922
But for mx with OS version doesn't support dhcp_server, it would still generate empty json like string, which would cause failure
Change empty golden config generated for mx doesn't support dhcp_server
Deploy-mg

[deploy-mg][mx] Fix generate golden config db failed in mx with OS version doesn't support dhcp_server

---

tests/generic_config_updater/test_lo_interface.py

Summary: Reload after lo test to recover default route
default route test would fail after lo test
Recover default route after test
E2E test

[GCU] Reload after lo test to recover default route

---

tests/platform_tests/test_cpu_memory_usage.py

Summary:
29844233
Memory usage is increasing due to more and more feature introduced in new image.
https://github.com/sonic-net/sonic-buildimage/issues/19828
Modify the lower memory device memory threshold 
https://elastictest.org/scheduler/testplan/675659228c6a916fb2ed5f4e
https://elastictest.org/scheduler/testplan/6756592f083d896c5b8ad5d9
https://elastictest.org/scheduler/testplan/67565a7c083d896c5b8ad5dd
https://elastictest.org/scheduler/testplan/67565aa7dee125b47d881e31
Low memory device

test_cpu_memory_usage.py update memory threshold for 4600 and 2700

---

tests/common/snappi_tests/multi_dut_params.py
tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_downlink_port_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_downlink_process_crash.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_tsa.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_multi_po_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_member_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_process_crash.py
tests/snappi_tests/variables.py

Cherry pick  https://github.com/sonic-net/sonic-mgmt/pull/15957
Currently the Snappi based T2 route convergence tests can only be used with single set of duts (hardcoded in variables.py). Enhanced the testcases/Infra to provide support for more than one platforms. The platform is fetched at runtime based on testbed parameters.
Fetch the platform info first by comparing the DUTs passed in testcase and duts defined in variables.py. Use this platform info through out the tests to fetch various other parameters
Ran the T2 snappi route convergance tests
None
Summary:

[202405][chassis] T2 Snappi Based route convergence: Code changes to support multiple platform (#15957)

---

tests/pfcwd/files/pfcwd_helper.py
tests/pfcwd/test_pfcwd_cli.py
tests/pfcwd/test_pfcwd_function.py

Summary:
This PR is to fix test issue caused by PR https://github.com/sonic-net/sonic-mgmt/pull/15946
The code below is to ensure there is PFCWD triggered on new queues before checking syslog.
https://github.com/sonic-net/sonic-mgmt/blob/15bf90347aa121064884adeacaed8ed5ba084e63/tests/pfcwd/test_pfcwd_function.py#L739-L741
The test is flaky after change in #15946 because the wait time is not enough for PFCWD to be triggered on new queues.
This PR is to fix test issue caused by PR https://github.com/sonic-net/sonic-mgmt/pull/15946
Change the logic back while maintain compatibility with chassis.
The change is verified on a Mellanox platform.
```
collected 5 items …
```

[202405] Fix test_pfcwd_function on Mellanox platform

---

tests/telemetry/events/dhcp-relay_events.py
tests/telemetry/events/event_utils.py

Summary:
Client mac of DHCP packets should be ptf interface mac rather than DUT interface mac
Modify test case to use ptf interface mac
Run tests in m0/t0 topo

[dhcp_relay][telemetry] Fix incorrect client mac in dhcp_relay related telemetry test

---

tests/ptf_runner.py

Summary:
This PR is to lower the log level for the message `DUT type file doesn't exist` from **ERROR** to **INFO**.
The log message is annoying in the test result, and the log message is not monitored.
This PR is to lower the log level for the message `DUT type file doesn't exist` from **ERROR** to **INFO**.
Change the log level.
The change is verified by running a test on a physical testbed.
No.

Lower log level for message  `DUT type file doesn't exist`

---

tests/arp/test_stress_arp.py

Summary:
ARP stress test is failing for certain CISCO 8000 platforms as the tested scale exceeds the HW availablity
Choose ARP scale based on available NH entries for CISCO 8000 platforms
- [ x] Bug fix
Pass all sonic mgmt tests on CISCO 8000  platforms
ARP scale depends on NH Scale. Earlier NH scale is not considered while pushing ARP entries. Now NH scale is also used.
Make sure all learnt ARP's are installed by comparing the neighbor entries installed in HW with ARP requests sent .
Ran it on T0 setup of Cisco-8122-O64 and Cisco-8111-O32 platforms
In certain CISCO platforms, Each Neighbor needs one NH entry. As a general fix,  we limit the number of Neighbor entries tested to the available NH entry on the platform

Choose ARP scale based on available NH entries for CISCO 8000 platforms

---

tests/lldp/test_lldp_syncd.py

…cd and orchagent
Summary:
Address https://github.com/sonic-net/sonic-mgmt/issues/15889
Add a new test case to address https://github.com/sonic-net/sonic-mgmt/issues/15889
Restart syncd and orchagent, then check lldp entries in APPL_DB
run test_lldp_syncd.py

[test gap] Add a new test case to verify lldp entry after restart syncd and orchagent

---

tests/common/helpers/pfcwd_helper.py
tests/pfcwd/test_pfcwd_cli.py
tests/pfcwd/test_pfcwd_function.py

Summary:
This PR is to fix test issue caused by PR #14711
The code below is to ensure there is PFCWD triggered on new queues before checking syslog.
https://github.com/sonic-net/sonic-mgmt/blob/15bf90347aa121064884adeacaed8ed5ba084e63/tests/pfcwd/test_pfcwd_function.py#L739-L741
The test is flaky after change in 14711 because the wait time is not enough for PFCWD to be triggered on new queues.
This PR is to fix test issue caused by PR https://github.com/sonic-net/sonic-mgmt/pull/15946
Change the logic back while maintain compatibility with chassis.
The change is verified on a Mellanox platform.
```
collected 5 items …
```

Fix test_pfcwd_function on Mellanox platform

---

tests/lldp/test_lldp_syncd.py

Fix case failure of Failed: lldp_rem_sys_cap_supported does not match for eth0
Summary:
For the mgmt port, the lldp_rem_sys_cap_supported could be 20 00.

Fix different format mgmt ip for eth0 in test_lldp_syncd

---

tests/pc/test_lag_member.py

Summary:
During movement test to Python 3 (#14944), were deleted necessary imports of fixtures with "autouse=True":
`copy_ptftests_directory`
`copy_arp_responder_py`
**copy_arp_responder_py**:
The fixture copied required configuration files. The arp responder configurations used in the test by method `setup_arp_responder`
Error from test without this fixture:
```Failed: Setup failed with error: run module shell failed, Ansible Results =>
failed = True
changed = True
end = 2024-12-11 05:18:59.588230
cmd = supervisorctl restart arp_responder
delta = 0:00:02.249219
rc = 7
invocation = {'module_args': {'creates': None, 'executable': None, '_uses_shell': True, 'strip_empty_ends': True, '_raw_params': 'supervisorctl restart arp_responder', 'removes': None, 'argv': None, 'warn': False, 'chdir': …
```

[lag_member] add necessary missed imports to test

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py

Summary:
Add the hwsku Mellanox-SN4280-O28 to ansible variable and port_utils.
Add the hwsku Mellanox-SN4280-O28 to ansible variable and port_utils.
Run regression on the SN4280 testbed.

[Mellanox] Add the hwsku Mellanox-SN4280-O28 to ansible variable and port_utils

---

tests/hash/test_generic_hash.py

Fix the ValueError in test_generic_hash.py
Check if the field existed in the list before removing it
Run test_generic_hash.py
Summary:

Fix the syntax error in test_generic_hash.py

---

tests/test_pretest.py

…all features
Summary:
Enhance test_disable_rsyslog_rate_limit to only fail after iterating all features
Avoid rsyslog_rate_limit not being disabled on working dockers when other dockers are unresponsive.
Adjust test_disable_rsyslog_rate_limit to collect the errors and only fail the test and display them after iterating through all features.
Run the test on a SONiC Platform

Enhance test_disable_rsyslog_rate_limit

---

tests/platform_tests/test_reload_config.py

Summary:
`platform_tests/test_reload_config.py::test_reload_configuration_checks` failed due to the following error:
`TypeError: unsupported type for timedelta seconds component: NoneType`
in the following error test log:
```
File \"/tmp/.ansible-AzDevOps/ansible-tmp-1734119665.955616-147727-226449133302882/AnsiballZ_wait_for.py\", line 107, in <module>
_ansiballz_main()
File \"/tmp/.ansible-AzDevOps/ansible-tmp-1734119665.955616-147727-226449133302882/AnsiballZ_wait_for.py\", line 99, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File \"/tmp/.ansible-AzDevOps/ansible-tmp-1734119665.955616-147727-226449133302882/AnsiballZ_wait_for.py\", line 47, in invoke_module …
```

Fix unexpected exception in wait_for while executing reboot

---

tests/hash/generic_hash_helper.py

Add a 60 seconds sleep due to issue https://github.com/sonic-net/sonic-buildimage/issues/20381
Need to revert this change after the PR fixed
Summary:
Issue https://github.com/sonic-net/sonic-buildimage/issues/20381
Add external sleep time

Add a 60 seconds sleep due to issue #20381

---

tests/platform_tests/fwutil/conftest.py

Summary:
Undo skip of ONIE component as result of 
Undo skip on ONIE component in fwutildue to old ONIE version not supporting downgrade test (https://github.com/sonic-net/sonic-mgmt/pull/5920)
Undo skip on ONIE component due to old ONIE version not supporting downgrade test
Run the test on SONiC Platforms

Delete ONIE Component skip on fwutil test

---

tests/snmp/test_snmp_queue.py

Summary:
Adjusted the test to skip validation of queue counter on inactive ports.
Adjust test to only check queue counter of active ports
Check that a port is up before validating its queue counter.

Adjust test to only check queue counter of active ports

---

tests/telemetry/events/host_events.py

Use 1 percent as cpu threshold for all the platforms.
It covers the sn4280, it has more cpu cores, and the threshold should be lower than 2 percent.
Summary:
telemetry.test_events#test_events failure 
telemetry.test_events#test_events failure due to gRPC error at sn4280, it has more cpu cores, so the cpu threshold should be lower.
Use lower cpu threshold for Nvidia platforms once it is clear that the new threshold is OK for all Nvidia platforms.
run the test on multiple Nvidia platforms.

[Mellanox] Update telemetry event test cpu threshold

---

tests/telemetry/conftest.py
tests/telemetry/telemetry_utils.py
tests/telemetry/test_telemetry.py

Backport PR of #15071 
After config reload, other telemetry cases fail since testing telemetry config is no longer present. This causes that telemetry config will not have client_auth set to false which results in cert errors when running telemetry query.
Added disable_loganalyzer to test_telemetry_queue_buffer_cnt since we see teardown loganalyzer errors complaining about non telemetry related syncd SAI_API logs
Ensure that telemetry present after each config reload call.
Manual/Pipeline
Summary:

Ensure correct testing telemetry config after config reload (#15071)

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
Fixes #16092 
To ignore acl egress feature unavailable error logs that get generated due to fabric cards not supporting this feature
Whitelisted the log
I am running the drop_packet test to verify that these logs were no longer reported

Whitelist acl egress logs on fabric cards

---

tests/common/platform/interface_utils.py

Summary: skip virtual chassis supervisor in check_interface_status_of_up_ports. Virtual T2 chassis supervisor does not have any front-end interface and neither 'PORT' configuration, so we should not run this check on virtual chassis SUP.
Microsoft ADO number: 30553232
Make the sanity check on T2 chassis smoother
Add code to skip chassis supervisor in check_interface_status_of_up_ports
Run the sanity check with such a change on a virtual chassis

skip chassis supervisor in check_interface_status_of_up_ports

---

tests/snmp/test_snmp_queue_counters.py

Regression test were failing becuase it was not bale to calculate correct range
Support for single Queue was not there such as 'Ethernet128|1' modified core to support both 
'Ethernet128|1' and 'Ethernet128|0-2'
Summary:

[test_snmp_queue_counters.py]: Added support for single buffer queue and fix range related issues

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Cherry-pick PR of https://github.com/sonic-net/sonic-mgmt/pull/15947, in https://github.com/sonic-net/sonic-utilities/pull/3102, the feature comparing yang model with configDB was added to sonic-utilities submodule, but feature subnet decap haven't been added to yang model, so the PR test advancing sonic-utilities to buildimage would fail in subnet decap test.
Created issue https://github.com/sonic-net/sonic-buildimage/issues/21090 and temporary skip subnet decap test until issue resolved

[202411] Temporary skip subnet decap test with issue since feature haven't been added to yang model

---

tests/acl/test_stress_acl.py

Fix acl/test_stress_acl.py using bad interface name for ACL table creation
Summary:
In `acl/test_stress_acl.py`, it attempts to retrieve an interface that can be used to create a ACL table. DUTs with and without PortChannels require different methods respectively.
Currently, it checks by filtering with topo. However, some topology flags can have configurations that have or not have PortChannels, making topos no longer a sufficient check - in some topos the test will fail with:
```
Error: Failed to parse ACL table config: exception=Cannot bind ACL to specified port Ethernet136
```
Reproducible by manually running the following on the DUT:
```
config acl add table DATAACL L3 -s ingress -p Ethernet0
^FAILS
config acl add table DATAACL L3 -s ingress -p PortChannel101
^WORKS …
```

Fix acl/test_stress_acl.py invalid interface name

---

.github/workflows/pr_cherrypick_prestep.yml

Summary:
Fix cherry pick workflow.
When there is already a PR for the cherry-pick, the action should continue the cherry-pick workflow instead of failing.

[action] Continue cherry pick workflow when PR already exists.

---

tests/common/plugins/conditional_mark/__init__.py

Summary:
This change is to support matching the test by regular expression in the conditional mark logic.
Sometimes we need to skip a test by a pytest parameter in the testcase name, which is not supported by the current longest match logic.
For example:
autorestart/test_container_autorestart.py::test_containers_autorestart[dut01-None-**teamd**]
If we only want to skip the **teamd** test case in the test test_container_autorestart.py, we are not able to do that because the first parameter is the dut name and it is different with different testbeds.
With this change, we are able to match the test case name by using a regex pattern, so that the teamd test case can be easily skipped.
The example of the skip condition is like this:
``` …
```

Update the conditional mark skip logic to support regular expression

---

tests/common/vxlan_ecmp_utils.py
tests/vxlan/bfd_notifier.py
tests/vxlan/test_vnet_bgp_route_precedence.py

These tests check the Vnet route precedence over bgp learnt route. 
Summary:
Currently if a route is learnt via BGP and added into the hardware, adding a VNET route results in failure. In addition due to a bug in VnetOrch, we start advertising the failed route, This prompts the BGP to remove the learnt route in favor of the local route. Since the Vnet Orch doesn't retry adding the Vnet route, This results in no route being present in the Hardware.
The fix is in PR https://github.com/sonic-net/sonic-swss/pull/3345
These tests cover various scenario in which VNET and BGP routes are added and removed in different order
Cisco-8000 and mlnx.
There are 5 differnet scenarios which are checked. Each scenario is tested with with the following options.
Encap types [v4_inv4, v6_inV4] …

Tests for VNET route precedence over BGP learnt route.

---

tests/platform_tests/api/test_chassis_fans.py

Summary:
Fixes wrong dut maybe selected to stop thermalctrl in chassis_fan tests.
TestChassisFans::setup fixture will select the first DUT as the duthost to stop/start thermal control daemon.
However, in the test case, it will enum_rand_one_per_hwsku_hostname to do the test.
Therefore, we will see something like the following. that lc4 is being selected to stop thermalctld, but the test is running on supervisor.
```
16/12/2024 12:42:40 base._run                                L0071 DEBUG  | /var/src/sonic-mgmt_xxx/tests/common/devices/sonic.py::stop_pmon_daemon_service#888: [xxx-lc4-1] AnsibleModule::shell, args=["docker exec pmon supervisorctl stop thermalctld"], kwargs={"module_ignore_errors": true}
......
16/12/2024 12:42:54 __init__._log_sep_line                   L0170 INFO   | …
```

fix flaky issue in test_set_fans_speed 

---

tests/platform_tests/api/test_chassis_fans.py

Cherry pick #16162 
Summary:
Fixes wrong dut maybe selected to stop thermalctrl in chassis_fan tests.
TestChassisFans::setup fixture will select the first DUT as the duthost to stop/start thermal control daemon.
However, in the test case, it will enum_rand_one_per_hwsku_hostname to do the test.
Therefore, we will see something like the following. that lc4 is being selected to stop thermalctld, but the test is running on supervisor.
```
16/12/2024 12:42:40 base._run                                L0071 DEBUG  | /var/src/sonic-mgmt_xxx/tests/common/devices/sonic.py::stop_pmon_daemon_service#888: [xxx-lc4-1] AnsibleModule::shell, args=["docker exec pmon supervisorctl stop thermalctld"], kwargs={"module_ignore_errors": true}
......
16/12/2024 12:42:54 __init__._log_sep_line …
```

[202405] fix flaky issue in test_set_fans_speed 

---

tests/common/snappi_tests/common_helpers.py

Braodcom DNX only supports WRED red.  So update test accordingly.
Summary:

Use WRED red for DNX

---

tests/common/fixtures/ptfhost_utils.py
tests/qos/test_qos_sai.py

Summary:
To address the unexpected packet drops on the DUT when running the testQosSaiHeadroomPoolSize, we identified that the unexpected packets are sent from the PTF container, and the leaf fanout ARP update is forwarding them to the DUT. Therefore, a fixture has been added to disable IPv6 on the PTF container to prevent the unexpected packets, and the values are restored after the tests.
Add fixture to disable IPv6 for all interfaces in ptf container before the test and restore the original IPv6 settings after the test.
Verify it by running tests/logs/qos/test_qos_sai.py::TestQosSai::testQosSaiHeadroomPoolSize[single_asic]
```
-------------------------------------- generated xml file: /data/sonic-mgmt-int/tests/logs/qos/test_qos_sai.py::TestQosSai::testQosSaiHeadroomPool …
```

Add fixture to disable IPv6 in PTF container

---

tests/common/fixtures/ptfhost_utils.py
tests/common/plugins/conditional_mark/tests_mark_conditions_skip_traffic_test.yaml
tests/common/plugins/ptfadapter/dummy_testutils.py
tests/conftest.py
tests/pytest.ini

Summary:
But some traffic test using ptfadapter can't be tested on KVM platform, we need to skip traffic test if needed.
1. Add `skip_traffic_test` marker
2. Create a dummy ptf testutils library to return True for all testutils.verify function
3. Add pytest hook to capture `skip_traffic_test` marker, if with this marker, replace testutils.verify with dummy library and always get return True
4. Add `skip_traffic_test` marker for route perf test in multi-asic T1 PR test
For tests needs return value(maybe tuple, str, int) of testutils.verify function, need to add some capability change

[202405] Support skip traffic test with testutils in KVM

---

tests/common/helpers/pfc_storm.py
tests/common/helpers/pfcwd_helper.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/pfcwd/test_pfcwd_all_port_storm.py
tests/pfcwd/test_pfcwd_cli.py
tests/pfcwd/test_pfcwd_function.py
tests/pfcwd/test_pfcwd_timer_accuracy.py
tests/pfcwd/test_pfcwd_warm_reboot.py

Summary:
But some traffic test can't be tested on KVM platform, we need to skip traffic test if needed
This PR adds pfcwd tests to the KVM-based PR test framework with the following scope and modifications:
1. Excludes fanout switch-related configurations, which are not applicable in the KVM test environment.
2. Traffic tests have been intentionally skipped due to the limitations of running traffic in the KVM environment.

Support pfcwd tests on KVM with partial configuration coverage

---

tests/dash/gnmi_utils.py
tests/gnmi/helper.py

Summary:
Microsoft ADO: 30577576
PTF container will not support python2, and GNMI test is using python2 gnmi client.
Use python2 for original PTF container
Use python3 for python3 only PTF container

Update gnmi test to support python3 gnmi client

---

tests/common/snappi_tests/common_helpers.py
tests/common/snappi_tests/traffic_generation.py
tests/snappi_tests/multidut/ecn/files/multidut_helper.py
tests/snappi_tests/multidut/ecn/test_multidut_ecn_marking_with_pfc_quanta_variance_with_snappi.py
tests/snappi_tests/multidut/ecn/test_multidut_xoff_variance_ecn_marking_with_snappi.py

Summary:
Add IXIA based test case to demonstrate ECN marking. The test will inject XOFF frame(s) to congest a queue that results in ECN marking. 
Using Snappi infra
- setup continous traffic at 99.98% line rate with 1350B packets
- Test sends a single XOFF frame to the egress port to create congestion in the queue3.
- A pfc frame is sent with quanta set to values between 500 and 65000,  one at a time -
- read the base ECN counter using serviceability CLI
- inject XOFF- 
- read the ECN counters
- At the end of the iteration, once the data is collected, ensure that for each case, with increase in quanta, the marked count at index (n+1) is >= count observed with collection at index (n). Further if the marked count at index (n) > 0,  verify that once marking happens, the …

ECN probabilistic marking with PFC induced congestion

---

tests/voq/test_voq_chassis_app_db_consistency.py

Summary:
Due to LAG ID SET Changes https://github.com/sonic-net/sonic-buildimage/pull/20369.
The Test Case Expectation and Assertion need to be changed.
Changes by the Functionality https://github.com/sonic-net/sonic-buildimage/pull/20369 of Lag ID assignment.
The TC Expectation and assertion is changed
Ignoring the SYSTEM_LAG_ID_SET to be same as in case pre-dump.
But rather be assigned from `SYSTEM_LAG_IDS_FREE_LIST` in order.
Added a sanity of lag_id_set to ensure the functionality of PR https://github.com/sonic-net/sonic-buildimage/pull/20369.
Tested and Verified on a T2 VOQ Chassis

Reg: TC test_voq_chassis_app_db_consistency.py Modification Due to Lag ID Set Changes

---

tests/platform_tests/test_cpu_memory_usage.py

Summary:
Fixes #16104
We wish to increase the mem threshold for Arista 7800 devices to 90 in order to help the platform_tests pass.
Modified the threshold in `tests/platform_tests/test_cpu_memory_usage.py`
Pending testing

Increase mem threshold for arista 7800 devices

---

tests/dhcp_relay/test_dhcp_relay_stress.py

Summary:
To ensure proper Dual ToR setups in test_dhcp_relay_stress testcase.
Added the Dual ToR-related fixture.
Validated that Dual ToR setups successfully pass the test_dhcp_relay_stress test case.

add dualtor fixture for test_dhcp_relay_stress 

---

tests/conftest.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py

Summary:
Currently, test_pfc_pause_single_lossy_prio and test_pfc_pause_single_lossy_prio_reboot are using more parameters than its needed, resulting in a longer execution time
Fixes # (issue) 30562817
Reducing the number of DUT but still give enough priorities for coverage
Modify the current fixture to add an option to pick 1 DUT for testing only
physical testbed

feat: add one_dut fixture to only use one dut

---

ansible/config_sonic_basedon_testbed.yml
ansible/library/dual_tor_facts.py
ansible/library/mux_cable_facts.py
ansible/library/test_facts.py
ansible/library/topo_facts.py
ansible/module_utils/dualtor_utils.py
tests/dualtor/templates/multivlan_ip_template.j2
tests/dualtor/templates/multivlan_mux_config_template.j2
tests/dualtor/templates/multivlan_template.j2
tests/dualtor/test_mux_port_iptables_entries.py

Covers test gap https://github.com/sonic-net/sonic-mgmt/issues/11436 which is raised to cover this issue https://github.com/sonic-net/sonic-host-services/pull/95. The test will check nat rules and make sure vlan ip to mux cable soc_ip snat is correct, and in the case of multivlan, only vlan ip of the vlan as soc_ip is used.
Summary:
Fixes #11436 
Covers test gap https://github.com/sonic-net/sonic-mgmt/issues/11436.
Run test on dualtor aa testbeds.

[dualtor-aa] add test to verify iptables nat rules for mux port

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skip test Fdb Mac Learning on dualtor setup for github issue https://github.com/sonic-net/sonic-mgmt/issues/16110
Summary:
fdb/test_fdb_mac_learning.py could not run pass at dualtor aa setup
Add a skip for the issue https://github.com/sonic-net/sonic-mgmt/issues/16110

Skip test Fdb Mac Learning on dualtor setup for github issue #16110

---

ansible/roles/fanout/library/port_config_gen.py
ansible/roles/fanout/library/sonic_sku_create.py
ansible/roles/fanout/tasks/sonic/fanout_sonic_202311.yml
ansible/roles/fanout/templates/sonic_deploy_202311.j2

During SONiC fanout deployment, when port split is needed. But there is no port name exists in port_config.ini for the split port. Then SONiC fanout deployment would failed due to this reason.
There would be 2 ways to fix this issue:
**[Solution 1]**
There would be a dynamic mechanism to generate a fake hwsku to meet this requirement. The solution is depend on a script called **sonic_sku_create.py**, it would based on lab connection graph xml to generate a suite of fake hwsku
In this implementation, only device and link csv files need to be updated:
1. HwSkuType="dynamic" should be set for the fanout switch, such as: 
**Hostname,ManagementIp,HwSku,Type,Protocol,Os,HwSkuType** 
r-tigon-21,10.210.24.193/22,Mellanox-SN4600C-C64,DevSonic,,sonic, …

Add solution for changing port_config.ini at fanout switch according to assigned hwsku

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Due to hardware limitation, when ecmp and lag hash at the same time, it would not support setting ecmp hash as CRC_CCITT and lag hash as CRC on ingress port hash field The hash result at this scenario would be bad
Summary:
Due to hardware limitation, when ecmp and lag hash at the same time, it would not support setting ecmp hash as CRC_CCITT and lag hash as CRC on ingress port hash field The hash result at this scenario would be bad
Skip test_ecmp_and_lag_hash[CRC_CCITT-IN_PORT case
No

Add community skip for ecmp and lag hash

---

ansible/roles/test/files/ptftests/py3/hash_test.py

Summary:
Preventing the hash test to fail in case of congestion on PTF.
Added a retry mechanism on hash test in case a packet wasn't sent correctly to the DUT, the retry will be applied on the same hash ket and same IPs
Ran the hash test on ipv4/6 mode multiple times and ensured it was passing.

Added a retry mechanism on hash test

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

In PR #16083, we used conditional marks to skip certain test scripts on vs testbeds. However, we mistakenly added the condition for `test_get_transceiver_threshold_info`. This PR corrects this issue.
Summary:
In PR #16083, we used conditional marks to skip certain test scripts on vs testbeds. However, we mistakenly added the condition for `test_get_transceiver_threshold_info`. This PR corrects this issue.
Add another condition to skip on vs testbed.

Fix incorrect conditional mark for `test_get_transceiver_threshold_info`

---

ansible/roles/vm_set/files/mux_simulator.py
ansible/roles/vm_set/tasks/control_mux_simulator.yml
ansible/roles/vm_set/templates/mux-simulator.service.j2

Summary:
The dualtor nightly suffers from mux simulator timeout issue, and there are always HTTP timeout failures observed.
This PR tries to improve the mux simulator performance:
1. improve the all mux toggle performance.
2. improve the mux simulator read/write throughput.
PR [1522](https://github.com/sonic-net/sonic-mgmt/pull/15226) was a quick fix to address, but it was a temporary quick fix.
1. run mux simulator with `gunicorn` instead of its own built-in HTTP server.
The mux simulator is running with `Flask`'s own built-in HTTP server. Previously, the mux simulator is running with single-threaded mode, which limits its performance && throughput; and the mux simulator is observed stuck in reading from dead connection; PR …

[dualtor] Improve `mux_simulator`

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py

Summary:
Not all HWSKUs are included in the variables file.
The missing HWSKUs frequently cause sync conflicts.
This change added the missing HWSKUs to the variables file.

Add missing HWSKUs to variables

---

tests/snmp/conftest.py

Fixture enable_queue_counterpoll_type in snmp is enabling queue counterpolls. But for Nokia 7215 armhf platforms, as queue statistics are not supported, there is an error while executing this command : "SAI_OBJECT_TYPE_QUEUE is not Supported".
So, added a skip condition inside the fixture for Nokia 7215 armhf platforms
Summary:
Fixes error: "SAI_OBJECT_TYPE_QUEUE is not Supported" in Nokia 7215 armhf platforms
Added condition inside fixture to skip for Nokia 7215 armhf platform
Run snmp test suite and verify fixture is not executed on Nokia-7215 armhf platforms

[snmp]Skipping enable_queue_counterpoll_type fixture for Nokia 7215 armhf platforms

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/dualtor_mgmt/test_egress_drop_nvidia.py

In PR #16083, we transitioned some test scripts from `pr_test_skip_scripts.yaml` to conditional marks, focusing mainly on T0 test scripts. In this PR, we complete the transition by addressing the remaining scripts.
Summary:
In PR #16083, we transitioned some test scripts from `pr_test_skip_scripts.yaml` to conditional marks, focusing mainly on T0 test scripts. In this PR, we complete the transition by addressing the remaining scripts.
In this PR, we complete the transition from `pr_test_skip_scripts.yaml` to conditional marks by addressing the remaining scripts.

Transite to conditional marks for skipping test scripts.

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Ignore nss_tacplus error log report by NTPD during config reload.
During config reload, tacacs config will be re-render by hostcfgd, NTPD will call getpwnam API during config reload, so will report nss_tacplus error.
These error can be ignored, getpwnam API will success in this case.
- Microsoft ADO: 
Ignore nss_tacplus error log report by NTPD.
Ignore nss_tacplus error log report by NTPD during config reload.

Ignore nss_tacplus error message reported by NTPD

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Some dataplane test scripts have been added to PR test and put into optional onboarding job to test case performance, I calculated the success rate of test scripts in recent 3 days, I think I can move high success rate test scripts to t0/t1 job now
TestbedName | FilePath | TestCase | SuccessCount | FailureCount | TotalTests | SuccessRate
vms-kvm-t1-lag | pfcwd/test_pfcwd_all_port_storm.py | test_all_port_storm_restore[vlab-03] | 81 | 0 | 81 | 1
vms-kvm-t1-lag | pfcwd/test_pfcwd_function.py | test_pfcwd_actions[vlab-03] | 81 | 0 | 81 | 1
vms-kvm-t1-lag | pfcwd/test_pfcwd_function.py | test_pfcwd_multi_port[vlab-03] | 81 | 0 | 81 | 1
vms-kvm-t1-lag | pfcwd/test_pfcwd_function.py | test_pfcwd_mmu_change[vlab-03] | 81 | 0 | 81 | 1 …

Move stable pfcwd tests from onboarding test set to PR test set

---

.azure-pipelines/baseline_test/baseline.test.template.yml

Summary:
Currently KVM dualtor test is not stable enough, baseline test is continuously generating work items for KVM dualtor, but some of them are duplicate. Platform owner will take actions to fix the issue recently, too much work items will cause noise during the fix.
Temporary skip dualtor test in baseline test.

Temporary skip dualtor test in baseline test

---

ansible/roles/vm_set/library/vm_topology.py

Summary:
`vm_topology` builds up the testbed connections (`veth` links, ovs bridges, etc) on the test server by running Linux commands, which involves a lot of waiting for I/O operations.
* the `vm_topology` script running statistics with `restart-ptf`:
```
real    18m50.615s
user    0m0.009s
sys     0m0.099s
```
With the I/O bound nature, `vm_topology` runtime could be greatly decreased by using threading pool to parallelize the I/O operations.
Introduce the thread pool to `vm_topology` to parallel run functions that take time to finish.
* `restart-ptf` on `dualtor-120` `vm_topology` profile statistics:
Top three total run time function call:
|function name|total run time|
|-|-|
|`add_host_ports`|1040s|
|`bind_fp_ports`|96.3s| …

[Infra][add/remove topo] Improve `vm_topology` performance

---

tests/common/plugins/sanity_check/checks.py
tests/common/plugins/sanity_check/recover.py

Summary:
BGP routes would be setup during add-topo https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/roles/vm_set/tasks/add_topo.yml#L276.
But there are some scenarios that route in DUT has been messed up, but bgp sessions are all up, sanity would treat it as healthy and wouldn't take action to recover it.
1) Loopbackv4 address has been replaced, it would cause all kernel routes from bgp miss
2) In some test cases announce or withdraw routes from ptf but fail to recover (i.e. test_stress_routes)
Healthy status:
```
admin@sonic:~$ ip route show default
default nhid 282 proto bgp src 10.1.0.32 metric 20 
nexthop via 10.0.0.57 dev PortChannel101 weight 1 
nexthop via 10.0.0.59 dev PortChannel103 weight 1 
nexthop via 10.0.0.61 dev PortChannel105 weight 1 
nexthop …
```

[sanity_check][bgp] Add default route check in sanity for single asic

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

In PR #16083, we transitioned T0 skipped test scripts from `pr_test_skip_scripts.yaml` to conditional marks. However, for the test script `test_vrf_attr.py`, we mistakenly omitted adding the condition to extended entries. This PR addresses and corrects this oversight.
Summary:
In PR #16083, we transitioned T0 skipped test scripts from `pr_test_skip_scripts.yaml` to conditional marks. However, for the test script `test_vrf_attr.py`, we mistakenly omitted adding the condition to extended entries. This PR addresses and corrects this oversight.
Add the condition to extended entries for test script `test_vrf_attr.py`.

Skip `test_vrf_attr.py` in PR testing using conditional mark. 

---

tests/qos/files/qos_params.th2.yaml

Summary:
encountered KeyError: '100000_300m' when run test_xoff_for_pcbb test fro 202405 branch
```
29/11/2024 22:41:51 __init__._fixture_func_decorator         L0073 ERROR  | 
KeyError('100000_300m')
File "/azp/_work/4/s/tests/common/plugins/log_section_start/__init__.py", line 71, in _fixture_func_decorator
return fixture_func(*args, **kargs)
File "/azp/_work/4/s/tests/qos/tunnel_qos_remap_base.py", line 308, in qos_config
return qos_configs['qos_params'][dut_asic][dut_topo][profile_name]
KeyError: '100000_300m'
```
run tests/qos/files/brcm/qos_param_generator.py to auto generate qos parameter for xoff case, and copy param to qos.yml for pcbb case.
```
25/12/2024 17:53:40 qos_param_generator.msg                  L0134 INFO   | Clone …
```

generate 100000_300m pcbb qos test param for th2

---

tests/bgp/conftest.py
tests/bgp/test_bgp_stress_link_flap.py

Summary:
auto merge conflict
backport 
https://github.com/sonic-net/sonic-mgmt/pull/14393
https://github.com/sonic-net/sonic-mgmt/pull/14890

[202405] backport #14393 #14890 to 202405 branch

---

tests/common/fixtures/duthost_utils.py
tests/conftest.py
tests/platform_tests/counterpoll/test_counterpoll_watermark.py

Details of failure described in more detail in https://github.com/sonic-net/sonic-mgmt/issues/15991
Created a new fixture `backup_and_restore_config_db_frontend` which uses `enum_rand_one_per_hwsku_frontend_hostname` so `test_counterpoll_watermark.py` can run it.
Updated `_backup_and_restore_config_db` to work on multi-asic LCs
Summary:
Fixes #15991

Fix config_db.json backup in `test_counterpoll_watermark.py`

---

tests/container_checker/test_container_checker.py
tests/process_monitoring/test_critical_process_monitoring.py

Summary:
Notice quite a lot flaky failures on PR test,
https://elastictest.org/scheduler/testplan/676e75562c6c7b8d3e3bd8bf?testcase=process_monitoring%2Ftest_critical_process_monitoring.py&type=console
Simply wait for 120s is not enough for multi-asic kvm testbeds, enhance the config_reload to use safe_reload to make sure the testbed is healthy.
Notice quite a lot flaky failures on PR test,
https://elastictest.org/scheduler/testplan/676e75562c6c7b8d3e3bd8bf?testcase=process_monitoring%2Ftest_critical_process_monitoring.py&type=console
Simply wait for 120s is not enough for multi-asic kvm testbeds, enhance the config_reload to use safe_reload to make sure the testbed is healthy.
PR test will verify it.

Add safe_reload and interface check for process monitoring and container check tests

---

tests/telemetry/events/dhcp-relay_events.py

Summary:
There are global unique ipv6 address and link local ipv6 address configured in Vlan, not need to flush all of them to trigger fail to bind issue.
Only delete GUA in Vlan
Run test

[dhcp_relay][telemetry] Update events test for dhcp6relay bind issue

---

tests/dash/gnmi_utils.py
tests/gnmi/helper.py

Summary:
Microsoft ADO: 30577576
We have detected a syntax warning when using the gNMI client with Python 3:
E           Exception: error:/root/gnxi/gnmi_cli_py/py_gnmicli.py:508: SyntaxWarning: "is not" with a literal. Did you mean "!="?
E             if filter_event_regex is not "":
E           /root/gnxi/gnmi_cli_py/py_gnmicli.py:510: SyntaxWarning: "is not" with a literal. Did you mean "!="?
E             if len(match) is not 0:
Do not check stderr in the test

Ignore gnmi client stderr

---

tests/voq/test_fabric_cli_and_db.py
tests/voq/test_fabric_reach.py

Summary:
Fixes # 16067 
https://github.com/sonic-net/sonic-mgmt/issues/16067
- [X ] 202405
Fixing issue 16067. 
Changed to not re-write originalIsolateStatus but instead write to isolateStatus.
Also added try/catch block to both tests as today if the test fails it exits without restoring the state of the port.
I also added check  to tests/voq/test_fabric_reach.py::test_fabric_reach_supervisor to run against only if asic is present. Right not the tests get the max asics for the platform and assumes they are all present.
Ran against t2 Nokia chassis

fix for voq fabric related tests

---

tests/common/plugins/sanity_check/recover.py

Summary:
Default route check in sanity is added by https://github.com/sonic-net/sonic-mgmt/pull/16235
It only supports single asic for now. But constraint for single asic in recover stage is missed
It would cause keyError in multi-asic if there is bgp sanity check failure
```
def adaptive_recover(dut, localhost, fanouthosts, nbrhosts, tbinfo, check_results, wait_time):
outstanding_action = None
for result in check_results:
if result['failed']:
if result['check_item'] == 'interfaces':
action = _recover_interfaces(dut, fanouthosts, result, wait_time)
elif result['check_item'] == 'services':
action = _recover_services(dut, result)
elif result['check_item'] == 'bgp':
>                   if ("no_v4_default_route" in result['bgp'] and len(result['bgp']) == 1 or …
```

[sanity][bgp] Skip default route missing recover for multi-asic

---

tests/common/snappi_tests/qos_fixtures.py

Summary:
Even after https://github.com/sonic-net/sonic-mgmt/pull/15863, the problem is still seen in RP. The issue is that the sort() function only sorts alphabetically, not numerically. So we need to use natsort module instead of normal sort() in these functions.
Seeing a lot of loganalyzer messages, but in RP only.
Change sort to natsort().
Running in my TB, I don't see the LA error anymore.
T2 mAsic only.

T2/snappi: Use natsort instead of sort for sorting the asic list in disable_pfcwd and enable_pfcwd functions.

---

tests/common/plugins/sanity_check/__init__.py
tests/common/plugins/sanity_check/checks.py

Add BFD up count check and MAC entries count check to sanity check for T2 topo.
Summary:
Fixes # (issue) Microsoft ADO 29825439 & 29825466
During our T2 Nightly run, we found that there will be a chance that the port channel connection between 2 ASICs is up but MAC address was not learned and the BFD session between them is down. Therefore, we need to have sanity check to make sure BFD are all up and all MAC addresses are learned, otherwise issue like this will affect the test result and can impact production env.
1. Added `check_bfd_up_count()` function to sanity check for T2 topo only. This check will take ~4 seconds to run on a T2 device with 3 LC (frontend nodes).
2. Added `check_mac_entry_count()` function to sanity check for T2 supervisor only. This check will take ~17 seconds to …

feat: add more sanity checks for T2

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/vxlan/test_vnet_bgp_route_precedence.py

Summary:
Skip tests/vxlan/test_vnet_bgp_route_precedence.py for non cisco and mnlx platforms
Add skip condition in conditional mark file
Run tests/vxlan/test_vnet_bgp_route_precedence.py on broadcom platform

Skip vxlan/test_vnet_bgp_route_precedence.py for non cisco and mnlx platforms

---

tests/common/plugins/sanity_check/recover.py

Summary:
Manually cherry-pick this PR: https://github.com/sonic-net/sonic-mgmt/pull/16264
Default route check in sanity is added by https://github.com/sonic-net/sonic-mgmt/pull/16235
It only supports single asic for now. But constraint for single asic in recover stage is missed
It would cause keyError in multi-asic if it trys to recover bgp sanity check failure
```
def adaptive_recover(dut, localhost, fanouthosts, nbrhosts, tbinfo, check_results, wait_time):
outstanding_action = None
for result in check_results:
if result['failed']:
if result['check_item'] == 'interfaces':
action = _recover_interfaces(dut, fanouthosts, result, wait_time)
elif result['check_item'] == 'services':
action = _recover_services(dut, result)
elif result['check_item'] == 'bgp':
> …
```

[202405][sanity][bgp] Skip default route missing recover for multi-asic (#16264)

---

spytest/spytest/framework.py
spytest/spytest/infra.py
spytest/spytest/testbed.py

Summary:
Added functionality to retrieve console information from testbed devices in spytest framework. This enables access to console details (IP, port, protocol) for test cases and debugging purposes.
To provide easy access to device console information within spytest framework, which helps in debugging and monitoring test cases that require console access.
- Added new method `get_console()` in framework.py to access testbed console info
- Implemented `get_console_info()` in infra.py as a utility function
- Added `get_console()` in testbed.py to retrieve console IP, port, and protocol from device info
By running spytest with a testbed configuration that includes console information and verifying the returned console details match the configuration.
Sample testbed yaml file includes:
``` …
```

[spytest] feature: add functionality to retrieve console information

---

tests/override_config_table/test_override_config_table_masic.py

Enhance the `override_config_table/test_override_config_table_masic.py` to make it compatible with the parallel run infra.
Summary:
We wanted to enable parallel run for `override_config_table/test_override_config_table_masic.py`, so we need to deprecate `enum_upstream_dut_hostname`.
I ran the updated code and can confirm it's working as expected.

refactor: enhance override config masic test

---

tests/platform_tests/test_cpu_memory_usage.py

Increase the memory threshold for the Cisco 8000 supervisor to 65% to make the test stable.
Summary:
Fixes # (issue) Microsoft ADO 30114189
During recent nightly runs, we observed that the Cisco 8000 supervisor had an average memory usage of 59.7% (calculated from the values 60.3, 59.9, 58.9, 59.2, 59.8, and 60.2). Since the memory threshold is set at 60%, this resulted in two failures. To ensure the stability of the tests, we propose increasing the memory threshold for the Cisco 8000 supervisor to 65%.
I ran the updated code on Cisco 8000 and can confirm it's working well.
Cisco 8000 chassis

fix: bump memory limit for Cisco 8000 supervisor

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skipping test_voq_queue_counter[multi_dut_shortlink_to_longlink] because of issue #21098
Summary:
we need to skip test_voq_queue_counter[multi_dut_shortlink_to_longlink]  testcase until issue #21098 is fixed.
Tested on a multi ASICs chassis

Skipping test_voq_queue_counter[multi_dut_shortlink_to_longlink]. Issue #21098

---

tests/qos/qos_sai_base.py
tests/qos/test_qos_sai.py

https://github.com/sonic-net/sonic-mgmt/pull/14469 was introduced to increase the LACP timeout of EOS neighbors during QOS tests.
This was required because the QOS tests would disable TX credits on the test's dest ports, without TX credits LACP packets won't egress and eventually the LAG will be brought down by the EOS neighbor due to LACP timeout.
This change adds a couple improvements to that existing PR:
-Updated to work with single-asic LCs
-Updated to change the LACP timeout multiplier for all 3 dst_port_id neighbors.
Also made testQosSaiPfcXonLimit use fixture change_lag_lacp_timer

Fix a couple issues in `change_lag_lacp_timer`

---

tests/route/test_default_route.py

Summary:
This PR fixes issue #9052, where '_test_default_route_with_bgp_flap_' fails with "_Default route nexthops doesn't match the testbed topology_" issue.
The count of the next hops is not matching with the upstream neighbor as per the topology (reading data from config facts).
-  '_test_default_route_with_bgp_flap_' fails with "_Default route nexthops doesn't match the testbed topology_" issue.
- The count of the next hops is not matching with the upstream neighbor as per the topology.
- Instead of skipping T3 neighbors of AZNGHub, use the address family and next hops information to find out the list of upstream neighbors.
- Ran the above-mentioned test case on a T2 chassis and made sure the test passed without any issues.

[default-route-bgp-flap]: Fix for 9052 - test failure

---

tests/test_parallel_modes/cisco_t2_8800.json

Enable parallel run for `override_config_table/test_override_config_table_masic.py` in 202405
Summary:
Previously we disabled parallel run for `override_config_table/test_override_config_table_masic.py` in 202405 as it's not compatible with the existing infra. Now this test has been enhanced in #16226 so we can enable parallel run for it.

chore: enable parallel run for override in 202405

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
Due to known issue sonic-net/sonic-buildimage#21319, ignore the ERR logs in loganalyzer.
Due to known issue sonic-net/sonic-buildimage#21319, ignore the ERR logs in loganalyzer.
Update loganalyzer ignore file.
Verified on Nokia-7215 DUT, confirmed testcase can ignore this ERR log.
Fix for Marvell-Armhf platform.

[loganalyzer] Ignore pmon#stormond iSmart binary format ERR log

---

tests/platform_tests/test_cpu_memory_usage.py

Increase the memory threshold for the Cisco 8000 supervisor to 65% to make the test stable.
Summary:
Fixes # (issue) Microsoft ADO 30114189
During recent nightly runs, we observed that the Cisco 8000 supervisor had an average memory usage of 59.7% (calculated from the values 60.3, 59.9, 58.9, 59.2, 59.8, and 60.2). Since the memory threshold is set at 60%, this resulted in two failures. To ensure the stability of the tests, we propose increasing the memory threshold for the Cisco 8000 supervisor to 65%.
I ran the updated code on Cisco 8000 and can confirm it's working well.
Cisco 8000 chassis

[manual] [PR:16206] fix: bump memory limit for Cisco 8000 supervisor

---

tests/voq/test_fabric_cli_and_db.py

Summary: Fix the fabric_cli_and_db  test so it only tests connected links. 
The fabric_cli_and_db failed in cases where the test selected a link that was not connected. This issue occurred because the portList set was not reset for each chip, allowing links that were connected on other chips to be tested, even though they were not connected on the chip being tested. In this PR, the portList is reset for each chip, and the 'show fabric reachability' command is also run on each chip. As a result, the test now only choose connected links on the chip under test.

Fix fabric_cli_and_db so it only tests on connected links.

---

tests/bgp/test_seq_idf_isolation.py

The test is flaky because it checks routes on neighbors immediately after isolating dut. So the test may fail if the neighbors (VM) are not able to process route withdraw in time. Make the test more robust by retrying validation for 60 seconds.
Summary:
- [ x] 202405

Make test_idf_isolated_withdraw_all more robust

---

.azure-pipelines/impacted_area_testing/calculate_instance_number.py

In this PR, we have added additional logging to the `calculate_instance_number.py` script to improve tracking and visibility of its operations.
Summary:
In this PR, we have added additional logging to the calculate_instance_number.py script to improve tracking and visibility of its operations.
Add additional logging to the `calculate_instance_number.py` script.

Add additional logging to script `calculate_instance_number.py`

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

The script `test_advanced_reboot.py` has an extensive runtime in PR testing. To optimize efficiency, we will skip this script during PR testing, except for the `test_warm_reboot` test case on the T0 topology in consistency with original PR testing. 
Summary:
The script `test_advanced_reboot.py` has an extensive runtime in PR testing. To optimize efficiency, we will skip this script during PR testing, except for the `test_warm_reboot` test case on the T0 topology in consistency with original PR testing. 
Skip `test_advanced_reboot.py` except for the `test_warm_reboot` test case on the T0 topology using conditional mark.

Skip `test_advanced_reboot.py` in PR testing. 

---

ansible/roles/vm_set/library/vm_topology.py

Summary:
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/16230 into 202405

[202405][Infra][add/remove topo] Improve `vm_topology` performance (#16230)

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/kubesonic/kubesonic_test.md
tests/kubesonic/test_k8s_join_disjoin.py

Test the sonic device join k8s cluster and disjoin k8s cluster.
Setup a single master node cluster on the server of testbed, make sonic device join the cluster and disjoin the cluster to check if it works, deploy a daemonset to check if the pods are able to run on sonic.
Run it in the KVM testbed and physical testbed, it works
No, should be good for all platform
Supported testbed topology if it's a new test case? Any
Documentation
In the PR md file.
Summary:

Add k8s join and disjoin test cases (#16141)

---

tests/common/plugins/sanity_check/checks.py
tests/conftest.py

Summary:
This support add sanity check for snappi related topologies by skipping BGP and nbrhost check as there is no cEOS neighbor in snappi topologies.
support sanity check for IXIA toplogy.
Skip the items which is not needed for snappi testbed.
Verified on T2 snappi testbed.

support Ixia topology in sanity check

---

tests/acl/test_acl.py

Summary:
test_acl failed due to failed on `setup with "KeyError: 'Vlan1000'"` after changing to use 2vlan in topo file.
If enable 2vlan config in topology file(such as `ansible/vars/topo_t0-116.yml`):
change from 
```
vlan_configs:
default_vlan_config: one_vlan_a
```
to 
```
vlan_configs:
default_vlan_config: two_vlan_a
```
Then vlan name is not Vlan1000 anymore, it could be Vlan100 or Vlan200.
So, in https://github.com/sonic-net/sonic-mgmt/pull/9334/files, it sets default vlan name to Vlan1000 in `pytest_generate_tests` for T0 is not very reasonable.
So, in test_acl, for T0 topology, still get vlan name from config, not from `vlan_name` parameter, then test_acl can pass.
Run test_acl on  testbed with 2vlan config.

Support 2 vlan config in topology for test_acl

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Summary:
Fixes Ignore NTP leap second file expired syslog
Recently testcase fails with the syslog error:
2024 Dec 30 15:13:59.746932 str3-7260cx3-acs-14 ERR ntpd[64974]: CLOCK: leapsecond file ('/usr/share/zoneinfo/leap-seconds.list'): expired less than 3 days ago 
Ignore this syslog error for now.

Ignore NTP leap second file expired syslog

---

tests/platform_tests/test_cpu_memory_usage.py

Summary:
This PR is to backport #15948 to 202405 branch.
29844233
Memory usage is increasing due to more and more feature introduced in new image.
https://github.com/sonic-net/sonic-buildimage/issues/19828
Modify the lower memory device memory threshold 
https://elastictest.org/scheduler/testplan/675659228c6a916fb2ed5f4e
https://elastictest.org/scheduler/testplan/6756592f083d896c5b8ad5d9
https://elastictest.org/scheduler/testplan/67565a7c083d896c5b8ad5dd
https://elastictest.org/scheduler/testplan/67565aa7dee125b47d881e31
Low memory device

[202405] test_cpu_memory_usage.py update memory threshold for 4600 and 2700

---

tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_member_flap.py
tests/snappi_tests/variables.py

Summary:
T2 Snappi based automation testcases, currently didnt have Different types of upstream neighbors support.
As part of this PR, 
1. Different upstream neighbors support is added. 
2. Fixed a bug where t2_uplink_fanout_info was not parsed correctly.
3. Po members flap test to skip if num_po_members < 2.
T2 Snappi based automation testcases, currently didnt have Different types of upstream neighbors support.
Different upstream neighbors support is added. This also covers different route policies on different types of upstream neighbors
Ran the testcases locally and captured the results.
NA

T2: Snappi Based Route Convergence Test Changes 

---

.azure-pipelines/impacted_area_testing/calculate-instance-numbers.yml
.azure-pipelines/impacted_area_testing/get-impacted-area.yml

In our Impacted Area Based PR testing, we noticed some failure beacuse of the error `Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 5166 (dpkg)`. In this PR, we add a timeout for acquiring dpkg lock to avoid this issue. 
Summary:
In our Impacted Area Based PR testing, we noticed some failure beacuse of the error `Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 5166 (dpkg)`. In this PR, we add a timeout for acquiring dpkg lock to avoid this issue. 
In this PR, we add a timeout for acquiring dpkg lock to avoid this issue.

Add a timeout for acquiring dpkg lock. 

---

tests/qos/files/qos_params.jr2.yaml

The JR2 tuning values were copied over from the J2c+ tuning values here: https://github.com/sonic-net/sonic-mgmt/pull/13660
But the JR2 tunings are slightly different as the shared buffer pool is different on JR2 vs J2c+.
J2c+:
```
root@cmp206-4:~# bcmcmd -n 0 "tm ing vsq resources"
tm ing vsq resources
==========================================================================================
|                               Core 0 Resource Allocation                               |
==========================================================================================
| Parameter        | Bytes                   | OCB Buffers      | OCB Packet Descriptors |
==========================================================================================
| Nominal Headroom | 198048000 …
```

[T2] Updated JR2 tuning values for T2 systems

---

tests/common/helpers/tacacs/tacacs_helper.py

Create /etc/tacacs folder on PTF when it's missing
TACACS test failed because /etc/tacacs+ folder does not exist, which recently missing on some version of PTF container image.
Error message:
E           msg = Destination directory /etc/tacacs+ does not exist
- Microsoft ADO: 30626377
Create /etc/tacacs folder on PTF when it's missing
Create /etc/tacacs folder on PTF when it's missing

Create /etc/tacacs folder on PTF when it's missing

---

tests/common/utilities.py
tests/tacacs/test_authorization.py

Remove golden config file and revert config when load golden config failed.
Fix bug https://github.com/sonic-net/sonic-mgmt/issues/16338
TACACS test case reload golden config failed, and golden config not remove because a code bug, then all test case failed after that because login failed.
- Microsoft ADO: 30667311
add try finally to make sure golden config always remove after reload config.
Remove golden config file and revert config when load golden config failed.

Remove golden config file and revert config when load golden config failed.

---

ansible/templates/minigraph_link_meta.j2

Summary:
This PR is to add a check in `minigraph_link_meta.j2` to ensure that AN enabled ports are present in the definition of connection graph. Otherwise the configuration will not be generated.
This change is required because it's possible that `autoneg_interfaces` is defined in the definition of topology, but the link is not defined in connection graph. In this case, `config load_minigraph` throws an exception
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'Ethernet248'
fatal: [str-msn4700-01]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'Ethernet248'"}
```
This PR is to add a check in `minigraph_link_meta.j2` …

Check AN enabled port is in connection graph

---

.azure-pipelines/pr_test_scripts.yaml
.azure-pipelines/pr_test_skip_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
But some traffic test can't be tested on KVM platform, we need to skip traffic test if needed.
For tests adding to PR checker list, use Elastictest to verify:
TestbedName | FilePath | TestCase | SuccessCount | FailureCount | TotalTests | SuccessRate
vms-kvm-t1-lag | qos/test_qos_dscp_mapping.py | test_dscp_to_queue_mapping_pipe_mode | 30 | 0 | 30 | 1
vms-kvm-t1-lag | qos/test_qos_dscp_mapping.py | test_dscp_to_queue_mapping_uniform_mode | 30 | 0 | 30 | 1
vms-kvm-t1-lag | qos/test_pfc_counters.py | test_pfc_pause | 30 | 0 | 30 | 1
vms-kvm-t1-lag | qos/test_pfc_counters.py | test_pfc_unpause | 30 | 0 | 30 …

Add some qos/pfcwd tests to PR checker and skip some tests in PR test

---

tests/bgp/test_reliable_tsa.py

Optimize `bgp/test_reliable_tsa.py` with multithreading to reduce the running time.
Summary:
The `bgp/test_reliable_tsa.py` takes a very long time to finish on T2 chassis (5.5h ~ 6h), so we wanted to optimize it using multithreading to reduce the running time. After the optimization, the running time is reduced to ~3.5h. 
I ran the updated code and can confirm it's working as expected. Elastictest [link](https://elastictest.org/scheduler/testplan/677bd96dfd38d01ddaaf3253?leftSideViewMode=detail&testcase=bgp%2Ftest_reliable_tsa.py&type=console) with flaky test case re-run [link](https://elastictest.org/scheduler/testplan/677c7f1e56078c01462d4777?leftSideViewMode=detail&testcase=bgp%2Ftest_reliable_tsa.py%3A%3Atest_dut_tsa_with_conf_reload_when_sup_on_tsa_dut_on_tsb_init&type …

refactor: optimize reliable tsa test

---

tests/common/plugins/sanity_check/__init__.py
tests/common/plugins/sanity_check/recover.py

Summary:
Sometimes exabgp in ptf would be in incorrect status by stress testing, hence add restarting exabgp before re-announce routes in sanity check.
1. Restart exabgp before re-announce routes
2. Add try catch to handle failed to re-announce issue
Run test with sanity check

[sanity_check][bgp] Enhance sanity check recover for bgp default route missing

---

tests/arp/test_arp_dualtor.py

Summary:
This PR temporarily skips test_arp_update_for_failed_standby_neighbor when the test is executed on a KVM testbed and the neighbor IP is an IPv6 address. The reason is that this test case is currently blocking sonic-swss submodule from being updated.
Unblocking sonic-swss submodule update.
Skipped the failing test case when the test is executed on a KVM testbed and the neighbor IP is an IPv6 address.
N/A
The test is only skipped on VS switches.
N/A
N/A

Temporarily skipping a test in test_arp_dualtor.py that is failing consistently

---

tests/saitests/py3/sai_qos_tests.py

In https://github.com/sonic-net/sonic-mgmt/pull/8149 the `multi-asic` and `multi-dut` variants were added to `test_qos_sai.py`.
This required updating calls to `dynamically_compensate_leakout` to specify either the `src_client` or dst_client` but a couple calls in `PGSharedWatermarkTest` passed the wrong client.
For more details on the failure this causes see https://github.com/sonic-net/sonic-mgmt/issues/16167
Summary:
Fixes #16167

Correcting client arguments to `dynamically_compensate_leakout` in `PGSharedWatermarkTest`

---

tests/arp/test_arp_dualtor.py

Summary:
This PR temporarily skips test_standby_unsolicited_neigh_learning when the test is executed on a KVM testbed and the neighbor IP is an IPv6 address. The reason is that this test case is currently blocking sonic-swss submodule from being updated.
Unblocking sonic-swss submodule update.
Skipped the failing test case when the test is executed on a KVM testbed and the neighbor IP is an IPv6 address.
Tested on a local dualtor KVM testbed.
The test is only skipped on VS switches.
N/A
N/A

Temporarily skipping a failing test in test_arp_dualtor.py

---

tests/bgp/test_bgp_bbr_default_state.py
tests/drop_packets/test_drop_counters.py
tests/snmp/test_snmp_queue_counters.py

Summary:
On Broadcom platforms, ECMP/LAG hash is not supported. Adding ERR log ignore as it is expected for this error log to print.
On Broadcom platforms, ECMP/LAG hash is not supported. Adding ERR log ignore as it is expected for this error log to print.
Add by extending log regex in individual test cases. Not adding to loganalyzer_common_ignore.txt because that would cause expected fail tests to pass during CI.
The following tests no longer fail on 7060X6 t1
`snmp/test_snmp_queue_counters.py`
`drop_packets/drop_packets.py`
`bgp/test_bgp_bbr_default_state.py`
Only applies to Broadcom platform.

[202405] Add ERR log ignore for ECMP/LAG hash not supported

---

tests/gnmi/helper.py

Summary:
Microsoft ADO: 30073317
GNMI needs to use role to in API operations, for example, read-only user can't call write API.
Modify current end to end test, default role should be rw.

Use readwrite as the default role

---

.azure-pipelines/pytest-collect-only.yml
azure-pipelines.yml

Summary:
1. use sonic-ubuntu-1c instead of sonic-common.
2. Fix docker run command to reuse agent.

Deprecate sonic-common agent pool.

---

tests/qos/files/qos_params.gb.yaml

Summary:
https://migsonic.atlassian.net/browse/MIGSMSFT-855
Fix failure of case qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark[multi_dut_shortlink_to_longlink-wm_pg_shared_lossless]
Update pkts_num_trig_pfc of wm_pg_shared_lossless in yaml file.
pkts_num_trig_pfc in this case means the maximum buffers in queue, which is 14812.
```
Source queue counters for Ethernet0 tc 3:
SQ buffer counter 14812
SQ congestion state Xoff
SQ headroom counter in buffers 1156 (trigger ingress drop)
```
Verified it in T2 testbed.
```
------------ generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark_2025-01-08-21-54-09.xml ------------
------------------------------------------------------- …
```

update pkts_num_trig_pfc of wm_pg_shared_lossless in yaml file

---

tests/arp/test_arp_extended.py

Summary:
This PR temporarily skips test_proxy_arp when the test is executed on a KVM testbed and IPv6 packets are used for testing. The reason is that this test case is currently blocking sonic-swss submodule from being updated.
Unblocking sonic-swss submodule update.
Skipped the failing test case when the test is executed on a KVM testbed and IPv6 packets are used for testing.
Tested on a local dualtor KVM testbed.
The test is only skipped on VS switches.
N/A
N/A

Temporarily skipping a failing test in test_arp_extended.py

---

.azure-pipelines/pytest-collect-only.yml
azure-pipelines.yml

Summary:
1. Use sonic-ubuntu-1c instead of sonic-common.
2. Fix docker run command to reuse agent.

Deprecate sonic-common agent pool. (#16385)

---

tests/bgp/test_bgp_port_disable.py

Summary:
Issue:
Several TCP ports bound to localhost are potentially vulnerable and need to be secured.
Solution:
A combination of "Iptables Control Table" and "Start FRR Daemons with Parameter -P 0" is implemented to secure the ports.
[Pull request 11395282: add iptables cmd - Repos](https://msazure.visualstudio.com/One/_git/Networking-acs-buildimage/pullrequest/11395282)
[Disabling ports by adding parameter ‘-P 0’ by yyynini · Pull Request #21296 · sonic-net/sonic-buildimage](https://github.com/sonic-net/sonic-buildimage/pull/21296)
This testcase is designed to address the concerns about TCP ports bound to localhost on the device. The aim is to ensure that the related ports are either being disabled or restricted, preventing from unauthorised access. 
To test …

Port disable for vulnerable daemons testgap

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
https://msazure.visualstudio.com/One/_workitems/edit/30281490/?view=edit
Testcase fails under certain conditions in dualtor.
The XFail Conditions PR: https://github.com/sonic-net/sonic-mgmt/pull/15811
code: [[ptf] Consider only expected packets for timeout by vkjammala-arista · Pull Request #21150 · sonic-net/sonic-buildimage](https://github.com/sonic-net/sonic-buildimage/pull/21150/files)
[add dualtor fixture for test_dhcp_relay_stress by yyynini · Pull Request #16171 · sonic-net/sonic-mgmt](https://github.com/sonic-net/sonic-mgmt/pull/16171)
Testcase passed in dualtors.

Update test_dhcp_relay_stress Testcase: Remove XFail Conditions for dualtor

---

tests/platform_tests/test_intf_fec.py

As the FEC mode can be set to "none" as well, instead of setting the FEC mode to rs when testing the configuration, set the FEC mode to existing configuration of the interface.
Summary:
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/16120
Verified the fix on lab testbed where the FEC mode is set to "none" and the test case is failing before the fix.

test_config_fec_oper_mode: Set the fec_mode to align with the current configuration of the interface.

---

tests/common/config_reload.py

Summary:
This PR is to add some additional wait for BGP up on multi-ASIC vs platform.
We are seeing the BGP sessions are up after around 8 minutes after config reload on multi-asic vs platform. This issue leads to the flakiness in PR test.
For now, the issue is only in `202405` branch and vs testbed.
This PR is to add some additional wait for BGP up on multi-ASIC vs platform.
Add an additional wait.
The change is verified by PR test.
VS platform only.

[202405] Add additional wait for BGP up on multi-ASIC vs platform

---

tests/common/snappi_tests/traffic_generation.py
tests/snappi_tests/multidut/ecn/files/multidut_helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_runtime_traffic_helper.py

Summary:
In snappi tests, we have a number of tests with UDP streams. We need them to be counted sequentially instead of random, or any other order. This PR addresses some of the mistakes in the udp port count logic.
The tests fail in cisco-8000 due to backplane bandwidth limitations. The backplane bandwidth limit will be avoided if the number of streams we use in the traffic is large enough to cause load balancing across the backplane, so that many backplane ports are used instead of just one. This PR addresses some of the script locations where the udp port numbers are not correctly calculated.
Ran it on my TB, with a -e --count=2 option, for repeating the tests 2 times:
```
=========================================================================================================== …
```

snappi: T2: Convert all udp port numbers to serial sequence.

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary: K8s feature is not enabled for master branch, so need to filter the master branch for nightly test. Update the conditional mark file to filter master branch.
Avoid k8s case nightly test failure on master branch
Update conditional mark file to filter master branch
Run test on sonic image built from master branch, check if the k8s case is skipped.

Skip k8s test case for master branch

---

azure-pipelines.yml

In #15666, we introduced a new approach to PR testing called `Impacted Area-Based PR Testing`. This model will be rolled out in phases. This PR represents step 2 of the rollout, specifically implementing the t1-lag PR checker partly.
Summary:
In #15666, we introduced a new approach to PR testing called `Impacted Area-Based PR Testing`. This model will be rolled out in phases. This PR represents step 2 of the rollout, specifically implementing the t1-lag PR checker partly.

[Impacted Area Based PR testing] Roll out t1-lag PR checker.

---

.azure-pipelines/pr_test_scripts.yaml

Summary:
But some traffic test can't be tested on KVM platform, we need to skip traffic test if needed.
Test in Elastictest, only 1 test failed in sanity check, not related to testcase:
TestbedName | FilePath | TestCase | SuccessCount | FailureCount | TotalTests | SuccessRate
vms-kvm-dual-t0 | dualtor/test_mux_port_iptables_entries.py | test_mux_port_iptables_entries | 27 | 1 | 28 | 0.9643
vms-kvm-dual-t0 | dualtor/test_mux_port_iptables_entries.py | test_multivlan_mux_port_iptables_entries | 27 | 0 | 27 | 1
Add dualtor mux port iptables entries test to PR test

Add dualtor mux port iptables entries test to PR test

---

.azure-pipelines/pr_test_scripts.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Dash tests is a important part in PR test coverage, currently most of dash tests do not support running on KVM because some configuration and traffic tests can't be tested on KVM platform.
Add dash tests to PR test and skip unsupported tests in conditional mark with issue.

Add dash tests to PR test and skip unsupported tests in conditional mark with issue

---

tests/tacacs/test_ro_disk.py

Enhance Read-only disk test case, verify remote user can do TSA/TSB after monit script mitigate issue.
Verify after monit fix login issue ,remote user can run TSA/TSB command.
- Microsoft ADO: 28263221
Check remote user can do TSA/TSB after monit script mitigate issue.
Enhance Read-only disk test case, verify remote user can do TSA/TSB after monit script mitigate issue.

Enhance Read-only disk test case, verify remote user can do TSA/TSB after monit script mitigate issue.

---

tests/pfcwd/cisco/default_pfc_time.py
tests/pfcwd/cisco/set_pfc_time.py
tests/pfcwd/conftest.py
tests/pfcwd/test_pfcwd_all_port_storm.py
tests/pfcwd/test_pfcwd_function.py
tests/pfcwd/test_pfcwd_timer_accuracy.py

Summary:
Fixes the flakiness of pfc_gen in pfcwd scripts for cisco-8000. We use a new debug CLI script to force the DUT to wait longer in case of a miss in pfc packets from the fanout due to pfc_gen script. So even if the pfc_gen/fanout misses a couple of pfc frames to DUT, the dut would still not send out data packets.
Flakiness of pfc-gen. Particularly with 400G links.
We have added a new dshell based script that will force the DUT to wait before transmitting data in case of a miss in pfc pause frames.
Ran on our duts, with 100G and 400G.
The new fix specific only to cisco-8000.

Add pfc-timer-set to 500mS for pfcwd tests.

---

.azure-pipelines/impacted_area_testing/calculate_instance_number.py

In the previous implementation, we retrieved 5 test case entries from Kusto to calculate the total running time of a script. However, the query included the condition `| where FilePath == '{script}'`, and since each script may contain multiple test cases, this approach only sampled 5 random test cases from the script. As a result, the calculated average running time was inaccurate. In this PR, we resolve the issue by selecting the most recent 5 test plans instead, ensuring that we account for all test cases executed in the script.
Summary:
In the previous implementation, we retrieved 5 test case entries from Kusto to calculate the total running time of a script. However, the query included the condition `| where FilePath == '{script}'`, and since each script may contain …

 [Impacted Area Based PR testing] Fix script timing with recent test plans

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

The script `dualtor_io/test_tor_bgp_failure.py` has recently been failing frequently on the KVM testbed. This issue is being tracked in #16448. As a temporary measure, we have applied a conditional mark to skip this test in PR checks.
Summary:
The script `dualtor_io/test_tor_bgp_failure.py` has recently been failing frequently on the KVM testbed. This issue is being tracked in #16448. As a temporary measure, we have applied a conditional mark to skip this test in PR checks.
As a temporary measure, we have applied a conditional mark to skip this test in PR checks.

Skip script `dualtor_io/test_tor_bgp_failure.py` temporarily in PR test. 

---

tests/qos/qos_sai_base.py

Optimize the `qos/test_qos_sai.py` test to reduce the running time.
Summary:
The running time of the `qos/test_qos_sai.py` test is too long (~9h) on T2 chassis so we wanted to reduce the running time. With this implementation, the running time will be reduced to (~7.5h)
I ran the updated code and can confirm it's working well on T2 chassis: Elastictest [link](https://elastictest.org/scheduler/testplan/67802e043dd5199fbee9dcbc?leftSideViewMode=detail&testcase=qos%2Ftest_qos_sai.py&type=console). The 2 DWRR failures are expected, which will be fixed after #16199 
I also ran a T1 regression test to confirm: Elastictest [link](https://elastictest.org/scheduler/testplan/67806217745d47c6b42e53b9?leftSideViewMode=detail&testcase=qos%2Ftest_qos_sai.py&type=co …

refactor: optimize qos sai test

---

tests/common/dhcp_relay_utils.py
tests/generic_config_updater/test_dhcp_relay.py

Summary:
In gcu dhcp_relay test, it would add 2 vlans with 4 dhcp servers. Previously all 8 dhcp servers are added by cli separately, it would restart dhcp_relay container 8 times, which would cause dhcp_relay container is not running in gcu test in some low performance devices.
Use sonic-db-cli to add dhcp servers, then manually resetart dhcp_relay container once.
Run tests

[gcu][dhcp_relay] Fix dhcp_relay container is not running in gcu test

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Skip test_dhcp_relay_restart_with_stress in vs due to flaky issue https://github.com/sonic-net/sonic-mgmt/issues/16450
Skip in condition mark
Run test

[dhcp_relay] Skip test_dhcp_relay_restart_with_stress in vs

---

tests/snmp/test_snmp_link_local.py

Summary:
On Nokia-7215 platform, we observed below flaky failure:
```
invocation = {'module_args': {'_raw_params': 'docker exec snmp snmpget -v2c -c public fe80::...
_ansible_no_log = None
stdout =
stderr =
Timeout: No Response from fe80::xxxx%eth0.
```
The root cause is that Nokia-7215 has low performance and the `snmpget` command is issued before snmpagent fully start.
To resolve this issue, I added a wait_until to ensure snmpagent already listening on the link-local IP address.
On Nokia-7215 platform, we observed below flaky failure:
```
Timeout: No Response from fe80::xxxx%eth0.
```
The root cause is that Nokia-7215 has low performance and the `snmpget` command is issued before snmpagent fully start.
To resolve this issue, I added a wait_until to ensure snmpagent already listening on …

SNMP link-local test: wait until snmp agent fully start

---

tests/qos/qos_sai_base.py
tests/saitests/py3/sai_qos_tests.py

Summary:
Fixes # 16314
The recent commit for dwrr works for multi-asic only. This PR handles the single asic platforms.
Making sure to use the correct container to use for single asic tests.
Not done yet. @kevinskwang , @yejianquan : Can you pls try this out ? I will try it when I get the testbed access.
For cisco-8000 only.

qos-sai:dwrr:cisco-8000:Handle non-multiasic part as well for the dshell-script change.

---

tests/qos/qos_sai_base.py
tests/qos/test_qos_sai.py
tests/saitests/py3/sai_qos_tests.py

Summary:
Fixes the flakiness of DWRR testcase. The PR adds a new fixture that slows down the scheduler without changing the underlying algorithm. This allows the dWRR test to pass consitently.

Porting 15718 to 202405: Adding a fixture to set scheduler to slower speeds and revert it back.

---

ansible/roles/fanout/tasks/fanout_sonic.yml
ansible/roles/fanout/tasks/sonic/fanout_sonic_202405.yml
ansible/roles/fanout/templates/sonic_deploy_202405.j2

Summary:
Current 2024 sonic fanout is using 202311 template. 
However, with TH5, we need to skip BUFFER_PG config for now. Hence, replaced the soft link with an actual file.
Support 202405 and 202411 image.
replace soft link with hard copy. and modified it to suit 202405 requirement.
Tested it locally.

add fanout support for 202405 and 202411

---

tests/pfcwd/test_pfcwd_timer_accuracy.py

Summary:
29970341
Since the test environment limitation, sometimes, pfcwd could not be triggered expectedly.
It would cause exception failure due to grep pfc watchdog syslog return failure.
Handle the exception, return failure instead of raise an exception.
inject an failure and run the case locally.
```
pfcwd/test_pfcwd_timer_accuracy.py::TestPfcwdAllTimer::test_pfcwd_timer_accuracy[bjw-can-7050qx-1] 
---------------------------------------------------------------------------------------------------------------------- live log call -----------------------------------------------------------------------------------------------------------------------
05:57:06 test_pfcwd_timer_accuracy.retrieve_times L0371 WARNING| ##### Randomly skip timestamp 05:56:16.168697 parsing for …
```

[test_pfcwd_timer_accuracy] handle exception during grep log

---

tests/common/helpers/pfcwd_helper.py
tests/pfcwd/test_pfcwd_warm_reboot.py

Summary:
29870655
Script log Analyzer timestamp is 2025-01-07 13:26:55.978427 while the real detect timestamp in syslog is Jan  7 13:27:18.132683.
Need delay more time to grep the syslog
`2025 Jan  7 13:26:55.996909 bjw2-can-7260-2 DEBUG extract_log combine_logs from file /var/log/syslog create time 2025-01-07 13:26:55.978427, size 4236007`
`syslog:23447:2025 Jan  7 13:27:18.132683 bjw2-can-7260-2 NOTICE swss#orchagent: :- report_pfc_storm: PFC Watchdog detected PFC storm on port Ethernet24, queue index 3, queue id 0x1500000000014d and port id 0x1000000000001`
Increase the delay time and add some debug log in script
Use elastic to run the case on 7060 and 2700, passed.
https://elastictest.org/scheduler/testplan/67808a9a572c09d3aa482375 …

[test_pfcwd_wb] increase delay time for detecting pfcwd storm

---

ansible/roles/test/files/ptftests/py3/generic_hash_test.py
tests/hash/generic_hash_helper.py

Cisco support different HASH algorithms and fields as of now than default
**Some issues were because CISCO was not supporting certain hash algorithms and Fields which led to issues like below** 
```
/12/2024 03:58:04 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 513, in __call__
return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 120, in _hookexec
return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
File …
```

[test_genric_hash.py]: cisco platform checks fix

---

ansible/ansible.cfg
tests/platform_tests/fwutil/conftest.py
tests/platform_tests/fwutil/fwutil_common.py
tests/platform_tests/fwutil/test_fwutil.py

Summary:
This PR contains the following enhancements:
1. Remove the randomization in selecting component, instead, parameterize the test by the components type.
2. Add the FPGA component for Nvidia sn4280 platform.
3. Increase the ServerAliveCountMax in ansible config to keep the ssh connection when buring the FPGA(it takes 15~20 mins with no data transferred in the channel).
4. When testing the install test cases, even if we only have one version of the component, still run the test.
Enhance the fwutil test.
See the summary.
Run the test on multiple testbeds, all passed.

Enhance the fwutil test

---

tests/snmp/test_snmp_fdb.py

Summary:
`test_snmp_fdb_send_tagged` is flaky on dualtor testbed.
Two improvements:
1. flush fdb table on the correct DUT.
2. check the fdb table first to ensure the fdb table is correctly populated before checking snmp, also increase the timeout.
```
snmp/test_snmp_fdb.py::test_snmp_fdb_send_tagged PASSED                                                                                                                                                                                                                [100%]
================================================================================================================== 1 passed, 1 warning in 377.48s (0:06:17) …
```

Stabilize `test_snmp_fdb_send_tagged`

---

tests/common/snappi_tests/snappi_fixtures.py

Summary: Removing unused fixtures: get_multidut_tgen_peer_port_set and
get_multidut_snappi_ports from snappi_fixtures.py
https://github.com/sonic-net/sonic-mgmt/issues/16015
deleted the code

[#16015 Fix]: Cleaning up unused code from snappi_fixtures

---

.azure-pipelines/impacted_area_testing/calculate_instance_number.py

In PR #16437, we addressed the script timing issue by selecting the five most recent test plans. However, this caused an incorrect ActualCount, as it was summarizing the number of test cases instead of the test scripts. Since the number of test scripts matches the number of test plans, this PR updates the query to correctly count the test plans.
Summary:
In PR #16437, we addressed the script timing issue by selecting the five most recent test plans. However, this caused an incorrect ActualCount, as it was summarizing the number of test cases instead of the test scripts. Since the number of test scripts matches the number of test plans, this PR updates the query to correctly count the test plans.
Since the number of test scripts matches the number of test plans, this PR …

[Impacted Area Based PR testing] Fix actually count calculation for test scripts.

---

tests/iface_namingmode/test_iface_namingmode.py
tests/route/test_route_perf.py
tests/telemetry/test_telemetry.py
tests/telemetry/test_telemetry_cert_rotation.py

In PR #15162, we introduced new topology markers for specific subtypes, such as `t1-multi-asic`, and applied these markers to the relevant test scripts. However, some newly added test scripts are missing these markers. To prepare for enabling the multi_asic checker in Impacted Area-Based PR testing, this PR adds the appropriate markers to those scripts.
Summary:
In PR #15162, we introduced new topology markers for specific subtypes, such as `t1-multi-asic`, and applied these markers to the relevant test scripts. However, some newly added test scripts are missing these markers. To prepare for enabling the multi_asic checker in Impacted Area-Based PR testing, this PR adds the appropriate markers to those scripts.
Add the appropriate markers to newly added scripts.

Add topology marks `t1-multi-asic` for some subtype topologies. 

---

tests/common/gu_utils.py
tests/generic_config_updater/test_incremental_qos.py
tests/generic_config_updater/test_pfcwd_interval.py

Generic config update module tests are skipped for marvell-teralynx platform and enabling same
Summary:
Enabling generic_config_updater tests for marvell-teralynx platform

Enabling generic_config_updater tests for marvell-teralynx platform

---

ansible/group_vars/ptf/secrets.yml
ansible/group_vars/ptf_host/secrets.yml
ansible/roles/vm_set/tasks/add_topo.yml
ansible/roles/vm_set/tasks/announce_routes.yml
ansible/roles/vm_set/tasks/ptf_change_mac.yml
ansible/roles/vm_set/tasks/ptf_portchannel.yml
ansible/roles/vm_set/tasks/renumber_topo.yml
ansible/roles/vm_set/tasks/start_ptf_tgen.yml
ansible/roles/vm_set/tasks/start_tacacs_daily_daemon.yml
ansible/roles/vm_set/tasks/update_ptf_password.yml
ansible/veos_vtb
tests/scp/test_scp_copy.py

Summary:
The PTF container is always using default password. If the PTF container is on same bridge with the host server's management IP, then it is easily accessible from other host servers. This is not secure enough. We need to support alternate password for the PTF container and password rotation.
This change improved the ansible related code to support accessing the PTF containers using the `multi_ssh_pass` ansible plugin. Then we can specify alternate passwords for the PTF container. When alternate passwords are specified, the default password of PTF container is updated after PTF creation.
Tested remove-topo/add-topo/restart-ptf on KVM and physical testbed.

Support alternate password for PTF container

---

tests/common/dhcp_relay_utils.py
tests/generic_config_updater/test_dhcp_relay.py

In gcu dhcp_relay test, it would add 2 vlans with 4 dhcp servers. Previously all 8 dhcp servers are added by cli separately, it would restart dhcp_relay container 8 times, which would cause dhcp_relay container is not running in gcu test in some low performance devices.
Use sonic-db-cli to add dhcp servers, then manually resetart dhcp_relay container once.
Run tests
Summary:
Manually cherry-pick and resolve conflict of this PR: https://github.com/sonic-net/sonic-mgmt/pull/16460

[202405][gcu][dhcp_relay] Fix dhcp_relay container is not running in gcu test (#16460)

---

tests/dhcp_relay/test_dhcpv6_relay.py

Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/16344
We add wait LLA logic in dhcp6relay with https://github.com/sonic-net/sonic-dhcp-relay/pull/52
Current PR is to add test for it to verify dhcp6relay would work well when LLA is missing
Modify `test_interface_binding`:
1. Remove LLA for Vlans
2. Restart dhcp_relay container
3. Verify whether sockets for LLA are not established
4. Add LLA back
5. Verify whether sockets for LLA are established
Run test_dhcpv6_relay.py
```
collected 6 items …
```

[dhcp_relay] Add test case to verify dhcp6relay LLA waiting logic

---

tests/test_parallel_modes/cisco_t2_8800.json

Disable parallel run for `tacacs/test_ro_disk.py` test.
Summary:
Fixes # (issue) Microsoft ADO 30848681
The `tacacs/test_ro_disk.py` test is using a special reboot process on the DUT and if we run this test with parallel run enabled, the LCs might not be ready after Supervisor's reboot. Therefore, we need to disable parallel run for this test.

chore: disable parallel run for ro disk test

---

ansible/library/snmp_facts.py
tests/snmp/test_snmp_cpu.py

Summary:
Fixes #30112399
Fix test_snmp_cpu failures on Cisco chassis.
1. Incorporate timeout setting in all SNMP commands
2. Increase chassis SNMP request timeout to 20s
Run on Cisco chassis and it stably pass.

[test_snmp_cpu]Use timeout configuration in all SNMP request, increase SNMP request timeout to 20

---

tests/common/config_reload.py
tests/common/plugins/sanity_check/checks.py
tests/common/reboot.py
tests/tacacs/test_ro_disk.py

Cisco chassis used to be unstable months ago, so updated the wait time of sshd ready to 600s, and service ready to 900s.
After the image became stable, we can reduce the time to:
sshd ready: 420s
service ready: 600s
Will keep monitoring and see whether we can reduce the wait time to align with t0/t1 in the future.
Summary:
Cisco chassis used to be unstable months ago, so updated the wait time of sshd ready to 600s, and service ready to 900s.
After the image became stable, we can reduce the time to:
sshd ready: 420s
service ready: 600s
Will keep monitoring and see whether we can reduce the wait time to align with t0/t1 in the future.
In the nightly test, the configuration works well.

[Chassis] Reduce wait/timeout time for chassis

---

tests/common/helpers/pfcwd_helper.py
tests/pfcwd/test_pfcwd_warm_reboot.py

Script log Analyzer timestamp is 2025-01-07 13:26:55.978427 while the real detect timestamp in syslog is Jan 7 13:27:18.132683. Need delay more time to grep the syslog
2025 Jan  7 13:26:55.996909 bjw2-can-7260-2 DEBUG extract_log combine_logs from file /var/log/syslog create time 2025-01-07 13:26:55.978427, size 4236007
syslog:23447:2025 Jan  7 13:27:18.132683 bjw2-can-7260-2 NOTICE swss#orchagent: :- report_pfc_storm: PFC Watchdog detected PFC storm on port Ethernet24, queue index 3, queue id 0x1500000000014d and port id 0x1000000000001
Increase the delay time and add some debug log in script
Use elastic to run the case on 7060 and 2700, passed. https://elastictest.org/scheduler/testplan/67808a9a572c09d3aa4 …

 [202411] backport (#16445) [test_pfcwd_wb] increase delay time for detecting pfcwd storm 

---

tests/arp/test_stress_arp.py

Modifying condition check in apr stress case for incomplete arp
The actual number of arp request sent is tgt_conntrack_cnt but in verification it is multiplied by 0.1.
This is causing the test to fail and hence modifying the condition check.
Summary:

Modifying condition check in apr stress case for incomplete arp

---

ansible/templates/minigraph_dpg_asic.j2

Signed-off-by: Anand Mehra anamehra@cisco.com
Summary:
Fixes # [(issue)]https://github.com/sonic-net/sonic-mgmt/issues/16463
delopy-mg fails to create minigraph.xml for LCs on a chassis-packet Chassis. The creation fails in minigraph_dpg_asic.j2 
```
{% include 'minigraph_cpg.j2' %}
{% include 'minigraph_dpg.j2' %}
{% include 'minigraph_png.j2' %}
{% include 'minigraph_device.j2' %}
{% include 'minigraph_meta.j2' %}
{% include 'minigraph_link_meta.j2' %}
<Hostname>{{ inventory_hostname }}</Hostname>
<HwSku>{{ hwsku }}</HwSku>
</DeviceMiniGraph>
): coercing to Unicode: need string or buffer, list found"}  
```
https://github.com/sonic-net/sonic-mgmt/pull/14595 introduced changes for smarswitch and caused this regression.
Fixes minigraph_dpg_asic.j2 template to comply with …

[chassis]: Fix minigraph_dpg_asic template for Chassis LCs

---

tests/qos/qos_sai_base.py

Description of PR:
This fix is to address the issue introduced by smartswicth interafces Ethernet-BP0 to Ethernet-BP7 .
These new interfaces are breaking test_qos_sai.py test cases. 
Summary:Excluded the DPU interafces Ethernet-BP0 to Ethernet-BP7 from the minigraph_facts
- [X ] Bug fix
exclude new DPU interfaces Ethernet-BP0 to Ethernet-BP7 
The new DPU interfaces Ethernet-BP0 to Ethernet-BP7 is breaking test_qos_sai.py regression.
Excluded the DPU interafces Ethernet-BP0 to Ethernet-BP7 from the minigraph_facts from src_mgFacts dictionary
Ran complete test_qos_sai.py regression under sonic-mgmt.
Verified and Tested on Cisco-8102-28FH-DPU-O-T1.
it should not impact other vendor platforms.
topo_t1_28_lag.yml
SKIPPED [6] qos/test_qos_sai.py:1793: multi-dut is not supported …

Excluded the DPU interafces Ethernet-BP0 to Ethernet-BP7 from the minigraph_facts

---

tests/pc/test_po_update.py

Summary:
Master PR https://github.com/sonic-net/sonic-mgmt/pull/14842
The Test Cases focuses on the below PR Changes of lagid allocation to portchannel and new SYSTEM_LAG_IDS_FREE_LIST
https://github.com/sonic-net/sonic-platform-daemons/pull/542
https://github.com/sonic-net/sonic-swss/pull/3303
https://github.com/sonic-net/sonic-buildimage/pull/20369
This PR is dependent on the above mentioned PR.
Verification of the new feature of LAG ID allocation to PortChannel and new list of SYSTEM_LAG_IDS_FREE_LIST
The test case verifies traffic flow between all port channels in a full mesh topology. It begins with a system reboot to allocate the lower series of LAG IDs and validate the SYSTEM_LAG_IDS_FREE_LIST. Next, the LAG IDs are incremented through temporary port channel additions and …

[Cherry-pick 202405] New TC for PC Test on higher lag ids

---

tests/telemetry/test_telemetry.py

Fix `test_sysuptime` fails with error 
Summary:
Fixes # NA
Fix broken test
Fix format parsing before type conversion
Tested on 7050cx3
None
NA

Fix test_sysuptime failure

---

tests/pfcwd/test_pfcwd_function.py

Summary:
The issue was introduced by PR https://github.com/sonic-net/sonic-mgmt/pull/15772
The ASIC check is not working as expected because of the syntax error in the code. It should be `in` instead of `==`
https://github.com/sonic-net/sonic-mgmt/blob/21dbd804383d5d1e44b32e0f22c8d22b0f427a58/tests/pfcwd/test_pfcwd_function.py#L757
The issue will cause PFCWD function not stable on some platform.
This PR is to fix a syntax issue in `test_pfcwd_function.py`.
Fix the syntax.
```
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_actions[bjw2-can-4 …
```

Fix ASIC check in test_pfcwd_function

---

tests/common/snappi_tests/common_helpers.py

The clear_counter function in tests/common/snappi_tests/common_helper.py used dut.shell to clear the sonic counters.
However, the dut.shell inherently uses sudo, thus sonic clear counters in non-sudo mode were not getting cleared.
Replacing dut.shell with dut.command to ensure that sonic-clear counters works in both SUDO and non-SUDO mode.
Summary:
Fixes #16270 
Replacing dut.shell with dut.command to clear the counters in both SUDO and non-SUDO mode.
Replaced dut.shell with dut.command.
Local clone.
```
AzDevOps@68684a43ec9e:/data/tests$ date;python3 -m pytest --inventory ../ansible/ixia-sonic --host-pattern ixre-egl-board71,ixre-egl-board72 --testbed ixre-chassis17-t2 --testbed_file ../ansible/testbed.csv --log-cli-level info --log-file-level info --kube_master unset --showlocals -ra …
```

[Snappi] Replacing dut.shell with dut.command for clearing counters in snappi clear_counter function

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Now test_conditional_mark uses the longest match mechanism to search the matched scripts/cases.
In mark file, `hash/test_generic_hash.py::test_lag_member_flap[CRC-INNER_IP_PROTOCOL` is longer than `hash/test_generic_hash.py::test_lag_member_flap`, so even on Broadcom testbed, it will still run `test_ecmp_and_lag_hash[CRC_CCITT-INNER_IP_PROTOCOL-ipv4-ipv6-vxlan]`, which should be skipped actually.
Add Broadcom asic type for those longer cases, to make sure those test_generic_hash cases should be skipped on broadcom platforms.
Run test_generic_hash on broadcom testbed.
```
plugins: metadata-3.1.1, allure-pytest-2.8.22, forked-1.6.0, repeat-0.9.3, html-4.1.1, ansible-4.0.0, xdist-1.28.0
collected 10 items …
```

Skip some test_generic_hash cases for Broadcom platforms

---

tests/fdb/test_fdb_mac_learning.py

Summary:
`testFdbMacLearning` is flaky on dualtor.
Let's toggle the mux ports to the random selected DUT, so all packets will be forwarded to it.
```
fdb/test_fdb_mac_learning.py::TestFdbMacLearning::testFdbMacLearning PASSED                                                                                                                                                                                            [100%]
================================================================================================================= 1 passed, 3 warnings in 1558.19s (0:25:58) =================================================================================================================
```

[dualtor] Fix `testFdbMacLearning`

---

tests/gnmi/test_gnoi_system.py

Create a new file for testing GNOI System API and bootstrap it with a simple test for System.Time
Summary:
Create a new file for testing GNOI System API and bootstrap it with a simple test for System.Time
Create a new file for testing GNOI System API and bootstrap it with a simple test for System.Time
Run on KVM

Add test_gnoi_system.py with a simple test for System.Time.

---

tests/common/dualtor/data_plane_utils.py
tests/common/plugins/sanity_check/__init__.py

Add sanity check command to debug PTF unreachable issue.
TACACS test case failed because PTF device unreachable, need more info to debug.
- Microsoft ADO: 30626367
Add sanity check command to debug PTF unreachable issue.
Add sanity check command to debug PTF unreachable issue.

Add sanity check command to debug PTF unreachable issue

---

ansible/library/announce_routes.py
tests/common/testbed.py

Summary:
This PR is to support `smartswitch` in `get_testbed_type`.
Before this change, the WARNING message shows up in each run.
This PR is to support `smartswitch` in `get_testbed_type`.
Update the regex in `get_testbed_type` to include `smartswitch.
Verified by manually run a test. The warning message doesn't show up any more.
No.

Support smartswitch in get_testbed_type and announce_routes

---

tests/acl/test_acl.py
tests/common/reboot.py

The reboot process for chassis will need longer time to wait for the BGP to be established. For example, the `acl/test_acl.py` can be flaky if we are not waiting BGP long enough. Therefore, we are introducing `wait_for_bgp` option to the `reboot()` function. 
Summary:
Fixes # (issue) Microsoft ADO 30862178
We found that tests like `acl/test_acl.py` can be flaky if we are not waiting for BGP long enough on chassis after reboot. Therefore, we want to mimic what we have in `config_reload()` to also introduce the `wait_for_bgp` option to the `reboot()` function.
I ran the updated acl test code and can make sure it's working well.

feat: add wait_for_bgp option to reboot

---

tests/ipfwd/test_nhop_group.py

Test ipfwd/test_nhop_group.py::test_nhop_group_interface_flap failing as the fanout port was configured no-shut instead of shutdown. This was done by PR15531 and same reverted to pass this test in this PR.
Below PR changed the fanout port shut to no_shut as part of adding other condition check.
https://github.com/sonic-net/sonic-mgmt/pull/15531
Summary:

Revert wrong change done by PR15531 shut to noshut

---

tests/platform_tests/api/test_sfp.py

Summary:
Some sfp transceivers have known issues with lpmode test, where it fails to set_lpmode successfully. After discussion, we need a firmware from optics vendor to fix this issue. 
Therefore, we will temporarily skip this set_lpmode test for known manufacturer and 400G combination until fix is available.
Temporarily skip known test failure
check conditions to skip the test
platform_tests/api/test_sfp.py::TestSfpApi::test_lpmode[xxx-lc4] 
03:30:49 test_sfp.test_lpmode                     L0795 WARNING| test_lpmode: Skipping transceiver 0 (not applicable for this transceiver type)
03:30:49 test_sfp.test_lpmode                     L0795 WARNING| test_lpmode: Skipping transceiver 1 (not applicable for this transceiver type)
03:30:49 test_sfp.test_lpmode                     L0795 WARNING| …

Temporarily skip lpmode test for some transceivers with known issue

---

tests/common/devices/multi_asic.py
tests/common/platform/interface_utils.py
tests/common/platform/transceiver_utils.py
tests/common/port_toggle.py
tests/platform_tests/api/test_sfp.py
tests/platform_tests/sfp/test_sfputil.py

Summary:
Fixes interface stays down after tests/platform_tests/api/test_sfp.py::sfp_reset()
And causing error during `shutdown_ebgp` fixture teardown.
keep interface up after sfp_reset if it's T2 and QSFP-DD SFP.
flap the interface after sfp_reset to restore the interface state.
passed on physical testbed with 
```
admin@svcstr2-8800-lc1-1:~$ sudo sfputil show eeprom -d -p Ethernet0
Ethernet0: SFP EEPROM detected
...
Application Advertisement: 400GAUI-8 C2M (Annex 120E) - Host Assign (0x1) - Active Cable assembly with BER < 5x10^-5 - Media Assign (0x1)
CAUI-4 C2M (Annex 83E) - Host Assign (0x1) - Active Cable assembly with BER < 5x10^-5 - Media Assign (0x1)
CMIS Revision: 4.0
Connector: No separable connector
Encoding: N/A
Extended Identifier: Power Class 5 (10.0W Max)
Extended RateSelect …
```

flap interface after sfp reset

---

tests/acl/test_acl.py
tests/common/reboot.py

The reboot process for chassis will need longer time to wait for the BGP to be established. For example, the `acl/test_acl.py` can be flaky if we are not waiting BGP long enough. Therefore, we are introducing `wait_for_bgp` option to the `reboot()` function. 
Summary:
Fixes # (issue) Microsoft ADO 30862178
We found that tests like `acl/test_acl.py` can be flaky if we are not waiting for BGP long enough on chassis after reboot. Therefore, we want to mimic what we have in `config_reload()` to also introduce the `wait_for_bgp` option to the `reboot()` function.
I ran the updated acl test code and can make sure it's working well.

[manual] [PR:16542] feat: add wait_for_bgp option to reboot

---

tests/dhcp_relay/test_dhcpv6_relay.py

Summary:
Manually cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/16554 since the dependency fucn `restart_dhcp_service` is not included in 202405
We add wait LLA logic in dhcp6relay with sonic-net/sonic-dhcp-relay#52 Current PR is to add test for it to verify dhcp6relay would work well when LLA is missing
Modify test_interface_binding:
Remove LLA for Vlans
Restart dhcp_relay container
Verify whether sockets for LLA are not established Add LLA back
Verify whether sockets for LLA are established
Run test_dhcpv6_relay.py

[202405][dhcp_relay] Add test case to verify dhcp6relay LLA waiting logic (#16494)

---

tests/override_config_table/test_override_config_table.py
tests/override_config_table/test_override_config_table_masic.py

ADO: 30864778
Summary:Remove test for no yang supported table test
We plan on strict yang enforcement on config CLI. Thus it will fail for non-yang supported NEW_FEATURE_TABLE
Remove test for tables without yang model
E2E test

[override] Remove table test which has no YANG model

---

ansible/library/announce_routes.py
ansible/roles/vm_set/tasks/announce_routes.yml

Summary:
In this PR, we added new features to make announce routes script more powerful.
1. Variable ipv6 address pattern, previously, we are hardcoding ipv6 prefix with pattern 20%02X:%02X%02X:0:%02X::/64, now, it can be set in script or topology file.
2. Selectable exabgp setting up and routes generation. now we can add flag in topology file to enable ipv4 or ipv6, or disable ipv4 or ipv6.
3. Aggregated routes on peers. At the VM definition in topology file, we now support define aggregate route on the VM.
To make route announcement more powerful.
Add routes generation switch, aggregate routes and variable ipv6 address pattern
Verified on 7215 testbed with t0 and t1 topologies.

[testbed] announce routes with routes generation switch, aggregate routes and variable ipv6 address pattern

---

tests/common/reboot.py

Summary:
Revert double root bug introduced in #16348
Revert bug introduced in #16348 that performs 2 reboots instead of one (also performed in line 284/283)
Remove one instance of reboot
N/A
N/A
N/A
N/A

Fix double reboot bug introduced in #16348

---

.azure-pipelines/impacted_area_testing/constant.py
.azure-pipelines/impacted_area_testing/get_test_scripts.py
azure-pipelines.yml

In #15666, we introduced a new approach to PR testing called Impacted Area-Based PR Testing. This model will be rolled out in phases. This PR implement the left PR checkers.
Summary:
In #15666, we introduced a new approach to PR testing called Impacted Area-Based PR Testing. This model will be rolled out in phases. This PR implement the left PR checkers.
Roll out the left PR checkers. 
Test by pipeline itself, to see if PR checkers are running as expected.

[Impacted Area Based PR testing] Roll out rest of the PR checkers

---

.azure-pipelines/baseline_test/baseline.test.template.yml

Reverts sonic-net/sonic-mgmt#16241
I think it's better to run dualtor tests in baseline because it would help us to keep the integrity of data, but we can skip creating baseline IcMs in automation

Revert "Temporary skip dualtor test in baseline test"

---

azure-pipelines.yml

After rolling out all of the new PR checkers, the old PR checkers are no longer needed. We decide to phase them out gradually. In this PR, we phase out the PR checker `t0-2vlans`, `t0-sonic`, `t1-multi-asic`, `dpu` and `dualtor`.
Summary:
After rolling out all of the new PR checkers, the old PR checkers are no longer needed. We decide to phase them out gradually. In this PR, we phase out the PR checker `t0-2vlans`, `t0-sonic`, `t1-multi-asic`, `dpu` and `dualtor`.
Deprecate the old PR checkers and make the new PR checkers as mandatory.
Test by pipeline itself, to see if we can successfully finish the pipeline.

[Impacted Area Based PR testing] Deprecate old PR checkers. 

---

tests/golden_config_infra/templates/sample_golden_config_db.j2

ADO: 30864778
Summary: Remove table that has no yang support in golden infra test
We plan on strict yang enforcement on config CLI. Thus it will fail for non-yang supported NEW_FEATURE table
Remove non-YANG supported tables in test 
E2E test

[golden_config_infra] Remove tables that has no YANG model

---

docs/testplan/WoL-test-plan.md

Summary:
Remove unicast address test in test plan, as we don't expected there is any routable unicast address to devices already shut down.
We don't expected there is any routable unicast address to devices already shut down.
Remove unicast address test in test plan.
NA
NA

[wol testplan] Remove unicast address test in plan

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
xfail for the testcase test_generic_hash 
add xfail condition
xfail on cisco devices, version 202405

xfail for test_generic_hash until the issue has been addressed

---

tests/srv6/test_srv6_static_config.py

Summary: Add a control plane test case to verify that SRv6 static SIDs gets programmed correctly from CONFIG_DB to APPL_DB.
Verify the functionality of SRv6 in Control Plane
Add two test cases to test the configuration of uN and uDT46 SIDs.
Run it on VS testbed
VS by now
T0 only by now

[SRv6] Add SRv6 control plane test case

---

.azure-pipelines/impacted_area_testing/calculate-instance-numbers.yml
.azure-pipelines/impacted_area_testing/calculate_instance_number.py
.azure-pipelines/impacted_area_testing/get_test_scripts.py
azure-pipelines.yml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

In PRs #15666 and #16403, we partially rolled out the T0 and T1 PR checkers, considering resource utilization since these checkers require over 20 instances and needed to run in parallel with the legacy PR checkers. After a period of observation, we have confirmed the stability of the new system. In this PR, we complete the rollout of the remaining T0 and T1 PR checkers and officially deprecate the old PR checkers. At the same time, we have added all test scripts into PR testing, and we will gather scripts though pytest mark, so we don't need onboarding PR checkers anymore. 
Summary:
In PRs #15666 and #16403, we partially rolled out the T0 and T1 PR checkers, considering resource utilization since these checkers require over 20 instances and needed to run in parallel with …

[Impacted Area Based PR testing] Roll out T0 and T1 PR checkers. 

---

tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py

Summary:
T2-Snappi-Route-Convergence: Fix Process Crash test for single asic linecards
Snappi based T2 convergence test(process crash) fails on single-asic linecard. 
The container name is appended with asic# even for single-asic linecard, which is incorrect. Fixed it by explicitly checking for single-asic linecard and not appending asic# to container name..
Ran the test on Single-asic linecard and verified that the test passes
NA
NA

T2-Snappi-Route-Conv: Fix Process Crash test for single asic linecards

---

tests/wol/test_wol.py

Fix bug with wol tests. Checking for received packets is always flaky. 1 in 10-20 of tests will fail. Packets will not arrive on time for one test and be received in later tests, breaking 2 tests at once. It is caused by importing ptf.dataplane as dataplane. dataplane is a module and a variable at the same time. Importing it and naming it dataplane breaks existing ptf.testutils behaviors (like flushing and syncing) and causing flaking packet analysis in testutils. 
Also some parametrize options are removed to prevent tests from running too long.
wol/test_wol.py::TestWOLSendFromInterface::test_wol_send_from_interface[False-None-None-None] PASSED                                                 [  1%]
wol/test_wol.py::TestWOLSendFromInterface::test_wol_send_from_interface[False-None-2-0] …

[wol] Fix wol tests bug

---

tests/dhcp_relay/conftest.py

Summary:
This skip condition would take effect on all test cases under `dhcp_relay` folder, which would skip dhcpv6_relay tests too. But we don't want to skip it when dhcp_server is enabled.
And dhcpv4_relay test is only running in m0 and t0, which wouldn't enable dhcp_server
Remove skip check
Run tests

[dhcp_relay] Remove skip dhcp_relay test when dhcp_server is enabled

---

tests/qos/files/vs/dutConfig.json
tests/qos/files/vs/dutQosConfig.json

Summary:
TO support PR test of QoS SAI, need to provide varous configuration to mock dutConfig and dutQosConfig
collect dutConfig and dutQosConfig on a single box 8102, and upload as fake parameter for mock purpose

upload fake dutConfig and dutQosConfig parameters to support kvm PR test

---

tests/pfcwd/test_pfcwd_function.py

Summary:
Fixes the following error per discussion in #16535
`UnboundLocalError: local variable 'PFC_STORM_TIMEOUT' referenced before assignment`
fix syntax error in test_pfcwd_function.py:
passed on msn2700. failed on 8102.

fix UnboundLocalError in test_pfcwd_function.py

---

tests/common/config_reload.py
tests/common/plugins/loganalyzer/loganalyzer.py
tests/common/plugins/loganalyzer/utils.py
tests/common/reboot.py

Summary:
Fixes #7313 
Fix the bug that run with --disable_loganalyzer
1. Always remove ignore_loganalyzer from the original kwargs
2. Rename to a more correct name
Tested on physical T2 testbeds

[loganalyzer] Fix the bug of ignore_loganalyzer decorator

---

tests/bfd/test_bfd_static_route.py
tests/drop_packets/drop_packets.py
tests/snmp/test_snmp_queue_counters.py

Summary:
Fixes MSFT PBI#30938349
1. Ignore the err logs during loganalyzer analyzer on config_reload and reboot, so that we can enable log analyzer on other codes beyond config reload/reboot, rather than skip on all of the test module.
2. Ignore err logs in bfd_static_route tests
1. Ignore the err logs during loganalyzer analyzer on config_reload and reboot, so that we can enable log analyzer on other codes beyond config reload/reboot, rather than skip on all of the test module.
2. Ignore err logs in bfd_static_route tests
Verified on physical chassis testbeds

[Chassis] ignore log analyzers on config reload/reboot, and bfd test

---

ansible/group_vars/ptf/secrets.yml
ansible/group_vars/ptf_host/secrets.yml
ansible/roles/vm_set/tasks/add_topo.yml
ansible/roles/vm_set/tasks/announce_routes.yml
ansible/roles/vm_set/tasks/ptf_change_mac.yml
ansible/roles/vm_set/tasks/ptf_portchannel.yml
ansible/roles/vm_set/tasks/renumber_topo.yml
ansible/roles/vm_set/tasks/start_ptf_tgen.yml
ansible/roles/vm_set/tasks/update_ptf_password.yml
ansible/veos_vtb
tests/scp/test_scp_copy.py

Manually cherry-pick #16457 to 202311 branch due to conflicts.
Summary:
The PTF container is always using default password. If the PTF container is on same bridge with the host server's management IP, then it is easily accessible from other host servers. This is not secure enough. We need to support alternate password for the PTF container and password rotation.
This change improved the ansible related code to support accessing the PTF containers using the multi_ssh_pass ansible plugin. Then we can specify alternate passwords for the PTF container. When alternate passwords are specified, the default password of PTF container is updated after PTF creation.
Tested remove-topo/add-topo/restart-ptf on KVM and physical testbed.

[202311] Support alternate password for PTF container (#16457)

---

ansible/roles/test/files/ptftests/py3/hash_test.py
tests/fib/test_fib.py

'ip-proto' hash_key only has 8-bits of entropy which won't result in good distributions on systems with large ECMP groups.
T2 systems have a 24-way ecmp which sees some paths deviate from the 25% threshold for the `ip-proto` hash key.
This change increases the tolerance just for `ip-proto` and `t2` full topologies.
For more details see https://github.com/sonic-net/sonic-mgmt/issues/16147
Summary:
Fixes #16147

Increase tolerance for 'ip-proto' hash_key on t2 topos

---

ansible/fanout_connect.yml
ansible/roles/fanout/tasks/rootfanout_connect.yml

Summary:
In PR: #15643, it add a new optional variable `clean_before_add` for template `arista_7260_connect.j2` to indicate whether clean vlan range before add vlan range, however, this variable are defined in `fanout_connect.yml` which will call `rootfanout_connect.yml`, this will be a bug, because when `rootfanout_connect.yml` is called by other playbook, it will raise error: clean_before_add undefined, so, to fix this bug, we move the `clean_before_add` definition from `fanout_connect.yml`  to 
`rootfanout_connect.yml`.
this will be a bug, because when `rootfanout_connect.yml` is called by other playbook, it will raise error: clean_before_add undefined
move the `clean_before_add` definition from `fanout_connect.yml`  to 
`rootfanout_connect.yml`.
local run playbook

[fanout connect playbook] Fix variable undefined in rootfanout_connect.yml

---

tests/gnmi/test_gnoi_killprocess.py

Summary:
gnmi/test_gnoi_killprocess.py is a newly added test in 202411 and it aims to test functionality of a new API - KillProcess. It tests the API by killing then re-enabling services, but 2 of the tested services in the test file is disabled in upstream 202411 build config (restapi and telemtry), resulting in a `service could not be found` failure.
https://github.com/sonic-net/sonic-buildimage/blob/202411/rules/config#L134
https://github.com/sonic-net/sonic-buildimage/blob/202411/rules/config#L150
Removing the `telemetry` and `restapi` case from the test file so it does not fail from testing disabled services. Also skipping the dhcp_relay case for t1 topos as t1 topos does not use the `dhcp_relay` service.
This test file no longer fails on `Unit XXXXX.service could not …

Fix gnmi/test_gnoi_killprocess.py checking disabled services

---

tests/common/plugins/sanity_check/__init__.py
tests/common/plugins/sanity_check/checks.py

Summary:
Recently, we observed some DUT lost IPv4 MGMT reachability. However, since it's still IPv6 MGMT reachable, the issue is hard to be noticed.
To catch such issue, this PR introduces IPv4 MGMT sanity check. **If the device has IPv4 MGMT IP assigned but it's unreachable, then sanity_check will fail the testcase.**
Recently, we observed some DUT lost IPv4 MGMT reachability. However, since it's still IPv6 MGMT reachable, the issue is hard to be noticed.
To catch such issue, this PR introduces IPv4 MGMT sanity check. **If the device has IPv4 MGMT IP assigned but it's unreachable, then sanity_check will fail the testcase.**
Verified by run `test_bgp_fact` with sanity_check.
When DUT IPv4 MGMT is reachable, sanity_check will pass and we can see below logs:
```
{
"failed": false, …
```

[sanity-check] Add IPv4 MGMT reachability check

---

tests/ecmp/test_ecmp_sai_value.py

Summary:
Dualtor doesn't support warm reboot, so the warm reboot tests in `test_ecmp_hash_seed_value` will leave the DUT dataplane in an inconsistent state. Let's skip them.
Run on dualtor.
```
ecmp/test_ecmp_sai_value.py::test_ecmp_hash_seed_value[str2-7050cx3-acs-09-common] PASSED                                                                                                                                                                              [ 10%]
ecmp/test_ecmp_sai_value.py::test_ecmp_hash_seed_value[str2-7050cx3-acs-09-restart_syncd] PASSED …
```

[ecmp] Skip warm-reboot tests on dualtor

---

tests/common/dualtor/mux_simulator_control.py

Summary:
This is to fix https://github.com/sonic-net/sonic-mgmt/issues/16495.
The root cause is that, on dualtor testbed, the post request to `mux_simulator` to toggle all mux ports can take up to 15+ seconds to finish; but the post timeout is 10s, so the post request to toggle all mux ports always timeout.
Here is the workflow for a HTTP requests to `mux_simulator`:
```
#
```
The HTTP requests are handled by TCP listen/accept queue first; after the connection is established, `mux_simulator` will consume the request and dispatch the request to workers to handle the request.
Back to the toggle all mux ports post request, the client times out and disconnects, but the request has already been dispatched by the `mux_simulator`, its handler worker is still busy handling the …

[dualtor][mux simulator] Fine-tune the mux simulator control post timeout

---

tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_ungraceful_restart.py

Summary:
T2-Route-Convergence: cherry-pick PR: Add Ungraceful restart(Sup/Uplink LC/Downlink LC) testcase
Master Branch PR: https://github.com/sonic-net/sonic-mgmt/pull/16636
- [] 202405
- [] 202411
New test case to verify route convergence in ungraceful reset scenarios
Reset DUT by creating kernel panic, and measure traffic loss
Ran the test on T2 DUTs
NA
T2

[202405]T2-Snappi-Conv: cherry pick ungraceful restart tc

---

tests/pfcwd/test_pfcwd_function.py

Summary:
We need to verify the new code before enabling it for cisco-8000. For now, we are temporarily disabling it.
Temporarily remove cisco-8000 from using the new code for mellanox.
Removed the cisco-8000 string from the supported list.
Running in my TB:
```
=========================================================================================================== PASSES ===========================================================================================================
_______________________________________________________________________________________ TestPfcwdFunc.test_pfcwd_actions[croc-t1-dut] ________________________________________________________________________________________
______________________________________________________________________________________ …
```

Temporarily remove cisco-8000 from pfcwd/PFC_STORM_TIMEOUT.

---

tests/arp/test_stress_arp.py

Summary:
This PR is to stabilize `test_stress_arp.py` on some platform.
The test is flaky on some platform due to the low performance of CPU. This PR addressed the issue by adding a short delay in sending packet and waiting longer time for checking MAC table.
This PR is to stabilize `test_stress_arp.py` on some platform.
This PR addressed the issue by adding a short delay in sending packet and waiting longer time for checking MAC table.
The change is verified by running the test on a physical testbed. It can pass consistently now.
```
collected 2 items …
```

Stabilize stress ARP test

---

tests/arp/test_stress_arp.py

Summary:
This PR is to stabilize `test_stress_arp.py` on some platform.
The test is flaky on some platform due to the low performance of CPU. This PR addressed the issue by adding a short delay in sending packet and waiting longer time for checking MAC table.
This PR is to stabilize `test_stress_arp.py` on some platform.
This PR addressed the issue by adding a short delay in sending packet and waiting longer time for checking MAC table.
The change is verified by running the test on a physical testbed. It can pass consistently now.
```
collected 2 items …
```

[202405][cherry-pick] Stabilize stress ARP test

---

ansible/library/announce_routes.py
tests/common/testbed.py

Summary:
This PR is to support `smartswitch` in `get_testbed_type`.
Before this change, the WARNING message shows up in each run.
This PR is to support `smartswitch` in `get_testbed_type`.
Update the regex in `get_testbed_type` to include `smartswitch.
Verified by manually run a test. The warning message doesn't show up any more.
No.

[202405] Support smartswitch in get_testbed_type and announce_routes

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Enable BFD and VxLAN ECMP tests for nvidia and cisco smartswitch platforms
Summary:
* Updated tests_mark_conditions.yaml to run test_bfd.py and test_vxlan_ecmp.py on smartswitch platforms.
BFD and VxLAN ECMP test cases are supported on smartswitch t1 platforms
Update the skip condition markers for these test cases to allow these platforms
By running the updated sonic-mgmt test on smartswitch t1.

Enable BFD and VxLAN ECMP tests for smartswitch

---

tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_member_flap.py
tests/snappi_tests/variables.py

Summary:
T2 Snappi based automation testcases, currently didnt have Different types of upstream neighbors support.
As part of this PR, 
1. Different upstream neighbors support is added. 
2. Fixed a bug where t2_uplink_fanout_info was not parsed correctly.
3. Po members flap test to skip if num_po_members < 2.
- [] 202405
cherry pick PR https://github.com/sonic-net/sonic-mgmt/pull/16337
T2 Snappi based automation testcases, currently didnt have Different types of upstream neighbors support.
Different upstream neighbors support is added. This also covers different route policies on different types of upstream neighbors
Ran the testcases locally and captured the results.
NA

[202405-cherry-pick]T2: Snappi Based Route Convergence Test Changes (#16337)

---

.azure-pipelines/impacted_area_testing/get_test_scripts.py
.azure-pipelines/testscripts_analyse/analyse_testscripts.py
tests/srv6/test_srv6_basic_sanity.py

add ciscovs-7nodes and ciscovs-5nodes  pytest topology marker for test_srv6_basic_sanity test
to fix issue #15561
Summary:
Fixes # (issue)15561

fix(tests): add pytest topology mark for test_srv6_basic_sanity test

---

tests/snmp/test_snmp_memory.py

Summary:
1. For Nokia-7215 which has only 3GB memory, diff percentage threshold 8% is not enough.
In this PR, I updated the threshold as below:
```
* DUT memory in [4GB, +inf): 4%  <-- Same as current impl.
* DUT memory in (3GB, 4GB] : 8%  <-- Arista-7050QX still fall in this range (as current impl)
* DUT memory in (2GB, 3GB] : 10% <-- Nokia-7215 will fall in this range
* DUT memory in (0, 2GB]   : 12% <-- Same as current impl.
```
2. Enhance the test failure message to print more information. Below are the new failure message:
*test_snmp_memory*
```
E       Failed: Snmp memory differs more than 0.01%, details: {'ansible_sysCachedMemory': {'snmp_value': 466824, 'sys_value': 467456, 'diff': 0.13538292804140317}, 'ansible_sysTotalSharedMemory': {'snmp_value': 30584, 'sys_value': '30588', …
```

Update percentage threshold based on DUT memory

---

tests/bgp/test_bgp_bbr.py
tests/bgp/test_bgp_dual_asn.py
tests/common/gu_utils.py
tests/common/helpers/dut_utils.py
tests/generic_config_updater/gu_utils.py
tests/generic_config_updater/test_aaa.py
tests/generic_config_updater/test_bgp_prefix.py
tests/generic_config_updater/test_bgp_sentinel.py
tests/generic_config_updater/test_bgp_speaker.py
tests/generic_config_updater/test_bgpl.py
tests/generic_config_updater/test_cacl.py
tests/generic_config_updater/test_dhcp_relay.py
tests/generic_config_updater/test_dynamic_acl.py
tests/generic_config_updater/test_ecn_config_update.py
tests/generic_config_updater/test_eth_interface.py
tests/generic_config_updater/test_incremental_qos.py
tests/generic_config_updater/test_ip_bgp.py
tests/generic_config_updater/test_kubernetes_config.py
tests/generic_config_updater/test_lo_interface.py
tests/generic_config_updater/test_mgmt_interface.py
tests/generic_config_updater/test_mmu_dynamic_threshold_config_update.py
tests/generic_config_updater/test_monitor_config.py
tests/generic_config_updater/test_ntp.py
tests/generic_config_updater/test_pfcwd_interval.py
tests/generic_config_updater/test_pfcwd_status.py
tests/generic_config_updater/test_pg_headroom_update.py
tests/generic_config_updater/test_portchannel_interface.py
tests/generic_config_updater/test_syslog.py
tests/generic_config_updater/test_vlan_interface.py

For GCU test suites, configuration changes applied via patches sometimes target a specific ASIC namespace or apply globally to the card (localhost), depending on the feature functionality.
With the recent merged PR https://github.com/sonic-net/sonic-mgmt/pull/14098, configuration changes are now applied to both localhost and all ASIC namespaces for all multi-ASIC platforms by default, which is incorrect.
Examples:
Configuration paths like /BGP_NEIGHBOR/ should apply only to the ASIC namespace.
Paths like /SYSLOG_SERVER/ should apply only to the localhost namespace.
This PR addresses the issue by introducing a missing flag for "asic_specific" configurations. It adapts the calls appropriately in each test suite based on the targeted configuration scope (ASIC namespace or localhost). …

Apply GCU changes to the appropriate namespace scope for each suite

---

tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_burst_storm_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_multi_node_helper.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_runtime_traffic_helper.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py
tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_m2o_with_snappi.py
tests/snappi_tests/test_multidut_snappi.py

Summary: Update the missing T0 T1 tests feature in multidut
Fixes # (issue) 30929279
The following PR were migrated for pfcwd
- https://github.com/sonic-net/sonic-mgmt/pull/7370
- https://github.com/sonic-net/sonic-mgmt/pull/9567 
- https://github.com/sonic-net/sonic-mgmt/pull/7367 to multidut code
- https://github.com/sonic-net/sonic-mgmt/pull/7712

[T0 T1 merge] update multidut pfcwd tests

---

tests/bgp/route_checker.py
tests/bgp/test_reliable_tsa.py
tests/bgp/test_seq_idf_isolation.py
tests/bgp/test_startup_tsa_tsb_service.py
tests/bgp/test_traffic_shift.py

Summary:
Partially tackles #16577 
Tests are flaky, sometimes failing on `verify_only_loopback_routes_are_announced_to_neighs`: `Failed to verify routes on nbr in TSA`
Add a function wrapping `verify_only_loopback_routes_are_announced_to_neighs` with wait_until and assert to allow time for neighbor to update routes
These logs were seen in passed tests, showing that wait_until helps avoid false negatives
```
17/01/2025 05:42:18 utilities.wait_until                     L0153 DEBUG  | verify_only_loopback_routes_are_announced_to_neighs is False, wait 10 seconds and check again
05:42:12 route_checker.verify_loopback_route_with L0014 INFO   | Verifying only loopback routes are announced to bgp neighbors
05:42:18 parallel.on_terminate                    L0085 INFO   | process …
```

Add function to wrap verify_only_loopback_routes with assert and wait_until

---

tests/voq/fabric_data/Arista-7804R3-FM.yaml
tests/voq/fabric_data/Arista-7808R3A-FM.yaml
tests/voq/fabric_data/Nokia-IXR7250E-SUP-10.yaml
tests/voq/test_fabric_reach.py

Summary:
Fixes #15753 
The original test used a base moduleID offset for Arista devices, however, this offset created mismatch in the moduleID and led the test to fail.
Remove the base module ID offset variable: `supervisorAsicBase`
I ran the test successfully on a T2 testbed to verify the change.

Remove supervisorAsicBase offset from test_fabric_reach.py test

---

tests/pc/test_po_update.py

`test_po_update_with_higher_lagids` was added recently by https://github.com/sonic-net/sonic-mgmt/pull/16142 And does config reloads and reboots causing loganalyzer to fail.

Disabling loganalyzer for `test_po_update_with_higher_lagids`

---

tests/common/testbed.py

The value is_smartswitch is missing from TESTBED_FIELDS_RECOMENDED
The value 'is_smartswitch' is missing from TESTBED_FIELDS_RECOMMENDED and causes an error when running test_pretest.py.  Without adding 'Is_smartswitch' the following error will output at end of a test:
ValueError: Unsupported testbed fields ['conf-name', 'group-name', 'topo', 'ptf_image_name', 'ptf', 'ptf_ip', 'ptf_ipv6', 'server', 'vm_base', 'dut', 'inv_name', 'auto_recover', 'is_smartswitch', 'comment']
To add value 'is_smartswitch' as a recognized field within sonic-mgmt.
Attempted to run test_pretest.py with a smartswitch testbed
Attempted to run locally in my development container

Updating TESTBED_FIELDS_RECOMMENDED with value 'is_smartswitch'

---

tests/platform_tests/test_intf_fec.py

FEC correctable codeword errors should not exceed FEC symbol errors, as a codeword is composed of multiple symbols. If this occurs, it likely indicates a reporting bug, misconfiguration, or data misinterpretation, requiring validation of counters, FEC settings, and system behavior. Fix the conditional check in the test case accordingly.
Summary:
Issue in the conditional check
Fix the conditional check for FEC errors
Verified on SN4700 platform.

Fix the conditional check for FEC errors

---

tests/platform_tests/test_power_off_reboot.py

Summary:
Fixes #16279, update platform_tests/power_off_reboot.py to support T2 devices
Test failures on T2 devices
Change check for power on each PDU to check for power on sets of PDUs (by PSU), add duthosts argument to `reboot_and_check` function to support sup cards
Perform regression test on T1 https://elastictest.org/scheduler/testplan/677b439de1be6860ea024869?testcase=platform_tests%2Ftest_power_off_reboot.py&type=console
Perform test on T2 to ensure these failures are gone (still failure in #16289)
N/A
N/A

Add T2 support to test_power_off_reboot.py

---

tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py

Summary:
In the function: save_restore_config() in test_multidut_pfcwd_basic_with_snappi.py, the teardown section copies back the backup files to /etc/sonic/. But the next line is to save config, which is not right. This PR fixes this issue.
The backup files contain the original configs for the DUT, but the config save command will overwrite them. In teardown, we want the original configs back, not the running configs.
Remove the config-save command in teardown.
Ran it on my TB. I checked if the running config is different from saved config, and verified the new code works correctly.
@sdszhang , @auspham : For viz. This might potentially fix the issues in pfcwd_basic/reboot cases.

T2:snappi_tests:Don't save config after copying over the backup files.

---

tests/pfcwd/conftest.py
tests/pfcwd/test_pfcwd_function.py

Summary:
pfcwd_multi_port test failed when using the longer PFC_STORM_TIMEOUT seconds. We found this is due to fake-storm flag. After disabling the fake-storm, the test is passing.
Enabling the longer pfc storm timeout and disabling fake-storm for cisco-8000.
Enabled the if conditions for mellanox to include cisco-8000.
Ran it on my TB, verified on 8102, 8111 and T2:
8102 run log:
```
collected 5 items                                                                                                                                                                                                            
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_actions[mth-t0-64] PASSED …
```

pfcwd: Set fake-storm false for cisco platforms.

---

tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py

Summary:
Use method `round()` to suit better need comparing to ceil vs int().
Fixes # (issue) #16080

feat: use round() instead of ceil to fix #16080

---

ansible/generate_topo.py
ansible/vars/topo_t1-isolated-d28u1.yml

Summary:
In d28u1 topology, current link was not selected correctly for t1 hwsku.
```
Ethernet96  121,122,123,124     400G   9100    N/A  Ethernet13/1  routed      up       up  OSFP 8X Pluggable Transceiver         off
Ethernet100  125,126,127,128     400G   9100    N/A  Ethernet13/5  routed    down     down  OSFP 8X Pluggable Transceiver         off
Ethernet112               97     100G   9100     rs  Ethernet15/1  routed    down     down  OSFP 8X Pluggable Transceiver         off
Ethernet113               98     100G   9100     rs  Ethernet15/2  routed    down     down  OSFP 8X Pluggable Transceiver         off
Ethernet114               99     100G   9100     rs  Ethernet15/3  routed    down     down  OSFP 8X Pluggable Transceiver         off
Ethernet115              100     100G   9100 …
```

fix t1-isolated-d28u1 link mapping

---

tests/snappi_tests/pfc/test_pfc_mixed_speed.py
tests/snappi_tests/pfc/test_pfc_no_congestion_throughput.py
tests/snappi_tests/pfc/test_pfc_port_congestion.py
tests/snappi_tests/pfcwd/test_pfcwd_actions.py
tests/snappi_tests/pfcwd/test_pfcwd_mixed_speed.py

Summary:
Current new PFC ECN test cases will fail if testbed doesn't meet the requirement. Change it to skip instead.

[Snappi] skip instead of assert if port doesn't meet the requirement.

---

tests/platform_tests/test_intf_fec.py

While the current condition if fec_corr_int > fec_symbol_err_int: correctly returns false when fec_corr_int is 0, I want to explicitly check for fec_corr_int > 0 to enhance the robustness of the test case.
Additionally, optimize the process by replacing commas in the FEC stats counters earlier, before converting them to integers.
Summary:
Verified on Arista 7060x6 testbed where the fec-stats counters are 0's.

test_verify_fec_stats_counters: Enhance the condition for robustness and optimize its efficiency.

---

ansible/group_vars/sonic/variables

Add Cisco-8102-28FH-DPU-O-T1 to list of Cisco GB hwskus to make sure that all T1 test cases pass for Cisco smartswitch T1 as well.
Summary:
Fixes # (31110663)
To improve nightly test pass percentages for cisco smartswitch
By adding smartswitch T1 hwsksu to cisco hwskus list
By running T1 test cases via nightly runs

Add Cisco-8102-28FH-DPU-O-T1 to list of Cisco GB hwskus

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary: The srv6/test_srv6_static_config.py requires particular image support that creates a dummy interface sr0. Currently,
only 202412 images have such support so I want to add a release based conditional marker for this test case.
Fixes #16627

Add release based conditional marker for srv6/test_srv6_static_config.py

---

tests/common/snappi_tests/traffic_generation.py
tests/snappi_tests/multidut/ecn/files/multidut_helper.py
tests/snappi_tests/multidut/ecn/test_multidut_ecn_marking_with_snappi.py

Summary:
Verify if ingress congestion experienced markets pkts (ECT bit b11) are causing the ecn counter increment on the DUT as expected on congestion
Wrote snappi test to cause congestion on the port
Injected frames with ECT bit set and caused congestion on the egress port.
Verified that the DUT is counting the ECN marking and the counter is incrementing.

Test for ecn counter increment for ECT marked packets

---

tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_multi_node_helper.py

Summary:
The all_to_all test is still using the random udp ports, and runs into random failures. This PR serializes the udp ports for traffic streams.
Random failure in all_to_all multidut snappi tests.
Serialized the udp port numbers used by this script.
Ran it on my TB. I verified that I could recreate the issue first, and then after the modifications, it passed:
```=============================================================================================== PASSES ===============================================================================================
_____________________________________________________________________ test_multidut_pfcwd_all_to_all[multidut_port_info3-False] ______________________________________________________________________ …
```

snappi_tests:T2: Serialize the udp ports for all_to_all test

---

tests/common/plugins/sanity_check/__init__.py
tests/conftest.py

Change custom message name to be more intuitive and set new standard for future message names.
Summary:
Currently, custom message is used to record of failures throughout the test runs. But with names we have now, it might not intuitive enough to understand what the message is about.
Therefore, set new standard for custom message name to be more intuitive and easier to understand, so future custom messages can follow the same standard.
Instead of mixture of xxx_failed and yyy_pass, merge all messages with xxx_failed, so everytime custom message is recorded, it's always result of failures.
Not intuitive names for custom message.
Change name of custom message names and merge into xxx_failed

Intuitive custom msg

---

tests/acl/test_acl.py

Summary:
Fixes #30114164
Fixes #30114164, test_acl is flaky on chassis device.
We observe flakiness failure on chassis devices
Suspect it's because the route is not programmed into hardware
Add external sleep to make sure route is in hardware
Add extra waiting time for chassis device port toggle tests.
Run on PR test, and physical test is running.

[Chassis] Add extra wait after port toggle so that the routes got programmed into hardware

---

tests/platform_tests/test_power_off_reboot.py

Add support for test_power_off_reboot for Cisco 8808 chassis. For chassis, till we can add calculation to find minimum number of PSU up based on the load of the system, we will bringup all the PSU before we continue the test.
Summary:
Add support for test_power_off_reboot for Cisco 8808 chassis. For chassis, till we can add calculation to find minimum number of PSU up based on the load of the system, we will bringup all the PSU before we continue the test.
On T2 profiles
Cisco 8808 chassis
=========================================================================================== PASSES ===========================================================================================
______________________________________________________________________________ …

Add support for test_power_off_reboot for Cisco 8808 chassis

---

tests/acl/templates/acltb_v6_test_rules.j2
tests/acl/templates/acltb_v6_test_rules_part_2.j2
tests/acl/test_acl.py

Summary:
Fixes https://github.com/sonic-net/sonic-buildimage/issues/21183
Prevent T2 BGP neighbors going down during ACL tests
Prevent last 64 bits of a DROP rule IP from being the same as a BGP neighbor
Run on T2 devices
T1 regression test: https://elastictest.org/scheduler/testplan/679c3507f5a74203a8e1b10b
N/A
N/A

Prevent T2 BGP neighbors going down during ACL tests

---

ansible/library/exabgp.py

The docker-ptf PY3 only image uses ExaBGP v4. The ExaBGP v4+ requires process API to acknowledge messages from ExaBGP else the server blocks after a while and hangs. This causes BGP timeouts in our stress tests. This PR fixes the issue.
Summary:
Not applicable to backport since it only applies to docker-ptf PY3 only image.
The docker-ptf PY3 only image uses ExaBGP v4. The ExaBGP v4+ requires process API to acknowledge messages from ExaBGP else the server blocks after a while and hangs. This causes BGP timeouts in our stress tests. This PR fixes the issue.
Set exabgp.api.ack to false.
Ran tests/stress/test_stress_routes.py on 7050cx3 to confirm.
No
NA
NA

Fix ExaBGP v4 hang during announce routes stress tests

---

tests/cacl/test_cacl_function.py
tests/common/helpers/snmp_helpers.py

Summary:
Fixes #30114164
Fix the cacl test failure on Cisco chassis packet.
Reduce the timeout setting.
Run on physical testbed.

[chassis] Reduce timeout for packet chassis

---

tests/telemetry/test_telemetry.py

This PR fixes the second occurrence of the conversion error when running test_sysuptime.
Summary:
Fix broken telemetry test_sysuptime.
Fix string parsing.
on 7050cx3
None
NA
NA

Fix test_sysuptime conversion error

---

tests/pfcwd/test_pfcwd_timer_accuracy.py

Summary:
Fixes # (issue) 31202914
From #16446 we are changing to use regex to capture the timestamp for pfc timer accuracy. However, the regex does not cover the scenario where date digit is 1. For example: `2025 Jan  5 00:53:14.103188 `
Comparing between:
- `2025 Jan 26 17:36:31.27789`
- `2025 Feb  2 15:17:24.055182`
We can see that we might need up to 2 spaces after month and the number of day digits can vary between 1 to 2.
Adjust the regex so it matches for both format

fix: pfc timer accuracy timestamp regex

---

tests/platform_tests/test_power_off_reboot.py

Summary:
Fixes #16771
Prevent test failures due to KeyError when retrieving PDU["output_watts"]
Use `.get` function to provide default value for PDUs that don't have `output_watts` as an attribute
Tested on T2 device with PDUs that don't provide `output_watts` (thanks @auspham)
N/A
N/A

Prevent `output_watts` KeyError

---

tests/gnmi/helper.py
tests/gnmi/test_gnoi_killprocess.py
tests/gnmi/test_gnoi_system.py

Summary:
Add module as an input parameter for gnoi_request. Previously it implicitly rely on "gnoi_client" having a “-module" flag with
default value "System". This change make it possible to use other module like "OS."
Add module as a parameter to gnoi_request.
Support other module parameter value.
Add module as a parameter to gnoi_request.
On KVM: gnmi:test_gnoi_system.py.

Add module as an input parameter for gnoi_request.

---

tests/common/plugins/sanity_check/__init__.py

Summary: "check_bfd_up_count" and "check_mac_entry_count" does not work on voq chassis, so we should skip it.

Add filtering to skip two new check items for voq chassis in sanity check

---

tests/pfcwd/conftest.py
tests/pfcwd/test_pfcwd_function.py

Summary:
pfcwd_multi_port test failed when using the longer PFC_STORM_TIMEOUT seconds. We found this is due to fake-storm flag. After disabling the fake-storm, the test is passing.
Enabling the longer pfc storm timeout and disabling fake-storm for cisco-8000.
Enabled the if conditions for mellanox to include cisco-8000.
Ran it on my TB, verified on 8102, 8111 and T2:
8102 run log:
```
collected 5 items                                                                                                                                                                                                            
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_actions[mth-t0-64] PASSED …
```

Porting : 16695 to 202405: Set fake_storm to false for cisco-8000

---

tests/bgp/test_startup_tsa_tsb_service.py

As described in:
https://github.com/aristanetworks/sonic/issues/118
The LC reboot-cause doesn't match the test's expectations because Arista SKUs reboot the LCs when a reboot occurs on the supervisor.
We will look into fixing this but in the meantime skipping this check in the test for the Arista SKUs.

Skip the LC reboot-cause check since it's broken on Arista

---

tests/kubesonic/test_k8s_join_disjoin.py

Summary: The k8s feature in not enabled for public branches. So the test case should be skipped for public branches
Fixes # ([issue](https://github.com/sonic-net/sonic-mgmt/issues/16617))
The k8s feature in not enabled for public branches. So the test case should be skipped for public branches
Check the image type and skip the test case if it is public branch
Yes
No
Not new case

Skip kubesonic test case for public branch

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Ignore nss_tacplus error log report by NTPD during config reload.
This is a cherry-pick PR: https://github.com/sonic-net/sonic-mgmt/pull/16239
During config reload, tacacs config will be re-render by hostcfgd, NTPD will call getpwnam API during config reload, so will report nss_tacplus error.
These error can be ignored, getpwnam API will success in this case.
- Microsoft ADO: 
Ignore nss_tacplus error log report by NTPD.
Ignore nss_tacplus error log report by NTPD during config reload.

[202411] Ignore nss_tacplus error message reported by NTPD

---

ansible/roles/vm_set/tasks/add_ceos_list.yml

PR adds ability to use configured container registry for cEOS net base containers instead of using the default (DockerHub). DockerHub throttles the number of pulls leading to error "toomanyrequests: You have reached your pull rate limit...". The PR CI and test environments use Azure container registry.
Summary:
PR adds ability to use configured container registry for cEOS net base containers instead of using the default (DockerHub). DockerHub throttles the number of pulls leading to error "toomanyrequests: You have reached your pull rate limit...". The PR CI and test environments use Azure container registry.
Specify the container registry for the image.
Ran add-topo on test environments.
No
NA
NA

Add support for configurable container registry for cEOS net base image

---

tests/bgp/test_reliable_tsa.py

Bump the timeout limit in reliable tsa test to make the test more stable.
Summary:
Fixes # (issue) Microsoft ADO 31235033
Previously, we discussed in the Cisco sync-up meeting to increase the time diff limit and bgp wait timeout in `bgp/test_startup_tsa_tsb_service.py`: #16638. We need to make similar changes to `bgp/test_reliable_tsa.py` as we are seeing similar flaky issues in it.

chore: bump timeout limit in reliable tsa test

---

tests/common/fixtures/duthost_utils.py
tests/common/helpers/ntp_helper.py
tests/common/helpers/tacacs/tacacs_helper.py
tests/common/helpers/telemetry_helper.py
tests/conftest.py
tests/ip/test_mgmt_ipv6_only.py
tests/ntp/test_ntp.py
tests/tacacs/conftest.py
tests/telemetry/conftest.py

ipv6 mgmt only tests can fail in setup, after config has been modified, leading to the teardown to not be run, and the duts to be left in an unreachable state. Refactor the test to split backing up and restoring the config into an independent fixture, such that failures in setting the mgmt IPs won't nuke the testbed. Also refactor / cleanup some other aspects of the tests to enhance clarity. 
Summary:
Fixes #16441
- [x ] Bug fix
- [x ] Test case improvement
Fix failures in test setup leaving the testbed in a wedged state, due to removed ipv4 mgmt IPs
Refactor the test to have config backup and restore in a separate fixture

[ip/test_mgmt_ipv6_only]: Refactor to properly cleanup on failure

---

tests/common/reboot.py

Summary: Cherry-pick #16773 conflict
Summary: 
When executing `show reboot-cause history`, swss needs to access `/var/run/redis/sonic-db/database_config.json` we're dependent on the database service to boot up.
Without waiting for this service to boot up we might run into runtime error:
```
/usr/local/lib/python3.8/dist-packages/_pytest/main.py:305: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: terminalreporter, Hook: pytest_sessionfinish
KeyboardInterrupt: 
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
config.hook.pytest_sessionfinish(
File "/var/src/sonic-mgmt-int/tests/platform_tests/test_power_off_reboot.py", line …
```

Cherry-pick conflict #16773

---

tests/tacacs/test_accounting.py
tests/tacacs/utils.py

`change_and_wait_aaa_config_update` validates that the `auditd` service publishes the log `audisp-tacplus re-initializing configuration` after executing the passed in `command`.
However, it did this by checking that the timestamp in the log message was different than the previously emitted log.
As shown in https://github.com/sonic-net/sonic-mgmt/issues/16709 these message can appear within the same second and cause the test to fail.
Instead this PR changes the approach to look at how many logs have been emitted before and after the command rather than the timestamp changes.
Summary:
Fixes #16709

Use number of logs instead of timestamp in `change_and_wait_aaa_config_update`

---

.github/workflows/sdn.yml

- Adding Build CI workflow for sdn_tests Pins_ondatra.
Summary:
- [-] Testbed and Framework(new/improvement)
- [-] 202411

[sdn_tests]: Adding Pins_ondatra build workflow

---

azure-pipelines.yml

In this PR, we transition the multi_asic_t1 PR checker to impacted area-based PR checker, enabling automatic selection of test scripts using pytest marks.
Summary:
In this PR, we transition the multi_asic_t1 PR checker to impacted area-based PR checker, enabling automatic selection of test scripts using pytest marks.
Transition the multi_asic_t1 PR checker to impacted area-based PR checker,
Test by pipeline itself.

Transition multi_asic_t1 PR checker to impacted area-based PR checker

---

tests/generic_config_updater/test_bgp_speaker.py

ADO: 30945722
Summary: Remove BGP_PEER_RANGE config before rollback
Patch Applier:   * [{\"op\": \"remove\", \"path\": \"/BGP_PEER_RANGE/BGPSLBPassiveV6\"}]\n
Patch Applier:   * [{\"op\": \"add\", \"path\": \"/BGP_PEER_RANGE/BGPVac\", \"value\": {\"ip_range\": [\"192.168.0.0/21\"], \"name\": \"BGPVac\", \"src_address\": \"10.1.0.32\"}}]\n
Patch Applier:   * [{\"op\": \"remove\", \"path\": \"/BGP_PEER_RANGE/BGPSLBPassive\"}]\n
Patch Applier:   * [{\"op\": \"add\", \"path\": \"/BGP_PEER_RANGE/BGPSLBPassive\", \"value\": {\"ip_range\": [\"10.255.0.0/25\"], \"name\": \"BGPSLBPassive\", \"src_address\": \"10.1.0.32\"}}]
The problem comes from that the running config already has 192.168.0.0 in BGPSLBPassive when add ip_range 192.168.0.0 to BGPVac. Then it cause the ip_range …

[GCU] Update the testcase to avoid duplicate ip range

---

tests/platform_tests/link_flap/test_cont_link_flap.py

This change was made because in modular chassis with multi-asic LCs, the link flap test might run on the uplink LC followed by the downlink LC. Since the uplink has a lot of neighbors the downlink CPU is busy re-routing the different pathways. In such a scenario, the downlink LC will still be hot (above 10% utilization) before we flap its interfaces. Hence, the increase in timeout.
We tested it with a timeout of 500 and it failed so we are increasing it to 600 which has been passing on our local T2 testbeds.
Summary:
Fixes #16186
To make sure that the timeout for the Orchagent CPU utilization check is large enough for the test to pass.
Increased the timeout from 100 to 600.
Ran the test on T2 testbed with a timeout of 600 (Passed) and 500 (Failed)

Increase Orch CPU utilization timeout before link flap

---

tests/syslog/test_syslog_rate_limit.py

This PR addresses an issue where the syslog rate_limit configuration command does not take effect properly because certain containers are not fully initialized before the command execution. To resolve this, "safe reload" option has been added to the config reload. This ensures that all containers and critical processes are up and running before the configuration is applied, ensuring successful configuration
Summary:
Intermittent syslog_rate_limit testcase failure on Nokia-7215 platforms
Fix intermittent failure caused by containers not up before rate_limit config command execution
Added safe=True option to config reload
Run test_syslog_rate_limit testcase on Nokia-7215 platforms

Added safe reload=True option for config reload performed in syslog_rate_limit to eliminate intermittent failures

---

tests/generic_config_updater/test_cacl.py

ADO: 31219916
Summary: Reload DUT before cacl test to avoid ip rule change by other tests
The initial ip rule was impact by other test. Since this is not config related change, so general DUT recover will not be executed on such DUT. The missing ip rule would cause comparison diff between initial and after test.
Refresh ip table after reload DUT 
E2E

[GCU] Refresh DUT env before cacl test to avoid ip rule impact

---

tests/common/config_reload.py

Summary:
Some test cases fail due to passing keyword arguments to this function which don't exist in this branch (as it is old and relatively inactive, it does not receive the most up-to-date cherry picks). Resolving these differences would be quite time consuming and error-prone, as this branch has diverged quite significantly from the master branch.
Added `**kwargs` to the `config_reload` function signature, along with warning logs printing any unhandled keyword arguments (to assist in debugging, in the event that these arguments are required for passing results).
Previously, running `cacl/test_cacl_application.py::test_cacl_acl_loader_commands_internal` threw the following exception:
```
08:30:07 __init__._fixture_generator_decorator    L0089 ERROR  |
TypeError("config_reload() got an …
```

[common - config_reload] Add workaround for 202012 tests to pass

---

tests/common/platform/device_utils.py
tests/conftest.py
tests/platform_tests/api/conftest.py

In PR #15605, the `platform_api_conn` fixture was relocated to a common location. The fixture `start_platform_api_service` used by it is not imported in this script, which will casue error `fixture 'start_platform_api_service' not found`. This PR addresses the issue by moving fixture `start_platform_api_service` to a common place `tests/conftest.py`. 
Summary:
In PR #15605, the `platform_api_conn` fixture was relocated to a common location. The fixture `start_platform_api_service` used by it is not imported in this script, which will casue error `fixture 'start_platform_api_service' not found`. This PR addresses the issue by moving fixture `start_platform_api_service` to a common place `tests/conftest.py`. 
This PR addresses the issue by moving fixture …

[Bugfix] Fix import error in `device_utils.py`.

---

tests/fdb/test_fdb.py
tests/fdb/test_fdb_flush.py
tests/fdb/test_fdb_mac_move.py
tests/fdb/utils.py

Fanout switch should not learn any FDB entries at all, but it learns tens of thousands of them.  FDB table for fanout is much bigger than FDB table for DUT. In this case, when do shutdown of the port from DUT, the port on the fanout will also go down. FDB flush also executed on this port on fanout, if there is too many fdb entries on the port, then during flushing following event occurred on fanout: INFO database#supervisord: redis 40:M 24 Oct 2024 15:23:08.510 #Lua slow script detected: still in execution after 6524 milliseconds. You can try killing the script using the SCRIPT KILL command. Script SHA1 is: 7acccfabe7fbd17d9a74e91c34de49c51d70749b ERR pmon#psud: :- checkReplyType: Expected to get redis type 3 got type 6, err: BUSY Redis is busy running a script. You can only call SCRIPT …

Clean up the fdb on the sonic fanout in fdb test

---

ansible/roles/test/files/ptftests/py3/advanced-reboot.py

* Add more debug information to the advance reboot
1. Add more debug information
2. When get the dut time has exception, need to not break the get teamd state function
3. When get the finalizer_state, if the state is set to empty should not return.
Summary:
cherry-pick for https://github.com/sonic-net/sonic-mgmt/pull/1588

[202405]Enhance advance reboot test  (#15880)

---

tests/common/snappi_tests/common_helpers.py

Summary:
The ECN configuration commands still used 'sudo ip netns exec asicX' command to check and configure the ECN. 
In 202405, there were changes done to fix the ECN configuration CLIs and hence the above needs to modified.
The correct way to reference ECN configuration is : sudo ecnconfig -n asicX - to check and configure ECN on SONIC DUTs.
#16304 
The use of 'sudo ip netns exec asic' to check and configure ECN fails in 2405 release. With new changes, the ecnconfig -n asic - will be required to check and change ECN configuration.
All changes are done in tests/common/snappi_tests/common_helpers.py:
1. For enable_ecn and disable_ecn functions, changed the reference from - sudo ip netns exec asic - to - sudo ecnconfig -n asic.
2. For config_wred function, changed …

[snappi]: Remove references of 'sudo ip netns exec asic' for ECN configuration in common_helpers file

---

tests/pc/test_retry_count.py

If the test case name has the 'teamd_' in it, in the loganalyzer, when add the marker, the log will be writen to the /var/log/teamd.log, but not the /var/log/syslog, it will fail the loganalyzer
Summary:
Change the test cases name to not fail the loganalyzer
When run the test case: tests/pc/test_retry_count.py:: TestNeighborRetryCount:: test_kill_teamd_lag_up, it failed when add_end_marker in the loganalyzer, and could reproduce it by manual. 
_sudo python /tmp/loganalyzer.py --action add_end_marker --run_id test_kill_teamd_lag_up.2025-01-05-03:24:03
File "/tmp/loganalyzer.py", line 878, in <module>
main(sys.argv[1:])
File "/tmp/loganalyzer.py", line 859, in main
analyzer.place_marker(
File "/tmp/loganalyzer.py", line 262, in place_marker …

Change the test case name to not include 'teamd_' in it

---

tests/acl/custom_acl_table/test_custom_acl_table.py
tests/acl/null_route/test_null_route_helper.py
tests/acl/test_acl.py

Align acl test for t0-isolated-d16u16s1, in this t0 topo, there is no portchannel, need to update the test case to get the correct upstream port.
Summary:

Align acl test case for new t0 topo

---

tests/common/dualtor/mux_simulator_control.py

Summary:
Dualtor I/O tests are flaky due to the DUT is stuck in heartbeat suspension, so the DUT cannot react to any failure scenarios, this is causing some nightly failures like the following:
1. the heartbeat suspension leaves the mux port in `unhealthy` state:
```
E       Failed: Database states don't match expected state standby,incorrect STATE_DB values {
E           "MUX_LINKMGR_TABLE|Ethernet48": {
E               "state": "unhealthy"
E           }
E       }
```
2. if there is a failure triggered during the heartbeat suspension, the DUT will fail to toggle to the correct state:
```
E       Failed: Database states don't match expected state active,incorrect APP_DB values {
E           "HW_MUX_CABLE_TABLE:Ethernet60": {
E               "state": "standby"
E …
```

[dualtor] Restart linkmgrd before toggle

---

ansible/roles/test/files/ptftests/remote.py
tests/common/plugins/ptfadapter/__init__.py
tests/iface_loopback_action/conftest.py
tests/srv6/test_srv6_basic_sanity.py

update to configure the backplane port only in the srv6 test. 
fix #16585 
Summary:
Fixes #16585 
- [X ] Bug fix
Backplane port is necessary in our srv6 tests, but it will cause random failure in other tests.  When the test packet dst IP matches the IP prefix advertised by the exabgp, the ptf backplane interface will receive the test packet from the neighbor VM. The reason is the routes are advertised by exabgp to VM through the ptf backplane interface. And methods like verify_packet_any_port() not only validate the packet is received by the expected ports, but also validate it's not received by the unexpected ports.
Added configuration options in ptf initial to limite the configuration scenarios of backplane ports only in srv6 tests
we tested it via daily jenkins run

fix(tests): add backplane port only in srv6 tests

---

tests/common/snappi_tests/qos_fixtures.py

Summary:
The test used to select supervisor sometimes which will not work in case of Nokia and Arista Chassis.

RDMA Tests Enhancements

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
ADO: 31292774
The test requires a minimum of two port channels. However, in the case of the T2-min topology, while there are typically two port channels, they are distributed across different ASICs. When this test was originally developed, multi-ASIC scenarios were not considered. Therefore, we are skipping this test for the T2-min topology.

Skip test_ip_packet.py for t2-min topology

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/fib/test_fib.py

To skip NVGRE hash tests for Broadcom SKUs
With the default hash algorithm, NVGRE hash test fails for Broadcom SKUs, so skip.
Check for the asic_type and skip for Broadcom SKUs.

Skip NVGRE hash tests for Broadcom SKUs

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skipping generic_config_updater/test_dynamic_acl.py on Q200 platforms as its not supported on Q200
Added a skip condition for generic_config_updater/test_dynamic_acl.py for Q200 platforms in tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
**Type of change** 
-Test modification
**Back port request** 
-202311
-202405
Made sure that TC is skipped on Q200 platforms

skipping dynamic_acl TC on Cisco Q200 platforms

---

tests/platform_tests/test_power_off_reboot.py

Summary:
Fixes #16898
PR https://github.com/sonic-net/sonic-mgmt/pull/16736 reintroduces bug that we previously fixed in https://github.com/sonic-net/sonic-mgmt/pull/16313 by making it only applying it to Cisco chassis.
Let `duthosts` be passed to `reboot_and_check` for all T2/chassis devices
Run on non Cisco T2 device
N/A
N/A
N/A

Fix T2 duthosts tests_power_off_reboot.py bug again

---

.azure-pipelines/impacted_area_testing/get-impacted-area.yml

In the `Get Impacted Area stage`, we use regular expressions to determine whether the changes in a PR are related to a specific feature. In this PR, we refine the regular expression to reduce false matches and improve accuracy.
Summary:
In the `Get Impacted Area stage`, we use regular expressions to determine whether the changes in a PR are related to a specific feature. In this PR, we refine the regular expression to reduce false matches and improve accuracy.
In this PR, we refine the regular expression to reduce false matches and improve accuracy.
For string like `ansible/roles/files/ptftests`, we can't match the pattern. And for string start with `tests/`, we can match this pattern.

[Impacted Area Based PR testing] Enhancing regex accuracy in impacted area detection.

---

tests/conftest.py
tests/platform_tests/link_flap/test_cont_link_flap.py

Add a module-level fixture for temporarily disabling route check for a test module
Summary:
Fixes # (issue) Microsoft ADO 31326413
In our recent Cisco T2 Nightly run, we observed that we would get the following error syslog during some test modules:
```
E               Failed: Processes "['analyze_logs--<MultiAsicSonicHost dut-lc1-1>']" failed with exit code "1"
E               Exception:
E               match: 1
E               expected_match: 0
E               expected_missing_match: 0
E               2025 Feb  3 03:03:29.550827 svcstr2-8800-lc1-1 ERR monit[914]: 'routeCheck' status failed (255) -- Failure results: {{#012    "asic1": {#012        "Unaccounted_ROUTE_ENTRY_TABLE_entries": [#012            "100.1.0.22/32",#012
```
After …

feat: add fixture for disabling route check

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/qos/files/vs/dutConfig.json
tests/qos/files/vs/dutQosConfig.json
tests/qos/qos_sai_base.py
tests/qos/test_qos_sai.py

Summary:
But some traffic test can't be tested on KVM platform, we need to skip traffic test if needed.
This PR adds qos tests to the KVM-based PR test framework with the following scope and modifications:
1. Update kvm qos config template
2. In kvm qos sai test, read kvm qos config from template json
3. Skip traffic test in qos sai test

Support qos sai test in KVM

---

tests/pfcwd/test_pfcwd_timer_accuracy.py

Summary:
same with https://github.com/sonic-net/sonic-mgmt/pull/16757
31202914
Need handle regex1 too
Follow previous PR, modify the regex1 
```
>>> regex = re.compile(r'\b[A-Za-z]{3}\s{1,2}\d{1,2} \d{2}:\d{2}:\d{2}\.\d{6}\b')
>>> syslog_msg_1 = "May 29 02:47:40.345257 str3-dut INFO"
>>> syslog_msg_2 = "May 9 02:47:40.345257 str3-dut INFO"
>>> syslog_msg_3 = "May  9 02:47:40.345257 str3-dut INFO"
>>> syslog_msg_4 = "2024 May 29 02:47:40.345257 str3-dut INFO"
>>> syslog_msg_5 = "2024 May 9 02:47:40.345257 str3-dut INFO"
>>> syslog_msg_6 = "2024 May  9 02:47:40.345257 str3-dut INFO"
>>> search_string = regex.search(syslog_msg_1)
>>> search_string
<re.Match object; span=(0, 22), match='May 29 02:47:40.345257'>
>>> search_string.group()
'May 29 02:47:40.345257'
>>> …
```

[test_pfcwd_timer_accuracy]: fix pfc timer accuracy timestamp regex

---

ansible/group_vars/sonic/variables

Add Cisco-8102-28FH-DPU-O-T1 to list of Cisco GB hwskus to make sure that all T1 test cases pass for Cisco smartswitch T1 as well.
Summary:
Fixes # (31110663)
To improve nightly test pass percentages for cisco smartswitch
By adding smartswitch T1 hwsksu to cisco hwskus list
By running T1 test cases via nightly runs

[202405]: Add Cisco-8102-28FH-DPU-O-T1 to list of Cisco GB hwskus (Backport #16697)

---

tests/telemetry/telemetry_utils.py
tests/telemetry/test_telemetry_cert_rotation.py

Summary:
Fixes # (issue) 30600475
There are cases where gnmi_get is called when server is not fully ready after rotation which is a timing issue for a few seconds. If we retry the gnmi_get call, it will succeed. Add wait_until to retry the client calls for a period of 30 seconds.
Add wait_until to retry for 30 seconds
Manual test/pipeline

Retry gnmi_get calls for potential server startup timing issue

---

tests/bgp/test_reliable_tsa.py
tests/bgp/test_startup_tsa_tsb_service.py
tests/common/config_reload.py

Summary:
TSA-TSB service Testcases: Adjust the testcases to adhere to new behavior of config_reload
As a fix for the issue https://github.com/sonic-net/sonic-buildimage/issues/21586, TSA-TSB service is invoked upon swss bring up(https://github.com/sonic-net/sonic-buildimage/pull/21587).
This affects config_reload behavior, where after config reload the tsa-tsb service will be restarted, and the device will be in TSA state till timer expires. Adjusting the testcase to explicitly execute TSB for the DUT to be ready for next testcase,
Enhanced the config_reload api to optionally take exec_tsb parameter. For startup-TSA-TSB and reliable TSA-TSB testcases, pass this flag to True to explicitly execute TSB on the device after config reload.
Ran the tests on t2 
NA
NA

Adjust TSA-TSB related sonic-mgmt testcases

---

ansible/roles/test/files/ptftests/device_connection.py

Summary:
In the DeviceConnection class, if none of the passwords appear to work, then try again from the first provided password. The reason for this is if a a device initially needs some password specified in the alternate passwords list, but then later needs to use some earlier-specified password (because of some config change), then connection attempts will fail until a new DeviceConnection object is instantiated.
Instead, work around that by trying the passwords in a loop (i.e. from the beginning again). This also means that the class doesn't really need to keep track of what password might be the "primary" password and what password might be alternates.

Retry from the first provided password if none of the passwords work

---

.azure-pipelines/testbed_health_check.py

Enable T2 auto health check and add running container info to return data.
Summary:
Fixes # (issue) Microsoft ADO 30293537
We want to enable T2 auto health check as we have now supported T2 auto recover.

feat: enable T2 auto health check

---

tests/test_parallel_modes/cisco_t2_8800.json

Disable parallel run for `pc/test_po_cleanup.py` test.
Summary:
Fixes # (issue) Microsoft ADO 31368079
There is config reload with `wait_for_bgp=True` in `pc/test_po_cleanup.py`, so when parallel run is enabled, LCs will do config reload at different time and we cannot make sure all the iBGP in one LC can be established after config reload within the given time limit.

chore: disable parallel run for po cleanup test

---

tests/generic_config_updater/test_dynamic_acl.py

Summary:
1. failures of test_gcu_acl_arp_rule_creation when enabling 2 vlan config
With 2vlan config on testbed, GCU test_dynamic_acl failed due to ip conflict with the ip address of the second vlan interface,
192.168.0.129.
ping success, but there is no arp entry for this ip address.
Then case failed.
2. Failures of test_gcu_acl_dhcp_rule_creation when enabling 2 vlan config
Previous logic just picks up the latest ipv4 address or ipv6 address from `mg_facts['minigraph_vlan_interfaces']`, which doesn't work for the first vlan case
1. With 2vlan config on testbed, such as t0-118, by default, ipv4 range for vlan1000 is 192.168.0.1/25 and ipv4 range for vlan2000 192.168.0.129/25, so set increment to 65.
Otherwise, incrementing by 129 will cause IP overlap within the second …

Fix GCU test_dynamic_acl failure on 2vlan config testbed

---

ansible/templates/minigraph_png.j2
ansible/vars/topo_tgen_t2_2lc_masic_route_conv.yml
ansible/vars/topo_tgen_t2_2lc_route_conv.yml

Summary:
Created 2 new topology files for T2 Snappi based convergence tests.
topo_tgen_t2_2lc_masic_route_conv.yml: for muti-asic testbed
topo_tgen_t2_2lc_route_conv.yml: for single asic testbed
Currently snappi based T2 convergence tests assumes DUT to be in certain initial state. And as part of tests, it configures BGP neighbors/Portchannel/Interface IPs etc. This is error prone. Also bringing DUT to that initial state requires manual steps.. 
Created new topology files. The testbeds for snappi based convergence tests will use these topology files to generate initial DUT config(deploy-mg).
With this, the DUT config portion is automated, and hence we could remove the DUT config part as part of snappi tests going forward..
Ran the deploy-mg on both single and multi-asic testbed and could …

Add new topo files for T2 Snappi route-conv automation tests

---

tests/crm/test_crm.py

Disable route checker for `crm/test_crm.py::test_crm_nexthop_group` test case.
Summary:
Fixes # (issue) Microsoft ADO 31326413
Recently, we found that we would also get the routeCheck log analyzer error in `crm/test_crm.py::test_crm_nexthop_group` test case, so we decided to disable route checker for it as well.
I ran the updated code and can confirm it's working well.

chore: disable route checker for crm nexthop group

---

tests/syslog/test_syslog_source_ip.py

Skip test_syslog_config_work_after_reboot due to the bug https://github.com/sonic-net/sonic-buildimage/issues/21201
Summary:
Skip test_syslog_config_work_after_reboot 
when dut_mgmt_network is a sub_network of forced_mgmt_routes, skip it
run test_syslog_config_work_after_reboot 
no

Skip test_syslog_config_work_after_reboot

---

tests/pfcwd/test_pfcwd_timer_accuracy.py

…gument
Summary:
It should be the day1 issue, but it was exposed by PR https://github.com/sonic-net/sonic-mgmt/pull/16897
add quotes to ensure that the entire string is treated as a single argument
local run 
pfcwd/test_pfcwd_timer_accuracy.py::TestPfcwdAllTimer::test_pfcwd_timer_accuracy[bjw-can-7050qx-1] 
----------------------------------------------------------------------------------- live log call -----------------------------------------------------------------------------------
12:56:13 test_pfcwd_timer_accuracy.retrieve_times L0349 WARNING| Get timestamp: An unexpected error occurred: pattern [P]FC_STORM_END err run module shell failed, Ansible Results =>
failed = True
changed = True
rc = 1
cmd = grep "[P]FC_STORM_END" /var/log/syslog
start = 2025-02-14 …

[test_pfcwd_timer_accuracy]: fix pfc timer accuracy date cmd input string issue

---

tests/common/macsec/macsec_helper.py

Summary:
Two of the PR's passed different set of parameters to the API get_macsec_counters.
https://github.com/sonic-net/sonic-mgmt/pull/15257
https://github.com/sonic-net/sonic-mgmt/pull/15905
Fix is to use the latest change made as per https://github.com/sonic-net/sonic-mgmt/pull/15257

Fix to correct the parameters passed to this API get_macsec_counters

---

tests/syslog/test_syslog_source_ip.py

Summary:
Without safe_reload, it's not enough time to wait system healthy. safe_reload will check critical services after reload.
Add safe_reload=True, for config_reload
Run test_syslog_source_ip on testbed.

Add safe_reload for config_reload in test_syslog_srouce_ip

---

tests/snmp/test_snmp_queue_counters.py

The interface from  where the queuestats fetched was different from the interface that was deleted from the BUFFER_QUEUE.
Github  issue: https://github.com/aristanetworks/sonic-qual.msft/issues/371
This issue is seen after PR: https://github.com/sonic-net/sonic-mgmt/pull/15688
The issue was that 
XML dump  is below for context
```
buffer_queue_to_del = 'Ethernet112|6'
buffer_queues = ['Ethernet112|0-1', 'Ethernet112|2-4', 'Ethernet112|5', 'Ethernet112|6', 'Ethernet112|7', 'Ethernet116|0-1', ...]
buffer_queues_removed = 1
interface  = 'Ethernet68'
```
When the string 'Ethernet112|6' when split with delimiter "|" the string in 1st index "6" is a substring of "Ethernet68" and it picked as a candidate to delete it from BQ, which is wrong.
Summary:
Fixes # …

Fixed logic to delete the interface from BUFFER_QUEUE

---

tests/generic_config_updater/templates/create_arp_forward_rule.json
tests/generic_config_updater/templates/create_dhcp_forward_rule_both.json
tests/generic_config_updater/templates/create_forward_rules.j2
tests/generic_config_updater/templates/create_initial_drop_rule.j2
tests/generic_config_updater/templates/create_ndp_forward_rule.json
tests/generic_config_updater/templates/create_secondary_drop_rule.j2
tests/generic_config_updater/templates/create_secondary_forward_rules.j2
tests/generic_config_updater/templates/create_three_drop_rules.j2
tests/generic_config_updater/templates/replace_nonexistent_rule.json
tests/generic_config_updater/templates/replace_rules.j2
tests/generic_config_updater/test_dynamic_acl.py

Lowers rule priorities of dynamic acl test rules so that they correctly have less priority than the hardcoded rule in dualtor devices

Lower Dynamic ACL test rules to fix bug in dualtor devices

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
This PR is to skip `test_syslog_source_ip` due to testbed unreachable issue https://github.com/sonic-net/sonic-mgmt/issues/16997
There are some testbed unreachable after running test `test_syslog_source_ip` .
Update tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
```
collected 15 items                                                                                                                                                                                                            
syslog/test_syslog_source_ip.py::TestSSIP::test_basic_syslog_config[str-msn2700-22-None-vrf_unset_source_unset_port_None] SKIPPED (Vs setup doesn't work when creating mgmt vrf)                                        [  6%] …
```

Skip test_syslog_source_ip due to testbed unreachable issue

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Some new Cisco platforms for 8122 are running tests now, e.g.`x86_64-8122_64ehf_o-r0`.
Since these test markings for QOS SAI apply generally to the 8122 series Cisco asic, catch all future such platforms. 
Improve and help future-proof further issues for QOS SAI in this area.
Before change, was seeing "VOQ" tests running when they should not be on this architecture, e.g.:
- testQosSaiLosslessVoq
- testQosSaiLosslessVoq
- testQosSaiLossyQueueVoqMultiSrc
With change, these are now skipped or unskipped appropriately. e.g. testQosSaiPgHeadroomWatermark is now verified unskipped and running for x86_64-8122_64ehf_o-r0. 
qos/test_qos_dscp_mapping also xfails as desired for this platform.
Cisco-8000 only.

Generalize Cisco 8122 test markings for QOS SAI

---

tests/qos/qos_helpers.py
tests/qos/test_pfc_pause.py

Summary:
As new testbeds are being created with more VLANs, the assumption that a device should only contain 1 VLAN no longer holds. As such, certain helpers/parts of the framework need to be modified to allow for multiple VLANs to be present and tested.
1. Added a `get_all_vlans` function to extract all vlans from the duthost object
2. The functions which get information related to vlans (`get_active_vlan_members` and `get_vlan_subnet`) now take a vlan configuration dictionary (which itself is taken from the get_all_vlans function)
3. `pfc_test_setup` now returns a list of VLAN configurations, instead of just one
4. The `run_test` wrapper now runs the relevant test for each VLAN supplied
5. Also removed `gen_testbed_t0`, which is not used anywhere (validated with grep)
Before this …

[QOS - Test PFC Pause] Multi VLAN Support

---

tests/common/helpers/tacacs/tacacs_helper.py

Increase tacacs server reachability check timeout.
In some test environments, the IPV6 network is not stable, increase timeout to improve test case pass rate. 
- Microsoft ADO: 31219981
Increase timeout to 2 minutes.
Increase tacacs server reachability check timeout

[TACACS] Increase tacacs server reachability check timeout

---

tests/test_parallel_modes/cisco_t2_8800.json

Enable parallel run for test_nbr_health.py
Summary:
Fixes # (issue) Microsoft ADO 28851202
We wanted to enable parallel run for `test_nbr_health.py` to reduce the time taken for the test to run
I ran the updated code and can confirm it's working well. Elastictest [link](https://elastictest.org/scheduler/testplan/67b3fdf19e505949e9369f58?testcase=test_nbr_health.py_svcstr2-8800-lc2-1&type=console)

chore: enable parallel run for nbr health test

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
PR https://github.com/sonic-net/sonic-mgmt/pull/16998 was raised to skip the test on all platform because some testbeds were unreachable after running this test module `test_syslog_source_ip`.
However, test case `test_syslog_config_work_after_reboot` is still running because the the longest path matching policy. 
This PR addressed the issue by removing the condition for `syslog/test_syslog_source_ip.py::TestSSIP::test_syslog_config_work_after_reboot`, and adding the github issue to condition `syslog/test_syslog_source_ip.py::TestSSIP::test_syslog_protocol_filter_severity`.
This PR is to skip the test case `test_syslog_source_ip` to avoid testbed unreachable issue.
1. Remove the condition for `syslog/test_syslog_source_ip.py::TestSSIP::test_syslog_config_work_after_ …

Skip test_syslog_source_ip to avoid testbed unreachable issue

---

docs/testplan/BGP-Router-ID-test-plan.md

Summary:
Add test plan for bgp router id

[bgp][test plan] Add test plan for bgp router id

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Vxlan hash and Nvgre hash are not supported on M* topology. So we skip the testcases.
Vxlan hash and Nvgre hash are not supported on M* topology. So we skip the testcases.
Skip testcase via conditional mark.
```
fib/test_fib.py::test_basic_fib[True-True-1514] PASSED                                                                                  [  6%]
fib/test_fib.py::test_hash[ipv4] PASSED                                                                                                 [ 12%]
fib/test_fib.py::test_hash[ipv6] PASSED                                                                                                 [ 18%]
fib/test_fib.py::test_ipinip_hash[ipv4] SKIPPED (The test case runs on T1 topology) …
```

[M0/Mx] Skip Vxlan hash and Nvgre hash test on M0/Mx testbeds

---

ansible/roles/test/files/ptftests/py3/advanced-reboot.py

Summary: Improve timing of starting tcpdump relative to packet sending in advanced-reboot
In advanced-reboot, sender can start after the sleep but there is no guarantee that the sniffer (tcpdump) would be ready by then. 
Move start of sender to after tcpdump has fully started to ensure all packets are captured.

Ensure that packets start sending after tcpdump has started in advanced-reboot

---

tests/l2/test_l2_configure.py

Summary:
`test_l2_configure` moves the `/etc/sonic/minigraph.xml`, but when it fails, it won't restore the minigraph file.
let's ensure the minigraph is restored in this situation.
Wrap the test operations in a `try ... finally` block, and put the minigraph restore in the `finally` clause.
Run on dualtor testbed.

[test_l2_configure] Ensure minigraph restore when the test fails

---

tests/common/helpers/tacacs/tacacs_helper.py
tests/tacacs/test_ro_user.py

Increase test_ro_user_banned_command test case tacacs config update check timeout
The test case test_ro_user_banned_command is not stable, randomly failed because hostcfgd not update tacacs config in 2 minutes
- Microsoft ADO: 31344522
Increase timeout to 4 minutes.
Increase test_ro_user_banned_command test case tacacs config update check timeout

[TACACS] Increase test_ro_user_banned_command test case tacacs config update check timeout

---

tests/pc/test_lag_member.py

Summary:
Fixes #16891
Fix failing pc/test_lag_member.py::test_lag_member_status by ensuring arp_responder.py is copied over to the PTF host during test setup.
Fix pc/test_lag_member.py failing
Ensure arp_responder.py is copied over to the PTF host during test setup
Ran and verified pc/test_lag_member.py::test_lag_member_status passes

[202411] Fix test_lag_member.py::test_lag_member_status arp responder

---

tests/bgp/test_bgp_route_neigh_learning.py

Summary:
The test `test_bgp_route_neigh_learning.py::test_bgp_neighbor_route_learnning` modifies the CEOS VM's BGP configuration as part of the test. However, it assumes that the BGP AS number to always be `64600`, which is not the case.
Test was failing. The reason was because the test assumes the BGP AS number to always be `64600`
Query the DUT for each neighboring VM's BGP AS number instead of assuming its `64600`.
Test no longer fails.

Fix bgp/test_bgp_route_neigh_learning.py BGP AS assumption

---

ansible/roles/test/files/acstests/everflow_policer_test.py

Summary:
This PR is to fix `test_everflow_dscp_with_policer` in Py3 environment.
The error message is 
```
File "acstests/everflow_policer_test.py", line 324, in runTest
count = self.checkOriginalFlow()
File "acstests/everflow_policer_test.py", line 183, in checkOriginalFlow
testutils.send_packet(self, self.src_port, str(self.base_pkt), count=self.NUM_OF_TOTAL_PACKETS)
File "/root/env-python3/lib/python3.7/site-packages/ptf/testutils.py", line 3202, in send_packet
pkt = bytes(pkt)
TypeError: string argument without an encoding
```
This PR is to fix `test_everflow_dscp_with_policer` in Py3 environment.
Remove the conversion to str.
```
collected 2 items …
```

Fix test_everflow_dscp_with_policer in py3 env

---

ansible/templates/minigraph_link_meta.j2
ansible/vars/topo_t0-56-o8v48.yml

This PR updates the `minigraph_link_meta.j2` template and topology configuration to enhance how AutoNegotiation (`autoneg`) interfaces are processed in SONiC's Ansible scripts. The changes streamline interface detection and remove redundant conditions.
Summary:
- Removed dependency on `msft_an_enabled` for processing `autoneg_interfaces`.
- Improved logic to check for `'autoneg'` directly in `device_conn` rather than relying on predefined interface lists.
- Ensured FEC settings are included only if `msft_an_enabled` is defined.

Enhance minigraph link template for autonegotiation and remove requirement to add autoneg interfaces in topo file

---

tests/bgp/test_bgp_suppress_fib.py

Update vrf configuration to pass the yang validation.
1. Add 'BGP_GLOBALS' into config db
2. Remove 'nhopself' and 'rrclient' from 'BGP_NEIGHBOR'
Summary:
Fix the yang validation failure of vrf configuration.
1. Add 'BGP_GLOBALS' into config db
2. Remove 'nhopself' and 'rrclient' from 'BGP_NEIGHBOR'

Update bgp suppress fib script for vrf case

---

tests/common/helpers/tacacs/tacacs_helper.py
tests/zmq/test_gnmi_zmq.py

Increase ZMQ test case config change timeout
The test case zmq/test_gnmi_zmq.py failed on Mellanox 2700 device because GNMI service take 4 minutes to start after config reload.
- Microsoft ADO: 30980895
Increase ZMQ test case config change timeout
Increase ZMQ test case config change timeout

[ZMQ] Increase ZMQ test case config change timeout

---

tests/generic_config_updater/test_dynamic_acl.py

Summary:
GCU test_dynamic_acl  failed on dualtor after https://github.com/sonic-net/sonic-mgmt/pull/16637
```
generic_config_updater/test_dynamic_acl.py::test_gcu_acl_arp_rule_creation[IPV4-str2-7050cx3-acs-06-None-default-Vlan1000] 
-------------------------------- live log setup --------------------------------
12:25:59 __init__._fixture_func_decorator         L0073 ERROR  | 
AddrFormatError("failed to detect a valid IP address from 'grat_arp'")
File "/var/src/sonic-mgmt_vms24-dual-t0-7050-1_646f1405735219c3e54440f4/tests/common/plugins/log_section_start/__init__.py", line 71, in _fixture_func_decorator
return fixture_func(*args, **kargs)
File "/var/src/sonic-mgmt_vms24-dual-t0-7050-1_646f1405735219c3e54440f4/tests/generic_config_updater …
```

Fix failures of test_dynamic_acl on dualtor

---

tests/vxlan/test_vxlan_bfd_tsa.py

Summary:
In `test_vxlan_bfd_tsa`, it will do `config save` command and after enable bfd session, iptables will add the following iptables rules, and it didn't have any chance to restore the configuration after the test. These iptables rules will be left on the DUT, which will impact the test results for `test_cacl_application`.
```
iptables -I INPUT 2 -p udp -m multiport --dports 3784,4784 -j ACCEPT
ip6tables -I INPUT 2 -p udp -m multiport --dports 3784,4784 -j ACCEPT
```
Backup and restore configuration for test_vxlan_bfd_tsa
Call the existing function `backup_and_restore_config_db_on_dut`s in `fixture_setUp` fixture of `test_vxlan_bfd_tsa`  and do `config reload` after `config_db.json` restoration.
Run test_vxlan_bfd_tsa on dut and check if

Restore configuration after test_vxlan_bfd_tsa.py

---

tests/pfcwd/cisco/set_pfc_time.py
tests/pfcwd/conftest.py

Summary:
We recently introduced a new fixture to use debug-shell in cisco-8000 to remove flakyness in the pfcwd scripts that use pfc_gen.py. But the previous PR restricts the new fixture to only T2/modular-chassis. In this PR, we open up the fixture to all cisco-8000, for any topology.
Removing flakyness in pfcwdd scripts that use pfc_gen.py.
Built on the last PR that implemented the new fixture only for T2.
Ran it on my TB:
```
---------------------------------------------------- generated xml file: /run_logs/pfcwd_t0t1/2025-02-06-21-11-50/pfcwd/pfcwd/test_pfcwd_function_2025-02-06-21-11-50.xml ----------------------------------------------------
--------------------------------------------------------------------------------------------------- live log sessionfinish …
```

cisco-8000: pfcwd: Open up the new pfcwd fixture for t0/t1.

---

tests/scripts/getbuild.py

The previous code retrieved all images from the `Azure.sonic-buildimage` pipeline, which does not include the 202412 branch. This PR resolves the issue by adding a conditional check. If the branch is 202412, the image will be downloaded from the `Azure.sonic-buildimage-msft.PR` pipeline (definitionId: 2511).
Summary:
The previous code retrieved all images from the `Azure.sonic-buildimage` pipeline, which does not include the 202412 branch. This PR resolves the issue by adding a conditional check. If the branch is 202412, the image will be downloaded from the `Azure.sonic-buildimage-msft.PR` pipeline (definitionId: 2511).
This PR resolves the issue by adding a conditional check. If the branch is 202412, the image will be downloaded from the `Azure.sonic-buildimage-msft.PR` …

Support downloading buildimage from 202412 branch. 

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
This PR is to skip `test_everflow_frwd_with_bkg_trf` on dualtor platform due to issue https://github.com/sonic-net/sonic-mgmt/issues/17034
This PR is to skip `test_everflow_frwd_with_bkg_trf` on dualtor.
Update tests/common/plugins/conditional_mark/tests_mark_conditions.yaml.
The change is verified by YAML syntax check and run it on a dualor testbed.
```
collecting 2 items …
```

Skip test_everflow_frwd_with_bkg_trf on dualtor platform

---

tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py

What I did:
Fix the logic of getting pid of process inside container for BGP convergence testing
Why I did:
Current logic to parse output and doing split is not reliable and was not working on packet-chassis.
How I verify:
After fixing test was working fine.

Fix the logic of getting pid of process inside container for BGP convergence testing

---

tests/common/fixtures/advanced_reboot.py
tests/common/fixtures/consistency_checker/consistency_checker.py
tests/common/fixtures/consistency_checker/constants.py
tests/common/helpers/upgrade_helpers.py
tests/platform_tests/test_advanced_reboot.py
tests/upgrade_path/test_multi_hop_upgrade_path.py
tests/upgrade_path/test_upgrade_path.py

Summary: Added consistency checker to all relevant advanced-reboot cases and added minor improvements including:
- Ignoring NULL values in ASIC querying
- Logging ASIC/DB inconsistencies

Added consistency checker to all relevant advanced-reboot cases

---

tests/tacacs/test_authorization.py
tests/tacacs/utils.py

Summary:
In tacacs tests, there are lots of verify codes like `pytest_assert(exit_code == 0)` didn't print any error message, only a return code, which caused some difficulty when debugging flaky issues.
Print error command and messages when running ssh commands failed in tacacs tests

Print error logs when running ssh commands in tacacs tests

---

.azure-pipelines/pr_test_scripts.yaml
azure-pipelines.yml

Summary:
We have added lots of control plane and data plane test to PR test in master branch, and onboarding test job was created for piloting.
Currently we have finished the job in master branch, if we need to backport to 202411, will do cherry-pick and use impact area for PR test, do not need onboarding test job anymore.
Remove onboarding test jobs and test scripts in 202411 branch

[202411] Remove onboarding test jobs and test scripts

---

ansible/vars/configdb_jsons/7nodes_cisco/P1.json
ansible/vars/configdb_jsons/7nodes_cisco/P2.json
ansible/vars/configdb_jsons/7nodes_cisco/P3.json
ansible/vars/configdb_jsons/7nodes_cisco/P4.json
ansible/vars/configdb_jsons/7nodes_cisco/PE1.json
ansible/vars/configdb_jsons/7nodes_cisco/PE2.json
ansible/vars/configdb_jsons/7nodes_cisco/PE3.json

…nodes_cisco
Summary:
Add a field "ring_thread_enabled"  in every node in `confdb_jsons/7nodes_cisco`  to enable ring feature by default in this topology
ring buffer feature should be able to get turned on/off by a flag in configuration
Add a field "ring_thread_enabled" in "DEVICE_METADATA"| "localhost" table
https://github.com/sonic-net/sonic-buildimage/pull/19652/
No

Add "ring_thread_enabled" field in confdb_jsons/7nodes_cisco

---

tests/gnmi/helper.py

Summary:
ADO: 30909878
- [] 202012
- [] 202205
- [] 202305
- [] 202311
The test will fail if the dut time is not in sync with the NTP Server because the gnmi certs have dependency upon system time.
Syncing the dut time with NTP server while applying the certs
Ran it on Microsoft Lab testbed

Gnmi Test Case Fix

---

tests/common/helpers/tacacs/tacacs_helper.py
tests/zmq/test_gnmi_zmq.py

Disable LogAnalyzer during ZMQ test
The test case zmq/test_gnmi_zmq.py failed because LogAnalyzer found some error message, which is not related with ZMQ feature.
The test case is GNMI test, not touch any syncd related feature:
On 720dt has following error, which already confirmed fixed on latest release:
expected_missing_match: 0 Match Messages: 2025 Jan 20 17:50:16.879657 bjw2-can-720dt-1 ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:509 Invalid sai_api_t 536870912 passed to sai_api_query 2025 Jan 20 17:50:16.879657 bjw2-can-720dt-1 ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:509 Invalid sai_api_t 536870913 passed to sai_api_query 2025 Jan 20 17:50:16.879657 bjw2-can-720dt-1 ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:509 Invalid sai_api_t …

[ZMQ] Ignore loganalyzer during ZMQ test

---

tests/srv6/test_srv6_static_config.py

Summary: Add a pytest asic marker to restrict test_uDT46_config to only run on the VS platform.
The programming of uDT46 entries is currently not supported in physical hardware.

Mark test_uDT46_config as only applicable to VS platform

---

tests/pfcwd/conftest.py
tests/pfcwd/test_pfcwd_function.py

Summary:
pfcwd_multi_port test failed when using the longer PFC_STORM_TIMEOUT seconds. We found this is due to fake-storm flag. After disabling the fake-storm, the test is passing.
Enabling the longer pfc storm timeout and disabling fake-storm for cisco-8000.
Enabled the if conditions for mellanox to include cisco-8000.
Ran it on my TB, verified on 8102, 8111 and T2:
8102 run log:
```
collected 5 items                                                                                                                                                                                                            
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_actions[mth-t0-64] PASSED …
```

Porting 16695 to 202411, set fake_storm to false for cisco-8000.

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Warmboot is not required for 202412 PR testing and currently fails during the process. To address this, we will bypass it in 202412 PR testing.
Summary:
Warmboot is not required for 202412 PR testing and currently fails during the process. To address this, we will bypass it in 202412 PR testing.
Use conditional mark to skip test case `platform_tests/test_advanced_reboot.py::test_warm_reboot`.

Skip warm reboot related tests in 202412 testing

---

tests/wol/test_wol.py

Summary:
Enable WoL test on M0 topo.
Enable WoL test on M0 topo.
Add `m0` to pytest mark.
Verified on Arista-720DT M0 testbed.
```
wol/test_wol.py::TestWOLSendFromInterface::test_wol_send_from_interface[False-None-None-None] PASSED                                                          [  1%]
wol/test_wol.py::TestWOLSendFromInterface::test_wol_send_from_interface[False-None-3-1000] PASSED                                                             [  3%]
wol/test_wol.py::TestWOLSendFromInterface::test_wol_send_from_interface[False-11:22:33:44:55:66-None-None] PASSED                                             [  5%]
wol/test_wol.py::TestWOLSendFromInterface::test_wol_send_from_interface[False-11:22:33:44:55:66-3-1000] PASSED                                                [  7%] …
```

[WoL] Enable WoL test on M0 topo

---

ansible/lab
ansible/roles/vm_set/tasks/docker.yml
ansible/vars/configdb_jsons/7nodes_force10/P1.json
ansible/vars/configdb_jsons/7nodes_force10/P2.json
ansible/vars/configdb_jsons/7nodes_force10/P3.json
ansible/vars/configdb_jsons/7nodes_force10/P4.json
ansible/vars/configdb_jsons/7nodes_force10/PE1.json
ansible/vars/configdb_jsons/7nodes_force10/PE2.json
ansible/vars/configdb_jsons/7nodes_force10/PE3.json
ansible/vars/init_cfg_profiles.yml
ansible/vars/topo_force10-7nodes.yml
ansible/veos_vtb
ansible/vtestbed.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/srv6/test_srv6_basic_sanity.py

In #15349 and #15723 , the 7-nodes testbed for SRv6 based on Cisco VS hwsku was added with the corresponding tests. In this PR, a testbed with similar config to the cisco one, but based on Force 10 hwsku, is introduced.
The cisco vs testbed requires specific SONiC image and data plane emulation toolset from Cisco to work. Therefore, for the sake of testing the control plane only using SONiC images with the `vs` hwsku, this testbed is added.
Additionally, tests for SRv6 that don't require data plane (i.e. non-traffic-check cases) are enabled for the new Force 10 testbed. 
Summary:
~Fixes # (issue)~ (Not appliciable)
Enable the control plane test for SRv6 with a `vs` hwsku, without any specific emulation software.
Duplicate the configuration from the cisco vs testbed, and modify it for …

Add 7 nodes SRv6 testbed configuration based on Force 10 hwsku

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py
ansible/roles/test/tasks/dir_bcast.yml
ansible/roles/test/tasks/fdb.yml
ansible/roles/test/tasks/fdb_mac_expire.yml
ansible/roles/test/tasks/pfc_wd/choose_test_port.yml
ansible/roles/test/tasks/pfc_wd/iterate_portchannels.yml
ansible/roles/test/tasks/qos_sai.yml
ansible/roles/test/tasks/shared-fib.yml
ansible/roles/test/tasks/warm-reboot-multi-sad.yml
ansible/roles/test/tasks/warm-reboot-sad-lag-member.yml
ansible/roles/test/templates/fib.j2
ansible/roles/test/vars/testcases.yml
ansible/testbed-new.yaml
tests/common/platform/warmboot_sad_cases.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
tests/fdb/test_fdb.py
tests/qos/qos_sai_base.py
tests/qos/test_qos_sai.py
tests/saitests/py3/sai_qos_tests.py

Summary:
Add Arista-7260CX3-D108C10 t0-118 test configs (emulate t0-116 configs)
Add t0-118 test configs to sonic-mgmt
Arista-7260CX3-D108C10

Add t0-118 topo test configs

---

ansible/roles/test/files/ptftests/py3/vxlan-decap.py
tests/vxlan/test_vxlan_decap.py

Summary:
The vxlan-decap testcases cannot be supported in some testbeds without port-channel
Adapting the test parameters on both portchannel and non-portchannel scenarioes.
Run it on non-portchannel platform:
```
==================================================================================================================================== test session starts =====================================================================================================================================
platform linux -- Python 3.8.10, pytest-7.4.0, pluggy-1.5.0
ansible: 2.13.13
rootdir: /data/sonic-mgmt-int/tests
configfile: pytest.ini
plugins: ansible-4.0.0, metadata-3.1.1, html-4.1.1, xdist-1.28.0, forked-1.6.0, repeat-0.9.3, allure-pytest-2.8.22
collecting ... …
```

[vxlan]: Enhance vxlan decap test to support non-portchannel testcases

---

tests/bgp/test_bgp_suppress_fib.py

Stabilize bgp suppress fib test on the switch with low power CPU(sn2700 A0) and a lot of BGP neighbors
Adjust performance threshold according to design suggestion and test result
Summary:
Stabilize bgp suppress fib test on the switch with low power CPU and a lot of BGP neighbors
Based on the design suggestion and test result, update the time threshold for 1K BGP route average process.
Run it at local setup

Stabilize bgp suppress fib test on switch with low power CPU and a lot of BGP neighbors

---

tests/zmq/test_gnmi_zmq.py

Fix GNMI ZMQ test case failed because python2 deprecated on latest pft docker image.
GNMI ZMQ test case failed on some pfthost, it's because python2 deprecated on latest pft docker image.
- Microsoft ADO: 
Change GNMI ZMQ test case use python.
Fix GNMI ZMQ test case failed because python2 missing on ptfhost.

Fix GNMI ZMQ test case failed because python2 deprecated on latest pft docker image.

---

tests/platform_tests/test_process_reboot_cause.py

The [process-reboot-cause](https://github.com/sonic-net/sonic-host-services/blob/master/scripts/process-reboot-cause) populates the STATE_DB with the most recent and 10 previous reboot causes. The script does this by reading `reboot-cause_*.json` files present in `/host/reboot-cause/history` populated by a different script.
This PR addresses the sonic-mgmt test gap for the following scenarios this script might encounter:
**1. test_status_on_boot**
This test asserts that the process-reboot-cause service ran sucessfully on boot, the result of the ExecStart process was successful and it's exit status is 0.
**2. test_empty_json_file**
This test creates an empty JSON file in the history directory and re-runs the process-reboot-cause service. It then asserts, based on the image version, that …

Added sonic-mgmt tests for process-reboot-cause script

---

tests/common/plugins/sanity_check/checks.py

Summary:
Skip the `mux_simulator` status check in sanity on `dualtor-aa` testbeds.
run on `dualtor-aa` testbed:
```
dualtor_io/test_tor_failure.py::test_active_tor_reboot_downstream[active-active] PASSED                                                                                                                                                                                [100%]
```

[dualtor-aa][sanity] Skip active-standby checks in sanity

---

tests/snmp/test_snmp_queue_counters.py

https://github.com/sonic-net/sonic-mgmt/pull/16687 recently merged to fix an issue on non-chassis systems but it broke chassis systems as described in https://github.com/sonic-net/sonic-mgmt/issues/17131
This change will solve the issue originally targeted by https://github.com/sonic-net/sonic-mgmt/pull/16687
Where 'Ethernet112|6' when split with delimiter "|" the string in 1st index "6" is a substring of "Ethernet68"
By using `val == interface` it no longer matters if the buffer queue matches up a substring of the interface.
Summary:
Fixes #17131

Fixing `PR16687` to work for chassis and non-chassis

---

tests/common/plugins/conditional_mark/README.md
tests/common/plugins/conditional_mark/__init__.py

In PR #14395, we optimized the matching rule for conditional marks by considering all potential matches. If a mark is unique among these matches, it is applied to the test case. Otherwise, the longest matching entry is used.
In this PR, we further refine this logic by ensuring that the longest match where the condition is true is used. This means that if the conditions of the longest matching entry are false,  we will consider the next longest matching entry.
Summary:
In PR #14395, we optimized the matching rule for conditional marks by considering all potential matches. If a mark is unique among these matches, it is applied to the test case. Otherwise, the longest matching entry is used.
In this PR, we further refine this logic by ensuring that the longest match where the …

Refine the logic of matching conditional mark.

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
This PR is to skip `test_everflow_frwd_with_bkg_trf` on dualtor and Non-T2 platform due to issue https://github.com/sonic-net/sonic-mgmt/issues/17034
This PR is to skip `test_everflow_frwd_with_bkg_trf` on dualtor and Non-T2 platform.
Update tests/common/plugins/conditional_mark/tests_mark_conditions.yaml.
The change is verified by YAML syntax check and run it on a dualor testbed.
```
collecting 2 items …
```

Skip test_everflow_frwd_with_bkg_trf on dualtor and Non-T2 platform

---

tests/dualtor/test_switchover_faulty_ycable.py

Summary:
`test_switchover_faulty_ycable` uses faulty ycable driver, which will trigger the following errors that need to be ignored:
```
E               2025 Feb 26 06:30:44.358985 bjw2-can-7260-4 ERR pmon#CCmisApi: Error: Could not establish the active side for Y cable port Ethernet0 to perform read_y_cable update state db
E
E               2025 Feb 26 06:30:44.406811 bjw2-can-7260-4 ERR pmon#CCmisApi: Error: Could not establish the active side for Y cable port Ethernet4 to perform read_y_cable update state db
E
E               2025 Feb 26 06:30:44.452066 bjw2-can-7260-4 ERR pmon#CCmisApi: Error: Could not establish the active side for Y cable port Ethernet8 to perform read_y_cable update state db
E
E               2025 Feb 26 …
```

[test_switchover_faulty_ycable] Ignore pmon errors on the correct ToR

---

tests/dualtor_io/test_tor_bgp_failure.py

Summary:
The following errors should be ignored as bgpd is killed:
```
E               2025 Feb  5 23:19:11.881870 str2-7050cx3-acs-07 ERR bgp#bgpmon: *ERROR* Failed with rc:1 when execute: ['vtysh', '-H', '/dev/null', '-c', 'show bgp summary json']
E               2025 Feb  5 23:19:25.232074 str2-7050cx3-acs-07 ERR bgp#mgmtd[33]: [X3G8F-PM93W] BE-adapter: mgmt_msg_read: got EOF/disconnect
E               2025 Feb  5 23:19:25.565904 str2-7050cx3-acs-07 ERR bgp#mgmtd[33]: [X3G8F-PM93W] BE-adapter: mgmt_msg_read: got EOF/disconnect
```
Add regex strings to the ignore list.
```
dualtor_io/test_tor_bgp_failure.py::test_standby_tor_kill_bgpd_downstream_active[active-st …
```

[dualtor-io] Update the ignored kill-bgp errors

---

tests/bgp/test_bgp_bbr_default_state.py

Add safe_reload flag to config_reload method to ensure device is ready to execute commands.
Otherwise the following command `show runningconfiguration bgp | grep allowas` may fail.
Change-Id: Ibb4c83671b31d4d9267bc024d6640f9315974b88
Summary:
I've run the `test_bbr_disabled_constants_yml_default` test in a loop to verify there is no issue with executing commands on the DUT right after a config reload.

add safe_reload flag in test_bbr_disabled_constants_yml_default

---

tests/dhcp_relay/test_dhcp_relay.py

use config interface command instead of ifconfig to shut down/bring up the interface
the motivation to make the command compatible with interfaces, not only portchannels
Summary:
the motivation is to make the command compatible with interfaces, not only portchannels
Ran test_dhcp_relay_after_link_flap on t0-128 topology

DHCP_RELAY: use config interface instead of ifconfig

---

tests/platform_tests/test_intf_fec.py

**Summary:** This patch removes unused function arguments, fixes inconsistent interface name handling, corrects command formatting errors, and simplifies error handling in FEC-related test cases.
get_fec_eligible_interfaces() returns list of interface names and not the dictionary. Fix the interface names accordingly.
**Removed Unused Function Arguments**
The functions test_verify_fec_oper_mode, test_config_fec_oper_mode, test_verify_fec_stats_counters, and test_verify_fec_histogram previously accepted enum_frontend_asic_index and conn_graph_facts, which were unused.
These parameters have been removed to streamline function definitions.
**Fixed Incorrect Interface Input Handling**
The original code inconsistently accessed the interface name using both intf['interface'] and …

The patch corrects improper formatting and inconsistent interface input references

---

tests/clock/conftest.py
tests/clock/test_clock.py

Enable test_clock.py in all chassis, as its currently being skipped due to param requirement
Summary:
Fixes #31478372
Enable test_clock.py in all chassis, as its currently being skipped due to param requirement
Currently it requires --ntp_server='ip_adrs' in extra parameters to run the test, but it can be improved by using ntp_server address from inventory files.
Also refactor some code to make it compatible with T2 chassis
clock/test_clock.py has been skipped in all nightly, due to missing parameter 'ntp_server'. Since ntp_server exist and recorded in inventory already, it makes sense to use that value to run this test in nightly.
If extra parameter 'ntp_server' is not provided, use ntp_server from inventory instead.
checked the results against 202405 version and 202411 with this fix …

Enable skipped test due to extra param requirement

---

tests/qos/qos_sai_base.py

…ailure.
Summary:
Fixes [#460](https://github.com/aristanetworks/sonic-qual.msft/issues/460)
- [] 202405
1. Regression due to: https://github.com/sonic-net/sonic-mgmt/pull/15938
2. This PR changes the scope of swapSyncd_on_selected_duts and dut_disable_ipv6 from class to module.  This was to reduce execution time in T2. The fixtures used to fire multiple times for chassis.
3. There is a fixture in global conftest, `core_dump_and_config_check` which in its teardown restores DUT config to the state as it was prior to the test. https://github.com/sonic-net/sonic-mgmt/blob/202411/tests/conftest.py#L2542
4. All the three fixtures are currently autouse and module scoped and core_dump_and_config_check and dut_disable_ipv6 share no explicit dependencies hence they will fire in any order.
5. If …

Fix fixture invocation order in qos_sai_base.py to prevent teardown failure.

---

tests/fdb/test_fdb_mac_learning.py

Summary: [fdb/test_fdb_mac_learning.py] Correct regex to match log message repetetion
Fixes # https://github.com/aristanetworks/sonic-qual.msft/issues/422
Currently test is ignoring log `.*ERR swss#orchagent: :- update: Failed to get port by bridge port ID.*` (done through https://github.com/sonic-net/sonic-mgmt/pull/15797), but in case if the log message gets repeated multiple times then the log message looks like `ERR swss#orchagent: message repeated 3 times: [ :- update: Failed to get port by bridge port ID 0x3a000000000646.]`. Current ignore log regex is not considering log message repetition and thus failing some times during teardown.
Updated the regex to match on log message repetition as well.
Verified the test is passing consistently with the fix.

[fdb/test_fdb_mac_learning.py] Correct regex to match log message repetition

---

tests/qos/test_pfc_counters.py

Summary:
Test failures in test_pfc_counters.py
Change the 'duthosts[rand_one_tgen_dut_hostname]' to 'duthosts[enum_rand_one_per_hwsku_frontend_hostname]'
and.
'fanout_graph_facts' to 'enum_fanout_graph_facts'
Executed t2 test for broadcom-dnx chassis & verify the results.

[Qos]Fixture update for duthost selection in test_pfc_counter.py

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

ERR swss1#orchagent: :- handlePortStatusChangeNotification: Failed to get port object for port id 0x1010000000000df
This log is discussed here: https://github.com/sonic-net/sonic-buildimage/issues/16489
It's been ignored for specific tests here: https://github.com/Azure/sonic-mgmt.msft/commit/8e128b911b5464f361b505ee3c04d80d2a414fae
This is ignoring it in general as we've seen it in other tests:
```
-snmp/test_snmp_loopback.py::test_snmp_loopback::test_snmp_loopback
-voq/test_fabric_reach.py voq.test_fabric_reach test_fabric_reach_supervisor
-fib/test_fib.py::test_fib::test_basic_fib
-qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueue
```

Ignore the `handlePortStatusChangeNotification` log

---

tests/gnmi/test_gnmi.py

Reverts sonic-net/sonic-mgmt#16955
Fixes https://github.com/sonic-net/sonic-mgmt/issues/17126

Revert "Running test_gnmi.py on each hwsku instead of selecting one rand hwsku"

---

tests/route/test_route_consistency.py

We were seeing that we'd get occasional AssertionErrors in `test_route_withdraw_advertise` when the routes were advertised because we didn't wait long enough before the assertion.
Instead of increasing the `sleep` time further I converted the assertion to a `wait_until` so we will only wait as long as we need to.
Note: When casting to `202405` we'll need to add the include for `wait_until`, it's not in this PR because it's already included in `master`
`from tests.common.utilities import wait_until`

Change assertion to a `wait_until` in `test_route_withdraw_advertise`

---

ansible/templates/minigraph_link_meta.j2

This PR refactors minigraph_link_meta.j2 by:
- Replacing link_metadata_defined with Jinja2 namespace (ns) for better variable scoping.
- Optimizing auto-negotiation detection using selectattr() to reduce looping.
- Improving code readability with structured formatting and consistent indentation.
These changes enhance efficiency and maintainability without altering functionality.
Summary:
Correct the minigraph generation For autoneg in SONiC
This minigraph is generated
```
<LinkMetadataDeclaration>
<Link xmlns:a="http://schemas.datacontract.org/2004/07/Microsoft.Search.Autopilot.Evolution">
<a:LinkMetadata>
<a:Name i:nil="true"/>
<a:Properties>
<a:DeviceProperty>
<a:Name>AutoNegotiation</a:Name>
<a:Value>True</a:Value>
</a:DeviceProperty>
<a:DeviceProperty> …
```

[ansible] Correct the formatting for linkmetadata minigraph generation for autonegotiation

---

.azure-pipelines/pr_test_scripts.yaml
tests/dhcp_relay/test_dhcp_relay.py

Summary:
Skip test_dhcp_relay in vs with t0-2vlans topo due to flaky to unblock pr check
Skip test_dhcp_relay in vs with t0-2vlans topo due to flaky to unblock pr check
PR check

[dhcp_relay] Remove test_dhcp_relay test in t0-2vlans

---

tests/snappi_tests/multidut/bgp/conftest.py
tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_downlink_port_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_downlink_process_crash.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_tsa.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_ungraceful_restart.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_multi_po_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_member_flap.py
tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_process_crash.py
tests/snappi_tests/variables.py

Summary:
1. Infra changes to support automation of T2 DUT config using new tgen topo file using deploy-mg
2. Infra changes to support automation of T1 and Fanout config at runtime
For T2 Snappi based route convergence tests to be run through our Nightly pipeline, We need to be able to achieve T2 DUT initial config via deploy-mg
Also, T1 Config and fanout config needed to be automated(to avoid manual steps)
For the currently Nightly pipeline, infrastructure doesnt support multiple DUT type(t2, t1) in the testbed. As we can only provide single image path during the pipeline run.
To Achieve T2 DUT config automation: New topo files were checked in earlier via PR: https://github.com/sonic-net/sonic-mgmt/pull/16957
To achieve T1 and fanout initial config: wrote a placeholder initial_setup() …

T2-Snappi-Route-Conv: Initial DUT Config Automation, Remove T1 from DUTList

---

tests/bgp/test_bgp_authentication.py

Support EOS neighbor for `bgp/test_bgp_authentication.py` test.
Summary:
Fixes # (issue) Microsoft ADO 28851199
We want `bgp/test_bgp_authentication.py` to be able to run with EOS neighbors in order to resolve the test gap and increase test coverage.
I ran the updated code and can confirm it's working well with EOS neighbors. Elastictest [link](https://elastictest.org/scheduler/testplan/67c063887690266512706e68?leftSideViewMode=detail&testcase=bgp%2Ftest_bgp_authentication.py&type=console)

feat: support eos neighbor for bgp auth test

---

tests/qos/qos_sai_base.py
tests/saitests/py3/sai_qos_tests.py

Summary:
Fixes # 16314
The recent commit for dwrr works for multi-asic only. This PR handles the single asic platforms.
Making sure to use the correct container to use for single asic tests.
Not done yet. @kevinskwang , @yejianquan : Can you pls try this out ? I will try it when I get the testbed access.
For cisco-8000 only.

Prting 16315 to 202411: qos-sai:dwrr:cisco-8000:Handle non-multiasic part as well for the dshell-script change.

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Current hash logic can not support lag only and ecmp only hash
Summary:

Skip test_lag_hash and test_ecmp_hash on Cisco platform

---

ansible/roles/vm_set/library/vlan_port.py
tests/bgp/route_checker.py
tests/bgp/test_bgp_bbr.py
tests/bgp/test_traffic_shift.py
tests/common/dualtor/data_plane_utils.py
tests/common/dualtor/dual_tor_io.py
tests/common/dualtor/mux_simulator_control.py
tests/common/reboot.py
tests/common/utilities.py
tests/platform_tests/test_advanced_reboot.py
tests/platform_tests/test_cont_warm_reboot.py
tests/platform_tests/test_platform_info.py
tests/scp/test_scp_copy.py
tests/scripts/dual_tor_sniffer.py
tests/smartswitch/common/device_utils_dpu.py
tests/test_posttest.py
tests/test_pretest.py

Replace the deprecated `warn()` method with `warning()` for Python logging.
Summary:
The `warn()` method is deprecated since Python 3.3 and we will get the following warning if we still use the `warn()` method:
So we want to replace it with the `warning()` method. Reference: https://github.com/python/cpython/blob/3.3/Lib/logging/__init__.py#L1252-L1253

chore: replace warn with warning for logging

---

ansible/module_utils/port_utils.py

Add port interface support for MSM4280, HwSKU = ACS-SN4280
This PR is to add support for Nvidia smartswitch when creating ports.
Summary:
This PR is to add support for nvidia smartswitch when creating ports.
Local dev container within my own test environment
Added new lines to existing script and ran it within my own container.
Mellanox Nvidia MSN4280-WS2RXOS

Adding nvidia smartswitch support for MSN4280

---

tests/route/test_forced_mgmt_route.py

Enable `route/test_forced_mgmt_route.py::test_update_forced_mgmt` test case on T2 topo to resolve the T2 test gap.
Summary:
Fixes # (issue) Microsoft ADO 28837282
We want to run more tests on T2 topo to increase the test coverage. In this PR, we enabled `route/test_forced_mgmt_route.py::test_update_forced_mgmt` on T2 topo.
The other test case `test_forced_mgmt_route_add_and_remove_by_mgmt_port_status()` will still be skipped for multi-asic devices (for example, T2 devices) as I couldn't find a device with `eth1` port available, so I never got the chance to verify it. I have created a GitHub issue here to track this: #17250 
Elastictest link: https://elastictest.org/scheduler/testplan/67bf90c1fdc60a30648c223b?testcase=route%2Ftest_forced_mgmt_route.py&type=console&leftSideViewMode=detail

feat: enable forced mgmt route test on T2

---

tests/bgp/test_bgp_operation_in_ro.py

Summary:
[New Testcase] By mounting /tmp to tmpfs in #20640, we should be able to run BGP operations while device in RO filesystem. Add new testcase to verify this.
Add new testcase to verify BGP operations can run in RO state.
PR test and https://elastictest.org/scheduler/testplan/67c02654c28247f5cc75e265?testcase=bgp%2Ftest_bgp_operation_in_ro.py&type=console
Enable testcase on t0 and t1 to start with.

Add new testcase to run BGP operations in RO state

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Ignore ZMQ test case because python version changes in ptf image
ZMQ test case failed because python version changes in ptf image
- Microsoft ADO: 
Ignore ZMQ test case because python version changes in ptf image
Ignore ZMQ test case because python version changes in ptf image

Ignore ZMQ test case because python version changes in ptf image

---

tests/srv6/test_srv6_dataplane.py

Summary:
Previously, the `neighbor_ip` variable was not initialized before being assigned inside the loop. If the loop did not find a match, `neighbor_ip` remained undefined, leading to an `UnboundLocalError` when accessed later.
Initialize neighbor_ip before use to avoid UnboundLocalError
Initialized `neighbor_ip` to None before the loop.

Initialize neighbor_ip before use to avoid UnboundLocalError

---

ansible/roles/test/files/ptftests/py3/hash_test.py

Fix typo of UDP source port range.
Summary:
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/17223

Fix UDP port range typo

---

tests/cacl/test_cacl_application.py

Summary:
To address https://github.com/sonic-net/sonic-mgmt/issues/16548.
The issue https://github.com/sonic-net/sonic-buildimage/issues/21290, the issue of INFO level logs disappear in caclmgrd was reported after the commit got merged months later.
We need a test case to help us report this kind of issue earlier.
A new test case to check if INFO logs of caclmgrd was printed into syslog successfully.
1. rotate syslog
2. restart caclmgrd
3. check if iptables syslog existing in syslog file
4. Check if iptables rules are applied successfully in the output of systemctl status caclmgrd
Run the new test case on the testbed

[test gap] Add a new case to check caclmgrd syslog

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Skip dynamic ACL test on all Nokia 7215 devices.  Previous skip had a release qualifier which meant that it started running in 202411 devices.  This was not intentional

Remove release qualifier when skipping dynamic ACL test on Nokia 7215

---

tests/bgp/test_passive_peering.py
tests/common/devices/eos.py

chore: update test for t2
Summary:
Previously this test skipped for eos neighbor due to legacy. Now we should be able to enable this. This PR added the necessary changes to make this compatible
Fixes # (issue) 28839241
Adjust the relevant code to be compatible with eos neighbor. 
Verified on T2 testbed compatibility.

adding eos neighbor support for bgp passive peering

---

tests/platform_tests/link_flap/test_cont_link_flap.py

Add a 60s sleep to the end of `platform_tests/link_flap/test_cont_link_flap.py` test
Summary:
There could be a small chance that the `sudo route_check.py` ran during the teardown stage of `platform_tests/link_flap/test_cont_link_flap.py` test would fail

chore: add delay to the end of cont flap test

---

tests/vxlan/test_vnet_decap.py

This PR adds a test for VNet decapsulation. IP-in-IP packets that are sent to the switch are expected 
Summary:
Fixes #13122 
Microsoft ADO ID: 31628440
To test VNet decapsulation, we first configure a VXLAN tunnel, a VNet, and a VNet route with a single endpoint on the switch. Then we send an IP-in-IP packet to the switch with the following properties:
1. The outer IP packet is from an arbitrary address (192.168.0.1) to the VXLAN tunnel's src IP.
2. The inner IP packet is from an arbitrary address (192.168.0.1) to the VNet route's destination.
We verify that the switch sends out a VXLAN packet from the VXLAN tunnel's src IP to the VNet route's endpoint containing the inner IP packet.
Testing VNet decapsulation on T1 switches.
We configure a VXLAN tunnel, a VNet, and a VNet route with a …

Added a test for VNet IPinIP decapsulation

---

tests/common/plugins/conditional_mark/unit_test/README.md
tests/common/plugins/conditional_mark/unit_test/tests_conditions.yaml
tests/common/plugins/conditional_mark/unit_test/unittest_find_all_matches.py

This PR is based on PR #16930. After changing the logic of conditional marks, we need to add unit test to make sure it works as expected. 
Summary:
This PR is based on PR #16930. After changing the logic of conditional marks, we need to add unit test to make sure it works as expected. 
```
yutongzhang@sonic_mgmt:/data/sonic-mgmt$ python -m pytest --noconftest --capture=no tests/common/plugins/conditional_mark/unit_test/unittest_find_all_matches.py -v -s
tests/common/plugins/conditional_mark/unit_test/unittest_find_all_matches.py::TestFindAllMatches::test_all_false_conditions_in_matching_path_1 PASSED
tests/common/plugins/conditional_mark/unit_test/unittest_find_all_matches.py::TestFindAllMatches::test_all_false_conditions_in_matching_path_2 PASSED …
```

Add unit test for conditional marks. 

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
The feature is not ready for BRCM platform, need to xfail for BRCM before the fix is in place.
To xfail the test_lag_member_forwarding on BRCM platform. 
Xfail the test_lag_member_forwarding in conditional mark file. 
Run test.
Only xfail for BRCM platform.

[XFAIL] xfail test_lag_member_forwarding.py for platform

---

tests/bgp/test_bgp_fact.py
tests/bgp/test_bgp_router_id.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/ip/test_mgmt_ipv6_only.py

Summary:
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/17211
Add test for bgp router id: https://github.com/sonic-net/sonic-mgmt/pull/16896
1. Test in default config, bgp router id should be aligned with Loopback IPv4 address
2. Test when bgp_router_id and Loopback IPv4 address both exist in running config, bgp router id should be aligned with bgp_router_id in running config. And Loopback IPv4 address should be advertised to neighbor
3. Test when bgp_router_id configured but Loopback IPv4 address missing, bgp could work well.
Run test in m0/t0/t1/dualtor/dualtor-aa testbed, all passed

[202405][bgp] Add bgp router id test (#17211)

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary: Ignore DHCP relay related failed testcases (GCU, gNOI) as DHCP relay is not enabled for T0 using isolated topology.
Ignore DHCP relay related failed testcases (GCU, gNOI) as DHCP relay is not enabled on BT0.
```
SKIPPED [1] gnmi/test_gnoi_killprocess.py:14: DHCP relay is disabled on T0 using isolated topo
```
str4-sn5600-1
t0-isolated-u16d16s1

Ignore DHCP relay related testcases for testbed with DHCP relay feature disabled

---

tests/generic_config_updater/test_portchannel_interface.py

Summary:
Fixes # [438](https://github.com/aristanetworks/sonic-qual.msft/issues/438)
- Fixes failures in generic_config_updater/test_portchannel_interfaces.py failure on dualtor
- In dualtor topologies, the test picks ToR-A to apply portchannel config changes but verifies their effect on ToR-B instead, leading to test failure 
Use rand_one_dut_hostname to ensure the same ToR is picked throughout the test run 
Ran generic_config_updater/test_portchannel_interfaces.py on DCS-7260CX3 and DCS-7050CX3

Fix for generic_config_updater/test_portchannel_interfaces.py on dualtor

---

ansible/vars/topo_t1-isolated-d28u1.yml

Add "tornum" for t0 VM definition in ansible/vars/topo_t1-isolated-d28u1.yml to trigger exabgp announce route during topology deployment.
The "tornum" is necessary for generating routes from T0 VM:
https://github.com/sonic-net/sonic-mgmt/blob/221012beaac677677139fed1ab92cd0d5adad789/ansible/library/announce_routes.py#L417
>                 suffix = ((podset * tor_number * max_tor_subnet_number * tor_subnet_size) +
>                           (tor * max_tor_subnet_number * tor_subnet_size) +
>                           (subnet * tor_subnet_size))
>                 octet2 = (168 + int(suffix / (256 ** 2)))
>                 octet1 = (192 + int(octet2 / 256))
>                 octet2 = (octet2 % 256)
>                 octet3 = (int(suffix / 256) % 256)
>                 octet4 = (suffix % …

Topology definition update of topo_t1-isolated-d28u1.yml for exabgp failed to announce route from t0 VM

---

tests/restapi/test_restapi.py

Summary:
t0-isolated/t1-isolated topology doesn't support warm/fast reboot. 
Skip warm/fast reboot for restapi test case for isolated topology.
Running this test with t1-isolated topology will result in failure.
Skip it for isolated topologies.
Verified on physical testbed.

Skip warm/fast reboot for test_restapi.py for isolated topology

---

tests/pc/test_lag_member_forwarding.py

Summary:
Ignore invalid sai_api_t logs that does not affect functionality of test. Mainly affecting pc/test_lag_member_forwarding.py testing on 720DT
pc/test_lag_member_forwarding.py is failing due this log in loganalyzer that does not affect functionality of test. Broadcom will patch this error in the next PAI release. We will ignore this error for now.

Ignore gbsyncd invalid sai_api_t logs for pc/test_lag_member_forwarding.py

---

tests/copp/test_copp.py

For non T2 topologies, setting upStreamDuthost as duthost to cover dualToR scenarios.
Summary: Fix test_copp on non T2 topologies
Fix flaky test copp/test_copp.py on dualtor
Fixes # [#435](https://github.com/aristanetworks/sonic-qual.msft/issues/435)
BGP is shutdown on a TOR different from the one where package download is supposed to happen in DualTOR topology. The cause of the issue is T2 approach is being extended to multi DUT topologies which is leading to failures.
The DUT where package download is supposed to happen should match the one where BGP is being shutdown. In multi DUT  topologies with this change, we are making sure that BGP shutdown happens in the appropriate DUT.
Test is consistently passing with the fix. Tested with 202411 image on Arista-7050CX3 with dualtor-aa.

Fix test_copp on non T2 topologies

---

tests/everflow/test_everflow_testbed.py

Summary:
Fixes https://github.com/aristanetworks/sonic-qual.msft/issues/437
- Fix failures in everflow/test_everflow_testbed.py::test_everflow_frwd_with_bkg_trf is failing on dualtor-aa/dualtor-aa-56 variants 
- The test case brings down Bgp as part of the test. In the case of dualtor-aa/dualtor-aa-56, this causes the selected ToR on which Everflow is configured to transition into a standby ToR, affecting upstream and downstream test traffic flows. 
- In active-active dualtor topology variants, upstream traffic from the server can land on either of the ToRs - given we configure the Everflow rules on a single ToR, we want the traffic stream to always land on the selected ToR. This can be done by setting up the unselected ToR as the standby 
Calling fixtures …

Fix everflow/test_everflow_testbed.py for dualtor-aa/dualtor-aa-56

---

tests/common/plugins/conditional_mark/__init__.py
tests/common/plugins/conditional_mark/unit_test/README.md
tests/common/plugins/conditional_mark/unit_test/tests_conditions.yaml
tests/common/plugins/conditional_mark/unit_test/unittest_find_all_matches.py

In PR #16930, we refined the logic of conditional marking to ensure that the longest matching entry with a True condition is prioritized. If the condition for the longest match is False, we then consider the next longest match.
However, there is a special case where the longest match has a False condition, but we still want to adopt this False condition instead of falling back to shorter matches. For example, in a skip scenario:
- Shorter matching entries have True conditions, meaning the test should be skipped.
- The longest matching entry has a False condition, meaning the test should not be skipped.
- In this case, we actually want to respect the longest match and not skip the test.
To address this, this PR introduces a new key, `use_longest`. When `use_longest` is set to True, only …

Enhance conditional mark logic with `use_longest` for special cases

---

ansible/library/interface_facts.py
tests/bgp/test_bgp_dual_asn.py
tests/bgp/test_bgp_speaker.py
tests/common/helpers/dut_ports.py
tests/route/test_static_route.py
tests/test_interfaces.py

Summary:
Fix those failures on secondary subnet enabled testbed:
`test_interfaces.py` failed 
```
>           pytest_assert(found, "{} not found in the list {}".format(ip, ips_found))
E           Failed: 192.169.0.1 not found in the list ['192.168.0.1']
```
`bgp/test_bgp_speaker.py` failed:
```
stderr =
Error: inet6 prefix is expected rather than "192.169.0.2/22".
```
`route/test_static_route.py` failed:
```
AssertionError: config static route: 2000:1::/64 nexthop 192.169.0.26
real:
['']
```
`bgp/test_bgp_dual_asn.py` failed:
```
File "/usr/lib/python3.8/ipaddress.py", line 1844, in __init__
self._ip = self._ip_int_from_string(addr_str)
File "/usr/lib/python3.8/ipaddress.py", line 1581, in _ip_int_from_string
raise AddressValueError(msg)
ipaddress.AddressValueError: At …
```

Fix test case failures after secondary subnet enabled

---

tests/bgp/test_bgp_session.py

Summary:
Fixes the following error in `test_bgp_session.py`:
```
>           raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
E           tests.common.errors.RunAnsibleModuleFail: run module command failed, Ansible Results =>
E           rc = 101
E           cmd = ['warm-reboot']
E           start = 2025-02-28 21:50:57.537650
E           end = 2025-02-28 21:51:03.919474
E           delta = 0:00:06.381824
E           msg = non-zero return code
E           invocation = {'module_args': {'_raw_params': 'warm-reboot', '_uses_shell': False, 'warn': False, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'chdir': None, 'executable': None, 'creates': None, 'removes': None, 'stdin': None}}
E …
```

update timeout value and skip warm reboot on isolated topology for test_bgp_session.py

---

tests/bgp/test_bgp_router_id.py

Summary:
After restart BGP, low performance devices need more time to sync bgp_facts, hence add time wait after restarting bgp.
Add time wait after restarting bgp
Run test

[bgp] Add time wait for test_bgp_router_id

---

tests/route/test_duplicate_route.py

Summary:
Fixes test gap ADO 28839417
Existing test case support Vlan and loopback interfaces onT0 and M0 topologies only.
This PR extend the support to other topologies as long as they have Loopback interfaces or vlan IPs presented.
Added multi-asic support, and skip condition.
Verified on T1, T2, All passed.

[Test Gap] Support loopback duplicate route check case on non-T0 platform

---

tests/common/helpers/sonic_db.py
tests/iface_namingmode/test_iface_namingmode.py

Summary: 
Add support for multi-asic compatible for this tests. This PR requires https://github.com/sonic-net/sonic-utilities/pull/3781 to be merged as it's support `-n <namespace>`
Fixes # (issue) 28837145 
Utility improvement: https://github.com/sonic-net/sonic-utilities/pull/3781
Use namespace to get the information so that it's compatible with  multi-asic.
Enabled internal port when querying for port_alias_fact which was disabled before for compatibility
T2 testbed verified

add multidut support for enable_iface_naming_mode

---

tests/common/plugins/sanity_check/checks.py

Handle errored DUT shell result in sanity checks.
Summary:
Fixes # (issue) Microsoft ADO 31652009
There will be a chance that the DUT shell command returning error response. If we don't add `module_ignore_errors=True`, such error response could make a check exit early with exception, which leads to unexpected sanity check behavior. Hence, we want to handle the situation when there is an error with the shell command.
I ran a sanity check with a DUT shell command that returns an error response and can confirm the sanity check will not raise an exception anymore.

fix: handle sanity check error DUT shell result

---

tests/fib/test_fib.py

Fix test_vxlan_hash in fib/test_fib.py for dualtor active-active topologies
Summary: Fix test_vxlan_hash in fib/test_fib.py
Fixes [#476](https://github.com/aristanetworks/sonic-qual.msft/issues/476)
- [] 202411
This test fails on DualTor
The approach to fix this is to replace the `ptf_test_port_map` fixture with dualtor compatible fixture ` ptf_test_port_map_active_active`
Ran tests on Arista-7260CX3 in Dualtor Setup

[202411][sonic-mgmt]Fix test_vxlan_hash in fib/test_fib.py

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Summary: Skip `link_down_on_sup_reboot` on topologies that don't use modular switches
Fixes # [464](https://github.com/aristanetworks/sonic-qual.msft/issues/464)
test_linkdown_on_sup_reboot() testcase should be  skipped for non-T2 topologies 
All testcases in this module were recently enabled for non-T2 topologies in https://github.com/sonic-net/sonic-mgmt/pull/13582
platform_tests/test_link_down.py::test_link_down_on_sup_reboot is still meant to be run on a modular chassis which reboots supervisor and then checks the port status on all linecards. However this ends up running on all multidut topologies due to this
check: https://github.com/sonic-net/sonic-mgmt/blob/202411/tests/platform_tests/test_link_down.py#L152-L153 which includes dualTor where every duthost is a standalone device as …

Skip linkdown_on_sup_reboot on topologies that don't use modular switches

---

tests/bmp/helper.py
tests/bmp/test_bmp_statedb.py
tests/bmp/test_docker_restart.py

Summary: Fix BMP tests
Fixes [#459](https://github.com/aristanetworks/sonic-qual.msft/issues/459])
`bmp/test_bmp_statedb.py` and `bmp/test_docker_restart.py` are failing as they try to test BMP without enabling it.
Created a fixture to enable BMP. For the CLI to work we also need: https://github.com/sonic-net/sonic-buildimage/pull/21863
Ran all tests in the BMP directory.

Fix BMP tests

---

tests/route/test_route_consistency.py

This is a cherry-picked PR with resolved auto merge conflict issue to merge test_route_consistency changes already delivered to master and 202405, and now targeting 202411 branch.
Summary:
add upstream linecard check for chassis_packet, T2 Cisco device in get_route_prefix_snapshot_from_asicdb
This was to use correct num_routes_withdrawn during asserts, where we only had upstream support for 'voq' and failed for 'chassis_packet'
------------------------------------------------------ generated xml file: /var/src/sonic-mgmt-int/tests/logs/route/test_route_consistency.xml ------------------------------------------------------
============================================================================= 3 passed, 1 warning in 1482.39s (0:24:42)

[manual] [PR:16089] Fix typo on route_consistency

---

tests/qos/test_tunnel_qos_remap.py

Summary:
Fixes an issue where sometimes the test framework would lockup due to trying to clear out packets from the PTF buffer, but failing to ever do so due to endless ICMP responder packets. 
The "clear out packets" operation is actually unnecessary due to the following loop iteration using a different DSCP, which will cause the extra packets from the prior loop to not match the next loop's packet verification mask. 
Fix a flaky issue. 
Verified 2 tests pass. 
Cisco-8000 test.

Fix PCBB watermark test flaky issue

---

tests/dualtor_io/test_tor_bgp_failure.py

Summary:
Fixes #[445](https://github.com/aristanetworks/sonic-qual.msft/issues/445)
Improving regex match in [17173](https://github.com/sonic-net/sonic-mgmt/pull/17173) 
Some examples of the syslog entries encountered when running dualtor_io/test_tor_bgp_failure.py - 
ERR bgp#mgmtd[34]: [X3G8F-PM93W] BE-adapter: mgmt_msg_read: got EOF/disconnect
ERR bgp#mgmtd[38]: [X3G8F-PM93W] BE-adapter: mgmt_msg_read: got EOF/disconnect
ERR bgp#mgmtd[32]: [X3G8F-PM93W] BE-adapter: mgmt_msg_read: got EOF/disconnect
Changed regex to match any decimal digits instead of just 33
Ran dualtor_io/test_tor_bgp_failure.py on DCS-7260CX3 and DCS-7050CX3

Fix for dualtor_io/test_tor_bgp_failure.py on dt/dt120

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
This PR is to cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/17406 to `202405` branch.
This PR is to skip `test_incremental_qos.py` on Mellanox dualtor testbed.
It's not skipped now because there is a longer match in the condition list. Actually it's not needed as there is only 1 test case in test module `test_incremental_qos.py`.
```
generic_config_updater/test_incremental_qos.py::test_incremental_qos_config_updates:
skip:
reason: "This test is not run on this hwsku/asic type or version or topology currently"
conditions_logical_operator: "OR"
conditions:
- "not any(i in hwsku for i in ['2700', 'Arista-7170-64C', 'montara', 'newport']) and asic_type in ['broadcom', 'cisco-8000'] and release in ['202211']"
- "'t2' in topo_name"
```
This PR is to skip …

[202405] Skip test_incremental_qos on Mellanox dualtor

---

tests/container_checker/test_container_checker.py

Summary:
This PR is to skip the test on `radv` container on `dualtor-aa` platform in `test_container_checker`.
It's because container `radv` is killed forcefully on `dualtor-aa` platform.
Related PR https://github.com/sonic-net/sonic-buildimage/pull/13408
This PR is to skip the test on `radv` container on `dualtor-aa` platform in `test_container_checker`.
Add `radv` container into the skip list if topo is `dualtor-aa`.
Verified on a physical dualtor testbed.
Dualtor-aa platform.

Skip radv container in test_container_checker on dualtor-aa

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

When a vlan member is removed, we get an error message in syslog like below
ERR swss#orchagent: :- update: Failed to get port by bridge port ID 0x3a000000000583
This message is already added to loganalyzer_common_ignore.txt as seen below because it does not have a functionality impact.
https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt#L210
The message that we are seeing in the latest Image is a bit different than the message that is being ignored.
This PR modifies loganalyzer_common_ignore.txt so that both old and new messages get ignored.
Modified the message in loganalyzer_common_ignore.txt file
old:
r, ". *ERR swss#orchagent: :- update: FdbOrch MOVE …

modifying Ignore message for 'Failed to get port by bridge port ID'

---

tests/show_techsupport/test_auto_techsupport.py

**Summary:**
In test_auto_techsupport.py script, there is a function named get_expected_oldest_timestamp_datetime whcih finds the oldest timestamp that should be present in the generated techsupport. This function is called before checking if the expected show-techsupport process is present. If there are lot of syslog files on DUT, this method was taking a long time and show-techsupport process was already ending before the script checks it. This was causing a failure like "AssertionError: Expected techsupport generation not started'"
This PR improves the method get_expected_oldest_timestamp_datetime to make it more efficient
Bug fix
202405
202411
202311
**Approach**
The method …

improve timing in test_auto_techsupport testcase

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
This PR is to skip `test_incremental_qos.py` on Mellanox dualtor testbed.
It's not skipped now because there is a longer match in the condition list. Actually it's not needed as there is only 1 test case in test module `test_incremental_qos.py`.
```
generic_config_updater/test_incremental_qos.py::test_incremental_qos_config_updates:
skip:
reason: "This test is not run on this hwsku/asic type or version or topology currently"
conditions_logical_operator: "OR"
conditions:
- "not any(i in hwsku for i in ['2700', 'Arista-7170-64C', 'montara', 'newport']) and asic_type in ['broadcom', 'cisco-8000'] and release in ['202211']"
- "'t2' in topo_name"
```
This PR is to skip `test_incremental_qos.py` on Mellanox dualtor testbed.
Update …

Skip test_incremental_qos on Mellanox dualtor

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

[202411 conflict handle]
Due to hardware limitation, when ecmp and lag hash at the same time, it would not support setting ecmp hash as CRC_CCITT and lag hash as CRC on ingress port hash field The hash result at this scenario would be bad
Summary:
Due to hardware limitation, when ecmp and lag hash at the same time, it would not support setting ecmp hash as CRC_CCITT and lag hash as CRC on ingress port hash field The hash result at this scenario would be bad
Skip test_ecmp_and_lag_hash[CRC_CCITT-IN_PORT case

[Mellanox] Add community skip for ecmp and lag hash

---

tests/clock/conftest.py
tests/clock/test_clock.py

Summary:
After this PR, the test_clock.py was enabled [Enable skipped test due to extra param requirement by augusdn · Pull Request #17059 · sonic-net/sonic-mgmt](https://github.com/sonic-net/sonic-mgmt/pull/17059)
Before that, this case was skipped. And this case will always set timezone to Asia/Jerusalem before and after test case, which is definitely a problem.
```
@pytest.fixture(scope="function")
def init_timezone(duthosts):
"""
@summary: fixture to init timezone before and after each test
"""
logging.info(f'Set timezone to {ClockConsts.TEST_TIMEZONE} before test')
ClockUtils.run_cmd(duthosts, ClockConsts.CMD_CONFIG_CLOCK_TIMEZONE, ClockConsts.TEST_TIMEZONE)
yield
logging.info(f'Set timezone to {ClockConsts.TEST_TIMEZONE} after test')
ClockUtils.run_cmd(duthosts, …
```

Fix time zone changed issue after test_clock

---

ansible/library/interface_facts.py
tests/bgp/test_bgp_dual_asn.py
tests/bgp/test_bgp_speaker.py
tests/common/helpers/dut_ports.py
tests/route/test_static_route.py
tests/test_interfaces.py

backport #17153 into 202405.
These cases do not consider the secondary subnet scenario.
Add several common helper functions t get vlan interface information.
get_vlan_interfaces_dict
get_vlan_interface_list
get_vlan_interface_info
Run bgp/test_bgp_speaker.py and test_interfaces.py on single vlan testbed and secondary subnet enabled testbed.
Test evidence for test_interface.py on secondary subnet testbed:
python3 -m pytest test_interfaces.py --inventory ../ansible/bjw2,../ansible/veos --host-pattern bjw2-can-7260-11 --testbed testbed-bjw2-can-t1-7260-11 --testbed_file ../ansible/testbed.yaml --skip_sanity  --disable_loganalyzer  --log-file /data/logs/testbed-bjw2-can-t1-7260-11_test_interfaces.py_2025-02-24_0 …

[202405] Fix test case failures after secondary subnet enabled (#17153)

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Update the skip condition for test_vlan_subnet_decap(cherry-pick for PR https://github.com/sonic-net/sonic-mgmt/pull/15932 )
Summary:

Update the skip condition for test_vlan_subnet_decap(cherry-pick for PR 15932)

---

tests/common/plugins/memory_utilization/__init__.py
tests/dut_console/test_console_baud_rate.py

Summary:
30980898
The case would do the reboot and send "ctrl + C" to let the device run into ABoot.
Then do the reboot again in the teardown to recover the device.
However, the memory check teardown would be called before the case module teardown.
Skip the memory check for this case test_baud_rate_boot_connect
Local run the case, skipped the memory check for this case
And run the case 
https://elastictest.org/scheduler/testplan/67c966cfb038ae23fc82ca03

[test_baud_rate_boot_connect] skip memory utilization

---

ansible/vars/topo_t1-isolated-d224u8.yml

Topology t1-isolated-d224u8 is missing the tornum definitions for its T0 peers. This change adds those definitions, which are needed for BGP announce routes during topology deployment.
Summary:
Fix an issue that is encountered when deploying the t1-isolated-d224u8 topology.
Added the missing tornum definitions to the t1-isolated-d224u8 topology file.
Verfied the issue is no longer encountered during topology deployment.
Tested on Arista-7060X6-64PE-C224O8.

sonic-mgmt: add tornums for t1-isolated-d224u8

---

tests/common/platform/templates/expect_boot_messages

Summary:
On 202405 images and newer, primarily because of the upgrade to Debian Bookworm, the syslog regexes to search for have changed. Because of this, timing information cannot be correctly calculated.
Update these regexes to make it work for 202405 images. They should still work for upgrades to older images.
Verified that on an upgrade path test, timing information is more fully populated:
```
"time_span": {
"radv": "96.507709",
"bgp": "81.059592",
"syncd": "65.405027",
"swss": "",
"teamd": "78.26226",
"database": "",
"syncd_create_switch": "8.901015",
"sai_create_switch": "0.003605",
"apply_view": "10.918213",
"init_view": "11.141743",
"neighbor_entry": "0.988314",
"port_init": "0.849263",
"port_ready": "",
"finalizer": "0.0",
"lag_ready": "0.005578", …
```

Update regexes used for calculating timings when upgrading to 202405

---

tests/tacacs/test_accounting.py
tests/tacacs/test_authorization.py
tests/tacacs/utils.py

Check TACACS login performance by check how many commands run during login.
When TACACS enabled, If some hardware SKU run too many commands during user login, it will cause login performance issue. Add new test case to check and prevent this happen.
- Microsoft ADO: 25504697
Check how many commands run during user login.
Add new test case.
will updated with this PR image later.
- [] SONiC.master-16482.360728-2c8b4066f
Check TACACS login performance by check how many commands run during login.

Check TACACS login performance by check how many commands run during login.

---

tests/arp/test_arp_update.py
tests/common/fixtures/ptfhost_utils.py

The ip used in the test case is hard coded with the base ip + 2, in some topo, the ip is not added to the arp responder, then the test could fail. update it to use dynamic offset which could make sure the target ip in in the arp responder.
Summary:

Update the arp update test failure

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/qos/qos_sai_base.py

Summary:
After https://github.com/sonic-net/sonic-utilities/pull/3792, we need to disable pfcwd on backplane ports. 
PFCWD needs to be disabled on backplane ports when running qos_sai testing
added module level fixture to disable pfcwd
TBD

disable pfcwd before running qos_sai testing.

---

tests/common/fixtures/fib_utils.py

Replace duthost.fetch to duthost.fetch_no_slurp, as normal fetch causes delays in the test
Summary:
Fixes #31598080 fib/test_fib.py spend long time
duthost.fetch can cause significant delays in the test and this PR replaces it with duthost.fetch_no_slurp, where we observe dramatic save in time during the test.
Before the change, it caused 10 mins per fetch per ASIC in Cisco T2 chassis, where as the fix reduced this time down to ~3seconds per fetch per ASIC. Since we have 3 ASICs per LC and 3 LCs in DUT, this fix will theoretically save 5373s/89.55mins per test, which is 99.5% reduction in fetch time.
duthost.fetch causing significant delay in test, even test failure due to timeout in T2 Chassis.
Replace duthost.fetch with duthost.fetch_no_slurp, introduced in other PR to resolve similar …

Fix duthost.fetch causing delays in the test_fib

---

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Skip test_check_sfp_eeprom_with_option_dom on spc3 and later because the device doesn't support the command like 'mlxlink -d /dev/mst/mt53104_pci_cr0 -p 1 -m' on mellanox spc3 and later when software control is enabled 
Summary:
Skip test_check_sfp_eeprom_with_option_dom on spc3 and later for mellanox device
Add skip condition
Run test_check_sfp_eeprom_with_option_dom on spc3 and later
spc3 and later

[Mellanox] Skip test_check_sfp_eeprom_with_option_dom on spc3 and later

---

tests/lldp/test_lldp_syncd.py

Summary:
In lldp/test_lldp_syncd.py::test_lldp_entry_after syncd_orchagent testcase, after the swss is restarted, The lldp entries take longer time to be populated again. 
So added wait 60 to allow more time for it to populate.
Add wait to allow more time for lldp to populate
Added wait time after swss restart and critical process check to allow lldp entries to be populated again
Run test_lldp_syncd.py::test_lldp_entry_after_syncd_orchagent on Nokia-armhf platform

[lldp_syncd]Added wait after swss restart/critical process check to allow lldp entries to be repopulated

---

tests/everflow/test_everflow_ipv6.py
tests/everflow/test_everflow_testbed.py

Summary: [dualtor] Fix neighbor address slection logic for everflow tests
Fixes # https://github.com/aristanetworks/sonic-qual.msft/issues/463
Everflow tests `test_everflow_ipv6.py` and `test_everflow_testbed.py::test_everflow_frwd_with_bkg_trf` are starting background traffic before verifying actual test traffic. Background traffic verification is failing in dualtor if rand selected dut (`everflow_dut`) is lower ToR (i.e second dut). Reason being `neigh_ipv[4|6]` collection is relying on `ptfadapter.mg_facts['minigraph_bgp']` which is having neighbours (T1) addresses corresponding to upper ToR only. Thus background traffic send to lower ToR with destination address corresponding to upper ToR's neighbor address will not reach any server ports and thus causing test failures with symptom …

[sonic-mgmt][dualtor] Fix neighbor address slection logic for everflow tests

---

tests/bmp/test_bmp_statedb.py

Summary:
Extend bmp test case timeout, which will contain the time that bmp table is enable, and bgpd will send bgp updates to bmpd daemon, then bmpd daemon will populate BMP_STATE_DB, finally read from BMP_STATE_DB, previously the entire flow timeout is set as 360s which gets failed from time to time, now extend it into 6 minutes, once it get the entities it will return immediately instead of waiting for that long time.
Microsoft ADO (number only):31380216
BMP state db retrieve case only uses 36s as timeout which is not enough for some slow devices.
Extend the timeout value.
N/A
N/A

Extend bmp table entries retry timeout into 360s

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

The error 
```
File "/var/src/sonic-mgmt/tests/common/plugins/conditional_mark/__init__.py", line 549, in evaluate_condition
condition_result = bool(eval(condition_str, basic_facts))
File "<string>", line 1
topo_name not in ['t0', 't0-64', 't0-116', 't0-118', 't0-35', 't0-56', 't0-standalone-32', 't0-standalone-64', 't0-standalone-128', 't0-standalone-256', 'dualtor-56', 'dualtor-120', 'dualtor', 't0-80', 't0-backend', 't1-lag', 't1-28-lag', t1-64-lag', 't1-56-lag', 't1-backend', 't2', 't2_2lc_36p-masic', 't2_2lc_min_ports-masic'] and asic_type not in ['mellanox']
```
is caused by the lack of `'`. In this PR, we fix this issue. 
Summary:
The error 
```
File …
```

[bugfix] Fix syntax error in conditional evaluation due to missing quotation mark

---

tests/dualtor_io/conftest.py
tests/dualtor_io/test_normal_op.py

Summary:
dualtor_io testcases always skip loganalyzer on those testcases with reboot/reload.
better to collect syslog, but no analyze; this is to help debug.
Add fixture `setup_loganalyzer` to enable collect only.
```
dualtor_io/test_normal_op.py::test_upper_tor_config_reload_upstream[active-active] PASSED                                                                                                                                                                              [100%]
========================================================================================================== 1 passed, 1 deselected, 2 warnings in 568.14s (0:09:28) =================================================================================== …
```

[dualtor_io] Collect syslogs for failure ToR

---

tests/qos/test_buffer.py

For x86_64-nvidia_sn4280-r0, because some ports are NPU DPU ports that do not have lossless traffic, so remove the ports from tested ports
Summary:
Fix qos buffer test issue for x86_64-nvidia_sn4280-r0
Remove NPU DPU ports from the tested ports
run test buffer tests on x86_64-nvidia_sn4280-r0
x86_64-nvidia_sn4280-r0

[202411] Fix dynamic buffer issue for x86_64-nvidia_sn4280-r0 platform

---

tests/common/platform/transceiver_utils.py
tests/platform_tests/api/test_sfp.py
tests/platform_tests/conftest.py
tests/platform_tests/sfp/test_sfputil.py
tests/platform_tests/sfp/util.py

Update spf platform test related to error status, due to PR: https://github.com/sonic-net/sonic-buildimage/pull/20964
When software control is enabled, the port error status is as follows:
1. For active module, the expected state is OK
2. For cmis passive module, when cmis ver is 3.0, the expected state is ModuleLowPwr, else it is OK
3. For non cmis passive module, the expected state is 'Not supported'
When software control is disabled, the port error status keeps the original behaviour
Summary:
Update spf test related to error status when sw control is enabled
When sw control is enabled, check the error stats as the following logic:
1. For active module, the expected state is OK
2. For cmis passive module, the expected state is ModuleLowPwr
3. For non cmis passive module, …

[Mellanox] Update spf test related to error status when sw control is enabled

---

tests/qos/qos_sai_base.py

Summary:
After sonic-net/sonic-utilities#3792, we need to disable pfcwd on backplane ports.
(cherry picked from commit 69034abd8b261edf18ba4362b03c55c3e066b1b6)
Summary:
PFCWD needs to be disabled on backplane ports when running qos_sai testing
added module level fixture to disable pfcwd

[202411] disable pfcwd before running qos_sai testing. (#17393)

---

ansible/vars/topo_t0-isolated-d2u254.yml
ansible/vars/topo_t0-isolated-d2u254s1.yml
ansible/vars/topo_t0-isolated-d2u254s2.yml
ansible/vars/topo_t0-isolated-d2u510.yml
ansible/vars/topo_t1-isolated-d254u2.yml
ansible/vars/topo_t1-isolated-d254u2s1.yml
ansible/vars/topo_t1-isolated-d254u2s2.yml
ansible/vars/topo_t1-isolated-d510u2.yml

Summary:
To setup bgp routes with correct count, we need to adjust podset parameters in topology files.
And to generate routes on ceos ToR, we need to add tornum in topology files.
We need to setup bgp routes with correct count and generate routes on ceos ToR.
adjusted podset parameters in topology files and added tornum in topology files.
deploy topology in lab

[isolated topo] adjust podset parameters and add tornum

---

tests/test_pretest.py

Summary:
Patch PR https://github.com/sonic-net/sonic-buildimage/pull/21992 into 202405 dualtor nightly DUTs.
```
test_pretest.py::test_patch_dualtor_mux_simulator PASSED                                                                                                                                                                                                               [100%]
../../../../../../usr/local/lib/python3.8/dist-packages/param …
```

[pretest] Patch dualtor mux service to increase tunnel wait timeout

---

ansible/roles/test/files/ptftests/py3/wr_arp.py

Summary:
Fixes #17502
In KVM environments, it's possible that an ARP response that gets forwarded is less than 60 bytes, less than the minimum Ethernet frame size. In physical environments, it'll almost always be at least the minimum Ethernet frame size. In the lab, the `arp_responder.py` script adds a marker in the padding at the end of the ARP packet to indicate that it came from that script.
To gracefully handle all cases, generate the expected ARP response packet as a 42-byte packet, and ignore extra bytes.

Modify wr_arp PTF script to generate an ARP packet of only 42 bytes

---

tests/common/helpers/ntp_helper.py
tests/gnmi/helper.py
tests/mvrf/test_mgmtvrf.py
tests/ntp/test_ntp.py

Summary:
With the NTP daemon being changed from ntpd to chrony, commands that refer to the ntpd daemon need to be updated to point to chrony instead.
Update the gnoi and mvrf test cases to point to chrony-related commands instead of ntpd-related commands.
Tested on physical T0 and T2 testbed.

Update gnoi and mvrf test cases for chrony support

---

tests/platform_tests/api/conftest.py
tests/platform_tests/api/test_module.py

Increase timeout for module api test_reboot for t2, as 300 sec is not long enough
Also also provide a helpful fail message on teardown
Summary:
- [x ] Bug fix
- [ x] 202405
- [ x] 202411
Test is failing because it is not waiting long enough after reboot
ran on arista t2 chassis
t2

[platform/api/test_module]: Increase timeout for test_reboot for t2

---

ansible/roles/vm_set/tasks/get_dut_port.yml

Summary: After the https://github.com/sonic-net/sonic-mgmt/pull/16716 merged,  the remove topo failed. fix it in this PR
Deploy the setup could pass with the fix

Fix the issue introduced by the PR #16716

---

tests/ipfwd/test_dip_sip.py

Summary:
Following testcases added for IPv4 and IPv6 traffic
1. traffic test with different DIP and SIP for directly connected DIP
2. traffic test with different DIP and SIP for DIP reachable through configured static route.
Fixes # 17057
- [ x] Test case improvement
Additional coverage in forwarding test
Added extra cases to the existing script to handle the cases where traffic is sent to directly connected route as well as to a prefix that is reachable through a static route. 
Run on T1 topology running master: 
ipfwd/test_dip_sip.py::test_ipv4_forwarding[usschq-mswdut-t005-None-ipv4_same_sip_dip] PASSED                                                                 
ipfwd/test_dip_sip.py::test_ipv4_forwarding[usschq-mswdut-t005-None-ipv4_different_sip_dip_connectedroute] PASSED …

Add traffic tests for static and directly connected routes in IPFWD test suite

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

* Skip this test on broadcom platforms for 202411 due to a known issue.
Summary:

[202411] Skip test_neighbor_miss on broadcom platforms

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Fixes # (issue) Microsoft ADO 30579337
The GNOI KillProcess test was supposed to test whether GNOI can issue sigterm to a process, but since this is written to kill all sonic critical services and restarts, it ended up being very noisy with all issues on startup scripts. Disabling this test for now to rewrite and put the test in the scope of individual service instead of GNOI.
Disable the test kill_process_and_restart
on KVM

disable killprocess test to rewrite

---

tests/auditd/32-test.rules
tests/auditd/conftest.py
tests/auditd/test_auditd.py
tests/common/helpers/tacacs/tacacs_helper.py
tests/container_upgrade/container_upgrade_helper.py
tests/container_upgrade/parameters.json
tests/container_upgrade/testcases.json
tests/tacacs/conftest.py
tests/tacacs/test_accounting.py
tests/tacacs/test_authorization.py
tests/tacacs/test_jit_user.py
tests/tacacs/test_ro_disk.py
tests/tacacs/test_ro_user.py
tests/tacacs/test_rw_user.py

Summary: Add auditd test cases to qualify auditd and auditd_watchdog containers in container upgrade nightly test in KubeSonic
Microsoft ADO: 30451821, 30451826
Test the functionality of auditd feature on SONiC switch, auditd and auditd_watchdog containers, which are deployed or upgraded by a Kubernetes master outside SONiC. 
Utilize and run test plans 
https://elastictest.org/scheduler/testplan/67d86de4607a6896f60ddf7f
No
Any topo
auditd test plan: https://microsoft.sharepoint.com/:w:/r/teams/SONiC2/_layouts/15/doc2.aspx?sourcedoc=%7B62B19989-2A2C-432C-A97A-5B96DF4BF02F%7D&file=[auditd_container_watchdog_testplan.docx](https://microsoft.sharepoint.com/:w:/r/teams/SONiC2/_layouts/15/doc2.aspx?sourcedoc=%7B62B19989-2A2C-432C-A97A-5B96DF4BF02F%7D&file=auditd_container_watchdo …

[KubeSonic] add auditd test cases

---

tests/common/dualtor/dual_tor_utils.py
tests/dualtor_mgmt/test_server_failure.py

Summary:
After server reboot (simulated by port down on both sides), the mux ports can reconcile to consistent && healthy, but without the gurantee which side is fixed to be active/standby.
Change the check condition to validate both sides are consistent && healthy.
```
dualtor_mgmt/test_server_failure.py::test_server_reboot[active-standby] PASSED                                                                                                                                                                                         [ 50%]
dualtor_mgmt/test_server_failure.py::test_server_reboot[active-active] SKIPPED (Skip as no mux ports of 'active-active' cable type) …
```

[test_server_reboot] Fix the consistency check

---

tests/srv6/test_srv6_dataplane.py

New test case that verifies when a SRv6 packet does not hit any MY SID entry, it should be blackholed.

---

tests/common/fixtures/ptfhost_utils.py

Have fixture setup_vlan_arp_responder skip choosing secondary subnet IP as the base ip
Summary:
Fixes #17537
Fix https://github.com/sonic-net/sonic-mgmt/issues/17537
Have fixture setup_vlan_arp_responder select the primary VLAN ip as the base ip instead of the secondary subnet ip.
Tested on t0-118

Skip secondary subnet selection for base ip in setup_vlan_arp_responder fixture

---

ansible/roles/test/files/ptftests/py3/advanced-reboot.py
ansible/roles/test/files/ptftests/py3/wr_arp.py

Summary:
- `platform_tests.test_advanced_reboot` failed due to
`Exception: host number 127 is greater than number of hosts 126 in the network 192.168.0.0/25`
```
Vlan1000                  192.168.0.1/25       up/up         N/A             N/A
192.169.0.1/22                     N/A             N/A
Vlan2000                  192.168.0.129/25     up/up         N/A             N/A
```
prefix is 192.168.0.1/25 , i = 127
`addr = self.host_ip(prefix, i)`
```
def host_ip(self, net_ip, host_number):
src_addr, mask = net_ip.split('/')
n_hosts = 2**(32 - int(mask))
if host_number > (n_hosts - 2):
raise Exception("host number %d is greater than number of hosts %d in the network %s" % (
host_number, n_hosts - 2, net_ip))
```
`n_hosts = 2**(32 - int(25)) = 128`, so host_ip will throw …

Fix failures for test_wr_arp and test_advanced_reboot with secondary subnet enabled

---

tests/common/platform/transceiver_utils.py
tests/platform_tests/api/test_sfp.py
tests/platform_tests/conftest.py
tests/platform_tests/sfp/test_sfputil.py
tests/platform_tests/sfp/util.py

Update spf platform test related to error status, due to PR: https://github.com/sonic-net/sonic-buildimage/pull/20964
When software control is enabled, the port error status is as follows:
1. For active module, the expected state is OK
2. For cmis passive module, when cmis ver is 3.0, the expected state is ModuleLowPwr, else it is OK
3. For non cmis passive module, the expected state is 'Not supported'
When software control is disabled, the port error status keeps the original behaviour
Summary:
Update spf test related to error status when sw control is enabled
When sw control is enabled, check the error stats as the following logic:
1. For active module, the expected state is OK
2. For cmis passive module, the expected state is ModuleLowPwr
3. For non cmis passive module, …

[202405|Mellanox] Update spf test related to error status when sw control is enabled

---

tests/common/cache/facts_cache.py

Handle `UnpicklingError` edge case in `FactsCache::read()` when parallel run is enabled.
Summary:
Fixes # (issue) Microsoft ADO 31839137
When parallel run is enabled, multiple processes may try to read/write the same cache file, so there will be a chance that a file is being read by multiple processes at the same time, causing UnpicklingError in some of the processes. Therefore, we decided to retry to read the file after a short random sleep. If we still get the same error after retrying, we will return NOTEXIST to overwrite the file.

fix: handle UnpicklingError in cache read

---

tests/common/fixtures/fib_utils.py

This is a cherry-picked PR with resolved auto merge conflict issue to merge test_fib changes already delivered to master, targeting 202411 branch.
Summary:
Fixes #31598080 fib/test_fib.py spend long time
duthost.fetch can cause significant delays in the test and this PR replaces it with duthost.fetch_no_slurp, where we observe dramatic save in time during the test.
Before the change, it caused 10 mins per fetch per ASIC in Cisco T2 chassis, where as the fix reduced this time down to ~3seconds per fetch per ASIC. Since we have 3 ASICs per LC and 3 LCs in DUT, this fix will theoretically save 5373s/89.55mins per test, which is 99.5% reduction in fetch time.
Before:
22/02/2025 23:04:02 base._run L0071 DEBUG | /var/src/sonic-mgmt_xxx/tests/common/fixtures/fib_utils.py::get_t2_fib_info#66: …

[manual] [PR:17385] Fix duthost.fetch causing delays in the test_fib

---

tests/generic_config_updater/test_aaa.py

Adding test cases to test_aaa in the GCU directory to cover adding RADIUS config over GCU.  Currently there doesn't exist any test cases in this area.
Summary:
Fixes #16828
- [X ] New Test case
To add some test coverage for configuring RADIUS via the GCU configuration parameter
Following the same general format as the existing TACACS test cases.
Tested both on T0 and T1 topologies:
Any testbed

adding gcu radius tests

---

tests/platform_tests/test_platform_info.py

Summary:
In platform_tests/test_platform_info.py::test_turn_on_off_psu_and_check_status, the condition to verify psu_num variable as null is returning False and is not honored when psu_num value is 0. This is because in Python, both None (representing null) and 0 are considered "false" values. This means that when used in a boolean context, such as an if statement, they evaluate to False.
Fix healthy psu check condition before proceeding the test
Modified condition to verify psu_num value is not None
run platform_tests/test_platform_info.py::test_turn_on_off_psu_and_check_status on nokia-armhf platforms

Fix condition to check psu_num variable check for null in test_turn_on_off_psu_and_check_status

---

tests/bgp/bgp_helpers.py
tests/bgp/templates/bgp_summary_extended.textfsm
tests/bgp/templates/show_proc_extended.textfsm
tests/bgp/test_bgp_update_replication.py
tests/bgp/test_bgp_update_timer.py
tests/common/helpers/bgp.py

Summary:
Fixes #3612 
Focuses on addressing the BGP update replication testgap.
1. Sets up 16 connections (using the DUT's physical interfaces)
* Issue recommends using 33, but I found that 16 allows for a much greater proportion of testbeds to be able to run the test (as it is skipped on devices with not enough physical interfaces)
2. Uses connections to create BGP neighbours (1 for route injection, 15 for route receiving)
1. Three nested loops are run (totalling 90000 announcements and 90000 withdrawals):
a. Outer loop: Intervals (3 sec, 1 sec, 0.5 sec)
b. First inner loop: 20 iterations (instead of 1000 suggested in the testgap issue, primarily for performance reasons)
c. Second inner loops: 10000 route announcements + withdrawals (between each announcement loop, measurements are …

[BGP Testgap] Add BGP Update Replication

---

tests/conftest.py
tests/drop_packets/test_drop_counters.py
tests/pc/test_po_cleanup.py

Optimize the `temporarily_disable_route_check()` fixture to avoid having errors when running `route_check.py`
Summary:
Fixes # (issue) Microsoft ADO 31854875
When a test module is running with the `temporarily_disable_route_check()` fixture, it will sometimes get an error when running `route_check.py` at the teardown stage. Therefore, we converted the route check to a timeout function to make sure it can pass within a certain time period.
I ran the updated code and can make sure it's working well.
- T1 regression test: https://elastictest.org/scheduler/testplan/67da156532d9ac47c1a58764
- T2 test: https://elastictest.org/scheduler/testplan/67da0f7f32d9ac47c1a5875a

refactor: optimize route check disable fixture

---

tests/dualtor/test_orch_stress.py
tests/dualtor/test_standby_tor_upstream_mux_toggle.py

Summary:
Testbed will get crm resources from asic, but it's not completely supported on KVM testbed.
Skip all crm facts check using `compare_crm_facts`

[dualtor] Skip crm compare check on KVM testbed

---

ansible/library/generate_golden_config_db.py

Summary:
manual cherrypick for PR:17024
Enable multiasic support in mgmt by ovewriting golden config. And refactor existing code to generalize the feature overwrite functions, so that other feature is able to turn-on easily with it.
Enable multiasic support in mgmt by ovewriting golden config. And refactor existing code to generalize the feature overwrite functions, so that other feature is able to turn-on easily with it.
FEATURE needs special handling since it does not support incremental update, which means the config passed in this library function will be below cases:
For multi-asic:
1. config without FEATURE, this needs load runningconfig to get all asics' FEATURE, and append BMP set, overwrite entire golden config.
2. config with other entities, but without FEATURE. This also needs …

enable multiasic support for bmp feature

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Update generic hash skip condition for INNER_IP_PROTOCOL due to HW limitation
Summary:
Update generic hash skip condition for INNER_IP_PROTOCOL due to Mellanox HW limitation
Skip all the hash field INNER_IP_PROTOCOL related cases
Mellanox platform

Update generic hash skip condition for INNER_IP_PROTOCOL due to HW limitation

---

tests/bmp/helper.py
tests/bmp/test_bmp_statedb.py
tests/bmp/test_docker_restart.py

Reverts sonic-net/sonic-mgmt#17179
BMP will be enabled by default by deploy-mg for all the tests due to this change: https://github.com/sonic-net/sonic-mgmt/pull/16081.
Therefore https://github.com/sonic-net/sonic-mgmt/pull/17179 is no longer needed.

Revert "Fix BMP tests"

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
macsec/test_interop_protocol.py::TestInteropProtocol::test_port_channel test will cause vsonic neighbor lost route to dut, which caused following test_snmp has high failure rate in PR testing, need to skip test_port_channel test with issue to unblock community
Skip test_port_channel test with issue https://github.com/sonic-net/sonic-mgmt/issues/17519

[macsec] Temporarily skip macsec TestInteropProtocol::test_port_channel test since it will cause vsonic neighbor lost route to dut

---

tests/run_tests.sh

Summary:
There is a typo introduced in https://github.com/sonic-net/sonic-mgmt/commit/53d61b7eea2f8198d6201e4e53943ead8d9d3f43
fix the typo
run on vs.

Fix a typo in run_tests.sh

---

ansible/roles/vm_set/tasks/get_dut_port.yml

Reverts sonic-net/sonic-mgmt#17516
Originally #17516 was intended to fix an issue introduced in #16716. However, it turns out that it does not work.
We have to revert #16716. Before reverting 16716, #17516 must be reverted first. Otherwise, there will be conflicts.

Revert "Fix the issue introduced by the PR #16716"

---

tests/platform_tests/test_process_reboot_cause.py

Summary:
`test_process_reboot_cause` was added in [Added sonic-mgmt tests for process-reboot-cause script by assrinivasan · Pull Request #14615 · sonic-net/sonic-mgmt](https://github.com/sonic-net/sonic-mgmt/pull/14615)
In test_empty_json_file, it will try to create an empty json file and test the process reboot cause.
`touch /host/reboot-cause/history/reboot-cause-2025_03_06_11_19_33.json`
But it will have an error syslog after test:
```
E               2025 Mar  6 11:19:35.170923 bjw-can-7260-8 ERR process-reboot-cause[266617]: Unable to process reload cause file /host/reboot-cause/history/reboot-cause-2025_03_06_11_19_33.json: Expecting value: line 2 column 1 (char 1)
```
Add the expected invalid syslog into ignore list before running …

Ignore expected invalid syslog in test_process_reboot_cause

---

tests/pfcwd/test_pfcwd_cli.py

Summary: Fix flakiness in pfcwd/test_pfcwd_cli.py
Fixes [#383](https://github.com/aristanetworks/sonic-qual.msft/issues/383)
Sometimes the test ends up picking an egress interface which happens to be a member of a LAG. If the LAG has multiple members and only one of them is stormed the drop/forwards expectations don't take into account lag hashing.
Some of the traffic is hashed to another LAG member which is not being stormed and no drops will occur. 
The proposed fix is to shutdown the remaining LAG members.
Tested on Arista-7260CX3 with dualtor-120 topology and 202411 image.

Fix flakiness in pfcwd/test_pfcwd_cli.py

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
bgp/test_bgp_bbr.py test is flaky in PR test, and sometimes retry couldn't pass, it may related to KVM performance issue.
Skip bgp/test_bgp_bbr.py test with issue https://github.com/sonic-net/sonic-mgmt/issues/17598 to unblock PR test, then investigate later.

Temporarily skip flaky test bgp/test_bgp_bbr.py in PR test

---

tests/qos/test_buffer.py

Remove admin down ports in BUFFER PG check logic.
After PR https://github.com/sonic-net/sonic-buildimage/pull/21874 merged, the admin down ports in table BUFFER_PG_TABLE only contain PG 0.
Summary:
Test update for design PR https://github.com/sonic-net/sonic-buildimage/pull/21874
Remove admin down ports in BUFFER PG check logic.

Remove admin down ports in BUFFER PG check logic

---

tests/hash/generic_hash_helper.py

Unify the ipv6 address to upper case in generic hash case
Summary:
Use upper case ipv6 address during add or remove ipv6 address, it would avoid config db recognizing lower case and upper case address as two different address. In this scenario, it may lead to intf creation or deletion issue.
Use upper case ipv6 address during add or remove ipv6 address
Run it in local testbed.

Unify the ipv6 address to upper case in generic hash case

---

tests/platform_tests/test_reload_config.py

Summary:
Test case platform_tests/test_reload_config.py::test_reload_configuration_checks fails on smartswitch dark mode because dhcp_relay and dhcp_server are disabled in dark mode.
The failure is in method check_docker_status(), it queries the dockers to check by command "docker ps -a" which includes the disabled dockers and then fails.
```
admin@mtvr-4280-03:~$ docker ps -a
CONTAINER ID   IMAGE                                COMMAND                  CREATED      STATUS                  PORTS     NAMES
f123d2f6a1b7   11e543c3bc4e                         "/usr/local/bin/supe…"   2 days ago   Up 22 minutes                     what-just-happened
e20f1d39f140   docker-snmp:latest                   "/usr/bin/docker-snm…"   2 days ago   Up 22 minutes                     snmp
3a350ce837d5 …
```

Do not check the docker which is disabled in config reload test

---

tests/common/plugins/loganalyzer/__init__.py
tests/common/plugins/loganalyzer/bug_handler_helper.py
tests/common/plugins/loganalyzer/loganalyzer.py

In this change it has following function:
1. Add ability to handle the err msg detected by loganalyzer
2. Do not run the loganalyzer in parallel if there is only 1 loganalyzer need to run
3. Increase the timeout from 120 to 240 for the parallel run of the loganalyzer since if lot of err msgs need to be handler, it will take more time to finish it.
4. When load the ignore regex list, also load the value of "extended_ignore_list" in the cache
Summary:

Add logic to handler err msg detected by loganalyzer

---

tests/upgrade_path/test_upgrade_path.py

Remove the 'multi_sad' from the upgrade sad test since it has duplicate with other sad types
since multi_sad == sad_bgp + sad_lag, no need to have the multi_sad type.  it will reduce the run type (3-4hrs)
Summary:
To reduce the run time of the test case
Run the test_warm_upgrade_sad_path, it could cover all kinds of the sad type after the change.

Remove the 'multi_sad' from the upgrade sad test since it has duplicate with other sad types

---

tests/bgp/conftest.py

Add config save and reload action to avoid ip address left in config db file
Although there is a ip address remove action in function _setup_interfaces_t1_or_t2
But it had not been saved to config db file
And due to it has external ip address cross test body, so there would be external acl rule installed for the ip address
This leftover could lead to generic config updater case failure
Summary:
Add config reload action to remove the external acl rule
Add config save and reload action to avoid ip address left in config db file

Add config save and reload action to avoid ip address left in config db file

---

tests/platform_tests/sfp/test_sfputil.py
tests/platform_tests/sfp/util.py
tests/show_techsupport/test_techsupport.py

Add test coverage for "Dump SFP EEPROM page data in show techsupport command", here is the HLD: https://github.com/sonic-net/SONiC/blob/master/doc/sfputil/dump_sfp_eeprom.md
Summary:
Run the relavent test case, and it pass.

Add test coverage for sfp eeprom dump

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
The pc/test_lag_member.py::test_lag_member_status test case can be run on KVM T0.
Allow this test case to run, to at least enable some coverage of the code in this file. Modify the conditional markings so that all test cases still get skipped on dualtor or backend T0, and only `lag_member_traffic` gets skipped on KVM.

Enable running pc/test_lag_member.py::test_lag_member_status on KVM T0

---

ansible/config_sonic_basedon_testbed.yml

Summary: Spawning a virtual T2 testbed in a server will create and run three KVM VMs which are consuming a lot of CPU resources. In this scenario, the time used by ntpsec.service in systemd to start/restart/stop may be longer than expected. So, we should add some additional timeout value for ntpsec.service to avoid the timeout issue.

Set the TimeoutSec of ntpsec to be 600

---

tests/acl/templates/acltb_test_rules.j2
tests/acl/templates/acltb_test_rules_part_1.j2
tests/acl/test_acl.py
tests/show_techsupport/test_techsupport.py
tests/ssh/test_ssh_stress.py

This is re-commit of following pull request, which was reverted back due to regression
https://github.com/sonic-net/sonic-mgmt/pull/11892
In Active-Active DUAL TOR setup, we have the following two important constraints to maintain link state of TORs:
1. gRPC communication between TORs and gRPC server (nic_simualtor).
2. Heartbeat between TORs and server (icmp_responder).
The issue with the failing testcases in test_acl.py is, it is fundamentally verifying the INGRESS ACL functionality and the ACLs being used in the testcase are not aware of the above 2 points. The moment we apply the INGRESS ACL, it starts blocking the above-mentioned control packets. This results in links in both TORs going in STANDBY mode, causing testcase failure.
As a fix, the proposal is to create a “pin hole” in the …

ACL testcases in A/A setup need additional rules to ALLOW the ICMP keepalives to ensure both TORs don't go in STANDBY mode

---

ansible/config_sonic_basedon_testbed.yml
ansible/library/generate_golden_config_db.py
ansible/library/get_macsec_profile.py
ansible/roles/eos/tasks/ceos_config.yml
ansible/templates/minigraph_link_meta.j2
ansible/templates/minigraph_meta.j2

This PR is separating the code changes made in PR : https://github.com/sonic-net/sonic-mgmt/pull/17087, to just take care of fixes to get the t2 toplogy deploy work with and without macsec_enabled.
Additional change is to support any cipher suite give in the arguments. In below eg: it uses MACSEC_PROFILE which is defined as **GCM-AES-XPN-256** here https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/macsec/profile.json#L69
```
./testbed-cli.sh -t testbed.yaml deploy-mg <testbed_name> <inventory_file> -e enable_macsec=True -e macsec_profile=MACSEC_PROFILE 
```
Summary:

Address fixes to make sure t2 topology deploy works with and without macsec enabled.

---

tests/common/gu_utils.py

Summary:
generic_config_updater/test_dynamic_acl.py::test_gcu_acl_scale_rules testcase fails for nokia-armhf platforms as it requires longer timer to scale acl rules due to the limited CPU computing power of ARM32 CPU. 
So , increased the GCUTIMEOUT value to wait for applying the patch to 1200 seconds.
Fixes failure of gcu test failure in nokia-armhf platforms
Fix failure of test_gcu_acl_scale_rules  test by increasing timeout for apply-patch for nokia-armhf platforms
Added platform specific check and modification of value for nokia-armhf platforms
Run generic_config_updater/test_dynamic_acl.py::test_gcu_acl_scale_rules on M0 topo on nokia-armhf platforms

Increase GCUTIMEOUT value for nokia-armhf platforms

---

tests/common/helpers/ntp_helper.py

Summary:
When using Chrony as the NTP daemon on the DUT, Chrony will not use NTP sources that have a root dispersion of more than 3 seconds (configurable via /etc/chrony/chrony.conf, but we currently don't touch that setting).
Block here until the root dispersion is less than 3 seconds so that we don't incorrectly fail the test.

Add check for max root dispersion on the PTF's NTP daemon

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary: Skip zmq/test_gnmi_zmq.py on all Arista platforms
Fixes [#462](https://github.com/aristanetworks/sonic-qual.msft/issues/462)
The test is written for smartswitch as it enabled this mode unconditionally: https://github.com/sonic-net/sonic-mgmt/blob/master/tests/zmq/test_gnmi_zmq.py#L54-L58
As of now none of the Arista platforms operate in this mode. 
Add a conditional mark to skip this on Arista platforms.
Ran this test on Arista-7260CX3
```
zmq/test_gnmi_zmq.py::test_gnmi_zmq SKIPPED (Test is for smartswitch)                                                            [100%]
```

Skip zmq/test_gnmi_zmq.py on all Arista platforms

---

tests/fdb/test_fdb_mac_learning.py

Summary: Fix flakiness of fdb/test_fdb_mac_learning.py
Fixes # https://github.com/aristanetworks/sonic-qual.msft/issues/487
Test is failing sometimes with error `Failed: After starting Ethernet0 and populating fdb, corresponding mac address entry not seen in mac table`
In case of dualtor active-standby, interface flap doesn't have any effect on mux status and thus there is no need to wait for mux status consistency. Updating the if condition to wait for mux consistency only for `dualtor-aa` which also allows delay (`time.sleep(30)`) needed to fix flakiness of this test for dualtor-120.
Stressed the test and no failures are seen with the fix.

[sonic-mgmt][dualtor-120] Fix flakiness of fdb/test_fdb_mac_learning.py

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Summary:
Skip this because it's not supported on the cisco platform

Skip test_ecmp_and_lag_hash testcase on cisco

---

tests/platform_tests/test_memory_exhaustion.py

Summary:
On some platforms we notice DUT not really reboot after OOM, but the test failure reason is some critical process unhealthy. To catch such issue, assert DUT reboot before starting critical process check.
On some platforms we notice DUT not really reboot after OOM, but the test failure reason is some critical process unhealthy.
Assert DUT reboot before starting critical process check.
Verified on Arista-720DT M0 testbed.

[OOM test] Assert DUT reboot before starting critical process check

---

tests/tacacs/test_authorization.py

Summary:
Recently an issue was found where the TACACs user was not able to execute the `show interfaces status` on a Nvidia smartswitch due to platform specific permission issue for a TACACS user. This test case update is to add this check for a TACACs user to execute the `show interfaces status` command so that this test case passes.
Failure of `show interfaces status` which was not caught by sonic-mgmt test.

[TACACS] Added additional show command check as tacacs user
