tests/vxlan/test_vxlan_bfd_tsa.py
This PR fixes test failures in `test_vxlan_bfd_tsa.py::Test_VxLAN_BFD_TSA`. These failures were observed on some platforms such as Mellanox msn4600c and Cisco 8102.
Summary:
Fixes #15728
Microsoft ADO ID: 31220198
PR for the master branch: #17511
The following two fixed were applied for `test_tsa_case4`, `test_tsa_case5`, and `test_tsa_case6`:
1. Replaced the manual execution of `sudo config reload -y` with a call to `config_reload` so that all interfaces and ports are up before configuring a VXLAN on the switch.
2. Added a check after configuring VNET routes to ensure that VNET routes are applied to the ASIC DB before running PTF tests.
`test_tsa_case4`, `test_tsa_case5`, and `test_tsa_case6` failed on some platforms such as Mellanox msn4600c and Cisco 8102.
By using `config_reload` …
=> [202405] Fixed two issues causing test failures in `test_vxlan_bfd_tsa.py`

ansible/roles/test/files/helpers/bfd_responder.py
fix bug https://github.com/sonic-net/sonic-mgmt/issues/17418
These 2 cases may cause BFD related mgmt test fails:
1, bfd responder can receive the packet it sent. and at the time of restart, partial packet could be process and cause it crash
2, In the case of bfd_responder restart and it get BFD UP packet, the packet become uninitialized, it cause socket sending packet error.
Summary:
https://github.com/sonic-net/sonic-mgmt/issues/17418
set a breakpoint in a sonic_mgmt test (test_bfd.py),  using a separately python script to craft and send BFD packet from the DUT to bfd_responder. it can trigger the second issue listed in the description section.
=> [sonic-mgmt][BFD][issues/17418]fix bfd responder crash

tests/bgp/test_bgp_suppress_fib.py
Summary:
During the test of test_bgp_suppress_fib, a configuration reload may be triggered, resulting in some expected error messages related to teamd and netlink access. These messages can be safely ignored.
During the test of test_bgp_suppress_fib, a configuration reload may be triggered, resulting in some expected error messages related to teamd and netlink access. These messages can be safely ignored.
Put teamd err msg into the ignore list. 
Run manual test.
=> [test_bgp_suppress_fib] Ignore err msg during reload

ansible/roles/test/files/ptftests/py3/hash_test.py
UDP sport 53 is a special port to be used in DNS and there is a rule in test server ovs switch 
It would forward packet with UDP sport 53 to VM instead of to PTF port due to an existing ovs rule:
`cookie=0x0, duration=8133.286s, table=0, n_packets=0, n_bytes=0, idle_age=8133, priority=8,udp,in_port=3,tp_src=53 actions=output:1`
Summary:
When UDP outer sport == 53, the packet would not be received at PTF ports in fib/test_fib.py::test_vxlan_hash test
When UDP outer sport == 53, the packet would not be received at PTF ports in fib/test_fib.py::test_vxlan_hash test
Exclude 53 from the port range
=> Update outer UDP sport range to exclude port 53

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Manually cherry-pick PR #16656 
Auto cherry-pick is not working PR #16922
=> [Cherry-pick #16656] Skipping dynamic_acl TC on Cisco Q200 platforms

tests/snappi_tests/ecn/files/helper.py, tests/snappi_tests/ecn/test_ecn_marking_with_snappi.py, tests/snappi_tests/files/helper.py
for cisco-8000 chassis in packet mode, add a test to verify ecn marking at congestion points based on traffic pattern 
Summary:
When multiple backplane traffic flows share the same slice of a asic on long-link card and use the default VOQ (as HBM-based long-link cards operate in default VOQ mode), the XOFF threshold gets breached.
This results in an XOFF signal being generated to the Fabric port, which leads to ECN marking at the Fabric port.
However, since no actual congestion is experienced on the egress port, it does not trigger ECN marking, leading to the test case failure.
- if ecn counter is not zero at egress port->success
- if ecn counter is zero:
- check the backplane ports on all FC - some of them should have non-zero ecn counters. pass the test else step 2
- …
=> [Cisco Specific] Fix to verify ecn marking when egress port is on long link (HBM) card

tests/common/fixtures/ptfhost_utils.py
Summary: Fix the issue introduced when handle the 2 PRs #16948 and #16970 (the test case failed on the dualtor when the 2 PRs merged.)
After the 2 PRs merged, since the conflict is not handled properly, it has problem when run on the dualtor setup:
for port in vlan_members:
ptf_index = dut_to_ptf_port_map[port]
if 'dualtor' in tbinfo['topo']['name']:
arp_responder_cfg['eth{}'.format(ptf_index)] = [
server_ip[port]['server_ipv4'].split('/')[0],
server_ip[port]['server_ipv6'].split('/')[0]
]
continue
ip_offset = ptf_index + 1  # Add one since PTF indices start at 0
arp_responder_cfg['eth{}'.format(ptf_index)] = [
str(ipv4_base.ip + ip_offset), str(ipv6_base.ip + ip_offset)
]
CFG_FILE = '/tmp/arp_responder_vlan.json'
with open(CFG_FILE, 'w') as file: …
=> Fix the issue introduced when handle the 2 PRs #16948 and #16970

tests/syslog/test_syslog_source_ip.py
Summary:
There could be a failure in the teardown of tests/syslog/test_syslog_source_ip.py.
The reason is in restore_config_by_config_reload, there is a step to remove the vrf configured in the test, which will cause ssh flap.
There is a wait_for for the ssh down, but the default connect_timeout for ssh connection in the the wait_for is 5s, meaning if in 5s the ssh connection is restored, it will not consider the connection as down.
The 5s is too long, the ssh could have already been restored from the flap caused by removing the vrf, shorten it to 1s.
And the same for the wait_for in configure_mgmt_vrf_test_data.
Fix for the syslog source ip test in the teardown of restore_config_by_config_reload.
Run the test, the failure didn't reproduce.
=> Fix for the syslog source ip test in the teardown of restore_config_by_config_reload.

tests/hash/generic_hash_helper.py
Handle non portchannel in the upstream ports for generic hash test script at topology t1-isolated-d28u1 and t0-isolated-d16u16s1
Summary:
No portchannels in topology t1-isolated-d28u1 and t0-isolated-d16u16s1, and generic hash test would be failed in this scenario.
Handle non portchannel in the upstream ports
Run in it local testbed
=> Update generic hash test to be supported on t1-isolated-d28u1 and t0-isolated-d16u16s1

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
test_gnoi_killprocess_*then*_restart is skipped. This one should be skipped for the same reason.
Summary:
- [x ] 202411
Turns out killprocess_then_restart and killprocess_restart both exists and should be skipped. Only the former one is skipped though.
on KVM.
=> Also skip test_gnoi_killprocess_restart

ansible/config_sonic_basedon_testbed.yml, tests/test_pretest.py
Summary:
Fixes #17246
Make sure tsa_enabled = false when startup_tsa_tsb is disabled through pretest
Add config save after TSB is executed
Output `tsa_enabled` before and after pretest to make sure it is working is intended
N/A
N/A
=> Ensure TSB is saved in config after deploy-mg and during pretest

tests/generic_config_updater/test_cacl.py
Summary: Modify config_reload as fixture and execute only once to save time
Fixes # (issue) ADO: 31983138
One time env setup is enough. Save running time
Change to fixture
E2E
=> [GCU] Change to fixture to save test running time

ansible/library/conn_graph_facts.py, ansible/templates/minigraph_link_meta.j2
Summary: Add option to toggle on FEC for minigraph in ixia topo
Fixes # (issue) 31623287
When in ixia FEC enabled port doesn't work well in some breakout ports. We want an option to force turn off FEC.
To use it, modify the links file. For example suppose we have the original _links.csv:
```
StartDevice,StartPort,EndDevice,EndPort,BandWidth,VlanID,VlanMode,AutoNeg
str-msn2700-01,Ethernet0,str-7260-10,Ethernet1,40000,1681,Access,on
str-msn2700-01,Ethernet4,str-7260-10,Ethernet2,40000,1682,Access,on
str-msn2700-01,Ethernet8,str-7260-10,Ethernet3,40000,1683,Access,on
str-msn2700-01,Ethernet12,str-7260-10,Ethernet4,40000,1684,Access,on
str-msn2700-01,Ethernet16,str-7260-10,Ethernet5,40000,1685,Access,on
str-msn2700-01,Ethernet20,str-7260-10,Ethernet6,40000,1686,Access,on …
```
=> feat: add option to toggle on FEC in minigraph

tests/clock/test_clock.py
Summary:
During test_clock testcase, the date will be set randomly.
When the TC finishes, the date will be set back by using "ntpdate a.b.c.d".
However, there is a bug ntpdate cannot handle if date difference is too big. The error is:
```
root@bjw-can-2700-2:~# ntpdate 10.150.22.222
File "/usr/bin/ntpdig", line 418, in <module>
returned += queryhost(server=server,
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/ntpdig", line 94, in queryhost
packet = request.flatten()
^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/ntp/packet.py", line 447, in flatten
body = struct.pack(SyncPacket.format,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: int too large to convert
```
See test_clock cannot change date back.
Change the date only after 1 day on based current date. …
=> Fix a bug that ntpdate cannot reset the date back in test_clock

tests/decap/test_subnet_decap.py
Summary:
For the IPinIP packets with dst IP in the VLAN subnet and src IP not in the configured decap term src subnet, they should be forwarded downstream to the server node. The testcase runs `arp_responder` to facilitate the neighbor setup, but some of those IPinIP packets might be dropped by the kernel in this ARP setup stage.
Send more packets.
Pass on dualtor.
=> [subnet decap] Send more packets for verification

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Ignore netlink socket readData error logs in syslog that are causing some tests to fail
This error message was ignored earlier, but only from swss. But the message is seen for teamd as well. Since there is no functional impact due to these logs, these are ignored.
More details abot the message are in https://github.com/sonic-net/sonic-swss/issues/353
The fix for swss was done under https://github.com/sonic-net/sonic-mgmt/pull/13639
But it was not done for teamd container.
=> Ignore netlink socket readData error=-33

tests/conftest.py, tests/performance_meter/config/sample_test_config, tests/performance_meter/config/sample_test_reboot_by_cmd, tests/performance_meter/conftest.py, tests/performance_meter/ops.py, tests/performance_meter/success_criteria.py, tests/performance_meter/test_performance.py
Add configuration of run count on different test case
Summary:
Originally run count of all performance meter test cases are the same and is input by command line argument from run_tests. It can be inconvenient sometimes
Add entry in config file and read it. The config file will be assessed in pytest_generate_tests
=> [performance_meter] allow specific run number for each test

tests/qos/test_tunnel_qos_remap.py, tests/qos/tunnel_qos_remap_base.py
Summary:
test_pfc_pause_extra_lossless_standby case failed, as below:
```
Failed: The queue 2 for port Ethernet60 counter increased unexpectedly:
Failed: The queue 6 for port Ethernet60 counter increased unexpectedly:
Failed: The queue 2 for port Ethernet172 counter increased unexpectedly: Received packet that we expected not to receive on device 0, port 71.
========== RECEIVED ==========
0000  42 6E C4 BB E2 A1 A4 3F 68 FA 7C 0C 08 00 45 09  Bn.....?h.|...E.
0010  00 6A 05 6A 00 00 FF 04 A1 DA 0A 01 00 21 0A 01  .j.j.........!..
0020  00 20 45 0D 00 56 00 01 00 00 3F 06 B8 E8 01 01  . E..V....?.....
0030  01 01 C0 A8 00 02 04 D2 00 50 00 00 00 00 00 00  .........P......
0040  00 00 50 02 20 00 94 88 00 00 74 65 73 74 73 2E  ..P. .....tests.
0050  71 6F 73 2E 74 65 73 74 …
```
=> disable checking queue counter in pfc_pause_test

.azure-pipelines/impacted_area_testing/calculate-instance-numbers.yml, .azure-pipelines/impacted_area_testing/calculate_instance_number.py
We occasionally encounter the error `test_plan.py create: error: argument --min-worker: invalid int value: '25+'` in the `Trigger Test` stage. 
It appears that the instance number is calculated correctly in the `Calculate instance number` step, suggesting that the issue likely occurs when transferring this variable within Azure Pipelines. We suspect that Azure Pipelines may misinterpret the value due to the presence of unexpected spaces or control characters.
```
echo "$INSTANCE_NUMBER"
echo -n "##vso[task.setvariable variable=INSTANCE_NUMBER]$INSTANCE_NUMBER"
```
So in this PR, we try to resolve the above issue by removing such character. 
Summary:
We occasionally encounter the error `test_plan.py create: error: argument --min-worker: invalid int value: '25+'` in the …
=> Remove unexpected spaces or control characters while passing `INSTANCE_NUMBER` to azure pipeline

tests/common/snappi_tests/snappi_fixtures.py
Summary:
Fixes # 17611
The recent addition for static route in snappi tests for cisco-8000 broke other platform runs. This PR attempts to fix the new function for the other platforms.
Converted the runtimeError to a warning, and return the same address.
Ran it with my TB, with both == cisco-8000, and != cisco-8000 checks.
and verified that the issue in the above git issue is not seen(global_pause is unsupported in cisco-8000):
```=========================================================================================================== PASSES ===========================================================================================================
___________________________________________________________________________________________ test_global_pause[multidut_port_info1] …
```
=> T2:Fixing the static-route function for other plats.

ansible/testbed_add_vm_topology.yml
Summary:
Fixes # (issue) Add option to specify ptf image, in case we need to support different image version per testbed
We run into this problem where a few testbed needs to change the versioning of ptf (ixia) image. This is not possible with the current add-topo when integrate with pipeline and need to do manually
By adding this option, we can specify the image version in the testbed.yaml file using `ptf_imagetag`. For example
For testbed that doesn't specify this option, we will fall back to the default that was set in add_topo.
```yml
- conf-name: vms-snappi-sonic-multidut
group-name: vms6-1
topo: ptf64
ptf_image_name: docker-ptf-snappi
ptf_imagetag: 10.25.2405.106 # Specify the image version here
ptf: snappi-sonic-ptf
ptf_ip: 10.251.0.232
ptf_ipv6:
server: Server_6
vm_base:
dut:
- …
```
=> chore: add option to specify image-tag for ptf/ixia image

tests/common/fixtures/ptfhost_utils.py
Check if attrs[val] is a dictionary before checking if vlan attribute is of a secondary subnet as not all attributes is a dictionary (ex: for dualtor).
Additionally, move ip_offset assignment to appropriate place to enable assignment.
Summary:
Fixture is failing for dualtor as not all vlan interface config attributes are a dictionary, so the `.get("secondary")` call will fial
Add a check to see if attribute item is a dictionary
=> Fix setup_vlan_arp_responder fixture secondary subnet skip

tests/platform_tests/link_flap/test_cont_link_flap.py
Revert #17103 
Summary:
Remove the extra sleep in `platform_tests/link_flap/test_cont_link_flap.py` added in #17103, as we have added the feature to wait until the `route_check.py` to succeed in both the setup and teardown of the `temporarily_disable_route_check()` fixture in #17550
=> revert: remove extra sleep of cont link flap test

tests/gnmi/test_gnmi_countersdb.py
Summary:
Fixes https://github.com/sonic-net/sonic-buildimage/issues/21961
Microsoft ADO: 31855770
test_gnmi_counterdb_streaming_sample_02() failed on some platforms.
Root cause: When we subscribe to the counters table or counters table + key, there are too many updates for the gNMI program to handle in time.
Now we only subscribe to counters table + key + field
=> Fix subscription streaming sample test for countersdb

tests/qos/qos_sai_base.py
Change `set_static_route` fixture and `set_static_route_ptf64` fixture in `qos/test_qos_sai.py` to class level. 
Summary:
The `qos/test_qos_sai.py` is taking too long on T2 devices, so we wanted to optimize the way `set_static_route` and `set_static_route_ptf64` instantiated to reduce the running time.
According to pytest official doc:
- There are only 3 ways that pytest handles the instantiation order of fixtures (doc [link](https://docs.pytest.org/en/stable/reference/fixtures.html#fixture-instantiation-order)): scope, dependencies & autouse 
- Higher-scoped fixtures are executed first (doc [link](https://docs.pytest.org/en/stable/reference/fixtures.html#higher-scoped-fixtures-are-executed-first))
- A fixture will only be invoked once per its scope …
=> refactor: change set_static_route fixture level

tests/common/config_reload.py, tests/common/reboot.py
Add option to skip iBGP check during health check after reboot and reload
Summary:
Sometimes we do not want to wait for iBGP to be up after reboot and reload as it's not related to our test and it's stopping us from utilizing the parallel run infrastructure. After adding this option, we can skip the iBGP check during health check after reboot and reload, so we can parallel run some test modules (e.g. `pc/test_po_cleanup.py`). After the test module is done, we can enable post-test sanity check to wait for all the BGP sessions (eBGP & iBGP) to be up before starting the next module.
I ran the updated code and can confirm it's working well.
=> feat: support skipping iBGP check in reboot/reload

tests/bgp/test_bgp_suppress_fib.py
Stabilize suppress fib vrf config reload test
The option "check_intf_up_ports" in common method config_reload could not work for the interfaces under user defined vrf Created a github issue to track the issue - https://github.com/sonic-net/sonic-mgmt/issues/17658 Then there added a new function to check the interface status
Summary:
The option "check_intf_up_ports" in common method config_reload could not work for the interfaces under user defined vrf 
1. Created a github issue to track the issue - https://github.com/sonic-net/sonic-mgmt/issues/17658
2. Added a new function to check the interface status for bgp suppress fib script
Run it at local setup
=> Stabilize suppress fib vrf config reload test

tests/bfd/test_bfd.py, tests/bgp/test_bgp_allow_list.py, tests/bgp/test_bgp_bbr.py, tests/bgp/test_bgp_dual_asn.py, tests/bgp/test_bgp_slb.py, tests/bgp/test_bgp_speaker.py, tests/bgp/test_bgp_update_timer.py, tests/bgp/test_bgpmon.py, tests/bgp/test_bgpmon_v6.py
Summary:
In pre-commit, we were using # noqa to ignore failures/errors/warnings in our code, but once we use # noqa, it will ignore all pre-commit errors in this line, the correct solution is using # noqa: so only specific failures/errors/warnings would be ignored.
Replace # noqa with # noqa: in tests/b*
=> [pre-commit] Use correct comment format # noqa: not # noqa in tests/b*

tests/qos/files/mellanox/qos_param_generator.py, tests/qos/files/mellanox/special_qos_config.yml, tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_base_test.py, tests/saitests/py3/sai_qos_tests.py
1. For spc4 and above, there is only the lossy buffer, so the buffer for the lossless buffer will be taken by the lossy buffer. If the packet size is too small, the packet number sent to occupy the shared buffer will increase a lot, which will lead to the descriptor being exhausted, so update testQosSaiPgSharedWatermark, testQosSaiQSharedWatermark, and testQosSaiLossyQueue accordingly.
2. Remove the test config of scheduler.block_data_plane, otherwise it might raise yang validation error when do config reload
3. When there is no lossless buffer, return a dump buffer lossless pg profile, and skip tests related to lossless buffer case dynamically
4.  Skip fixture reaseAllports for mellanox device, because after qos test is finished, the teardown will do config reload, it will restore the …
=>  Update qos sai due to no lossless pg for some platforms

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
=> Skip test_vnet_decap on Cisco-8000 with 202411

tests/generic_config_updater/test_incremental_qos.py
Summary:
Skip qos incremental test in case of no lossless buffer.
Skip the test to avoid 0m length cable and test failure in case of no lossless buffer.
Added a skip condition based on cable length.
Ran the test
5600/5610 only
=> Skip qos incremental test in case of no lossless buffer.

ansible/config_sonic_basedon_testbed.yml
Summary: Currently, we setup VS chassis by dynamically transform the HwSKU. If we use the old golden_config_db with single-ASIC hwsku to overwrite the config loaded from minigraph.xml, the HwSKU dynamically encoded in minigraph.xml will be overwritten by the HwSKU in golden_config_db. So, we need to flush the config db with minigraph before we generated the golden_config_db for VS chassis.
=> Preload minigraph to flush golden_config_db.json for vs chassis

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
- In multi asic linecards we have "macsec0", "macsec1" ... containers
- Without this fix, Log analyzer failed to ignore macsec messages on multi asic linecards.
Fixes : https://github.com/aristanetworks/sonic-qual.msft/issues/505
- With the fix, macsec tests are passing on multi asic linecards
=> Fixing loganalyzer for macsec

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/qos/qos_sai_base.py
Summary:
- Update test mark conditions to include dualtor-aa for every duplicate instance of the QOS SAI topo list (all lists are identical). Possible de-duplication here: #17707
- Only toggle simulator ports if active-standby. 
- Fix permissions on created empty write_standby file. 
Ran on dualtor AA cisco-8000, verified tests execute without major errors. Some tests fail due to some normal instability and known issues.
=> Dualtor AA enablement for QOS SAI

tests/platform_tests/daemon/test_sensord.py, tests/platform_tests/test_platform_info.py
Add a test to validate sensord is running if the sku supports it
Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/10505
- [x ] New Test case
Fill test gap by adding a test for sensord daemon
validate its running, and responds correctly when sent supported signals
Ran locally on t2 arista testbeds - passes
Nokia does not support sensord, so the test will be skipped in nokias cases.
=> [platform_tests/sensord]: add sensord platform daemon test

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
PR #16239 ignored an error message coming from ntpd (actually written by nss_tacplus). As that PR explains, this can happen when a `config reload` is run, and chrony calls `getpwnam` when `/etc/tacplus_nss.conf` is still being regenerated. However, it is not a failure.
With the change of NTP daemons, this loganalyzer ignore regex needs to be updated to match chrony.
=> Ignore nss_tacplus error message from chrony seen during config reloads

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Resolve backport conflict in https://github.com/sonic-net/sonic-mgmt/pull/16681
When restarting `swss` (and some other services) in `test_gnoi_killprocess.py`, there is a number of syslog errors (similar to how it is caused by config_reload). This is expected behavior.
This also occurs on other tests that runs `config_reload` or restarts `swss` (or other services). Therefore fix is put in `loganalyzer_common_ignore.txt` instead of being testcase specific.
Extending log_ignore to allow expected error logs.
Test no longer fails.
=> Add log ignore for 720DT (resolve backport conflict for 16681)

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Some experimental values from Broadcom SAI is causing error logs to be printed and catched by loganalyzer. These error logs are not actual errors and does not block anything, can be ignored.
Loganalyzer catching error logs that are not actual errors.
Ignore expected error logs.
`bgp.test_bgp_suppress_fib` no longer fails on T1 topos.
Broadcom only.
=> Ignore error logs from experimental SAI values

.azure-pipelines/collect_dump.py, tests/test_posttest.py
Summary:
posttest will collect techsupport and store in tests/logs, then elastictest will parse syslogs in dump file then upload both syslog and sonic dump file, but once posttest failed, then there will be no syslog and dumps.
1. Use a separate python script to collect dump and rename with testbed_name_with_idx, dut_name and timestamp, then parse syslog files
2. In dualtor, will collect on both duts
3. Use elastictest upload syslog and dump files
=> Add python script to collect dump on all duts

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
fast reboot is not supported on 202412 based hwsku
=> skip platform_tests/test_reboot.py::test_fast_reboot on 202412

ansible/veos
Summary:
Add the new topologies in #17642 and #17599 into the supported veos topologies list:
Add the topologies into the supported list.
run add-topo on a physical testbed.
=> update isolated 512 and v6 only topo in veos

tests/common/helpers/dut_ports.py, tests/vlan/test_secondary_subnet.py
Summary:
Address test gap https://github.com/sonic-net/sonic-mgmt/issues/17145.
Need to wait for https://github.com/sonic-net/sonic-mgmt/pull/17153/ being merged.
This PR introduces a test suite to verify secondary IP subnet management on VLAN interfaces. 
It includes:
- Functions to validate the presence or absence of secondary IP addresses via CLI (show ip interface) and Redis database.
- Tests to confirm correct addition, verification, and removal of secondary IP subnets on VLAN interfaces.
These tests ensure reliable secondary subnet configuration and cleanup on the DUT.
Add a new test script to cover the data consistency check for secondary subnet.
- Add a new function to get secondary ip in `dut_port.py`
- Functions to validate the presence or absence of secondary IP …
=> [test gap] Add test script to cover secondary subnet data consistency

ansible/roles/vm_set/tasks/add_topo.yml, ansible/roles/vm_set/tasks/renumber_topo.yml
Set the default value of PTF image tag (`ptf_imagetag`) to branch based tags published by the release branch builds. The branch based docker-ptf builds continue to be mixed (Python 2 + Python 3) images and the master branch builds will be migrated to Python 3 only image.
Summary:
Set the default value of PTF image tag (`ptf_imagetag`) to branch based tags published by the release branch builds. The branch based docker-ptf builds continue to be mixed (Python 2 + Python 3) images and the master branch builds will be migrated to Python 3 only image.
Change default value in add-topo and renumber-topo YAMLs.
Will be verified in this CI run
None
NA
NA
=> [202411] Modify ptf_imagetag default value to branch based tag value

tests/conftest.py
Optimize `core_dump_and_config_check()` by Python multithreading to reduce the running time.
Summary:
Fixes # (issue) Microsoft ADO 30849826
In `core_dump_and_config_check()`, we will run many commands on all the DUTs in sequence, which will take a long time to finish on multi-DUT devices, such as T2 devices. For a standard Nightly, we will basically run `core_dump_and_config_check()` for every non-skipped test module, which will accumulate to a very long time. Therefore, we wanted to reduce the running time by parallelizing the commands using Python multithreading.
I ran the updated code and can confirm it's working well. After the optimization, the running time of `core_dump_and_config_check()` has the following improvements:
- For dual ToR topo, the setup running time will be decreased …
=> refactor: optimize core dump and config checks

tests/common/plugins/loganalyzer/loganalyzer.py, tests/syslog/test_syslog_rate_limit.py
Summary: Fixed syslog rate-limit tests
Fixes # https://github.com/aristanetworks/sonic-qual.msft/issues/507
- The testcase (`"test_syslog_rate_limit.py"`) was flaky.
- Fixed flakiness in the test(`"test_syslog_rate_limit.py"`) by ensuring it includes the source application that triggered the test. Previously, valid rate-limit scenarios could add an extra log entry matching the search criteria, causing a count mismatch and test failure. Now, the test pattern explicitly includes the test application name.
- Refined error logs to provide more relevant context.
Ran `"tests/syslog/test_syslog_rate_limit.py"` repeatedly 20 times with dualtor topology on ARISTA switches, 
- 4/20 times it failed without the fix.
- It never failed with the fix.
Logs with fix:- …
=> Fixed syslog rate-limit tests

tests/common/snappi_tests/common_helpers.py, tests/snappi_tests/ecn/files/bpfabric_helper.py, tests/snappi_tests/ecn/files/ecnhelper.py, tests/snappi_tests/ecn/test_bp_fabric_ecn_marking_with_snappi.py, tests/snappi_tests/files/helper.py
Test Cases for ECN Marking Verification on Cisco-8000 (Packet Mode)
Fabric Card : Verify ECN marking on the egress interface under congestion.
Ingress Line Card: Verify ECN marking on the interface towards the fabric card under congestion.
Summary:
Added test case to verify the ecn marking on 
-- the Fabric egress interface 
-- the backplane egress interface of the LC
Verify ecn marking functionality of the fabric and back plane interfaces
Wrote snappi based test case 
Verified the test case on T2 ixia snappi test bed with sonic-mgmt
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================================================================================ PASSES …
```
=> Added testcase to verify ecn marking on the Fabric and Back plane interfaces in T2 [ Cisco specific]

tests/qos/qos_sai_base.py
Summary:
Fixes issue on some TBs where the "grep" script would incorrectly identify ports like "Ethernet24" as one of the members of a porthcannel where "Ethernet240" was a member. This causes DWRR tests to fail due to the incorrect port being slow-unblocked, as a result of no packets going through. 
Resolve by using minigraph facts instead of CLI commands. 
Issue reproduced on Cisco-8000 Dualtor platform during preliminary QOS SAI test case enablement. 
Validated fix works on:
- T0 Dualtor-AA passed both Dwrr and DwrrWeightChange (fixes regressions found )
- T1 64 LAG passed both Dwrr and DwrrWeightChange, produced the following line of relevant output:
```
tests.qos.qos_sai_base:qos_sai_base.py:2657 Interface Ethernet64 is a member of portchannel PortChannel108, setting interfaces list …
```
=> Fix DWRR scheduler LAG member search

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/db_migrator/test_migrate_dns.py
Summary:
Microsoft ADO: 31757149
There's a test gap, we don't have test to verify db_migrator
This test will modify CONFIG_DB and run db_migrator, and verify that DNS_NAMESERVER is from minigraph or golden config.
* test_migrate_dns_02: there's minigraph.xml and dns.j2, and there's no golden config. After migration, there's DNS_NAMESERVER in CONFIG_DB, because db_migrator can migrate from minigraph.
* test_migrate_dns_03 is used to reproduce SonicQosProfile issue: there's minigraph.xml and dns.j2, and I added SonicQosProfile in minigraph.xml, and there'no golden config. After migration, there's no DNS_NAMESERVER in CONFIG_DB, because db_migrator can't migrate from minigraph.
Run end to end test
=> Add test to verify db_migrator with DNS_NAMESERVER

tests/common/helpers/pfcwd_helper.py, tests/pfcwd/conftest.py
Summary: Fix pfcwd/test_pfcwd_function.py for dualtor topologies
Fixes: [#495](https://github.com/aristanetworks/sonic-qual.msft/issues/495)
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_actions is flaky and fails with the following signature.
```
FAIL: pfc_wd.PfcWdTest
File "ptftests/py3/pfc_wd.py", line 148, in runTest
return verify_packet_any_port(self, masked_exp_pkt, dst_port_list)
File "/root/env-python3/lib/python3.7/site-packages/ptf/testutils.py", line 3437, in verify_packet_any_port
% (result.port, device_number, ports, result.format())
AssertionError: Received expected packet on port 1 for …
```
=> Fix pfcwd/test_pfcwd_function.py for dualtor topologies

tests/common/fixtures/advanced_reboot.py, tests/common/helpers/dut_ports.py
Summary:
Address https://github.com/aristanetworks/sonic-qual.msft/issues/518
There are 2 Vlans on the t0-118 topology. We observe that the ptftest launched from upgrade_path tests will default to using the 192.169.0.0/22 IP for Vlan1000 and the test would fail with DUT is not ready due to packets sent by the PTF does not have any response from the DUT.
However, by switching to use 192.168.0.0/25 for Vlan2000, upgrade_path no longer fails on DUT is not ready and is able to pass normal warm upgrade.
Call the common help function `get_vlan_interface_list` and `get_vlan_interface_info` to get vlan interface and ipv4 address.
Run platform_tests.test_advanced_reboot on T0 testbeds.
T0 platforms
=> Choose correct vlan ip for 2vlan config in advance_reboot

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip generic_config_updater/test_dynamic_acl.py on x86_64-8101_32fh_o_c01-r0 platforms as its not supported.
make sure testcase is skipped
=> skip dynamic_acl on platform x86_64-8101_32fh_o_c01-r0

tests/common/fixtures/duthost_utils.py, tests/ip/test_mgmt_ipv6_only.py
Optimize the `ip/test_mgmt_ipv6_only.py` test module with Python multithreading.
Summary:
The `ip/test_mgmt_ipv6_only.py` takes a long time to finish on a multi-DUT device, for example, ~100 min on T2 device, so we wanted to optimize it with Python multithreading to reduce the running time.
I ran the updated code on a multi-DUT device and verified that the running time was reduced to ~50 min: Elastictest [link](https://elastictest.org/scheduler/testplan/67ee1c9aee36ddba96be573a?leftSideViewMode=detail&testcase=ip%2Ftest_mgmt_ipv6_only.py&type=console)
Besides, I also verified the change on T0 and dualtor:
- T0: https://elastictest.org/scheduler/testplan/67f05c6787ffab7db692a20b?testcase=ip%2Ftest_mgmt_ipv6_only.py&type=console&leftSideViewMode=detail …
=> refactor: optimize mgmt ipv6 only test

tests/common/helpers/inventory_utils.py, tests/conftest.py
Support trimming the inventory files such as `ansible/lab`, `ansible/t2_lab` etc when passing `--trim_inv` option.
Summary:
When we enable inventory trimming by passing the `--trim_inv` option, the current logic is to only trim the `ansible/veos` file, but we noticed that the other inventory file (such as `ansible/lab`) should also be trimmed because it contains the configs of all the devices in that lab, but we only need the configs related to the current test run. Therefore, we decided to support trimming these inventory files as well.
Please note that the PDU & Fanout hosts trimming is not supported in this PR as it's currently blocked by #17347 
I ran the new trimming logic on various lab files and can confirm it's working well:
- …
=> feat: support trimming lab inv file

tests/platform_tests/test_intf_fec.py
Summary: Add multi ASIC support for test-intf-fec. This is possible with the utility command update in https://github.com/sonic-net/sonic-utilities/pull/3819
Fixes # (issue) 28838870
Described
Update the command from https://github.com/sonic-net/sonic-utilities/pull/3819 and update the code base so that works with T2. For 202405
Please note that for a release branch to work internally, the following PR here needs to be included:
https://github.com/sonic-net/sonic-mgmt/pull/17183 
https://github.com/sonic-net/sonic-mgmt/pull/14661
https://github.com/sonic-net/sonic-mgmt/pull/16424 
https://github.com/sonic-net/sonic-mgmt/pull/15481 
T2 platform verified
=> Add multi-asic support for test-intf-fec

tests/hash/test_generic_hash.py
tests/hash/test_generic_hash.py test_reboot does not config save when the warm reboot is selected.
Test tries to configure the global hash configuration, and does warm reboot. In warm reboot all the containers are restarted, which looses the configuration that is not saved.
Summary:
Added warm boot aslo part of config save check.
Ran Sonic-mgmt with the fix 
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
------------------------------------ generated xml file: /data/tests/logs/tr_2025-04-03-19-04-31.xml ------------------------------------
=============================================== 1 passed, 1 warning in 847.24s (0:14:07) ================================================
DEBUG:tests.conftest:[log_custom_msg] item: <Function …
=> tests/hash/test_generic_hash.py test_reboot  warm boot to config save before reboot

ansible/module_utils/port_utils.py
Summary:
Add port alias-to-name mapping for Arista-7050CX3-32S-S128
Add port alias-to-name mapping for Arista-7050CX3-32S-S128
Update port_utils.py.
Verified by deploy testbed.
=> [port_util] Add port alias-to-name mapping for Arista-7050CX3-32S-S128

tests/common/helpers/dut_utils.py, tests/conftest.py
Add a fixture to enable NAT for  the dpus on smartswitch so we can call dpuhosts or dpuhost directly.
Regarding dpuhosts or dpuhost, please see PR:https://github.com/sonic-net/sonic-mgmt/pull/15695
Summary:
enable nat for dpus on smartswitch
Add a fixture to enable nat for dpus
Run test cases with duphosts
smartswitch
=> Add a fixture to enable nat for dpus

tests/decap/test_subnet_decap.py
Summary: Solve IndexError: list index out of range in dut_port = list(mg_facts['minigraph_portchannels'].keys())[0] when minigraph_portchannels is empty.
Solve IndexError: list index out of range in dut_port = list(mg_facts['minigraph_portchannels'].keys())[0] because minigraph_portchannels is empty.
This checks if any portchannels exist before attempting to access them, preventing the IndexError.
```
========================================================================================================================================================================================= short test summary info ========================================================================================================================================================================= …
```
=> Ignore subnet decap test when no portchannels found

tests/fdb/test_fdb_mac_learning.py
Summary: Fix flakiness of fdb/test_fdb_mac_learning.py for dualtor-aa
Fixes # https://github.com/aristanetworks/sonic-qual.msft/issues/515
After link bringup, it's taking some time for mux status to be consistent in `dualtor-aa` topology (i.e SERVER_STATUS is 'unknown'). And it's not a test specific issue, I can see similar behaviour on dut where dualtor-aa is deployed.
So increasing the timeout to 300 (currently it's 150 secs) to fix flakiness.
=> [sonic-mgmt][dualtor-aa] Fix flakiness of fdb/test_fdb_mac_learning.py

ansible/roles/vm_set/tasks/add_topo.yml, ansible/roles/vm_set/tasks/renumber_topo.yml
Set the default value of PTF image tag (`ptf_imagetag`) to branch based tags published by the release branch builds. The branch based docker-ptf builds continue to be mixed (Python 2 + Python 3) images and the master branch builds will be migrated to Python 3 only image.
Summary:
Set the default value of PTF image tag (`ptf_imagetag`) to branch based tags published by the release branch builds. The branch based docker-ptf builds continue to be mixed (Python 2 + Python 3) images and the master branch builds will be migrated to Python 3 only image.
Change default value in add-topo and renumber-topo YAMLs.
Will be verified in this CI run
None
NA
NA
=> [202305] Modify ptf_imagetag default value to branch based tag value

ansible/roles/vm_set/tasks/add_topo.yml, ansible/roles/vm_set/tasks/renumber_topo.yml
Set the default value of PTF image tag (`ptf_imagetag`) to branch based tags published by the release branch builds. The branch based docker-ptf builds continue to be mixed (Python 2 + Python 3) images and the master branch builds will be migrated to Python 3 only image.
Summary:
Set the default value of PTF image tag (`ptf_imagetag`) to branch based tags published by the release branch builds. The branch based docker-ptf builds continue to be mixed (Python 2 + Python 3) images and the master branch builds will be migrated to Python 3 only image.
Change default value in add-topo and renumber-topo YAMLs.
Will be verified in this CI run
None
NA
NA
=> [202405] Modify ptf_imagetag default value to branch based tag value

tests/everflow/test_everflow_ipv6.py
Summary: Increase timeout to 5 in verify_packet_any_port for background traffic
Fixes [#522](https://github.com/aristanetworks/sonic-qual.msft/issues/522), [#496](https://github.com/aristanetworks/sonic-qual.msft/issues/496)
The test is giving us a false negative 
```
msg        = 'Did not receive expected packet on any of ports [7, 13, 17, 30, 27, 25, 5, 34, 21, 16, 24, 1, 33, 12, 4, 20, 2, 0, 11... 01  .............0..\n0050  00 AA BB CC DD EE                                ......\n==============================\n'
self       = <tests.common.plugins.ptfadapter.ptfadapter.PtfTestAdapter testMethod=runTest>
/usr/lib/python3.8/unittest/case.py:753: AssertionError
```
Although on a closer look we found that the DUTis forwarding the packet in a reasonable duration of time but for some reason …
=> Increase timeout to 5 in verify_packet_any_port for background traffic

ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py, tests/dhcp_relay/test_dhcp_relay.py
Summary:
Add log for test_dhcp_relay for triaging issue
Add log for test_dhcp_relay for triaging issue
Run test and find below log files
```
/tmp/dhcp_relay_test.DHCPTest.default.Vlan1000.log               /tmp/dhcp_relay_test.DHCPTest.src_ip.Vlan1000.log
/tmp/dhcp_relay_test.DHCPTest.default.Vlan1000.pcap              /tmp/dhcp_relay_test.DHCPTest.src_ip.Vlan1000.pcap
/tmp/dhcp_relay_test.DHCPTest.default.Vlan1000.pcap.tar.gz       /tmp/dhcp_relay_test.DHCPTest.src_ip.Vlan1000.pcap.tar.gz
/tmp/dhcp_relay_test.DHCPTest.link_flap.Vlan1000.log             /tmp/dhcp_relay_test.DHCPTest.unicast_mac.Vlan1000.log
/tmp/dhcp_relay_test.DHCPTest.link_flap.Vlan1000.pcap            /tmp/dhcp_relay_test.DHCPTest.unicast_mac.Vlan1000.pcap …
```
=> [dhcp_relay] Optimize log for test_dhcp_relay

.azure-pipelines/pr_test_scripts.yaml, tests/dhcp_relay/test_dhcp_relay.py
This reverts commit 1762bc28f8ccdbde3cedd83ceb2f76204b2f2e17.
Summary:
test_dhcp_relay in t0-2vlans has been disabled in https://github.com/sonic-net/sonic-mgmt/pull/17208 to unblock PR check.
Suspect previous failure is flaky and not related to current case itself, hence re-enable it.
Run 11 rounds in current PR check, didn't see previous issue any more.
=> Revert "[dhcp_relay] Remove test_dhcp_relay test in t0-2vlans (#17208)"

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
The test result is not stable on Cisco platform.
Skip the testcase on Cisco platform.
N/A
=> Skip test_reload_configuration_checks on Cisco platform

ansible/vars/topo_t0-d18u8s4.yml
Summary:
Fixes same issue in [#22022](https://github.com/sonic-net/sonic-buildimage/pull/22022) by updating the peer T0's ASN to 4 bytes ASN number.
Fix topo error.
```
admin@sonic:~$ show ip bgp summary
IPv4 Unicast Summary:
BGP router identifier 10.1.0.32, local AS number 65100 vrf-id 0
BGP table version 2
RIB entries 3, using 672 bytes of memory
Peers 12, using 8903712 KiB of memory
Peer groups 5, using 320 bytes of memory
Neighbhor      V          AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down    State/PfxRcd    NeighborName
-----------  ---  ----------  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.0.0.57      4       64600          0          0         0      0       0  never      Active          ARISTA01T1
10.0.0.59      4 …
```
=> update d18u8s4 PT0 ASN to 4 bytes

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/dualtor_io/test_normal_op.py, tests/dualtor_io/test_switchover_impact.py
New test to measure switchover impact during planned vs unplanned switchover. The test runs send_t1_to_server_with_action with a mux switchover and measures the duration of the traffic impact.
Steps:
1. set up ipv4 and ipv6 neighbors. default 10 ipv4 and 64 ipv6.
2. set dut to active.
3. start traffic test.
4. switch interface to standby.
5. record and validate results.
by default the test runs 100 iterations, taking around 3 hours. The test will fail if one of the following conditions occur:
- Traffic drop exceeds threshold. (100ms for planned, 400ms for
unplanned)
- Switchover metrics on at least one of the duts do not match within threshold of measured traffic impact. (100ms for planned, 400ms for unplanned)
- Metrics on either device are not present.
- If there are multiple …
=> [dualtor_io] Add test_tor_switchover_impact test

tests/srv6/test_srv6_dataplane.py
Summary: There were two issues in srv6/test_srv6_dataplane.py
1. There were three places where run_srv6_traffic_test was called without ptfhost as an argument.
2. The blackhole packet drops should not be counted as RX_DROP so the blackhole test case should be marked as xfail since the discussion of how to handle this kind of drop is still ongoing
Fixes #17602 (issue)
=> Fix srv6/test_srv6_dataplane.py

tests/dash/configs/privatelink_config.py
* Default mac for direction lookup is src_mac, so outbound_direction_lookup needs to be explicitly set to "dst_mac"
Summary:
=> Fix pl test to handle outbound_direction_lookup

tests/common/dualtor/data_plane_utils.py, tests/common/dualtor/dual_tor_io.py, tests/dualtor_io/test_link_failure.py
Summary:
The following two link failure cases are failing on Cisco/MLNX:
```
test_active_link_down_downstream_active
test_active_link_down_downstream_active_soc
```
The reason is that, after link down, between the fdb flush and tunnel route add (due to mux toggle-to-standby), the ASIC has no l2 information for server/soc neighbors, downstream traffic will flood to all vlan member ports on Cisco/MLNX platform.
Those two testcase has no tolerance for packet duplications due to that, on Broadcom platform, traffic to neighbors with no l2 information will be simply dropped.
Let's adapt to Cisco/MLNX platform, by allowing packet duplications for those two testcases.
``` …
```
=> [dualtor_io] Allow duplications for link down downstream I/O

ansible/roles/vm_set/tasks/add_topo.yml, ansible/roles/vm_set/tasks/renumber_topo.yml
Set the default value of PTF image tag (`ptf_imagetag`) to branch based tags published by the release branch builds. The branch based docker-ptf builds continue to be mixed (Python 2 + Python 3) images and the master branch builds will be migrated to Python 3 only image.
Summary:
Set the default value of PTF image tag (`ptf_imagetag`) to branch based tags published by the release branch builds. The branch based docker-ptf builds continue to be mixed (Python 2 + Python 3) images and the master branch builds will be migrated to Python 3 only image.
Change default value in add-topo and renumber-topo YAMLs.
Will be verified in this CI run
None
NA
NA
=> [202311] Modify ptf_imagetag default value to branch based tag value

tests/qos/tunnel_qos_remap_base.py
Summary:
TC_TO_DSCP map defaults to 1-1 to help preserve encapsulated packet DSCPs during T1-transit. Reflect the default in the test configuration. 
Fixes a couple tests that would fail to find some extra configuration when producing a DSCP->DSCP map. 
Validated 2 failing tests in qos/test_tunnel_qos_remap.py passed on Cisco-8000 dualtor:
- test_encap_dscp_rewrite
- test_tunnel_decap_dscp_to_pg_mapping
Specific to Cisco-8000 dualtor platform.
=> Specify 1-1 default map for TC_TO_DSCP for Cisco-8000

tests/vxlan/test_vxlan_ecmp.py
Summary:
[test_cacl_application.py](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/cacl/test_cacl_application.py) was failing on smartswitch due to BFD iptable rules not being cleaned up by test_vxlan_crm.py, similarly to https://github.com/sonic-net/sonic-mgmt/pull/17046 .
[test_vxlan_crm.py](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/vxlan/test_vxlan_crm.py) was recently enabled for smartswitch, which uses the same setup fixture as [test_vxlan_ecmp.py](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/vxlan/test_vxlan_ecmp.py). However, the tests in test_vxlan_ecmp.py have additional cleanup code to handle these BFD entries which is missing in test_vxlan_crm.py.
Added a config restore fixture, same as in …
=> Restore config after vxlan_crm from vxlan_ecmp.

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Fix chrony related loganalyzer regex to ignore ERR logs that was added in #17801 
Summary:
PR https://github.com/sonic-net/sonic-mgmt/pull/16239 ignored an error message coming from ntpd (actually written by nss_tacplus). As that PR explains, this can happen when a config reload is run, and chrony calls getpwnam when /etc/tacplus_nss.conf is still being regenerated. However, it is not a failure.
With the change of NTP daemons, this loganalyzer ignore regex needs to be updated to match the right chrony log.
By running sonic-mgmt tests that perform config reload and verifying that these errors do not cause loganalyzer to mark the tests as failed.
=> Fix loganalyzer regex to ignore chronyd related ERR logs

tests/srv6/test_srv6_vlan_forwarding.py
Summary: This is to add a test case to verify that after enabling proxy_arp, there is no L2 flooding in downstream VLAN even though the switch does not have a FDB entry to forward a downstream SRv6 packet.
=> Add test_srv6_uN_no_vlan_flooding test case

.azure-pipelines/pr_test_scripts.yaml, tests/dhcp_relay/test_dhcp_relay.py
This reverts commit 53e58628642db1dacc0c5374f63e3a4246c7c86c.
Summary:
test_dhcp_relay would flaky fail in t0-vlans in PR check, which would block PR check-in, hence skip it for now
=> Revert "Revert "[dhcp_relay] Remove test_dhcp_relay test in t0-2vlans (#17208)" (#17676)"

tests/bmp/test_bmp_configdb.py, tests/bmp/test_bmp_statedb.py
Reverts sonic-net/sonic-mgmt#17910
=> Revert "Disable all bmp table after bmp test to avoid potential impact to other test cases"

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip test_null_route_helper (https://github.com/sonic-net/sonic-utilities/pull/1718) on M1/M2/M3 topo.
Current testcase requires VLAN on testbed. M1/M2/M3 don't have VLAN.
Skip test_null_route_helper on M1/M2/M3 topo.
Update conditional mark.
Verified by running test on M1 testbed:
```
acl/null_route/test_null_route_helper.py::test_null_route_helper SKIPPED (Skip running on dualtor/m1/m2/m3 ...) [100%]
=============================================== short test summary info ===============================================
SKIPPED [1] acl/null_route/test_null_route_helper.py: Skip running on dualtor/m1/m2/m3 testbed
=========================================== 1 skipped, 1 warning in 39.49s ============================================
```
=> [M1/M2/M3] Skip test_null_route_helper on M1/M2/M3 topo

tests/test_pretest.py
Summary:
Fix method collect_dut_lossless_prio.
The pfc_enable parameter can be empty.
Without this change we can get error:
```
>   result = [int(x) for x in port_qos_map[intf]['pfc_enable'].split(',')]
E   ValueError: invalid literal for int() with base 10: ''
```
PRs with related changes:
https://github.com/sonic-net/sonic-buildimage/pull/22252
https://github.com/sonic-net/sonic-buildimage/pull/22067
stable test_pretest.py
Used method `get`
Test passed after changes
=> [pretest] update collect_dut_lossless_prio method

tests/common/devices/sonic.py
Summary:
Gather facts will run commands on sonic hosts and get the results of platform information. But in dualtor, hosts may need more time to get the return results and caused pretest failure.
Increase timeout in gathering facts and check if the success rate increase in a week.
=> Increase timeout for gathering sonic hosts facts

ansible/config_sonic_basedon_testbed.yml
Summary:
Enable bmp table dump before all test cases as pre-condition
Enable bmp table dump before all test cases as pre-condition
update ansible/config_sonic_basedon_testbed.yml and add one blocl
validation will cover it.
N/A
N/A
=> Enable bmp table dump before all test cases as pre-condition

tests/generic_config_updater/test_eth_interface.py, tests/generic_config_updater/test_ip_bgp.py, tests/generic_config_updater/test_portchannel_interface.py
Currently, function `format_json_patch_for_multiasic` that is used to format json path based on the namespace that chnage targets, gets as argument the asic namespace or the asic namespaces list if it is targetted to more than one, in case duthost is multiasic.
There is bug in the way we pass this argument to function as it is sent with a '/' before namespace name.
This PR fixes this issue that should be seen only on multi-asic platforms.
Summary:
Tested in vs-kvm t0 and t2
=> [GCU] Fixing argument passed to format_json function for multi-asic case

tests/bfd/test_bfd.py
Summary:
On Smartswitch, the following non-multihop specific failures are seen after running test_bfd.py:
Failure 1:
Testcases: bfd/test_bfd.py::test_bfd_basic[ipv4-dut_init_first], bfd/test_bfd.py::test_bfd_basic[ipv4-ptf_init_first], bfd/test_bfd.py::test_bfd_basic[ipv6-dut_init_first]
File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 493, in call
return self._hookexec([self.name](http://self.name/), self._hookimpls, kwargs, firstresult)
File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 115, in _hookexec
return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 113, in _multicall
raise exception.with_traceback(exception.traceback)
File …
=> Fix BFD status check and ipv6 PTF intermittent issue.

tests/platform_tests/test_cpu_memory_usage.py
Skip nasa proc check because high usage of nasa is expected
Summary:
Skip nasa proc check because high usage of nasa is expected
Skip check nasa proc
Run it on smartswitch dpu
smartswtich dpu
=> [Mellanox] Skip nasa proc check in test_cpu_memory_usage

ansible/roles/test/files/ptftests/router_adv_mflag_test.py
Summary:
In some testbeds, `eth1` isn't always present. This PR is to enhance the test case to support the testbed without `eth1`.
Replace the `ptf_port_index` as IPv6 advertisement interface which will be always present in the testbed.
```
radv/test_radv_ipv6_ra.py::test_radv_router_advertisement PASSED                                      [ 25%]
radv/test_radv_ipv6_ra.py::test_solicited_router_advertisement PASSED                                [ 50%]
radv/test_radv_ipv6_ra.py::test_unsolicited_router_advertisement_with_m_flag PASSED       [ 75%]
radv/test_radv_ipv6_ra.py::test_solicited_router_advertisement_with_m_flag PASSED           [ 100%]
```
=> [radv_ipv6_ra]: Fix the hardcode interface for IPv6 advertisement interface

ansible/roles/test/files/ptftests/py3/advanced-reboot.py, tests/scripts/arp_responder.py
Summary:
Improve the overall performance of arp_responder.py.
1. Reuse the socket that is receiving ARP/NDP requests for sending ARP/NDP responses. This avoids opening a socket, binding it to an interface, sending the packet, and closing it everytime, and just requires one syscall to send the packet.
2. Use the libpcap socket backend in scapy. With libpcap, instead of needing to use `recvmsg` syscalls to get packets one at a time, a RX ring buffer is set up as shared memory between userspace and kernel space. The kernel then writes incoming packets into that ring buffer, and then userspace reads it from there. All this happens with only one syscall to `select` (or equivalent) to know when data (one or more packets) is available, instead of 2 syscalls per packet. The …
=> Improve arp_responder.py performance

ansible/roles/test/files/ptftests/py3/advanced-reboot.py, tests/common/fixtures/advanced_reboot.py
Summary:
This is (hopefully) more efficient on the system by being a single process (but multiple threads for each interface), and also stores information about which interface each packet was seen on. This also eliminates the need to run mergecap afterwards.
In addition, specify the snapshot length to 1514 bytes to optimize for "small" packets (small relative to the default snapshot length of 262144 bytes). Because libpcap is being used, which means a RX packet ring is being used, and the snapshot length directly relates to the number of packets that can be stored in the ring (assuming a fixed buffer size) before it needs to be processed. The largest packet that we care about capturing is less than 200 bytes, but use 1514 bytes as a conservative size.
For now, …
=> Switch from tcpdump to dumpcap

tests/pfcwd/conftest.py, tests/pfcwd/test_pfcwd_function.py
Summary:
1. Updated the test case logic to include active interfaces from all available ASICs, preventing unnecessary skips.  
2. Ensured that the multi-port test case selects an appropriate RX port for the second port, avoiding the use of an already stormed port.
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/16777
Failure of the Test Case of test_pfcwd_multi_port on min topology because of the rx port selection of stormed port and on max topo because of not including all the active interfaces on both the basics
https://github.com/sonic-net/sonic-mgmt/issues/16777
Add the scope of using the Active interfaces from all the ASIC.
Added the requirement of not to use the RX which is going to be stormed 
Verified on t2 voq chassis on min and max topo
=> Pfcwd multi port: Fix for Multi-asic Scenario and test_multi_port Requirement of 3 routed ports

tests/l2/test_l2_configure.py
Summary:
Fixes # (issue) Microsoft ADO 31856103
Address flakes such as https://elastictest.org/scheduler/testplan/67d6bf6e607a6896f60ddd2a?testcase=l2%2ftest_l2_configure.py&type=console
```
if callback.unreachable:
>           raise AnsibleConnectionFailure(
"Host unreachable in the inventory",
dark=callback.unreachable,
contacted=callback.contacted,
)
E           pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inventory
```
During config reload, the ipv4 connection can get broken and the ansible will through an exception here.
This doesn't affect the assertion of this particular test.
Catch the exception.
10 runs of test_l2_configure.py on kvm.
=> Reduce flakiness of test_l2_configure.py on kvm.

tests/platform_tests/api/watchdog.yml
Summary:
Add the `x86_64-8101_32fh_o_c01-r0` config to the `platform_tests/api/watchdog.yml` file in order to fix the failing test `platform_tests/api/test_watchdog.py`.
To fix the failing test `platform_tests/api/test_watchdog.py`.
Modify the `platform_tests/api/watchdog.yml` config file.
Run the `platform_tests/api/test_watchdog.py`.
=> [watchdog] Add the x86_64-8101_32fh_o_c01-r0 config to the platform_tests/api/watchdog.yml

tests/common/utilities.py, tests/qos/test_qos_dscp_mapping.py
Summary:
test_qos_dscp_mapping.py was always directing traffic to the router's mac. However, some topos (primarily dualtor) use a vlan that overrides the mac address to be different from the router. This results in an incorrect VLAN broadcast operation, none of which goes to the uplink portchannels, causing the traffic to not be detected. 
- Added a common utility to retrieve the vlan name from a given port name
- Check if the src port is in a vlan, if so, grab its mac addr and use that instead of the router address. 
- Fix an issue with the ipv4 loopback getter where it would break, but not fully break the second loop. This would result in Loopback3 on dualtor being selected instead of Loopback0. Loopback3 has an OVS flow for packet duplication, which would result in traffic being …
=> Fix vlan vs router mac issue with test_qos_dscp_mapping.py

ansible/group_vars/sonic/variables
Summary:
T add Cisco-8101-V64 to the cisco-8000_gb_hwskus list. If it is not in the list, then the test is not able to identify the asic type as “gb” using a reverse lookup.
Added hwsku Cisco-8101-V64 to the cisco-8000_gb_hwskus list.
The error "Failed: Cannot identify DUT ASIC type" no longer occurs on a Cisco-8101-V64 device.
=> add hwsku Cisco-8101-V64 to the cisco-8000_gb_hwskus list

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Align the sensors data for SN4280 with [sonic-buildimage PR#21845](https://github.com/sonic-net/sonic-buildimage/pull/21845).
The temperature sensor for "\*-mdio-\*" is ignore in sensor conf, the test data should be aligned.
=> [Mellanox] Align the sensors data for SN4280 with sonic-buildimage PR#21845

tests/platform_tests/test_intf_fec.py
Add retry when checking fec mode restore status in test_intf_fec.py
It may need some seconds for fec mode to restore to the original value
Summary:
tests/platform_tests/test_intf_fec.py failed with low chance
Add retry when checking fec mode restore status in test_intf_fec.py
=> Add retry when checking fec mode restore status in tests/platform_tests/test_intf_fec.py

tests/arp/test_arp_update.py
Enhance tests/arp/test_arp_update.py to support port toggle at dualtor active active testbed.
Currently, it only support port toggle at dualtor active standby testbed, it could not do port toggle at dualtor active active setup.
Summary:
The script tests/arp/test_arp_update.py does not support port toggle at dualtor aa setup
The script tests/arp/test_arp_update.py does not support port toggle at dualtor aa setup
Invoke dualtor aa setup port toggle fixture
=> Enhance arp update test to support port toggle at dualtor active active testbed

tests/common/fixtures/duthost_utils.py
Summary:
Fixes failure if DUT does not have ipv6 management address set
If DUT does not have ipv6 mgmt address to be set - TC fails 
Add pytest.skip if ipv6 mgmt address not set
Run TC. TC skip
=> Added skip for test_mgmt_ipv6_only TC if ipv6 mgmt not available

tests/hash/generic_hash_helper.py, tests/hash/test_generic_hash.py
Update generic hash test to support dualtor active active topology
Summary:
https://github.com/sonic-net/sonic-mgmt/issues/15340
Bug fix for https://github.com/sonic-net/sonic-mgmt/issues/15340
Integrate the generic hash test to dualtor-aa topology
=> Update generic hash test to support dualtor active active topology

tests/common/helpers/constants.py
Summary:
Add M1 up/down stream neighbor type.
Add M1 up/down stream neighbor type.
Add M1 up/down stream neighbor type.
Verified by testcase `route/test_default_route.py`.
=> [M1] Add M1 up/down stream neighbor type

tests/acl/test_acl.py
Summary:
Fixes #17048 
Previously ACL test change picks up loopback ip from `rand_selected_dut`, on T2 devices supervisor card doesn't have a loopback ip causing errors
Use `rand_selected_front_end_dut` instead of `rand_selected_dut` for T2
Ran 61 iterations of basic ACL test to make sure it passes on T2 device
Additionally:
T0: [Test plan 67daa46be946313de56c8bf2: ACL changes regression test T0 - Elastictest (elastictest.org)](https://elastictest.org/scheduler/testplan/67daa46be946313de56c8bf2)
T1: [Test plan 67daa4a42f30cd54926394de: ACL changes regression test T1 - Elastictest (elastictest.org)](https://elastictest.org/scheduler/testplan/67daa4a42f30cd54926394de)
T2: [Test plan 67daa4ebe946313de56c8bf4: ACL changes regression test T2 - Elastictest …
=> [acl/test_acl.py] Ensure frontend dut is used for T2 in ACL testing

tests/srv6/test_srv6_dataplane.py
Summary: Previously I changed the import of scapy from ptf.packet to direct import, that broke the scapy header classes reference in the TestSRv6Base. Besides, when there is no LLDP neighbors, we should directly skip the test script.
=> Fix incompatible import of scapy and skip when no lldp neigh in test_srv6_dataplane.py

tests/lldp/test_lldp_syncd.py
Summary:
- Split the original PR https://github.com/sonic-net/sonic-mgmt/pull/17130 into individual PRs for each test.
- If switch type is VOQ, decide based on the number of Duts and also based on if the DUT is modular chassis or not.
=> [PR#17130] - lldp - Changes for VOQ single-dut multi-asic

tests/arp/test_arp_dualtor.py
Summary:
Fix `test_arp_dualtor` on active-active dualtor.
Two issues:
1.  `test_arp_update_for_failed_standby_neighbor` is failing on `active-active` dualtor.
The testcase is designed to validate the `FAILED` neighbor behavior on `active-standby` dualtor and the test steps are not working on `active-active` dualtor. 
The testcase is based on the fact that, on active-standby dualtor, the mux will drop downstream packets from the standby ToR, so any ARP probes from the standby ToR will be dropped by the mux -> no ARP replies -> `FAILED` neighbor on the standby ToR.
The mux forwarding behavior is different on active-active dualtor: the mux still forwards the ARP probes from the standby ToR -> ARP replies are generated -> `REACHABLE` neighbor on both ToRs.
2. …
=> [dualtor-aa] Fix `test_arp_dualtor` on active-active dualtor

ansible/roles/vm_set/templates/sonic.xml.j2
Summary:
KVM testbed have a chance to fail for memory exhaustion:
```
>       pytest.fail(message)
E       Failed: [ALARM]: monit:memory_usage, Previous memory usage 90.2 exceeds high threshold 90.0
```
Increase KVM testbed memory from 4G to 6G
=> Increase KVM testbed memory from 4G to 6G

tests/common/fixtures/fib_utils.py
Summary:
- Split the original PR https://github.com/sonic-net/sonic-mgmt/pull/17130 into individual PRs for each test.
- If switch type is VOQ, decide based on the number of Duts and also based on if the DUT is modular chassis or not.
=> [PR#17130] - fib - Changes for VOQ single-dut multi-asic 

tests/common/helpers/voq_lag.py
Summary:
- Split the original PR https://github.com/sonic-net/sonic-mgmt/pull/17130 into individual PRs for each test.
- If switch type is VOQ, decide supervisor based on the number of Duts and also based on if the DUT is modular chassis or not.
=> [PR#17130] - VOQ Lag - Changes for VOQ single-dut multi-asic

ansible/group_vars/all/creds.yml
Summary:
The eos default cred is all digits. It may be interpreted as an integer and raise below error during tests:
```
File "/var/src/sonic-mgmt/tests/common/devices/eos.py", line 85, in shutdown
out = self.eos_config(
File "/var/src/sonic-mgmt/tests/common/devices/base.py", line 131, in _run
raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
tests.common.errors.RunAnsibleModuleFail: run module eos_config failed, Ansible Results =>
failed = True
module_stdout = 
module_stderr = Expected unicode or bytes, got 123456
msg = MODULE FAILURE
See stdout/stderr for the exact error
_ansible_no_log = None
changed = False
stdout =
stderr =
```
Add quote to the all digits default cred to force string type.
=> Force eos default creds to be string

ansible/roles/fanout/templates/arista_7060_deploy.j2, ansible/roles/fanout/templates/arista_7260cx3_deploy.j2
Summary:
PR #15004 enhanced the connection graph csv files to support "AutoNeg". After this change, deploy fanout switch using connection graph csv files missing this field would fail.
This change updated the fanout deploy template to best effort getting value of "autoneg" for links. With this change, the field "AutoNeg" in csv file would be optional and default to "off" or on according to context.
Verified deployment on physical fanout switch.
=> Make "autoneg" in connection graph optional

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
* These errors are temporarily ignored until the issues referenced below are fixed: 
https://github.com/sonic-net/sonic-buildimage/issues/22346
https://github.com/sonic-net/sonic-buildimage/issues/22348
The PR ignores the following errors seen on kvm test runs on master branch:
E               Failed: Got matched syslog in processes "analyze_logs--<MultiAsicSonicHost vlab-01>" exit code:"1"
E               match: 7
E               expected_match: 0
E               expected_missing_match: 0
E               2025 Apr 16 19:34:25.031707 vlab-01 ERR hostcfgd: ['sonic-kdump-config', '--disable'] - failed: return code - 1, output:#012None
E               2025 Apr 16 19:34:25.714266 vlab-01 ERR hostcfgd: ['sonic-kdump-config', …
=> Add certain error signatures to loganalyzer ignore list

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
The fib/test_fib.py::test_nvgre_hash is not fully supported on Mellanox SPC1 platforms.
I have opened an issue https://github.com/sonic-net/sonic-mgmt/issues/17526 to enhance the test.
Skip the test based on the issue.
Fix #17526
=> [Mellanox] Skip the fib nvgre hash test on SPC1 with t1-lag topology

ansible/testbed-cli.sh, ansible/testbed_config_vchassis.yml
Summary: Previously, the testbed_config_vchassis.yml playbook was called with some unnecessary arguments which may cause failures for certain users depending on the user input. Now, we remove the unnecessary arguments to reduce the possibility caused by misinput.
Fixes #17922  (issue)
=> Remove unused arguments when calling testbed_config_vchassis playbook.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Warm reboot is not fully-supported on dualtor, and might leave the testbed in a corrupted state.
Let's skip the pfc wb testcase for now.
Skip the pfcwd warm reboot test on dualtor.
```
pfcwd/test_pfcwd_warm_reboot.py::TestPfcwdWb::test_pfcwd_wb[no_storm-str3-7260cx3-acs-1] SKIPPED (Warm Reboot is not supported in T2 or in standalone topos. / Pfcwd tests skipped on M* testbed. / Warm reboot is not required for 202412 / Pfcwd warm reboot is not
supported on cisco-8000 platform.)                                                                                                                                                                                                                                     [ 33%] …
```
=> [dualtor] Skip pfcwd warm reboot on dualtor

tests/common/utilities.py, tests/qos/test_qos_dscp_mapping.py
Summary:
Double commit  #17846
=> [202411] Fix vlan vs router mac issue with test_qos_dscp_mapping.py

tests/common/devices/multi_asic.py
Summary:
Sometimes dhcp containers are messed up by previous test, but sanity check cannot notice it because they are not critical services
Add them to critical services if features are enabled
Run tests
=> [DHCP] Add dhcp_server and dhcp_relay services to critical services if features are enabled

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/gnmi/helper.py
Update GNMI test case to support cname role list. 
GNMI service will change to mapping cname to a role list:
https://github.com/sonic-net/sonic-buildimage/pull/21849
To make sure GNMI test case in sonic-mgmt can pass with/without this change, we need improve test case to handle both case.
- Microsoft ADO: 31561802
Ignore test case bug github issue: https://github.com/sonic-net/sonic-mgmt/issues/17876
Change GNMI setup code to handle role list by check yang model
Update GNMI test case to support cname role list.
=> Update GNMI test case to support cname role list.

ansible/roles/eos/templates/t0-isolated-v6-d128u128s1-leaf.j2, ansible/roles/eos/templates/t0-isolated-v6-d128u128s2-leaf.j2, ansible/roles/eos/templates/t0-isolated-v6-d16u16s1-leaf.j2, ansible/roles/eos/templates/t0-isolated-v6-d16u16s2-leaf.j2, ansible/roles/eos/templates/t0-isolated-v6-d256u256s2-leaf.j2, ansible/roles/eos/templates/t0-isolated-v6-d32u32s2-leaf.j2, ansible/roles/eos/templates/t0-isolated-v6-d96u32s2-leaf.j2, ansible/roles/eos/templates/t0-v6-leaf.j2, ansible/templates/topo_t0-isolated-v6.j2, ansible/templates/topo_t1-isolated-v6.j2, ansible/vars/topo_t0-isolated-v6-d16u16s2.yml, ansible/vars/topo_t0-isolated-v6-d256u256s2.yml, ansible/vars/topo_t0-isolated-v6-d32u32s2.yml, ansible/vars/topo_t1-isolated-v6-d28u1.yml, ansible/vars/topo_t1-isolated-v6-d448u16.yml, ansible/vars/topo_t1-isolated-v6-d56u2.yml
Summary:
Fixes issues in isolated v6 topo.
Fix the following error
- ipv6 address pattern
- 'route-id' typo
-  remove template dependencies for `nhipv4` and `host['interfaces']['Loopback0']['ipv4']`
=> Fix t0-isolated-v6 topo errors

ansible/library/generate_golden_config_db.py
Summary: BMP feature is not needed for chassis supervisors because they don't have BGP service running.
=> Disable BMP feature for chassis supervisors

tests/common/dualtor/dual_tor_utils.py, tests/common/dualtor/mux_simulator_control.py, tests/telemetry/test_events.py
Summary: Fix telemetry/test_events.py for dualtor
Fixes [#480](https://github.com/aristanetworks/sonic-qual.msft/issues/480)
`telemetry/test_events.py` is flaky
The verification of events wrt DHCP via telemetry involves sending traffic. In that case it is intended that -
1. For active-standby dualtor the randomly selected ToR is active.
2. For active-active dualtor the traffic doesn't go to the unselected ToR
Proposed fix is to introduce following new fixtures -
1. toggle_all_simulator_ports_to_enum_rand_one_per_hwsku_host_m which will make the randomly selected ToR as active in active-standby dualtor
2. setup_standby_ports_on_non_enum_rand_one_per_hwsku_host_m will make the unselected ToR as standby in active-active dualtor
These fixtures rely on `enum_rand_one_per_hwsku_hostname` for …
=> Fix telemetry/test_events.py for dualtor

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/qos/files/qos_params.j2c.yaml, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py
The existing HeadroomPool size test is based on traditional way of buffer allocation to calculate the headroompoolsize.
For Broadcom chassis, this new test calculates the buffer allocation using dynamic threshold to fill shared pool & headroom and verify the headroom size per vsq.
Skip test :-testQosSaiHeadroomPoolWatermark - SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES is not supported on broadcom-dnx
Summary:
For Broadcom chassis, since the headroom per vsq is huge, 4 src port are used to fill the headroom.
Issue : https://github.com/sonic-net/sonic-mgmt/issues/13503
Verifying HeadroomPoolsize  test for  broadcom-dnx chassis
Executed qos test for headroomPool size and verify the  results
Resource allocation
max headroom per vsq
=> [Qos]HeadroomPoolSize test with dynamic_threshold based buffer allocation 

tests/dash/conftest.py, tests/dash/test_dash_privatelink.py
* Teardown configurations after the test
* Make sure that vnet mapping is configured after routing_type is configured
* Add an option to select the dpu to use for testing
Summary:
To make sure that configuration applied during the test is cleaned up properly at the end of the test.
By adding cleanup logic for PL tests.
By running sonic-mgmt test PL test and verifying that the DASH objects programmed during the test are cleaned up at the end.
=> DASH PL tests fixes

ansible/config_sonic_basedon_testbed.yml, ansible/library/load_extra_dpu_config.py
Summary: Make DPU workflow rotate password instead of hardcode
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/17773
1. Make rotate password instead of hardcode; 2. Add comment for smartswitch topo.
Try preset creds info.
E2E test with non hardcode password.
```
PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************
TESTBED            : ok=100  changed=34   unreachable=0    failed=0    skipped=69   rescued=0    ignored=1   
Monday 21 April 2025  02:27:15 +0000 (0:00:00.449)       0:03:37.697 ********** 
========================================================================== …
```
=> [smartswitch] Make DPU workflow auto rotate password

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: Mark xfail for flaky hashing behavior when using a specific combination of hash field and algorithm, such as CRC-INNER_L4_DST_PORT-ipv4-ipv6-nvgre.
Mark xfail for flaky hashing behavior when using a specific combination of hash field and algorithm, such as CRC-INNER_L4_DST_PORT-ipv4-ipv6-nvgre.
Mark test_generic_test.py as xfail in mark conditions yaml file
Verified it in nightly test run.
str4-sn5600-1
t0-isolated-u16d16s1
=> Mark xfail for generic hash test in isolated topo

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/18031 into 202411
=> [202411][dualtor] Skip pfcwd warm reboot on dualtor

ansible/roles/eos/tasks/ceos.yml
Summary:
When adding topology with batch size 30, the task snmp_facts may take hours due to there is no ceos container responding.
We need to skip this task when there is no ceos container to save time.
Check if ceos container exsit, if no, skip snmp_facts task
Tested on testbed with add-topo after remove-topo
from the pic, we can see that, due to ceos container was deleted when remove-topo, so when add-topo, there is no ceos container, and the snmp_facts task was skipped.
=> [testbed-cli opt] skip snmp_facts when ceos container doesn't exist to save time

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Temporarily skip test_acl for isolated-v6 topo until #18077 is fixed.
skip test_acl for v6 only
skip test_acl module for v6 only
=> skip acl for isolated-v6 topo temporarily

tests/acl/test_acl.py
Summary:
This PR is to reduce the time cost for running acl test.
**Before this change:**
`port_toggle` and `cold reboot` are issued for each param combination. That's 8 times in total.
The time cost for acl test is 90 minutes on a T0 testbed.
**After this change:**
Only run `port_toggle` and `cold_reboot` once, and then run test with different param combinations. This is closer to the production scenario.
The time cost for acl test is 60 minutes on a T0 testbed.
So the change can save 30% of the time cost for running acl test.
This PR is to improve `test_acl`.
Add two static variable to ensure DUT only run `port_toggle` and `reboot` once.
The change is verified on a physical T0 testbed.
```
collected 800 items …
```
=> [SONiCMgmtBoost] Boost acl test by only running reboot/port toggle once

ansible/group_vars/sonic/variables, ansible/module_utils/port_utils.py, ansible/roles/test/tasks/dir_bcast.yml, ansible/roles/test/tasks/fdb.yml, ansible/roles/test/tasks/fdb_mac_expire.yml, ansible/roles/test/tasks/pfc_wd/choose_test_port.yml, ansible/roles/test/tasks/pfc_wd/iterate_portchannels.yml, ansible/roles/test/tasks/qos_sai.yml, ansible/roles/test/tasks/shared-fib.yml, ansible/roles/test/tasks/warm-reboot-multi-sad.yml, ansible/roles/test/tasks/warm-reboot-sad-lag-member.yml, ansible/roles/test/templates/fib.j2, ansible/roles/test/vars/testcases.yml, ansible/testbed-new.yaml, tests/common/platform/warmboot_sad_cases.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml, tests/fdb/test_fdb.py, tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py
Summary:
Manually backport t0-118 test configs (https://github.com/sonic-net/sonic-mgmt/pull/16659) to 202411
Ran test suite on t0-118 supported DUT
=> Backport t0-118 test configs to 202411

ansible/group_vars/sonic/variables, ansible/module_utils/port_utils.py, ansible/roles/test/tasks/dir_bcast.yml, ansible/roles/test/tasks/fdb.yml, ansible/roles/test/tasks/fdb_mac_expire.yml, ansible/roles/test/tasks/pfc_wd/choose_test_port.yml, ansible/roles/test/tasks/pfc_wd/iterate_portchannels.yml, ansible/roles/test/tasks/qos_sai.yml, ansible/roles/test/tasks/shared-fib.yml, ansible/roles/test/tasks/warm-reboot-multi-sad.yml, ansible/roles/test/tasks/warm-reboot-sad-lag-member.yml, ansible/roles/test/templates/fib.j2, ansible/roles/test/vars/testcases.yml, ansible/testbed-new.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml, tests/fdb/test_fdb.py, tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py
Summary:
Manually backport t0-118 test configs (https://github.com/sonic-net/sonic-mgmt/pull/16659) to 202405
=> Backport t0-118 test configs to 202405

ansible/roles/test/files/ptftests/py3/advanced-reboot.py
Summary: 
Extend LACP timeout for cEOS peers by setting LACP timer multiplier to `5` during advanced-reboot PTF test, and restore the value to the default `3` after the test completes.
Transitioning from using vSonic peers to cEOS peers for some tests. Requested by Microsoft.
Adding cli commands for each cEOS peers at the start and end of the PTF test `advanced-reboot.py`.
Tested with `test_upgrade_path.py::test_upgrade_path` on a `Arista-7050CX3-32S-C32`.
=> Extend LACP time multiplier for advanced-reboot tests with cEOS peers

tests/memory_checker/test_memory_checker.py
This patch adds handling for concatenating multi-line output to the prior service's last value.
Summary: memory_checker/test_memory_checker.py fix reading monit status
Fixes https://github.com/sonic-net/sonic-mgmt/issues/18101
In some circumstances monit can return multiline data for a value for a service, such as:
```
Program 'routeCheck'
status                       Status ok
monitoring status            Monitored
monitoring mode              active
on reboot                    start
last exit value              255
last output                  Some routes are not set offloaded in FRR                           but all routes in APPL_DB and ASIC_DB are in sync
Failure results: {{
"": {
"missed_FRR_routes": [
{
"destSelected": true,
"distance": 1,
...
```
This results in a parser error …
=> monit service parsing needs to handle multi-line data

tests/qos/tunnel_qos_remap_base.py
Summary:
This PR is to fix an issue caused by PR #17800
`python: can't open file '/packets_aging.py': [Errno 2] No such file or directory`
Root cause:
If `swap_syncd` fixture is executed, the file copied to `syncd` container will be removed. 
This PR addressed the issue by ignoring the errors for running the script or removing the script.
This PR is to fix an issue caused by PR #17800
```
python: can't open file '/packets_aging.py': [Errno 2] No such file or directory
```
Ignore the error.
The change is verified by running `test_tunnel_decap_dscp_to_pg_mapping` on a dualtor testbed with `swap_syncd` enabled.
``` …
```
=> Fix packets_aging.py not found issue

tests/everflow/everflow_test_utilities.py
Summary:
Fix error when running everflow/test_everflow_testbed.py::TestEverflowV4EgressAclEgressMirror::test_everflow_dscp_with_policer: 
```
E cmd = ['config', 'acl', 'add', 'table', 'EVERFLOW_DSCP', 'MIRROR_DSCP', '--stage', 'egress', '-p', 'Not', 'Applicable']
E Error: Got unexpected extra argument (Applicable)
```
The shell interpreter treats "Not Applicable" as two separate arguments instead of one value.
The shell interpreter treats "Not Applicable" as two separate arguments instead of one value, and causes error: RunAnsibleModuleFail: run module command failed
By filtering out "Not Applicable" entries from the port list
Verified it in nightly test run:
``` …
```
=> Fix for Everflow ACL Table Configuration Error

tests/qos/test_tunnel_qos_remap.py, tests/qos/tunnel_qos_remap_base.py
Summary:
This PR is to cherry-pick #17800 to 202411 branch and address an issue as well.
This PR is to fix an issue introduced by https://github.com/sonic-net/sonic-mgmt/pull/17728
The auto-used PR is still required for the test cases in [tests/qos/test_tunnel_qos_remap.py](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:restore_disable_packet_aging_fixture?expand=1#diff-0bc1dc320b693a545a1dd0b09c307b3f13faf79f79650fc7a1fe4fb78e3c8480) because fixture `update_docker_services` is only called for several test cases.
This PR is to fix an issue introduced by https://github.com/sonic-net/sonic-mgmt/pull/17728
Add the fixture back.
Verified on a physical SN4700 dualtor testbed.
```
collected 4 items …
```
=> [202411] Restore disable packet aging fixture 202411

ansible/testbed_config_vchassis.yml, ansible/veos_vtb, tests/common/devices/multi_asic.py
Summary: there were some issues with the infrastructure found during testing with virtual chassis, as articulated below:
1. BMP feature is enabled on latest master image with multi-asic LCs. However, it is not marked as DEFAULT_ASIC_SERVICES so we need to manually check it when doing modify_syslog_rate_limit. 
2. The virtual chassis supervisor is not acting like a fabric card and it does not have fabric card's info so we should not mark its switch_type as fabric. I added a new switch_type called 'dummy-sup'.
=> Repave testing infra for virtual chassis

tests/qos/files/cisco/qos_param_generator.py
Summary:
https://migsonic.atlassian.net/browse/MIGSMSFT-848
qos.test_qos_sai.TestQosSai.testQosSaiXonHysteresis failed on hwsku Cisco-8101-O32 T1 setup.
VOQ tail drop since connected routes use default voq. Multi src_ports → same dst_port using same voq, caused voq tail drop happen before PFC triggered.
Fix testQosSaiXonHysteresis failures for Cisco-8101-O32.
Adjust port selection to avoid multiple flows using same voq.
Verified on Cisco-8101-O8C48 T1 testbed.
SONiC Software Version: SONiC.azure_cisco_202411.23036-dirty-20250402.193037
sdk-version: 24.11.3000.24
```
-------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiXonHysteresis_2025-04-25-23-19-16.xml -------------- …
```
=> Adjust port selection in testQosSaiXonHysteresis for Cisco-8101-O32

azure-pipelines.yml
Modify PR tests pipeline to increase the usage of `py3only` docker-ptf tag to 70% of the PRs.
Summary:
Modify PR tests pipeline to increase the usage of `py3only` docker-ptf tag to 70% of the PRs. More testing of `py3only` tag before full rollout.
NA
NA
NA
NA
NA
=> Set PR tests to use py3only PTF image tag to 70%

ansible/roles/fanout/templates/sonic_deploy_202405.j2
Summary:
When vlanids are not provided in the links.csv, need to skip generating vlan member configuration.
When links.csv is defined as following where no VLAN id is provided.  This is a use case where in minimised isolated-xx topology, VLANs are not needed for some links to save VLAN id resource
```
dut1,Ethernet0,fanout1,Ethernet0,100000,,Access,off
```
fanout.yaml will generate the following incorrect config, and cause vlanmgr crash.
```
"Vlan|Ethernet0": {
"tagging_mode": "untagged"
},
```
The format vlanmgr expects is following:
```
"Vlan2900|Ethernet0": {
"tagging_mode": "untagged"
},
```
Skip generating wrong vlan member configuration in fanout.yml
manually verified on physical testbed.
=> skip vlan member config if no vlan is defined in fanout.yml deployment

tests/memory_checker/test_memory_checker.py
Summary:
memory_checker test uses fixed memory threshold for gnmi and telemetry container.
We will increase memory threshold for gnmi container, and then this threshold will be wrong.
Read monit config file to get memory threshold.
Run memory_checker test.
=> Read memory threshold from monit config to improve memory_checker test

ansible/roles/test/files/ptftests/py3/fdb_mac_learning_test.py, tests/fdb/test_fdb_mac_learning.py
Summary:
few improvements/fixes to `fdb_mac_learning_test.py`:
1. replace the `config reload` in the setup with `sonic-clear` commands to cleanup fdb/arp entries in setup, this reduces the reload overhead.
2. send ARP packets instead of simple Ether packets to populate fdb table, this avoids the complex toggle logic on dualtor as the ARP packets are duplicated/accepted by both sides regardless of the mux status.
3. add the ip assignment before the neighbor check to validate the ip is correctly assigned on DUT.
4. sleep after ip assignment/before ping to wait for the ip assignment finish.
t0:
```
fdb/test_fdb_mac_learning.py::TestFdbMacLearning::testFdbMacLearning PASSED …
```
=> [dualtor] Refine `fdb_mac_learning_test.py`

tests/dualtor_io/conftest.py, tests/dualtor_io/test_tor_failure.py
Summary:
Fix the following issue:
```
E               Exception: start-LogAnalyzer-test_active_tor_reboot_downstream_standby[active-standby].2025-04-22-10:20:35 was not found in /var/log
```
The issue is introduce by PR: https://github.com/sonic-net/sonic-mgmt/pull/17722.
The root cause is, if the dualtor io reboot failure testcases are running over Arista devices, the syslogs doesn't persist through reboot due to `/var/log` is a tmpfs directory. So `loganalyzer` fails to find the start marker in this case.
As the primary goal is to collect syslog after reboot, let's change the start marker as the kernel first boot log, so the dualtor io testcase with reboot will be able to collect logs after kernel boot up.
``` …
```
=> [dualtor_io] Fix the start marker not found issue

tests/common/fixtures/advanced_reboot.py, tests/common/fixtures/consistency_checker/consistency_checker.py, tests/common/fixtures/consistency_checker/constants.py, tests/common/fixtures/consistency_checker/query-asic/parser.py, tests/common/fixtures/consistency_checker/query-asic/query-asic.py, tests/platform_tests/args/advanced_reboot_args.py, tests/platform_tests/test_advanced_reboot.py, tests/upgrade_path/test_upgrade_path.py
Summary:
This is a manual backport of the consistency-checker utility from master at commit f2cadae6. This includes the following two PR's:
- https://github.com/sonic-net/sonic-mgmt/pull/14402
- https://github.com/sonic-net/sonic-mgmt/pull/16877
Manually backported due to conflicts.
There were conflicts in creating cherry-pick backport PR's hence this manual approach.
Cherry-picked the changes from the two PR's and resolved conflicts.
Ran test_upgrade_path and test_advanced_reboot on this branch. The feature in general has also been tested thoroughly on master.
=> Port consistency checker to 202311 (f2cadae6)

tests/fdb/test_fdb_mac_learning.py
Summary:
Two improvements:
1. ensure the `testARPCompleted` cleanup the ptf/dut ip if the test fails.
2. use `reload` to restore the DUT.
Run on dualtor/t0 testbed and pass.
=> [testARPCompleted] Cleanup ptf ip after test failure

tests/common/helpers/tacacs/tacacs_helper.py
PR11614 adds two new sets of credentials to the tacplus authentication config, "duthost_admin_user" and "ansible_ssh_user", however in our testbed set-up, these are both the DUT admin user, causing problems due to duplicate tacplus config.  The observed behavior is as described in https://github.com/sonic-net/sonic-mgmt/issues/13708
This PR adds a check for whether ansible_ssh_user is the same as duthost_admin_user, preventing duplicate config.
Summary:
Fixes #13708
Investigating the cause of sonic-mgmt tacacs test fails on 202405, determined it was caused by duplicate user entry in tacplus config.
After this change, all the tacacs sonic-mgmt tests pass for us in 202405.
=> Fix duplicate entry of admin user in the tacacs config

tests/qos/files/qos_params.gb.yaml
Summary:
Fixes the failure of qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark for long->short.
Recently a change went into the cisco-8000 platform that reduces the PFC threshold for long links. We need to reduce the values in qos parameters for this combination as well.
In rx cgm profile, SQ drop if SQ occupancy > 115MB (PFC pause threshold 25MB + headroom size 90MB).
Before change:
Headroom drop is triggered at 14724 packets. There is 2 buffers padding in PFC pause threshold, and 2 buffers padding in headroom drop threshold. The number of packets to trigger rx drop is:
```
>>> 115*1024**2/8192+2+2
14724.0 
```
After change:
SQ drop is triggered at 14722 packets. There is 2 buffers padding in SQ drop threshold. The number of packets to trigger rx drop is:
```
>>> …
```
=> T2:Qos-Sai:Pg shared wm lossless

ansible/library/exabgp.py
Add topo fails with exabgp error during startup. Failing due to usage error. Fixed by specifying long name for environment file.
Summary:
Fix add topo failure with exabgp v4
Fixed by specifying long name for environment file.
Ran add-topo locally.
NA
NA
NA
=> Fix exabgp v4 error during startup

tests/common/dualtor/data_plane_utils.py, tests/common/dualtor/dual_tor_io.py, tests/dualtor_io/test_link_failure.py
Reverts sonic-net/sonic-mgmt#17970
=> Revert "[action] [PR:17909] [dualtor_io] Allow duplications for link down downstream I/O"

ansible/roles/sonic/tasks/vsonic.yml
cEOS peers advertises loopback routes as /128, so vSonic should as well when used as the peer.  This was causing test failures in things such as snmp/test_snmp_loopback.py when using a vSonic peer instead of cEOS.  It was instead receiving multiple /64 routes since each peer has a loopback address using a /128 that is technically in the same /64 range, so there was no guarantee the packets would be shipped off to the right peer.
The DUT is unchanged.
Summary: vSonic peer ipv6 loopback routes need to be /128 to mimic cEOS
Fixes https://github.com/sonic-net/sonic-mgmt/issues/18102
Failures when using vSonic instead of cEOS for the peers
Added `bgp_adv_lo_prefix_as_128=true` to the vsonic peer configuration.
By running `snmp/test_snmp_loopback.py` and observing the ipv6 tests now pass. …
=> vSonic peer ipv6 loopback routes need to be /128

tests/common/devices/sonic.py
1.Update speed advertise command for sonic fanout switch 
2.Use state db to get port speed
Summary:
1. Command "config interface advertised-speeds Ethernet0 None" is not supported on sonic fanout switch.
2. Port speed in APPL_DB is not reliable after autoneg operation.
1. Command "config interface advertised-speeds Ethernet0 None" is not supported on sonic fanout switch.
2. Port speed in APPL_DB is not reliable after autoneg operation.
1. Update the comand "config interface advertised-speeds Ethernet0 None" to "config interface advertised-speeds Ethernet0 all".
2. Use STATE_DB to get port speed after autoneg operation.
Run it in internal testbed
=> Update sonic port configure and check method

tests/fib/test_fib.py
The port toggle method of case test_basic_fib and test_hash could not work on dualtor active active setup 
Enhance it on dualtor active active testbed
Summary:
The port toggle method of case test_basic_fib and test_hash could not work on dualtor active active setup 
Enhance it on dualtor active active testbed
=> Enhance the fib test to run on dualtor active active setup

ansible/library/announce_routes.py, tests/stress/test_stress_routes.py
stress/test_stress_routes.py is flaky in T2 testing because ofhttps://github.com/sonic-net/sonic-mgmt/issues/16541. Only announce and withdraw a small amount of routes in T2 testing to make it robust.
Summary:
=> Make stress/test_stress_routes.py robust in T2 testing

tests/common/reboot.py
Summary:
test_pfcwd_basic_single_lossless_prio_reboot failed due to dshell initialization.
Fix the failures caused by dshell initialization.
If cisco-8000, wait dshell ready after reboot.
Tested it on T2 testbed.
```
23:44:54 base._run                                L0108 DEBUG  | /data/tests/common/devices/multi_asic.py::_run_on_asics#136: [yy39top-lc4] AnsibleModule::command Result => {"changed": true, "stdout": "PFC support is enabled on the device\nSQG counters:\n   SQG 0: 0          (0x0)\n   SQG 1: 0          (0x0)\n   SQG 2: 0          (0x0)\n   SQG 3: 0          (0x0)\n\nTC counters (global):\n   CTC 0: 0          (0x0)\n   CTC 1: 0          (0x0)\n   CTC 2: 0          (0x0)\n   CTC 3: 0          (0x0)\n   CTC 4: 0          (0x0)\n   CTC 5: 0          (0x0)\n   CTC …
```
=> MIGSMSFT-965 [T2] failures in test_pfcwd_basic_with_snappi.py reboot cases

tests/common/snappi_tests/snappi_fixtures.py, tests/gnmi/test_gnoi_system_grpc.py, tests/snappi_tests/bgp/files/bgp_convergence_helper.py, tests/snappi_tests/bgp/files/bgp_test_gap_helper.py, tests/snappi_tests/bgp/test_bgp_convergence_performance.py, tests/snappi_tests/bgp/test_bgp_local_link_failover.py, tests/snappi_tests/bgp/test_bgp_remote_link_failover.py, tests/snappi_tests/bgp/test_bgp_rib_in_capacity.py, tests/snappi_tests/bgp/test_bgp_rib_in_convergence.py, tests/snappi_tests/bgp/test_bgp_scalability.py
Summary: Updating the BGP convergence cases to accomodate latest Snappi Api Model
The snappi_convergence library has been replaced to snappi_api
To update the scripts for latest snappi models
Removed snappi_convergence apis and replaced with snappi_api apis
Tested on Edgecore DUT
------------------------------------------------------------------------------------------------ live log call -------------------------------------------------------------------------------------------------
20:12:31 bgp_convergence_helper.duthost_bgp_confi L0222 INFO   | Removing configured IP and IPv6 Address from Ethernet64
20:12:33 bgp_convergence_helper.duthost_bgp_confi L0222 INFO   | Removing configured IP and IPv6 Address from Ethernet68
20:12:35 bgp_convergence_helper.duthost_bgp_confi …
=> Updating the BGP convergence cases to latest Snappi Api Model instead of Snappi_convergence module

tests/pfcwd/cisco/default_pfc_time.py, tests/pfcwd/cisco/set_pfc_time.py
Summary:
The pfc-512bit script was working in previous builds, but fails in later builds. It started giving the unknown variable error. This is because the later images have stopped the auto-import of the variables used in the scripts.
Pls see description.
Added the new import in the scripts.
Ran the failing test on T2 TB:
```
====================================================================================================================== warnings summary ======================================================================================================================
../../usr/local/lib/python3.8/dist-packages/paramiko/transport.py:236
/usr/local/lib/python3.8/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
"class": …
```
=> cisco-8000:pfcwd:512bit script needs imports now, since the DUT is not auto-importing them anymore.

tests/acl/test_acl.py
Summary:
test_acl.py has a high chance to fail on Cisco chassis.
It's a flakiness failure, add extra sleeping time to wait for the routes to be programmed.
test_acl.py has a high chance to fail on Cisco chassis.
It's a flakiness failure, add extra sleeping time to wait for the routes to be programmed.
Add extra sleeping time to wait for the routes to be programmed.
Test on physical testbeds and it stables passes.
=> [Cisco chassis] Add extra sleep after reboot to fix the flakiness failure

tests/common/snappi_tests/traffic_generation.py
Summary:
Following tests were failing on Gr2:
snappi_tests.pfc.test_pfc_pause_lossy_with_snappi#test_pfc_pause_single_lossy_prio::test_pfc_pause_single_lossy_prio
Error:
Failed: PFC pause frames should be received and counted in RX PFC counters for priority 2
Ran the test with changes and test passed
Only for cisco-8000
=> Check for Gr2 in single lossy priority case

tests/snappi_tests/pfc/test_pfc_mixed_speed.py, tests/snappi_tests/pfc/test_pfc_no_congestion_throughput.py, tests/snappi_tests/pfc/test_pfc_port_congestion.py, tests/snappi_tests/pfcwd/test_pfcwd_actions.py, tests/snappi_tests/pfcwd/test_pfcwd_mixed_speed.py, tests/snappi_tests/test_multidut_snappi.py
These tests were failing with FixureLookUpError
snappi_tests.pfc.test_pfc_no_congestion_throughput#test_single_lossless_prio
snappi_tests.pfc.test_pfc_no_congestion_throughput#test_multiple_prio_uni_dist
snappi_tests.pfc.test_pfc_no_congestion_throughput#test_multiple_prio_diff_dist
snappi_tests.pfc.test_pfc_mixed_speed#test_mixed_speed_no_congestion
snappi_tests.pfc.test_pfc_mixed_speed#test_mixed_speed_uni_dist_over
snappi_tests.pfc.test_pfc_mixed_speed#test_mixed_speed_diff_dist_over
snappi_tests.pfcwd.test_pfcwd_mixed_speed#test_mixed_speed_pfcwd_disable
snappi_tests.pfcwd.test_pfcwd_mixed_speed#test_mixed_speed_pfcwd_enable
snappi_tests.pfcwd.test_pfcwd_actions.py (all tests)
snappi_tests.test_multidut_snappi#test_snappi
file /data/tests/snappi_tests/pfc/test_pfc_mixed_speed.py, line …
=> fixing FixtureLookUp Error

tests/hash/test_generic_hash.py
Summary:
During the run of `test_reboot` we are randomly generating `reboot_type` which can be one of following values `'cold', 'warm', 'fast', 'reload'` and in the test we are checking if `reboot_type ` is one of that values
`if reboot_type in ['cold', 'reload', 'warm']:`
But there are missing check for 'fast'` 
And as a result we are not saving config  before reboot if reboot type is `fast ` and because of that 
`ecmp hash fields` and `lag hash fields` are empty
Failed test hash/test_generic_hash.py
Added 'fast' reboot type check in order to save config for this type of reboot
Run test in testbed
=> Bug: hash/test_generic_hash.py "Failed: The global hash configuration is not as expected:"

tests/bgp/conftest.py
Summary:
Fix test_bgp_update_timer on M1 topo
Fix test_bgp_update_timer on M1 topo
Verified on Arista-7050CX3 M1-48 testbed.
```
bgp/test_bgp_update_timer.py::test_bgp_update_timer_single_route[bjw2-can-7050-5-default] PASSED                      [ 50%]
bgp/test_bgp_update_timer.py::test_bgp_update_timer_session_down[bjw2-can-7050-5-default] PASSED                      [100%]
========================================= 2 passed, 1 warning in 834.24s (0:13:54) ==========================================
```
=> [M1] Fix test_bgp_update_timer on M1 topo

.azure-pipelines/run-test-elastictest-template.yml, azure-pipelines.yml
The PR removes pipeline job that was introduced to run pilot rollout of Python 3 only docker-ptf image as the rollout is now complete.
Summary:
The docker-ptf:latest now uses Python 3 only image. The code that was used to test pilot rollout of this feature is no longer needed.
Remove job and related references from the pipeline.
N/A
No
N/A
N/A
=> Remove docker-ptf py3only tag based pilot rollout code

tests/generic_config_updater/templates/create_forward_rules_same_priority.j2, tests/generic_config_updater/test_dynamic_acl.py
Summary:
Adds in a test where we have multiple forward rules with the same priority, and confirms that packets are still forwarded/dropped appropriately when this is the case
Confirm that we can have ACLs where rules share priorities
Added a new test case
Tested on a sample T0 testbed
T0
=> Add new test to test_dynamic_acl to confirm that ACLs work appropriately if rules share priorities

tests/common/helpers/tacacs/tacacs_helper.py
Improve ssh_remote_run_retry method stability by increase retry times.
test_ro_user_ipv6_only failed, according to test log, TACACS server on ptf docker crashed when receive TACACS authorization request.
The crash issue is a known issue and currently the only solution is retry.
- Microsoft ADO: 32312956
In ssh_remote_run_retry method, increase to retry 6 times.
Improve ssh_remote_run_retry method stability by increase retry times.
=> Improve ssh_remote_run_retry method stability by increase retry times.

tests/srv6/test_srv6_dataplane.py
Summary: Previously, the test case verified the dropping of 100 packets one-by-one, which was very slow. Now, we changed it to send 100 packets in a single batch and then verified the no-receiving behavior. Besides, there was a parsing error regarding the counter value when the platform is a mellanox device. I forgot to convert str to int before calculating the counter values.
=> Fix parsing error and speedup testing in test_srv6_no_sid_blackhole

tests/gnmi/helper.py, tests/gnmi/test_gnmi_configdb.py
Summary:
Fixes # 17885
Add a test case to gnmi/test_gnmi_configdb.py to test sending a full configuration file using SET-REPLACE in order to trigger a call to GCU's 'config replace' on the device.
This tests the codepath introduced [here](https://github.com/sonic-net/sonic-gnmi/pull/369).
To support the changes to sonic-gnmi proposed [here](https://github.com/sonic-net/sonic-gnmi/pull/369)
Add a new test case following the existing testcase that tests a full config reload (test_gnmi_configdb_full_01).
With the changes made to sonic-gnmi to use ConfigReplace for a full config update, the current test fails. This version passes with those changes.
Supports all testbeds supported by the test as a whole.
=> Issue #17885: Add SET-REPLACE full config test to gnmi/test_gnmi_configdb.py

tests/snappi_tests/pfc/test_pfc_mixed_speed.py, tests/snappi_tests/pfcwd/test_pfcwd_mixed_speed.py
Summary:
Some of the mixed speed test should use multidut_port_info, otherwise it will not be parameterised properly
Fixes # (issue) 32678097
=> chore: fix parameterise mixed speed

tests/gnmi/conftest.py, tests/gnmi/helper.py
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/18203
Issue : GNMI test cases fails if NTP is not configured prior to running suite
Root cause : GNMI suite has dependency on NTP, but it doesn't setup ntp before running gnmi cases
Fix : Ensure NTP client & server configuration are done for gnmi cases
GNMI test cases fails if NTP is not configured prior to running suite
Ensure NTP client & server configuration are done for gnmi cases
Run all GNMI & NTP test cases
NA
NA
NA
=> Changes to setup NTP before executing gnmi suite

tests/tacacs/test_accounting.py, tests/tacacs/utils.py
Summary:
[TACACS] Fix auditd TACACS config re-init check failed issue.
- Microsoft ADO: 32621325
- [] 202411
TACACS test case failed because change_and_wait_aaa_config_update failed
The issue introduced by [this PR](https://github.com/sonic-net/sonic-mgmt/pull/16723/files) when fix bug https://github.com/sonic-net/sonic-mgmt/issues/16709
The code in PR #16723 check timestamp count, however there is a case some older log will lost in the "sudo journalctl -u auditd --boot --no-pager" command, which will cause older log count bigger than newer log count.
Add a 2seconds delay before change AAA config, so the latest config re-init timestamp will not have same timestamp with last one.
Pass all test case
=> [TACACS] Fix auditd TACACS config re-init check failed issue.

tests/bgp/test_ipv6_bgp_scale.py
Summary:
The device unisolation test will restart all ports on DUT, after all bgp routes were stable in FRR after ports restart, however, the routes may not stable in ASIC, so the member scale test will be affected. To avoid this, move the device unisolation test to the last.
The device unisolation test will restart all ports on DUT, after all bgp routes were stable in FRR after ports restart, however, the routes may not stable in ASIC, so the member scale test will be affected.
To avoid this, move the device unisolation test to the last.
Run test on DUT
=> [bgp-scale-test] reorder test cases to avoid device unisolation test effect other tests

tests/tacacs/test_authorization.py
[TACACS] Add test case to verify per-command authorization send correct remote address to TACACS server.
Add test case for PR: https://github.com/sonic-net/sonic-buildimage/pull/22327#issuecomment-2811338514
- Microsoft ADO: 32291587
Add new PR to verify per-command authorization send correct remote address to TACACS server
[TACACS] Add test case to verify per-command authorization send correct remote address to TACACS server.
=> [TACACS] Add test case to verify per-command authorization send correct remote address to TACACS server.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
`macsec/test_interop_protocol.py::TestInteropProtocol::test_snmp` test has high failure rate and is blocking PR test
Skip `macsec/test_interop_protocol.py::TestInteropProtocol::test_snmp` with https://github.com/sonic-net/sonic-mgmt/issues/18273 to unblock
=> Skip macsec/test_interop_protocol.py::TestInteropProtocol::test_snmp to unblock PR test

ansible/roles/test/templates/fib.j2
Summary:
Remove interfaces 0, 1 from fib.j2 for t0-118 as they are not uplinks
=> Fix t0-118 fib.j2 test configs

ansible/roles/vm_set/tasks/main.yml
Summary: 
Increase our VM threshold to support deploy large scale vms.
Fixes # (issue) 32767670
Without this change, ceos VM will abnormally terminate ProcMgr.service which led to BGP down. During this time I noticed dmesg
```
[4351605.348948] neighbour: ndisc_cache: neighbor table overflow!
[4352518.918103] neighbour: ndisc_cache: neighbor table overflow!
[4353433.024687] neighbour: ndisc_cache: neighbor table overflow!
[4353433.024717] neighbour: ndisc_cache: neighbor table overflow!
[4353737.315904] neighbour: ndisc_cache: neighbor table overflow!
```
Which indicate the neighbor arp cache table be out of entry. Adjusting here make the VM more stable on large scale.
=> chore: increase vm threshold

tests/bgp/test_seq_idf_isolation.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
This PR skips modular chassis specific tests on disaggregated chassis
Modular chassis specific tests that involve triggers on supervisor are not applicable to disaggregated chassis.
Add skip conditions for BGP tsa-tsb-services tests that are specific to modular chassis with a supervisor
Verified that the tests are skipped on disaggregated chassis
=> Skip T2 tests not applicable to disaggregated chassis

tests/arp/test_neighbor_mac_noptf.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
In testNeighborMacNoPtf test the bgp is disabled and checks that there are no routes installed by BGP in ASIC_DB
by filtering out all local routes installed on testbed. For voq chassis, this collection of local routes was not including voq inband routes which mislead the correct summation of local routes on voq chassis.
Summary:
Added the voq inband ip routes in summation of all local routes
Test case failure for  single_dut_multi_asic chasiss
=> Considering voq inband routes in local route count for  testNeighborMacNoPtf

.azure-pipelines/baseline_test/baseline.test.template.yml
Summary:
We were using Azure DevOps pipeline job timeout to set max execution time in baseline test jobs, so once baseline test exceed timeout, test plans will be cancelled by Azure DevOps pipeline and we will get the error code "TEST_PLAN_CANCELLED", and we won't be able to distinguish whether the test plan is cancelled by timeout or other reasons.
Use Elastictest timeout MAX_RUN_TEST_MINUTES to set max execution time in baseline test plans, and update test job timeout longer than Elastictest timeout, so once baseline test exceed timeout, test plans will be cancelled by Elastictest and we will get different error code.
=> Update baseline test plan max execution time and test job timeout

tests/common/snappi_tests/snappi_fixtures.py, tests/snappi_tests/ecn/files/ecnhelper.py, tests/snappi_tests/ecn/test_dequeue_ecn_with_snappi.py, tests/snappi_tests/ecn/test_ecn_marking_cisco8000.py, tests/snappi_tests/ecn/test_red_accuracy_with_snappi.py
Static route changes for single asic DUT and Cisco specific ECN test changes
For ECN tests static routes were added recently for multi DUT in this PR https://github.com/sonic-net/sonic-mgmt/pull/17012, 
this PR enables the same for Single ASIC DUT's and Cisco specific ECN test changes.
- [ X] Bug fix
- [ X] Test case improvement
- [X ] 202411
Hitting failures in multiple tests due to traffic taking default voq (due to the connected routes).
Adding static route in case of Sinlge DUT as well.
Tested all ECN tests on M64 platform.
==================================== PASSES ====================================
[32m[1m______________ test_ecn_multi_lossless_prio[multidut_port_info0] _______________[0m
[32m[1m_ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info0-test_ecn_config0] …
=> Static Route and Cisco ECN test changes

tests/snappi_tests/test_snappi.py
Summary:
tests/snappi_tests/test_snappi.py is failing when we use the non-default queue mapping in variables.py. This is because it uses the priority as the queue id.
In this PR we change the code to use the correct queue_id from the variables.py.
The failure of test_snappi.py for non default queue mapping.
Pls see description.
Ran it in T2 testbed:
=> Snappi: Add the correct queue to select for test_snappi

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Reverts sonic-net/sonic-mgmt#17594
=> Revert "Temporarily skipping few testcases in platform_tests/api/test_thermal.py and test_thermal_state_db.py for cisco devices"

ansible/group_vars/lab/secrets.yml, tests/common/connections/terminate_serial_connection.py, tests/conftest.py
Summary:
Add a logic to terminate occupied serial connection for Cisco environment and a placeholder for other SONiC vendors.
Add logic to terminate occupied serial connection.
In case when some developer forget to exit the telnet this logic will kill existing telnet session.
Add a function `terminate_occupied_serial_connection` and provide a `Cisco-specific` implementation.
This function serves as a placeholder for other SONiC vendors to add their own implementations. Different vendors may use different methods for terminating serial connections, such as Telnet, Minicom, etc.
1. Establish serial connection with a DUT.
2. Run the `dut_console/test_escape_character.py` test
=> [cisco] [dut_console] [serial] Add a logic to terminate occupied serial connection.

tests/common/snappi_tests/snappi_fixtures.py
When the number if snappi ports used in the test and number of l3 interfaces or number of Vlan members configured on DUT are not same it was failing to generate the snappi configuration and was failing in
https://wwwin-github.cisco.com/whitebox/sonic-test/blob/343dc8e4dfb9d6137e6ff09cc9a9a1b516e76daf/sonic-mgmt/tests/common/snappi_tests/snappi_fixtures.py#L152
OR
https://wwwin-github.cisco.com/whitebox/sonic-test/blob/343dc8e4dfb9d6137e6ff09cc9a9a1b516e76daf/sonic-mgmt/tests/common/snappi_tests/snappi_fixtures.py#L233
Summary:
Fixes the error seen and generates the Snappi configuration accordingly.
- [X ] 202411
Tests were failing 
Added the fix to handle the scenario
Manually ran the test with changes and verified it passes
No
No
=> Fixing the error seen while generating Snappi configuration for L3 interfaces and Vlan interfaces

tests/snappi_tests/files/helper.py, tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
In tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py, we have reboot testcases.
We disable the PFCWD and Credit-WD in the testcase and reboot the the DUT depending upon type of reboot. However, on cold-reboot, the Credit-WD is getting reset back.
This causes the lossless test flows on IXIA to continuously send traffic despite of the pause-storm. The run_traffic in traffic_generation.py is trying to determine if the test stops within a stipulated duration, which it does not and throws an assert that flows have not stopped within the given time duration and attempts.
Summary:
#18082 
The reboot_dut was called after the PFCWD and Credit-WD disable. The reboot caused the Credit-WD to reset back and hence test failed.
Created a single fixture called …
=> [snappi]: Changed order of reboot and pfcwd_disable for reboot cases in pfc_pause_lossless test

tests/vxlan/test_vnet_bgp_route_precedence.py
Summary:
Fixes #18291 
Fix bug, and let code run by design.
Adjust the check condition for if there is portchannel.
Verified by running local test on testbed with no portchannel, and was erroring out before the fix.
=> Fix Skip tests if no portchannels are found in prepare_test_port fixture

tests/acl/test_acl.py
If we have a T2 topology with ports in the same namespace connecting to both upstream and downstream ports we'll end up excluding them from the ACL.
E.G.
```
> show acl table
Name                    Type       Binding          Description             Stage    Status
----------------------  ---------  ---------------  ----------------------  -------  --------
DATA_INGRESS_IPV4_TEST  L3         Ethernet32       DATA_INGRESS_IPV4_TEST  ingress  Active
PortChannel2001
PortChannel2003
PortChannel2004
```
But we can see it excluded Ethernet248 (which is connected to a downstream port):
```
Interface                            Lanes    Speed    MTU    FEC         Alias             Vlan    Oper    Admin
-----------  -------------------------------  -------  -----  -----  ------------ …
```
=> [T2][ACL-test] Allow upstream and downstream rifs in the same namespace

tests/stress/test_stress_routes.py
Without this change `stress/test_stress_routes.py` will fail on multi-asic systems with:
```
E           tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
E           rc = 1
E           cmd = vtysh -c "show memory bgpd"
E           start = 2025-04-27 06:02:20.869391
E           end = 2025-04-27 06:02:20.882943
E           delta = 0:00:00.013552
E           msg = non-zero return code
E           invocation = {'module_args': {'_raw_params': 'vtysh -c "show memory bgpd"', '_uses_shell': True, 'warn': False, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'chdir': None, 'executable': None, 'creates': None, 'removes': None, 'stdin': None}}
E           _ansible_no_log = None
E …
```
=> Handle multi-asic systems in `get_frr_daemon_memory_usage`

tests/scripts/dual_tor_sniffer.py
Summary:
On scapy with version v2.40 and under, the sniffer will capture packets on every interface if no interface is given.
On scapy with version v.2.50 and higher, the sniffer will capture packets on `conf.iface` if no interface is given; on the ptf, `conf.iface` is `mgmt`, so `dual_tor_sniffer` is not able to capture any meaningful dataplane packets.
https://github.com/secdev/scapy/pull/1420
Let `dual_tor_sniffer` explicitly sniff on dataplane ports (any ptf ports starting with `eth`)
Run dualtor I/O testcase.
=> [dualtor][sniffer] Explicitly set listen ports

tests/gnmi/test_gnmi_configdb.py
Summary:
Microsoft ADO: 32456075
The BGP sessions are idle after test_gnmi_configdb, and then bgp related test failed.
Check bgp status after test_gnmi_configdb to make sure bgp sessions are recovered.
=> Check bgp status for gnmi test

tests/common/helpers/ptf_tests_helper.py
Summary: The upstream_links fixture assumes that BGP neighbors are always using IPv4 addresses which is false for IPv6 only topology. This PR initializes two variables to prevent unbound variable error in the upstream_links fixture setup.
=> Initialize two variables to prevent unbound variable error in upstream_links fixture

tests/dash/proto_utils.py
Fix the prefix_to_ipv4 to return a prefix made of decimal values and not hex values
=> fix the prefix_to_ipv4 to return decimal format address

ansible/templates/minigraph_dpg.j2
Summary: Change the current logic for portchannel naming to only apply for multi-asics. For topology that requires more than 100 lags, if we use `PortChannel10x` as the prefix we will get more than 16 characters which will violate the linux interface naming convention (only less than 15 characters)
Fixes # (issue) 32562998
Only apply `PortChannel10` if num_asics > 1, otherwise we stick with standard `PortChannel` to restrict the change to multi-asics
=> chore: change portchannel naming

tests/kubesonic/test_k8s_join_disjoin.py
Summary:
Fixes #18277
We noticed `kubesonic/test_k8s_join_disjoin.py` was causing failures in `cacl/test_cacl_application.py` as teardown didn't set `iptables`/`ip6tables` to original state.
Save `iptables`/`ip6tables` config before the test, then restore it after the test
Ensure that `iptables`/`ip6tables` was the same before and after test, and it doesn't cause failures in `cacl/test_cacl_application.py` when run after
N/A
N/A
=> Ensure iptables is restored to original state in kubesonic test

tests/wol/test_wol.py
Currently test allows very little difference in the time to receive packets, which create many false errors. Increase the error margin to reduce those.
Summary:
Current error margin is too small
Increase error margin
Run wol test
=> [wol] increase acceptable error margin on time

ansible/plugins/connection/multi_passwd_ssh.py
When running a command through the plugin multi_passwd_ssh, it will try every password, and at the end, the password will be reset to the original password. If ipv4 fails, the connection error will be caught, and switch to using ipv6, and it will stick to using ipv6 for all future connections. This change will switch back to trying ipv4, if ipv6 fails. Sometimes we have ipv4 and ipv6 recorded in inventory for a device but only one of them (typically ipv4) is configured (like when the mgmt interface is configured manually), the previous behavior is multi_passwd_ssh will always fail if an ipv4 connection ever fails, like during a reboot, or waiting for some breaking network changes.
Summary:
When ipv4 fails, the multi_passwd_ssh switches to using ipv6. We would want it to …
=> [multi_passwd_ssh] switch ipv6 back to ipv4 when failed

tests/bgp/test_bgp_session.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Skip following cases due to warm reboot is not supported on Arista-7050CX3-32S-C28S4 with t0-d18u8s4 topology:
- platform_tests/test_reboot.py::test_warm_reboot -> conditional mark
- bgp/test_bgp_slb.py::test_bgp_slb_neighbor_persistence_across_advanced_reboot -> conditional mark
=> Skip warm reboot related case on Arista-7050CX3-32S-C28S4

ansible/library/generate_golden_config_db.py
Summary:
This PR is to update [ansible/library/generate_golden_config_db.py](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:golden_config_fec?expand=1#diff-14615f70e25f270530ef358a27e43c8497c14381923d7bfe1d15b6c1cdd6afa7) to support generating golden_config for topo ft2-64 to enable FEC.
It has to be done because `minigraph.py` doesn't support generating AN config for Non-100Gb ports. 
https://github.com/sonic-net/sonic-buildimage/blob/8fa62b5c03414940d1c74ba99e20472c4a4a243b/src/sonic-config-engine/minigraph.py#L2432
This PR is to update [ansible/library/generate_golden_config_db.py](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:golden_config_fec?expand=1#diff-14615f70e25f270530ef358a27e43c8497c14381923d7bfe1d15b6c1cdd6afa7) to support …
=> Support generating golden_config for topo ft2-64

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
This is the manual cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/17527 to 202411.
=> [202411][Mellanox] Skip the fib nvgre hash test on SPC1 with t1-lag topology

ansible/roles/vm_set/library/vm_topology.py
Summary:
This PR is to use `ip link` instead of `ifconfig -a` to speed up `add-topo`.
**Time cost of `ifconfig -a`** - Around 10 seconds
```
$ /usr/bin/time ifconfig -a | grep -E br-VM41177-[0-9]+ 
br-VM41177-0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9216
br-VM41177-1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9216
br-VM41177-2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9216
br-VM41177-3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9216
3.52user 6.17system 0:09.77elapsed 99%CPU (0avgtext+0avgdata 6100maxresident)k
0inputs+0outputs (0major+1028minor)pagefaults 0swaps
```
**Time cost of `ip link`** - Less than 1 second
```
/usr/bin/time ip link | grep -E br-VM41177-[0-9]+
74966: br-VM41177-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9216 qdisc noqueue state UNKNOWN …
```
=> Use ip link instead of ifconfig to speed up

tests/common/plugins/sanity_check/__init__.py
Summary:
This PR is to skip `check_bfd_up_count` and `check_mac_entry_count` from `sanity_check` list for topo `lt2` and `ft2`.
This PR is to skip `check_bfd_up_count` and `check_mac_entry_count` from `sanity_check` list for topo `lt2` and `ft2`.
Check topo name and remove `check_bfd_up_count` and `check_mac_entry_count` from `sanity_check` list.
No.
=> Skip bfd and mac check on LT2/FT2

tests/show_techsupport/tech_support_cmds.py
PR [#3865](https://github.com/sonic-net/sonic-utilities/pull/3865) updated the `generate_dump` script to run the `show queue counters` command only in the host namespace, instead of for each ASIC namespace.
As a result, the test case in `show_techsupport/test_techsupport.py`, which was verifying that the command ran for each ASIC namespace failed.
This PR modifies the testcase to align with the new behavior.
Fixes [ #18364](https://github.com/sonic-net/sonic-mgmt/issues/18364)
Removed `{}` from `{} show queue counters` in `misc_show_cmds`, which is used to generate `commands_to_check`, to prevent per-ASIC expansion and check only the host namespace.
run `show_techsupport/test_techsupport.py`
=> [show_techsupport] Remove asic dependency for show queue counters

tests/vrf/test_vrf.py, tests/vrf/vrf_config_db.j2, tests/vrf/vrf_neigh.j2
fixes: https://github.com/sonic-net/sonic-mgmt/issues/18355
Fix multiple issues in test_vrf.py:
- 1. Use integer division for python 3 compatibility
- 2. Use items instead of iteritems in vrf_neigh.j2 for python 3 compabibility
- 3. Wait for interface to be bound to vrf, instead of immediately asserting
- 4. In Python 3, tempfile.NamedTemporaryFile() defaults to binary mode (mode='w+b'), whereas the test is opening it in text mode. Opening it explicitly in text mode for python3 compatibility using
`with tempfile.NamedTemporaryFile(mode='w+', encoding='utf-8', delete=False)`
- 5. Test is using a hack to configure a bgp router so that bgp port can be opened. However in most cases bgp router config is already present, which causes the config to fail. Get the bgp asn from tbinfo and use that …
=> Fixing multiple issues in test_vrf.py

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
GNMI ZMQ has an issue in isolated topology, but fixing it is not a priority because it isn't used in isolated topology. So, just skip this test.
Add a condition in the skip file
Check locally
=> [tests_mark_conditions.yaml]: Skip GNMI/ZMQ test for isolated topology

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/pc/test_lag_member.py
Summary:
Fixes #13898
I'm suspecting that something in the ping code and the timeouts is causing random intermittent failures in test_lag_traffic, in the form of the ARP entry not getting populated.
Try to make it more reliable by getting rid of the `timeout` wrapper around the call and let ping's `-w` flag effectively act as a timeout. Also, send 5 ping packets at once, just to avoid potential missed packets.
Also, enable this test case on VS/KVM by commenting out the ARP check for the portchannel interface entry.
Tested on KVM and physical device
=> Try to fix/make more reliable test_lag_traffic

tests/acl/test_acl.py
Summary:
Fixes #18320 
Fix all tests in `acl/test_acl.py` for t1-isolated-d28/128.
We modify the ACL test configuration by splitting the downlinks into two groups (odd and even port indices) and run the ACL tests between these two groups.
Tested on t1-isolated-d28 and t1-isolated-d128
=> Fix ACL tests for t1-isolated-d28/128

tests/platform_tests/link_flap/link_flap_utils.py, tests/platform_tests/link_flap/test_cont_link_flap.py, tests/platform_tests/link_flap/test_link_flap.py
check_orch_cpu_utilization and radis memory issue has been fixed by https://github.com/sonic-net/sonic-mgmt/pull/15732. It is found that in scaling test bed this test could sometimes still fail. Need to adjust the wait time to be longer for check_orch_cpu_utilization and also the memory threshold need to be adjusted a little bit bigger. (from 10% to 15% for m2). 
Summary:
Fix test failure
Test is not failing anymore with the fix on scaling test bed.
=> Fix: Adjust wait time for check_orch_cpu_utilization and threshold for validate_redis_memory_increase

ansible/roles/test/files/ptftests/py3/advanced-reboot.py, tests/common/fixtures/advanced_reboot.py, tests/conftest.py
Summary:
Add an argument for the advanced_reboot PTF test to set the LACP multiplier for ceos neighbors.
Can be set when running `run.sh` via `-e` (extra parameters).
i.e.:
```
-e "--ceos_neighbor_lacp_multiplier=5"
```
Requested here:
https://github.com/sonic-net/sonic-mgmt/pull/17964#issuecomment-2837412391
To be able to have different LACP multipliers when running tests on different platforms.
Mirror `--neighbor_type` param changes.
Tested with a Arista 7050-CX3 with and without the parameter. Can observe that the LACP multiplier is properly set on the ceos neighbors when parameter is given, and see that there are no changes when the parameter is not set.
Tested wtih:
```
sudo ./run_tests.sh -n ardut -u -x -c 'upgrade_path/test_upgrade_path.py::test_upgrade_path' -e …
```
=> Add PTF test parameter for ceos neighbor lacp multiplier

tests/common/dualtor/data_plane_utils.py, tests/common/dualtor/dual_tor_io.py, tests/dualtor_io/test_link_failure.py
Summary:
SONiC on MLNX/Cisco will flood downstream packets if the link is down due to the fdb flush.
The following two testcases will report duplications or two disruptions when running on MLNX/Cisco.
`test_active_link_down_downstream_active`
`test_active_link_down_downstream_active_soc`
Actually, the flooding is an expected behavior on those two platforms, so we need to adjust the dualtor I/O verification to allow this.
1. Allow the duplications on MLNX/Cisco.
2. Merge the duplications with disruptions on MLNX/Cisco to reassemble the true disruptions.
```
dualtor_io/test_link_failure.py::test_active_link_down_downstream_active_soc[active-active] PASSED …
```
=> [dualtor io] Allow link down duplications on MLNX/Cisco

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
This test was being skipped due to a https://github.com/sonic-net/sonic-mgmt/issues/13804 The issue as https://github.com/sonic-net/sonic-mgmt/pull/11441, but the test was never re-enabled.
Fixes #18352
Increase test coverage by re-enabling test.
Removed conditional skip clause.
Ran the test with the clause removed and it passed.
=> Issue #18352: Stop skipping test/test_pktgen.py (#183)

tests/bgp/test_bgp_session.py
This PR adds following updates to script `test_bgp_session.py`:
1. It adds support to run this script when frr_mgmt_framework_config is set to "true" in DEVICE_METADATA. This change includes check for the knob and if it is enabled the it adds an extra parsing step for bgp_neighbors to consider namespace key in the table.
2. The second change is to look for any BGP IPv6 neighbors. The script was looking for only 'show ip interface' output and not the 'show ipv6 interface' to populate the interface mapping.
3. Timeouts in wait_until are increased to give enough time for BGP peers to come up in scale/stress scenario. Tested scenario which needed these timeout values: T1 topology with >6k route scale per neighbor, 16 BGP neighbors with timers 3/10.
4. It is same as …
=> test_bgp_ session.py fails when DUT is running FRR unified framework

tests/bgp/test_bgp_session_flap.py
Summary:
Fixes #16883
- [ X] Bug fix
This test case fails when a sonic-mgmt topo has Sonic VM neighbors
Adds a check for instance type before determining which show command to run
Passes on T0/T1 topo
bgp/test_bgp_session_flap.py::test_bgp_single_session_flaps[usschq-nswdut-t002-None] PASSED [ 50%]
bgp/test_bgp_session_flap.py::test_bgp_multiple_session_flaps[usschq-nswdut-t002-None] PASSED [100%]
=> Adds a check for neighbor type in test_bgp_session_flap

tests/bgp/bgp_helpers.py, tests/bgp/conftest.py, tests/bgp/test_bgp_bbr.py, tests/bgp/test_bgp_peer_shutdown.py, tests/bgp/test_bgp_route_neigh_learning.py, tests/common/devices/eos.py, tests/common/devices/sonic.py, tests/stress/test_stress_routes.py
Fixes https://github.com/sonic-net/sonic-buildimage/issues/22578
The following are a set of testcase which fail when we use sonic as neighbor device.  This set of testcases use EOS as neighbor device.
List of test cases:
/tests/bgp/test_bgp_peer_shutdown.py
/tests/bgp/test_bgp_route_neigh_learning.py
/tests/bgp/test_bgp_bbr.py
The changes include some of the common and helper function update to support sonic related configuration and validaton and using these in these test cases.
Summary:
=> BGP testcases failure having sonic as neighbor device

tests/acl/test_acl.py, tests/acl/test_stress_acl.py, tests/common/dualtor/dual_tor_utils.py, tests/common/plugins/ptfadapter/README.md, tests/decap/test_subnet_decap.py, tests/dualtor/test_ipinip.py, tests/dualtor/test_tor_ecn.py, tests/everflow/test_everflow_ipv6.py, tests/everflow/test_everflow_per_interface.py, tests/everflow/test_everflow_testbed.py, tests/route/test_static_route.py
Summary:
Replace hardcoded value (0, 0) in ACL test with a dynamic selection to improve robustness across diverse topologies.
Fixes:
The hardcoded value (0, 0) does not account for scenarios where device_number or port_number is not 0, which causes failures in certain topologies. 
When running nightly tests using the t2_single_node_min topology, we encountered failures in the ACL test. The root cause was a hardcoded call to get_mac(0, 0), which assumes that a device with device_number = 0 and port_number = 0 exists. This assumption does not hold true in some topologies like t2_single_node_min.
Instead of using the hardcoded (0, 0) port index, this PR dynamically selects the first available port from the existing list of ports. This improves compatibility and prevents test failures across …
=> Fix the hardcoded interface issue in PTF

tests/container_upgrade/parameters.json
Summary:
When upgrading existing containers such as gNMI using Kubernetes, the gNMI process does not start automatically after the upgrade.
It's blocked by container_startup.py introduced by this PR: https://github.com/sonic-net/sonic-buildimage/pull/5421
Add environment variable `RUNTIME_OWNER` to skip container_startup.py.
Run container_upgrade test.
=> Update RUNTIME_OWNER to skip container_startup.py

ansible/config_sonic_basedon_testbed.yml, ansible/library/generate_golden_config_db.py
Summary:
Update default_pfcwd_status to disable for some platform which only have lossy traffic. 
Note: This PR needs the image fix https://github.com/sonic-net/sonic-utilities/pull/3880 for it to work.
Update the default pfcwd status in golden_config for lossy platform
Update the default pfcwd status in golden_config for lossy platform
Verified on physical platform.
=> disable pfcwd for lossy platforms in deploy-mg

tests/common/snappi_tests/snappi_fixtures.py, tests/snappi_tests/bgp/files/bgp_convergence_helper.py, tests/snappi_tests/bgp/files/bgp_test_gap_helper.py, tests/snappi_tests/bgp/test_bgp_convergence_performance.py, tests/snappi_tests/bgp/test_bgp_local_link_failover.py, tests/snappi_tests/bgp/test_bgp_remote_link_failover.py, tests/snappi_tests/bgp/test_bgp_rib_in_capacity.py, tests/snappi_tests/bgp/test_bgp_rib_in_convergence.py, tests/snappi_tests/bgp/test_bgp_scalability.py, tests/snappi_tests/lacp/files/lacp_dut_helper.py, tests/snappi_tests/lacp/files/lacp_physical_helper.py, tests/snappi_tests/lacp/test_add_remove_link_from_dut.py, tests/snappi_tests/lacp/test_add_remove_link_physically.py, tests/snappi_tests/lacp/test_lacp_timers_effect.py, tests/snappi_tests/reboot/files/reboot_helper.py, tests/snappi_tests/reboot/test_cold_reboot.py, tests/snappi_tests/reboot/test_fast_reboot.py, tests/snappi_tests/reboot/test_soft_reboot.py, tests/snappi_tests/reboot/test_warm_reboot.py
… of Snappi_convergence module (#18044)
Summary: Updating the BGP, Reboot and LACP   convergence cases to accomodate latest Snappi Api Model Fixes # (issue)
Type of change
The snappi_convergence library has been replaced to snappi_api
Approach
To update the scripts for latest snappi models
Removed snappi_convergence apis and replaced with snappi_api apis
Tested on Edgecore DUT
Supported testbed topology if it's a new test case? Documentation
Output
------------------------------------------------------------------------------------------------ live log call ------------------------------------------------------------------------------------------------- …
=> [202411 ] Updating the BGP, Reboot and LACP  convergence cases to latest Snappi Api Model instead of Snappi_convergence module [ PR 18044 ]

tests/common/devices/sonic.py
Summary:
Fixes Pretest failure when router-type is UpperSpineRouter and macsec is enabled. 
Fix issue where macsec is not added to default services on UpperSpineRouter. Also skip adding macsec on lowerspinerouter
Changed check for adding macsec to default services to look for type/subtype from DEVICE_METADATA in running config
Verified by running test_pretest.py::test_disable_rsyslog_rate_limit UpperSpineRouter and T2 chassis
=> Fix pretest failure on UpperSpineRouter when macsec is enabled

ansible/generate_topo.py
Summary:
Fixes the following error in generate_topo.py,  as this is a master only change. Separate this change with other topo changes which is needed in 202412 for https://github.com/sonic-net/sonic-mgmt/pull/18224
```
~/.../sonic-mgmt-fix/ansible $ ./generate_topo.py -r t1 -k isolated -t t1-isolated -c 64 -l 'c448o16-sparse'
File "./generate_topo.py", line 492, in <module>
main()
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File …
```
=> fix error in generate topo.

tests/auditd/test_auditd.py
Summary:
Bug fix addressing an incorrect auditd file deletion assertion.
Updated auditd file deletion test to use dynamically generated filenames with UUIDs for more reliable log verification.
1. static filenames are replaced with dynamic ones using uuid to create unique identifiers.
1. the test now checks log outputs for the unique UUID in both non-sudo and sudo file deletion scenarios
1. removing redundant SSH execution and hardcoded management IP usage.
There was an incorrect auditd file deletion assertion.
Checks log outputs for the unique UUID in both non-sudo and sudo file deletion scenarios
Ran test in testbed.
=> Fix Auditd File Deletion Assertion.

tests/show_techsupport/tech_support_cmds.py
The regex is enhanced to capture the logs correctly.
Test failed with error  - 
"_Failed: Commands not found for 'bgp_cmds': vtysh(\s+-Ec 'show bgp ipv4 neighbors .* advertised-routes' -Ec 'show bgp ipv4 neighbors .* routes')+; vtysh(\s+-Ec 'show bgp ipv6 neighbors .* advertised-routes' -Ec 'show bgp ipv6 neighbors .* routes')+_ "
Summary:
Test failed with error  - 
"_Failed: Commands not found for 'bgp_cmds': vtysh(\s+-Ec 'show bgp ipv4 neighbors .* advertised-routes' -Ec 'show bgp ipv4 neighbors .* routes')+; vtysh(\s+-Ec 'show bgp ipv6 neighbors .* advertised-routes' -Ec 'show bgp ipv6 neighbors .* routes')+_ "
Executed test suite and verfiy
=> Regex correction for bgp commands in show_tech_cmds.py

tests/bgp/test_bgp_peer_shutdown.py, tests/bgp/test_bgp_update_replication.py, tests/bgp/test_bgp_update_timer.py
Summary:
This PR updates the BGP neighbor type for UpperSpineRouter in bgp tests that use it
test_bgp_peer_shutdown.py fails on UpperSpineRouter
Added handling for UpperSpineRouter in bgp_peer_shutdown test and other tests where similar check is done
Run bgp/test_bgp_peer_shutdown.py on device with dut_type UpperSpineRouter
=> Update neighbor type for upperspinerouter

tests/conftest.py, tests/pfcwd/conftest.py, tests/qos/test_tunnel_qos_remap.py
Add background traffic for test_pfc_pause_extra_lossless test in script tests/qos/test_tunnel_qos_remap.py
Summary:
Bug fix for https://github.com/sonic-net/sonic-mgmt/issues/17252
Add background traffic for case test_pfc_pause_extra_lossless test in script tests/qos/test_tunnel_qos_remap.py
=> Add background traffic for test_pfc_pause_extra_lossless test

tests/crm/conftest.py, tests/crm/test_crm_available.py
Summary:
This is a new test case to verify the CRM nexthop_group threshold, which is typically set to at least 256. However, for some HWSKUs, such as 7215 and 720dt, the value is lower. This is acceptable due to their specific application scenarios, which have lower requirements for ECMP group capacity.
- [] 202405
To address the test gap related to nexthop group requirements.
To verify the total number of nexthop groups supported by the platform and ensure it meets the minimum required threshold.
Run the test case on device. 
't0', 't1', 'm0', 'mx', 'm1', 'm2', 'm3'
=> [TESTGAP] Implement new test case to check the crm nexthop_group

tests/upgrade_path/conftest.py, tests/upgrade_path/test_multi_hop_upgrade_path.py
Summary:
test_multi_hop_upgrade_path should be consistent with test_upgrade_path in allowing for test to restore device back to a given image.
Tested on arista testbed: device is restored back to given image after test completes
=> Add restore_image fixture to test_multi_hop_upgrade_path

tests/platform_tests/test_kdump.py
Summary:
Fixes #18392
Changed in 7250e code makes kernel panic on sup cards leave reboot-cause on LCs as `Heartbeat with supervisor card lost` instead of `cold`
https://github.com/sonic-net/sonic-buildimage/pull/22034
Add `Nokia-IXR7250E` to SKUs checking for `Heartbeat lost` cause rather than `cold` cause in `test_kdump.py`
TBC
7250E
N/A
N/A
=> Have Nokia-IXR7250E SKUs check for hearbeat lost with sup when Sup kernel panics

tests/common/plugins/sanity_check/checks.py
Summary:
To improve the speed of mux state recovery by restarting the linkmgrd process directly, reducing the time taken to recover from an inconsistent mux state.
Added a linkmgrd restart command to save time for inconsistent mux state.
Ran the pre-test and confirmed that it can recover the inconsistent mux state.
Before:
After:
=> Recovery for inconsistent mux state issue

tests/acl/test_acl.py, tests/acl/test_stress_acl.py, tests/qos/qos_sai_base.py
Summary:
Add t1-isolated-d56u2 topo support into test_acl.py, test_stress_acl.py and test_qos_sai
Add t1-isolated-d56u2 topo support into test_acl.py, test_stress_acl.py and test_qos_sai
Add t1-isolated-d56u2 topo support into test_acl.py, test_stress_acl.py and test_qos_sai
Ran on physical testbed.
=> support t1-isolated-d56u2 in test_acl.py, test_stress_acl.py and test_qos_sai

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
In the PR #16836, new parameter is added to the test_everflow_per_interface, so the original skip could not work for the ipv6, update it
Summary:
=> Update the skip for the ipv6 everflow test

tests/common/plugins/sanity_check/checks.py
Hi @cyw233  @yejianquan ,
In case of presanity check for bfd, if _check_bfd_up_count is false once, the state never changes to true even when all the bfd sessions come up, added a small fix to set the state to true at the start of the check, this way it is able to recover
16/05/2025 00:50:23 checks._check_bfd_up_count L1137 INFO | BFD up count on asic0 of sfd-lt2-lc0: 160. Expected BFD up count: 160
16/05/2025 00:50:23 utilities.wait_until L0153 DEBUG | _check_bfd_up_count is False, wait 20 seconds and check again
16/05/2025 00:50:43 utilities.wait_until L0135 DEBUG | Time elapsed: 46.300968 seconds
16/05/2025 00:50:43 base._run L0071 DEBUG | /data/tests/common/devices/multi_asic.py::_run_on_asics#136: [sfd-lt2-lc0] AnsibleModule::shell, args=["ip netns exec asic2 show bfd summary | grep …
=> BFD check in sanity check was always reporting as false

tests/common/helpers/platform_api/sfp.py
Update get_transceiver_bulk_status to match the new SFP API naming.
In sfp.py call get_transceiver_dom_real_value instead of get_transceiver_bulk_status. The change is according to
https://github.com/sonic-net/sonic-platform-common/pull/556/files
Summary:
Update in the SFP API of renaming the get_transceiver_bulk_status function to get_transceiver_dom_real_value.
Update get_transceiver_bulk_status in sfp.py file to call the new function name.
Rerun successfully.
=> Update get_transceiver_bulk_status to match the new SFP API naming.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
1. Issue [#16161](https://github.com/sonic-net/sonic-buildimage/issues/16161) is fixed.
2. Some test cases that were failing in active-standby due to issue #8272 have been passing in active-active. Only test_active_link_down_downstream_active_soc[active-active] is still failing.
=> [Mellanox] Remove the skip/xfail for the dualtor_io link failure test

tests/lldp/test_lldp.py
Avoid config reload at the end of test_lldp_neighbor_post_orchagent_reboot tc to save ~4m of test execution time
Summary:
We disable the auto_restart of swss as part of test_lldp_neighbor_post_orchagent_reboot and do not revert it. That causes running config mismatch and a config reload is issued with the pre test running config. This config reload adds ~4m to the test execution time.
**Test log excerpts**
```
13/05/2025 **10:37:06** conftest.core_dump_and_config_check      L2555 WARNING| Core dump or config check failed for lldp/test_lldp.py, results: {"core_dump_check": {"failed": false, "new_core_dumps": {"mathilda-01": []}}, "config_db_check": {"failed": true, "pre_only_config": {"mathilda-01": {"null": {}}}, "cur_only_config": {"mathilda-01": {"null": {}}}, …
```
=> Avoid config reload in test_lldp_neighbor_post_orchagent_reboot to save ~4m of test execution time

ansible/roles/eos/templates/t1-48-lag-spine.j2, ansible/roles/eos/templates/t1-48-lag-tor.j2, ansible/vars/topo_t1-48-lag.yml
Summary: added new topo t1-48-lag for cisco hwsku Cisco-8102-28FH-DPU-O8C40
- [ X] 202405
- [X ] 202411
Introduced new cisco hwsku Cisco-8102-28FH-DPU-O8C40 for T1 role which requires new topology
deployed minigrapg and verified sanity 
Cisco-8102-28FH-DPU-O8C40
t1-48-lag
=> added new topo 't1-48-lag' for cisco hwsku Cisco-8102-28FH-DPU-O8C40

tests/common/helpers/dut_utils.py
Current implementation of `verify_orchagent_running_or_assert` does not verify orchagent state on all ASIC's. This is the code in question:
```
if duthost.is_multi_asic:
num_asic = duthost.facts.get('num_asic')
for asic_index in range(num_asic):
cmd = 'docker exec swss{} supervisorctl status orchagent'.format(asic_index)
output = duthost.shell(cmd, module_ignore_errors=True)
pytest_assert(not output['rc'], "Unable to check orchagent status output for asic_id {}"
.format(asic_index))
else:
cmds = 'docker exec swss supervisorctl status orchagent'
output = duthost.shell(cmds, module_ignore_errors=True)
pytest_assert(not output['rc'], "Unable to check orchagent status output")
return 'RUNNING' in output['stdout']
```
On multi-ASIC, the validation of orchagent running state `return 'RUNNING' …
=> Fix verify_orchagent_running_or_assert() for multi-ASIC

tests/snmp/test_snmp_phy_entity.py
Summary: Modify tests to also consider fans under fabric modules.
Fixes #16189 
Currently, `test_fan_info` operates under the assumption
that fans are only present in fan drawers. But, with Modular
Chassis, fans can also be present in the fabric modules.
Modify the test to consider this scenario while testing for fan
information.
1. Added a new test which only tests for fans under fabric cards.
2. Modified `test_fan_info` in such a way that depending on where
the fan is present (i.e fabric card or fan drawer) appropriate parent
is chosen and its information is verified.
Tested it manually on Arista machines.
No
N/A
Other PRs of interest for this change: https://github.com/sonic-net/sonic-platform-daemons/pull/601, https://github.com/sonic-net/sonic-snmpagent/pull/349
=> snmp: modify tests to also consider fans under fabric module

tests/fib/test_fib.py
Reverts sonic-net/sonic-mgmt#17627
This breaks the test fib setup on active active dualtor.
=> Revert "Enhance the fib test to run on dualtor active active setup"

ansible/testbed_config_vchassis.yml, tests/common/devices/sonic.py
Summary: The execution time of critical process check and routeCheck.py on virtual chassis becomes very high on elastictest backend so we need to increase the timeout value.
=> Higher timeout for vs chassis

tests/acl/test_acl.py
Summary:
Adapt ACL test on M1 topo.
Adapt ACL test on M1 topo.
Verified on Arista-7050CX3 M1-48 testbed.
=> [M1] Adapt ACL test for M1 topo

tests/acl/test_acl.py, tests/common/helpers/constants.py, tests/common/utilities.py
Summary:
In M1 topo, we have 2 upstream neighbor types: MA and MB.
We need to collect all upstream ports to avoid packet capture flaky failure.
In M1 topo, we have 2 upstream neighbor types: MA and MB.
We need to collect all upstream ports to avoid packet capture flaky failure.
Add function to read all up/down stream neighbor types.
Verified by ACL test on M1.
=> [M1] Collect all upstream ports for ACL test

tests/everflow/everflow_test_utilities.py, tests/everflow/test_everflow_ipv6.py, tests/everflow/test_everflow_per_interface.py, tests/everflow/test_everflow_testbed.py
Summary:
This PR skips the IPv6 Everflow tests on KVM testbeds to improve PR test execution time.
Everflow tests take a lot of time to execute. After adding IPv6 test cases (#16836), the execution time has roughly doubled. Now it takes more than 2 hours to run all tests in `everflow/test_everflow_testbed.py`. Since these tests are part of PR tests, if they take too long to run, the PR test will be cancelled. This PR skips the IPv6 Everflow tests on KVM testbeds (which are used for PR tests) to address this issue.
**Note:** The IPv6 Everflow tests will still run during nightly tests.
Added a new pytest fixture that will skip the tests when `erspan_ip_ver == 6` and the DUT is a virtual switch.
Ran the tests to ensure that the tests will be skipped when `erspan_ip_ver == 6`.
Only applies to …
=> Skipped IPv6 Everflow tests on virtual switch to speed up PR test execution

ansible/group_vars/vm_host/main.yml, ansible/templates/topo_t0-isolated.j2, ansible/templates/topo_t1-isolated.j2, ansible/vars/topo_t0-isolated-d16u16s1.yml, ansible/vars/topo_t0-isolated-d16u16s2.yml, ansible/vars/topo_t0-isolated-d32u32s2.yml, ansible/vars/topo_t1-isolated-d28u1.yml, ansible/vars/topo_t1-isolated-d56u2.yml
Summary:
Fixes #18056 by expanding the ptf subnet from /24 to /22 to accommodate up to 1024 exabgp neighbor IPs
Tested in physical testbed with existing t0 topo.  https://elastictest.org/scheduler/testplan/681c5af9750afedc7f448247
=> update ptf subnet to /22

tests/fib/test_fib.py
**Summary:**
This PR introduces a new test case to verify the hash behavior of IPinIP traffic on T0 topology, addressing the need outlined in [Issue #16531](https://github.com/sonic-net/sonic-mgmt/issues/16531).
To validate the hashing behavior of IPinIP traffic on T0 devices, ensuring consistent and expected ECMP behavior.
Analyzed the codebase and testbed setup.
Developed the test case targeting IPinIP hash behavior.
Resolved login issues with the SAW device to enable test execution 1.
Using fib/test_fib.py::test_ipinip_hash
Deployed the T0 topology and dualtor in the testbed.
Ran sample pytest cases to validate the environment.
Verified hash behavior through controlled …
=> Enable the test_ipinip_hash for T0 topo

ansible/library/generate_golden_config_db.py
Summary:
To the lossy platform, the buffer mode is traditional instead of dynamic.
Fix the buffer mode for the golden config generation.
Check in local
=> [generate_golden_config]: Fix wrong buffer mode for lossy platform

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
The invalid signal test was accidentally left out when this test was disabled for the rewrite in https://github.com/sonic-net/sonic-mgmt/pull/17553. The entire test should be disabled.
- [ x] Test case improvement
Disable the entire test for the rewrite
=> Disable kill_process test for rewrite.

tests/conftest.py, tests/macsec/test_docker_restart.py
test_docker_restart.py requires macsec docker containers to test container restart. This container is only available in macsec duthost and non-macsec duthosts will fail the test.
Therefore, we replace randomly choosing duthost to test with enum_rand_one_per_hwsku_macsec_frontend_hostname fixture, so test will not fail on non-macsec duthosts
Summary:
Fixes test_docker_restart.py failure in Cisco T2 8800 devices and potentially others.
Failure of test_docker_restart.py during macsec validation in Cisco T2 8800 devices
Replace randomly choosing duthost with enum_rand_one_per_hwsku_macsec_frontend_hostname fixture in test_restart_macsec_docker
tested in Cisco 8800 device
macsec/test_docker_restart.py::test_restart_macsec_docker[MACSEC_PROFILE] PASSED
=> Update test_docker_restart to use macsec host only

tests/common/helpers/pfc_gen_t2.py
Summary:
Fixes # 17533
Change max to min in pfc_gen_t2.py. The current code results in out-of-memory conditions in sonic fanouts, if we give a large number of packets as argument.
OOM in fanout when a large number of packets is requested in command line for pfc_gen_t2.py.
Changed max to min in the code.
Ran it on T2 systems:
```
====================================================================================================== warnings summary ======================================================================================================
../../usr/local/lib/python3.8/dist-packages/paramiko/transport.py:236
/usr/local/lib/python3.8/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
"class": algorithms.Blowfish,
-- Docs: …
```
=> Change max to min in pfc_gen_t2.py

tests/qos/qos_sai_base.py
Summary:
VOQ watchdog will be enabled on T2, tx disable for 60 seconds will trigger soft reset.
Disable VOQ watchdog when running qos_sai script.
Avoid soft reset caused by tx disable.
Disable voq watchdog.
Enable voq watchdog on T2 testbed and run qos-sai regression.
T2.
=> Disable voq watchdog in qos_sai script

tests/common/snappi_tests/snappi_fixtures.py
For mixed mode testing we need Ixia ports in different speed connected to DUT. Like 100G and 400G. In snappi fixture there was a check which was making sure all snappi ports are of same speed which was bailing out mixed mode tests.
Removing the check to have same speed Ixia ports to accommodate mixed speed testing
- [X ] Test case improvement
All mixed speed tests were failing with below error:
`12/05/2025 16:59:05 __init__._log_sep_line                   L0170 INFO   | ==================== snappi_tests/pfc/test_pfc_mixed_speed.py::test_mixed_speed_no_congestion[multi-dut-long-400g-short-100g-port_map0] call ==================== 12/05/2025 16:59:05 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last): File …
=> Changes to accommodate Mixed mode testing

tests/snappi_tests/pfc/files/m2o_fluctuating_lossless_helper.py
Currently, the results were verified using round which resulted in some failures where 10.85% rounds to 11 and fails the test on Nokia Platforms. Modified the condition to have some more room for values of drop between 9-11%.
Summary:
https://github.com/sonic-net/sonic-mgmt/issues/18043
To enhance the check for verification of drops in the test case.
By changing the assertion used to verify the drops.
Tested on Nokia Chassis in msft lab
=> [Snappi]: Pass/fail criteria for pfc m2o testcase have thinner margins causing intermittent failures.

tests/pfcwd/conftest.py
Summary:
Fixes the issue:
raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
E           tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
E           rc = 2
E           cmd = show platform npu script  -s set_pfc_time.py
E           start = 2025-01-23 04:05:01.590011
E           end = 2025-01-23 04:05:03.007243
E           delta = 0:00:01.417232
E           msg = non-zero return code
E           invocation = {'module_args': {'_raw_params': 'show platform npu script  -s set_pfc_time.py', '_uses_shell': True, 'warn': False, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'chdir': None, 'executable': None, 'creates': None, 'removes': None, 'stdin': None}} …
=> T2:pfcwd:Fix the asic_id check - It fails for asic0

tests/pfcwd/test_pfcwd_cli.py, tests/pfcwd/test_pfcwd_function.py, tests/pfcwd/test_pfcwd_warm_reboot.py
Innovium chip name is changed to marvell-teralynx in Sonic and hence same modification needed in pfcwd cases.
Please merge this PR to 202411 also.
Summary:
- [*] Testbed and Framework(new/improvement)
Innovium chip name is changed to marvell-teralynx in Sonic and hence same modification needed in pfcwd cases.
=> Changing innovium name to marvell-teralynx in pfcwd module

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/vxlan/test_vxlan_route_advertisement.py
Enabling VXLAN route advertisement test for marvell-teralyx platform
Summary:
=> Enabling VXLAN route advertisement test for marvell-teralyx platform

ansible/library/exabgp.py, tests/common/helpers/bgp.py, tests/dualtor/test_orchagent_slb.py
Summary:
`test_orchagent_slb` is flaky, let's collect more test information:
1. enable `exabgp` to run in debug mode.
2. collect slb `exabgp` logs and save to the logs directory so nightly can collect them afterwards.
3. show the l3 neighbor on the DUTs and FIB on PTF in teardown.
```
dualtor/test_orchagent_slb.py::test_orchagent_slb[ipv4-active-standby] PASSED                                                                                                                  [100%]
====================================================================== 1 passed, 3 deselected, 97 warnings in 617.67s (0:10:17) ======================================================================
```
=> [test_orchagent_slb] Enable `exabgp` debug mode and collect logs

tests/common/configlet/utils.py
Summary: Skip last_update_time per design.
Fixes # (issue) ADO: 32970571
Due to recent change in https://github.com/sonic-net/sonic-platform-daemons/pull/604, the last_udpate_time was added. It should be skipped for comparison per design.
The `last_update_time` field was added in four place including `post_diagnostic_values_to_db, post_port_dom_flags_to_db, post_port_transceiver_hw_status_flags_to_db, post_port_vdm_thresholds_to_db`.
So there are many table involved such as `TRANSCEIVER_STATUS`, `TRANSCEIVER_STATUS_FLAG`. Thus skip in the val comparison.
Skip the last_update_time for comparison
E2E
=> [configlet] Skip last_update_time for comparison per design

ansible/roles/test/files/ptftests/py3/IP_decap_test.py
Summary:
This PR is to fix decap test on FT2 topo.
The test gets stuck on FT2 because all the ports are in nexthop for default route. Hence the check in function `get_src_and_exp_ports` runs into dead loop.
This PR addressed that issue by checking if the route points to default route, and ignore the check `src_port in exp_port_list` if that's the case.
This PR depends on https://github.com/sonic-net/sonic-mgmt/pull/18442
This PR is to fix decap test on FT2 topo.
This PR addressed that issue by checking if the route points to default route, and ignore the check `src_port in exp_port_list` if that's the case.
The change is verified on a FT2 topo.
```
collected 4 items …
```
=> Fix decap test on FT2 topo

tests/bmp/helper.py, tests/bmp/test_frr_bmp_sanity.py, tests/common/helpers/monit.py, tests/monit/test_monit_status.py
Summary:
Add monit test case with disable bmp but enable frr_bmp feature switch to block regression
Add one more test for monit syslog checking and disable bmp in advance which reflects real production config.
New test case passed without issue
Used old image which does not have monit fix https://github.com/sonic-net/sonic-buildimage/pull/22588 it broke the test case
With new image all test verification with frr_bmp enable + bmp disable are also passed, result could be found https://dev.azure.com/mssonic/build/_build/results?buildId=859705&view=results
N/A
N/A
=> Add monit test case with disable bmp but enable frr_bmp feature switch to block regression

tests/common/helpers/ntp_helper.py
NTP Service name differs based on type. Classic NTP has service name of `ntp` while NTPSEC on Bookworm has service name as `ntpsec`. This PR sets the service name based on type.
 
Summary:
This change is backward compatible and is required to support running tests in docker-ptf Bookworm image.
See description.
Manually
NA
NA
NA
=> Set NTP service name based on type

tests/build-gnmi-stubs.sh
Modify the generate gNMI stub script to check if the directory exists. This was due to a bug https://github.com/grpc/grpc/issues/39583 in `grpc_tools.protoc` which is now fixed.
Summary:
Fix issue with stub generation script.
See description above.
Manually
NA
NA
NA
=> Modify gnmi stub generate script in line with issue in protoc fixed

tests/common/snappi_tests/snappi_fixtures.py, tests/common/snappi_tests/traffic_generation.py, tests/snappi_tests/pfc/files/lossless_response_to_external_pause_storms_helper.py, tests/snappi_tests/pfc/files/lossless_response_to_throttling_pause_storms_helper.py, tests/snappi_tests/pfc/files/m2o_fluctuating_lossless_helper.py, tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_helper.py, tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py, tests/snappi_tests/pfc/files/m2o_oversubscribe_lossy_helper.py, tests/snappi_tests/pfcwd/files/pfcwd_basic_helper.py, tests/snappi_tests/pfcwd/files/pfcwd_burst_storm_helper.py, tests/snappi_tests/pfcwd/files/pfcwd_multi_node_helper.py, tests/snappi_tests/pfcwd/files/pfcwd_runtime_traffic_helper.py, tests/snappi_tests/pfcwd/test_pfcwd_actions.py, tests/snappi_tests/qos/files/packet_reorder_helper.py, tests/snappi_tests/test_multidut_snappi.py, tests/snappi_tests/test_snappi.py
Summary:
Recently we introduced a function to use static-route and static-routed destinations for traffic in snappi scripts. This was needed for cisco-8000 to make sure that the split-voq functionality is used, and in addition, the connected route was not the use case scenario as well.
In this PR, we propagate the changes to newly rewritten/merged multidut code, which now can be run on T0/T1 and T2. So with this change all scripts use static route for cisco-8000.
Cisco-8000 uses split voq only when the packets are destined to routed dests. The snappi scripts were written for connected routes, which is not the usecase for cisco-8000 platform. This PR changes the traffic to static-routed destinations.
Changed all ipv4.dst.values to the new function that will return static routed dest for …
=> Snappi: T0/T1/T2: Convert all traffic to static routed destinations in snappi scripts.

tests/vxlan/test_vxlan_decap.py
Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/18618
To fix the broken testcase vxlan/test_vxlan_decap.py.
By changing the name of the vxlan netdev.
1. Manually
2. Running the testcase vxlan/test_vxlan_decap.py
generic
=> Shrink the vxlan_tunnel name len to be less than IFNAMSIZ

tests/common/dualtor/dual_tor_utils.py, tests/dualtor_io/test_normal_op.py
Summary:
If the previous testcase (in the same test session) leaves the DUT in an error state - mux status is not active for libra, the testcases following this one will suffer from this to fail.
Let's validate before each testcase run to ensure the DUTs are in active-active setup, and recover if neccessary.
1. leaves the DUT in an error state, as this issue: https://github.com/sonic-net/sonic-linkmgrd/issues/292
2. run test
```
dualtor_io/test_normal_op.py::test_tor_switch_upstream[active-active] PASSED                                                                                                                                                                                           [100%] …
```
=> [dualtor-io] Validate and recover active-active setup

tests/common/platform/device_utils.py
Summary:
The  PR(#18286) changed the psu_line_pattern, but for Mellanox devices, the output keeps the same. 
Although the output line can be matched by the new pattern, but the groups changed in the match, which lead to test_turn_on_off_psu_and_check_psustatus test failure.
We should still use the old pattern.
Still use the old pattern for Mellanox devices.
Run the platform_tests/test_platform_info.py::test_turn_on_off_psu_and_check_psustatus which uses the pattern on Mellanox device and passed.
=> [Mellanox] Fix psu_line_pattern for mellanox devices

ansible/roles/test/files/ptftests/fib_test.py, ansible/roles/test/files/ptftests/py3/hash_test.py, tests/fib/test_fib.py
Summary:
This PR is to enhance `test_fib` to support a new topology `FT2`.
Changes include
1. Pass `topo_type` to ptf script 
2. Improve port selection for `FT2`
3. Fix the exception when `hash_key` is `ingress-port`. 
This PR is to enhance `test_fib` to support a new topology `FT2`.
1. Pass `topo_type` to ptf script 
2. Improve port selection for `FT2`
3. Fix the exception when `hash_key` is `ingress-port`. 
The change is verified on a FT2 testbed.
```
collected 15 items                                                                                                                                                                                                            
fib/test_fib.py::test_basic_fib[True-True-1514]  …
```
=> [DT2] Enhance fib test to support FT2

tests/snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py
Summary: Add support using snappi_tests dynamic
Fixes # (issue) 33003932
Added support for `--enable-snappi-dynamic-ports` pfcwd_a2a_with_snappi test. Also make sure that the override variable is cross-compatible for legacy method
Update the fixture usage
Verified on physical testbed with both overrides option and dynamic ports options
Run with enable dynamic port option `--enable-snappi-dynamic-ports`
=> feat: add support for dynamic ports

tests/test_pretest.py
Fix the dut variable name in `test_disable_startup_tsa_tsb_service()` in `test_pretest.py` added in #17247
Summary:
When using multithreading parallel run, we cannot refer to the `duthost` variable, we need to use `dut` instead.
=> fix: correct DUT variable name in startup tsa pretest

ansible/library/announce_routes.py, ansible/vars/topo_t0-isolated-d2u254.yml, ansible/vars/topo_t0-isolated-d2u254s1.yml, ansible/vars/topo_t0-isolated-d2u254s2.yml, ansible/vars/topo_t0-isolated-d2u510.yml, ansible/vars/topo_t0-isolated-d2u510s2.yml
Summary:
In bgp scale test, pt0 should announce vlan routes, so this PR mark pt0 as role tor, and it won't generate routes.
In bgp scale test, pt0 should announce vlan routes
this PR mark pt0 as role tor, and it won't generate routes
Run ansible script to announce routes on testbed
=> [topo file] Fix pt0 announce routes in bgp scale topologies

tests/conftest.py, tests/route/test_route_flap.py
Summary:
Adapt testcase `test_route_flap` to M1 topo.
Adapt testcase `test_route_flap` to M1 topo.
1. Support M1 topo.
2. Use default route for flap test because default route is the only multipath route on M1 topo.
Verified on Arista-7050CX3 M1-48 testbed.
=> [M1] Adapt test_route_flap to M1 topo

azure-pipelines.yml, sdn_tests/pins_ondatra/BUILD.bazel, sdn_tests/pins_ondatra/tests/BUILD.bazel
Adding new BUILD.bazel file in /pins_ondatra  folder which helps to build All Ondatra Tests in single run using bazel commands below
Also modified pins_ondatra/tests/BUILD.bazel file to execute all the tests at a time
To Build All Tests:  bazel build ...
To Build and Execute all Tests : bazel test //tests:all_tests
=> Enhanced Ondatra's Build.bazel to trigger build for all test cases

tests/show_techsupport/test_techsupport.py
Fix for test_techsupport.py failure on marvell-teralynx platform.
Default GRE version `0x6558` used by the test case is not correct for marvell-teralynx platform resulting in testcase failure.
Marvell-teralynx platforms support GRE protocol type 0x88BE i.e., ERSPAN Type II.
Summary:
To fix show_techsupport/test_techsupport.py failures on marvell-teralynx platform
Added marvell-teralynx platform check to fix failure.
By running show_techsupport PTF testcases.
```
show_techsupport/test_techsupport.py::test_techsupport[acl-str-marvell-01] PASSED         [ 25%]
show_techsupport/test_techsupport.py::test_techsupport[mirroring-str-marvell-01] PASSED   [ 50%]
show_techsupport/test_techsupport.py::test_techsupport_commands[str-marvell-01] PASSED    [ 75%]
```
Fix is specific to …
=> [show_techsupport]: Fix test_techsupport.py on marvell-teralynx

ansible/roles/eos/tasks/ceos.yml, ansible/roles/eos/templates/dpu-tor.j2, ansible/roles/eos/templates/m0-mx.j2, ansible/roles/eos/templates/t0-8-lag-leaf.j2, ansible/roles/eos/templates/t0-backend-leaf.j2, ansible/roles/eos/templates/t0-leaf-lag-2.j2, ansible/roles/eos/templates/t0-leaf.j2, ansible/roles/eos/templates/t0-mclag-leaf.j2, ansible/roles/eos/templates/t0-v6-leaf.j2, ansible/roles/eos/templates/t1-28-lag-spine.j2, ansible/roles/eos/templates/t1-28-lag-tor.j2, ansible/roles/eos/templates/t1-56-lag-tor.j2, ansible/roles/eos/templates/t1-64-lag-tor.j2, ansible/roles/eos/templates/t1-8-lag-spine.j2, ansible/roles/eos/templates/t1-8-lag-tor.j2, ansible/roles/eos/templates/t1-backend-tor.j2, ansible/roles/eos/templates/t1-lag-spine.j2, ansible/roles/eos/templates/t1-lag-tor.j2, ansible/roles/eos/templates/t1-smartswitch-ha-spine.j2, ansible/roles/eos/templates/t1-smartswitch-ha-tor.j2, ansible/roles/eos/templates/t2-core.j2, ansible/roles/eos/templates/t2-leaf.j2, ansible/roles/eos/templates/t2-vs-core.j2, ansible/roles/eos/templates/t2-vs-leaf.j2
Summary: Force the cEOS instances to use their own IP for next-hop
Fixes #18658
Fixing a bug introduced by using a newer version of cEOS for testing.  While the current documentation doesn't specify a newer version of cEOS, it would be good to have this fix in place before people start using a newer version of cEOS.
Adjust the cEOS configuration templates to force cEOS to rewrite the next-hop as itself
Normal sonic-mgmt test run
Not platform-dependent.
All
Just a bugfix.
=> Update cEOS configuration to use next-hop-self

tests/bgp/conftest.py
Summary:
Small PR to add support for LT2 in BGP tests, through the use of an appropriate setup function for the platform.
To ensure that we can run the BGP tests on the Lower T2 platform, we needed to add explicit support and initial testing for these testcases.
Added `lt2` to the list of topologies that uses the t1 & t2 interface setup function.
Running the previously failing tests, we can observe that they pass:
Other than loganalyzer fail, all testcases run successfully:
Change is only relevant to the LT2 platform - all others are unaffected by this change.
N/A
N/A
=> [BGP Tests] Enable Tests for LT2 and FT2 Topologies

tests/upgrade_path/conftest.py, tests/upgrade_path/test_multi_hop_upgrade_path.py
test_multi_hop_upgrade_path should be consistent with test_upgrade_path in allowing for test to restore device back to a given image.
Tested on arista testbed: device is restored back to given image after test completes
Summary:
=> Add restore_image fixture to test_multi_hop_upgrade_path (#18230)

tests/bgp/conftest.py
Manual cherry-pick for #18669
Summary:
Small PR to add support for LT2 in BGP tests, through the use of an appropriate setup function for the platform.
To ensure that we can run the BGP tests on the Lower T2 platform, we needed to add explicit support and initial testing for these testcases.
Added `lt2` to the list of topologies that uses the t1 & t2 interface setup function.
Running the previously failing tests, we can observe that they pass:
Other than loganalyzer fail, all testcases run successfully:
Change is only relevant to the LT2 platform - all others are unaffected by this change.
N/A
N/A
=> [cherry-pick] [BGP Tests] Enable Tests for LT2 and FT2 Topologies

ansible/config_sonic_basedon_testbed.yml
Summary:
Enhance the playbook to resolve `maximum recursion depth exceeded` issue while deploy-mg on 512-neighbor topo.
```
The full traceback is:
File "/usr/local/lib/python3.8/dist-packages/ansible/executor/task_executor.py", line 524, in _execute
self._task.post_validate(templar=templar)
File "/usr/local/lib/python3.8/dist-packages/ansible/playbook/task.py", line 291, in post_validate
super(Task, self).post_validate(templar)
File "/usr/local/lib/python3.8/dist-packages/ansible/playbook/base.py", line 656, in post_validate
value = templar.template(getattr(self, name))
File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 903, in template
d[k] = self.template(
File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init …
```
=> Enhance deploy-minigraph ansible playbook

tests/bgp/conftest.py
The test_bgp_update_timer.py selects the ports via random port selection in setup. The fixture 'common_setup_teardown' fails the test if the ports belong to different asics for mutli-asic chassis.
Hence updated the function '_setup_interfaces_t1_or_t2' to apply random selection on the set of interfaces belonging to same asic.
Summary:
Test failure due to selected ports belonging to different asics
=> Fix for lag port selection in test_bgp_update_timer.py

ansible/roles/vm_set/tasks/control_mux_simulator.yml
On server < 2024.04, when the script attempts to install flask==2.3.3, it requires blinker >= 1.6.2. However server already has blinker from apt and it is only 1.4 and cannot be upgraded. The change force pip to install new blinker.
Summary:
=> [dualtor-aa] fixed add-topo for dualtor

ansible/roles/eos/tasks/ceos_ensure_reachable.yml
Summary:
The ansible-playbook checks container's reachability on the wrong host. If the number of neighbors is large, it can waste a lot of time.
Fix the wrong host from ansible executing host to container host.
Check it locally.
=> [ceos_ensure_reachable.yml]: Fix wrong host of ceos

tests/acl/test_stress_acl.py
Summary:
Fix test_stress_acl for the t1-isolated-d32/128 topology, where uplinks are all T0 peers
=> Fix test_stress_acl uplinks for t1-isolated-d128

ansible/roles/fanout/tasks/sonic/fanout_sonic_cisco_8101_202205.yml, ansible/roles/fanout/templates/sonic_deploy_cisco_8101_202205.j2
The previous ansible template does not distinguish between sonic name and alias in the links file, which causes sonic unable to understand vlan members which should always be sonic name
Summary:
Fix 8101 fanout deployment bug
Fix bug
Deployed fanout
Cisco-8101 only
=> [8101] Fix bug that confuses sonic name with alias

tests/drop_packets/drop_packets.py, tests/drop_packets/test_configurable_drop_counters.py, tests/drop_packets/test_drop_counters.py
Changes made in tests/drop_packets files.
Noqa replaced with noqa:
=> Replaced noqa eith noqa: in tests/drop_packets

tests/scripts/dual_tor_sniffer.py
Summary:
Fix the dualtor io failure:
```
>       pytest_assert(len(failures) == 0, '\n' + '\n'.join(failures))
E       Failed:
E       Traffic on server 192.168.0.2 was disrupted prior to test start, missing 1 packets from the start of the packet flow
E       Traffic on server 192.168.0.4 was disrupted prior to test start, missing 1 packets from the start of the packet flow
E       Traffic on server 192.168.0.6 was disrupted prior to test start, missing 1 packets from the start of the packet flow
```
The issue is introduced by PR https://github.com/sonic-net/sonic-mgmt/pull/18299. 
The reason is that, the dualtor sniffer now listens to all dataplane interfaces on ptf (with prefix `eth`); for topo like `dualtor-120`, it has 128 dataplane interfaces, dualtor sniffer takes up …
=> [dualtor-io] fix dualtor sniffer start slow issue

ansible/library/announce_routes.py
Summary:
Currently T2 announce route script are publishing 32 routes x 3 for 3 groups of VM to T1. I.e:
- 192.168.x.x first 32 routes
- 192.169.x.x next 32 routes
- 192.170.x.x next 32 routes
Since LT1 have 110 T1, we will use another 192.171.x.x (32 routes) to satisfy the requirement
Add more routing to match with current T2 setup
Broadcast the following sequentially in 4 groups of 110 VM:
- 192.168.x.x first 32 routes
- 192.169.x.x next 32 routes
- 192.170.x.x next 32 routes
- 192.171.x.x next 32 routes
The last group of 110 will broadcast 14 routes of 192.171.x.x
Verify on LT2 device
=> chore: update announce routes script to match T2

tests/bgp/test_seq_idf_isolation.py
Summary:
Enabling test_seq_idf_isolation.py on LowerSpineRouter
For disaggregated T2, sequential IDF isolation needs to be done on LowerSpineRouter
Enable test to run on topo 'lt2' 
Ran idf isolation commands manually and verified isolation/unisolation on a couple of T1 neighbors
=> Enable sequential IDF isolation test on LowerSpineRouter

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/conftest.py
Summary:
Fixes #18619, added comment to improve user experience on T2 MACSec tests 
Also skip MACSec tests for T2, when enable_macsec is not set during test run.
macsec_enabled:
macsec/test_docker_restart.py::test_restart_macsec_docker[macsec_LC1] PASSED                                                                   [100%]
================================================================= 1 passed, 1 warning in 332.85s (0:05:32) ================================================================
not passing in macsec_enabled:
SKIPPED [1] macsec/test_docker_restart.py: got empty parameter set ['enum_rand_one_per_hwsku_macsec_frontend_hostname'], function test_restart_macsec_docker at /tests/macsec/test_docker_restart.py:14
===================================================================== …
=> [T2 MACSec] Skip macsec tests for T2 without macsec enable param

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
This is a manual cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/18276 to fix conflict.
=> [202411][Mellanox] Remove the skip/xfail for the dualtor_io link failure test

tests/qos/qos_sai_base.py
Update qos sai tests due to splitting buffer queue configuration for lossy queue only port. The design PR is: https://github.com/sonic-net/sonic-buildimage/pull/22474
Summary:
Update qos sai tests due to splitting buffer queue configuration for lossy queue only device
Align qos sai tests according to the PR of https://github.com/sonic-net/sonic-buildimage/pull/22474
Run the qos sai tests related to lossy queue.
SN5610/SN5600/SN5640
=> Update qos sai tests due to splitting buffer queue configuration for lossy queue only device

tests/platform_tests/sfp/test_sfputil.py
Summary: test_check_sfputil_error_status errors out on cisco-8000 smartswitch platforms when the DPU backplane ports  are configured in STATE DB.
RC: sudo sfputil show error-status CLI errors out on cisco-8000 smartswitch platform when STATE_DB populate with backplane ports 
cisco@MtFuji-dut:~$ sudo sfputil show error-status                                                                                                                                                   
Error: invalid port 'Ethernet224'                                                                                                                                                                    
Valid values for port: ['Ethernet0', 'Ethernet8', 'Ethernet16', 'Ethernet24', 'Ethernet32', 'Ethernet40', …
=> filterd backplane ports from STATE_DB while checking 'sudo sfputil show error-status'

tests/auditd/test_auditd.py
Add test_rate_limit to auditd watchdod test cases
Auditd watchgod container add ratelimit check in this PR: 
https://github.com/sonic-net/sonic-buildimage/pull/22620
Also, json format fix in this PR:
https://github.com/sonic-net/sonic-buildimage/pull/22709
Add new test case to prevent regression
- Microsoft ADO **(number only)**:32313402
Add test_rate_limit to auditd watchdod test cases
Add test_rate_limit to auditd watchdod test cases
=> Add test_rate_limit to auditd watchdog test cases

tests/hash/test_generic_hash.py
Summary:
During the run of `test_reboot` we are randomly generating `reboot_type` which can be one of following values `'cold', 'warm', 'fast', 'reload'` and in the test we are checking if `reboot_type ` is one of that values
`if reboot_type in ['cold', 'reload']:`
But there are missing check for `'warm', 'fast'` 
And as a result we are not saving config  before reboot if reboot type is `fast ` or `warm `and because of that 
`ecmp hash fields` and `lag hash fields` are empty
Failed test hash/test_generic_hash.py
Added 'fast' and 'warm' reboot type check in order to save config for this type of reboot
=> Bug: added fast reboot into reboot_type check

tests/snmp/test_snmp_link_local.py
Summary:
Add SNMP LLDP check after config reload in test cleanup
SNMP LLDP takes a bit longer to be ready after `config reload`. Ensure that it is ready before proceeding to the next test (`snmp/test_snmp_lldp.py`).
The next test fails because SNMP LLDP is not ready (fails on `KeyError` because SNMP LLDP entries are not populated properly from snmpwalk).
Ensure SNMP LLDP is ready after `config reload` before proceeding to the next test.
`snmp/test_snmp_lldp.py` no longer fails when run right after `snmp/test_snmp_link_local.py`.
=> Add snmp lldp state check after config_reload

tests/conftest.py
Summary: Disable the default dynamic variable snappi fallback since T1-tgen testbed does not support this feature yet and currently generating alert. Disabling this now to suspress the alert.
Fixes # (issue) 33123296
Disable the default dynamic variable snappi fallback since T1-tgen testbed does not support this feature yet and currently generating alert. Disabling this now to suspress the alert.
@sdszhang @kamalsahu0001 @amitpawar12 for viz
=> chore: disable default dynamic var snappi fallback

tests/snappi_tests/files/helper.py
Summary: Skip fast / warm reboot testcases
Fixes [#18410](https://github.com/sonic-net/sonic-mgmt/issues/18410), [#18409](https://github.com/sonic-net/sonic-mgmt/pull/18409)
Warm reboot is not needed for Jericho2 and Jericho2C+ 
Fast reboot is being skipped for all topologies in sonic-mgmt, so same should be done for snappi_tests
=> Skip fast / warm reboot testcases in snappi test suite

tests/acl/test_acl.py
Summary:
Change t1-isolated-d28 to d32 in ACL tests
=> Change t1-isolated-d28 to d32 in ACL tests

tests/acl/test_acl.py, tests/acl/test_stress_acl.py, tests/common/helpers/constants.py, tests/common/helpers/ptf_tests_helper.py
Summary:
In the topology with service ports, like t0-d18u8s4, t0-isolated-d16u16s1, t0-isolated-d32u32s2. we should include the PT0 neighbor port in the upstream neighbor list. With the enhancement in #18516, we can achieve this by adding pt0 in UPSTREAM_ALL_NEIGHBOR_MAP.
To include service ports into upstream neighbors list.
Update the UPSTREAM_ALL_NEIGHBOR_MAP.
Run acl test and passed.
=> [ACL] Include service port into upstream neighbors

tests/dualtor_io/test_link_failure.py
…
Summary:
To fix https://github.com/sonic-net/sonic-buildimage/issues/16161.
Work Item: 33161901
Allow duplications on MLNX/Cisco platforms.
```
dualtor_io/test_link_failure.py::test_active_link_down_downstream_active[active-standby] PASSED                                                                                                                                                                        [100%]
```
=> [dualtor-io] Fix `test_active_link_admin_down_config_reload_link_up_downstream_standby` on Cisco/MLNX

tests/common/dualtor/data_plane_utils.py
Summary:
Work Item: 33161844
Fix the `dualtor_io.test_link_failure.test_active_link_down_downstream_active_soc[active-active]` failure:
```
Failed: 
Traffic to server 192.168.0.15 was disrupted 2 times. Allowed number of disruptions: 1
```
The server 192.168.0.15 I/O result shows that there are two disruptions:
```
01/06/2025 15:06:12 dual_tor_io.examine_flow                 L0740 INFO   | Server 192.168.0.15 results:
{
"sent_packets": 652,
"received_packets": 650,
"disruption_before_traffic": false,
"disruption_after_traffic": false,
"duplications": [],
"disruptions": [
{
"start_time": 1748790187.24364,
"end_time": 1748790187.772263,
"start_id": 70,
"end_id": 72
},
{
"start_time": 1748790187.772263,
"end_time": 1748790188.304254,
"start_id": 72,
"end_id": 74
}
]
}
``` …
=> [dualtor-io] Fix duplication merge condition

tests/conftest.py, tests/macsec/test_docker_restart.py
Cheery-picking PR#https://github.com/sonic-net/sonic-mgmt/pull/18518 and PR#https://github.com/sonic-net/sonic-mgmt/pull/18725 for 202505 branch
cherry-pick 2 PRs in 1, as 18725 covers regression from 18518
Summary:
=> [Cherry-pick][macsec]Update test_docker_restart to use macsec host only

tests/acl/test_acl.py, tests/acl/test_stress_acl.py, tests/common/helpers/constants.py, tests/common/helpers/ptf_tests_helper.py
Summary:
This is a manual cherry-pick of #18671
In the topology with service ports, like t0-d18u8s4, t0-isolated-d16u16s1, t0-isolated-d32u32s2. we should include the PT0 neighbor port in the upstream neighbor list. With the enhancement in #18516, we can achieve this by adding pt0 in UPSTREAM_ALL_NEIGHBOR_MAP.
=> [Cherry-pick][ACL] Include service port into upstream neighbors

tests/iface_namingmode/test_iface_namingmode.py
Check both admin and oper port states after a port toggle 
We need to ensure port is up and can receive packets before verifying its lldp neighbors
Summary:
=> Update test_config_interface_state in iface_namingmode

tests/srv6/srv6_utils.py, tests/srv6/test_srv6_dataplane.py
Add ASIC DB verification for SRv6 SID entries
Summary:
- Introduced a new function `verify_asic_db_sid_entry_exist` to check for the existence of SRv6 SID entries in the ASIC DB.
- Updated multiple test cases to assert the presence of these entries after configuration reload, BGP restart, and reboot events.
Fix cases in which the configuration is not present on asic-db, before running the test. 
Added validation to query the asic-db and verify the configuration exist
=> Add ASIC DB verification for SRv6 SID entries

tests/platform_tests/test_power_off_reboot.py
Summary:
Fixed power off reboot test to support multiple outlets
Currently the test was turning off all outlets but turning on only one outlet.
It worked for system with 1 outlet, but not for systems with 2 or more.
This fix is ensuring that the test will power on all the outlets.
Changes the turn on to run on all outlets instead of part of them.
Ran the test
=> Fixed power off reboot test to support multiple outlets

tests/acl/test_acl.py, tests/acl/test_stress_acl.py, tests/common/helpers/constants.py, tests/common/helpers/ptf_tests_helper.py, tests/common/utilities.py
Summary:
This is a manual cherry-pick of #18516 and #18671 to include service port into upstream neighbors in ACL tests.
=> [Cherry-pick][ACL] Collect all upstream ports and Include service port into upstream neighbors in ACL tests

tests/fib/test_fib.py
Summary:
Enable `test_nvgre_hash` run on `dualtor-aa` testbeds.
By using dualtor-aa supported ptf port mapping for the nvgre hashing ptf test.
```
fib/test_fib.py::test_nvgre_hash[ipv4-ipv4] PASSED                                                               [ 25%]
fib/test_fib.py::test_nvgre_hash[ipv4-ipv6] PASSED                                                               [ 50%]
fib/test_fib.py::test_nvgre_hash[ipv6-ipv6] PASSED                                                               [ 75%]
fib/test_fib.py::test_nvgre_hash[ipv6-ipv4] PASSED                                                               [100%]
====================================== 4 passed, 3 warnings in 1129.28s (0:18:49) …
```
=> [dualtor-aa] Add dualtor-aa support to `test_nvgre_hash`

ansible/library/announce_routes.py
Summary:
After the change in : https://github.com/sonic-net/sonic-mgmt/pull/17943,  default route will advertised from T0 peer in t1-isolated-d56u2 or t1-isolated-d56u1-lag topo. and caused multiple failures in test_acl, as both T0 and T2 are advertising default route.
This PR will limit the default route advertisement to -d128 topology only.
Fix failures in test_acl due to the route advertisement change.
acl/test_acl.py::TestBasicAcl::test_ingress_unmatched_blocked[ipv4-ingress-downlink->uplink-default-no_vlan] PASSED [  0%]
acl/test_acl.py::TestBasicAcl::test_egress_unmatched_forwarded[ipv4-ingress-downlink->uplink-default-no_vlan] SKIPPED [  0%]
acl/test_acl.py::TestBasicAcl::test_source_ip_match_forwarded[ipv4-ingress-downlink->uplink-default-no_vlan] PASSED [  0%] …
=> advertise tor default route for t1-isolated-d128 only

tests/common/helpers/portchannel_to_vlan.py
Summary: This PR fixes an issue where an UnboundLocalError exception was raised when 
the setup_dut_ptf function failed during test execution. The error occurred 
because ptf_lag_map was being referenced in the finally block before being 
assigned a value when an exception was thrown in the try block.
This PR fixes an issue where an UnboundLocalError exception was raised when 
the setup_dut_ptf function failed during test execution. The error occurred 
because ptf_lag_map was being referenced in the finally block before being 
assigned a value when an exception was thrown in the try block.
Initialize ptf_lag_map = None before the try block, and add conditional check in finally block to only call ptf_teardown when ptf_lag_map is not None
``` …
```
=> Fix UnboundLocalError in portchannel_to_vlan fixture

tests/bgp/test_bgp_stress_link_flap.py
Summary:
32454304
We plan to use this case test_bgp_stress_link_flap for the longevity test, current thorough run time is not meet the requirement, need enlarge the run time value for thorough level.
update completeness_level for test_bgp_stress_link_flap.py
Enlarge the runtime for the case and add the memory monitor during test in thorough level.
Run the pipeline
NA
=> [test_bgp_stress_link_flap] update completeness_level for bgp link flap case

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
https://github.com/sonic-net/sonic-mgmt/issues/18873
To xfail test_crm_available, which has a known issue on broadcom dualtor platform. 
Add xfail in tests_mark_conditions.yaml
Run test on dualtor platform
=================================================================================================================== short test summary info ====================================================================================================================
XFAIL crm/test_crm_available.py::test_crm_next_hop_group[bjw-can-7260-16-None] - There is a known issue with broadcom dualtor
Broadcom dualtor platform
=> [XFAIL: test_crm_available.py] set xfail of test_crm_available on dualtor platform

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
`test_iface_naming_mode.py::test_config_interface_speed` is failing due to a bug in the interpretation of `config_db.json` when determining the supported speeds of an intf.
xfailing until fix for issue is made to unblock other test cases in the test file. Low priority issue as only fixed config is used.
=> xfail test_iface_naming_mode.py::test_config_interface_speed

tests/bgp/test_bgp_multipath_relax.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: Skip `bgp/test_bgp_multipath_relax.py` on t1-isolated topologies.
Skip because the test is not designed for t1-isolated and it fails.
=> Skip test_bgp_multipath_relax.py on t1-isolated

tests/bgp/test_bgp_command.py
Summary:
In `bgp/test_bgp_command.py`, the test only checks for the existence of multipath (denoted by `*=`) bgp routes - which requires having multiple uplinks and is not always the case (i.e. [topo_t1-isolated-d28u1](https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/vars/topo_t1-isolated-d28u1.yml)).
Changing the test to check for `best` bgp routes (denoted by `*>`) as well.
Account for topologies without multiple uplinks, which does not have multipath bgp entries.
Changing the test to check for `best` bgp routes (denoted by `*>`) in addition to the existing multipath bgp route check.
Test no longer fails on topo_t1-isolated-d28u1
=> Extend bgp command check to allow multipath routes and "best" routes

tests/common/snappi_tests/read_pcap.py
Summary:
Fixes #18590 
The read_pcap.py file has function "is_ecn_marked" which is checking if the packet is ECN marked or not.
However the logging is set to INFO level, which means that every packet in the PCAP when checked for ECN marking, will generate an INFO level log. For check of 1000 packets, it will generate 1000 such INFO level logs.
Reduced the severity of the log from INFO->DEBUG. 
Ran ECN marking testcase. In 'Before' output, since 9k packets are being checked for ECN marked, it will generate 9k INFO level logs. In 'After' logs, the test-case itself is printing if the packet is detected as ECN marked or not.
Before:
```
14:20:21 test_multidut_dequeue_ecn_brcm_dnx.verif L0261 INFO   | Running verification for ECN dequeue test
14:20:21 test_multidut_dequeue_ecn_brcm_dnx.verif …
```
=> [Snappi] Changed logging from info to debug for ECN packet marking

tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
This is to fix the failure reported in [MIGSMSFT-1039](https://migsonic.atlassian.net/browse/MIGSMSFT-1039)
```
FAILED snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py::test_pfc_pause_single_lossless_prio_reboot[multidut_port_info0-cold-svcstr2-8800-lc1-1|3]
FAILED snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py::test_pfc_pause_single_lossless_prio_reboot[multidut_port_info1-cold-svcstr2-8800-lc1-1|3]
FAILED snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py::test_pfc_pause_multi_lossless_prio_reboot[multidut_port_info1-cold]
```
```
        if exceeds_headroom:
            pytest_assert(tx_bytes_total > dut_buffer_size,
                          "Total TX bytes {} should exceed DUT buffer size {}".
                          format(tx_bytes_total, dut_buffer_size))
    …
```
=> MIGSMSFT-1039: calling the fixture to disable PWCWD on all DUT's in reboot test cases

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/qos/qos_sai_base.py
Summary:
Double commit of #17765
- Update test mark conditions to include dualtor-aa for every duplicate instance of the QOS SAI topo list (all lists are identical). Possible de-duplication here: #17707
- Only toggle simulator ports if active-standby. 
- Fix permissions on created empty write_standby file. 
Master PR: Ran on dualtor AA cisco-8000, verified tests execute without major errors. Some tests fail due to some normal instability and known issues. 
Double commit:
=> [202411] Dualtor AA enablement for QOS SAI

tests/platform_tests/test_link_down.py
Summary: This PR resolves the test failure in `test_link_status_on_host_reboot`, which occurs when the DUT does not become reachable via SSH within the timeout period after a reboot.
To solve the test failure when the DUT didn’t come back online in time after a reboot. Specifically, the SSH service wasn’t reachable within the expected timeout. 
Increased the SSH wait timeout after reboot to accommodate longer DUT boot times.
```
------------------- generated xml file: /data/sonic-mgmt-int/tests/logs/platform_tests/test_link_down.xml -------------------
-------------------------------------------------- live log sessionfinish ---------------------------------------------------
07:38:52 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. …
```
=> Increase SSH Wait Timeout After DUT Reboot in SN5640 Platform Tests

tests/test_posttest.py
`test_posttest.py::test_recover_rsyslog_rate_limit` iterates over the results of `show feature status` and executes the following commands:
```
docker exec -i frr_bmp sed -i 's/^#\\$SystemLogRateLimit/\\$SystemLogRateLimit/g' /etc/rsyslog.conf
docker exec -i frr_bmp supervisorctl restart rsyslogd
```
`frr_bmp` shows up in `show feature status` but it isn't a real docker container so we should skip it.
Similar PR: https://github.com/sonic-net/sonic-buildimage/pull/22588
Summary:
Fixes #18753
=> Skip `frr_bmp` in `test_posttest.py::test_recover_rsyslog_rate_limit`

tests/fib/test_fib.py
Summary:
test_fib.py: test_ecmp_group_member_flap fails when selected source port for the packet ingress is the one that is shut in the test.
#18807 
To fix failing test case test_fib.py: test_ecmp_group_member_flap
To avoid selecting the port that is shutdown, in the fix it is being removed from the set of possible ingress ports.
Verified that the test case always passes with this fix.
=> test_fib.py: test_ecmp_group_member_flap fails when selected source port is shut

ansible/roles/eos/templates/t0-isolated-d2u254s1-tor.j2, ansible/roles/eos/templates/t0-isolated-d2u254s2-tor.j2, ansible/roles/eos/templates/t0-isolated-d2u510s2-tor.j2
Summary:
In PR #18686, we set pt0 as role tor, however, there is no ceos template for it, we need to create the ceos template for tor.
In PR #18686, we set pt0 as role tor, however, there is no ceos template for it
create the ceos templates for PT0
=> [isolated-topology] Add ceos config template for PT0 in isolated topology

tests/qos/tunnel_qos_remap_base.py
Summary:
When running test_tunnel_qos_remap.py, the BGP bgpmon and bgpd service stop and start hacking does not correctly bring BGP back up on Cisco-8000 devices. Modify shutdown/startup to match QOS SAI's test fixtures, as revised by PR #15108.
Note that this only causes issues with BGP if the syncd swap is not performed (i.e. it's already loaded and --qos_swap_syncd is set to False). If the swap is performed, then the entire config is reloaded, which masks the fact that BGP didn't come back up correctly. 
Validated on dualtor-aa Cisco-8000 that BGP comes back up after running test_tunnel_qos_remap.py xoff test cases. 
Ran without doing dynamic syncd container swap, per above note about this masking the BGP issue. 
Output after test pass shown here as sessions are up for 39 seconds. 
``` …
```
=> Shutdown BGP for PCBB tests instead of stopping processes

tests/process_monitoring/test_critical_process_monitoring.py
Fix test_orchagent_heartbeat failed because orchagent freeze failed issue
The test case test_orchagent_heartbeat fails intermittently due to a failure in freezing orchagent. This issue occurs because test_monitoring_critical_processes stops orchagent, and when the test fails, it does not restart the process, leaving orchagent in a stopped state.
- Microsoft ADO **(number only)**:33034949
Add new fixture to recover all container after test_monitoring_critical_processes finished
Fix test_orchagent_heartbeat failed because orchagent freeze failed issue
=> Fix test_orchagent_heartbeat failed because orchagent freeze failed issue

tests/gnmi/helper.py
Summary:
Microsoft ADO: 33257276
test_gnmi_configdb_streaming_onchange_01 failed on KVM DUT, and test logs show that it needs more than 30 seconds to get all the results from GNMI server.
Update timeout from 30 seconds to 120 seconds.
=> Update timeout for gnmi subscribe API

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Workaround for https://github.com/sonic-net/sonic-mgmt/issues/19034
As changing port speed on 7060x6 will cause orchagent crash, resulting in subsequence test case failure. Skip it for now until the issue is fixed.
Skip test case which cause orchagent crash on 7060x6 platform
change from xfail to skip
SKIPPED [2] iface_namingmode/test_iface_namingmode.py:678: Unsupported topology
SKIPPED [2] iface_namingmode/test_iface_namingmode.py:699: Unsupported topology
SKIPPED [2] iface_namingmode/test_iface_namingmode.py: Incorrect supported speeds for 7060X6 in STATE_DB, fix TBD
============ 54 passed, 6 skipped, 4 warnings in 1778.39s (0:29:38) ============
Only on 7060x6-64pe platform
=> skip interface speed change on 7060x6 as it causes crash

tests/cacl/test_cacl_application.py
Summary:
This is a manual cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/18920 to 202505 branch.
This is a manual cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/18920 to 202505 branch.
=> [202505][DualToR] add BGP drop rules on Loopback1 via iptables (from PR #18920)

ansible/generate_topo.py, ansible/vars/topo_ft2-64.yml, ansible/vars/topo_lt2-p32o64.yml
Summary: Correct the ASN number of LT2 and FT2
Fixes # (issue) 33226573
- Correct the ASN number of FT2 to LT2. For these 2 groups we should have the same ASN.
- Added some missing code for generate_topo
=> chore: adjust ASN value for LT2 and FT2

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Fixes skip condition for test_iface_namingmode.py::TestConfigInterface::test_config_interface_speed due to ASIC limitation.
Correct the skip condition.
This is for Arista 7060X6 platform only.
=> skip speed change for Arista 7060x6 platform

tests/bgp/conftest.py, tests/bgp/test_ipv6_bgp_scale.py
Summary:
After adding announce different routes set by https://github.com/sonic-net/sonic-mgmt/pull/19041, test_ipv6_bgp_scale need to be updated to support it
1. For `test_sessions_flapping` and `test_device_unisolation`, modify the function to get ecmp routes
2. For `test_nexthop_group_member_scale`:
2.1 Modify the function to get ecmp routes
2.2 Add support to specify flap neighbor count
2.3 Sample:
To be noticed that the parameter is to specify neighbors' number to withdraw one route in test_nexthop_group_member_scale. In this test, we would withdraw 1 route from number of neighbors, the nexthop group member would be increased with the increasing with neighbors' number withdraw routes. Due to hw limitaion in some platform, the blast of nexthop group members would cause …
=> [bgp_scale] Update test_ipv6_bgp_scale to support different routes sets

ansible/roles/vm_set/tasks/main.yml
Summary:
When deploying thousands of ceos and net containers on server, we see below failure due to PTY resource restriction.
```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /dev/ptmx: no space left on device: unknown
```
The `kernel.pty.max` default value is 4096.
To solve this issue, set `kernel.pty.max` to 8192 in add-topo ansible-playbook.
Support deploy thousands of ceos/net containers on a single server.
Set `kernel.pty.max` to 8192 in add-topo ansible-playbook.
Verified by deploy physical testbed.
=> [add-topo] Set `kernel.pty.max` to 8192

ansible/library/generate_golden_config_db.py
Summary:
deploy-mg script fails while generating config for MX testbeds. Script has a typo.
#18809 
To fix deploy-mg failure on MX topology testbeds
Fix the typo in the config generation function.
Verified that deploy-mg does not fail for MX testbeds with the fix
=> deploy-mg script fails while generating config for MX testbeds

ansible/library/generate_golden_config_db.py, ansible/verify_config.py, tests/tacacs/utils.py
Summary:
Remove non-standard quote marks from two Python scripts in the ansible directory. For Python 3, things will still work. However, in cases where these scripts are executed in a Python 2 context (because the SONiC device is running an old version of SONiC), it will cause problems. This may be the case for upgrade path testing, where old versions of SONiC might be running on the device.
=> Remove special characters (special quotes) from Python scripts

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/route/test_duplicate_route.py
* Following changes in https://github.com/sonic-net/sonic-swss/pull/3587, test_duplicate_route.py needs to be updated accordingly.
* Skip the test temporarily until swss submodule update is complete to avoid failures due to a circular dependency.
Summary:
=> Fix test_duplicate_route.py as per new orchagent crash handling changes

tests/platform_tests/test_power_off_reboot.py
Summary:
From https://github.com/sonic-net/sonic-mgmt/pull/18488 it introduced a bug where if the reboot cause is power off, it will return REBOOT_TYPE_SUPERVISOR_HEARTBEAT_LOSS which fail test_power_off_reboot.
This PR fix this issue
Intercept the reboot_ctrl_dict before the test, adjusted the order of REBOOT_TYPE_SUPERVISOR_HEARTBEAT_LOSS to be last by popping the key out and putting it back again.
This will make sure that .items() will loop through the REBOOT_TYPE_SUPERVISOR_HEARTBEAT_LOSS last and get to the right condition first for test_poweroff_reboot_only
test_power_off_reboot
=> Fix test_poweroff_reboot

tests/pc/test_retry_count.py
Summary:
If the `disable_retry_count_on_peer` or `disable_retry_count_on_dut` fixtures fail, then collect the techsupport on the neighbor devices. There is already code to collect the techsupport on neighbor devices if the main test fails, but not if the fixtures fail. However, the current common cause of failures appear to be in the fixtures failing, which means the current code won't catch that.
Add `collect_techsupport_all_nbrs` to the list of fixtures needed for `disable_retry_count_on_peer` and `disable_retry_count_on_dut`.
=> Collect techsupport on neighbors if fixture fails in pc/test_retry_count

tests/common/cisco_data.py, tests/snappi_tests/cisco/helper.py, tests/snappi_tests/pfcwd/test_pfcwd_actions.py
Disabling voqWD in testcase where PFCWD is disabled and traffic is run for more than 1min. Added a method to check if dshell client is up and running
Summary:
Fixes # 
`FAILED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_disable_pause_cngtn[multidut_port_info0-port_map0] - Failed: Losses observed in lossy traffic streams`
- [X ] Test case improvement
- [X ] 202405
We had added the fixture to disable the voqWD.
https://github.com/sonic-net/sonic-mgmt/blob/939485fd3e5d890de5d94f3b7eedd44e82844180/tests/snappi_tests/pfcwd/test_pfcwd_actions.py#L18
But every tests does config reload on the DUT’s which reverses disabled voqWD config.
Hence the test was failing
FAILED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_disable_pause_cngtn[multidut_port_info0-port_map0] - Failed: Losses …
=> voqWD disabling and method to check dshellClient is running

tests/bgp/test_bgp_azng_migration.py, tests/bgp/test_bgp_suppress_fib.py, tests/common/devices/sonic.py, tests/platform_tests/sfp/test_sfputil.py, tests/platform_tests/sfp/test_show_intf_xcvr.py, tests/platform_tests/test_reload_config.py
**Summary:**
I updated the assertion statements in the following test files to include …
=> Added detailed reason for assert failure for bgp,sonic,sfp

tests/common/platform/device_utils.py, tests/platform_tests/api/test_watchdog.py, tests/platform_tests/api/watchdog.yml
Enable platform api watchdog tests for dpu. Since platform api tests need to run a http server on the dut, so when dut is dpu, we need to add a nat config for the specific api service port for the tested dpu.
The relevant PRs:
- https://github.com/sonic-net/sonic-buildimage/pull/22046
- https://github.com/sonic-net/sonic-buildimage/pull/22587
Summary:
Enable platform api watchdog tests for dpu.
Add a nat config for the specific api service port for the tested dpu.
Run the platform api watchdog tests on dpu
dpu
=> Enable platform api watchdog  tests for dpu

ansible/generate_topo.py, ansible/vars/topo_ft2-64.yml, ansible/vars/topo_lt2-p32o64.yml
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/18915
Summary: Correct the ASN number of LT2 and FT2
Fixes # (issue) 33226573
- Correct the ASN number of FT2 to LT2. For these 2 groups we should have the same ASN.
- Added some missing code for generate_topo
=> [Cherry-pick 202505] chore: adjust ASN value for LT2 and FT2

azure-pipelines.yml
[CI][master]increase pr test job timeout to 8 hours to mitigate timeout issues
The test plan has a separate timeout setting for runtime limits and it's 4~5 hours.
=> [CI][202505]increase pr test job timeout to 8 hours to mitigate timeout issues

tests/telemetry/conftest.py
Summary:
Microsoft ADO: 33257886
We will enable user_auth by default, and then telemetry test will be blocked.
Set user_auth as none before the telemetry test, and recover user_auth after the telemetry test.
Run telemetry end to end test
=> Enable user_auth for telemetry test

tests/bgp/test_bgp_session.py
Summary:
Increase timeout value to wait non-portchannel bgp neighbor to align with default hold-timer.
=> [test_bgp_session] Increase timeout to wait hold-timer expire

tests/acl/test_acl.py
ports
Summary:
Record service ports individually and add them to the acl_table_ports
https://elastictest.org/scheduler/testplan/6852a36a7f408d23fa4bdbac
=> [ACL] Record service ports individually and add them to the acl_table_ports

tests/dut_console/test_console_baud_rate.py
Summary:
Previously, test_baud_rate_boot_connect would invoke helper function `reboot` to reboot device. But this function would collect console log, which would clear console line https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/reboot.py#L342. It would cause this case fail
Use duthost.sheel to directly reboot device instead of using helper function `reboot` to avoid clearing console line
Run test
```
collected 1 item                                                                                                                                                                                        
dut_console/test_console_baud_rate.py::test_baud_rate_boot_connect PASSED …
```
=> [dut_console] Fix failure on test_baud_rate_boot_connect

tests/macsec/test_dataplane.py
Summary:
In the DT2 topology, there is a scenario where DUT and LT2 are connected via a portchannel, but it is not configured as an upstream.
The current MACsec unit test assumes all portchannels are upstream, which causes the test to fail when trying to retrieve an upstream object by iterating through portchannels.
When running tests using the t2_single_node_max topology, and enable MACsec, we encountered failures in test_dataplane test. The root cause was using requester = upstream_links[portchannels[i]["members"][0]] to get upstream_links, while some portchannels link to LT2 and is not in upstream_links. Use this way can't get proper upstream.
When iterating through portchannels, check if the current portchannel is in upstream_links. If it is not, skip the subsequent tests.
Tested the …
=> [macsec]: Improve test_dataplane for DT2 topology

tests/snmp/test_snmp_queue_counters.py
Summary:
Fix 'loganalyzer object is not subscriptable' error when using the --disable_loganalyzer option.
When running tests with the --disable_loganalyzer option, a 'loganalyzer' object is not subscriptable error occurs in the snmp/test_snmp_queue_counters.py.
The expected behavior is that tests should still run even when log analyzer is disabled.
Add a check to see if the loganalyzer instance exists before accessing loganalyzer.ignore_regex. If it doesn't exist skip the related operations.
Local testing and Elastic platform testing (https://elastictest.org/scheduler/testplan/682da599ff4b6456dcc655f7)
=> skip loganalyzer when its not instantiated

tests/ip/test_mgmt_ipv6_only.py
Summary:
Microsoft ADO: 33257886
We will enable user_auth by default, and then telemetry test will be blocked.
Set user_auth as none before the telemetry test, and recover user_auth after the telemetry test.
Run ip/test_mgmt_ipv6_only.py
=> Improve test to support user_auth mode

ansible/group_vars/vm_host/ceos.yml, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Previously we updated ceos image version to 4.32.5M to meet the needs of test server OS version upgrade to Ubuntu 24, but it's causing bgp gr failure and the issue may not be able to have a quick fix.
Roll back ceos image version to 4.29.3M.
=> Roll back ceos image version since it's causing bgp failure

azure-pipelines.yml
[CI][master]increase pr test job timeout to 8 hours to mitigate timeout issues
The test plan has a separate timeout setting for runtime limits and it's 4~5 hours.
=> [CI][master]increase pr test job timeout to 8 hours to mitigate timeout issues

ansible/setup-management-network.sh
Fixes https://github.com/sonic-net/sonic-mgmt/issues/19098
The script to setup the management network should automatically the restart the necessary services when installing the packages.
Summary:
Fixes # [19098](https://github.com/sonic-net/sonic-mgmt/issues/19098)
In a virtual testbed, when setting up management-network, the script attempts to install the bridge-utils, which requires some services to be restart and since the install is invoked by a script, the TUI waits for an input and doesnt proceed.
Use noninteractive mode and also set NEEDRESTART_MODE to automatically restart services when required.
Verified the management setup is successful
NA
NA
=> Make apt-get install non-interactive in setup-management-network

tests/qos/qos_sai_base.py, tests/qos/test_voq_watchdog.py
Summary:
Consolidate voq watchdog test cases into a single test case using parametrize to simplify the code.
A requirement from PR comments: https://github.com/Azure/sonic-mgmt.msft/pull/405
Verified on T1 testbed:
```
------------------------------- generated xml file: /tmp/qos/test_voq_watchdog_2025-06-18-00-56-38.xml --------------------------------
------------------------------------------------------- live log sessionfinish --------------------------------------------------------
01:05:43 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs
======================================================= short test summary info …
```
=> Consolidate voq watchdog testcases to single testcase

ansible/library/generate_golden_config_db.py, tests/conftest.py
Summary:
Some test cases would modify /etc/sonic/golden_config_db.json without restoring it, which would cause config incorrect
Add origin golden_config_db.json and restore it in each test
Run test
=> [golden_config_db] Add origin golden_config_db.json and restore it in each test

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/dhcp_relay/test_dhcp_relay.py, tests/dhcp_relay/test_dhcpv6_relay.py
Summary:
Move skip condition from test case into condition mark file to improve performance for dhcp_relay test
Move skip condition from test case into condition mark file to improve performance for dhcp_relay test
Run the test and verified
=> [dhcp_relay] Remove useless release skip in dhcp_relay test

tests/decap/test_decap.py
Summary: [Mellanox]Update the ecn_mode  on Mellanox to be same as other platforms, The update is for the feature https://github.com/sonic-net/sonic-buildimage/pull/22667[Mellanox] remove mlnx specific condition for the ipinip tunnel ecn_mode
=> [Mellanox]Update the ecn_mode  on Mellanox to be same as other platforms

tests/generic_config_updater/test_kubernetes_config.py
Summary: Previously, GCU/test_k8s_config.py failed on multi-asic kvm pr checker because of white space difference in stdout. To fix this issue, I changed the code to do string comparison with white-space ignorance.
=> Change to do string comparison with white-space ignorance in gcu/test_k8s_config.py

tests/acl/test_acl.py
In t1-48-lag topo, the downstream links are physical ports, the upstream links are portchannels.
This change is needed to add the links to the acl_table_ports and prevent test failure.
Summary:
- [] 202411
- [] 202505
Fix test_acl failures with t1-48-lag topo
By adding support for this topo in the test
By running the test case manually.
=> Support t1-48-lag topo for acl tests

ansible/group_vars/sonic/variables, tests/common/mellanox_data.py
Added 2 new spc5 hwskus Mellanox-SN5640-C512S2, Mellanox-SN5640-C448O16 for Nvidia SN5640 platforms. Resolve conflicts with 202505 in: #18921 
Added data to sonic-mgmt framework
Manually verified it in multiple platform tests such as platform_tests/test_reboot.py
================================================================================================================================================== short test summary info ================================================================================================================================================== SKIPPED [1] platform_tests/test_reboot.py: Skip test_soft_reboot for m0/mx and test is supported only on S6100 hwsku SKIPPED [1] …
=> Add SPC5 hwskus for SN5640 platforms (#18921)

tests/common/snappi_tests/common_helpers.py, tests/common/snappi_tests/snappi_fixtures.py
Summary: Fix t0 t1 problems related to snappi vlans config and pfcQueueGroupSize. For t0 t1 we cant setup the vlans because of the current condition. Hence blocking the test.
=> [Snappi] Fix t0 t1 setup vlan problem

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
test_ser.py is consistently failing on 202412. Xfail it and raise CSP to Broadcom to follow up.
=> [Conditional mark] Xfail test_ser.py in 202412

ansible/roles/eos/templates/t0-leaf.j2
Summary:
This PR is to enhance VM template to support route reflector.
In DT2 topologies, the BGP sessions between FT2 and LT2 are IBGP. Hence, the routes learnt from exabgp, which is also IBGP session, are not advertised to DUT.
To workaround this, this PR set VM as route reflector if the VM type is `lowerspine` or `fabricspine`.
This PR is to support route reflector in VM template.
Check VM type and enable route reflector if  VM type is `lowerspine` or `fabricspine`.
The change is verified on a physical testbed. 
No.
=> Set VM as reflector for LT2/FT2

tests/acl/test_acl.py
Summary:
Fixes #19219
Stop test failures because ACL counters weren't being updated within the previous 10s window
Increase the delay before collecting counters in `test_acl.py`
https://elastictest.org/scheduler/testplan/685d4ca77c68e1a8ec7df01e
N/A
N/A
N/A
=> Increase delay before collecting counters in `test_acl.py`

tests/show_techsupport/test_techsupport.py
Update testcase test_techsupport.py
**Summary:**
The current if condition only checks for E1031 and 720DT.
So update the if condition to:
if duthost.topo_type in ["mx", "m0", "m1"]:
**### Approach**
Update testcase test_techsupport.py
update the if condition to:
if duthost.topo_type in ["mx", "m0", "m1"]:
Verified by PR test.
=> [M1] Skip QOS check in test_techsupport

ansible/library/generate_golden_config_db.py, tests/conftest.py
Some test cases would modify /etc/sonic/golden_config_db.json without restoring it, which would cause config incorrect
Add origin golden_config_db.json and restore it in each test
Run test
Summary:
Manually cherry-pick and resolve conflict of this PR: https://github.com/sonic-net/sonic-mgmt/pull/19192
=> [202505][golden_config_db] Add origin golden_config_db.json and restore it in each test (#19192)

tests/acl/test_stress_acl.py
Update tests/acl/test_stress_acl.py
**Summary:**
Adding the if condition to:
(topo == "m1" and ("MA" in neighbor["name"] or "MB" in neighbor["name"])) or \
Update tests/acl/test_stress_acl.py
Add the if condition to:
(topo == "m1" and ("MA" in neighbor["name"] or "MB" in neighbor["name"])) or \
Verified by PR test.
=> [M1] Adapt stress ACL test to M1 topo

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Whenever CFG_MUX_CABLE_TABLE_NAME is updated we get the following error,
2025 Jun 15 22:30:03.459694 gd272 ERR mux#linkmgrd: MuxManager.cpp:297 updateProberType: Ethernet140: Unsupported link failure detection type for : software
This is a regression caused by PR : https://github.com/sonic-net/sonic-linkmgrd/pull/288.
This is not causing any functionality breakage. But log analyzer reports this new error and hence the testcase fails.
Since there is no functionality impact, we have added this error message to the list of ignored patterns.
Summary:
Fixes # 
https://github.com/aristanetworks/sonic-qual.msft/issues/624 
https://github.com/sonic-net/sonic-linkmgrd/issues/301
Loganalyzer was not aware of this newly introduced error message and was failing many of the tests.
Added a regex …
=> LogAnalyzer: Ignore a non-functional error thrown from Linkmgrd

tests/common/dhcp_relay_utils.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/dhcp_relay/conftest.py, tests/dhcp_relay/dhcp_relay_utils.py, tests/dhcp_relay/test_dhcp_counter_stress.py, tests/dhcp_relay/test_dhcp_relay.py, tests/dhcp_relay/test_dhcp_relay_stress.py
Summary:
Currently, there is no test case for dhcp relay per-interface counter stress test.
Add stress test case for dhcp relay per-interface counter to compare the actual packet count and the counter value.
Run the test case
Test plan: https://github.com/sonic-net/sonic-mgmt/pull/19138
=> [dhcp_relay] Verify per-interface counter under stress test

tests/dhcp_relay/test_dhcp_counter_stress.py
Summary:
There is not waiting in dhcpmon stress test, which would flaky fail the test due to verification happens before DB update
Add sleep before verification
Run tests
=> [dhcp_relay] Add sleep for stress dhcpmon test

setup-container.sh, tests/common/plugins/conditional_mark/issue.py
[202405]manual cherry pick PR 19116 to Fix github api rate limit issue
https://github.com/sonic-net/sonic-mgmt/pull/19116
=> [202405]manual cherry pick PR 19116 to Fix github api rate limit issue

ansible/plugins/connection/multi_passwd_ssh.py
When attempting to run an Ansible module in a newer environment (Ansible [core 2.18.6] with Python 3.12), the following error occurs:
```
yutongzhang@sonic_mgmt:/data/sonic-mgmt/ansible$ ansible -i veos_vtb vlab-01 -m config_facts -a 'source=running host=vlab-01'
vlab-01 | FAILED! => {
"msg": "Requested entry (plugin_type: connection plugin: multi_passwd_ssh setting: current_password_hash ) was not defined in configuration."
}
```
This issue is caused by the multi_passwd_ssh connection plugin referencing an option named current_password_hash, which was not defined in its configuration schema.
This PR resolves the issue by explicitly adding current_password_hash to the plugin’s configuration documentation.
Summary:
When attempting to run an Ansible module in a newer …
=> Add missing current_password_hash option in multi_passwd_ssh plugin configuration

tests/generic_config_updater/test_ecn_config_update.py
Summary:
Microsoft ADO ID: 32849826
Modified `test_ecn_config_update.py` so that it no longer requires a `WRED_PROFILE` named `AZURE_LOSSLESS`.
The `test_ecn_config_update.py` test fails on devices that do not have a `WRED_PROFILE` named `AZURE_LOSSLESS`.
Instead of updating the `WRED_PROFILE` named `AZURE_LOSSLESS`, the test now updates all WRED profiles found in `CONFIG DB` and then verifies that these updates are applied to `ASIC DB`.
**Note:** In order for this test to pass, changes on the GCU side are also needed. Here is the PR in sonic-utilities for GCU changes: https://github.com/sonic-net/sonic-utilities/pull/3910
Tested on a Mellanox switch with 3 WRED profiles, none of which were named `AZURE_LOSSLESS`. The old version of the test failed, while the new version passed.
``` …
```
=> Updating `test_ecn_config_update.py` to fix nightly test failures

tests/crm/test_crm.py
On certain platforms `test_crm_neighbor` can create commands that go beyond our character limit, resulting in errors like:
`[Errno 7] Argument list too long: '/bin/sh`
This change will chunk up the long commands into smaller batches that don't go beyond the character limit to avoid hitting these failures.
Details in: https://github.com/sonic-net/sonic-mgmt/issues/18624
A similar issue and solution has been seen in this test in the past, used the same approach:
Issue: https://github.com/sonic-net/sonic-mgmt/issues/8125
Solution: https://github.com/sonic-net/sonic-mgmt/pull/8126
Summary:
Fixes #18624
=> Batch neighbor add/del commands in `test_crm_neighbor`

tests/common/fixtures/fib_utils.py
On new single-asic fixed VOQ systems we don't need a inband port nor do we have one, this causes test_fib.py to fail with:
```
dut_inband_intfs = {}
dut_port_channels = {}
switch_type = ''
for duthost in duthosts.frontend_nodes:
cfg_facts = duts_cfg_facts[duthost.hostname]
for asic_cfg_facts in cfg_facts:
if duthost.facts['switch_type'] == "voq":
switch_type = "voq"
&gt;                   dut_inband_intfs.setdefault(duthost.hostname, []).extend(asic_cfg_facts[1]['VOQ_INBAND_INTERFACE'])
E                   KeyError: 'VOQ_INBAND_INTERFACE'
```
We can skip adding this if there is no `VOQ_INBAND_INTERFACE` as `dut_inband_intfs` is only used to skip internal ports later in the function:
```
if remote_neigh_intf in dut_inband_intfs[remote_duthost_name]:
skip = True
continue
```
=> [fib] Handle VOQ systems which don't have inband ports

tests/dualtor/test_ipinip.py
Summary:
Fix the mirror session add error due to the incorrect GRE type on Cisco platform.
Use `0x88BE` for cisco 8100.
test is passing on cisco 8101 with the fix.
```
dualtor/test_ipinip.py::test_encap_with_mirror_session PASSED                                                                                                                                                                                                          [100%]
```
=> [dualtor][cisco] Fix `test_encap_with_mirror_session`

tests/common/plugins/sanity_check/checks.py
Summary:
Fix the following error:
```
tests.common.errors.RunAnsibleModuleFail: run module bgp_facts failed, Ansible Results =>
failed = True
msg = Command failed rc=1, out=, err=Exiting: failed to connect to any daemons.
invocation = {'module_args': {'num_npus': 1, 'instance_id': None}}
_ansible_no_log = None
changed = False
stdout =
stderr =
, error:run module bgp_facts failed, Ansible Results =>
failed = True
msg = Command failed rc=1, out=, err=Exiting: failed to connect to any daemons.
invocation = {'module_args': {'num_npus': 1, 'instance_id': None}}
_ansible_no_log = None
changed = False
stdout =
stderr =
```
This issue is due to that, if the first `_check_bgp_status_helper` fails, the recover tries to restart `bgp` on the DUT; but bgpd takes time to startup, so the …
=> [sanity] Fix sanity check bgp not ready after restart

tests/generic_config_updater/test_eth_interface.py
Summary:
When interface FEC is not configured (N/A or none). The GCU rollback fails and port become operational down due to incorrect FEC.
Enhance the testcase to set FEC back to N/A (none).
When interface FEC is not configured (N/A or none). The GCU rollback fails and port become operational down due to incorrect FEC.
Enhance the testcase to set FEC back to N/A (none).
Enhance the testcase to set FEC back to N/A (none).
Verified by run test on Arista-7050CX3 M1 testbed.
=> [GCU] Enhance test_eth_interface

ansible/module_utils/port_utils.py
Summary:
Remove Ethernet512, Ethernet513 mapping for 7060X 128 port skus as they are not needed
=> Remove S2 port mappings for 7060X O128 port skus

ansible/roles/vm_set/tasks/kickstart_vm.yml
In an Ansible playbook, the `vars` field must be defined as a dictionary (i.e., a set of key-value pairs), not as a list prefixed with -. When upgrading to a newer version of Ansible, the parser may enforce stricter validation on playbook syntax, which can result in errors like the following:
```
TASK [vm_set : Kickstart VMs] **************************************************
ERROR! Vars in a Task must be specified as a dictionary. 
The error appears to be in '/var/src/sonic-mgmt/ansible/roles/vm_set/tasks/kickstart_vm.yml': line 154, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
vars:
- ansible_connection: 'network_cli'
^ here
```
This PR fixes the issue by correcting the structure of the vars section in the playbook …
=> Fix invalid vars format in playbook for Ansible compatibility.

tests/bfd/test_bfd.py
Summary:
On Nvidia paltforms, while running this test BFD session creation can fail sometime resulting in some syslog errors.
THe syncd retries in such a case and is able to create the BFD session subsequently. So these errors can be ignored.
There is already a PR handling the same errors in tests/vxlan/test_vxlan_ecmp.py: https://github.com/sonic-net/sonic-mgmt/pull/14025
Tested on Nvidia plarforms, errors can be ignored.
=> [Mellanox] Ignore the expected errors in bfd test

tests/common/helpers/ntp_helper.py
The test initiates an NTP server on PTF, which has a pool of 4 network NTP servers and sets the local clock as the preferred option. However, the local server's clock (crystal oscillator) has poor accuracy, causing the PTF's NTP server to dynamically switch to other network NTP servers in the pool. As a result, when DUT uses the PTF NTP server as the clock, synchronization becomes difficult. To  resolve the issue, remove the network NTP configuration from the pool.
Summary:
Fix ntp synchronization issue for test_ntp
Just keep one ntp clock for the ptf ntp server
Run test_ntp.py
Any
=> Fix ntp synchronization issue for test_ntp

tests/vlan/test_vlan_ping.py
Update vlan ping test to override the affection of secondary vlan ip address
Related community PR https://github.com/sonic-net/sonic-mgmt/pull/18399
Summary:
Update vlan ping test to override the affection of secondary vlan ip address
Related community PR https://github.com/sonic-net/sonic-mgmt/pull/18399
Handle the secondary ip
=> Update vlan ping test to override the affection of secondary vlan ip

tests/cacl/test_cacl_application.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:  Original PR: https://github.com/sonic-net/sonic-mgmt/pull/18834
This PR updates the iptables and ip6tables rules to block incoming BGP (TCP port 179) traffic on the `eth0` interface. This change ensures that BGP sessions are only allowed on non-management interfaces.
Fixes: _N/A_
To support test updates in this PR: [sonic-host-services#197](https://github.com/sonic-net/sonic-host-services/pull/197).  
Additionally, it ensures BGP port 179 is not exposed on the management interface (`eth0`).
On t0-64 testbed
None
N/A
_No new documentation required._
=> Update iptables to block BGP (TCP 179) traffic on eth0 - 202505

tests/srv6/srv6_utils.py, tests/srv6/test_srv6_dataplane.py
1.Add more timeout for ptf to handle a large scale of bgp packets after config reload/bgp restart/reboot
2.Add BGP route sync check
This PR would based on the https://github.com/sonic-net/sonic-mgmt/pull/18775
Summary:
Case not stable
1.Add more timeout for ptf to handle a large scale of bgp packets after config reload/bgp restart/reboot
2.Add BGP route sync check
=> Enhance PTF and BGP route sync validation of msft srv6 test cases

ansible/module_utils/port_utils.py
Support Arista-7050CX3-32S-C28S16 in port_utils
Update port_alias_to_name_map in port_utils.py
Verified by deploy C28S16 testbed.
Summary:
=> [202505][7050CX3] Support Arista-7050CX3-32S-C28S16 in port_utils (#19136)

tests/common/devices/sonic.py, tests/common/gu_utils.py
Fix test_pfcwd_status.py failure
Fix verified on marvell-teralynx platform.
Summary:
Fixes #18456 
os_version format on DUT can be in any of 202411.1, 20241100.1
On DUT `gcu_field_operation_validators.conf.json` field validator version is in format of "20241100"
Because of the version comparison issue, test case is failing.
Also added marvell-teralynx asic_name in get_asic_name
Verified by running generic_config_updater/test_pfcwd_status.py test on marvell-teralynx platform.
```
generic_config_updater/test_pfcwd_status.py::test_stop_pfcwd[single] PASSED    [25%]
generic_config_updater/test_pfcwd_status.py::test_stop_pfcwd[all] PASSED       [50%]
generic_config_updater/test_pfcwd_status.py::test_start_pfcwd[single] PASSED   [75%]
generic_config_updater/test_pfcwd_status.py::test_start_pfcwd …
```
=> [gcu]: Fix test_pfcwd_status.py failure

tests/syslog/test_syslog_source_ip.py
Ignore case when validating IPv6 address in syslog CLI output
`show syslog` CLI output shows IPv6 address in lower case.
But PTF ansible's can have IPv6 configuration in any case. This leads to test failure 
Sample Sonic PTF ansible IPv6 config:
```
ansible_hostv6 : FC00:2::32
```
Sonic DUT CLI output:
```
root@str-marvell-01:/home/admin# show syslog
SERVER IP      SOURCE IP      PORT    VRF
-------------  -------------  ------  --------
10.28.60.1     10.28.60.9     800     mgmt
100.100.100.1  100.100.100.2  800     default
200.200.200.1  200.200.200.2  800     Vrf-data
2221::1111     2221::1112     800     Vrf-data
2222::1111     2222::1112     800     default
fc00:2::1      fc00:2::32     800     mgmt      <===
```
Summary:
Fixes #18438 
Change CLI validation code in …
=> [syslog]: test_syslog_source_ip.py fix IPv6 address case issue

tests/l2/test_l2_configure.py
Summary:
Fixes # (issue) Microsoft ADO 31856103
Backport of this PR to 202411 branch 
https://github.com/sonic-net/sonic-mgmt/pull/17577
Address flakes such as https://elastictest.org/scheduler/testplan/67d6bf6e607a6896f60ddd2a?testcase=l2%2ftest_l2_configure.py&type=console
if callback.unreachable:
>           raise AnsibleConnectionFailure(
"Host unreachable in the inventory",
dark=callback.unreachable,
contacted=callback.contacted,
)
pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inventory
During config reload, the ipv4 connection can get broken and the ansible will through an exception here.
This doesn't affect the assertion of this particular test.
=> Reduce flakiness of test_l2_configure.py. Backport to 202411

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
The test is still not fully stabilized on dualtor aa setup as some failures are observed. Xfail it in 202411 and we will enhance the test in future release.
=> [Dualtor][202411] Xfail generic hash test on dualtor-aa

tests/telemetry/telemetry_utils.py, tests/telemetry/test_telemetry.py, tests/telemetry/test_telemetry_poll.py
Summary:
MS ADO: 33256194
This PR does the following:
1) Uses netstat to ensure that there is an established TCP connection between the client and server which is a more reliable check instead of pid check. This new check will help ensure that client is connected and can receive all notifications.
2) Ensures that we are giving enough time for default route to populate in APPL_DB after bgp sessions have been restored. There are some situations where we grab 10 updates, but default route has not been populated yet, so we miss the update. We will let the query run for longer and check less frequently to ensure that we see the default route entries after restoring bgp sessions.
Code change
202411 test
```
telemetry/test_telemetry_poll.py::test_poll_mode_default_route[xxxxxxxx-False] PASSED …
```
=> Fix flakiness with poll mode tests when client has not connected yet or default route has not populated yet

tests/common/plugins/sanity_check/checks.py
Summary:
Fixes #33668010
systemctl restart bgp.service fails on multi-asic devices.
Enhacne and add compatible logic for multi-asic devices.
systemctl restart bgp.service fails on multi-asic devices.
Enhacne and add compatible logic for multi-asic devices.
https://elastictest.org/scheduler/testplan/686a3db4c452a23450444da8?testcase=test_pretest.py%7C%7C%7Cvms-kvm-four-asic-t1-lag_219086&type=log
=> [sanity_check] Fix bgp recovery for multi-asic devices

ansible/library/get_ip_in_range.py, ansible/roles/test/files/ptftests/py3/pfc_wd.py, tests/common/helpers/pfcwd_helper.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/conftest.py, tests/pfcwd/test_pfcwd_all_port_storm.py, tests/pfcwd/test_pfcwd_cli.py, tests/pfcwd/test_pfcwd_function.py, tests/pfcwd/test_pfcwd_timer_accuracy.py, tests/pfcwd/test_pfcwd_warm_reboot.py
Add IPv6 test coverage for PFCWD.
Summary:
https://github.com/sonic-net/sonic-mgmt/issues/10959
https://github.com/sonic-net/sonic-buildimage/issues/17446 
This issue was raised regarding PFCWD not dropping IPv6 traffic during storm. It revealed the need for test coverage.
- I added a parametrized ip_version fixture [*tests/conftest.py*]
- This fixture is used in the setup_pfc_test fixture [*tests/conftest.py*]
- All the tests that use setup_pfc_test to initialize the TrafficPorts will create them using once with IPv4 and once with IPv6
- TrafficPorts [*tests/common/helpers/pfcwd_helper.py*] uses the ip version to determine the test interfaces' and neighbour's ip addresses
- The ip_version is used explicitly in tests with a SendVerifyTraffic class …
=> [Test gap] Add coverage for IPv6 traffic to the PFCWD PTF test cases

ansible/generate_topo.py, ansible/vars/topo_t0-isolated-d128u128s2.yml, ansible/vars/topo_t0-isolated-d256u256s2.yml, ansible/vars/topo_t0-isolated-v6-d16u16s2.yml, ansible/vars/topo_t0-isolated-v6-d256u256s2.yml, ansible/vars/topo_t0-isolated-v6-d32u32s2.yml
Summary:
Peer T0 is using 2 bytes ASN in t0-isolated-v6 topo. Update the topo file with correct settings.
Update t0-isolated-v6 topo with correct PT0 ASN settings.
=> correct PT0 ASN number in t0-isolated-v6 and full topo.

tests/hash/test_generic_hash.py
Update generic hash script to fix error log during test execution.
There were error logs randomly during the test on **dualtor** setup:
```
ERR swss#orchagent: :- setSwitchHash: Failed to remove switch ECMP hash configuration: operation is not supported
ERR swss#orchagent: :- doCfgSwitchHashTableTask: Failed to set switch hash: ASIC and CONFIG DB are diverged
```
Summary:
There were error logs randomly during the test:
```
ERR swss#orchagent: :- setSwitchHash: Failed to remove switch ECMP hash configuration: operation is not supported
ERR swss#orchagent: :- doCfgSwitchHashTableTask: Failed to set switch hash: ASIC and CONFIG DB are diverged
```
Replace duthost by rand_selected_dut in case test_hash_capability, test_backend_error_messages, test_algorithm_config
Run it in …
=> [Dualtor] Update generic hash script to fix error log 

ansible/vars/topo_t1-smartswitch-ha.yml
Summary:
Default loopback address is identical on all DUTs. Need to explicitly set it to a different value on 2 DUTs, otherwise tunnel won't work. 
Tested on internal testbed with deploy-mg. Loopback0 was configured as expected.
=> [ssw][ha] add loopback0 config to DUT in topo file

tests/voq/test_voq_nbr.py
Summary:
Fixes #19331
(From #19331) Fix testcase `voq/test_voq_nbr.py::TestNeighborLinkFlap::test_front_panel_linkflap_port` fails on condition `table state delay is not reachable`. This is because the test expects the ARP table to update instantly from `STALE` to `REACHABLE` after a ping is sent, which is the case for non-portchannel interfaces, however there is a small 2-3s delay state for portchannel interfaces `STALE` -> `DELAY` (2-3s) -> `REACHABLE`
Implement a `wait_until` for ARP repopulation after a linkflap, similar to other testcases in the same test module
Ran it 5 times to ensure it's not flaky. https://elastictest.org/scheduler/testplan/6865300c3d76d955497fbe94?leftSideViewMode=detail
3x pass on minor iteration: https://elastictest.org/scheduler/testplan/686635aa6bbbe4a384a7bf …
=> Add wait_until for ARP population on linkflap testcase in test_voq_nbr.py 

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Manual cherry-pick of #19078 to 202411 due to conflicts
Skip running tests on topologies that don't support it causing redundant test runs.
Added a check to skip the test on non-T0 testbeds.
Only run it on t0 testbeds from now on.
Summary:
=> Skip multi-hop upgrade tests on non-T0 testbeds [cherry-pick to 202411]

setup-container.sh
The PR https://github.com/sonic-net/sonic-mgmt/pull/19116 adds -e args for setup-container.sh for all PR test pipelines.
This PR is to cherry pick the change of adding -e for setup-container to fix github api rate limit issue.
=> [202305] Cherry pick the change of adding -e for setup-container to fix github api rate limit issue

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: skipped generic_config_updater.test_pfcwd_status for non-supported hwsku SN5640 and Arista7060X6PE 
Skipped generic_config_updater.test_pfcwd_status for non-supported hwsku SN5640 and Arista7060X6PE 
Add non-supported hwsku to conditional markers
Veried it in sonic mgmt test generic_config_updater.test_pfcwd_status
str4-sn5640-3
t1-isolated-d56u1-lag
=> [test_pfcwd_status] skipped generic_config_updater.test_pfcwd_status for non-supported hwsku SN5640 and Arista7060X6PE 

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/everflow/everflow_test_utilities.py, tests/everflow/test_everflow_testbed.py
Summary:
- A new test case has been added to make sure mirrored packets are sent on the recycle port via the specific queue configured under mirror session config.
- To make sure specific queue configuration under mirror session config is verified.
- And to make sure the mirrored packets are sent on the recycle port via the specific queue configured.
- Added a new test case to verify mirrored packets are sent via the specific queue configured under mirror session config.
- Ran the test on T2 VOQ chassis and made sure the tests are passing.
=> Everflow - Test for recycle port queue counter

tests/syslog/test_logrotate.py
Summary:
Fixes #33258706
[logrotate] Fix the issue that no logs will be consider as non-zero return in grep
Fix the issue that no logs will be consider as non-zero return in grep
Ignore errors of grep return
Tested on physical testbeds and it works well
=> [logrotate] Fix the issue that no logs will be consider as non-zero return in grep

ansible/library/nut_allocate_ip.py, ansible/library/nut_test_facts.py, ansible/roles/testbed/nut/tasks/testbed_facts.yml, ansible/vars/nut_topos/nut-2tiers-backend.yml, ansible/vars/nut_topos/nut-2tiers.yml, ansible/vars/nut_topos/nut-single-dut.yml, docs/testbed/README.testbed.NUT.md
Summary:
When defining the testbeds, it turns to be many testbeds will share the same topology. Repeating this info in all the testbeds is not ideal.
Extracted DUT template and TG template out of the testbed definition and make them a topology for NUT.
Yes, deployed the testbed locally and all passing.
```
./testbed-cli.sh -t testbed.nut.yaml gen-cfg nut-sn5640-stress-1 ixia ../../password.txt
```
No.
NUT testbeds.
Included in PR.
=> Add topology support for NUT testbeds.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip warm/fast reboot cases on dualtor.
Add those cases to the conditional mark skip list.
```
vrf.test_vrf.TestVrfWarmReboot.test_vrf_swss_warm_reboot
vrf.test_vrf.TestVrfWarmReboot.test_vrf_system_warm_reboot
gnmi.test_gnoi_system_reboot.test_gnoi_system_reboot_warm
mvrf.test_mgmtvrf.TestReboot.test_warmboot
mvrf.test_mgmtvrf.TestReboot.test_fastboot
sflow.test_sflow.TestReboot.testFastreboot
sflow.test_sflow.TestReboot.testWarmreboot
```
```
mvrf/test_mgmtvrf.py::TestReboot::test_fastboot SKIPPED (Dualtor topology doesn't support warm-reboot)           [100%]
mvrf/test_mgmtvrf.py::TestReboot::test_warmboot SKIPPED (Dualtor topology doesn't support warm-reboot)           [100%] …
```
=> [dualtor] Skip warm/fast reboot cases on dualtor

tests/dualtor_io/test_link_failure.py
Summary:
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/18829 into 202505
Signed-off-by: Longxiang Lyu [lolv@microsoft.com](mailto:lolv@microsoft.com)
=> [dualtor-io] Fix test_active_link_admin_down_config_reload_link_up_downstream_standby on Cisco/MLNX

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip unsupported everflow testcases on Nokia-7215.
Skip unsupported everflow testcases on Nokia-7215.
Skip testcase via condition mark.
Verified on Nokia-7215 M0:
```
everflow/test_everflow_per_interface.py::test_everflow_per_interface[ipv4-erspan_ipv4-m0_vlan_scenario] PASSED                                                        [  6%]
everflow/test_everflow_per_interface.py::test_everflow_packet_format[ipv4-erspan_ipv4-m0_vlan_scenario] PASSED                                                        [ 12%]
everflow/test_everflow_per_interface.py::test_everflow_per_interface[ipv4-erspan_ipv4-m0_l3_scenario] PASSED                                                          [ 18%]
everflow/test_everflow_per_interface.py::test_everflow_packet_format[ipv4-erspan_ipv4-m0_l3_scenario] …
```
=> [7215] Skip unsupported everflow testcases

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: This enable qos_sai_test support for ft2-64, lt2-p32o64 and lt2-o128
Fixes # (issue) 33702469
Enable conditional mark
=> [DT2] Enable qos_sai for dt2

tests/everflow/test_everflow_per_interface.py
Summary:
This PR is to fix [test_everflow_per_interface.py](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:fix_everflow_per_interface_on_lt2?expand=1#diff-6d0768046d4041cf91f44c70f9910c4f782d20c768315ddf2ec663a878ef69e1) on LT2 and FT2.
The test can't pass on LT2/FT2 because TTL is decrease by 1 mistakenly. 
This PR is to fix [test_everflow_per_interface.py](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:fix_everflow_per_interface_on_lt2?expand=1#diff-6d0768046d4041cf91f44c70f9910c4f782d20c768315ddf2ec663a878ef69e1) on LT2 and FT2.
Only decrease TTL on chassis T2.
Change is verified on LT2 testbed.
```
collected 4 items …
```
=> Fix everflow_per_interface test on LT2/FT2

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/16935
Summary:
=> Enable skipped BFD and VxLAN tests on smartswitch T1

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Due the design code change https://github.com/sonic-net/sonic-buildimage/pull/21868, it set IPinIP tunnel dscp mode default value from uniform to pipe. The skip condition for decap/test_decap.py on Mellanox platform need to be updated.
Summary:
Due the design code change https://github.com/sonic-net/sonic-buildimage/pull/21868, it set IPinIP tunnel dscp mode default value from uniform to pipe.
The skip condition for decap/test_decap.py on Mellanox platform need to be updated.
=> Update skip condition for test_decap.py

tests/everflow/test_everflow_per_interface.py
Summary:
In the test everflow/test_everflow_per_interface.py::test_everflow_per_interface
When the erspan version is IPv6 and the topo is t0, there will be a storm in the vlan when the test packet is sent to the dut.
And the test fails sometimes because the flooded packets are all sent to ptf and the ptf is not able to finish the poll in timeout.
AssertionError: Did not receive expected packet on any of ports [29] for device 0.
========== EXPECTED ==========
Mask:
packet status: OK
packet:
0000  00 01 02 03 04 05 B0 CF 0E 39 76 00 86 DD 62 00  .........9v...b.
0010  00 00 00 7E 2F 04 11 11 00 00 00 00 00 00 00 01  ...~/...........
0020  00 01 00 01 00 01 22 22 00 00 00 00 00 00 00 02  ......""........
0030  00 02 00 02 00 02 00 00 89 49 00 00 00 00 00 00  .........I......
0040  00 00 00 …
=> Fix everflow test for erspan V6

tests/platform_tests/conftest.py
PR #16573 added some fixtures for getting port information for sfp tests, however when these fixtures run on supervisor nodes, it fails as sfputil is not valid for supervisors.
Add a check in these fixtures to skip supervisor nodes
Summary:
- [ x] Bug fix
- [x ] 202405
- [ x] 202411
Tested on nokia 7250 chassis
=> [platform_tests/sfp]: Skip getting sfp info for supervisor

tests/common/devices/eos.py
Ignore case for speed regex when looking up interface speeds on eos. Newer versions of EOS changed the format from "Speed/Duplex" to "Speed/duplex", causing failures when working with fanouts/ devices with newer EOS versions
Summary:
- [ x] Bug fix
- [ x] 202405
- [ x] 202411
- [x ] 202505
https://elastictest.org/scheduler/testplan/687076b73e9a888e73a505b8
=> [devices/eos]: Ignore case when searching for interface speeds

tests/disk/test_disk_exhaustion.py
Enhance test_disk_exhaustion with leaving some free space to avoid kernel errors.
The allocation still appears to succeed even when it returns an error like:
`fallocate: fallocate failed: No space left on device`
```
admin@sonic:~$ df /tmp
Filesystem     1K-blocks      Used Available Use% Mounted on
root-overlay   229572940 102699796 126856760  45% /
admin@ sonic:~$ fallocate -l 229572940k /tmp/huge_dummy_file         
fallocate: fallocate failed: No space left on device
admin@ sonic:~$ 
admin@ sonic:~$ df /tmp
Filesystem     1K-blocks      Used Available Use% Mounted on
root-overlay   229572940 229556556         0 100% /
```
@kebol@nvidia.com mentioned that when allocate 100% may cause kernel errors like:
```
2025 Jun 18 07:12:22.363360 sonic_testbed ERR kernel: [ 1009.228833] loop: …
```
=> Enhance test_disk_exhaustion with leaving some free space to avoid kernel errors

tests/vxlan/test_vxlan_bfd_tsa.py
Add assert when checking vnet route asic installation
Summary:
When using wait until function, it would not fail the case when it exit wait until function due to timeout.
Add assert when checking vnet route asic installation. 
=> Enhance test_vxlan_bfd_tsa test

tests/qos/qos_sai_base.py
resolve conflicts of [#14763 ](https://github.com/sonic-net/sonic-mgmt/pull/14763)
Summary:
LLDP daemons were previously disabled in the test. Not all daemons were disabled, resulting in leftover daemons raising errors in the log. The change will disable the entire container to avoid such cases.
Example for such log errors can be seen in the https://github.com/sonic-net/sonic-mgmt/pull/12375
Add function updateFeatureState to disable LLDP container.
Run the test_qos_sai test to verify it works.
=> Disable LLDP container in test_qos_sai (resolve conflicts for 14763)

tests/scripts/dual_tor_sniffer.py
Summary:
Fix the dualtor sniffer not capture any packets:
```
dualtor_io/test_normal_op.py::test_normal_op_upstream[active-active] 
03:52:04 dual_tor_io.examine_flow                 L0691 ERROR  | self.all_packets not defined.
PASSED  
```
```
14/07/2025 05:12:15 dual_tor_io.examine_flow                 L0706 INFO   | Number of filtered packets captured: 0
14/07/2025 05:12:15 dual_tor_io.examine_flow                 L0708 ERROR  | Sniffer failed to capture any traffic
```
**Why `dual_tor_sniffer cannot capture any I/O?**
For scapy 2.5.0 and above, the `L2ListenSocket` uses `getsockname()` to retrieve the socket hardware type [1], and the socket hardware type is used to build the packet [2] …
=> [dualtor] Fix sniffer not capture packets

tests/snappi_tests/pfcwd/test_pfcwd_burst_storm_with_snappi.py, tests/snappi_tests/pfcwd/test_pfcwd_m2o_with_snappi.py, tests/snappi_tests/pfcwd/test_pfcwd_runtime_traffic_with_snappi.py, tests/snappi_tests/test_multidut_snappi.py
Added support for tgen-port-info for the PFCWD testcases.
Testcases modified:
```
tests/snappi_tests/pfcwd/test_pfcwd_runtime_traffic_with_snappi.py
tests/snappi_tests/pfcwd/test_pfcwd_m2o_with_snappi.py
tests/snappi_tests/pfcwd/test_pfcwd_burst_storm_with_snappi.py
tests/snappi_tests/test_multidut_snappi.py
```
Summary:
The support for dynamic and static port selection during test execution is available. Modified the PFCWD testcases to have that support.
1. Added the num_tx_rx_ports to ensure that test ONLY uses limited number of ports.
2. Removed old and unused imports.
3. testbed_config, port_config_list and snappi_ports are now defined using tgen_port_info.
Ran on multidut-tgen environment with both static and dynamic port selections.
Logs:
``` …
```
=> [Snappi]: Modified PFCWD testcases with tgen-port-info support

ansible/generate_topo.py, ansible/vars/topo_t0-isolated-d96u32s2.yml, ansible/vars/topo_t0-isolated-v6-d96u32s2.yml, ansible/veos
Summary:
update topo t0-isolated-d96u32s2 with the following:
1. use /22 for bp_interfaces
2. correct typo for router-id in ipv6 only topo
3. update PT0 ASN to 2 bytes in ipv6 only topo
4. Add d96u32s2 support into veos
update topo t0-isolated-d96u32s2 with the following
=> [TH5] update t0-isolated-d96u32s2 topo

tests/bgp/test_bgp_suppress_fib.py
Summary:
With exabgp version 4.x, it doesn't accept "withdraw attribute", only accepting "withdraw attributes". The issue has been fixed in https://github.com/Exa-Networks/exabgp/commit/2946f34bd3d202faaa744601b952a481fae2fda2, but it's not included in 4.2.x version yet.
When running test_bgp_suppress_fib.py test case, it will failed to withdraw the routes, and result in following failures.
```
vmhost = <EosHost VM92012>, route_list = ['91.0.1.0/24', '91.0.2.0/24']
bgp_neighbor = '10.0.0.192', vrf = 'default', ip_ver = 4, exist = False
def validate_route_propagate_status(vmhost, route_list, bgp_neighbor, vrf=DEFAULT, ip_ver=IP_VER, exist=True):
"""
Verify ipv4 or ipv6 route propagate status
:param vmhost: vm host object
:param route_list: ipv4 or ipv6 route list
:param bgp_neighbor: ipv4 …
```
=> Fix test_bgp_suppress_fib.py failure with exabgp 4.x version

ansible/vars/configdb_jsons/7nodes_cisco/PE1.json, ansible/vars/configdb_jsons/7nodes_cisco/PE2.json, ansible/vars/configdb_jsons/7nodes_cisco/PE3.json, tests/srv6/test_srv6_basic_sanity.py
Summary:
Update the test case for srv6 based on 7nodes_cisco.
Currently FRR limits the function length up to 20 bits for a srv6 locator, but the configuration in 7nodes_cisco topology is 32 bits. Let's change it as 16 (less than 20).
Update the configuration for locator and SID in 7nodes_cisco, and update the test case for srv6 according to the new value.
This test case is a part of project Phoenix Wing, and the changes have been verified on its vSONiC testbed.
=> SRv6: Update SRv6 test case to align with 16-bit locator function length

tests/qos/files/qos_params.th5.yaml
Summary:
This pull request includes a minor update to the `qos_params` configuration in the `tests/qos/files/qos_params.th5.yaml` file. The change adds a new topology reference.
This pull request includes a minor update to the `qos_params` configuration in the `tests/qos/files/qos_params.th5.yaml` file. The change adds a new topology reference.
=> chore: add topo-lt2-p32o64 in qos_params

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Add an xfail for `test_cont_link_flap` based on issue https://github.com/sonic-net/sonic-buildimage/issues/23121 for t1-lag topology on SN2 devices
Summary:
Make `test_cont_link_flap` failures to be expected
Since the issue was observed only on SN2 devices with t1-lag topo, we added these conditions to the xfail
=> skip test_cont_link_flap on SN2 and t1-lag due to issue 23121

tests/route/test_route_flap.py
We currently have a condition in this test case that searches for the string "Ethernet" in the port alias mapping. However, some platforms use "etp" in the alias, which causes the test to fail on those platforms. Rather than explicitly adding support for "etp", it would be more robust to remove this check entirely to better accommodate future devices and variations in port alias naming.
Summary:
To fix test_route_flap on x3b platforms.
By removing a condition that checks for Ethernet string in port alias mapping
Ran on x3b platforms in msft lab.
=> Adding fix for port_alias mapping in test_route_flap.py

tests/test_pktgen.py
On multi-asic systems the kernel interfaces of the front panel ports live in the per-asic namespace.
E.G.
```
> ifconfig | grep -i Ethernet0
> sudo ip netns exec asic0 ifconfig | grep Ethernet0
Ethernet0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9100
```
Meaning commands like `echo 'add_device Ethernet0' > /proc/net/pktgen/kpktgend_0` need to be run within the asic namespace.
=> Add multi-asic support to `test_pktgen.py`

tests/common/devices/multi_asic.py
In critical_services_tracking_list it previously only removed disabled features from the critical services list on modulars.
We can have disabled features on non-modulars as well.
Also handle the case where the feature is missing from config_db.
This came up in the context of the `bmp` feature which can be enabled/disabled.
It's being added to the `DEFAULT_ASIC_SERVICES` in https://github.com/sonic-net/sonic-mgmt/pull/18653
=> Exclude disabled/missing features on non-modulars as well in `critical_services_tracking_list`

tests/telemetry/test_telemetry.py
Summary:
YANG validation is not done during config reload in 202411 test, master branch backport to 202411 carried this change to check for yang_validate parameter which would not exist.
Removed yang_validate argument from config reload
Pipeline
=> [202411] Remove yang_validate option from test_telemetry test

tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py
Summary: Fix `qos/test_qos_sai.py` for active-active dualtor
Fixes [#636](https://github.com/aristanetworks/sonic-qual.msft/issues/636), [#670](https://github.com/aristanetworks/sonic-qual.msft/issues/670)
The following testcases fail on active-active dualtor 
1. testQosSaiPgSharedWatermark
2. testQosSaiQSharedWatermark
These tests involve shutting down the Tx on the egress interface and then fill up the buffers to get the reading of shared watermark. In case of active-active DualToR there is gRPC traffic flowing between the DUT and the NIC SImulator which fills up the buffers earlier than expected leading to incorrect results and test failures.
Also the test is selecting invalid destination IP addresses
The proposed fix is as follows -
1. Fix host address selection/assignment by …
=> Fix qos/test_qos_sai.py for active-active dualtor

tests/platform_tests/api/test_watchdog.py
Current memory utilization checks are taking longer time that leads to watchdog getting triggered before disarm.
since all tests in `platform_tests/api/test_watchdog.py` focuses on precision of watchdog timeout , its better to disable memory utilization check for these tests
Summary: Fix platform_tests/api/test_watchdog.py failure
Fixes #19302 
multiple test cases from platform_tests/api/test_watchdog.py are failing with `exceptiongroup.ExceptionGroup: errors while tearing down`.
disabled memory utilization check for these tests, as all tests here focuses on precision of watchdog timeout.
=> Disable memory utilization checks for `platform_tests/api/test_watchdog.py`

tests/srv6/test_srv6_dataplane.py
Summary:
Add wait time for DUT to get neighbour mac after config reload in srv6/test_srv6_dataplane.py.test_srv6_dataplane_after_config_reload if MAC address is not currently ready
Fixes `IndexError: list index out of range` errors after config reload in srv6/test_srv6_dataplane.py.test_srv6_dataplane_after_config_reload
=> Add wait time to get neighbor mac for SRv6 tests

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip SRv6 tests for non Arista-7060X6-64PE-B-* TH5 SKUs and t0-isolated-d96u32, t1-isolated-d32/128 topologies
=> Add additional SRv6 test skip conditions for TH5

tests/bgp/test_bgp_router_id.py
Summary: This PR will address BGP test failure for FT2 route since it doesn't broadcast loopback ipv4
We ignore the FT2 neighbor during this check.
=> fix: test_bgp_router_id_set for lt2

ansible/roles/test/files/helpers/bfd_responder.py
Summary:
bfd_responder (used by bfd/test_bfd.py) is failing to start in the PTF container with the following error:
```
File "/opt/bfd_responder.py", line 213, in <module>
main()
File "/opt/bfd_responder.py", line 190, in main
curr_session["mac"] = get_mac(str(bfd["ptf_intf"]))
File "/opt/bfd_responder.py", line 31, in get_mac
return get_if(iff, SIOCGIFHWADDR)[18:24]
File "/opt/bfd_responder.py", line 24, in get_if
ifreq = ioctl(s, cmd, struct.pack("16s16x", iff))
struct.error: argument for 's' must be a bytes object
```
After adding the modifications, in this PR, the test is finally passing:
Pls see description. The bfd_responder was not able to start in the ptf container.
Updated the script with more recent python functions.
Ran it on a TB, pls see …
=> Adding fixes for bfd_responder, it is giving a bunch of failures.

tests/bgp/test_bgp_queue.py, tests/bmp/test_bmp_statedb.py, tests/dualtor/test_orchagent_slb.py
**Summary:**
I updated the assertion statements in the following test files to include descriptive error …
=> Added detailed reason for assert failure for bgp,bmp,dualtor

tests/common/helpers/ptf_tests_helper.py
Add interface up check in function apply_dscp_cfg_setup to make sure port up before dscp mapping test
Summary:
Avoid of test failure due to port not up.
Add interface up check in function apply_dscp_cfg_setup to make sure port up before dscp mapping test.
=> Add interface up check in function apply_dscp_cfg_setup

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Skip SRv6 uDT46 test on mellanox platform
Due to not support in design
Summary:
Skip SRv6 uDT46 test on mellanox platform
Due to not support in design
Skip SRv6 uDT46 test on mellanox platform
Added it into skip list locally
=> Skip SRv6 test_srv6_static_config.py::test_uDT46_config test on mellanox platform

ansible/roles/vm_set/tasks/kickstart_vm.yml
Summary:
As part of the commit [`56cf79b`](https://github.com/sonic-net/sonic-mgmt/commit/56cf79bddfad388d1b7919745a1673a4cd43ebe2), where image filename variables were moved from `ansible/group_vars/vm_host/main.yml` to platform-specific group vars (`vm_host/veos.yml`, `vm_host/vsonic.yml`,`vm_host/vcisco.yml` etc.) but `kickstart_vm.yml` was not updated accordingly for veos testbeds. 
So, when deploying virtual or KVM testbeds for veos VMs, the `kickstart_vm.yml` playbook fails with an undefined variable error during the `Respin failed vm` task:
`hdd_image_filename` is undefined or 
`cd_image_filename` is undefined
`Respin failed vm` task in kickstart_vm.yml fails with 'hdd_image_filename' variable is undefined for veos VMs in virtual testbeds. Similarly for the …
=> Fix undefined veos image filename variables in kickstart_vm.yml

tests/generic_config_updater/test_lo_interface.py
The original change was included in https://github.com/sonic-net/sonic-mgmt/pull/15236/files. 
However, the code changes were handled in a different PR. This PR only adds support for T2.
Summary:
- [ X] 202405
Ran in kvm-t0, t2 chassis.
=> [GCU] Adding t2 support in gcu lo test case

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skipped Everflow IPv6 tests failing on Arista 7060CX due to a Broadcom SAI issue
Arista 7060CX also has the same SAI issue as 7260CX3, which causes Everflow IPv6 tests to fail (#19096):
```
ERR syncd#syncd: [none] SAI_API_ACL:_brcm_sai_acl_xgs_create_entry:6142 field entry install failed with bcm error Feature unavailable (0xfffffff0).#012!!!
```
Skipped the Everflow IPv6 tests on Arista 7060CX as well.
Arista 7060CX
=> Skipped Everflow IPv6 tests on Arista 7060CX due to SAI issue

ansible/config_sonic_basedon_testbed.yml
Summary: Some of the test disable ipv6 on devices. If the test were halted halfway and cannot reach recovery code, the testbed will have ipv6 disabled and caused unexpected behavior. 
This will enhance our deploy-mg script to make sure that ipv6 is enabled.
Fixes # (issue) 33852458
Adjust deploy-mg step
T2 devices
=> Enable ipv6 for deploy-mg

tests/fib/test_fib.py
Summary:
Fixes # ([665](https://github.com/aristanetworks/sonic-qual.msft/issues/665))
- test_ipinip_hash is failing because ptf_test_port_map params is fetched using “ptf_test_port_map” instead of “ptf_test_port_map_active_active”
By using dualtor-aa supported ptf port mapping for ipinip_hash test
Tested on Arista-7050CX3 running dualtor-active-active topology
=> [sonic-mgmt]Fix for fib/test_fib.py::test_ipinip_hash for active-active topology variants

tests/snmp/test_snmp_phy_entity.py
**Added detailed Reason for Assert failure**
**Summary:**
The motivation is to improve test debuggability by adding detailed failure reasons in assertions for selected test cases. This enhancement makes it easier to identify the root cause of test failures in logs, thereby reducing triage time and simplifying test maintenance
I updated the assertion statements in the following test files to include descriptive error …
=> Added detailed reason for assert failure for snmp

tests/common/platform/device_utils.py, tests/platform_tests/test_platform_info.py
Skip PSUs listed under skip_modules, to avoid false alarms during test_platform_info.py tests
For Cisco 8808 chassis, PSUs are installed by rows and not by single PSU. 
Therefore, when row of PSU is installed and if any PSU in that row is not plugged in with PDU, status of PSU will be displayed as 'NOT OK'.
currently, if we have "NOT OK" status, test_platform_info will automatically skip the test and resulting a failure. 
This PR is to address this issue, by skipping PSUs based on inventory file declaration. 
Summary:
This pull request enhances the PSU testing framework by introducing the ability to skip specific PSUs based on an inventory configuration. The changes ensure that skipped PSUs are excluded from status checks and power toggle tests, improving test reliability and …
=> Skip PSUs listed under skip_modules

tests/conftest.py, tests/dash/conftest.py, tests/route/conftest.py, tests/vxlan/conftest.py
Two option strings, `--num_routes` and `--skip_cleanup` conflict between a couple of test suites.  This causes `./run_tests.sh` when executing test cases simultaneously (such as when running the full suite) to exit with an error of something like:
```
argparse.ArgumentError: argument --num_routes: conflicting option string(s): --num_routes
```
Move these arguments into the global scope from their conflicting locations.
Fixes https://github.com/sonic-net/sonic-mgmt/issues/5526
Make running all tests pass
Move conflicting options to global scope.
```
./run_tests.sh -n vms-kvm-t0 -d vlab-01 -f vtestbed.yaml -i ../ansible/veos_vtb -e "--neighbor_type=sonic" -t t0,any
```
=> argparse conflicting option string

ansible/templates/minigraph_meta.j2, ansible/templates/minigraph_png.j2, ansible/templates/topo_lt2_128.j2, ansible/templates/topo_lt2_p32o64.j2, ansible/vars/topo_lt2-o128.yml, ansible/vars/topo_lt2-p32o64.yml, tests/bgp/test_bgp_peer_shutdown.py, tests/bgp/test_bgp_update_replication.py, tests/bgp/test_bgp_update_timer.py
Summary: Adjust the LT2 type to `LowerSpineRouter` and its VM neighbors. 
Also updated some test cases to include LowerSpineRouter
Fixes # (issue) 33894729
=> chore: change the type LT2 to LowerSpineRouter

tests/dash/configs/privatelink_config.py, tests/dash/packets.py
Summary:
From this PR, https://github.com/sonic-net/sonic-swss/pull/3763 outbound_direction_lookup of 'dst_mac' would be for FNIC scenario. setting this for VM mode operation would fail. Thus update the test 
Remove the outbound_dir_lookup from the DASH_APPLIANCE_TABLE and modify the packets to have the correct INNER_MAC attributes.
Ran the tests and verified
=> [Dash] Fix the tests for VM Mode

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary: cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/15940
=> [202411] Ignore auditd error in loganalyzer

ansible/library/announce_routes.py
Summary:
This PR is to improve [ansible/library/announce_routes.py](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:fix_announce_route_for_dt2?expand=1#diff-68b518f15cfb2d75f404b5d982cd1b23244d0775494df25b73f029842c384ec0) to support scenario when the number of VMs is not exactly divisible by `GROUP_SIZE`.
Before this change: The last group doesn't have route advertised from exabgp.
After this change: All groups have routes from exabgp.
This PR is to improve ansible/library/announce_routes.py for DT2.
Use `ceil` to get the correct number of groups.
The change is verified by running `announce_routes` on a physical testbed.
No.
=> Fix announce_route for DT2

tests/bfd/test_bfd.py, tests/platform_tests/sfp/test_sfpshow.py, tests/route/test_static_route.py
This PR is the cherry pick PR to 202505
[Added detailed reason for assertfailure by bachalla · Pull Request #18426 · sonic-net/sonic-mgmt](https://github.com/sonic-net/sonic-mgmt/pull/18426)
**Summary:**
The motivation is to improve test debuggability by adding detailed failure reasons in assertions for selected test cases. This enhancement makes it easier to identify the root cause …
=> [202505]Add detailed reason for Assertfailure for bfd,sfp,route

tests/snappi_tests/pfc/files/lossless_response_to_external_pause_storms_helper.py, tests/snappi_tests/pfc/files/lossless_response_to_throttling_pause_storms_helper.py, tests/snappi_tests/pfc/files/m2o_fluctuating_lossless_helper.py, tests/snappi_tests/pfc/test_lossless_response_to_external_pause_storms.py, tests/snappi_tests/pfc/test_lossless_response_to_throttling_pause_storms.py, tests/snappi_tests/pfc/test_m2o_fluctuating_lossless.py
Previously, the background priorities are hardcoded. 
Now the changes are incorporated to randomly pick priorities from available list of background priorities. 
Each time, it will pick different background priorities so that it can cover all different priorities. 
Summary:
Fixed both helper file and test case to pick priorities on the fly.
- [ x] Test case improvement
To cover all available list of priorities. 
Tested against a DUT internally
=> Removed hardcoded priorities for background flows and incorporated the changes to pick background priorities from available list of priorities.

tests/dualtor/test_orchagent_standby_tor_downstream.py
test was failing due to missing ptftest files. Add fixture to copy files to ptf.
Summary: Fix test_standby_tor_downstream test by copying ptftest files to ptf
test_standby_tor_downstream was failing due to missing ptftest files on ptf
imported pytest fixture to copy test files
ran on testbed with change
None
N/A
N/A
ADO: 33739975
=> [dualtor] fix test_standby_tor_downstream failure

pylintrc
Remove discontinued options from pylintrc.
Summary:
tests/common2 is enforced with pylintrc. Remove discontinued options.
Remove discontinued options from rc file.
Run pylint
NA
NA
NA
=> [pylintrc] remove discontinued options

tests/generic_config_updater/test_srv6.py
Summary:
test_srv6 uses _enum_rand_one_per_hwsku_frontend_hostname_ fixture to select the dut, which is different from the one used by _ignore_expected_loganalyzer_exceptions_ fixture in conftest.
This results in 2 different duts to be selected sometimes. This leads us to the issue where errors of the pattern "ERR sonic_yang." are not ignored by loganalyzer.
This is not seen consistently beacuse there is a probability that same device might be randomly be selected in some scenarios where it wont fail.
Fixes # 
[(issue)](https://github.com/sonic-net/sonic-mgmt/issues/19411)
https://github.com/aristanetworks/sonic-qual.msft/issues/664
Failure of test_srv6.py
I've added fix to use _rand_one_dut_hostname_ in the test_srv6 which is also used by _ignore_expected_loganalyzer_exceptions_ fixture. …
=> Fix generic_config_updater/test_srv6 to use the correct fixture to select dut

tests/crm/test_crm_available.py
Summary:
Fix crm/test_crm_available.py by adding the nexthop threshold for arista-7050cx3-32s-c6s104 to the test.
There was an assert failure in test_crm_available.py for this SKU because it defaults to a nexthop threshold of 256 which is higher than the threshold the chip actually supports.
Added an entry under SKU_NEXTHOP_THRESHOLDS dictionary to set the nexthop threshold to 255 which is in line with other SKUs that have the same switch ASIC.
Ran the test with and without the change. Passing with the change.
=> Add nexthop threshold for arista-7050cx3-32s-c6s104

tests/pfcwd/test_pfcwd_all_port_storm.py
Summary:
Fixes # ([709](https://github.com/aristanetworks/sonic-qual.msft/issues/709))
- The test will pick a ToR randomly for the test without ascertaining if it's an active ToR
- In such cases, when the selected ToR is the standby, resolve_arp(which sends out a docker exec swss arping <>) would fail since the downstream facing interface is in standby mode, and the test will not proceed
This fix ensures the selected ToR will be set to be the active ToR
Verified on Arista-7050CX3 running dualtor topology
=> [sonic-mgmt]Fix flakiness in pfcwd/test_pfcwd_all_port_storm.py for active-standby topology variants

tests/common/helpers/pfc_storm.py
Summary:
This PR is to enhance [pfc_storm.py](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:fix_pfc_storm?expand=1#diff-484e78c60cc240abdb6d3334458ae4f0c19d720d758b99b3d7540a6450bfc757) to use platform specific script to generate PFC pause when leaf fanout is running SONiC OS.
This PR is to enhance pfc_storm.py to use platform specific script to generate PFC pause when leaf fanout is running SONiC OS.
Update pfc_storm.py.
No.
=> Run platform specific pfc_gen script when OS is SONiC

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skipped packet trimming tests on non-supported platforms. Packet trimming is only supported on certain Mellanox SN5640 and Arista 7060X6 SKUs.
Packet trimming nightly tests fail on non-supported platforms.
Skipped packet trimming tests on all non-supported SKUs.
Verified that packet trimming tests are not skipped on Mellanox-SN5640-C512S2.
Verified that packet trimming tests are skipped on a SN4600 device.
Skipped on all SKUs except Arista-7060X6-64PE-B-C448O16, Arista-7060X6-64PE-B-C512S2, Mellanox-SN5640-C448O16, and Mellanox-SN5640-C512S2.
N/A
N/A
=> Skipped packet trimming tests on non-supported platforms

ansible/generate_topo.py, ansible/vars/topo_lt2-o128.yml
Summary:
This PR is to update the topo definition for LT2-O128.
Change list
- Remove LAG between LT2 and UT2
- Add two VMs for UT2
This PR is to update the topo definition for LT2-O128.
- Remove LAG between LT2 and UT2
- Add two VMs for UT2
The change is verified by deploying it on a physical testbed.
No.
=> Update topo definition lt2-o128

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
T2 single node does not run chassisd and thus does not fill in the chassis module table.
T2 single node does not run chassisd and thus does not fill in the chassis module table.
I added the test to the conditional skip list.
I verified that the test was skipped on a t2-single-node-min topology.
=> Skip test_show_chassis_modules.py on T2 single node

docs/testplan/snappi/bgp_convergence_test.md
Summary:
Currently, we don't have any test plan that uses tgen for measure the BGP convergence performance and data plane downtime, especially in multi-tier network topology.
This PR adds the test plan that uses tgen for testing, which is based on NUT testbed.
Doc only.
- Test case 1: https://github.com/sonic-net/sonic-mgmt/pull/18779
No.
- `nut-single-dut`
- `nut-2tier`
=> [Test plan] Snappi-based BGP Convergence Test

tests/common/dhcp_relay_utils.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/utilities.py, tests/dhcp_relay/conftest.py, tests/dhcp_relay/test_dhcp_counter_stress.py
Summary:
Previous counter stress tests only checked 2 interfaces (port channel interface for  discover and request, client interface for offer and ack). In some cases, the packet count of testbed received and relayed are not equal, it may due to dhcy relay issue instead of dhcy relay counter. The test cases should distinguish this scenario.
Catch packets from both directly for the four request types and compare the cached packet number and counter value.
run the stress test.
=> Imporve DHCP relay counter stress test

tests/route/test_default_route.py
Summary:
Fix the test `route/test_default_route.py::test_default_route_with_bgp_flap` failure in the topo with PT0.
Add PT0 to the upstream neighbors
Check it locally
=> [test_default_route]: Fix default route for PT0

tests/conftest.py, tests/ip/test_mgmt_ipv6_only.py
Summary:
`test_mgmt_ipv6_only` will disable ipv4 mgmt address in its setup, which will cause the self-acting toggle from `setup_dualtor_mux_ports` failing as DUT cannot talk to `mux_simulator`.
Add the unsupported mark `pytest.mark.dualtor_skip_setup_mux_ports`.
Skip setup mux ports for `test_mgmt_ipv6_only`
```
ip/test_mgmt_ipv6_only.py::test_bgp_facts_ipv6_only PASSED                                                                                                                                                                                                             [100%]
```
=> [dualtor] Skip toggle failure introduced by `setup_dualtor_mux_ports`

ansible/group_vars/sonic/variables, ansible/templates/minigraph_meta.j2, tests/db_migrator/test_migrate_dns.py
Summary:
PR https://github.com/sonic-net/sonic-buildimage/pull/11429 added support of SonicQosProfile in minigraph parser. This change is to align the test code to cover SonicQosProfile in minigraph.xml.
1. Updated ansible/group_vars/sonic/variables to add variable `sonic_qos_profile`.
2. Updated minigraph template file `minigraph_meta.j2` to generate DeviceProperty for SonicQosProfile based on value of variable sonic_qos_profile.
3. Script test_migrate_dns.py is impacted by this change. This test always inserts SonicQosProfile in minigraph.xml in one of its test case. This change adapted the script to insert the SonicQosProfile config only when it is missing.
* Tested "gen-mg" and "deploy-mg".
* Tested test_migrate_dns.py.
=> Add support of DeviceProperty SonicQosProfile in minigraph.xml

tests/common/platform/device_utils.py, tests/platform_tests/api/test_watchdog.py, tests/show_techsupport/test_techsupport.py
This changes is because is_dpu method was removed
by below PR
[smartswitch]: Add is_smartswitch and is_dpu facts to simplify platform-specific test handling (#19313)
The way to check if is dpu should use `duthost.dut_basic_facts()['ansible_facts']['dut_basic_facts'].get("is_dpu")` instead of `duthost.get_facts().get('is_dpu')` becasue PR #19313 added the facts into dut_basic_facts
Summary:
Fixes #19573 
To fix bugs that cause test failure
update tests that calls method that does not exist
run test before and after the PR to verify it works as expected
=> Refactor DPU check in device_utils and test_watchdog

sdn_tests/pins_ondatra/infrastructure/testhelper/config_convergence.go, sdn_tests/pins_ondatra/infrastructure/testhelper/config_restorer.go, sdn_tests/pins_ondatra/infrastructure/testhelper/platform_components.go
Keyword Check:
/sonic-mgmt/sdn_tests/pins_ondatra$ ~/tools/keyword_checks.sh .
Keyword check Passed.
Build Result:
sonic-mgmt/sdn_tests/pins_ondatra$ bazel build ...
Starting local Bazel server and connecting to it...
INFO: Analyzed 19 targets (507 packages loaded, 30100 targets configured).
INFO: Found 19 targets...
INFO: Elapsed time: 267.900s, Critical Path: 101.99s
INFO: 3 processes: 1 internal, 2 linux-sandbox.
INFO: Build completed successfully, 3 total actions
Test Result:
/sonic-mgmt/sdn_tests/pins_ondatra$ bazel test ...
INFO: Analyzed 20 targets (0 packages loaded, 0 targets configured).
INFO: Found 18 targets and 2 test targets...
INFO: Elapsed time: 62.176s, Critical Path: 44.12s
INFO: 2 processes: 1 internal, 1 linux-sandbox.
INFO: Build completed successfully, 2 total …
=> [ondatra] Improve ConfigRestorer with config convergence verification and port polling fix.

tests/common/snappi_tests/common_helpers.py, tests/common/snappi_tests/traffic_generation.py
Printing 'show interface counters detailed' for the interfaces used in test to help with debugging
Summary:
Fixes # To help debug https://migsonic.atlassian.net/browse/MIGSMSFT-1080
- [X ] Test case improvement
MSFT is seeing loss at TGEN where as DUT doesnt report any loss. This command will help confirm the issue might be on the Ixia side.
Added the code to print the command output in test logs
Manually ran the test and verified
Testlog will have this info printed
```
10/07/2025 23:30:43 base._run                                L0071 DEBUG  | /data/tests/common/devices/multi_asic.py::_run_on_asics#136: [yy40-mixed-short] AnsibleModule::command, args=["show interface counters detailed Ethernet128"], kwargs={}
10/07/2025 23:30:45 base._run                                L0108 DEBUG  | …
```
=> show interface counters detailed

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/qos/qos_sai_base.py
Summary:
Fixes # [643](https://github.com/aristanetworks/sonic-qual.msft/issues/643)
- Enabled test_qos_sai test on dualtor-active-active-56 topology by modifying the tests_mark_conditions.yaml file and qos_sai_base.py. 
- Please note that https://github.com/sonic-net/sonic-mgmt/pull/19585 is required for these tests to run
Verified on Arista-7260CX3 running dualtor-active-active-56 topology
=> [7260CX3][dualtor-aa-56][202505]Enable qos.test_qos_sai support on dualtor-aa-56 topology

ansible/library/generate_golden_config_db.py
Enable orch_northbond_route_zmq_enabled feature in sonic-mgmt test.
Test orch_northbond_route_zmq_enabled in PR validation and nightly test.
- Microsoft ADO **(number only)**: 32582830
Enable orch_northbond_route_zmq_enabled in golden config.
Enable orch_northbond_route_zmq_enabled feature in sonic-mgmt test.
=> Enable orch_northbond_route_zmq_enabled feature in sonic-mgmt test.

tests/test_pretest.py
Summary:
The saithrift package download fails for Mellanox platforms on internal-202411 branch because the code was hardcoding bullseye as the Debian codename for all ASIC types, but Mellanox requires the actual Debian codename from the syncd container.
Modified the condition to only use hardcoded bullseye for non-Mellanox platforms on internal-202411
For Mellanox on internal-202411, the code now retrieves the actual Debian codename via docker command
This ensures the correct saithrift package URL is constructed for each platform type
local test
=> Fix saithrift URL generation for Mellanox on internal-202411 branch

tests/bmp/test_bmp_configdb.py, tests/macsec/test_fault_handling.py
**Summary:**
I updated the assertion statements in the following test files to include descriptive error messages: …
=> Added detailed reason for assert failure for macsec,bmp

tests/bgp/test_bgp_router_id.py, tests/bgp/test_bgp_speaker.py
**Summary:**
I updated the assertion statements in the following test files to include …
=> Added detailed reason for assert failure for bgp

tests/snappi_tests/pfc/test_pfc_port_congestion.py
Summary:
Fixes the following issues in test_pfc_port_congestion.py:
1. Fixed the rx/tx port sequence,  the currnet port_map is defined as [total egress port, egress port speed, total ingress ports, ingress port speed]. So get the rx port info from the first two elements.
2. pfcwd will be triggered on cisco platform as we are sending oversubscribed traffic, so disabling it during the test.
Adopt this test case for 400G speed
Fixed the case to use correct RX/TX port_map sequence. and disable pfcwd inside the test case.
```
snappi_tests/pfc/test_pfc_port_congestion.py::test_multiple_prio_diff_dist[multidut_port_info0-port_map0] SKIPPED [  6%]
snappi_tests/pfc/test_pfc_port_congestion.py::test_multiple_prio_diff_dist[multidut_port_info0-port_map1] 
-------------------------------- live log …
```
=> [Snappi] Fix tx/rx port sequence in test_pfc_port_congestion.py

tests/snappi_tests/files/helper.py
Summary:
Fixes the following import error.
```
def test_pfc_pause_single_lossless_prio_reboot(snappi_api,                   # noqa: F811
file /data/tests/snappi_tests/files/helper.py, line 127
@pytest.fixture(autouse=True)
def setup_ports_and_dut(
E       fixture 'multidut_port_info' not found
```
Update to use tgen_port_info
=> fix import errors in test_pfc_pause_single_lossless_prio_reboot

tests/common/reboot.py
Add Redis service check after reboot to avoid duthost.critical_services_tracking_list failure due to redis not start
Summary:
Sometimes, after reboot, even database docker is UP, there would be some chance that Redis DB is under initialization.
In this scenario, the test would failed due to duthost.critical_services_tracking_list() failure:
https://github.com/sonic-net/sonic-mgmt/blob/005c92029ca963161400bb26723c67082a1b09d6/tests/common/reboot.py#L382
Add Redis service check after reboot
Run it at local setup
=> Add Redis service check after reboot

tests/crm/conftest.py
The fixture crm_resources is auto use fixture, in it, it will check the crm resources, the timeout of checking the crm resource is 90s, if there is a config reload did before the test, and since the default crm polling interval is 360s, so the 90s timeout is not enough, actually, there is another auto use fixture set_polling_interval which is also module level, in it, the crm polling interval will be changed to 1s, but it is called after the crm_resources, change the set_polling_interval always called before the crm_resources, then even if there is config reload did before this test, 90s timeout is enough to get the crm resources.
Summary: The fixture crm_resources  is new added in https://github.com/sonic-net/sonic-mgmt/pull/18465. 
=> Stabilize the crm test

tests/hash/test_generic_hash.py
Summary:
Reapplying routes (including VXLAN routes) takes longer after an interface shutdown/startup. Since there is only one member in the ECMP group, there is no alternate path to the destination when the interface goes down. As a result, any traffic sent before the routes are fully restored will be lost. 
Make a test stable with topos with 1 member in ECMP group
Added 5 sec sleep after flap interface 3 times
Run test, test passed
=> Validate BGP sessions are up | generic hash nexthop flap test

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
test_generic_hash is a test case that fails on many platforms and is only expected to be supported on a limited set. Since this feature is used in a very narrow scope, we’ll mark the test as xfail—it will still run, but the results won’t be validated for now.
Add xfail for test_generic_test
N/A
N/A
=> [conditional mark] xfail  test_generic_hash

tests/system_health/test_watchdog.py
This relax is needed for https://github.com/sonic-net/sonic-buildimage/pull/23513. Since that PR will change the installation path of supervisor-proc-exit-listener.
Summary:
=> Check supervisor-proc-exit-listener process by full path or filename only

tests/common/snappi_tests/snappi_fixtures.py
There are a few different errors but all are part of the function `setup_dut_ports` when trying to configure ports using dynamic port selection. There are 3 main issues to deal with here:
ISSUE 1
The assumption from the 3 functions written (`__vlan_intf_config`, ` __portchannel_intf_config`, `__l3_intf_config`) is that they would run independently of each other, which is not the case looking at the function `setup_dut_ports`. `port_config_list`, an initially empty list is passed to all three functions and then used by the caller. In such a case, such a comparison (`len(port_config_list) != len(snappi_ports)`) within each function is wrong. It should be ideally done under `setup_dut_ports` after all 3 configuration functions are run.
ISSUE 2 - ` __portchannel_intf_config`
Port channel LAG …
=> [SNAPPI] `pfc/test_pfc_pause_lossless_with_snappi.py` failed to configure ports

tests/voq/test_voq_chassis_app_db_consistency.py
Summary:
Fixes #19980 
`test_voq_chassis_app_db_consisitency.py` reboot_dut case on dT2 would fail with `Timeout (62s) waiting for privilege escalation prompt:` as it would try to perform `get_db_dump` on the rebooting dut. Not a problem for T2 as the DUT rebooting is always a frontend node and `get_db_dump` is always called on a supervisor node.
Made a change so test would only `check_db_consistency` on a rebooting DUT if there are more than 1 DUT (basically if it's T2)
Ran the test, didn't see the same failure.
N/A
N/A
N/A
=> Ensure get_db_dump is not called on rebooting DUT

tests/qos/test_oq_watchdog.py, tests/qos/test_voq_watchdog.py, tests/saitests/py3/sai_qos_tests.py
Use voq occupancy to determine whether voq watchdog is triggered.
Use oq occupancy to determine whether oq watchdog is triggered.
Summary:
https://migsonic.atlassian.net/browse/MIGSMSFT-1146
To identify the failure reason of oq watchdog test case.
Add some CLI output in script to capture more information when test case fails.
Verified on T2 testbed.
OQ watchdog:
```
----------------------------- generated xml file: /run_logs/qos/test_oq_watchdog_2025-07-28-05-53-07.xml ------------------------------
------------------------------------------------------- live log sessionfinish --------------------------------------------------------
06:56:18 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure …
```
=> MIGSMSFT-1146 Use queue occupancy to determine whether oq/voq watchdog is triggered

tests/acl/test_acl.py
Cherry-pick changes in PR #19235 to 202505.
Summary:
=> [202505]: Support t1-48-lag topo for acl tests

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
We got below loganalyzer failure on latest Arista images. Since this ERR log is only for SRV6, I ignore them in loganalyzer:
```
E               Failed: Got matched syslog in processes "analyze_logs--<MultiAsicSonicHost 720dt-3>" exit code:"1"
E               match: 2
E               expected_match: 0
E               expected_missing_match: 0
E               2025 Aug  2 17:59:33.069264 720dt-3 ERR syncd#syncd: [none] SAI_API_SRV6:_brcm_sai_srv6_config_get:1309 SRV6 unsupported or not enabled on this device
E               2025 Aug  2 17:59:33.069264 720dt-3 ERR syncd#syncd: [none] SAI_API_SWITCH:sai_object_type_get_availability:1002 availablity my_sid failed with error -2.
```
Ignore SRV6 ERR in loganalyzer.
Ignore …
=> [Arista] Ignore SRV6 ERR log on Arista platforms

ansible/templates/minigraph_link_meta.j2
Summary:
Current 'autoneg' column in links.csv only support 'on'.  If it's  'off' or other settings, it will default to platform.json behavior.
This PR add the support for 'off' settings.  
For  DUT which want to use the default behavior, it can leave that column empty, or use any other value, e.g. 'none'
Note: There will be a behavior change if user is using `off` in links.csv already for their DUT.
old behavior:  the autoneg settings will be derived from platform.json, which chould be `on` or `off` or not defined.
new behavior:  will be `off` always.
If users is using `off` already, they need to update their links.csv to leave autoneg field as empty if they want to use the default settings in platform.json.
update autoneg setting to support 'off'
Check autoneg value for both `on` and …
=> update autoneg setting to support 'off' when deploy-mg

tests/qos/qos_sai_base.py, tests/saitests/py3/sai_qos_tests.py
Summary:
There are 2 issue in the Qos sai test on dualtor testbed.
1. The dualTorScenario is only for mocked dualtor testbed(This is introduced in https://github.com/sonic-net/sonic-mgmt/pull/5947). It changes the configuration in some tests. It should be False when it's real dualtor topo.
2. def_vlan_mac for dualtor should be the mac of vlan interface(00:aa:bb:cc:dd:ee), but the logic to update mac for dualtor was broken in PR(https://github.com/sonic-net/sonic-mgmt/pull/7716). The mac update logic is not executed because it's in a "elif" and the dualtor topo is also in SUPPORTED_T0_TOPOS.
The test case qos/test_qos_sai.py::TestQosSai::testQosSaiHeadroomPoolSize fails due the the above issues.
```
ERROR: …
```
=> [Dualtor][Qos SAI] Fix qos sai test for dualtor

tests/qos/files/mellanox/qos_param_generator.py
To set the margin to a reasonable value and stabilize the testQosSaiLossyQueue for mellanox spc4 above platform, adjust margin to 2% of share buffer size for testQosSaiLossyQueue
Summary:
To set the margin to a reasonable value and stabilize the testQosSaiLossyQueue for mellanox spc4 above platform.
adjust margin to 2% of share buffer size for testQosSaiLossyQueue
Run testQosSaiLossyQueue on spc4 above platform 
spc4 above
=> [Mellanox] Adjust margin to 2% of share buffer size for testQosSaiLossyQueue for spc4 above platform

tests/common/reboot.py
Summary:
Fix the console log fetching, to prevent a race condition between the disconnection of the console session, to the system boot.
The "disconnect" function of console session is sending "exit" command to console, and in some occasions,  this command is sent exactly when the system is booting, causing system to be sent to grub edit mode, due to the "e" letter in "exit" which initiated this mode.
The fix ensures the disconnection happens only after system is fully booted.
Move the "disconnect" function to run after system finished boot.
Ran the test
=> Fix the console log fetching, to prevent a race condition

tests/crm/test_crm.py
test_crm_nexthop_group was failing on sn4700 testbeds due to a known orchagent crash. The crash is caused by a few factors:
- Expected neighbor entry missing from kernel, causing tunnel-route to be programmed for unresolved nexthop.
- tunnel-route being removed when nexthop group was deleted
- route bulker ending early due to ITEM_NOT_FOUND (not processing remaining bulk removes)
- next-hop group delete failing due to OBJECT_IN_USE.
This PR addresses the first issue.
During neighbor generation for the test, some of the neighbor updates were being missed from APPL_DB on sn4700 devices. Previously, the neighbors were programmed in the kernel in a single ip command, this fix splits up the neighbor programming into batches in order to prevent updates from being dropped.
Summary:
Fixes …
=> [crm] Fix test failures on SN4700 by batching neighbor creation

tests/voq/test_voq_ipfwd.py
Summary:
Fixes #19971 
When using `pick_ports` function in `test_voq_ipfwd.py`, it was possible that the function chose the same port for 'portA' and 'portB' when forced to choose 2 of the same types of ports. This was causing failures in `test_voq_disrupts.py` which used the function.
Remove 'portA' from candidates for 'portB'.
Ran the failing test a few times to make sure it no longer fails
N/A
N/A
N/A
=> Ensure 'portA' and 'portB' are different in pick_ports

tests/mvrf/test_mgmtvrf.py
Summary:
Update the mgmtvrf test case for ntp by having it use Chrony
Reuse existing code that is in the common ntp_helper module instead of copy-pasting code here.
=> Clean up mgmtvrf test for ntp by reusing existing code

tests/qos/qos_sai_base.py
Summary:
change the topo-name from dualtor-aa to dualtor-aa-56 as PR https://github.com/sonic-net/sonic-mgmt/pull/19890 was intended to enable qos.test_qos_sai support on dualtor-aa-56 topology.
modified the qos_sai_base.py file
Verified on Arista-7260CX3 running dualtor-active-active-56 topology
=> Correcting topo-name in PR #19890 

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Ignore lldp related error log in log analyzer.
To ignore LLDP-related error logs in the log analyzer—such as those shown below—which are observed only on 512-port devices and have no functional impact.
```
2025 Aug  2 00:04:20.447956 str5-7060x6-512-3 ERR container: docker cmd: stop for lldp failed with 500 Server Error for http+docker://localhost/v1.43/containers/5ff64ad7a6bee49abdc2aee23b458ebfdbf457e0cecc8f5f6550d0c11eddad9a/stop: Internal Server Error ("cannot stop container: 5ff64ad7a6bee49abdc2aee23b458ebfdbf457e0cecc8f5f6550d0c11eddad9a: tried to kill container, but did not receive an exit event")
```
Ignore lldp error log in loganalyzer.
Verify it locally.
=> [Log analyzer] Ignore lldp failed with 500 server error log

tests/common/plugins/loganalyzer/utils.py
Fixing `support_ignore_loganalyzer` wrapper to add `end_ignore_mark` in case of exceptions as well.
for example: In `config_reload`, if we get any pytest_assert failure, which will cause `end_ignore_marker` to not get added, leading to this crash during further processing in loganalyzer.
Summary: fix loganalyzer crash with `Exception: pop from empty list`
Fixes #19632 
loganalyzer is crashing in case `config_reload` raising any exceptions.
`support_ignore_loganalyzer` wrapper was not handling the addition of `end_ignore_marker` in case of wrapped function raised exceptions, added try and finally block to add `end_ignore_marker`
=> Fix loganalyzer crash with `Exception: pop from empty list`

ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py, tests/common/dhcp_relay_utils.py, tests/dhcp_relay/test_dhcp_relay.py
Summary:
Previous tests only covered normal types: Discover, Offer, Request and Ack
We should test all of DHCP packet types.
Add the rest packet types: Unknown, Decline, Nak, Release and Inform
Run test case: test_dhcp_relay_default
=> [DHCP relay counter] Add all DHCP packet type for DHCP relay counter tests

tests/platform_tests/api/test_chassis.py
Summary: Fix the test_status_led error in case if the chassis led is not controllable
The [platform_tests/api/test_chassis.py::test_status_led testcase](https://github.com/vhlushko-cisco/sonic-mgmt/blob/98ce5e3642535775404f7498b663fa357298c9d8/tests/platform_tests/api/test_chassis.py#L468) code logic assumes that the chassis main led [is always controllable](https://github.com/vhlushko-cisco/sonic-mgmt/blob/98ce5e3642535775404f7498b663fa357298c9d8/tests/platform_tests/api/test_chassis.py#L499).
But for some of the Cisco devices [this test logic](https://github.com/vhlushko-cisco/sonic-mgmt/blob/98ce5e3642535775404f7498b663fa357298c9d8/tests/platform_tests/api/test_chassis.py#L502):
```
status_led = duthost.facts.get("chassis").get("status_led")
```
always returns `None`, which means that …
=> [platform] Fix the test_status_led error in case if the chassis led is not controllable

ansible/roles/vm_set/tasks/add_topo.yml
Summary:
Ignore any router advertisements sent by a DUT, and don't set a default route or an address based on it. This could happen if a T0 testbed with radv running sends router advertisements on a VLAN interface, which may result in the PTF container adding a default route on all of the VLAN interfaces. This could result in some IPv6 test cases breaking.
Set the `net.ipv6.conf.default.accept_ra` sysctl to 0 when creating the PTF container. All of the interfaces that get created/moved into the PTF container then inherit this setting.
Ran add-topo for vms-kvm-t0, and verified that the router advertisements sent by the T0 didn't result in a default route being learned.
=> Ignore router advertisements in PTF

tests/bmp/test_docker_restart.py
Summary:
There is a bmp container per ASIC so we need to use the correct per-ASIC names if we are on a multi-ASIC DUT.
I updated the restart command to use the correct API for restarting a per-ASIC service.
We ran the test locally on an Arista multi-ASIC DUT.
=> bmp: Fix docker restart test for multi-asic

tests/kubesonic/test_k8s_join_disjoin.py
Summary: It's an improvement for testbed vms75-t0-7050cx3-1. For this SKU, the kubelet needs more time(around 70s) to join the minikube cluster, so increased the wait time for joining node to cluster.
Fixes # (33976122)
It's an improvement for testbed vms75-t0-7050cx3-1. For this SKU, the kubelet needs more time(around 70s) to join the minikube cluster.
Increased the wait time for joining node to cluster.
Run this test in testbed vms75-t0-7050cx3-1 to see if it passes.
None
None
=> Fix k8s node join time not enough issue

ansible/roles/test/files/ptftests/py3/hash_test.py
Summary:
This PR is to stabilize `test_hash` on FT2 topology.
The test is flaky on FT2 because of the insufficient entropy and enormous number of neighbors.
The PR stabilized the test by loosing the balance check criteria.
This PR is to stabilize `test_hash` on FT2 topology.
Loose balance check criteria. Test is considered as passing if all ports received over 20% expected packets.
```
collected 2 items                                                                                                                                                                                                             
fib/test_fib.py::test_hash[ipv4] 
-------------------------------------------------------------------------------------------------------- …
```
=> Stabilize hash_test on FT2 topology

tests/disk/test_disk_exhaustion.py
Since the latest image mounts /tmp as tmpfs, it uses RAM instead of disk storage. To simulate a disk full scenario, use the /host directory instead.
The /host path is backed by the host’s actual disk (/dev/sda1, ext4), not memory. Therefore, operations performed in /host consume real disk space, and commands like fallocate behave as expected.
Since the latest image mounts /tmp as tmpfs, it uses RAM instead of disk storage. To simulate a disk full scenario, use the /host directory instead.
Replace /tmp with /host
Test locally on testbed.
=> Enhance test_disk_exhaustion with using /host for Simulating Disk Full.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip decap and fib tests for t1-isolated-d128/32 as these tests expect uplinks
=> Skip decap and fib tests for t1-isolated-d128/32

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
SRv6 is not used in Moby T0 topology. Skipping SRv6 related test cases.
Also fixed the topology name in existing skip conditions.
Skip SRv6 for Moby topology
skip condition.
=> skip srv6 for Moby topology t0-isolated-d96u32s2

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
warm reboot is not supported in isolated topology.  change the skip condition to cover both 202412 and 202505 branch.
skip warm reboot test cases for pfcwd
skip it with conditional mark
=> skip warm reboot for pfcwd on isolated topology.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
DHCP relay feature is not enabled in t0-isolated topology. Skip it as it's not supported.
Skip DHCP test case in test_dynamic_acl.py
skip it in conditional marker.
run in local test testbed.
=> skip test_gcu_acl_dhcp_rule_creation for isolated topology

tests/restapi/conftest.py, tests/restapi/test_restapi.py
Update restapi test to invoke apply_cert_config in smartswitch and isolated topology
The configuration needed for the restapi server is added directly to the running config using sonic-db-cli commands: https://git-nbu-sw.nvidia.com/r/gitweb?p=switchx/sonic/sonic-mgmt.git;a=blob;f=tests/restapi/test_restapi.py;h=5be4008d7d4d353e69ff8f032faf2b0badf15a75;hb=refs/heads/develop#l52 And we perform warm-reboot:
https://git-nbu-sw.nvidia.com/r/gitweb?p=switchx/sonic/sonic-mgmt.git;a=blob;f=tests/restapi/test_restapi.py;h=5be4008d7d4d353e69ff8f032faf2b0badf15a75;hb=refs/heads/develop#l75 Which saves the running configuration to the config_db.json as part of the warmboot-finalizer.service script finalize-warmboot.sh https://github.com/nvidia-sonic/sonic-buildimage/blob/0bd8460a403b77ba399a2f4f48e8aa …
=> Update restapi test to invoke apply_cert_config in smartswitch and isolated topology

tests/bgp/test_bgp_suppress_fib.py, tests/common/helpers/ptf_tests_helper.py, tests/pc/test_lag_member_forwarding.py, tests/qos/test_qos_dscp_mapping.py, tests/qos/test_qos_sai.py
Ignore error during config reload in BGP/QOS/FPC test cases 
Cherry-pick for https://github.com/sonic-net/sonic-mgmt/pull/19869
BGP/QOS/FPC test case failed because following error:
E               2025 Jul 28 04:41:57.469604 str2-msn2700-spy-1 ERR iptables: tac_connect_single: connection to 10.64.246.145:49 failed: Network is unreachable
These test case reload_config but not set ignore_loganalyzer parameter.
Because reload config will restart networking service, which will cause TACACS server unreachable during networking service shutdown.
- Microsoft ADO **(number only)**: 
Set reload_config ignore_loganalyzer parameter in BGP/QOS/FPC test cases.
Ignore error during config reload in BGP/QOS/FPC test cases
=> [202505] Ignore error during config reload in BGP/QOS/FPC test cases

.azure-pipelines/impacted_area_testing/calculate-instance-numbers.yml, .azure-pipelines/impacted_area_testing/calculate_instance_number.py
Summary:
Our goal is limit PR test into 120 mins, previously due to lack of PR test instances and Elastictest limitation, we set it to 180 mins, but now we have enough instances and Elastictest limitation was fixed, we can use more instances to lower PR test time.
Set target PR test time to 120 mins in library, and import from group, then we don't need to change it in code.
Before change:
2025-08-07T05:18:29.0819937Z INFO:root:Total running time: 112067.61339999993
2025-08-07T05:18:29.1170502Z + INSTANCE_NUMBER=13
After change:
2025-08-07T07:27:51.3542401Z INFO:root:Total running time: 112067.61339999993
2025-08-07T07:27:51.3974217Z + INSTANCE_NUMBER=21
=> Add instances to shorten PR test time

tests/bfd/bfd_helpers.py, tests/bgp/test_bgp_azng_migration.py, tests/bgp/test_bgp_queue.py, tests/bgp/test_bgp_suppress_fib.py, tests/fdb/test_fdb.py, tests/lldp/test_lldp.py, tests/platform_tests/link_flap/test_link_flap.py, tests/platform_tests/test_reload_config.py, tests/route/test_static_route.py, tests/snmp/test_snmp_phy_entity.py
Removed hostname,platform and hwsku from assert failed summary
**Summary:**
Removed hostname, platform, and hwsku from assertion failure summaries to make them more consistent across test cases. Including these details caused unique messages per DUT, making automated failure grouping harder. This change helps streamline log analysis and improves failure aggregation.
The Motivation is to improve the consistency of assertion failure messages across test cases. Including dynamic values like hostname, platform, and hwsku leads to unique failure summaries for each DUT, making it difficult to group and analyze failures automatically. By removing these, we enable better aggregation and more …
=> Removed hostname,platform and hwsku from assert failed summary

tests/common/devices/sonic.py, tests/iface_namingmode/test_iface_namingmode.py
Summary:
Test case `test_config_interface_speed_40G_100G` didn't adjust FEC when changing speed. e.g. if FEC is configured as `rs` in 100G case initially, it won't be valid when moving to 40G, and link may not come up.
And not all vendors/platforms support/enable auto-neg on FEC.
Generrally:
1. For 100G, FEC can be either `rs` or `none`
2. For 40G, FEC can be either `fc` or `none`
Fix: 
If link couldn't come up with native FEC config, loop through all possible FECs for the particular speed to see which one brings up the link.
Passed the testcase on T1 setup
=> Adjust FEC based on speed for test_config_interface_speed_40G_100G

tests/common/fixtures/ptfhost_utils.py, tests/qos/test_qos_sai.py
Summary:
Backport of #19709 with merge conflict resolution for the 202505
This PR is dependent on the PR (https://github.com/sonic-net/sonic-buildimage/pull/23382) and should be merged only after that PR.
A new fixture, iptables_drop_ipv6_tx, has been created to use ip6tables to drop IPv6 traffic. This fixture is being used in place of disable_ipv6, which uses sysctl.
Using sysctl to disable IPv6 caused interfaces to lose their configured addresses, resulting in connectivity issues with the PTF container. Using ip6tables fulfills the requirement to block IPv6 traffic while the scenario is running without affecting the interfaces.
Created a new fixture iptables_drop_ipv6_tx
Verified on Arista-7260CX3 running dualtor-120 topology
=> [sonic-mgmt][202505] Fix for no_v6_default_route error

ansible/library/minigraph_facts.py, ansible/templates/minigraph_link_meta.j2, tests/macsec/test_interop_protocol.py
Fix test_interop_protocol.py::TestInteropProtocol::test_bgp  for t2 single node topo. 
Summary:
The test_interop_protocol.py::TestInteropProtocol::test_bgp  is failing for t2 single node topo. This is due to mimatch between ctrl_links and upstream_links content were not matching which is current assumption. This is due to both upstream and downstream neighbors are present on same card, this change will address this issue.
Test case change to support  T2 single node topo 
- [ x] Test case improvement
- [ x] 202505
Please Backport to 202503 also
Fix test_interop_protocol.py::TestInteropProtocol::test_bgp for t2 single node
Change minigraph_link_meta.j2 template to enable MACSec only for upstream neighbors for topo T2.
Change in minigraph facts for getting macsec enabled …
=> Fix macsec test_interop_protocol for t2 single node topo

tests/bgp/test_bgp_command.py
Summary:
Fixes #19605 
To support IPv6 topo. 
Remove unnecessary fail and reduce total test run time.
Enable topo check when it tries to run IPv4 test.
If topo is IPv6 but test is IPv4, the test will skip.
Ran on local testbed to verify.
=> Skip IPv4 BGP network command test in IPv6 topology

tests/route/test_route_perf.py
Summary:
For testcase test_route_perf.py, ignore ERR log during config reload.
For testcase test_route_perf.py, ignore ERR log during config reload.
=> [test route perf] Ignore ERR log during config reload

ansible/module_utils/graph_utils.py
Summary:
When an test port in the traffic generator is shared by multiple testbeds, the current lab graph doesn't support this case and will only keep 1 port in the end. This causes OCS link could not be correctly setup.
This change fixes the lab graph and keep all the links in the graph for link selection.
Run locally and works.
No.
=> Fix incorrectly selected OCS links when traffic generator are shared by multiple testbed

tests/pc/test_retry_count.py
This PR contains the following changes to the retry count test cases:
1. Use `command` instead of `shell` to avoid needing to start a shell where it's not needed.
2. Fix some Python style issues.
3. Rework the retry count test case logic to do a proper tear down by not having an assertion in a fixture. Instead, move the assertion to the test case itself. That makes sure that the teardown part of a fixture runs.
4. Fix the teamd kill test cases failing when running them individually in Elastictest, due to commands taking more time to run there.
Summary:
Tested via running `pc/test_retry_count.py` 20 times [here](https://elastictest.org/scheduler/testplan/689cc5be133795c925d9077e). There are only a couple passes, but the failures are because of loganalyzer failures not …
=> Fix retry count test case to properly teardown in case of failure

tests/qos/qos_sai_base.py, tests/saitests/py3/sai_qos_tests.py
1. Align the QoS test to the features of Per-Queue, Per-Priority, and Per-Direction.
-  For per direction, we increase three scenarios (src_uplink_dst_downlink, src_downlink_dst_uplink, src_downlink_dst_downlink) and select the src and dst testing ports based on these scenarios.
- When the topology is T0 and the scenarios are src_uplink_dst_downlink and src_downlink_dst_uplink, we need to set the router_mac to the DUT ASIC MAC; otherwise, the packet will not be routed to the correct port.
- For per queue, the original code already includes coverage for each queue.
3. PR: https://github.com/sonic-net/sonic-buildimage/pull/22869
Summary:
Align the QoS sai test to the features of Per-Queue, Per-Priority, and Per-Direction …
=>  Align the QoS sai test to the features of Per-Queue, Per-Priority, and Per-Direction

tests/common/helpers/drop_counters/drop_counters.py
Summary:
In PR(https://github.com/sonic-net/sonic-mgmt/pull/14676) , we increased the DROP_MARGIN in the drop counters test for T0 due to noisy packets in the test environment was also counted during the test.
Those packets were send to the dut Vlan and dropped, which increased the drop counter unexpectedly.
For dualtor, we need to double the DROP_MARGIN due to we have 2 duts and sometimes the noisy packets are doubled.
Here is an failure example on dualtor-aa-64-breakout topology, the expected drop counter is 1000, but we got 1046. 
An we have exact 23 interfaces in the Vlan.
```
Failed: 'RX_ERR' drop counter was not incremented on iface Vlan1000. DUT RX_ERR == [46, 1046]; Sent == 1000
```
To stabilize the drop counters test on dualtor testbed.
Run the test in regression, failure is not …
=> [Dualtor] Double the DROP_MARGIN in drop counters test for dualtor

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
In PR19199 we added skips for `platform_tests/cli/test_show_chassis_module.py` but accidentally added a `s` on the end of the test name.
Fixing that here.
https://github.com/sonic-net/sonic-mgmt/pull/19199
=> Fix typo in PR19199 in the test name

tests/bfd/bfd_helpers.py, tests/bgp/test_bgp_azng_migration.py, tests/bgp/test_bgp_queue.py, tests/bgp/test_bgp_suppress_fib.py, tests/fdb/test_fdb.py, tests/lldp/test_lldp.py, tests/platform_tests/link_flap/test_link_flap.py, tests/platform_tests/test_reload_config.py, tests/route/test_static_route.py, tests/snmp/test_snmp_phy_entity.py
Removed hostname,platform and hwsku from assert failed summary
**This PR is the cherry pick PR to 202505**
https://github.com/sonic-net/sonic-mgmt/pull/19889
**Summary:**
Removed hostname, platform, and hwsku from assertion failure summaries to make them more consistent across test cases. Including these details caused unique messages per DUT, making automated failure grouping harder. This change helps streamline log analysis and improves failure aggregation.
The Motivation is to improve the consistency of assertion failure messages across test cases. Including dynamic values like hostname, platform, and hwsku leads to unique failure summaries for each DUT, making it difficult to group …
=> [202505]Removed hostname,platform and hwsku from assert failed summary

tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Currently, the snmp pdu controller, which is both used by tests and devutils, only supports snmp v2c. Snmp v2c supports only community string as credential, and is currently shared by dut and pdu. This change supports a series of credentials that starts with pdu_, to separate dut snmp credentials from pdu snmp credentials. The pdu snmp variables can be provided either in inventory, group_vars or host_vars, depending on how lab ansible is setup. To accommodate old settings, if these pdu_* variables are not provided, we will fall back to the previous credential, which is the one shared with dut, snmp_rocommunity and snmp_rwcommunity.
New variables:
pdu_ro_snmp_version: # v2c or v3
pdu_snmp_rocommunity: # credential for v2c
pdu_ro_snmp_user: # credential for v3, user name …
=> [snmp] use snmpv3 in pdu controller

tests/qos/qos_sai_base.py, tests/saitests/py3/sai_qos_tests.py
1. Align the QoS test to the features of Per-Queue, Per-Priority, and Per-Direction.
-  For per direction, we increase three scenarios (src_uplink_dst_downlink, src_downlink_dst_uplink, src_downlink_dst_downlink) and select the src and dst testing ports based on these scenarios.
- When the topology is T0 and the scenarios are src_uplink_dst_downlink and src_downlink_dst_uplink, we need to set the router_mac to the DUT ASIC MAC; otherwise, the packet will not be routed to the correct port.
- For per queue, the original code already includes coverage for each queue.
3. PR: https://github.com/sonic-net/sonic-buildimage/pull/22869
Summary:
Align the QoS sai test to the features of Per-Queue, Per-Priority, and Per-Direction …
=> [202505] Align the QoS sai test to the features of Per-Queue, Per-Priority, and Per-Direction

tests/saitests/py3/sai_qos_tests.py
Summary:
This is to fix a test issue only observed on MSFT testbed due to noisy packets received by dut during the test. The size of the packet is very big, so the base watermark of PG0 has an unexpected big initial value which casues test failure. 
When the test fails, the pg 0 watermark is already 9216 before disabling the egress port, so we have the counter but not the packet in buffer:
```
08:48:08.060  root      : INFO    : [9216, 0, 0, 0, 0, 0, 0, 0]
```
The test then sends 100 small packets which should take 100 cells and the size should be 14400 on SN4700 platform.
And then it calculates the difference between the watermark after 100 packets and the base one. This is correct logic if the big packet was received after the tx disable, while it will fail the test if the packet is …
=> [Dualtor] Stabilize the test_tunnel_decap_dscp_to_pg_mapping test case

tests/platform_tests/test_intf_fec.py
`test_verify_fec_stats_counters` iterates over all ports in `intf_status` (up and down)
A down port is going to return an empty string for it's speed from STATE_DB.
If we try to cast that into an int we'll get the following error:
```
for intf in intf_status:
intf_name = intf['iface']
speed = duthost.get_speed(intf_name)
>           speed_gbps = f"{int(speed) // 1000}G"
E           ValueError: invalid literal for int() with base 10: ''
```
Summary:
Fixes #20104
=> `test_intf_fec.py` skip ports that are link down

tests/route/test_duplicate_route.py
Reverts sonic-net/sonic-mgmt#20232 since it's blocking PR test
=> Revert "Update expect_regex in test_duplicate_route to support bulk update mode"

tests/fib/test_fib.py
Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/17887
This fixes issue mentioned in https://github.com/sonic-net/sonic-mgmt/issues/17887. 
For pizza box DUTs, multi-port portchannel scenario was not handled, which caused issue on certain specific topologies.
Add all members of PORT_CHANNEL (if the port being shutdown is part of PORT_CHANNEL) to the filtered ports list, so that during fib_test, these ports are not randomly picked as src port.
Verified on t1-lag topology. the testcase passes.
Logs:
```
07/08/2025 20:31:13 test_fib.test_ecmp_group_member_flap     L0864 INFO   | Shutting down one uplink port.
07/08/2025 20:31:13 test_fib.test_ecmp_group_member_flap     L0869 INFO   | Shutting down port Ethernet0
07/08/2025 20:31:31 test_fib.get_port_and_portchannel_member L0764 …
```
=> Handle Multi-port portchannel member case in ECMP member flap TC

tests/gnmi/helper.py
Summary:
Microsoft ADO: 34432821
Sometimes recover_cert_config could not recover gnmi server, and it seems that "supervisorctl reload" is not reliable.
Use "supervisorctl start" to recover all the stopped program.
=> Improve gnmi test recover method

tests/common/plugins/memory_utilization/memory_utilization_dependence.json
Summary:
Fix following error in pretest:
```
>               pytest.fail(failure_message)
E               Failed: [ALARM]: frr_bgp:used, Previous memory usage 273.0 MB exceeds high threshold 256.0 MB (previous: 273.0 MB, current: 273.0 MB)
E               [ALARM]: frr_bgp:used, Current memory usage 273.0 MB exceeds high threshold 256.0 MB (previous: 273.0 MB, current: 273.0 MB)
This is a new memory checking feature in 202505. Therefore, the fix is not applicable to 202412 branch.
```
TH5 testbed may have 32 neighbors, and each has 6400 prefixes, the total memory after deploy-mg is around 260-300MB. increase to 384MB.
=> update FRR bgp memory for high bgp sessions count hwskus

tests/common/plugins/conditional_mark/__init__.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/qos/qos_sai_base.py
cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/20290 to 202505 
Summary:
Add 't0-d18u8s4', 't0-isolated-d96u32s2', 't1-isolated-d128', 't1-isolated-d32' into test_qos_sai support list.
also refactored the marking conditions to have one topologies list instead multiple.
refactor and enable test_qos_sai support.
Added one common constant and added new `isolated` topo into the list.
in local testbed.
=> [202505] update test_qos_sai skip conditions and Enable th5 and FT topo in test_qos_sai

tests/test_pretest.py
Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/20339
MSFT ADO: 34478399
Fix saithrift VERSION_CODENAME on multi-asic issue
If device is multi-asic, use 'syncd{index}' instead of 'syncd'
Tested on physical multi-asic devices, it works well
=> Fix saithrift VERSION_CODENAME on multi-asic issue

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: Remove xfail as #18594 has been fixed in #19242, test could pass.
Remove xfail as #18594 has been fixed in #19242, test could pass.
Verified it on internal mgmt test
```
vxlan/test_vnet_bgp_route_precedence.py::Test_VNET_BGP_route_Precedence::test_vnet_route_after_bgp[v4_in_v4-custom-initially_up] SKIPPED [  2%]
vxlan/test_vnet_bgp_route_precedence.py::Test_VNET_BGP_route_Precedence::test_vnet_route_before_bgp_after_ep_up[v4_in_v4-custom-initially_up] SKIPPED [  5%]
vxlan/test_vnet_bgp_route_precedence.py::Test_VNET_BGP_route_Precedence::test_vnet_route_bgp_removal_before_ep[v4_in_v4-custom-initially_up] SKIPPED [  8%]
vxlan/test_vnet_bgp_route_precedence.py::Test_VNET_BGP_route_Precedence::test_vnet_route_after_bgp_multi_flap[v4_in_v4-custom-initially_up] …
```
=> [vxlan.test_vnet_bgp_route_precedence]: Remove xfail as test has been fixed

ansible/library/announce_routes.py, tests/bgp/test_ipv6_bgp_scale.py, tests/conftest.py
Summary:
In some user scenario, for example bgp scale test in this PR, we need designed routes information of topology file to announcee routes on exabgp, so this PR add a new fixture to provide designed routes information of topology file, and use the fixture in scale test to help annouce routes on exabgp.
In some user scenario, for example bgp scale test in this PR, we need designed routes information of topology file to announcee routes on exabgp
add a new fixture to provide designed routes information of topology file, and use the fixture in scale test to help annouce routes on exabgp.
run on testbed
No
=> Add fixture to provide designed routes information of topology file

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip test_bgp_operation_in_ro due to feature reverted
Issue: https://github.com/sonic-net/sonic-buildimage/issues/23462
PR: https://github.com/sonic-net/sonic-buildimage/pull/23460
Skip test_bgp_operation_in_ro due to feature reverted
Skip test via conditional mark.
Verified on 7050CX3 T0 testbed.
=> Skip test_bgp_operation_in_ro due to feature reverted

tests/acl/test_acl.py, tests/common/fixtures/duthost_utils.py, tests/everflow/everflow_test_utilities.py, tests/everflow/test_everflow_testbed.py
Add multi binding acl test into everflow test scope
1. Toggle dualtor setup to AS mode
2. Only send packet from upstream to standby downstream side
3. Match the bounce back ipinip tunnel packet my multi binding acl at active downstream side
4. Mirror the match result
5. Validate the inner packet
Run pass at local setup:
Summary:
Add multi binding acl test into everflow test scope
1. Toggle dualtor setup to AS mode
2. Only send packet from upstream to standby downstream side
3. Match the bounce back ipinip tunnel packet my multi binding acl at active downstream side
4. Mirror the match result
5. Validate the inner packet
=> Add multi binding acl test into everflow test scope

ansible/module_utils/port_utils.py
Summary:changed port alias index for cisco platforms as per sonic standard
- [X ] Bug fix
- [X ] 202411
- [X ] 202505
updated port_alias_to_name_map variable for all cisco smartswicth platforms.
verified port_alias_to_name_map has all ports with alias index as port port_config.ini file.
Cisco-8102-28FH-DPU-0 and other cisco smartswicth platforms
t1-128-lag
=> changed port alias index for cisco platforms as per sonic standard

ansible/roles/test/files/ptftests/py3/copp_tests.py, tests/copp/copp_utils.py, tests/copp/scripts/update_copp_config.py, tests/copp/test_copp.py
1. Added/updated tests to cover [sonic-net/SONiC#1943](https://github.com/sonic-net/SONiC/pull/1943)
2. If the platform supports the CoPP neighbor_miss trap, verify that VLAN subnet traffic is policed under the neighbor_miss CoPP (200 PPS). If not, verify it under the existing default CoPP logic.
3. CoPP trap capability of platform is determined by COPP_TRAP_CAPABILITY_TABLE in STATE_DB.
4. Added a test case to verify the `show copp configuration` CLI output - `test_verify_copp_configuration_cli`.
5. Updated the existing test case to validate the trap installation status for the trap being verified with traffic.
Summary:
[sonic-net/SONiC#1943](https://github.com/sonic-net/SONiC/pull/1943)
1. Modified `update_copp_config.py` script to not modify neighbor_miss trap CBS/CIR …
=> [CoPP]: Added neighbor_miss trap verification and cli test

tests/qos/files/qos_params.th2.yaml
Summary:
QoS tests are failing with KeyError: 'xon_1' when running on TH2 ASIC with topo-dualtor-aa-56 topology and 100000_300m speed/cable length configuration. as below:
```
13/08/2025 08:31:56 __init__._fixture_generator_decorator    L0088 ERROR  | 
KeyError('xon_1')
File "/var/src/sonic-mgmt_testbed-bjw3-can-dual-t0-7260-2/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
res = next(it)
File "/var/src/sonic-mgmt_testbed-bjw3-can-dual-t0-7260-2/tests/qos/qos_sai_base.py", line 1744, in dutQosConfig
qosParams = qpm.run()
File "/var/src/sonic-mgmt_testbed-bjw3-can-dual-t0-7260-2/tests/qos/files/brcm/qos_param_generator.py", line 521, in run
self.prepare_default_parameters()
File …
```
=> fix xon key error for th2 asic's qos test

tests/smartswitch/common/reboot.py, tests/smartswitch/platform_tests/test_reload_dpu.py
Fixed  test_cold_reboot_dpus
Summary:
The test was not handling the exceptions correctly, as the result it passed even and the DPUs were not rebooted.
Exceptions were caused by the incorrect access to duthost facts and using the platform API in multiple threads concurrently.
False pass on test_cold_reboot_dpus tests
Updated logic access to the duthost facts to match the recent change.
Inquired the DPU names in the main thread, before rebooting them in parallel
Ran both positive (test PASS as expected) and negative scenario (test FAIL because of the exception)
=> Fixed test_cold_reboot_dpus test

ansible/group_vars/sonic/sku-sensors-data.yml, tests/platform_tests/sensors_utils/psu_data.yaml
Summary:
Updates for SN5600 sensors data, reflect the changes in https://github.com/sonic-net/sonic-buildimage/pull/23613
Align the sensors data in sku-sensors-data.yml and psu_data.yml according to the sensors.conf updates.
Updated the relevant sensors labels
tested test_sensors.py on SN5600 platform
Mellanox
=> [Mellanox] Updated SN5600 section in sku-sensors-data.yml

tests/srv6/test_srv6_static_config.py
Summary: The func_len in the configuration was not set to 0, which might cause problems for MY_SID programming in certain scenarios.
=> Set func_len in test_srv6_static_config as 0

tests/pfcwd/test_pfcwd_cli.py
Summary:
Fixes test_pfcwd_show_stat flakiness
test_pfcwd_show_stat  is not stable.
sleep before checking the pfc stat
On Cisco 8102 but should work on other platform.
=> Fix flakiness of test_pfcwd_show_stat

tests/route/test_forced_mgmt_route.py
Summary: Enable the test on ft2 and lt2 platform
Fixes # (issue) 3291771
Enable the test on ft2 and lt2 platform
=> [Test Gap] enable test_forced_mgmt_route for lt2 and ft2

tests/route/test_duplicate_route.py
The sonic-sairedis change from https://github.com/sonic-net/sonic-sairedis/pull/1613 modified the behavior of BULK operations which resulted in the log spew looking different before and after on API failures. This impacts test_duplicate_route.py. As this test is failing with the above sonic-sairedis change included, sonic-buildimage PRs that bump up the submodule reference fail pipeline checks.
The fix is to move all regexes to the ignore list so that the test can continue to pass with and without this sonic-sairedis change. Once the sairedis change merges, we can change the ignore list to the expect list.
Summary:
Fixes # 20231
The sonic-sairedis change from https://github.com/sonic-net/sonic-sairedis/pull/1613 modified the behavior of BULK operations which resulted in the log spew …
=> Update ignore_regex in test_duplicate_route to support bulk update mode

tests/smartswitch/common/device_utils_dpu.py
Summary:
Fixes the dpu_ctrl test timeout 
DPU tests that expects processes running fail since there is not enough time (360s) to DPU to start all processes
Created a separate timeout constant DPU_MAX_PROCESS_UP_TIMEOUT = 400 s for the processes to start.
The old boot DPU_MAX_TIMEOUT renamed to DPU_MAX_ONLINE_TIMEOUT and remains 360 s
Re-ran the test with the new timeouts
=> Increase max dpu processes up timeout from 360s to 400s

ansible/library/load_extra_dpu_config.py, tests/common/helpers/gnmi_utils.py, tests/gnmi_e2e/conftest.py, tests/gnmi_e2e/helper.py, tests/gnmi_e2e/test_gnmi_auth.py, tests/gnmi_e2e/test_telemetry_auth.py
Add Telemetry cert authorization E2E test
Telemetry cert authorization does not have end to end test.
- Microsoft ADO **(number only)**: 
Add Telemetry cert authorization E2E test
Add Telemetry cert authorization E2E test
=> Add Telemetry cert authorization E2E test

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_sonic_vpp.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_vs_t2.yaml, tests/platform_tests/test_link_down.py, tests/platform_tests/test_link_down_sup.py, tests/platform_tests/utils.py
Optimize the `platform_tests/test_link_down.py` test for T2 splitting into two files: `platform_tests/test_link_down.py` for T2 front-end nodes (Line cards) with parallel optimization, and `platform_tests/test_link_down_sup.py` for the T2 Supervisor. T0 & T1 topologies are unchanged.
Summary:
Fixes # (issue) Microsoft ADO 34559041
On T2 topo, `platform_tests/test_link_down.py` currently takes too long (~85 minutes) to finish and we wanted to reduce the running time. 
We split it into two files: `platform_tests/test_link_down.py` for Line cards and `platform_tests/test_link_down_sup.py` for the Supervisor. 
The `platform_tests/test_link_down.py` now parallelizes across LCs using Python multithreading, which can reduce the running time by ~40%. The `platform_tests/test_link_down_sup.py` …
=> refactor: optimize test link down for T2

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
ERSPAN meter is not supported for Cisco-8000 ASICs so need to Skip this testcase
Summary:
Fixes # Failure due to Error thrown by SDK due to unsupported feature.
=> ERSPAN meter is not supported for Cisco-8000 ASICs so need to Skip this testcase

.azure-pipelines/pr_test_template.yml, azure-pipelines.yml
Summary:
In PR https://github.com/sonic-net/sonic-mgmt/pull/20002, I refined PR test template with strategy matrix jobs to reduce duplicate code, but it imported 2 issues:
1. Impact area would use `condition: contains(dependencies.get_impacted_area.outputs['SetVariableTask.PR_CHECKERS'], variables['CHECKER'])` to decide if we need to skip the topology, but variables['CHECKER'] would be get in such early step, it would pass empty string, so it would always success, then caused following calculate instance number failure.
2. `continueOnError` became a global configuration, so for optional jobs, if pipeline fail with stuck/timeout/cancel, the whole sonic-mgmt test will show as failure, then we can only force merge.
Roll back PR test template to hardcode version.
=> Roll back PR test template to fix PR test issues

tests/gnmi/test_gnmi_smartswitch.py
Using duthost.show_and_parse function
Summary:
Fixes # [18453](https://github.com/sonic-net/sonic-mgmt/issues/18453)
Bug fix, incorrect parsing of the command output with values containing spaces.
Eliminate code duplication.
Utilized the existing correct functionality to parse.
Ran the test on the on sn4280.
Applies to sn4280 platform.
N/A
=> Fixed the dpu status output parsing error.

tests/smartswitch/platform_tests/test_platform_dpu.py
Setting the "date" command parameters in the test to retrieve the system date/time from the DUTs in the ISO format and UTC timezone for the simpler and correct parsing in Python.
Summary:
Fixes erroneous failure of the test_npu_dpu_date 
Observed bogus test failures. Python3.8 incorrect handling of the timezones.
Aligned/simplified the "date" output formats
Ran on the system with the synchronized and non-synchronized DPUs
Switch+4 DPUs
N/A
=> Use ISO/UTC format when requesting the date/time from the DUT/DPUs.

ansible/roles/test/files/ptftests/py3/advanced-reboot.py
Summary:
Fix max_allowed_lacp_session_wait, needs to be set according to LACP multiplier used in test.
Set max_allowed_lacp_session_wait based on neighbor type and multiplier configuration
Ran test without providing ceos_neighbor_lacp_multiplier and setting ceos_neighbor_lacp_multiplier = 5.
=> [advanced-reboot] Set max_allowed_lacp_session_wait based on test_params

ansible/roles/test/files/ptftests/py3/copp_tests.py
Summary:
Fix the issue that m1 topos fail COPP test on LLDP and UDLD.
COPP rate limit of queue4_group3 for Mgmt devices is set to 300. But in copp_test default value of 100 is used.
m0 and mx were fixed in https://github.com/sonic-net/sonic-mgmt/pull/14627, now add m1.
test_copp.py passed for m1 topos
=> Set PPS_LIMIT to 300 on LLDP/UDLD/DHCP COPP test for m1 topology

tests/platform_tests/api/test_sfp.py
Summary:
Fix the following issue:
```
platform_tests/api/test_sfp.py::TestSfpApi::test_get_rx_los[xxxx]   FAILED     43%
01/09/2025 09:42:17 sfp.sfp_api                              L0018 INFO   | Executing sfp API: "get_rx_los", index: 16, arguments: "[]", result: "[False, False, False, False, False, False, False, False]"
01/09/2025 09:42:17 sfp.sfp_api                              L0018 INFO   | Executing sfp API: "get_transceiver_info", index: 17, arguments: "[]", result: "{'type': 'Backplane Cartridge', 'type_abbrv_name': 'BP', 'hardware_rev': '0.0', 'serial': 'APH1725600050   ', 'cable_length': 1.0, 'manufacturer': 'Amphenol        ', 'model': 'HS33006-001     ', 'vendor_date': '2025-04-30   ', 'vendor_oui': '41-50-48', 'vendor_rev': '03', 'application_advertisement': "{1: …
```
=> Fix is_xcvr_optical check failure for Moby backplane port SFP type

tests/qos/files/qos_params.th2.yaml
Summary:
encountered keyerror issue for topology topology dualtor-aa-56 on th2. as below:
```
qos/test_qos_sai.py::TestQosSai::testParameter[single_asic] 
-------------------------------- live log setup --------------------------------
02/09/2025 10:56:46 __init__._fixture_generator_decorator    L0088 ERROR  | 
KeyError('wm_pg_shared_lossless')
File "/var/src/sonic-mgmt_testbed-bjw3-can-dual-t0-7260-2/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
res = next(it)
File "/var/src/sonic-mgmt_testbed-bjw3-can-dual-t0-7260-2/tests/qos/qos_sai_base.py", line 1767, in dutQosConfig
qosParams = qpm.run()
File "/var/src/sonic-mgmt_testbed-bjw3-can-dual-t0-7260-2/tests/qos/files/brcm/qos_param_generator.p …
```
=> add missing qos test parameter for topology dualtor-aa-56 on th2

tests/common/helpers/platform_api/sfp.py, tests/platform_tests/api/test_sfp.py
Summary: As a result of https://github.com/sonic-net/sonic-platform-common/pull/590 , the application dependent fields are not returned by get_transceiver_info api. `platform_tests/api/test_sfp.py::TestSfpApi::test_get_transceiver_info` and 
`platform_tests/api/test_sfp.py::TestSfpApi::test_get_transceiver_threshold_info` were failing as a result. Removed application dependent fields from the tests to get them to pass again.
Fixes failure of `platform_tests/api/test_sfp.py::TestSfpApi::test_get_transceiver_info` and 
`platform_tests/api/test_sfp.py::TestSfpApi::test_get_transceiver_threshold_info` tests after https://github.com/sonic-net/sonic-platform-common/pull/590 is merged.
As a result of https://github.com/sonic-net/sonic-platform-common/pull/590 , the application …
=> Remove application dependent fields from get_transceiver_info tests.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Skip warm/fast reboot for isolated topo, as they are not supported.
skip unsupported platform test for `isolated` topo
updated mark conditions
on physical testbed.
=> skip warm/fast reboot for isolated topo

tests/bgp/test_prefix_list.py
Summary:
Add test case for T2 anchor feature
Test plan: https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/BGP-T2-Anchor-prefix-test-plan.md
Add 2 tests:
1. TSA test
* Announce contributing routes from neighbor for testing
* Add Anchor prefix and verify
```
1) Anchor prefixes are existing in DB
2) Anchor prefixes are existing in BGP table in DUT
3) Anchor prefixes are NOT existing in FIB table in DUT
) Anchor prefixes and contributing routes are announced to the neighbors with correct communities
```
* TSA device and verify
```
1) Anchor prefixes are existing in DB
2) Anchor prefixes are existing in BGP table in DUT
3) Anchor prefixes are NOT existing in FIB table in DUT
4) Anchor prefixes and contributing routes are NOT announced to the neighbors with …
```
=> [T2] Add T2 Anchor prefix test

tests/qos/files/qos_params.th5.yaml, tests/qos/qos_sai_base.py, tests/saitests/py3/sai_qos_tests.py
This adds QoS parameters and the necessary test case changes to use them. This generalizes the handling of `pkts_num_egr_mem` to be applied to all `Arista-7060X6*` SKUs and updates its value for TH5-512.
Changes were manually tested and verified for 100% pass rate of the `qos/test_qos_sai.py` tests.
Summary:
=> Add qos params for Arista-7060X6-16PE-384C-B-O128S2

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
34489144
Xfail the test_pfcwd_warm_reboot 
Xfail the test_pfcwd_warm_reboot
=> xfail test_pfcwd_warm_reboot for broadcom and mellanox

tests/common/devices/multi_asic.py, tests/common/devices/sonic_docker.py, tests/test_pretest.py
Summary:
This PR abstract the container handling method for sonic-mgmt. Provide a consistent way to handle and run command on docker containers in multi-asic and single-asic platform.
- https://github.com/sonic-net/sonic-mgmt/issues/20348 
- 34520139
Add abstraction for containers handling in sonic-mgmt
```python
Usage: 
duthost.containers().<container_name>().<method>()
```
Previously 
1. Execute on `syncd` for single-asic, `syncd0` for multi asic
```python
if duthost.is_multi_asic:
duthost.shell("docker exec syncd0 echo hello-world")
else:
duthost.shell("docker exec syncd echo hello-world")
```
2. Execute on `syncd` for single-asic. `syncd0`, `syncd1`, ...`syncdN` for multi asic
```python
if duthost.is_multi_asic:
for asic in duthost.asics:
duthost.shell(f"docker exec …
```
=> feat: add sonic docker manager module

tests/tacacs/test_ro_disk.py
Summary:
Fixes #20577 and Fixes #20584 
Bugs were causing failures on T2/multi-asic devices.
Correct the TSA/TSB assert behaviour
Tested on T2 multi-asic device - https://elastictest.org/scheduler/testplan/68c00dccdaa8f852625c8d1c
Tested on T1 single-asic device - https://elastictest.org/scheduler/testplan/68c0391b22b1312120142cd6
N/A
N/A
N/A
=> [test_ro_disk.py] Fix behaviour of TSA/TSB assert check on supervisor and multi-asic devices

tests/common/fixtures/ptfhost_utils.py, tests/run_tests.sh
Summary:
On dualtor testbed, in very early setup, it will try to fixture `run_icmp_responder_session`, if ptf is unreachable, the script doesn't know about it and still use ptfhost.copy to copy file from local to pfthost.
In this PR, the script will capture this exception and ensure to exit pytest early, no need to run any more cases on this unhealthy testbed, which wastes time and also avoids uploading many noise failed test results.
In ElasticTest, if ptfhost unreachable on one testbed, case failed on this testbed, and will pick up another testbed to run, it will generate many flaky results. It's better to exit pytest early and this testbed will be kicked out and no more other flaky results generated.
Similar PR was filed before …
=> Exit pytest with error code 16 if ptfhost is unreachable

tests/bgp/test_bgp_bbr_default_state.py
In the test, there is config reload, run loganalyzer when reload config run in the test will introduce some noise.
Summary:
=> skip the loganalyzer for the test_bbr_disabled_constants_yml_default

tests/dhcp_relay/test_dhcp_counter_stress.py
Summary:
In this test, we would invoke tcpdump to capture packets in DUT and compare packets count with DHCP counter and pcap file captured by tcpdump. Previous tcpdump buffer size was set to 0.1M, but in some low performance devices, buffer size of tcpdump is too small, which would cause packets capture incorrect sometimes
Increase the packets buffer size to 9M
1. Run tests in 7060 testbed
2. Run below cmd on 720DT / 7215 M0, 7260 / 7050 / 2700 /4600 t0 testbeds, make sure it wouldn't break stress test
```
nohup tcpdump --buffer-size=1048576 --immediate-mode -U -i any -w /tmp/func_capture_and_check_packet_on_dut_d67d67ae-7fd7-4b3e-b248-90b7b3884956.pcap udp dst port 67 or udp dst port 68 > /dev/null 2>&1
```
=> [dhcp_relay] Increase buffer size of tcpdump in dhcpmon counter stress test

tests/generic_config_updater/test_kubernetes_config.py
Summary: For this GCU test case, it doesn't need to enable log analyzer. And the log analyzer reports some error logs which are not relevant to this case itself, so need to disable the log analyzer to avoid flaky failure.
For this GCU test case, it doesn't need to enable log analyzer. And the log analyzer reports some error logs which are not relevant to this case itself, so need to disable the log analyzer to avoid flaky failure.
Disable the log analyzer for this case.
Run it in a testbed, it passed.
N/A
=> Disable log analyzer for k8s GCU test case to avoid flaky failure

ansible/roles/test/files/ptftests/py3/advanced-reboot.py
This allows timestamp comparisons to work
Summary:
MSFT ADO: 34628299
Fix the following error when advanced-reboot calculates dataplane disruption duration
```
******************************************stderr =
advanced-reboot.ReloadTest ... 02:55:33.486  device_connection: ERROR   : Caught exception socket.timeout: TimeoutError(), , <class 'TimeoutError'>
ERROR
ERROR: advanced-reboot.ReloadTest
File "/root/ptftests/py3/advanced-reboot.py", line 1470, in runTest
self.handle_post_reboot_test_reports()
File "/root/ptftests/py3/advanced-reboot.py", line 1344, in handle_post_reboot_test_reports
self.no_routing_stop - …
```
=> Fix fast-reboot advanced-reboot test TypeError: conversion from datetime.datetime to Decimal is not supported

tests/gnmi/conftest.py
Summary:
We disabled gnmi test for arm platform, and now we can remove this limitation.
Remove related fixture, including disable test and download gnmi client.
=> Enable gnmi test for non x86 platform

tests/iface_namingmode/test_iface_namingmode.py
…p checks instead
Summary:
- The test fails/flakes due to a fanout speed parser issue:
On the fanout the CLI prints Operational speed: (lowercase s), but our get_speed function in eos.py looks for Operational Speed: (capital S):
`found_txt = re.search(r'Operational Speed: (\S+)', output['stdout'][0])`
Because of the casing mismatch (and potential vendor/image formatting differences), the regex returns no match and the test fails.
- When the target speed of DUT is correct and the link is up, the link partner (fanout) must also be at a compatible speed, otherwise the link would not come up. Therefore, the fanout is at a compatible speed.
Removed the fanout speed assertion.
=> Skip fanout speed check due to EOS casing, using DUT speed and link up checks

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/conftest.py
Summary:
Fixes test_route_flap.py case failure on t1-isolated-d128 topo by skipping the case.
```
>       pytest.fail("Did not find a dut in duthosts that for topo type {} that has upstream nbr type {}".
format(tbinfo["topo"]["type"], upstream_nbr_type))
E       Failed: Did not find a dut in duthosts that for topo type t1 that has upstream nbr type T2
```
To fix the test_route_flap.py on t1-isolated-d128 topo.
`enum_upstream_dut_hostname` is supposed to find a dut that has upstream nbr for its topo. But since t1-isolated-d128 didn't have upstream, case would be failed at setup. And `enum_upstream_dut_hostname` is only used for T2 topo, so return a first DUT name for t1-isolated-d128 topo to get the case running. Case is skipped after the fix, so skip it in conditional mark.
``` …
```
=> [t1-isolated-d128][test_route_flap] Skip test_route_flap.py on t1-isolated-d128 topo

tests/platform_tests/api/watchdog.yml
Summary:
Missing the watchdog configure in the watchdog.yml so that the case `platform_tests/test_sequential_restart.py` failed
This pull request introduces support for the `x86_64-nvidia_sn5640-r0` platform in the watchdog API tests by adding relevant timeout settings.
Check in the sn5640 platform
=> [test_watchdog]: Add watchdog yml for sn5640

tests/platform_tests/test_link_down.py
Summary: Enable DT2 on test link down
Fixes # (issue) 32921769
this test is passing and can be enabled for dt2 topo
ft2: 
lt2:
=> chore: enable dt2 on test_link_down

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
…r 202505 release
Summary:
skip generic_config_updater.test_packet_trimming_config_asymmetric  for 202505 release as there is no packet trim feature in 202505 release
Previous PR skipped test_packet_trimming_config_symmetric, this PR adds test_packet_trimming_config_asymmetric, 
skip generic_config_updater.test_packet_trimming_config_asymmetric  for 202505 release as there is no packet trim feature in 202505 release
=> skip generic_config_updater.test_packet_trimming_config_asymmetric for 202505

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
This is adding a new section to the tests_mark_conditions.yaml file so that common conditions can be defined once, and then re-used in the rest of this file.
This section currently only defines lossyTopos, and this change uses that throughout the tests_mark_conditions.yaml file.
This is a manual cherry-pick of
https://github.com/sonic-net/sonic-mgmt/pull/20326
https://github.com/sonic-net/sonic-mgmt/pull/20642
=> 202505 cherry-pick: Skipping PFCWD tests for lossy topos & add anchor section

tests/lldp/test_lldp_syncd.py
Summary: Sometimes the function `get_lldp_entry_content` will return an empty result since the content has not populated to database yet. When re-run the query we can see the content exists
This PR will add a simple retry mechanism to make sure that the content exists
This is to prevent false positive issue like
```
File "/var/src/sonic-mgmt_vms13-lt2-7060x6-8/tests/lldp/test_lldp_syncd.py", line 246, in verify_each_interface_lldp_content
assert_lldp_entry_content(interface, entry_content, lldpctl_interface)
File "/var/src/sonic-mgmt_vms13-lt2-7060x6-8/tests/lldp/test_lldp_syncd.py", line 156, in assert_lldp_entry_content
chassis_info = lldpctl_interface["chassis"][entry_content["lldp_rem_sys_name"]]
KeyError: 'lldp_rem_sys_name'
```
Fixes # (issue) 34939751
Fix flakiness for lldp syncd …
=> [DT2] get entry content with retry to ensure populated

tests/qos/qos_sai_base.py
Summary:
For hwsku using t1-isolated-d128 topo, there is no uplink neighbor, all neighbors are T0. Removing them from the per_dir list.
Removing TH5 400G t1 hwsku from the per_dir list.
=> remove per_dir support for t1-isolated-d128 topo

tests/gnmi/helper.py, tests/gnmi/test_gnmi_stress.py
Summary:
We need to assess GNMI API latency across multiple platforms.
The new test will invoke the GNMI API 10 times and measure the total execution time. Currently, there is no defined latency threshold. The next step will be to collect performance data across multiple platforms, which will inform the establishment of an appropriate latency threshold.
=> Add stress test for GNMI API latency

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Note: this is a manual cherry-pick to 202505 of https://github.com/sonic-net/sonic-mgmt/pull/20552
Note: depends on https://github.com/sonic-net/sonic-mgmt/pull/20382 to pass static analysis.
Skip the following tests:
decap/test_decap.py::test_decap[ttl=pipe, dscp=uniform, vxlan=set_unset]
vxlan/test_vxlan_decap.py
for the following topologes:
- t0-isolated-d32u32s2
- t0-isolated-d256u256s2
- t0-isolated-v6-d32u32s2
- t0-isolated-v6-d256u256s2
- t1-isolated-d56u2
- t1-isolated-d56u1-lag
- t1-isolated-d448u15-lag
- t1-isolated-v6-d56u2
- t1-isolated-v6-d56u1-lag
- t1-isolated-v6-d448u15-lag
- t1-isolated-d32
- t1-isolated-d128
- t1-isolated-v6-d128
- t0-isolated-d96u32s2
- t0-isolated-v6-d96u32s2
Summary:
Skip tests that are not required for the following topologies: …
=> [TH5] Skip VxLAN Tests for Non-Applicable Topologies

ansible/templates/minigraph_device.j2
Summary:This commit introduces logic to assign the 'Dpc' role based on specific conditions within the port alias and subtype.
- [ X] 202411
- [X ] 202505
The 'Dpc' role is now assigned when:
The subtype is defined and equals 'SmartSwitch'.
The integer value extracted from the intf variable (starting from the 8th character) is greater than or equal to 224.
Deployed the minigraph and confirmed that the DPU role configuration is present for all backplane interfaces.
HwSKU: Cisco-8102-28FH-DPU-O
t1-128-lag
=> Add Dpc role assignment for SmartSwitch interfaces

tests/common/snappi_tests/common_helpers.py
Summary: community is using different naming convention for ixia devices. This will add some extra naming convention as required 
Fixes # (issue) 34957124
=> fix: fix peer_snappi_chassis issue for t0/t1 community

tests/snappi_tests/bgp/conftest.py
Summary: Fix stop iteration for bgp t0/t1 device 
```
@decorator.decorator
def _fixture_generator_decorator(fixture_generator, *args, **kargs):
logging.info("-" * 20 + (" fixture %s setup starts " % fixture_generator.__name__) + "-" * 20)
it = fixture_generator(*args, **kargs)
try:
>           res = next(it)
E           StopIteration
```
Fixes # (issue) 3498901
=> chore: fix StopIteration on bgp test

tests/common/snappi_tests/port.py, tests/common/snappi_tests/snappi_fixtures.py
Summary: Add support for ipv6 addresses in T0 and T1 for future testing use cases (ex. packet trimming)
To allow support for ipv6 traffic flows on T0/T1 snappi flows
=> [Snappi] Add support for ipv6 in T0 and T1

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Ignore iptable command nss_tacplus error in loganalyzer_common_ignore.txt
test_everflow_dscp_with_policer failed because following error:
2025 Sep 13 00:18:15.829923 str2-msn2700-spy-2 ERR iptables: nss_tacplus: failed to connect TACACS+ server 10.64.246.146:49, ret=-8: Operation now in progress
These test case enable everflow which may cause DUT device lost network to PTF device.
- Microsoft ADO **(number only)**: 34922073
Ignore iptable command nss_tacplus error in loganalyzer_common_ignore.txt
Ignore iptable command nss_tacplus error in loganalyzer_common_ignore.txt
=> Ignore iptable command nss_tacplus error in loganalyzer_common_ignore.txt

tests/qos/files/qos_params.th2.yaml
Summary:
nightly failure, as below:
```
KeyError('wm_q_shared_lossless')
File "/var/src/sonic-mgmt_vms64-dual-t0-7260-1/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
res = next(it)
File "/var/src/sonic-mgmt_vms64-dual-t0-7260-1/tests/qos/qos_sai_base.py", line 1767, in dutQosConfig
qosParams = qpm.run()
File "/var/src/sonic-mgmt_vms64-dual-t0-7260-1/tests/qos/files/brcm/qos_param_generator.py", line 521, in run
self.prepare_default_parameters()
File "/var/src/sonic-mgmt_vms64-dual-t0-7260-1/tests/qos/files/brcm/qos_param_generator.py", line 640, in prepare_default_parameters
self.create_default_queue_shared_watermark_parameter(que_profile)
File …
```
=> correct qos param of topo dualtor-aa-56 on th2 platform

ansible/library/testbed_vm_info.py
Summary:
After ansible >= 2.14, custom modules are executed on the managed node (or in an execution environment container) that only contains the runtime bits Ansible intentionally ships there (mainly ansible.module_utils plus Python stdlib). Controller‑only internals like ansible.inventory.manager and ansible.parsing.dataloader are not present. So importing them on the remote side is fundamentally unsupported now.
This change removed the code of importing ansible API in the testbed_vm_info.py customized module. Then this module can be executed in sonic-mgmt docker using ansible >= 2.14.
Tested on ansible 2.13.13 and 2.19.2
=> Fix testbed_vm_info.py for ansible >= 2.14

tests/common/plugins/sanity_check/checks.py
Summary:
Some tests might left the DUT with mux config as `active`/`standby`, and sanity check will complain.
Let's recover the DUT mux config back to `auto` in the very first place.
* set mux config as standby on DUT, and run testcase to validate the sanity check can recover and testcase can pass.
```
bgp/test_bgp_update_timer.py::test_bgp_update_timer_single_route[str3-7260cx3-acs-2-default] PASSED                                                                                                                                                                                                                                          [100%]
======================================================================= …
```
=> [dualtor] Recover mux config to `auto` in sanity check

ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py, tests/common/dhcp_relay_utils.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/dhcp_relay/test_dhcp_relay.py
Summary:
Currently, we don't have test case to check if the DHCP montior's cheksum validation works or not.
Send invalid packets with incorrect IP/UDP checksum and check of the counter of Malformed
run the test case test_dhcp_monitor_checksum_validation 
Due to this PR https://github.com/sonic-net/sonic-dhcpmon/pull/51 blocks the new image build, we need to bypass the test_dhcp_relay_default and test_dhcp_relay_monitor_checksum_validation, once the new image built, we can recover the test cases.
=> Add test case test_dhcp_monitor_checksum_validation to verify dhcp monitor IP/UDP checksum validation feature

tests/route/test_static_route.py
Summary:
Stablize `test_static_route` on dualtor:
1. check neighbor status after populating the arp entry.
2. send more packets in packet verification.
3. recover mux config to `auto` to allow faster recovery.
```
route/test_static_route.py::test_static_route[bjw3-can-7260-15] PASSED                                                                                                                                                                                                                                                                       [ 25%]
route/test_static_route.py::test_static_route_ecmp[bjw3-can-7260-15] PASSED …
```
=> [dualtor] Stablize `test_static_route`

tests/dualtor_mgmt/test_server_failure.py
Summary:
The test requires the upper tor to be active, but it uses
`toggle_all_simulator_ports`, which is deprecated.
Let's use the correct toggle fixture to allow better toggle success.
```
dualtor_mgmt/test_server_failure.py::test_server_reboot[active-standby] PASSED                                   [ 50%]
dualtor_mgmt/test_server_failure.py::test_server_reboot[active-active] SKIPPED (Skip as no mux ports of 'active-
active' cable type)                                                                                              [100%]
=================================================== warnings summary ===================================================
```
=> [dualtor] Fix `test_server_reboot`

tests/telemetry/telemetry_utils.py, tests/telemetry/test_telemetry.py
The PR contains changes to `test_telemetry.py` failures when `docker-ptf` was updated to build on Debian Bookworm slave with locally installed p4lang packages. The changes are required because of restricted Ansible shell python path settings and globally installed p4lang package dependencies (`protobuf` compiler) conflicting with the virtual environment changes.
Summary:
See above.
Set env-python3 python path.
Locally
NA
NA
=> Telemetry test fixes for updated docker-ptf

tests/bgp/test_bgp_suppress_fib.py
Summary:
Skip test_bgp_suppress_fib if T1 topology does not have spine layer (ex: t1-isolated-d128)
=> Skip test_bgp_suppress_fib for T1 with no spine layer

tests/common/dualtor/dual_tor_utils.py
Validates server-status for active-active mux ports
Summary:
Fixes # (https://github.com/aristanetworks/sonic-qual.msft/issues/804)
In some tests, we configure active active dualtor to active standby via `config mux mode <state> <port>`. State of the configured port should be validated from server's perspective as well to meet test's expectations.
Added extra check for `SERVER_STATUS`
=> Validate server-status for active-active mux ports.

tests/everflow/everflow_test_utilities.py, tests/everflow/test_everflow_testbed.py
We should not use soc ip as server ip, It can interfere with grpc connection between tor and nic_simulator.
We should not use soc ip as server ip, It can interfere with grpc connection between tor and nic_simulator.
Summary:
Fixes # (https://github.com/aristanetworks/sonic-qual.msft/issues/804)
In case of dualtor, we have notion of soc IPs, which are critical for tor-nic-simulator communication via grpc. For everflow/test_everflow_testbed.py we were using one of these IPs as `DEFAULT_SERVER_IP` that can interfere with grpc connection.
defined `get_default_server_ip()` which gives correct server IP in case of dualtor topo
ran everflow/test_everflow_testbed.py
=> Avoid using soc ip as server ip in everflow/test_everflow_testbed.py

tests/arp/conftest.py
Summary:
Allow time for ndppd to fully start up after ndp proxy changes
Test is running when ndppd is not fully ready yet. Happens only on topologies with many interfaces (even if those interfaces are down).
`arp/test_arp_extended.py::test_proxy_arp[v6-*]` no longer fails.
Large topologies, i.e.  > 256 total intfs (up and down).
=> Allow time for ndppd to startup after arp/ndp proxy changes

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
dhcp_relay related tests were skip in vs by this PR https://github.com/sonic-net/sonic-mgmt/pull/20655
It was to unblock submodule update PR: https://github.com/sonic-net/sonic-buildimage/pull/24046. Now the submodule update pr has been merged, hence remove the skip condition
Remove skip for dhcp_relay test on vs
PR check
=> [dhcp_relay] Remove skip dhcp_relay related tests on vs asic

ansible/library/announce_routes.py
Summary:
When announce routes more than 1000, previous code will post those routes in single http post, and the exceed routes may be dropped in silence, when show routes on DUT, DUT only print 1000 routes.
To avoid this issue, post routes in batch.
When announce routes more than 1000, previous code will post those routes in single http post, and the exceed routes may be dropped in silence, when show routes on DUT, DUT only print 1000 routes.
To avoid this issue, post routes in batch.
Run on testbed
=> Post routes to ptf exabgp in batch to avoid failure in silence

tests/bgp/test_bgp_establish_combo.py
Summary:
Add testcase to verify BGP establish on various role combo for M1.
Add testcase to verify BGP establish on various role combo for M1.
Modify DUT type and it's neighbor type, then restart BGP service and verify BGP session can establish.
Verified on Arista-7050CX3 M1-128 testbed.
M1 specific testcase.
=> [M1] Add testcase to verify BGP establish on various role combo

tests/qos/files/qos_params.th5.yaml
Summary:
For Moby hwsku, uplink and downlink has different speed and cable length, hence creating the params for each profile seperately.
one params for 400000_5m.
```
pkts_num_trig_ingr_drp: 136239
pkts_num_trig_pfc: 134690
pkts_num_trig_egr_drp: 134624
```
one params for 400000_40m.
```
pkts_num_trig_ingr_drp: 136446
pkts_num_trig_pfc: 134690
pkts_num_trig_egr_drp: 134624
```
Update QoS params values.
=> Update qos params for Arista-7060X6-16PE-384C-B-O128S2

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/lldp/test_lldp.py
Summary:
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/19658
This pull request updates the LLDP test suite to improve reliability and clarity when testing LLDP neighbor functionality after restarting the `swss` container, instead of just the `orchagent` process. The changes also improve log analysis and clean up code to remove unnecessary complexity.
**Test behavior and reliability improvements:**
* The test previously named `test_lldp_neighbor_post_orchagent_reboot` has been renamed to `test_lldp_neighbor_post_swss_reboot` and now restarts the entire `swss` container, not just the `orchagent` process. This makes the test more robust and consistent with how services are typically managed. [[1]](diffhunk://#diff-9dc8b2b410c2fb399f9fd25115bb8b5c13e2d1f1a393e9fa0942957171e0530fL26-L3 …
=> Fix lldp test on all platform

tests/bfd/test_bfd.py
Double commit of https://github.com/sonic-net/sonic-mgmt/pull/19972 to 202505
Summary:
=> [202505] Send ping to bringup IPv6 BFD sessions.

tests/drop_packets/configurable_drop_counters.py
This PR addresses parsing issues in the get_device_capabilities() function that led to incorrect mapping between drop counter types and reasons.
Motivation for this PR 
drop_packets/test_configurable_drop_counters.py test_neighbor_link_down test case failure. 
The failure occurred due to incorrect parsing of the show dropcounters capabilities CLI output. Drop reasons from PORT_EGRESS_DROPS and SWITCH_EGRESS_DROPS were incorrectly appended to the ingress drop counter reasons, leading to test failure
CLI Parsed 
```
cisco@sup-t0-dut:~$ show dropcounters capabilities
Counter Type            Total
--------------------  -------
PORT_INGRESS_DROPS       5000
PORT_EGRESS_DROPS        5000
SWITCH_INGRESS_DROPS     5000
SWITCH_EGRESS_DROPS      5000
PORT_INGRESS_DROPS
BLACKHOLE_ROUTE …
```
=> Fixing parsing get_device_capabilities show dropcounters capabilities

docs/testplan/dash/VXLAN_source_port_range.md, tests/dash/constants.py
Summary:
The port number should be [5120, 5247] when the start port is 5120 and the mask is 7 bits.
Run the dash pl test on SN4280, passed.
=> [Dash] Fix the wrong port number range in dash vxlan source port test

tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
The secret_group_vars is not always exist for all users, need to allow the secret_group_vars not defined as previously, the logic was broke by the PR: https://github.com/sonic-net/sonic-mgmt/pull/20269
Summary:
=> Fix pdu issue 

tests/qos/test_buffer.py
Summary: Fixes the buffer-deployment test bug where buffer checks were being done on service ports which do not have key buffer attributes; skip lossless buffer config checks on those ports where lossless config is not present/expected. This makes the test case more robust.
With the changes in [#24085](https://github.com/sonic-net/sonic-buildimage/pull/24085), this test now passes.
Bug fix - causing successive test failures.
If a port does not have any lossless config associated with it, skip the lossless buffer check
=> [QoS] Fix buffer-deployment test bug

tests/lldp/test_lldp.py
Summary:
This PR is to address new issue found on PR https://github.com/sonic-net/sonic-mgmt/pull/20838
Issue caused by loganalyzer not applied for all DUTs for T2, failing the test as we observe ERR logs (as expected during swss restart).
This PR is to ignore expected ERR messages on other DUTs.
T2 test plan 68d53b2af0e80c65e670d63f
============= 2 passed, 1 skipped, 4 warnings in 994.55s (0:16:34) =============
=> Apply loganalyzer on all duts for T2 support

tests/acl/custom_acl_table/test_custom_acl_table.py, tests/acl/null_route/test_null_route_helper.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: Update tests for V6 only topo.
- _custom_acl_,  _null_route_ - do validation only for ipv6
- _stress_acl_ - the test is ipv4 only, added skip in conditions mark
Tests running on new topologies
Updated existing tests
Tests verified on t0-isolated-v6-d32u32s2
=> Update tests custom_acl, null_route for V6 only topo

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Xfail test_acl_egress_drop for ipv6 only topologies.
*https://github.com/sonic-net/sonic-mgmt/issues/19921
- [] New Test case
- [] Skipped for non-supported platforms
*The test is set for IPv4 and fail when run on IPv6 only topo testbed
Add xfail in tests_mark_conditions.yaml as this test run only for ipv4.
rerun and make sure test is skip if fail for ipv6 only.
=> Xfail test_acl_egress_drop for ipv6 only topologies.

tests/telemetry/show_cli_to_gnmi_path.py
Summary:
Add python library for converting show command into SHOW gnmi xpath.
Rules:
- Cannot use short form of options (-v, -i, -a)
- For options that take in a value such as --period or --interface they must be supplied with "=" and the value such as --period=5 or --interface=Ethernet0,Ethernet40
- All other long form option without values will be treated as bools like --verbose = [verbose=True]
- Escape forward slash, use shlex to unescape . Special characters like =,[,] will be errored out if they appear in path or option key/value
- Convert show cli command to SHOW gnmi path in place, keep option order and tokens
show interfaces counters --period=5 detailed --verbose = "interfaces/counters[period=5]/detailed[verbose=True]
```
$ python3 show_cli_to_gnmi_path.py -c …
```
=> Add show command to gnmi path conversion library

.azure-pipelines/pr_test_scripts.yaml
Summary:
test_vxlan_bfd_tsa is not supported on sonic-vpp platform yet. 
remove the test suite from .azure-pipelines/pr_test_scripts.yaml
=> Remove test_vxlan_bfd_tsa from t1-lag-vpp test list

tests/smartswitch/common/device_utils_dpu.py, tests/smartswitch/platform_tests/test_reload_dpu.py
Mellanox DPUs report a different reason for the DPU reboot when the switch is rebooted.
Summary:
Fixes # (issue) N/A
Support the Mellanox and other platforms that may report the reboot reason differently
Passing a complied regex in the case of multiple possible reboot reasons. Checking the type before comparing with the reported reboot reason.
ran dpu_reload_test.py
Mellanox DPU reports "Non-hardware" as the reboot reason when the switch is rebooted.
N/A
N/A
=> Add a regex option to support multiple  DPU reboot reasons

tests/bgp/test_bgp_update_replication.py
Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/20583
Additionally, adds missing topology markers.
As mentioned in the issue, Mellanox devices would consistently fail upon starting the lower intervals. Additionally, CPU and memory thresholds were arbitrary and unnecessary, and could not be guaranteed to be satisfied.
Topology markers were also missing, so added them to ensure tests run on all expected platforms.
* Replaced intervals with platform-specific intervals, with the default ensuring passing on all platforms, and more specific intervals allowing platform owners to speed up the test after performing tests on devices:
* Defaults to [10, 9, 8] 
* Mellanox: [4.0, 3.5, 3.0]
* Arista: [5.0, 4.5, 4.0]
* Removed CPU and memory thresholds (kept the calculated values in the …
=> [BGP] Fix Update Replication Test on Mellanox Devices

ansible/library/nut_allocate_ip.py, ansible/module_utils/graph_utils.py, ansible/roles/testbed/finalize/tasks/main.yml, ansible/roles/testbed/nut/tasks/dut_create_config_patch.yml, ansible/roles/testbed/nut/templates/config_patch/dut/interfaces.json.j2
Summary:
In the L3 snake setup, we need distinct MAC address for each interface, otherwise it will fail on the L2 forwarding.
This commit adds the interface MAC.
Tested locally with ping after config.
=> Fix L3 snake testbed setup.

ansible/roles/test/files/ptftests/py3/hash_test.py, tests/common/plugins/conditional_mark/tests_mark_conditions_sonic_vpp.yaml, tests/fib/test_fib.py
Summary:
Port test_fib.py to sonic-vpp platform. sonic-vpp has limited support with hash calculation but it does support src-ip, dst-ip, src-port, dst-port. With these, it can support base hash test.
There is also a bug in hash_test.py where hash_key parameter is not provided in the call of check_within_expected_range. 
Specify supported hash-key for vpp platform
Remove skip marker to enable fib/test_fib.py::test_hash
run the test in t1-lag topology
This is specific for sonic-vpp
=> Port test_fib.py test cases to sonic-vpp platform
