sonic-net/sonic-mgmt

tests/snappi/files/helper.py, tests/snappi/pfc/test_pfc_pause_lossy_with_snappi.py, tests/snappi/pfcwd/test_pfcwd_basic_with_snappi.py, tests/snappi/pfcwd/test_pfcwd_m2o_with_snappi.py
Summary:
Skip snappi warm-reboot testcases on TD2 platform
Skip snappi warm-reboot testcases on TD2 platform
Compare the skipped testcases of tgen and snappi, and skip the ones that need to be skipped in snappi.
=> [RDMA&SNAPPI] Skip snappi warm-reboot testcases on TD2 platform

tests/bfd/conftest.py, tests/bfd/test_bfd.py
- BFD Session scaling to 100 sessions.
- Added testcases to verfiy both IPV4 and V6 session creation in both orders
- DUT Initiation followed by PTF
- PTF session creation followed by DUT.
- Modified the test to use batch commands instead of single ones to improve test performance.
Summary: Updated the BFD test to perform the following.
The existing BFD tests were not functional and they were not providing sufficient coverage.
Added more test cases, Improved the structure of existing test cases, and added a scale test.
Ran on a DUT.
=> BFD test update

tests/pipelines/cont-warmboot.yml
Summary:
Transfer organization from Azure to sonic-net
=> [ci] Transfer organization from Azure to sonic-net

tests/common/utilities.py, tests/conftest.py
Summary:
Cherry pick PR https://github.com/sonic-net/sonic-mgmt/pull/6007 to 202012
branch has conflicts.
Created a separate PR to have those changes in 202012 branch.
=> Fix filename issue and collect important DB dumps

tests/generic_config_updater/test_cacl.py
Summary: Resolve dualTor cacl test failure.
Change to identical DUT for cacl test
Change fixture from `duthost` to `rand_selected_dut`
=> [GCU] Change to identical DUT for cacl test

tests/saitests/sai_qos_tests.py
Fix issue: there should be one DSCP mapped to queue 2/6 in non dual-ToR scenarios
Summary:
=> Fix issue: there should be one DSCP mapped to queue 2/6 in non dual-ToR scenarios

tests/common/utilities.py
Summary: Bug fix: add missing import for util function in test_decap
test_decap is failing on master branch due to a bug introduced by https://github.com/sonic-net/sonic-mgmt/pull/5834
The changes were tested on 202012, but not on master where the json import did not exist.
Added missing import.
Tested on physical testbed
```
decap/test_decap.py::test_decap[ttl=pipe, dscp=uniform, vxlan=disable] PASSED                                                                                                   [ 25%]
decap/test_decap.py::test_decap[ttl=pipe, dscp=uniform, vxlan=set_unset] PASSED                                                                                                 [ 50%]
decap/test_decap.py::test_decap[ttl=pipe, dscp=pipe, vxlan=disable] SKIPPED …
```
=> [decap] Bug fix: add missing import for util function in test_decap

tests/configlet/util/generic_patch.py
Summary: Remove the ignore path that were blocked by YANG before.
The ignore_path should be removed in apply-patch operation.
Remove ignore_path.
=> [tests/configlet] Remove ignore path in addrack test

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
There is a condition error in tests_mark_conditions.yaml, fix it. 
Summary:
There is a condition error in tests_mark_conditions.yaml, fix it.
=> [bugfix] Fix an error in tests_mark_conditions.yaml

docs/testplan/syslog/Syslog_Source_IP_test_plan.md
Add test plan for syslog source ip feature.
Syslog source IP HLD: https://github.com/JibinBao/sonic-mgmt/pull/new/syslog_test_plan
Summary:
Add test plan for syslog source ip feature
Any
Any
=> Add test plan for syslog source ip feature

ansible/roles/eos/templates/dpu-tor.j2, ansible/vars/topo_appliance.yml
Summary:
New topology is needed for DASH testbeds
=> [topo]: Add appliance topology files

docs/testbed/README.testbed.VsSetup.md
Summary:
The command `ssh $USER@172.17.0.1` would not work if openssh-server is not installed on host server.
=> Update README.testbed.VsSetup.md to include installation of openssh-server

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Fixes sensors case errors
Make sensors case working for x86_64-wistron_sw_to3200k-r0 platform
Update sensors data
Run sensors TC case and get PASS result
root@lab-3200k:/home/admin# show version
SONiC Software Version: SONiC.202111.0-dirty-20220727.101343
Distribution: Debian 11.4
Kernel: 5.10.0-8-2-amd64
Build commit: 04cd65ded
Build date: Wed Jul 27 02:30:41 UTC 2022
Built by: roger@ntc-PowerEdge-R740
Platform: x86_64-wistron_sw_to3200k-r0
HwSKU: Wistron_sw_to3200k_32x100
ASIC: innovium
ASIC Count: 1
Serial Number: 681Z0P16000512600006M0SE
Model Number: SW-TO3200K
Hardware Revision: 0
Uptime: 16:48:37 up 9 min,  2 users,  load average: 2.03, 2.1
=> [sensors] Add sku sensor data for Wistron sw_to3200K platform

.azure-pipelines/run-test-scheduler-template.yml
Summary:
Use TestbedV2's public email group
Use TestbedV2's public email group
=> [TestbedV2]Use TestbedV2's public email group

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Skip some platform tests due to HW design limitation
Avoid some unexpected failures when platform test
Add skip case in tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Perform platform test cases
N/A
N/A
=> Add the skip item for wistron 3200K platform

tests/common/innovium_data.py, tests/common/system_utils/docker.py, tests/qos/test_buffer.py
Signed-off-by: kbabujp [kbabujp@marvell.com](mailto:kbabujp@marvell.com)
Adding Innovium(Marvell) specific changes to run QOS buffer tests
Summary:
* Added file to check the chip type
* Changed the buffer item to check in innovium (Marvell) chip
* Added vendor_id check in common/system_utils/docker.py
To pass QOS buffer test on innovium(Marvell) chip
Added conditional check to modify expected buffer item to check in buffer_items_to_check_dict dictionary 
Test test_buffer.py passed with this change
=> Adding Innovium(Marvell) specific changes to run QOS module tests

ansible/library/snmp_facts.py, ansible/roles/test/tasks/snmp/memory.yml, tests/snmp/test_snmp_memory.py
Summary:
Memory spelled as Memery
Spelling mistake sometimes makes it difficult to locate code
Run tests
=> [typo] fix spelling mistake "memery"

ansible/templates/minigraph_png.j2
Summary:
dev_type spelled as dev_ytpe
Fix spelling mistakes
Generate minigraph and deploy to DUT.
Use ./testbed-cli.sh deploy-mg to gen&deploy minigraph successfully,
All the related configuration are correct pushed to DUT after deploy.
=> [typo] fix spelling mistake "dev_ytpe"

ansible/group_vars/sonic/sku-sensors-data.yml, tests/platform_tests/test_sensors.py
Summary:
We have a new respin type of msn3700/3700c which is called the swb respin msn3700/3700c. The new respin have differences in sensors compared to the legacy type . The sensor conf file for the swb respin have been merged as part of this PR: https://github.com/sonic-net/sonic-buildimage/pull/11553. 
So the test need to be updated for it. 
Update sensors test for the new respin msn3700/3700c
Add the new swb respin platform in the /ansible/group_vars/sonic/sku-sensors-data.yml. 
Add logic in test_sensors.py to decide if the dut is the respin 3700/3700c.
By manual and automation.
The change is only for the swb respin msn3700/3700c
=> [Mellanox][sensors] Update sensors test for the new respin msn3700/3700c

tests/common/plugins/conditional_mark/__init__.py
Summary:
For now we can't skip a test on a specific testbed by the pytest conditional mark. The reason why we need that is we have some tests for transceivers that may fail on the testbeds with some specific type of transceivers when there is a bug, and we want to skip the test while the bug is being handled.
And the way to get the improvement is very easy, just need to add the testbed_name item into the basic_facts dict so that we can skip test by a specific setup or setup and topology.
For example, after the improvement we can add skip condition in test_mark_conditions.yaml like:
```
xxx/test_xxx.py:
skip:
reason: "Skip running on r-tigon-21"
conditions:
- "'r-tigon-21' in testbed"
xxx/test_xxx.py:
skip:
reason: "Skip running on r-tigon-20 when topology is t1"
conditions:
- …
```
=> Add a new 'by testbed' skip condition for the pytest conditional mark

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Ignore the error relating to SAI_OBJECT_TYPE_ACL_COUNTER reported by syncd of vSonic. 
In test case `generic_config_updater/test_monitor_config.py`, it will create acl rule and acl flex counter.  In vSonic, feature **acl** has not been implemented and acl counter cannot be collected from vs SAI. The following error message needs ignored:
> Aug 23 04:08:54.213088 vlab-01 ERR syncd#syncd: :- collectData: Failed to get attr of SAI_OBJECT_TYPE_ACL_COUNTER 0x9000000000727: -15
=> [LogAnalyzer] Add ignore log for SAI_OBJECT_TYPE_ACL_COUNTER

tests/ip/test_ip_packet.py
Summary:
1. Need to run ip packet testcase with topology
2. Need to optimize code and error log
1. Add topology mark any
2. Add more discription in error log
3. Change max packet range and some logic
Run test
=> Enable and optimize ip_packet case

ansible/library/snmp_facts.py, tests/common/helpers/snmp_helpers.py, tests/snmp/test_snmp_memory.py
Add swap related functions and tests to snmp tests
Summary:
We plan on turning on swap for Haliburton device. So naturally related tests are needed.
Modified ansible module and add related tests.
Run test and it passed.
=> [snmp] enable swap related functions and tests for snmp

.azure-pipelines/pr_test_scripts.yaml, .azure-pipelines/run-test-scheduler-template.yml, .azure-pipelines/test_plan.py, azure-pipelines.yml
Summary:
Migrate t0 test to TestbedV2
Migrate t0 test to TestbedV2
Migrate t0 test to TestbedV2
The pr test pipeline itself tests it
=> [TestbedV2] Migrate t0 test to TestbedV2

ansible/roles/vm_set/tasks/announce_routes.yml, ansible/roles/vm_set/tasks/remove_topo.yml, ansible/roles/vm_set/tasks/renumber_topo.yml
Summary:
We observed test server CPU stuck issue when "testbed-cli.sh restart-ptf"
is executed to restart the PTF docker container for a deployed testbed
topology. The stuck issue has been correlated with the stop of removing
the PTF container.
There have been some efforts trying to work around this issue:
* https://github.com/sonic-net/sonic-mgmt/pull/6131
* https://github.com/sonic-net/sonic-mgmt/pull/6191
It turns out that these changes are not working.
This change is to stop the exabgp process running in PTF container before
stopping and removing it.
Tried "testbed-cli.sh restart-ptf" over 30 times with this change, the stuck
issue is not observed. Let's take this change and keep watching to see if
the issue happens again.
Tried "testbed-cli.sh restart-ptf" over 30 …
=> Stop exabgp before stopping and removing PTF container

.azure-pipelines/test_plan.py
Summary:
Print test plan utils parameters
Print test plan utils parameters
Print test plan utils parameters
=> [TestbedV2]Print test plan utils parameters

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Fix the missing entries in sku-sensors-data.yml for wistron 3200K
Missing items will cause fail
add the 
"
psu_skips: {} 
sensor_skip_per_version: {}
"
Perform platform test cases
N/A
N/A
=> Correct the sku-sensors-data.yml for Wistron 3200K platform

tests/show_techsupport/tech_support_cmds.py, tests/show_techsupport/test_techsupport.py
Summary:
update show tech command case since generate_dump output changed
Latest generate_dump output changes due to enhancement.
Need to modify the case script meanwhile.
Checked the output of generate_dump, whether including "bash -c".
If including"bash -c", add '/' in check cmd group.
Run the show tech commands case in both 202205 and 202012 OS images.
=> 20220830 15280278 showtech commands

tests/acl/null_route/test_null_route_helper.py, tests/acl/test_acl_outer_vlan.py, tests/arp/test_tagged_arp.py, tests/bgp/test_bgp_speaker.py, tests/copp/test_copp.py, tests/dhcp_relay/test_dhcp_relay.py, tests/dhcp_relay/test_dhcpv6_relay.py, tests/everflow/test_everflow_ipv6.py, tests/fdb/test_fdb.py, tests/fdb/test_fdb_mac_expire.py, tests/generic_config_updater/test_bgpl.py, tests/generic_config_updater/test_cacl.py, tests/generic_config_updater/test_dhcp_relay.py, tests/generic_config_updater/test_incremental_qos.py, tests/generic_config_updater/test_lo_interface.py, tests/generic_config_updater/test_portchannel_interface.py, tests/generic_config_updater/test_vlan_interface.py, tests/ipfwd/test_dip_sip.py, tests/ipfwd/test_dir_bcast.py, tests/lldp/test_lldp.py, tests/pfc/test_unknown_mac.py, tests/radv/test_radv_ipv6_ra.py, tests/route/test_static_route.py, tests/sflow/test_sflow.py, tests/snmp/test_snmp_fdb.py, tests/testbed_setup/test_populate_fdb.py, tests/vlan/test_host_vlan.py, tests/vlan/test_vlan.py, tests/vlan/test_vlan_ping.py
Summary:
Fix conflicts of merging [[m0] Mark test cases applicable to M0 #6291](https://github.com/sonic-net/sonic-mgmt/pull/6291) into branch 202012
=> [202012][m0] Mark test cases applicable to M0 #6291

docs/testbed/README.testbed.Setup.md
Summary:
Make some updates.  *This document should be maintained on an ongoing basis.
=> Update the links to download dockers

tests/snmp/test_snmp_memory.py
Default error percentage 4 is not enough on platform with small memory. Adjust it auomatically depending on total memory.
Summary:
Default error percentage 4 is not enough on platform with small memory. Adjust it auomatically depending on total memory.
Adjust it auomatically depending on total memory.
Run tests
=> [snmp] adjust percentage for snmp_memory test

ansible/group_vars/all/creds.yml, ansible/group_vars/vm_host/creds.yml, ansible/testbed_add_vm_topology.yml, ansible/testbed_remove_vm_topology.yml, ansible/testbed_renumber_vm_topology.yml, ansible/veos_vtb, docs/testbed/README.testbed.VsSetup.md
Summary:
Ansible playbooks use `ansible_user` and `ansible_password` to login to managed nodes. However, when ansible loads variables from multiple places (e.g. `group_vars/all`, `group_vars/vm_host`, `group_vars/{lab-name}`), it's hard for us to give `ansible_user` and `ansible_password` a correct value. So, I add `vm_host_username` and `vm_host_password`, they will be only used for login to vm hosts.
Ansible playbooks use `ansible_user` and `ansible_password` to login to managed nodes. However, when ansible loads variables from multiple places (e.g. `group_vars/all`, `group_vars/vm_host`, `group_vars/{lab-name}`), it's hard for us to give `ansible_user` and `ansible_password` a correct value. So, I add `vm_host_username` and `vm_host_password`, they will be only used for login to VM …
=> [ansible/testbed] Use `vm_host_*` variables to login to vm hosts

tests/common/dualtor/mux_simulator_control.py
Summary:
Fix the following three fixtures:
* toggle_all_simulator_ports_to_rand_selected_tor
* toggle_all_simulator_ports_to_rand_unselected_tor
* toggle_all_simulator_ports_to_rand_selected_tor_m
Those fixtures doesn't have decent time waiting for toggle finish.
This is because, without icmp_responder running, when linkmgrd enters
(unknown, active, up) states, it will suspend heartbeats, and the
suspension will be at most around 50 ~ 60 seconds, and linkmgrd only
reprobes the mux state after the suspension.
So this PR is to enlarge the time waiting for toggle sucess.
As above.
=> [dualtor] Fix random toggle fixtures

azure-pipelines.yml, tests/kvmtest.sh
1. Add following tests to multi-asic PR check
over the long weekend there are 61 runs in mgmt repo finished with the following tests, with sanity and loganalyzer too, 1 captured a valid error, 1 unvalid error seen in test_accounting_local_only that fail to open channel, which I would say within tolerance.
`    bgp/test_bgp_fact.py 
snmp/test_snmp_default_route.py 
snmp/test_snmp_loopback.py 
snmp/test_snmp_pfc_counters.py 
snmp/test_snmp_queue.py 
tacacs/test_accounting.py 
tacacs/test_authorization.py 
tacacs/test_jit_user.py 
tacacs/test_ro_user.py 
tacacs/test_rw_user.py`
3. enabling the mgmt PR check to mandatory: 
the existing PR check with sanity_check looks fine too, marking as mandatory
Summary:
=> [pr check] [masic] Add sanity check and tests, also mark multi-asic PR check as required

tests/qos/qos_helpers.py, tests/qos/test_pfc_counters.py
The script qos/test_pfc_counters.py needs to be updated to handle nexus as fanout switch.
=> Adding nexus support for test_pfc_counters.py

ansible/module_utils/port_utils.py
Summary:
Update `port_utils.py` to adapt `Arista-720DT-48S`.
Update `port_utils.py` to adapt `Arista-720DT-48S`.
Add the `alias` -> `name` mapping to `port_utils.py`.
Verified on physical testbeds.
=> [ansible/dut] Update `port_utils.py` to adapt `Arista-720DT-48S`

tests/scripts/getbuild.py
Summary:
Several failures were found during getbuild.py in TestbedV2 pull request test run.
Add some debug logs and retry function to fix and locate it.
Several failures were found during getbuild.py in TestbedV2 pull request test run.
Add some debug logs and retry function to fix and locate it.
Add some debug logs and retry function.
The pull request test will verify it.
=> Add debug logs and retry function in getbuild.py

ansible/roles/test/files/ptftests/py3/sflow_test.py
Summary:  After sFlow ptftests migrated to python3, executing time of a single sFlow ptftest increased from 50-80 seconds to 5000 seconds. As investigation showed, executing time of function that send pkt's increased significantly.
When executed using `python3 `it takes about ~11-18 seconds to send 512 pkt's:
```
12:45:01.563  root      : INFO    : Sending 512 pkts to Ethernet124  time_it_took_to_send 0:00:12.623860
12:45:12.655  root      : INFO    : Sending 512 pkts to Ethernet112  time_it_took_to_send 0:00:11.087558
12:45:28.359  root      : INFO    : Sending 512 pkts to Ethernet120  time_it_took_to_send 0:00:15.700587
12:45:41.719  root      : INFO    : Sending 512 pkts to Ethernet116  time_it_took_to_send …
```
=> [sFlow] Fix sFlow TC and improve execution time

tests/acl/test_acl.py, tests/dhcp_relay/test_dhcp_relay.py, tests/dhcp_relay/test_dhcpv6_relay.py
Summary:
Manually cherry pick this PR: https://github.com/sonic-net/sonic-mgmt/pull/6344
=> [202012][m0] Fix acl/dhcp_relay test cases (#6344)

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:  fix the order of the yaml file "tests_mark_conditions.yaml"
keep the test cases in alphabetical order in "tests/common/plugins/conditional_mark/tests_mark_conditions.yaml"
sort test cases in alphabetical order
=> sort tests_mark_conditions.yaml

ansible/roles/test/files/ptftests/dir_bcast_test.py, tests/copp/test_copp.py, tests/crm/test_crm.py, tests/fdb/test_fdb_mac_expire.py, tests/ipfwd/test_dip_sip.py, tests/ipfwd/test_dir_bcast.py
Summary:
Some test cases skip m0 topo due to hard code.
Related test cases:
* test_copp
* test_crm
* test_fdb_mac_expire
* test_dip_sip
* test_dir_bcast
Add support for m0 in some test cases.
Run test cases.
=> [202012][m0] Add support for M0 topo in some test cases

docs/testbed/README.testbed.VsSetup.md
Summary:
There are errors in deploying the t0 topology following the [KVM testbed setup](https://github.com/sonic-net/sonic-mgmt/blob/6323090c6d73d7f2324ca8e04427c28ce401e208/docs/testbed/README.testbed.VsSetup.md) which can be resolved by the recommended changes.
There are errors in deploying the t0 topology following the [KVM testbed setup](https://github.com/sonic-net/sonic-mgmt/blob/6323090c6d73d7f2324ca8e04427c28ce401e208/docs/testbed/README.testbed.VsSetup.md) which needs to be addressed. 
The given modifications has to be addressed for the successful deployment of t0 topology without any error. 
- In order to start the necessary number of VMS for t0 topology or to avoid the crashing of the VMs midway, there should be at least **20GB** of memory free as each VM takes more than 3GB …
=> [doc]: Update README.testbed.VsSetup.md

tests/arp/test_unknown_mac.py
Summary:
Remove m0 mark on test_unknown_mac
=> [m0] Remove m0 mark on test_unknown_mac

tests/container_checker/test_container_checker.py, tests/copp/test_copp.py, tests/iface_namingmode/test_iface_namingmode.py
…ingmode/test_copp
Summary:
Some test cases skip m0 topo due to hard code.
Related test cases:
* test_container_checker
* test_copp
* test_iface_namingmode
Add support for m0 in some test cases.
Run test cases.
=> [m0] Add support for m0 topo in some test cases

tests/dualtor_io/test_tor_bgp_failure.py
Summary:
Correct the expected standby health to `unhealthy`.
=> [dualtor][active-active] Fix `test_tor_bgp_failure`

tests/platform_tests/daemon/test_syseepromd.py
Summary:
Improve logging to show more
Run tests
=> [syseeprom] improve logging to show more in syseeprom

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Add skip conditions for m0 in custom mark file
Run test cases.
=> [m0] Add skip conditions for m0

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/6383
=> [202012][m0] Add skip conditions for m0 (#6383)

ansible/library/announce_routes.py, ansible/vars/topo_m0.yml, tests/acl/test_acl.py, tests/arp/test_unknown_mac.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml, tests/container_checker/test_container_checker.py, tests/copp/test_copp.py, tests/iface_namingmode/test_iface_namingmode.py
Summary:
Manually cherry pick these PRs:
https://github.com/sonic-net/sonic-mgmt/pull/6362
https://github.com/sonic-net/sonic-mgmt/pull/6365
https://github.com/sonic-net/sonic-mgmt/pull/6371
https://github.com/sonic-net/sonic-mgmt/pull/6383
=> [202205][m0] Manually cherry pick m0 related PR

.github/PULL_REQUEST_TEMPLATE.md
Summary:
After the 202205 branch was created, some critical changes may need to backport to 202012 branch.
This change updated the Github Pull Request template to support marking 202205 branch backport.
=> Update PR template to support marking 202205 branch backport

tests/platform_tests/api/test_thermal.py
Get minimum and maximum temperature from platform.JSON and use that in checking against valid minimum and maximum recorded temperatures in test_thermal.py
When checking the minimum and maximum recorded temperature, the validation is hard-coded to use 100 in test_thermal.py.  Max temperature value above 100 would cause the test case to fail.
However, on some boxes, temperatures above 100 are still considered OK - like Nokia's linecards.
Added code to get the min and max temperature from platform.json, and use that instead of the hard-coded 100. These values can be defined in the platform.json as:
```
{
"chassis": {
....
"thermal_temperature": {
"minimum": 0,
"maximum": 110
},
....
```
To get the test to pass:
- Added a get_thermal_temperature definition to get the min and max values from …
=> Chassis: Get minimum and maximum temperature from platform.json

spytest/Doc/install.md
Summary:
Fixes # (This PR fixes link to `README.testbed.Setup.md` in `spytest/Doc/install.md`)
just want the documentation up to date
find the file by the 'find' command and replace obsolete URL
It was checked manually that the new link is not broken and it is redirected to correct file.
=> [doc] fix link to README.testbed.Setup.md in spytest/Doc/install.md

ansible/module_utils/port_utils.py
Summary:
According to [SONiC port naming convention change](https://github.com/sonic-net/SONiC/blob/master/doc/sonic-port-name.md), update the port alias to `etp1`\~`etp52` for Arista-720DT.
According to [SONiC port naming convention change](https://github.com/sonic-net/SONiC/blob/master/doc/sonic-port-name.md), update the port alias to `etp1`\~`etp52` for Arista-720DT.
Update the port alias mapping in `port_utils.py`.
Verified on physical testbeds.
=> [ansible/dut] Update Arista-720DT port alias mapping

tests/sai_qualify/cases_brcm_t0.py
Summary:
Add 10 new ecmp cases to case list.
Manually run internal pipeline and all cases passed.
=> [SAI Qualify] Add 10 ecmp cases

tests/tacacs/test_accounting.py
Summary: fixed TACACS Local Accounting tests
TACACS Local Accounting tests check if the commands executed by TACACS users are logged locally in DUT.
The tests execute a `grep` command using a TACACS user and then check presence of the corresponding accounting log in syslog using `sed` utility. The code fragment demonstrating it:
```
ssh_run_command(rw_user_client, "grep")
check_local_log_exist(rw_user_client, tacacs_creds, "grep")
```
The issue is that `check_local_log_exist` calls `sed` to query for accounting logs and this query command itself is logged too so tests pass even when the initial command is not logged.
Currently the test catches this log:
```
INFO audisp-tacplus: Audisp-tacplus: Accounting: user: test_rwuser, tty: (none), host: mytestbed-1-dut, command: …
```
=> fixed TACACS Local Accounting tests

tests/acl/test_acl.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Add skip due to Egress ACLs are not applicable to M0 topo
Check if it is needed to skip in stage function
=> [M0] Skip acl egress on m0 topo

setup-container.sh
Summary:
Running the `setup-container.sh` script to setup sonic-mgmt container needs to install some packages on the fly using `pip`. We need to ensure that the pip package itself is up to date to avoid potential dependency issue while installing other packages using `pip install`.
This change added extra step to upgrade the pip package firstly before installing other packages using `pip install`.
Locally run `setup-container.sh`.
=> [setup-container.sh] Fix 'pip install' dependency issue

tests/platform_tests/daemon/test_chassisd.py
test_chassisd.py tests fails intermittently due to early exit of _collect_data function before the db is populated completely
Added code to avoid early exit of _collect_data function
return false until the number of db device keys after restarting chassisd process matches the number of db keys before restart
Summary:
test_chassisd.py tests fails intermittently due to early exit of _collect_data function before the db is populated completely
Added code to avoid early exit of _collect_data function
Verified on cisco-8000 platform with T2 profile
=> fix to validate all db device keys are populated after chassid restart

ansible/library/port_alias.py, tests/common/testbed.py
Summary:
Some new devices use a different platform key string in their `machine.conf` file
=> [ansible]: Update port_alias module for bf devices

tests/qos/files/qos.yml
Summary:
To add QoS test params for J2C+ HWSKUs
Updated qos params in qos.yml file.
Verification still in progress on real HWSKUs. These are starting values.
=> QoS test params for J2C+ based HWSKUs

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
test_syslog_source_ip failed since day one, skip for now. 
raised issue https://github.com/sonic-net/sonic-mgmt/issues/6479 to track
=> [test skip] skip test_syslog_source_ip

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
`test_fwutil` was introduced into nightly test in https://github.com/sonic-net/sonic-mgmt/pull/6231, but all failed due to not found fixture.
File an issue #6489 and skip it for now.
Add skip section in platform test mark condition yml file.
```
platform_tests/fwutil/test_fwutil.py::test_fwutil_update_bad_config
SKIPPED                                                                                                          [ 10%]
platform_tests/fwutil/test_fwutil.py::test_fwutil_install_file[str-dx010-acs-4] SKIPPED                                                                                 [ 20%]
platform_tests/fwutil/test_fwutil.py::test_fwutil_install_url[str-dx010-acs-4] SKIPPED …
```
=> Skip test_fwutil due to not found fixture

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip generic_config_updater/test_bgp_speaker for M0 topo
=> [m0] Skip generic_config_updater/test_bgp_speaker for M0 topo

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Manually cherry pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/6497
=> [202205][m0] Skip generic_config_updater/test_bgp_speaker for M0 topo #6497

.azure-pipelines/pre-commit-check.yml, .pre-commit-config.yaml, azure-pipelines.yml
Summary:
The pre-commit framework is an easy to use and powerful framework that can
be used in git hooks.
This PR enables the pre-commit code check to ensure better code quality.
* Added pre-commit configuration
* Updated the azure pipeline yaml to run pre-commit check.
=> Enable pre-commit code check

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
`pc/test_po_cleanup.py/test_po_cleanup`  and `pc/test_po_cleanup.py/test_po_update_io_no_loss` failed at loganalyzer, it's a known issue, Broadcom is fixing it but not sure when it's finished.
Ignore these 3 ERR logs for now, will remove it after the issue is fixed.
```
E               Oct 12 22:04:42.047504 str-dx010-acs-1 ERR syncd#syncd: [none] SAI_API_ACL:_brcm_sai_acl_table_group_bind_point_detach:8792 Unused acl table group.
E               Oct 12 22:04:42.047892 str-dx010-acs-1 ERR syncd#syncd: [none] SAI_API_ACL:_brcm_sai_acl_obj_unbind:9780 acl table group bind point detach failed with error -5.
E               Oct 12 22:04:42.048205 …
```
=> Ignore Broadcom sai acl unbind ERR log for now

tests/snmp/test_snmp_memory.py
test_snmp_swap referenced variables that were removed in other commits.
Summary:
Test_snmp_swap referenced variable that was removed in other commits.
Run tests.
=> [snmp] fix bug with test_snmp_swap

ansible/library/snmp_facts.py, tests/common/helpers/snmp_helpers.py, tests/snmp/test_snmp_memory.py
2 swap related tests were not back ported to 202012 from master. Did it manually.
Master had bug fix related to these commits, and the fix has been included as well.
Summary:
2 commits were left out of master, and a relevant fix is also included.
Cherry-picked from master
Run tests.
=> [202012] enable swap related functions and tests for snmp

ansible/plugins/callback/yaml.py, tests/common/cache/facts_cache.py, tests/run_tests.sh
Summary:
Fixes run_test.sh script to support Python3 venv
Python3 migration
Add if statement to differentiate Python2 and Python3 in run_test.sh
Python2 testcases can run successfully.
N/A
N/A
N/A
=> Python3 migration: Modify run_test.sh to support Python3 venv

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
ecmp test_fgnhg.py test case failed recently, create an issue and xfail the case at this moment.
Summary:
=> xfail ecmp test_fgnhg.py

tests/route/test_static_route.py
Test case miss dual-tor consideration, static route only configed on ut0, after reload ut0 became standby, ds traffic will reach lt0.
But missing static route config lead traffic goes to default port (output interface is port channel member interface), which is not expect result.
Dual-tor only
Summary:
Script issue fix
Add missing case for dual-tor
Run script on dual-tor, result pass
=> add fix for test static route script issue on dual-tor

tests/pc/test_lag_member.py
Summary:  Test `test_lag_member` fails when port members are added to newly created PortChannel1 with below error:
```
E           RunAnsibleModuleFail: run module shell failed, Ansible Results =>
E           {
E               "changed": true, 
E               "cmd": "config portchannel member add PortChannel1 Ethernet184", 
E               "delta": "0:00:00.608702", 
E               "end": "2022-09-18 04:54:14.547431", 
E               "failed": true, 
E               "invocation": {
E                   "module_args": {
E                       "_raw_params": "config portchannel member add PortChannel1 Ethernet184", 
E                       "_uses_shell": true, 
E                       "argv": null, 
E …
```
=> Fix test_lag_member TC

tests/common/plugins/conditional_mark/tests_mark_conditions_202205.yaml
Summary:
add test_dhcpv6_relay_counter to xfail
=> [xfail] add test_dhcpv6_relay_counter to xfail

tests/scripts/getbuild.py
Summary:
Update getbuild.py to match the master branch
Update getbuild.py to match the master branch
Update getbuild.py to match the master branch
=> Update getbuild.py to match the master branch

tests/common/plugins/conditional_mark/tests_mark_conditions_202012.yaml
Summary:
In order to surface new regression on 202012 branch quickly, put all known issues to the xfail list and track them by github issues. 
In order to surface new regression on 202012 branch quickly, put all known issues to the xfail list and track them by github issues.
=> Add xfail list specific for 202012 branch

tests/common/plugins/conditional_mark/tests_mark_conditions_202012.yaml
Summary:
Missed colon for xfail list.
skip test_advanced_reboot for both dual and single tor 
Missed colon for xfail list.
skip test_advanced_reboot for both dual and single tor.
=> xfail list for 202012

.azure-pipelines/test_plan.py
Summary:
The test_plan script supports to pass mgmt_branch, to support buildimage repo run test bases on different sonic-mgmt branch.
The test_plan script supports to pass mgmt_branch, to support buildimage repo run test bases on different sonic-mgmt branch.
The test_plan script supports to pass mgmt_branch, to support buildimage repo run test bases on different sonic-mgmt branch.
=> [TestbedV2] test_plan script supports to pass mgmt_branch

tests/ecmp/inner_hashing/conftest.py, tests/ecmp/inner_hashing/test_inner_hashing.py, tests/ecmp/inner_hashing/test_inner_hashing_lag.py, tests/ecmp/inner_hashing/test_wr_inner_hashing.py, tests/ecmp/inner_hashing/test_wr_inner_hashing_lag.py
Summary:
In order to test the hash performance, the test will send out big quantity pkts, which is time killer, for test_inner_hashing.py, single module will take more than 100 mins, and there are 4 different testcases related to this same function, it will take more than 5 hours, which is too much for nightly run.
By adding the completeness level, to reduce the pkt quantity for lower completeness level, which can save 4 hours for normal run and keep the capability to run full pkts when specified "thorough" mode.
In order to test the hash performance, the test will send out big quantity pkts, which is time killer, for test_inner_hashing.py, single module will take more than 100 mins, and there are 4 different testcases related to this same function, it will take more than …
=> Time reduction for inner hash test

ansible/testbed-cli.sh
Summary:
This PR replaces PR https://github.com/sonic-net/sonic-mgmt/pull/5674
Enhance testbed-cli.sh script to support caching deployed topologies.
This is to reduce time when a developer wants to deploy a certain topology on a testbed, so only cached topology will be removed instead of all known topologies.
Add a caching mechanism, each time a user ask to add a topology using the testbed-cli script, it will be cached.
Once the user will ask to deploy a different topology using testbed-cli script, only the cached topology will be removed and the new topology will be configured.
The cached topologies will be saved on a shared location known to all sonic-mgmt dockers and servers.
The path of the shared location should be provided as a separate file named "cached_topologies_path" under the …
=> Enhance testbed-cli.sh script to support caching of deployed topologies

tests/route/test_route_flap.py
Summary:
Fixes [# (6575)](https://github.com/sonic-net/sonic-mgmt/issues/6575)
test_route_flap failed in M0 topo due to prefix length of routes announced is different from other topos.
Add support for m0.
Run test case.
=> [m0] Add support for m0 in test_route_flap

ansible/roles/vm_set/templates/cleanup.sh.j2
Summary:
There have been some efforts to fix the test server stuck issue. However, the test server cleanup scenario was missed. When we run testbed-cli.sh cleanup-vmhost, the cleanup.sh script will be eventually called. This script has steps to remove the PTF containers without stopping the exabgp service in them in advance. This also could result in test server stuck.
The previous efforts trying to work around this issue:
https://github.com/sonic-net/sonic-mgmt/pull/6131
https://github.com/sonic-net/sonic-mgmt/pull/6191
https://github.com/sonic-net/sonic-mgmt/pull/6241
1. Stop exabgp services before stopping all running docker containers in cleanup.sh.j2 file.
2. Get all ptf containers in current server, and use docker exec to get all exabgp services of ptf containers, …
=> Stop exabgp before stopping and removing PTF container in cleanup

ansible/library/extract_log.py, ansible/roles/test/files/tools/loganalyzer/loganalyzer.py
Reverts sonic-net/sonic-mgmt#6577
It blocks smoke test since the image fix https://github.com/sonic-net/sonic-buildimage/pull/12425 is not in internal branch.
=> Revert "Revert "Fix loganalyzer.py UnicodeDecodeError issue""

ansible/group_vars/all/creds.yml, ansible/group_vars/vm_host/main.yml, ansible/module_utils/serial_utils.py, ansible/roles/cisco/tasks/main.yml, ansible/roles/cisco/tasks/vcisco.yml, ansible/roles/cisco/templates/wan-pub-leaf.j2, ansible/roles/vm_set/library/cisco_kickstart.py, ansible/roles/vm_set/tasks/kickstart_vm.yml, ansible/roles/vm_set/tasks/main.yml, ansible/roles/vm_set/tasks/respin_cisco_vm.yml, ansible/roles/vm_set/tasks/start.yml, ansible/roles/vm_set/tasks/start_vm.yml, ansible/roles/vm_set/tasks/stop_vm.yml, ansible/roles/vm_set/templates/cisco.xml.j2, ansible/testbed-cli.sh, ansible/testbed_add_vm_topology.yml, ansible/vars/azure_storage.yml
The wan-pub topo needs to support multi-vendor neighbors for inter-ops tests, so to make cisco VM as the testbed servers is useful for wan topology. This PR introduces cisco VM in testbed servers for wan topology.
Summary:
Add cisco VM in testbed server for wan topology.
Add a role for cisco VM and modify some playbooks related to VM start, stop and configuration deployment.
Follow below steps:
1. Skip download cisco VM step and put a cisco VM image in `{{ root_path }}/images/`
2. Set parameter `-k vcisco` and use command `./testbed-cli.sh -m veos_vtb -k vcisco -t vtestbed.yaml start-topo-vms vms-kvm-wan-pub password.txt` to start cisco VM.
3. Set parameter `-k vcisco` and use command `../testbed-cli.sh -t vtestbed.yaml -m veos_vtb -k vcisco add-topo vms-kvm-wan-pub …
=> [VM]: Support cisco VM on the server for wan topology

.azure-pipelines/pr_test_scripts.yaml
Summary:
Add pr test scripts to branch 202012.
Add pr test scripts to branch 202012.
Add pr test scripts to branch 202012.
=> [202012]Add pr test scripts

tests/scripts/sai_qualify/DUTScript/README.md, tests/scripts/sai_qualify/DUTScript/Utils.sh, tests/scripts/sai_qualify/DUTScript/all_container.sh, tests/scripts/sai_qualify/DUTScript/all_listener.sh, tests/scripts/sai_qualify/DUTScript/all_service.sh, tests/scripts/sai_qualify/DUTScript/prepare_saiserver_service.sh, tests/scripts/sai_qualify/DUTScript/pull_saiserver_syncd_rpc_dockers.sh, tests/scripts/sai_qualify/DUTScript/restore_saiserver.sh, tests/scripts/sai_qualify/DUTScript/restore_syncd.rpc.sh, tests/scripts/sai_qualify/DUTScript/sai_warm_profile.sh, tests/scripts/sai_qualify/DUTScript/start_syncd_rpc.sh, tests/scripts/sai_qualify/DUTScript/syncd_rpc_debug_container.sh, tests/scripts/sai_qualify/DUTScript/syncd_rpc_shell/init_env.sh, tests/scripts/sai_qualify/DUTScript/tests/mlnx-saiserver-files/usr/bin/saiserver.sh, tests/scripts/sai_qualify/DUTScript/tests/mlnx-saiserver-files/usr/lib/systemd/system/saiserver.service, tests/scripts/sai_qualify/DUTScript/tests/mlnx-saiserver-files/usr/local/bin/saiserver.sh, tests/scripts/sai_qualify/DUTScript/tests/mlnx-saiserver-files/usr/local/bin/saiserver_common.sh, tests/scripts/sai_qualify/DUTScript/tests/mlnx-syncd-files/usr/bin/syncd.sh, tests/scripts/sai_qualify/DUTScript/tests/mlnx-syncd-files/usr/lib/systemd/system/syncd.service, tests/scripts/sai_qualify/DUTScript/tests/mlnx-syncd-files/usr/local/bin/syncd.sh, tests/scripts/sai_qualify/DUTScript/tests/mlnx-syncd-files/usr/local/bin/syncd_common.sh
Summary:
Add script which will be deployed to DUT when setup the sai test environment, those script will be used for debugging as well.
Add script which will be deployed to DUT when setup the sai test environment, those script will be used for debugging as well.
Verified those script on DUT
=> [SAI-Qualify] Add shell script for setup DUT for sai test and debugging

tests/sai_qualify/conftest.py, tests/sai_qualify/sai_infra.py, tests/sai_qualify/setup_test_env.py, tests/sai_qualify/test_brcm_t0.py, tests/sai_qualify/test_community.py, tests/sai_qualify/test_sai_ptf.py, tests/sai_qualify/test_warm_reboot.py
Summary:
Add script for preparing the SAI test env and seperate it from the test process, then we can use script to make operate modification after setup the environment.
Add script for preparing the SAI test env and seperate it from the test process, then we can use script to make operate modification after setup the environment.
Add script for preparing the SAI test env and seperate it from the test process, then we can use script to make operate modification after setup the environment.
Test Done:
Pipeline test and local test
=> [SAI Qualify] Add script to prepare the env

tests/common/plugins/conditional_mark/tests_mark_conditions_202205.yaml
Summary:
Create issues for 202205 xfail cases and assign.
Create issues for 202205 xfail cases.
Add issue info into the conditional mark file in the 202205 branch.
=> Create issues for 202205 xfail cases.

SECURITY.md, tests/test_features.py, tests/test_interfaces.py, tests/test_nbr_health.py, tests/test_posttest.py, tests/test_pretest.py, tests/test_procdockerstatsd.py, tests/test_vs_chassis_setup.py
Summary:
This change fixes the style issues of test scripts directly under the tests folder.
=> [pre-commit] Fix style issues in test scripts directly under `tests` folder

tests/conftest.py
Summary:
This change fixes the style issues in `tests/conftest.py`.
What's more, built-in function `reduce` is used in `tests/conftest.py`. This built-in function is no longer supported in python3. This change updated the code using `reduce` to use `sum` instead.
=> [pre-commit] Fix style issues in `tests/conftest.py`

tests/common/sai_adhoc.py, tests/sai_qualify/conftest.py
Summary:
Fix the issue for error message in sai_adhoc
Enable deployment parameter
Test Done:
Local test
Pipeline test
=> [SAI_Qualify] Fix issue in sai_adhoc script and enable deployment parameter

test_reporting/report_data_storage.py, test_reporting/requirements.txt, test_reporting/sai_swss_invocations.py, test_reporting/sairedis log scanner.md, test_reporting/swss.yml
1. collect sairedis logs from different types of machines
2. analyze the logs, extract the key and value organized by json
3. ingest json file to the kusto table SwssInvocationReport
Summary:
=> [SAI-Qualify]scan Swss log and upload to kusto

tests/common/plugins/conditional_mark/tests_mark_conditions_202205.yaml
Summary:
202205 conditional marks are not sorted.
Sorted the conditional marks by alphabetic order.
Enabled the pre-commit check for this commit.
=> [202205][conditional_marks] sort the conditions by alphabetic order

.azure-pipelines/run-test-scheduler-template.yml, .azure-pipelines/test_plan.py, azure-pipelines.yml
Migrate dualtor test to TestbedV2
Summary:
Migrate dualtor test to TestbedV2
Migrate dualtor test to TestbedV2
The pr test pipeline itself tests it
=> [TestbedV2] Migrate dualtor test to TestbedV2

tests/ptf_runner.py
Summary:
Improve the ptf log collection to attach ptf logs to allure report, which bring some convenience when debugging ptf test failures. 
Improve the ptf log collection to attach ptf logs to allure report, which bring some convenience when debugging ptf test failures. 
In the tests/ptf_runner.py
1. Attach the ptf log and pcap files to allure report in ptf_runner.py
2. Attach the result of ptf command to the allure report when ptf test passed
3. Attach traceback message to allure report when ptf test failed
4. Fix a bug in the log/pcap file name, the old name was like: 'wr_arp.ArpTest.log.2022-09-26 20:07:29.992511.log', remove the '.log' in the middle and replace the space between the date and time by '.'.
Verified in automated regression
=> Improve the ptf log collection to attach ptf logs to allure report

tests/common/plugins/conditional_mark/tests_mark_conditions_202205.yaml
Summary:
xfail test_no_pfc
xfail test_no_pfc
=> [202205][dualtor] test_no_pfc xfail for 202205 branch

ansible/roles/test/files/acstests/IP_decap_test.py, ansible/roles/test/files/acstests/acl_port_range_traffic_test.py, ansible/roles/test/files/acstests/acl_tcp_test.py, ansible/roles/test/files/acstests/acltb_test.py, ansible/roles/test/files/acstests/acs_base_test.py, ansible/roles/test/files/acstests/dscp_ecn_send.py, ansible/roles/test/files/acstests/dscp_mapping.py, ansible/roles/test/files/acstests/everflow_policer_test.py, ansible/roles/test/files/acstests/everflow_tb_test.py, ansible/roles/test/files/acstests/lag_test.py, ansible/roles/test/files/acstests/router_utils.py
Summary:
This change fixes the style issues of test scripts under the `ansible/roles/test/files/acstests` folder
=> [pre-commit] Fix style issues in test scripts under `ansible/roles/test/files/acstests` folder

tests/autorestart/test_container_autorestart.py
Summary:
This change fixes the style issues of test scripts under the `tests/autorestart` folder
=> [pre-commit] Fix style issues in test scripts under `tests/autorestart` folder

tests/bfd/test_bfd.py
Summary:
This change fixes the style issues of test scripts under the `tests/bfd` folder
=> [pre-commit] Fix style issues in test scripts under `tests/bfd` folder

tests/arp/arp_utils.py, tests/arp/conftest.py, tests/arp/test_arp_dualtor.py, tests/arp/test_arp_extended.py, tests/arp/test_arpall.py, tests/arp/test_neighbor_mac.py, tests/arp/test_neighbor_mac_noptf.py, tests/arp/test_stress_arp.py, tests/arp/test_tagged_arp.py, tests/arp/test_unknown_mac.py, tests/arp/test_wr_arp.py
Summary:
This change fixes the style issues of test scripts under the `tests/arp` folder
=> [pre-commit] Fix style issues in test scripts under `tests/arp` folder

tests/dhcp_relay/test_dhcp_pkt_fwd.py
Summary:
Add support for m0 in test_dhcp_pkt_fwd
Run test
=> [m0] Add support for m0 in test_dhcp_pkt_fwd

ansible/library/lldp_facts.py, ansible/roles/cisco/templates/wan-pub-core.j2, ansible/vars/topo_wan-pub-cisco.yml, ansible/veos_vtb, ansible/vtestbed.yaml, tests/wan/lldp/test_lldp.py, tests/wan/lldp/test_wan_lldp.py
Add one new topo to support cisco kvm as neighbor and LLDP testcases to fit this topo 
Summary:
1. add new topo to support cisco kvm as neighbor
2. add LLDP testcases to run based on this topo
1. to support cisco kvm as dut neighbor
2. to make LLDP testcases run smoothly based on cisco kvm neighbor
1. add new topo to support cisco neighbor
1. verify existing LLDP testcases based no new topo
2. verify new LLDP testcases based on new topo
N/A
N/A
=> add new topo and lldp testcases fit it

tests/qos/files/qos.yml, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py
Rebased from https://github.com/sonic-net/sonic-mgmt/pull/6106
Adding new testcase testQosSaiLosslessVoq specific to cisco platform .
This testcase verifies QoS SAI XOFF limits for various voq mode configurations .
Verify Qos SAI XOFF limits for various voq mode configurations .
Verified the testcase on local cisco-8000 setup and it passes .
=> Test lossless queue for cisco-8000 platform

test_reporting/kusto/sai_report_setup.kql, test_reporting/report_data_storage.py, test_reporting/report_uploader.py, test_reporting/sai_coverage/case_scanner.py, test_reporting/sai_coverage/constant.py, test_reporting/sai_coverage/data_model/sai_interface_header.py, test_reporting/sai_coverage/data_model/test_invocation.py, test_reporting/sai_coverage/sai_adapter_scanner.py, test_reporting/sai_coverage/sai_header_scanner.py, test_reporting/sai_coverage/sai_report_utils.py, test_reporting/sai_coverage_scan_and_upload.sh, test_reporting/sai_coverage_scanner.md
Signed-off-by: zhiyuanliang-ms <t-zhliang@microsoft.com>
1. Scan SAI header files
2. Scan SAI API definitions
3. Parse and filter, generating report
4. Ingest json files to the kusto table CaseInvocationReportV2
Summary:
=> [SAI-PTF] Scan SAI interface and upload to Kusto

tests/macsec/test_macsec.py
Signed-off-by: Ze Gan <ganze718@gmail.com>
The rekey test checks the packet loss during two rekey rotations. But this time is 480s(8 mins) which is too long to ansible connection.
Hup the ping process to background with `nohup` command and redirect the output to a temp file.
Check Azp
=> [test_macsec]: Fixbug rekey test timeout issue

ansible/roles/eos/templates/wan-2dut-core.j2, ansible/testbed-cli.sh, ansible/vars/topo_wan-2dut.yml, ansible/veos_vtb, ansible/vtestbed.yaml
Add a new topo wan-2dut for wan multi-dut test
Summary:
1. Add a new topo (wan-2dut) for wan multi-dut test
2. Check `vm_type`, if it is vcisco, set `-e eos_batch_size=1` in `ansible_options` for [iosxr_config configuration upload issue](https://github.com/ansible-collections/cisco.iosxr/issues/67)
1. Follow topo definition procedure to add wan-2dut topo for ceos and vcisco VM.
2. In `testbed-cli.sh`, when there is a need to upload configuration to cisco VM, add `-e eos_batch_size=1` to `ansible_options`
1. Using command `./testbed-cli.sh -t vtestbed.yaml -m veos_vtb -k vcisco/ceos add-topo vms-kvm-wan-2dut password.txt` and check duts and VMs would startup.
2. Using command `./testbed-cli.sh -t vtestbed.yaml -m veos_vtb deploy-mg vms-kvm-wan-2dut veos_vtb password.txt` …
=> [VM]: add new topo wan-2dut for wan multi-dut topo

tests/common/fixtures/advanced_reboot.py
Summary:
The existing logic prints all data from logs in any case. in this fix, only a summary of downtime will be printed in case of success, and in case of failure, all data from log will be printed for debug purpose.
In the current situation, a relevant information for debug wasn't printed in the log in case of failure, only the specific fail reason.
In addition, in case the test passes, there were no stats about the data & control plane downtime during the reboot.
These stats are important to measure the performance of the reboot process and to detects degradations in downtime.
My fix prints important debug info from the reboot log in case of failure, and a summary of downtime in case of success.
By that, only relevant information will appear in log, and will make the log much more …
=> Added a new logic for reboot logs print.

test_reporting/kusto/sai_report_setup.kql, test_reporting/sai_coverage/case_scanner.py, test_reporting/sai_coverage/data_model/test_invocation.py, test_reporting/sai_coverage_scanner.md
Signed-off-by: zhiyuanliang-ms <t-zhliang@microsoft.com>
1. Fix a logical bug by adding `upload_time` attribute in python script
Summary:
Fix the logical bug of recording upload time
Add `upload_time` attribute in python script
=> [SAI-PTF] Scan SAI interface and upload to Kusto (add upload_time)

docs/testbed/README.testbed.WANSetup.md
Change description about cisco neighbor topo.
Summary:
It is doc pr, modify description about cisco neighbor topo.
Modify description about cisco neighbor topo
Modify document
N/A
N/A
N/A
=> add description about cisco kvm neighbor

.azure-pipelines/pr_test_scripts.yaml
Split t0-sonic test cases.
Summary:
Split t0-sonic test cases
Split t0-sonic test cases
=> [202205][TestbedV2] Split t0-sonic test cases

tests/sai_qualify/conftest.py
Signed-off-by: richardyu-ms <richard.yu@microsoft.com>
Summary:
Skip sai env deployment base on condition
Skip sai env deployment base on condition
Skip sai env deployment base on condition
Test done:
Local container
=> [SAI_Qualify]Skip sai env deployment base on condition

ansible/testbed-cli.sh
Summary:
Add an option to testbed-cli script to install an image to all DUTs in a testbed from a given image URL.
=> [testbed-cli]: Add option to install image

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
xfail platform_tests PSU related failure cases
some cases consistently failed on Celestica platform
xfail these cases and waiting for fix
verified it on Celestica platform
=> [XFAIL] xfail PSU related failure cases

tests/common/multibranch/cli/auto_techsupport.py
Summary:
show auto-techsupport-feature output change. 
Enhance the search pattern to search the output.
show auto-techsupport-feature output change. 
There would be an int or a float value in AVAILABLE MEM THRESHOLD item. 
Need to enhance the search pattern.
Enhance the search pattern.
Run cases and pass.
=> enhance show_auto_techsupport_feature output search pattern

.azure-pipelines/pr_test_scripts.yaml
Add dualtor test case for 202012 pr test. 
Summary:
Add dualtor test case for 202012 pr test. 
Add dualtor test case for pr test in `.azure-pipelines/pr_test_scripts.yaml`.
=> Add dualtor testcase for 202012. 

tests/platform_tests/cli/test_show_platform.py
Fix the test_show_platform_fan test case statistically failure and fix the pep8 failure at the same time
Fan having temporary status “NOT OK” is not a bug. It could happen in following case:
1.	Thermalctld/kernel changes the target speed. Hardware needs time to adjust the fan speed to target speed.
2.	Another thread of thermalctld reads the target speed and actual speed immediately. At this time point, there is a gap between fan target speed and actual speed which would cause “high speed warning” and fan status “NOT OK”.
Add retry in the test case to make the test case stable
Summary: Fix the test_show_platform_fan test case statistically failure
Fix the test_show_platform_fan test case statistically failure
Add retry when validate the fan status
Run the …
=> Fix the test_show_platform_fan test case statistically failure

tests/autorestart/test_container_autorestart.py
Update regular expression of ignore error logs  in test_container_autorestart
Update regular expression of ignore error logs  in test_container_autorestart
=> Update regular expression of ignore error logs  in test_container_autorestart

tests/common/devices/sonic.py
Summary:
Add remove vlan function in sonic.py
=> Add remove vlan function in sonic.py

tests/common/devices/aos.py, tests/common/devices/base.py, tests/common/devices/duthosts.py, tests/common/devices/eos.py, tests/common/devices/fanout.py, tests/common/devices/ixia.py, tests/common/devices/k8s.py, tests/common/devices/multi_asic.py, tests/common/devices/onyx.py, tests/common/devices/ptf.py, tests/common/devices/sonic.py, tests/common/devices/sonic_asic.py
Summary:
This change fixes the style issues of test scripts under `tests/common/device` folder
=> [pre-commit] Fix style issues in test scripts under `tests/common/device` folder

ansible/vtestbed.csv
PR [https://github.com/sonic-net/sonic-mgmt/pull/6418] added the simple wan topo in `vtestbed.yaml`. In this pr, I add this topo in `vtestbed.csv` **temporarily** to support TestbedV2 scheduler. After TestbedV2 scheduler convert from `vtestbed.csv` into `vtestbed.yaml`, we will no longer use `vtestbed.csv`. 
Summary:
PR [https://github.com/sonic-net/sonic-mgmt/pull/6418] added the simple wan topo in `vtestbed.yaml`. In this pr, I add this topo in `vtestbed.csv` **temporarily** to support TestbedV2 scheduler. After TestbedV2 scheduler convert from `vtestbed.csv` into `vtestbed.yaml`, we will no longer use `vtestbed.csv`. 
Add wan topo in `vtestbed.csv` **temporarily**.
=> [TestbedV2] Add simple wan topo support .

tests/kvmtest.sh
Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>
Summary:
Add pretest check in multi-asic pr checker
Remove disable_loganalyzer in multi-asic vs official azp
=> [multi-asic][vs]: Add pretest check in multi-asic pr checker

test_reporting/report_uploader.py
Summary:
Since image_url is changed, we have to update parse function accordingly.
master or internal key words could be in image url
Run nightly test.
=> update parse function for image url

azure-pipelines.yml
Add wan topo test using TestbedV2.
Summary:
Add wan topo test using TestbedV2.
Add a job to run wan topo in pr test.
=> [TestbedV2] Add wan topo test using TestbedV2.

tests/disk/test_disk_exhaustion.py
After exhausting disk space with `fallocate` command, we try to test SSH connect and IP packet forward, but if any exception is raised among that, this module would fail, and post steps outside this TC would be executed. But without releasing the disk space, it would cause other errors like `AnsibleConnectionFailure: Host unreachable`. So add the final block to wait the space to be released in order to not impact post steps.
After exhausting disk space with `fallocate` command, we try to test SSH connect and IP packet forward, but if any exception is raised among that, this module would fail, and post steps outside this TC would be executed. But without releasing the disk space, it would cause other errors like …
=> [Test gap] Fix bug in test_disk_exhaustion.py

tests/vxlan/test_vxlan_ecmp.py
Removing a pdb inserted by mistake.
=> Remove the pdb left by mistake.

.azure-pipelines/run-test-scheduler-template.yml, .azure-pipelines/test_plan.py, tests/scripts/getbuild.py
Add support if use access token when creating test plan and downloading artifacts.
Add support if use access token when creating test plans and downloading artifacts.
Add optional parameters `access_token` when creating test plans and downloading artifacts.
Use token manually and write test case to download artifacts, both passed.
=> Add support if use access token when creating test plans and downloading artifacts

tests/vxlan/conftest.py, tests/vxlan/test_vxlan_crm.py, tests/vxlan/test_vxlan_ecmp.py
https://github.com/sonic-net/sonic-mgmt/pull/6857
=> [202012]: Porting changes for vxlan-crm to 202012.

tests/scripts/getbuild.py
Summary:
Support to pass an empty access_token
Support to pass an empty access_token
Support to pass an empty access_token
=> Support to pass an empty access_token

tests/passw_hardening/test_passw_hardening.py
Summary: When running passw_hardening TC on SONiC image which is older than 10 days, DUT can become inaccessible.
This happens after `configuring passw-hardening expiration value of 10 days`, and if you're SONiC image is older than 10 days, you're password will be expired and you wont be able to ssh to DUT until password will be changed.
```
You are required to change your password immediately (password expired).
You are required to change your password immediately (password expired).
You are on
____   ___  _   _ _  ____
/ ___| / _ \| \ | (_)/ ___|
\___ \| | | |  \| | | |
___) | |_| | |\  | | |___
|____/ \___/|_| \_|_|\____|
-- Software for Open Networking in the Cloud --
Unauthorized access and/or use are …
```
=> Fix passwrd expiration issue in passw-hardening

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/restapi/conftest.py, tests/restapi/restapi_operations.py, tests/restapi/test_restapi_vxlan_ecmp.py
Summary:
Added a stress test. This test continuously adds and removes routes while reading the routes multiple times.
=> stress test to replicate production scenario

tests/acl/test_acl.py
Summary:
Remove skip for m0 egress acl test
=> [acl][m0] Remove skip for m0 egress acl test

tests/acl/test_acl.py
Summary:
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/6925
=> [202012][acl][m0] Remove skip for m0 egress acl test #6925

tests/acl/test_acl.py
Summary:
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/6925
=> [202205][acl][m0] Remove skip for m0 egress acl (#6925)

tests/acl/templates/acltb_v6_test_rules.j2, tests/acl/templates/acltb_v6_test_rules_part_2.j2, tests/acl/test_acl.py
Summary:
- 8 ACL tests fail against DNX chipset due to its limitations. But added a fix to have unique source IPV6 and destination IPV6 fields in the ACL rules used. 
- As part of PR #6390, added similar fix but missed to add unique IPV6 addresses for certain ACL rules used.
Due to the limitation of DNX chipset with regards to IPv6 src and dst address present in the ACL rule (BRCM CSP #**CS00012257197**), 8 tests '_test_icmp_match_forwarded_' are throwing errors in counters not incremented for RULE_3. 
Hence, we added unique source and destination IPV6 address fields to the ACL rules used for the tests mentioned above.
Added unique 64 bit fields for the destination IPV6 addresses so that source and destination addresses won't match in the ACL rules being used.
Ran ACL …
=> Fix erros - Added unique IPV6 address for the missed ACL rules; Ref PR #6390

.azure-pipelines/run-test-scheduler-template.yml, .azure-pipelines/test_plan.py, azure-pipelines.yml
Previously, we set timeout in each step such as `Lock testbed`, `Prepare testbed`, `Run test` and `KVM dump`. When some issue suck like retry happens in one step, it will cause timeout error, but actually, it only needs more time to success. In this pr, we remove the timeout limit in each step and control the timeout outside in each job. When the job runs more than four hours, it will be cancelled. 
Summary:
Previously, we set timeout in each step such as `Lock testbed`, `Prepare testbed`, `Run test` and `KVM dump`. When some issue suck like retry happens in one step, it will cause timeout error, but actually, it only needs more time to success. In this pr, we remove the timeout limit in each step and control the timeout outside in each job. When the job runs more than …
=> Remove timeout in each step.

tests/common/mellanox_data.py, tests/platform_tests/api/watchdog.yml, tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
Update platform test data for SN5600
Change-Id: I8a4d5d51752f593c6e1a09c31057f21516559e39
Summary:
Update test data for new platform
Update test data
run platfrom test
SN5600
any
=> [Mellanox] Fix platform test issue for SN5600

test_reporting/junit_xml_parser.py
Summary:
Pytest in python2 environment was also upgraded from 4.6.4 to 4.6.11 in sonic-mgmt docker image, test report xml has added a layer `testsuites` out of `testsuit`, which caused xml parse error.
If `testsuites` doesn't exist, keep previous parse routine, if `testsuites` exists, ignore `testsuites` and parse `testsuite` because nothing useful information in `testsuites` now.
Run junit parser
=> Fix test report xml parse error

tests/streaming-events-telemetry.md
Plan for testing streaming structured events via gNMI
Summary:
=> Test Plan: Streaming structured events via gNMI 

tests/sai_qualify/cases_brcm_t0.py
Signed-off-by: zhoudongxu <Dongxu.Zhou@microsoft.com>
Summary: Add svi macmove test cases to BRCM T0 case 
Enable pipeline  to run these t0 tests automatically
I just change tests/sai_qualify/cases_brcm_t0.py
platform independent
yes
=> Add svi mac move test list

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/6997
=> [202205][m0] Remove skip watchdog reboot for m0 (#6997)

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/6997
=> [202012][m0] Remove skip watchdog reboot for m0 (#6997)

tests/common/devices/multi_asic.py
Summary:
Improve runtime of tests. The update of the asic service related to multi-devices only. 
Fixes #6872
short runtime of tests
added "if" condition before removing service from DEFAULT_ASIC_SERVICES
executed and compared the runtime before and after the change
=> [runtime] improve runtime of tests

tests/autorestart/test_container_autorestart.py
Ignore expected error log in 202012.
Ignore expected error log in 202012.
=> [autorestart] Ignore expected error log in 202012

tests/dualtor/test_orchagent_active_tor_downstream.py
Summary:
Fixes: I removed some import lines in [PR#6984](https://github.com/sonic-net/sonic-mgmt/pull/6984). These import lines are marked unused by pre-commit checker. But the removal breaks other test script.
I removed some import lines in PR6984. These import lines are marked unused by pre-commit checker. But the removal breaks other test script.
Add the removed lines back.
Manually run testcase.
N/A
N/A
=> Fix unwanted removal of import in PR6984

tests/common/mellanox_data.py
For SPC1, in the in the cli command for the "show platform temp" has additional sensor type "SODIMM 1 Temp" in master branch, add support in the mock data
Summary: For SPC1, in the in the cli command for the "show platform temp" has additional sensor type "SODIMM 1 Temp" in master branch, add support in the mock data
Fixes # (issue) Add sodimm in mock data for: x86_64-nvidia_sn2201-r0, x86_64-mlnx_msn2700-r0, x86_64-mlnx_msn2410-r0, x86_64-mlnx_msn2010-r0, x86_64-mlnx_msn2100-r0
For SPC1, in the in the cli command for the "show platform temp" has additional sensor type "SODIMM 1 Temp" in master branch, add support in the mock data
Add sodimm in mock data for: x86_64-nvidia_sn2201-r0, x86_64-mlnx_msn2700-r0, x86_64-mlnx_msn2410-r0, x86_64-mlnx_msn2010-r0, x86_64-mlnx_msn2100-r0
Run …
=> [Mellanox]Fix test_show_platform_temperature_mocked issue for Mellanox SPC1

tests/show_techsupport/test_auto_techsupport.py
Improved auto-techsupport tests stability
Summary: Improved auto-techsupport tests stability
Time to time test test_limit fails, now it should be more stable
See code
Executed all auto-techsupport tests
=> Improved auto-techsupport tests stability

lgtm.yml
Summary:
The LGTM service has been stopped. It has been replaced with Github code scan and pre-commit check.
This change removed lgtm.yml to deprecate LGTM check.
=> Deprecate LGTM check

tests/qos/qos_sai_base.py
Since for mellanox device qos sai test is running on ptf32 topo, need to add some logic to run testQosSaiSeparatedDscpQueueMapping and testQosSaiSeparatedDscpToPgMapping on mellanox device.
Summary:
Make testQosSaiSeparatedDscpQueueMapping and testQosSaiSeparatedDscpToPgMapping run on mellanox device.
Add some logic to get the uplink and downlink information which are required in the two cases
Run the two cases on Mellonax devices
Mellanox-SN4600C-C64
Mellanox-SN4600C-D48C40
Mellanox-SN2700
Mellanox-SN2700D-48C8
ptf32
=> Add some logic to run testQosSaiSeparatedDscpQueueMapping and testQosSaiSeparatedDscpToPgMapping on mellanox device

tests/common/plugins/conditional_mark/tests_mark_conditions_202205.yaml
Summary:
To remove xfail for fixed cases
Remove xfail from conditional file.
=> [remove xfail] TestAutoTechSupport pass now, remove xfail

tests/saitests/py3/sai_qos_tests.py
Summary:
Enhance PFC XON testcase to correct PG buffer occupying in dst port 1
On brcm platform, PG won't resume to XON state, after drain off all pkts in dst port 2 and dst port 3.
The root cause is the buffer occupied by dst port 1 is equal or more than xon offset threshold.
decrease dst port 1's buffer occupying, to make sure its size is less than xon offset threshold. as below:
**Before fix**:
```
shared buffer theshold
xon offset                            |
|                                 |
config                                                           +                                 +
-----------------------------------------------------------------*---------------------------------*----------------------
traffic in each port …
```
=> Enhance PFC XON testcase to correct PG buffer occupying in dst port 1

tests/saitests/sai_qos_tests.py
Summary:
Enhance PFC XON testcase to correct PG buffer occupying in dst port 1
On brcm platform, PG won't resume to XON state, after drain off all pkts in dst port 2 and dst port 3.
The root cause is the buffer occupied by dst port 1 is equal or more than xon offset threshold.
decrease dst port 1's buffer occupying, to make sure its size is less than xon offset threshold. as below:
**Before fix:**
```
shared buffer theshold
xon offset                            |
|                                 |
config                                                           +                                 +
-----------------------------------------------------------------*---------------------------------*----------------------
traffic in each port …
```
=> [double commit 202012] Enhance PFC XON testcase to correct PG buffer occupying in dst port 1

tests/qos/qos_sai_base.py
Summary:
miss json module
miss importing "json" module
import json module
=> [qos] miss json module

ansible/dualtor/nic_simulator/nic_simulator.py
Summary:
Let's allow both ToRs to receive any `ICMPv6` traffic from the `ptf`.
Add an upstream flow to forward the `ICMPv6` traffic to both ToRs.
Check that with `garp_service` running, both ToRs could have IPv6 neighbors.
=> [nic_simulator] Add upstream duplicate `ICMPv6` flow

tests/qos/qos_sai_base.py
Summary:
correct the parameter of stopServices
correct the parameter of stopServices
pass local tests
=> revert parameter of stopServices

tests/nat/nat_helpers.py, tests/nat/test_dynamic_nat.py
Summary:
Changes according to the errors issued by pre-commit tool in  #5639  for files:
- nat/test_dynamic_nat.py
- nat/nat_helpers.py
Pre-commit tool detected issues in the files for #5639
Fix those issues using flake8 rules 
Run pre-commit locally and tests
=> [NAT] Changes according to the errors issued by pre-commit tool

tests/platform_tests/counterpoll/test_counterpoll_watermark.py
Summary:
PR https://github.com/sonic-net/sonic-mgmt/pull/6907 introduced the following error:
```
_ ERROR collecting tests/platform_tests/counterpoll/test_counterpoll_watermark.py _
Fixture "backup_and_restore_config_db" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
```
Remove unnecessary usefixtures.
run `platform_tests/counterpoll/test_counterpoll_watermark.py`
=> Remove unnecessary usefixtures

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Many testcases failed at teardown loganalyzer phase on s6100 devices, the error log looks like this:
```
E Match Messages: 
E Dec 30 12:49:36.512773 str-s6100-acs-5 ERR CCmisApi: system_service[Errno 32] Broken pipe 
E 
E Dec 30 12:49:36.694357 str-s6100-acs-5 ERR CCmisApi: message repeated 325 times: [ system_service[Errno 32] Broken pipe] 
E 
E Dec 30 12:49:36.695649 str-s6100-acs-5 ERR CCmisApi: system_service[Errno 32] Broken pipe 
E 
E Dec 30 12:49:36.696029 str-s6100-acs-5 ERR CCmisApi: system_service[Errno 32] Broken pipe 
E 
E Dec 30 12:49:36.703308 str-s6100-acs-5 ERR CCmisApi: message repeated 8 times: [ system_service[Errno 32] Broken pipe]
```
Add it to ignore while list temporarily for now, raise …
=> Ignore ERR CCmisApi: system_service Broken pipe

tests/show_techsupport/test_auto_techsupport.py
Summary:
In latest image, for some platform testbed, the time limit for creating new tech file is not enough.
need to enlarge the time limit value.
In latest image, for some platform testbed, the time limit for creating new tech file is not enough.
Enlarge the time limit value from 300s to 600s for test case test_max_limit.
Re-run the failure case.
=> enlarge time limit for creating new tech file

tests/saitests/sai_qos_tests.py
Summary:
Enhance egress share buffer watermark test for lossy traffic
enhance testQosSaiPgSharedWatermark and testQosSaiQSharedWatermark
- add more output message for troubleshooting
- enable dynamically compensate leakout packet on brcm platform
=> [QoS] enhance egress shared buffer watermark test for lossy traffic

tests/sai_qualify/test_community.py
Summary:
Fixes #6788 
Tests could not be collected due to imports in sai_qualify tests. This occurs due to some of import statements pointing to incorrect files.
Corrected import statements to point to appropriate files.
Used --collect-only for sai_qualify tests.
=> Fix sai_qualify imports

ansible/group_vars/lab/lab.yml
Modify tacscs_servers IP, avoid conflicts with bgp neighbor IP.
Modify tacacs_servers IP, avoid conflicts with bgp neighbor IP.
Modify tacacs_servers IP from 10.0.0.x to 10.0.20.x.
Run pretest and tacacs/test_ro_user&test_rw_user, all passed.
=> Modify tacacs_servers IP, avoid conflicts with bgp neighbor IP

tests/memory_checker/test_memory_checker.py
Summary:
Recently, test_memory_checker.py failed at setup function `install_stress_utility`, unable to locate package stress.
```
RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{"changed": true, "cmd": "docker exec telemetry bash -c 'export http_proxy=http://10.10.10.10:8080/                                         && export https_proxy=http://10.10.10.10:8080/                                         && apt-get install stress -y'", "delta": "0:00:00.237748", "end": "2022-12-31 03:33:16.436027", "failed": true, "msg": "non-zero return code", "rc": 100, "start": "2022-12-31 03:33:16.198279", "stderr": "E: Unable to locate package stress", "stderr_lines": ["E: Unable to locate package stress"], "stdout": …
```
=> Add apt-get update before install stress in test_memory_checker.py

tests/dhcp_relay/test_dhcp_relay.py, tests/generic_config_updater/test_dhcp_relay.py
Summary:
Skip dhcp_relay test for mx.
Skip dhcp_relay test for mx.
=> [mx] Skip dhcp_relay test for mx

tests/nat/conftest.py, tests/nat/test_static_nat.py
Summary:
Changes according to the errors issued by pre-commit tool for files:
- nat/test_static_nat.py
- nat/conftest.py
Update NAT suite for next updates without errors issued by pre-commit tool
Fix pre-commit issues using flake8 rules
Run pre-commit locally and tests
=> [NAT] Changes according to the errors issued by pre-commit tool #2

ansible/roles/test/files/ptftests/py3/dir_bcast_test.py
Summary:
Add support for mx in test_dir_bcast
Add support for mx in test_dir_bcast
Run test on mx testbed
=> [202205][mx] Add support for mx in test_dir_bcast

ansible/files/creategraph.py
Reverts sonic-net/sonic-mgmt#7110
I found there is a bug in sonic-net/sonic-mgmt#7110. From [port_utils.py](https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/module_utils/port_utils.py) we can see many platforms are using Ethernet* as both port name and alias (for example, Ethernet1 appears in both port names and alias on platform Arista-7050-QX-32S). So, it's hard to tell if Ethernet* in link.csv is a name or an alias. I'll open a new PR later to take this situation into consideration.
=> Revert "[testbed] Convert port alias to name when generating connection graph"

ansible/config_sonic_basedon_testbed.yml, ansible/roles/eos/templates/wan-ecmp-core.j2, ansible/templates/isis_config.j2, ansible/vars/topo_wan-ecmp.yml, ansible/veos_vtb, ansible/vtestbed.yaml, tests/wan/isis/test_isis_ecmp.py
The PR is for WAN ISIS ECMP test. To verify ECMP create a multiple link multiple devices topo.
Summary:
Add new topo to verify ISIS ECMP scenarios.
Verify ISIS ECMP functionality
1. add new topo to support multiple links and multiple devices
2. add new testcases based on this new created topo
1. run testcase based on new topo.
2. create existing topo based on code change
N/A
N/A
=> add ecmp topo and testcase

test_reporting/kusto/setup.kql
Add version information `sai_origin_version` and `sai_upgrade_version` in TestReportMetadata
Summary:
Supplement of this [PR](https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html).
Add `sai_origin_version` and `sai_upgrade_version` in TestReportMetadata and the corresponding ingestion mapping.
The modified Kusto commands work as expected.
No
No
=> [SAI-PTF] Add versions in TestReportMetadata

tests/common/utilities.py, tests/route/test_default_route.py, tests/route/test_route_flap.py, tests/route/test_static_route.py
Summary:
Add support for mx in test_default_route, test_static_route, test_route_flap
Add support for mx in test_default_route, test_static_route, test_route_flap
Run tests
=> [mx] Add support for mx in route test

tests/crm/test_crm.py
Summary:
fix Celestica E1031 platform test_crm_fdb_entry failure issue.
For E1031 platform, SDK for Helix4 chip does not support retrieving max l2 entry(refer CSP CS00012270660), HW and SW CRM available counter would be out of sync, we need to customize this case for E1031.
./run_tests.sh -d cel-e1031-01 -n cel_e1031_t0 -t t0,any -u -c crm/test_crm.py
=> Celestica E1031: fix test_crm_fdb_entry failure issue

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py, tests/saitests/sai_qos_tests.py
Summary:
suport headroom test for Arista-7050CX3-32S-D48C8 and Arista-7050CX3-32S-C32 on branch 202012
double commit 2 PR in master:
https://github.com/sonic-net/sonic-mgmt/pull/7220
https://github.com/sonic-net/sonic-mgmt/pull/7226
=> [QoS 202012] headroom test support for Arista-7050CX3

.azure-pipelines/test_plan.py
In pr [#6837](https://github.com/sonic-net/sonic-mgmt/pull/6837), it improves the display of pipeline. But it still has duplicate parameter `expected_states` in order to compate to sonic-buildimage repo. After the modification in sonic-buildimage repo, I remove this parameter.
Summary:
In pr  [#6837](https://github.com/sonic-net/sonic-mgmt/pull/6837), it improves the display of pipeline. But it still has duplicate parameter `expected_states` in order to compate to sonic-buildimage repo. After the modification in sonic-buildimage repo, I remove this parameter.
Remove the patameter `expected_states` in `.azure-pipelines/test_plan.py` and the code compating to sonic-buildimage.
By running pipeline.
=> [TestbedV2]Remove parameter expected_states in `.azure-pipelines/test_plan.py`

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: enable VxLAN ECMP tests for Barefoot
=> enable VxLAN ECMP tests for Barefoot

tests/gnmi/conftest.py, tests/gnmi/helper.py, tests/gnmi/test_gnmi.py, tests/gnmi/test_gnmi_appldb.py, tests/gnmi/test_gnmi_configdb.py
Summary:
And e2e test for GNMI native write.
Create certificates for GNMI with below tests:
GNMI capabilities.
Incremental config update for ConfigDB.
Full config update for ConfigDB.
Update and delete for ApplDB.
Run sonic-mgmt test.
=> E2E test for GNMI native write

tests/gnmi/conftest.py
Summary:
Nightly test is broken by gnmi commit
Add __init__.py and fix import path.
Run end2end test and check result.
=> Fix GNMI import issue

ansible/module_utils/port_utils.py
Summary:
Update hardware sku for Arista-720DT.
Update hardware sku for Arista-720DT.
Update code in `port_utils.py`
Verified on physical testbeds.
=> [Arista-720DT] Update hardware sku for Arista-720DT

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Manually cherry-pick of this PR: https://github.com/sonic-net/sonic-mgmt/pull/7252
There are error logs in syslog which have no effect on the result
Add ignore regex
Run tests
=> [202205][loganalyzer] Add loganalyzer inore regex (#7252)

tests/everflow/everflow_test_utilities.py, tests/everflow/test_everflow_per_interface.py
Modified the everflow script to support it on marvell asic
- [-/ ] 201911
- [-/ ] 202012
- [ X] 202205
Modified the everflow script to support it on marvell asic
test suite is passing on community testbed
Yes(related to Marvell asic)
=> Modified everflow script to run it on Marvell chip

tests/common/dualtor/dual_tor_io.py
Summary:
Submitting to fix https://github.com/sonic-net/sonic-mgmt/issues/7237. 
To fix test case regression introduced to master branch. 
Ran the test `dualtor_io.test_normal_op::test_tor_switch_upstream`, it passed with the change.
=> [dualtor_io][test_normal_op] fix regression caused by recent `dual_tor_io.py` change

ansible/library/isis_facts.py, tests/common/devices/eos.py, tests/wan/isis/conftest.py, tests/wan/isis/isis_helpers.py, tests/wan/isis/template/eos_isis_config.j2, tests/wan/isis/template/sonic_isis_config.j2, tests/wan/isis/test_isis_dynamic_hostname.py, tests/wan/isis/test_isis_neighbor.py
In order to facilitate isis testcase development, add isis_facts to collect isis information from SONiC. And also add two isis testcases to check neighbor and dynamic hostname.
Summary:
Add isis_facts to facilitate isis testcase development.
Add isis testcases to check neighbor and dynamic hostname feature.
Add isis_facts to collect isis information from dut, uses `vtysh` to get `database`, `neighbor`, `hostname` and `route` information, and store them under `ansible_facts` `isis_facts`.
Add two testcases to check isis neighbor status and whether dynamic hostname would be reflected in lspid.
1. Setup isis in wan topology, check isis_facts would return the correct value.
2. Run testcases under `wan/isis` folder and check the tests would pass.
`wan-pub`, `wan-4link`, …
=> [VM]: add isis_facts and isis testcases

tests/common/marvell_data.py, tests/sai_qualify/conftest.py
Summary:
Why
Support Marvell device deployment
Signed-off-by: richardyu-ms <richard.yu@microsoft.com>
How
Add Marvell device deployment
Test
Pipeline
=> [SAI-PTF]Support Marvell device deployment

tests/scripts/sai_qualify/sai_warm_profile.sh
Signed-off-by: zhiyuanliang <t-zhliang@microsoft.com>
Fix `tests/scripts/sai_quality/sai_warm_profile.sh` for warm reboot.
Fix a bug in `tests/scripts/sai_quality/sai_warm_profile.sh`, also a supplement for PR #7176. 
Delete a exit command in `tests/scripts/sai_quality/sai_warm_profile.sh`.
Verified by running debug pipeline.
=> [SAI-PTF] Fix sai_warm_profile.sh for warm reboot

tests/sai_qualify/conftest.py, tests/sai_qualify/sai_infra.py, tests/sai_qualify/test_brcm_t0.py, tests/sai_qualify/test_sai_ptf.py, tests/sai_qualify/test_sai_ptf_warm_reboot.py, tests/sai_qualify/test_sai_t0_warm_reboot.py
Summary:
why
In currernt work flow, we created different folders for differernt test set, and the est folders complex the method for composing the parameters for running PTF. Besides, the whole process copy the test set base on different purpose, but which canbe copied once in a folder. Also, some parameters for setting up the environment duplicated with others.
How
Adjust the workflow.
- remove duplicated parameters
- simplify the workflow
Test
Pipeline
DUT
=> [SAI_Qualify]Simplify parameters and adjust dev env setup process

ansible/module_utils/port_utils.py
Signed-off-by: Kevin Wang <shengkaiwang@microsoft.com>
Summary:
=> Correct the port alias mapping for Cisco-8101-C48T8

tests/wan/isis/template/sonic_isis_config.j2, tests/wan/isis/test_isis_level_capacity.py
Add new testcase for IS-IS level verification.
Summary:
N/A
To verify IS-IS level capability.
Add new case to verify L1, L1-2, L2
Based on WAN topo, configure different level and verify
N/A
WAN topo
=> add isis level capability testcase

tests/common/helpers/assertions.py, tests/common/helpers/backend_acl.py, tests/common/helpers/drop_counters/drop_counters.py, tests/common/helpers/drop_counters/fanout_drop_counter.py, tests/common/helpers/dut_ports.py, tests/common/helpers/dut_utils.py, tests/common/helpers/enable-dynamic-buffer.py, tests/common/helpers/generators.py, tests/common/helpers/parallel.py, tests/common/helpers/pfc_gen.py, tests/common/helpers/pfc_storm.py, tests/common/helpers/platform_api/chassis.py, tests/common/helpers/platform_api/component.py, tests/common/helpers/platform_api/fan_drawer.py, tests/common/helpers/platform_api/fan_drawer_fan.py, tests/common/helpers/platform_api/module.py, tests/common/helpers/platform_api/psu_fan.py, tests/common/helpers/platform_api/scripts/platform_api_server.py, tests/common/helpers/platform_api/sfp.py, tests/common/helpers/platform_api/watchdog.py, tests/common/helpers/port_utils.py, tests/common/helpers/sad_path.py, tests/common/helpers/snmp_helpers.py, tests/common/helpers/sonic_db.py, tests/common/helpers/voq_lag.py
Summary:
This change fixes the style issues of test scripts under `tests/common/helpers` folder
=> [pre-commit] Fix style issues in test scripts under `tests/common/helpers` folder

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
720dt doesn't support test_ser for now.
Add xfail condition for 720dt
Run test
=> [720DT] Add xfail condition for 720dt

tests/crm/test_crm.py
Summary:
The following commit done as part of cherry-picking to 202012 appears bad (https://github.com/sonic-net/sonic-mgmt/commit/ab3d07d95039429e2e601de30848d3276825e724)
This was trying to bring in changes from #6968 and #6994
Cleaned up the inadvertent changes
Ran the crm testcase "test_crm_nexthop" with the changes and it passes
=> [202012] Fix crm test failures due to bad cherry-pick

tests/platform_tests/test_reload_config.py
test_reload_configuration_checks fails occasionally. The reason is when do config reload interfaces-config.service isn't exited sometimes. So, it will rasise some exceptions like below:
_{'stderr_lines': [u'Traceback (most recent call last):', u'  File "/usr/local/...: Unable to connect to redis: Cannot assign requested address', 'failed': True}_
To overcome the above case, add one check to verify if interfaces-config.service is exited before doing config reload
Summary:
Stabilize test_reload_configuration_checks
add one check to verify if interfaces-config.service is exited before doing config reload
Any
=> Stabilize test_reload_configuration_checks

tests/common/devices/eos.py, tests/common/devices/fanout.py, tests/common/devices/sonic.py
https://github.com/sonic-net/sonic-mgmt/pull/7000 removed those functions that were originally added in https://github.com/sonic-net/sonic-mgmt/pull/6397
master branch is fine, 202205 wrongly kept those functions
Summary:
=> [202205] Remove deleted functions in master, 202205 branch wrongly kept those functions

tests/saitests/py3/sai_qos_tests.py
Summary:
according to failure log of testQosSaiPgHeadroomWatermark,
```
"dst_port_id: 1, src_port_id: 2, src_port_vlan: None", 
"actual dst_port_id: 16", 
"pkts num to send: 5, total pkts: 5, pg headroom: 624", 
"lower bound: 256, actual value: 0, upper bound: 2304", 
"FAIL", 
```
Transmit have some leakout, need to dynamic compensation.
- porting dynamic compensation code from other case
- correct dest mac address of traffic with default vlan mac address
=> [QoS master/202205] dynamic compensate leakout pkg for testQosSaiPgHeadroomWatermark

docs/testbed/README.testbed.PDUWiring.md, tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Add support for a new type of pdu.
Summary:
Current APC code failed to control the new APC devices.
Checked manual.
Run test on lab devices
=> [devutils] add ApcRPDU support for PDU controller

tests/dualtor_io/test_normal_op.py
Summary:
This PR is to fix `test_normal_op` cases that failed due to recent sonic-linkmgrd change: https://github.com/sonic-net/sonic-linkmgrd/pull/163
Run the 3 cases on mixed-topo testbeds. All passed.
=> [dualtor_io] update `test_normal_op` cases impacted by `healthy` label definition change

tests/common/dualtor/mux_simulator_control.py
Summary:
The toggle utilities fail to toggle the mux ports in nightlies.
It is because that, without `icmp_responder`, `linkmgrd` is stuck in wait state and it has larger mux probe interval. So the mux status sync between `linkmgrd` and the mux simulator takes longer time.
Add the following improvements:
1. add wait for mux toggle success
2. proactively probe the mux for unchanged ports after toggle to reduce the wait time
=> [dualtor] Improve toggle fixtures

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Issue [#12464](https://github.com/sonic-net/sonic-buildimage/issues/12464) was fixed in https://github.com/sonic-net/sonic-mgmt/pull/7092.
Remove skip condition for `test_cacl_application.py`
Run `test_cacl_application.py` against master image.
=> Remove skip condition for test_cacl_application since issue was fixed

tests/wan/isis/test_isis_hello_interval.py
Add IS-IS hello interval testcase.
Summary:
N/A
To verify IS-IS hello interval functionality.
Add new testcase to verify this function point.
Run case based on WAN topo
N/A
WAN topo.
=> add isis hello interval testcase

tests/acl/templates/acltb_test_stress_acl.sh
Summary:
Manually cherry-pick of this PR: https://github.com/sonic-net/sonic-mgmt/pull/7387
=> [202205][acl] Remove typo in shell of test_stress_acl

tests/show_techsupport/test_auto_techsupport.py
Summary: `show_techsupport/test_auto_techsupport.py::TestAutoTechSupport::test_max_limit[core]` fails with below error:
```
AssertionError: New expected techsupport file was not generated
E           assert False
E            +  where False = wait_until(300, 10, 0, is_new_techsupport_file_generated, <MultiAsicSonicHost 7-dut>, [])
```
On some platforms time needed to generate auto_techsupport dump may take up `~ 15 min or more.` Reason for this is that on some platforms, amount of space dedicated to root-overlay could be up `to 100 Gb or more`, in such case 5 dummy core dumps will be created each with 5% of space, this will resolve in `25 Gb of core dumps`.
During auto_techsupport generation, `core dumps is copied …
=> Limit core dump size in auto_techsupport

tests/sai_qualify/conftest.py, tests/sai_qualify/sai_infra.py
Summary:
Copy the test invocation logs
Copy the test invocation logs to sonic-mgmt container and publish them
verify
Test the script in DUT and pipeline
=> [SAI_Qualify] Store the SAI test invocation logs

tests/show_techsupport/test_techsupport.py
Added additional validation for test case "test_techsupport"
Now test in additional doing check for content of techsupport dump file
- Check that we have "sai_sdk_dump" folder in tar.gz file and folder not empty
- Check that we have "dump" folder in tar.gz file and folder has not less than 50 files
- Check that we have "etc" folder in tar.gz file and folder has not less than 50 files
- Check that we have "log" fodler in tar.gz file and folder not empty
Summary: Added additional validation for test case "test_techsupport"
Fixes # (issue) fixed issue when techsupport has empty "dump" or "logs" or other folders but test passed
Added possibility to handle case when techsupport dump has empty "dump" or "log" or other folder. Previously test passed, …
=> [techsupport] Added additional validation for test case "test_techsupport"

tests/common/devices/sonic.py, tests/common/helpers/parallel.py
Summary:
From a sample profiling with `test_bgp_fact`, `SonicHost._gather_facts` has noticeable cumulative runtime around **30s**:
```
2    0.001    0.000   30.989   15.495 sonic-mgmt/tests/common/devices/sonic.py:175(_gather_facts)
```
As `SonicHost._gather_facts` is called during `duthosts` fixture setup, it is a mandatory call for every pytest session.
So the optimization looks promising here.
Use a thread pool to run those facts collect calls.
With improvements, the runtime of `SonicHost._gather_facts` is reduced to **15s**:
```
2    0.000    0.000   15.053    7.527 sonic-mgmt/tests/common/devices/sonic.py:176(_gather_facts)
```
=> [perf] Improve `SonicHost._gather_facts`

tests/tacacs/test_authorization.py
Summary:
test_bypass_authorization will failed due to error output change
Add exp list to support for new output
Run test
```
tacacs/test_authorization.py::test_authorization_tacacs_only[] PASSED                                                                                                                                                                                             [ 12%]
tacacs/test_authorization.py::test_authorization_tacacs_only_some_server_down[] PASSED                                                                                                                                                                            [ 25%]
tacacs/test_authorization.py::test_authorization_tacacs_only_then_server_down_after_login[] PASSED …
```
=> [tacacs] Fix test_bypass_authorization error caused by output change

.azure-pipelines/fake_script.py, .azure-pipelines/pre-commit-check.yml
Summary:
Posting Github comment during pre-commit check failed somehow.
This PR is to debug and fix this issue.
=> Fix issue of posting Github comment during pre-commit check

tests/tacacs/test_authorization.py
Summary:
Manually cherry-pick of this pr: https://github.com/sonic-net/sonic-mgmt/pull/7445
test_bypass_authorization will failed due to error output change
Add exp list to support for new output
Run test
=> [202205][tacacs] Fix test_bypass_authorization error caused by output change (#7445)

tests/dualtor/test_toggle_mux.py
Summary:
Improve `test_toggle_mux`.
1. As the link prober interval reset is needed by all cases in `test_toggle_mux.py`, wrap this logic into a module-level fixture.
2. Restarting `linkmgrd` to reduce the SONiC wait time to learn hardware mux change.
```
dualtor/test_toggle_mux.py::test_toggle_mux_from_simulator[upper_tor] PASSED                                                                                                                                                                                           [ 25%]
dualtor/test_toggle_mux.py::test_toggle_mux_from_simulator[lower_tor] PASSED …
```
=> [dualtor] Improve `test_toggle_mux`

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
- [] 202012
- [] 202205
test_gnmi_configdb.py failed and somehow caused portchannels and bgp sessions down.
File an issue https://github.com/sonic-net/sonic-mgmt/issues/7462
Skip it for now until the issue is fixed.
run gnmi/test_gnmi_configdb.py.
=> Skip test_gnmi_configdb.py for now

tests/qos/files/mellanox/packets_aging.py
Summary:
Support disabling timers on LAG members on Mellanox platforms for DSCP remapping test
There is a logic to disable some timers in ASIC before QoS test but the logic is not supported on LAG members.
Originally, QoS test cases run on PTF topo only and there is no LAG on it.
Now, for DSCP remapping test, some QoS test run in T0 topo where there are LAGs configured.
So, we need to configure disabling timers on LAG members.
Support disabling timers on LAG members on Mellanox platforms
Let's say the following sets
- all ports' set: P
- all LAGs' set: L
- all LAG members' set: M
Originally, we disabled timer for all ports in `P`
Now, we will do that for all ports in `P - M + L`
Manually test
For Mellanox platform only.
=> [Mellanox] Support disabling timers on LAG members for QoS test in dual ToR DSCP remapping scenario

test_reporting/kusto/setup.kql
To support uploading dut core dump and config check result into kusto, we shoud add a column in table `Testcases` in db `SonicTestData` to record this result. 
Summary:
To support uploading dut core dump and config check result into kusto, we shoud add a column in table `Testcases` in db `SonicTestData` to record this result. 
Add a column in table `Testcases` in db `SonicTestData`.
=> Add a column in table `Testcases` in db `SonicTestData`. 

docs/code-review-guidlines.md
The intention of this PR is to introduce code review guidelines, to be followed by the authorized sonic-mgmt reviewers.
=> sonic-mgmt code review guidelines

.azure-pipelines/pr_test_scripts.yaml
Summary:
Temporary remove test_advanced_reboot.py since it stably fails:
https://www.testbed-tools.org/scheduler/testplan/63eafe325fd40eb56f5826df
Temporary remove test_advanced_reboot.py since it stably fails
=> Temporary remove test_advanced_reboot.py since it stably fails.

tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py, tests/platform_tests/mellanox/test_psu_power_threshold.py
Summary:
Adjust test case for PSU power threshold checking
1. The slope should be per PSU value instead of global
2. Cosmetic change: power_warning_threshold => power_warning_suppress_threshold
3. Fix pre-commit check failures
Adjust test case for PSU power threshold checking.
Manual and regression test.
=> Adjust test case for PSU power threshold checking

tests/crm/test_crm.py
Summary:
Modified the crm test case to run it on marvell asic
- [ X] 202205
CRM test_acl_entry test case is modified for marvell asic. Added marvell specific check according to marvell design
test case is passing on community testbed
```
crm/test_crm.py::test_crm_route[str-marvell-acs-1-None-ipv4] PASSED                    
crm/test_crm.py::test_crm_route[str-marvell-acs-1-None-ipv6] PASSED                    
crm/test_crm.py::test_crm_nexthop[str-marvell-acs-1-None-4-2.2.2.2] PASSED             
crm/test_crm.py::test_crm_nexthop[str-marvell-acs-1-None-6-2001::1] PASSED             
crm/test_crm.py::test_crm_neighbor[str-marvell-acs-1-None-4-2.2.2.2-2.2.2.1/8] PASSED  
crm/test_crm.py::test_crm_neighbor[str-marvell-acs-1-None-6-2001::1-2001 …
```
=> Modified the crm test case to run it on marvell asic

tests/bgp/test_bgp_update_timer.py, tests/common/dualtor/mux_simulator_control.py
Summary:
This reverts commit d88b354e070e5e264300566443a0ee9f092af77e.
As the PR uses fixtures not available in the 202012 branch.
=> [202012] Revert "[dualtor] Fix `test_bgp_update_timer` (#7448)"

tests/autorestart/test_container_autorestart.py
=> [container_autorestart] Ignore error logs

.azure-pipelines/test_plan.py
1. Add support **sonic-testbed-tools dev** scope according to different `testbed-tools-url`.
2. If request failed and got error response, it will not have `success` attribute (actually, no data), only has `msg`. So that check response `data` first.
3. Add argument `repo-name` for other repos if want to run test using **sonic-mgmt** repo.
=> Add support sonic-testbed-tools dev scope

tests/wan/isis/conftest.py, tests/wan/isis/test_isis_auth.py
Summary:
Add new test cases to verify FRR ISIS password auth configuration.
Verify SONiC ISIS password auth configuration.
Config area or interface password on both DUT and NBR
Verify routing table on DUT ensure ISIS routing to NBR is available.
No
Yes
=> Add new test cases of FRR ISIS clear/md5 password auth

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Skip test_forward_ip_packet_with_0xffff_chksum_tolerant and run test_forward_ip_packet_with_0xffff_chksum_drop on DNX.
Summary:
=> Fix test_forward_ip_packet_with_0xffff_chksum test for DNX

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
skip testQosSaiHeadroomPoolWatermark on mellanox platform
skip testQosSaiHeadroomPoolWatermark on mellanox platform
=> [qos] skip testQosSaiHeadroomPoolWatermark on mellanox platform

.azure-pipelines/pr_test_scripts.yaml
add following stable tests for multi-asic pr check:
- bgp/test_bgp_bbr.py
- bgp/test_bgp_fact.py
- bgp/test_bgp_update_timer.py
- snmp/test_snmp_default_route.py
- snmp/test_snmp_loopback.py
- snmp/test_snmp_pfc_counters.py
- snmp/test_snmp_queue.py
- tacacs/test_accounting.py
- tacacs/test_authorization.py
- tacacs/test_jit_user.py
- tacacs/test_ro_user.py
- tacacs/test_rw_user.py
- cacl/test_cacl_function.py
- platform_tests/link_flap/test_link_flap
- monit/test_monit_status.py
- iface_namingmode/test_iface_namingmode/test_config_interface_ip.py
- scp/test_scp_copy.py
- test_interfaces.py
- override_config_table/test_override_config_table.py
- process_monitoring/test_critical_process_monitoring.py
- container_checker/test_container_checker.py
- http/test_http_copy.py
tests are picked …
=> [pr check] [masic] [chassis] add tests for multi-asic pr check

tests/dualtor/conftest.py, tests/dualtor/test_dualtor_bgp_update_delay.py, tests/dualtor/test_grpc_server_failure.py, tests/dualtor/test_ingress_drop.py, tests/dualtor/test_ipinip.py, tests/dualtor/test_orch_stress.py, tests/dualtor/test_orchagent_active_tor_downstream.py, tests/dualtor/test_orchagent_mac_move.py, tests/dualtor/test_orchagent_slb.py, tests/dualtor/test_orchagent_standby_tor_downstream.py, tests/dualtor/test_server_failure.py, tests/dualtor/test_standby_tor_upstream_mux_toggle.py, tests/dualtor/test_tor_ecn.py, tests/dualtor_io/test_heartbeat_failure.py, tests/dualtor_io/test_link_drop.py, tests/dualtor_io/test_link_failure.py, tests/dualtor_io/test_normal_op.py, tests/dualtor_io/test_tor_bgp_failure.py, tests/dualtor_io/test_tor_failure.py, tests/dut_console/test_escape_character.py, tests/dut_console/test_idle_timeout.py
Summary:
This change fixes the style issues of test scripts under `tests/d*` folder
=> [pre-commit] Fix style issues in test scripts under `tests/d*` folder

ansible/roles/test/files/acstests/everflow_policer_test.py, tests/everflow/everflow_test_utilities.py, tests/everflow/test_everflow_testbed.py
#
Summary:
Modified the everflow policer script for Marvell ASIC
- [X ] 201911
- [X ] 202012
- [X ] 202205
Modified the everflow policer script for Marvell ASIC
Changed the CIR value according to Marvell ASIC design
test cases are passing on community testbed
everflow/test_everflow_testbed.py::TestEverflowV4IngressAclIngressMirror::test_everflow_dscp_with_policer[cli-downstream] PASSED
everflow/test_everflow_testbed.py::TestEverflowV4IngressAclIngressMirror::test_everflow_dscp_with_policer[cli-upstream] PASSED  
Yes
=> Modified the everflow policer script for Marvell ASIC

tests/fdb/conftest.py, tests/fdb/test_fdb.py, tests/fdb/test_fdb_mac_move.py, tests/fdb/utils.py, tests/fib/test_fib.py, tests/flow_counter/flow_counter_utils.py
Summary:
This change fixes the style issues of test scripts under `tests/f*` folder
=> [pre-commit] Fix style issues in test scripts under `tests/f*` folder

tests/generic_config_updater/conftest.py, tests/generic_config_updater/gu_utils.py, tests/generic_config_updater/test_aaa.py, tests/generic_config_updater/test_bgp_prefix.py, tests/generic_config_updater/test_bgp_speaker.py, tests/generic_config_updater/test_bgpl.py, tests/generic_config_updater/test_cacl.py, tests/generic_config_updater/test_dhcp_relay.py, tests/generic_config_updater/test_incremental_qos.py, tests/generic_config_updater/test_ipv6.py, tests/generic_config_updater/test_monitor_config.py, tests/generic_config_updater/test_ntp.py, tests/generic_config_updater/test_pfcwd_interval.py, tests/generic_config_updater/test_portchannel_interface.py, tests/generic_config_updater/test_syslog.py, tests/generic_config_updater/test_vlan_interface.py
Summary:
This change fixes the style issues of test scripts under `tests/g*` folder
=> [pre-commit] Fix style issues in test scripts under `tests/g*` folder

tests/common/devices/base.py, tests/common/devices/sonic.py, tests/common/dualtor/data_plane_utils.py, tests/common/dualtor/dual_tor_io.py, tests/common/dualtor/mux_simulator_control.py, tests/common/fixtures/advanced_reboot.py, tests/common/fixtures/conn_graph_facts.py, tests/common/fixtures/duthost_utils.py, tests/common/fixtures/fib_utils.py, tests/common/fixtures/pfc_asym.py, tests/common/fixtures/populate_fdb.py, tests/common/helpers/parallel.py
Summary:
This change fixed all style issue in files under `tests/common`.
=> [pre-commit] Fix style issue of files under `tests/common`

spytest/apis/switching/vlan.py
Vlan Test update with regards to the HLD [Switch Port Modes and VLAN CLI Enhancement](https://github.com/sonic-net/SONiC/pull/912)
Summary:
=> updated vlan creation in '/spytest/apis/switching/vlan.py' with switchport mode assignment

.azure-pipelines/pr_test_scripts.yaml
https://github.com/sonic-net/sonic-mgmt/pull/7601 introduced 2 invalid tests due to syntax issue, they were not caught by azp/PR checks, because test with this name were not found and were skipped
This PR: 
removing test_link_flap as no fanout host VS for PR checks
fix syntax for test_iface_namingmode.py
Summary:
=> [pr checks] [masic] fix multi_asic PR tests

tests/generic_config_updater/test_monitor_config.py
Summary: Missing argument placeholder in one of the cli command
Add back missing argument placeholder
Add back missing argument placeholder
E2E test
=> [GCU] argument missing placeholder in test_monitor_config.py

ansible/library/isis_facts.py
Add spf related items in isis_facts
Summary:
For better support IS-IS spf related testcases, add spf related items in isis_facts.
Collect `isis spf-delay-ietf` command result and extend summary result to include spf related items.
Run IS-IS testcases, spf items would be shown in isis_facts.
=> [VM]Add spf related items in isis_facts

tests/common/fixtures/duthost_utils.py, tests/common/fixtures/fib_utils.py
Summary:
test_snmp_fdb/test_fib/test_tagged_arp failed due to "members" field removed by this PR: https://github.com/sonic-net/sonic-buildimage/pull/13660
Add support for this change.
Run test
```
snmp/test_snmp_fdb.py::test_snmp_fdb_send_tagged PASSED                                                                                                                                                                                                                          [100%]
fib/test_fib.py::test_hash[ipv4] PASSED                                                                                                                                                                                                                                          [ 50%] …
```
=> [portchannel] Fix test_snmp_fdb/test_fib/test_tagged_arp failed due to config_db change

.github/CODEOWNERS
Summary:
Update the owner of platform_tests.
=> Update code owner of platform_tests

ansible/module_utils/port_utils.py
Summary:
Update port_utils.py to support generating name/alias mapping for DellEMC-Z9332f-C32.
Update port_utils.py to support generating name/alias mapping for DellEMC-Z9332f-C32.
Update port_utils.py according to port_config.ini
Verified on Dell Z9332f switches with 100G cables connected.
=> Update port_utils for DellEMC-Z9332f-C32

tests/common/fixtures/duthost_utils.py, tests/common/fixtures/fib_utils.py
Summary:
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/7650
test_snmp_fdb/test_fib/test_tagged_arp failed due to "members" field removed by this PR: sonic-net/sonic-buildimage#13660
Add support for this change.
Run test
=> [202205][portchannel] Fix test_snmp_fdb/test_fib/test_tagged_arp failed due to config_db change (#7650)

tests/common/cisco_data.py
Summary:
Fix Cisco-8000 platform file writing.
Platform file variable location moved into a deeper structure, added relevant accessor to change these variables. 
Reproduced breakage on 202012 branch for LossyQueueVoq test case, verified this change passes the test. 
Uplifted 202012 edited code to master to file this PR since master/202205 also needs the change.
=> Fix Cisco-8000 platform file writing

tests/wan/isis/conftest.py
Summary:
Get ISIS peer's P2P address to check ISIS routing hop
Check routing table to identify if next hop to neighbor is available.
=> Retrieve DUT and NBR ISIS P2P from facts

.azure-pipelines/pr_test_scripts.yaml
Comment override_config_table/test_override_config_table.py to unblock 202205 buildimage PR merge
Summary:
override_config_table/test_override_config_table.py stably fails on 202205 buildimage's PR test.
https://dev.azure.com/mssonic/build/_build/results?buildId=229839&view=logs&jobId=a95fab0a-d7c5-510e-6b42-8a669dd84f78&j=a95fab0a-d7c5-510e-6b42-8a669dd84f78&t=6626bf19-b62a-5887-f5b3-3b7e9d350724
Hence Temporarily comment the test module.
override_config_table/test_override_config_table.py stably fails on 202205 buildimage's PR test.
https://dev.azure.com/mssonic/build/_build/results?buildId=229839&view=logs&jobId=a95fab0a-d7c5-510e-6b42-8a669dd84f78&j=a95fab0a-d7c5-510e-6b42-8a669dd84f78&t=6626bf19-b62a-5887-f5b3-3b7e9d350724
Hence Temporarily comment the test module.
=> Comment override_config_table/test_override_config_table.py to unblock 202205 buildimage PR merge

.azure-pipelines/fake.py, .azure-pipelines/pre-commit-check.yml
Summary:
Previously the Github comment posted by pre-commit check is using personal Github account. It would be better to use a common account.
Update service connection name used by pre-commit check. The new connection is using a common account.
=> Update service connection name used by pre-commit check

ansible/files/lab_connection_graph.xml, ansible/files/sonic_lab_console_links.csv, ansible/library/conn_graph_facts.py
Add baud rate config to console_links.csv and the related tools.
Summary:
Automating deployment of MC0 would need this information.
Add a column to console_links.csv. Also conn_graph_facts.py need adjustments to include this information.
=> [connection graph] add baud rate config to console_links.csv

ansible/roles/test/files/ptftests/py3/fdb_flush_test.py, tests/fdb/test_fdb_flush.py
Summary:
Fix test gap issue 5822
https://github.com/sonic-net/sonic-mgmt/issues/5822
Fix test gap for issue 5822
https://github.com/sonic-net/sonic-mgmt/issues/5822
Add 4 new cases.
Verifies fdb operation is smooth, No new core files are generated after fdb operation.
Pass locally test
=> add new fdb flush test

tests/route/test_route_perf.py
* Adding traffic verification after the routes are installed.
* Current verification done with APP DB commands.
* Adding traffic verification and using different route prefix will harden the test
* It will also ensure the routes are actually programmed on asic.
Summary:
Enhancing test_route_perf.py to add traffic verification
Enhancing test_route_perf.py to add traffic verification
Ran this test in T0, T1, M0 topo and it passed
=> Enhancing test_route_perf.py to add traffic verification

tests/common/devices/sonic.py
Summary: Removed git conflict records that have been merged into tests/common/devices/sonic.py(introduced by https://github.com/sonic-net/sonic-mgmt/pull/5871
Fixes # (issue) Fix https://github.com/sonic-net/sonic-mgmt/issues/7666
=> Remove the git conflict records which has been merged

docs/testplan/dual_tor/dual_tor_orch_test_plan.md
Summary:
We recently noticed some issues with standalone tunnel route in active-active dualtor setup, adding test cases for better coverage on this feature. 
=> [dualtor] Add test for standalone tunnel route

tests/ipfwd/test_dir_bcast.py
Summary:
test_dir_bcast failed in mx because mx doesn't have portchannel
Change method of getting upstream ptf port.
Run test in t0, m0, mx topo, all passed
=> [mx][ipfwd] Fix test_dir_bcast failed in mx topo

ansible/files/lab_connection_graph.xml, ansible/files/sonic_lab_console_links.csv, ansible/files/sonic_lab_devices.csv, ansible/group_vars/lab/lab.yml, ansible/lab, ansible/library/conn_graph_facts.py, ansible/mcx.yml, ansible/roles/mcx/tasks/main.yml, ansible/roles/mcx/templates/console_config.j2, ansible/roles/mcx/templates/mcx_config.j2
MCX is the combination of MX and C0. Add ansible playbook to deploy console server as part of MCX's configuration process.
Summary:
Add ansible playbook do autodeploy console servers.
Add mcx.yaml playbook.
Try deploying console server in lab.
=> [ansible] add config mcx

tests/crm/conftest.py
Summary:
fix CRM setup failure
fix CRM setup failure
https://github.com/sonic-net/sonic-mgmt/pull/7452
fix, revert code as original one
run crm case
=> fix crm setup failure

tests/copp/copp_utils.py
Summary:
The function _install_nano in COPP module would install some additional packages during the tests.
it would increase the image size.
The function _install_nano in COPP module would install some additional packages during the tests.
it would increase the image size.
Restart the syncd after COPP test.
Run original test and check the size.
=> restart syncd after copp test

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml, azure-pipelines.yml
Summary:
code scanning query 'py/polynomial-redos' hangs for unknown reason.
This PRs' codeql will not pass. After it is merged, code scanning will pass.
Issue on codeql: https://github.com/github/codeql/issues/12528
=> Walk around for code scanning hanging issue.

test_reporting/kusto/swss_scan.kql
Signed-off-by: ms-junyi <t-junyixiao@microsoft.com>
add swss scan kql
Summary:
=> add swss scan kql

.azure-pipelines/test_plan.py
Summary:
Enhance test_plan script for nightly test scenario,
Add new parameters:
testbed-name, image_url, hwsku, test-plan-type, platform, scripts,
Detail logic in the code.
Enhance test_plan script for nightly test scenario,
Add new parameters:
testbed-name, image_url, hwsku, test-plan-type, platform, scripts,
Detail logic in the code.
=> Enhance test_plan script for nightly test scenario

spytest/Doc/README, spytest/Doc/README.md, spytest/Doc/install.md, spytest/Doc/intro.md, spytest/README.md, spytest/containers/README.md, spytest/spytest/tgen/init.py
added references to docs, created readme.md where missing, created links between the docs
Summary:
update and clarify and make docs easier to be found
created few readme.md and links between them
verified the links in my own repo
spytest
=> spytest docs update

tests/qos/qos_sai_base.py
Summary:
Currently the Qos SAI test doesn't support the topology t0-56-po2vlan, in this topology there are 2 downlink Vlans and a extra portchannel is the member of both vlans. Need to adjust the test to support this topology.
Support t0-56-po2vlan topology in Qos SAI test
The test will fail in __assignTestPortIps() in tests/qos/qos_sai_base.py because it doesn't expect there are multiple Vlans or a Vlan member is portchannel.
I add logic that when the topo is t0-56-po2vlan, choose the Vlan with physical ports to test and remove the portchannel member from the testVlanMembers. 
By automation, all cases in test test_qos_sai.py passed on t0-56-po2vlan topo.
=> Add support for t0-56-po2vlan topo to qos sai test

tests/testbed_setup/test_add_property_spytest_junit_xml.py
Summary:
Add missing topo mark `util`.
=> Add missing topo mark to `test_add_property_spytest_junit_xml`

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
add to skip conditions of ecmp test "test_fgnhg" the issue https://github.com/sonic-net/sonic-mgmt/issues/7755
=> [ecmp] update skip for test_fgnhg

.azure-pipelines/test_plan.py
Summary:
Refine test_plan.py code logic
Refine test_plan.py code logic
Refine test_plan.py code logic
=> Refine test_plan.py code logic

ansible/module_utils/port_utils.py
Summary:
Fixes Python syntax error imported from #7694.
- Fix the missing right parenthesis on line 253
- Fix flake8 errors.
=> Fix a missing right parenthesis and flake8 issues in port_utils.py

ansible/roles/test/files/ptftests/IP_decap_test.py, ansible/roles/test/files/ptftests/pfc_wd.py, ansible/roles/test/files/ptftests/populate_fdb.py, ansible/roles/test/files/ptftests/vnet_vxlan.py, ansible/roles/test/files/ptftests/vrf_test.py, tests/common/cache/facts_cache.py, tests/common/devices/cisco.py, tests/common/devices/duthosts.py, tests/common/fixtures/advanced_reboot.py, tests/common/fixtures/ptfhost_utils.py, tests/common/helpers/platform_api/scripts/platform_api_server.py, tests/common/pkt_filter/filter_pkt_in_buffer.py, tests/crm/test_crm.py, tests/ecmp/test_fgnhg.py, tests/fdb/test_fdb.py, tests/generic_config_updater/test_vlan_interface.py, tests/pc/test_lag_member.py, tests/pfcwd/files/pfcwd_helper.py, tests/voq/test_voq_intfs.py, tests/wan/lacp/test_wan_lag_member.py
Summary:
Fix issues found during internal smoke test
1. str <-> unicode
2. str style: u''
3. Other bad changes introducted by 2to3 tool
Internal smoke test failure
Review what 2to3 tool has done and revert some changes.
Run test manually
=> [Python3 migration]Revert some changes introducted by 2to3 tool

setup-container.sh
Summary:
This PR https://github.com/sonic-net/sonic-buildimage/pull/14291 removed the python virtual environment env-201811. After this change, the `.local` folder under `/var/AzDevOps` no longer exists. Then `setup-container.sh` will fail at copying this folder.
This change improved the robustness of setup-container.sh for copying the hidden files.
The change is to loop through the hidden stuff that needs to be copied. Then try to copy them with best effort.
Run `setup-container.sh` using latest sonic-mgmt docker image.
=> Improve robustness of setup-container.sh for copying hidden files

.azure-pipelines/run-test-scheduler-template.yml, .azure-pipelines/test_plan.py
Summary:
Enhance test plan script, support to pass more test plan parameters
To support nightly test plan.
Enhance test plan script, support to pass more test plan parameters
=> Enhance test plan script, support to pass more test plan parameters

ansible/files/creategraph.py
Create default bmc csv file variable in creategraph.
Summary:
Run without -i will result in error.
Run test in lab.
=> [ansible/create_graph.py]fix bug with creategraph.py

tests/common/devices/arista.py, tests/common/devices/cisco.py, tests/common/devices/juniper.py
Summary:
This is related to move WAN test vendor test case to sonic-mgmt, adding vendor juniper, arista and Cisco APIs to the open-source repos and avoid the code conflict as sonic-wan team also using those APIs. 
Adding Arista, juniper and Cisco APIs to support wan vendor test case.
NA
Verified those APIs with wan test case in local lab.
Arista, Cisco and Juniper OS only.
NA
=> Adding wan test vendor APIs

tests/telemetry/conftest.py, tests/telemetry/test_telemetry.py
Summary:
Fix migration issue in telemetry testcase
@zbud-msft found that the test_telemetry.py is incorrectly merged in Python3 migation PR.
Change the file with correct content.
Run the test case manually.
=> [Python3 migration]Fix migration issue in telemetry testcase

tests/route/test_default_route.py
Fix 1 issues described in https://github.com/sonic-net/sonic-mgmt/issues/7824
pass `device_neigh_metadata` in `get_uplink_ns`
Summary:
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/7824
After:
```
route/test_default_route.py::test_default_route_set_src[masic-1-3] PASSED                                                                                                                                                                     [ 33%]
route/test_default_route.py::test_default_ipv6_route_next_hop_global_address[masic-1-0] PASSED                                                                                                                                                [ 66%]
route/test_default_route.py::test_default_route_with_bgp_flap[masic-1] PASSED …
```
=> [chassis] Fix test_default_route.py for chassis

tests/dualtor/test_tor_ecn.py
Summary:
Currently, test_tor_ecn.py use same outer dscp with inner dscp, which does not cover PCBB.
In function `build_encapsulated_ip_packet`, if enable PCBB, will use correct outer dscp accordingly, otherwise, it will use same outer dscp with inner dscp.
1. Enable PCBB:
```
inner dscp|outer dscp
3|2
4|6
2|0
6|0
```
3.Disable PCBB:
```
inner dscp|outer dscp
3|3
4|4
2|2
6|6
```
Run `dualtor/test_tor_ecn.py`.
=> Use dynamic outer dscp for test_tor_ecn

.azure-pipelines/test_plan.py
Summary:
Make test_plan.py compatible between python2 and python3
Make test_plan.py compatible between python2 and python3
=> Make test_plan.py compatible between python2 and python3

.azure-pipelines/run-test-scheduler-template.yml
=> Refine testbedv2 template output

tests/fdb/test_fdb_mac_move.py
In PR [#7789](https://github.com/sonic-net/sonic-mgmt/pull/7789), I add mark `pytest.mark.topology('any')` before the script `test_fdb_mac_move.py`, thus this script will run on all of topologies. But in this script, we need to get the VLAN information of topo. On no-vlan topo, such as t1, it will raise an error `KeyError: 'VLAN'`. So in this PR, modify the mark and this script will only run on T0.
Summary:
Fixes [#7789](https://github.com/sonic-net/sonic-mgmt/pull/7789)
In PR [#7789](https://github.com/sonic-net/sonic-mgmt/pull/7789), I add mark `pytest.mark.topology('any')` before the script `test_fdb_mac_move.py`, thus this script will run on all of topologies. But in this script, we need to get the VLAN information of topo. On no-vlan topo, such as t1, it will raise an error …
=> Fix a bug in script `test_fdb_mac_move.py`.

ansible/ansible.cfg, ansible/dualtor/nic_simulator/__init__.py, ansible/plugins/callback/yaml.py, tests/common/cache/facts_cache.py, tests/common/plugins/conditional_mark/__init__.py, tests/common/plugins/log_section_start/__init__.py, tests/configlet/util/common.py, tests/conftest.py, tests/run_tests.sh
Summary:
Add Python3 support for run_tests.sh
Add testcase name (eg. tests/bgp/test_bgp_fact.py) to tests/python3_test_files.txt. The testcase will run in Python3
Add Python3 support for run_tests.sh
Cherry-pick commits from master branch:
49e545b, 09c47e9, ccad1b0, 979eb20
N/A
N/A
=> Add Python3 support for run_tests.sh

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
The indentations are missing in some lines in tests_mark_conditions_platform_tests.yaml. The prevents us from running platform tests. Add the missing indentations.
Summary:
https://github.com/sonic-net/sonic-mgmt/issues/7940
=> Add missing indentation in tests_mark_conditions_platform_tests.yaml

tests/memory_checker/test_memory_checker.py
Summary:
- 'test_memory_checker.py' test cases fail at setup function while installing stress package.
- The fix is to verify if the stress package is already present on DUT. If not, install the stress package by doing apt-get update first followed by package installation.
- 'test_memory_checker.py' test cases fail at setup function while installing stress package.
- Make sure the stress package is present on DUT or not. If not, install the stress package by doing apt-get update first followed by package installation.
- Ran the test_memory_checker test cases against a multi-asic line card in a T2 chassis.
=> Check stress package existence on dut and do apt update followed by stress package install

tests/qos/files/cisco/qos_param_generator.py, tests/qos/files/qos.yml, tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py
=> Added Cisco qos param generator (#7889)

ansible/roles/test/files/ptftests/advanced-reboot.py, ansible/roles/test/files/ptftests/arista.py
Summary: Improve LACP session wait time calculation by collecting and comparing all LACPDUs during reboot window
In present logic, LACPDU collection is stopped when control plane goes down. However, there is a chance that the last LACPDU is sent after control plane (ping to Loopback) is detected to be down.
Collect all LACPDUs uuring reboot window from when device is starting to go down to when device is back up.
At the end of test, compare maximum time difference between two consecutive LACPDUs.
Use this max wait as the deciding factor for LACP 90s window.
Tested on physical DUT - multiple platforms.
=> [advanced-reboot] Collect all LACPDUs and find max time gap btw two LACPDUs

ansible/group_vars/sonic/sku-sensors-data.yml
Add sensors data for platform x86_64-nvidia_sn5600-r0 
Summary:
Add sensors data for platform x86_64-nvidia_sn5600-r0 
Add sensors data for platform x86_64-nvidia_sn5600-r0 into file of ansible/group_vars/sonic/sku-sensors-data.yml
run test_sensors case
x86_64-nvidia_sn5600-r0
=> [Nvidia] Add sensors data for platform x86_64-nvidia_sn5600-r0 

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Many cases failed due to following ERR syslog with the latest master image, ignore them for now until the test case are fixed.
```
2023-04-03T13:38:29.7036719Z E               Failed: Processes "['analyze_logs--<MultiAsicSonicHost str2-7050cx3-acs-07>', 'analyze_logs--<MultiAsicSonicHost str2-7050cx3-acs-06>']" failed with exit code "1"
2023-04-03T13:38:29.7038281Z E               Exception:
2023-04-03T13:38:29.7039419Z E               match: 2
2023-04-03T13:38:29.7040400Z E               expected_match: 0
2023-04-03T13:38:29.7041496Z E               expected_missing_match: 0
2023-04-03T13:38:29.7042604Z E               
2023-04-03T13:38:29.7043550Z E               Match Messages:
2023-04-03T13:38:29.7045663Z E               Apr  3 13:34:25.039607 str2-7050cx3-acs-07 ERR …
```
=> Ignore err log of SAI_API_ACL:_brcm_sai_acl_entry_bind

tests/qos/Pfc_Storm_with_Shared_Headroom_test_plan.md, tests/qos/buffer_helpers.py, tests/qos/conftest.py, tests/qos/files/brcm/qos_param_generator.py, tests/qos/files/mellanox/qos_param_generator.py, tests/qos/files/qos.yml, tests/qos/qos_fixtures.py, tests/qos/qos_helpers.py, tests/qos/qos_sai_base.py, tests/qos/test_buffer.py, tests/qos/test_buffer_traditional.py, tests/qos/test_pfc_counters.py, tests/qos/test_pfc_pause.py, tests/qos/test_qos_masic.py, tests/qos/test_qos_sai.py, tests/qos/test_tunnel_qos_remap.py, tests/qos/tunnel_qos_remap_base.py
Summary:
This change fixes the style issues of test scripts under `tests/q*` folder
=> [pre-commit] Fix style issues in test scripts under `tests/q*` folder

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Skipping test test_update_valid_invalid_index[33-True] on Mellanox platform due to bug of https://github.com/sonic-net/sonic-mgmt/issues/7733
Summary:
Skip test_update_valid_invalid_index[33-True]
Run test_update_valid_invalid_index[33-True], it is sipped
Pytest run test_update_valid_invalid_index[33-True]
Any
=> Skip test_update_valid_invalid_index[33-True]

ansible/roles/vm_set/files/mux_simulator.py
Summary:
Mux simulator script only has post method log, need to add get method log to help analysis mux simulator status.
Get method is very frequently, so print 1 log every 100 gets
According to `ansible/roles/vm_set/files/mux_simulator.md`
=> Log GET requests in mux simulator

tests/radv/test_radv_ipv6_ra.py, tests/radv/test_radv_restart.py, tests/read_mac/conftest.py, tests/read_mac/test_read_mac_metadata.py, tests/restapi/conftest.py, tests/restapi/helper.py, tests/restapi/restapi_operations.py, tests/restapi/test_restapi.py, tests/restapi/test_restapi_vxlan_ecmp.py, tests/route/conftest.py, tests/route/test_default_route.py, tests/route/test_route_flap.py, tests/route/test_route_flow_counter.py
Summary:
This change fixes the style issues of test scripts under `tests/r*` folder
=> [pre-commit] Fix style issues in test scripts under `tests/r*` folder

tests/bgp/test_bgp_update_timer.py
Summary: Increase update time when suppress feature is enabled on device
On image with suppress-fib-pending know set it is expected to get BGP update later due to additional messages need to be sent between bgpd/zebra/fpmsyncd.
E.g:
```
Mar 29 14:19:20.949852 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:20 BGP: [W0R38-AAD36] 20.0.0.1 rcvd 10.10.100.128/27 IPv4 unicast
Mar 29 14:19:21.010574 r-tigon-11 INFO bgp#fpmsyncd: :- isRawProcessing: Rx MsgType:24 Encap:0
Mar 29 14:19:21.010722 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [YXCJP-0WZWV] netlink_nexthop_msg_encode: ID (713): 20.0.0.1, via PortChannel1015(1194) vrf default(0)
Mar 29 14:19:21.010722 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [R43C6-KYHWT] …
```
=> [test_bgp_update_timer] Increase update time when suppress feature is enabled on device

ansible/devutil/ansible_hosts.py
Summary:
In case the inventory file is incorrect, the tool will give confusing error like 'Unsupported ansible module "hostnames"' . It's because the ansible inventory manager is not able to find any host from a non-existent inventory file. Then it tries to raise an exception. However, the exception message has another error referencing an undefined attribute `hostname`. While raising another exception for the new error, python eventually tries to access "hostnames" attribute and lead to error 'Unsupported ansible module "hostnames"'.
This change added existence check of the inventory files and fixed the issue of referring undefined attribute.
=> [devutil/ansible_hosts] Check existence of inventory files

tests/dualtor_io/test_tor_failure.py
Summary:
stablize `test_active_tor_reboot_downstream`
use `loganalyzer` to store the syslogs of the lower ToR to help debug the toggle peer process
run on `dualtor-mixed` testbed:
```
dualtor_io/test_tor_failure.py::test_active_tor_reboot_downstream[active-active] PASSED                                                                                                                                              [100%]
================================================================================================= 1 passed, 1 deselected in 537.29 seconds =================================================================================================
```
=> [dualtor] stablize `test_active_tor_reboot_downstream`

ansible/cliconf_plugins/aos.py, ansible/devutil/conn_graph_helper.py, ansible/devutil/inv_helpers.py, ansible/devutil/ssh_utils.py, ansible/devutil/task_runner.py, ansible/dualtor/nic_simulator/nic_simulator.py, ansible/dualtor/nic_simulator/nic_simulator_client.py, ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service.proto, ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service_pb2.py, ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service_pb2_grpc.py, ansible/dualtor/nic_simulator/nic_simulator_grpc_service.proto, ansible/dualtor/nic_simulator/nic_simulator_grpc_service_pb2.py, ansible/dualtor/nic_simulator/nic_simulator_grpc_service_pb2_grpc.py, ansible/files/check_testbed_and_inventory_file.py, ansible/files/creategraph.py, ansible/group_vars/all/labinfo.json, ansible/group_vars/lab/secrets.yml, ansible/host_vars/STR-ACS-SERV-01.yml
Summary:
This change fixes the style issues of test scripts under `ansible/c*` to ansible/h*` folder
=> [pre-commit] Fix style issues in test scripts under `ansible/c*` to `ansible/h*` folder

tests/wan/isis/conftest.py, tests/wan/trex/imix.py, tests/wan/trex/stl_imix.py
Summary:
This change fixes the style issues of test scripts under `tests/w*` folder
=> [pre-commit] Fix style issues in test scripts under `tests/w*` folder

tests/tacacs/000-ro_disk.conf, tests/tacacs/test_accounting.py, tests/tacacs/test_authorization.py, tests/tacacs/test_jit_user.py, tests/tacacs/test_ro_disk.py, tests/tacacs/test_ro_user.py, tests/tacacs/test_rw_user.py, tests/telemetry/events/bgp_events.py, tests/telemetry/test_events.py, tests/telemetry/test_telemetry.py, tests/templates/bfd_responder.conf.j2, tests/testbed_setup/conftest.py, tests/testbed_setup/test_gen_spy_testbed.py, tests/testbed_setup/test_populate_fdb.py
Summary:
This change fixes the style issues of test scripts under `tests/t*` folder
=> [pre-commit] Fix style issues in test scripts under `tests/t*` folder

tests/acl/test_acl.py
Summary:
Fix #5580, this test file is not supported to run on ptf32.
Fix 5580, this test file is not supported to run on ptf32.
Changing the condition mark topology form "any" to ("t0", "t1", "t2", "m0", "mx")
N/A
N/A
N/A
=> Correct the condition mark topology for test_acl.py

azure-pipelines.yml, tests/arp/files/ferret.py, tests/arp/test_arp_dualtor.py, tests/autorestart/test_container_autorestart.py, tests/bgp/bgp_helpers.py, tests/bgp/conftest.py, tests/bgp/test_bgp_allow_list.py, tests/bgp/test_bgp_gr_helper.py, tests/bgp/test_bgp_update_timer.py, tests/bgp/test_traffic_shift.py, tests/cacl/test_cacl_application.py, tests/common/cisco_data.py, tests/common/devices/fanout.py, tests/common/devices/multi_asic.py, tests/common/dualtor/control_plane_utils.py, tests/common/dualtor/mux_simulator_control.py, tests/common/fixtures/advanced_reboot.py, tests/common/fixtures/ptfhost_utils.py, tests/common/helpers/dut_utils.py, tests/common/plugins/pdu_controller/snmp_pdu_controllers.py, tests/common/portstat_utilities.py, tests/common/reboot.py, tests/conftest.py, tests/crm/test_crm.py, tests/everflow/test_everflow_ipv6.py, tests/fdb/test_fdb.py, tests/fib/test_fib.py, tests/generic_config_updater/test_pfcwd_interval.py, tests/platform_tests/api/test_sfp.py, tests/streaming-events-telemetry.md
Summary:
This change fixes the style issues of test scripts in sonic-mgmt repo and make pre-commit to mandatory PR check
=> [pre-commit] Fix style issues in test scripts in sonic-mgmt repo and make pre-commit to mandatory PR check 

ansible/devutils, ansible/library/conn_graph_facts.py, ansible/linkstate/scripts/mlnx/fanout_listener.py, ansible/roles/vm_set/library/vm_topology.py
Summary:
When fixing style issue, some error was added like import path error
Change import position and ignore pre-commit check error
=> Fix import error added when fixing style issue

tests/platform_tests/api/test_chassis.py, tests/platform_tests/api/test_chassis_fans.py, tests/platform_tests/api/test_component.py, tests/platform_tests/api/test_fan_drawer.py, tests/platform_tests/api/test_fan_drawer_fans.py, tests/platform_tests/api/test_module.py, tests/platform_tests/api/test_psu.py, tests/platform_tests/api/test_psu_fans.py, tests/platform_tests/api/test_sfp.py, tests/platform_tests/api/test_thermal.py
Summary:
Fixes pre-commit issue under tests/platform_tests
Add a few # noqa
Only comments added so no need to run tests.
=> Fix pre-commit issue under tests/platform_tests

setup-container.sh
Summary:
Make the sonic-mgmt container hostname align with the container name on the host.
Run the `setup-container.sh` script and verify the created container hostname is the same as the `-n` argument given to the script.
=> Set sonic-mgmt docker hostname

tests/crm/test_crm.py
Summary: Modified CRM ACL entry testcase according to Marvell Design
Ran test case on sonic PTF testbed and test case is passing
crm/test_crm.py::test_acl_entry[str-marvell-acs-1-None] PASSED
YES
=> Modified CRM ACL entry testcase according to Marvell Design

ansible/group_vars/sonic/sku-sensors-data.yml
Update sensors data for sn5600 due to hardware change
Summary:
Update sensors data for sn5600
update ansible/group_vars/sonic/sku-sensors-data.yml
run test_sensors.py
sn5600
Any
=> [Nvidia]Update sensors data for sn5600

tests/saitests/py3/sai_base_test.py
Summary:
A cross circular reference of a global variable caused a conflict in `tests/saitests/py3/sai_base_test.py`
Import after variable was defined
Run qos test
=> Fix import error in saitests

tests/route/test_static_route.py
Summary:
Cherry pick PR into 202012 because of conflict
https://github.com/sonic-net/sonic-mgmt/pull/6385
https://github.com/sonic-net/sonic-mgmt/pull/7898
https://github.com/sonic-net/sonic-mgmt/pull/7984
Also use 'Black' for format refine.
=> [cherry pick] PR #7984, #6385, #7898 into 202012

tests/common/devices/sonic.py, tests/common/devices/sonic_asic.py, tests/common/fixtures/duthost_utils.py, tests/common/fixtures/ptfhost_utils.py, tests/conftest.py, tests/qos/files/mellanox/qos_param_generator.py, tests/qos/qos_helpers.py, tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_base_test.py, tests/saitests/py3/sai_qos_tests.py, tests/saitests/py3/switch.py, tests/test_pretest.py
Summary:
Revert #8059 and #8148 because they caused QoS test failure
QoS SAI test failed (test setup failed) due to #8059 and #8148 
Revert #8059 and #8148
N/A
=> Revert PR8059 and PR8148 in 202205 branch

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Xfail test_eth_interface due to many failures found
File an issue #8143
Add xfail session for test_eth_interface
run generic_config_updater/test_eth_interface.py
=> Xfail test_eth_interface due to many failures found

tests/gnmi/conftest.py, tests/gnmi/helper.py
Summary:
GNMI container name can be "telemetry" and "gnmi".
Add logic to detect GNMI container name.
Run gnmi end2end test.
=> Add support for GNMI container

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/qos/test_buffer_traditional.py
Summary:
Changes from #8062 
Make the test_buffer_traditional multi-asic compatible
Verified the changes against single asic and multi asic platforms and it passes
=> [qos] Add multi-asic support for test_buffer_traditional

.azure-pipelines/run-test-scheduler-template.yml
Summary:
Enhance testbedv2 scheduler template:
1. Remove kvm_dump step if it is not needed.
2. Support to set max run test time.
Enhance testbedv2 scheduler template:
1. Remove kvm_dump step if it is not needed.
2. Support to set max execute time.
=> Enhance testbedv2 scheduler template

tests/common/fixtures/fib_utils.py
Added missing changes of PR #7385 to fib_utils.py
Summary:
Some changes of PR #7385 were missed in fib_utils.py.  We need to add the those changes for fib testcases to pass.
Added the missed codes to fib_utils.py.
Tested fib testcases.
=> Added missing changes of PR#7385 to fib_utils.py

tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
=> Separate the condition for different platform to avoid interaction

tests/drop_packets/test_drop_counters.py
Summary:
Some errors were imported when fixing style issue. Imported by PR: https://github.com/sonic-net/sonic-mgmt/pull/8001
Fix imported issues
=> [drop_packets] Fix drop_packets test failure

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
The check to make sure that the condition marker file is sorted alphabetically has been added to pre-commit check, need to sort these yaml files to make sure future PR not be blocked by previous unsorted issue
Sort all tests_mark_conditions*.yaml files
=> [pre-commit] Fix style issues in tests_mark_conditions*.yaml

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
This PR is to update the skip condition for `test_fgnhg.py`.
The test is skipped in any of below conditions
- The running image is below `202012`
- The testbed is a SN2700 testbed
- The testbed is not `Mellanox` platform
- The topology is not `T0`
This PR also removes the `xfail` condition as the xfail is probably covering issues.
This PR is to update the skip condition for `test_fgnhg.py`.
Update the `tests_mark_conditions.yaml`.
The yaml file is validated.
No.
No.
=> Update the skip conditions for fgnhg test

ansible/mcx.yml, ansible/roles/mcx/tasks/dry_run_incremental.yml, ansible/roles/mcx/tasks/dry_run_reset.yml, ansible/roles/mcx/tasks/incremental_update.yml, ansible/roles/mcx/tasks/main.yml, ansible/roles/mcx/tasks/reset_update.yml, ansible/roles/mcx/templates/incremental_mcx_config.j2, docs/testbed/README.testbed.MCX.md
Add option to let mcx ansible playbook to config mcx incrementally or completely new
Summary:
Currently mcx playbook will wipe out all configurations when deploying mcx, add an option to update incrementally.
Add new function
Run test.
=> [ansible] update mcx ansible to config incrementally

ansible/vars/topo_tgen-t1-64-3.yml
Summary: Introducing a 3 port topo to run RDMA nightly tests on the switch. 
New topo needed for RDMA nightly testing on lab device. 
Created a new topo file
=> [Topo] 3 port tgen topo for RDMA testing

tests/common/devices/onyx.py
Added FEC support for MLNX/Nvidia fanout
Added possibility to get/set FEC for MLNX/Nvidia fanout
Summary: Added FEC support for MLNX/Nvidia fanout
Added possibility to run autoneg tests which require fanout FEC config on setups with Mellanox/Nvidia fanout
see code
Executed autoneg tests
Mellanox/Nvidia fanout related
=> [auton-neg] Added FEC support for MLNX/Nvidia fanout

tests/qos/files/mellanox/qos_param_generator.py, tests/qos/qos_sai_base.py
Update qos sai test paramters for Spectrum 4 of nvaidia platform
Summary:
Update qos sai test paramters for Spectrum 4
run qos sai tests on Spectrum 4 of nvidia platform
run qos sai tests
spc4
t0
=> [Nvidia] Update qos sai test for Spectrum 4

ansible/dualtor/nic_simulator/nic_simulator.py
Summary:
Update `nic_simulator` upstream flows to follow the same tx logic.
Add three extra flows to duplicate the following upstream packets:
1. upstream packets from `ptf` with dest ip as `Loopback2`
2. upstream packets from `ptf` with dest ip as `Loopback3` of the upper ToR
3. upstream packets from `ptf` with dest ip as `Loopback3` of the lower ToR
Redeploy with the updated `nic_simulator`.
=> [dualtor][active-active][nic_simulator] Update tx logic

.azure-pipelines/pr_test_scripts.yaml
Reverts sonic-net/sonic-mgmt#7340
=> Revert "Add test_events.py to test scripts"

tests/platform_tests/test_cpu_memory_usage.py
adding memory threshold for some VOQ chassis
Summary:
=> [chassis] adding memory threshold for some VOQ chassis

docs/testbed/sai_quality/ExampleCheckSonicVersionAndBuildSaiserverDocker.md, docs/testplan/Chassis-everflow-test-plan.md, tests/acl/test_acl.py, tests/common/helpers/dut_utils.py
Summary:
All the SONiC repositories have been migrated to github.com/sonic-net. We need to correct the links referring to old URLs.
This change is to cleanup a few references to github.com/Azure.
Document change. No test required.
=> Cleanup reference to github.com/Azure for SONiC repositories

.azure-pipelines/get_dut_version.py
In TestbedV2, we need to get return value of script `get_dut_version.py`, but it is difficlut to get the return value of a python script. If we print the return value out, there is additional information and also hard to split them. So we decide to output the return value into a file, and add an argument to decide whether the return value will be output. 
Summary:
In TestbedV2, we need to get return value of script `get_dut_version.py`, but it is difficlut to get the return value of a python script. If we print the return value out, there is additional information and also hard to split them. So we decide to output the return value into a file, and add an argument to decide where the return value will be output. 
Add an argument to decide where the return value will be …
=> Add argument `output` in script `get_dut_version.py` to support TestbedV2 scenario.

tests/radv/test_radv_run.py
Summary:
Radv service should be disabled for po2vlan.
Update deployment id, restart radv container, and then check radv service.
=>  Radv test case for po2vlan

.azure-pipelines/pr_test_scripts.yaml, tests/kvmtest.sh
Summary: Remove override test from t1 suite due to override CLI change.
Current override test doesn't support multi-asic after the config override CLI change. Remove it from t1 suite.
Remove it from t1 suite.
E2E test
=> [override_config_table]Remove override test in t1 test suite

tests/pfcwd/test_pfcwd_function.py
Summary:
If ‘tunnel_qos_remap’ is enabled, the PGs ‘2-4’ will be seen instead of ‘3-4’.
A check need to be added to use ‘2-4’ if ‘SYSTEM_DEFAULTS’ has ‘tunnel_qos_remap’ enabled else continue to use ‘3-4’
If ‘tunnel_qos_remap’ is enabled, the PGs ‘2-4’ will be seen instead of ‘3-4’.
A check need to be added to use ‘2-4’ if ‘SYSTEM_DEFAULTS’ has ‘tunnel_qos_remap’ enabled else continue to use ‘3-4’
Run the original case, pass with the fix while failed without the fix.
=> update queue range if qos remap enabled

ansible/vars/topo_t0-8-lag.yml
Summary:
Test failures seen due to incorrect deployment with two vlans. Modifying the topo to use single vlan
=> Update vlan topo for 16 uplink testbed

tests/memory_checker/test_memory_checker.py
Summary:
test_memory_checker failed with 202012 latest image.
The reason I didn't submit PR from master is that the master/202205 already has the fix
To update the apt-get before install. 
Run sonic-mgmt test
=> To enhance the test test_memory_checker

tests/show_techsupport/test_auto_techsupport.py
Changed logic which doing counting for free/used space to use 1Mb = 1000Kb
Originally we used logic which expected 1Mb = 1024Kb, but seems like it's wrong and we need to use 1Mb = 1000Kb
Auto-techsupport used shutil python lib to get used/free space
If we use on the same host "shutil" and "df" we will see next output:
```
>>> import shutil
>>> shutil.disk_usage('/')
usage(total=11491549184, used=5826863104, free=5057351680)
```
```
df linux utils shows next output:
[petrop@mtr-vdi-077 sonic-mgmt]$ df /
Filesystem              1K-blocks    Used Available Use% Mounted on
/dev/mapper/centos-root  11222216 5690296   4938820  54% /
```
Test used "df" in case when get total space.
If use 1Mb = 1024 Kb - in result we will have: 10 959 Mb If use 1Mb = 1000 Kb - in result we will have: 11 222 Mb …
=> [auto-techsupport] Changed logic which doing counting for free/used space to use 1Mb = 1000Kb

tests/dut_console/test_console_baud_rate.py
Summary:
If we are requested to enter username and pwd for DUT, it means that we connected to DUT from console successfully. So, it is no need to login DUT from console.
Remove login step.
Run test.
=> [console] Optimize test_console_baud_rate

tests/conftest.py, tests/snappi/qos/files/__init__.py, tests/snappi/qos/files/packet_reorder_helper.py, tests/snappi/qos/test_ipip_packet_reorder_with_snappi.py
Summary: We observed some IPinIP packets of various sizes are reordered when passing through a switch even though they belong to the same stream. As a result, this test case aims to fill this test gap by passing IPinIp packets between two ports on a traffic generator through a switch to see if the packets get re-ordered by the switch. 
Fixes (issue) #7525 
There was a customer issue in which a switch was dropping IPinIP packets of varying sizes, and no test cases to cover this scenario in which the packets were re-ordered causing customer impact. Hence, this test case aims to check for packet re-order scenarios in switches. 
Generate a sequence of packet and flow configurations and run the traffic from a traffic generator through the DUT (device under test) to see if the packets are …
=> [Snappi] Validate the IPinIP packet can be transferred without any re-order

.azure-pipelines/test_plan.py
Summary:
Fix the issue that token will be outdated after 24 hours
Fix the issue that token will be outdated after 24 hours
Refresh the token periodically.
=> [Fix] Fix the issue that token will be outdated after 24 hours

tests/pc/test_lag_member.py
Summary:
test_lag_member_traffic failed in many testbeds.
1. Add ping from ptf before run traffic test to ensure that arp table in DUT has been refreshed.
2. Split ptf/dut setup and generate, adding try/exception to avoid exception in setup period cause teardown failed.
Run tests.
```
collected 2 items                                                                                                                                                                                                                            
pc/test_lag_member.py::test_lag_member_status PASSED                                                                                                                                                                                   [ 50%] …
```
=> [portchannel] Fix test_lag_member failed

tests/ptf_runner.py
Summary:
Throw the original exception from ptf_runner to provide more information for debugging.
Throw the original exception from ptf_runner to provide more information for debugging.
Throw the original exception out. The exception info will be printed in test log when test fail.
Verified via `ipfwd/test_dir_bcast.py`.
=> [ptf_runner] Throw the original exception out

docs/testplan/Extend_L3V6ACL_test_plan.md
Summary:
Test Plan added for L3V4V6 type ACL Table
Test Plan reviewed by community on 22 March, 2023
Test plan added for L3V4V6 type ACL table
Test cases written in reference to L3V4V6 type ACL Table HLD
Steps cover the test cases from the test plan
Platform capability check for this feature will be checked before configuration
t0,t1
Link to HLD document
https://github.com/sonic-net/SONiC/blob/aac00395634ac9935d5c44493c4591f024a53742/doc/acl/Extend-L3V6ACLs.md
=> Test plan for L3V4V6 type ACL table

.azure-pipelines/test_plan.py
Summary:
Compatible with SONiC Elastictest migration
Compatible with SONiC Elastictest migration
=> [CI/CD] Compatible with SONiC Elastictest migration

.azure-pipelines/test_plan.py
Summary:
Fix the issue of refresh token doesn't work on polling
=> [Fix] Fix the issue of refresh token doesn't work on polling

tests/bgp/test_bgp_dual_asn.py
Fix test failure of test_bgp_dual_asn.py on dual-tor environment.
Summary:
Fix test failure of test_bgp_dual_asn.py on dual-tor environment.
Need apply toggle all to selected DUT, since we are testing bgp speaker's behavior, which setup interface with vlan member interface.
Also extend the waiting time after config restall.
Fix script issue
Add toggle all logic in script.
run test case on dual-tor env.
=> fix dual tor issue of test_bgp_dual_asn.py

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
[platform_tests/test_sensors.py] - case failure on Arista platform with 202205 image 
https://github.com/sonic-net/sonic-mgmt/issues/8437
[platform_tests/test_sensors.py] - case failure on Arista platform with 202205 image 
Xfail the case on Arista with 202205 image
Run original case
========================================================================================== short test summary info ==========================================================================================
XFAIL platform_tests/test_sensors.py::test_sensors
=> xfail test_sensors on Arista with 202205 image

.azure-pipelines/run-test-scheduler-template.yml, .azure-pipelines/test_plan.py
=> [CI/CD] Refine PR test templates and test_plan.py to be ready to migrate to Elastictest

tests/qos/test_tunnel_qos_remap.py
Summary:
case "test_pfc_pause_extra_lossless_standby" and "test_pfc_pause_extra_lossless_active" failed, as below:
```
try:
start_pfc_storm(storm_handler, peer_info, prio)
base_queue_count = get_queue_counter(rand_selected_dut, actual_port_name, queue, True)
testutils.send_packet(ptfadapter, src_port, pkt, 1)
testutils.verify_no_packet_any(ptfadapter, exp_pkt, dst_ports)
queue_count = get_queue_counter(rand_selected_dut, actual_port_name, queue, False)
>               pytest_assert(base_queue_count == queue_count, "The queue {} for port {} counter increased unexpectedly".format(queue, actual_port_name))
E               Failed: The queue 6 for port Ethernet124 counter increased unexpectedly
```
RCA:
performance issue of sending pfc, it cause failed to pause dut's …
=> [qos] add retry to tolerate performance issue of send pfc

tests/dhcp_relay/test_dhcpv6_relay.py
Summary:
Refactor test_dhcpv6_relay.py
1. Dual-tor and single-tor wouldn't happen in one DUT, so remove pytest params in testing_config.
2. In test_dhcp_relay_default, dual-tor skip_release has been covered by previous skip, so remove it.
3. Remove unused fixtures in testcases.
Run test in t0/dualtor/m0/mx testbeds, all passed.
=> [dhcp_relay] Refactor test_dhcpv6_relay

azure-pipelines.yml
Summary:
Migrate to SONiC Elastictest
=> [CI/CD] Migrate to SONiC Elastictest

.github/CODEOWNERS
Summary:
To assign code owner for default code reviewer based on feature sets.
Change the .github/CODEOWNERS to have owners.
N/A
=> To add code owners to have default code reviewer for testcases

tests/bgp/conftest.py
When setup bgp speaker session on m0/t0, current code choose ptf ports and configure ip with same subnets in Vlan scope. This will cause network connection issue when PTF send layer 3 packets to DUT. This PR fix this issue on single tor t0 and m0.
Summary:
Fixes unstable bgp speaker connection issue.
We use PTF to simulator DUT VLAN interface (192.168.0.1/23) neighbor, and on PTF we config:
ifconfig eth1 192.168.0.3 netmask 255.255.254.0  
ifconfig eth2 192.168.0.4 netmask 255.255.254.0  
This will generate two connected route on PTF: 
192.168.0.0/23 dev eth1 proto kernel scope link src 192.168.0.3  
192.168.0.0/23 dev eth2 proto kernel scope link src 192.168.0.4  
Then traffic to VLAN interface 192.168.0.1 will always match first connect route (5 tuple ECMP). 
So in DUT FDB table, arp …
=> fix bgp speaker connection unstable issue

.github/workflows/automerge_scan.yml, .github/workflows/pr_cherrypick_poststep.yml, .github/workflows/pr_cherrypick_prestep.yml
Summary:
Enable auto cherry pick workflow for sonic-mgmt.
=> [action] Enable auto cherry pick.

ansible/roles/fanout/templates/sonic_deploy_202012.j2, ansible/roles/fanout/templates/sonic_deploy_202205.j2
Current config for fanout is missing MGMT_PORT section, which will make dut fail yang model check.
Summary:
- [] 202012
- [] 202205
Fanout config missing MGMT_PORT
Add MGMT_PORT section
Add this part in template, run it and make sure yang check pass.
=> [ansible] add MGMT_PORT config to sonic fanout config_db

tests/common/plugins/conditional_mark/__init__.py, tests/common/plugins/conditional_mark/issue.py
Summary:
Conditional mark failed to query github issue state to decide skip/xfail behaviors due to proxy issue
Get proxies through inventory env.yml, and add proxies to requests
=> Fix conditional mark query Github failed issue

ansible/roles/fanout/templates/sonic_deploy_202012.j2, ansible/roles/fanout/templates/sonic_deploy_202205.j2
Summary:
Update SONiC fanout template to support both uppercase and lowercase in column `VlanMode`.
Update SONiC fanout template to support both uppercase and lowercase in column `VlanMode`.
Convert the string to lower case before compare.
Verified by redeploy fanout.
=> [Fanout] Update SONiC fanout template to improve robust

tests/bgp/test_bgp_fact.py
Why I did:
Cherry-pick of PR: https://github.com/sonic-net/sonic-mgmt/pull/8462
=>  Enhanced bgp_fact to validate NEIGH_STATE_TABLE element 'peerType' 

tests/generic_config_updater/gcu_field_operation_validators.conf.json, tests/generic_config_updater/gu_utils.py, tests/generic_config_updater/test_ecn_config_update.py, tests/generic_config_updater/test_incremental_qos.py, tests/generic_config_updater/test_pfcwd_interval.py
Cherry-pick PR https://github.com/sonic-net/sonic-mgmt/pull/8341 into 202205 branch, manual to resolve merge conflicts
=> [GCU E2E Testing] Update RDMA GCU E2E Tests cherry-pick into 202205

tests/qos/files/mellanox/qos_param_generator.py, tests/qos/qos_sai_base.py
Summary: Fix python3 migration issue for qos_sai and test_sub_port_l2_forwarding
Fixes # (issue) Fix the issues: https://github.com/sonic-net/sonic-mgmt/issues/7866 and https://github.com/sonic-net/sonic-mgmt/issues/7884
Fix the test failure caused by python3 migration
Run qos sai and test_sub_port_l2_forwarding, and it could pass
=> [python3_migration]Fix python3 migration issue for qos_sai and test_sub_port_l2_forwarding

tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
Summary:
Remove skip as https://github.com/sonic-net/sonic-mgmt/issues/5207 not relevant 
- [] Bug fix
Increase test coverage 
Remove skip from conditional marks
Run TC, TC passed
=> Remove skip for test_non_routable_igmp_pkts[vlan_members]

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/generic_config_updater/test_mmu_dynamic_threshold_config_update.py
After enabling docker_inram feature, test_trap_config_save_after_reboot is experiencing a hang in the nightly pipeline build. Docker_inram feature would install docker into memory instead of disk. so it would not keep the change after reboot.
Skip the case
copp/test_copp.py::TestCOPP::test_policer[str2-7050qx-32s-acs-01-ARP] PASSED [ 7%] copp/test_copp.py::TestCOPP::test_policer[str2-7050qx-32s-acs-01-IP2ME] PASSED [ 14%] copp/test_copp.py::TestCOPP::test_policer[str2-7050qx-32s-acs-01-SNMP] PASSED [ 21%] copp/test_copp.py::TestCOPP::test_policer[str2-7050qx-32s-acs-01-SSH] PASSED [ 28%] copp/test_copp.py::TestCOPP::test_no_policer[str2-7050qx-32s-acs-01-BGP] PASSED [ 35%] …
=> [cherry-pick to 202205] skip test_trap_config_save_after_reboot (#8575)

ansible/roles/fanout/tasks/fanout_sonic.yml, ansible/roles/fanout/tasks/main.yml, ansible/roles/fanout/tasks/sonic/fanout_sonic_dry_run_202205.yml, ansible/roles/fanout/tasks/sonic/fanout_sonic_incremental_202205.yml, ansible/roles/fanout/templates/sonic_deploy_incremental_202205.j2
Currently ansible deployment for fanout devices will replace old config with new. This incremental update method utilizes config apply-patch and json patch to apply config, with as little disruption to current config as possible. Changes only apply to 202205 sonic fanout deployment.
Summary:
To deploy fanout using latest sonic feature apply-patch.
Deployed some fanouts.
=> [ansible] Incremental update for fanout deployment

tests/common/plugins/conditional_mark/__init__.py
Summary:
Fix a cherry-pick issue in PR: https://github.com/sonic-net/sonic-mgmt/pull/8597
Variable used but not defined
Define variable before used
=> Fix conditional mark issue in 202012

tests/common/plugins/conditional_mark/__init__.py, tests/common/plugins/conditional_mark/issue.py
Summary:
Conditional mark failed to query github issue state to decide skip/xfail behaviors due to proxy issue
Get proxies through inventory env.yml, and add proxies to requests
Cherry-pick from PR https://github.com/sonic-net/sonic-mgmt/pull/8537
=> Fix conditional mark query Github failed issue in 202205

.azure-pipelines/test_plan.py
Summary:
compatible with 'steps' refactor in the test plan structure
- [x Testbed and Framework(new/improvement)
compatible with 'steps' refactor in the test plan structure
=> [CI/CD] compatible with 'steps' refactor in the test plan structure

tests/qos/files/qos.yml
Summary:
This PR is to fix `test_xoff_for_pcbb` for `202205` branch.
This PR is to fix `test_xoff_for_pcbb` for `202205` branch.
Update `pkts_num_trig_pfc` and `pkts_num_trig_ingr_drp` in `qos.yml`.
Verified by running `test_xoff_for_pcbb` on a dualtor testbed
```
collected 4 items                                                                                                                                                                           
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb[pcbb_xoff_1]  ^HPASSED                                                                                                                  [ 25%]
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb[pcbb_xoff_2]  ^HPASSED …
```
=> [202205] Fix pcbb xoff test

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml, tests/platform_tests/test_reboot.py
Reverts sonic-net/sonic-mgmt#8512
=> Revert "Watchdog reboot skip"

tests/saitests/sai_qos_tests.py
Summary:
encounter qos sai case failure:
```
sai_qos_tests.PFCXonTest ... ERROR
ERROR: sai_qos_tests.PFCXonTest
File \"saitests/sai_qos_tests.py\", line 1722, in runTest
1)[0][0]
File \"saitests/sai_qos_tests.py\", line 377, in get_multiple_flows
pkt_args.update({dl_vlan_enable:True})
NameError: global name 'dl_vlan_enable' is not defined
Ran 1 test in 16.703s
```
RCA:
syntax error introduced by PR https://github.com/sonic-net/sonic-mgmt/pull/8399
fix syntax error
=> fix "dl_vlan_enable is not defined"

docs/testbed/README.testbed.Keysight.md
Summary: This PR changes the url for downloading the latest IxNEtwork Web Edition Docker image file
=> Update Keysight download links 

.azure-pipelines/pr_test_scripts.yaml
Summary:
specify specific_param for macsec pr tests
=> [CI/CD,Elastictest] specify specific_param for macsec pr tests

.azure-pipelines/pr_test_scripts.yaml
Approach
specify specific_param for macsec pr tests
Summary:
=> [CI/CD,Elastictest] specify specific_params for macsec pr tests (#8667)

.azure-pipelines/pr_test_scripts.yaml
Summary:
Enable warm reboot test on 202012 kvm
Test on ElasticTest
https://elastictest.org/scheduler/testplan/6495b855a63f1ce5ce9b0744
(https://www.testbed-tools.org/scheduler/testplan/6493392669af2f12866fa306)
=> [202012] Enable test_warm_reboot in PR check

.azure-pipelines/pr_test_scripts.yaml
Summary: Enable warm reboot kvm test
Enable warm reboot test on 202205 kvm
Test on Elastic test run
https://elastictest.org/scheduler/testplan/6495b7cd75768730ce0de83b
=> [202205] Enable warm reboot test

.azure-pipelines/test_plan.py
Summary:
create test plan with new data structure
=> [CI/CD,Elastictest] create test plan with new data structure

.azure-pipelines/run-test-scheduler-template.yml, azure-pipelines.yml
Summary:
t0-sonic's specific params has been set on sonic-mgmt repo, remove useless SPECIFIED_PARAMS usage
=> [CI/CD] refine t0 sonic test definition

tests/pfcwd/test_pfcwd_function.py
Summary:
PFCWD case failure during verifion
update rx_action of pfcwd for the device which enabled tunnel_qos_remap
Run original failure case.
devices which enabled tunnel_qos_remap
=> update rx_action of pfcwd for the device which enabled tunnel_qos_remap

azure-pipelines.yml
Summary:
Comment wan test job since SONiC WAN project had been postponed
=> [CI/CD] comment wan test job

.azure-pipelines/pr_test_scripts.yaml
Summary: Enabled warm_reboot test in master PR check
Warm reboot test was previously disabled in PR checks due to failures. Enable check now the test is passing
Running PR check
=> Enable warm_reboot test in PR tests

tests/configlet/test_add_rack.py, tests/configlet/util/common.py
ADO 24290402
Summary: Skip clet test in configlet test.
The clet test fail when comparing DATAACL. It is a hidden issue that the comparison should fail whereas it succeeds.
Skip clet test.
E2E test.
=> [test_add_rack] Skip clet test

tests/common/dualtor/mux_simulator_control.py
Summary:
Use toggle function with mux direction check.
Run dualtor-io testcases.
=> [dualtor] Add mux direction checks to toggle fixtures

tests/qos/test_tunnel_qos_remap.py
Summary:
Fix the following issue, it only happened in py3 env, not for py2.
The error is introduced by https://github.com/sonic-net/sonic-mgmt/pull/8317
```
==================================== ERRORS ====================================
________________ ERROR collecting qos/test_tunnel_qos_remap.py _________________
ImportError while importing test module '/azp/_work/43/s/tests/qos/test_tunnel_qos_remap.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
qos/test_tunnel_qos_remap.py:27: in <module>
from tunnel_qos_remap_base import leaf_fanout_peer_info, start_pfc_storm, \
E   ModuleNotFoundError: No module named …
```
=> Fix import error in test_tunnel_qos_remap for py3 env

tests/bgp/test_bgp_bbr.py
Cherry-Pick https://github.com/sonic-net/sonic-mgmt/pull/7897 into 202205
Summary:
Cherry-Pick https://github.com/sonic-net/sonic-mgmt/pull/7897 into 202205
=> [Cherry Pick] PR#7897, fix connection issue in test_bgp_bbr into 202205 

tests/common/plugins/sanity_check/recover.py
we tries to find internal interfaces and if any is down, do config reload. in https://github.com/sonic-net/sonic-mgmt/pull/6076 Here `pn` is already all lowercases, we need to change keyword to lowercase as well, or the keyword will never be found.
Summary:
=> [MASIC] [chassis] change internal interfaces keywords to lowercase search in sanity check

tests/generic_config_updater/test_vlan_interface.py
Summary:
m0-2vlan topo will encounter below three error log in syslog and causes test failure.
```
E               Jul  6 03:47:21.431315 bjw-can-720dt-4 ERR swss#intfmgrd: :- setIntfIp: Command '/sbin/ip -6 address "add" "fc02:1000::1/64" broadcast "fc02:1000::ffff:ffff:ffff:ffff" dev "Vlan1000"' failed with rc 2
E              
E               Jul  6 03:48:27.764302 bjw-can-720dt-4 ERR bgp#bgpcfgd: Directory: Can't remove key 'fc02:1000::1' from slot 'LOCAL__local_addresses'. The key doesn't exist
E              
E               Jul  6 03:48:27.765925 bjw-can-720dt-4 ERR swss#intfmgrd: :- setIntfIp: Command '/sbin/ip -6 address "del" "fc02:1000::1/64" broadcast "fc02:1000::ffff:ffff:ffff:ffff" dev "Vlan1000"' failed with rc 2
```
After investigated, find that first log …
=> [m0][gcu] Fix log analyzer error in gcu/test_vlan_interface

tests/voq/test_voq_nbr.py
**Cherry-Pick PR** for 202205 from master #8313 
Summary:
- voq/test_voq_nbr.py test cases 'test_neighbor_hw_mac_change' and 'test_gratarp_macchange'
- Above two test cases fail for IPV4 neighbor case where the neighbor MAC is not changed in DUT's arp table.
- This PR also contains timeout fix for the issue https://github.com/sonic-net/sonic-mgmt/issues/8671.
- This PR helps to fix 'test_neighbor_hw_mac_change' and 'test_gratarp_macchange' voq-nbr test cases.
- Tests fail for IPV4 neighbor, when its mac change is not updated in the DUT's arp table.
- _ping_all_local_nbrs parallel processes get completed faster for smaller chassis.
- For bigger DUTs like (400G T2 max/100G T2 max), it takes more than ~4 minutes.
- For test_neighbor_hw_mac_change, by doing neighbor …
=> [cherry-pick] [PR:8313] [chassis][voq] Fixes for voq_nbr test failures (#8313)

tests/qos/tunnel_qos_remap_base.py
Summary:
Need to increase timeout for tunnel_qos_remap.
As below, encountered timeout failure:
```
"======================================================================",
"ERROR: sai_qos_tests.TunnelDscpToPgMapping",
"----------------------------------------------------------------------",
"Traceback (most recent call last):",
"  File \"saitests/py3/sai_qos_tests.py\", line 1075, in runTest",
"    time.sleep(8)",
"  File \"/root/env-python3/lib/python3.7/site-packages/ptf/ptfutils.py\", line 110, in raise_timeout",
"    raise Timeout.TimeoutError()",
"ptf.ptfutils.Timeout.TimeoutError",
"",
"----------------------------------------------------------------------",
"Ran 1 test in 600.007s",
"",
```
increase ptf timeout to 1200 to align with other qos sai cases' ptf timeout …
=> increase ptf timeout for tunnel_qos_remap

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/8833
Raise a new PR manually to solve the conflict.
=> [202205]Fix wrong build_version comparison condition

tests/conftest.py
There is a conflict when cherry pick PR (https://github.com/sonic-net/sonic-mgmt/pull/8744) into 202012 branch, so raise this PR to cherry pick.
Summary:
There is a conflict when cherry pick PR (https://github.com/sonic-net/sonic-mgmt/pull/8744) into 202012 branch, so raise this PR to cherry pick.
=> [202012]Add a function to compare running config.

tests/conftest.py, tests/test_posttest.py, tests/test_pretest.py
Sync function core_dump_and_config_check with master branch.
Summary:
Sync function core_dump_and_config_check with master branch
=> [202205]Sync function core_dump_and_config_check with master branch.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/8833
Raise a new PR manually to solve the conflict.
=> [202012]Fix wrong build_version comparison condition

tests/configlet/test_add_rack.py
Summary: Skip clet test in configlet test. Backport PR of https://github.com/sonic-net/sonic-mgmt/pull/8665
=> [202205][test_add_rack] Skip clet test

.azure-pipelines/test_plan.py
Summary:
Enhance test plan script to additionally check test plan result, this feature is to support run to the end in pr test.
=> [Elastictest] enhance test plan script to additionally check test plan result

tests/qos/tunnel_qos_remap_base.py
Summary:
double commit PR https://github.com/sonic-net/sonic-mgmt/pull/8861 to branch 202205
Need to increase timeout for tunnel_qos_remap.
As below, encountered timeout failure:
```
"======================================================================",
"ERROR: sai_qos_tests.TunnelDscpToPgMapping",
"----------------------------------------------------------------------",
"Traceback (most recent call last):",
"  File \"saitests/py3/sai_qos_tests.py\", line 1075, in runTest",
"    time.sleep(8)",
"  File \"/root/env-python3/lib/python3.7/site-packages/ptf/ptfutils.py\", line 110, in raise_timeout",
"    raise Timeout.TimeoutError()",
"ptf.ptfutils.Timeout.TimeoutError",
"",
"----------------------------------------------------------------------",
"Ran 1 test in 600.007s", …
```
=> [qos][double commit][202205] increase ptf timeout for tunnel_qos_remap

ansible/module_utils/port_utils.py, tests/common/devices/sonic_asic.py
What I did:
Cherry Pick of Master PR #8790, #8736, #8898 into 202205.
How I verify:
Manual Verification
=> Cherry Pick of Master PR #8790, #8736, #8898

tests/route/test_route_flow_counter.py
Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/8724
Missed topology mark
Added topology mark "any"
Run both t0/t1. TC passed
=> Added missed topo mark for test_route_flow_counters

tests/crm/test_crm.py
Modified the test script to fix the issue because of PR: https://github.com/sonic-net/sonic-mgmt/pull/7816"
Summary:
- [ x] Bug fix
- [ x] 202205
Modified the test script to fix the issue because of PR: https://github.com/sonic-net/sonic-mgmt/pull/7816"
crm/test_crm.py::test_acl_entry[str-marvell-acs-1-None] PASSED
Yes
=> Modified the test script to fix the issue because of PR: 7816

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
remove duplicated skip condition for test_sai_sdk_dump
remove duplicated skip condition
=> remove duplicated skip condition for test_sai_sdk_dump

.azure-pipelines/run-test-scheduler-template.yml, .azure-pipelines/test_plan.py, azure-pipelines.yml
Summary:
Support to set kvm_image_branch in the test plan
=> [CI/CD] Support to set kvm_image_branch in the test plan

tests/bgp/test_bgp_bbr.py
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/7897 into 202012
Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/7897 into 202012
=> [cherry pick] #7897 fix connection issue in test_bgp_bbr into 202012

tests/minigraph/test_masked_services.py
TC `test_masked_services` aims to mask telemetry service, then test load_minigraph and check its success. But loading minigraph will change running config, and will be caught by fixture core_dump_and_config_check and do config reload in teardown period. In order to avoid config reload by fixture core_dump_and_config_check, in this PR, we do config reload after test case running and restore the running config. 
Summary:
TC `test_masked_services` aims to mask telemetry service, then test load_minigraph and check its success. But loading minigraph will change running config, and will be caught by fixture core_dump_and_config_check and do config reload in teardown period. In order to avoid config reload by fixture core_dump_and_config_check, in this PR, we do config reload …
=> Add config reload at the end of TC `test_masked_services`

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
double commit PR https://github.com/sonic-net/sonic-mgmt/pull/8241
and remove duplicated rule 
double commit PR#8241
and remove duplicated rule
=> [double commit][PR#8241]update skip rule of test_check_sfputil_low_power_mode for cisco-8000, and remove duplicated rule

.azure-pipelines/pytest-collect-only.yml, .azure-pipelines/run-test-scheduler-template.yml, azure-pipelines.yml, tests/fdb/test_fdb_mac_move.py, tests/ssh/conftest.py, tests/vtestbed.yaml
Summary:
Enable PR test on 202012 branch
=> [202012, CI/CD] Enable PR test

spytest/Doc/intro.md
SPyTest Documentation Update
Summary:
Add feature details and clarity on existing features
Re-Write the documentation with more details
Re-Write the documentation with more details
N/A
N/A
N/A
=> SPyTest Documentation Update

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_match.txt
Should not ignore all err matched "kernel:.*atomic"
Change-Id: Ifb71dd1e48310075f09ea208e6f0b21019ecba74
Summary: Should not ignore all err matched "kernel:.*atomic"
Somtimes there would be following log msgs present in the syslog, but the log msgs are not err msg, in the current logic they are treated as err msgs due to they will match "kernel:.*atomic" defined in ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_match.txt, this is not reasonable. if some some specific msg should which match  "kernel:.*atomic" should be ignored, they can be added in the tests/common/plugins/loganalyzer/loganalyzer_common_ignore.txt
_2023-06-29T04:48:41.083717+00:00 sonic kernel: [    0.147146] DMA: preallocated 2048 KiB GFP_KERNEL pool for atomic allocations …
=> Update the regex used in the loganalyzer

tests/saitests/sai_qos_tests.py
Summary:
observed lots console log in qos sai test:
```
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => 3, src_ip:192.0.0.249 dstip:192.168.0.5",
"Trying 2 => …
```
=> fix huge console log generated by get_multiple_flows

tests/show_techsupport/test_auto_techsupport.py
Summary:
This PR is to stabilize test cases in `test_auto_techsupport.py`.
The changes include
- Skip `restapi` docker in test
- Get existing tech support files before triggering the auto techsupport.
Besides, the `test_sai_sdk_dump` can fail if `syncd` is not started with TEMP_VIEW enabled. That can happen if the last reboot is fast-reboot. The fix is not included in this PR.
This PR is to stabilize test cases in `test_auto_techsupport.py`.
- Skip `restapi` docker in test
- Get existing tech support files before triggering the auto techsupport.
The change is verified on a 2700 T0 testbed
```
collected 5 items …
```
=> Stabilize auto techsupport test

tests/common/plugins/sanity_check/checks.py
Summary:
Cherry-pick #7937 into 202205 branch
=> Probe mux cable when sanity check fails in show mux status (#7937)

ansible/roles/fanout/templates/sonic_mlnx_copp_cfg.j2
Fix bug with mlnx fanout deploy template bug
Summary:
Bug fix
Bug fix
Deploy fanout
=> fix bug with mlnx fanout deploy template

tests/platform_tests/test_advanced_reboot.py
Summary: test missing import random
Add missing import
=> Add import random to test_advanced_reboot

tests/configlet/test_add_rack.py, tests/configlet/util/base_test.py, tests/configlet/util/configlet.py, tests/configlet/util/generic_patch.py, tests/configlet/util/mock_for_switch.py, tests/configlet/util/run_test_in_switch.py, tests/configlet/util/strip.py
Summary:
Fix the import issue of test_add_rack.py
Fix the import issue of test_add_rack.py
PR test verify.
=> [Fix, 202205] Fix import issue of test_add_rack.py 

.azure-pipelines/pr_test_scripts.yaml, tests/configlet/test_add_rack.py, tests/configlet/util/base_test.py, tests/configlet/util/common.py, tests/configlet/util/configlet.py, tests/configlet/util/generic_patch.py, tests/configlet/util/mock_for_switch.py, tests/configlet/util/run_test_in_switch.py, tests/configlet/util/strip.py
=> [Fix, 202012] Fix import issue of test_add_rack.py

ansible/module_utils/dualtor_utils.py, ansible/roles/vm_set/library/vm_topology.py
Summary:
This is manually cherry-pick PR #9080 
testbed-cli.sh should modify to be compatible with both Python2 and Python3.
Use six package to deal with str/unicode error: 'str' object has no attribute 'decode'
Work around with a kernel issue: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1811241.html
With physical testbed, we can remove-topo, add-topo and deploy-mg.
=> Modify testbed-cli.sh to adapt upcoming new sonic-mgmt-docker with PY3 as default

spytest/vsnet/autorun.sh, spytest/vsnet/requirements.sh, spytest/vsnet/sonic_import_img.sh, spytest/vsnet/test.sh, spytest/vsnet/vsnet
vsnet tool to create network of virtual sonic instances
Summary:
VSNet is an efficient tool that simplifies the process of creating virtual instances of the SONiC operating system within a controlled environment and connecting them based on the specified network topology.
To simplify sonic-vs network creation and execute test scripts
details in [HLD](https://github.com/sonic-net/sonic-mgmt/blob/master/spytest/Doc/vsnet.md)
Execute vsnet command as described in the HLD
sonic-vs
NA
[HLD](https://github.com/sonic-net/sonic-mgmt/blob/master/spytest/Doc/vsnet.md)
=> VSNet Virtual Sonic Helper

.azure-pipelines/run-test-elastictest-template.yml, .azure-pipelines/test_plan.py, azure-pipelines.yml
Add new pr test template: run-test-elastictest-template.yml. Use it as the sole template for referencing by other repositories.
Currently, there are several repos and too many branches enabled PR test by Elastictest, but they all maintained their own PR test template file, which caused extra effort to develop and maintain. So, this change adds a new PR test template file and use it as the sole template for referencing by other repositories
Add run-test-elastictest-template.yml and modify test job template to use it for PR pipelines.
PR test executing normally. Because other repos will refer to this template as resource, we could not verify its adaptation for all situations in single PR. So we keep the original template file until all …
=> [CI/CD] Use new pr test template: run-test-elastictest-template.yml.

azure-pipelines.yml
Use remote PR test template from sonic-mgmt master to run PR test.
Use remote PR test template from sonic-mgmt master to run PR test.
Modify PR test azure pipeline yml file.
PR test executing normally.
=> [202012，CI/CD] Use remote PR test template from sonic-mgmt master to run PR test

azure-pipelines.yml
Use remote PR test template from sonic-mgmt master to run PR test.
Use remote PR test template from sonic-mgmt master to run PR test.
Modify PR test azure pipeline yml file.
PR test executing normally.
=> [202205, CI/CD] Use remote PR test template from sonic-mgmt master to run PR test

tests/memory_checker/test_memory_checker.py
Compare config fails in module `memory_checker/test_memory_checker.py` because the error
```
mv: cannot stat '/tmp/monitrc': No such file or directory
```
which is generated by function `test_setup_and_cleanup` in teardown period. And this error will block the execution of the following functions, which will recovery the testbed. The lack of these functions will cause the running config change on dut, and will cause reload by fixture `core_dump_and_config_check`. In this PR, I add a try-finally structure to ensure that these recovery functions will be executed no matter if the above function is success. 
Summary:
Compare config fails in module `memory_checker/test_memory_checker.py` because the error
```
mv: cannot stat '/tmp/monitrc': No such file or directory
```
which …
=> Restart container no matter if restore monit config files is success in module `memory_checker/test_memory_checker.py`.

tests/pfcwd/conftest.py, tests/pfcwd/test_pfcwd_function.py
What I did:
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/8859 inro 202205.
=> [202205] [Cherry-pick] Master PR #8859

.azure-pipelines/get_dut_version.py, .azure-pipelines/upgrade_image.py, ansible/TestbedProcessing.py, ansible/devutils, ansible/files/check_testbed_and_inventory_file.py, ansible/files/creategraph.py, ansible/health_checker.py, ansible/linkstate/testbed_inv.py, ansible/recover_server.py, ansible/restart_nightly_ptf.py, ansible/upgrade_sonic.py
Summary:
This is a part of Python3 migration. The incoming new sonic-mgmt-docker will set Python3 as default.
Old branch will use Python2 explicitly.
This is a part of Python3 migration. The incoming new sonic-mgmt-docker will set Python3 as default.
Old branch will use Python2 explicitly.
1. In tool scripts, add head: #!/usr/bin/env python2
2. In any caller of tool scripts, use "./" to call the scripts.
N/A
=> Change tool scripts to use Python2 explicitly

tests/telemetry/events/swss_events.py, tests/telemetry/test_events.py
Summary:
Add if_state, pfc_storm, chk_crm_threshold swss test to nightly test
Added new test case for test_events
Pipeline, manual testing
=> Add swss events to test_events

azure-pipelines.yml
Enable PR test on branch 202305.
Enable PR test on branch 202305.
Modify PR test azure pipeline yml file.
PR test executing normally.
=> [CI/CD] Enable PR test on 202305

ansible/group_vars/sonic/variables, tests/qos/qos_sai_base.py
Qos-sai script run enablement on cisco-8111 platform
Qos-sai script run enablement on cisco-8111 platform
=> Qos enablement cisco-8111 platform

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
https://github.com/sonic-net/sonic-mgmt/issues/9201
Xfail advanced reboot due to known issue.
Skip test_bgp_slb_neighbor_persistence_across_advanced_reboot on dual tor since it got stuck during warm reboot due to known issue on master and internal image.
Run tests/platform_tests/test_advanced_reboot.py
Run bgp/test_bgp_slb.py::test_bgp_slb_neighbor_persistence_across_advanced_reboot on dualtor testbed.
=> Xfail advanced reboot due to known issue

tests/telemetry/events/bgp_events.py, tests/telemetry/events/event_utils.py, tests/telemetry/events/eventd_events.py, tests/telemetry/events/host_events.py, tests/telemetry/events/run_events_test.py, tests/telemetry/telemetry_utils.py, tests/telemetry/test_events.py
Summary:
Add events from host to nightly test such as disk-usage, space-usage, memory-usage, kernel events, mem threshold exceeded
Code change 
Explanation about wait_until  for is_gnmi_cli_finished(duthost) inside run_events_test:
The idea is that in between tests, eventd stops/starts caching events. When gnmi client connects and starts listening for events, eventd will drain cache and no longer cache events, as events will now be sent directly to client. Once client disconnects, events will start being cached again until next client connect. In between tests, we wait for eventd to start caching by looking for log 'Set heartbeat_ctrl pause=1'.
If we see this log, we can be sure that we can move on to next test case. Or if we do not see due to excessive logs as you …
=> Add host events to test_events

tests/snmp/memory.py
Summary:
24450772
In a low memory device, the case would be failed due to no enough memory for the big list.
use chunk instead of big list to avoid memory corrption.
Run the memory.py
Platform with low memory
=> [snmp-memory] use chunk instead of big list to avoid memory corruption in low memory device

tests/common/fixtures/duthost_utils.py, tests/common/helpers/portchannel_to_vlan.py, tests/fdb/test_fdb.py
Summary:
Fixes # 8730
BSL test failed for key error.
Update related test for BSL mode.
Run related test.
=> Fix bsl test

ansible/TestbedProcessing.py, ansible/config_sonic_basedon_testbed.yml, ansible/library/test_facts.py, ansible/linkstate/testbed_inv.ini, ansible/recover_server.py, ansible/roles/test/tasks/sonic.yml, ansible/testbed-cli.sh, ansible/upgrade_sonic.yml, tests/run_tests.sh
Summary:
In most cases, we use testbed.yaml as default testbed file
Set the default testbed file to testbed.yaml
Run test
=> Use testbed.yaml as default testbed file

tests/crm/templates/acl.json, tests/crm/test_crm.py
Cherry pick conflict #9199
Summary:
Cherry pick conflict #9199
=> [cherry pick] #9199 Recover default acl rules if necessary in module `crm/test_crm.py` in 202012

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/9209
=> [202012]Skip test_module for non T2 topology

tests/telemetry/test_telemetry.py
Cherry pick conflict #9168 
Summary:
Cherry pick conflict #9168
=> [cherry pick] #9168 Recover telemetry settings when error happens in module telemetry/test_telemetry.py in 202205

.azure-pipelines/test_plan.py
Remove unused filed `secrets` in test plan creating. Because these variables could be obtained from environments.
Remove unused filed `secrets` in test plan creating.
Modify `test_plan.py`.
Test plan creating normally in PR testing.
=> [master][CI/CD] Remove unused filed secrets in test plan creating

tests/acl/test_acl_outer_vlan.py
Summary:
MX doesn't have portchannel, which would cause failure in this case. This PR is to fix this problem.
Modify the method of getting upstream neighbor port.
Run tests in m0/mx/t0 physical testbeds, all passed.
=> [mx][acl] Fix test_acl_outer_vlan failed at mx

tests/common/fixtures/duthost_utils.py, tests/common/helpers/portchannel_to_vlan.py, tests/fdb/test_fdb.py
Summary:
Fixes #8730
This PR is used to cherry pick below PR to 202205 branch:
https://github.com/sonic-net/sonic-mgmt/pull/9254
BSL test failed for key error.
Update related test for BSL mode.
Update related test for BSL mode.
=> Fix bsl test for 202205

ansible/roles/test/files/ptftests/py3/copp_tests.py, tests/copp/test_copp.py
Summary:
Migrate test_copp 's PTF script to Python3.
This is part of sonic-mgmt Python3 migraiton project.
This PR migrates test_copp 's PTF script to Python3.
Use 2to3 and manually change code.
Run testcase on physical testbed.
=> [PTF python3 migration] Modify test_copp PTF script

ansible/roles/test/files/ptftests/advanced-reboot.py
Summary: Due to FDB flush issue t1->server traffic gets flooded after APPLY_VIEW. Reduce the flooding duration by generating traffic from all servers.
Without this fix:
Total capture packets are >10x the amount of packets sent.
```
2023-07-30 00:36:52 : Total sent packets by sender: 33982
2023-07-30 00:40:45 : Number of all packets captured: 348058
2023-07-30 00:48:29 : Packet flow examine finished after 0:07:41.452730
```
With this fix:
Total capture packets are <3x the amount of packets sent.
```
2023-08-01 08:57:38 : Total sent packets by sender: 33306
2023-08-01 08:58:36 : Number of all packets captured: 90479
2023-08-01 09:01:11 : Packet flow examine finished after 0:02:31.662552
```
Due to less number of packets captured, the pcap collection and analysis time is …
=> [advanced-reboot] Enhance server->t1 IO to generate traffic from all servers

tests/vxlan/test_vxlan_ecmp.py
This commit fixes adds the following.
1) import copy module being used by test_vxlan_ecmp.
2) Log Analyzer ignore for  **ERR swss#orchagent: :- doTask: Logic error: basic_string** .
Summary:
ADO : 24786677, 24787472
=> fixed bugs causing failures.

tests/common/plugins/conditional_mark/tests_mark_conditions_acl.yaml
Summary:
Test parameters are changed by this PR: https://github.com/sonic-net/sonic-mgmt/pull/9334, so we need to modify condition mark too.
Optimize acl xfail condition.
Run tests.
=> [acl] Optimize acl xfail condition

tests/saitests/py3/sai_qos_tests.py
Summary:
test hang when run xon case on non-cisco8000 platform.
RCA:
infinite loop for getting traffic streams in get_multiple_flows()
- Limit infinite loop for traffic streams to 200 iterations
- revert changes of PR https://github.com/sonic-net/sonic-mgmt/pull/8500 for xon case part
for cisco-8000:   (vms61-t1-8101-02)
```
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_1] PASSED [  8%]
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_2] PASSED [ 16%]
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_3] SKIPPED [ 25%]
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_4] SKIPPED [ 33%]
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_dut_multi_asic-xon_1] …
```
=> run XON case hang for non-cisco8000 platform

tests/saitests/py3/sai_qos_tests.py
Double commit https://github.com/sonic-net/sonic-mgmt/pull/9038
Summary:
=> Double commit #9038 update BufferPoolWatermarkTest for cisco-8000 hbm

ansible/roles/test/files/ptftests/advanced-reboot.py
In the device where logs are in tmpfs, a backup is made for log_analyzer to work after reboot. However, there have been many cases when one or more backup files are empty or not created. Based on current RCA this happens when reboot CLI is executed from test and then SSH command times out.
When command execution ends, but reboot is still in progress in the device, any writes to stdout / etderr fails as there is no reader.
To fix no reader issue, run the reboot CLI w/ nohup and redirect the output to a file.
Tested on physical device
Summary:
=> [cherry-pick][202012][advanced-reboot] Use nohup when executing reboot CLI to prevent PIPE errors

ansible/roles/test/files/ptftests/py3/pfc_wd.py, tests/pfcwd/test_pfcwd_function.py, tests/pfcwd/test_pfcwd_warm_reboot.py
Summary:
Migrate test_pfcwd PTF script to Python3
This PR migrate test_pfcwd PTF script to Python3.
2to3 and manually code change
Run with phsycial testbed
=> [PTF python3 migration] Modify test_pfcwd PTF script

.azure-pipelines/run-test-elastictest-template.yml, .azure-pipelines/test_plan.py
Summary:
Allow to not pass topo parameter
Allow to not pass topo parameter
=> [Elastictest] Allow to not pass topo parameter

tests/iface_loopback_action/iface_loopback_action_helper.py
Summary:
This PR is to fix test cases in `iface_loopback_action.py`
The error message is
```
tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{"changed": true, "cmd": "sudo ip neigh replace 11.0.0.10 lladdr b'd2:dd:9d:31:61:19' dev Ethernet104", "delta": "0:00:00.023903", "end": "2023-08-06 16:26:19.266103", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2023-08-06 16:26:19.242200", "stderr": "\"bd2\" is invalid lladdr.", "stderr_lines": ["\"bd2\" is invalid lladdr."], "stdout": "", "stdout_lines": [], "warnings": ["Consider using 'become', 'become_method', and 'become_user' rather than running sudo"]}
```
It's a python3 issue.
This PR is to fix test cases in `iface_loopback_action.py`
decode the bytes to string.
Verified on a SN4600 …
=> Fix iface_loopback_action test

tests/snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py
Summary: Cherry-pick from PR #8800 
Ran test on lab DUT, and see that containers restart correctly.
=> [202205][Snappi] Config reload to stabilize DUT after container restart

spytest/utilities/common.py, spytest/utilities/ctrl_chars.py, spytest/utilities/excel.py, spytest/utilities/exceptions.py, spytest/utilities/inet.py, spytest/utilities/json_helpers.py, spytest/utilities/parallel.py, spytest/utilities/rest.py, spytest/utilities/services.py, spytest/utilities/tracer.py, spytest/utilities/utils.py
=> spytest pre-commit warnings fix in utilities

spytest/spytest/main.py, spytest/utilities/profile.py
=> utility to start and stop profiling

spytest/datastore/prompts/Prompts_Support.md, spytest/spytest/batch.py, spytest/spytest/cmdargs.py, spytest/spytest/ordyaml.py, spytest/spytest/template.py, spytest/spytest/testbed.py, spytest/spytest/tgen/tgen_utils.py, spytest/spytest/tgen_api.py, spytest/tests/batch/test_spytest_infra_1.py
=> spytest pre-commit warnings fix in framework and use caching

spytest/apis/common/hooks.py, spytest/apis/common/sonic_features.py, spytest/apis/common/sonic_hooks.py, spytest/apis/common/sonic_prompts.py
=> refactor hooks as sonic hooks to support additional types

spytest/apis/common/__init__.py, spytest/apis/common/hooks.py, spytest/apis/common/init.py, spytest/apis/common/sonic_config.py, spytest/apis/common/sonic_features.py, spytest/apis/common/sonic_hooks.py, spytest/apis/common/sonic_prompts.py, spytest/apis/common/wait.py
=> Spytest 2.2 feature apis common hooks base config

spytest/apis/common/__init__.py, spytest/apis/common/hooks.py, spytest/apis/common/init.py, spytest/apis/common/linux_hooks.py, spytest/apis/common/linux_prompts.py, spytest/apis/common/sonic_config.py, spytest/apis/common/sonic_features.py, spytest/apis/common/sonic_hooks.py, spytest/apis/common/sonic_prompts.py, spytest/apis/common/wait.py
=> Spytest 2.2 feature apis common hooks linux

.azure-pipelines/run-test-elastictest-template.yml
Summary:
Refine the parameter input, explicitly designate value
Refine the parameter input, explicitly designate value
Refine the parameter input, explicitly designate value
PR test will cover it
=> [Refine] Refine Elastictest template

spytest/vsnet/vsnet
=> spytest pre-commit warnings fix in vsnet

spytest/spytest/access/linux_connection.py, spytest/spytest/access/netmiko_connection.py, spytest/spytest/access/paramiko_connection.py, spytest/spytest/access/utils.py
=> spytest pre-commit warnings fix in device access

spytest/apis/common/__init__.py, spytest/apis/common/hooks.py, spytest/apis/common/init.py, spytest/apis/common/linux_hooks.py, spytest/apis/common/linux_prompts.py, spytest/apis/common/poe_hooks.py, spytest/apis/common/poe_prompts.py, spytest/apis/common/sonic_config.py, spytest/apis/common/sonic_features.py, spytest/apis/common/sonic_hooks.py, spytest/apis/common/sonic_prompts.py, spytest/apis/common/wait.py
=> Spytest 2.2 feature apis common hooks poe

spytest/apis/common/__init__.py, spytest/apis/common/hooks.py, spytest/apis/common/init.py, spytest/apis/common/linux_hooks.py, spytest/apis/common/linux_prompts.py, spytest/apis/common/poe_hooks.py, spytest/apis/common/poe_prompts.py, spytest/apis/common/sonic_config.py, spytest/apis/common/sonic_features.py, spytest/apis/common/sonic_hooks.py, spytest/apis/common/sonic_prompts.py, spytest/apis/common/support.py, spytest/apis/common/wait.py
=> Spytest 2.2 feature apis common tech support

tests/qos/files/qos_params.gb.yaml
Double commit gb qos yml file to 202305.
Summary:
=> qos.yml update for gb topo-t2 and longlink

tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py
Double commit https://github.com/sonic-net/sonic-mgmt/pull/8546
testQosSaiPGDrop is cisco only case, make it same as 202205 branch.
Summary:
=> Double commit #8546 add overflow_egress for PGDropTest multi-asic

tests/platform_tests/broadcom/files/ser_injector.py
Summary:
Cherry-pick 9309
Cherry-pick 9309
Cherry-pick 9309
Cherry-pick 9309
TH2
=> [202205] update ser timeout ignore memory for th2

tests/ixia/README.md
Summary: Fix URL link to snappi directory since being renamed to `snappi_tests`. 
- [] 201911
=> [Ixia] Update README.md

tests/snappi_tests/pfc/files/helper.py
Summary: PR 8661 (validating PFC frames) introduced an unwanted indent which resulted in a `local variable referenced before assignment` error. This PR resolves that issue. 
Bug fix. 
On nightly testbed.
=> [Snappi] Update PFC helper for bug fix

ansible/roles/test/files/ptftests/py3/pfc_wd.py, tests/pfcwd/test_pfcwd_function.py, tests/pfcwd/test_pfcwd_warm_reboot.py
Summary:
Manually cherry-pick #9358
Migrate test_pfcwd PTF script to Python3
=> [202205][PTF python3 migration] Modify test_pfcwd PTF script

ansible/roles/test/files/ptftests/py3/populate_fdb.py, tests/common/fixtures/populate_fdb.py
Summary:
Manually cherry-pick #9405
Migrate populate_fdb PTF script to Python3
=> [202205][PTF python3 migration] Modify populate_fdb PTF script

tests/vlan/test_host_vlan.py
Summary:
This PR is to fix a code bug in `test_host_vlan.py`.
The fixture `setup_host_vlan_intf_mac` changed the MAC address of `Vlan1000` but didn't restore it.
That results in test failure in `test_interfaces.py`
```
def verify_mac_address(host_facts, intfs, router_mac):
for intf in intfs:
if 'attachto' in intf:
ifname = intf['attachto']
else:
ifname = intf['name']
pytest_assert(host_facts[ifname]['macaddress'].lower() == router_mac.lower(), \
>                   "interface {} mac address {} does not match router mac {}".format(ifname, host_facts[ifname]['macaddress'], router_mac))
E           Failed: interface Vlan1000 mac address 1c:34:da:bb:84:ff does not match router mac 1c:34:da:bb:84:00
```
This PR fixed the issue by restoring the MAC address in the teardown of fixture …
=> Restore the MAC address of VLAN at the end of test_host_vlan

ansible/roles/test/files/ptftests/py3/copp_tests.py, tests/copp/test_copp.py
Summary:
Manually cherry-pick #9326
Migrate test_copp 's PTF script to Python3.
=> [202205][PTF python3 migration] Modify test_copp PTF script

ansible/roles/test/files/ptftests/py3/voq.py, tests/voq/test_voq_ipfwd.py, tests/voq/test_voq_nbr.py
Summary:
Manually cherry-pick #9449
Migrate test_voq_nbr and test_voq_ipfwd PTF script to Python3
=> [202205][PTF python3 migration] Modify test_voq_nbr and test_voq_ipfwd PTF script

spytest/templates/index
=> spytest textfsm template changes-1

ansible/roles/test/files/ptftests/py3/fg_ecmp_test.py
Summary:
Fixed flaky failure issue on fg_ecmp tests
We have flaky failure on fg_ecmp tests.
Increase the max_deviation and add retry on creat_flows to reduce the flaky failure rate on fg ecmp tests.
Verified on tests. The failure rate is significantly reduced.
=> enhance ecmp tests

ansible/roles/test/files/ptftests/py3/vxlan_traffic.py, tests/vxlan/test_vxlan_ecmp.py
Summary:
Migrate test_vxlan_ecmp PTF script to Python3
This PR migrate test_vxlan_ecmp PTF script to Python3.
2to3 and manually code change
N/A due to no test run internally
=> [PTF python3 migration] Modify test_vxlan_ecmp PTF script

ansible/roles/test/files/ptftests/py3/utilities.py, ansible/roles/test/files/ptftests/py3/wr_arp.py, tests/arp/test_wr_arp.py
Summary:
Migrate test_wr_arp PTF script to Python3
This PR migrate test_wr_arp PTF script to Python3.
2to3 and manually code change
N/A
=> [PTF python3 migration] Modify test_wr_arp PTF script

tests/qos/files/qos_params.spc3.yaml
Summary:
This PR is to add qos params for topology `dualtor-64`.
The arguments are copied from `topo-dualtor`. 
This PR is to add QoS param for topology dualtor-64.
Copy the QoS param of topology `topo-dualtor`.
The change is verified by running `test_xoff_for_pcbb`.
```
collected 4 items                                                                                                                                                          
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb[pcbb_xoff_1] PASSED                                                                                                 [ 25%]
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb[pcbb_xoff_2]  ^HPASSED                                                                                                 [ 50%] …
```
=> Add qos params for topology dualtor-64

.azure-pipelines/run-test-elastictest-nightly-template.yml, .azure-pipelines/test_plan.py
Summary:
Create a nightly template to leverage elastictest template and fulfill some general parameter
Create a nightly template to leverage elastictest template and fulfill some general parameter
=> [Elastictest] nightly test template

tests/cacl/test_cacl_function.py, tests/common/templates/default_acl_rules.json, tests/common/utilities.py, tests/crm/conftest.py, tests/crm/test_crm.py
Cherry pick conflict #9523 and #9312
Summary:
Cherry pick conflict #9523 and #9312
=> [cherry pick] #9523 Fix PR #9312 for KeyError and AttributeError in 202205

.azure-pipelines/run-test-elastictest-nightly-template.yml
=> [Elastictest] fix nightly-template

ansible/roles/test/files/ptftests/device_connection.py
Summary:
Manually cherry-pick #9582
Fix Python2/3 compatibility issue in device_connection.py
=> [202305][Cherry-pick#9582]Fix Python2/3 compatibility issue in device_connection.py

.azure-pipelines/run-test-elastictest-template.yml, .azure-pipelines/test_plan.py
Summary:
Support to pass specific parameter
=> [Elastictest] support to pass specific parameter

tests/telemetry/telemetry_utils.py, tests/telemetry/test_telemetry.py
Summary:
Add testcase to support new fix in sonic-gnmi https://github.com/sonic-net/sonic-gnmi/pull/138
Tested for key in update from gnmi output
=> Add on change update test case to test_telemetry

docs/testbed/README.testbed.VsSetup.md
Its title level must be Header 3 as Option 1 and 2.
=> nit: Fix the title level of Option 3 in README.testbed.VsSetup.md

.azure-pipelines/run-test-elastictest-template.yml, .azure-pipelines/test_plan.py
Support to pass parameter: affinity to specify some test modules not run on some testbed.
Summary:
Support to pass parameter: affinity to specify some test modules not run on some testbed.
=> [Elastictest] Support to pass affinity.

tests/iface_namingmode/test_iface_namingmode.py
For nvidia device,the headroom size is related to the speed and cable length. When platform is x86_64-nvidia_sn5600-r0 and above,we need to choose interface whose cable length is 40m not 300m. Because this platform supports speeds of 400G and above, if we use 300m cable length it will exceed the headroom limit and cause some log errors.
Summary:
Fix test_config_interface_speed issue for platform x86_64-nvidia_sn5600-r0
Select interface with  cable length 40m or 5m 
Run test_config_interface_speed  on  x86_64-nvidia_sn5600-r0
x86_64-nvidia_sn5600-r0
t1
=> [Mellanox] Fix test_config_interface_speed issue

docs/testplan/dns/static-dns-test-plan.md
Describe the test cases that will cover the static DNS feature: https://github.com/sonic-net/SONiC/blob/master/doc/static-dns/static_dns.md
Summary: Test plan for  the static DNS nameserver
Decrible what kind of test case will be added to cover the static dns nameserver test case
=> Add Static DNS test plan

tests/cacl/test_cacl_function.py, tests/common/utilities.py, tests/conftest.py, tests/crm/conftest.py, tests/crm/test_crm.py
Cherry pick conflict #9523
Summary:
Cherry pick conflict #9523
=> [cherry pick] #9523 Fix PR #9312 for KeyError and AttributeError in 202305

tests/vxlan/test_vxlan_ecmp.py
Fix to remove the installed routes at the end of the test and added igore regex to ignore a syslog message.
Summary:
Ado : 24908849
=> [testfix] test_vxlan_ecmp unexpected logs fix.

.github/CODEOWNERS
Summary:
to cherry pick https://github.com/sonic-net/sonic-mgmt/pull/8482 to 202205
=> Cherry-pick To add code owners to have default code reviewer for testcases 2022205

.github/CODEOWNERS
Summary:
to cherry pick https://github.com/sonic-net/sonic-mgmt/pull/8482 to 202012
=> Cherry-pick to add code owners to have default code reviewer for testcases 202012

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Cherry-pick #9419 to 202305 branch.
=> [202305] Sensor test update #9419

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Cherry-pick #9419 to 202205 branch.
=> [202205] Sensor test update #9419

tests/cacl/test_cacl_application.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Since https://github.com/sonic-net/sonic-buildimage/issues/10883 was fixed, enable scale cacl test cases.
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/8592
=> [202205]Enable scale cacl test cases

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Since https://github.com/sonic-net/sonic-buildimage/issues/10883 was fixed, enable scale cacl test cases.
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/8592
=> [202012]Enable scale cacl test cases

ansible/roles/test/files/ptftests/py3/vxlan-decap.py
Summary:
Fixes bug in vxlan-decap.py for testcase test_vxlan_decap
=> [202205][PTF Python3 migraiton]Fix bug in vxlan-decap.py for testcase test_vxlan_decap

tests/saitests/sai_qos_tests.py
Summary:
PR #8399 break backend device's qos test
```
FAILED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[str2-*-32s-acs-03-None-xon_1]
FAILED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[str2-*-32s-acs-03-None-xon_2]
FAILED qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueue[str2-*-32s-acs-03-None]
FAILED qos/test_qos_sai.py::TestQosSai::testQosSaiDwrr[str2-*-32s-acs-03-None]
FAILED qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark[str2-*-32s-acs-03-None-wm_pg_shared_lossless]
FAILED qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark[str2-*-32s-acs-03-None-wm_pg_shared_lossy]
FAILED qos/test_qos_sai.py::TestQosSai::testQosSaiDwrrWeightChange[str2-*-32s-acs-03-None]
============== 7 failed, 8 passed, 27 skipped in 3021.77 seconds …
```
=> partially revert PR "Fixes for qos-sai for all tests in T1 - 202012 branch. #8399"

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
cherry pick https://github.com/sonic-net/sonic-mgmt/pull/9096 to 202205
=> Cherry-Pick [conditional mark] skip test_bgp_suppress_fib before release 202305

tests/crm/test_crm.py
Summary:
On broadcom platforms, the counters for available IPv4 and IPv6 routes are not exact and instead represent a lower bound on the number of routes that are available.
Skip these counters on Broadcom platforms
Run the test on Broadcom platforms, verify that it passes now
=> [crm]: Skip 'available' CRM check on broadcom

tests/common/fixtures/duthost_utils.py, tests/common/helpers/ptf_tests_helper.py, tests/qos/test_qos_dscp_mapping.py
Summary: The DSCP to Queue Mapping test introduced a bug whereby certain fixtures available in other branches to access the `duthost` was not available in the master branch. Moreover, this PR also fixes bugs caused by ansible module failures which are now in a try catch block now. 
Bug fix
=> [QoS] Bug fix for DSCP to Queue Mapping Test

tests/snappi_tests/pfcwd/files/pfcwd_basic_helper.py, tests/snappi_tests/pfcwd/files/pfcwd_multi_node_helper.py
Summary: Cherry-pick PR for 202205 from #9567 
Lab device
=> [202205][Snappi] PFCWD Tolerance Fixes (#9567)

tests/fdb/conftest.py
Backport #9487 changes into 202012
=> [202012] [fdb] Address failures on td2 asics for fdb mac move test

tests/snappi_tests/pfcwd/files/pfcwd_runtime_traffic_helper.py
Summary: When warm up traffic was introduced, several new "flows" were created which created metrics unaccounted for in the verify function, which created faulty checks. This PR filters the traffic to only test flows and runs verification on these traffic flow metrics. 
PFCWD runtime traffic fix for nightly tests 
=> [Snappi] PFCWD runtime traffic bug fix

tests/acl/test_stress_acl.py
Cherry pick conflict #9331
Summary:
Cherry pick conflict #9331
=> Cherry pick conflict #9331 Add try-finally to recovery DUT in module `acl/test_stress_acl.py` in 202012

tests/acl/test_stress_acl.py
Cherry pick conflict #9331 
Summary:
Cherry pick conflict #9331
=> Cherry pick conflict #9331 Add try-finally to recovery DUT in module `acl/test_stress_acl.py` in 202205.

ansible/module_utils/port_utils.py
Summary:
update port utils for cisco 8000
update it
passed local test
=> update port utils for cisco 8000

.azure-pipelines/get_dut_version.py, .azure-pipelines/upgrade_image.py
Summary:
Modify python script's hashbang
Modify python script's hashbang
=> [202012]Modify python script's hashbang

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
show_techsupport.test_techsupport.test_techsupport failed due to https://github.com/sonic-net/sonic-mgmt/issues/7520.
To xfail test which has known issue.
xfail it in the conditional mark.
N/A
=> [conditional mark] Xfail techsupport for 202305

tests/show_techsupport/test_techsupport.py
Summary:
Fixes # (https://github.com/sonic-net/sonic-mgmt/issues/7520). Added checking sai_sdk_dump only on Mellanox platform
Issue https://github.com/sonic-net/sonic-mgmt/issues/7520
Added check for Mellanox asic
Run TC, check sai_sdk_dump  happens only if asic is Mellanox
=> [show techsupport] Added fix for show_test_techsupport

tests/dualtor/test_tunnel_memory_leak.py
Summary:
The test statistically fails due to a slight violation of the memory threshold. I have investigated the failure and believe there is no real memory leak. 
So, I have made some changes to improve the stability of the test.
To improve the stability of dualtor memory leak test.
1. Increase the memory threshold buffer from 0.02 to 0.03.
We found that the test occasionally fails on Nvidia 4600C platform due to the memory usage after the test is 103% of the original memory usage, which is 1% more than the buffer defined in the test. I have tried to modify the test and repeat the neighbor leaning action much more times than it is in the test, and no real memory leak was observed.
Since the 0.02 is an experience value, I suggest we increase it a little bit to 0.03.
2. Get the original …
=> [Dual-Tor] Improve the stability of dualtor memory leak test

ansible/group_vars/sonic/sku-sensors-data.yml
Revise lable name and fix typo in sensor.conf of 4600C. Test case change for PR https://github.com/sonic-net/sonic-buildimage/pull/16271
- Microsoft ADO **(number only)**:
Revise label name and fix typo  of 4600C
sonic-mgmt test_sensors.py
=> Fix issue: fix typo and remove unused sensor for 4600C

tests/snmp/test_snmp_default_route.py, tests/snmp/test_snmp_loopback.py
Cherry Pick https://github.com/sonic-net/sonic-mgmt/pull/9441 to 202205
Summary:
Cherry Pick https://github.com/sonic-net/sonic-mgmt/pull/9441 to 202205
=> [Cherry Pick] 202205 Skip default route and loopback case in BSL testing

tests/macsec/macsec_config_helper.py, tests/macsec/profile.json
PR : https://github.com/sonic-net/sonic-mgmt/pull/9812 in branch 202205
All details in https://github.com/sonic-net/sonic-mgmt/pull/9812
All details in https://github.com/sonic-net/sonic-mgmt/pull/9812
=> Macsec profiles to accept type 7 encoded keys

spytest/apis/switching/mac.py
Add GNMI Support and minor improvements
Summary:
=> Add GNMI Support and imrovements

ansible/roles/vm_set/tasks/main.yml
Reverts sonic-net/sonic-mgmt#9877
=> Revert "[Testbed] Fix the MAC address of br1 on server during add/remove topo"

tests/qos/files/qos_params.gb.yaml
Updated qos params for gb 400000_120000m.
Summary:
=> Updated qos params for gb 400000_120000m

tests/common/fixtures/duthost_utils.py
Fix for GCU DHCP_relay update submodule head
=> Updated Fix for GCU Dhcp_relay

tests/generic_config_updater/test_pg_headroom_update.py
Add GCU testcase for PG headroom modification
Ran the test on a private build against broadcom and mellanox platforms and it passed
=> [GCU] Add GCU testcase for PG headroom modification

tests/cacl/test_ebtables_application.py, tests/common/helpers/dut_utils.py, tests/ixia/pfcwd/test_pfcwd_basic.py, tests/ixia/pfcwd/test_pfcwd_burst_storm.py, tests/snappi_tests/bgp/files/bgp_convergence_helper.py, tests/snappi_tests/lacp/files/lacp_dut_helper.py, tests/snappi_tests/lacp/files/lacp_physical_helper.py, tests/snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py, tests/tacacs/test_ro_disk.py
Summary:
After the sonic-mgmt docker image is upgraded, some missed imports can be detected during static analysis.
This change added the missing imports to pass PR testing static analysis.
=> [202205] Fix missing imports detected in static analysis

tests/common/fixtures/duthost_utils.py
This PR is added to fix sub module HEAD PR by solving issue in GCU fixture/dut_utilites.py
=> Fix for switchport mode routed in GCU DHCP_Realy

ansible/roles/test/files/ptftests/py3/fg_ecmp_test.py
cherry-pick 0425c6b to 202205
Summary:
=> cherry-pick #9541 to 202205

ansible/roles/test/files/ptftests/arista.py, ansible/roles/test/files/ptftests/py3/advanced-reboot.py, ansible/roles/test/files/ptftests/py3/arista.py, ansible/roles/test/files/ptftests/py3/host_device.py, ansible/roles/test/files/ptftests/py3/sad_path.py, ansible/roles/test/files/ptftests/sonic.py, tests/common/fixtures/advanced_reboot.py, tests/platform_tests/conftest.py
Summary:
This PR migrate test_advanced_reboot's PTF script advanced-reboot.py to Python3.
This PR migrate test_advanced_reboot's PTF script advanced-reboot.py to Python3.
2to3 tool and manually.
Run test_advanced_reboot testcases with 3800 physical testbed on Azure pipeline.
=> [Python3 migration] Migrate test_advanced_reboot's PTF script advanced-reboot.py to Python3

spytest/apis/routing/vrf.py
Add support for GNMI to VRF APIs
Summary:
Improvement in VRF APIs
NA
Internal sonic tests were run
=> Add support for GNMI

spytest/apis/routing/ip.py
Add GNMI support to IP APIs and also improvements 
Summary:
Running internal regression suites.
-->
=> Add GNMI support and enhancement to existing APIs

spytest/apis/routing/nat.py, tests/copp/copp_utils.py
Add GNMI Support for NAT APIs
Summary:
Internal regression test
=> Add support for GNMI for NAT

spytest/apis/routing/sag.py
Add GNMI Support for SAG APIs
Summary:
Internal regression tests
=> Add GNMI support for SAG APIs

spytest/apis/switching/portchannel.py
-->
Add GNMI support and other enhancements
Summary:
Internal FT regression runs
=> Add GNMI support and enhancements;

spytest/apis/switching/pvst.py
Add GNMI Support for STP APIs
Summary:
=> Add GNMI support for STP

spytest/apis/switching/vlan.py
Add GNMI API support for VLAN 
Summary:
=> Add GNMI support to VLAN APIs

spytest/apis/security/radius.py, spytest/apis/switching/portchannel_rest.py
Add GNMI support for radius API and minor fix in portchannel_rest
=> Add GNMI support for radius APIs

spytest/apis/security/tacacs.py
=> Add GNMI support for TACACS

spytest/apis/system/sflow.py
=> Add GNMI support for SFLOW

spytest/apis/routing/bgp.py
Add GNMI support for BGP and some minor fixes
=> Add GNMI support for BGP and some minor fixes

spytest/apis/qos/cos.py
=> Add GNMI support for COS

spytest/apis/qos/acl.py, spytest/apis/qos/cos.py
=> Apis qos acl

spytest/apis/qos/acl.py, spytest/apis/qos/cos.py, spytest/apis/qos/wred.py, spytest/apis/system/reboot.py, spytest/apis/system/switch_configuration.py
Add GNMI support to WRED and other enhancements
=> Apis qos wred

spytest/apis/qos/acl.py, spytest/apis/qos/cos.py, spytest/apis/qos/qos.py, spytest/apis/qos/wred.py, spytest/apis/system/reboot.py, spytest/apis/system/switch_configuration.py
Add GNMI support for QOS Maps and buffer pool APIs'
=> Apis qos qos

spytest/apis/system/interface.py
Add GNMI support for interface APIs
Internal Daily  Regression runs
=> Add GNMI support for interface APIs

spytest/apis/system/port.py
Add GNMI support for Port APIs
=> Add GNMI support for port APIs

spytest/apis/common/asic.py
Enhancement to ASIC debug APIs
=> Enhancement to ASIC debug APIs

tests/vxlan/vnet_utils.py
Summary:
Created a method to verify routes configuration on vnet vxlan tests
Details:
This method queries the routes from ASIC DB and counts them, to check that a sufficient amount of routes were added or cleaned.
The method will fail the test in case not enough routes were added or cleaned from the ASIC DB.
The PR also sets a dynamic timeout of route configuration based on the number of routes added or cleaned.
Adding a pre-validation method to avoid the PTF test to run before we ensure all routes are configured properly.
Added a method that queries the routes from ASIC DB, and waits until all routes are configured in ASIC DB.
Ran the test in multiple number of routesm and verified that the timeout is correct.
No
=> Added verify routes method on vnet vxlan tests.

tests/bgp/test_bgp_sentinel.py
Summary: Fixed failures caused by python 3 conversion
Fixed failures caused by python 3 conversion, 
Convert dict_keys to list so that it would have remove method.
Run the testcase in new version and testcase would pass.
=> [VM]Add bgp sentinel peer type convert

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
To xfail following warm reboot related cases on 7050cx3:
- platform_tests/test_cont_warm_reboot.py
- arp/test_wr_arp.py
- pfcwd/test_pfcwd_warm_reboot.py
=> Xfail reboot cases

tests/pfcwd/test_pfcwd_function.py
Backport #8709 
Ran the test_pfcwd_function.py suite against dx010 and all cases passed
=> [202012] [pfcwd] Add testcase for pfcwd multi port storm trigger and restore

tests/acl/test_acl_outer_vlan.py
Summary:
Need to verify ACL bind to portchannel.
Update test_acl_outer_vlan.py and bind ACL to portchannel.
Run end2end test with different hwsku.
=> Verify ACL bind to portchannel

tests/common/connections/base_console_conn.py
To support getting output when doing power cycle, we enhance the function `posix_shell` in class `BaseConsoleConn` to support ascii output. 
Summary:
To support getting output when doing power cycle, we enhance the function `posix_shell` in class `BaseConsoleConn` to support ascii output. 
Set the type of output using `sys.setdefaultencoding('utf8')`.
=> Update function `posix_shell` in class `BaseConsoleConn` to support ascii output. 

tests/snmp/memory.py
Summary:
cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/9645
202305 cherry-pick conflict
Cherry-pick the PR manually
NA
=> [test_snmp_memory_load] reserver 256M free memory cherry-pick PR 9645 to 202305

tests/common/dualtor/data_plane_utils.py, tests/common/dualtor/dual_tor_io.py, tests/dualtor_io/test_normal_op.py
Summary:
Add server to server normal testcase to cover the east-to-west traffic verification for dualtor.
1. Select two mux ports, one as source port, one as dest port.
2. Send traffic from source port and verify traffic delivery at the dest port.
```
dualtor_io/test_normal_op.py::test_normal_op_server_to_server[active-active] PASSED                                                                                                                                                                                    [100%]
================================================================================================================ 1 passed, 1 deselected in 287.93s (0:04:47) …
```
=> [dualtor_io] Add server to server I/O normal op test

tests/qos/qos_sai_base.py
What I did:
Cherry Pick of master PR: https://github.com/sonic-net/sonic-mgmt/pull/10052
=>     Increased socket buffer for PTF while running QoS test

tests/platform_tests/api/watchdog.yml
Summary:
Update timeout values to be used for testing watchdog APIs in Dell platforms.
=> [watchdog.yml] Update timeout value for Dell platforms

tests/common/platform/device_utils.py, tests/platform_tests/cli/test_show_platform.py
Reverts sonic-net/sonic-mgmt#9264
It will block 8102 and 8101
=> Revert "Cisco-8000 psu led support"

tests/dualtor/test_tunnel_memory_leak.py
Summary:
This is the manual cherry-pick of PR (#9198) to 202205 branch for conflict resolving.
This is the manual cherry-pick of PR (#9198) to 202205 branch for conflict resolving.
The conflict is caused by the Python2/3 migration change which is not included in 202205 branch. I removed the change to resolve the conflict.
Run the test 5 times on 4600C with 202205 SONiC image, all passed.
=> [202205] Cherry-pick : Improve the stability of dualtor memory leak test (#9198)

tests/common/devices/sonic.py, tests/platform_tests/api/test_sfp.py, tests/platform_tests/sfp/test_sfputil.py
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/8556 from master to 202205
Update lpmode tests
1. Update lpmode tests due to the design change for Nvidia devices: https://github.com/sonic-net/sonic-buildimage/pull/14130
a) For Nvidia devices, before setting lpmode we need to shutdown admin ports
b) Add one step to check when setting lpmode to enabled with admin port up, lpmode is still off and port is still up.
2. Fix issue of test_check_sfputil_low_power_mode. Previously after setting the lpmode, test checks the value is on or off, which is not correct. we should check if the value of lpmode is the set one.
3. Optimize test of test_check_sfputil_low_power_mode, reduce time for looking up if port supports lpmode. Previously it was needed to look up two times, currently only one …
=> [202205 | Mellanox] Update lpmode tests

tests/common/helpers/pfc_gen.py, tests/common/helpers/pfc_storm.py, tests/common/templates/pfc_storm_onyx.j2, tests/common/templates/pfc_storm_stop_onyx.j2, tests/pfcwd/test_pfcwd_warm_reboot.py
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/8145 from master to 202205
On onyx fanout, sending pfc frames is not distributed evenly in terms of time which makes some period of time unblocked. 
So, athough sometimse fanout send enough pfc frames, it cannot trigger pfcwd status.
So, add some delay for every PFC frame to make the sending pfc frames is distributed evenly, which can improve triggering pfcwd status stability.
Summary:
It is to resovle the issue that PFC frames are not distributed evenly so it can not trigger pfcwd status sometimes.
Add one delay for sending every pfc frame. The delay is caculated based on the port speed.
Send pfc frames for multi ports at the same time from fanout.
Beofore adding delay, when total port numbesr is increased to 4, it …
=> [202205 | Nvidia|pfcwd] Fix pwfwd test failure due to send pfcwd is not distributed evenly on onxy fanout 

ansible/roles/test/files/ptftests/advanced-reboot.py
Revert https://github.com/sonic-net/sonic-mgmt/pull/8089 to fix issue https://github.com/sonic-net/sonic-mgmt/issues/10064 :sometimes it will cause warm-reboot case is stuck in endless loop.
Summary:
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/10064
fix Issue  https://github.com/sonic-net/sonic-mgmt/issues/10064
Revert https://github.com/sonic-net/sonic-mgmt/pull/8089
Review code or run test-warm reboot sad case
=> [202205 | Warm-reboot] Revert PR 8089 to fix issue that sometimes warm-reboot case is stuck in endless loop

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/10135 into 202205
=> [202205]Ignore Failed to parse lldp age error log

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/10135
=> [202012]Ignore Failed to parse lldp age error log

ansible/roles/test/files/ptftests/py3/advanced-reboot.py, ansible/roles/test/files/ptftests/sonic.py
This file is used with the advanced-reboot test case with SONiC neighbors.
This also makes sure the advanced reboot test case fails if there's some exception raised in the neighbor VM thread, so that failures (and the traceback) are more easily visible. It also fixes a potential false positive where advanced-reboot thinks that there were LAG flaps, even though there were done during the test.
Summary:
Tested by doing a warm reboot with SONiC neighbors, and verifying that the neighbor thread completed successfully.
=> Fix Python 3 syntax errors in sonic.py

tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC3.yaml, tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC4.yaml, tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC5.yaml, tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC6.yaml, tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC10.yaml, tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC3.yaml, tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC4.yaml, tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC5.yaml, tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC6.yaml, tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC7.yaml, tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC8.yaml, tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC9.yaml, tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC3.yaml, tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC4.yaml, tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC5.yaml, tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC6.yaml, tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC10.yaml, tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC3.yaml, tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC4.yaml, tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC5.yaml, tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC6.yaml, tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC7.yaml, tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC8.yaml, tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC9.yaml, tests/voq/test_fabric_reach.py
Summary: The test_fabric_reach test errored on 7800R3AK-36DM2-C36 cards due to missing expected fabric data file. This change adds the expected data for that type of cards. Also updated the test to fix some issue.
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/8383
=> Add fabric test data for 7800R3AK-36DM2-C36 cards

tests/platform_tests/test_auto_negotiation.py
For Nvidia device, only support to raise link Force<->Force or Auto-negotiation<->Auto-negotiation flows
For other scenario the port may not come up in timeout, but could come up in longer time, for example may need 120s.
Summary: 
Fixes # (issue) The auto-nego test not stable, sometimes the port could not come up in the 90s timeout
fix the test unstable issue
Shutdown the dut port before change the interface type on both the dut port and the fanout port, startup the dut port after the config finished. with this method we can make sure the interface type can be same (both force or both auto-nego) when the 2 ports are both in up state. 
run the autonego test on Nvidia platform, and it could pass stablly
=> fix auto-negotiation test unstable issue

tests/conftest.py, tests/run_tests.sh
Summary:
Cherry pick #10243 into 202012
=> [202012]Exit pytest with error code 15 if duthosts fixture fails

spytest/tests/routing/test_ip.py
Basic TCs for IP
Summary:
Internal regular FT runs
-->
=> Add basic IP TCs

spytest/tests/routing/test_arp.py, spytest/tests/routing/test_ndp.py, spytest/tests/sanity/test_sanity_l3.py
=> Add Neighbor and L3 Sanity TC

spytest/tests/routing/NAT/test_nat.py
=> remove few invalid tests

spytest/tests/routing/VRF/vrf_lib.py
Library function for VRF Testcases
Summary:
Internal Daily FT runs
=> update lib for VRF

spytest/tests/routing/VRF/test_vrf.py
Add functional testcases for VRF
Summary:
Internal daily FT Runs
=> Add functional testcases for VRF

spytest/tests/routing/VRF/test_vrf_scale.py, spytest/tests/routing/VRF/vrf_vars.py
Add VRF Scale Testcases
Summary:
Internal FT runs
=> Add VRF Scale Testcases

spytest/tests/routing/BGP/bgp4nodelib.py, spytest/tests/routing/BGP/test_bgp_4node.py
Enhance/Add TCs for BGP confed and RR
Summary:
=> Enhance TCs forBGP confed and RR

spytest/tests/routing/BGP/bgplib.py, spytest/tests/routing/BGP/test_bgp.py
=> Update BGP func testcases

spytest/tests/qos/test_qos_save_reboot.py, spytest/tests/routing/BGP/test_bgp_rr_traffic.py
Enhance existing testcses - bgp and qos
Summary:
=> Enhance existing testcses - bgp and qos

spytest/tests/system/test_device_mgmt.py, spytest/tests/system/test_sflow.py
Enhance sflow and system testcases
Summary:
=> Enhance sflow and system testcases

spytest/tests/routing/test_l3_performance.py
Enhance testcases and remove invalid ones
Summary:
=> Enhance testcases and remove invalid ones

tests/bgp/test_traffic_shift.py
Fix issue:  https://github.com/sonic-net/sonic-mgmt/issues/10119
It might be a multi-thread issue. when concurrent_tasks is 8, the case fails about 1 time per 3 times, when it is set to 4, run the test 20 times, and all pass.
Summary:
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/10119
Fix issue:  https://github.com/sonic-net/sonic-mgmt/issues/10119
decrease the multi-task number from 8  to 4
Run Test_TSA 20 times
Any
=> [202205]Fix potential multi-thread issue of TSA test

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/utilities.py
Summary: DSCP pipe decap mode is not supported by vendors Mellanox and Cisco (SAI support not provided by vendor), hence the the pipe decap mode tests are expected to fail.
Test shows xfail status on lab device
=> [QoS] Xfail setup for IPIP dscp queue mapping DSCP pipe decap mode tests

ansible/roles/fanout/templates/sonic_deploy_202012.j2
Summary:
Update SONiC.202012 fanout config template for Celestica-E1031.
Update SONiC.202012 fanout config template for Celestica-E1031.
Remove some unsupported configuration for Celestica-E1031.
Verified on physical fanout device.
=> [Fanout] Update SONiC.202012 fanout config template for Celestica-E1031

tests/flow_counter/flow_counter_utils.py, tests/route/test_route_flow_counter.py
PR https://github.com/sonic-net/sonic-mgmt/pull/8732 added test topo to `any`, but the CLI this test used will not work for multi-asic card, also it should not run on SUP.
Before we make this test to MA workable, we should not run on T2.
Summary:
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/10208
https://github.com/sonic-net/sonic-mgmt/issues/10203
run on T2
```
SKIPPED [9] /var/src/private/sonic-mgmt-int/tests/flow_counter/flow_counter_utils.py:119: Skip test for T2 and multi-asic
========================= 9 skipped in 360.47 seconds ==========================
```
=> [chassis] skip test_route_flow_counter.py for t2

spytest/utilities/utils.py
=> avoid reading data map while importing

spytest/spytest/batch.py, spytest/spytest/main.py, spytest/spytest/ordyaml.py, spytest/spytest/testbed.py, spytest/utilities/cache.py, spytest/utilities/profile.py
=> move cache utility apis from profile apis

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Cherry-pick conflict: https://github.com/sonic-net/sonic-mgmt/pull/9922
=> [202012][dualtor] update skip logic of `test_wr_arp` for dualtor 

tests/dualtor_io/test_normal_op.py
Summary:
Put back the commented import.
=> Fix the commented import

tests/bgp/test_bgp_update_timer.py
Summary:
Log the bgp update packet details.
```
bgp/test_bgp_update_timer.py::test_bgp_update_timer_session_down[str2-msn4600c-acs-03-default] PASSED                                                                                                                                                                  [100%]
```
=> [test_bgp_update_timer] Log the update packets

tests/bgp/test_bgp_update_timer.py
Summary:
24933545
Add debug log to record timestamp in case test_bgp_update_timer_session_down
add debug log to record timestamp
Run the case and check the log
17/10/2023 08:52:15 test_bgp_update_timer.test_bgp_update_ti L0448 DEBUG  | timer: DUT 1697532735.077164 local 1697532735.10403
=> record timestamp log for case test_bgp_update_timer_session_down

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
25496853
there is a warm reboot related known issue on the 202305 branch.
xfail the warm reboot related cases on 202305 branch for 6100 and 7260
platform_tests/test_cont_warm_reboot.py
arp/test_wr_arp.py
pfcwd/test_pfcwd_warm_reboot.py
6100 and 7260
=> xfail warm reboot for 6100 and 7260

tests/dualtor_io/test_link_drop.py
Summary:
Add back the toggle, which is removed by PR: https://github.com/sonic-net/sonic-mgmt/pull/9568
=> [dualtor-io] Add the miss toggle

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Added skip based at https://github.com/sonic-net/sonic-buildimage/issues/15051
TC failed due to sonic-buildimage issue
Added skip based at open issue 
Run TC. TC skipped
=> Added skip for test_max_limit[core] 

tests/qos/files/qos_params.gb.yaml, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py
Double commit https://github.com/sonic-net/sonic-mgmt/pull/10067
Summary:
=> Fix BufferPoolWatermarkTest failure for cisco long-link

tests/common/dualtor/mux_simulator_control.py, tests/qos/qos_sai_base.py
Summary:
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/10428 into 202205
=> [202205][test_qos_sai] Fix toggle failures on dualtor testbed (#10428)

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
25496853
there is a warm reboot related known issue on the 202305 branch.
xfail the warm reboot related cases on 202305 branch for 7050qx
platform_tests/test_cont_warm_reboot.py
arp/test_wr_arp.py
pfcwd/test_pfcwd_warm_reboot.py
=> skip warm reboot cases for 7050qx

tests/route/test_route_consistency.py
Summary:
Currently there is testGAP in verifying route_consistency upon different triggers. 
Added new testcases (applicable to all topology types) to verify routes consistency by comparing route snapshot from ASIC DB pre and post trigger.
Executed the new tests on kvm-t1-lag topo testbed
Executed the new tests on T2 testbed
None
NA
=> New Testcases for route_consistency

tests/ntp/test_ntp.py
Summary:
This is a follow-up to #10413.
This updates `ntp/test-ntp.py::test_ntp` to add support for ntpsec, which is being used in Bookworm.
Tested on Bookworm base image.
=> Update test_ntp for Bookworm

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
cherry pick https://github.com/sonic-net/sonic-mgmt/pull/10395
=> Cherry pick Skip non t2 for voq test to 202205

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
cherry pick https://github.com/sonic-net/sonic-mgmt/pull/10395
=> Cherry pick Skip non t2 for voq test to 202305

tests/platform_tests/verify_dut_health.py
Summary:
This is the manual cherry-pick of PR #10076 for conflict resolving.
Fix test issues in verify_dut_health.py, this script is used in the advanced reboot test.
There are two issues:
1. In check_services(), when the service check fails, it should not directly fail the test by pytest_assert. Instead, it should raise the RebootHealthError so the exception can be handled and added to the test report.
2. In the verify_dut_health(), the logic in verify_dut_health before the yield is not correct, the test does not fail on any health errors because any string(failure reason) is considered as True in the all() method.
Fix test issues in verify_dut_health.py
1. Raise the RebootHealthError when the service check fails.
2. If there is any failure in the pre-reboot checks, fail the test.
Run …
=> [202205] Fix test issues in verify_dut_health.py

tests/platform_tests/test_auto_negotiation.py
This is only for 202205 branch due to the merge conflict in https://github.com/sonic-net/sonic-mgmt/pull/9813
For Nvidia device, only support to raise link Force<->Force or Auto-negotiation<->Auto-negotiation flows
For other scenario the port may not come up in timeout, but could come up in longer time, for example may need 120s.
Summary: 
Fixes # (issue) The auto-nego test not stable, sometimes the port could not come up in the 90s timeout
fix the test unstable issue
Shutdown the dut port before change the interface type on both the dut port and the fanout port, startup the dut port after the config finished. with this method we can make sure the interface type can be same (both force or both auto-nego) when the 2 ports are both in up state. 
run the autonego test on Nvidia platform, and …
=> [202205]fix auto-negotiation unstable issue

tests/platform_tests/fwutil/conftest.py
Summary: In the existing implement of the fwutil test, the data(--fw-pkg) is saved in the xx.tar.gz file, and the json file is included in the tar.gz file. Enhance the test to support input a json file to --fw-pkg.
User can either specify the tar.gz or json file to the --fw-pkg when run the test_fwutil.py
Run the  test_fwutil.py, and test cases pass
=> Update the fwutil test case

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Added skip based at  # ([16685](https://github.com/sonic-net/sonic-buildimage/issues/16685))
Avoid fails at Mellanox platforms
Add skip statement
Run TC, skipped based at asic and issue
=> Skip test_sfputils for Mellanox

tests/generic_config_updater/gu_utils.py, tests/generic_config_updater/test_ecn_config_update.py, tests/generic_config_updater/test_incremental_qos.py, tests/generic_config_updater/test_pfcwd_interval.py, tests/generic_config_updater/test_pfcwd_status.py, tests/generic_config_updater/test_pg_headroom_update.py
Cherry-pick 2 PRs: https://github.com/sonic-net/sonic-mgmt/pull/10214, https://github.com/sonic-net/sonic-mgmt/pull/10241/files
ADO 25310959
=> [GCU] Cherry-pick fix pfcwd test, ensure valid operation in RDMA validator

tests/acl/test_acl_outer_vlan.py
Summary:
Fix traffic issue on fanout switch.
Nightly test for EXO is broken.
Microsoft ADO: 25579175
1. Do not use duthost directly
2. Fix mac conflict on fanout switch
Run end to end test
=> Fix nightly test for EXO

tests/acl/test_acl_outer_vlan.py
Summary:
Fix traffic issue on fanout switch.
Nightly test for EXO is broken.
Microsoft ADO: 25579175
Backport https://github.com/sonic-net/sonic-mgmt/pull/10512
1. Do not use duthost directly
2. Fix mac conflict on fanout switch
Run end to end test
=> [202205] Fix nightly test for EXO

tests/saitests/py3/sai_qos_tests.py
Double commit https://github.com/sonic-net/sonic-mgmt/pull/10338
Summary:
=> Update class LossyQueueVoqTest to handle dst_port in port-channel

ansible/group_vars/sonic/sku-sensors-data.yml
update sensors data for x86_64-mlnx_msn4600c-r0
Summary:
Update sensors data for x86_64-mlnx_msn4600c-r0
update ansible/group_vars/sonic/sku-sensors-data.yml
Run platform_tests/test_sensors.py
x86_64-mlnx_msn4600c-r0
Any
=> [Mellanox]Update sensors data for  x86_64-mlnx_msn4600c-r0

ansible/library/show_interface.py, tests/test_pktgen.py
Testcase does the following steps:
1. Check max CPU utilized , number of core and dump files before starting the run
2. Configure pktgen traffic and start it, check if the pktgen process has generated the packets and 
if the packets are seen across the interface
3. Check max CPU utilized , number of core and dump files after the run is complete and verify if there any additional 
core/dump files
- [ x] 202205
Ran it on Cisco M64 devices (T0 and dualtor topo) and it passed
=> New testcase for pktgen testing

tests/telemetry/events/host_events.py
Summary:
Current test_events only support telemetry container.
Check docker images to choose from telemetry and gnmi.
=> Update test_events to support gnmi and telemetry

tests/telemetry/events/swss_events.py
Summary:
Fixes # (issue) 25060523
Add additional threshold configuration to invoke crm threshold event
Change ipv4 route percentage for threshold event
Manual testing/pipeline
=> Add additional threshold checks for invoking crm_threshold event

tests/override_config_table/test_override_config_table.py, tests/override_config_table/test_override_config_table_masic.py
Summary:
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/10618
Ran on our single-asic and multi-asic t2 DUTs
=> Fix setup_env() from test_override_config_table.py and test_override_config_table_masic.py to run for each duthost

tests/bfd/test_bfd.py
Summary:
Fixes test_fbd.py flaky result
This is double commit of #10682
=> Fix test_fbd.py flaky result

tests/common/dualtor/mux_simulator_control.py
Summary:
Transient HTTP connection timeout error is observed in nightly:
```
05/11/2023 09:30:32 mux_simulator_control._post              L0181 WARNING| POST http://10.64.246.133:8082/mux/vms21-6?reqId=63a6d7fa-667d-4477-b2d3-1045ef80f144 with data {'active_side': 'random'} failed, err: ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='10.64.246.133', port=8082): Read timed out. (read timeout=10)"))
```
Add retries.
Run `test_decap.py` on dualtor testbed, verified the retry works:
```
09/11/2023 04:36:50 mux_simulator_control._toggle_all_simula L0410 INFO   | Toggle all ports to "random"
09/11/2023 04:36:50 mux_simulator_control._toggle_all_simula L0413 INFO   | Retry=1, toggle all mux cables to random side
09/11/2023 04:36:50 mux_simulator_control._post …
```
=> [dualtor] Add toggle retries

tests/bgp/test_bgp_suppress_fib.py
Summary:
bgp suppress fib enabled by default, which could fail below two cases
test_bgp_route_without_suppresstest_bgp_route_without_suppress
test_credit_loop
To disable the bgp suppress fib at the beginning of test. And enhance the restore_bgp_suppress_fib function
Run sonic-mgmt test
=> Fix suppress fib failure

tests/common/dualtor/mux_simulator_control.py
Summary:
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/10691 into 202205
=> [202205][dualtor] Add toggle retries (#10691)

tests/saitests/py3/switch.py
Adding the definition of a new function to switch.py, to be used by sai_qos_tests.py.
=> Adding the new function: sai_thrift_read_pg_occupancy.

tests/bgp/test_bgpmon.py, tests/common/fixtures/pfc_asym.py, tests/console/test_console_loopback.py, tests/dualtor/test_tor_ecn.py, tests/platform_tests/api/test_psu_fans.py, tests/sai_qualify/test_community.py, tests/sai_qualify/test_sai_ptf.py, tests/sai_qualify/test_warm_reboot.py
Summary:
Did another round of scan and found more missing imports.
This change added the missing imports.
=> [202205] Add more missing imports

tests/common/fixtures/pfc_asym.py, tests/dualtor/test_tor_ecn.py, tests/platform_tests/api/test_psu_fans.py, tests/sai_qualify/conftest.py
Summary:
Did another round of scan and found more missing imports.
This change added the missing imports.
=> [202012] Add more missing imports

tests/show_techsupport/test_auto_techsupport.py
Summary:
The Test Case "test_rate_limit_interval" experiences intermittent failures when validating that only one instance of "techsupport" is running, when multiple core files are generated within the limit of "DEFAULT_RATE_LIMIT_GLOBAL." This issue arises because, during core file generation, the process "coredump_gen_handler.py" runs briefly to verify if another instance is active ,where it struggles to acquire a lock and complete the cycle within short period. In the current scenario, this brief process is erroneously counted among the active processes of "coredump_gen_handler," causing the test case to fail.
This modification aims to address this issue by allowing sufficient time for all processes to complete, ensuring accurate counting and preventing the test case failure. …
=> Intermittent Failure due to coredump_gen_handler process execution time on test_auto_techsupport.py Test Case test_rate_limit_interval 

tests/common/dualtor/mux_simulator_control.py
Summary:
Noticed in recent `test_link_drop` test runs, cases can't pass for "failed to set drop" or unable to recover drop. 
Adding a retry logic for `mux_simulator_control` request. 
 
* Run link drop case `test_active_link_drop_upstream`, shutdown mux_simulator to enforce retries. 
```
19:55:54 mux_simulator_control._post              L0184 DEBUG  | POST http://10.64.246.225:8082/mux/vms28-6/output?reqId=95dc3f92-b670-4efa-ad22-dfec8358044f with {'out_sides': ['upper_tor', 'lower_tor', 'nic']}
19:55:54 connectionpool._new_conn                 L0227 DEBUG  | Starting new HTTP connection (1): 10.64.246.225:8082
19:55:54 retry.increment                          L0575 DEBUG  | Incremented Retry for …
```
=> [dualtor] Add retry logic for `mux_simulator_control` post requests 

tests/acl/test_stress_acl.py
Summary:
The stress ACL test has a relatively low probability of failing during execution. The reason could be that the add and delete of ACLs require some time, and occasionally, the short time frame may cause the add and delete operations to not occur promptly, resulting in test case failure.
ref PR: https://github.com/sonic-net/sonic-mgmt/pull/10715
Add wait_until to check if acl rule added/deleted in state db.
Run test
=> [202205] Add wait until in stress acl test

tests/acl/test_stress_acl.py
Summary:
The stress ACL test has a relatively low probability of failing during execution. The reason could be that the add and delete of ACLs require some time, and occasionally, the short time frame may cause the add and delete operations to not occur promptly, resulting in test case failure.
ref PR: https://github.com/sonic-net/sonic-mgmt/pull/10715
Add wait_until to check if acl rule added/deleted in state db.
Run test
=> [202012] Add wait until in stress acl test

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip test_bgp_queue for m0/mx.
**The skip condition is included in this PR was also included in https://github.com/sonic-net/sonic-mgmt/pull/10102, which should not be backport, so manually update it.**
Add skip condition.
Run test.
=> [202205][bgp] Skip test_bgp_queue for m0/mx

tests/drop_packets/drop_packets.py, tests/drop_packets/test_drop_counters.py
cherry pick https://github.com/sonic-net/sonic-mgmt/pull/10634
Summary:
=> [202205]Fix Unknown header type in drop counter test

ansible/module_utils/port_utils.py
Summary:
double commit PR #9797
update port utils for cisco 8000
cherry-pick and fix conflict
=> [202205][double commit] update port utils for cisco 8000 (#9797)

tests/telemetry/conftest.py
Summary:
If there's sonic-gnmi or sonic-telemetry docker image, we should not skip telemetry test.
Check both sonic-gnmi and sonic-telemetry docker image.
Run end to end test for telemetry.
=> Support gnmi and telemetry container

tests/common/dualtor/data_plane_utils.py
Summary:
Cherry-pick commits: 
```
c7854694d update traffic disruption validating logic for dualtor_io tests (#8858)
45453bf32 fix divided by zero (#10275)
```
=> [202012] update traffic disruption validating logic for dualtor_io tests

tests/common/helpers/gnmi_utils.py
Summary:
Telemetry test failed for single telemetry container.
Fix typo in test code.
Run end to end test for telemetry.
=> [202305] Fix typo in gnmi helper

tests/common/helpers/gnmi_utils.py, tests/telemetry/conftest.py
Summary:
If there's sonic-gnmi or sonic-telemetry docker image, we should not skip telemetry test.
Check both sonic-gnmi and sonic-telemetry docker image.
Run end to end test for telemetry.
=> Support gnmi and telemetry container (#10823)

tests/saitests/py3/sai_base_test.py, tests/saitests/py3/sai_qos_tests.py
Summary:
Fix 2 issues of the dscp remapping test:
1. The fix for the QoS SAI test lag support on Mellanox devices(PR #9587) is not working with the dscp remapping test. 
This affects the test case test_xoff_for_pcbb and test_tunnel_decap_dscp_to_pg_mapping
2. Restore a logic which was accidently chnaged by PR #8149:
https://github.com/sonic-net/sonic-mgmt/pull/8149/files#diff-c1dbec061026de1f0fe921b088b2596a0a2b31ce337f567d3aadda76521254b0L835-R845
Without the correct values for inner and outer dscp, the test will fail on Nvidia platforms.
Fix 2 issues of the dscp remapping test
1. For the first issue, when getting the dut port, if there is no key "dst" in interface_to_front_mapping, try to get the port by key "src". Currently the logic is if we use "port_map_file_ini" in the ptf …
=> [Nvidia] Fix dscp remapping cases

tests/common/dualtor/mux_simulator_control.py
Summary:
Fix the error observed in nightly:
TypeError("__init__() got an unexpected keyword argument 'allowed_methods'")
It is introduced by PR: https://github.com/sonic-net/sonic-mgmt/pull/10739
This is due to that the urllib3 used in nightly agents is of version
'1.25.8', which have argument `method_whitelist` instead of
`allowed_methods` to take the allowed HTTP methods.
Let's check first before init `Retry`.
=> [dualtor] Fix toggle request retry failure

.azure-pipelines/upgrade_image.py, ansible/devutil/devices/sonic.py, ansible/library/reduce_and_add_sonic_images.py
Summary:
The customized module `reduce_and_add_sonic_images` looks like a blackbox with too few messages for debugging when it failed. When upgrade image failed, we usually do not have enough information for debugging
This change enhanced module `reduce_and_add_sonic_images` to return more meaningful debug messages.
This change also improved the `upgrade_image.py` script to have better log messages. The check of reachability before image upgrading is also enhanced.
Tested run on physical devices.
=> Improve debuggability of sonic image upgrading

.azure-pipelines/baseline_test/baseline.test.mgmt.public.master.yml, .azure-pipelines/baseline_test/baseline.test.template.yml
Summary:
Modify the wrong yml path in baseline test yaml
=> Modify template path in baseline test yaml

spytest/containers/keysight-ubuntu18/Dockerfile
Summary: Upgrading Ubuntu image verison from 18.04 to 22.04 for Spytest
Upgrade Ubuntu image version to 22.04
Verified the upgrade on my local testbed server
=>  Upgrading Ubuntu image verison to 22.04 for Spytest

spytest/containers/README.md, spytest/containers/keysight-ubuntu18/Dockerfile, spytest/spytest/tgen/init.py
Summary: Upgrading spytest support to Ixnetwork 9.30 and python3
Upgrade spytest support from Ixnetwork 9.20 to 9.30 and python2 to python3
Tested locally on the testbed server
Ran community-pass cases and verified
=> Upgrading spytest support to Ixnetwork 9.30 and python3

spytest/bin/env, spytest/spytest/tgen/init.py
Summary: This PR fixes the issue [spytest collateral] PR 9364 has introduced a collateral where the hlt and tgen path are wrong #10632
=> Fixing issue [spytest collateral] PR 9364 has introduced a collateral where the hlt and tgen path are wrong #10632

.azure-pipelines/baseline_test/baseline.test.mgmt.public.master.yml, .azure-pipelines/baseline_test/baseline.test.template.yml
Summary:
Jobs template yaml could not start with variables
Set variables under stage
=> Update baseline test yaml

.azure-pipelines/testbed_health_check.py
[Refine] Enhance testbed health check scripts.
- Add interfaces status check
- Add critical containers check
- Fix and improve BGP sessions check
- Refine output result and logs
- Catch specific exceptions to distinguish different failure clearer
Enhance scripts to fix bugs and meet requirements.
Enhance scripts.
Verified locally.
=> [master][Refine] Enhance testbed health check scripts, catch specific exceptions

tests/qos/test_qos_sai.py
Enable TestQosSaiDscpToPgMapping on Mellanox device
Summary:
Enable TestQosSaiDscpToPgMapping on Mellanox device
Enable TestQosSaiDscpToPgMapping on Mellanox device
Run  TestQosSaiDscpToPgMapping on Mellanox device
Mellanox 
t0, t1,ptf
=> [Mellanox|202205] Enable TestQosSaiDscpToPgMapping 

tests/generic_config_updater/test_vlan_interface.py
ADO: 26066269
Summary: Fix one fixture that may result in inconsistencies between the device setup and the device under test
One fixture may  result in inconsistencies between the device setup and the device under test
Change to same dut
E2E test
=> [GCU][test_vlan_interface] Update fixture to accommodate dualtor testbed

tests/bgp/test_bgp_queue.py
`bgp/test_bgp_queue.py` is broken on multi-asic because it's not aware of multi-asic.  Fix the test accordingly.
Summary:
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/10767
- [ x] 202205
- [ x] 202305
=> Make bgp/test_bgp_queue.py aware of multi-asic

docs/testplan/dns/static-dns-test-plan.md
Summary: Update the static dns test plan according to the comments in test plan review meeting
Update the test plan according to the test plan review comments
Add one more test case: Verify dynamic DNS will take effect when there is no static dns nameserver is configured and the ip is changed to the dynamic ip.
=> Update the static dns test plan according to the review comments

tests/reset_factory/test_reset_factory.py
=> Fix for test_reset_factory_keep_all_config test (issue #10664)

ansible/vars/topo_t1-56-lag.yml
Summary:
check in topo_t1-56-lag.yml for O8C48
=> check in topo_t1-56-lag.yml for O8C48

tests/generic_config_updater/test_eth_interface.py
Cherry-pick PR to 202205: https://github.com/sonic-net/sonic-mgmt/pull/10920
ADO 25517954
=> [202205 GCU E2E Testing Cherry-pick] test_eth_interface.py DUT Selection Fix

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
add xfail skip to test because of open github issue
add xfail skip to test because of open GitHub issue
added new test entry to the YAML file
=> Add github issue skip to link_flap test

tests/ipfwd/test_nhop_group.py
Summary:
test_nhop_group.py failed in nightly
RCA:
DUT reload in previous case, and CRM stats is not initialized when test nhop, cuased relevant command failure.
experiments result:
- checking output of "docker ps -a" and "systemctl --type=service --state=running" is not helpful. So directly check output of "sonic-db-cli  COUNTERS_DB HMGET CRM:STATS crm_stats_nexthop_group_used .... ...."
- maximum wait time for CRM:STATS re-initialization is 6 minutes.   So, in setup stage of nhop , max wait time is 6 min.
pass local test.
=> wait for CRM stats init complete before start nhop test

tests/common/dualtor/dual_tor_utils.py
Summary:
The test case tests/dualtor/test_orchagent_active_tor_downstream.py::**test_downstream_ecmp_nexthops** fails on our testbed because of 2 issues:
1. The packets with source IP addresses in 127.0.0.0/8 is not allowed, such packets are discarded on purpose on Nvidia platforms. 
2. Packet loss in ptf is observed, after debugging we think the reason is the performance of ptf on our test server is not enough to receive all the packets sent in the test. 
As a fix, I increase the packet receive timeout to 1s, and decrease the packet number to 1000 as 10000 packets is not necessary since we no longer verify balance in this test and also it's time consuming to send and verify such many packets. 
Fix the dualtor ecmp nexthop test issue 
1. Update the source IP address range to exclude …
=> Fix the dualtor ecmp nexthop test

tests/pfcwd/test_pfcwd_warm_reboot.py
Summary:
The test_pfcwd_warm_reboot.py no_storm and async_storm test cases sometimes fails on MSFT SKU setups due to the change in PR:
-  https://github.com/sonic-net/sonic-swss/pull/2883
-  https://github.com/sonic-net/sonic-buildimage/pull/16233.
With this change, all buffer counters (which are read from SAI) will be created after warm reboot as soon as possible, regardless of the CONFIG_DB buffers configuration. It will take much longer time to complete the counter creation
And the pfcwd is only available after all the counters are created, when the test sends pfc storm after warm-reboot, the counters could have not been completely created, so no storm is detected by the pfcwd. This causes the test to fail on the platforms with MSFT SKUs.
We need to add some delay after warm-reboot if …
=> Update the pfcwd warm reboot test for "create_only_config_db_buffers"

tests/dash/crm/files/del_dash_crm_config.json, tests/dash/crm/files/set_dash_crm_config.json, tests/dash/crm/test_dash_crm.py, tests/dash/proto_utils.py
Summary:
Update dash crm test to use GNMI for confiugration
Update dash crm test to use GNMI for confiugration
Use the existing gnmi utils to do the configuration in dash crm test.
Run the tests on DPU.
=> Update dash crm test to use GNMI for confiugration

tests/route/test_route_flap.py
Summary:
During the test_route_flap, there could be transient that route is not offloaded, and the monit route_check will complain the missed_FRR_routes errors. The previous code to ignore this error msg doesn't work.
To ignore missed_FRR_routes error log
Manual test
=> [test_route_flap] ignore the missed_FRR_routes for test_route_flap

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Added skip of fgnhg test due to issue #7755
Upstream local skip
=> [test_fgnhg] skip test due to issue 7755

.azure-pipelines/common.py, .azure-pipelines/upgrade_image.py
Cherry pick conflict #10995 
Summary:
Cherry pick conflict #10995
=> [202305] Move public functions from `upgrade_image.py` to `common.py`.

.azure-pipelines/common.py, .azure-pipelines/upgrade_image.py
Cherry pick conflict #10995 
Summary:
Cherry pick conflict #10995
=> [202205] Move public functions from `upgrade_image.py` to `common.py`.

tests/bgp/test_traffic_shift.py, tests/conftest.py
Cherry pick conflict #9821
Summary:
Cherry pick conflict #9821
=> [202205] Skip checking expected core dump in module `bgp/test_traffic_shift.py`.

ansible/roles/eos/templates/t1-56-lag-spine.j2, ansible/roles/eos/templates/t1-56-lag-tor.j2
Summary:
check in topo t1-56-lag template for O8C48
=> check in topo t1-56-lag template for O8C48

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
For now, test_iface_loopback_action has some failures, but it doesn't leave testbed unreachable, we can remove skip condition now.
Enable test_iface_loopback_action in nightly test.
work item: 26158406
remove skip conditions
run test_iface_loopback_action.py
=> Remove some skip condition for test_iface_loopback_action

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Due to https://github.com/sonic-net/sonic-mgmt/issues/11103, skip reset_factory script in nightly test
add skip condition for test_reset_factory
Run reset_factory/test_reset_factory.py
=> Skip reset_factory case due to a known issue

tests/vlan/test_vlan.py
Summary:
Microsoft ADO: 26205716
Sometimes test_vlan failed, and ptf can't receive expected packets.
I can't reproduce this issue, and I suspect that packets are discared on fanout switch.
When we send a packet to a portchannel, we send one packet to each member of the portchannel.
Fanout switch will learn the source mac on both ports, and then we can avoid non congestion discards on fanout switch.
Run end to end test on different testbed.
=> Send packet to portchannel to improve test_vlan

tests/platform_tests/counterpoll/test_counterpoll_watermark.py
Summary:
Manually cherry-pick PR #10877
Close auto cherry-pick PR #10987
=> [manually cherry-pick PR10877] Fix test_counterpoll_watermark flakiness

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
This PR is to cherry-pick #11168 to `202305` branch after resolving conflicts.
There are some test cases being skipped or running on `x86_64-mlnx_msn2700-r0` platform. This PR is to update the `tests_mark_conditions.yaml` to apply the same operation to new platform `x86_64-mlnx_msn2700a1-r0`.
Skipped test cases:
- ecmp/inner_hashing/test_inner_hashing.py
- ecmp/inner_hashing/test_inner_hashing_lag.py
- ecmp/inner_hashing/test_wr_inner_hashing.py
- ecmp/inner_hashing/test_wr_inner_hashing_lag.py
- ecmp/inner_hashing/test_fgnhg_inner_hashing_internal.py
- ecmp/test_fgnhg.py
Test cases run on the new platform:
- vxlan/test_vxlan_ecmp.py
- vxlan/test_vxlan_crm.py
This PR is to update `tests_mark_conditions.yaml`  to apply the same operations to the new platform …
=> [202305][cherry-pick] Skip test cases on x86_64-mlnx_msn2700a1-r0 platform

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Update DualToR skip issues based on github issues or known limitations specific to a vendor. 
Add the skip conditions for DualToR
Run regression with the skip conditions.
Although some issues may affect all vendors, for now we only skip the tests on Nvidia platforms since we don't know for sure about the test results on other vendors.
It is recommended to take further look and adopt some of the ignore skip due to general issues observed.
=> Add xfail conditions for DualToR

tests/common/plugins/loganalyzer/__init__.py, tests/common/plugins/loganalyzer/loganalyzer.py
add 3 new flags:
store_la_logs - store loganalyzer errors in a file on the player
ignore_la_failure - do not fail the test if new errors were found 
loganalyzer_rotate_logs -rotate log on all the dut engines at the beginning of the loganalyzer
the default behavior is the same: rotate log, fail the test if nre errors were found and do not store the errors on the player.
Summary:
add the option to disable log rotation for the loganalyzer
add the option to store the log errors on the player
add the option to ignore loganalyzer failure
default behavior will not change!
add the option to disable log rotation for the loganalyzer, with adding the flag loganalyzer_rotate_logs=False
add the option to store the log errors on the player, with flag: store_la_logs=True and the function …
=> loganalyzer changes

tests/common/devices/sonic.py, tests/syslog/test_logrotate.py
Summary:
Use signals to pause/resume orchagent to reproduce the logrotate/pending APPL_DB entry issue
Tested with image 20201231.89 and verified that the test failed
Tested with image 20220531.38 and verified that the test passed
=> [syslog]: Add orchagent logrotate test

tests/copp/test_copp.py, tests/platform_tests/test_reload_config.py
Summary:
timing issue caused test_copp/test_reload_config test failure in nightly
refine timeout value for those cases
pass local test and nightly test
=> update timeout for reload_config_check and copp

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Let's ignore the error logs from `dualtor_neighbor_check` for now, because those error logs could be caused by transient inconsistencies.
Add to the ignore pattern list.
=> [loganalyzer][dualtor] Ignore `dualtor_neighbor_check` error logs

tests/qos/args/qos_sai_args.py, tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py
Fix issue:https://github.com/sonic-net/sonic-mgmt/issues/11156
1. When sending a burst packet, sometimes packets will lost on the server side, which will cause a test fail, so change the port speed to decrease the burst rate
2. When the previous test case just sends a large of packets only by one queue such as queue1, then Dwrr test might fail, because queue1 has got much chance to send packets before, so it will get less chance to send packets than expected. Therefore add one first run as a dry run, and it will not check Dwrr function. After the dry run, all tested queues can be scheduled so that all queues are at the same start.
Summary:
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/11156
Fix testQosSaiDwrr issue: https://github.com/sonic-net/sonic-mgmt/issues/11156
1. …
=> Fix testQosSaiDwrr issue

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/11203
=> [202305] Fix wrong skip condition in test_decap on 7260CX3

tests/common/helpers/portchannel_to_vlan.py
Summary:
Microsoft ADO: 26298422
Some po2vlan tests failed on new testbed, and this new testbed is using SONiC leaf fanout.
This leaf fanout does not support trunk mode, and tagged packets are discarded.
Skip po2vlan test for testbed with SONiC leaf fanout.
Run related po2vlan test.
=> Skip po2vlan test for sonic fanout

tests/dut_console/test_console_baud_rate.py
Summary:
If ManagementIP in inventory file contains "/", it wil cause test failure in test_console_baud_rate.
Add support for "/" in ManagementIP.
Run tests.
=> [console] Fix format issue in test_console_baud_rate

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip test_eth_interface_admin_change because it will cause testbed unhealthy
Skip it in conditional mark file
run generic_config_updater/test_eth_interface.py::test_eth_interface_admin_change on 7260 testbed
=> Skip test_eth_interface_admin_change for known issue

ansible/module_utils/port_utils.py, ansible/roles/fanout/tasks/fanout_sonic.yml, ansible/roles/fanout/tasks/sonic/copp_cfg_mlnx.j2, ansible/roles/fanout/tasks/sonic/fanout_sonic_202305.yml, ansible/roles/fanout/templates/sonic_deploy_202305.j2
Summary:
This PR is to support using SONiC 202305 image as leaf fanout switch OS.
Change list is as below.
- Update [port_utils.py](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:leaf_fanout_sonic_202305?expand=1#diff-2e3adf42b9b205770272a4157e3b5cf3c430d8b897f36be2a891d8aeb049cd86) to support mode SKUs
- Update [ansible/roles/fanout/tasks/fanout_sonic.yml](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:leaf_fanout_sonic_202305?expand=1#diff-7383b404a3b49cf1b0c810b5b2ab3c42879cb59e64d54fd8ea4f7ec03b95d153) to support deploying 202305 image in Leaf fanout switch
- Add configuration for Mellanox leaf fanout switch
This PR is to support deploying SONiC 202305 leaf fanout switch.
The change is verified by deploying a SN4700 device as leaf fanout …
=> Support using SONiC 202305 image as leaf fanout switch

tests/copp/test_copp.py, tests/platform_tests/test_reload_config.py
Reverts sonic-net/sonic-mgmt#11167
=> Revert "update timeout for reload_config_check and copp"

tests/conftest.py
Summary:
If ManagementIP in inventory file contains "/", it will cause test failure in DUT console related testcases.
Reference: #11249
If ManagementIP in inventory file contains "/", it will cause test failure in DUT console related testcases.
Add support for "/" in ManagementIP.
Verified by run testcase `dut_console/test_idle_timeout.py`.
=> [console] Fix format issue in common function `duthost_console`

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Cherry-pick PR https://github.com/sonic-net/sonic-mgmt/pull/11224 into 202205
=> [202205][loganalyzer][dualtor] Ignore `dualtor_neighbor_check` error logs

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Cherry-pick PR https://github.com/sonic-net/sonic-mgmt/pull/11224 into 202305
=> [202305][loganalyzer][dualtor] Ignore `dualtor_neighbor_check` error logs

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Cherry-pick PR https://github.com/sonic-net/sonic-mgmt/pull/11224 into 202311
=> [202311][loganalyzer][dualtor] Ignore `dualtor_neighbor_check` error logs

docs/testplan/dash/Dash-ACL-Tag-test-plan.md
Summary:
This is a new PR of #9844 since the original author Anton is not available now. 
There are 2 modifications comparing to 9844:
1. Add a test case "ACL Tag Remove IP Address" for the comment in 9844.
2. Removed the negative test case for it's not possible to test it with GNMI, the invalid configuration is validated and denied by the GNMI utils before it can be applied to the DPU.
Add testplan for DASH ACL Tag tests
For topology DPU
=> [DASH] Add testplan for DASH ACL Tag tests

ansible/group_vars/sonic/sku-sensors-data.yml
The MSN2700-A1 platform Sensor data inside sku-sensors-data.yml is not correct, this PR is intended to fix the wrong sensor data.
Summary:
Fix sensor test failure on the MSN2700-A1 platform.
Fix sensor test failure on the MSN2700-A1 platform.
Update the MSN2700-A1 platform Sensor data inside sku-sensors-data.yml. 
Run sensor test on the MSN2700-A1 platform.
Only relevant to MSN2700-A1 platform.
=> [Mellanox] Fix sensor data for platform MSN2700-A1

tests/acl/null_route/test_null_route_helper.py
test_null_route_helper.py deleting only DATAACL before starting the test and adding 2 new ACL tables in the test case.
If there is no enough hardware resource, the second table creation fails. For successful creation of 2 new acl tables, deleting one more acl table to free-up space.
Summary:
- [*] 202305
=> Removing Everflow acl table along with DATAACL to free hw resources for test_null_route_helper.py

tests/conftest.py
Backport #11281
If ManagementIP in inventory file contains "/", it will cause test failure in DUT console related testcases.
Add support for "/" in ManagementIP.
Verified by run testcase dut_console/test_idle_timeout.py.
Summary:
=> [202311][console] Fix format issue in common function duthost_console (#11281)

.azure-pipelines/testbed_health_check.py
Enhance testbed health check script.
- Make the script always execute to the end, catch any errors and log the results
- Check duthost and fanouthost reachability in pre-check
=> [Enhance] Enhance testbed health check script

azure-pipelines.yml
Summary:
Refine branch setting, automatically choose test branches
So that new branch-outed feature branch has the correct branch setting
=> [PR Test] refine branch setting, automatically choose test branches

spytest/apis/qos/qos.py
Summary:
Added sleep time based on chip
our local daily runs
=> upstream qos api changes

ansible/group_vars/sonic/sku-sensors-data.yml, tests/common/mellanox_data.py, tests/platform_tests/conftest.py
1. Update mellanox_data for ACS-MSN4700
2. Update sensor data for ACS-MSN4700
3. Update skip_on_simx to support ACS-MSN4700
Summary:
Update data for simx ACS-MSN4700
update mellnanox data and sensor data for ACS-MSN4700
Update skip_on_simx to support ACS-MSN4700
Run platfrom tests on simx ACS_MSN4700
simx ACS_MSN4700
Any
=> [Mellanox] Update for simx ACS-MSN4700

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:  Skip err msg for the known issue :
https://github.com/sonic-net/sonic-buildimage/issues/7895
https://github.com/Azure/sonic-sairedis/issues/582
This is a PR to fix the chery-pick conflict for the : https://github.com/sonic-net/sonic-mgmt/pull/10396
=> Skip err msg for the known issue

.azure-pipelines/pr_test_scripts.yaml, azure-pipelines.yml
Summary:
[202211, PR test] Update PR test settings
=> [202211, PR test] Update PR test settings

tests/show_techsupport/conftest.py
Summary: The err msg could be ignored when run the techsupport. there is also a github issue related to the err msg that added to the ignore list: https://github.com/sonic-net/sonic-buildimage/issues/15051
Ignore some err msg for the techsupport test case
=> [techsupport] Add err msg ignore for techsupport test

tests/tacacs/test_authorization.py
Summary:
PR backport to 202311
https://github.com/sonic-net/sonic-mgmt/pull/11481
=> [202311] enhance test_authorization_tacacs_only case since slim image has no telemetry

tests/tacacs/test_authorization.py
Summary:
PR backport to 202305
https://github.com/sonic-net/sonic-mgmt/pull/11481
=> [202305] enhance test_authorization_tacacs_only case since slim image has no telemetry 

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
cherry pick #11027
cherry pick #11027
=> [202305]Remove some skip condition for test_iface_loopback_action

tests/bgp/test_traffic_shift.py, tests/conftest.py
Cherry pick conflict #9821
Summary:
Cherry pick conflict #9821
=> [202012] Skip checking expected core dump in module `bgp/test_traffic_shift.py`.

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
cherry pick https://github.com/sonic-net/sonic-mgmt/pull/11382/files to 202305
=> [202305]Disable iface_loopback_action tests on Broadcom switches

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip test_replace_fec because it will cause testbed unhealthy on 3800 and 7260 devices (issue tracked in https://github.com/sonic-net/sonic-mgmt/issues/11237)
Skip in conditional mark file
=> Skip test_replace_fec for known issue

spytest/apis/system/boot_up.py, spytest/apis/yang/utils/query_param.py
Summary:
added query_param file
=> upstream changes in API

spytest/apis/system/boot_up.py, spytest/apis/system/system_server.py
=> upstream changes in API system_server.py

spytest/apis/system/boot_up.py, spytest/apis/system/snmp.py
=> upstream changes in API snmp.py

spytest/apis/qos/copp.py
=> upstream copp latest changes

spytest/apis/routing/bgp.py
Summary:
changes to support bgp community list
=> upstream bgp changes to community

spytest/apis/system/boot_up.py, spytest/apis/system/snapshot.py
=> upstream changes in API snapshot

spytest/apis/system/boot_up.py, spytest/apis/system/in_memory.py
=> upstream changes in API in_memory.py

spytest/apis/system/boot_up.py, spytest/apis/system/crm.py
=> upstream changes in API crm.py

spytest/apis/system/boot_up.py, spytest/apis/system/config_qos.py
=> upstream changes in config_qos.py

spytest/apis/system/boot_up.py, spytest/apis/system/box_services.py
=> Api boxser

spytest/apis/qos/qos.py, spytest/apis/routing/arp.py
Summary:
added 2 APIs
in our local daily runs
=> Upstream API file arp.py

spytest/apis/system/boot_up.py, spytest/apis/system/connection.py
=> upstream changes in API connection.py

spytest/apis/system/boot_up.py, spytest/apis/system/ztp.py
Summary:
added new APIs for ztp
=> upstream changes in API ztp.py

spytest/apis/system/boot_up.py, spytest/apis/system/storm_control.py
=> upstream changes in API storm_control.py

spytest/apis/system/boot_up.py, spytest/apis/system/config_session.py
Summary:
added new APIs for config session
=> Api confsess

spytest/apis/system/boot_up.py
=> upstream changes in API boot_up.py
