sonic-net/sonic-mgmt

ansible/host_vars/switch1/minigraph_facts.yml, ansible/roles/sonic-common/tasks/main.yml
Add interfaces config and update minigraph_facts.yml
Signed-off-by: John Arnold <johnar@microsoft.com>
=> Add interfaces config and update minigraph_facts.yml

ansible/roles/sonic-common/tasks/sonicdocker.yml, ansible/roles/sonic-common/tasks/sudoers.yml, ansible/roles/sonicv2/tasks/sonic-brcm.yml, ansible/roles/sonicv2/tasks/sonic-mlnx.yml, ansible/roles/sonicv2/tasks/sonicdocker.yml
Signed-Off-By: John Arnold <johnar@microsoft.com>
=> Bugfix: remove platform container references, fix v1 removal for mellanox. Pull latest updates

ansible/deploy_docker_registry.yml, ansible/roles/docker_registry/tasks/main.yml
=> Add deploy_docker_registry playbook

ansible/group_vars/sonic/vars, ansible/group_vars/sonic_latest/package_versions.yml, ansible/roles/sonic-common/tasks/main.yml, ansible/roles/sonicv2/tasks/quagga.yml, ansible/roles/sonicv2/templates/etc/ssw/AS7512/profile.ini.j2, ansible/roles/sonicv2/templates/etc/ssw/XP-SIM/profile.ini.j2
Add changes for cavium platform support
=> Support for cavium platform: initial commit

ansible/roles/sonic-common/tasks/database.yml, ansible/roles/sonic-common/tasks/sonicdocker.yml, ansible/roles/sonicv2/tasks/quagga.yml, ansible/roles/sonicv2/tasks/sonic-brcm.yml, ansible/roles/sonicv2/tasks/sonic-mlnx.yml
- All containers share the domain socket directory of redis-server
=> Containers share the domain socket directory of redis-server

ansible/roles/test/files/tools/loganalyzer/loganalyzer.py
* loganalyzer.py - log analyzer to analyze system log file and
additionally specified input files.
signed-off-by: hrachya@mellanox.com
=> [loganalyzer] implementation with sample files

ansible/roles/test/files/acstests/fib_test.py, ansible/roles/test/files/tools/loganalyzer/loganalyzer_analyze.yml, ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_match.txt, ansible/roles/test/files/tools/loganalyzer/loganalyzer_end.yml, ansible/roles/test/files/tools/loganalyzer/loganalyzer_init.yml, ansible/roles/test/tasks/fib.yml, ansible/roles/test/tasks/fib/fib_match_messages.txt, ansible/roles/test/templates/fib.j2
* yml files to invoke loganalyzer
* loganalyzer match and ignore files common for all tests
* fib_tst.yml which invokes loganalyzer yml files.
signed-off-by hrachya@mellanox.com
=> [ansible][FIB][loganalyzer] Ansible scripts to invoke FIB test and loganalyzer

ansible/roles/sonicv2/templates/etc/systemd/system/syncd.j2
Signed-off-by: Nadiya.Stetskovych <Nadiya.Stetskovych@cavium.com>
=> Add xpnet start/stop

ansible/roles/sonicv2/tasks/sonic-cavm.yml
Signed-off-by: Nadiya.Stetskovych <Nadiya.Stetskovych@cavium.com>
=> Make cavium containers share the domain socket directory of redis-server

ansible/roles/test/files/acstests/lag_test.py, ansible/roles/test/files/acstests/router_utils.py, ansible/roles/test/files/tools/loganalyzer/loganalyzer_analyze.yml, ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_match.txt, ansible/roles/test/files/tools/loganalyzer/loganalyzer_init.yml, ansible/roles/test/tasks/lag.yml, ansible/roles/test/templates/lag.j2
* Ansible scripts for running LAG test
* j2 file to generate lag info, consumed by lag_test.py
* common code which will be used by lag/fib/ip decap tests.
* test run-time ~ 60sec
=> [LAG] LAG test code and ansible files

ansible/roles/test/files/acstests/lag_test.py, ansible/roles/test/files/acstests/router_utils.py
=> [LAG] Add support for ipv6

ansible/roles/test/files/acstests/lag_test.py, ansible/roles/test/tasks/lag.yml, ansible/roles/test/tasks/per_lag_member_test.yml, ansible/roles/test/tasks/per_lag_test.yml, ansible/roles/test/templates/lag.j2
* Added test to send traffic while flapping lag interfaces.
Signed-off-by: Hrachya Mughnetsyan <hrachya@mellanox.com>
=> [LAG][test] Flap lag interfaces on DUT

ansible/roles/sonicv2/files/bin/sonic_support, ansible/roles/sonicv2/tasks/main.yml
Differences from original:
Add redis dump
Add saidump call
Remove brcm (vendor data to be dumped via SAI API)
=> Integrate dump script

ansible/roles/sonicv2/tasks/sonic-cavm.yml
Signed-off-by: Nadiya.Stetskovych <Nadiya.Stetskovych@cavium.com>
=> Fix sonicdocker path for cavm

ansible/host_vars/STR-ACS-SERV-01.yml, ansible/host_vars/STR-ACS-SERV-02.yml, ansible/library/minigraph_facts.py, ansible/roles/eos/tasks/main.yml, ansible/roles/eos/templates/t0-64-leaf.j2, ansible/roles/fanout/tasks/rootfanout_connect.yml, ansible/roles/test/tasks/lldp.yml, ansible/roles/test/tasks/lldp_neighbor.yml, ansible/roles/test/tasks/ptf_runner.yml, ansible/roles/vm_set/tasks/main.yml, ansible/roles/vm_set/tasks/start.yml, ansible/roles/vm_set/templates/cleanup.sh.j2, ansible/vars/topo_t0-64.yml
It contains:
- new testbed topology: t0-64
- script for cleaning testbed after power outage
- fixes for the testbed server configuration which permits bridging in kernel
- some fixes for Ansible 2.2
=> Update from our private mgmt repo

ansible/roles/test/tasks/everflow.yml
Fix issue observed when tests are run without "everflow" tag.
=> [everflow_tests]: Fix error in everflow.yml

ansible/roles/eos/templates/t1-lag-spine.j2
Fix for this issue https://github.com/Azure/sonic-mgmt/issues/143
=> Make lacp rate normal t1-lag testbed

ansible/veos
=> Add t0-64 into veos inventory file

ansible/roles/test/files/ptftests/dhcp_relay_test.py
- This PR is dependent upon https://github.com/p4lang/ptf/pull/67.
=> Fix DHCP Relay Test bugs

ansible/roles/test/files/tools/loganalyzer/loganalyzer_end.yml
Signed-off-by: marian-pritsak <marianp@mellanox.com>
=> [loganalyzer]: Rename sonic_support to generate_dump

ansible/roles/test/files/ptftests/copp_tests.py
Sometimes ptf_nn_agent doesn't work on remote side. In this case copp ptf test works for ever and never stops. This code will stop test itself after 5 minutes of running
=> [copp]: Timeout a testcase if it lasts more than 5 minutes

.gitignore, ansible/library/minigraph_facts.py, ansible/roles/test/files/ptftests/dhcp_relay_test.py, ansible/roles/test/tasks/dhcp_relay.yml
- Also resolves #173 
- Also remove unused line from minigraph_facts.py
- Also add .gitignore file and ignore compiled Python files in plugins/ directory
=> [DHCP Relay test]: Update test to verify new Option 82 field contents

ansible/roles/test/files/tools/loganalyzer/loganalyzer_analyze.yml, ansible/roles/test/files/tools/loganalyzer/loganalyzer_init.yml
- Reduce list of variables required to run loganalyzer.
=> [loganalizer]: Simplify init/analyze procedure for loganalyzer.

ansible/roles/test/tasks/fdb.yml
- also remove supervisorctl path
=> [fdb]: Update FDB test to support t0-64 topology

ansible/library/minigraph_facts.py
This change fixes the port mapping for 7260CX3 platforms.
The issue was caught by SNMP Test and validated by SNMP Test.
=> [minigraph_fact] fix Arista 7260CX3 platform port mapping

ansible/group_vars/sonic/sku-sensors-data.yml
This is a preliminary definition for sensors test, it is in no sense complete.
Adding these information will enable sensors test though.
=> [sensors test] add preliminary sensors definitions for Arista 7260CX3 platform

ansible/boot_onie.yml
Signed-off-by: Qi Luo <qiluo-msft@users.noreply.github.com>
=> After boot_onie, admin up all bgp interfaces

ansible/plugins/connection/switch.py
Adding  Dell Platform to  determine the sku in show verison.
=> Adding Dell platform

ansible/library/minigraph_facts.py
This issue was introduced by my change earlier.
=> [minigraph_facts] add the missing brace

ansible/templates/topo/t0-64.j2, ansible/templates/topo/t0.j2
=> [minigraph_template]fix t0 templates for generate minigraph

ansible/templates/topo/t0-64.j2, ansible/templates/topo/t0.j2
=> increase length of t0 portchannel interface name

ansible/roles/test/tasks/acltb.yml
Signed-off-by: Qi Luo <qiluo-msft@users.noreply.github.com>
=> Copy acsbase files to ptf before ptf_runner

ansible/roles/test/tasks/pfc_wd/config_test/config_test.yml, ansible/roles/test/tasks/pfc_wd/functional_test/functional_test.yml, ansible/roles/test/templates/pfc_wd_config.j2
Changes include:
- Adaptation to Config DB
- Counters verification
- Ingress traffic verification
- Timers adjustments
Signed-off-by: marian-pritsak <marianp@mellanox.com>
=> [pfc_wd]: Rework for P2

ansible/group_vars/sonic/sku-sensors-data.yml
Change has been tested on 7260/7060 device.
=> [sensors] add sensor definitions for arista 7260/7060

ansible/group_vars/sonic/sku-sensors-data.yml
As the the sensor labels from the output of the "sensors" command have been changed, the sensor labels used in the test for verification also have to be updated. 
- [+] Bug fix
=> Change sensor labels for Arista 7050 and 7260

ansible/testbed-cli.sh
add connect_topo command for testbed-cli.sh for connecting topology to the DUT
run testbed-cli.sh connect-topo toponame
added testbed-cli command help
=> add connect_topo command for testbed-cli.sh

ansible/roles/test/files/helpers/arp_responder.py
convert the interface from unicode to string
run arp responder manually in vlantb test case
=> [bug]: convert the interface from unicode to string

ansible/roles/test/tasks/bgp_speaker.yml
Signed-off-by: Sihui Han <sihan@microsoft.com>
Always clean up test environment after test finishes
Run the test on DUT
=> [bgp_speaker]: always clean up test environment after test finishes 

ansible/roles/test/vars/testcases.yml
some outside job also need restart swss, make it callable as a test name
added one test name which calling already existed task file
locally validated on my dut
no
any
=> add restart_swss

ansible/group_vars/sonic/vars, ansible/roles/test/vars/testcases.yml
- deprecated unused variable.
- fix a typo in fdb test case.
- enable t0 and t0-116 for IP decap test
- rename sensors_check to sensors to match test tag.
- some cosmetic changes
I wasn't able to test all test cases. Following test cases were tested after the changes:
sensors, fib, fdb, decap, dhcp_relay, mem_check
=> [Test cases] clean up some test cases changes and enabling more tests

ansible/roles/test/tasks/run_command_with_log_analyzer.yml
Signed-off-by: Qi Luo <qiluo-msft@users.noreply.github.com>
Fixes https://github.com/Azure/sonic-utilities/pull/177#issuecomment-355436852
How did you verify/test it? Run ACL Test locally
=> Run sudo command with log_analyzer

ansible/group_vars/all/labinfo.json
Updated labinfo file with Arista fanout sku
How did you do it? 
Updated the HWSKU for fanout
Tested on DUT
=> Updated labinfo file with Arista fanout sku

ansible/roles/test/tasks/base_sanity.yml, ansible/roles/test/tasks/test_sonic_by_testname.yml
- How did you do it?
add an orchagent process check in sanity check task
add a sanity check after each test run
- How did you verify/test it?
tested in my local testbed and it was working
=> add orchagent process check before each test and sanity after each test

ansible/library/snmp_facts.py, ansible/roles/test/tasks/snmp/pfc_counters.yml, ansible/roles/test/tasks/snmp/queues.yml
Added a new SNMP tests to cover PFC and Queue counters MIBs. 
If you want new tests to your testbed then you just need to add the new tags to your "sonic.yml" file. 
```
- name: Test SNMP Queues
include: snmp/queues.yml
tags: snmp_queues
- name: Test SNMP PFC counters
include: snmp/pfc_counters.yml
tags: snmp_pfc
```
- Test case(new/improvement)
Gather relevant information from SNMP agent on DUT
It was tested on MLNX platforms which supports PFC and Queue counters. 
No
Yes, they are new test cases.
=> Added SNMP PFC and Queue tests

ansible/roles/test/tasks/pfc_wd/functional_test/functional_test.yml
This is an urgent fix for playbook other than pfc.
=> Workaround ansible issue: with_sequence include will ignore upper level tags

ansible/roles/test/tasks/ecn_wred.yml
Follow up https://github.com/Azure/sonic-mgmt/pull/384
=> Fix set_fact tags, so playbook unrelated will work correctly

ansible/roles/test/vars/testcases.yml
Updated missing test case to testcases.yml file
Execute the command to run the testcase by _name_ 
N/A
N/A
=> Added directed broadcast test to testcases list

ansible/group_vars/sonic/vars
need change one more place for new hwsku
add new hwsku to correct group
tested in local testbed
=> [hwsku]one more place for hwsku of new Mellanox 2700

ansible/group_vars/sonic/sku-sensors-data.yml
Fixes DellS6000 sensors test fail
- How did you do it?
DellS6000 sensors test always fail due to wrong check module/parameters after image sensor module change, remove the wrong module name
- How did you verify/test it?
tested it in my local testbed and it passed
=> [sensors]fix Dell S6000 sensors test fail

ansible/ansible.cfg
enable gathering fact by default
- How did you do it?
we have seen some failure cases due to ansible facts caching during running/debugging test cases
change the ansible.cfg for fact gathering option from smart to implicit in the effort to solve such issue
- How did you verify/test it?
tested in local testbed, no side effect found
=> [ansible]gather fact by default

ansible/roles/test/tasks/test_sonic_by_tag.yml
comment out test tag of pfc_wd
comment out pfc_wd test in test_sonic_by_tag.yml
newly improved pfc_wd test works better with specify testname in roles/test/var/testcases.yml
when run other testcases by tag, trying include pfc_wd related yaml file will error out. 
verified in my local testbed
=> [test_tag]remove pfc_wd test tag from test by tag main yaml

ansible/library/extract_log.py
I've added additional timestamp format used in SONiC log files.
Changed extract_log.py
I've run it in our testbed
=> Add support for additional timestamp format

ansible/roles/test/tasks/snmp.yml
add newly added snmp counters test to main snmp.yml
add newly added SNMP counters test to main snmp.yml
tested in my local testbed and it works
=> [SNMP]add new SNMP tests to main snmp.yml

ansible/group_vars/sonic/sku-sensors-data.yml
Update Sensor data for Dell Z9100 platform
Update the sensor data for Z9100
Verified on Dell Z9100 platform
=> Adding sensor data for Dell  Z9100

ansible/group_vars/sonic/sku-sensors-data.yml
=> Adding sensor data for S6100

ansible/templates/topo/t1-64-lag.j2
=> [topology]: Update t1-64-lag topology template to add AclInterfaces piece

ansible/roles/test/tasks/acltb.yml
=> [acl_test]: Add ptf_platform_dir: ptftests to use customized platform code to support 64 ports

ansible/plugins/action/onie.py
We don't need this retry logic. If anything bad happens, I will follow up with small scope fix.
=> Disable upgrade_sonic retry

ansible/roles/test/files/tools/loganalyzer/loganalyzer_end.yml
generate_dump command must be run as root (or in sudo)
=> [log_analyzer]: Add become: true to generate_dump command

ansible/library/topo_facts.py, ansible/minigraph/lab-s6100-01.t1-64.xml, ansible/testbed.csv, ansible/vars/topo_t1-64.yml
Signed-off-by: Shuotian Cheng <stcheng_89@hotmail.com>
=> [topo_t1-64]: Add topo_t1-64.yml to support ptf64 topology

ansible/library/bgp_facts.py
- "admin": "down" or "admin": "up" will be added to the result
- "ip_version": 6 or "ip_version": 4 will be added to the result
=> [bgp_facts]: Add support to parse admin down and IPv4/IPv6

ansible/roles/test/templates/pfc_storm_mlnx.j2
Signed-off-by: Andriy Moroz <c_andriym@mellanox.com>
Updated storm generation template to use new script which supports storm on multiple ports.
=> Update MLNX storm template to support storm on all ports

ansible/roles/test/tasks/acltb.yml
Missing root privilege for config save
How did you do it? Modified the yml script
How did you verify/test it? Run the test on device
=> Root privileges for config save

ansible/roles/test/tasks/acltb.yml
Added changes to ensure acltb_test_rules-del.json is copied after reload
=> Modified clean up section in acltb.yml

ansible/plugins/connection/switch.py
Signed-off-by: Sihui Han <sihan@microsoft.com>
=> [connection]: Increase switch connection timeout

ansible/plugins/connection/switch.py
Signed-off-by: Sihui Han <sihan@microsoft.com>
=> [switch]: increase prompt waiting timeout

ansible/group_vars/sonic/vars
One of the tests uses mellanox_hwskus variable, need to update it.
=> [hwsku] add ACS-MSN2740, ACS-MSN2100, ACS-MSN2410

ansible/roles/test/files/tools/loganalyzer/loganalyzer.py, ansible/roles/test/files/tools/loganalyzer/loganalyzer_analyze.yml, ansible/roles/test/files/tools/loganalyzer/loganalyzer_init.yml
=> Revert "[LogAnalyzer]: Accumulate syslog files rather than force logrotate"

ansible/roles/test/vars/testcases.yml
Remove a test that was added to testcases.yml by mistake. 
https://github.com/Azure/sonic-mgmt/issues/648
Modified testcases.yml
=> [testcases] remove changes made by mistake

ansible/roles/test/tasks/pfc_wd.yml
Signed-off-by: Sihui Han <sihan@microsoft.com>
Summary:
- [] Bug fix
Reduce the number of tested port each day. It takes hours for platforms that have hundreds of ports.
Tested on DUT
=> [pfcwd]: reduce the number of tested port each day

ansible/roles/test/files/acstests/acltb_test.py, ansible/roles/test/tasks/acl/acltb_test_rules.json, ansible/roles/test/tasks/acl/acltb_test_rules_part_2.json
How did you do it? Added a rule in the json file that calls for dropping of udp packets
How did you verify/test it? In my local. Both using ansible and running python script in PTF container. Create a rule that denies udp packets. Create a simple udp packet and verify it is not received on any ports.
Any platform specific information? No
Supported testbed topology if it's a new test case? t1, t1-lag, t1-64-lag
https://github.com/Azure/sonic-mgmt/pull/466
[I have been having git uses in my local, created this new branch to reflect cleaner changes made for above, previous pull request]
=> Acl udp test

ansible/library/snmp_facts.py, ansible/roles/test/tasks/snmp.yml, ansible/roles/test/tasks/snmp/phys_table.yml
Summary:
Extend snmp test case to support xcvrd snmp test
- [] Bug fix
Add new test cases in snmp test to test xcvrd feature
detail see test plan [https://github.com/Azure/SONiC/blob/gh-pages/doc/xcvrd-snmp-testbed-test-plan.md](url)
run test on mlnx platform.
Test plan link:  [https://github.com/Azure/SONiC/blob/gh-pages/doc/xcvrd-snmp-testbed-test-plan.md](url)
=> [snmp] extend snmp test for xcvrd

ansible/TestbedProcessing.py, ansible/doc/README.new.testbed.Configuration.md, ansible/roles/test/tasks/syslog.yml, ansible/testbed-new.yaml
Summary:
The script TestbedProcessing.py can generate testbed configuration based on testbed-new.yaml .
- [] Bug fix
python TestbedProcessing.py testbed-new.yaml
output files created:
[1]  /group_vars/vm_host/main.yml
[2]  /group_vars/vm_host/creds.yml
[3]  /files/sonic_lab_devices.csv
[4]  /testbed.csv
[5]  /files/sonic_lab_links.csv
[6]  /group_vars/eos/creds.yml
[7]  /group_vars/fanout/secrets.yml
[8]  /group_vars/lab/secrets.yml
[9]  /lab
[10] /veos
[11*] /host_vars/<host_var>.yml (where * is 0 or more)
no.
all.
Refer testbed-new.yaml description.
=> New Testbed Configure File and Script

ansible/roles/test/files/ptftests/copp_tests.py
Summary:
Fixes #685 
Ignore the packets received in the first second because of CBS.
- [] Bug fix
Update copp_tests.py
-- add variable - needSlip to determine if need ignoring packets in the first second (PolicyTest)
-- add thread - slipSometime, flush dataplane after 1 second.
locally test.
Compare the statistics of **RX PPS**
None
N/A
=> [copp] skip packets in the first second for PolicyTest

ansible/roles/test/files/ptftests/IP_decap_test.py
=> [IPinIP] Remove ip range slicing added by mistake

ansible/roles/test/tasks/snmp/pfc_counters.yml
Will be cherry-picked to 201803 branch after merged.
=> Ignore mamagement ports when checking PFC counters

ansible/roles/test/files/saitests/pfc_asym.py, ansible/roles/test/tasks/pfc_asym.yml, ansible/roles/test/tasks/pfc_wd.yml, ansible/roles/test/tasks/test_sonic_by_tag.yml, ansible/roles/test/templates/pfc_storm_arista.j2, ansible/roles/test/templates/pfc_storm_mlnx.j2, ansible/roles/test/vars/testcases.yml
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>
Summary:
Add test for the asymmetric PFC feature
- [] Bug fix
Implemented new ansible test for the asymmetric PFC feature
Executed test on T0 topology and verified then is is passing each time
```
$ ansible-playbook test_sonic.yml -i inventory --limit testbed-t0 -e testbed_name=<testbed>-t0 -e testbed_type=t0 -e testcase_name=pfc_asym
```
N/A
Supports only T0 topology (asymmetric PFC is only for T0)
https://github.com/Azure/SONiC/wiki/Asymmetric-PFC-High-Level-Design
=> [pfc_asym]: Add test for the asymmetric PFC feature

ansible/group_vars/sonic/vars
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
Update *mellanox_hwskus* group variable used in some tests.
Summary:
- [] Bug fix
Update mellanox_hwskus group variable used in some tests.
=> [hwsku] add MSN2010 to mlnx hwsku list

ansible/group_vars/sonic/sku-sensors-data.yml, ansible/group_vars/sonic/vars
Modify sensor data to match with the latest hw-mgmt
Add sensor data for SN2010
Signed-off-by: Kevin Wang <kevinw@mellanox.com>
Summary:
- [] Bug fix
=> [sensors] Modify sensor data according to latest hw-mgmt

ansible/roles/test/tasks/snmp/lldp.yml
Summary:
- Provide more detailed task name
- Fix some asserts
=> [snmp] enhance/fix lldp mib subtest

ansible/roles/test/tasks/everflow_testbed/get_session_info.yml
These changes are intended to align everflow testcase with the recent changes in MLNX SAI
Summary:
* N/A
- [] Bug fix
GRE type will be updated if running everflow testcase on MLNX platforms
Verified on MLNX platforms
* N/A
* N/A
* N/A
=> Fixed Mellanox GRE protocol type

ansible/config_sonic_basedon_testbed.yml
Otherwise the config change will not take effect.
=> Restart automatic minigraph update service after changing conf

ansible/library/minigraph_facts.py
Add Arista-7060CX-32S-C32-T1 
Summary:
- [] Bug fix
=> Add T1 HWSKU for Arista

ansible/roles/test/tasks/test_sonic_by_testname.yml
=> [test]: Fix typo

ansible/group_vars/all/labinfo.json, ansible/group_vars/sonic/vars, ansible/library/minigraph_facts.py
=> Arista 7170 added to topology, sku updates

ansible/roles/test/files/acstests/acltb_test.py
=> [acl]: Fix print out wrong information

ansible/roles/test/files/acstests/acltb_test.py, ansible/roles/test/templates/acltb.j2
Signed-off-by: Shuotian Cheng <stcheng_89@hotmail.com>
=> [acl]: Enable ACL test on t1-64-lag topology

ansible/group_vars/sonic/sku-sensors-data.yml
=> Add Arista 7170 platform to sensors check

ansible/roles/test/files/ptftests/advanced-reboot.py
Fix previous PR #758: this is a missing commit which collect portchannel last status change time
=> Add portchannel last status change time into collected data

ansible/roles/test/tasks/sonic.yml
=> allow user to pass testbed file to run test

ansible/lab, ansible/vtestbed.csv
=> add ptf_vms6-1 in lab inventory

ansible/roles/test/tasks/sonic.yml
=> set default testbed file for test

ansible/config_sonic_basedon_testbed.yml
=> [testbed] define default testbed file name

ansible/roles/test/files/ptftests/advanced-reboot.py
Summary:
- Fix syntax error when warm reboot test observed no data plane disruption.
- Update BGP graceful restart timeout default value to match SONiC default.
- warm reboot test
- fast reboot test
=> [warm/fast reboot] fix warm reboot test issue and update bgp graceful restart timeout

ansible/doc/README.testbed.VsSetup.md
=> [doc]: update vs testbed setup doc

ansible/doc/README.testbed.VsSetup.md
=> minor update VS testbed step doc

ansible/roles/test/tasks/neighbour-mac.yml
Fixed neighbor test case
Signed-off-by: Vitaliy Senchyshyn [vsenchyshyn@barefootnetworks.com](mailto:vsenchyshyn@barefootnetworks.com)
Summary:
- [] Bug fix
Replaced "ifconfig" with SONiC CLI command for interface IP on DUT change 
Tested on Barefoot Networks paltform
=> [ansible] Fix neighbor test case

ansible/roles/test/tasks/config.yml, ansible/roles/test/vars/testcases.yml
- [] Bug fix
Enable config test case for T0-116 topology
- Remove topology check in config.yml since testcase is already gating topology list.
Manually executed this test case on my DUT.
=> [config test] enable config test case for T0-116 topology

ansible/roles/vm_set/tasks/main.yml
=> Fix for permission

ansible/group_vars/sonic/sku-sensors-data.yml
Added sensor configs for new Mellanox platforms: SN3700 and SN3700C
- [N/A] Bug fix
- [N/A] Testbed and Framework(new/improvement)
- [sensors] Test case(new/improvement)
1. Added sensor configs for SN3700 and SN3700C
1. Executed sensors test
* N/A
* N/A
* N/A
=> Added sensors config for new Mellanox platforms: SN3700 and SN3700C

ansible/testbed-cli.sh
Summary:
There are some duplicated case branches in the testbed-cli.sh script. Simply removed them.
Removed the duplicated case branches in testbed-cli.sh.
=> Remove duplicated case branches in testbed-cli.sh

ansible/roles/test/templates/pfc_wd_config.j2
Summary:
- [] Bug fix
Change pfc watchdog table PFC_WD_TABLE --> PFC_WD (the table name is changed in sonic image)
manually run pfc_wd test
=> [pfc_wd] change pfc watchdog table name according to the sonic code change

ansible/swap_syncd.yml
Depends on https://github.com/Azure/sonic-buildimage/pull/2782
=> Scrub credential in `docker pull` command line

ansible/library/minigraph_facts.py
Fix bug introduced by https://github.com/Azure/sonic-mgmt/pull/674
=> [minigraph] Fix minigraph parsing error on Mellanox-SN2700-D48C8

tests/ansible_host.py
now test work with ansible-2.7
Summary:
- [] Bug fix
```
========================================================= test session starts ==========================================================
platform linux2 -- Python 2.7.12, pytest-4.3.0, py-1.8.0, pluggy-0.9.0 -- /usr/bin/python
ansible: 2.7.0
rootdir: /data/sonic-mgmt/tests, inifile: setup.cfg
plugins: ansible-2.0.1
collected 4 items                                                                                                                      
test_bgp_fact.py::test_bgp_facts PASSED                                                                                          [ 25%]
test_bgp_speaker.py::test_bgp_speaker PASSED …
```
=> [pytest]: use AdHocResult to determine if there is module failure or not

ansible/templates/minigraph_dpg.j2
=> [minigraph]: Fix indentation

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Summary:
Modified sensors data for S6100/Z9100 according to latest output
updated sensors variables according to the output
dell platforms (Z9100, S6100)
This need to be merged after the PR Azure/sonic-buildimage#2861 is merged
=> [201811]Modified sensors data for S6100/Z9100 according to latest output

ansible/roles/test/files/ptftests/advanced-reboot.py
=> [advanced-reboot] fix fast-reboot failure (DUT is flooding always)

ansible/roles/test/files/ptftests/dhcp_relay_test.py
The pull request https://github.com/Azure/sonic-buildimage/pull/2857 in sonic-buildimage will cause the dhcp_relay test to erroneously fail, due to minor changes in the relayed OFFER and ACK packets. This change will ensure the dhcp_relay test works as expected after the aforementioned PR is merged.
=> [201803][dhcp_relay] More detailed crafting and strict testing of OFFER and ACK packets

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Modified sensors data for S6100 according to latest output
Updated sensors variables according to the output
Dell platform S6100
=> [201811]: Updated S6100 sensors data

ansible/roles/test/tasks/advanced-reboot.yml, ansible/roles/test/tasks/arpall.yml, ansible/roles/test/tasks/common_tasks/reload_config.yml, ansible/roles/test/tasks/common_tasks/update_supervisor.yml, ansible/roles/test/tasks/neighbour-mac-noptf.yml, ansible/roles/test/tasks/pfc_asym.yml, ansible/roles/test/tasks/vlan_cleanup.yml, ansible/roles/test/tasks/vlan_test.yml, ansible/roles/test/tasks/vnet_vxlan.yml, ansible/roles/test/tasks/vxlan-decap.yml
Added common tasks for supervisor update and sonic config reload
- [improvement] Testbed and Framework
* Refactored code: added reload_sonic.yml and update_supervisor.yml
* Executed relevant test cases
* N/A
* N/A
* N/A
=> Added common tasks for supervisor update and sonic config reload

ansible/roles/test/files/ptftests/vnet_vxlan.py, ansible/roles/test/tasks/vnet_vxlan.yml
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>
Summary:
- [] Bug fix
Extended VNET test with "remove" flows
Executed VNET test and verified it passed
N/A
N/A
N/A
=> [vnet]: Extend VNET test with "remove" flows

ansible/roles/test/tasks/iface_naming_mode/add_user.yml, ansible/roles/test/tasks/iface_naming_mode/iface_naming_mode_tests.yml
Summary:
Add "become: yes" when creating user or removing user.
- [] Bug fix
Add "become: yes" when creating or removing user.
Run iface_mode test without permission denied error.
Resolves https://github.com/Azure/sonic-mgmt/issues/938
=> [iface_mode]: Add become for creating or removing user

ansible/roles/test/tasks/vnet_vxlan.yml
Summary:
Condition was not checked for route delete. Added clean-up check
=> Added clean-up check to a missed execution

ansible/roles/test/tasks/copp.yml
Change-Id: I29d8d7c892790e8383edf491bceb9ac9aa61ca06
Summary:
- [] Bug fix
=> [mlnx] remove call to removed file disable_copp_rate_limiting.sh

ansible/roles/test/tasks/link_flap.yml, ansible/roles/test/tasks/link_flap/link_flap_helper.yml
Improved link flap test: added smart timeout
* Test case improvement
* Added smart timeout
1. Ran link flap test
* N/A
* N/A
* N/A
=> Improved link flap test: added smart timeout

ansible/roles/test/tasks/everflow_testbed/testcase_8.yml
=> [everflow]: Fix the tearing down procedure order

ansible/roles/test/files/mlnx/upgrade_mlnx_fw.sh, ansible/roles/test/tasks/advanced-reboot.yml, ansible/roles/test/tasks/advanced_reboot/upgrade_mlnx_fw.yml
Upgrade firmware for Mellanox platforms before fast-reboot from March to Nov branch
- [] Bug fix
Tested on T0 topology on 
1. Mellanox platforms with all conditions matching. FW upgrade script was executed
2. Mellanox platforms with few conditions match. Upgrade script wasn't executed
3. Broadcom platforms. Upgrade script wasn't executed
=> [fast-reboot] Upgrade FW for mellanox before fast-reboot

ansible/README.test.md
Summary: Added 'read_mac' test to the test list described in README.test.md
Fixes #
- [] Bug fix
=> Added 'read_mac' test description to the README.test.md

ansible/README.test.md
Update with all the current testcases and their usage
=> Update testcase document

ansible/library/reduce_and_add_sonic_images.py
Summary:
- [] Bug fix
As the hard drive permits, we keep a few history images in the past so
that we could easily go back to them.
Recent test failure shows a downside of that decision. When a test failed
and leave an installed image in broken state. We likely restore the system
by booting into another working image. However, if the broken image is not
removed before installation happens again, because the target image exists,
the installation could be skipped or not fixing the existing issue. So
when we boot into the image again, the device is still in broken state.
Removing all non-current and non-next images give the DUT a better chance
to start a clean test.
=> [sonic_upgrade] remove non-current and non-next images

ansible/roles/fanout/tasks/main.yml
Converted line endings: CRLF to LF
* CRLF->LF
* N/A
* N/A
* N/A
* N/A
=> Convert line endings: CRLF to LF

ansible/README.test.md
=> Fix error in testcase doc

ansible/roles/test/tasks/common_tasks/reboot_sonic.yml, ansible/roles/test/tasks/vxlan-decap.yml
Summary:
1. Do reboot before the test
2. Send 10 packets instead of 1 packets
Run this test 10 times on my DUT
=> Some improvements for vxlan decap test

ansible/group_vars/sonic/sku-sensors-data.yml
Add sensor info for Arista-7260CX3-Q64
- [] Bug fix
Ran the sensors test on Arista-7260CX3-Q64 and it passed
=> Add sensor data for Arista-7260CX3-Q64

ansible/roles/test/files/acstests/everflow_policer_test.py
Mallnox uses a different GRE protocol 0x8949 and crafts extra information
in the packet that we need to take care of specifically.
=> [everflow]: Add Mellanox support due to specific GRE packet format

ansible/roles/test/files/acstests/everflow_policer_test.py
Summary:
Run PTF everflow policer test in a loop after ansible configuration
=> [everflow_policer] stabilize policer test case

ansible/roles/fanout/tasks/mlnx/check_pfcwd_fanout.yml, ansible/roles/test/templates/pfc_storm_mlnx.j2, ansible/roles/test/templates/pfc_storm_stop_mlnx.j2
- updated Fanout config check to fail if config is not valid
- updated storm start/stop script to avoid disturbing Google DNS
Ran the test
=> [Mellanox][pfcwd] Fanout config fixes 

ansible/roles/test/templates/fib.j2
Fixed FIB V4/V6: aligned facts generator (fixes #1089)
* Fixed roles/test/templates/fib.j2
* Tested on t0/t1/t1-lag
* N/A
* N/A
* N/A
=> [fib]: Fixed FIB V4/V6: aligned facts generator

ansible/roles/test/tasks/pfc_asym.yml
Fixed Asym PFC configuration commands
* Fixed command syntax
* Ran test
```bash 
ansible-playbook test_sonic.yml -i inventory --limit ${SWITCH}-${TOPO} -e  testbed_name=${SWITCH}-${TOPO} -e testbed_type=${TOPO} -e testcase_name=pfc_asym -vvvvv
```
* N/A
* N/A
* N/A
=> Align Asym PFC configuration commands

ansible/roles/test/files/ptftests/hash_test.py, ansible/roles/test/tasks/hash.yml, ansible/roles/test/tasks/test_sonic_by_tag.yml, ansible/roles/test/vars/testcases.yml
=> [hash]: Add hash test to validate the hash fields

ansible/roles/test/files/helpers/ferret.py, ansible/roles/test/files/ptftests/wr_arp.py, ansible/roles/test/tasks/wr_arp.yml, ansible/roles/test/templates/ferret.conf.j2, ansible/roles/test/vars/testcases.yml
Summary:
This is Control Plane Assistent test for Warm-Reboot.
The test first start Ferret server, implemented in Python. Then initiate Warm-Reboot procedure. While the host in Warm-Reboot test continuously sending ARP request to the Vlan member ports and
expect to receive ARP replies. The test will fail as soon as there is no replies for more than 25 seconds for one of the Vlan member ports
To Run the test from the command line:
```
ansible-playbook test_sonic.yml -i str --limit your_dut --vault-password-file password.txt -e testcase_name=wr_arp -e testbed_name=yourtestbed
```
All T0
=> Warm-reboot control plane assistant test

ansible/roles/test/files/tools/loganalyzer/loganalyzer_end.yml
dump only the current result and summary files for debugging and troubleshooting purpose
Infrastructure change taken out of https://github.com/Azure/sonic-mgmt/pull/834
Tested on regular pfc watchdog without break.
Summary:
- [] Bug fix
=> loganalyzer_end: dump only the current result and summary files

ansible/roles/test/vars/testcases.yml
Add t0-52 topology for some testcases
Summary:
- [] Bug fix
=> M0 testcases

ansible/roles/test/templates/pfc_storm_mlnx.j2, ansible/roles/test/templates/pfc_storm_stop_arista.j2, ansible/roles/test/templates/pfc_storm_stop_mlnx.j2
To allow per-queue per-port granularity. Create a separate PR for the infrastructure change in https://github.com/Azure/sonic-mgmt/pull/825
Tested on PFC watchdog test, and this change does not impact the PFC watchdog test.
Signed-off-by: Stepan Blyschak **<stepanb@mellanox.com>**
Signed-off-by: Wenda Ni <wenni@microsoft.com> 
Summary:
- [] Bug fix
=> Fine control PFC storm stop at Arista & Mellanox fanout

ansible/group_vars/sonic/vars, ansible/library/minigraph_facts.py, ansible/roles/sonic-common/tasks/main.yml, ansible/roles/test/tasks/sonic.yml
Adding Marvell platform related changes
Summary:
Added Marvell platform info in the following files:-
library/minigraph_facts.py
group_vars/sonic/vars
roles/test/tasks/sonic.yml
roles/sonic-common/tasks/main.yml
testcases are passing with the following changes
=> Support for Marvell platform: initial commit

ansible/group_vars/sonic/sku-sensors-data.yml
Remove some missing sensors and change lm75 sensors path
Summary:
- [] Bug fix
=> update Seastone devices sensors

ansible/roles/test/files/helpers/change_mac.sh, ansible/roles/test/files/helpers/remove_ip.sh, tests/scripts/change_mac.sh, tests/scripts/remove_ip.sh
Summary:
PR https://github.com/Azure/sonic-mgmt/pull/1141 is required for the 201811 branch. But the differences between 201811 and master would cause merging conflicts. Purpose of this PR is to make the change of https://github.com/Azure/sonic-mgmt/pull/1141 to the 201811 branch too. 
After this PR is merged, the changed files will be the same between 201811 and master branches and will be compatible with PTF image from both branches. Then we will not have merge conflicts in the future for these files.
=> Improve the scripts for preparing PTF interfaces 201811

ansible/roles/test/files/saitests/sai_qos_tests.py, ansible/roles/test/files/saitests/switch.py, ansible/roles/test/tasks/qos_sai.yml, ansible/vars/qos.yml
These are local development commits that have not undergone internal reviews yet.
Summary:
- [] Bug fix
=> QoS SAI test update

ansible/vars/qos.yml
Align with https://github.com/Azure/sonic-buildimage/pull/3600
Summary:
- [] Bug fix
=> PG headroom change for th2

ansible/roles/test/files/saitests/sai_qos_tests.py
=> qos sai: refactor tx enable/disable

ansible/roles/test/tasks/qos_sai.yml
=> qos sai: enable headroom pool test on Arista-7260CX3-Q64

ansible/roles/test/tasks/pfc_wd/functional_test/functional_test_restore_perq.yml, ansible/roles/test/tasks/pfc_wd/functional_test/functional_test_storm_perq.yml
This improves the test stability
Summary:
- [] Bug fix
=> pfcwd warm-reboot: sleep to allow control-plane messages flow into syslog

ansible/roles/test/files/ptftests/advanced-reboot.py, ansible/roles/test/files/ptftests/vnet_vxlan.py, ansible/roles/test/tasks/ptf_runner_reboot.yml, ansible/roles/test/tasks/warm-reboot-vnet.yml, ansible/roles/test/tasks/warm-reboot.yml, ansible/roles/test/vars/testcases.yml
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>
Summary:
Add test for VNET with warm-reboot
```ansible-playbook test_sonic.yml -i inventory --limit <testbed_name> -e testbed_name=<testbed_name> -e testbed_type=<topo> -e testcase_name=warm_reboot_vnet```
- [] Bug fix
Added test for VNET with warm-reboot
Ran test and verified it passed
N/A
T0 only
N/A
=> [vnet]: Add test for VNET with warm-reboot

ansible/roles/test/files/saitests/sai_qos_tests.py, ansible/roles/test/files/saitests/switch.py
Address comment: https://github.com/Azure/sonic-mgmt/pull/1162#discussion_r335932851
Tested on brcm dut
Summary:
- [] Bug fix
=> Extend tx enable/disable to support port id list

ansible/roles/test/files/saitests/sai_qos_tests.py
=> qos sai dscp to queue mapping test: Sleep to allow counter change propagate to COUNTERS_DB

ansible/group_vars/sonic/sku-sensors-data.yml
remove and change  some sensors path
Summary:
- [] Bug fix
=> update sensors path for seastone

ansible/roles/test/files/helpers/ferret.py
Summary:
I changed the script to read GRE type field and use it to extract encapsulated packet with the correct offset.
I ran the script on my DUT
Now it should work on Mellanox
=> [ferret.py]: Support two hw platforms in the ferret.py

ansible/roles/test/tasks/pfc_wd.yml
=> PFC wd warm-reboot: Ensure default pfc wd config is used for warm-reboot test

ansible/plugins/connection/switch.py, ansible/roles/fanout/tasks/mlnx/check_pfcwd_fanout.yml, ansible/roles/fanout/tasks/mlnx/deploy_pfcwd_fanout.yml, ansible/roles/fanout/templates/mlnx_deploy_pfcwd_fanout.j2, ansible/roles/test/files/mlnx/docker-tests-pfcgen/start.sh, ansible/roles/test/files/mlnx/docker-tests-saveargs/Dockerfile, ansible/roles/test/files/mlnx/docker-tests-saveargs/Makefile, ansible/roles/test/files/mlnx/docker-tests-saveargs/save_args.sh, ansible/roles/test/templates/pfc_storm_mlnx.j2, ansible/roles/test/templates/pfc_storm_stop_mlnx.j2
=> [mlnx][fanout] simplify mlnx pfc storm on fanout functionality

ansible/roles/test/files/helpers/ferret.py
Summary:
Change one symbol in the text file.
Using dump of Mellanox gre packet
=> Fix wrong GRE type constant in ferret.py

ansible/plugins/connection/switch.py, ansible/roles/fanout/tasks/mlnx/check_pfcwd_fanout.yml, ansible/roles/fanout/tasks/mlnx/deploy_pfcwd_fanout.yml, ansible/roles/fanout/templates/mlnx_deploy_pfcwd_fanout.j2, ansible/roles/test/files/mlnx/docker-tests-pfcgen/start.sh, ansible/roles/test/files/mlnx/docker-tests-saveargs/Dockerfile, ansible/roles/test/files/mlnx/docker-tests-saveargs/Makefile, ansible/roles/test/files/mlnx/docker-tests-saveargs/save_args.sh, ansible/roles/test/templates/pfc_storm_mlnx.j2, ansible/roles/test/templates/pfc_storm_stop_mlnx.j2
=> [201811][mlnx][fanout] simplify mlnx pfc storm on fanout functionality

tests/ansible.cfg
Need to make pytest-ansible to use ansible.cfg, otherwise if hosts
are not in known_hosts we will get the following error:
```
16:02:49         "    def _run(self, *module_args, **complex_args):",
16:02:49         "        module_ignore_errors = complex_args.pop('module_ignore_errors', False)",
16:02:49         "        module_async = complex_args.pop('module_async', False)",
16:02:49         "    ",
16:02:49         "        if module_async:",
16:02:49         "            def run_module(module_args, complex_args):",
16:02:49         "                return self.module(*module_args, **complex_args)[self.hostname]",
16:02:49         "            pool = ThreadPool()",
16:02:49         "            result = pool.apply_async(run_module, (module_args, complex_args))",
16:02:49         " …
```
=> [tests] add sym link to ansible.cfg for pytest-tests

ansible/roles/vm_set/library/sonic_kickstart.py
=> increase wait for bgp timeout to 60 seconds

ansible/roles/test/tasks/bgp_speaker.yml
Summary:
Fixes the testcase after https://github.com/Azure/sonic-buildimage/pull/3708
Changed testcase to use the new filename and new schema
Run on my testbed
=> Fix bgp_speaker testcase after change sonic-buildimage master

ansible/group_vars/sonic/sku-sensors-data.yml
Added sensors config for new Mellanox platform: SN3800
* Added relevant configs for SN3800
1. Ran sensors test
* Supported platform: SN3800
* N/A
* N/A
=> [mellanox] Added sensors config for new Mellanox platform: SN3800

ansible/roles/test/tasks/fdb.yml, ansible/roles/test/tasks/snmp.yml, ansible/roles/test/tasks/test_sonic_by_testname.yml, ansible/roles/vm_set/tasks/start_sid.yml
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
Summary:
"type" is mostly defined for kvm and simx DUTs, It could result in "undefined variable" in few places.
Make sure that `when` expressions are safe
=> [simx vt] avoid undefined 'type' variable

ansible/plugins/callback/yaml.py, ansible/roles/vm_set/tasks/docker.yml, ansible/roles/vm_set/tasks/main.yml, ansible/roles/vm_set/tasks/remove_topo.yml, ansible/shell_plugins/docker.py
Summary:
Fix some compatibility issues related to ansible 2.8.7
* N/A
1. Run topo remove/add
* N/A
* N/A
* N/A
=> [ansible] Fix some compatibility issues related to ansible 2.8.7

ansible/roles/test/tasks/decap.yml
Added dscp mode for decap test for marvell
Summary:
Added dscp mode for marvell in decap.yml file
Tested in local testbed
N/A
N/A
=> Added dscp mode for decap test for marvell

ansible/roles/vm_set/templates/sonic.xml.j2
=> increase to four cores for sonic vm

tests/test_interfaces.py
verify the port channel, vlan, port channel member, vlan member,
lo interface configuration
Summary:
- [] Bug fix
```
johnar@e1ea830bda60:/data/sonic-mgmt/tests$ py.test --inventory veos.vtb --host-pattern all --user admin --testbed vms-kvm-t0 --testbed_file vtestbed.csv -l test_interfaces.py --disable_loganalyzer | tee abc1.txt
platform linux2 -- Python 2.7.12, pytest-4.6.6, py-1.8.0, pluggy-0.13.1
ansible: 2.8.7
rootdir: /data/sonic-mgmt/tests, inifile: pytest.ini
test_interfaces.py .                                                     [100%] …
```
=> [pytest]: add test_interfaces.py to verify the interface configuration

tests/test_interfaces.py
=> [pytest/test_interfaces]: fix issue when there are multiple IPs on lo

ansible/roles/vm_set/library/kickstart.py, ansible/roles/vm_set/library/sonic_kickstart.py, ansible/roles/vm_set/library/vm_topology.py
add timestamp in the debug file
Summary:
- [] Bug fix
run refresh-dut
check /tmp folder on the server.
=> add retry in update in vm_topology

ansible/roles/test/templates/vnet_config.j2
Summary:
Fixes #  #1208 
Jinja file has been updated to generated correct endpoint IPs.
=> Fix for issue 1208 - VNET test is not working for large scale numbers

ansible/library/extract_log.py, ansible/library/interface_facts.py, ansible/roles/test/tasks/acl/acl_counter_traffic_test/acl_counter_traffic_test.yml, ansible/roles/test/tasks/continuous_link_flap.yml, ansible/roles/test/tasks/iface_naming_mode/iface_naming_mode_tests.yml, ansible/roles/test/tasks/port_toggle.yml, ansible/roles/test/tasks/portstat.yml, ansible/roles/test/tasks/sonic.yml, ansible/roles/test/tasks/vxlan-decap.yml
This is the continuation of #1235
Faced some issues when tried to run tests from the latest docker-sonic-mgmt container.
1. Specifying variable on include top level is deprecated: [link](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.0.html#deprecated)
2. imterface_facts up_ports could be a dict and a list
3. Some TC failed with:  'always' keyword cannot be used without 'block'
4. The conditional check '(testcase_name is not defined) or (testbed_type not in testcases[testcase_name]['topologies'])' failed
5. 'module' object has no attribute 'strptime'
Summary:
Fix some issues related to ansible 2.8.7 part 2
1. Provided variable to included files as specified in ansible doc. …
=> [ansible] Fix some issues related to ansible 2.8.7 part 2

tests/snmp/test_snmp_cpu.py, tests/snmp/test_snmp_interfaces.py, tests/snmp/test_snmp_lldp.py, tests/snmp/test_snmp_pfc_counters.py, tests/snmp/test_snmp_queue.py
=> [pytest]: use ip instead of hostname for snmp_facts module

ansible/roles/vm_set/tasks/docker.yml
I faced issue with hardcoded default pip path.
```
TASK [vm_set : remove old python packages] ********************************************************************************************************************************************************************
bash: TASK: command not found
user@dfcf062fed64:~/jenkins/sonic-mgmt/ansible$ Tuesday 10 December 2019  20:58:59 +0000 (0:00:00.051)       0:00:12.795 ****** 
bash: syntax error near unexpected token `('
user@dfcf062fed64:~/jenkins/sonic-mgmt/ansible$ fatal: [STR-ACS-SERV-02]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip", "uninstall", "-y", "docker-py"], "msg": "\n:stderr: Traceback (most recent call last):\n  File \"/usr/bin/pip\", line 9, in <module>\n    from pip import main\nImportError: cannot import name main\n"}
bash: …
```
=> [ansible] Use pip insted of hard coding full path

ansible/roles/test/tasks/continuous_link_flap.yml, ansible/roles/test/tasks/dhcp_relay.yml, tests/acl/test_acl.py, tests/test_vrf.py, tests/test_vrf_attr.py
This is the continuation of #1235 and #1261 
Faced some issues when tried to run tests from the latest docker-sonic-mgmt container.
- with_dict incorrect usage
- acl.pytest failed with `AttributeError: can't set attribute`
- continuous_link_flap failed with `'interface' is undefined` and `Not all interfaces are up`
References:
https://github.com/ansible/ansible/blob/4efb8bdc4fc8b2395d0e0c5a86f6361afb697382/lib/ansible/vars/manager.py#L136
https://docs.python.org/2.7/library/functions.html#property
Summary:
Fix some issues related to ansible 2.8.7 part 3
Summary:
- fixed with_dict syntax
- changed directly `_extra_vars` instead of read-only property `extra_vars`
- uncomment part of …
=> [ansible] Fix some issues related to ansible 2.8.7 part 3

ansible/library/exabgp.py
=> create /etc/exabgp if it does not exist

tests/acl/test_acl.py, tests/conftest.py, tests/fdb/test_fdb.py, tests/test_vrf.py, tests/test_vrf_attr.py
Summary:
- [] Bug fix
```
johnar@e1ea830bda60:/data/sonic-mgmt/tests$ py.test --inventory veos.vtb --host-pattern all --user admin --testbed vms-kvm-t0 --testbed_file vtestbed.csv fdb/test_fdb.py --disable_loganalyzer | tee abc.txt
platform linux2 -- Python 2.7.12, pytest-4.6.6, py-1.8.0, pluggy-0.13.1
ansible: 2.8.7
rootdir: /data/sonic-mgmt/tests, inifile: pytest.ini
fdb/test_fdb.py .                                                        [100%]
========================== 1 passed in 186.85 seconds ==========================
```
=> add topo properties in testbed fixture

ansible/roles/test/tasks/warm-reboot-sad-bgp.yml, ansible/roles/test/tasks/warm-reboot-sad-lag-member.yml, ansible/roles/test/tasks/warm-reboot-sad-lag.yml, ansible/roles/test/tasks/warm-reboot-sad-vlan-port.yml, ansible/roles/test/vars/testcases.yml
Split warm reboot sad test into multiple scripts
- [] Bug fix
Create separate .yml files for each sad operation
Tested the new yml files on t0-64 topology and they passed
=> Break down warm boot sad into multiple testcases

ansible/config_sonic_basedon_testbed.yml
=> Drop the external flag and instead check for clet file presence.

ansible/config_sonic_basedon_testbed.yml
vars/configlet/{{ topo }}/apply_clet.sh
Summary:
- [] Bug fix
=> Replace apply_configlet parameter with a check on file presence

ansible/roles/test/tasks/vnet_vxlan.yml
Signed-off-by: Vitaliy Senchyshyn <vsenchyshyn@barefootnetworks.com>
Fix vnet_vxlan test synax according to ansible 2.8
Summary:
- [] Bug fix
Fixed syntax.
=> [vnet_vxlan] Fix test synax according to ansible 2.8

ansible/library/snmp_facts.py, tests/snmp/test_snmp_lldp.py
Depends on sonic-snmpagent [#112](https://github.com/Azure/sonic-snmpagent/pull/112).
Summary:
Update test cases corresponding to SNMP LLDP modification in sonic-snmpagent.
- [] Bug fix
- [V] Test case(new/improvement)
Remove the test code for MIB nodes that are removed in sonic-snmpagent [#112](https://github.com/Azure/sonic-snmpagent/pull/112).
Run SNMP LLDP test cases.
No.
N/A.
N/A
=> [snmp] Remove Ansible test cases for LLDP code modification.

ansible/roles/fanout/tasks/mlnx/download_copy_pfcwd_fanout.yml
The pfcwd docker image downloaded from a URL is saved to tmp folder
with a temporarily file name. Then it is copied to fanout and the
temporarily file name is kept. Subsequent "docker load" will complain
file not found and fail. This issue was not caught in previous testing
because we already have a pfcwd_storm.tgz file on fanout switch. The
"docker load" command was loading from the old image, not from the
just copied image.
The fix is to copy the temporarily downloaded file to fanout switch
with its original image name, not the temporarily filename.
Summary:
The pfcwd docker image downloaded from a URL is saved to tmp folder
with a temporarily file name. Then it is copied to fanout and the
temporarily file name is kept. Subsequent "docker load" will complain
file not …
=> Fix issue of bad pfcwd docker image filename copied to fanout

ansible/config_sonic_basedon_testbed.yml
=> show docker status before load_minigraph

ansible/roles/vm_set/library/sonic_kickstart.py
=> increase the cmd timeout default to 60 seconds

tests/common/helpers/platform_api/scripts/platform_api_server.py, tests/common/helpers/platform_api/watchdog.py, tests/platform/api/conftest.py, tests/platform/api/test_watchdog.py, tests/platform/api/watchdog.yml
Summary: Add watchdog API test
PyTest Infrastructure and new test case
- [] Bug fix
Added an infrastructure for testing platform API by using platform_api_server.py script.
Run platform test with -k 'Watchdog'
Different platforms may have different watchdogs with their own capabilities or limitations.
Look at watchdog.yml file in this PR for details.
No specific topology.
=> [tests] Add watchdog platform API test

ansible/roles/test/tasks/pfc_wd/functional_test/functional_test.yml
Summary:
Should fix https://github.com/Azure/sonic-mgmt/issues/1303
=> [PFC WD] Add missed space

ansible/roles/test/files/ptftests/advanced-reboot.py
We missed a bug causing total_disrupt_time to be > 1 sec.
This is because the test asserts longest_disrupt_time < 1 sec.
However, there might be a lot of small periods of time which are < 1 sec
which result in total big downtime.
The fix is to assert also on total_disrupt_time in warm reboot test.
For fast reboot the test does not calculate total_disrupt_time because
it is assumed the lognest_disrupt_time == total_disrupt_time in case of
fast reboot.
Summary:
=> [advanced-reboot] assert on total_disrupt_time

ansible/doc/README.new.testbed.Configuration.md, ansible/doc/README.testbed.Setup.md, ansible/doc/README.testbed.SimXSetup.md, ansible/doc/README.testbed.VsSetup.md, ansible/group_vars/vm_host/main.yml, ansible/testbed-new.yaml
=> upgrade vEOS to 4.20.15M

ansible/doc/README.testbed.VsSetup.md, ansible/vtestbed.csv, tests/vtestbed.csv
=> use docker-ptf for Vs testbed

tests/snmp/test_snmp_interfaces.py, tests/snmp/test_snmp_psu.py
Summary:
- Convert SNMP PSU test to pytest
- [] Bug fix
=> [pytest snmp] add test_snmp_psu

ansible/roles/test/tasks/lag_fallback.yml
Summary:
Fix conditional check Error for lag fallback [(#1331)](https://github.com/Azure/sonic-mgmt/issues/1331)
- [v] Bug fix
Fix conditional check Error for lag fallback
Test it on a broadcom platform.
=> Fix conditional check Error for lag fallback

tests/conftest.py, tests/snmp/test_snmp_queue.py, tests/test_bgp_speaker.py
=> [pytest]: add collect_techsupport fixture to snmp and bgp_speaker test

ansible/roles/vm_set/tasks/docker.yml, ansible/roles/vm_set/tasks/external_port.yml, ansible/roles/vm_set/tasks/main.yml
Summary:
- [] Bug fix
- Add required packages.
- Add public key before adding docker repo.
- Make sure path exists before adding file to it.
Deployed a brand new server with only O.S installed.
=> [deploy server] changes to make server deployment smoother

tests/common/mellanox_data.py
Summary:
Add mellanox 4700 support for sonic-mgmt
Add meta data for new mellanox SKU ACS-MSN4700
Run it with Jenkins.
Only for mellanox SKU ACS-MSN4700.
All existing topology.
=> Add new mellanox SKU ACS-MSN4700 support for sonic-mgmt

ansible/roles/vm_set/tasks/stop_sid.yml
Change-Id: I10e42e1de872ac3935f6b94b8d45c3de5d26690b
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
Summary:
Align with new ansible version
- [] Bug fix
=> [simx] replace docker with docker_container (new ansible ver)

tests/test_interfaces.py
Summary:
- [] Bug fix
do not gather bgp_facts for test interfaces test
```
=============================================== 1 passed in 23.48 seconds ===============================================
johnar@e1ea830bda60:/data/sonic-mgmt/tests$ py.test --inventory veos.vtb --host-pattern all --user admin -vvv --show-capture stdout --testbed vms-kvm-t0 --testbed_file vtestbed.csv --disable_loganalyzer test_interfaces.py
aa================================================== test session starts ==================================================
platform linux2 -- Python 2.7.12, pytest-4.6.6, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python
ansible: 2.8.7
rootdir: …
```
=> [test_interfaces]: do not gather bgp_facts for test interfaces test

tests/test_config.py
* Add test_config.py
Signed-off-by: Jing Kan jika@microsoft.com
Summary:
Convert config.yaml to pytest.
Write the pytest by referring the config.yaml
Run the test case in my virtual testbed.
```
ansible: 2.8.7
rootdir: /data/sonic-mgmt/tests, inifile: pytest.ini
test_config.py::test_config PASSED                                       [100%]
========================== 1 passed in 240.19 seconds ==========================
```
No.
=>  [tests/config]: Convert config.yaml to pytest

ansible/group_vars/sonic/sku-sensors-data.yml, ansible/group_vars/sonic/vars, tests/platform/mellanox/test_check_sfp_presence.py
Summary:
1. Add SKU 4700 as new mellanox SKU to ansible\group_vars\sonic\vars
2. Add 4700 related sensor config to ansible\group_vars\sonic\sku-sensors-data.yml
3. Change qsfp sysfs path according to SKU 4700
1. Add SKU 4700 as new mellanox SKU to ansible\group_vars\sonic\vars
2. Add 4700 related sensor config to ansible\group_vars\sonic\sku-sensors-data.yml
3. Change qsfp sysfs path according to SKU 4700
Verified with Jenkins regression on T1/T0/T1-LAG topology.
x86_64-mlnx_msn4700-r0
All existing topology.
=> [Mellanox] Add support for new SKU SN4700

ansible/doc/README.testbed.VsSetup.md
<!--
Please make sure you've read and understood our contributing guidelines;
https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md
Summary:
- [] Bug fix
- Fix the sonic mgmt docker downloading link.
- Make some clarifications.
=> [vs setup doc] fix sonic-mgmt docker download link

ansible/roles/test/tasks/copp/ip2me_600.json, ansible/roles/test/tasks/copp/ip2me_6000.json
https://github.com/Azure/sonic-swss/pull/1125 changed the trap group name. As test changes the configuration for that group.
Summary: 
Update config files according to latest changes in community
Fix trap group name 
run COPP test
=> [COPP] Fix trap group name

tests/common/mellanox_data.py
Summary:
Support SKU Mellanox-SN3800-D112C8
- [] Bug fix
=> [Mellanox]Support "Mellanox-SN3800-D112C8"

ansible/doc/README.testbed.Setup.md
Summary:
- [] Bug fix
Fix the sonic mgmt docker download link in testbed setup doc.
=> [link] fix the sonic management docker download link

ansible/roles/vm_set/library/mellanox_simx_port.py, ansible/roles/vm_set/tasks/main.yml, ansible/roles/vm_set/tasks/start_sid.yml, ansible/roles/vm_set/templates/settings.ini.j2
Change-Id: Icecbc6926f2869c42e4f0e9093611950cd7eebe3
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
Summary:
Update Mellanox SimX infrastructure to use new docker image. Add pulling the docker image from the registry.
- [] Bug fix
Redeploy virtual testbed, apply topology.
Only affects Mellanox SimX vtestbed
=> [simx] update Mellanox simx vtestbed infra

ansible/roles/test/vars/testcases.yml
There is no yml file for this test. 
Summary: Remove qos test from testcases.yml
- [] Bug fix
Remove item from testcases.yml
N/A
N/A
=> [BFN] Remove qos test from testcases.yml

ansible/roles/test/files/helpers/ferret.py, ansible/roles/test/tasks/wr_arp.yml
To be able to do warm-reboot during this test you also should have sonic with these fixes: 
- https://github.com/Azure/sonic-buildimage/pull/4050
Summary:
Fix wr_arp test
- Replace ptf_host with ptf_host_ip where needed 
- Fix ip route show command. According to man `ip route show proto RTPROTO`. Where `RTPROTO := [ kernel | boot | static | NUMBER ]`
- Fix offset for 0x88be GRE type. 0x88be GRE type means that we have ERSPAN type 2 header after GRE. Reference https://tools.ietf.org/html/draft-foschiano-erspan-00
Run wr_arp test
N/A
=> [wr_arp] Fix wr_arp test

tests/conftest.py, tests/log_messages.py, tests/show_techsupport/files/acl_rule_persistent-del.json, tests/show_techsupport/files/acl_rule_persistent.json, tests/show_techsupport/files/acl_rules_del.json, tests/show_techsupport/templates/acl_rule_persistent.json.j2, tests/show_techsupport/templates/acltb_table.j2, tests/show_techsupport/templates/acltb_test_rules.j2, tests/show_techsupport/test_techsupport.py
Summary:
Added test case for execution of 'show techsupport' command in a loop
After execution, need to verify CPU, memory and loganalyzer are valid. 
Additional setup configurations are available - ACL, Mirroring. 
The purpose of the test is:
* Verify that when the system is configured, SDK problems will be found. 
* Verify that 'show techsupport' command works well in a loop. 
- [] Bug fix
- [V] Test case(new/improvement)
Add configurations extensions and execute 'show techsupport' command in a loop. 
Run the test with additional configurations as arguments, and verify that CPU, memory and loganalyzer are valid.
For example, 
` py.test --inventory ../ansible/inventory --host-pattern <host> --module-path ../ansible/library/ …
=> [Mellanox] Add 'show techsupport' test and additional conftest options

ansible/vars/qos.yml
Add watermark and DWRR parameters for Arista-7060CX-32S-C32
- [] Bug fix
Ran the watermark and DWRR test for 7060 and it passed
=> Add watermark and DWRR parameters for Arista-7060CX-32S-C32

ansible/vars/qos.yml
Fix QOS parameters for S6100 and Arista-7260CX3-D108C8
Type of Change
- [] Bug fix
Calculated the parameters based on the buffer size. Not tested
=> Fix QOS parameters for S6100 and Arista-7260CX3-D108C8

ansible/vars/qos.yml
Fix headroom parameters for Arista-7260cx3-Q64
- [] Bug fix
- [x Test case(new/improvement)
Ran the test on Q64 and it passes
=> Fix headroom parameters for Arista-7260cx3-Q64

ansible/roles/test/tasks/buff_wm.yml, ansible/roles/test/tasks/qos_get_max_buff_size.yml, ansible/roles/test/tasks/qos_get_ports.yml, ansible/roles/test/tasks/qos_sai.yml
Disable buffer watermark and dscp-pg mapping test
- [] Bug fix
Verified that the buffer watermark and dscp-pg mapping tests are skipped
=> Provide knob to disable buffer watermark and dscp-pg mapping test

ansible/roles/test/files/saitests/switch.py, ansible/roles/test/tasks/qos_sai.yml
* packets_aging.py was failing but the ansible test was still reporting pass. With the change, the test reports the correct results. 
* Check for the presence of var before using it
* Added the missing constants that were used in some methods
Ran the test with the changes and the results are reported correctly
=> Enable error handling and fix issues due to undefined vars

ansible/roles/test/tasks/buff_wm.yml, ansible/roles/test/tasks/qos_get_max_buff_size.yml, ansible/roles/test/tasks/qos_get_ports.yml, ansible/roles/test/tasks/qos_sai.yml
Provide knob to disable buffer watermark and dscp-pg mapping test
Same as #1431. Raising a new one because a lot of merge conflicts were seen while trying to cherry-pick
Summary:
- [] Bug fix
=> [201811] Provide knob to disable buffer watermark and dscp-pg mapping test

ansible/roles/test/files/saitests/switch.py, ansible/roles/test/tasks/qos_sai.yml
* Init global vars used for scheduler/port pause/release
* Enable error handling and fix issues due to undefined vars
Summary:
- [] Bug fix
=> [201811] Enable error handling and fix issues due to undefined vars

ansible/roles/test/tasks/mtu.yml, tests/test_mtu.py
Signed-off-by: Arvindsrinivasan Lakshminarasimhan <arlakshm@microsoft.com>
Summary: Convert ansible mtu test to pytest
- [] Bug fix
arlakshm@3176a03c5c39:/var/repos/public/my_repo/sonic-mgmt/tests$ ANSIBLE_KEEP_REMOTE_FILES=1  py.test  --inventory /var/repos/files/veos.vtb  --host-pattern all --user admin -vvv --testbed vms12-t1-lag-1 --testbed_file /var/repos/files/vtestbed.csv --disable_loganalyzer --junitxml=test_mtu.xml --show-capture stdout test_mtu.py
=================================================== test session starts ====================================================
platform linux2 -- Python 2.7.12, pytest-4.6.6, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python
cachedir: …
=> Convert ansible mtu test to pytest

ansible/vars/qos.yml
Add QOS parameters for Force10-S6000
- [] Bug fix
Qos sai test passes on this hwsku
=> Add QOS parameters for Force10-S6000

ansible/roles/vm_set/tasks/add_topo.yml, ansible/roles/vm_set/tasks/remove_topo.yml, ansible/templates/eos/t0-leaf.j2, ansible/templates/eos/t1-lag-spine.j2, ansible/templates/eos/t1-lag-tor.j2
Summary:
test refresh-dut command.
=> [ceos]: ingore ceos playbook if vm_type is not defined

ansible/roles/vm_set/tasks/start_sonic_vm.yml, ansible/veos.vtb
=> [testbed/vs]: add dut specific console port for sonic kvm

tests/platform/files/valid_policy.json, tests/platform/mellanox/mellanox_thermal_control_test_helper.py, tests/platform/test_platform_info.py, tests/platform/thermal_control_test_helper.py
Summary:
Fixes 1. fan information should be all N/A when fan is not present; 2. temperature should not be 0; 3. incorrect fan status
Verified on manually run regression
No
N/A
=> [Mellanox] Adjust regression test case according to thermal control bug fix

ansible/roles/test/tasks/interface.yml
Summary: temporally disable interface counters check to avoid test case failures until:
- Issue https://github.com/Azure/sonic-buildimage/issues/2738 will be fixed
- PR https://github.com/Azure/sonic-mgmt/pull/1165 will be merged
=> Temporal disable interface counters check

ansible/roles/vm_set/library/vm_topology.py
remove existing ovs port if they are not in the right ovs bridge
Summary:
- [] Bug fix
provision the testbed
=> [vm_topology]: recreate ovs bridge port and remove existing port

ansible/doc/README.testbed.VsSetup.md, ansible/lab, ansible/plugins/filter/filters.py, ansible/roles/eos/templates/t1-lag-spine.j2, ansible/roles/eos/templates/t1-lag-tor.j2, ansible/roles/eos/templates/t1-tor.j2, ansible/roles/vm_set/tasks/main.yml, ansible/testbed-cli.sh, ansible/vars/topo_t1-lag.yml, ansible/veos.vtb, ansible/vtestbed.csv, tests/common/plugins/fib.py, tests/veos.vtb, tests/vtestbed.csv
=> add t1-lag support in virtual switch testbed

tests/platform/mellanox/mellanox_thermal_control_test_helper.py
Summary:
Fixes typo
Manually run the test case.
=> [Mellanox] Fix typo in thermal control test case

ansible/doc/README.testbed.VsSetup.md, ansible/eos.yml, ansible/library/exabgp.py, ansible/library/image_facts.py, ansible/roles/fanout/tasks/fanout_mlnx.yml, ansible/roles/test/files/helpers/arp_responder.py
Summary:
General codebase improvements
=> [framework] General codebase improvements

tests/test_nbr_health.py
remove hardcoded Management0 interface in the check
as vEOS uses Management1 interface
Summary:
=> [pytest/nbr_health]: add support for vEOS

ansible/doc/README.testbed.VsSetup.md
=> [doc]: add sudoer configuration for user foo the VsSetup doc

ansible/config_sonic_basedon_testbed.yml
=> Revert "Enable core uploader service"

tests/test_lag_2.py
Convert single_lag_test.yml to pytest
1. Convert single_lag_test.yml to pytest
2. Convert lag_minlink.yml to pytest
I will use the pytest version lag test replace the original lag_2.yml after all sub-testcase converted.
Summary:
1. Convert single_lag_test.yml to pytest
2. Convert lag_minlink.yml to pytest
3. Use ansible eos config module to shut/noshut interface
Run test in local vstestbed
```
test_lag_2.py::test_lag_2
/usr/local/lib/python2.7/dist-packages/pytest_ansible/module_dispatcher/v28.py:70: UserWarning: provided hosts list is empty, only localhost is available
warnings.warn("provided hosts list is empty, only localhost is available")
-- Docs: …
```
=> [tests/lag_2] Convert single_lag_test.yml to pytest

.github/PULL_REQUEST_TEMPLATE.md
**Summary**
Refine the type of change section and shows empty checkbox instead of raw text which will help contributor have a better experience when raising Pull Request
**Before**
**After**
Update the pull request template with correct markdown syntax
Github markdown preview
=> [github/pr]: Refine the pull request template

tests/pc/test_po_update.py
Summary:
```
johnar@1cafe0c9f994:/data/tests$ py.test $PYTEST_COMMON_OPTS --log-file ~/abc.log pc/test_po_update.py | tee ~/abc.txt                           ============================= test session starts ==============================
ansible: 2.8.7
pc/test_po_update.py::test_po_update PASSED                              [100%]
```
=> [pytest/pc]: rename test_config.py to test_po_update.py

tests/test_lldp.py
=> [pytest/lldp]: collect tech support when test fails

lgtm.yml
Summary: Adds all of the testing code to the LGTM analysis.
I added a catch-all rule to disable LGTM's default handling of test files. This will ensure that all of our testing code gets analyzed when people submit PRs under the `tests` directory.
Used the "Test Analysis Configuration" tool on LGTM to make sure that the config file worked for this project.
=> [lgtm] Configure LGTM to analyze test code

tests/common/fixtures/advanced_reboot.py, tests/test_everflow_testbed.py
Summary: Addresses LGTM errors in the `tests` directory.
I queried for `Error` level alerts in the `tests` folder and cleaned up the affected files.
Tests still work after making the edits.
=> [tests] Fix LGTM errors in tests folder

tests/common/plugins/tacacs.py
Summary:
for better deniability
```
johnar@1cafe0c9f994:/data/tests$ py.test $PYTEST_COMMON_OPTS --log-file ~/abc.log tacacs/test_ro_user.py | tee ~/abc.txt
ansible: 2.8.7
tacacs/test_ro_user.py::test_ro_user PASSED                              [100%]
```
=> [tacacs]: replace shell command with service module

tests/common/fixtures/advanced_reboot.py, tests/platform/args/advanced_reboot_args.py, tests/scripts/fast-reboot
Adding an option to replace fast reboot script on dut as part of
testbed preparation.
signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
Summary:
=> [pytest] Add replace fast-reboot script test option

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Fix issue: remove non-exist sensor sysfs files from Mellanox 3700 platform
Remove non-existing sensor data
Manually run sensor test on Mellanox 3700
=> [Mellanox] Fix sensor data for 3700

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Fix issue: remove non-exist sensor sysfs files from Mellanox 4700 platform
Remove non-existing sensor data
Manually run sensor test on Mellanox 4700
=> [Mellanox] Fix issue: remove non-exist sensor sysfs files for 4700

tests/common/helpers/assertions.py
Summary:
introduce assertion handling code
Add assertion wrapper. pytest assert condition, message sometimes generate error following error message and obscures the test summary.
E       AttributeError: 'module' object has no attribute 'locals'
Usage:
from common.helpers import assertions
assertions.pytest_assert(condition, message)
Recommend always use this helper with a proper message:
>       assertions.pytest_assert(False, "status {}".format(status))
E       Failed: status {u'Ethernet0': {u'alias': u'Ethernet1/1', u'oper_state': u'up', u'name': u'Ethernet0', u'admin_state': u'up', u'vlan': u'trunk', u'speed': u'50G'}}
... ...
FAILED experiment/test_experiment.py::test_experiment - Failed: status {u'Ethernet0': {u'alias': u'Ethernet1/1', u'oper_state': u'up', u'name': u'Ethernet0', …
=> [pytest assersion] introduce assertion handling code

tests/test_procdockerstatsd.py
Verify procdockerstatsd daemon is Active and Running
Verify daemon uploads data to STATE_DB successfully 
Summary:
- [ *] Test case(new/improvement)
Verified against virtual test bed
Supported in 201911 image
=> [test/procdockerstatsd] Verify daemon is active/running and uploads data successfully

tests/route/test_default_route.py, tests/route/test_route_set_src.py
Summary:
```
johnar@1cafe0c9f994:/data/tests$ py.test $PYTEST_COMMON_OPTS --log-file logs/abc.log route/test_default_route.py  | tee ~/abc.txt               ============================= test session starts ==============================
ansible: 2.8.7
collecting ... collected 2 items
route/test_default_route.py::test_default_route_set_src PASSED           [ 50%]
route/test_default_route.py::test_default_ipv6_route_next_hop_global_address PASSED [100%]
=============================== warnings summary …
```
=> [pytest/default_route_check]: check various aspect related to default route learnt from bgp

tests/route/test_default_route.py
Summary:
add support for 201911/201811 release
```
johnar@1cafe0c9f994:/data/tests$ py.test $PYTEST_COMMON_OPTS --log-file logs/abc.log route/test_default_route.py  | tee ~/abc.txt
ansible: 2.8.7
collecting ... collected 2 items
route/test_default_route.py::test_default_route_set_src PASSED           [ 50%]
route/test_default_route.py::test_default_ipv6_route_next_hop_global_address PASSED [100%]
```
=> [pytest/test_default_route]: support 4.9 kernel 201911/201811 release

tests/platform/mellanox/check_sysfs.py
Summary:
On 3700c sometimes the CPU temperature is greater than the alarm threshold. Having discussed with hardware engineers we find that the CPU should be compared against critical threshold rather than alarm threshold.
=> [Mellanox/platform] Compare CPU's temperature against critical threshold

tests/conftest.py, tests/pc/test_lag_2.py, tests/test_nbr_health.py
Summary:
check the pr
run test
```
johnar@1cafe0c9f994:/data/tests$ py.test $PYTEST_COMMON_OPTS --log-file ~/abc.log test_nbr_health.py  | tee ~/abc.txt    ============================= test session starts ==============================
ansible: 2.8.7
test_nbr_health.py::test_neighbors_health PASSED                         [100%]
```
run lag test failed. not able to pass the lag test even without my change. But, it does not look like my change affect the test.
=> [pytest/nbrhost]: add neighbor config info in nbrhost class

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Fixes sensor data for 3700/3700c/3800
=> [Mellanox]Fix sensor data for 3700/3700c/3800

tests/common/plugins/dut_monitor/pytest_dut_monitor.py
Summary: Fixed pytest fixture scope conflict between 'dut_ssh' and 'creds' fixtures.
- [ +] Bug fix
Changed "session" to "module" scope of 'dut_ssh' pytest fixture to fix fixtures scope conflict between "dut_ssh" and "creds" fixtures.
Tested on the local setup.
=> Fixed fixture scope conflict in DUT monitoring

tests/bgp/conftest.py, tests/bgp/test_bgp_gr_helper.py, tests/common/devices.py, tests/common/utilities.py
Summary:
add bgp graceful restart helper test.
there is one TODO list, is to verify no change in app db.
this pr depends on #1621 
```
johnar@1cafe0c9f994:/data/tests$ py.test $PYTEST_COMMON_OPTS --log-file ~/abc.log bgp/test_bgp_gr_helper.py  | tee ~/abc.txt
ansible: 2.8.7
bgp/test_bgp_gr_helper.py::test_bgp_gr_helper_routes_perserved PASSED    [100%]
```
no
t0
=> [pytest/bgp_gr_test]: add bgp graceful restart helper test

tests/common/devices.py
=> [pytest]: fix typo in parse default route output

tests/common/fixtures/advanced_reboot.py
This code ports PR 1637 to advanced reboot.
ported-pr: https://github.com/Azure/sonic-mgmt/pull/1637
signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
ported pr: https://github.com/Azure/sonic-mgmt/pull/1637
=> [advanced-reboot] Fix IP range overalapping

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Fixes sensor data for 4700
=> [Mellanox] Fix sensor data for SN4700

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Fixes sensor test failure on Mellanox 2010 platform.
Rename sysfs file name due to hw-mgmt upgrading.
Manually run the regression and get a pass.
Mellanox 2010 platform
N/A
=> [Mellanox] Fix sensor data for 2010 platform

tests/ntp/test_ntp.py
Summary: Added additional verification to check 'wait_until' result
- [+] Test case(new/improvement)
Added verification of 'wait_until' result, to easier understand test case failure reason.
Tested on the local setup
=> Minor improvement for NTP test case

ansible/vars/qos.yml
Summary:
Provide QoS parameters:
- packet size for the shared buffer watermark test
- parameters for 40G*40m
=> [Mellanox] Provide qos parameters for packet size and 40G 40m

ansible/roles/test/tasks/qos_sai.yml, ansible/vars/qos.yml
Specify packet size for PG Shared WM tests for all asics
=> [QOS] Include pkt size parameter for PG SharedWM tests

tests/common/plugins/sanity_check/constants.py
show bgp summary is removed in
https://github.com/Azure/sonic-utilities/commit/c5a60cef23caf841642e150994be01bbf1ab240a
Summary:
run `bgp/test_bgp_fact.py` and check the log
```
INFO     common.plugins.sanity_check.checks:checks.py:179 cmd='show ipv6 bgp summary', output:
[   
"",
"IPv6 Unicast Summary:",
"BGP router identifier 10.1.0.32, local AS number 65100 vrf-id 0",
"BGP table version 5",
"RIB entries 9, using 1656 bytes of memory",
"Peers 4, using 82 KiB of memory",
"Peer groups 6, using 384 bytes of memory",
"",
"Neighbor        V         AS MsgRcvd MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd\tNeighborName",
"fc00::72        4      64600   43762   43761        0    0    0 1d12h27m            1\tARISTA01T1", …
```
=> [pytest/sanity_check]: use show ip[v6] bgp summary

ansible/group_vars/sonic/vars, ansible/roles/test/tasks/qos_get_ports.yml, ansible/roles/test/tasks/qos_sai.yml, ansible/vars/qos.yml
* Qos SAI test restructure
PR raised since #1682 cannot be cleanly cherry-picked
=> [201811] Qos SAI test restructure

.gitignore
Summary:
Some test cases generate dump files on DUT and copy the files to
tests/logs when testing failed. Update the .gitignore file to ignore
the dump files.
Avoid all the dump files to be listed in `git status` output.
Update the .gitignore file to ignore all files under `tests/logs`
=> Ignore the dump files stored to tests/logs

ansible/roles/vm_set/templates/sonic.xml.j2
admin@vlab-01:~$ free -m
total        used        free      shared  buff/cache   available
Mem:           1946        1491         116           8         338         281
Swap:             0           0           0
admin@vlab-01:~$
Summary:
=> [sonicvm]: increase memory to 3GB

ansible/doc/README.testbed.Setup.md
=> [doc]: change lab server to 18.04

tests/common/devices.py, tests/scripts/exec_template.yml
Summary:
Fixed pytest version of pfc asymmetric test case
To fix failure of PFC asmmetric test case
Tested on the local setup
=> [pytest] Fixed PFC asymmetric test case

tests/cacl/test_control_plane_acl.py
Summary:
PR #1786 fixed an issue that no exception is raised for some failed ansible
modules. With that fix, the controle plane acl testing will fail. The reason is
that calling some of the ansible modules in this script is expected to fail.
However, because of the issue fixed by #1786, no exception is raised .
The test script explicitly check error message to determine if the ansible
module calling is failed or not.
With the fix of #1786, exception will be raised while calling ansible modules
that are expected to fail. We need to add `module_ignore_errors=True` for
these modules. Then we check the msg field of ansible module results to
determine whether the testing is expected or not.
The control plane ACL testing will fail if PR #1786 is merged. The problem is not with …
=> Fix control plane ACL testing for PR #1786

ansible/roles/test/tasks/qos_sai.yml
Please refer PR#https://github.com/Azure/sonic-mgmt/pull/1810 for deatils
=> Ported changes from Master PR : https://github.com/Azure/sonic-mgmt/pull/1810 to 201811

tests/common/plugins/loganalyzer/loganalyzer.py
PFC wd testcase requires to search for regexs based off existing start msg in the log (eg. ongoing storm during warm boot). Hence extending the loganalyzer to specify a custom start marker vs. writing a new one into the log. 
Also in some cases, we might need to search for the number of a times a regex was seen in the log, 
Changes made to support the above 2 cases by including a start_marker during the loganalyzer init as well as providing a 'expected_matches_target' to specify the number of times a regex is expected
Tested the changes as well as regressed the existing loganalyzer code using the pfcwd warmboot test
=> [pytest] Loganalyzer enhancements

tests/common/helpers/pfc_storm.py, tests/pfcwd/test_pfcwd_warm_reboot.py
Pytest conversion for pfcwd warm reboot part of 'pfc_wd.yml' playbook
Ran the test with few ports (out of the entire selected list) on T0 and it passed
Depends on #1823
=> [pytest] Pfcwd warm reboot test

tests/arp/test_neighbor_mac_noptf.py
Summary:
This PR converts Ansible neighbor-mac-noptf test case to pytest framework.
signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
Closing gap between Ansible and pytest framework
Converted .yml test to Python pytest
```
tests$ pytest arp/test_neighbor_mac_noptf.py --testbed=vms12-t0-s6000-1 --inventory=../ansible/str --testbed_file=../ansible/testbed.csv --host-pattern=str-s6000-acs-14 --module-path=../ansible/library --disable_loganalyzer --skip_sanity
================================================================================================================================================== test session starts ==================================================================================================================================================
platform linux2 -- …
```
=> [pytest][neighbor-mac] Convert Neighbor MAC no PTF test case

tests/platform_tests/api/test_chassis.py, tests/platform_tests/api/test_watchdog.py
Make class names PascalCase. Also fix a couple typos.
=> [Platform API][pytest] Minor case adjustments

tests/common/mellanox_data.py
Summary:
Some device data is missing for several Mellanox SKU
Add thermal data for ACS-MSN3700 and Mellanox-SN3800-D112C8
Add device data for ACS-MSN4600C and ACS-MSN3420
run related platform test on Mellanox platform
This is change is Mellanox platform specific
N/A
=> [Mellanox]Add new Mellanox platform device data

ansible/plugins/connection/switch.py
Summary: Fixed 'UnicodeDecodeError' in 'switch.py'
- [+] Bug fix
The motivation is to fix error which occurs during execution of 'pfc_asym/test_pfc_asym.py' test cases on stage of running 'pfc_gen.py' on Fanout switch.
Observed issue traceback:
```
E           The full traceback is:
E           Traceback (most recent call last):
E             File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 145, in run
E               res = self._execute()
E             File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 664, in _execute
E               result = self._handler.run(task_vars=variables)
E             File …
```
=> Fixed 'UnicodeDecodeError: 'ascii' codec can't decode byte' in switch.py

ansible/roles/test/templates/ptf_nn_agent.conf.dut.j2, ansible/swap_syncd.yml
Porting Master PR#https://github.com/Azure/sonic-mgmt/pull/1857 to 201811
=> Copp fix for Non-policier test case 

tests/README.md
Summary:
- unify the way community runs pytests.
- provide examples of using run_test.sh
=> [tests] add some instructions regarding how to run py tests

tests/everflow/everflow_test_utilities.py, tests/everflow/test_everflow_testbed.py
- Update expected GRE type for Everflow test cases
- Make testcase 5 clean-up steps more robust
Summary: Fix errors in the policer test case (formerly test case 5).
We noticed that test cases were failing because the GRE type was set to `0x6558` by default. This is actually the Ethertype for GRE, not the GRE type for ERSPAN.
We also noticed that these test failures would leave the system in an inconsistent state, so that has been made more robust as well.
- Updated the default GRE value
- Added a mirror session + policer fixture so that the setup/teardown would be more consistent
- Added a `try/finally` to clean up the rest of the setup (this should also be a fixture but that would touch all the other test cases, so I'll do that in a …
=> [everflow] Fix policer test case failures

tests/common/plugins/loganalyzer/__init__.py
Summary:
The `loganlyzer` fixture still adds marker to syslog when log analyzer is disabled. This PR improves this behavior.
When log anlayzer is disabled, do nothing except output a log message indicating that log analyzer is disabled.
When log analyzer is disabled, it's unnecessary to add start marker to syslog. This PR can save some script execution time in setup/teardown sections of test case when log analyzer is disabled. The log messages would be fewer too.
Updated the `loganalyzer` fixture. When log analzyer is disabled, skip adding start marker to DUT's syslog.
Tested scenarios:
* Disable log analyzer from pytest cli
* Run regular test case
* Run test case explicitly called log analyzer
* Run test case with `@pytest.mark.disable_loganalyzer
* Disable log analyzer …
=> Skip adding loganalyzer marker if loganalyzer is disabled

ansible/doc/README.testbed.Setup.md
=> [doc]: update README.testbed.Setup.md for building dockers

tests/bgp/conftest.py
Summary:
fix lgtm warning
check lgtm
=> [pytest]: fix lgtm warning for bgp gr test

ansible/roles/test/files/helpers/arp_responder.py, ansible/roles/test/files/ptftests/vxlan-decap.py, tests/vxlan/test_vxlan_decap.py
Summary:
Fix test_vxlan_decap on DUT with more interfaces (like Arista-7260cx3).
1. The test_vxlan_decap fails on DUT with more interfaces (like Arista 7260cx3) because the FDB and ARP table built in **warmup** procedure  get timeout and invalid before or running test. 
The test steps are as following:
```
#warmup 
Vxlan
RegularLAGtoVLAN # FDB and ARP table are built
RegularVLANtoLAG 
#worktest
Vxlan test #Costs hours and FDB/ARP table gets timeout
RegularLAGtoVLAN test # May fail bacause FDB/ARP table is incompleted
RegularVLANtoLAG test 
```
2. The test costs too much time, and optimization is needed.
1. Remove unnecessary steps in warmup so that the test is much faster;
2. Add two wrapper method to speed up tests;
3. Rearrange test steps in order to ensure FDB and ARP …
=> Fix vxlan decap test

ansible/TestbedProcessing.py
Summary: Fixed issue with local variable `ptf_ipv6` in TestbedProcessing.py due to latest changes. see traceback bellow
```PROCESS STARTED
BACKUP PROCESS STARTED
Error: could not back up group_vars/eos/creds.yml
BACKUP PROCESS COMPLETED
LOADING PROCESS STARTED
LOADING: bfn-testbed.yaml
TestbedProcessing.py:532: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
doc = yaml.load(open(args.i, 'r'))
LOADING PROCESS COMPLETED
GENERATING FILES FROM CONFIG FILE
CREATING SONIC LAB LINKS: files/sonic_lab_links.csv
CREATING SONIC LAB DEVICES: files/sonic_lab_devices.csv
CREATING TEST BED: testbed.csv
File "TestbedProcessing.py", line 583, in <module> …
```
=> Fixed 'referenced before assignment' in TestbedProcessing.py

ansible/group_vars/sonic/variables, ansible/library/minigraph_facts.py
Signed-off-by: Nazar Tkachuk <nazarx.tkachuk@intel.com>
Summary:
Add new Barefoot Networks platform 
Run related platform test
This change is BFN platform specific
=> [BFN] Add new platform Newport

tests/pfcwd/conftest.py
Fixing a bug in code where vlan info was passed for all topologies causing failure on T1
=> Fix pfcwd test errors on T1

tests/common/helpers/platform_api/psu.py, tests/platform_tests/api/test_psu.py
Add DeviceBase class api check to test_psu.py
=> Add DeviceBase class api check to test_psu.py

tests/telemetry/test_telemetry.py
Adding a check for telemetry docker presence for each telemetry test
Summary:
Currently test run even though telemetry docker is not present which results in failure.
=> [test-telemetry] add check for docker image

tests/fib/test_fib.py
Signed-off-by: Oleksandr Kozodoi <oleksandrx.kozodoi@intel.com>
Summary:
Updated hash test for supported hash of Barefoot platform
=> [ test_fib ] update hash for Barefoot platform

tests/platform_tests/api/test_watchdog.py
Summary:
Fixes python syntax error in test_watchdog.py
Found a few python syntax errors in test_watchdog.py, fixed them
Correct all the syntax issues
Manual run the test cases.
N/A
N/A
=> [watchdog] Fix python syntax error in test_watchdog.py

ansible/group_vars/sonic/sku-sensors-data.yml
Fix Arista 7050QX-32 sku sensors data according to raw data from Sujin.
Summary:
=> [Arista] Fix 7050QX-32 sku sensors data

README.md, ansible/doc/README.testbed.VsSetup.md, setup-container.sh
Summary:
Ease the process of setting up a new sonic-mgmt Docker container by automating it
* Add `setup-container.sh` script to create sonic-mgmt container and configure the user inside the container
* Update README with script instructions
Run the script as described in the README and verified on the created container that the UID and GID match between container and host, and that the user inside the container has passwordless sudo access.
=> [docker]: Automate sonic-mgmt container creation

spytest/templates/show_interfaces_status_qa.tmpl
A new column `FEC` is introduced to `show interfaces status` output,
adjust the template to adapt to the change.
Summary:
To adapt to the new column `FEC` in the output from `show int status`:
```
Interface            Lanes    Speed    MTU    FEC         Alias    Vlan    Oper    Admin             Type    Asym PFC
-----------  ---------------  -------  -----  -----  ------------  ------  ------  -------  ---------------  ----------
Ethernet0      33,34,35,36     100G   9100     rs   Ethernet1/1  routed      up       up  QSFP28 or later         off
Ethernet4      37,38,39,40     100G   9100     rs   Ethernet2/1  routed    down     down  QSFP28 or later         off
Ethernet8      41,42,43,44     100G   9100     rs …
```
=> [Spytest] Adapt to 'show interfaces status' change

tests/conftest.py, tests/platform_tests/broadcom/test_ser.py
Summary:
Address LGTM warnings from #2040 
Remove unused imports and only import specific function.
Run test_interface.py aand test_ser.py
=> [LGTM] address a few LGTM warnings

tests/telemetry/test_telemetry.py
=> [Telemetry-Pytest] fix docker image present check

ansible/roles/test/files/ptftests/advanced-reboot.py
Summary:
After PR https://github.com/Azure/sonic-mgmt/pull/1939/, fast and warm reboot testcases are failing due to invalid access of instance method in advanced-reboot script. 
Error seen in fast and warm reboot testcases:
```
E               "stderr_lines": [
E                   "WARNING: No route found for IPv6 destination :: (no default route?)", 
E                   "advanced-reboot.ReloadTest ... Exception in thread Thread-15:", 
E                   "Traceback (most recent call last):", 
E                   "  File \"/usr/lib/python2.7/threading.py\", line 801, in __bootstrap_inner", 
E                   "    self.run()", 
E                   "  File \"/usr/lib/python2.7/threading.py\", line 754, in run", 
E                   "    self.__target(*self.__args, …
```
=> Bug fix in advanced-reboot check-sonic-version

ansible/group_vars/sonic/sku-sensors-data.yml
Signed-off-by: Roman Savchuk <romanx.savchuk@intel.com>
Summary:
- [+ ] Testbed and Framework(new/improvement)
=> Added Acton sku sensors data

ansible/veos_vtb
Summary:
This PR will allow a smooth transition to the merging of https://github.com/Azure/sonic-mgmt/pull/2072, which depends on https://github.com/Azure/sonic-build-tools/pull/145. However, there is a chicken-and-egg problem, where without this intermediary PR, the check builds will be broken for a period of time.
Infrastructure (inventory file)
=> Add symlink from 'veos_vtb' to 'veos.vtb'

ansible/library/testbed_vm_info.py
Summary:
If the veos inventory file is converted to yaml format, the testbed_vm_info module will be affected. Consequently `testbed-cli.sh gen-mg` and `testbed-cli.sh deploy-mg` that are dependent on this module will fail.
The reason is that `testbed_vm_info` parses the `veos` inventory file as plain text and expects the `veos` file to have the `ansible_host=x.x.x.x` variable on the same line with host name like `VM0001`.
Update the module to use the ansible `InventoryManager` for parsing the `veos` inventory file. Then it will always work no matter the inventory file is ini format or yaml format.
Test run `testbed-cli.sh gen-mg` and `testbed-cli.sh deploy-mg` using both ini and yaml format `veos` inventory file.
=> Fix the issue of parsing yaml inventory file in the testbed_vm_info module

tests/common/helpers/platform_api/component.py, tests/platform_tests/api/test_component.py
=> [Platform API] Add basic tests for Component class

ansible/doc/README.testbed.Overview.md, ansible/doc/README.testbed.VsSetup.md
Summary:
Fixes # 2083 ( Ixia API server deployment instruction)
This is documentation of instruction on deployment of Ixia API server docker
It's a documentation change
=> Ixia api server docker depolyment instruction 

tests/fdb/files/fdb.j2
vlan interface has now IPv6 address, so fdb.j2 renders all fdb info in one line and fdb_info.txt parser logic fails with below error. To fix this issue, a new line added between addresses in the template.
Otherwise, fdb_mac_expire test fails:
expire_test.FdbMacExpireTest ... ERROR",
"",
"======================================================================",
"ERROR: fdb_mac_expire_test.FdbMacExpireTest",
"----------------------------------------------------------------------",
"Traceback (most recent call last):",
"  File \"ptftests/fdb_mac_expire_test.py\", line 35, in runTest",
"    self.populateFdb()",
"  File \"ptftests/fdb_mac_expire_test.py\", line 23, in populateFdb",
"    self.fdb = fdb.Fdb(self.fdb_info)",
"  File \"ptftests/fdb.py\", line 18, in __init__",
" …
=> [fdb] Add New Line Between V4/V6 Addresses In FDb Template

ansible/TestbedProcessing.py, ansible/doc/README.new.testbed.Configuration.md, ansible/roles/sonic-common/tasks/sonicdocker.yml, ansible/roles/vm_set/tasks/add_topo.yml, ansible/roles/vm_set/tasks/renumber_topo.yml, ansible/swap_syncd.yml, ansible/testbed-new.yaml, ansible/vars/docker_registry.yml
Summary:
We already configured the docker registry with read only access by anonymous user. So no need to `docker login` before `docker pull`.
=> Access docker registry anonymously

tests/README.md
Summary:
Add example and guideline for how to run test scripts using pytest. Also explained the reason of why sonic-mgmt extended pytest options must be after test scripts on command line.
Updated sonic-mgmt/tests/README.md
=> Add pytest command line example to pytest README.md

tests/platform_tests/api/watchdog.yml
Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>
Summary:
=> [watchdog.yml] correct values for msn2xxx platforms

ansible/config_sonic_basedon_testbed.yml, ansible/group_vars/all/telemetry_certs.yml
Why I did:
Ported master PR https://github.com/Azure/sonic-mgmt/pull/1825
for 201811 so that we can run 209111 image using anisble-playbook.
=> [201811] Telemetry cert deployment

tests/qos/test_qos_sai.py
Add testcase for verifying buffer pool watermark. This test is currently disabled. Will enable it when the feature is fully tested.
=> [qos] Add buffer pool watermark tests

.github/PULL_REQUEST_TEMPLATE.md
Summary:
Fix typo in the Github PR template.
=> Fix typo in the Github PR template

ansible/host_vars/STR-ACS-SERV-01.yml, ansible/host_vars/STR-ACS-SERV-02.yml, ansible/host_vars/STR-ACS-VSERV-01.yml, ansible/lab, ansible/roles/vm_set/library/vm_topology.py, ansible/roles/vm_set/tasks/add_topo.yml, ansible/roles/vm_set/tasks/renumber_topo.yml, ansible/setup-management-network.sh, ansible/testbed_add_vm_topology.yml, ansible/testbed_refresh_dut.yml, ansible/veos_vtb, ansible/vtestbed.csv, tests/veos_vtb
- Add IPv6 address gateway address to br1 bridge.
- Fix IPv6 address for vlab-01 DUT to use a different address
instead of using gateway IP address.
- Update host_vars files to include IPv6 mgmt address.
Signed-off-by: SuvarnaMeenakshi <sumeenak@microsoft.com>
Summary:
PTF docker is provided with an IPv6 address to run IPv6 tacacs test. 
To ensure reachability, If PTF docker IP and DUT are in different IPv6 networks, ptf docker should be configured with gateway IPv6 address.
- Add IPv6 address gateway address to br1 bridge.
- Fix IPv6 address for vlab-01 DUT to use a different address instead of using gateway IP address.
- Update host_vars files to include IPv6 mgmt address.
- Bring up vms-kvm-t0 testbed after the changes.
Ensure that a default route is getting added in …
=> [IPv6]: Add IPv6 mgmt gateway address to server

tests/bgp/test_bgp_speaker.py
Summary:
This PR fix test failure of test_bgp_speaker_announce_routes_v6 by adding ping nexthop_v6. 
When there is no arp entry for next hop, routes learnt from exabgp will not be set down to ASIC. Therefore, this commit add a ping6 command for each next hop in ipv6 before ipv6 routes are announced.
This PR is to fix the failure of test_bgp_speaker_announce_routes_v6. When there is no arp entry for next hop, routes learnt from exabgp will not be set down to ASIC. This PR work around this issue with ping6 command to each next hop in ipv6.
Add a ping6 command to each next hop in ipv6 before ipv6 routes are announced.
Verified on Arista-7260 after clear arp cache and ipv6 neighbor cache.
```
platform linux2 -- Python 2.7.12, pytest-4.6.5, py-1.8.1, pluggy-0.13.1 -- …
```
=> [BGP&IPv6]Add ping in test_bgp_speaker_announce_routes_v6

tests/platform_tests/api/watchdog.yml
Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>
Summary:
=> [watchdog.yml] Add MSN3420 watchdog tests values

ansible/roles/fanout/templates/arista_7260cx3_deploy.j2
Summary: New 7260cx3 switch deployment template
Adding new ansible template for 7260cx3 device
Successfully deployed configuration for a lab fanout switch using this template
For Arista 7260cx3 device
=> New 7260cx3 deployment template

tests/copp/conftest.py, tests/copp/copp_utils.py, tests/copp/test_copp.py
Update test_copp to add option to install test dependencies syncd container by using proxy.
Test test_copp failed. Must be option to install test dependencies to running syncd container
Add option to install test dependencies to make test compatible.
Run test test_copp. Test passed.
=> [ test_copp ] add option to install test dependencies to running syncd container

tests/common/devices.py
I added two functions `get_container_autorestart_states(...)` and `get_critical_group_and_process_list(...)` which
are related to auto-restart feature in devices.py.
I tested these two functions on virtual testbed.
=> [pytest] Add auto-restart related functions in devices.py

tests/telemetry/test_telemetry.py
Summary:
This change is to fix the test_telemetry_ouput case failure. After the telemetry
service is restarted, the telemetry TCP port still needs some time to go up.
If immediately run the py_gnmicli.py script to get data from the telemetry
TCP port, the script may fail with "Connection refused". 
The fix added code to wait for the telemetry TCP port. When the port is up, then proceed with testing.
Test run the test_telemetry.py script, all cases passed.
=> Wait for telemetry port up after telemetry service is restarted

tests/common/plugins/sanity_check/checks.py
If pretest sanity checks fails and allow_recover is set, the BGP check
after adaptive recovery might fail due to its short wait time(120s).
Allowing the retry for BGP check when networking uptime is short to
wait BGP session to be established.
Summary:
In 7060 T1 nightly, `test_crm` fails in BGP check with unestablished neighbors. The reason is that the testcase always starts with DUT that has several stopped services and processes. Sanity check tries to do an adaptive recovery with `config reload` but the BGP sessions fail to establish after the short wait time(120s).
Allow retries for `BGP` check till networking uptime last enough.
=> [sanity_check] Allow retry for BGP check

ansible/library/minigraph_facts.py
Summary:
Updating minigraph facts support for new HW SKU
To run tests on new SKU - Arista-7060CX-32S-Q32
Updated conditional handling with new SKU.
Executed advanced_reboot tests.
=> Arista-7060CX-32S-Q32 SKU addition in mg facts

ansible/library/conn_graph_facts.py
Summary:
Refactoring conn_graph_facts.py. Solving outstanding review issues from PR #2194 
- Look up with either hostnames or anchor but not both.
- hostnames takes precedence of anchor.
- use os.path.join to build full path names.
- use safe_load to load yml file.
- add filepath argument to be ready for pytests.
Tested with remove-topo and add-topo.
=> [conn graph] refactoring connection graph look up code

tests/testbed_setup/test_gen_spy_testbed.py
Add the missing import for `conn_graph_facts_multi_duts`.
Summary:
run testcase `testbed_setup/test_gen_spy_testbed.py`
=> [test_gen_spy_testbed] Fix import error

tests/qos/files/qos.yml
Failures seen on Th nightly runs for xon testcases
Tested on Th T1 and T0 topologies
=> [qos] Fine tune Th xon params

test_reporting/kusto/flat_views.kql, test_reporting/kusto/heat_maps.kql, test_reporting/kusto/reports.kql, test_reporting/kusto/setup.kql
Summary: Add Kusto scripts for setup and common functions
To upstream the steps used to setup the database referenced in #2225.
Added the kusto queries/functions that were added to support the test report database.
Deployed the DB and executed queries against it.
N/A
N/A
To be added shortly.
=> [reporting] Add Kusto scripts for setup and common functions

tests/drop_packets/test_drop_counters.py
Summary: Fix failure of 'test_ip_pkt_with_exceeded_mtu' test case in 'test_drop_counters.py' test suite
- [+] Test case(new/improvement)
Fix failure of 'test_ip_pkt_with_exceeded_mtu' test case.
Added 'global' keyword.
Tested on the local setup.
=> Fix 'test_ip_pkt_with_exceeded_mtu' in test_drop_counters.py

tests/platform_tests/api/test_component.py, tests/platform_tests/api/test_psu.py
=> [Platform API][PSU][Component] Compare applicable data against values from platform.json

ansible/roles/fanout/tasks/fanout_sonic.yml, ansible/roles/fanout/templates/sonic_deploy.j2
1. For `sonic_deploy.j2`, use port alias to setup vlan config.
2. For SONiC 201803 images, there will be connection error because
docker `-H` option requires version >= 18.09. Change back to use `shell`
module with `doker exec`.
Summary:
To enable `SONiC` fanout setup.
```
```
=> [fanout.yml] Fix SONiC fanout setup

docs/pfc/GLOBAL_PAUSE_README.md, docs/pfc/PFC_PAUSE_LOSSLESS_README.md, docs/pfc/PFC_PAUSE_LOSSY_README.md
Summary: README files for some basic PFC test cases.
RDMA/PFC test cases need documents
=> [doc] Add README files for basic PFC test cases

docs/ecn/ECN_ACCURACY_README.md, docs/ecn/EGRESS_ECN_README.md
=> [doc] Add README files for basic ECN test cases

tests/platform_tests/api/test_fan_drawer_fans.py, tests/platform_tests/api/test_psu_fans.py
Summary:
fixing some typos in two tests 
To improve the quality of the PSU Fans and Fan Drawers Fans platform API test
Fixed the typos
Run PSU's fan tests , Fan Drawer Fan tests on a device with a populated platform.json present
Platform must have a populated platform.json present
Signed-off-by: vaibhav-dahiya <vdahiya@microsoft.com>
=> [Platform API][Fan][PSU][FanDrawer] Fix typos in Fan_Drawer_fans test and PSU_fans test

docs/pfcwd/PFCWD_BASIC.md
Summary: README file for a basic PFC watchdog test. 
=> [doc] Add README for a basic PFC watchdog test

ansible/roles/fanout/templates/mlnx_fanout.j2
Summary:
Fix CLI incompatibility appeared after release new Onyx version 
Fixed configuration script in j2 file
Deploy fanout using standard command  and verify basic fanout functionality
`ansible-playbook -i lab fanout.yml -l <fanout> -vvvvv`
no
any
=> Fix configuration script to avoid problems while configuring fanout

tests/platform_tests/api/test_watchdog.py
=> disable loganalyzer for test_watchdog

tests/platform_tests/broadcom/files/ser_injector.py
Summary:
Broadcom SER test fails because some memory location timeout waiting for ser fix.
- discovered more misaligned memory locations on TH2 and added them to the misaligned list.
- improve wait loop efficiency
- increase basic sample size
Tested change on TH and TH2 platforms. They both passed confident and basic level tests.
=> [broadcom ser] add more misaligned memory entries

setup-container.sh
Summary:
various enhancement on setup-container script
- build local container with correct user/group setup
- add private key into the container
- make workdir correct
- change default shell to /bin/bash
run ./setup_container.sh and check
=> various enhancement on setup-container script

ansible/library/multi-asic_aware_module_guidelines.md, ansible/library/multi-asic_aware_module_requirements.md
Summary:
Add document for guidelines of designing ansible modules for multi ASIC system
To support multi ASIC system testing, some of the customized ansible modules need to be updated. 
This change added a document with some guidelines for designing customized ansible modules that need to deal with multi ASIC.
=> Add document for guidelines of designing ansible modules for multi ASIC system

ansible/group_vars/sonic/sku-sensors-data.yml
Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>
Summary:
Align sensors labels for human readable output for MSN2700.
Modify 'sku-sensors-data.yml' file with correct labels from 'sonic-buildimage' repo.
Run sensors test.
=> [Mellanox] Align sensors labels for human readable output for MSN2700

ansible/group_vars/sonic/sku-sensors-data.yml
Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>
Summary:
Align sensors labels for human readable output for MSN2100.
Modify 'sku-sensors-data.yml' file with correct labels from 'sonic-buildimage' repo.
Run sensors test.
=> [Mellanox] Align sensors labels for human readable output for MSN2100

ansible/group_vars/sonic/sku-sensors-data.yml
Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>
Summary:
Align sensors labels for human readable output for MSN2010.
Modify 'sku-sensors-data.yml' file with correct labels from 'sonic-buildimage' repo.
Run sensors test.
=> [Mellanox] Align sensors labels for human readable output for MSN2010

ansible/doc/README.testbed.VsSetup.md
Summary:
simplify the doc for vs setup
remove build sonic-mgmt container, use setup_container.sh instead
=> [doc]: simplified the Vs Setup steps

ansible/lab
Summary:
Add 'model' field to example DuT in ansible/lab file, as this value is referenced in the platform API tests
To provide a complete example for the current state of tests
Add 'model' field to example DuT in ansible/lab file,
Run platform chassis tests, ensure the retrieved value is compared against this value
=> Add 'model' field to DuT in ansible/lab file

ansible/group_vars/sonic/variables, ansible/library/minigraph_facts.py
Signed-off-by: Nazar Tkachuk <nazarx.tkachuk@intel.com>
Summary:
Add new Barefoot Networks platform
Run related platform test
This change is BFN platform specific
=> [BFN] Add new Arista platform

ansible/library/monit_process.py, tests/platform_tests/test_cpu_memory_usage.py
Add test `platform_tests/test_cpu_memory_usage.py`:
1. Check DUT memory usage don't exceeds threshold.
For the following platforms, threshold is 75%.
x86_64-cel_e1031-r0
x86_64-arista_7050_qx32s
x86_64-arista_7050_qx32
For others, threshold is 60%.
2. Check process cpu percent don't persistently exceeds threshold: 50%.
Summary:
=> [platform_tests] Add test to check memory and cpu usage

tests/kvmtest.sh
Summary:
add test feature, test_procdockerstatsd, ifname mode to kvmtest suite.
run it offline.
=> [kvmtest]: add a few more tests to kvmtest suite

tests/kvmtest.sh, tests/platform_tests/test_cpu_memory_usage.py
Summary:
add cpu/mem test to kvmtest suite
run locally.
=> [kvmtest]: add cpu/mem to kvmtest suite

ansible/library/monit_process.py
Change cpu percentage to irix mode, which reflects single-core usage.
Summary:
Fixes https://github.com/Azure/sonic-mgmt/issues/2440
=> [monit_process] Change cpu percent to Irix mode

ansible/roles/test/files/ptftests/advanced-reboot.py
Summary:
The advanced-reboot.py script was stuck occasionally on some DUT. I did some investigation on this issue but haven't found the root cause. I noticed that some child processes was stuck in endless loop if warm-reboot/fast-reboot failed or DUT failed to get ready for testing, which may break the cleanup of ptf. This update breaks the endless loop in these cases.
This PR is to fix endless loop issues in ```advanced-reboot.py```, which might be related to the stuck of test cases in ```test_advanced_reboot```.
An event is triggered when timeout, and the worker process will watch the signal and exit from endless loop if the event is set.
1. I added some log to verify if worker process exited when some exceptions were raised.
2. Verified by running ```test_warm_reboot``` …
=> [advanced-reboot] Update advanced-reboot.py to avoid endless loop

ansible/config_sonic_basedon_testbed.yml, ansible/minigraph/lab-a7260-01.t0-116.xml, ansible/minigraph/lab-s6000-01.t0.xml, ansible/minigraph/lab-s6100-01.t0-64.xml, ansible/minigraph/str-msn2700-01.t0.xml, ansible/scripts/testmg.sh
Summary:
add script to test minigraph generation
run scripts/testmg.sh without error
=> [kvmtest]: add script to test minigraph generation

tests/kvmtest.sh
Summary:
add arp tests to kvm test suite
modify kvmtest.sh
run test locally
=> [kvmtest]: add arp tests to kvm test suite

tests/show_techsupport/test_techsupport.py
Summary: Use specific GRE type for barefoot hwsku
=> [BFN] Fix GRE type in show_techsupport test

tests/kvmtest.sh
Summary: Enable warm reboot test for kvm in PR test
Enable advanced reboot test for PR tests 
Enable advanced reboot test for PR tests and confirm it passes with all Jenkins test workers.
=> Enable advanced reboot test for PR tests 

tests/copp/test_copp.py
Summary: Fix COPP test regression errors
After https://github.com/Azure/sonic-mgmt/pull/2458 PR, COPP tests are failing due to:
```
@pytest.fixture(scope="class")
def copp_testbed(duthosts, rand_one_dut_hostname, creds, ptfhost, tbinfo, request):
"""
Pytest fixture to handle setup and cleanup for the COPP tests.
"""
duthost = duthosts[rand_one_dut_hostname]
test_params = _gather_test_params(tbinfo, duthost, request)
if test_params.topo not in (_SUPPORTED_PTF_TOPOS + _SUPPORTED_T1_TOPOS):
pytest.skip("Topology not supported by COPP tests")
>       _setup_testbed(duthost, creds, ptfhost, test_params)
E       TypeError: _setup_testbed() takes exactly 5 arguments (4 given)
```
Moved disable/enable container autorestart fixture usage to another Pytest fixture to handle setup …
=> Fix COPP regression error

tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
Summary:
Fix issue: check all fan speed failed 'list object has no attribute target_speed_file'
Fix issue: check all fan speed failed 'list object has no attribute target_speed_file'
The variable fan_data in check_all_fan_speed is no longer an instance of FanData due to previous change. Fixed it by loop the fan_data from other data structure.
Manually run the regression case
N/A
N/A
=> Fix issue: check all fan speed failed 'list object has no attribute target_speed_file'

tests/ixia/test_ixia_traffic.py, tests/ixia/test_tgen.py, tests/run_tests.sh
Skip tests using traffic generator currently in the nightly runs
Summary:
=> Skip traffic generator tests in nightly

tests/platform_tests/test_platform_info.py
Summary:
Skip log analyzer errors for particular test cases.
1. Skip "Error getting sensor data: dps460.*Kernel interface error" for test_thermal_control_psu_absence and test_turn_on_off_psu_and_check_psustatus
2. Skip "ERR pmon#thermalctld.*int() argument must be a string or a number" for test_show_platform_temperature_mocked
In some test cases, it shutdown powers or remove relevant sysfs files, and there is chance that SONiC daemons could read the power or sysfs file status during the test. It usually triggers an error log in syslog which caught by log analyzer and cause the test case fail. Since the test case is designed to shutdown power or remove relevant sysfs files, we need ignore such error logs during these test cases.
Add a fixture ignore_particular_error_log, and user can …
=> [Mellanox] skip particular error logs in test_platform_info.py

tests/vxlan/test_vnet_vxlan.py, tests/vxlan/vnet_utils.py
Summary:
fix leftovers that remained after test execution
I removed remained vnet related config and added Ethernet4 interface back to VLAN1000
run `py.test vxlan/test_vnet_vxlan.py --inventory "../ansible/inventory, ../ansible/veos" --host-pattern arc-switch1041-t0 --module-path ../ansible/library/ --testbed arc-switch1041-t0 --testbed_file ../ansible/testbed.csv --skip_sanity --disable_loganalyzer -v --log-cli-level info` <--- this test may add leftovers (before this fix)
run` py.test iface_namingmode/test_iface_namingmode.py::TestShowVlan::test_show_vlan_config --inventory "../ansible/inventory, ../ansible/veos, ../ansible/lab" --host-pattern arc-switch1041-t0 --module-path ../ansible/library/ --testbed arc-switch1041-t0 --testbed_file ../ansible/testbed.csv …
=> [vnet] fix leftovers: remove 'INTERFACE' entry from redis and add VLAN_MEMBER back in Cleanup block 

tests/qos/qos_sai_base.py
Replace all occurrences of assert used in qos sai base file with pytest_assert
Ran qos sai test on Th and it passed
=> [qos] Replace assert with pytest_assert

tests/arp/test_wr_arp.py
Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>
Added missing Ferret argument in wr_arp TC.
=> Added missing Ferret argument in wr_arp TC

tests/common/plugins/psu_controller/snmp_psu_controllers.py
Summary:
PSU controller support for Sentry4 PDU
Add snmp oids for Sentry4 PDU control
Turn on/off using : snmpset  -v 1 -c private -Ofenq {psu_ip} .1.3.6.1.4.1.1718.4.1.8.5.1.2.{unit}.{cord}.{outlet} i 1(on)/2(off)
Status check using : snmpwalk -v 1 -c public -Ofenq {psu_ip} .1.3.6.1.4.1.1718.4.1.8.3.1.1.{unit}.{cord}.{outlet}
=> Add psu controller support for sentry4 pdu

setup-container.sh
sonic-mgmt image name only allows all lower case. In case the user
name is mixed case, we need to change user name to all lower case.
Summary:
sonic-mgmt image name only allows all lower case. In case the user
name is mixed case, we need to change user name to all lower case.
change  user name to lower case.
run setup-container when username is mixed case
=> [setup-container]: force user name to lower case

tests/kvmtest.sh
Summary:
add several options for user to define the kvmtest behavior
allow user to skip refresh dut step by passing -n option.
run kvmtest -n option
=> [kvmtest]: improve kvmtest to parse options

tests/common/dualtor/dualtor_utils.py
Summary:
This PR add several new interfaces and fixtures in dualtor_utils.
Functions:
```
toggle_simulator_port_to_tor_a
toggle_simulator_port_to_tor_b
check_simulator_read_side
```
Fixtures:
```
toggle_all_simulator_ports_to_tor_a
toggle_all_simulator_ports_to_tor_b
```
The next plan is to toggle y_cable simulator ports with these newly implemented functions and fixtures.
This PR is to add several new interfaces and fixtures in dualtor_utils.
Verified by a demo script, which toggled all ports and verified returned status.
No.
No.
=> Implement more interfaces in dualtor_utils

ansible/roles/vm_set/files/mux_simulator.md, ansible/roles/vm_set/files/mux_simulator.py
Summary:
Enhance the mux simulator so that it would be easier to manipulate the mux status from test script side.
Add documentation.
This change made some enhancements to the mux simulator and added documentation.
* Add support of "toggle" active side.
* Add support of randomly set active side.
* Add support of set active side for all bridges of specified vm_set.
Use curl to test the affected APIs.
=> Enhance APIs of mux simulator and add documentation

tests/kvmtest.sh
Summary:
log for successful run is used for comparison
add -r option
run locally
=> [kvmtest]: preserve test log for successful run as well

docs/testplan/BGP-Allow-List.md, docs/testplan/BGP-BBR.md, docs/testplan/BGP-BGPMON.md, docs/testplan/BGP-TSA.md, docs/testplan/BGP-Update-Timer.md
Summary:
Add test plans for BGP.
Checked my notes and also followed the source codes for the tests
n/a
=> [testplan]: Add BGP testplans

tests/arp/test_arp_dualtor.py
Summary:
Topology marker for this test module has an extra set of parentheses.
=> [arp]: Fix topology marker for dual ToR tests

tests/drop_packets/fanout/mellanox/mellanox_fanout.py
Summary:
Change 'fanout_hosts' to 'fanout_host'
update tests/drop_packets/fanout/mellanox/mellanox_fanout.py file
run drop_counters test
N/A
N/A
=> Fix typo in tests/drop_packets/fanout/mellanox/mellanox_fanout.py

docs/testbed/README.testbed.Setup.md
improved server configuration steps and updates for ubuntu 20.04
added netplan networking
added ubuntu 20.04
and made some details more explicit.
rework of https://github.com/Azure/sonic-mgmt/pull/2557, I closed that since it had too many problems and focused on one change at a time.
Summary:
while using the docs to create my own setup I enhanced the details needed for the steps
Ubuntu 20.04 support
I have created my own setup and documented the steps taken and enhanced the docs where more details were needed.
I have done the steps described in the doc, in the order from the doc
added interface config using netplan for ubuntu 20.04 but also kept the old instructions for interfaces for ubuntu 18.04
this PR is only for documentation updates.
=> [Docs] improved server configuration steps and updates for ubuntu 20.04

azure-pipelines.yml
Summary:
add azure pipeline
https://dev.azure.com/sonicswitch/build/_build/results?buildId=2127&view=results
=> [ci]: add azure pipeline

tests/common/devices.py
Summary:
Fixes #2818
Some tests need to check CRM resource usage from time to time. A convenient tool could help.
This change added a new method 'get_crm_facts' to the SonicHost class. This method runs multiple sub-commands of the 'crm show' command, parses their output and returns the gathered CRM facts in a dict.
Tested a script like below:
```
import json
import logging
logger = logging.getLogger(__name__)
def test_case1(duthosts):
for duthost in duthosts:
crm_facts = duthost.get_crm_facts()
logger.info(json.dumps(crm_facts, indent=2))
```
=> Add method 'get_crm_facts' to SonicHost class for getting CRM facts

tests/kvmtest.sh
=> [kvmtest]: Add dual ToR ARP tests to KVM test suite

tests/common/ixia/common_helpers.py, tests/common/ixia/ixia_helpers.py, tests/common/ixia/qos_fixtures.py, tests/ixia/pfcwd/conftest.py, tests/ixia/pfcwd/files/pfcwd_basic_helper.py, tests/ixia/pfcwd/test_pfcwd_basic.py
Summary: Add [PFC watchdog basic test cases](https://github.com/Azure/sonic-mgmt/blob/master/docs/testplan/pfcwd/PFCWD_BASIC.md) implemented using [Tgen API](https://github.com/open-traffic-generator/ixnetwork)
We need PFC watchdog test cases
1. Add PFC watchdog related helper functions in tests/common/ixia/common_helpers.py 
2. Update tests/common/ixia/ixia_helpers.py to parse the latest fanout format
3. Implement test cases in tests/ixia/pfcwd/
I did test using SONiC switches and IXIA chassis. The Tgen API version is 0.0.73.
T0 topology using IXIA chassis as the fanout
https://github.com/Azure/sonic-mgmt/blob/master/docs/testplan/pfcwd/PFCWD_BASIC.md
=> [pfcwd] Add basic PFC watchdog test

.azure-pipelines/run-test-template.yml, azure-pipelines.yml, setup-container.sh, tests/kvmtest.sh
Summary:
add t1-lag kvmtest testbed
check pr build
=> add t1-lag kvmtest testbed

tests/tacacs/test_ro_user.py
New test cases to make sure readonly user could run allowed commands and cannot run privileged  commands.
=> Add test cases to test sudoers file

ansible/library/interface_facts.py, tests/common/devices.py
Update needed to interface_facts anisible module to fetch interface details from namespaces in multi-asic platforms.
The approach taken is to carve out the logic of interface details retrieval into a python script named "/tmp/gather_intf_ip_info.py". This python script will be copied on to the DUT when this ansible module is run. This script will have the same functional logic as earlier to retrieve the interface details. This script will be invoked per namespace in case of multi-asic platforms and once per host in case of a single asic platform. The data collected is given back in the similar format as before. 
The ansible module also accepts namespace as the parameter, where the interface facts from a specific namespace could be fetched.
Support interface facts retrieval for multi-asic …
=> [multi-asic] Update interface_facts to handle namespaces for multi_asic platforms

.github/CODEOWNERS
Summary:
Add default owners to be notified when PR was created in certain area.
Add default owners to be notified when PR was created in certain area.
=> [code owners] add some initial default code owners

tests/system_health/files/device_check.json, tests/system_health/files/external_check.json, tests/system_health/files/ignore_asic_check.json, tests/system_health/files/ignore_device_check.json, tests/system_health/files/ignore_fan_check.json, tests/system_health/files/ignore_psu_check.json, tests/system_health/mellanox/mellanox_device_mocker.py, tests/system_health/test_system_health.py
Summary:
1. Aligh system health test cases with latest production code
2. Fix issue when mocking fan speed value
3. Combine multiple mock together to save test time
Fix test cases to align with latest production code
1. Aligh system health test cases with latest production code
2. Fix issue when mocking fan speed value
3. Combine multiple mock together to save test time
Manually run the test cases
N/A
N/A
=> [test_system_health] Align system health test cases with production code and fix issues

tests/sflow/conftest.py, tests/sflow/test_sflow.py
Summary:
Sflow test suite checks if sFlow feature is enabled on DUT, and if not then skips all tests. 
By default, sFlow is disabled on DUT -  [init_cfg](https://github.com/Azure/sonic-buildimage/blob/afee1a851c5e96c54bfb933bd82fe369df932a88/files/build_templates/init_cfg.json.j2#L36),  [config](https://github.com/Azure/sonic-buildimage/blob/9e90fac18b3b741bc5dedc4a9d37ec423c0304dd/rules/config#L103).
So in order to run this tests automatically without manually turning sFlow feature, I added argument which can be passed to test to turn Sflow feature on DUT. 
Be able to run test_sflow cases automatically by passing an argument to TC, without manually changing sFlow feature status on DUT before TC run. 
Added a …
=> [sflow] Added an argument to enable Sflow feature on DUT

ansible/roles/vm_set/library/kickstart.py, ansible/setup-management-network.sh
Summary: Fix minor issues faced during virtual testbed bring up on u20.04
I have tried to bring up virtual testbed on clean u20.04 server and faced some issues, mostly python related
- install dependencies in proper way
- fix kikstart.py
Follow https://github.com/Azure/sonic-mgmt/blob/master/docs/testbed/README.testbed.VsSetup.md to bring up vtestbed
N/A
=> [testbed][KVM] Fix minor u20 issues

tests/kvmtest.sh
Summary:
add two more bgp tests to kvm t1-lag test
run test locally
=> [kvmtest]: add bgp update_timer/traffic shift tests

.gitignore
Summary: [.gitignore] Add auto-generated files to .gitignore
To prevent accidentally commiting/pushing auto-generated test files.
Updated the ignore file.
Checked `git status` and verified that logs, cache files, metadata, etc. are no longer present.
=> [.gitignore] Add auto-generated files to .gitignore

ansible/devutils, tests/common/plugins/psu_controller/snmp_psu_controllers.py
Summary:
Add PDU support to devutils
Add a tool to check DUT PDU status.
Leverage the existing PDU support to query status, turn on/off or reboot the device.
Reboot is implemented with turn off then turn off all PDU outlets associated with the DUT.
Added Json output for ping/list/pdu actions
Unify the host title/key to 'Host'.
Sort the output by hostname.
```
yinxi@681acf730601:/var/src/sonic-mgmt/ansible$ ./devutils -i str -g sonic -a pdu_status -l str-7260cx3-acs-1
+-------------------+----------+----------------------------------------------------------------------------------------------------------------------------+-----------+
| DUT               | Action   | PDU status                                                                                                                 | …
```
=> [devutils] add PDU support: status/on/off/reboot

tests/qos/files/mellanox/qos_param_generator.py, tests/qos/files/qos.yml, tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py, tests/saitests/sai_qos_tests.py
Summary:
Fix QoS test issues on Mellanox platform
Fix QoS test issues on Mellanox platform
- Skip DWRR weight change test on Mellanox platform
- Relax the checking at the beginning of PGSharedWatermark
It isn't necessary to check the lower bound of the shared buffer pool watermark at the beginning of the test
- Fetch the source and destination ports of the shared headroom pool test from dutConfig instead of using hardcoded numbers
See above
Run QoS test
=> Fix QoS test issues

ansible/dualtor/y_cable_simulator_client.j2
=> [y_cable_sim]: Use consistent upper/lower ToR terms

ansible/group_vars/lab/lab.yml, tests/common/plugins/tacacs.py, tests/kvmtest.sh, tests/tacacs/tac_plus.conf.j2, tests/tacacs/test_jit_user.py, tests/tacacs/test_ro_user.py
Summary:
* 73c6e5d7 2021-02-06 | [kvmtest]: add test_jit_user to kvmtest (HEAD -> jit, lgh/jit) [Guohan Lu]
* 527b65fc 2021-02-06 | [tacacs/test_jit_user]: test same user with different privilege level (ceos) [Guohan Lu]
* a5847c2d 2021-02-05 | [test_ro_user]: check stderr to make sure error is due to sudo issue [Guohan Lu]
run tests
=> various improvement of tacacs tests

tests/tacacs/test_ro_user.py
Summary: Fix the test case running against 201911 image, which support only `sonic_installer` but not `sonic-installer`.
=> Refine RO test case for 201911 image

tests/common/fixtures/ptfhost_utils.py, tests/scripts/icmp_responder.py, tests/templates/icmp_responder.conf.j2
Add icmp_responder that runs over ptf to reply ICMP echo-request packets
sent by the ToR's LinkProber to simulate a physical server.
Summary:
Simulate the physical servers for dualtor testbeds that could reply ICMP echo-request(heatbeat).
Add a service `icmp_responder` to `ptf` container.
demo test
```python
import pytest
from tests.common.fixtures.ptfhost_utils import run_icmp_responder
pytestmark = [
pytest.mark.topology("any"),
]
TARGET_SERVER = "192.168.0.100/21"
DUT_PORT = "Ethernet8"
@pytest.fixture(scope='function', autouse=True)
def setup_intf(ptfhost):
ptf_port = "eth2"
ptfhost.shell("ifconfig %s %s" % (ptf_port, TARGET_SERVER))
yield ptf_port
ptfhost.shell('ifconfig %s 0.0.0.0' % ptf_port) …
```
=> [dualtor] Add icmp_responder

tests/platform_tests/api/watchdog.yml
Signed-off-by: Arun Saravanan Balachandran <Arun_Saravanan_Balac@dell.com>
Summary:
Add timer values to be used for testing watchdog APIs in DellEMC S6100
=> [watchdog.yml] Add test values for DellEMC S6100

tests/ixia/pfcwd/test_pfcwd_basic.py
Add reboot and restart scenarios for pfcwd. Depends on #2880 
Verified the reboot and restart code flow. the pfcwd flow was validated on ixia testbed through #2880
=> [rdma] Add reboot and restart scenarios for pfcwd

test_reporting/report_data_storage.py, test_reporting/report_uploader.py
Summary:
We want to keep track of testbed health/reachability similar to how we view test results.
I added a new category of data to upload based on the output of the devutils tool.
Uploaded ping data to kusto and verified that it was ingested correctly.
=> [report_uploader] Add support for uploading ICMP ping data from devutils

tests/platform_tests/api/watchdog.yml
Summary: Update watchdog.yaml with arista watchdog config
Fixes # 2971
To allow TestWatchdogApi to pass fully on Arista platforms
Updated watchdog.yml to include suitable timeout configuration for Arista watchdog
Ran the test with the updated file to confirm that the test passes
Applies to arista platforms only
Signed-off-by: Andy Wong andywong@arista.com
=> Update watchdog.yaml with arista watchdog config

tests/ixia/ecn/files/helper.py, tests/ixia/pfc/files/helper.py, tests/ixia/pfcwd/files/pfcwd_basic_helper.py, tests/ixia/pfcwd/files/pfcwd_runtime_traffic_helper.py, tests/ixia/pfcwd/test_pfcwd_basic.py
Summary: Some minor fixes of RDMA IXIA test cases
1. Check if flows complete in max_attempts rounds/seconds. 
2. Fix a variable name  
I did test using Mellanox SN2700 and IXIA chassis
=> [rdma] Minor fixes

ansible/lab
Summary:
There's not enough data from sonic-mgmt for device facts fetched by platform API.
In Arista testbed we use veos file, the example lab file needs more fields in order to pass the platform API tests.
Some platform API tests fail because it cannot fetch the values for device data from duthost_vars.
https://github.com/Azure/sonic-mgmt/blob/master/tests/platform_tests/api/test_chassis.py#L61
Added additional fields for Arista 7260 in lab file.
=> [Arista] Update Arista 7260 lab example data

ansible/library/port_alias.py
Reverts Azure/sonic-mgmt#2887
This PR causes minigraph deploy fail.
=> Revert "Parse platform.json, hwsku.json for generate minigraph"

setup-container.sh
- Fix -i option in the script.
- Update USER env variable
Summary: MInor fixes
Fix script to be up to date with help output
See changes
Use -i option
N/A
=> [setup-container.sh] setup-container minor fixes

tests/qos/files/dynamic_buffer_param.json, tests/qos/test_buffer.py
Summary:
Add test cases for shared headroom pool on top of the dynamic buffer calculation.
1. Update the existing test cases for the dynamic buffer calculation in the following aspects:
- When checking the pool size, take shared headroom pool related parameters into account
- Replace "headroom" with "size" as the it stands for size of the PG.
2. Add test case for shared headroom pool configuration test.
Run the regression test.
=> Support shared headroom pool on top of dynamic buffer calculation 

tests/platform_tests/api/conftest.py
On the Mellanox platform the SFP related platform APIs are not migrated to python3 yet, thus have to make the TestSfpApi an exception to start the related test with python2
To fix a platform API test issue on the Mellanox platform, part of the Mellanox platform APIs not migrated to python3 yet, for these have to start the test with python2 instead of python3.
Before starting the platform API test server, judge the test class name and the ASIC type, if the condition hits, start the test with python2.
run the related platform API test on the Mellanox platform
Only take effects on the Mellanox platform.
N/A
=> [Mellanox] make Mellanox SFP related platform API test starting with python2

ansible/recover_server.py
Summary:
This PR is to update ```recover_server.py```
1. Add tests to syspath to address FactsCache issue
2. start-topo-vm -> start-vms.
This PR is to update ```recover_server.py```
1. Add tests to syspath to address FactsCache issue
2. Use ```start-topo-vm``` to reloace ```start-vms``` to start all vms in advance.
Verified on server_17.
No.
No.
=> Update server recovery script

docs/testplan/dual_tor/dual_tor_orch_test_plan.md
Add test plan for:
1. IPinIP tunnel
2. ECMP hashing
3. Decap flow
4. CRM
Summary:
=> Create dual_tor orchagent/tunnel test plan

ansible/devutils, ansible/library/conn_graph_facts.py
Summary:
This PR updates ```devutils``` and ```conn_graph_facts.py```.
1. Use conn_graph_facts to retrieve pdu info and console info in devutils
2. Update conn_graph_facts library to support standlone running.
This PR is to update ```devutils``` and ```conn_graph_facts.py```.
1. Update ```conn_graph_facts.py``` to support calling in ```devutils```
2. Update ```devutils``` to get pdu and console info from ```conn_graph_facts```. Info in inventory is used as a fallback.
1. Verified pdu info retrieved from ```conn_graph_facts``` is correct
2. Verified console info retrieved from ```conn_graph_facts``` is correct
3. Verify ```conn_graph_facts.py``` is compatible with Ansible after update.
No.
No.
=> Integrate conn_graph_facts into devutils

tests/conftest.py
Summary:
This PR implements two fixtures for geting randomly selected/unselected dut host.
Some test cases need to get the ```selected``` and ```unselected``` ToR frequently.  
Please see code.
Verified by a sample script.
No.
No.
=> Implement fixtures to get selected/unselected DUT host

tests/pfcwd/test_pfcwd_warm_reboot.py
Pfcwd warm reboot tests need to be run only on T0 topologies
Summary:
=> [pfcwd] Update topo for warm reboot test

tests/qos/test_buffer.py
Summary:
Enhance the test case for exceeding the headroom limit
- Don't use hard-coded value of the super long cable length
Find out the longest cable length by retrying in a loop
- Use log analyzer to verify whether the expected error messages are found
Run the regression test
=> [Dynamic buffer calc] Enhance the test case for exceeding the headroom limit

tests/saitests/sai_qos_tests.py
Summary:
Update PFC Xoff test to handle LAG ports
Before starting the test send a packet with same parameters (src/dst IP, proto ID) to find out the LAG rx port. Use the received port as part of the test.
```
samaddik@svcstr-server-2:/var/sonic-mgmt/tests$  pytest qos/test_qos_sai.py --testbed=vmsvc1-t1-nmasic-acs-1 --inventory=../ansible/strsvc  --testbed_file=../ansible/testbed.csv --host-pattern=svcstr-nmasic-acs-1  --module-path=../ansible/library --disable_loganalyzer --skip_sanity  -k PfcXoffLimit --log-level DEBUG                                               
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in …
```
=> [Qos pfcXoff] Update PFC Xoff test to handle LAG ports

tests/common/reboot.py, tests/platform_tests/test_reboot.py
This is for adding a test for soft-reboot.
Summary:
To verify all dockers and services are running as expected after soft-reboot.
Add the soft-reboot test to test_reboot.py
Run a pytest with following command after installing the soft-reboot on the DUT.
```
export PYTEST_SCRIPTS="platform_tests/test_reboot.py"
export SWITCH="<DUT_NAME>"
export TOPO="<TESTBED_TOPO>"
export JOB_NAME="test_reboot"
pytest ${PYTEST_SCRIPTS} --testbed=${TOPO} --inventory=../ansible/str --testbed_file=../ansible/testbed.csv --host-pattern=${SWITCH} --module-path=../ansible/library --show-capture=no -v -k "test_soft_reboot"
```
=> Add test for soft-reboot

tests/bgp/test_bgpmon.py, tests/common/helpers/generators.py
Summary:
This PR moves ```route_through_default_routes```  and ```generate_ip_through_default_route``` from ```test_bgpmon.py``` to ```generators.py``` since same logic is needed for dualtor test cases.
This PR is to refactor code.
Move ```route_through_default_routes```  and ```generate_ip_through_default_route``` from ```test_bgpmon.py``` to ```generators.py```.
Verified by running ```test_bgpmon```, and no error is found.
No.
No.
=> Refactor code for generating random ip

tests/pfcwd/test_pfcwd_function.py
Test if mmu changes (updating dynamic threshold) in between pfcwd storm/restore events have an impact on the pfcwd functionality
Ran the test on Th2 and Mellanox and it passed
=> [rdma] Test if mmu change has impact on pfcwd functionality

ansible/devutil/conn_graph_helper.py
Summary:
Recent PR #2823 missed ```conn_graph_helper.py```. This PR is to fix the issue.
Next job is to add a test for ```devutils```.
This PR is to check in missing file for devutils.
Checkin missing file.
Verified with a clean repo, and confirmed everying is fine.
No.
No.
=> Add missing conn_graph_helper.py for devutils

tests/common/dualtor/control_plane_utils.py
Summary:
Some changes were made to the STATE_DB schema, necessitating changes to this util. 
* Update tables/fields to match new STATE_DB schema and remove unused table
* Use `redis-dump` to improve performance
* Refactor into a single method
* Allow passing 'all' for intf_names
Call the function to verify both APP and STATE DB during tests
=> [dualtor]: Update control plane utils

tests/common/dualtor/dual_tor_mock.py
Summary:
Move dual ToR mock closer to full feature parity with real dual ToR testbeds.
* Use new `rand_selected_dut` fixture
* Remove prefix from PEER_SWITCH table loopback IP
* Add `peer_switch` and `subtype` fields to DEVICE_METADATA table
=> [dualtor_mock]: Various improvements:

docs/testplan/pfcwd/PFCWD_2SENDER_2RECEIVER.md, tests/ixia/pfc/files/helper.py, tests/ixia/pfcwd/files/pfcwd_2sender_2receiver_helper.py, tests/ixia/pfcwd/test_pfcwd_2sender_2receiver.py
Summary: Test PFC watchdog in a three-node topology with 2 senders and 2 receivers. 
We need more PFC watchdog test cases
1. Implement helper functions in tests/ixia/pfcwd/files/pfcwd_2sender_2receiver_helper.py 
2. Implement the test case in tests/ixia/pfcwd/test_pfcwd_2sender_2receiver.py
I did test using SONiC switches and IXIA chassis. The Tgen API version is 0.0.75. The IXIA Linux API server version is 9.10.
N/A
T0 topology using IXIA chassis as the fanout
The document is also included in the PR
=> [rdma] Test PFC watchdog in a three-node topology with 2 senders and 2 receivers

tests/platform_tests/api/watchdog.yml
Summary:
Common timer values in watchdog.yml file for testing watchdog API for DellEMC platforms
=> Common timer values for testing watchdog API for DellEMC platforms

tests/common/devices/base.py, tests/common/plugins/sanity_check/README.md, tests/common/plugins/sanity_check/__init__.py, tests/common/plugins/sanity_check/checks.py, tests/common/plugins/sanity_check/constants.py, tests/conftest.py
Summary:
Currently if post test sanity check is enabled, the exactly same set of checks
will be performed just like pre test sanity check. Sometimes we may want to
perform different set of checks for post test sanity check.
This change improved sanity check in many ways:
* Added --post_check command line option.
* Added --post_check_items command line option for fine tuning post test sanity
check items.
* Added 'post_check_items' keyword argument for the sanity_check marker for fine
tuning post test sanity check items.
* Added support of passing arguments to the check functions defined in check
fixtures.
* Added argument 'stage' to 'do_checks' function. Then the check functions
would be able to know the stage (pre or post test) of checking.
* Used shell_cmds module to run …
=> Improve post test sanity check

tests/common/plugins/sanity_check/checks.py
Check if the file change in rw folder is as expected when secureboot feature enabled.
Summary:
=> Add rw file change sanity check for secureboot

tests/common/dualtor/dual_tor_mock.py, tests/common/utilities.py, tests/dualtor/conftest.py, tests/dualtor/test_orch_stress.py
Summary:
Fixes #2802 
To cover the stress test case in the Dual ToR Orchagent test plan https://github.com/Azure/sonic-mgmt/blob/master/docs/testplan/dual_tor/dual_tor_orch_test_plan.md
Changes:
* Added new test script for dualtor stress test
* Added new fixture mock_server_ip_mac_map in dual tor mock utility
* Used minigraph facts for getting Vlan interface name and IP. The minigraph facts is cached. It is faster than config facts.
* Improved topology check of applying the apply_mock_dual_tor_tables and
apply_mock_dual_tor_kernel_configs fixtures
* Tested on T0 KVM.
* Tested on dual ToR physical testbed.
N/A
t0, dualtor
https://github.com/Azure/sonic-mgmt/blob/master/docs/testplan/dual_tor/dual_tor_orch_test_plan.md
=> Add dualtor orchagent stress test

ansible/library/snmp_facts.py, docs/testplan/SNMP-interfaces-test-plan.md, tests/snmp/test_snmp_interfaces.py
Summary: This PR implements a new test case test_snmp_interfaces_mibs according to the following test plan.
Test should verify correct behavior of ports MIB objects such as:  ifIndex, ifMtu, ifSpeed, ifAdminStatus, ifOperStatus, ifAlias, ifHighSpeed, ifType. 
**Testplan:**
* Retrieve facts for a device using SNMP
* Get expected values for a device from DUT per each port.
* Compare that facts received by SNMP are equal to values received from system.
Add test case to verify proper work of Interfaces MIB
Retrieve facts for a device using SNMP and compare with data collected from DUT per each port. 
Run test on `master` and `201911` images, on `t0` and `t1` topology. …
=> [SNMP] Add SNMP test case to test Interfaces MIB

docs/testplan/dual_tor/dual_tor_orch_test_plan.md
Update orchagent test cases to cover routes pointing to nexthops that are active/standby
Summary:
=> [DualTor] Update orch test for route cases

tests/common/dualtor/dual_tor_io.py
Summary:
We run a PTF script on PTF to sniff traffic. The PTF script calls scapy's sendrecv.sniff which by default capture
on all the PTF interfaces, including the backplane interface for announcing routes from PTF to VMs.
On VMs, the PTF backplane is the next hop for the announced routes. So, packets sent by DUT to VMs
are forwarded to the PTF backplane interface as well. Then on PTF, the packets sent by DUT to VMs can
be captured on both the PTF interfaces tapped to VMs and on the backplane interface. This will result in
packet duplication and fail the test. 
This change is to add capture filter to filter out all the packets destined to the PTF backplane interface.
Scapy 2.3 supports specifying a list of interfaces to be sniffed on. I have tried scapy 2.3 to sniff only …
=> [dualtor] Filter out packets destined to PTF backplane interface during sniffering

ansible/roles/vm_set/tasks/add_topo.yml
Signed-off-by: Roman Savchuk <romanx.savchuk@intel.com>
Summary:
Fixes https://github.com/Azure/sonic-mgmt/issues/3061
Can not add ptf topology for CT
Added condition to add-topo.yml for skip announce routes when topo contains 'ptf' 
Run arp/test_neighbor_mac.py. Test passed
=> [ Issue 3061 ] Fix for ptf topo creation

ansible/roles/fanout/templates/mlnx_fanout.j2
Summary:
Fix test fail that appeared while executing test_pfcwd_timer_accuracy.py test
I have changed instruction that executed during configuring onyx switch.
Now we run docker inside of management vrf
`py.test pfcwd/test_pfcwd_timer_accuracy.py --inventory "../ansible/inventory, ../ansible/veos" --host-pattern <testbed>-<topo> --module-path ../ansible/library/ --testbed <testbed>-<topo> --testbed_file ../ansible/testbed.csv --allow_recover -v --log-cli-level info`
=> [Mellanox] Fix Onyx fanout configuration template

tests/kvmtest.sh
=> [kvm]: add bgp/test_bgp_update_timer.py to t0 topo

tests/common/mellanox_data.py
Summary: Fixed test case test_platform_info.py for MSN4600C
Fixes # (issue) previous test fails with error: Failed: Thermal mock data mismatch
and
Found extra data in actual_data: 
```
[ 
{ 
"temperature": "N/A", 
"crit low th": "N/A", 
"high th": "N/A", 
"crit high th": "N/A", 
"warning": "False", 
"timestamp": "20210323 21:34:11", 
"low th": "N/A", 
"sensor": "xSFP module 61 Temp" 
}, 
{ 
"temperature": "N/A", 
"crit low th": "N/A", 
"high th": "N/A", 
"crit high th": "N/A", 
"warning": "False", 
"timestamp": "20210323 21:34:11", 
"low th": "N/A", 
"sensor": "xSFP module 62 Temp" 
}, 
{ 
"temperature": "N/A", 
"crit low th": "N/A", 
"high th": "N/A", 
"crit high th": "N/A", 
"warning": "False", 
"timestamp": "20210323 21:34:11", 
"low th": "N/A", 
"sensor": "xSFP module 63 Temp" 
}, 
{ …
```
=> [Mellanox] Fixed test_platform_info.py for SN4600C

tests/snmp/test_snmp_lldp.py
[SNMP][LLDP][multi-asic]: Modify LLDP test case to support multi-asic 
platform. Changes made to retrieve minigraph facts from all namespaces.
Signed-off-by: SuvarnaMeenakshi <sumeenak@microsoft.com>
Summary:
SNMP LLDP test case should be modified to support multi-asic platform.
- Retrieve minigraph facts from all namespaces.
Verified on multi-asic VS testbed and single asic VS testbed.
Output from multi-asic msft_four_asic_vs hwsku :
pytest --testbed=vms-kvm-four-asic-t1-lag --inventory=veos_vtb --testbed_file=vtestbed.csv --host-pattern=vlab-08 --module-path=../ansible/library "snmp/test_snmp_lldp.py" --show-capture=no --disable_loganalyzer --skip_sanity -v
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python …
=> [SNMP][LLDP][multi-asic]: Modify LLDP test case to support multi-asic

tests/common/plugins/pdu_controller/__init__.py, tests/conftest.py, tests/lldp/test_lldp.py, tests/pc/test_po_cleanup.py, tests/pc/test_po_update.py, tests/snmp/conftest.py, tests/snmp/test_snmp_cpu.py, tests/snmp/test_snmp_default_route.py, tests/snmp/test_snmp_interfaces.py, tests/snmp/test_snmp_lldp.py, tests/snmp/test_snmp_loopback.py, tests/snmp/test_snmp_memory.py, tests/snmp/test_snmp_pfc_counters.py, tests/snmp/test_snmp_phy_entity.py, tests/snmp/test_snmp_psu.py, tests/snmp/test_snmp_queue.py, tests/snmp/test_snmp_v2mib.py
Modified testcases for T2 topology, these are very small changes mainly replaced 'rand_one_dut_hostname' with 'enum_rand_one_per_hwsku_frontend_hostname' for multi-dut.
Summary:
Modified testcases to run on multi-dut
Replaced 'rand_one_dut_hostname' with 'enum_rand_one_per_hwsku_frontend_hostname' 
Modified and ran on T2 topology
=> Modified SNMP, LLDP and PC testcases for T2 topology

tests/qos/qos_sai_base.py
Summary:
Fixes a typo in qos_sai_base.py
Fix a typo in qos_sai_base.py
Fix the typo
Run regression test
=> [QoS] Fix a typo in qos_sai_base.py

tests/drop_packets/test_configurable_drop_counters.py
Summary:
Extend configurable drop counters test.
Add new test cases for the next drop reason:
-   SIP_LINK_LOCAL 
-   DIP_LINK_LOCAL 
Ran `drop_packets/test_configurable_drop_counters.py`  locally on devices to verify the functionality was working
N/A
**T0** topology
=> Add new config drop counters tests for SIP/DIP_LINK_LOCAL

ansible/roles/test/files/ptftests/advanced-reboot.py
Summary:
The nightly KVM continuous warmboot test often fails within 10 iterations. Mostly the failure is due to `date` command returning empty output. This is due to control plane going down at the time when date is being executed.
Nightly pipeline failures: https://dev.azure.com/mssonic/build/_build?definitionId=124&_a=summary
```
2021-04-13T05:53:28.3581459Z Exception: Error collecting current date from DUT: empty value returned
2021-04-13T05:53:28.3582132Z 
2021-04-13T05:53:28.3582678Z FAIL
2021-04-13T05:53:28.3582864Z 
2021-04-13T05:53:28.3583500Z ======================================================================
2021-04-13T05:53:28.3584746Z FAIL: advanced-reboot.ReloadTest
2021-04-13T05:53:28.3585941Z --------------------------------------------------------------- …
```
=> [warm-reboot] Start finalizer-check after control plane is UP

ansible/library/reduce_and_add_sonic_images.py
Summary:
Do cleanup to free up disk space before installation.
For A7060 that has limited disk space, `upgrade_sonic` sometimes fails.
Remove unnecessary logs, dumps and core files.
* create a big file in `/var/dump` to consume up the free disk spaces.
* run `upgrade_sonic`
```
```
=> [upgrade_sonic] Do cleanup before installation

tests/restapi/conftest.py, tests/restapi/restapi_operations.py, tests/restapi/test_restapi.py
Summary:
Add tests for validating the RESTAPIs exposed by SONiC
- [ - ] Test case(new/improvement)
To validate the RESTAPIs exposed by SONiC. 
Add a new directory and all related tests to it.
Ran the test and made sure they all pass
T0
=> Add RESTAPI tests

tests/common/dualtor/dual_tor_utils.py, tests/common/dualtor/tunnel_traffic_utils.py, tests/common/utilities.py, tests/dualtor/test_ipinip.py, tests/dualtor/test_orchagent_active_tor_downstream.py, tests/dualtor/test_orchagent_standby_tor_downstream.py
Summary:
Test that with neighbor entry, the traffic to the server is passed directly, without neighbor entry, the traffic is dropped.
1. add testcase `test_active_tor_remove_neighbor_downstream_active`
2. put shared code from `test_standby_tor_remove_neighbor_downstream_standby`  to common modules.
=> [dualtor][orchagent] Add active ToR neighbor testcase

tests/common/fixtures/ptfhost_utils.py, tests/dualtor/test_link_drop.py
Summary:
Test failures/skips
- Make `run_garp_service` fixture compatible with dual ToR testbeds
again
- Add topology marker for link drop tests
Ran a dual ToR test case on a dual ToR testbed and verified it passed
Ran dual ToR IP-in-IP test case on a T0 testbed and verified it passed
=> [dualtor]: Test fixes

ansible/roles/test/files/ptftests/advanced-reboot.py
Summary:
Fix the below error that is seen in integration tests. Example is here:
https://dev.azure.com/mssonic/build/_build/results?buildId=11734&view=logs&j=551384a3-3c3d-5d98-9a93-ab579ce10658&t=dcc0ef7a-c27d-5084-36c2-e0f4d142c187
```
E                   "======================================================================", 
E                   "ERROR: advanced-reboot.ReloadTest", 
E                   "----------------------------------------------------------------------", 
E                   "Traceback (most recent call last):", 
E                   "  File \"ptftests/advanced-reboot.py\", line 1168, in runTest", 
E                   "    self.handle_post_reboot_test_reports()", 
E                   "  File \"ptftests/advanced-reboot.py\", line 1108, in …
```
=> [advance_reboot] Check for IO variables value before reporting downtime

ansible/vars/topo_tgen_t0-3.yml, ansible/vars/topo_tgen_t1-3-lag.yml
Define T0 and T1 topologies for RDMA Tgen tests
=> [rdma] Define topologies for Tgen tests

tests/route/test_route_perf.py
Summary: Ensure interface exists before adding neighbor in test_route_perf.py
Fixes https://github.com/Azure/sonic-mgmt/issues/3380
There are test failures of test_route_perf.py due to interfaces do not exist. This PR checks the existence of the interface before proceeding.
Get a list of existing interfaces and only use the ones that exist.
=> Ensure interface exists before adding neighbor in test_route_perf.py

spytest/tests/system/test_ssh.py
N/A
Summary:
Enhanced the script to make use of replace() function instead of strip().
N/A
Change the python strip() function to replace().
N/A
N/A
N/A
N/A
=> Fix for Spytest issue:#3160

tests/common/plugins/ptfadapter/ptfadapter.py
Summary:
This PR fixed below exception.
```
self = <DataPlane(Thread-15, stopped 139691644352256)>
def kill(self):
"""
Stop the dataplane thread.
"""
self.killed = True
self.waker.notify()
self.join()
>       del self.ports
E       AttributeError: ports
```
The exception will be raised if ptfadapter failed to establise TCP connection to ```ptf_nn_agent``` because ```self.ports``` is not defined yet at such case.
This PR is to fix ```del self.ports``` exception in ptfadapter.
Add a flag ```self.connected``` to mark if the connection is established successfully. The ```self.kill``` is not called if ```self.connected``` is ```False```. 
Verified on MSN2700, both positive and negative cases.
No.
=> Fix 'del self.ports' exception in ptfadapter.

test_reporting/requirements.txt
Summary:
While running the test report uploading script in sonic-mgmt docker installed with newer version
of azure.kusto.data package, below ImportError was hit:
```
python3 report_uploader.py -c test_result -e vms20-t1-dx010-6#12366 ../results SonicTestData
File "report_uploader.py", line 10, in <module>
from report_data_storage import KustoConnector
File "/azp/agent/_work/1/s/test_reporting/report_data_storage.py", line 8, in <module>
from azure.kusto.data import KustoConnectionStringBuilder
File "/var/johnar/env-python3/lib/python3.6/site-packages/azure/kusto/data/__init__.py", line 5, in <module>
from .client import KustoClient, KustoConnectionStringBuilder, ClientRequestProperties
File …
```
=> Specify dependent package 'aiohttp' for test reporting

tests/ixia/test_tgen.py
Signed-off-by Wei Bai webai@microsoft.com
Summary: Update Tgen API sample script
Update Tgen API sample script
=> [rdma] Update Tgen API sample script

tests/ixia/ecn/test_dequeue_ecn.py, tests/ixia/ecn/test_red_accuracy.py, tests/ixia/pfc/test_global_pause.py, tests/ixia/pfc/test_pfc_pause_lossless.py, tests/ixia/pfc/test_pfc_pause_lossy.py, tests/ixia/pfcwd/test_pfcwd_a2a.py, tests/ixia/pfcwd/test_pfcwd_basic.py, tests/ixia/pfcwd/test_pfcwd_m2o.py, tests/ixia/pfcwd/test_pfcwd_runtime_traffic.py
Tgen marker was incorrectly applied at testcase level instead of file level
Summary:
=> [rdma] Apply tgen marker at file level

tests/arp/files/ferret.py, tests/arp/test_wr_arp.py
Summary: Check vlan_port in config db, and use it in the response packet generated by Ferret script.
`test_wr_arp ` fails for some platforms/images. This is due to the response packet in Ferret script is generated for the incorrect destination port.
```
E               "stderr": "WARNING: No route found for IPv6 destination :: (no default route?)\n/usr/local/lib/python2.7/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.\n  from cryptography.hazmat.backends import default_backend\nwr_arp.ArpTest ... FAIL\n\n======================================================================\nFAIL: …
```
=> [wr_arp] Fix test_wr_arp - use vxlan_port defined in DUT in the response packet

tests/snmp/test_snmp_phy_entity.py, tests/system_health/mellanox/mellanox_device_mocker.py
Summary: Fixes for Test issues after changes
1. snmp test - the usage of function "_check_psu_status_after_power_off" was changed. 
https://github.com/Azure/sonic-mgmt/commit/05c5fa93c2bf6a98da9a9b8eadbe59aa68069e7d
now the function getting the "creds" of all systems and not DUT only.
2. system_health tests - the method "_file_exist" was removed.
https://github.com/Azure/sonic-mgmt/commit/3012631b67c2093fd27e341358d9add258b27785
but the test was not changed
=> Fix system health tests

tests/route/test_static_route.py
Summary: Add test for static route feature
Test for the newly added static route feature.
Add a vlan static route and send packets to an address in the prefix. Check if the packet gets forwarded to the expected port.
Run the test on kvm and dut and confirm that the test passes using images with static route feature.
This test case supports t0 topology.
=> Add test for static route feature

tests/platform_tests/link_flap/link_flap_utils.py
Summary:
```test_cont_link_flap``` failed on because following errors
```
pytest_assert(wait_until(100, 2, check_orch_cpu_utilization, duthost, orch_cpu_threshold),
"Orch CPU utilization {} > orch cpu threshold {} before link flap"
>                 .format(duthost.shell("show processes cpu | grep orchagent | awk '{print $9}'")["stdout"], orch_cpu_threshold))
E       Failed: Orch CPU utilization  > orch cpu threshold 10 before link flap
```
The root cause for the failure is helper function ```check_orch_cpu_utilization``` calls ```show processes cpu``` to retrieve the cpu usage of orchagent, but the output of ```show processes cpu``` is truncated automatically according to the shell width. For example, command ```orchangent``` might be truncated into ```orchage+```. As a …
=> Fix check_orch_cpu_utilization helper function.

tests/platform_tests/cli/test_show_platform.py
Fixed validation for test_show_platform_syseeprom
Summary: Fixed validation for test_show_platform_syseeprom
Previously test failed due to incorrect validation
Changed logic where we compare output
Executed test case 'test_show_platform_syseeprom'
Mellanox only
any
=> [Mellanox] Fixed validation for test_show_platform_syseeprom

test_reporting/README.md
Summary: Add upload script instructions to README
To add some more basic setup steps/validations and clarify instructions for using the report_uploader script to push test results to Kusto.
Updated the README.
N/A
=> [test_reporting] Add upload script instructions to README

ansible/roles/test/files/acstests/everflow_policer_test.py
Summary: fixed everflow_policer_test for BF
- fixed original packet extraction
The test was failing at the step of original packet comparison, because it didn't take into account ERSPAN header presence on top of original packet. Modified the test to extract original packet correctly for further payload check
- added ERSPAN header check
Fix test issue and expand packet check
Noticed an original packet check fails, fixed packet extraction. 
py.test --inventory=../ansible/lab,../ansible/veos --testbed_file=../ansible/testbed.csv --module-path=../ansible/library -v -rA --topology=t1 everflow/test_everflow_testbed.py -k test_everflow_dscp_with_policer
=> fixed everflow_policer_test for BF

tests/console/test_console_loopback.py
Summary:
Add loopback test(ping-pong) for console switch
Verify data can go out through the console switch and come back through the console switch
Verify data can go out through the console switch and come back through the console switch
Listening a serial port A and send "pong" after "ping" came, then send "ping" to opposite port B (Port Range: 17-36)
Run tests on physical DUT with below configuration:
```bash
sudo config console enable
sudo config console add 1 -b 9600
sudo config console add 2 -b 9600
sudo config console add 3 -b 9600
sudo config console add 4 -b 9600
sudo config console add 5 -b 9600
sudo config console add 6 -b 9600
sudo config console add 17 -b 9600
sudo config console add 18 -b 9600
sudo config console add 19 -b 9600
sudo config console add 20 -b 9600
sudo config …
```
=> [console][loopback] Add loopback test(ping-pong) for console switch

tests/bgp/conftest.py
Summary:
This PR is to fix setup failure in ```test_bgp_gr_helper```.
```
if not wait_until(60, 5, duthost.check_default_route):
>           pytest.fail("ipv4 or ipv6 default route not available")
E           Failed: ipv4 or ipv6 default route not available
```
The failure is caused by insufficient waiting time for checking default routes. I found that it needs around ```70``` seconds for default routes being built. However, we only wait ```60``` seconds. This PR increase the waiting time to ```100``` seconds.
Another fix is to refactor the ```setup_bgp_graceful_restart``` code to ensure that configuration on VMs will be restored even test failed. 
This PR is to fix setup failure in ```test_bgp_gr_helper```.
Increase the waiting time to ```100``` seconds.
Verified on …
=> Fix setup failure in test_bgp_gr_helper

tests/dualtor/test_orchagent_standby_tor_downstream.py
Summary:
Test `test_downstream_standby_mux_toggle_active` is currently failing on real dualtor testbed.
The failure is due to:
1. Wrong destination address for the route added.
2. Wrong tor selected for monitoring traffic packets.
Add a route to a address in 10.x  network. Earlier this route was added to the server which also was the nexthop address.
Fix the test by using correct torhost objects to monitor server and tunnel traffic respectively.
Tested on a real dualtor testbed and the test passes with the fix.
```
22:54:09 facts_cache.read                         L0093 INFO   | Load cache file "/var/src/Networking-acs-sonic-mgmt/tests/_cache/str2-7050cx3-acs-09/mg_facts.pickle" failed with exception: IOError(2, 'No such file or directory')
22:54:10 facts_cache.write …
```
=> [dualtor orchagent] Fix failures in case standby_mux_toggle_active

ansible/group_vars/sonic/sku-sensors-data.yml
Summary:
Mellanox Spectrum-2 platform's sensor conf have been updated in PR https://github.com/Azure/sonic-buildimage/pull/7726 and  PR https://github.com/Azure/sonic-buildimage/pull/7725, sensor test case need to been updated accordingly
Update sensor data in sku-sensors-data.yml to make the sensor test align with the latest sensor conf on the Mellanox platform.
update the sku-sensors-data.yml according to the latest sensor conf
Run sensor test on relevant Mellanox Spectrum-2 platforms.
Change only for the Mellanox platform.
=> [Mellanox] Update sku-sensors-data.yml according to sonic-buildimage change

tests/restapi/test_restapi.py
Summary:
Use VNID above 7036001 while configuring VNETs
To not conflict with reserved VNIDs
=> [Vnet/Restapi] Use high values for VNI

tests/run_tests.sh
Make `run_tests.sh` ready for `testbed.yaml`.
Summary:
Make `run_tests.sh` ready for `testbed.yaml`.
```
./run_tests.sh -c vlan/test_vlan.py -f ../ansible/testbed.yaml -i ../ansible/lab -n lab-t0 -e "--collect-only"
```
=> [run_tests.sh] Enable testbed.yaml

ansible/group_vars/sonic/sku-sensors-data.yml, tests/platform_tests/test_sensors.py
Summary:
Update sku-sensors-data.yml  and test_sensors.py to support Mellanox MSN4600 A0 and A1 system.
To have sensor test support Mellanox MSN4600 A0 and A1 system. 
Add MSN4600 A0 and A1 sensor data to sku-sensors-data.yml 
Update test_sensors.py to differentiate A0 and A1 system.
Run sensor test against Mellanox 4600 A0 and A1 system.
Change only take effect on the Mellanox platform.
=> [Mellanox] update sensor test case for MSN4600 A0 and A1 system

ansible/roles/test/files/ptftests/sad_path.py
Summary:
In the sad_path for warmreboot test, the test was using v4 command for both v4 and v6
In the sad_path for warmreboot test, the test was using v4 command for both v4 and v6
=> Use the right BGP neighbors command based on v4/v6

azure-pipelines.yml, setup-container.sh
Summary:
When we build sonic-mgmt image on azp, we have AzDevOps user already. We don't need to add user and group.
but we need to change user home directory from /var/AzDevOps to /home/AzDevOps. Because ssh need proper private key PATH.
=> [CI] Fix vmss scaling issue when using azp built docker-sonic-mgmt image.

tests/bgp/test_bgpmon.py
Summary:
Sometimes the bgp/test_bgpmon.py testing failed with "BGPMon Peer connection not established".
This should be a timing issue. Sometimes, the exabgp process needs longer time to startup for
the bgp monitor session to be established.
The fix is to firstly wait for the exabgp process to startup. Then wait for the bgp monitor session
to be established.
Test run the test_bgpmon.py script multiple times on VS setup. All passed.
=> Improve robustness of test_bgpmon.py

ansible/roles/vm_set/library/vm_topology.py
Signed-off-by: Ze Gan <ganze718@gmail.com>
Summary:
=> [fixbug] Skip to move bp port to docker if neighbor devices are sonic

tests/pfc/test_unknown_mac.py
Summary:
This PR is to fix failure of ```test_unknown_mac``` on dualtor testbed.
Two updates:
1. Randomly select ip address that is not in ```MUX_CABLE``` table
2. Toggle to the selected tor before testing to address the ```ping``` failure.
This PR is to fix ```test_unknown_mac``` on dualtor testbed.
1. Randomly select ip address that is not in ```MUX_CABLE``` table
2. Toggle to the selected tor before testing to address the ```ping``` failure.
Verified on both T0 and dualtor testbed.
No.
No.
=> Fix ```test_unknown_mac``` on dualtor testbed

tests/bgp/test_bgpmon.py
Summary:
```test_bgpmon``` failed with below error
```
E       AssertionError: Received expected packet on port 34 for device 0, but it should have arrived on one of these ports: [28, 29, 30, 31].
E       ========== RECEIVED ==========
E       0000   52 54 00 6C 5E 6E D4 AF  F7 4D A4 44 08 00 45 C0   RT.l^n...M.D..E.
E       0010   00 3C D4 4E 40 00 40 06  50 8C 0A 01 00 20 0B 00   .<.N@.@.P.... ..
E       0020   00 01 9E 63 00 B3 EF 16  57 BA 00 00 00 00 A0 02   ...c....W.......
E       0030   F7 BC 01 1B 00 00 02 04  05 B4 04 02 08 0A E5 AF   ................
E       0040   6E 6F 00 00 00 00 01 03  03 07                     no........
E       ==============================
```
It was because helper function ```get_default_route_ports``` called ```minigraph_facts``` to retrieve …
=> Fix ```test_bgpmon``` on dualtor testbed

ansible/plugins/filter/filters.py
Summary:
Fix the bad indentation of the filter plugin file.
Make the indentation of 4 spaces.
=> [Ansible] Fix indentation  of the filters

ansible/library/lag_facts.py
If the switch is running an older image, and multi_asic is not present,
then use default values or don't call functions in that module.
Signed-off-by: Saikrishna Arcot <saiarcot895@gmail.com>
Tested with an internal setup running a 201811 image, where multi_asic is not present.
=> [test_lag_2] Fix import error if multi_asic is not present

tests/acl/Untitled-1, tests/acl/templates/acltb_test_rules.j2, tests/acl/templates/acltb_test_rules_part_2.j2, tests/acl/templates/acltb_v6_test_rules.j2, tests/acl/templates/acltb_v6_test_rules_part_2.j2, tests/acl/test_acl.py
Summary:
Fixes #3635 
ICMP type/code match was recently added to acl-loader, so we need to validate the functionality.
Added a new test case and new rules for IPv4 and IPv6.
Ran new test cases locally.
=> [acl] Add tests for matching ICMP type/code

tests/qos/qos_sai_base.py, tests/saitests/sai_qos_tests.py
The changes in this PR allow pytest qos tests to be run against 201811 branch
Ran qos pytest testcases against a 201811 branch
=> [qos] Enable pytest qos runs on 201811

ansible/roles/test/files/ptftests/dir_bcast_test.py
Summary: update test to run it on t0-56 topology
the test is under adaptation tests plan to t0-56
add special condition to t0-56 topology
manually test run
=> [dir_bcast_test] update test to run on t0-56 topology

tests/common/config_reload.py, tests/common/plugins/sanity_check/constants.py, tests/common/plugins/sanity_check/recover.py, tests/k8s/test_config_reload.py, tests/nat/nat_helpers.py, tests/platform_tests/test_reload_config.py, tests/vlan/test_vlan.py, tests/vxlan/test_vnet_route_leak.py
Modify sonic-mgmt test cases to handle new config reload behavior. Config reload will perform system checks before proceeding. If the listed system checks fail config reload will not execute.
Summary:
To enhance the test cases as per new config reload behavior.
Added system check in tests before executing config reload command so that it would not fail. Additionally add new test case to validate config reload command behavior.
Run config reload platform tests.
=> Modifying tests to adapt to new config reload system checks

tests/common/plugins/allure_server/__init__.py
Improvements to allure server plugin
- added to Allure report info about SONiC version, platform, hwsku, asic
- added cleanup for reports data, after report generated
Summary: Improvements to allure server plugin
Added additional info to allure reports about SONiC vesrion
See in code
Executed tests with and without Allure
no
any
=> Improvements to allure server plugin

ansible/vars/topo_t0-backend.yml
Summary:
Define `t0-backend` to describe storage backend t0 topology.
Add `t0-backend.yml`
=> [Ansible] Add t0-backend topology

tests/qos/test_pfc_counters.py
Summary:
Fixes https://github.com/Azure/sonic-buildimage/issues/8038
Fixes test errors of ```test_pfc_counters```.
```test_pfc_counters::test_pfc_pause/unpause``` failed because pfc counter doesn't increase as expected. The root cause of the issue is ```fast-reboot``` will disable all ```flex_counters```
https://github.com/Azure/sonic-utilities/blob/4818360d7d9f5460169bce9a9f87f44311647a64/scripts/fast-reboot#L674
```
if [[ "$REBOOT_TYPE" = "fast-reboot" ]]; then
CONFIG_DB_FILE=/etc/sonic/config_db.json
COUNTERPOLL_DISABLE_RC=0
/usr/local/bin/counterpoll config-db disable $CONFIG_DB_FILE || COUNTERPOLL_DISABLE_RC=$?
if [[ COUNTERPOLL_DISABLE_RC -ne 0 ]]; then
error "Failed to disable counterpoll. Exit code: $COUNTERPOLL_DISABLE_RC"
/usr/local/bin/counterpoll config-db enable …
```
=> Enable flex counter for ports in ```test_pfc_counters```

tests/route/test_route_perf.py
Summary:
Increase route change check timeout, to make the test stable.
Make sure the test is stable.
Manually on different systems
=> [test_route_perf] increase route change check timeout

tests/fib/test_fib.py
Summary:
Make `test_fib` compatible with backend topologies
1. In retrieving fib info, add support to parse subinterfaces as the destination ports
2. Adding pseudo default ipv4 and ipv6 routes to the fib.
Run `test_fib`
```
fib/test_fib.py .                                                                                                                                                                                         [100%]
=========================================================================================== 1 passed in 43.87 seconds ===========================================================================================
```
=> [test_fib] Enable backend topologies

tests/arp/conftest.py
Summary:
Enable `test_arp` for storage backend topologies.
Select testing interfaces from the vlan sub interfaces for storange
backend topologies.
run `test_arp`
```
arp/test_arpall.py::test_arp_unicast_reply[str2-7050qx-32s-acs-03-None] PASSED                                                                                                                            [ 20%]
arp/test_arpall.py::test_arp_expect_reply[str2-7050qx-32s-acs-03-None] PASSED                                                                                                                             [ 40%]
arp/test_arpall.py::test_arp_no_reply_other_intf[str2-7050qx-32s-acs-03-None] PASSED …
```
=> [test_arp] Enable storage backend topologies

.github/CODEOWNERS
Summary: Update platform_tests code owner
=> [code owners] Update platform_tests code owner

ansible/library/minigraph_facts.py
Summary:
1. fix the variable error.
2. add vlan type.
=> [minigraph_facts] Improve minigraph_facts

tests/common/dualtor/tunnel_traffic_utils.py
Summary:
Fixes https://github.com/Azure/sonic-buildimage/issues/8086
`test_orchagent_slb` failed due to the unmatched queue counter check, this is due to that there might exist other queues that have 10 packets the same as the expected queue.
1. let `_check_queue` use `re.findall` to search all queues that has 10 packets.
2. clear queue counters when entering `tunnel_traffic_monitor`
```
dualtor/test_orchagent_slb.py::test_orchagent_slb PASSED                                                                                                                                                  [100%]
========================================================================================== 1 passed in 303.37 seconds …
```
=> [dualtor] Enhance `tunnel_traffic_monitor`

docs/testplan/HTTP_copy-test-plan.md, tests/http/start_http_server.py, tests/http/test_http_copy.py
Signed-Off By: Andoni Sanguesa
Summary:
Adds a test that checks that the DUT is able to access external objects via HTTP.
This test existed in the Arista testplan but was not present for SONiC.
An HTTP server is started on the localhost where a large file is downloaded. The DUT uses `curl` to fetch the file from the HTTP server. File integrity is checked by comparing checksums for the file before and after transport.
The test passed on my platform and confirmed that the file was copied to the host and the dut manually. 
I've been encountering the issue found in #3778 , so I've had to skip the sanity checks to confirm that this test passes. This shouldn't be an issue since this test does not interact with the T1 leaf nodes in any way. The only communication necessary is between the host …
=> added http copy test

ansible/roles/vm_set/files/mux_simulator.py
Summary:
Improve the robustness of mux-simulator
In rare case, the muxy interfaces in PTF docker could be gone. Parsing the output may get None for
'out_port'. This will cause exception and crash the mux-simulator. Since mux-simulator is shared
by multiple dualtor setups, it should be able to handle such abnormal scenario. 
This change added more checks while parsing the flows to avoid crash. Then the good testbed 
won't be affected.
=> Improve the robustness of mux-simulator

ansible/roles/test/files/helpers/remove_ip.sh, tests/scripts/remove_ip.sh
Summary:
Let `remove_ip.sh` removes IP addresses assigned to to sub-interfaces.
=> [remove_ip.sh] Support sub-interfaces

docs/testbed/README.md, docs/testbed/README.testbed.Example.Config.md
Add a md document for how to get the testbed information
Summary:
None
md doc
=> Add a example doc for how to manual check the testbed topology

ansible/roles/test/files/ptftests/IP_decap_test.py, ansible/roles/test/files/ptftests/fib_test.py, tests/common/fixtures/fib_utils.py, tests/common/fixtures/ptfhost_utils.py, tests/conftest.py, tests/decap/test_decap.py, tests/fib/test_fib.py
Summary:
Fixes https://github.com/Azure/sonic-buildimage/issues/8098 
The IP decap testing was only designed for single ToR. This PR is to adapt the IP decap testing for dualtor testbed as well.
The IP decap testing was only designed for single ToR. This PR is to adapt the IP decap testing for dualtor testbed as well.
Changes:
* Add common fib_utils.py script for FIB related helper functions.
* Updated the fib testing to use the tools in common fib_utils.py file.
* Update the IP decap testing scripts to support dualtor.
Test run the script on both single ToR and dualToR testbeds.
=> Update IP decap testing for dualtor

tests/common/snappi/__init__.py, tests/common/snappi/common_helpers.py, tests/common/snappi/port.py, tests/common/snappi/qos_fixtures.py, tests/common/snappi/snappi_fixtures.py, tests/common/snappi/snappi_helpers.py, tests/snappi/test_snappi.py
Reverts Azure/sonic-mgmt#3766 since the build is using the new docker
=> Revert "Revert "Snappi sample""

tests/common/plugins/ptfadapter/__init__.py
Summary:
depends on #3808 
Enable testcases to use original ports for storage backend topologies.
Since `ptfadapter` is a module-level fixture, we could modify its port mapping behavior by setting a test module global variable so that it could be parsed by `ptfadapter` fixture to determine its port choice.
=> [ptfadapter] Support two ptf port mapping modes

tests/pc/test_lag_2.py
Summary:
```test_lag_2[lacp_rate]``` set ```/tmp``` as test running dir. However, the setting is not safe since there are junk scripts in ```/tmp```, and these files may be imported and run by ptf.
This PR changes the test running dir from ```/tmp``` to ```/tmp/acstests```.
This PR is to make ```test_lag_2``` more robust.
This PR changes the test running dir from ```/tmp``` to ```/tmp/acstests```.
Verified on SN4600, T1 testbed.
No.
No.
=> Change test running dir for test_lag_2

tests/platform_tests/conftest.py
Summary: Kexec timing calculation from syslog messages is overwritten by bgp log messages.
This happens due to same variable is first set and then unset as part of same function call by syslog and bgp log parsing.
Time data is missing for `offset_from_kexec` due to kexec time being overwritten to "N/A":
```
{
"offset_from_kexec": {
"database": "",
"finalizer": "",
"init_view": "",
"syncd_create_switch": "",
"fpmsyncd_reconciliation": "",
"port_init": "N/A",
"port_ready": "N/A",
"sai_create_switch": "",
"neighbor_entry": "N/A",
"default_route_set": "N/A",
"apply_view": "",
"lag_ready": "N/A",
"route_deferral_timer": ""
},
"controlplane": {
"arp_ping": "",
"downtime": "74.22523"
},
"time_span": {
"radv": "59.476844",
"bgp": "46.913575",
"syncd": "29.556605",
"swss": …
```
=> [advance-reboot] Fix reboot timing collection error

tests/common/fixtures/fib_utils.py, tests/fib/test_fib.py
Summary:
Restore changes of #3734 that are removed by #3702 . 
```
fib/test_fib.py::test_basic_fib[True-True-1514] PASSED                                                                                                                                                    [ 33%]
```
=> [test_fib] Enable storage backend topologies

tests/common/fixtures/fib_utils.py, tests/fib/test_fib.py
=> Revert "[test_fib] Enable storage backend topologies"

ansible/library/reduce_and_add_sonic_images.py
Summary:
ansible module issue commands with 'sh' as shell.
update the syntax to be sh compatible
Trigger a test when the swap file is in use.
=> [installer] issue command to be sh compatible

ansible/restart_nightly_ptf.py
Summary:
Restart testbeds' ptf that have pipelines defined.
Run all testbeds in each server per process.
=> Add script `restart_nightly_ptf` to restart nightly testbed ptf

tests/common/plugins/allure_server/__init__.py
Allure report URL print moved to be at the end(as possible) of tests output
Allure report URL print moved to be at the end(as possible) of tests output
Summary: Allure report URL print moved to be at the end(as possible) of tests output
It is better to find report URL at the end of test session output
See code
Executed tests and checked allure report URL
=> Allure report URL print moved to be at the end(as possible) of tests output

ansible/library/fabric_info.py, ansible/library/port_alias.py, ansible/library/test_facts.py, ansible/library/topo_facts.py
Summary:
make script compatible for both python2  and python3
use python3 as interpreter and run the deploy-mg
=> [python3]: make modules python2/python3 compatible

tests/qos/files/qos.yml, tests/qos/qos_sai_base.py
Summary:
Test parameters update due to change in behavior of disable port function
Updated test params for TD3 based systems
Verified on TD3 based setups
Arista-7050CX3-32S-C32, Arista-7050CX3-32S-D48C8
=> QoS test cases fixes for TD3 based systems

ansible/group_vars/sonic/variables, tests/qos/files/qos.yml, tests/qos/qos_sai_base.py
Adding test infrastructure parameters for TH3 based systems
Summary:
Adding test infrastructure parameters for TH3 based system
Updated QoS related test files
verified on T0 topology of Dell Z9332 systems.
T0
=> TH3 test parameters for Dell Z9332 systems

tests/common/constants.py, tests/common/devices/sonic.py, tests/ipfwd/conftest.py, tests/ipfwd/test_mtu.py
Summary:
Fixes https://github.com/Azure/sonic-mgmt/issues/3879 
Fix the nightly testcase failure.
https://github.com/Azure/sonic-mgmt/issues/3879 
Update interface/sub-interface fetch logic to compatible with backend storage t1 topology, details in the code.
Run the testcase and make sure they passed
ipfwd/test_mtu.py::test_mtu[str2-7050qx-32s-acs-03-None-1514] PASSED [ 50%]
ipfwd/test_mtu.py::test_mtu[str2-7050qx-32s-acs-03-None-9114] PASSED [100%]
=> FIX:  fix ipfwd/test_mtu testcase failure in backend storage topology

ansible/group_vars/sonic/variables, tests/drop_packets/test_drop_counters.py, tests/everflow/test_everflow_testbed.py, tests/iface_namingmode/test_iface_namingmode.py
Summary: Changes to skip unsupported test cases on TH3 platform
1. https://github.com/Azure/sonic-buildimage/issues/6357 - Since Broadcom has confirmed that Mirror policing is not supported  on TH3, skipping this test
2. https://github.com/Azure/sonic-buildimage/issues/8424 - DATAACL is not programmed on TH3. Test cases that lookup ACL table error out when DATAACL is not configured
Mirror policing and DATAACL programming are not supported on TH3. 
Added checks to skip the unsupported tests on TH3. Two kinds of checks are added
1. TH3 based check for scripts that program mirror policing 
2. DataACL exist check in facts for ACL cases that expect DATAACL table entry. TH3 runs are triggered with DATAACL disabled.
Manually triggered the following tests on TH3 based setup and …
=> [TH3] Skip unsupported test cases on 9332

tests/ipfwd/conftest.py
Fixed a small python format error.
Summary:
=> ipfwd: In 'conftest.py' Fixed format error

ansible/module_utils/port_utils.py
Summary:
Add new Ragile platform
Run tests against RA-B6510-48V8C
This change is Ragile platform specific
=> [Ragile] Add new platform RA-B6510-48V8C

tests/kvmtest.sh
Summary:
add test_static_route to topo t0
kvmtest
=> [kvmtest]: add route/test_static_route.py to topo t0

ansible/roles/vm_set/tasks/main.yml, ansible/testbed_renumber_vm_topology.yml
Summary:
Some nightly might not able to acquire the apt lock during restart-ptf
because other running nightly is holding the lock. Since only deployed
testbeds needs to run restart-ptf, we could assume that the common
package installation/update is done during the testbed deployment.
Let's disable the package installation for restart-ptf.
Let's check variable `package_installation` for every apt installation/update in the role `vm_set`'s `main.yml`.
only when it is not defined or evaluates to `true` will the package installation/update step be triggered.
Run two `restart-ptf` in parallel and no more errors like:
```
TASK [vm_set : Install docker-ce] **************************************************************************** …
```
=> [restart-ptf] Disable apt package installation

ansible/library/announce_routes.py
Summary:
Fixes #4096
As for now, `t0-backend` still have BGP default route present, let's remove it from the fib.
=> [announce_route] Disable announcing default route for storage backend

tests/conftest.py, tests/platform_tests/fwutil/conftest.py, tests/platform_tests/fwutil/fwutil_common.py, tests/platform_tests/fwutil/test_fwutil.py
Implemented the fwutil test plan here: 
https://github.com/Azure/sonic-mgmt/blob/master/docs/testplan/FWUtil-test-plan.md
See HLD
See HLD
Tested on CPLD / ONIE on Mellanox 2010 / 2100 / 2410 / 2700 / 3420 / 3700 / 3800 / 4600 / 4700
Currently running in mellanox internal regression. 
See HLD. Every platform will need to provide custom `firmware.tar.gz` file. Will update the HLD and a wiki page to have a very specific specification / instructions soon.
N/A Platform Test
Pending, need to create wiki page and update HLD.
=> Implement FWUtil Test Plan

ansible/roles/vm_set/templates/cleanup.sh.j2
Summary:
enhance cleanup.sh.j2, make sure remove be executed successfully
otherwise recover pipeline will be blocked, and images need to be delete manually
cleanup.sh executed failure will block subsequent tasks in recover pipeline,
and it requires to delete docker images manually.
add -f while deleting, uniq to make sure bash run successfully.
run it on server 27
=> enhance cleanup.sh.j2, make sure remove be executed successfully

tests/platform_tests/api/conftest.py
Summary: platform api tests - made tests to better communicate "method is not implemented" issue
- made platform api tests to clearly notify about not implemented Platform API methods
Currently it is difficult to understand that a test failure happened because of the tested method not implemented:
```
>           pytest_assert(False, err_msg)
E           Failed: Unable to retrieve fan_drawer 0 serial number
platform_tests/api/platform_api_test_base.py:32: Failed
```
The PR resolves the issue with an additional message that clearly communicates the root cause:
```
>           raise LogAnalyzerError(result)
E           LogAnalyzerError: {'match_messages': {'/tmp/syslog.igk-1-dut.2021-08-20-11:26:21': ["Aug 20 13:12:51.079211 igk-1-dut WARNING pmon#platform_api_server.py: API …
```
=> platform api tests: made tests to better communicate "method is not implemented" issue

tests/conftest.py, tests/run_tests.sh, tests/sai_qualify/conftest.py, tests/sai_qualify/sai_infra.py, tests/scripts/saiserver.sh
Enable SAI testbed and run SAI test cases in PTF
Co-authored-by: yizhouwang <yizhouwang@microsoft.com>
Summary:
Run SAI test cases in PTF, including prepare saiserver in DUT and prepare the test cases, then start run test cases and get back the result.
Run SAI test cases from PTF
prepare saiserver in DUT and prepare the test cases, then start run test cases and get back the result.
run it in pipeline
BRCM
=> Enable SAI testbed and run SAI test cases in PTF

tests/common/dualtor/mux_simulator_control.py
Summary:
This PR is to add a verification after toggling all mux cable interfaces.
We found that some test case, like ```test_fdb``` failed because mux cable didn't toggle to expected ToR. To detect the error before test running, a verification is added in fixture ```toggle_all_simulator_ports_to_rand_selected_tor```.
This PR is to add a verification after toggling all mux cable interfaces.
Call SONiC CLI ```show mux cable status``` to retrieve mux cable status, and verify all status are expected.
Verified on dualtor testbed. The fixture works as expected.
Dual-tor specific. 
No.
=> Check mux cable status after toggling

tests/ipfwd/conftest.py
Summary:
refine backend topology assertion code in ipfwd/conftest.py
refine backend topology assertion code in ipfwd/conftest.py
Shorten assertion with dict get_with_default function
Rerun testcase
ipfwd/test_mtu.py::test_mtu[str2-7050qx-32s-acs-03-None-1514] PASSED                                      [ 50%]
ipfwd/test_mtu.py::test_mtu[str2-7050qx-32s-acs-03-None-9114] PASSED                                      [100%]
------------------------- generated xml file: /var/src/sonic-mgmt-int/tests/logs/tr.xml -------------------------
=> refine backend topology assertion code in ipfwd/conftest.py

tests/configlet/everlow_delete.json, tests/configlet/test_add_rack.py, tests/configlet/util/common.py, tests/configlet/util/configlet.py, tests/configlet/util/files_create.py, tests/configlet/util/helpers.py, tests/configlet/util/strip.py, tests/kvmtest.sh
Summary:
Added test case for configlet to test AddRack scenario.
Provide test coverage for AddRack scenario
Wrote a test code to simulate AddRack scenario and test.
Run the test to pass
None
T1
=> configlet test code for AddRack scenario

tests/autorestart/test_container_autorestart.py
Signed-off-by: Yong Zhao <yozhao@microsoft.com>
Summary:
- [x ] Bug fix
- [x ] 201911
This PR aims to skip the fixture function if the parameterized container name is `unknown`.
I used the `pytest_require(...)` to decide whether the container name is correct or not.
I tested this change on DuT `str-msn2700-03`.
N/A
N/A
=> [auto-restart] Skips fixture function if container name is unknown.

docs/testbed/README.testbed.VsSetup.md
Signed-off-by: Ze Gan <ganze718@gmail.com>
Summary:
To disambiguate the Doc for VsSetup. Some new users think the parameters `-k vsonic` is for SONiC DUT.
Add more description for the parameters.
=> [Doc]: Clarify the Readme for VsSetup

tests/common/utilities.py, tests/pfc/test_unknown_mac.py
Summary:
Fixes #4033
1. enhance test_unknown_mac testcase, fix failure in backend T0 topology, test sub interfaces instead of portchannels in backend topology.
2. code refine.
Fix test_unknown_mac testcase failure in backend T0 topology,
test sub interfaces instead of portchannels in backend topology.
Run it again:
pfc/test_unknown_mac.py::TestUnknownMac::test_unknown_mac[dscp-3] PASSED [ 33%]
pfc/test_unknown_mac.py::TestUnknownMac::test_unknown_mac[dscp-4] PASSED [ 66%]
pfc/test_unknown_mac.py::TestUnknownMac::test_unknown_mac[dscp-8] PASSED [100%]
-------- generated xml file: /var/src/sonic-mgmt-int/tests/logs/tr.xml ---------
========================== 3 passed in 281.17 seconds ==========================
=> fix test_unknown_mac testcase failure in backend T0 topology

tests/bgp/templates/bgp_no_export.j2, tests/bgp/templates/bgp_plain.j2, tests/bgp/test_bgp_bounce.py
=> Revert "[test_bgp_bounce] Fix BGP template issues"

tests/bgp/test_bgp_bbr.py
Summary:
Fixes https://github.com/Azure/sonic-buildimage/issues/8425
Improve the robustness of `test_bgp_bbr`
Improve test_bgp_bbr:
1. for the route check on the first ToR that receives the update and
DUT, let's keep checking for a period of time to see if the route's
presence.
2. for the route check on the DUT, add extra check to verify the route
is advertised to the selected VMs.
Run over `t1` and `t1-backend`
=> [bgp] Improve test_bgp_bbr

tests/dualtor_io/test_heartbeat_failure.py
=> Revert "[test_heartbeat_failure] skip the heartbeat test"

ansible/library/extract_log.py, tests/common/plugins/loganalyzer/loganalyzer.py, tests/conftest.py
loganalyzer first collect logs from /var/log/syslog*
add more debug info to collect how logs are extracted
from /var/log/syslog* for log analyzer
Summary:
loganalyzer first collect logs from /var/log/syslog*
add more debug info to collect how logs are extracted
from /var/log/syslog* for log analyzer
=> [loganalyzer]: add more logging to debug loganalyzer

tests/qos/test_buffer.py
Summary: added a topo mark for test_buffer
- added a missing topo mark
Enable the test by marking its topo
=> added a topo mark for test_buffer

tests/common/dualtor/mux_simulator_control.py, tests/fib/test_fib.py
Summary:
Fixes https://github.com/Azure/sonic-buildimage/issues/8519
Fixes https://github.com/Azure/sonic-buildimage/issues/8103
Improve `test_fib` stability over dualtor testbed
Add a few improvements:
1. For `test_basic_fib`:
1.1 Add back the logic to toggle the ports to random side.
1.2 Use fixture `toggle_all_simulator_ports_to_random_side` to do the
toggle instead and add extra check `_check_mux_status_consistency` to
ensure the mux status from the DUTs and mux simulator is consistent
after the toggle.
2. For `test_hash`:
2.1 Use `toggle_all_simulator_ports_to_rand_selected_tor` to do the
toggle because it has check to verify the toggle.
Run it over dualtor, t0 and t1 testbed.
=> [test_fib] Improve test_fib

tests/platform_tests/daemon/test_syseepromd.py
Summary:
Adding syseepromd regression test
Added tests/platform_tests/daemon/test_syseepromd.py 
Run tests/platform_tests/daemon/test_syseepromd.py  test on DUT
=> [Platform_tests::daemon] Add syseepromd regression test

tests/common/dualtor/mux_simulator_control.py
- add a function level fixture to toggle all ports against the randomly selected tor
- fix a few comment errors
=> Add a fixture for port toggling

tests/test_pretest.py
Summary:
kvm test randomly failing due to fstrim service didn't do time wait after reboot and get stuck.
Reboot DUT if service state didn't become all valid in 3 minutes.
This PR test.
=> [pretest] reboot dut if features are not ready

ansible/library/feature_facts.py
Summary: Adjust feature_fact module to fit the new feature cli
Fixes # (issue) Adjust feature_fact module to fit the new feature cli
Adjust feature_fact module to fit the new feature cli
change the sonic-db-cli CONFIG_DB HGET "FEATURE|{}" status to sonic-db-cli CONFIG_DB HGET "FEATURE|{}" state
Do maunal check on the switch with sonic-db-cli CONFIG_DB HGET "FEATURE|database" state
sonic-db-cli CONFIG_DB HGET "FEATURE|database" state
always_enabled
sonic-db-cli CONFIG_DB HGET "FEATURE|swss" state
enabled
Run the regression
No, it effects all kinds of platform
=> Adjust feature_fact module to fit the new feature cli

tests/dualtor_io/test_tor_bgp_failure.py
Summary:
During nightly test runs, container autorestart is disabled. This prevents the BGP container from exiting when the bgpd process is killed during this set of test cases, which prevents a switchover from occurring.
Prior to the test, enable container autorestart for the BGP container. After the test is over, restore the previous autorestart state
Run the tests with container autorestart originally disabled. Verify that the tests are able to pass, and that autorestart for BGP is disabled after the test ends.
=> [dualtor_io]: Enable autorestart for BGP tests

tests/common/plugins/sanity_check/recover.py
Summary:
The sanity check uses reboot as a last resort method to recover the device
if some checks failed. The current reboot_dut function used by sanity check
has bug and cannot really work.
This change updated the recover_dut function in sanity check recover to call
the common reboot function which is much more robust.
1. Stop snmp docker on DUT.
2. Tweak the recover function a little bit to call the updated reboot_dut function when service check failed.
3. Run a test.
Of course code in this PR does not have the tweak for testing.
=> Use the common reboot function in sanity check recover

tests/kvmtest.sh
Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>
Summary:
On multi-asic VS testbed, sanity check runs for long time and times out without completing sanity check.
24/08/2021 01:01:08 parallel.parallel_run                    L0073 DEBUG  | Started process 14462 running target "_check_processes_on_dut--<MultiAsicSonicHost> vlab-08"
24/08/2021 01:01:08 parallel.parallel_run                    L0077 DEBUG  | Wait for process "_check_processes_on_dut--<MultiAsicSonicHost> vlab-08" with pid "14462" to complete, timeout=1000
…
24/08/2021 01:17:48 parallel.parallel_run                    L0079 DEBUG  | Process "_check_processes_on_dut--<MultiAsicSonicHost> vlab-08" with pid "14462" completed
24/08/2021 01:17:48 parallel.parallel_run                    L0098 ERROR  | …
=> [multi-asic]: Skip sanity check for multi-asic testing.

tests/dualtor/test_ipinip.py
Garp packets will flood to all interfaces in the same VLAN on the mocked single-tor system.
Even increase the interval to 10s, it still can't guarantee the ptf could catch up with verifying the expected packet. Add a filter to just compare the non-arp packets.
Use testutils.add_filter() to filter the non-arp packets.
Run the test_ipinip.py.
Summary:
=> [dualtor][ipinip] Add arp filter for ptf

tests/sai_qualify/conftest.py, tests/sai_qualify/sai_infra.py
Summary:
Add debug parameters to keep the debug environment
Add debug parameters to keep the debug environment. When set that parameters, DUT and PTF environment will not be cleared
local debug environment
brcm td2
=> Add a debug parameters to keep the debug environment

tests/common/platform/interface_utils.py, tests/common/plugins/sanity_check/checks.py, tests/platform_tests/mellanox/test_check_sfp_presence.py, tests/platform_tests/mellanox/test_check_sfp_using_ethtool.py, tests/platform_tests/sfp/test_sfputil.py, tests/platform_tests/sfp/util.py, tests/platform_tests/test_sequential_restart.py, tests/snmp/conftest.py, tests/snmp/test_snmp_default_route.py, tests/snmp/test_snmp_lldp.py, tests/snmp/test_snmp_loopback.py, tests/telemetry/test_telemetry.py
Reverts Azure/sonic-mgmt#3663
This change causes test failure in test_reboot.py and a few other tests.
=> Revert "Modify tests to run on zero ports systems "

ansible/roles/test/files/ptftests/arista.py
Summary:
Enhance arista command execution logic, avoid multi-thread dead lock caused by network stuck
Add timeout control to command execution
run platform_tests/test_advanced_reboot.py which is related to EOS VMs closely.
platform_tests/test_advanced_reboot.py::test_fast_reboot SKIPPED         [  9%]
platform_tests/test_advanced_reboot.py::test_warm_reboot PASSED          [ 18%]
platform_tests/test_advanced_reboot.py::test_cancelled_fast_reboot SKIPPED [ 27%]
platform_tests/test_advanced_reboot.py::test_cancelled_warm_reboot PASSED [ 36%]
platform_tests/test_advanced_reboot.py::test_warm_reboot_sad SKIPPED     [ 45%]
platform_tests/test_advanced_reboot.py::test_warm_reboot_multi_sad SKIPPED [ 54%]
platform_tests/test_advanced_reboot.py::test_warm_reboot_multi_sad_inboot …
=> arista paramiko ssh command timeout control

tests/platform_tests/api/test_psu.py
Summary:
Fixes # (https://github.com/Azure/sonic-buildimage/issues/8821)
Fix issue #(https://github.com/Azure/sonic-buildimage/issues/8821)
Add duthosts into test api input params
Run test_psu.py::TestPsuApi::test_power
=> [platform api tests] fix test_psu.py::TestPsuApi::test_power failure with dut_hosts not defined.

tests/ssh/test_ssh_stress.py
Summary:  
test_ssh_stress would be failed intermittent, which is caused by a known issue of the 3rd party lib and tracking by https://github.com/paramiko/paramiko/issues/1508, skip this test before it get fixed. 
=> Skip test_ssh_stress which failed intermittent

tests/dualtor/test_ipinip.py
Garp packets will flood to all interfaces in the same vlan,  even add a filter for ptf, it still can't gurantee the ptf could catch up with verifying the expected packet.
Stop garp service while ptf sending/verifying the pkts and start it again after the verification is done.
Run the test_ipinip.py.
Summary:
=> [dualtor][ipinip] Stop garp service while sending/verifying the pkts

tests/dualtor/test_tor_ecn.py
Garp packets will flood to all interfaces in the same vlan,  it can't gurantee the ptf could catch up with verifying the expected packet.
Stop garp service while ptf sending/verifying the pkts and start it again after the verification is done.
Run the test_tor_ecn.py.
Summary:
=> [dualtor][ecn] Stop garp service while sending/verifying the pkts

tests/syslog/test_syslog.py
=> Revert "Update test_syslog to test 2 syslog servers"

ansible/library/dut_basic_facts.py, tests/common/plugins/conditional_mark/README.md, tests/common/plugins/conditional_mark/__init__.py, tests/common/plugins/conditional_mark/credentials.yaml, tests/common/plugins/conditional_mark/issue.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml.example, tests/conftest.py
Summary:
Sometimes we need to add marks like `skip` or `xfail` to test cases for some known issues. For easier
management, it would be better to have a centralized place to specify the tests that need to be
conditionally marked.
This PR is inspired by https://github.com/Azure/sonic-mgmt/pull/3577. This plugin also supports all
the functionalities of the `custom skipif` plugin added in #3577.
If this PR is accepted by community, we can deprecate the `custom skipif` plugin.
Example variables can be used in conditions:
```
{ …
```
=> [infra] Plugin for conditionally adding any marks to specified tests

tests/common/plugins/conditional_mark/README.md, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/drop_packets/drop_packets.py, tests/platform_tests/fwutil/test_fwutil.py, tests/platform_tests/test_sequential_restart.py, tests/qos/test_pfc_pause.py, tests/route/test_static_route.py, tests/ssh/test_ssh_stress.py
Summary:
Some tests are unconditionally skipped. After the conditional mark plugin is introduced
in PR #4365, we can use this plugin to skip the tests.
Change:
1. Added file tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
2. Removed @pytest.mark.skip for some tests.
3. Defined skip mark for these tests in the tests_mark_conditions.yaml file.
4. Added content to the conditional mark README.md.
=> Use the conditional mark plugin to skip some tests

tests/common/dualtor/dual_tor_utils.py, tests/common/utilities.py, tests/route/test_static_route.py
Summary:
fix route/test_static_route.py failure in backend t0 topology
Fixes #4026
fix route/test_static_route.py failure in backend t0 topology
Fixes #4026
Modify assertion and ip address setting logic, suitable for backend topology scenario
Run on backend t0 topo:
route/test_static_route.py::test_static_route PASSED                     [ 25%]
route/test_static_route.py::test_static_route_ecmp PASSED                [ 50%]
route/test_static_route.py::test_static_route_ipv6 PASSED                [ 75%]
route/test_static_route.py::test_static_route_ecmp_ipv6 SKIPPED          [100%]
And a not backend topo:
route/test_static_route.py::test_static_route PASSED                     [ 25%]
route/test_static_route.py::test_static_route_ecmp PASSED                [ 50%] …
=> [storage backend] fix route/test_static_route.py failure in backend t0 topo

ansible/module_utils/port_utils.py
Adding support for Cisco 8000 platforms
Summary:
Adding support for Cisco 8000 platforms
=> Adding support for Cisco 8000 platforms

ansible/group_vars/sonic/sku-sensors-data.yml
Adding sensor support for Cisco 8102 platforms
Summary:
Adding sensor support for Cisco 8102 platforms
=> Adding sensor support for Cisco 8102 platforms

tests/show_techsupport/tech_support_cmds.py, tests/show_techsupport/test_techsupport.py
Summary:
show tech support command test case is failing.
The change was from: https://github.com/Azure/sonic-utilities/pull/1723
Update the command format
Run show_techsupport test.
=> [show techsupport] update the command list according to image changes

tests/platform_tests/test_reboot.py
Summary:
When power reboot fails, it could leave the DUT powering back up and taking a few minutes to become healthy again. Meanwhile subsequent test will fail because DUT is unreachable or not healthy.
e.g. when one of the 2 PDU outlet is no longer sending power, DUT is powered by only one outlet, then the sequence of power of all, then power on the no power outlet won't bring DUT back.
1. To avoid the confusion, explicitly turn on all powers in case of test failure and wait for DUT to become healthy again before failing. 
2. Fail power off reboot test directly if any outlet is not providing power.
Run power off reboot test on a DUT with one outlet cable becomes loose (no output power).
With change 1, the test will fail because DUT not coming back. The failure takes a few …
=> [power reboot] improve robustness of power reboot test

tests/common/dualtor/data_plane_utils.py
Summary:
Add extra logging to gather info during nightly tests
=> [dualtor_io]: Add extra logging

ansible/roles/test/files/ptftests/dhcpv6_relay_test.py
Summary: 
ISC-DHCP has been replaced with SONiC dhcp6relay. Test only DHCPv6 packets, that includes option 79 - client link layer address option, sent by dhcp6relay
=> Test only SONiC DHCPv6 Relay packets

tests/route/test_static_route.py
Summary:
This PR is to improve ```test_static_route``` because the test case is flaky on mlnx-4600. The reason for the failure is 350 seconds delay is not enough for establishing BGP sessions and announcing routes to neighbors.
The improvement includes:
1. Wait all BGP sessions up after config reload (timeout = 300s)
2. Add a retry in check advertised routes to neighbors
This PR is to improve ```test_static_route```.
1. Wait all BGP sessions up after config reload (timeout = 300s)
2. Add a retry in check advertised routes to neighbors
Verified on SN4600, T0 testbed for several times. All passed.
=> Improve test_static_route

ansible/roles/test/files/ptftests/fg_ecmp_test.py
Summary:
Fixes  ```test_fgnhg```.
```test_fgnhg``` was consistently failing with below error message
```
File "ptftests/fg_ecmp_test.py", line 496, in runTest
self.fg_ecmp()
File "ptftests/fg_ecmp_test.py", line 331, in fg_ecmp
self.test_balancing(hit_count_map)
File "ptftests/fg_ecmp_test.py", line 132, in test_balancing
assert deviation <= self.max_deviation
AssertionError
```
The reason for the failure is the default range of src_ip is not enough to ensure hash balance.
This PR addressed the issue by enlarging the range of src_ip.
This PR is to fix ```test_fgnhg```.
This PR addressed the issue by enlarging the range of src_ip.
Verified on SN4600 T0 testbed. Test can pass now.
No.
No.
=> Fix ```test_fgnhg```

tests/fdb/test_fdb.py
Signed-off-by: Gang Lv ganglv@microsoft.com
Summary:
https://github.com/Azure/sonic-mgmt/issues/4395
Need to update test_fdb to support t0-56-po2vlan.
Add support for portchannel and tagged VLAN port.
Run this test case with t0 topology and t0-56-po2vlan topology.
=> [fdb]: Update test_fdb to support t0-56-po2vlan.

docs/testbed/README.testbed.Setup.md
Update the download link of docker-sonic-mgmt from Jenkins to Azurewebsites.
Add the download link of docker-ptf
Update the download link of docker-sonic-mgmt from Jenkins to Azurewebsites.
Add the download link of docker-ptf
Summary:
The old Jenkins website is no longer for use. The original document is not friendly to beginners.
Download docker-ptf and docker-sonic-mgmt from the links.
NA
NA
=> Update the docker-ptf and the docker-sonic-mgmt docker's download link

ansible/roles/vm_set/library/vlan_port.py
Summary:
Fixes #4481
Fixes #4481
Vlan ports conflicted during restart-ptf.
Remove vlan port before adding to avoid potential conflict.
Manually add duplicated vlan port during restart-ptf, and now it can avoid the conflict by removing and adding again.
And then run the test case bgp/test_bgp_fact.py and it passed.
=> [restart_ptf] remove vlan port before adding to avoid potential conflict

tests/platform_tests/test_cpu_memory_usage.py
Summary: In current design, the interval of  cpu and memory utilization check is 5 seconds, and 12 iterations, over threshold for more than 4 iterations would be considered as an error, it is too strict, loose the check to 2 mins (24 iterations) with 8 iterations of over threshold. 
=> [platform_test] loose check for the CPU and memory utilization

tests/common/testbed.py
Generates SAI testbed info
- Support generating the sai testbed info from CSV and YAML
- unified the process for generating the testbed info
- parameterize the function for generating the testbed info
Summary:
Enhance the process for generating SAI testbed info
Support generating the sai testbed info from CSV and YAML
unified the process for generating the testbed info
parameterize the function for generating the testbed info
local testing
- test for sai test info with testbed vms3-4 from CSV file
- test for sai test info with testbed vms13-t0-a7170 from YAML file
- test for normal testbed info generation, from CSV file
- test read the YAML file
None
=> [SAITest]Generates SAI testbed info

ansible/library/sensors_facts.py, ansible/library/sonic_release.py
Fixes #4514
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>
Summary:
=> Add Python 3 support to sensors_facts.py and sonic_release.py

tests/common/dualtor/mux_simulator_control.py
Summary:
The mux toggle fixtures are not just used in the dualtor specific test scripts. Some test scripts
that are generic to both dualtor and non-dualtor topo also use the mux toggle fixtures. These
fixtures need to handle both dualtor and non-dualtor topo.
This change added code checking topo to the fixtures. When the current topology is
non-dualtor, simply return.
Created a temp script that uses all the touched fixtures.
Tested the temp script on both dualtor and non-dualtor testbeds.
=> Update the mux toggle fixtures to skip non-dualtor topo

tests/acl/test_acl.py
Summary:
There are some unnecessary imports in test_acl.py. 
This change is to remove them.
Test run test_acl.py
=> Remove unused imports in test_acl.py

ansible/roles/vm_set/library/vlan_port.py
Summary:
Fixes #4292
There is `restart-ptf` failure for t0-backend topology that `vlan_port` failed to create the vlan interface because the vlan interface exists already.
Add log to show the existing vlan interface in the server host before adding vlan interface
Run `restart-ptf`
=> [vlan_port] Add log to show vlan interface existence

tests/platform_tests/test_cpu_memory_usage.py
For some HW platforms, syncd which will consume CPU resources a lot for the flex counter threads. Increase the threshold of CPU utilization test for those platforms. 
Summary:
- [ x ] Test case(new/improvement)
=> [flex counter] Flex counter threads consume too much CPU resources. 

tests/platform_tests/link_flap/test_cont_link_flap.py
=> [link_flap] Log neighbor's bgpv6 info as well

tests/platform_tests/conftest.py
Summary:
advanced reboot test fails analyzing logs when booting into new images.
- Tolerate event timestamp with and without milliseconds value.
- Tolerate early new image boot event when host name was still 'sonic'.
run advanced reboot to upgrade to new image.
=> [warm reboot utilities] improve shared warm reboot helper functions

tests/common/dualtor/control_plane_utils.py
Summary:
When tests fail due to DB mismatches, the mismatched data is not printed.
Fix typo in variable name during assignment
=> [dualtor]: Fix typo in control plane utils

ansible/roles/test/files/ptftests/copp_tests.py, tests/copp/test_copp.py
Reverts Azure/sonic-mgmt#4456
This feature has not yet been reviewed https://github.com/Azure/SONiC/pull/858
Affecting nighty run results because of this new testcase without feature support
=> Revert "Add test case for trap flow counter feature"

tests/qos/files/qos.yml, tests/qos/test_qos_sai.py, tests/saitests/sai_qos_tests.py
Summary:
Fixes couple of QoS test cases for Z9332 on T0 and t1 topology
Updated QoS test parameters as well as test logic .
Fix QoS test cases for Z9332 platform.
Updated test params and test logic for Z9332.
Verified these test cases on HWSKU DellEMC-Z9332f-O32 and DellEMC-Z9332f-M-O16C64
=> Fixed couple of QoS test cases for Z9332 platform

tests/everflow/test_everflow_per_interface.py
Summary: skipped a test_everflow_per_interface test for Barefoot platform
- skipped a test_everflow_per_interface test for Barefoot platform
- moved test skipping code to a single function
=> skipped a test_everflow_per_interface test for Barefoot platform

setup-container.sh
**Summary:**
This is a refactoring/bugfixing/improvement of the  `setup-container.sh`
* Bugfixes & improvements for `setup-container.sh` script
* Reworked existing stuff & added new features
1. ./setup-container.sh -n sonic-mgmt-nazariig_master
* N/A
* N/A
```bash
nazariig@sonic: sonic-mgmt$ ./setup-container.sh -h
Usage ./setup-container.sh [OPTIONS]
Mandatory options:
-n <container_name>  set the name of the Docker container
Other options:
-i <image_id>        specify Docker image to use. This can be an image ID (hashed value) or an image name.
If no value is provided, defaults to the following images in the specified order:
1. The local image named "docker-sonic-mgmt"
2. The local image named "sonicdev-microsoft.azurecr.io:443/docker-sonic-mgmt"
3. The remote image at …
```
=> [container]: Refactor setup container script

tests/common/plugins/conditional_mark/issue.py
Summary:
There is an error log printed out during the process of test_pretest.py when running test_bgp_fact.py.
It's caused by empty credentials.yaml, now it's a default empty yaml file. The code didn't handle the exception for this scenario, fix it in this PR.
------------------------------------------------------------ live log collection -------------------------------------------------------------
08:20:55 issue.get_cred                           L0060 ERROR  | Load credentials from /data/sonic-mgmt/tests/common/plugins/conditional_mark/credentials.yaml failed
08:20:56 issue.get_cred                           L0060 ERROR  | Load credentials from /data/sonic-mgmt/tests/common/plugins/conditional_mark/credentials.yaml failed
```
with open(creds_file_path) as creds_file: …
```
=> fix the error log caused by empty credentials.yaml

docs/testbed/README.testbed.Overview.md
remove a 'of' in a sentence
Summary:
remove a 'of' in a sentence
remove a 'of' in a sentence
=> Fix a typo in the testbed overview document

tests/arp/test_arp_dualtor.py
Summary:
Fixes #4733
`test_proxy_arp` ipv6 failed on t0-backend nightlies.
The failure is because the interval between the neighbor solicitation and advertisement packet is larger than the verification timeout.
1. increase the verification timeout
2. for t0-backend, the ptf interface to do IO should be `eth%d.1000` other than `eth%d`, so let's retrieve the ptf port name from the `iface_map` initialized by `ptfadapter`
=> [storage_backend] Fix test_proxy_arp ipv6

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
PR #4575 introduced indention issue to file `tests_mark_conditions.yaml`.
This change is to fix those indention issues.
=> Fix indention issue in tests_mark_conditions.yaml

tests/vlan/test_vlan.py
Summary:
Fixes unicast packets being flooded due to destination mac not learned for tagged ports.
Recent changes in vlan/test_vlan.py [removed arp_responder](https://github.com/Azure/sonic-mgmt/pull/4388) and [creation of vlan interfaces on ptf](https://github.com/Azure/sonic-mgmt/pull/4591/). This resulted in testcases, which send unicast packets to tagged ports (tc4, tc6, tc7) to fail due to packets being flooded instead of forwarded:
`AssertionError: Received packet that we expected not to receive on device 0, port 1.` 
This occurs due to no entry being present in fdb for tagged ports.
Created function which would send tagged icmp packet from ptf to DUT for each tagged port in each vlan and added this function to setup_vlan fixture. 
Execute vlan/test_vlan.py:
``` …
```
=> [vlan] Populate fdb for tagged ports on DUT

tests/common/devices/sonic.py, tests/common/plugins/sanity_check/checks.py
Summary:
Sanity check is performed for each test script. Currently it takes more than 40 seconds to run a sanity check on
a regular DUT running T0 topology. If the DUT is multi-asic, sanity check may need even over 900 seconds. PR
#3826 was to workaround such issue on multi-asic DUT by simply increasing the timeout. If we can reduce the
time required by sanity check, the overall nightly test can benefit.
This PR aims to reduce the time required by sanity check. Changes:
1. Removed `check_service`. This is already covered in `check_process`. It's unnecessary to run it again.
2. Improved the methods used by `check_process`. The current methods run multiple command on DUT to
get critical process definition and process status for each critical services. The new way is to …
=> Reduce the time required by sanity check

tests/common/dualtor/dual_tor_utils.py, tests/common/dualtor/tunnel_traffic_utils.py, tests/dualtor/conftest.py, tests/dualtor/test_orchagent_active_tor_downstream.py
Summary:
Fixes #4687
Add ipv6 support for the dualtor downstream active traffic testcases.
```
dualtor/test_orchagent_active_tor_downstream.py::test_active_tor_remove_neighbor_downstream_active[ipv4] PASSED                                                                                                                                                        [ 25%]
dualtor/test_orchagent_active_tor_downstream.py::test_active_tor_remove_neighbor_downstream_active[ipv6] PASSED                                                                                                                                                        [ 50%]
dualtor/test_orchagent_active_tor_downstream.py::test_downstream_ecmp_nexthops[ipv4] PASSED …
```
=> [test_orchagent_active_tor_downstream] Support ipv6

ansible/group_vars/sonic/sku-sensors-data.yml, tests/common/mellanox_data.py
Summary:
Rename platform x86_64-mlnx_msn4800 to x86_64-nvidia_sn4800
Rename platform x86_64-mlnx_msn4800 to x86_64-nvidia_sn4800
Rename platform x86_64-mlnx_msn4800 to x86_64-nvidia_sn4800
Manual test
Mellanox
N/A
=> [Mellanox] Rename platform x86_64-mlnx_msn4800 to x86_64-nvidia_sn4800

tests/pc/test_po_cleanup.py
Summary:
Added fix of the test issue after updating the script. See the description in the fixed bug.
The fix for #4887 
Fix the test issue.
Added checker of services after restart of swss docker.
Executed all tests in the test_po_cleanup.py 
N/A
N/A
=> [test_po_cleanup] add checker of services after restart of swss docker

ansible/group_vars/sonic/sku-sensors-data.yml, tests/platform_tests/test_sensors.py
Signed-off-by: Kebo Liu <kebol@nvidia.com>
Summary:
To support the MSN4600C A1 platform sensor test.
Add sensor data for the MSN4600C A1 platform. 
Run sensor test on MSN4600C A1 platform. 
Mellanox platform only
N/A
=> [Mellanox] Add sensor data for MSN4600C A1 platform

ansible/cliconf_plugins/aos.py, ansible/library/aos/aos_command.py, ansible/library/aos/aos_config.py, ansible/module_utils/aos/aos.py, ansible/terminal_plugins/aos.py, tests/run_tests.sh
Summary: added support for AOS devices configuration
Project configures EOS fanouts using Ansible. For AOS devices there is no such option because Ansible does not support it out of the box. This PR brings AOS devices support making possible to configure AOS fanouts too
Examples of commands are:
```
- name: apply config file
aos_config:
src: "{{ lookup('file', 'config.cfg') }}"
```
```
- name: configure a single entity
aos_config:
lines:
- description IFACE11
- no mac-learning
parents: interface ethernet 1/1
```
```
- name: execute single command
aos_command:
commands: show interfaces brief
```
Add support for AOS fanouts configuration
Added AOS devices support for Ansible
Execute commands provided above. Note these hostvars must be set for AOS hosts:
``` …
```
=> added support for AOS devices configuration

ansible/group_vars/sonic/sku-sensors-data.yml
Updating sensor values for Cisco 8102 platform
Summary:
Updating sensor values for Cisco 8102 platforms
Verified that test_sensor.py passed for Cisco 8102 platform
=> [sku_sensors]: Updating sensor values for cisco-8102 platform

tests/cacl/test_cacl_application.py
Summary:
Fix #3596.
Add a test case to test Control Plane Access-control lists (ACL) scale rules
1. Generate a template json file with 50 rules for three control plane ACL tables: SNMP-ACL, ssh-only, ntp-acl.
2. Use acl-loader command to apply these rules on DUT.
3. Check if ACL rules matches the rules of iptables
4. Delete json file and clear ACL configuration
5. Rerun step 1-4 for ipv6.
Run test case test_cacl_scale_rules in tests/cacl/test_cacl_application.py.
=> Add a test case for testing control plane ACL scale rules

tests/platform_tests/conftest.py
Summary: Improve handling of reboot and post reboot timestamps in test_advance_reboot
Two improvements in this PR:
1. Apply changes for time formatting similar to https://github.com/Azure/sonic-mgmt/pull/4673
2. Gracefully handle the failure case when DUT fails to reboot for any reason. In the present code, if DUT fails to reboot, then the script fails at `post_reboot_analysis` with below error. If the reboot did not happen, then do not run `post_reboot_analysis`.
```
28/12/2021 13:43:40 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", …
```
=> [advanced-reboot] Reboot timestamp and formatting improvements

tests/qos/test_buffer.py
Summary:
Enhance exceeding headroom test
Enhance exceeding headroom test
Find out the exact point from which the accumulative headroom starts to exceed the limit via using binary search
Run regression test.
=> [Dynamic buffer] Enhance exceeding headroom test

tests/crm/test_crm.py
- The underlying resource for storing routes (LPM) in Cisco 8000 is algorithmic, meaning it won't be a 1:1 relationship between route and crm_routes consumed.
- This change is adding 10 IPV4 routes instead of 1, such that the crm_available_routes get decremented
With the existing testcase which adds only 1 IPv4 route, the counter crm_available_routes stays same and it fails.
Verified on cisco-8000 platform
cisco-8000
=> Modifications to test_crm.py::test_crm_route to accomodate Cisco-8000

tests/bgp/test_bgp_speaker.py
Summary:
Fixes #4968
Fix the test case failure on backend-t0 topology
Import necessary dependency.
=> [backend] import necessary constants dependency

tests/crm/test_crm.py
Enhancement on https://github.com/Azure/sonic-mgmt/pull/4737/files. Pytest assertion lines are missing in test_crm_route
Verified on cisco-8000 platform
=> Added pytest assertions in test_crm_route

tests/qos/test_buffer.py
Summary:
Fix the logic to fetch the effective speed when calculating headroom size in the test case.
Fix the logic to fetch the effective speed when calculating headroom size in the test case.
Originally, the effective speed is the configured speed.
However, with port auto-negotiation supported, we need to take more factors into account:
- If the port auto-negotiation is enabled,
the effective speed should be the maximum speed in the configured advertised speeds list or the supported speeds list
- Otherwise, the effective speed is the configured speed.
Run regression test.
=> [Dynamic buffer calculation] Fix the logic to fetch the effective speed in headroom size calculation

test_reporting/requirements.txt
Summary:
To avoid potential compatibility issue introduced by pip package version upgrade, this change
froze version of pip packages required for test report uploading.
Specify package version in the requirements.txt file for test report uploading.
=> Freeze version of pip packages required for test report uploading

tests/common/fixtures/duthost_utils.py
Proc is missing a check  to see if a system is a multi-asic system or not and hence hitting issue #4955. This fix introduces a check to see if the system is multi-asic system or not and modifies the commands accordingly. This issue causes the test crm/test_crm.py::test_crm_fdb_entry to error out.
@abdosi kindly review the fix.
Summary:
This fix introduces a check to see if the system is multi-asic system or not and modifies the commands accordingly. This issue causes the test crm/test_crm.py::test_crm_fdb_entry to error out.
Verified the fix on T2 profile.
=> Change to fix issue #4955 - fix for multi-asic chassis_packet

tests/platform_tests/link_flap/test_cont_link_flap.py
Skip if the neighbor type is 'SmartCable', 'Server', 'Asic' and the
peer-tor in dual-tor system. Just focus on the neighbor which will
announce the BGP routes.
This PR is to log the neigbor's bgp info while error happened for debug
purpose.
Run the cont link flap test case.
Summary:
=> [link_flap] Log neighbor's bgp info just for specified neighbor type

ansible/devutil/inv_helpers.py, ansible/devutils
Add limit argument check for pdu_reboot, pdu_on, pdu_off actions.
If no limit argument for these actions, will not execute the process for all devices.
Summary:
Currently, if no limit argument input for devutils, it will execute the action for all devices found in inventory file.
If action is pdu_reboot, pdu_on, pdu_off and user forget to add limit argument accidentally, devutils will do these pdu actions for all devices, it will shutdown the whole lab. This PR is for safe check.
Add limit argument check for pdu_reboot, pdu_on, pdu_off actions.
If no limit argument for these actions, will not execute the process for all devices.
If user is pretty sure to do pdu action to all devices, please specify -l/--limit all.
Prevent users from …
=> Add limit argument check for pdu_reboot, pdu_on, pdu_off actions

tests/conftest.py
Fix issue on test_sensor failures
Summary:
Fixes # ([5066](https://github.com/Azure/sonic-mgmt/issues/5066))
- [ x] Bug fix
Fix the sensor_data missing issue from creds
Add the sensor_data to dut creds for test_sensors tests
Run test_sensors
=> Add sensor data back to dut creds for test_sensor failures

tests/conftest.py
Summary:
Fixes #4585
Fix the KeyError issue in pretest.
Assert whether key "asic_services" exists, if not, skip composing logic.
Run pretest on a kvm testbed, and it works well.
=> [FIX] fix asic_services KeyError issue

tests/acl/test_acl.py
On T1, we don't know the specific port for downstream traffic as it doesn't populate the ARP entries for the target IP.
So still need to use verify_packet_any_port() to validate the expected pkt
If can find the specific port from DOWNSTREAM_IP_PORT_PORT, then we can use verify_packet(). Otherwise, we still need to use verify_packet_any_port()
Run the test_acl.py
Summary:
=> [acl] Fix get_dst_port() failure on T1

test_reporting/kusto/setup.kql
Summary:
The KQL statements for creating Kusto tables/functions have line wrapping issue.
Especially the statements for defining ingestion json mappings. They can't simply
be copied to the Kusto Explorer and run.
This change fixed the KQL syntax issue.
Another change is that the TestCases table has been extended with an extra "Summary"
column. We need to pickup this change in the statements for creating tables.
=> Improve the KQL for creating Kusto tables/functions

setup-container.sh
Summary:
The tool `setup-container.sh` simply copies all the python virtual environments
of use AzDevOps to home folder of current user. The copied python virtual env
files still have many pointers to path /var/AzDevOpts/env-*. After activating
the copied python environment using command like `source ~/env-python3/bin/activate`,
'pip install xx' will try to install packages to /var/AzDevOps/env-python3 and
fail with permission denied. This makes the copied virtual environment not
really useful.
The fix is to skip directly copy the python virtual environments. After home
folder is setup for the current user in sonic-mgmt docker, setup a new
python virtual environment in home folder of current user. Then install the
same set of packages to the new venv.
Only virtual …
=> Fix python3 virtual environment issue in tool setup-container.sh

tests/configlet/util/common.py
Summary:
Test occasionally fails
Fix a code bug which returns int instead of (int, str) tuple
Ran it
=> [configlet]: fix return value as tuple

tests/qos/test_buffer.py
Summary:
Fixes #4973
Updated testcase to check the correct buffer attributes for non Mellanox platforms
Ran the test on Mellanox, TD2 and Th platforms and it passed
=> [qos] Add support to run buffer deployment testcase on non Mellanox platforms

tests/common/plugins/conditional_mark/__init__.py
Summary:
While loading multiple conditions files, exact same log message is
logged after each conditions file is loaded. This is a little bit confusing.
This change improved the log messages of the conditional mark plugin.
=> Improve the log messages of conditional mark

tests/tacacs/test_ro_disk.py
Summary:
Do a reboot, if there is any transient state to restore to clean state, before starting the test.
Flaky test
Check if system is in clean state, by looking for dirs under /run/mount.
If there is any it implies a transient state left behind by earlier test.
Do a reboot to clean; Ensure tacacs config is in place upon reboot.
Create transient look alike (mkdir /run/mount/xx)
Run the test & watch it succeeds
=> tacacs: test RO disk: Reboot to clear any transient state

tests/platform_tests/mellanox/test_check_sfp_using_ethtool.py
Fixed test test_check_sfp_using_ethtool to do validation only for SFP ifaces
Previously test tried to check SFP info for all interfaces on DUT and it failed on SN2201 device due to RJ45 ifaces
Now test do check for SFP ifaces only if interface type not RJ45
Summary: Fixed test test_check_sfp_using_ethtool to do validation only for SFP ifaces
Fixed test test_check_sfp_using_ethtool to do validation only for SFP ifaces
See code
Executed test case tests/platform_tests/mellanox/test_check_sfp_using_ethtool.py
Mellanox/Nvidia
=> [Mellanox/Nvidia] Fixed test test_check_sfp_using_ethtool to do validation only for SFP ifaces

test_reporting/kusto/setup.kql, test_reporting/report_data_storage.py
Summary:
Currently the test report uploading script firstly ingest test case results
into the RawTestCases table. Then an update policy automatically expands the
results in RawTestCases table and ingests into the TestCases table.
The problem is that each time when the uploading script is executed, it firstly
ingests all test results of the current round into a single row of the
RawTestCases table. The RawTestCases table has single column. This means that
all the test results are ingested into a single cell.
When the test results exceed certain size, it will hit the Kusto limitation of
single cell size. Eventually, data ingestion will fail silently.
This PR introduced a new JSON mapping for the TestCases table. The uploading
script was also updated to directly ingest data …
=> Update test report uploading to directly ingest into TestCases table

tests/tacacs/test_ro_user.py
Added import logging to tacacs/test_ro_user
Summary:
To fix a missing "import logging" since it it is missing in the file.
Added import logging to tacacs/test_ro_user
Tested on linecard in a VoQ chassis
=> Added import logging to tacacs/test_ro_user.py

tests/sai_qualify/conftest.py, tests/sai_qualify/sai_infra.py
correct the private metod name in sai_quality
Signed-off-by: richardyu-ms <richard.yu@microsoft.com>
Summary:
=> Correct the private method name in sai_qualify

.github/PULL_REQUEST_TEMPLATE.md
Summary:
After the 202012 branch was created, some critical changes may
need to backport to 202012 branch.
This change updated the Github Pull Request template to support
marking 202012 branch backport.
=> Update PR template to support marking 202012 branch backport

ansible/library/extract_log.py, ansible/roles/test/files/ptftests/remote.py, spytest/apis/qos/acl_dscp.py, spytest/apis/routing/ip.py, spytest/tests/routing/test_l3_scale_ecmp_paths.py, tests/common/helpers/enable-dynamic-buffer.py, tests/common/helpers/pfc_gen.py, tests/platform_tests/test_xcvr_info_in_db.py, tests/saitests/sai_base_test.py, tests/saitests/switch.py, tests/telemetry/test_telemetry.py
Summary:
Semicolon is not required in end of line of python code.
This change removed all the unnecessary semicolons.
=> Remove semicolons in end of line of python code

ansible/roles/test/files/ptftests/copp_tests.py, tests/copp/test_copp.py
Summary:
Add DHCPv6 CoPP test
Send multicast DHCPv6 packet
Ran test on T0/M0
=> Add DHCPv6 Copp Test

tests/platform_tests/api/test_chassis.py
Fix the description error in revision check test.
Summary:
Fix the description error
Change the serial number into revision
Run test
=> Fix the description error

tests/vlan/test_vlan.py
Improve test_vlan test case.
Flush the queue before sending pkt, and increase the timeout value of pkt polling.
Run the test_vlan.py.
Summary:
=> [vlan] Increase the timeout value of pkt polling

docs/testbed/sai_quality/PTF-SAIv2TestingGuide.md, docs/testbed/sai_quality/README.md
Summary:
This article will introduce the detailed processing of entire PTF-SAIv2 testing, including:
* Build PTF-SAIv2 infras leveraged by [sonic-buildimage](https://github.com/Azure/sonic-buildimage)
* Setup the testbed by sonic-mgmt
* Setup saiserverv2 docker on DUT (Device under testing)
* Prepare the testing env and start PTF-SAIv2 testing within ptf-sai docker
Add document for PTF-SAIv2 testing demo
Add document for PTF-SAIv2 testing demo
Start PTF-SAIv2 testing according to guideline
=> [PTF-SAIv2] Add PTF-SAIv2 testing demo doc

tests/tacacs/test_ro_disk.py
Summary:
1) Don't add any commands to "finally" clause in main test as any failure could prevent reboot. Leave reboot as the only command in finally.
2) Don't use duthost to fetch as that could fail, when test takes longer.
Ran the test in two testbeds. Both success & failed scenarios. Simulated failed scenario, by removing disk_check call from monit's conf.
=> tacacs: test_ro_disk: Fix possible failure which could prevent reboot

tests/dualtor/test_tunnel_memory_leak.py
Summary:
Fixes #5018
The tunnel packet handler service running in the SWSS container was found to have a memory leak associated with receiving IPinIP packets from the standby ToR.
Add a new test script to check if there is memory leak for service tunnel_packet_handler.
Test steps:
1. Send ip packets from standby TOR T1 to Server, standby TOR will forward the packets to active TOR with tunnel, active TOR will decapsulate the IPinIP packets, but there is no neighbor for destination as we remove neighbor before test, tunnel_packet_handler will be triggered and neighbor will be added. Then server will receive the packets. 
2. Check if memory usage percent is increased after tunnel_packet_handler's operation. Since tunnel_packet_handler is only triggered by the first packet, loop the process …
=> [test_gap][dualtor]: Test tunnel packet handler memory leak

tests/sai_qualify/community_cases.py, tests/sai_qualify/conftest.py, tests/sai_qualify/sai_infra.py
Summary:
Enable PTF-SAI testing on pipeline framework
Leverage the PTF-SAI test cases on SAI v1.9 branch
Test done:
Tested on sonic mgmt internal pipeline
=> [Pipeline] Enable PTF-SAI testing on pipeline framework

tests/qos/files/qos.yml, tests/saitests/sai_qos_tests.py
Summary:
QoS PGSharedWatermark test case for lossy queue for TD3 platform
- [x ] Testbed and Framework(new/improvement)
To fix PGSharedWatermark QoS test  for lossy queue 
Updated test function to improve tolerance for leaky packets for TD3 platform
On TD3 platform
=> QoS test fixes for TD3 and TH3-T0 platforms

ansible/roles/vm_set/library/vm_topology.py
Currently, the ovs bridge for the first data interface of each VM has 3 ports attached:
VM dataplane interface
PTF injected interface
DUT VLAN interface
For the 3 parties to properly communicate with each other, the OVS bridge also has open flow rules configured to control the traffic flow:
All packets sent out from VM are only forwarded to DUT.
All packets sent out from DUT are forwarded to both VM and PTF.
All packets sent out from PTF are only forwarded to DUT.
EOS will receive all traffic from DUT even it's PTF test traffic, this will make CPU usage too high on EOS when traffic is very heavy, then BGP session may flap between EOS and DUT.
The changes in this PR is tp filter unnecessary PTF test traffic and not send them to EOS to improve the stability of EOS.
Signed-off-by: Zhaohui …
=> Update ovs-bridge rules to improve the stability of EOS

tests/bgp/test_traffic_shift.py
Summary:
Improve pr test stability.
Fix: https://dev.azure.com/mssonic/build/_build/results?buildId=81632&view=logs&j=551384a3-3c3d-5d98-9a93-ab579ce10658&t=bbd192f0-b3ea-5cf8-016f-b12e888237fc&l=1219
Improve pr test stability.
Fix: https://dev.azure.com/mssonic/build/_build/results?buildId=81632&view=logs&j=551384a3-3c3d-5d98-9a93-ab579ce10658&t=bbd192f0-b3ea-5cf8-016f-b12e888237fc&l=1219
Wait for all critical processes to become healthy after TSA and TSB to avoid affecting other test cases.
Run it locally.
=> Wait critical processes after TSA/TSB

tests/conftest.py
Summary:
DB dump variable name error in a for loop.
Fix variable name error.
Run a testcase.
=> Fix variable name error in the collect DB dump fixture

ansible/lab, ansible/veos_vtb, ansible/vtestbed.csv, ansible/vtestbed.yaml
Summary:
Add another 2 t0 KVM testbeds.
Add another 2 t0 KVM testbeds.
Add vms-kvm-t0-3 and vms-kvm-t0-4
Make sure their ips have not been taken.
Run bgp/test_bgp_fact and it passed after deploy.
=> add kvm-t0-3 and kvm-t0-4

ansible/library/announce_routes.py, ansible/library/topo_facts.py, ansible/roles/eos/templates/t0-mclag-leaf.j2, ansible/roles/vm_set/library/vm_topology.py, ansible/vars/topo_t0-mclag.yml
Summary: Added new topology **t0-mclag** which might be used to test mclag feature. In order to use such topology, a root fanout should be used to connect one test server and two leaf fanout which lead to two DUTs. 
t0-mclag: 
**Example of topology in testbed.csv:** 
`vms1-t0-mclag,vms1,t0-mclag,docker-ptf,ptf_vms1,10.1.1.1/24,,server_1,VM0128,[dut-1;dut-2],Comment`
**Steps to deploy t0-mclag topo:**
```
./testbed-cli.sh add-topo vms1-t0-mclag 
./testbed-cli.sh deploy-mg vms1-t0-mclag 
```
Add new topology t0-mclag.
By deploying topology, minigraph and removing topology:
```
./testbed-cli.sh remove-topo
./testbed-cli.sh add-topo
./testbed-cli.sh deploy-mg
```
=> [topology] Add new topology t0-mclag

tests/configlet/test_add_rack.py, tests/configlet/util/common.py, tests/configlet/util/generic_patch.py, tests/configlet/util/helpers.py, tests/configlet/util/mock_for_switch.py
Summary:
Fixes pr test errors
Fix pr test errors:
/usr/local/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/local/lib/python2.7/dist-packages/py/_path/local.py:704: in pyimport
__import__(modname)
E     File "/var/src/s/tests/configlet/test_add_rack.py", line 35
E       pytest.skip('Generic patch updater does not support multiasic")
E                                                                     ^
E   SyntaxError: EOL while scanning string literal
Fix the importation
Trigger kvmtest
=> fix the pr test error(import error in test_add_rack.py)

tests/qos/test_pfc_pause.py
This PR contains the following changes
* Reduce the run time of the script by reducing the number of intfs to iterate over and reducing the number of packets sent in each iteration
* For dual TOR setups, get the server ips from the dut and use them for sending traffic
* Always enable pfcwd at the end of the test
Ran the test with these changes on a dualToR setup and it passed
=> [pfc] Get server ips from config for dualTor

.azure-pipelines/run-test-template.yml
Summary:
add detailed log during refresh-dut, and archive to AZP artifact
pr test sometimes stucks on some steps, add more log for investigation
Add more log
Run it on github pipeline
=> add detailed log during refresh-dut, and archive to AZP artifact

ansible/roles/test/files/ptftests/inner_hash_test.py, tests/ecmp/inner_hashing/conftest.py, tests/ecmp/inner_hashing/test_inner_hashing_lag.py, tests/ecmp/inner_hashing/test_wr_inner_hashing.py, tests/ecmp/inner_hashing/test_wr_inner_hashing_lag.py
This reverts commit 3244df1482e009d855fe528beae460bbb266e72d.
Summary: The fix for issue #5280 was provided in https://github.com/Azure/sonic-buildimage/pull/10184.
Revert back the changes, which reverted in https://github.com/Azure/sonic-mgmt/pull/5282
Add back the changes
=> Revert "Revert "[inner hahsing] extension of PBH tests (#4848)" (#5282)"

tests/kvmtest.sh
[Done]Wait for issue https://github.com/Azure/sonic-utilities/issues/2041 to be resolved to pass the bgpl test.
[Done]Wait for updated sonic-utilities including https://github.com/Azure/sonic-utilities/pull/2044 advanced in sonic-buildimage.
[Done]Remove cacl_test.
[Done]wait for 2092 sonic-util submodule update
Summary:
Add previous Generic Configer Updater tests into kvm test suite
Move GCU test into kvm daily test
Add GCU test case into kvmtest.sh
Run test of sonic-mgmt/tests/generic_config_updater/*.py on KVM
=> GCU tests add to kvm test

tests/common/system_utils/docker.py
Summary: added an option to setup a local syncd-rpc for QoS SAI tests
QoS SAI tests require syncd-rpc to be installed. The syncd-rpc image is expected to be located at Docker registry where it is pulled from. 
This PR brings an alternative for syncd-rpc setup for the case when its image is present locally in SONiC. If the local image is present it's favored and will be installed instead of looking on registry.
Add an option to install a local syncd-rpc
=> added an option to setup a local syncd-rpc for QoS SAI tests

tests/ssh/test_ssh_ciphers.py
Fix the test case issue, we need support either password or alt_password to do this verification.
Run this test case.
Summary:
Fix the test case issue, we need support either password or alt_password to do this verification.
Run this test case.
=> Support alt_password as well

tests/fdb/test_fdb.py
test_fdb is failed at multiple devices. It takes a long duration as it required sending lots of pkts between paired ports.
It is difficult to guarantee there is no congestion end-to-end between this period, especially at the server side as there are many workloads running on the server.
To enhance the stability, if one pkt is not received at PTF, we can re-sent/verify this pkt for 3 times.
Run test_fdb.py
Summary:
=> [fdb] Enhance the stability of test_fdb

tests/nat/nat_helpers.py, tests/nat/test_dynamic_nat.py
Summary:
Fix for new iptables output
Fix incorrect test behavior.
PREROUTING entry in iptables now displayed:
Now
`DNAT all -- 0.0.0.0/0 0.0.0.0/0 to:1.1.1.1  `
Before (what expected in TC)
`DNAT all -- 0.0.0.0/0 0.0.0.0/0 to:1.1.1.1 fullcone`
Format of iptables has changed to: 
Now:
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
Chain POSTROUTING (policy ACCEPT)                        <--
target     prot opt source               destination
```
Before (what expected in code)
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
Chain INPUT (policy …
```
=> [NAT] Fix for new iptables output

ansible/group_vars/sonic/variables, tests/qos/qos_sai_base.py
Adding support for Cisco-8000 platform in qos_sai_base script.
Summary:
- [x ] 202012
To add support for Cisco-8000 platform in qos_sai_base script.
Against Cisco-8000 platform
=> [qos_sai]Adding support for Cisco 8000 platform

tests/saitests/sai_qos_tests.py
Added pg_dropped_cntr check for cisco platforms.
This changes will verify that pg_dropped_cntr are correctly incrementing for relevant dscp by comparing old and new values . Also added a condition to verify that only PG drop counters for relevant dscp increases and for no others PG's .
Added pg_dropped_cntr verification for cisco-8000 platforms
Verified the change in local setup and it works
=> Add pg_dropped_cntr verification for cisco-8000 platforms

ansible/roles/test/files/ptftests/copp_tests.py, tests/copp/test_copp.py
=> Revert "Add DHCP IP2ME copp test"

tests/sai_qualify/conftest.py, tests/sai_qualify/sai_infra.py
Summary:
Fixed Export PLATFORM issue via ~/.bashrc for PTF-SAI Testing
Tested on DUT
=> Fixed Export PLATFORM issue via ~/.bashrc for PTF-SAI Testing

tests/copp/test_copp.py
Summary:
Enable test_copp on t0
Enable test_copp on t0
Enable test_copp on t0
Run it locally
=> enable test_copp on t0

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
auto negotiation test doesn't work for broadcom platform, skip.
and it only work with mellanox platform, fanout and dut both have to be mellanox platforms, and doesn't work for sonic OS, skip also. 
Filed below issue to track
https://github.com/Azure/sonic-mgmt/issues/5447
Summary:
skip an test
add skip in the condition mark file
No
=> [test_auto_negotiation] skip an test

tests/macsec/__init__.py, tests/macsec/macsec_config_helper.py, tests/macsec/macsec_helper.py, tests/macsec/macsec_platform_helper.py, tests/macsec/test_macsec.py
Summary:
Fixes LGTM analysis alerts in https://github.com/Azure/sonic-mgmt/pull/5362
To fix the below alerts:
> This pull request introduces 7 alerts when merging https://github.com/Azure/sonic-mgmt/commit/0f728b6844a617e43bcca2cc3aed84362d8373b9 into https://github.com/Azure/sonic-mgmt/commit/c1c503c6629f738798050b4c3a9485956192d1c1 - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-mgmt/rev/pr-6ea8920079e4f8a129295aa523fa087f330ca4ad)
> 
> new alerts:
> 
> 6 for 'import *' may pollute namespace
> 1 for Loop variable capture
=> [macsec] Fix lgtm alerts in #5362

tests/bgp/test_traffic_shift.py
Summary:
This change is to fix the test issue Fixes https://github.com/Azure/sonic-mgmt/issues/4337 [bgp_traffic_shift] no neighbors check after restart bgp service | dependency of execution tests order.
This change is to fix the test issue Fixes https://github.com/Azure/sonic-mgmt/issues/4337 [bgp_traffic_shift] no neighbors check after restart bgp service | dependency of execution tests order.
When another bgp test run after test_traffic_shfit.py::test_TSA_B_C_with_no_neighbors, there is a chance that the routes used in the test have not yet been learnt by the VMs.
To resolve the issue, all routes on the VMs need to be checked at the end of test_TSA_B_C_with_no_neighbors.
It costs a lot of time if we verify routes on VMs one by one. So I changed parse_routes_on_eos() to run in parallel …
=> [BGP] Adding checks for bgp sessions and routes on VMs

tests/fdb/test_fdb.py
Enhance the test case
Send some more pkts in the retry to make the case to be more tolerant of congestion on server/ptf
Run test_fdb.py
Summary:
=> [fdb] Send some more pkts in retry

tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Summary:
* Support *Vertiv Geist Upgradeable PDU* in `snmpPduController`.
* Fix some typo and flake8 warning.
Support *Vertiv Geist Upgradeable PDU* in `snmpPduController`.
Add some MiB OID of *Vertiv Geist Upgradeable PDU* in class `snmpPduController`.
Verified on *Vertiv Geist Upgradeable PDU*
=> Support Vertiv PDU in snmpPduController

docs/testplan/DHCP-Server-test-plan.md
Summary:
Add test plan for DHCP Server feature
=> Add DHCP Server Testplan

azure-pipelines.yml
Summary:
Remove pool for job kvmtest-t0 in azure-pipelines.yml
Current job `kvmtest-t0` doesn't run any test cases, just wait the results of `t0_part1` and `t0_part2`.
It wastes resource of VM if using agent pool for `kvmtest-t0`.
Remove pool for job `kvmtest-t0` also remove timeoutInMinutes.
Because there is a scenario that there is no VM resource for job `t0_part1` and `t0_part2`, or there is some issue to allocate VM from agent pool,  `t0_part1` and `t0_part2` are in queue and waiting for VM to run test cases, if there is timeoutInMinutes for `kvmtest-t0`, it will fail when timeout value arrives no matter the status of `t0_part1` and `t0_part2`. 
Remove timeoutInMinutes to make sure it will get the final results of …
=> Remove pool for job kvmtest-t0 in azure-pipelines.yml

tests/console/test_console_loopback.py, tests/console/test_console_reversessh.py
Signed-off-by: Xichen Lin <xichenlin@microsoft.com>
Summary:
Error message from some console tests does not contain caught exception, which makes debugging difficult.
Added printing exception.
Run manually on testbed.
=> [console] add printing err

tests/common/ptf_agent_updater.py, tests/mclag/MCLAG_Test_Plan.md, tests/mclag/conftest.py, tests/mclag/mclag_helpers.py, tests/mclag/templates/ptf_nn_agent.conf.ptf.j2, tests/mclag/templates/ptf_portchannel.j2, tests/mclag/test_mclag_l3.py, tests/sub_port_interfaces/conftest.py, tests/sub_port_interfaces/sub_ports_helpers.py
Summary: Added basic test cases to verify MCLAG feature in L3 scenario. 
In order to run test cases, **t0-mclag** topology should be deployed - [t0-mclag](https://github.com/Azure/sonic-mgmt/pull/5171)
Added test cases: 
- test_check_keepalive_link
- test_check_teamd_system_id
- test_mclag_intf_status_down
- test_mclag_intf_status_up
To avoid code duplicating, functions that update **ptf_nn_agent** were moved from **sub_ports_helpers** to a common space, sub-ports test was updated accordingly. 
Add test cases to verify MCLAG feature in SONiC
`py.test --testbed=testbed-t0-mclag --inventory=../ansible/lab --testbed_file=../ansible/testbed.csv --host-pattern=all -- module-path=../ansible/library mclag` …
=> [MCLAG] Added basic MCLAG L3 tests

ansible/dualtor/nic_simulator/nic_simulator.py, ansible/dualtor/nic_simulator/nic_simulator_client.py, ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service.proto, ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service_pb2.py, ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service_pb2_grpc.py, ansible/dualtor/nic_simulator/nic_simulator_grpc_service.proto, ansible/dualtor/nic_simulator/nic_simulator_grpc_service_pb2.py, ansible/dualtor/nic_simulator/nic_simulator_grpc_service_pb2_grpc.py
Summary:
Correct protocol buffer service definitions.
1. modify `nic_simulator_grpc_service.proto` to have versions APIs.
2. modify `nic_simulator.py` accordingly to reflect protocol buffer changes.
Ensure `nic_simulator_client.py` could interacts with server.
=> [nic_simulator] Correct proto service definitions

tests/drop_packets/drop_packets.py
Summary:
This PR is to add a check for the type of DUT and fanout switch and skip `test_equal_smac_dmac_drop`, `test_multicast_smac_drop` and `test_non_routable_igmp_pkts` if DUT is not mellanox or the fanout switch is not mellanox, since these 3 test cases require mellanox fanout switch or non-onyx os fanout switch.
The PR #5291 removed the functionality of #3544.
As the description in #5291: "This fixture is used in test_equal_smac_dmac_drop, test_multicast_smac_drop
These tests are skipped on Mellanox hwsku with SONIC OS because drop counters
are not shown in SONIC for this reason", it should skip these 3 test cases on other platform DUT and when fanout is SONiC OS mellanox.
But from test result, it doesn't. Other platforms run these cases because of fanout is not None. …
=> Fix fanouthost fixture in drop_packets

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
To ignore 2 error logs.
Below one is false alarm, ignore it.
ERR swss#buffermgrd: :- doTask: Failed to process invalid entry, drop it
Below one is under investigate, and track by https://msazure.visualstudio.com/One/_workitems/edit/14233938, move it to ignore list for now.
ERR swss#fdbsyncd: :- readData: netlink reports an error=-25 on reading a netlink socket
=> [loganalyzer] move some log errors to ignore list

tests/everflow/everflow_test_utilities.py
=> Revert "Everflow packets TTL check for cisco platform"

tests/kvmtest.sh
Summary: Add test_add_rack to KVM daily test
Add test_add_rack to KVM daily test
Add test_add_rack to KVM daily test
Run E2E test.
=> [configlet] Add test_add_rack to KVM daily test

tests/conftest.py
Summary:
Need to fail test case if there is any core dump generated post a test
Compare the number of files under /var/core before test and after tear down
If there are new files, fail this test case.
Run a test
=> Check if there is new core dump under /var/core post test

docs/testplan/Chassis-fabric-test-plan.md
=> Add fabric test plan

tests/kvmtest.sh
This reverts commit d807c2bcf7849250fa769086fe0efb6e2a74dcf0.
Summary: Revert to unblock PR checker failure
=> Revert "[configlet] Add test_add_rack to KVM daily test (#5630)"

tests/qos/test_qos_sai.py, tests/saitests/sai_qos_tests.py
Changes for testQosSaiPfcXonLimit on Cisco-8000.
Test case modifications for Cisco-8000:
-Account for leakout using utility.
The above changes are backwards compatible with other vendors.
Provide Cisco-8000 support for testQosSaiPfcXonLimit.
Verified the Changes on Cisco platform and Testcase Passes
=> Changes to testQosSaiPfcXonLimit for cisco-8000

ansible/group_vars/all/nic_simulator_grpc_port_map.yml, ansible/plugins/filter/filters.py, ansible/roles/vm_set/tasks/add_topo.yml, ansible/roles/vm_set/tasks/control_nic_simulator.yml, ansible/roles/vm_set/tasks/remove_topo.yml, ansible/roles/vm_set/tasks/renumber_topo.yml, ansible/roles/vm_set/templates/nic-simulator.service.j2
Summary:
Add deployment support for `nic_simulator`
For `add-topo`, start `nic_simulator` service.
For `remove-topo`, stop `nic_simulator` service.
For `restart-ptf`, restart `nic_simulator` service.
Run `add-topo`, `remove-topo`, and `restart-ptf` on a dualtor-mixed testbed.
=> [dualtor][ansible] Add nic simulator deployment support

tests/saitests/sai_qos_tests.py
Changes for testQosSaiLossyQueue on Cisco-8000. 
Test case modifications for Cisco-8000:
- Account for leakout using utility.
Changes for testQosSaiLossyQueue on Cisco-8000. 
Verified the Changes on cisco-8000 local setup and testcase passes .
=> changes for testQosSaiLossyQueue on cisco-8000

tests/qos/test_qos_sai.py, tests/saitests/sai_qos_tests.py
Creates new test case testQosSaiPgDrop specific to cisco-8000. 
Verify PG drops occur at expected threshold within a given margin and are accounted for by the drop counter. 
Verify cisco-8000 specific PG drops.
Verified the testcase on local cisco-8000 setup and it passes .
=> New Testcase testQosSaiPgDrop specific for cisco-8000 platform

tests/common/plugins/sanity_check/__init__.py, tests/common/plugins/sanity_check/checks.py
A typeError sometimes occurs in common/plugins/sanity_check/__init__.py:206, but existing log can not help us find out the reason of this failure. So add some logs for debug. 
Summary:
A typeError sometimes occurs in common/plugins/sanity_check/__init__.py:206, but existing log can not help us find out the reason of this failure. So add some logs for debug. 
Add some dubug logs.
=> Add log for debug in sanity check. 

tests/show_techsupport/test_auto_techsupport.py
Implemented auto-techsupport test cases which will validate auto-techsupport feature
Summary: Implemented auto-techsupport test cases
New tests added for new SONiC feature
Implemented new tests(see code)
Executed new tests on latest master image
any
=> [test_auto_techsupport] Implemented auto-techsupport test cases

ansible/dualtor/nic_simulator/nic_simulator.py
Summary:
Modify `nic_simulator` rpc calls `QueryAdminForwardingPortState` and `SetAdminForwardingPortState` to respond based on request port.
For `portid == 0`, get/set upper ToR admin forwarding state.
for `portid == 1`, get/set lower ToR admin forwarding state.
Test with gRPC calls to specified `portid`.
=> [dualtor][nic_simulator] Correct to respond based on portid

tests/sai_qualify/sai_infra.py
Summary:
Fixed an 'out of range' error introduced from PR #5363,  which caused a failure during the pipeline run test.
Fixed an 'out of range' error introduced from PR #5363,  which caused a failure during the pipeline run test.
Checked in internal pipeline
=> Fixed pipeline 'list index out of range' error

tests/common/plugins/loganalyzer/loganalyzer.py
The current UI of Log Analyzer reports in allure is messy, isn’t organized and has bad readability. 
The current format consists of 2 inner dictionaries inside the main dictionary, which prints the error messages “as is” without newlines.
The improvement includes a new method for LogAnalyzer class, which represents the dictionary as a readable string, and prints only the relevant data to the user.
Creating a readable format and removing unnecessary information, while keeping the essential details needed to analyze the errors.
I created a new method, which prints the total amount of matches, checks the lists of match messages, and prints them as a string if they aren't empty.
I ran full regression on community tests.
Relevant for all platforms.
=> Log Analyzer improvements

ansible/files/check_testbed_and_inventory_file.py, ansible/vtestbed.yaml
Summary:
When we may make some mistakes while adding or updating testbed
configurations in testbed file and inventory files. These mistakes
are hard to find and can cause many troubles. 
This PR added a tool to do some basic checks of testbed file and the 
related inventory files. This tool only supports the yaml format testbed file.
Checked items:
* Check if the topologies defined in vm inventory file are valid.
* Check if there is duplicated testbed name in testbed file.
* For each test server, check if there is duplicated group name.
* Check if the topo name of each testbed is valid.
* Check if the PTF host of each testbed is defined in inventory
file. Also check if the PTF IP in testbed file matches the IP
address defined in inventory file.
* Check if there is …
=> Add a tool to check testbed and inventory file

tests/pc/test_po_update.py
Previously, a config_reload will always be executed to recover the testbed after test case test_po_update_io_no_loss is executed, no matter whether it passed or not. 
But there're lots of syslog brought up during config_reload, which causes a passed test case to be assumed as failed. 
So now, if the test case passed, the recovery will be finished by commands, a config_reload will only be executed if the test case failed, or recovery failed, to avoid affecting the following test cases.
I also reduced the test time, to avoid the affection of Scapy performance on the test result.
Summary:
test_po_update always failed on two points:
1. config_reload causes loganalyzer raise exception
2. Scapy performance causes packet loss(suspection)
1. Recover testbed with several port …
=> [test_po_update] Recover portchannel by commands if test cases passed rather than reload; Reduce test time to avoid scapy performance influence

ansible/roles/test/files/ptftests/py3/README.md
Summary:
Add the introduction of docker-ptf python3 migration.
=> Add the introduction doc for docker-ptf migration

ansible/dualtor/nic_simulator/nic_simulator.py
Summary:
The flows defined in the OVS bridge  previously has no priority:
```
[1]: cookie=0x0, duration=4.564s, table=0, n_packets=41, n_bytes=2829, in_port="vlab-11-2" actions=output:"iaa-vms6-8-1",output:"nic-vms6-8-1"
[2]: cookie=0x0, duration=4.552s, table=0, n_packets=43, n_bytes=2967, in_port="vlab-12-2" actions=output:"iaa-vms6-8-1",output:"nic-vms6-8-1"
[3]: cookie=0x0, duration=4.533s, table=0, n_packets=0, n_bytes=0, in_port="nic-vms6-8-1" actions=output:"vlab-12-2",output:"vlab-11-2"
[4]: cookie=0x0, duration=4.497s, table=0, n_packets=0, n_bytes=0, in_port="iaa-vms6-8-1" actions=group:1
[5]: cookie=0x0, duration=4.522s, table=0, n_packets=84, n_bytes=5796, icmp,in_port="iaa-vms6-8-1" actions=output:"vlab-12-2",output:"vlab-11-2"
```
But the flow to replicate …
=> [nic_simulator] Fix nic simulator flows

tests/conftest.py
Summary:
Provide a more convenient view to see new core dumps.
Print new core dump filename.
Run a test
=> Print new core dump filename under /var/core post test

test_reporting/report_data_storage.py
Summary:
To support kusto cluster HA for sonic test data
To support kusto cluster HA for sonic test data
To add a backup Kusto cluster for test data upload.
Verified by manually run the pipeline and check the results in Kusto.
=> [Test Data Upload] add backup Kusto cluster for test result data

tests/platform_tests/templates/expect_boot_messages
Summary: Update regex for FDB learning-enable for 201911
=> Update FDB learning enable regex in template file

tests/crm/test_crm.py
Sometimes CRM tests may fail, because we did get for available/used CRM resources one time and few steps before setting thresholds and after we get available/used CRM stats - resources usage may change and as result when we set specific threshold - test may fail(because threshold is incorrect).
Now after fix we do get for available/used CRM resources right before doing set for threshold.
Summary: Improved stability of CRM tests - by doing get CRM resources right before setting thresholds
Stabilize CRM tests
See code
Executed all tests from CRM folder
=> [CRM] Improved stability of CRM tests - by doing get CRM resources right before setting thresholds

tests/macsec/test_macsec.py
Signed-off-by: Ze Gan <ganze718@gmail.com>
Summary:
Add config_reload with MACsec configuration
Running config_reload and check MACsec entries again
Check Azp status
=> [test_macsec]: Add config reload testcase

tests/pc/test_po_update.py
Summary:
Allow slightly packet loss during portchannel members add/removal
Allow slightly packet loss during portchannel members add/removal.
If match_count is larger than 99% of the send_count, consider the test case as passed.
Run it on physical testbeds.
=> [test_po_update] Allow slightly packet loss during portchannel members add/removal

docs/testplan/MACsec-test-plan.md
Summary:
Add the test details of Macsec counters
=> [doc] Add Macsec counters on Macsec test plan

tests/qos/files/qos.yml
Adding qos.yml parameters for cisco-8000 platform
Adding qos.yml parameters for cisco-8000 platform
Verifed this parameters for test_qos_sai.py script and all the testcase passes on local setup .
=> update qos.yml for cisco-8000 platform

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
remove xfail for test case which is expected to pass.
remove xfail for test case which is expected to pass.
=> [xfail] remove xfail for some testcases

tests/platform_tests/test_cpu_memory_usage.py
Summary:
Loose criteria of memory usage for test_cpu_memory_usage
platform_tests/test_cpu_memory_usage.py failed because of memory usage exceeds 80%.
Change memory criteria from 80 to 90.
run tests/platform_tests/test_cpu_memory_usage.py
=> Loose criteria of memory usage for test_cpu_memory_usage

ansible/module_utils/port_utils.py
TD3: RA-B6510-32C
TH3: RA-B6920-4S
Summary:
Add two Ragile plkatforms to support pytest. (TD3 + TH3)
=> Add two Ragile platforms

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip ecmp test scripts on Mellanox 2700 platform
Add it in tests_mark_conditions.yml
Run ecmp test scripts on Mellanox  2700 testbed.
Mellanox 2700
=> Skip ecmp test scripts on Mellanox 2700 platform

tests/override_config_table/test_override_config_table.py
Summary: Add skip_release import for reload for override test.
=> Add import for skip_release

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
To ignore log error for now, which is triggered by a known issue.
=> loganalyzer ignore

docs/tests/README.md
Summary:
fix path to README files in docs/tests (plugins section)
just want to give you a hand in keeping the documentation up to date 
It was checked manually that the new link is not broken and it is redirected to correct file.
["Plugins" section](https://github.com/Azure/sonic-mgmt/blob/master/docs/tests/README.md)
fix path to README files in docs/tests
=> fix path to README files in docs/tests (plugins section)

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Skips unsupported platform tests for barefoot
Skips the following unsupported tests for barefoot devices:
```
platform_tests/api/test_chassis.py::TestChassisApi::test_get_watchdog
platform_tests/api/test_psu.py::TestPsuApi::test_power
platform_tests/api/test_sfp.py::TestSfpApi::test_tx_disable_channel
platform_tests/test_reload_config.py
```
Updated conditional_mark skip conditions.
Run above mentioned tests - all tests should be skipped.
=> [barefoot] Skip unsupported platform tests

tests/pfc/test_unknown_mac.py
Summary: skipped test_unknown_mac for Barefoot
The test expects packets with unknown destination MAC to drop, but for Barefoot platform flooding is expected instead
=> skipped test_unknown_mac for Barefoot

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
There is an error due to the lack of a quotation in `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml`. Add the quotation in this pr.
Summary:
Fixes #5806
There is an error due to the lack of a quotation in `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml`. Add the quotation in this pr.
Add the lack quotation.
=> Fix a bug in `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml`

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: enabled PFC Asym tests for Barefoot
=> enabled PFC Asym tests for Barefoot

.azure-pipelines/run-test-template.yml, azure-pipelines.yml, tests/common/plugins/conditional_mark/issue.py, tests/kvmtest.sh
We can use github issues as conditions in `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml`. If the status  of issue is `closed`, we will not skip the test case. Due to the lack of git credentials, we can not visit github and consider all the issues as open before. In this pr, we add the git credentials into environment variables, so we can get the real status of issue. And the status of this issue is closed, we will not skip this test case. 
Summary:
We can use github issues as conditions in `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml`. If the status  of issue is `closed`, we will not skip the test case. Due to the lack of git credentials, we can not visit github and consider all the issues as open before. In this pr, we add the git …
=> Get token from environment variable for accessing Github

ansible/health_checker.py, test_reporting/kusto/setup.kql
Summary:
Check ICMP reachability of server and ptf for testbeds as well.
Check ICMP reachability of server and ptf for testbeds as well. Add several new columns for testbed health info table in Kusto.
The final data looks like this:
```
[
{
"TestbedName": "vms1-1",
"DutIP": "10.10.10.10",
"ServerName": "server-1",
"ServerIcmpReachability": 1,
"DutName": "str-1",
"DutIcmpReachability": 1,
"PtfIP": "20.20.20.20",
"ServerIP": "30.30.30.30",
"DutConsoleReachability": null,
"PtfName": "ptf-1",
"DutSshReachability": null,
"PtfIcmpReachability": 1
}
]
```
Improve `health_checker.py` to check icmp for all hosts in inventory files.
Then parse `testbed.yaml` file to get all testbeds.
Check the ping result of dut/server/ptf from …
=> Check ICMP reachability of server and ptf for testbeds

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Update the ignore of PBH tests.
The feature was introduced in branch 202111. All later branches support this feature.
run tests on 202111 branch
updated the ignore
verified on 202111 branch
=> [PBH] enable PBH tests on valid branches only

tests/show_techsupport/test_auto_techsupport.py
[auto-techsupport] Stabilize auto-techsupport tests
Improved tests stability
Old logic expected that specific timestamp will be in last log file. Sometimes last log file could be not the same as we expected(near it it but different file with different old timestamp).
Now instead of checking that oldest timestamp == expected oldest timestamp - we do check that oldest timestamp in [list of expected(possible) oldest timestamps]
Some tests were not stable and time to time fail. This commit should increase tests stability.
Summary: Stabilize auto-techsupport tests
Stabilize tests, reduce test failures
Changed logic from: oldest timestamp == expected oldest timestamp to oldest timestamp in [ expected oldest timestamps ]
Executed …
=> [auto-techsupport] Stabilize auto-techsupport tests

tests/everflow/test_everflow_per_interface.py
Summary:
Remove barefoot asic for everflow_per_interfaces TC
Functional tested by everflow_per_interfaces TC has been added to Barefoot 
Removed asic type from skip list
Run everflow_per_interfaces TC. TC passed
=> [everflow] enabled everflow per interfaces for barefoot asic

tests/generic_config_updater/test_aaa.py, tests/generic_config_updater/test_bgp_prefix.py, tests/generic_config_updater/test_bgp_speaker.py, tests/generic_config_updater/test_bgpl.py, tests/generic_config_updater/test_cacl.py, tests/generic_config_updater/test_dhcp_relay.py, tests/generic_config_updater/test_ipv6.py, tests/generic_config_updater/test_lo_interface.py, tests/generic_config_updater/test_monitor_config.py, tests/generic_config_updater/test_portchannel_interface.py, tests/generic_config_updater/test_syslog.py, tests/generic_config_updater/test_vlan_interface.py
Summary: Improve GCU test with less running time; Resolve dualTor test failure.
GCU long running tests were skipped. This PR is to add them back with reduced runnning time.
Change to choose the idential DUT for test in dualTor.
Combining subtests into one test, thus eliminate the Log Analyzer running time.
Change duthost fixture to rand_selected_dut.
Running kvm test
=> [GCU] Improve GCU test with reduced testing time

ansible/group_vars/all/creds.yml, ansible/roles/vm_set/tasks/main.yml, ansible/roles/vm_set/tasks/manage_duts.yml, ansible/roles/vm_set/templates/sonic.xml.j2, ansible/testbed-cli.sh, tests/common/testbed.py
Summary:
This pr is for feature enhancement of support wan topo
Leverage sonic mgmt framework to support more complex topo and multi-vendor devices
Leverage main process of sonic mgmt, and separate deployment logic from current sonic mgmt
Use T0 topo to verify code changes
None
NA
=> enhance to support wan topo

tests/conftest.py
Summary:
The autoused fixture for collecting DB dumps for failed cases need to run
some redis-dump commands for each of the DBs. The original implementation
called the ansible command module on DUT once for each of the redis-dump
command. This is not efficient enough because of the extra ansible overheads.
This change updated the code to use "shell_cmds" module to run all the
redis-dump commands in a batch.
This change also updated the dump file name to include test module name,
not just the test case name which could conflict across different test scripts.
Tested on vSONiC setup, this change can decrease redis-dump execution
time from 13 seconds to 6 seconds.
=> Optimize DB dump collection for failed test case

tests/common/plugins/conditional_mark/__init__.py
In order to skip test cases using conditional marks, we need to gather the basic facts of dut, which will cost some time. `session.config.cache` in pytest can support sharing values between py.test invocations. So we use this to cache the basic facts of dut.
Summary:
In order to skip test cases using conditional marks, we need to gather the basic facts of dut, which will cost some time. `session.config.cache` in pytest can support sharing values between py.test invocations. So we use this to cache the basic facts of dut.
Compare the tbname with cached tbname.
If they are not the same testbed, clear the cache, get the new basic facts, and put the new tbname and basic facts in cache. 
If the tbname is same as cached tbname, if we already have dut basic facts in cache, use …
=> Cache dut basic fact using `session.config.cache`. 

tests/common/sai_adhoc.py
Summary:
Encapsulated ansible API using Python
Support three operation `cmd, fetch, copy` on DUT and PTF
Tested done in the internal pipeline.
=> Add SAI ansible adhoc API

setup-container.sh
Summary:
Sometimes setup container takes long time and not sure where it was spending time.
Add option -x to enable execution tracing.
run setup container script with -x option
=> [setup container] add option to show setup container execution details

tests/snappi/ecn/test_dequeue_ecn_with_snappi.py, tests/snappi/ecn/test_red_accuracy_with_snappi.py, tests/snappi/pfc/test_global_pause_with_snappi.py, tests/snappi/pfc/test_pfc_pause_lossless_with_snappi.py, tests/snappi/pfc/test_pfc_pause_lossy_with_snappi.py, tests/snappi/pfcwd/test_pfcwd_a2a_with_snappi.py, tests/snappi/pfcwd/test_pfcwd_basic_with_snappi.py, tests/snappi/pfcwd/test_pfcwd_burst_storm_with_snappi.py, tests/snappi/pfcwd/test_pfcwd_m2o_with_snappi.py, tests/snappi/pfcwd/test_pfcwd_runtime_traffic_with_snappi.py
Summary:
Enable snappi test cases on tgen testbeds
Enable snappi test cases on tgen testbeds
Enable snappi test cases on tgen testbeds
Enable it and will verify it in the future nightly test runs.
=> [RDMA&SNAPPI] Enable snappi test cases in nightly run

tests/saitests/switch.py
Updating PG_SHARED_WATERMARK testcase for cisco Platform .
Updating PG_SHARED_WATERMARK testcase for cisco Platform .
Verified the Change on the local cisco-8000 platform
=> updating pg_shared_watermark_test for cisco-8000

tests/platform_tests/test_memory_exhaustion.py
Summary:
Some DUTs with few free memory (eg. Celestica-E1031) may reboot before ansible receive the result of `tail /dev/zero`, so we add `sleep 5` to ensure ansible receive the result first.
Some DUTs with few free memory (eg. Celestica-E1031) may reboot before ansible receive the result of `tail /dev/zero`, so we add `sleep 5` to ensure ansible receive the result first.
Add `sleep 5` to ensure ansible receive the result before DUT reboot.
Verified on Celestica-E1031.
=> [test_memory_exhaustion] Fix test failure on DUTs with few free memory

tests/override_config_table/test_override_config_table.py
Summary: Make DUT identical when testing on dualTor case.
=> [tests/override_config_table] Handle dualTor test

ansible/roles/vm_set/tasks/main.yml
Summary:
Support ubuntu 22.04 in deployment of testbed.
=> Support ubuntu 22.04 in deployment of testbed

tests/route/test_route_flap.py
Summary: This PR should fix test_route_flap, with such issues as:
1) It seems that TC didn't perform withdraw or announce operations properly
**Logs from exabgp:**
```
Mon, 06 Jun 2022 07:32:48 | INFO     | 539    | processes     | Command from process http-api : neighbor 10.1.0.32 withdraw route 192.182.216.0 next-hop 10.0.0.57 
Mon, 06 Jun 2022 07:32:48 | WARNING  | 539    | reactor       | no neighbor matching the command : withdraw route 192.182.216.0 next-hop 10.0.0.57
Mon, 06 Jun 2022 07:34:05 | INFO     | 539    | processes     | Command from process http-api : neighbor 10.1.0.32 announce route 192.182.216.0 next-hop 10.0.0.57 
Mon, 06 Jun 2022 07:34:05 | WARNING  | 539    | reactor       | no neighbor …
```
=> Fix test_route_flap case

tests/crm/test_crm.py
In the test_crm.py, it is using the sleep, but the sleep time is not reliable, sometimes, it may not enought, and cause the test case fail.
Change-Id: Ie55738820ea25d68a24da3e443f1c9c4a2afda8a
Summary: Use wait_until instead of sleep when check the states in test_crm.py 
Fixes # (issue) When use sleep, the sleep time is fixed, it can be not enough, and then will cause the test fail, and if the sleep time is too long, it will increase the test run time.
Fix the test failure caused by the sleep time is not enough.
Failed: "crm_stats_ipv4_neighbor_available" counter was not incremented
Failed: "crm_stats_nexthop_group_available" counter was not incremented
Use wait until instead of sleep when check the states in test_crm.py 
Run the test_crm.py test serveral times , and it pass
No
=> [crm]Use wait_until instead of sleep when check the states

ansible/templates/minigraph_meta.j2
Why I did:
As describe here: https://github.com/Azure/sonic-buildimage/pull/11407
=> Added Deployment_id in Asic metadata.

tests/sai_qualify/cases_brcm_t0.py
Summary:
Add FDB test cases
Add fdb cases
Add fdb cases to the case list
Run it on dx010 with sai qualify framework
=> add fdb test cases

tests/common/plugins/conditional_mark/__init__.py
Improved conditional_mark plugin to support "OR" or "AND" operand between condition in conditions list
Previously every time we did AND operand between condition in conditions list, now we can provide "conditions_logical_operator" argument with operation which should be performed between conditions.
Possible arguments(by default, if not provided - AND used): 
```
conditions_logical_operator: or
conditions_logical_operator: and
```
Example of usage(test will be ignored if first or second condition in list True):
```
ecmp/test_fgnhg.py:
skip:
reason: "Testcase ignored - check ignore condition in ignore file"
conditions_logical_operator: or
conditions:
- "https://redmine.x.com/issues/12345 and 'msn2' in platform"
- …
```
=> [conditional_mark] Improved conditional_mark plugin to support "OR" or "AND" operand between condition in conditions list

ansible/dualtor/nic_simulator/nic_simulator.py, ansible/roles/vm_set/library/vm_topology.py
Summary:
mgmt client could not talks to the gRPC server.
1. Bring up loopback device to enable mgmt service talks to each gRPC server interacting with SONiC.
2. Add common gRPC options to the `nic_simulator`.
3. Add timeout for the gRPC calls from mgmt service.
Verify mgmt client could talks to the mgmt service of `nic_simulator.
=> [nic_simulator] Fix several issues

ansible/roles/vm_set/library/vm_topology.py
Summary:
The `testbed-cli.sh remove-topo` operation is to remove the topology, including cEOS neighbors, ovs bridge bindings, and ovs bridges.
For some reason, the ovs bridges to be removed may be gone. In this case, the `testbed-cli.sh remove-topo` will fail with not able to find the bridges.
Indeed, this failure is unnecessary because this operation is to remove the bridge bindings and bridges. If a bridge is already gone, then we can simply ignore it.
This change improved the vm_topology ansible module to skip a bridge if it does not exit while trying to remove the bridge bindings and bridges. With this change, the `testbed-cli.sh remove-topo` always can succeed and do the job.
This PR also improved the error message if run a command failed.
Tested on physical and …
=> Improve robustness of remove-topo operation
