sonic-net/sonic-mgmt

- tests/acl/test_acl.py
Issue:
ACL byte counters not incrementing in Cisco 8111 and test_acl.py tests fail due to assertion for byte counters.
RC:
Due to differences in ASIC, Cisco 8111 supports only frame/packet accounting for ACE counters(ACL counters). 
Fix:
Skip byte accounting only for hwsku's for Cisco 8111.
> ACL test fix for 8111

- tests/snappi/pfcwd/test_pfcwd_basic_with_snappi.py
Summary: After pfcwd tests that restarted the swss container, corresponding containers such as bgp, teamd, radv would also go down without recovering in RDMA nightly pipelines. The effect of these down containers would successively spread to future tests causing them to fail. Normally, the sanity checker in the pipeline will handle down containers and restart them as necessary, but due to the limitations of the sanity checker, they cannot be enabled on RDMA pipelines, hence the power to restart down containers after a test is not there, so this change acts to reload the containers after swss service restart tests for pfcwd.
Prevent successive test failure for RDMA pipelines when containers fail to be brought up again
config reload the DUT safely after swss service restart …
> [Snappi] Config reload to stabilize DUT after container restart

- tests/snappi/pfcwd/test_pfcwd_basic_with_snappi.py
Summary: Cherry pick from PR #8800
```
admin@STR-8102:~$ docker ps 
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS               NAMES
b877f06c8159        docker-snmp:latest                "/usr/local/bin/supe…"   7 hours ago         Up 9 minutes                            snmp
97ae0dccd69e        docker-sonic-telemetry:latest     "/usr/local/bin/supe…"   7 hours ago         Up 9 minutes                            telemetry
fced3f4e7dc6        docker-vnet-monitor:latest        "/usr/local/bin/supe…"   7 hours ago         Up 9 minutes                            vnet-monitor
899aef30bdc5        docker-dhcp-relay:latest          "/usr/bin/docker_ini…"   7 hours ago         Up 9 minutes …
```
> [202012][Snappi] Config reload to restart down containers

- ansible/roles/test/files/ptftests/py3/dhcpv6_relay_test.py
Improve dhcpv6_relay_test.py test packets, insert different options in different packets to cover more cases.
1. Add DHCP6OptServerId in Relay-Reply packets
2. Add DHCP6OptIfaceId in Relay-Reply packets
3. Add DHCP6OptElapsedTime relay-forward packets
Summary:
Improve dhcpv6 test cases to cover option parser logic and packet sanity tests.
Improve dhcpv6_relay_test.py test packets, insert different options in different packets to cover more cases.
1. Add DHCP6OptServerId in Relay-Reply packets
2. Add DHCP6OptIfaceId in Relay-Reply packets
3. Add DHCP6OptElapsedTime relay-forward packets
Add DHCP6OptServerId, DHCP6OptIfaceId, DHCP6OptElapsedTime in relay-forward/relay-reply packets.
> improve dhcpv6 test packets to cover option parse cases

- tests/bgp/test_traffic_shift.py
Fix test_traffic_shift.py unstable failure, it not always failure but can be reproduced occasionally.
E               Failed: Processes "['parse_routes_process--<EosHost VM21027>']" failed with exit code ""
E               Exception:
E               Traceback:
Summary:
Fix test_traffic_shift.py parallel_run  parse_routes_process timeout issue. 
Seems sometime parse_routes_process executing on EOS did not give response before timeout due to some unknown reason.
As a work around, extend wait timeout value to avoid the issue.
Extend wait time out value. 
rerun test_traffic_shift.py multiple times.
> fix python process parse_routes_process timeout waiting issue

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
`system_health/test_system_health.py::test_service_checker_with_process_exit` is running to pass with latest 202012 image whatever platform is.
But from test result, it's still xfail, because the build_version is 20201231.105, string comparing with 20201231.44, it's smaller than 20201231.44.
Split the version number and do compare then.
`system_health/test_system_health.py::test_service_checker_with_process_exit PASSED [100%]`
> Remove xfail condition mark for test_system_health

- tests/common/dualtor/mux_simulator_control.py
Summary:
Use toggle function with mux direction check.
Run dualtor-io testcases.
> [202205][dualtor] Add mux direction checks to toggle fixtures

- tests/common/plugins/conditional_mark/tests_mark_conditions_202205.yaml
Summary:
These dualtor and dualtor_io testcase failures must be fixed in 202205 branch. So remove the xfail mark.
These dualtor and dualtor_io testcase failures must be fixed. So remove the xfail makr.
Remove from tests_mark_conditions_202205.yaml
N/A
> Remove dualtor and dualtor_io 's xfail condition mark

- tests/qos/qos_sai_base.py
Summary: One of the change in qos_sai_base for  populateArpEntries in PR -https://github.com/sonic-net/sonic-mgmt/pull/8377 ; the check for t2 is failing
The dutTestParams["topo"] return a string which is combination of topo_type and chassis name.
For ex., **t2_ixre_chassisxxx**
Hence, the correct check would be - -> if "t2" in dutTestParams["topo"]
Qos  test suite failed as the if condition was not fulfilled and the arp table were cleared for t2 topology
Changed the if condition to check if "t2" string is present in the dutTestParams["topo"]
Ran the Qos test suite for t2 topology
> Correction in condition check for t2 in  dutTestParams - qos_sai_base

- tests/platform_tests/daemon/test_chassisd.py
- tests/platform_tests/daemon/test_psud.py
**Cherry-Pick PR #7781 :** For resolving conflicts.
Fix for PID assertion issue - PSUD and CHASSID platform cases.
Fixing up other chassisd and psud platform tests to poll for deamon to restart with bigger pid than before.
This is an extension of PR https://github.com/sonic-net/sonic-mgmt/pull/7150.
Summary:
Fixes PSUD '_stop & start_', '_term & start_' and '_kill & start_' test cases by making sure the daemon restarted has bigger PID than before.
Fixes CHASSID '_stop & start'_ and '_kill & start_' test cases by making sure the daemon restarted has bigger PID than before.
- Currently PSUD and CHASSID platform test cases like 'term & start', '_kill & start_' and '_stop & start'_ don't check if the restarted daemon has bigger pid than the previous one or not.
- Currently …
> [cherry-pick] [PR:7781] Fix for PID assertion issue - PSUD and CHASSID platform cases (#7781)

- tests/scp/test_scp_copy.py
Enhance test_scp_copy.py to run on rand_one_dut_hostname(randomly selected dut). We need the test cases to run on both supervisor and the line card (per hwsku).
This PR is the same as PR #6880.  I created this PR due to Cherry Pick Conflict_202205. 
Summary:
Modified testcases to run on multi-dut.
Replaced 'rand_one_dut_hostname' with 'enum_rand_one_per_hwsku_hostname'.
Ran test cases on a multi duts multi asics chassis.
> Adapting tests to run on T2 chassis by changing rand_one_dut_hostname

- tests/autorestart/test_container_autorestart.py
There is a config reload in module `autorestart/test_container_autorestart.py` and previously it reload from `running_golden_config`. This source will add BREAKOUT_CFG in running config and cause another reload in the teardown period of this module. In this PR, we change the reload source from `running_golden_config` to `config_db`, which will avoid unnecessary reload and save running time. 
Summary:
There is a config reload in module `autorestart/test_container_autorestart.py` and previously it reload from `running_golden_config`. This source will add BREAKOUT_CFG in running config and cause another reload in the teardown period of this module. In this PR, we change the reload source from `running_golden_config` to `config_db`, which will avoid unnecessary reload and save …
> Change reload source in module `autorestart/test_container_autorestart.py`.

- tests/qos/files/qos.yml
Summary:
test_xoff_for_pcbb hit failure as below:
```
>       return qos_configs['qos_params'][dut_asic][dut_topo][profile_name]
E       KeyError: u'100000_300m'
```
RCA:
miss th2's qos parameter for "100000_300m".
add th2 qos parameter for 100000_300m
pass local test:
```
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb[pcbb_xoff_1] PASSED     [ 25%]
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb[pcbb_xoff_2] PASSED     [ 50%]
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb[pcbb_xoff_3] PASSED     [ 75%]
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb[pcbb_xoff_4] PASSED     [100%]
```
just for broadcom th2 platform
> th2 qos parameter for 100000_300m

- tests/common/fixtures/ptfhost_utils.py
Summary:
This PR is a part of fixes for `dualtor_io` flaky tests. Observed mux flaps before tests start. It is because for acitve-standby dualtors, icmp_responder is started by `run_icmp_reponder` fixture which runs on module level. 
To make sure icmp_responder consistently functions, I'm enabling it from session level now. 
Notice: 
For active-active and mixed topo, icmp_responder starts at session level, and remains running at end of test.  
For active-standby topo, icmp_responder starts at session level, and stops at end of test, 
For other cases, icmp_responder is handled by `run_icmp_responder` which runs on module level. 
Run test_normal_op tests on dualtor-aa topo and dualtor topo. 
```
[dualtor-aa]
22:50:55 …
```
> Enable `icmp_responder` on session level for `dualtor` topology

- tests/vxlan/vxlan_ecmp_utils.py
This PR fixes the issue which is caused when the decode function is called on a string in python3. There is no decode function implemented in python3 as strings in python3 are by default unicode. This results in an exception.
This change checks if the decode function is present. i.e python2.7 then calls it otherwise skips it.
Summary:
> Vxlan ECMP test failure in python3 env.

- tests/qos/files/qos.yml
Summary:
double commit PR https://github.com/sonic-net/sonic-mgmt/pull/8815
test_xoff_for_pcbb hit failure as below:
```
>       return qos_configs['qos_params'][dut_asic][dut_topo][profile_name]
E       KeyError: u'100000_300m'
```
RCA:
miss th2's qos parameter for "100000_300m".
add th2 qos parameter for 100000_300m
pass local test:
```
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb[pcbb_xoff_1] PASSED     [ 25%]
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb[pcbb_xoff_2] PASSED     [ 50%]
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb[pcbb_xoff_3] PASSED     [ 75%]
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb
```
just for broadcom th2 platform
> [qos][doble commit] th2 qos parameter for 100000_300m

- tests/common/dualtor/dual_tor_mock.py
Summary:
For Nvidia platforms, the tunnel source IP is needed for the IPinIP tunnel configuration. Currently, the dualtor t0 mocked tests doesn't configure the src_ip, need to add it when the dut is Nvidia device.
Support the dualtor t0 mocked tests on Nvidia platforms.
Add the src_ip in the mocked tunnel configuration.
By automation, all related tests passed on 4600C.
> [Dual-Tor][Nvidia] Update the mocked tunnel configuration for Nvidia platforms

- tests/route/test_route_perf.py
Summary:
test_route_perf failed at m0-2vlan topo
Add support for m0-2vlan
Run test
> [202205][m0][route] Add support for m0-2vlan in test_route_perf

- tests/conftest.py
In PR (https://github.com/sonic-net/sonic-mgmt/pull/6527), it enhanced function `core_dump_and_config_check` to be multi-asic aware. But in single-asic scenerio, it simply set the key None, which does not make scene. In this PR, I reset the key "asic0" in single-asic scenerio to keep consistent with the key value of multi-asic scenerio. 
Summary:
In PR (https://github.com/sonic-net/sonic-mgmt/pull/6527), it enhanced function `core_dump_and_config_check` to be multi-asic aware. But in single-asic scenerio, it simply set the key None, which does not make scene. In this PR, I reset the key "asic0" in single-asic scenerio to keep consistent with the key value of multi-asic scenerio. 
Change the key in single-asic scenerio from `None` to `asic0`.
> Set key "asic0" in single-asic scenerio to keep consistent with multi-asic in function `core_dump_and_config_check`.

- tests/conftest.py
There is a cherry pick conflict in 202012 branch of PR (https://github.com/sonic-net/sonic-mgmt/pull/8884).
Summary:
There is a cherry pick conflict in 202012 branch of PR (https://github.com/sonic-net/sonic-mgmt/pull/8884).
I tested using 202012 branch on 202012 image, and no error occurs.
> [202012]Set key "asic0" in single-asic scenerio to keep consistent with multi-asic in function `core_dump_and_config_check`.

- .azure-pipelines/test_plan.py
Summary:
fix the issue that endless waiting if expected_result is specified
> [Elastictest] fix the issue that endless waiting if expected_result is specified

- tests/common/devices/sonic.py
- tests/qos/test_tunnel_qos_remap.py
…ic name
Summary:
hit test_tunnel_decap_dscp_to_pg_mapping failure on testbed "vms21-dual-t0-7260", as below:
```
"/root/env-python3/bin/ptf",
"--test-dir",
"saitests/py3",
"sai_qos_tests.TunnelDscpToPgMapping",
"--platform-dir",
"ptftests",
"--platform",
"remote",
"-t",
"platform_asic=u'broadcom';cell_size=256;inner_dscp_to_pg_map={0: 0, 1: 0, 2: 0, 3: 2, 4: 6, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 0, 18: 0, 19: 0, 20: 0, 21: 0, 22: 0, 23: 0, 24: 0, 25: 0, 26: 0, 27: 0, 28: 0, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0, 40: 0, 41: 0, 42: 0, 43: 0, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 0, 50: 0, 51: 0, 52: 0, 53: 0, 54: 0, 55: 0, 56: 0, 57: 0, 58: 0, 59: 0, 60: 0, 61: 0, 62: 0, 63: …
```
> fix test_tunnel_decap_dscp_to_pg_mapping failure caused by unknonw asic name

- tests/configlet/test_add_rack.py
- tests/vxlan/test_vxlan_ecmp.py
- tests/vxlan/vxlan_ecmp_utils.py
This PR adds the tests for priority tunnels where switchover from primary-secondary endpoint sets is performed upon failure of endpoint.
Summary:
These tests only run on platforms that support Vxlan tunnels, such as Cisco 8102, Mlnx 4600, Mlnx 2700
t1-64-lag
> Vxlan ecmp primary/secondary switchover tests.

- tests/common/fixtures/advanced_reboot.py
Summary: This is an enhancement to warm reboot test to help store logs under host/logs_before_reboot in techsupport capture during upgrade pipeline runs
Currently logs under /host/logs_before_reboot is not collected during show techsupport. Moving /host/logs_before_reboot directory to /var/log temporarily under a more permanenetly solution exists in image
Move directory /host/logs_before_reboot to /var/log
Manually ran test_warm_reboot. Directory /host/logs_before_reboot was moved to /var/log and test passed
https://elastictest.org/scheduler/testplan/64ac3c778524edcd5632d407
> Move logs_before_reboot directory to /var/log after reboot

- tests/platform_tests/test_power_off_reboot.py
this is to fix regression caused by https://github.com/sonic-net/sonic-mgmt/pull/8646
cherry pick PR of https://github.com/sonic-net/sonic-mgmt/pull/8646 is https://github.com/sonic-net/sonic-mgmt/pull/8892 which already has the fix in current PR.
regression:
```
platform_tests/test_power_off_reboot.py::test_power_off_reboot[5-str2-7050cx3-acs-02] 
12:40:46 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
return self._hookexec(self, …
```
> [test_power_off_reboot.py] add missing fixture

- tests/tacacs/test_ro_disk.py
Summary:
Fix `os.mkdir()` failure in `test_ro_disk`:
```
if not os.path.exists(DATA_DIR):
>               os.mkdir(DATA_DIR)
E               OSError: [Errno 2] No such file or directory: 'logs/tacacs'
```
Fix `os.mkdir()` failure in `test_ro_disk`.
Use `os.makedirs()` instead of `os.mkdir()` to create multi-level folder.
Verified by running test on physical testbed.
> Fix `os.mkdir` failure in test_ro_disk

- tests/route/test_route_perf.py
Summary:
It's not need to set high test routes number for M0/MX topo, hence they don't require l3_alpm_enable.
Skip this precheck for M0/MX topo.
Run tests.
```
route/test_route_perf.py::test_perf_add_remove_routes[4-testbed-None] PASSED                                                                                                     [ 50%]
route/test_route_perf.py::test_perf_add_remove_routes[6-testbed-None] PASSED                                                                                                     [100%]
```
> [route] Fix test_route_perf failed in m0/mx

- tests/common/utilities.py
- tests/vlan/test_autostate_disabled.py
In module `vlan/test_autostate_disabled.py`, it will change the admin_state of interfaces. Although it will restore all interfaces to their original admin_state, it will add some entries in running config, which are not exist before. So in this PR, after the module running, we will delete these additional entries. 
Summary:
In module `vlan/test_autostate_disabled.py`, it will change the admin_state of interfaces. Although it will restore all interfaces to their original admin_state, it will add some entries in running config, which are not exist before. So in this PR, after the module running, we will delete these additional entries. 
Delete additional entries which are not exist before.
```
06:13:11 conftest.core_dump_and_config_check      L2131 INFO   | Core dump and …
```
> Delete interfaces admin_state after module `vlan/test_autostate_disabled.py` running. 

- .azure-pipelines/pr_test_scripts.yaml
- tests/iface_namingmode/test_iface_namingmode.py
…y static route (#8568)
cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/8568
For T2 topology, show ip route checks if there is a default route via non portchannel interface towards a T3 neighbor and test checks if that interface name is displayed as per the correct mode (default/alias). Test will be skipped for T2 topology if there is no T3 neighbor, this will skip the test on a LC if there is a no T3 neighbor. How did you do it?
Add a dummy route to 192.168.1.1/::0/0 via one of the non portchannel interface and update test to check if that particular interface name is displayed correctly as per the selected mode. Currently iface_namingmode test case is being run only for t0 testbed in PR checker, show_ip_route test is skipped on t0 as there …
> [202205]iface_namingmode: Modify show ip route test case using a dummy static route

- ansible/roles/test/files/helpers/arp_responder.py
Summary:
This import is necessary in the arp_responder but was accidentally removed by PR https://github.com/sonic-net/sonic-mgmt/pull/8064.
```
import scapy.arch.pcapdnet
```
Need to add it back or some tests will fail.(we have observed failures in acl test which is related to this issue)
For details of this import, please reference this PR https://github.com/sonic-net/sonic-mgmt/pull/8481
Fix the ansible arp_responder
Add the import 
```
import scapy.arch.pcapdnet
```
Run the affected acl test, all passed after the fix.
> Add back an important import in ansible arp_responder.py

- tests/common/devices/multi_asic.py
- tests/route/test_route_flap.py
Summary:
- This PR fixes "test_route_flap" test under route test suite.
"'route/test_route_flap.py::test_route_flap"
- For VOQ Chassis with Multi-Asic, there is no Key as "BGP_INTERNAL_NEIGHBOR" and hence the Test Case is failing if Next hop selected is peer asic. A filter with "VOQ_INBAND_INTERFACE" for Ethernert-IBs is added as well in order to support the VOQ Chassis
- Fixes issue Refer: https://github.com/sonic-net/sonic-mgmt/issues/8840
Currently the Test Case fails for VOQ Chassis(Muilti-Asic) as there is no key "BGP_INTERNAL_NEIGHBOR" in config facts.
Refer: https://github.com/sonic-net/sonic-mgmt/issues/8840
Create a new function get_voq_inband_interfaces in order to get VOQ_INBAND_INTERFACE from running config facts to exclude it from the list of hops.
Ran the …
> Reg: test_route_flap_voq_chassis_update

- tests/platform_tests/conftest.py
After certain tests, we try to bring up all the interfaces as a post-test action. However, the code as written doesn't work on multi-ASIC systems, since it doesn't provide the correct ASIC namespace to the command. We replace the call to an explicit CLI command to bring up the interface, and provide the namespace argument if needed.
> Fix missing namespace option in interface restart code

- ansible/roles/vm_set/files/mux_simulator.md
- ansible/roles/vm_set/files/mux_simulator.py
- tests/common/dualtor/mux_simulator_control.py
- tests/dualtor_io/test_link_drop.py
Summary:
There is no mux simulator API to drop flow for all ports. 
Currently, there is a loop to drop every port's flow one by one. This is too time-consuming.
In this PR, add output all and drop all mux simulator API and use the API in dualtor_io testcases
/mux/<vm_set>/output
/mux/<vm_set>/drop
Currently, there is no API to drop all flow. There is a loop to drop every port one by one. This is too time consuming.
Add two APIs to output/drop all ports in one API call.
Test with physical testbed with testcases in dualtor_io/test_link_drop.py
6 passed, 6 skipped, 2 warnings in 2019.75s (0:33:39)
> Add output all and drop all HTTP API in mux simulator in dualtor_io testcase

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
…6-lag
Summary:
update skip rule of test_lag_db_status_with_po_update to support t1-56-lag
update skip rule of test_lag_db_status_with_po_update to support t1-56-lag
> update skip rule of test_lag_db_status_with_po_update to support t1-56-lag

- tests/saitests/py3/sai_qos_tests.py
The DSCP to PG mapping test is using only one decrement for the returned packet. In case of cisco-8000 platform for T2, we have 2 DUTs when multiple-asics are used. So the TTL calculation needs to be fixed.
> cisco: qos-sai: Multi-asic: dscp to PG mapping and DscpMappingPB ttl check updated

- tests/crm/test_crm.py
Failed: Counter 'crm_stats_fdb_entry_available' was not incremented
Verify "crm_stats_fdb_entry_available" counter was incremented
pytest_assert(new_crm_stats_fdb_entry_available - crm_stats_fdb_entry_available >= 0, \
> "Counter 'crm_stats_fdb_entry_available' was not incremented")
E Failed: Counter 'crm_stats_fdb_entry_available' was not incremented
Summary:
**As per the detailed UT with crm/test_crm.py::test_crm_fdb_entry, below are my observations:**
* While CRM_POLLING_INTERVAL we can opt for CRM_UPDATE_TIME = 5 as FDB table get repopulated post 5msec which tends to fail our test checks.
* This testcase is meant for T0* & M0 only, so added "Unsupported topology, expected to run only on 'T0*' or 'M0' topology"
* While initial stage of testcase post fdbclear added extra …
> MIGSOFTWAR-2426 Counter crm_stats_fdb_entry_available was not incremented

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
… update it to support t1-56-lag
Summary:
update skip rule of test_lag_db_status_with_po_update to support t1-56-lag, and remove redundancy rule
update skip rule of test_lag_db_status_with_po_update to support t1-56-lag, and remove redundancy rule
> update skip rule of test_lag_db_status_with_po_update to support t1-56-lag, and remove redundancy rule

- tests/fib/test_fib.py
Summary:
test_fib will randomly fail in marvell asic. To fix it.
It failed because "240.0.0.0/24" is not excluded in test ip ranges. This PR [7030](https://github.com/sonic-net/sonic-mgmt/pull/7030) has added it but not let it take effect due to missing `asic_type` in the parameter.
Run tests.
> [fib] Fix test_fib failed in Nokia 7215

- tests/autorestart/test_container_autorestart.py
Summary:
Fix test_container_autorestart failed for mx in dhcp_relay container.
In mx topo, dhcp_relay container has two critical process group: dhcp-server with dnsmasq and dhcp-relay with dhcp6relay.
In this test, we will kill process in critical group to see whether the container can restart successfully. In mx scenario, it will kill dhcp6relay and cause dhcp_relay container restart. And then the dhcp_relay container restarts but the dnsmasq service is too late to start, which cause failed at check dhcp-server critical group.
Add wait_until before check, to ensure required process can start.
Run test in M0/MX/T0/T1 topos, all passed.
> [autorestart][mx] Fix test_container_autorestart failed in mx

- tests/common/dualtor/data_plane_utils.py
Summary:
For some `test_link_drop` cases we saw test failures due to two continuous disruptions combined as one. 
This PR updates verification logic for long disruptions. 
Run test_link_drop cases.  `disruption_length=11.6447122097` (which is greated than 10s), didn't cause test failure. 
```
21:24:49 data_plane_utils.validate_traffic_result L0087 INFO   | Server 192.168.0.19 summary:
{
"disruption_after_traffic": false, 
"disruption_before_traffic": false, 
"longest_disruption": 11.644712209701538, 
"longest_duplication": 0, 
"received_packet_diff": -74, 
"received_packets": 551, 
"total_disruptions": 2, 
"total_duplications": 0
}
21:24:49 data_plane_utils._validate_long_disrupti L0139 INFO   | disruption_length: …
```
> update traffic disruption validating logic for dualtor_io tests

- tests/platform_tests/test_power_off_reboot.py
- tests/platform_tests/test_reboot.py
PR https://github.com/sonic-net/sonic-mgmt/pull/8646 added default argument `interfaces_wait_time=MAX_WAIT_TIME_FOR_INTERFACES` in `check_interfaces_and_services`, 
with this `interfaces_wait_time` is getting directly from MAX_WAIT_TIME_FOR_INTERFACES, while this function has not yet called fixture `set_max_time_for_interfaces`.
change fixture  `set_max_time_for_interfaces` to autouse fixture as we need it throughout test module
Summary:
before:
```
File "/azp/_work/65/s/tests/platform_tests/test_reboot.py", line 112, in check_interfaces_and_services
interfaces_wait_time)
AssertionError: Not all transceivers are detected or interfaces are up in 300 seconds
```
after:
```
18:58:16 reboot.reboot                            L0255 INFO   | DUT str2-7804-lc7-1 up since …
```
> [plt_reboot_dict] auto use fixture set_max_for_interfaces in reboot tests

- ansible/roles/test/files/ptftests/arista.py
- ansible/roles/test/files/ptftests/sonic.py
Summary:
Now that sonic-net/sonic-buildimage#15688 has been merged, re-enable checking the IPv6 BGP neighbor status during a warm-reboot.
This reverts #8735 and #8746.
Did a warm-reboot on virtual switch, and verified that it passed.
One oddity that was noticed was that the IPv6 BGP appears to have gone down for about 23 seconds, whereas IPv4 BGP did not go down. This wasn't treated as a failure, though.
> Reenable IPv6 BGP neighbor check during warm-reboot

- ansible/roles/test/files/ptftests/py3/dhcpv6_relay_test.py
Cherry-Pick #8808 into 202205
Summary:
Cherry-Pick #8808 into 202205
> cherry pick #8808 to 202205 improve dhcpv6 test packets to cover option parse cases

- tests/common/helpers/snmp_helpers.py
- tests/macsec/test_interop_protocol.py
- tests/snmp/test_snmp_loopback.py
Summary:
cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/8802
sonic-net/sonic-buildimage#15487 modifies snmpd in SONiC to listen on management and loopback ip by default instead of listening on any IP. test_interop_protocol.py::test_snmp sends a query to the neighbor device using the link ip address. After the above change to listen on management and loopback ip, the snmp query will fail. Hence, modifying the test to send SNMP query to SONiC DUT from neighboring vsonic/eos using Loopback IP of SONiC DUT.
Get loopback IPv4 address DUT and use that to query from neighbor device. Added a generic helped function to send SNMP query to DUT from a neighbor.
(cherry picked from commit …
> [202205]Use device loopback IP address to send SNMP query from neighboring ceos or vsonic (#8802)

- tests/tacacs/test_accounting.py
- tests/tacacs/test_authorization.py
- tests/tacacs/utils.py
Enable TACACS accounting UT on 202012 branch
Enable TACACS accounting UT on 202012 branch
TACACS per-command accounting will be backport to 202012 branch, so enable related UT on 202012.
Remove 202012 branch from TACACS UT skip list
Pass all UT
> Enable TACACS accounting UT on 202012 branch

- tests/common/utilities.py
Fix cherry pick conflict of PR (https://github.com/sonic-net/sonic-mgmt/pull/8901)
But in 202012 branch, module vlan/test_autostate_disabled.py doesn't exist, so, only add function `delete_running_config` in this PR. 
Summary:
Fix cherry pick conflict of PR (https://github.com/sonic-net/sonic-mgmt/pull/8901)
But in 202012 branch, module vlan/test_autostate_disabled.py doesn't exist, so, only add function `delete_running_config` in this PR. 
Add function `delete_running_config` in this PR.
> [cherry pick] #8901 Delete interfaces admin_state after module vlan/test_autostate_disabled.py running into 202012.

- tests/conftest.py
In 202012 branch, there is no multi-asic scenerio. But in PR (https://github.com/sonic-net/sonic-mgmt/pull/8886) and  (https://github.com/sonic-net/sonic-mgmt/pull/8880), they innovate multi-asic scenerio in fixture `core_dump_and_config_check`. We think this innovation is unnecessary, so in this PR, we delete the code related to multi-asic scenerio. 
Summary:
Fixes # (https://github.com/sonic-net/sonic-mgmt/pull/8886) (https://github.com/sonic-net/sonic-mgmt/pull/8880)
In 202012 branch, there is no multi-asic scenerio. But in PR (https://github.com/sonic-net/sonic-mgmt/pull/8886) and  (https://github.com/sonic-net/sonic-mgmt/pull/8880), they innovate multi-asic scenerio in fixture `core_dump_and_config_check`. We think this innovation is unnecessary, so in this PR, we delete the code …
> [202012]Remove multi-asic scenerio in fixture `core_dump_and_config_check` in 202012 branch. 

- ansible/library/shell_cmds.py
- docs/api_wiki/ansible_methods/shell_cmds.md
- tests/common/devices/multi_asic.py
- tests/common/devices/sonic.py
Summary:
1. Add a parameter `timeout` to ansible library `shell_cmds`. The default value is `0` which means no limitation. **(However, this update also introduce a limitation. If the timeout is not 0, then the command should not contain single quotes `'`)**
2. Set the timeout of some commands to 30s to avoid costing too much time, also updated the command to adapt the timeout wrapper.
1. Add a parameter `timeout` to ansible library `shell_cmds`. The default value is `0` which means no limitation.
2. Set the timeout of some commands to 30s to avoid costing too much time, also updated the command to adapt the timeout wrapper.
1. Verified by run `test_pretest` and `test_memory_exhaustion` on physical testbeds.
2. Verified by PR test.
> Add param timeout to ansible library shell_cmds

- tests/upgrade_path/test_upgrade_path.py
- tests/upgrade_path/upgrade_helpers.py
Summary: Update the test test_upgrade_path.py to support validation of the copp tables after in/cross-branch upgrades.
Added validation after upgrade, to compare copp tables with copp_cfg.json file.
Fixes #8085 
Add validation of copp tables after improvement of fast-reboot
Added validation of copp tables after upgrade 
executed test _test_upgrade_path_ with _base_image=**201911**, target_image=**202205**, upgrade_type=**fast**_
> [copp tables] validate copp tables during in/cross-branch upgrades

- tests/saitests/py3/sai_qos_tests.py
Summary:
In experiment, observed current tolerance value is not enough for pg0 , pg2 and pg6.
increase tolerance value for pg0, pg2, pg3, pg4 and pg6
increase tolerance to 20 for pg0, to ignore more backgroup LACP/LLDP traffic
increase tolerance to 10 for pg2/3/4/6 as margin
> increase tolerance for TunnelDscpToPgMapping test

- ansible/roles/test/files/tools/loganalyzer/loganalyzer.py
- tests/common/plugins/loganalyzer/loganalyzer.py
- tests/platform_tests/conftest.py
Summary:
This PR is to fix flaky test case `test_warm_reboot_mac_jump`.
The test failed because the MAC jump log was not found in sairedis log. The error message is
```
['MAC jumping not detected when expected for address: 00-06-07-08-09-0A'])]
```
However, the log we are looking for is in sairedis log. Because it was dropped by LogAnalyzer because long log message (length > 1000) is skipped by default.
```
if in_analysis_range:
if not check_marker and len(rev_line) > 1000:
continue
if self.line_is_expected(rev_line, expect_messages_regex):
expected_lines.append(rev_line)
elif self.line_matches(rev_line, match_messages_regex, ignore_messages_regex):
matching_lines.append(rev_line)
```
https://github.com/sonic-net/sonic-mgmt/blob/9fef739a0ec33c8dce84b5d5bcd61afd0b73b54e/ansible/roles/test/f …
> Enhance LogAnalyzer to support parsing long log lines

- tests/cacl/test_cacl_application.py
The expected rules for dualtor are present in the script as a fixture "ignore_hardcoded_cacl_rule_on_dualtor" but the global variable "ignored_iptable_rules" is not called anywhere. This is causing test_cacl_application_dualtor to fail because the script is not expecting these rules.
Summary:
- [ x] Bug fix
- [ x] 202205
Checked it on DualToR testbed with Cisco devices
> Adding dualtor iptable rules for test_cacl_application_dualtor 

- tests/run_tests.sh
Summary:
Change run_tests.sh to use python2 explicitly(python->python2)
In future, python3 will be the default interpreter. Old branch which is using python2 should  *explicitly* use python2 not python.
Change python command to python2
Can run bgp/test_bgp_fact.py with physical testbed.
> Change run_tests.sh to use python2 explicitly(python->python2) in 202012 branch

- tests/run_tests.sh
Summary:
Change run_tests.sh to use python2 explicitly(python->python2)
In future, python3 will be the default interpreter. Old branch which is using python2 should explicitly use python2 not python.
Change python command to python2
Can run bgp/test_bgp_fact.py with physical testbed.
> Change run_tests.sh to use python2 explicitly(python->python2) in 202205 branch

- tests/common/fixtures/ptfhost_utils.py
Summary:
Enforcing same behavior on `dualtor`, `dualtor-aa` and `dualtor-mixed` topology. 
To enforce same behavior on `dualtor`, `dualtor-aa`, `dualtor-mixed` testbeds. 
Verified on dualtor testbed.
> [dualtor] Leave `icmp_responder` running on `dualtor` topology

- tests/fdb/test_fdb_mac_move.py
- tests/vxlan/test_vnet_route_leak.py
Summary:
Fixes "global name defaultdict is not defined" error in a few testcases
Testcase failed with error "global name defaultdict is not defined"
Add "from collections import defaultdict"
Run the testcase with physical testbed
> Fix global name defaultdict is not defined

- ansible/testbed-cli.sh
Summary:
When deploying vsonic neighbors, the `config_db.json` that gets generated for those neighbors now has a reference to the DUT's IP address (in the DEVICE_NEIGHBOR_METADATA table). This is accessed through `hostvars`, which is read from the inventory files passed in.
The problem is that if there are multiple inventory files being used, then the add-topo and remove-topo commands will only pass in the inventory file for the VMs, and not the DUTs. This results in `hostvars` not containing the DUT's IP address, which results in a failure for the `config_db.json` generation.
Fix this by also passing in the DUT's inventory file for add-topo and remove-topo.
Tested it by adding and removing ceos and vsonic neighbors when there are multiple inventory files used.
> Fix deploying vsonic neighbors with multiple inventory files

- tests/dhcp_relay/test_dhcp_relay.py
Summary: This is a cherry-pick of PR https://github.com/sonic-net/sonic-mgmt/pull/7656 and https://github.com/sonic-net/sonic-mgmt/pull/8655
Add dhcpmon test
To check dhcpmon counter in syslog is as expected
Run dhcpmon in debug mode and use loganalyzer to check expected counter in syslog
Ran test on kvm
> [202205][dhcp_relay] Add dhcpmon test to check for aggregated counter

- ansible/roles/test/files/tools/loganalyzer/loganalyzer.py
- tests/common/plugins/loganalyzer/loganalyzer.py
- tests/platform_tests/conftest.py
Summary:
**This PR is to backport PR  #8940 into `202205` branch.**
This PR is to fix flaky test case `test_warm_reboot_mac_jump`.
The test failed because the MAC jump log was not found in sairedis log. The error message is
```
['MAC jumping not detected when expected for address: 00-06-07-08-09-0A'])]
```
However, the log we are looking for is in sairedis log. Because it was dropped by LogAnalyzer because long log message (length > 1000) is skipped by default.
```
if in_analysis_range:
if not check_marker and len(rev_line) > 1000:
continue
if self.line_is_expected(rev_line, expect_messages_regex):
expected_lines.append(rev_line)
elif self.line_matches(rev_line, match_messages_regex, ignore_messages_regex):
matching_lines.append(rev_line)
``` …
> [202205] Enhance LogAnalyzer to support parsing long log lines

- tests/platform_tests/test_reload_config.py
This is cherry-pick (missed change) of https://github.com/sonic-net/sonic-mgmt/pull/7953 to 202205 
Summary:
> [cherry-pick PR8843 (master PR7953)] missing change for 202205 branch

- ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Many cases failed due to following ERR syslog with the latest master image, ignore them for now until the test cases are fixed.
`Jul  3 05:58:36.447220 str2-7260cx3-acs-9 ERR syncd#syncd: message repeated 119 times: [ [none] SAI_API_UNSPECIFIED:sai_bulk_object_get_stats:671 Unsupported object type type 1]`
Workitem: https://msazure.visualstudio.com/One/_workitems/edit/24444744/
Ignore the error message of SAI_API_UNSPECIFIED:sai_bulk_object_get_stats:671 Unsupported object type*
Add the regular expression of this error message into loganalyzer_common_ignore.txt
Run the test locally.
> Ignore err log SAI_API_UNSPECIFIED:sai_bulk_object_get_stats

- tests/span/conftest.py
In the span test, it will choose some physical port from the vlan, when there are more than one vlan, in original logic, it will always choose port from the first vlan member, but we can not guarantee there are more than 3 physical port in the first vlan member. change the logic to choose the physical port from the vlan which has more than 3 physical ports.
Change-Id: I587d716b7381b3cf9d44b09acc0120f078b260ee
Summary: Fix https://github.com/sonic-net/sonic-mgmt/issues/8795
Fixes # (issue) IndexError: list index out of range in the test_port_mirroring
When run the test_port_mirroring, sometimes we will get the following issue.
The root cause for the issue is that there maybe more than one vlan Vlan101 and Vlan102, in the current logic it will choose 3 physical ports from the vlan member, …
> [span]Fix span test issue: IndexError: list index out of range in the test_port_mirroring

- tests/saitests/py3/sai_qos_tests.py
Trivial test fix. .format() is intended for the entire string which was broken up by a line separator. This problem is specific to 202205 as code in master is already fixed by  miscellaneous style updates.
Summary:
- [X ] Bug fix
> [202205] Fix typo in string format

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
test `override_config_table/test_override_config_table.py` creates empty/partial/full configuration and tries to overwrite config_db.json partially or totally, on duthost, for multi-asic platforms.
There is coming change from ndm that golden config db is going to change, so that host config and asic configs are put in the same file, distinguished by keys `localhost` and `asic0` `asic1` ... and there comes PR https://github.com/sonic-net/sonic-utilities/pull/2825 to accommodate new ndm change.
with this new change, especially with https://github.com/sonic-net/sonic-utilities/pull/2825, this `override_config_table/test_override_config_table.py` no longer works for multi-asic scenarios, because test is providing incorrect format of `golden_config_db.json`. e.g. `localhost` and `asicx` is …
> [chassis] [multi-asic] skip override_config_table test for multi-asic platforms

- tests/acl/templates/acltb_test_rules.j2
- tests/acl/templates/acltb_test_rules_part_2.j2
- tests/acl/test_acl.py
Summary:
Previous test ip (192.168.0.251, 192.168.0.252, 192.168.0.253) for m0_vlan scenario is in Vlan2000 in m0-2vlan topo, but the verified vlan is Vlan1000, which would cause test failure.
Modify test ips to 192.168.0.121, 192.168.0.122, 192.168.0.123 for m0_vlan scenario, to make sure they are in Vlan1000.
Run test in m0, m0-2vlan, mx topo, all passed.
> [acl][m0] Fix test_acl failed in m0-2vlan

- tests/vlan/test_host_vlan.py
In PR (https://github.com/sonic-net/sonic-mgmt/pull/8728), we delete the vlan mac running config in the teardown period. But in dualtor scenario, it already has mac address in original config. So in this PR, when the testbed is dualtor, we skip deleting the vlan mac running config in the teardown period.
Summary:
In PR (https://github.com/sonic-net/sonic-mgmt/pull/8728), we delete the vlan mac running config in the teardown period. But in dualtor scenario, it already has mac address in original config. So in this PR, when the testbed is dualtor, we skip deleting the vlan mac running config in the teardown period.
Skip deleting the vlan mac running config in the teardown period when the testbed is dualtor.
```
08:25:47 conftest.core_dump_and_config_check      L2131 INFO   | …
```
> Fit dualtor scenario when deleting config `VLAN|mac` in module `vlan/test_host_vlan.py`

- tests/saitests/sai_qos_tests.py
Summary:
observed type error:
```
ERROR: sai_qos_tests.PFCXonTest
File "saitests/sai_qos_tests.py", line 1722, in runTest
1)[0][0]
File "saitests/sai_qos_tests.py", line 379, in get_multiple_flows
pkt = simple_tcp_packet(**pkt_args)
File "/usr/lib/python2.7/dist-packages/ptf/testutils.py", line 239, in simple_tcp_packet
with_tcp_chksum = with_tcp_chksum)
File "/usr/lib/python2.7/dist-packages/ptf/testutils.py", line 153, in simple_tcp_packet_ext_taglist
pkt = pkt/("".join([chr(x % 256) for x in xrange(pktlen - len(pkt))]))
File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 290, in __len__
return len(self.__str__())
File …
```
> [qos][202012] fix type error in get_multiple_flows

- ansible/setup-management-network.sh
Summary:
Lab server could have management IP configured on bridge "br1". If run this script on such lab server, the original mgmt IP could be changed and connectivity to the lab server may be lost.
This change updated the setup-management-network.sh script to skip configuring mgmt IP for br1 bridge if it already exists.
Tested on local server.
> Enhance setup-management-network.sh to avoid break lab server connectivity

- ansible/roles/test/files/ptftests/IP_decap_test.py
Summary:
The IP_decap_test.py PTF script needs to determine destination IPs to cover based on fib IP range length. For the fib class, ip range length is a function, not an attribute.
This change fixed the issue of calling `ip_range.length` to `ip_range.length()`.
Without this fix, for ip ranges with length 1 or 2, they are all considered as ip range with length longer than 2. Then the first, last and a random IP within the range are tested. Unnecessarily tested destination IPs repeatedly for such IP ranges.
Test run decap/test_decap.py
> Fib IP range length is function instead of attribute

- ansible/devutil/devices/ansible_hosts.py
- ansible/devutil/devices/factory.py
Summary:
The localhost ansible host object should be created with or without supplying ansible inventory file.
This change enhanced the libraries to support init a localhost ansible host object without supplying ansible inventory file.
```
>>> from devutil.devices import factory
>>> localhost = factory.init_localhost()
[WARNING]: No inventory was parsed, only implicit localhost is available
>>> localhost
<AnsibleHost localhost in None>
>>> localhost.command("date")
Thursday 20 July 2023  02:45:18 +0000 (0:00:30.547)       0:00:30.578 ********* 
{'hostname': 'localhost', 'reachable': True, 'failed': False, 'cmd': ['date'], 'stdout': 'Thu Jul 20 02:45:18 UTC 2023', 'stderr': '', 'rc': 0, 'start': '2023-07-20 02:45:18.195654', 'end': '2023-07-20 02:45:18.197592', 'delta': …
```
> Support init localhost ansible host object without supplying inventory

- tests/cacl/test_cacl_application.py
…tion
Summary:
test_cacl_application failed on dualtor testbed due to TypeError: 'list' object is not an iterator.
That's because the type of `ip_ntwrk.hosts()` is list for LOOPBACK_INTERFACE ip address FC00:1::38/128, can't be called for next() function.
For VLAN_INTERFACE, it has some non-ip address key for dualtor testbed, such as grat_arp or proxy_arp, if call `ipaddress.ip_network` for them, it will throw ValueError exception, but in existing code, it executes pass next. At this time, the iface_table_name == "VLAN_INTERFACE", the code will execute next() function for previous ip_ntwrk which is got from LOOPBACK_INTERFACE. According to previous saying, the TypeError: 'list' object is not an iterator will happen here.
```
"VLAN_INTERFACE": {
"Vlan1000": {
"grat_arp": …
```
> Fix TypeError: 'list' object is not an iterator for test_cacl_application

- tests/run_tests.sh
Summary:
It is decided that 202205 branch will NOT support Python3. So remove the python3 support in run_tests.sh
It is decided that 202205 branch will NOT support Python3. So remove the python3 support in run_tests.sh
Modify run_tests.sh
Can run test_bgp_facts.py with physical testbed.
> Remove Python3 support in run_tests.sh in 202205 branch

- tests/qos/test_tunnel_qos_remap.py
Summary:
observed error in test_pfc_pause_extra_lossless_active:
```
20/07/2023 15:12:12 test_tunnel_qos_remap.pfc_pause_test     L0338 INFO   | exception (<class 'TypeError'>, TypeError("object of type 'int' has no len()"), <traceback object at 0x7fe6f02cb940>)
```
RCA:
the last parameter of pfc_pause_test() requrie list type, but, in some corner case,, "dualtor_meta['target_server_port']" is not list. so cause this error:
```
if pfc_pause_test(storm_handler, peer_info, prio, ptfadapter, rand_selected_dut,
dualtor_meta['selected_port'], queue, tunnel_pkt.exp_pkt, src_port, exp_pkt,
dualtor_meta['target_server_port']):
```
solution:
make sure the last parameter of pfc_pause_test() is list type.
> fix occasional type error in test_pfc_pause_extra_lossless_active

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Cherry pick of https://github.com/sonic-net/sonic-mgmt/pull/8696 to resolve conflicts
> [202205 chassis] skip qos test on other dnx linecards platforms

- ansible/roles/test/files/ptftests/advanced-reboot.py
- tests/common/fixtures/advanced_reboot.py
- tests/platform_tests/test_advanced_reboot.py
Summary: This is a cherry-pick of PR https://github.com/sonic-net/sonic-mgmt/pull/7532
Fixed going down part of the warmboot test on dualtor. Capture sent server->t1 traffic on both DUT in dualtor scenario and listen for icmp on active ports
Packet drops are seen during dual tor tests due to not capturing DUT -> T1 packets.
ICMP ping packets are dropped on standby ToR
Added standby ToR portchannel ports to portchannel port list.
Fixed ping dut packets dropped on standby ToR by sending icmp ping to active ports only
Run warm-reboot test on standby ToR and confirm server->T1 and all ping DUT are received.
> [202205][advanced-reboot] Listen on peer dut during dualtor server->t1 traffic and fix loopback ping

- tests/saitests/py3/sai_qos_tests.py
Summary:
double commit PR https://github.com/sonic-net/sonic-mgmt/pull/9024
(there is no get_multiple_flows relevant code, so directly double commit to 202205 branch)
observed type error:
```
ERROR: sai_qos_tests.PFCXonTest
File "saitests/sai_qos_tests.py", line 1722, in runTest
1)[0][0]
File "saitests/sai_qos_tests.py", line 379, in get_multiple_flows
pkt = simple_tcp_packet(**pkt_args)
File "/usr/lib/python2.7/dist-packages/ptf/testutils.py", line 239, in simple_tcp_packet
with_tcp_chksum = with_tcp_chksum)
File "/usr/lib/python2.7/dist-packages/ptf/testutils.py", line 153, in simple_tcp_packet_ext_taglist
pkt = pkt/("".join([chr(x % 256) for x in xrange(pktlen - …
```
> [qos][202205] fix type error in get_multiple_flows

- ansible/roles/test/files/ptftests/advanced-reboot.py
Cherry pick of https://github.com/sonic-net/sonic-mgmt/pull/8089
To fix a rare issue when control plane is detected to be down before reboot is issued. This happens if any out of 10 ping packets are dropped (cause unknown). When this happens, the logic proceeds to wait (join) for sender and sniffer threads to complete. Since the device never really rebooted, there is a chance sender and sniffer threads are not initialized and started.
Additonally, removed the unused method send_and_sniff
Fix the issue by:
Initializing sender and sniffer threads in init.
Before joining the IO threads wait for them to start -- keep checking isAlive()
Tested on physical testbed and fix works.
Summary:
> [202205 cherry-pick][advanced-reboot] Check IO threads have started before joining (#8089)

- ansible/roles/test/files/ptftests/advanced-reboot.py
To fix a rare issue when control plane is detected to be down before reboot is issued. This happens if any out of 10 ping packets are dropped (cause unknown). When this happens, the logic proceeds to wait (join) for sender and sniffer threads to complete. Since the device never really rebooted, there is a chance sender and sniffer threads are not initialized and started.
Additonally, removed the unused method send_and_sniff
Fix the issue by:
Initializing sender and sniffer threads in init.
Before joining the IO threads wait for them to start -- keep checking isAlive()
Tested on physical testbed and fix works.
Summary:
> [202012 cherry-pick][advanced-reboot] Check IO threads have started before joining (#8089)

- tests/fib/test_fib.py
Summary:
Manually cherry-pick and resolve conflict of this PR: https://github.com/sonic-net/sonic-mgmt/pull/8960
test_fib will randomly fail in marvell asic. To fix it.
It failed because "240.0.0.0/24" is not excluded in test ip ranges. This PR [#7030](https://github.com/sonic-net/sonic-mgmt/pull/7030) has added it but not let it take effect due to missing asic_type in the parameter.
Run tests.
> [202012][fib] Fix test_fib failed in Nokia 7215 (#8960)

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Skip below testcases on M0/Mx topology:
* generic_config_updater/test_pfcwd_status.py
* platform_tests/counterpoll/test_counterpoll_watermark.py::test_counterpoll_queue_watermark_pg_drop
Skip below testcases on M0/Mx topology:
* generic_config_updater/test_pfcwd_status.py
* platform_tests/counterpoll/test_counterpoll_watermark.py::test_counterpoll_queue_watermark_pg_drop
Update conditional marks.
Verified on physical M0 testbed.
> Skip unsupported testcases on M0/Mx topology

- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Skip condition for 7215 and 1031 failed in this case due to https://github.com/sonic-net/sonic-mgmt/pull/8646
Modify skip condition.
Run tests.
> [platform][reboot] Fix test_power_off_reboot failed in 7215

- ansible/roles/vm_set/library/vm_topology.py
Summary:
New sonic-mgmt-docker will come with Python3 as default.
testbed-cli.sh should modify to be compatible with both Python2 and Python3.
testbed-cli.sh should modify to be compatible with both Python2 and Python3.
1. Use six package to deal with str/unicode error: 'str' object has no attribute 'decode'
2. Work around with a kernel issue: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1811241.html
With physical testbed, we can remove-topo, add-topo and deploy-mg.
> Modify testbed-cli.sh related vm_topology.py to be compatible with both Python2/3

- tests/vlan/test_host_vlan.py
Fix cherry pick conflict of PR #9025
Summary:
Fix cherry pick conflict of PR #9025
> [cherry pick] #9025 Fit dualtor scenario when deleting config VLAN|mac in module vlan/test_host_vlan.py into 202012. 

- tests/vlan/test_host_vlan.py
Fix cherry pick conflict of PR #9025 
Summary:
Fix cherry pick conflict of PR #9025
> [cherry pick] #9025 Fit dualtor scenario when deleting config VLAN|mac in module vlan/test_host_vlan.py into 202205. 

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
bpg suppress fib is a new feature support since 202305, need to skip test before this release.
skip the test in conditional mark 
PR
> [conditional mark] skip test_bgp_suppress_fib before release 202305

- tests/snmp/memory.py
- tests/snmp/test_snmp_memory.py
Summary:
This PR is to stabilize test case `test_snmp_memory_load`.
The test case run a python script `memory,py` on the DUT to allocate large amount of memory, and then retrieve the free memory by snmp and parsing `/proc/meminfo` correspondingly. And then compare the value retrieved from SNMP and CLI.
It's flaky because
1. The commands are running in 3 separated Ansible calls, which means there is a time gap (around 3 seconds) between each call. There can be memory usage change between each call.
2. The `memory.py` script is running to fast. We need to consume the memory gradually.
This PR addressed the issue with below changes
1. Run the 3 command in a single Ansible call.
2. Improve the `memory.py` script to allocate memory in a relatively slow pace.
This PR is to stabilize test case …
> Stabilize snmp memory load test

- tests/restapi/helper.py
Summary:
This PR is to increase the wait time for restapi service startup.
On SN2700 platform, the restart of restapi service costs 26 seconds. In this PR, I increase the wait time to 40 seconds to ensure the service is running.
This PR is to increase the wait time for restapi service startup.
Update `RESTAPI_SERVER_START_WAIT_TIME` from `15` to `40`.
The change is verified on SN2700 testbed. Now the test case is consistently passing.
No.
> Increase wait time for restapi service startup

- ansible/roles/test/files/ptftests/advanced-reboot.py
Summary: Enhance IO: start traffic when teamd goes down and run until FINALIZER is active
The test always sends pre-defined number of packets.
If the warm reboot shutdown or warm recovery takes more time then the IO stops before warm recovery finishes.
This leads to cases when test fails to evaluate dataplane impact completely.
The test could lead to false negatives w/ 0s downtime when in fact there are drops.
This issue is highlighted recently when lag_keepalive script was added to warm shutdown path. Keepalive script added sleep of 60s and running IO test during this duration leads to IO finishing up much earlier.
Start the IO when teamd goes down.
Run the IO continuously until FINALIZER service remains active.
Tested on KVM and physical device.
```
2023-07-14 18:38:52 : …
```
> [advanced-reboot] Enhance IO: start traffic when teamd goes down and run until FINALIZER is active

- tests/common/plugins/sanity_check/checks.py
Summary: Skip check_bgp_router_id on T2 devices
In chassis the a different Loopback ip is used as bgp router_id
Skip check_bgp_router_id on t2 topo
> Skip check_bgp_router_id on T2 devices

- ansible/roles/fanout/tasks/sonic/fanout_sonic_202205.yml
Summary:
In issue https://github.com/sonic-net/sonic-buildimage/issues/15649, we found container `swss` crash after feature teamd is disabled. Currently, the only way to mitigate this issue is delete the `teamd` container before loading new config on SONiC 202205 fanout switches.
In this PR, I add some steps to check if container `teamd` exists and remove it before loading new config_db.json.
In issue https://github.com/sonic-net/sonic-buildimage/issues/15649, we found container `swss` crash after feature teamd is disabled. Currently, the only way to mitigate this issue is delete the `teamd` container before loading new config on SONiC 202205 fanout switches.
Add some steps to check if container `teamd` exists and remove it before loading new config_db.json.
Verified on Nokia-7215 fanout …
> [Fanout] Remove `teamd` container before loading new config

- tests/macsec/macsec_helper.py
Summary:
Fix issue: https://github.com/sonic-net/sonic-mgmt/issues/8497
Change the type of recent_packets to ring buffer for reducing the recent failure packets
Check Azp.
> Fix issue 8497: PTF test collected a huge number of unexpected pkt when test failed

- tests/ipfwd/test_nhop_group.py
Splitting platform specific condition check to pass test_nhop_group.py test in Marvell(Innovium)
There was a common code used for Cisco and Marvell(Innovium ) but same is no longer valid as Cisco update it. Hence, splitting the condition check and reverting the old code used to pass test_nhop_group.py in Marvell(Innovium) platform.
Summary:
Splitting platform specific condition check to pass test_nhop_group.py test in Marvell(Innovium)
> Splitting platform specific condition check to pass test_nhop_group.py test in Marvell(Innovium)

- tests/dut_console/test_escape_character.py
Summary:
- This PR fixes '_test_escape_character_' test under _dut_console_ test suite.
- Currently test runs the respective '_ping_' command on the test bed server instead of running it on the **console** of the respective DUT.
- And also pexpect.spawn creates child process for ping under sonic-mgmt docker where the test is running instead of the DUT console.
- Fix '_test_escape_character_' test under _dut_console_ test suite, by calling '_duthost_console_' fixture. 
- Currently test runs on test bed server and executes '_ping_' command which is not the expected behavior.
- Call '_duthost_console_' fixture of conftest.py from the test case.
- Send 'ping' command and escape character directly on the DUT console instead of creating child process.
- Ran the dut_console test …
> Call duthost_console fixture for test_escape_character test case

- tests/platform_tests/test_platform_info.py
This PR fixes 3 issues:
1. https://github.com/sonic-net/sonic-mgmt/pull/8670 intends to get good PSU numbers not rely on output format. Because devices have different output format depending on image version.
e.g. 
image <= 201911
```
PSU    Status
-----  --------
PSU 1  OK
PSU 2  OK
```
image >201911:
```
PSU    Model    Serial                          Voltage (V)    Current (A)    Power (W)  Status    LED
-----  -------  ----------------------------  -------------  -------------  -----------  --------  -----
PSU 1  xx          xx                               11.93           0.53         xxx  OK        green
PSU 2  xx         xx                                 11.93           0.49         xxx  NOT OK        green
```
`fields`: split output of `sudo psuutil status` by whitespaces, if …
> [chassis] [test_platform_info.py] accommodate PSU 'NOT PRESENT' case

- tests/voq/test_voq_ipfwd.py
When the minigraph/Config has T3 Peer is a "Regional Hub" type in DEVICE_NEIGHBOR_METADATA and if we select that T3 peer loopback IP for end to end ping -- the ping from T1 --> T3 loopback ip fails. This is because the the routemaps for that "Regional Hub" type filter the loopback routes advertised to SONiC T2.
Summary:
Fixes #9021
Fix was to use T3 peer devices of this SONiC T2 which is of other types like AZNGHub. So filter the ethernet/portchannel interfaces based on which peer type it is connected to.
Ran the above tests which were failing earlier and it passes now.
```
collected 20 items …
```
> Fix to use non RegionalHub T3 peers when selecting port. 

- ansible/roles/test/templates/arp_responder.conf.j2
- tests/scripts/arp_responder.py
- tests/templates/arp_responder.conf.j2
This allows the use of scapy 2.5.0 and also fixes an issue where ARP packets are not being sent out fast enough/in time, causing control plane ping packets to fail to respond.
This depends on the PTF container changes done in sonic-net/sonic-buildimage#15573.
Summary:
Ran `route/test_static_route.py` so that this script gets tested.
> Convert arp_responder.py script to python 3

- tests/bgp/test_traffic_shift_sup.py
In test case tests/bgp/test_traffic_shift_sup.py, the module def run_cmd_on_sup(self, cmd): 
it spaws ssh connection to supervisor and expects password prompt but password is not send
instead the cmd is send which leads to error. In order to fix the test I am adding code to send
dutpass and expect prompt after successful login.
Summary:
- [x ] Bug fix
- [x ] 202205
In test case tests/bgp/test_traffic_shift_sup.py, the module def run_cmd_on_sup(self, cmd): 
it spaws ssh connection to supervisor and expects password prompt but password is not send
instead the cmd is send which leads to error. In order to fix the test I am adding code to send
dutpass and expect prompt after successful login.
added lines:
client.sendline(self.dutpass)
client.expect("admin*")
to complete ssh …
> fix tests/bgp/test_traffic_shift_sup.py failure

- tests/pc/test_retry_count.py
Summary:
Fixes test_retry_count.py PR test failure
test_retry_count.py PR test failure with following error:
File "/var/src/sonic-mgmt/tests/pc/test_retry_count.py", line 81, in higher_retry_count_on_peers
featureCheckResult = nbrhosts[nbrhosts.keys()[0]]['host'].shell(
TypeError: 'dict_keys' object is not subscriptable
In Python3, dict cannot be used with [] anymore.
Wrap with list like: list(nbrhosts.keys())[0]
Run with physical testbed
> Fix test_retry_count.py PR test failure - 'dict_keys' object is not subscriptable

- tests/common/fixtures/ptfhost_utils.py
Summary:
Disable running `icmp_responder` at session level.
The reason is that enabling `icmp_responder` at the session level could cause some T0 testcase failures as the ICMP replies pollute the FDB table.
For example:
Port `Ethernet4`, mux server IP `192.168.0.2`, connected to ptf port `eth1` that has mac `A`.
Port `Ethernet40`, connected to ptf port `eth10` that has mac `B`.
Some T0 testcases configure `192.168.0.2` IP on ptf port `eth10`, DUTs will learn the arp as `192.168.0.2` with mac `B` on port `Ethernet40`. After linkmgrd learns the arp, it will send heartbeats to `192.168.0.2` with dest mac as `B` on `Ethernet4`. As the `icmp_responder` is running, DUT will receive heartbeat replies with source IP `192.168.0.2` and source mac `B` on `Ethernet4`.
So DUT will …
> [dualtor] Disable running `icmp_responder` at session-level

- tests/dhcp_relay/test_dhcp_relay.py
Summary:
Add dualtor dhcpmon test, check on standby ToR has no dhcp packet count
Make loganalyzer check dhcp count dynamic to number of ip helpers configured on device
Enable on dualtor and check dhcpmon syslog on standby ToR
Modify loganalyzer regex
On single ToR and dualtor lab device
> Add dualtor standby drop test and check dhcpmon count based on number of dhcp servers configured

- tests/voq/test_voq_nbr.py
Summary:
- For test case '_test_neighbor_clear_one_', one of the untouched neighbor states went to '_stale_' during neighbor verification which happens around ~4 mins after neighbor flush.
- _check_nbr_state_ by default is set to true, which is not required for checking the _other_ neighbor presence as part of this test.
- Neighbor state check not required during these untouched neighbor presence check for this test. 
- _check_nbr_state_ by default is set to **true**, which is not required for this test.
- And also for bigger DUTs like (400G T2 max/100G T2 max), this check happens around ~4 mins after neighbor flush.
- Pass '_check_nbr_state_' as false during the other neighbors' check for this test.
https://github.com/sonic-net/sonic-mgmt/blob/2fd298b7ce58785de55e4eae94686 …
> [voq][neighbors_clear_one] Ignore nbr-state check for other neighbors

- tests/telemetry/telemetry_utils.py
Summary:
Fixes # (issue)[17449029](https://msazure.visualstudio.com/One/_workitems/edit/17449029)
Add reset failed to setup telemetry. Sometimes we will see during setup telemetry that we are unable to restart telemetry container due to "telemetry.service: Start request repeated too quickly" and "telemetry.service: Failed with result 'start-limit-hit'".
This leads to telemetry container not being up for telemetry tests:
Jul  8 09:14:41.829276 str-a7060cx-acs-10 ERR systemd[1]: Failed to start Telemetry container.
Add reset-failed to setup so that we don't run into start-limit-hit due to many restarts to telemetry that has happened before, for example in test_memory_checker
Pipeline
> Add reset-failed to setup telemetry in test_telemetry

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
bfd/test_bfd.py is skipped for 8101,
need to enable it.
update test_bfd's skip rule for 8101
> enable bfd test for 8101

- tests/show_techsupport/test_auto_techsupport.py
In module `show_techsupport/test_auto_techsupport.py`, it will randomly select a docker and update the docker settings using command `sudo config auto-techsupport-feature`. It will delete the settings and add again.  However, in the tear down period, when adding, it loses the feature `--available-mem-threshold`, which will cause inconsistent between previous running config and current running config, and cause unnecessary config reload. 
Summary:
In module `show_techsupport/test_auto_techsupport.py`, it will randomly select a docker and update the docker settings using command `sudo config auto-techsupport-feature`. It will delete the settings and add again.  However, in the tear down period, when adding, it loses the feature `--available-mem-threshold`, which will cause …
> Recover docker's available mem threshold after module `show_techsupport/test_auto_techsupport.py` running. 

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
8101 only support bfd_multihop,
so skip bfd.test_bfd.test_bfd_basic and bfd.test_bfd.test_bfd_scale
skip bfd.test_bfd.test_bfd_basic and bfd.test_bfd.test_bfd_scale for 8101 platform
> x86_64-8101_32fh_o-r0 only support bfd_multihop

- tests/platform_tests/conftest.py
Summary:
Tests failing on newly addded platforms where logs are moved to tmpfs.
Related PR: https://github.com/sonic-net/sonic-buildimage/pull/15077
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/15895
This change updates the check from hwsku match to platform match
> [advanced-reboot] Handle logs on tmpfs for all new platforms

- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Manually cherry-pick and resolve conflicts of this PR: https://github.com/sonic-net/sonic-mgmt/pull/9085
Skip condition for 7215 and 1031 failed in this case due to #8646
Modify skip condition.
Run tests.
> [202205][platform][reboot] Fix test_power_off_reboot failed in 7215 (#9085)

- tests/platform_tests/test_idle_driver.py
Currently some Intel CPU tends to have problem when CPU enters idle state. We expect Intel CPUs to not have an active idle driver and idle states.
Summary:
Make sure Intel CPU m0 won't enter idle states.
Check active idle driver (should be none) and available idle states (should be none)
Run test on device
Intel m0 only
> [platform_tests] add test to make sure cpuidle is off for m0 and mx

- ansible/roles/test/files/ptftests/advanced-reboot.py
Summary: Fix issues where error 141 (no PIPE) causes failure to backup logs needed by log_analyzer
In the device where logs are in tmpfs, a backup is made for log_analyzer to work after reboot.
However, there have been many cases when one or more backup files are empty or not created.
Based on current RCA this happens when reboot CLI is executed from test and then SSH command times out.
When command execution ends, but reboot is still in progress in the device, any writes to stdout / etderr fails as there is no reader.
To fix no reader issue, run the reboot CLI w/ nohup and redirect the output to a file.
Tested on a physical device in lab.
> [advanced-reboot] Use nohup when executing reboot CLI to prevent PIPE errors

- ansible/roles/test/files/ptftests/pfc_wd.py
- tests/pfcwd/conftest.py
- tests/pfcwd/test_pfcwd_function.py
Summary:
This PR is to improve test cases in [test_pfcwd_function.py](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:pfcwd_func_test_dualtor?expand=1#diff-bb4f2b9da0ca66c236beedfb7cc790bf6294f5bb8722ca0038e49d755c8f9c33) to support dualtor testbed.
The improvements include
1. Toggle mux cable to the randomly selected ToR before running test
2. Use vlan MAC (00:aa:bb:cc:dd:ee) if the ingress port is a vlan member on dualtor testbed
3. Pause `icmp_responder` if the test is running on dualtor testbed
4. Update the key name of `BUFFER_PG` table. Only use `2-6` if the port has 4 lossless queues.
The PR is to improve test cases in test_pfcwd_function.py to support dualtor testbed.
1. Toggle mux cable to the randomly selected ToR before running test
2. Use vlan MAC …
> Improve pfcwd function test to support dualtor testbed

- tests/telemetry/conftest.py
- tests/telemetry/telemetry_utils.py
In module telemetry/test_telemetry.py, errors may happen in the setup period of fixture setup_streaming_telemetry, and the the recover function can be not be executed in the teardown period. This will change the running config, and cause unnecessary reload. In this PR, when the errors happen in the setup period, we will recover the telemetry config immediately.
Summary:
In module telemetry/test_telemetry.py, errors may happen in the setup period of fixture setup_streaming_telemetry, and the the recover function can be not be executed in the teardown period. This will change the running config, and cause unnecessary reload. In this PR, when the errors happen in the setup period, we will recover the telemetry config immediately.
When the errors happen in the setup period, we …
> Recover telemetry settings when error happens in module `telemetry/test_telemetry.py`.

- .azure-pipelines/get_dut_version.py
- .azure-pipelines/upgrade_image.py
- ansible/TestbedProcessing.py
- ansible/devutils
- ansible/files/creategraph.py
- ansible/linkstate/testbed_inv.py
- ansible/recover_server.py
- ansible/restart_nightly_ptf.py
- ansible/upgrade_sonic.py
Summary:
This is a part of Python3 migration. The incoming new sonic-mgmt-docker will set Python3 as default. Old branch will use Python2 explicitly.
This is a part of Python3 migration. The incoming new sonic-mgmt-docker will set Python3 as default. Old branch will use Python2 explicitly.
In tool scripts, add head: #!/usr/bin/env python2
In any caller of tool scripts, use "./" to call the scripts.
> [202012] Change tool scripts to use Python2 explicitly

- ansible/devutil/devices/ansible_hosts.py
Summary:
PR #8035 was missed while backporting the devutils/devices/ansible_hosts.py changes to 202205 branch.
This PR is to backport the missed changes.
Added missed importing and some other code missed in backporting.
> [cherry-pick 8035] Check existence of inventory files

- tests/vxlan/test_vxlan_ecmp.py
The existing vxlan_ecmp tests are composed of multiple testlets and some of them add routes to the DUT without cleanup.
This results in around 10-15 routes with active BFD sessions. Since PTF is not able to support that many bfd sessions, this results in some BFD sessions going down. This causes the later running tests such as **test_vxlan_route2_shared_nh** and **test_vxlan_route2_shared_different_nh** to fail as some of the routes become inactive.
This fix does a cleanup of the additional routes added during the running of the tests in classes **Test_VxLAN_ecmp_create & Test_VxLAN_route_tests** when all tests are run.
Summary:
ADO :24446018
> [testfix] test_vxlan_ecmp cleanup of routes after test runs.

- tests/autorestart/test_container_autorestart.py
Summary:
Manually cherry-pick of this PR: https://github.com/sonic-net/sonic-mgmt/pull/8968
Fix test_container_autorestart failed for mx in dhcp_relay container. In mx topo, dhcp_relay container has two critical process group: dhcp-server with dnsmasq and dhcp-relay with dhcp6relay. In this test, we will kill process in critical group to see whether the container can restart successfully. In mx scenario, it will kill dhcp6relay and cause dhcp_relay container restart. And then the dhcp_relay container restarts but the dnsmasq service is too late to start, which cause failed at check dhcp-server critical group.
Add wait_until before check, to ensure required process can start.
Run test in M0/MX/T0/T1 topos, all passed.
> [202205][autorestart][mx] Fix test_container_autorestart failed in mx (#8968)

- tests/common/fixtures/advanced_reboot.py
- tests/common/fixtures/duthost_utils.py
- tests/common/plugins/sanity_check/checks.py
This is a cherry-pick PR for https://github.com/sonic-net/sonic-mgmt/pull/8576 and https://github.com/sonic-net/sonic-mgmt/pull/9090
Summary: Skip check_bgp_router_id on T2 devices
An issue was found that T0 did not announce Loopback to T1, this check is to bridge the test gap to ensure bgp router identifier matches Loopback0 IP.
Added in sanity_check to match bgp router id and loopback0 ip
Ran a advanced_reboot manually and checked expected log: BGP router identifier: <loopback0 ip>
https://elastictest.org/scheduler/testplan/649c780c75768730ce0de9f3
> [202012] Check if BGP has Loopback0 IP as its router ID (#8576)

- ansible/roles/test/files/ptftests/pfc_wd.py
- tests/pfcwd/conftest.py
- tests/pfcwd/test_pfcwd_function.py
Summary:
The PR is to backport PR #9158 into `202205` branch.
This PR is to improve test cases in [test_pfcwd_function.py](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:pfcwd_func_test_dualtor?expand=1#diff-bb4f2b9da0ca66c236beedfb7cc790bf6294f5bb8722ca0038e49d755c8f9c33) to support dualtor testbed.
The improvements include
1. Toggle mux cable to the randomly selected ToR before running test
2. Use vlan MAC (00:aa:bb:cc:dd:ee) if the ingress port is a vlan member on dualtor testbed
3. Pause `icmp_responder` if the test is running on dualtor testbed
4. Update the key name of `BUFFER_PG` table. Only use `2-6` if the port has 4 lossless queues.
The PR is to improve test cases in test_pfcwd_function.py to support dualtor testbed.
1. Toggle mux cable to the randomly …
> [202205] Improve pfcwd function to support dualtor testbed

- tests/qos/files/qos_params.gb.yaml
This PR is to replace 202205 PR https://github.com/sonic-net/sonic-mgmt/pull/8629 for wm_q_wm_all_ports entries and wm_q_shared_lossless update, and refine some entries to align with master PR https://github.com/sonic-net/sonic-mgmt/pull/9036.
1, Adjusted the order of some entries to align with master branch.
2, Added wm_q_wm_all_ports entries for gb long-link.
Packet size 6144 is used for long-link test, 1 packet occupies 1 hbm block. Queue watermark margin is updated since new voq_hbm_threshold, congestion level 11 watermark is 1x1024x6144, level 12 watermark is 20x1024x6144, so set the pkts_num_margin to 19*1024=19456.
pkt_count 855 is for multi-asic scenario, it is the packet number to trigger pfc in 200G backplane port. This case tests queue watermark in egress asic.
3, Updated …
> Align with master branch PR, update watermark entries

- tests/common/reboot.py
- tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
- tests/platform_tests/mellanox/test_reboot_cause.py
Summary:
PR has to be merged after https://github.com/sonic-net/sonic-buildimage/pull/15793
Changes in https://github.com/sonic-net/sonic-buildimage/pull/15793
Remove parts relates to cpu reboot cause
Run TC, TC passed
Nvidia (Mellanox)
> [Nvidia][reboot_cause] Remove cpu reset cause from test

- tests/snmp/test_snmp_memory.py
Summary:
https://github.com/sonic-net/sonic-mgmt/pull/9074 modified test_snmp_memory to make it stable.
This change executes commands to get snmp memory and memory from /proc/meminfo sequentially from duthost.
one of the commands is to use snmpget, which fails because snmpget is available only inside snmp docker.
Modify testcase to run docker exec snmp snmpget instead of snmpget
Verificed on testbed.
> [snmp] Fix snmpget command to run from duthost

- .azure-pipelines/get_dut_version.py
In PR #8917 , it re-organizes files under ansible/devutil, and change the path of function `init_localhost` and `init_testbed_sonichosts`. But it didn't modify the import path in script `get_dut_version.py`, which will cause import error. 
Summary:
In PR #8917 , it re-organizes files under ansible/devutil, and change the path of function `init_localhost` and `init_testbed_sonichosts`. But it didn't modify the import path in script `get_dut_version.py`, which will cause import error. 
Modify import path in script `get_dut_version.py`.
> Modify import path in script `get_dut_version.py`. 

- tests/dut_console/test_escape_character.py
**Cherry-Pick PR** for 202205 from master https://github.com/sonic-net/sonic-mgmt/pull/8733
Summary:
- This PR fixes 'test_escape_character' test under dut_console test suite.
- Currently test runs the respective 'ping' command on the test bed server instead of running it on the console of the respective DUT.
- And also pexpect.spawn creates child process for ping under sonic-mgmt docker where the test is running instead of the DUT console.
- Fix 'test_escape_character' test under dut_console test suite, by calling 'duthost_console' fixture.
- Currently test runs on test bed server and executes 'ping' command which is not the expected behavior.
- Call 'duthost_console' fixture of conftest.py from the test case.
- Send 'ping' command and escape character directly on the DUT …
> [cherry-pick] [PR:8733] Call duthost_console fixture for test_escape_character test case (#8733)

- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
test_module related cases would get the value of “`get_num_modules`”, if the value is equal to zero, then the case would be skipped due to “No modules found on device”.
The value of “`get_num_modules`” on T0/T1 is zero, so the cases would be skipped.
But if there is something wrong with API or unhealthy testbed issue, `get_num_modules` will not return 0 for T0/T1.
Thanks
Skip `test_module` for non T2 topology.
Run test_module on T0 or T1 testbed.
> Skip test_module for non T2 topology

- ansible/group_vars/all/ceos.yml
Summary:
Newer ceos image can run on Ubuntu 22.04 docker with cgroupv2
Change ceos version in group_vars/all/ceos.yml
Run nightly on ubuntu 20.04 and 22.04 server.
> [ansible] update default ceos image to newer version

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
17901021
The case was skipped by the PR https://github.com/sonic-net/sonic-mgmt/pull/7805 due to the known issue on T1.
Based on the Mellanox, need to add this case back after the issue been fixed.
Since the issue had been fixed by PR https://github.com/sonic-net/sonic-utilities/pull/2688
Add back this case for T1.
Add back this case for T1
Run the case on T1, not blocking the pipeline.
T1
> revert PR 7805, add test_loopback_action_basic back on T1

- tests/ipfwd/test_nhop_group.py
The intention of the testcase is to fill the ecmp member table, but the testcase considers available ecmp groups and then adds members to it without considering the availability in the member table. The change is to fill the members based on availability of both the member table and group table to avoid either of them going out of resource.
Changes:
For nhop_group_count, take the min of (availble ecmp groups) and (available ecmp members / default_max_nhop_paths). Creating ARP entries is consuming some ecmp members. So, query the crm available resources after arp entries are programmed and synced.
Summary:
> [202205]Update testcase test_nhop_group_member_count

- tests/snmp/test_snmp_lldp.py
Summary:
Use topology marker to run snmp_lldp case on supported topology which should be same as lldp case.
NA
- [V ] Test case(new/improvement)
Filter unsupported topology
Refer to lldp test case.
Can skip snmp_lldp test case on ptf32 topology.
> Use topology marker to run snmp_lldp case on supported topology

- tests/system_health/device_mocker.py
Summary:
observed syntax error in device_mocker_factory(), 
and cause outputting incompleted skip reason:
```
No mocker defined for this platform %s
```
> fix syntax error in device_mocker_factory

- tests/mvrf/test_mgmtvrf.py
Ignoring API connection failure to mux simulator because this is ought to happen when mvrf/test_mgmtvrf.py is run and currently it throws a loganalyzer error 
Summary:
- [x ] Bug fix
- [x ] 202205
when mgmt vrf is configured, by default eth0 and loopback0 is placed under it. All the routes from global default routes are removed. This explains why UCS is no longer reachable normally. Hence requests to mux server times out. We will have to ignore these errors.
E May 19 22:54:34.911514 tor40-2 ERR pmon#CCmisApi: y_cable_port 26: attempt=6, GET http://1.75.43.7:8080/mux/tor-40/26 for physical_port 26 failed with URLError(timeout('timed out'))
E
E May 19 22:54:34.911514 tor40-2 ERR pmon#CCmisApi: y_cable_port 26: Retry GET http://1.75.43.7:8080/mux/tor-40/26 for physical port …
> Ignoring API connection failure to mux simulator

- .azure-pipelines/pytest-collect-only.yml
- tests/snappi_tests/bgp/test_bgp_convergence_performance.py
- tests/snappi_tests/bgp/test_bgp_local_link_failover.py
- tests/snappi_tests/bgp/test_bgp_remote_link_failover.py
- tests/snappi_tests/bgp/test_bgp_rib_in_capacity.py
- tests/snappi_tests/bgp/test_bgp_rib_in_convergence.py
- tests/snappi_tests/bgp/test_bgp_scalability.py
- tests/snappi_tests/ecn/conftest.py
- tests/snappi_tests/ecn/test_dequeue_ecn_with_snappi.py
- tests/snappi_tests/ecn/test_red_accuracy_with_snappi.py
- tests/snappi_tests/lacp/test_add_remove_link_from_dut.py
- tests/snappi_tests/lacp/test_add_remove_link_physically.py
- tests/snappi_tests/lacp/test_lacp_timers_effect.py
- tests/snappi_tests/pfc/test_global_pause_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_response_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_unset_bit_enable_vector.py
- tests/snappi_tests/pfc/test_pfc_pause_zero_mac.py
- tests/snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_burst_storm_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_m2o_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_runtime_traffic_with_snappi.py
- tests/snappi_tests/qos/test_ipip_packet_reorder_with_snappi.py
Summary:
To support smooth python3 migration, we need to explicitly specify the python version to be used in each branch. For master branch, default python should be python3. Need to use python3 to run the collect-only check as well.
Because of the gap in collect-only check of PR testing, some import issues under tests/snappi_tests are not caught.
* Use "python3 -m pytest" instead of directly run "pytest" command to do collect-only check.
* Fixed all the import issues of tests/snappi_tests in python3.
> Fix import issue of tests/snappi_tests in python3

- tests/snmp/memory.py
- tests/snmp/test_snmp_memory.py
Summary:
This PR is to stabilize test case `test_snmp_memory_load`.
The test case run a python script `memory,py` on the DUT to allocate large amount of memory, and then retrieve the free memory by snmp and parsing `/proc/meminfo` correspondingly. And then compare the value retrieved from SNMP and CLI.
It's flaky because
1. The commands are running in 3 separated Ansible calls, which means there is a time gap (around 3 seconds) between each call. There can be memory usage change between each call.
2. The `memory.py` script is running to fast. We need to consume the memory gradually.
This PR addressed the issue with below changes
1. Run the 3 command in a single Ansible call.
2. Improve the `memory.py` script to allocate memory in a relatively slow pace.
This PR is to back port PR #9074 …
> [202205] Stabilize snmp memory load test

- tests/common/platform/processes_utils.py
- tests/platform_tests/test_memory_exhaustion.py
There are 2 fixes in this PR to enhance for chassis:
1. Right now in processes_utils.py when check_critical_services, we rely on what is pre-defined in inventory file, otherwise it is 300 sec, but for SUP, we should give 900sec as most SUPs have 10+ dockers that need to come back up, it should differ from linecards or any single-dut. magic 900 sec comes from experientment, where I had run twice the test, 1st time need 800+sec, 2nd time needs ~702sec
2. During memory exhaustion test, if the random selected dut is chassis SUP, we also need to check linecards bootup and critical services are up.
Summary:
https://github.com/sonic-net/sonic-mgmt/issues/9087
Before:
```
/azp/_work/12/s/tests/platform_tests/test_memory_exhaustion.py::check_ssh_state#92: [localhost] …
```
> [chassis] accomodate test_memory_exhaustion.py if random dut is chassis sup

- tests/arp/files/ferret.py
Summary:
Fixes #6657 
Fix "systemctl restart ferret" failure in test_decap testcase.
Fix "systemctl restart ferret" failure in test_decap testcase. After ferret is stopped, TCP session stuck in TIME_WAIT. Then starting ferret will trigger binding to the same port. This bind() function failed.
File "/opt/ferret.py", line 350, in <module>
main()
File "/opt/ferret.py", line 342, in main
rest = RestAPI(Ferret, db, src_ip)
File "/opt/ferret.py", line 99, in __init__
self.httpd = SocketServer.TCPServer(("", self.PORT), obj)
File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
self.server_bind()
File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
self.socket.bind(self.server_address)
File "/usr/lib/python2.7/socket.py", line 228, in …
> Issue #6657 - 'systemctl restart ferret' failure in test_decap testcase

- tests/saitests/py3/sai_qos_tests.py
After enable hbm for long-link, the bufferpool for lossless is hbm.
Before packets are evicted to hbm, the bufferpool watermark will always be 0.
Once hit the eviction threshold, the whole voq is evicted to hbm, and the bufferpool watermark will be increased once by a large value.
Send pkts_num_fill_ingr_min packets as initial, which is one packet less than eviction threshold, bufferpool watermark is 0.
Before the while loop, set expected_wm = pkts_num_fill_min * cell_occupancy.
Then in while loop, the expected_wm will be added up to the correct value.
Summary:
> Update BufferPoolWatermarkTest for cisco-8000 hbm

- tests/crm/test_crm.py
Some platforms (like broadcom-dnx) allocate ACL banks dynamically so if there are no ACL rules it returns a NULL value for CRM purposes. So leave 1 ACL rule when comparing the returned used/available CRM values.
Also on broadcom-dnx an ACL entry is used per bind point so account for that when calculating the expected available acl entries.
Summary:
Fixes #8812
> Leave 1 ACL rule in test_crm.py::test_acl_entry

- .azure-pipelines/run-test-elastictest-template.yml
[CI/CD] Refine PR test template console log, display Elastictest link more clearly.
Origin pipeline display console log not very clearly for user to quickly find the Elastictest page to check detailed issue.
Use log group to aggregate the output of calling test_plan.py.
Change text color for Elastictest info and page link.
PR test executing normally and log clearer.
> [master][CI/CD] Refine PR test template console log, display Elastictest link more clearly

- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
- tests/platform_tests/test_reboot.py
Test watchdog reboot is not supported in Cisco Platform x86_64-8102_64h_o-r0 having old fpga. MSFT cannot upgrade from the Ref. point to newer FPD. Upgrading to newer fpd will brick the box for old proto. Hence skipping this only for Cisco Platform x86_64-8102_64h_o-r0
Summary:
Test watchdog reboot is not supported in Cisco Platform x86_64-8102_64h_o-r0 having old fpga
Added skip in test_reboot.py for watchdog_reboot
============================================================================================= short test summary info =============================================================================================
SKIPPED [1] /data/tests/platform_tests/test_reboot.py:279: Skip test if BIOS ver <218 and topo is T1 and platform is …
> Watchdog reset skip

- tests/iface_namingmode/test_iface_namingmode.py
In module `iface_namingmode/test_iface_namingmode.py`, in function `test_config_interface_speed`, it will change interface speed and recover the native speed. But once changing the speed, it will add an entry like `pg_lossless_10000_300m_profile` in running config, which wil cause inconsistent between previous running config and current running config. And will cause config reload in the teardown period of module. 
Summary:
In module `iface_namingmode/test_iface_namingmode.py`, in function `test_config_interface_speed`, it will change interface speed and recover the native speed. But once changing the speed, it will add an entry like `pg_lossless_10000_300m_profile` in running config, which wil cause inconsistent between previous running config and current running config. …
> Remove pg lossless settings of port speed in module `iface_namingmode/test_iface_namingmode.py`.

- tests/conftest.py
Summary:
The fixtures creating testbed device objects depend on supplied inventory files. When multiple inventory files are supplied to the pytest command, fixture 'enhance_inventory' ensures that a list of inventory files are supplied to ansible's InventoryManager under the hood.
Although fixture `enhance_inventory` is set to "autouse". There is still chance that it is executed after fixtures like vmhost, ptfhost, fanouthots, etc. In this case, multiple inventory files may be supplied to InventoryManager as a string using "," to separate the inventory files. Then InventoryManager may fail to find the correct inventory files and eventually result in "KeyError" while trying to return some hosts defined in the inventory files.
This change fixed the issue by specifying …
> Fix potential KeyError of fixtures like vmhost, ptfhost, fanouthosts.

- tests/platform_tests/api/watchdog.yml
Adding watchdog parameter for cisco-8111 platform
Adding watchdog parameter for cisco-8111 platform .
This will address 1 testcase failure in /tests/platform_tests/api/test_watchdog.py
Verified this change on cisco-8111 platform and testcase now passes .
> Adding watchdog parameter for cisco-8111 platform

- tests/platform_tests/api/test_sfp.py
Fixed test_get_transceiver_info testcase for ZR SFPs
This Pr is the same as PR #7480
cherry picked from master
Summary:
To make test_get_transceiver_info pass if SFP is ZR.
test_get_transceiver_info testcase fails for a ZR SFP with the message:
Failed: Transceiver info contains unexpected field:
'supported_min_laser_freq', 'supported_max_tx_power', 'supported_min_tx_power', 'supported_max_laser_freq'
Added the above keys to tranceiver info keys if SFP is a ZR QSFP-DD
Tested test_get_transceiver_info testcase on a multi cards multi ASICs chassis
> Fixed test_get_transceiver_info testcase for ZR SFPs

- .azure-pipelines/get_dut_version.py
- tests/bgp/test_bgp_update_timer.py
PR #7907 import a fixture `has_suppress_feature` to get `bgp suppress-fib-pending` on DUT, which may add a config `suppress-fib-pending` in running config. And this will cause inconsiscient  between previous running config and current running config, and will cause unnecessary config reload after whole module running. In this PR, I delete this config in the teardown period of this module. 
Summary:
PR #7907 import a fixture `has_suppress_feature` to get `bgp suppress-fib-pending` on DUT, which may add a config `suppress-fib-pending` in running config. And this will cause inconsiscient  between previous running config and current running config, and will cause unnecessary config reload after whole module running. In this PR, I delete this config in the teardown period of …
> Delete config `suppress-fib-pending` after module `bgp/test_bgp_update_timer.py` running. 

- tests/radv/test_radv_ipv6_ra.py
Summary:
Script `test_radv_ipv6_ra.py` is unnecessarily skipped on non-dualtor topology. The reason is that this script uses fixture `toggle_all_simulator_ports_to_upper_tor` which depends on `cable_type` fixture.
The `cable_type` fixture requires that the topology must has "dualtor", otherwise skip the test.
This change updated the `test_radv_ipv6_ra.py` to use fixture `toggle_all_simulator_ports_to_random_side`.
> test_radv_ipv6_ra is unnecessarily skipped on non-dualtor topology

- .azure-pipelines/pytest-collect-only.yml
- tests/snappi_tests/bgp/test_bgp_local_link_failover.py
- tests/snappi_tests/bgp/test_bgp_remote_link_failover.py
- tests/snappi_tests/bgp/test_bgp_rib_in_capacity.py
- tests/snappi_tests/bgp/test_bgp_rib_in_convergence.py
- tests/snappi_tests/ecn/conftest.py
- tests/snappi_tests/ecn/test_dequeue_ecn_with_snappi.py
- tests/snappi_tests/ecn/test_red_accuracy_with_snappi.py
- tests/snappi_tests/lacp/test_add_remove_link_from_dut.py
- tests/snappi_tests/lacp/test_add_remove_link_physically.py
- tests/snappi_tests/lacp/test_lacp_timers_effect.py
- tests/snappi_tests/pfc/test_global_pause_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_response_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_unset_bit_enable_vector.py
- tests/snappi_tests/pfc/test_pfc_pause_zero_mac.py
- tests/snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_burst_storm_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_m2o_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_runtime_traffic_with_snappi.py
- tests/snappi_tests/qos/test_ipip_packet_reorder_with_snappi.py
Summary:
To support smooth python3 migration, we need to explicitly specify the python version to be used in each branch. For 202205 branch, default python should be python2. Need to use python2 to run the collect-only check as well.
To avoid potential import issue, updated the relative importing in scripts under tests/snappi_tests to absolute importing.
* Use "python2 -m pytest" instead of directly run "pytest" command to do collect-only check.
* Updated the relative importing in scripts under tests/snappi_tests to absolute importing.
> [202205] Fix import issue of scripts under tests/snappi_tests

- .azure-pipelines/pytest-collect-only.yml
- tests/snappi_tests/ecn/conftest.py
- tests/snappi_tests/ecn/test_dequeue_ecn_with_snappi.py
- tests/snappi_tests/ecn/test_red_accuracy_with_snappi.py
- tests/snappi_tests/pfc/test_global_pause_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_response_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_unset_bit_enable_vector.py
- tests/snappi_tests/pfc/test_pfc_pause_zero_mac.py
- tests/snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_burst_storm_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_m2o_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_runtime_traffic_with_snappi.py
- tests/snappi_tests/qos/test_ipip_packet_reorder_with_snappi.py
Summary:
To support smooth python3 migration, we need to explicitly specify the python version to be used in each branch. For 202012 branch, default python should be python2. Need to use python2 to run the collect-only check as well.
To avoid potential import issue, updated the relative importing in scripts under tests/snappi_tests to absolute importing.
* Use "python2 -m pytest" instead of directly run "pytest" command to do collect-only check.
* Updated the relative importing in scripts under tests/snappi_tests to absolute importing.
> [202012] Fix import issue of scripts under tests/snappi_tests

- tests/ipfwd/test_nhop_group.py
Add flow map for cisco-8111 targets
Summary:
> [202205]Update nhop_group_member_order_capability

- tests/conftest.py
Summary:
Cherry-pick #9259 
The fixtures creating testbed device objects depend on supplied inventory files. When multiple inventory files are supplied to the pytest command, fixture 'enhance_inventory' ensures that a list of inventory files are supplied to ansible's InventoryManager under the hood.
Although fixture `enhance_inventory` is set to "autouse". There is still chance that it is executed after fixtures like vmhost, ptfhost, fanouthots, etc. In this case, multiple inventory files may be supplied to InventoryManager as a string using "," to separate the inventory files. Then InventoryManager may fail to find the correct inventory files and eventually result in "KeyError" while trying to return some hosts defined in the inventory files.
This change fixed the issue …
> [202012] Fix potential KeyError of fixtures like vmhost, ptfhost, fanouthosts 

- tests/cacl/test_cacl_function.py
The timeout and the interval in the waituntil function should not be same, when it is same, waituntil could not work as expected, it will always only run the function for one time, if the function we are checking return False, it will not do retry.
Change-Id: Ib6069609a94af9b7e966fb7393247624b247ad56
Summary: 
Fixes # (issue) the test not stable issue
stabilize the cacl test case
Change the timeout and the interval in the waituntil func
Run the test case few times, and all pass.
No
> [cacl] stabilize the cacl test

- tests/conftest.py
Summary:
Cherry-pick #9259
The fixtures creating testbed device objects depend on supplied inventory files. When multiple inventory files are supplied to the pytest command, fixture 'enhance_inventory' ensures that a list of inventory files are supplied to ansible's InventoryManager under the hood.
Although fixture `enhance_inventory` is set to "autouse". There is still chance that it is executed after fixtures like vmhost, ptfhost, fanouthots, etc. In this case, multiple inventory files may be supplied to InventoryManager as a string using "," to separate the inventory files. Then InventoryManager may fail to find the correct inventory files and eventually result in "KeyError" while trying to return some hosts defined in the inventory files.
This change fixed the issue by …
> [202205] Fix potential KeyError of fixtures like vmhost, ptfhost, fanouthosts

- ansible/files/creategraph.py
Summary:
This fix is only required for 202305 branch.
Branch 202305 is the only branch uses python3 AND "creategraph.py". Older branches are still using python2.
Master branch is also using python3. However, the creategraph.py tool and XML based connection graph files have been deprecated.
The creategraph.py tool has some compatibility issue under python3. This change fixed the issues to make it work under both python2 and python3.
Tested run the tool to generate XML graph under both python2 and python3.
> [202305] Fix creategraph.py python3 compatibility issue

- tests/bgp/test_bgp_slb.py
Summary:
Fixes test_bgp_slb_neighbor_persistence_across_advanced_reboot test failure on dual tor
Fixes test_bgp_slb_neighbor_persistence_across_advanced_reboot test failure on dual tor.
In script using setup_interfaces for bgp connections which already use toggle_all_simulator_ports_to_enum_rand_one_per_hwsku_frontend_host_m and enum_rand_one_per_hwsku_frontend_hostname for muxcable toggle operation/selection on dualtor.
But script use toggle_all_simulator_ports_to_rand_selected_tor  and rand_one_dut_hostname in test case, which may not same as 
setup_interfaces and finally cause test case failure. 
Use enum_rand_one_per_hwsku_frontend_hostname and toggle_all_simulator_ports_to_rand_selected_tor .
bgp/test_bgp_slb.py::test_bgp_slb_neighbor_persistence_across_advanced_reboot[warm-str2-7050c …
> fix bgp slb test case dual tor issue

- tests/memory_checker/test_memory_checker.py
This is testcase enhancement, it'll save number of `skipped` testcases in this test file.
call combination of `enum_rand_one_per_hwsku_frontend_hostname, enum_rand_one_asic_index, enum_dut_feature` to let random feature choosing same dut as enum_rand_one_per_hwsku_frontend_hostname. 
original way of `enum_dut_feature_container, enum_rand_one_per_hwsku_frontend_hostname` will generate combination of 
`test_memory_checker[lc7-1-lc5-1|lldp1` which `lc5-1|lldp1` is generated by `enum_dut_feature_container` and `enum_rand_one_per_hwsku_frontend_hostname` is `lc7`. This combination then gets skipped when decoding enum_dut_feature_container. This PR intends to avoid those combinations, instead of skip.
Summary:
Before lots of skips due to:
```
SKIPPED [4] …
```
> [chassis] test_memory_checker.py use same random dut for fixtures and functions 

- tests/platform_tests/test_memory_exhaustion.py
https://github.com/sonic-net/sonic-mgmt/pull/9075 introduced new function which has 3 arguments, caller only give 2.
Summary:
verified on T0 device:
```
PASSED platform_tests/test_memory_exhaustion.py::TestMemoryExhaustion::test_memory_exhaustion[xxxacs-10]
================== 1 passed, 218 warnings in 1033.24 seconds ===================
```
> [regression] fix regression in test_memory_exhaustion.py

- docs/testplan/BGP-queue-test-plan.md
- tests/bgp/test_bgp_queue.py
- Add a test case to verify that BGP packets use queue7 on all platforms
- All control packets including BGP are expected to use queue7, separate from data packet queues
Summary:
Fixes # (17647967)
It was observed that control packets use queue 0 in TD2 platforms which can lead to these packets being lost when link utilization becomes close to 100%. This can lead to critical issues in field like BGP keepalive failures. This management test is a way to make sure that this doesn't happen again in production.
By bringing up BGP sessions with neighbors and making sure that BGP control traffic uses queue 7 by default using "show queue counters".
By running the test and making sure that it works as expected, reporting success or failure depending on which queues are used by control packets. …
> Add a test case to verify that BGP packets use queue7

- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
I noticed that XFAIL conditional mark was set for this test. I disabled it and then re-ran tests on 20201231.110 and 202205.36 images on dx010 and they both passed:
Summary:
Fixes: [SONiC_Nightly][Failed_Case][platform_tests.test_reboot][test_continuous_reboot][20220531][DX010] - [20201231]
(The GitHub issue in the conditional mark file does not correspond to this issue, hence not linking here )
XFAIL conditional mark was set for this test that was giving the impression that the test was failing.
I modified the conditional_mark YAML file to remove the XFAIL for that particular test and platform combination
re-ran tests on 20201231.110 and 202205.36 images on dx010 and they both passed
> Removed XFAIL for test_continuous_reboot which is passing on dx010 platform

- tests/qos/test_qos_sai.py
Summary:
24524861
After enabled docker_inram, test qossai related cases would always be tear down due to memory check failure.
qos sai test case would install a docker image which original size is about 1.1G.
It would cause 7050qx memory usage above the threshold since 70501x is a small memory device.
Ignore the memory threshold check since it is a expected behavior.
Run the original case.
7050qx
> ignore memory threshold check for 7050qx in qos sai test

- tests/platform_tests/broadcom/files/ser_injector.py
Summary:
24688867
test_ser failed due to timeout from new incoming memory for th2
update the failure memory into timeout ignore list
run the original case
TH2
> update ser timeout ignore memory for th2

- tests/acl/test_acl_outer_vlan.py
Summary:
Manually cherry-pick and resolve conflict of this PR: https://github.com/sonic-net/sonic-mgmt/pull/9310
MX doesn't have portchannel, which would cause failure in this case. This PR is to fix this problem.
Modify the method of getting upstream neighbor port.
Run tests in m0/mx/t0 physical testbeds, all passed.
> [202305][mx][acl] Fix test_acl_outer_vlan failed at mx (#9310)

- tests/conftest.py
We want to get core dump files for debugging if new core dump generates. In this PR, we use function `duthost.fetch` to copy core dump files from DUT to test server and Elastictest supports downloading files under `tests/logs` folder. So we can get these core dump files. 
Summary:
We want to get core dump files for debugging if new core dump generates. In this PR, we use function `duthost.fetch` to copy core dump files from DUT to test server and Elastictest supports downloading files under `tests/logs` folder. So we can get these core dump files. 
We use function `duthost.fetch` to copy core dump files from DUT to test server and Elastictest supports downloading files under `tests/logs` folder.
```
yutongzhang@yutongzhang-sonic-mgmt:/var/src/sonic-mgmt-int-202012/tests/log …
```
> Get core dump files from dut if new core dump generates.

- tests/common/plugins/conditional_mark/tests_mark_conditions_202205.yaml
Summary:
[202205] Remove test_decap xfail mark
#9250 has been merged to fix test_decap test failure.
This PR will remove test_decap xfail mark in 202205 branch.
Remove test_decap xfail mark.
N/A
> Remove test_decap xfail mark

- ansible/library/shell_cmds.py
- docs/api_wiki/ansible_methods/shell_cmds.md
- tests/common/devices/sonic.py
Summary:
Backport #8931 
1. Add a parameter `timeout` to ansible library `shell_cmds`. The default value is `0` which means no limitation. **(However, this update also introduce a limitation. If the timeout is not 0, then the command should not contain single quotes `'`)**
2. Set the timeout of some commands to 30s to avoid costing too much time, also updated the command to adapt the timeout wrapper.
1. Add a parameter `timeout` to ansible library `shell_cmds`. The default value is `0` which means no limitation.
2. Set the timeout of some commands to 30s to avoid costing too much time, also updated the command to adapt the timeout wrapper.
1. Verified by run `test_pretest` and `test_memory_exhaustion` on physical testbeds.
2. Verified by PR test.
> [202205] Add param timeout to ansible library shell_cmds (#8931)

- tests/qos/qos_sai_base.py
Due to the change in PR(#15914) the search criteria to get scheduler parameters from Redis db needs to be changed
Summary:
The query to redis db was previously searched with only port & queue . Now in addition to it the duthost & asic namespace has to be concatenated  in search
Due to the change in PR(#15914) the search criteria to get scheduler parameters from Redis db needs to be changed
Adding the correct duthost details in redis query fetch the appropriate result
qos test failed with - IndexError: list index out of range
Adding the correct duthost details in redis query fetch the appropriate result
Re-run the qos test suite
> Adding dut & dut_asic namespace to getSchedulerParam in qos_sai_base

- tests/qos/qos_sai_base.py
Due to the change in PR(#15914) the search criteria to get scheduler parameters from Redis db needs to be changed
PR# https://github.com/sonic-net/sonic-mgmt/pull/9125 raised for master branch
Summary:
The query to redis db was previously searched with only port & queue . Now in addition to it the duthost & asic namespace has to be concatenated in search
The code base is different from master branch, hence raising separate PR for 202205
Re-run the qos test suite
> [Cherry-pick #9125] Adding dut & dut_asic namespace to getSchedulerParam in qos_sai_base

- tests/pfcwd/conftest.py
Summary:
24767839
All pfcwd related cases on T1 failed after the PR https://github.com/sonic-net/sonic-mgmt/pull/8859
the PR would modify the return value of ip_ifaces as a list instead of dict, then caused the issue.
"ip_ifaces = duthost.get_active_ip_interfaces(tbinfo, asic_index="all")"
Workaround the issue, use 0 instead of "all" for asic_index, and need the owner of PR 8859 to further analyze.
Run original failure case
pfcwd/test_pfc_config.py::TestPfcConfig::test_forward_action_cfg[str3-7060-acs-3] PASSED  
T1
> workaround PFCWD T1 related cases after PR 8859

- tests/pfcwd/test_pfcwd_function.py
Sometimes pfcwd cases failed due to verify_rx_ingress("forward") failure, it is possibly caused by previous scripts or testbed in bad status before pfcwd script running, which is very confusing.
Add pre check traffic before pfc storm, to confirm the traffic issue is caused by pfc storm or not.
Summary:
run script test_pfcwd_function.py.
```
-------------------------------------------------------------- generated xml file: /data/tests/logs/tr_2023-08-06-06-36-22.xml --------------------------------------------------------------
---------------------------------------------------------------------------------- live log sessionfinish -----------------------------------------------------------------------------------
07:11:16 __init__.pytest_terminal_summary         L0064 INFO …
```
> pre check traffic before pfc storm

- tests/acl/templates/acltb_v6_test_rules.j2
- tests/acl/templates/acltb_v6_test_rules_part_2.j2
- tests/acl/test_acl.py
- tests/conftest.py
Summary:
Test second vlan for m0-2vlan in test_acl
Add a new fixture `vlan_name` to specify tested vlan.
Belows are IPs tested:
- IPv4:
| Vlan ID | ACL Action | IP |
| ------ | ------- | ----- |
|1000|default|192.168.0.123|
|1000|allow|192.168.0.122|
|1000|block|192.168.0.121|
|2000|default|192.168.0.253|
|2000|allow|192.168.0.252|
|2000|block|192.168.0.251|
- IPv6:
| Vlan ID | ACL Action | IP |
| ------ | ------- | ----- |
|1000|default|fc02:1000::5|
|1000|allow|fc02:1000::6|
|1000|drop|fc02:1000::7|
|2000|default|fc02:1000:0:1::5|
|2000|allow|fc02:1000:0:1::6|
|2000|drop|fc02:1000:0:1::7|
Run tests on t0/t1/m0/m0-2vlan/mx testbeds, all passed.
> [acl][m0] Test second vlan for m0-2vlan in test_acl

- tests/scripts/arp_responder.py
Summary:
Missing part of this PR: https://github.com/sonic-net/sonic-mgmt/pull/8697 would causes error while replying ndp.
```
root:/tmp# /root/env-python3/bin/python3 /opt/arp_responder.py -e
File "/opt/arp_responder.py", line 134, in <module>
main()
File "/opt/arp_responder.py", line 130, in main
scapy.sniff(prn=ARPResponder.action, filter="arp or icmp6", iface=list(ip_sets.keys()), store=False)
File "/root/env-python3/lib/python3.7/site-packages/scapy/sendrecv.py", line 1311, in sniff
sniffer._run(*args, **kwargs)
File "/root/env-python3/lib/python3.7/site-packages/scapy/sendrecv.py", line 1254, in _run
session.on_packet_received(p)
File "/root/env-python3/lib/python3.7/site-packages/scapy/sessions.py", line 109, in on_packet_received …
```
> [arp_responder] Fix error in generate_neigh_adv

- tests/crm/templates/acl.json
PR #9199 modified the template acl.json under folder `tests/crm/templates` and added a key `input_interface` in this template. Only backend topo supports this key, so it will generate an error log in non-backend topo. In this PR, I revert the change to this template. And for recovery, we have another template in PR #9312 .
Summary:
PR #9199 modified the template acl.json under folder `tests/crm/templates` and added a key `input_interface` in this template. Only backend topo supports this key, so it will generate an error log in non-backend topo. In this PR, I revert the change to this template. And for recovery, we have another template in PR #9312
Revert the change to template acl json.
> Revert the change to template acl.json. 

- tests/acl/templates/acltb_v6_test_rules.j2
- tests/acl/templates/acltb_v6_test_rules_part_2.j2
- tests/acl/test_acl.py
- tests/conftest.py
Summary:
Manually cherry-pick and resolve conflict of this PR: https://github.com/sonic-net/sonic-mgmt/pull/9334
Test second vlan for m0-2vlan in test_acl
Add a new fixture vlan_name to specify tested vlan.
Run tests on t0/t1/m0/m0-2vlan/mx testbeds, all passed.
> [202205][acl][m0] Test second vlan for m0-2vlan in test_acl (#9334)

- ansible/roles/test/files/ptftests/py3/IP_decap_test.py
- tests/decap/test_decap.py
Summary:
Migrate test_decap PTF script to Python3
This PR migrate test_decap PTF script to Python3.
2to3 and manually code change.
Run with physical testbed.
> [PTF python3 migration] Modify test_decap PTF script

- tests/scripts/arp_responder.py
Summary:
Introduced this PR: https://github.com/sonic-net/sonic-mgmt/pull/8697. Missing specifying interface would causes that ipv6 reply packet is sent by default interface([sendrecv.py](https://github.com/secdev/scapy/blob/2fe5cee7b2fdca940b1774ee26a4948e88417232/scapy/sendrecv.py#L452)), which is incorrect.
Specify send interface.
* Run this script in ptf and ping ipv6 address from DUT, then run `show ndp` in DUT, address pinged before can be seen in ndp table.
* Run **test_acl.py** in **m0** testbed, all passed. (This test case in m0 would trigger ndp reply)
> [arp_responder] Fix response icmpv6 packet error

- tests/dhcp_relay/test_dhcp_pkt_fwd.py
Summary:
Add support for in test_dhcp_pkt_fwd for m0-2vlan
Add support for in test_dhcp_pkt_fwd for m0-2vlan
Run tests
> [dhcp_relay][m0] Add support for in test_dhcp_pkt_fwd for m0-2vlan

- tests/common/fixtures/advanced_reboot.py
- tests/common/fixtures/duthost_utils.py
Summary: Run check_bgp_router_id post reboot
Run check_bgp_router_id on target image after reboot
Move check after ptf test
> [202012] Run check_bgp_router_id post reboot

- tests/common/fixtures/advanced_reboot.py
Summary: Run check_bgp_router_id post reboot
Run check_bgp_router_id on target image after reboot
Move check after ptf test
> Run check_bgp_router_id post reboot

- tests/qos/files/qos_params.jr2.yaml
Initial JR2 Qos parameters are copied from J2C+. These parameters are needed to run T2 tests against JR2 based platforms.
Summary:
This fixes `KeyError: 100000_120000m` seen while running sonic-mgmt/qos tests on JR2 based platforms.
> [Chassis T2] Added initial JR2 Qos params for T2 testing

- tests/dhcp_relay/test_dhcp_pkt_fwd.py
Summary:
Manually cherry-pick and resolve conflict of this PR: https://github.com/sonic-net/sonic-mgmt/pull/9356
Add support for in test_dhcp_pkt_fwd for m0-2vlan
Add support for in test_dhcp_pkt_fwd for m0-2vlan
Run tests
> [202205][dhcp_relay][m0] Add support for in test_dhcp_pkt_fwd for m0-2vlan (#9356)

- tests/cacl/test_cacl_function.py
- tests/common/templates/default_acl_rules.json
- tests/conftest.py
- tests/crm/conftest.py
- tests/crm/test_crm.py
In module `cacl/test_cacl_function.py`, it will use command `acl-loader delete` to delete all acl rules, no matter if the testbed has DATAACL rules before test or not. If this testbed has DATAACL rules before, this deletion will cause inconsistent between previous running config and current running config, and will cause unnecessary config reload. In PR #9199 , we have a fixture `recover_acl_rule` to recovery acl rules. So in this PR, I refactor this fixture and use this fixture to recover acl rules in module `cacl/test_cacl_function.py`.
Summary:
In module `cacl/test_cacl_function.py`, it will use command `acl-loader delete` to delete all acl rules, no matter if the testbed has DATAACL rules before test or not. If this testbed has DATAACL rules before, this deletion will …
> Refactor fixture `recover_acl_rule` and and use it in module `cacl/test_cacl_function.py`.

- tests/acl/test_stress_acl.py
Module `acl/test_stress_acl.py` will add several acl tules in config to test stress, and will delete the stess rules at the end of TC. But if there is something wrong happens, it will go to the end of TC, and will not delete these rules. This will cause unnecessary config reload. In this PR, we add try-finally to ensure the logic of recovering will be exectued. 
Summary:
Module `acl/test_stress_acl.py` will add several acl tules in config to test stress, and will delete the stess rules at the end of TC. But if there is something wrong happens, it will go to the end of TC, and will not delete these rules. This will cause unnecessary config reload. In this PR, we add try-finally to ensure the logic of recovering will be exectued. 
Add try-finally to ensure the logic of …
> Add try-finally to recovery DUT in module `acl/test_stress_acl.py`. 

- tests/restapi/test_restapi.py
Summary:
The test case `test_create_vrf` was failing at a very low possibility (around 1/10) with below error message.
```
expected = [{"nexthop": "100.78.60.37", "ip_prefix": "10.1.0.1/32", "vnid": 7039114, "mac_address": "00:0d:3a:f9:1a:20"},
{"nexthop": "100.78.60.37", "ip_prefix": "10.1.0.2/32", "vnid": 7039114, "mac_address": "00:0d:3a:f9:1a:20"},
{"nexthop": "100.78.60.37", "ip_prefix": "10.1.0.3/32", "vnid": 7039114, "mac_address": "00:0d:3a:f9:1a:20"},
{"nexthop": "100.78.60.37", "ip_prefix": "10.1.0.4/32", "vnid": 7039114, "mac_address": "00:0d:3a:f9:1a:20"},
{"nexthop": "100.78.60.37", "ip_prefix": "10.1.0.5/32", "vnid": 7039114, "mac_address": "00:0d:3a:f9:1a:20"}]
for route in expected:
>           pytest_assert(route in r.json())
E           Failed: <Failed instance>
``` …
> Stabilize `test_create_vrf`

- ansible/module_utils/port_utils.py
Summary:
The port_config.ini defines interface names as alias as follows:
Name                  Alias
Ethernet0     ...     Ethernet1/1
Ethernet8     ...     Ethernet2/1
The interface names are 0-based and offset by 8 in comparison to the alias name for the interface
Add support to SONiC Mgmt test to run on Arista-7060DX5-64S
> sonic-mgmt: Add port_alias_to_name_map support for Arista-7060DX5-64S

- tests/saitests/py3/sai_qos_tests.py
Summary:
When running isolated tests, the first packet sent on a host can egress out a different member due to missing ARP table entries. Send a preliminary packet to ensure ARP is fully resolved before returning the LAG ID. 
Observed issue when running isolated XoffLimit test case. 
Cisco8000 TB. 
Reproduced issue by clearing arp tables on DUT. Running the xoff test case would then fail due to incorrectly blocked egress because the get_rx_port function returned the wrong port ID. 
This fix works on this test when clearing ARP tables, it logs the correction.
> ARP resolution during get_rx_port to avoid flaky LAG ID

- tests/everflow/everflow_test_utilities.py
Summary:
This PR is to backport #9414 into `202205` branch.
The EVERFLOW Egress mirroring test was failing on Mellanox dualtor because the expected mirroring packet doesn't match the sent packet.
```
pytest_assert(inner_packet.pkt_match(mirror_packet_sent), "Mirror payload does not match received packet")
```
It's because for the downstream traffic on dualtor testbed, the src_mac should be the MAC address of `Vlan1000`. The value is different from the router MAC.
This PR addressed the issue by changing the src MAC address of the downstream traffic to VLAN MAC on dualtor testbed.
This PR is to fix EVERFLOW egress mirroring test in dualtor testbed.
This PR addressed the issue by changing the src MAC address of the downstream traffic to VLAN MAC on dualtor testbed.
Verified on a SN4600 …
> [202205] Fix EVERFLOW egress mirroring test in dualtor setup

- tests/pfcwd/test_pfcwd_warm_reboot.py
Summary:
This PR is to decrease the PFC frame counter in PFC watchdog warmboot test.
The change is required because the `pfc_gen.py` is left running on leaf fanout if the PFCStorm handler failed to kill the script for some reason. The script keeps running on leaf fanout for a few days and affects the nightly test.
The number is changed to  `1000000000` from `10000000000000`.
In my test, it costs around 1 hour for leaf-fanout to generate and send `1000000000` PFC pause frames on a `Intel(R) Pentium(R) CPU D1508 @ 2.20GHz` CPU. The test costs around 20 minutes to finish. So the number should be enough for the test.
This PR is to decrease the PFC frame counter in PFC watchdog warmboot test. 
Decrease the number to  `1000000000` from `10000000000000`.
The change is verified by running …
> Decrease the PFC frame counter in PFC watchdog warmboot test

- tests/bgp/conftest.py
- tests/bgp/test_bgpmon.py
- tests/bgp/test_bgpmon_v6.py
- tests/common/helpers/generators.py
- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Tests for IPv6-based bgpmon for T2 chassis
Add new test cases for IPv6-based bgpmon session
Modified tests to use IPv6 loopback4096 address as source and initiate v6 BGPMon session to exabgp on PTF
Tested on T2 chassis
> Add support for BGPMon over IPv6 for T2 chassis

- ansible/roles/test/files/acstests/lag_test.py
Summary:
If, for some reason, the LAG session is down and there are no LACP PDU packets being sent back and forth, then the `LacpTimingTest` class will fail with a error about an invalid argument to `float`.
In the LacpTimingTest class, when getting the initial LACP packet, first check to see that a packet was captured before trying to convert the timestamp value of the tuple to a `float`.
This doesn't necessarily prevent an error from being thrown, it just makes it a more graceful/expected failure.
> lag_test: Add check to verify that an initial LACP packet was received

- tests/bgp/test_bgp_suppress_fib.py
Summary:
TC test_credit_loop fails with error log: 
ERR swss#supervisor-proc-exit-listener: Process 'orchagent' is stuck in namespace 'host' (1.0 minutes).
Considering that the test stops orchagent on purpose, messages ignored above should be added to loganalyzer. 
Added ignore regex
Run TC, TC passed
> Added expected error to ignore for bgp suppress TC

- ansible/roles/test/files/ptftests/py3/populate_fdb.py
- tests/common/fixtures/populate_fdb.py
Summary:
Migrate populate_fdb PTF script to Python3
This PR migrate populate_fdb PTF script to Python3.
2to3 and manually change code
Test with physical testbed.
> [PTF python3 migration] Modify populate_fdb PTF script

- tests/platform_tests/test_cpu_memory_usage.py
Summary:
19998021
test_cpu_memory_usage case failure on 7050qx platform
system memory usage 85% exceeds 60%: {u'used_percent': 85.2, u'total': 4003824.0, u'used': 3121812.0, u'free': 593944.0}
Update the memory threshold for 7050qx, since it's an expect behavior after docker_inram enabled on 7050qx
Run test_cpu_memory_usage case on 7050qx
platform_tests/test_cpu_memory_usage.py::test_cpu_memory_usage[str2-7050qx-32s-acs-01] PASSED    
7050qx
> update memory threshold in case test_cpu_memory_usage  for 7050qx

- tests/generic_config_updater/test_ecn_config_update.py
For Cisco platforms, the command "sonic-db-cli ASIC_DB keys *WRED*” used in this testcase return 2 WRED object instead of 1 that the script expects. This is because one is the "default” WRED profile that SAI/SDK creates with default setting, while other is the user configured WRED profile that sonic creates.
Summary: This can be fixed by checking which WRED object corresponds to default WRED profile and which one corresponds to user configured WRED profile; then ignoring the default profile and using the user configured profile for the testcase
**Approach**
All 4 testcases in test_ecn_config_update.py fail on all testbeds
Check which one is the default profile and …
> cisco change for ecn-config-update

- tests/common/fixtures/ptfhost_utils.py
Summary:
This PR is to fix the port selection code in `ptfhost_utils.py`.
Because of the issue in port selection, the disabled port can be used in test and that results in test failure.
This PR is to fix the port selection code in `ptfhost_utils.py`.
This PR addressed the issue by using the correct key-value in dict `disabled_ptf_ports`.
The change is verified by running `test_decap`
```
collected 4 items                                                                                                                                                          
decap/test_decap.py::test_decap[ttl=pipe, dscp=uniform, vxlan=disable] ^HPASSED …
```
> Fix port selection in ptfhost_utils.py

- tests/everflow/everflow_test_utilities.py
Summary:
The EVERFLOW Egress mirroring test was failing on Mellanox dualtor because the expected mirroring packet doesn't match the sent packet.
```
pytest_assert(inner_packet.pkt_match(mirror_packet_sent), "Mirror payload does not match received packet")
```
It's because for the downstream traffic on dualtor testbed, the src_mac should be the MAC address of `Vlan1000`. The value is different from the router MAC.
This PR addressed the issue by changing the src MAC address of the downstream traffic to VLAN MAC on dualtor testbed.
This PR is to fix EVERFLOW egress mirroring test in dualtor testbed.
This PR addressed the issue by changing the src MAC address of the downstream traffic to VLAN MAC on dualtor testbed.
Verified on a SN4600 dualtor testbed.
```
collected 40 items …
```
> Fix EVERFLOW egress mirroring test in dualtor setup

- tests/bgp/conftest.py
Fix bgp update timer issue on dual tor env. 
Summary:
Fix bug update timer issue on dual tor, when set up bgp speaker session with dual tor.
Interface selection on PTF has wrong behavior, config IP addresses within same subnet on different interfaces would case connection error. Refer to analysis of #8487.
Config primary /secondary ip addresses on same physical interface.
re-run test on dual-tor env
> fix bgp update timer failure on dual tor

- tests/telemetry/events/swss_events.py
Summary:
Fixes # (issue) 24769530
Fix if-state testcase in test_events
Check for valid interfaces and perform trigger action on those interfaces
Run test/pipeline
> Fix if-state testcase in test_events

- tests/snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py
Summary: config_reload on 202205 uses "sonic_host" instead of "duthost" as on other branches. This was not caught during cherry-pick, and caused the test to fail on this line.  
Ran on 202205 nightly pipeline
> [202205][Snappi] Fix config_reload error

- tests/bgp/test_bgp_update_timer.py
Fix test_bgp_update_timer.py issue on T0 and T1, which caused by background running tcpdump issue.
Summary:
Fix test_bgp_update_timer.py issue on T0 and T1, which caused by background running tcpdump.
In script using "nohup <> &" running without waiting for tcpdump tool real running on DUT.
So in some failure case, bgp update sendout but tcpdump still not ready to capture packets and cause failure with saying bgp update not found.
Wait until tcpdump tool running on DUT before continue testing
Keep running 10 times on KVM environment without failure.
> fix tcpdump issue in bgp update timer testing

- setup-container.sh
Summary:
In setup-container stage, all packages under the user, AzpDevOps, will be reinstalled to the virtual environment of host user. But there are a few incompatible packages that cannot be installed by pip command of the virtual environment.
In setup-container stage, all packages under the user, AzpDevOps, will be reinstalled to the virtual environment of host user. But there are a few incompatible packages that cannot be installed by pip command of the virtual environment.
Filter out these incompatible packages at the re-installing step.
Check setup-container command in the locally.
```
$ ./setup-container.sh -n sonic-mgmt  -d /data
'/home/zegan/.ssh/id_rsa_docker_sonic_mgmt' -> '/tmp/tmp.Ssj2kL0x43/id_rsa'
'/home/zegan/.ssh/id_rsa_docker_sonic_mgmt.pub' -> …
```
> [setup-container]: Fix incompatible packages between virtual env and global env

- tests/conftest.py
Reverts sonic-net/sonic-mgmt#8884
In PR #8884, in multi-asic scenrio
```
node.copy(content=json.dumps(duts_data[node.hostname]["pre_running_config"]["asic0"], indent=4),
dest='/etc/sonic/config_db.json', verbose=False)
```
This code will overwrite the global config with asic0 config, which will cause failure. So revert this PR first. And then we will set a more exactly key name.
> Revert "Set key "asic0" in single-asic scenerio to keep consistent with multi-asic in function `core_dump_and_config_check`."

- tests/common/plugins/sanity_check/constants.py
- tests/common/plugins/sanity_check/recover.py
- tests/common/reboot.py
In the recover of sanity check, for config_reload, we simply sleep 120s.
In some topology, like multi-asic scenario, it's not enough. 
lldp services get a big chance that not ready after 120s, then sanity failed.
Use config_reload with safe_reload to better handle this flaky issue.
Summary:
Fix multi-asic lldp flaky issue.
Use config_reload with safe_reload to better handle this flaky issue.
> [Fix] Fix multi-asic flaky lldp not ready issue

- tests/common/plugins/sanity_check/constants.py
- tests/common/plugins/sanity_check/recover.py
- tests/common/reboot.py
cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/9453
In the recover of sanity check, for config_reload, we simply sleep 120s. In some topology, like multi-asic scenario, it's not enough. lldp services get a big chance that not ready after 120s, then sanity failed.
Use config_reload with safe_reload to better handle this flaky issue.
Approach
Fix multi-asic lldp flaky issue.
Use config_reload with safe_reload to better handle this flaky issue.
Summary:
> [Fix, 202012] Fix multi-asic flaky lldp not ready issue (#9453)

- tests/common/plugins/sanity_check/constants.py
- tests/common/plugins/sanity_check/recover.py
- tests/common/reboot.py
Cherry-pick: https://github.com/sonic-net/sonic-mgmt/pull/9453
In the recover of sanity check, for config_reload, we simply sleep 120s. In some topology, like multi-asic scenario, it's not enough. lldp services get a big chance that not ready after 120s, then sanity failed.
Use config_reload with safe_reload to better handle this flaky issue.
Approach
Fix multi-asic lldp flaky issue.
Use config_reload with safe_reload to better handle this flaky issue.
Summary:
> [Fix, 202205] Fix multi-asic flaky lldp not ready issue (#9453)

- tests/common/dualtor/mux_simulator_control.py
- tests/common/dualtor/nic_simulator_control.py
Summary:
Fix the error:
```
inv_files = request.config.option.ansible_inventory
> ip = utilities.get_test_server_vars(inv_files, server).get('ansible_host')
E AttributeError: 'NoneType' object has no attribute 'get'
```
The reason is that `request.config.option.ansible_inventory` returns a string, which could be a string of multiple inventory files like `"inv_file0,inv_file1"`
But `InventoryManager` takes inventory files as a list(https://github.com/ansible/ansible/blob/ca08261f08a5071cc5f8c73e61342f5a9581b9cd/lib/ansible/inventory/manager.py#L157-L163), so we should split the string if it contains multiple inventory files(from `"inv_file0,inv_file1"` to `["inv_file0", "inv_file1"]`
Run pretests.
> Fix dualtor inventory parse error

- tests/bgp/test_traffic_shift_sup.py
Summary:
Changes to fix the issue where after running bgp/test_traffic_sup.py and reload, the device came up with TSA enabled, causing subsequent test failures.
To fix the issue where after running bgp/test_traffic_sup.py and reload, the device came up with TSA enabled, causing subsequent test failures.
In test_TSA_TSB_chassis_with_config_reload, config was saved after TSA, but not after subsequent TSB. Due to this, the device returned to isolated state when rebooted in subsequent tests
Manual run of bgp/test_traffic_shift_sup.py and validated config DB and current state on all LCs
> Add config save after TSB to reset device state

- tests/cacl/test_cacl_application.py
The expected rules for dualtor are present in the script as a fixture "ignore_hardcoded_cacl_rule_on_dualtor" but the global variable "ignored_iptable_rules" is not called anywhere. This is causing test_cacl_application_dualtor to fail because the script is not expecting these rules.
Summary:
- [ x] Bug fix
- [ x] 202205
Checked it on DualToR testbed with Cisco devices
> Adding dualtor iptable rules for test_cacl_application_dualtor

- ansible/roles/test/files/ptftests/advanced-reboot.py
In the device where logs are in tmpfs, a backup is made for log_analyzer to work after reboot. However, there have been many cases when one or more backup files are empty or not created. Based on current RCA this happens when reboot CLI is executed from test and then SSH command times out.
When command execution ends, but reboot is still in progress in the device, any writes to stdout / etderr fails as there is no reader.
To fix no reader issue, run the reboot CLI w/ nohup and redirect the output to a file.
Tested on physical device
Summary:
> [cherry-pick][202205][advanced-reboot] Use nohup when executing reboot CLI to prevent PIPE errors

- tests/qos/files/qos_params.gb.yaml
qos.yml update for gb topo-t2 and longlink
Summary:
> qos.yml update for gb topo-t2 and longlink

- tests/common/fixtures/ptfhost_utils.py
Summary:
**This PR is to backport #9447 into `202205` branch.**
This PR is to fix the port selection code in `ptfhost_utils.py`.
Because of the issue in port selection, the disabled port can be used in test and that results in test failure.
This PR is to fix the port selection code in `ptfhost_utils.py`.
This PR addressed the issue by using the correct key-value in dict `disabled_ptf_ports`.
The change is verified by running `test_decap`
```
collected 4 items                                                                                                                                                          
decap/test_decap.py::test_decap[ttl=pipe, dscp=uniform, vxlan=disable] ^HPASSED …
```
> [202205] Fix port selection in ptfhost_utils.py

- tests/saitests/py3/sai_qos_tests.py
HeadroomPoolSize was taking more that ~14 mins to complete the test which results in the port flapping while test run
The sleep time added inside the loop contribute a lot to the long running iterations.
Summary:
Below are the changes in 3 loop structure in HeadroomPoolSize test:
1.**Loop to fill all pgs_num service pool**: Instead of 8 sec sleep every time after send packet and show port. Sleep time is added after packets are sent to all the pgs_num and then added another loop for show_port_counter iterating pgs_num .
2.**Loop iterating pgs_num for sending TCP packet:** Instead of sleep time every iteration before show_port_counter; Sleep time of 8 sec is allotted for non broadcom-dnx box.
3.**Loop to fill all pgs_num headroom pool:** Instead of 8 sec sleep every time after send packet …
> Optimizing testQosSaiHeadroomPoolSize runtime

- tests/test_pretest.py
Summary: Arista 7050CX3 has an ingress lossless pool size of 32.7MB and pg headroom size of 0.16MB. The params for the headroom response test assumed older values which were drastically smaller to collect packets in the queue. Since there is more space in the buffer now, the 7050CX3 can support longer delays in PFC response times from its peers. 
Fixed outdated test information
Test passes on 7050CX3 lab device.
> [Snappi] RDMA headroom test fix for 7050CX3

- tests/common/helpers/drop_counters/drop_counters.py
- tests/drop_packets/test_drop_counters.py
Summary:
Seeing failures on testbed with different hwsku's with different asic count.
In Chassis testbed, with different LC hwSKU , if one of the selected LCs have 3 asics and another LC has 2 asics, we see the below failure:
```
drop_packets/test_drop_counters.py::test_src_ip_is_loopback_addr[rif_members] 
02:08:08 utilities.wait_until                     L0118 ERROR  | Exception caught while checking <lambda>:Traceback (most recent call last):
File "/./tests/common/utilities.py", line 112, in wait_until
check_result = condition(*args, **kwargs)
File "/./tests/common/helpers/drop_counters/drop_counters.py", line 101, in <lambda>
check_drops_on_dut = lambda: packets_count in …
```
> [drop_packets]: Fix to support testbed with different hwsku with different asic count

- tests/common/plugins/ansible_fixtures.py
Summary:
This is to workaround pytest-ansible plugin issue:
Even no extra-inventory is specified, extra_inventory_manager will still be initialized.
https://github.com/ansible-community/pytest-ansible/issues/135
As of today, pytest-ansible supports host manager and module dispatcher v29, v212, v213. While initializing the pytest-ansible plugin, it tries to collect default ansible configurations and command line options. These options are used for creating host manager. When no extra_inventory is specified, the options passed to host manager will include extra_inventory=None. However, the host manager will still try to create extra_inventory_manager with None as the inventory source. This will cause the module dispatcher to run the module on hosts matching host pattern in …
> Workaound for ansible module executed twice issue of pytest-ansible

- tests/crm/test_crm.py
In PR #9054, it will try to get `duthost.facts["platform_asic"]` in test_crm.py, but in file `tests/common/devices/sonic.py`, which define the duthost.facts, platform_asic may not exist in duthost.facts. And this will cause KeyError in test_crm.py. In this PR, if platform_asic doesn't exist in duthost.facts, we set it None. 
Summary:
Fixes #9054 
In PR #9054, it will try to get `duthost.facts["platform_asic"]` in test_crm.py, but in file `tests/common/devices/sonic.py`, which define the duthost.facts, platform_asic may not exist in duthost.facts. And this will cause KeyError in test_crm.py. In this PR, if platform_asic doesn't exist in duthost.facts, we set it None.
> Fix KeyError caused by PR #9054. 

- tests/scripts/icmp_responder.py
Summary:
As the probes received from one port are the same basically(except those with TLVs), we could simply cache the replies instead of generating them in each reply cycle.
Use `functools.lru_cache` to cache the calls to `icmp_reply`.
With the `lru_cache`, the execution time of 1000 repeated calls to `icmp_reply` is reduced from `0.6184256076812744s` to `0.0006690025329589844s`.
> [icmp_responder] Cache replies to reduce response time

- tests/arp/test_neighbor_mac_noptf.py
test_neighbor_mac_noptf is flaky because sometimes it may take longer than usual to update intf address, add neighbor, and also change neighbor MAC. Make the test more robust by retrying the validation of neighbor in redis DB.
Summary:
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/9032
- [x ] Bug fix
- [ x] 202205
> Make test_neighbor_mac_noptf more robust

- .azure-pipelines/test_plan.py
Priority use `args.scripts` to get test modules if this param is not None for KVM platform. Because `pr_test_scripts.yaml` is the default file to get test modules, If we don't pass `args.scripts`, it will get test module from `pr_test_scripts.yaml`.
Priority use `args.scripts` to get test modules if this param is not None for KVM platform. Because `pr_test_scripts.yaml` is the default file to get test modules, If we don't pass `args.scripts`, it will get test module from `pr_test_scripts.yaml`.
Modify test_plan.py.
Manually trigger two test plans, one pass `args.scrips`, it will get test module from it, another don't pass `args.scripts`, it will get test module from `pr_test_scripts.yaml`. All as …
> [master][CI/CD] Priority use args.scripts to get test modules

- tests/memory_checker/test_memory_checker.py
The initial goal of this effort was to make this test more reliable on systems with low RAM (4GB).
After making some strides it became clear that some other places in this test needed enhancements.
Such as making the test run faster and removing the external dependency on the `stress` utility.
This refactor in the end introduces many changes:
- Better reliability on systems with small RAM capacity
- Better control over the amount of memory consumed by the test
- Remove the external dependency on the `stress` utility
- Faster overall runtime for the test
- A new test case making sure that monit recovers if memory was above threshold for only a single cycle
- Remove test case checking new/old syntax. It makes no sense to change the product code and then test that, that's not shipping code …
> [memory-checker] Refactor the test_memory_checker test

- spytest/bin/lint.sh
- spytest/bin/tools_install.sh
- spytest/bin/upgrade_requirements.sh
- spytest/spytest/gnmi/__init__.py
- spytest/spytest/remote/spytest-helper.py
- spytest/spytest/tgen/tg.py
- spytest/spytest/tgen/tgen_utils.py
> spytest-framework fix for E721 Do not compare types

- tests/voq/test_voq_disrupts.py
Summary:
- In case of multi-asic DUTs, for ping from eos peers to DUT's loopback address, use _loopback4096_ IP address which are unique to each line card instead of _loopback0_ IP.
For VOQ disrupts test cases, for ping from eos peers to DUT's loopback address, it's good to use _loopback4096_ IP address which are unique to each line card instead of _loopback0_ IP.
-  Change 'my_lb_ip' to 'my_lb4096_ip' in check_ip_fwd function in test
- Ran all the VOQ test cases against a multi-asic line card in a T2 chassis.
> [VOQ] - Use multi-asic dut's lb4096 IP instead of lb0 IP for ping from nbrs

- tests/qos/qos_sai_base.py
- tests/saitests/py3/sai_qos_tests.py
Qos test runs failed intermittently due to PortChannel flap.
As Broadcom dnx asic has larger queue buffer size which takes longer time interval
compared to other topology to fill up which leads to arp aging out intermittently as lag goes down due to
voq credits getting exhausted during test runs.
When Tx is disabled for destination port; which (if in case), is member of PortChannel,the lacp packets can't be sent out on that port after all the available voq credits are used. So the PortChannel flaps and the arps learned on that port channel are deleted.
After tx_enable , the neighbor's are added back , but there is a timing issue and test fails at get_rx_port 
To make sure we have enough credit on the destination port, Arp to all destination test ports before running qos test will help. …
> Adding populateArpEntries_T2 function to run for T2 Broadcom-dnx chassis in qos_sai_base 

- ansible/roles/test/files/ptftests/advanced-reboot.py
Summary: Fast-reboot is now using same infra for reconciliation and finalization as warm-reboot. Update test also to reuse common methods to measure IO drops.
A recent PR (https://github.com/sonic-net/sonic-mgmt/pull/8993) made changes to IO calculation for warm-reboot.
IO started w/ teamd going down, and ended when finalizer completed.
This PR updates fast-reload IO calculation to also use the same logic. This is now possible for fast-reboot due to recent chances in newer branches where fast-reload is using warm-reboot reconciliation and finalizer infrastructure. 
Utilize common functions for health check in fast and warm reboot cases.
Tested on physical device.
> [advanced-reboot] Update fast-reboot test IO to depend on finalizer status

- tests/everflow/everflow_test_utilities.py
Summary:
Fixes #9570 
This PR addressed the syntax issue on T2 topology.
```
UnboundLocalError: local variable 'duthost' referenced before assignment
```
This PR is to fix the everflow syntax issue on T2 topology.
Always define `duthost`, and set it to `None` by default.
No.
> Fix everflow syntax issue on T2 topology

- ansible/roles/test/files/ptftests/device_connection.py
Summary:
Possible bad fix introduced by #9475 
Fixes Python2/3 compatibility issue in device_connection.py
There is an import issue which is from Python2/3 compatibility issue.
from pip._vendor.retrying import retry
from retrying import retry
Use six package: six.PY2
N/A
> Fix Python2/3 compatibility issue in device_connection.py

- tests/snmp/test_snmp_default_route.py
- tests/snmp/test_snmp_loopback.py
Skip test_snmp_default_route and test_snmp_loopback in BSL testing, because BSL is layer2 which don't have BGP neighbors and default route.
Summary:
Skip test_snmp_default_route and test_snmp_loopback in BSL testing, because BSL is layer2 which don't have BGP neighbors and default route.
Remove @pytest.mark.bsl
> Skip default route and loopback case in BSL testing 

- tests/pc/test_lag_2.py
When test_lag_db_status testcase is run with the dut_lag parameter is "unknown" (test_lag_db_status[unknown|unknown]), the testcase fails with the following error: KeyError: 'unknown', at the time it tries to access the namespace_id value from the lag_facts dictionary with the lag name as the key. The testcase checks that if the dut_lag parameter is "unknown", the test should run for all the portchannels. But at this point, this check is after the testcase tries to access the namespace_id value based on the lag name, leading to failure when the dut_lag parameter is "unknown".
Fix: The testcase should first get the list of portchannels if the dut_lag is "unknown", and then fetch the namespace_id for the portchannels.
Summary:
> fix for test_lag_db_status run with dut_lag param as unknown

- tests/qos/files/qos_params.j2c.yaml
- tests/saitests/py3/sai_base_test.py
- tests/saitests/py3/sai_qos_tests.py
This PR is in continuation of PR# https://github.com/sonic-net/sonic-mgmt/pull/8149
which was originally part of PR# https://github.com/sonic-net/sonic-mgmt/pull/6946
The existing QoS (test_qos_sai.py) is written to accommodate a single asic on a single Dut. But, we require the same tests to be executed against a T2 chassis (with single/multi-asic linecards) and multi-asic pizza boxes.
Summary:
This PR is in continuation to above PR's mentioned
1.Qos test cases failed with intermittent errors
Two issues are addressed here :
1.The dscp queue mapping for LossyQueue Test changed in config file to map to queue 1 of traffic-class instead of  0  since disabling the tx and filling up the queue 0  prevents the lacp packets going out and port channel goes down
2.During Qos test on …
> Improvising qos tests by tunning the qos params for single_asic, single_dut_multi_asic and  multi_dut

- tests/snmp/test_snmp_queue.py
platform
Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>
(cherry picked from commit 38cb1337201d5f2d9f9f1c3fa9f438d907e41be0)
Summary:
Fixes # [(issue)](https://github.com/sonic-net/sonic-mgmt/issues/8934)
test_snmp_queue was modified to get keys "QUEUE|*" from config_db in https://github.com/sonic-net/sonic-mgmt/pull/6744.
This has to be modified to get keys from all namespace config_db on mulit-asic platform.
Currently, test tries to retrieve from host config_db and skips the test for multi-asic platform.
Test is currently skipped for supervisor node, but should not be skipped for supervisor node of packet chassis.
1. Modified to get interfaces with queue configuration from all namespaces.
2. The test case was not checking the right field in snmp_interfaces SNMP result. Test …
> [snmp][multi-asic]: Fix test_snmp_queue to support multi-asic platform

- tests/telemetry/telemetry_utils.py
Summary:
Fixes # (issue) 24668984
Need to add reset-failed such that telemetry can restart properly after restoring telemetry back to default config
Code change
Pipeline
> Add reset-failed after restoring telemetry config

- tests/common/utilities.py
Summary:
Testcase test_memory_exhaustion failed on dualtor due to:
```
if isinstance(population, _Set):
population = tuple(population)
if not isinstance(population, _Sequence):
>           raise TypeError("Population must be a sequence or set.  For dicts, use list(d).")
E           TypeError: Population must be a sequence or set.  For dicts, use list(d).
```
Fix the testcase issue on dualtor when it need to select one host to run test.
Pass list type parameters in random.sample().
Run test case locally with the change and it passed.
> Use list to fix wrong population type error

- tests/show_techsupport/test_auto_techsupport.py
In module `show_techsupport/test_auto_techsupport.py`, it will delete auto techsupport feature `lldp` and add it again. But when adding, it misses the parameter `available-mem-threshold`. This will cause inconsistent between previous running config and current running config, and cause unnecessary config reload. In this PR, we add the parameter `available-mem-threshold` when adding auto techsupport feature. Meanwhile, PR #9123 is unnecessary when updating auto techsupport feature, so revert part of PR #9123. 
Summary:
In module `show_techsupport/test_auto_techsupport.py`, it will delete auto techsupport feature `lldp` and add it again. But when adding, it misses the parameter `available-mem-threshold`. This will cause inconsistent between previous running config and …
> Add parameter `available-mem-threshold` when adding auto-techsupport-feature in module `show_techsupport/test_auto_techsupport.py`. 

- tests/cacl/test_cacl_function.py
- tests/common/templates/default_acl_rules.json
- tests/common/utilities.py
- tests/crm/conftest.py
- tests/crm/test_crm.py
Cherry pick conflict #9523 and #9312
Summary:
Cherry pick conflict #9523 and #9312
> [cherry pick] #9523 Fix PR #9312 for KeyError and AttributeError in 202012

- tests/qos/test_qos_sai.py
- tests/saitests/py3/sai_qos_tests.py
This reverts commit 9dd33d792b533ac49f836e4566c9c34dbce0ecc3.
Summary:
most of qos sai case failed because :
```
"  File \"saitests/py3/sai_qos_tests.py\", line 24, in <module>",
"    from switch import (switch_init,",
"ImportError: cannot import name 'sai_thrift_read_pg_occupancy' from 'switch' (saitests/py3/switch.py)"
```
RCA:
#8546 and #9464 have dependency, should double commit PR https://github.com/sonic-net/sonic-mgmt/pull/8664 first.
revert #9464, and request Raghav cherry pick #8664 asap.
> Revert "add overflow_egress for PGDropTest multi-asic (#9464)"

- tests/qos/test_tunnel_qos_remap.py
Summary:
observed duplicated code in test_pfc_pause_extra_lossless_active between
https://github.com/sonic-net/sonic-mgmt/blob/d8dc4cce01626f4ca89250a9fa1c728e41411a7d/tests/qos/test_tunnel_qos_remap.py#L466
and
https://github.com/sonic-net/sonic-mgmt/blob/d8dc4cce01626f4ca89250a9fa1c728e41411a7d/tests/qos/test_tunnel_qos_remap.py#L470
remove duplicated code
> remove duplicated script for test_pfc_pause_extra_lossless_active

- ansible/roles/test/files/ptftests/advanced-reboot.py
Summary: Currently dual tor warmboot fails w/ control plane not ready for warmboot. This is because the test expects 2 responses for every ping packet sent to Loopback. This expectation is not correct after PR https://github.com/sonic-net/sonic-mgmt/pull/9089 is merged.
Update the testcase to now only expect 1 icmp response for every icmp packet sent to Loopback0.
Dualtor warmboot fails w/ below error:
```
2023-08-17 18:14:39 : Send   100 Received   100 servers->t1
2023-08-17 18:14:41 : Send   500 Received   500 t1->servers
2023-08-17 18:14:41 : Data plane state transition from partial to up (500)
2023-08-17 18:14:42 : Send    10 Received     0 ping DUT
2023-08-17 18:14:45 : --------------------------------------------------
2023-08-17 18:14:45 : Fails:
2023-08-17 18:14:45 …
```
> [advanced-reboot][dualtor] Update Loopback0 ping test: expect same count for sent and rcvd packets

- tests/fdb/test_fdb.py
Summary:
Fixes #9457 
This PR is to reduce the time cost of `test_fdb` on dualtor-64 topology.
Before this change, the `test_fdb` costs over 4 hours.
Now it takes around 20 minutes after we run the test on less dummy MAC addresses. 
This PR is to fix #9457.
Use less dummy MAC address on dualtor-64 topology.
The change is verified on a dualtor-64 testbed.
```
collected 4 items                                                                                                                                                          
fdb/test_fdb.py::test_fdb[ethernet]  ^HPASSED                                                                                                                           [ 25%]
fdb/test_fdb.py::test_fdb[arp_request]  ^H ^HPASSED …
```
> Reduce time cost of test_fdb on topology dualtor-64

- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary: Add xfail on TD3 202305+ images, and skip test on 7050qx, dualtor (202012).
> [advanced-reboot] Update skip and xfail conditions for test_advanced_reboot

- tests/show_techsupport/test_auto_techsupport.py
Faulty revert part of PR #9123, so recreate a PR to recover. 
Summary:
Faulty revert part of PR #9123, so recreate a PR to recover.
> Recover docker's available mem threshold after module show_techsupport/test_auto_techsupport.py running.

- ansible/roles/test/files/ptftests/py3/IP_decap_test.py
Summary:
Fixes #9595
Remove the unneeded calls to `unicode()` to fix #9595
ran test_decap.py on 202205 with this change and confirmed it works
> [sonic-mgmt 202205] Remove 'unicode()' calls for py3 conversion in decap test

- ansible/roles/test/files/ptftests/py3/populate_fdb.py
Summary:
#9526 introduced this issue.
More fixes are needed in 202205 branch for PTF python3 migration.
Test failed with error:
File \"ptftests/py3/populate_fdb.py\", line 129, in __prepareVmIp", "    vmIp[vlan] = ipaddress.ip_address(unicode(config[\"addr\"])) + 1", "NameError: name 'unicode' is not defined"
In Python3, unicode is not needed.
N/A
> [py3 migration] [202205] fix incompatible py3 usage in populate_fdb.py

- tests/qos/test_tunnel_qos_remap.py
Summary:
Fixes # (https://github.com/sonic-net/sonic-mgmt/issues/8720)
The test will go to dead loop if the pfc_pause_test fails.  For details please check the issue.
Fix test issue (https://github.com/sonic-net/sonic-mgmt/issues/8720)
Don't catch exceptions in the pfc_pause_test function.
Run test with manual made failure in pfc_pause_test, after 5 time's retry, test failed as expected.
Remove the manual made failure, test passed.
> Fix a test issue in test case test_pfc_pause_extra_lossless_standby/active

- tests/generic_config_updater/conftest.py
Summary: Update the syslog ignore regex to ignore valid ERR message
Fixes # (issue) ADO: 24418747
Ignore valid log analyzer ERR message. In test_syslog, GCU will reset-failed service if syslog reach 'start-limit-hit' by design.
Add the known ERR message in ignoreRgex.
E2E test
> [GCU] Update syslog ignore regex

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Issue https://github.com/sonic-net/sonic-buildimage/issues/16165
Changes added in the PR https://github.com/sonic-net/sonic-buildimage/pull/15487 to support SNMP over IPv6 does not handle if mgmt IP address is obtained via DHCP.
Skip the sonic-mgmt SNMP IPv6 related tests in 202211 so that the https://github.com/sonic-net/sonic-buildimage/pull/15487 can be reverted.
> [SNMP][IPv6]: Skip SNMP IPv6 related tests in 202211 branch.

- tests/generic_config_updater/test_ntp.py
Summary: Update NTP ActiveState check
Fixes # (issue) ADO: 24867106
That is possibility that the ActiveState still in activating. We need to wait for it in active state.
Update the check with retry if failed
E2E test
> [GCU] Update NTP ActiveState check

- tests/show_techsupport/test_auto_techsupport.py
Summary:
There are 2 formats of syslog lines (before and after the rsyslog is started), and the test has only considered 1 of them when parsing the timestamp. The timestamp got by the test code is incorrect and will cause parser error if the log line is in the other format.
The syslog format before the rsyslog is running:
2022-12-22T11:55:48.606301+00:00 sonic systemd-modules-load[410]: Inserted module 'mlxbf_tmfifo'
After:
Aug  9 06:27:50.351965 r-tigris-26 NOTICE syncd#SDK: [SAI_OBJECT.NOTICE] ./src/mlnx_sai_object.c[251]- sai_object_type_get_availability_impl: Got SAI_OBJECT_TYPE_NEXT_HOP availability, #0 TYPE=SRV6_SIDLIST : 188944
Fix a test issue in parsing the syslog timestamp in test_auto_techsupport.py.
Try one format, if gets the ParserError exception, try the other format. …
> Fix a test issue of test_auto_techsupport.py

- tests/qos/test_buffer.py
Summary:
Added missed configuration in the calculation of headroom.
Related configuration: #2860
Fix failed tests on setups with 800G:
- tests/qos/test_buffer.py::test_port_auto_neg
- tests/qos/test_buffer.py::test_lossless_pg[6]
- tests/qos/test_buffer.py::test_lossless_pg[3-4]
Added missed config
Executed failed tests.
Now they are passing
> [Mellanox] Added missed config in headroom calculation for 800G ports

- tests/platform_tests/mellanox/check_sysfs.py
The logic of _is_fan_speed_in_range is not correct, we should check low_threshold < fan_speed_get <high_threshold, because there is a tolerance for min speed and max speed. Additionally, the return should be moved to the end, otherwise, it just checks one fan, and the loop will be ended.
Summary:
Fix fan speed check issue
Checking low_threshold < fan_speed_get <high_threshold instead of fan_min_speed < fan_speed_get < fan_max_speed
Run test_restart_swss
Any
Any
> [Mellanox] Fix check fan speed issue

- tests/common/platform/device_utils.py
- tests/platform_tests/cli/test_show_platform.py
Cisco-8000 platforms added support to display the PSU led colors. This has caused test failures since scripts are hard-coded to expect 'N/A' as the led color for these platforms.
Fixes 8/1 PSU related failures from https://migsonic.atlassian.net/browse/MIGSMSFT-246
PSU tests cases fail due to expecting `N/A` PSU led state, when actual colors are now displayed.
Remove the `cisco-8000` led color filter from psu test scripts in order for tests to pass using the default logic.
> Cisco-8000 psu led support

- tests/iface_namingmode/test_iface_namingmode.py
In PR #9256, we use function `delete_running_config` to delete pg lossless profile in running config, which will cause orchagent coredump. Actually, from SAI side, they don't support such usage. So in module `iface_namingmode/test_iface_namingmode.py`, after case `test_config_interface_speed` running, we use our fixture `core_dump_and_config_check` to do config reload to recover config, thus revert this PR. 
Summary:
Fixes #9256 
In PR #9256, we use function `delete_running_config` to delete pg lossless profile in running config, which will cause orchagent coredump. Actually, from SAI side, they don't support such usage. So in module `iface_namingmode/test_iface_namingmode.py`, after case `test_config_interface_speed` running, we use our fixture `core_dump_and_config_check` to do config …
> Revert PR #9256 "Remove pg lossless settings of port speed in module iface_namingmode/test_iface_namingmode.py".

- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Caught exception while initializing thermal manager in case test_thermal_control_load_invalid_value_json on S6100 platform.
thermal control is not supported by Dell for S6000 and S6100 platforms.
SKIP test thermal control related cases for S6100 platform
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/6051.
run platform_tests/test_platform_info.py
> [202012] SKIP test thermal control related cases for S6100 platform

- ansible/group_vars/sonic/variables
- tests/qos/qos_sai_base.py
enable qos-sai scripts for cisco 8800-LC-48H-C48 platform
Summary:
Enables support for a new asic and new card using that asic
enable qos-sai scripts for cisco 8800-LC-48H-C48 platform
On local system, patched the change and tested with test qos sai XOFF test
> enable cisco 8800-LC-48H-C48 platform for pac asic

- tests/platform_tests/daemon/test_syseepromd.py
Summary:
fix assertion on the test_syseepromd.py, tests failed over a comparison of irrelevant values.
tests cases failed with error:
Failed: DB data present before and after restart does not match, data_after_restart {'keys': [u'EEPROM_INFO|0x22', u'EEPROM_INFO|0x21', u'EEPROM_INFO|Checksum', u'EEPROM_INFO|TlvHeader', u'EEPROM_INFO|0xfd', u'EEPROM_INFO|0x2b', u'EEPROM_INFO|0x29', u'EEPROM_INFO|0x28', u'EEPROM_INFO|State', u'EEPROM_INFO|0x2a', u'EEPROM_INFO|0x26', u'EEPROM_INFO|0x23', u'EEPROM_INFO|0x25', u'EEPROM_INFO|0xfe', u'EEPROM_INFO|0x24'], 'data': {u'EEPROM_INFO|0x29': {'Value': '2022.08-5.3.0010-9600', 'Name': 'ONIE Version', 'Len': '21'}, u'EEPROM_INFO|0x28': {'Value': 'x86_64-mlnx_msn4600C-r0', 'Name': 'Platform Name', 'Len': '64'}, u'EEPROM_INFO|State': …
> Update assert on test_syseepromd.py (#8236)

- .azure-pipelines/pr_test_scripts.yaml
Summary:
This allows testing the teamd retry count feature with SONiC neighbors deployed as part of PR tests.
Add `platform_tests/test_advanced_reboot.py::test_warm_reboot` to the list of t0-sonic test cases to run.
> Enable warm-reboot test case on T0-sonic PR tests

- tests/platform_tests/api/conftest.py
Platform API server on Dell sometimes takes more than 5 seconds to setup. This is because all the later API's seem to work fine, and only test_get_name fails. Increasing the timeout would help in getting the setup finished and be able to run the test. 
Summary:
> [platform][s6100] increase timeout in wait_for to 10 seconds to invoke platform API server

- tests/lldp/test_lldp.py
Summary:
test_lldp failed on 4600 platform sometimes. But can't reproduce it locally, add debug info for further investigation.
```
>           assert nei_lldp_facts['ansible_lldp_facts'][neighbor_interface]['neighbor_sys_name'] == duthost.hostname
E           AssertionError
collect_techsupport_all_duts = None
config_facts = {'ACL_TABLE': {'DATAACL': {'policy_desc': u'DATAACL', 'ports': [u'PortChannel101', u'PortChannel102', u'PortChannel103...te_limit_interval': u'600', 'state': u'enabled'}, ...}, 'BGP_DEVICE_GLOBAL': {'STATE': {'tsa_enabled': u'false'}}, ...}
dut_system_description = u'SONiC Software Version: SONiC.20220531.37 - HwSku: Mellanox-SN4600C-C64 - Distribution: Debian 11.7 - Kernel: 5.10.0-18-2-amd64'
duthost    = <MultiAsicSonicHost str2-msn4600c-acs-03> …
```
> Add debug info in test_lldp for AssertionError

- tests/snmp/memory.py
Summary:
16303901
The case failed on 7050qx which is a low memory device
Reserve 256M memory for the system to avoid DUT out of memory
Run original case
snmp/test_snmp_memory.py::test_snmp_memory_load[str2-7050qx-32s-acs-01] PASSED  
Low memory device
> [test_snmp_memory_load] reserver 256M free memory

- tests/qos/qos_sai_base.py
- tests/qos/test_tunnel_qos_remap.py
- tests/saitests/py3/sai_base_test.py
- tests/saitests/py3/sai_qos_tests.py
Previously, on Nvidia devices, to make port congestion, we disable the port. So, if a LAG port is used as the tx port in the test, the LAG port will go down in 90s because the lacp pdus are also blocked, which will fail the tests. Therefore, we skip the test on the LAG port for QoS tests. Currently, to make the LAG port also support QoS test, we block the data plane queue instead of disabling the port. This change will work for all topo on Nvidia devices.
Summary:
Make Qos sai test support LAG port 
we block the data plane queue instead of disabling the port. So the control plane still work normally.
Run qos sai test on t1-lag-64 topo
Any
Any
> [Nvidia] Fix qos sai test for supporting LAG port 

- tests/copp/copp_utils.py
Summary:
This PR is to fix the permission of `/tmp` to unblock the copp test.
Because of issue https://github.com/sonic-net/sonic-buildimage/issues/16034 , the `/tmp` directory in syncd docker has incorrect permission.
This PR unblocked the issue by setting the permission to `777` before `apt install`.
This PR is to fix permission for `/tmp` to unblock copp test.
Change the permission of `/tmp` to `777` before `apt get`.
The change is verified on a MSN-2700 device
```
collected 14 items                                                                                                                                                         
copp/test_copp.py::TestCOPP::test_policer[str-msn2700-02-ARP]  ^HPASSED …
```
> Fix permission of /tmp to unblock copp test

- tests/platform_tests/test_reboot.py
Summary:
PR sonic-net/sonic-buildimage#16083 introduced `cpu_wdt` service on Celestica E1031 platform. The `cpu_wdt` service periodically sends keep alive message to watchdog via "watchdogutil arm -s <timeout>" command. This may affect the test result of `test_watchdog_reboot`. This PR add one step to stop the `cpu_wdt` service before doing watchdog reboot on the DUT.
On Celestica-E1031 platform, stop the `cpu_wdt` service before doing watchdog reboot.
Add one step in `test_watchdog_reboot`.
Verified on Celestica-E1031 testbed.
> [HLX] Stop cpu_wdt service before doing watchdog reboot

- .azure-pipelines/testbed_health_check.py
Add testbed health check scripts for testbed automatic monitor and recover.
SONiC Elastictest is onboarding to support testbed health automatic monitor and recover. It needs to do some health checks on testbeds.
SONiC Elastictest is onboarding to support testbed health automatic monitor and recover. It needs to do some health checks on testbeds.
Add a new script `testbed_health_check.py`.
Verify locally.
Example:
` ./testbed_health_check.py -t vms2-4-t0-2700 -i ../ansible/str --tbfile ../ansible/testbed.yaml -o testbed_health_check_result_vms2-4-t0-2700 --log-level info`
It will print the basic testbed check result to the console, if you specify an output file, it will write to it as well.
> Add testbed health check scripts for testbed automatic monitor and recover

- ansible/devutil/inv_helpers.py
- ansible/devutil/ssh_session_repo.py
- ansible/devutil/testbed.py
- ansible/ssh_session_gen.py
Summary:
This changes adds scripts for generating SecureCRT session files for testbeds.
To use it, we can run commands like `python3 ssh_session_gen.py -i inventory -o /data/sessions/testbeds -p some_securecrt_session.ini` to generate all session files in our testbed.
We can also use `-n <testbed-name-regex>` to scope to only the testbed we like to keep or use `-t <testbed-file> to use another testbed YAML config, if needed.
And to generate the SSH session files for SecureCRT, we need to do a few pre-steps:
- Install pycryptodome package via pip3.
- Prepare an existing session file as template (passed by -p). Since our dev machine might not have direct access to your testbed machines, this allows us to inherit the session settings from the template file, such as SSH proxies, fonts and …
> Add scripts for generating SecureCRT session files for testbeds.

- tests/common/snappi_tests/common_helpers.py
- tests/common/snappi_tests/pfc_packet.py
- tests/common/snappi_tests/read_pcap.py
- tests/common/snappi_tests/traffic_generation.py
- tests/snappi_tests/pfc/files/helper.py
Summary: The validate PFC frame PR introduced a bug with a `TypeError` since the default parameters of the `config_capture_pkt` were not set correctly. This PR also fixes a frame checker bug where the result was always set to False. Both bugs have been fixed in this PR.  There is also a duration limit of pause flow frames added compared to the continuous flow of pause frames previously - this will improve the reliability of the snappi capture module since the capture module is heavily unreliable when traffic flows continuously. 
bug fix
tested on lab device
> [Snappi] Validate PFC frame bug fix

- ansible/devutil/inv_helpers.py
- ansible/devutil/ssh_session_repo.py
- ansible/ssh_session_gen.py
Summary:
Add SSH config generation support for test bed. To execute it, we can specify the output format as ssh. 
And here is an example of generate the ssh config file to "/data/sessions/ssh_config" with jumpbox set to "devvm".
```bash
~/env-python3/bin/python3 ssh_session_gen.py -i inventory -o /data/sessions/ssh_config --format ssh --ssh-config-params "PROXYJUMP=devvm"
```
This change is supposed to help developers accessing the testbed in daily work.
This change improves the current SecureCRT testbed generation script by addin the SSH config generator as a new backend.
Generate all sessions and check the result:
N/A
N/A
> Adding SSH config generation support.

- tests/snappi_tests/pfcwd/files/pfcwd_basic_helper.py
- tests/snappi_tests/pfcwd/files/pfcwd_multi_node_helper.py
Summary: Cherry-pick PR for 202012 from #9567 
Lab device
> [202012][Snappi] PFCWD Tolerance Fixes (#9567)

- tests/bgp/conftest.py
- tests/bgp/test_bgpmon.py
- tests/bgp/test_bgpmon_v6.py
- tests/common/helpers/generators.py
- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Tests for IPv6-based bgpmon for T2 chassis
(Cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/9233)
Add new test cases for IPv6-based bgpmon session and skip IPv4-based bgpmon session on T2
Added bgpmon tests that use IPv6 loopback4096 address as source and initiate v6 BGPMon session to exabgp on PTF
Tested on T2 chassis
> [202205] Add support for BGPMon over IPv6 for T2 chassis (#9233)

- tests/generic_config_updater/test_bgp_sentinel.py
Summary:
Testcase of bgp sentinel config for generic updater apply-patch
This PR is to verify the usage of 'config apply-patch' works on bgp sentinel config
Add bgp sentinel config to dut and check if config change as expected
Run test of sonic-mgmt/tests/generic_config_updater/test_bgp_sentinel.py on KVM
> Add bgp sentinel support in GCU

- tests/conftest.py
- tests/test_posttest.py
Summary:
Add a parameter to specify show tech since in post-test. The default value is `yesterday`, which keeps the same behavior as current code.
To collect show tech result of all time spans, please specify `--posttest_show_tech_since='-1hour'`.
Add a parameter to specify show tech since in post-test.
Add parameter `--posttest_show_tech_since` in `conftest.py` and use it in `test_collect_techsupport`.
Verified on physical DUT with below parameters:
* Do not specify `--posttest_show_tech_since`
* Empty string: `--posttest_show_tech_since=`
* Collect all time span: `--posttest_show_tech_since='@0'`
* Collect since 1 hour ago: `--posttest_show_tech_since='-1hour'`
> [post-test] Add a param to specify show tech since in post-test

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
test_trap_config_save_after_reboot is skipped on 202205 since docker_inram enabled for 7050qx and 7060.
Need skip it on 202305 and later branch too
Skip the case
Run pipeline
7050qx 7060
> skip test_trap_config_save_after_reboot on 7050qx and 7060 for 202305 branch

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Skip below testcases via conditional mark:
* `platform_tests/test_secure_upgrade.py` on M0/Mx with 202305 release.
* `container_hardening/test_container_hardening.py` on SONiC 202305 and older releases.
Skip below testcases via conditional mark:
* `platform_tests/test_secure_upgrade.py` on M0/Mx with 202305 release.
* `container_hardening/test_container_hardening.py` on SONiC 202305 and older releases.
Update conditional mark files.
Verified on physical testbed.
> Skip test_container_privileged and test_secure_upgrade on m0/mx with 202305 release

- tests/fdb/conftest.py
Backport #9487  changes into 202205
> [202205] [fdb] Address failures on td2 asics for fdb mac move test

- tests/common/helpers/base_helper.py
- tests/common/helpers/ptf_tests_helper.py
- tests/qos/qos_sai_base.py
- tests/qos/test_qos_sai.py
- tests/saitests/py3/sai_qos_tests.py
Summary: Currently, the test case testQosSaiDscpPGMapping only verify the DSCP to PG mapping for regular traffic. The mapping of IPinIP traffic (decapsulated in IPinIP tunnel) is not tested. Hence a new test case is being added to verify the mapping for IPinIP traffic. This PR adds two tests to test IP-IP packet forwarding in both "uniform" and "pipe" decap mode on the DUT.
Fixes  (issue) #9576 
See summary.
1. Generate IPinIP traffic from ptf using ptfadapter. The destination IP in the outer layer of the packets should be the loopback (10.1.0.32) of DUT.
2. Ingress the packets to DUT, verify the packets are decapsulated.
3. Check the PG counter within the DUT (using saithrift api), ensure the mapping is as expected.
> [QoS] DSCP to PG mapping for IP-IP traffic

- ansible/library/shell_cmds.py
- tests/common/devices/sonic.py
This is an enhancement for sanity check or other places where call `shell_cmds` with batch of commands, in such case currently we only tell `one of these commands` failed. 
This PR helps to print the failed command so user would know which service has issue in `failed_cmds` list
Summary:
current impl:
```
"cmds": ["docker exec pmon supervisorctl status", "docker exec snmp supervisorctl status", "docker exec lldp supervisorctl status", "docker exec database supervisorctl status", "docker exec bgp supervisorctl status", "docker exec database supervisorctl status", "docker exec lldp supervisorctl status", "docker exec swss supervisorctl status", "docker exec syncd supervisorctl status", "docker exec teamd supervisorctl status"]}}, "msg": "At least running one of the commands …
```
> [ansible] Update shell_cmds.py to print exact failed service

- tests/platform_tests/test_reboot.py
Backport #9745
PR sonic-net/sonic-buildimage#16083 introduced cpu_wdt service on Celestica E1031 platform. The cpu_wdt service periodically sends keep alive message to watchdog via "watchdogutil arm -s " command. This may affect the test result of test_watchdog_reboot. This PR add one step to stop the cpu_wdt service before doing watchdog reboot on the DUT.
Add one step in test_watchdog_reboot to stop the cpu_wdt service before doing watchdog reboot.
Verified on Celestica-E1031 testbed.
Summary:
> [202012][HLX] Stop cpu_wdt service before doing watchdog reboot (#9745)

- tests/conftest.py
- tests/test_posttest.py
Backport #9771 
Add a parameter to specify show tech since in post-test. The default value is yesterday, which keeps the same behavior as current code. To collect show tech result of all time spans, please specify --posttest_show_tech_since='-1hour'.
Add parameter --posttest_show_tech_since in conftest.py and use it in test_collect_techsupport.
Verified on physical DUT with below parameters:
* Do not specify --posttest_show_tech_since
* Empty string: --posttest_show_tech_since=
* Collect all time span: --posttest_show_tech_since='@0'
* Collect since 1 hour ago: --posttest_show_tech_since='-1hour'
Summary:
> [202205][post-test] Add a param to specify show tech since in post-test (#9771)

- tests/conftest.py
- tests/test_posttest.py
Backport #9771 
Add a parameter to specify show tech since in post-test. The default value is yesterday, which keeps the same behavior as current code. To collect show tech result of all time spans, please specify --posttest_show_tech_since='-1hour'.
Add parameter --posttest_show_tech_since in conftest.py and use it in test_collect_techsupport.
Verified on physical DUT with below parameters:
* Do not specify --posttest_show_tech_since
* Empty string: --posttest_show_tech_since=
* Collect all time span: --posttest_show_tech_since='@0'
* Collect since 1 hour ago: --posttest_show_tech_since='-1hour'
Summary:
> [202012][post-test] Add a param to specify show tech since in post-test (#9771)

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: Skip `test_dir_bcast.py` on t0-backend topology. 
```
ipfwd/test_dir_bcast.py::test_dir_bcast SKIPPED
-------------------------------- generated xml file: /var/src/sonic-mgmt-int/tests/logs/tr.xml --------------------
================= short test summary info ==================
SKIPPED [1] ipfwd/test_dir_bcast.py: Unsupported topology.
============================ 1 skipped in 17.68 seconds ===============
```
> Skip test_dir_bcast test on t0-backend

- ansible/roles/test/files/ptftests/arista.py
- ansible/roles/test/files/ptftests/py3/advanced-reboot.py
- ansible/roles/test/files/ptftests/py3/arista.py
- ansible/roles/test/files/ptftests/py3/host_device.py
- ansible/roles/test/files/ptftests/py3/sad_path.py
- ansible/roles/test/files/ptftests/sonic.py
- tests/common/fixtures/advanced_reboot.py
Summary:
Manually cherry-pick PR #9550
Migrate test_advanced_reboot's PTF script to Python3
This PR migrate test_advanced_reboot's PTF script to Python3.
2to3 and manually code change
Test with KVM testbed, physical testbed 3800 and PR test.
Summary:
> [202305][PTF python3 migration] Modify test_advanced_reboot PTF script (#9550)

- tests/bgp/test_traffic_shift.py
- tests/conftest.py
In module `bgp/test_traffic_shift.py`, test case `test_TSA_B_C_with_no_neighbors` will stop bgp container, which may generate expected core dump files. But in fixture `core_dump_and_config_check`, when new core dump files generates, no matter if they are expected or unexpected. In order to avoid config reload caused by expected core dump files, we will add expected core dump files into dict `duts_data[duthost.hostname]["pre_core_dumps"]` of fixture `core_dump_and_config_check`. 
Summary:
In module `bgp/test_traffic_shift.py`, test case `test_TSA_B_C_with_no_neighbors` will stop bgp container, which may generate expected core dump files. But in fixture `core_dump_and_config_check`, when new core dump files generates, no matter if they are expected or unexpected. In order to …
> Skip checking expected core dump in module `bgp/test_traffic_shift.py`.

- tests/vlan/test_vlan.py
Summary:
test_vlan case failed at teardown phase, in which it found 'Failed to get port by bridge port ID' error syslog.
ADO 24807870
Bridge port was removed and as part of the removal all FDB entries are removed. As part of this notification, Broadcom sends 'SAI_FDB_EVENT_AGED'. When Sonic orchagent code checks for bridge_port, it was already removed. 
Ignore 'Failed to get port by bridge port ID' in test_vlan.py
run test_vlan.py
> Ignore 'Failed to get port by bridge port ID' in test_vlan.py

- tests/platform_tests/test_idle_driver.py
In test_idle_driver, the current_driver file, which is where we get the current driver value, could be nonexistent on AMD platform. Not considering that could result in error.
Summary:
Fix bug on AMD platform
Fix bug
Run test on previously failed 7215 device
> [platform_tests] fix getting current idle driver error

- tests/fdb/test_fdb.py
In some FDB test runs packets are not received by the PTF server. Add DUT's portstat in the test log to help debugging this issue.
Test case improvement
- [x ] 202012
- [x ] 202205
Add DUT's portstat output to debug any PTF server packet drop issues.
> Add portstat to debug FDB packet delay

- .azure-pipelines/run-test-elastictest-template.yml
- .azure-pipelines/test_plan.py
Summary:
Support to pass lock_wait_timeout_seconds in the template
Support to pass lock_wait_timeout_seconds in the template
> [Elastictest]Support to pass lock_wait_timeout_seconds in the template

- tests/conftest.py
We have a field `CustomMsg` to record the result of fixture `core_dump_and_config_check` in DB. But previously, we record the result of core dump check and config check combinationly, either core dump check fails or config check fails, we will record false in this filed. In this PR, we will specific this filed, and record this two type of results respectively. And the format of this filed in DB is 
```
{
'DutChekResult': {
'core_dump_check_pass': core_dump_check_pass,
'config_db_check_pass': config_db_check_pass
}
}
```
Summary:
We have a field `CustomMsg` to record the result of fixture `core_dump_and_config_check` in DB. But previously, we record the result of core dump check and config check combinationly, either core dump check fails or config check fails, we will …
> Specific field CustomMsg to distinguish config reload or core dump. 

- tests/acl/test_acl_outer_vlan.py
Summary:
`_setup_arp_responder` may be skipped in func `pre_running_hook`, which would cause `_teardown_arp_responder` error in func `post_running_hook` because arp_responder is not running.
The issue fixed by this PR was also fixed in https://github.com/sonic-net/sonic-mgmt/pull/7748, which should not be backport, so manually update it.
```
{
"changed": true,
"cmd": ["supervisorctl", "stop", "arp_responder"],
"delta": "0:00:00.166638",
"end": "2023-08-29 13:01:45.802702",
"failed": true,
"msg": "non-zero return code",
"rc": 1,
"start": "2023-08-29 13:01:45.636064",
"stderr": "",
"stderr_lines": [],
"stdout": "arp_responder: ERROR (no such process)",
"stdout_lines": ["arp_responder: ERROR (no such process)"]
}
```
Add ignore_errors to `_teardown_arp_responder`
Run tests. …
> [202205][acl_outer_vlan] Fix teardown error in test_acl_outer_vlan

- ansible/roles/test/files/ptftests/vxlan-decap.py
- tests/vxlan/test_vxlan_decap.py
Summary:
Revert modification to PTF script vxlan-decap.py in PR #9603 and #9761
Test failure due to Python3 migration.
Revert PR #9603 and #9761
Test with physical t0-2700 testbed.
> [202205]Revert vxlan-decap.py PTF Python3 migration

- ansible/roles/test/files/ptftests/py3/dhcpv6_counter_test.py
- ansible/roles/test/files/ptftests/py3/dhcpv6_relay_test.py
- tests/dhcp_relay/test_dhcpv6_relay.py
Fix test_dhcpv6_relay.py case test_dhcp_relay_default and test_dhcpv6_relay_counter failure on dualtor.
The issue is test gap after code commit of https://github.com/sonic-net/sonic-dhcp-relay/pull/42 in master 
and https://github.com/sonic-net/sonic-dhcp-relay/pull/40 in 202012. 
Summary:
Fix test_dhcpv6_relay.py case test_dhcp_relay_default and test_dhcpv6_relay_counter failure on dualtor.
1. Based on latest dhcprelay code, dhcpv6 relay will use loopback0 ipv6 address as source ip when relay packets to server.
So test case need modify to send Relay-Reply to loopback0 ipv6 address.
2. Improve test case behavior, enable source ipv6 check during test
3. remove unused option order sequence related test code
4. check loopback0 Relay-Reply counter in dualtor instead of vlan …
> Fix dual-tor dhcpv6 relay test cases failure in latest image

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
https://github.com/sonic-net/sonic-mgmt/pull/9630/ was added skip IPv6 related SNMP test cases in 202211 branch.
But the condition checks for branch name instead of release.
This is causing PR checker to fail as the branch name in PR checker is the PR number and not 202211
Change condition to look for 202211 in release and not branch.
> Skip condition to skip SNMP IPv6 test case in 202211 branch.

- tests/memory_checker/test_memory_checker.py
Cherry-pick of #9193
This refactor introduces many changes:
- Better reliability on systems with small RAM capacity
- Better control over the amount of memory consumed by the test
- Remove the external dependency on the `stress` utility
- Faster overall runtime for the test
- A new testcase making sure that monit recovers if memory was above threshold for only a single cycle
- Remove check of new/old syntax. It makes no sense to change the product code and then test that, that's not shipping code.
Summary: Refactor the test_memory_checker test
> [202205][memory-checker] Refactor the test_memory_checker test

- tests/qos/test_qos_sai.py
- tests/saitests/py3/sai_qos_tests.py
Addressing the following issues:
1. In T0 topology, since the packet can take any port in a Vlan, the get_multiple_flows function runs in to infinite loop. To avoid this, we set a limit on the loop to 20, and if it runs out, we use the port that packet is actually taking instead of the user-provided one. 
2. addressing the keyerror in BufferPoolWatermark testcase.
3. Addressed the assert error in AllPortQWatermark for T0.
@XuChen-MSFT : Pls review.
> Cisco: Fixing get_multiple_flows for T0.

- ansible/roles/test/files/ptftests/advanced-reboot.py
- ansible/roles/test/files/ptftests/arista.py
- ansible/roles/test/files/ptftests/py3/arista.py
- ansible/roles/test/files/ptftests/py3/host_device.py
- ansible/roles/test/files/ptftests/py3/sad_path.py
- ansible/roles/test/files/ptftests/sonic.py
- tests/common/fixtures/advanced_reboot.py
Reverts sonic-net/sonic-mgmt#9550, fe0d44d68c0fa17838dd91e2e83d7545b07c118f
This is causing a breakage when running on physical testbeds, due to (at least) the following error:
```
Exception in thread Thread-7:
File \"/usr/lib/python3.7/threading.py\", line 917, in _bootstrap_inner
self.run()
File \"/usr/lib/python3.7/threading.py\", line 865, in run
self._target(*self._args, **self._kwargs)
File \"ptftests/py3/advanced-reboot.py\", line 1664, in send_in_background
'not (arp and ether src {}) and not tcp'.format(self.test_params['dut_mac']))
File \"ptftests/py3/advanced-reboot.py\", line 1648, in apply_filter_all_ports
scapyall.attach_filter(port.socket, filter_expression)
AttributeError: module 'scapy.all' has no attribute 'attach_filter'
```
> Revert "[PTF python3 migration] Modify test_advanced_reboot PTF script"

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
There is a deadlock to merge this sonic-swss submodule PR: https://github.com/sonic-net/sonic-buildimage/pull/16455 as it has a prerequisite to merge this PR : https://github.com/sonic-net/sonic-mgmt/pull/9873 before that
Both PR's are dependent on each other and hence both PR merge is blocked.
To fix and come out of the deadlock, solution is to skip macsec tests in t0-sonic testbed and let the sonic-mgmt PR  https://github.com/sonic-net/sonic-mgmt/pull/9873 merge . We will introduce the macsec again and let is pass for the sonic-swss submodule update PR
> Skip tests macsec tests for t0-sonic

- tests/bgp/test_bgp_sentinel.py
Summary:
Python is updated and dict_keys would not plus list.
Convert dict_keys to list
Run testcase and testcase would pass.
> [VM]Convert bgp sentinel target route type

- tests/bgp/conftest.py
Cherry Pick https://github.com/sonic-net/sonic-mgmt/pull/9423 to 202205
Summary:
Cherry Pick https://github.com/sonic-net/sonic-mgmt/pull/9423 to 202205
> [Cherry Pick] 202205 fix bgp update timer failure on dual tor

- tests/bgp/test_bgp_slb.py
Cherry-Pick https://github.com/sonic-net/sonic-mgmt/pull/9239 to 202205
Summary:
Cherry-Pick https://github.com/sonic-net/sonic-mgmt/pull/9239 to 202205
Fixes test_bgp_slb_neighbor_persistence_across_advanced_reboot test failure on dual tor.
In script using setup_interfaces for bgp connections which already use toggle_all_simulator_ports_to_enum_rand_one_per_hwsku_frontend_host_m and enum_rand_one_per_hwsku_frontend_hostname for muxcable toggle operation/selection on dualtor.
But script use toggle_all_simulator_ports_to_rand_selected_tor and rand_one_dut_hostname in test case, which may not same as
setup_interfaces and finally cause test case failure.
> [Cherry Pick] 202205 bgp slb dual tor issue

- tests/common/plugins/sanity_check/__init__.py
Summary:
If something wrong with testbed, sanity check will try to recover testbed with reboot method.
But after https://github.com/sonic-net/sonic-mgmt/pull/9453, it uses safe reload instead, test case will terminate in reboot function, that's why sanity check won't fail and exit, it will run next test case, and same termination will happen.
That's not we expect, if unhealthy testbed can't be recovered, the whole pipeline will exit.
In reboot funciton, it uses pytest_assert to terminate the running. It raised Failed exception which is inherited from BaseException.
```
if safe_reboot:
pytest_assert(wait_until(wait + 300, 20, 0, duthost.critical_services_fully_started),
>                         "All critical services should be fully started!")
E           Failed: All …
```
> Change to capture BaseException instead of Exception in sanity check

- azure-pipelines.yml
This is a follow up of the fix earlier made to skip macsec tests from pipeline t0-sonic via this PR : https://github.com/sonic-net/sonic-mgmt/pull/9874
Even with this PR merged, there was still failures in one of the tests run in t0-sonic pipeline.
Further debugging showed that, we have this special param, to **enable macsec** (as shown below) which results in macsec setup with macsec enabled links which will fail again.
REF: 
```
specific_param:
t0-sonic:
- name: bgp/test_bgp_fact.py
param: "--neighbor_type=sonic --enable_macsec --macsec_profile=128_SCI,256_XPN_SCI" <<<<<<<
- name: macsec
param: "--neighbor_type=sonic --enable_macsec --macsec_profile=128_SCI,256_XPN_SCI"   <<<<<<<<
~ …
```
> Skip bgp/test_bgp_fact.py for sonic-t0 testbed

- tests/common/fixtures/duthost_utils.py
- tests/generic_config_updater/test_dhcp_relay.py
**Why I did it**
This PR is created to resolve GCU DHCP_Relay issues in kvm test failure in [Update submodule sonic-utilities to the latest HEAD](https://github.com/sonic-net/sonic-buildimage/pull/16267)
Summary: Fixed PR issues in fixture/duthost_utilites.py to solve vlan addition changes on Port
Signed-off-by: Rida Hanif [rida.hanif@xflowresearch.com](mailto:rida.hanif@xflowresearch.com)
> Fix for GCU Dhcp_Relay issue in KVM test failure 

- tests/bgp/conftest.py
- tests/bgp/test_bgp_gr_helper.py
Cherry Pick https://github.com/sonic-net/sonic-mgmt/pull/8084 to 202012
Summary:
Cherry Pick https://github.com/sonic-net/sonic-mgmt/pull/8084 to 202012
Fix ansible connection to server issue during testing, when T1 has multiple neighbors (In testing failure it's 24), sometime parallel bgp related check will failure due to connection to server failure.
> [Cherry Pick] 202012 limit parallel_run cct tasks number to avoid connection issue

- tests/bgp/test_bgp_suppress_fib.py
Summary:
This PR is to fix test failure in `test_bgp_suppress_fib.py`.
The error message is 
```
Failed: Vrf:Vrf1 - route:1000:1001::1/128 is not in queued state
```
The failure is because the advertised IPv6 route from T0 is denied by route-map on T1.
To work around the issue, I changed the route to `/64`.
This PR is to fix test failure in `test_bgp_suppress_fib.py`.
Change the advertised route to `/64`'
Verified on a SN2700 T1 testbed. Now the tese can pass
```
ollected 5 items                                                                                                                                                                                                             
bgp/test_bgp_suppress_fib.py::test_bgp_route_with_suppress[default]  ^HPASSED …
```
> Fix bgp suppress fib test

- tests/telemetry/events/host_events.py
Summary:
Add tests for events when container is stopped (sent when container is initially stopped) and when container is down (container has been down for some time)
Add tests
Manual/pipeline
> Add container stopped and container down events test

- tests/qos/files/qos_params.gb.yaml
Updating qos.yaml params for topo-t2 accounting for the fill_egress_plus_one API that is used by cisco-8000 specific code.
In this PR:
1. Updated the Xoff numbers for 100G_300m.
2. Reverted the limits for all wrr cases to 80.
3. Reduced the number of iterations for PGDrop to 50 for non-HBM T2 ingress scenario and  to 30 for HBM T2 ingress scenario. This is done account for PTF timeout that happens when the iterations are current value of 100.
> cisco: Update qos.yaml params for GB topo-t2.

- ansible/roles/test/files/ptftests/advanced-reboot.py
- ansible/roles/test/files/ptftests/arista.py
- ansible/roles/test/files/ptftests/py3/arista.py
- ansible/roles/test/files/ptftests/py3/host_device.py
- ansible/roles/test/files/ptftests/py3/sad_path.py
- ansible/roles/test/files/ptftests/sonic.py
- tests/common/fixtures/advanced_reboot.py
Reverts sonic-net/sonic-mgmt#9819, e014b5603ac3ef4a77ce3af8679704cc2f5e83db
This is causing a breakage when running on physical testbeds, due to (at least) the following error:
```
Exception in thread Thread-7:
File \"/usr/lib/python3.7/threading.py\", line 917, in _bootstrap_inner
self.run()
File \"/usr/lib/python3.7/threading.py\", line 865, in run
self._target(*self._args, **self._kwargs)
File \"ptftests/py3/advanced-reboot.py\", line 1664, in send_in_background
'not (arp and ether src {}) and not tcp'.format(self.test_params['dut_mac']))
File \"ptftests/py3/advanced-reboot.py\", line 1648, in apply_filter_all_ports
scapyall.attach_filter(port.socket, filter_expression)
AttributeError: module 'scapy.all' has no attribute 'attach_filter'
```
> Revert "[202305][PTF python3 migration] Modify test_advanced_reboot PTF script (#9550)"

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
`warmboot` is not fully supported on dualtor yet, and will cause orchagent crash and leave the testbed in bad state. For some reason sanity check wasn't able to recover the device and any following tests might fail. 
Before I root cause the warmboot issue and figure out a long term solution, submitting this PR to disable `test_wr_arp` to avoid warmboot.
Ran it on dualtor testbed and saw the test case be skipped.
> [dualtor] update skip logic of test_wr_arp for dualtor

- ansible/roles/vm_set/tasks/main.yml
Summary:
Fix the MAC address of `br1` on server during add/remove topo.
As we configure the MGMT IP address of server on a virtual bridge `br1`, it's MAC address is not fixed if it's not manually set. This makes the MAC address of `br1` changeable during add/remove topo. When the MAC address change, the other servers may not update their ARP table in time and temporarily lose the connection. In this PR, I added one step in add/remove topo to fix the MAC address of `br1` to avoid potential packet loss.
Fix the MAC address of `br1` on server during add/remove topo.
Add one step to explicitly set the MAC address of `br1`.
* For physical testbeds, verified on physical servers.
* For virtual testbeds, verified by PR test.
> [Testbed] Fix the MAC address of br1 on server during add/remove topo

- ansible/roles/fanout/tasks/sonic/fanout_sonic_202205.yml
Summary:
Refactor the ansible playbook for deploying SONiC 202205 fanout switches. Use ansible docker module instead of `sleep` to wait for `teamd` container stop.
Refactor the ansible playbook for deploying SONiC 202205 fanout switches. Use ansible docker module instead of `sleep` to wait for `teamd` container stop.
Use ansible docker module instead of `sleep` to wait for `teamd` container stop.
Verified by re-deploy `Nokia-7215` fanout switches.
> [Fanout] Refactor ansible-playbook for deploying SONiC 202205 fanout switch

- tests/platform_tests/mellanox/test_check_sfp_using_ethtool.py
Summary:
It seems that testcase test_check_sfp_using_ethtool is failing with the below traceback on Mellanox with 202305 image.
```
File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 116, in _multicall
raise exception.with_traceback(exception.__traceback__)
File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 80, in _multicall
res = hook_impl.function(*args)
File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 192, in pytest_pyfunc_call
result = testfunction(**testargs)
File "/azp/_work/32/s/tests/platform_tests/mellanox/test_check_sfp_using_ethtool.py", line 38, in test_check_sfp_using_ethtool
ethtool_sfp_output = duthost.command(
File "/azp/_work/32/s/tests/common/devices/multi_asic.py", line 118, in _run_on_asics
return …
```
> Fix testcase failure for test_check_sfp_using_ethtool

- ansible/roles/test/files/ptftests/arista.py
When runnig warm-reboot or fast-reboot test, sometimes we can encounter the error:[Functional] [fast-reboot] | Exception occured when parsing logs from VM: msg='module' object has no attribute '_strptime' type=<type 'exceptions.AttributeError'>.
This issue is a python2.7 known issue(https://stackoverflow.com/a/22476843/2514803), and it was fixed in sonic-mgmt before. But the relevant fix was removed by mistake by the PR: https://github.com/sonic-net/sonic-mgmt/pull/7968/files.  However, the relevant fix still exists on the branch 202205 and before. So,  add it back.
Summary:
Fix issue: https://stackoverflow.com/a/22476843/2514803
import _strptime
run warm-reboot or fast-reboot time 
Any
T0
> Fix _strptime type issue 

- ansible/roles/vm_set/tasks/main.yml
- ansible/setup-management-network.sh
New PR test issue detected: ptf's mgmt-ip not ready after 5 mins during add-topo.
Sample:
[Test plan 64fe6dd33c845190cd12fd82: GitHub_PullRequest_PR_15836_BUILD_359729_JOB_kvmtest-t0_by_Elastictest - Elastictest (elastictest.org)](https://elastictest.org/scheduler/testplan/64fe6dd33c845190cd12fd82?testcase=testbed_q_sonic-elastictest-prod-vmss-D8s-v3_19465_vms-kvm-t0_prepare.log&type=prepare)
This is caused by [#9877](https://github.com/sonic-net/sonic-mgmt/pull/9877), it causes the newly initialized br1 to have the wrong mac address so ptf’s mgmt-ip is not reachable.
The issue only can be reproduced on the VM that haven’t set up br1 yet, so it can pass the PR test.
The fix will remove br1 to refresh, so that this kind of corner case will be gated away as expected.
Summary:
Fixes # …
> [PR test issue]Fix br1 mac issue

- tests/dhcp_relay/test_dhcpv6_relay.py
DHCPv6 per interface counter automation script coverage
Summary:
1. Cover basic function of DHCPv6 per interface counter. 
2. Script support both old counter STATE_DB format and new format.
```
sonic-db-cli STATE_DB hgetall 'DHCPv6_COUNTER_TABLE|Vlan1000'
{'Unknown':'0','Solicit':'0','Advertise':'0','Request':'0','Confirm':'0','Renew':'0','Rebind':'0','Reply':'0','Release':'0','Decline':'0','Reconfigure':'0','Information-Request':'0','Relay-Forward':'0','Relay-Reply':'0','Malformed':'0'}
```
```
sonic-db-cli STATE_DB hgetall 'DHCPv6_COUNTER_TABLE|Vlan1000'
{'TX': "{'Unknown':'0','Solicit':'0','Advertise':'0','Request':'0','Confirm':'0','Renew':'0','Rebind':'0','Reply':'0','Release':'0','Decline':'0','Reconfigure':'0','Information-Request':'0','Relay-Forward':'0','Relay-Repl …
```
> dhcpv6 per-interface counter automation script coverage

- tests/common/devices/sonic.py
Add one basic function of is_host_service_running for the sonic device. So, it is convenient for other tests to check the service status.
Summary:
Add one basic function of is_host_service_running for the sonic device. So, it is convenient for other tests to check the service status.
Add one basic function of is_host_service_running 
Call this function
Any
Any
> Add is_host_service_running for sonic device

- tests/configlet/util/common.py
Summary: Remove transceiver check in add rack scenario.
Fixes # (issue) 24817075
The transceiver data such as rx_power and tx_power is different as expected.
For example, the rxpower before test is
{'rx1power': '0.547', 'rx2power': 'N/A', 'rx3power': 'N/A', 'rx4power': 'N/A', 'temperature': '24.652', 'tx1bias': '7.106', 'tx1power': '0.617', 'tx2bias': 'N/A', 'tx2power': 'N/A', 'tx3bias': 'N/A', 'tx3power': 'N/A', 'tx4bias': 'N/A', 'tx4power': 'N/A', 'voltage': '3.32'} 
which is different with 
{'rx1power': '0.549', 'rx2power': 'N/A', 'rx3power': 'N/A', 'rx4power': 'N/A', 'temperature': '24.0', 'tx1bias': '7.014', 'tx1power': '0.609', 'tx2bias': 'N/A', 'tx2power': 'N/A', 'tx3bias': 'N/A', 'tx3power': 'N/A', 'tx4bias': 'N/A', 'tx4power': 'N/A', 'voltage': '3.32'}
Remove the transceiver …
> [configlet] Remove transciver check

- tests/sflow/test_sflow.py
Why I did it
For  sflow_bug#13407: After migration of hsflowd version v2.0.51-26, When we are deleting the agent-id, hsflowd is referring for the eth0 interface and expecting samples in that interface. 
(This is with the updated hsflowd , When you start hsflowd with no explicit agent-id configured, it will run an "election" to decide which IP address to adopt.)
How I did it
Modified the script to check for mgmt_ip.
How to verify it
Post upgrade to latest version of hsflowd, run the script and make sure that it passes.
Signed-off-by: Gokulnath-Raja <Gokulnath_R@dell.com>
Co-authored-by: mohanapriya-meganathan <mohanapriya.m1@dell.com>
Script Log 
[test_sflow_log.txt](https://github.com/sonic-net/sonic-mgmt/files/12473632/test_sflow_log.txt)
> RCA is When we are deleting the agent-id, hsflowd is referring to eth0

- tests/cacl/test_ebtables_application.py
- tests/common/helpers/dut_utils.py
- tests/conftest.py
- tests/ixia/pfcwd/test_pfcwd_basic.py
- tests/ixia/pfcwd/test_pfcwd_burst_storm.py
- tests/platform_tests/reboot_timing_constants.py
- tests/process_monitoring/test_critical_process_monitoring.py
- tests/tacacs/test_ro_disk.py
Summary:
All PR test of 202012 branch failed at static analysis stage with below error:
```
E   ConftestImportFailure: (local('/var/src/sonic-mgmt/tests/platform_tests/conftest.py'), (<type 'exceptions.NameError'>, NameError("name 're' is not defined",), <traceback object at 0x7f97b817ba00>))
```
The reason is that module 're' is not imported in file `tests/platform_tests/reboot_timing_constants.py`. The issue has been there for a long time. Recently the sonic-mgmt docker image was upgraded to use python3 as default and somehow exposed this issue.
The fix is to add `import re` to the affected file. Only 202012 branch has this issue.
> Fix 're' not defined issue in 202012 PR test static analysis

- tests/crm/test_crm.py
Modified prefixes from 3.3.3.0,3.3.3.1 to 5.5.5.0,5.5.5.1
Summary:
Currently, we add routes of 3.3.3.0/24, 4.4.4.0/24 and arps of 3.3.3.1, 4.4.4.1
However 3.3.3.1 is the address of the inband interface and should not be used. Adding inband interface's ip brings down the iBGP neighbors
We are changing 3.3.3.0 and 3.3.3.1 to 5.5.5.0 and 5.5.5.1 respectively
modified prefixes 3.3.3.0 and 3.3.3.1 to 5.5.5.0 and 5.5.5.1 respectively
Tested the testcases on a multiasic chassis
> Modified prefixes from 3.3.3.0,3.3.3.1 to 5.5.5.0,5.5.5.1

- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:
Add xfail on TD3 202305+ images, and skip test on 7050qx, dualtor (202012).
This is manual cherry-pick to 202305 of #9615.
> [advanced-reboot][202305] Add skip and xfail conditions for test_advanced_reboot

- tests/bgp/conftest.py
- tests/bgp/test_bgp_slb.py
- tests/bgp/test_bgp_update_timer.py
Cherry Pick https://github.com/sonic-net/sonic-mgmt/pull/9239 to 202012
Summary:
Cherry Pick https://github.com/sonic-net/sonic-mgmt/pull/9239 to 202012
Fixes test_bgp_slb_neighbor_persistence_across_advanced_reboot test failure on dual tor.
In script using setup_interfaces for bgp connections which already use toggle_all_simulator_ports_to_enum_rand_one_per_hwsku_frontend_host_m and enum_rand_one_per_hwsku_frontend_hostname for muxcable toggle operation/selection on dualtor.
But script use toggle_all_simulator_ports_to_rand_selected_tor and rand_one_dut_hostname in test case, which may not same as
setup_interfaces and finally cause test case failure.
> [Cherry Pick] 202012 fix bgp slb test case dual tor issue

- ansible/roles/test/files/ptftests/py3/dhcpv6_counter_test.py
- ansible/roles/test/files/ptftests/py3/dhcpv6_relay_test.py
- tests/common/plugins/conditional_mark/tests_mark_conditions_202205.yaml
- tests/dhcp_relay/test_dhcpv6_relay.py
Summary:
Cherry pick (https://github.com/sonic-net/sonic-mgmt/pull/9842) to 202205
Cherry pick (https://github.com/sonic-net/sonic-mgmt/pull/9842) to 202205
Code gap is big, solution refined based on 202205 base code.
dhcp_relay/test_dhcpv6_relay.py::test_dhcp_relay_default
dhcp_relay/test_dhcpv6_relay.py::test_dhcpv6_relay_counter
> [Cherry Pick] 202205 Fix dual-tor dhcpv6 relay test cases failure

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Add xfail on 7050cx3 in 202305+ images.
> To xfail pfcwd_warm_reboot on 7050cx3 in 202305

- tests/dualtor_io/test_tor_bgp_failure.py
Summary:
When BGP is shutdown, default route n/a, linkmgrd will write unhealthy.
So let's change the expected health for the standby to `unhealthy`.
```
dualtor_io/test_tor_bgp_failure.py::test_active_tor_shutdown_bgp_sessions_upstream[active-standby] PASSED                                                                            [100%]
===================================================================================== warnings summary =====================================================================================
```
> [dualtor-io] Change the health expectation for bgp shutdown case

- ansible/roles/test/files/helpers/arp_responder.py
- tests/acl/test_acl_outer_vlan.py
Summary:
The PR is to fix `test_acl_outer_vlan.py`.
The test cases are failing because 
1. The `arp_responder.py` in `ansible/roles/test/files/helpers/` is not Python3 compatible. 
There are two `arp_responder.py` script. One is [ansible/roles/test/files/helpers/arp_responder.py](https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/roles/test/files/helpers/arp_responder.py), the other one is [tests/scripts/arp_responder.py](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/scripts/arp_responder.py). 
The outer vlan tests are using the first one, which is not Python3 compatible.
2. The TCP connection between `ptfadapter` and `ptf_nn_agent` is not stable enough. The connection is being reset frequently, which results in packet drop. 
To workaround, I reestablish the …
> Fix acl outer vlan test

- tests/platform_tests/counterpoll/test_counterpoll_watermark.py
Summary:
This PR is to stabilize `test_counterpoll_queue_watermark_pg_drop`.
The error message
```
msg = "no {} maps found in COUNTERS_DB".format(map_prefix)
>               pytest_assert(map_output, msg)
E               Failed: no PG maps found in COUNTERS_DB
```
It's because there is not enough delay after enabling the counterpoll.
This PR is to stabilize `test_counterpoll_queue_watermark_pg_drop`.
Add some delay after enabling counterpoll.
Verified on a SN2700 device
```
collected 1 item                                                                                                                                                           
platform_tests/counterpoll/test_counterpoll_watermark.py::test_counterpoll_queue_watermark_pg_drop[str-msn2700-02]  ^HPASSED …
```
> Stabilize counterpoll watermark test

- tests/common/helpers/snmp_helpers.py
- tests/snmp/test_snmp_loopback.py
Summary:
Cherry-pick with conflict resolution of https://github.com/sonic-net/sonic-mgmt/pull/8824
SNMP over Loopback ipv6 is currently being skipped.
https://github.com/sonic-net/sonic-buildimage/pull/15487 -fixes snmp over ipv6.
After the above fix, SNMP over Loopback and management should work.
Remove skip of ipv6.
> [IPv6][SNMP][202205]: Remove skip of IPv6 loopback testing

- tests/snmp/test_snmp_queue.py
Summary:
Cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/9115
test_snmp_queue was modified to get keys "QUEUE|*" from config_db in https://github.com/sonic-net/sonic-mgmt/pull/6744.
This has to be modified to get keys from all namespace config_db on mulit-asic platform.
Currently, test tries to retrieve from host config_db and skips the test for multi-asic platform.
Test is currently skipped for supervisor node, but should not be skipped for supervisor node of packet chassis.
1. Modified to get interfaces with queue configuration from all namespaces.
2. The test case was not checking the right field in snmp_interfaces SNMP result. Test case was checking for "description" of each interface, from description, interface name was extracted and checked if the …
> [snmp][multi-asic][202205]: Fix test_snmp_queue to support multi-asic platform

- tests/common/utilities.py
Summary:
Testcase test_memory_exhaustion failed on dualtor due to:
```
if isinstance(population, _Set):
population = tuple(population)
if not isinstance(population, _Sequence):
>           raise TypeError("Population must be a sequence or set.  For dicts, use list(d).")
E           TypeError: Population must be a sequence or set.  For dicts, use list(d).
```
This is a cherry-pick of #9586 
Fix the testcase issue on dualtor when it need to select one host to run test.
Pass list type parameters in random.sample().
Run test case locally with the change and it passed.
> [202205] Use list to fix wrong population type error

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
For Cisco-8000 devices, skipping test_nhop_group_member_order_capability for all release before 2022305
Summary:
Skipping test_nhop_group_member_order_capability for all release before 2022305
> Skipping test_nhop_group_member_order_capability for all release before 2022305

- ansible/roles/test/files/ptftests/dhcpv6_counter_test.py
- ansible/roles/test/files/ptftests/dhcpv6_relay_test.py
- tests/dhcp_relay/test_dhcpv6_relay.py
Summary:
Cherry pick (https://github.com/sonic-net/sonic-mgmt/pull/9842) to 202012
Cherry pick (https://github.com/sonic-net/sonic-mgmt/pull/9842) to 202012
Code gap is big, solution refined based on 202012 base code.
dhcp_relay/test_dhcpv6_relay.py::test_dhcp_relay_default
dhcp_relay/test_dhcpv6_relay.py::test_dhcpv6_relay_counter
> [Cherry Pick] 202012 Fix dual-tor dhcpv6 relay test cases failure

- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
- tests/platform_tests/test_reboot.py
Related to https://github.com/sonic-net/sonic-mgmt/pull/9160 which got merged into master and 202305. Here committing changes to 202205 branch. est watchdog reboot is not supported in Cisco Platform x86_64-8102_64h_o-r0 having old fpga. MSFT cannot upgrade from the Ref. point to newer FPD. Upgrading to newer fpd will brick the box for old proto. Hence skipping this only for Cisco Platform x86_64-8102_64h_o-r0
Summary:
Related to https://github.com/sonic-net/sonic-mgmt/pull/9160 which got merged into master and 202305. Here committing changes to 202205 branch. est watchdog reboot is not supported in Cisco Platform x86_64-8102_64h_o-r0 having old fpga. MSFT cannot upgrade from the Ref. point to newer FPD. Upgrading to newer fpd will brick the box for old proto. Hence …
> Watchdog skip 202205

- ansible/roles/eos/tasks/ceos_config.yml
Summary:
Host dir like "/data/ceos/ceos_vms6-1_VM0100" is mounted to cEOS container as flash disk. This dir contains all kinds of configuration files that may affect cEOS behaviors.
For example, older version of cEOS has file ".arista_archive_config" which enables archiving of configs every 1 minute. On newer version of cEOS, this config file is removed by default.
However, after cEOS is upgraded, the left over ".arista_archive_config" file will cause newer cEOS to archive configs every 1 minute by default.
To ensure that the cEOS container is always "cleanly" started, this change added code to always cleanup the mount dir before creating cEOS.
> Always cleanup cEOS mount dir before creating cEOS

- setup-container.sh
Summary:
The sonic-mgmt docker image has been updated to globally install all the packages in env-python3. Now, in the global python3 environment, we have all the required packages for running tests. Then it is unnecessary to have the env-python3 virtual environment. Before "env-python3" is deprecated in sonic-mgmt docker image, we can skip creating "env-python3" in the setup-container.sh script which is used for setting up sonic-mgmt container for user different than "AzDevOps" to solve permission issues of mapped directory.
This change added code to check if pytest is globally installed in python3 environment. If yes, then we can assume that all the env-python3 packages are also globally installed. Then we can skip creating env-python3 in setup-container.sh script.
Run …
> Conditionally install env-python3 in setup-container.sh

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
…te case
Summary:
test_lag_2.py::test_lag_db_status_with_po_update supports t1-64-lag topo.
Add t1-64-lag topo in conditions yaml file
Choose t1-64-lag testbed and run  test_lag_2.py::test_lag_db_status_with_po_update.
```
----------------------------------------------------------------------------------------------------- live log sessionfinish ------------------------------------------------------------------------------------------------------
08:23:24 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
=================== 24 passed, 3 warnings in 2551.00 seconds ===================
```
> Add t1-64-lag topo for test_lag_2.py::test_lag_db_status_with_po_update

- tests/common/plugins/ptfadapter/templates/ptf_nn_agent.conf.ptf.j2
- tests/vxlan/test_vxlan_ecmp.py
[Description] 
The system keep printing the following message, which lead to loganalyzer failure.
Sep  5 20:38:00.798086 m64-zz-2 ERR swss#orchagent: :- delOperation: VNET 'Vnet_v4_in_v4-0': Routes are still present
[Analysis]
Sometimes, after running the following two testcases, they could leave vnet routes in our system.
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_remove_route2[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_remove_route2[v6_in_v4]
For example: 
cisco@chu-dut:~$ show vnet routes all
...
vnet name        prefix                    endpoint                mac address    vni    status
Vnet_v4_in_v4-0  150.0.30.1/32             100.0.27.1,100.0.28.1                         inactive
Vnet_v6_in_v4-0  fddd:a150:a0::a102:1/128 …
> add vnet route cleanup and re-setup after test_vxlan_remove_route2

- ansible/roles/test/files/ptftests/py3/vxlan_traffic.py
- tests/vxlan/test_vxlan_ecmp.py
Pytest in python3 gets confused if a variable is named **setup** as it hunts for setup and teardown functions. In the recent python 3 conversion, this caused all the the vxlan ecmp tests to fail. SOme other failures were caused by python 3 conversion of ptf scripts as wells. These have been fixed this PR.
Summary:
> [testfix]Fixed failures caused by python 3 conversion.

- tests/route/test_route_flow_counter.py
Summary: Fix `test_route_flow_counter` when ran on supported platforms
When `test_route_flow_counter` is ran on unsupported platform, it fails due to `clear_route_flow_counter` fixture running which assumes that platform is supported.
Independent pytest fixtures can run even if one causes the test function to skip. The `clear_route_flow_counter` fixture should not run if the test is skipped (due to lack of support) so the appropriate fixture arg should be included to mark the dependency.
Added `skip_if_not_supported` as a dependency of `clear_route_flow_counter`. By doing this, if test is skipped because there is a lack of support then `clear_route_flow_counter` will not run.
Verified that test is skipped on unsupported platform
> Fix test_route_flow_counter

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
…_po_update case
Summary:
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/10031 to 202012.
> [202012]Add t1-64-lag topo for test_lag_2.py::test_lag_db_status_with_po_update

- tests/common/fixtures/duthost_utils.py
- tests/generic_config_updater/test_dhcp_relay.py
Testing possible fix for GCU Test_dhcp_relay.py
> [build] utilities fix for  GCU test_dhcp_relay.py

- tests/ipfwd/test_nhop_group.py
Summary:
Updated test nhop_group according to Nvidia ASICs behavior
Updated test nhop_group according to Nvidia ASICs behavior
Created dict with expected traffic redistribution for Nvidia-related ASICs
Removed test ignore for Mellanox/Nvidia platforms
Executed tests from file test_nhop_group.py
Nvidia
> [Mellanox] enable dynamic ecmp on Mellanox switches and updated test nhop_group per vendor

- ansible/library/conn_graph_facts.py
Summary:
24947066
Some sonic devices config the interface using interface name instead of interface alias, which causes graph facts mismatch.
Per device, get all ports first, and check whether the input is alias or name, if the input is interface alias, then modify it to interface name.
Deploy several testbeds, no issue
> [ansible/library/conn_graph_facts] convert interface aliases to interface names when all input links use aliases

- tests/common/config_reload.py
- tests/platform_tests/test_reload_config.py
Summary:
`test_reload_configuration_checks` failed occasionally due to:
1. `config reload` fails after reboot due to the delayed services are not active.
Enable `config_system_checks_passed` to check delayed services' states.
> [test_reload_config] Fix `test_reload_configuration_checks`

- tests/common/plugins/ptfadapter/templates/ptf_nn_agent.conf.ptf.j2
- tests/pc/test_po_update.py
On our dualtor test, the test_po_update_io_no_loss case failed because of excessive packet loss.  For example:
8:43:25 test_po_update.test_po_update_io_no_loss L0316 INFO   | match_count: 26206, send_count: 32401
After debug and investigation, we found the LACP communication is normal during the process. The cause of excessive packet loss is due to small rcv socket buffer of ptf_nn_agent.  On PTF side, the pytest uses a nn socket to communicate with ptf NN agent.  This socket's rcv buffer could lead to packet loss if the peer side could not handle the traffic asap.  All PTF threads are running on linux user space with common priority, if the server is not powerful enough or it's kinda busy, the ptf rcv thread may not be able to pull the pkts from socket buffer ASAP.
To improve this …
> reduce the burst rate for " test_po_update_io_no_loss"

- tests/saitests/py3/sai_base_test.py
Summary:
qos sai case encounter lots of  "KeyError: 'dst'" for master branch
```
ERROR: sai_qos_tests.PFCtest
File \"saitests/py3/sai_qos_tests.py\", line 1310, in runTest
pkt, int(self.test_params['pg']), asic_type))
File \"saitests/py3/sai_qos_tests.py\", line 246, in fill_leakout_plus_one
test_case.clients['dst'], \"dst\", dst_port_id)
KeyError: 'dst'
"======================================================================",
"ERROR: sai_qos_tests.PFCtest",
"----------------------------------------------------------------------",
"Traceback (most recent call last):",
"  File …
```
> [qos] fix keyerror dst

- tests/common/helpers/pfc_gen_t2.py
- tests/common/helpers/pfc_storm.py
- tests/common/templates/pfc_storm_sonic_t2.j2
- tests/common/templates/pfc_storm_stop_sonic_t2.j2
- tests/pfcwd/test_pfcwd_function.py
- tests/pfcwd/test_pfcwd_timer_accuracy.py
Summary:
- This PR fixes '_test_pfcwd_timer_accuracy_' test failures for **t2-chassis**.
- Currently, for '_t2_' chassis, the timer accuracy test fails w.r.t the issues related to PFC storm detection and restoration on the DUT.
- And also, this PR adds a new pfc_gen file specifically for 't2-chassis' w.r.t '_TestPfcwdFunc_' and '_TestPfcwdAllPortStorm_' test cases.
- PFC storm detection/restoration logic for t2-chassis w.r.t to the existing '_pfc_gen.py_' template is not working as expected.
- Due to this, the '_test_pfcwd_timer_accuracy_' , '_TestPfcwdFunc_' and '_TestPfcwdAllPortStorm_' tests fail for t2 multi-asic dut.
- By introducing a new template file for _t2-chassis_ which does bulk send from leaf fanout instead of sending 1 packet at a time, and also sends for a …
> PFCWD - Test fixes for t2-chassis

- ansible/TestbedProcessing.py
Various bug fixes and improvements to the TestbedProcessing script, mostly for T2 chassis testing:
- Add SlotId column to sonic_lab_links.csv.
- Quote string variables in lab INI output, since in T2 these can be a list that will otherwise not be parsed correctly by ansible.
- Add SwitchIds for fabric ASICs.
- Add model, serial, and base_mac fields for linecards.
- Fix hostvar filename to correctly match the case of the hostname in the inventory.
(will submit separate PRs for 202205 and 202012 due to conflicts)
This PR makes bug fixes and improvements to the TestbedProcessing script that are needed for T2 chassis testing.
These changes have been used internally at Arista for all sonic-mgmt testing.
> TestbedProcessing script fixes and improvements

- ansible/roles/vm_set/tasks/start.yml
Summary:
When the neighbor devices are specified to be the type vsonic, allow downloading a SONiC image if the file doesn't exist already. This matches the behavior that is present with veos, but requires the user to specify a file name.
This can (indirectly) be used to also have different SONiC images used for different testbeds.
This is needed to be able to easily run tests on servers with vsonic neighbors that don't already have a SONiC image downloaded.
Allow specifying the download URL, which will get used if the image doesn't already exist. (It may actually be useful to replace the existing SONiC image, so that a fixed image is used always, but for now, the image on disk takes precedence.) Also decompress the image if it is in gzip format.
Tested locally only, with …
> Add the ability to download a SONiC image for use as the neighbor image

- tests/platform_tests/daemon/test_chassisd.py
This is to fix flakiness in this test, that wait_data returned unsorted dictionary, but later when comparing unsorted dictionary, it is exact match -- if keys are the same but in different order, it will fail.
Summary:
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/9863
in `def collect_data`, sort return dictionary by keys and return in ordered_dictionary.
this function is used for `data_before_restart` and `data_after_restart`
before:
```
Failed: DB data present before and after restart does not match
data_after_restart = {'data': {u'CHASSIS_MIDPLANE_TABLE|SUPERVISOR0': {}, u'CHASSIS_MODULE_TABLE|LINE-CARD0': {}, u'CHASSIS_MODULE_TABLE|SU...IS 1', u'CHASSIS_MODULE_TABLE|LINE-CARD0', u'CHASSIS_MIDPLANE_TABLE|SUPERVISOR0', u'CHASSIS_MODULE_TABLE|SUPERVISOR0']} …
```
> [chassis] fix flakiness in test_chassisd.py

- tests/acl/test_acl_outer_vlan.py
Summary:
This PR is to stabilize `test_acl_outer_vlan.py`.
The test is flaky because of `arp_responder` running on ptf is not fully ready when the first test case starts to run.
This PR improve the test case by
1. Add a 10 seconds delay after starting `arp_responder`
2. Ping 3 times instead of 1 time to populate ARP entry.
This PR is to stabilize `test_acl_outer_vlan.py`.
1. Add a 10 seconds delay after starting `arp_responder`
2. Ping 3 times instead of 1 time to populate ARP entry
The change is verified on a SN2700 testbed.
```
collected 16 items                                                                                                                                                                                    
acl/test_acl_outer_vlan.py::TestAclVlanOuter_Egress::test_tagged_ …
```
> Stabilize acl_outer_vlan test

- tests/qos/files/qos_params.gb.yaml
- tests/qos/test_tunnel_qos_remap.py
- tests/qos/tunnel_qos_remap_base.py
- tests/saitests/py3/sai_qos_tests.py
Master PR: #9243
Summary:
Support the following tests for Cisco-8000:
- test_encap_dscp_rewrite[active-standby]
- test_tunnel_decap_dscp_to_queue_mapping
- test_tunnel_decap_dscp_to_pg_mapping
- test_xoff_for_pcbb (4)
Cisco-specific changes:
- Added qos.yml entries
- Leakout filling in various tests
- Packet sizing changes
Changes for all platforms:
- Some debuggability improvements
Support most PCBB tests for Cisco-8000.
Verified on Cisco-8000 dualtor platform.
> Cisco PCBB test support for 202305

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Collection of ipfwd/test_nhop_group.py::test_nhop_group_member_order_capability failed.
```
DEBUG:tests.common.plugins.conditional_mark:Found match "[{u'ipfwd/test_nhop_group.py::test_nhop_group_member_order_capability': {u'reason': u'Not supported before release 202305.', u'conditions': [u"release in ['201811', '201911', '202012', '202205', '202211']", u"asic_type in ['cisco-8000']"]}}]" for test case "ipfwd/test_nhop_group.py::test_nhop_group_member_order_capability[str3-s6100-acs-7-None]"
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File …
```
> Add missing skip section in ctests_mark_conditions.yaml

- azure-pipelines.yml
- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Revert the temporary Skips we did for bgp/test_bgp_fact.py, Skip macsec tests for sonic-t0 testsuite which is used to validate macsec.
> Revert Skip bgp/test_bgp_fact.py, Skip macsec tests for sonic-t0

- azure-pipelines.yml
- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Similar to PR's done in 202205
https://github.com/sonic-net/sonic-mgmt/pull/9874
https://github.com/sonic-net/sonic-mgmt/pull/9903
These changes will be reverted later (new PR similar to below one, to be raised in master) once sonic-swss submodule is updated in master branch
https://github.com/sonic-net/sonic-mgmt/pull/9909
> Temporarily skip macsec tests on sonic t0 testbed.

- tests/memory_checker/test_memory_checker.py
Summary:
The `test_memory_checker` is failing because of a timing issue.
```
tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzerError: match: 0
expected_match: 0
expected_missing_match: 5
Expected Messages that are missing:
.*restart_service.Restarting service 'telemetry'.
.Stopping Telemetry container.
.Stopped Telemetry container.
.Starting Telemetry container.
.Started Telemetry container.
```
This PR fix the issue by increasing the timeout for monit failure from 60 seconds to 80 seconds.
The `test_memory_checker` is failing because of a timing issue.
This PR fix the issue by increasing the timeout for monit failure from 60 seconds to 80 seconds.
Verified on a SN2700 testbed. The test is consistently passing after the change.
No.
> Stabilize test_memory_checker

- ansible/roles/test/files/ptftests/bfd_responder.py
- tests/vxlan/test_vxlan_ecmp.py
The bfd responder was creating a new discriminator for every attempt to create the same session. this causes BFD logic or SN2700 to throw errors. Also some tests were not doing cleanup which resulted in subsequent tests failing. This was also fixed.
Summary:
> [testfix] test cleanup and bfd_responder fix.

- tests/platform_tests/test_cpu_memory_usage.py
Changed mem threshold for msn4600c to 62 percent from 60 percent.
Summary:
ADO:25002224
> [testfix] test_cpu_memory_usage_counterpoll threshold change.

- ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Cherry-pick #9009 to `202205` after resolving conflict.
This PR is to ignore log pattern
```
Error getting sensor data: dps460/#10: Can't read
```
The error log was seen on `Mellanox` platform. It has been confirmed that the log message has no impact, and it's only seen on old PSU. The new PSU will address the issue.
To reduce noise, we ignore the error log pattern.
**Case Number:** 00577909
This PR is to ignore a certain pmon error log pattern.
As the error log doesn't show up frequently, I verified the regex by running a python script.
The error message is seen on `Mellanox` devices for now.
> [202205] [cherry-pick] Ignore pmon error for getting sensor data

- ansible/roles/test/files/ptftests/bfd_responder.py
- tests/vxlan/test_vxlan_ecmp.py
The bfd responder was creating a new discriminator for every attempt to create the same session. this causes BFD logic or SN2700 to throw errors. Also some tests were not doing cleanup which resulted in subsequent tests failing. This was also fixed.
Summary:
> [202205][testfix] test cleanup and bfd_responder fix

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip below testcases on M0/Mx topology:
- bgp/test_bgp_queue.py
- generic_config_updater/test_pg_headroom_update.py
Skip below testcases on M0/Mx topology:
- bgp/test_bgp_queue.py
- generic_config_updater/test_pg_headroom_update.py
Updated conditional mark file.
Verified on Mx testbed.
> [M0/Mx] Skip unsupported testcases on M0/Mx topology

- tests/qos/files/qos_params.gb.yaml
- tests/qos/test_qos_sai.py
- tests/saitests/py3/sai_qos_tests.py
1, For cisco-8000, pkts_num_fill_min is the maximum packet number in sms before evicted to hbm. These packets are also counted in buffer pool watermark after evicted to hbm.
2, Added some margin to BufferPoolWatermarkTest. 8140 B packets has 99.8% probability to increase SQ buffer counter by 1, and the 99.8% is not accurate for each test run that we can not count on. And we can't use 8156 B packet since one packet will occupy 2 hbm blocks.
Summary:
Verified it in testbed.
```
---------------------------------- generated xml file: /run_logs/6237-qos/2023-09-19-21-59-25/qos/test_qos_sai.py::TestQosSai::testQosSaiBufferPoolWatermark.xml ---------------------------------- …
```
> Fix BufferPoolWatermarkTest failure for cisco long-link

- tests/qos/qos_sai_base.py
- tests/qos/test_qos_sai.py
The Watermark tests need the values for destination port, but qos.yaml params are read for the source port only. Until the infra provides a way to get the dst qos parameters, we need to skip the tests.
> Cisco: Skip Watermark test for multi-DUT cases.

- tests/qos/qos_sai_base.py
Adding a check for single-asic for cisco-8000 T2 platforms.
For cisco-8000 platforms (currently named as "gb" in qos.yaml), we have to fallback to the qos.yaml parameters listed for topo-any in case of single-ASIC tests(src & dst ASICS are same). For multi-asic and multi-DUT tests, the qos.yaml provides the parameters under topo-t2.
So we add a logic to check if the current test is single-asic and use topo-any for the parameters, and if not, use topo-t2.
> Added support of Cisco gb asic in T2 role

- .azure-pipelines/pr_test_scripts.yaml
Summary:
Due to the TYPE 7 changing for MACsec, MACsec tests break the submodule,sonic-swss/sonic-sairedis, updating.
Disable MACsec tests in the pr_test script.
Check Azp
> [pr_test]: Disable MACsec tests

- tests/acl/templates/acltb_test_stress_acl_table.j2
After running "test_stress_acl.py", the DUT could not create new L3 table anymore.
If we run "test_acl.py" after "test_stress_acl.py", it will report 400 TCs error with ：
Expected Messages that are missing:
E               .Created ACL table.
For exmaple, after running "test_stress_acl.py", then we try to create a L3 table manually：
cisco@mth64-m5-2:~$ date
Fri 22 Sep 2023 09:27:32 PM UTC
cisco@mth64-m5-2:~$ sudo config acl add table DATA_INGRESS_IPV4_TEST_2 L3 -s ingress -p PortChannel1011,PortChannel1010,PortChannel1013,PortChannel1012,PortChannel1015,PortChannel1014,PortChannel1017,PortChannel1016,PortChannel1019,PortChannel1018,PortChannel105,PortChannel104,PortChannel107,PortChannel106,PortChannel101,PortChannel103,PortChannel102,PortChannel109,PortChannel108,PortChannel1024,PortChann …
> use a custom table type for stress test

- tests/tacacs/test_ro_disk.py
Summary:
The Test Case  tacacs/test_ro_disk.py::test_ro_disk, in finally block a reboot is performed, currently, the condition for reboot to be successful is to check the docker is running, the enhancement done is to wait till all the critical process in the docker are up and the interfaces are also up for all the line cards in case the supervisor is rebooted
The Particular improvement is required due to the changes with respect to PR https://github.com/sonic-net/sonic-buildimage/pull/16213.
The Particular improvement is required due to the changes with respect to PR https://github.com/sonic-net/sonic-buildimage/pull/16213. 
Assertion for successful reboot of supervisor card is updated to check all the process are up on critical docker and interfaces are also up on line cards.
Ran the …
> test_ro_disk:  Enhancement for reboot of supervisor card

- tests/saitests/py3/sai_qos_tests.py
Adding COUNTER_MARGIN to ingress drop counter for below test scenarios to avoid flakey results.
- TestQosSai.testQosSaiPfcXoffLimit
- TestQosSai.testQosSaiPfcXonLimit 
- TestQosSai.testQosSaiLossyQueue
Summary:
Sometimes for dnx, few extra ipv6 NS/RA pkt received from VM which get added to counter value & may give inconsistent test results.
Adding COUNTER_MARGIN to provide room to 2 extra pkt incase, extra traffic received. This will avoid inconsistent results on qos test.
Below tests are updated:
- TestQosSai.testQosSaiPfcXoffLimit
- TestQosSai.testQosSaiPfcXonLimit 
- TestQosSai.testQosSaiLossyQueue
Sometimes for dnx, few extra ipv6 NS/RA pkt received from VM which get added to counter value & may give inconsistent test results.
Providing room for 2 pkts (COUNTER_MARGIN) …
> Adding COUNTER_MARGIN to Ingress drop counters for qos tests

- tests/gnmi/test_gnmi_configdb.py
Summary:
"show interface status" is wrong after gnmi incremental config, this command reads from APPL_DB, and we should read from CONFIG_DB.
Microsoft ADO: 25136266
Read CONFIG_DB to get admin_status.
Run gnmi end2end test.
> Fix test_gnmi_configdb_incremental_01 failure

- tests/common/fixtures/duthost_utils.py
This PR is created to resolve issues in KVM test which are failing in advance utilities HEAD PR. KVM Elastic test are failing in generic_config_updater/test_dhcp_relay.py file due to missing mode attribute.
Modified GCU fixtures/duthost_utilities.py to make it compatible for HEAD PR . We have added "switchport mode command" in duthost_utilites to add mode trunk on Ethernet4 so that it will allow addition of vlan membership on ports. Added a function to check "switchport mode explicitly". The check was missing in earlier case due to which all port are running "switchport" command twice and change mode everytime.
> GCU Fix for DHCP Head PR

- tests/telemetry/events/host_events.py
Summary:
event-down-ctr test is flaky because we run the test before monit changes are in place which means start delay for monit is at 5 minutes, so container_checker will not catch event.
Move test after monit config is changed
Manual/pipeline
> Run container_down test after monit config change

- tests/common/devices/arista.py
- tests/macsec/macsec_config_helper.py
- tests/macsec/profile.json
Following this PR : https://github.com/sonic-net/sonic-swss/pull/2892.
MSFT ADO : 25046448
Updated the profile.json files and  macsec config helper eos macsec key configuration to start using type 7 keys
Ran the sonic-mgmt testsuite using azure pipeline : https://dev.azure.com/mssonic/internal/_build/results?buildId=355362&view=results
```
256 cipher suite
---------------------
2023-09-05T21:28:49.8247891Z macsec/test_controlplane.py::TestControlPlane::test_wpa_supplicant_processes[256_XPN_SCI] PASSED [ 25%]
2023-09-05T21:29:40.7325077Z macsec/test_controlplane.py::TestControlPlane::test_appl_db[256_XPN_SCI] PASSED [ 50%]
2023-09-05T21:30:42.5996584Z macsec/test_controlplane.py::TestControlPlane::test_mka_session[256_XPN_SCI] PASSED [ 75%]
2023-09-05T21:40:10.1442889Z …
```
> Macsec type7 support for CAK keys 

- ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
If ntp server changes, local time stamp may jump and will cause the age value in lldpctl json output turns to negative time such as  '00:-54:-15'. During lldp-syncd deamon process, it will fail and print an error log when parsing age:
`[ [lldp_syncd] ERROR: Failed to parse lldp age 0 day, 00:-54:-15 -- #012Traceback (most recent call last):#012 File "/usr/local/lib/python3.9/dist-packages/lldp_syncd/daemon.py", line 49, in parse_time#012 struct_time = time.strptime(hour_min_secs, LLDPD_TIME_FORMAT)#012 File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time#012 tt = _strptime(data_string, format)[0]#012 File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime#012 raise ValueError("time data %r does not match format %r" %#012ValueError: time data …
> Ignore Failed to parse lldp age error log

- tests/dualtor/test_ipinip.py
Summary:
The test case test_encap_with_mirror_session in tests/dualtor/test_ipinip.py uses the GRE type 1234(0x04d2) when configuring the mirror session.
But for Nvidia platforms, we only support the GRE type 35145(0x8949) for mirroring and this is already noted in our release notes.
Fix the GRE type test issue in test_encap_with_mirror_session test.
Use GRE type 0x8949 when it is Nvidia platform.
Run the test on 4600C dualtor setup, it passed.
This change is only for Nvidia platforms.
> [Dual-Tor][Mellanox]Use GRE type 0x8949 when it is Nvidia platform in the test_encap_with_mirror_session test.

- tests/sub_port_interfaces/sub_ports_helpers.py
Summary:
After the python3 migration, the routing between sub ports and tunneling cases started to fail in verifying the packets:
```
duthost = <MultiAsicSonicHost r-tigon-20>
ptfadapter = <tests.common.plugins.ptfadapter.ptfadapter.PtfTestAdapter testMethod=runTest>, src_port = 'eth6.20'
dst_port = 'eth6.50', ip_src = '172.16.0.2', ip_dst = '172.16.0.14', tr_type = 'TCP', pktlen = 100, ttl = 63
def generate_and_verify_tcp_udp_traffic(duthost, ptfadapter, src_port, dst_port, ip_src, ip_dst, tr_type, pktlen, ttl):
...
...
pkt_filter = FilterPktBuffer(ptfadapter=ptfadapter,
exp_pkt=exp_pkt,
dst_port_numbers=dst_port_number,
match_fields=[("802.1Q", "vlan"), ("Ethernet", "src"), ("Ethernet", "dst"),
("IP", "src"), ("IP", "dst"), (tr_type, "dport")],
ignore_fields=[])
pkt_in_buffer = …
```
> Fix sub_port_interfaces python3 migration issue

- tests/qos/tunnel_qos_remap_base.py
Summary:
For Nvidia, we use the RPC image instead of swapping syncd in the qos sai tests. We need an option to control if the swap_syncd should be executed.
The pytest option "--qos_swap_syncd" is used in the regular qos sai test and we should also use it in the dscp remapping test.
The default value of this option is True, so this change won't affect existing test execution.
https://github.com/sonic-net/sonic-mgmt/blob/master/tests/conftest.py#L95-L96
Only swap the syncd when "--qos_swap_syncd" is True.
Verified on dualtor testbed, no issues found.
> Use pytest option for swapping syncd in dscp remapping test

- tests/telemetry/events/bgp_events.py
Summary:
Add step in bgp holdtimer repro to list iptables rules.
The default chain policy is to accept all packets. When I add the rule to drop all packets (including bgp packets), when we list the iptable rules, the rules are reevaluated such that they take place into effect.
code change
manual/pipeline
> Fix bgp notification test

- tests/dualtor/test_tor_ecn.py
Summary:
In the dualtor scenario, when dscp remapping is enabled and packet with dscp 2 or 6 is received by the standby tor, the mapping behavior is different between Nvidia and other vendors.
On Nvidia platforms, the downstream packet with dscp 2 or 6 on the standby tor will be encapsulated with the same 2 or 6 outer dscp and bounced back to the tunnel as lossless packet. And this behavior will cause the dualtor ecn test fail.
Actually, this is not considered as a valid use case, the dscp 2 and 6 should be reserved for the remapped tunnel traffic. And this has been discussed and confirmed with the Community.
So, we need to skip the cases for dscp 2 and 6 on Nvidia platforms when dscp remapping is enabled.
Skip the dualtor ecn test cases for dscp 2 and 6 on Nvidia platforms when dscp …
> [Mellanox][DualTor] Skip dualtor ecn test cases for inner dscp 2 and 6 on Nvidia platforms.

- tests/qos/files/mellanox/qos_param_generator.py
- tests/qos/files/mellanox/special_qos_config.yml
- tests/qos/qos_sai_base.py
For Nvidia SN5600 the formula to calculate the shared buffer size for pg and queue differs from other Spectrum. So, update the corresponding code for it.
Summary:
Update QoS cases for SN5600
Update the code according to the relevant formula
Run qos tests on the SN5600 device
SN5600
Any
> [Nvidia] Update qos cases for SN5600

- .azure-pipelines/pr_test_scripts.yaml
- azure-pipelines.yml
- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Revert the PRs, to get the macsec tests run 
https://github.com/sonic-net/sonic-mgmt/pull/10101
https://github.com/sonic-net/sonic-mgmt/pull/10088
> Remove the skip for macsec tests

- tests/common/devices/sonic.py
- tests/common/dualtor/dual_tor_utils.py
- tests/dualtor_mgmt/test_egress_drop_nvidia.py
Summary:
Add two new test cases for Nvidia platforms to cover the test gap introduced by the deviation of the dualtor acl rule. Nvidia platforms use the egress drop rule instead of the ingress rule to drop the upstream traffic received by the standby ports. Comparing to the ingress rule, the egress rule should be applied on all ports but not only the vlan ports.
There are two cases:
1. test_egress_drop_standby_server_to_active_server
This test case covers the validation of egress drop rule in active-standby dualtor scenario when server A is active on the upper tor and standby on the lower tor, server B is standby on the upper tor and active on the lower tor, and the upstream traffic is sent from server A to server B.
When the upstream traffic from server A to server B is sent, the traffic …
> [Nvidia] [Dual-Tor] [Active-Standby] Add new active-standby dual-tor egress drop cases for Nvidia platforms

- tests/qos/qos_sai_base.py
- tests/qos/test_tunnel_qos_remap.py
- tests/saitests/py3/sai_base_test.py
- tests/saitests/py3/sai_qos_tests.py
Cherry-pick PR https://github.com/sonic-net/sonic-mgmt/pull/9587 from master to 202205
Previously, on Nvidia devices, to make port congestion, we disable the port. So, if a LAG port is used as the tx port in the test, the LAG port will go down in 90s because the lacp pdus are also blocked, which will fail the tests. Therefore, we skip the test on the LAG port for QoS tests. Currently, to make the LAG port also support QoS test, we block the data plane queue instead of disabling the port. This change will work for all topo on Nvidia devices.
Summary:
Make Qos sai test support LAG port 
we block the data plane queue instead of disabling the port. So the control plane still work normally.
Run qos sai test on t1-lag-64 topo
Any
Any
> [202205 | Nvidia] Fix qos sai test for supporting LAG port  (#9587)

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Fixes # (https://github.com/sonic-net/sonic-mgmt/issues/8198)
Added skip for release 202305 + master branch
deprecated, ethtool is not being used for 202305 an higher 
Add skip to conditional_marks
Run TC, skipped for 202305
> [Mellanox] skip test_check_sfp_using_ethtool for 202305 release

- ansible/roles/test/files/ptftests/advanced-reboot.py
Raising PR for cherry-pick conflict:
225e2570c [advanced-reboot][dualtor] Update Loopback0 ping test: expect same count for sent and rcvd packets (#9599)
> [202205][advanced-reboot][dualtor] Update Loopback0 ping test: expect same count for sent and rcvd packets

- ansible/roles/test/files/ptftests/advanced-reboot.py
- tests/common/fixtures/advanced_reboot.py
- tests/conftest.py
Cherry-pick the fix https://github.com/sonic-net/sonic-mgmt/pull/7707  from master to 202205
Replace scapy sniffer by tcpdump to overcome scapy performance issues when dealing with high load
Scapy has a known performance limitation when it comes to high number of packets and high rates: https://github.com/secdev/scapy/issues/2608
As a result, from time to time, packet losses are observed during fast and warm boot test. For example, the pcap file would contain 40k packets while actually 45k packets were transmitted - the latest 5k packets will be missing from the pcap.
To overcome that, scapy sniffer was replaced with tcpdump which has much better performance. Tcpdump is done on all the data ports in parallel.
Summary:Replace scapy sniffer by tcpdump to overcome scapy performance issues …
> [202205 | advanced-reboot] Replace scapy sniffer by tcpdump to overcome scapy performance issues when dealing with high load

- tests/qos/qos_sai_base.py
Summary:
This is the manual cherry-pick of PR (https://github.com/sonic-net/sonic-mgmt/pull/7703) to 202205 branch for conflicts resolving.
For details please check the original PR.
This is the manual cherry-pick of PR (https://github.com/sonic-net/sonic-mgmt/pull/7703) to 202205 branch for conflicts resolving.
Please check the original PR.
We run the Qos Sai tests on 2700 with t0-56-po2vlan topo, 202205 branch and this change, all cases passed.
> [202205]Cherry-pick: Add support for t0-56-po2vlan topo to qos sai test(#7703)

- tests/ipfwd/test_nhop_group.py
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/9738/ from master to 202205
Updated test nhop_group according to Nvidia ASICs behavior
Summary:
Updated test nhop_group according to Nvidia ASICs behavior
Created dict with expected traffic redistribution for Nvidia-related ASICs
Removed test ignore for Mellanox/Nvidia platforms
Executed tests from file test_nhop_group.py
Nvidia
> [202205|Mellanox] enable dynamic ecmp on Mellanox switches and updated test nhop_group per vendor

- tests/tacacs/test_accounting.py
- tests/tacacs/test_authorization.py
- tests/tacacs/utils.py
Ensure tacacs server running after UT stop it.
- Microsoft ADO: 25136260
Ensure tacacs server running after UT stop it.
UT randomly failed because SSH login failed.
Ensure tacacs server running after UT stop it.
Pass all UT
> [TACACS] Ensure tacacs server running after UT stop it.

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
The fix for https://github.com/sonic-net/sonic-swss/issues/2204 was reverted due to a Mellanox issue.
This has caused the ipv6 variant of test_everflow_per_interface.py to continue to fail.
Skipping that variant until the bug is fixed again.
> Skip test_everflow_per_interface.py for ipv6 variant on broadcom-dnx

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
- tests/snmp/test_snmp_loopback.py
Summary:
Skip SNMP IPv6 related test cases in 202211,202205 and 202305 branches until the approach to fix IPv6 issue is fixed.
PR contains details of the issue and approach https://github.com/sonic-net/SONiC/pull/1457 
Skip single asic IPv6 SNMP loopback test case and link local test case in branches with the testcase added.
Tested on 202205 single asic VS image:
```
snmp/test_snmp_loopback.py::test_snmp_loopback[vlab-01-IPv4Address] PASSED                                              [ 50%]
snmp/test_snmp_loopback.py::test_snmp_loopback[vlab-01-IPv6Address] SKIPPED                                             [100%]
----------------------------------- generated xml file: /data/sonic-mgmt/tests/logs/tr.xml ------------------------------------ …
```
> Skip SNMP IPv6 testcases in 2022xx 2023xx branches

- tests/qos/qos_sai_base.py
Only uplink port is able to change speed between 400G and 100G for o8c48. Hence get uplink port info to run test_qos_sai script.
-------------------------------------- generated xml file: /run_logs/ar/qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXoffLimit[single_asic-xoff_1]_2023-09-07-20-39-29.xml ---------------------------------------
--------------------------------------------------------------------------------------------- live log sessionfinish ----------------------------------------------------------------------------------------------
20:45:10 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs …
> Using uplink ports for qossai testing for O8c48 hwsku

- tests/cacl/test_cacl_application.py
This PR resolves the issue as described in issue 9864 
https://github.com/sonic-net/sonic-mgmt/issues/9864
Summary:
Fixes # 9864
- [ x] Bug fix
- [ x] 202205
output of show acl rule for  multi asic platforms   has 6 columns, while single asic platform have 5 columns and in chassis it could have upto 7 columns. To resolve this I introduced a mechanism that determines columns and their field length rather than using static values
the following parsing of output code needs to be enhanced for chassis
Verified with multi asic chassis platform ran this test with t2 topo
N/A
N/A
> Fix Cacl test fixes issue 9864

- tests/saitests/py3/sai_qos_tests.py
Summary:
The variable "dscp" in the debug print should be "inner_dscp":
1. The print is meant to log the inner_dscp value here.
2. The variable "dscp" is not assigned beforehand if the dut is Nvidia, so the test will fail.
Fix a wrong variable name in TunnelDscpToPgMapping test case.
Change it to "inner_dscp"
Run the test on 4600C test bed, the info was correctly printed.
> Fix a wrong variable name in TunnelDscpToPgMapping test case

- ansible/roles/test/files/ptftests/py3/IP_decap_test.py
- tests/decap/test_decap.py
On T1 testbeds, outer DSCP values 2 and 6 which map to PG 2 and 6 respectively are not supported, so those DSCP values are excluded in tests to avoid RX_DRPs.
Summary:
Fixes # 24920851
PG(2) and PG(6) do not have buffers for uplink and consequently packets mapping to those PGs will get dropped.
Exclude DSCP 2 and 6 for outer DSCP in ip_decap tests
Running sonic-mgmt test decap/test_decap.py
NA
NA
> Exclude unsupported DSCP values

- tests/qos/files/qos_params.j2c.yaml
Aligning to the change in PR# https://github.com/sonic-net/sonic-buildimage/pull/16690
Summary:
The ingress drop counter value adjusted in qos_params.j2c to align with change in total headroom pool size (PR#16690 ) 
PCFXoff  test cases failure
Executed qos  test for T2 topology.
> Updating ingress drop counters for 100G_120k profile in qos

- ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py
Summary: Skip checking for packet flood on dual tor testbed
Proxy Arp is enabled on dual tor testbeds, which will disable flooding of packets in hardware
Skip verify_dhcp_relay_pkt_on_other_client_port_with_no_padding and verify_dhcp_relay_pkt_on_server_port_with_no_padding on dual tor testbeds
Ran test on a dualtor testbed, corresponding tests were not ran and test suite passed
> Skip verify_dhcp_relay_pkt_with_no_padding on dualtor testbed

- tests/qos/qos_sai_base.py
FIx qos sai issue: https://github.com/sonic-net/sonic-mgmt/issues/9918: 'dict' object has no attribute 'append'
Summary:
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/9918
Fix https://github.com/sonic-net/sonic-mgmt/issues/9918
use list instead of dict
dualTorPortIndexes[src_dut_index][src_asic_index] = []
Review code or run qos_sai test on dualtor setup
> [qos]Fix issue: 'dict' object has no attribute 'append'

- ansible/roles/vm_set/tasks/control_mux_simulator.yml
Summary:
Starting on/around September 29th, the mux-simulator script on the host server failed to start. This is because both the Flask and Werkzeug python packages updated to version 3.0.0 on that day, and there were breaking changes in Werkzeug 3.0.0. Our yaml script installs a fixed Flask version of 2.0.3, and the dependency list for that package only specified "Werkzeug >= 2.0". This means that pip will happily install version 3.0.0 even though it is incompatible with this version of Flask.
As a fix, install specifically Flask 2.3.3 and Werkzeug 2.3.7. In addtion, to make it easier to notice failures here, check to see that the systemd service is actually running after it gets started.
Tested locally with dualtor KVM
> Fix mux-simulator script not starting due to Werkzeug update

- ansible/roles/eos/templates/t1-28-lag-spine.j2
- ansible/roles/eos/templates/t1-28-lag-tor.j2
- ansible/roles/test/vars/testcases.yml
- ansible/vars/topo_t1-28-lag.yml
- ansible/veos
- ansible/veos_vtb
Summary:
Add t1-28-lag topology
The topology has 4 T2 VMs each connected to a portchannel which has 2 members, and 20 T0 VMs each connected to a physical link.
Add t1-28-lag topology
Add and update the required ansible files.
Deploy the topology on Nvidia 4700 setup, no issues found.
> Add t1-28-lag topology

- tests/platform_tests/verify_dut_health.py
Summary:
Fix test issues in verify_dut_health.py, this script is used in the advanced reboot test.
There are two issues:
1. In check_services(), when the service check fails, it should not directly fail the test by pytest_assert. Instead, it should raise the RebootHealthError so the exception can be handled and added to the test report.
2. In the verify_dut_health(), the logic in verify_dut_health before the yield is not correct, the test does not fail on any health errors because any string(failure reason) is considered as True in the all() method.
Fix test issues in verify_dut_health.py
1.  Raise the RebootHealthError when the service check fails.
2. If there is any failure in the pre-reboot checks, fail the test.
Run the advanced reboot tests in regression, no issues found related to …
> Fix test issues in verify_dut_health.py

- tests/common/snappi_tests/common_helpers.py
Summary: Ansible stdout errors were causing the snappi tests to fail on the master branch. There is no need to encode to utf8 since python3 automatically supports this encoding. 
To allow master branch snappi_tests to run on other images.
Test runs and passes from the master branch when run on 202012 and 202205.
> [Snappi] Allow snappi_tests to run from master branch on other branch images

- tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
- tests/snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py
- tests/snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py
Summary: Ansible failure is seen on pfcwd basic test because we don't wait for a safe reboot for these tests - since Ansible is not waiting for enough time before trying to reconnect. Also, setting all snappi_tests reboots to safe. 
Nightly triage fix for pfcwd basic test
Allow safe reboot
> [Snappi] Enable safe reboot on snappi_tests reboot cases

- tests/saitests/py3/sai_qos_tests.py
Summary:
Taking too much time to run ping at the beginning of a qos sai test if there are a bunch of ip addresses that need to be pinged.
It causes some qos sai cases to fail.
- combine multiple ping command to one-line script, so just need to login DUT once via ssh to run multiple ping commands
- adjust ping options to save time
- parallel run ping command in background to save time
run test on t0-120 device, to compare test result before and after applying this fix.
- before apply this fix:
execution time of "sai_qos_tests.ARPpopulate" is around 5 minutes
- after apply this fix:
execution time of  "sai_qos_tests.ARPpopulate" is around 30 seconds
> [qos] reduce execution time of ping command

- tests/qos/qos_sai_base.py
Summary:
encounter syntax issue for t1 device qos sai test
```
testPortIps[src_dut_index] = {}
>           testPortIps[src_dut_index][src_asic_index] = self.__assignTestPortIps(src_mgFacts)
E           TypeError: __assignTestPortIps() takes exactly 3 arguments (2 given)
```
RCA:
introduced by PR https://github.com/sonic-net/sonic-mgmt/pull/10131
assign necessary argument "topo"
> miss necessary argument for calling __assignTestPortIps

- tests/qos/qos_sai_base.py
- tests/saitests/py3/sai_qos_tests.py
Summary:
[Nvidia] Fix qos sai test for supporting LAG port #9587 #10121
break the qos sai test for mlnx device when topo is t0-120
RCA:
complain keyError when accessing testPortIds.
```
def __buildTestPorts(self, request, testPortIds, testPortIps, src_port_ids, dst_port_ids, get_src_dst_asic_and_duts):                                                        """                                                                                                                                                              
Build map of test ports index and IPs …
```
> [qos] support t0-120 qos sai test

- tests/qos/test_qos_sai.py
Summary:
different input qos parameter for testQosSaiHeadroomPoolSize and 
wrong qos paramreter for testQosSaiHeadroomPoolWatermark,
```
"/root/env-python3/bin/ptf","--test-dir","saitests/py3","sai_qos_tests.HdrmPoolSizeTest",
... ... omitted ... ...
pgs_num=46;
pgs=[3, 4]",
... ... omitted ... .... 
[(0, 3, 5), (0, 4, 6), (1, 3, 5), (1, 4, 6), (2, 3, 5), (2, 4, 6), (3, 3, 5), (3, 4, 6), (4, 3, 5), (4, 4, 6), (5, 3, 5), (5, 4, 6), (6, 3, 5), (6, 4, 6), (7, 3, 5), (7, 4, 6), (8, 3, 5), (8, 4, 6), (9, 3, 5), (9, 4, 6), (10, 3, 5), (10, 4, 6), (11, 3, 5), (11, 4, 6), (12, 3, 5), (12, 4, 6), (13, 3, 5), (13, 4, 6), (14, 3, 5), (14, 4, 6), (15, 3, 5), (15, 4, 6), (16, 3, 5), (16, 4, 6), (17, 3, 5), (17, 4, 6), (18, 3, 5), (18, 4, 6), (19, 3, 5), (19, 4, 6), (20, 3, 5), (20, 4, …
```
> limit the modification of pg_num to only occur on the specific platform to fix testQosSaiHeadroomPoolWatermark failure

- tests/common/fixtures/duthost_utils.py
- tests/generic_config_updater/test_dhcp_relay.py
PORT/mode is not yang modelled. I see open PR https://github.com/sonic-net/sonic-buildimage/pull/13580.
This PR will revert all the commits related to manipulate PORT/mode in test, in order to unblock https://github.com/sonic-net/sonic-buildimage/pull/16267
Summary:
> Revert 7 commits related to manipulate PORT/mode in test

- tests/route/test_route_perf.py
port_indices obtained using port_indices mg_facts["minigraph_port_indices"] are not valid for dualtor testbeds causing test failures. The right way is to use mg_facts["minigraph_ptf_indices"] to get ptf port indices so the test passes on all testbeds.
Summary:
Fixes # 24668985
port_indices obtained using port_indices mg_facts["minigraph_port_indices"] are not valid for dualtor testbeds causing test failures
Use mg_facts["minigraph_ptf_indices"] to get ptf port indices so the test passes on all testbeds.
By running sonic-mgmt test route/test_route_perf.py
> [tests/route]: Use minigraph_ptf_indices to get ptf port indices

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
- tests/snmp/test_snmp_loopback.py
cherry pick of https://github.com/sonic-net/sonic-mgmt/pull/10097
Skip SNMP IPv6 related test cases in 202211,202205 and 202305 branches until the approach to fix IPv6 issue is fixed. PR contains details of the issue and approach sonic-net/SONiC#1457
Skip single asic IPv6 SNMP loopback test case and link local test case in branches with the testcase added.
Tested on 202205 single asic VS image
(cherry picked from commit a72a4db2955f78fbed1acddc85b13265e595f546)
Summary:
> [202305] Skip SNMP IPv6 testcases in 2022xx 2023xx branches

- .azure-pipelines/test_plan.py
Fix get **pr_id** is None for some repos PR test azure pipelines.
For `sonic-mgmt` and `sonic-buildimage` repo, in PR test azure pipelines, the **pr_id** is got from the ENV `"SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"`. But for other repos, the ENV name is different.
If `"SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"` exists, use it as **pr_id**, else get from another ENV name.
> [CI/CD][Fix] Fix get pr_id is None for some repos PR test azure pipelines

- tests/common/dualtor/data_plane_utils.py
- tests/common/dualtor/dual_tor_io.py
- tests/dualtor_io/test_normal_op.py
Approach
To cherry-pick PR https://github.com/sonic-net/sonic-mgmt/pull/10124 into 202205 branch
Add server to server normal testcase to cover the east-to-west traffic verification for dualtor.
Select two mux ports, one as source port, one as dest port. Send traffic from source port and verify traffic delivery at the dest port.
> [202205][dualtor_io] Add server to server I/O normal op test (#10124)

- tests/conftest.py
- tests/run_tests.sh
Summary:
Sometimes, some cases may cause testbed unhealthy, such as previous case do some operations on DUT, it may cause DUT network unreachable, in this case, currently mechanism throw AnsibleConnectionFailure and still run the next test case, actually, all left cases can't be ran, the whole pytest needs to exit, fail pipeline, it saves time and let user know these is something wrong with this DUT now.
This is traceback when DUT host is unreachable.
```
__________ ERROR at setup of TestAutoTechSupport.test_max_limit[core] __________
enhance_inventory = None
ansible_adhoc = <function init_host_mgr at 0x7f5826304ad0>
tbinfo = {'auto_recover': 'True', 'comment': 'zitingguo', 'conf-name': 'vms64-t1-s6100-1', 'duts': ['str3-s6100-acs-7'], ...}
request = <SubRequest 'duthosts' …
```
> Exit pytest with error code 15 if duthosts fixture fails

- tests/voq/test_voq_chassis_app_db_consistency.py
Summary:
- This PR Enhances VOQ test suite.
"tests/voq/test_voq_chassis_app_db_consistency.py" is added to VOQ test suite to incorporate test cases for https://github.com/sonic-net/sonic-buildimage/pull/16213.
The Test Case added is to verify any temporary change in config which modifies the below table should be cleaned up after config_reload or system reboot  and if the changes are saved then data should be persistent after config_reload.
(1) SYSTEM_NEIGH
(2) SYSTEM_INTERFACE
(3) SYSTEM_LAG_MEMBER_TABLE
(4) SYSTEM_LAG_TABLE
from the  chassis app db in redis_chassis server in the supervisor
New Test Cases for  verification of DB Consistency https://github.com/sonic-net/sonic-buildimage/pull/16213 
The test assign members, neigh ipv4 and ipv6  from another port channel to …
> New Test Cases for Chassis DB cleanup when asic comes up PR (sonic-buildimage/pull/16213)

- tests/crm/test_crm.py
Modified prefixes from 3.3.3.0,3.3.3.1 to 5.5.5.0,5.5.5.1
Summary:
Currently, we add routes of 3.3.3.0/24, 4.4.4.0/24 and arps of 3.3.3.1, 4.4.4.1
However 3.3.3.1 is the address of the inband interface and should not be used. Adding inband interface's ip brings down the iBGP neighbors
We are changing 3.3.3.0 and 3.3.3.1 to 5.5.5.0 and 5.5.5.1 respectively
modified prefixes 3.3.3.0 and 3.3.3.1 to 5.5.5.0 and 5.5.5.1 respectively
Tested the testcases on a multiasic chassis
> crm cherry picked - Modified prefixes from 3.3.3.0,3.3.3.1 to 5.5.5.0,5.5.5.1 #9865

- ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py
Cherry-pick of PR https://github.com/sonic-net/sonic-mgmt/pull/10201
Summary: Skip checking for packet flood on dual tor testbed
Proxy Arp is enabled on dual tor testbeds, which will disable flooding of packets in hardware
Skip verify_dhcp_relay_pkt_on_other_client_port_with_no_padding and verify_dhcp_relay_pkt_on_server_port_with_no_padding on dual tor testbeds
Ran test on a dualtor testbed, corresponding tests were not ran and test suite passed
> [202205] Skip verify_dhcp_relay_pkt_with_no_padding on dualtor testbed

- tests/dualtor_io/test_tor_bgp_failure.py
Approach
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/9980 into 202205
When BGP is shutdown, default route n/a, linkmgrd will write unhealthy. So let's change the expected health for the standby to unhealthy.
> [202205][dualtor-io] Change the health expectation for bgp shutdown case (#9980)

- ansible/dualtor/nic_simulator/nic_simulator.py
- ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service.proto
- ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service_pb2.py
- ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service_pb2_grpc.py
- ansible/dualtor/nic_simulator/nic_simulator_grpc_service.proto
- ansible/dualtor/nic_simulator/nic_simulator_grpc_service_pb2.py
- ansible/dualtor/nic_simulator/nic_simulator_grpc_service_pb2_grpc.py
- tests/common/dualtor/dual_tor_utils.py
- tests/common/dualtor/mux_simulator_control.py
- tests/common/dualtor/nic_simulator_control.py
- tests/dualtor_io/conftest.py
- tests/dualtor_io/test_grpc_server_failure.py
- tests/dualtor_io/test_heartbeat_failure.py
- tests/dualtor_io/test_link_drop.py
- tests/dualtor_io/test_link_failure.py
- tests/dualtor_io/test_normal_op.py
- tests/dualtor_io/test_tor_bgp_failure.py
- tests/dualtor_io/test_tor_failure.py
Approach
Cherry-pick PR https://github.com/sonic-net/sonic-mgmt/pull/9568 into 202205
For dualtor-io tests, log the mux port flaps to better help debug.
Add fixture check_simulator_flap_counter to show/check mux port flaps during test execution, and enable it for all dualtor-io testcases.
Run dualtor-io tests on both active-standby and active-active testbed.
> [202205][dualtor-io] show mux port flaps (#9568)

- tests/acl/test_acl_outer_vlan.py
- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Microsoft ADO: 22637175
Dualtor platform does not need portchannel in vlan
If testbed is dualtor, skip test_acl_outer_vlan
> Skip dualtor in test_acl_outer_vlan

- tests/acl/test_acl_outer_vlan.py
- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Microsoft ADO: 22637175
Backport #10252 to 202205 branch.
Dualtor platform does not need portchannel in vlan
If testbed is dualtor, skip test_acl_outer_vlan
> [202205] Skip dualtor in test_acl_outer_vlan

- tests/platform_tests/conftest.py
Summary:
Fix reboot type source fetch logic: Previously, the reboot type source was based on the test name. However, it doesn't work with the upgrade path test, as it does not include the reboot type in the name of the test. This fix treats the mentioned case by getting the name from the upgrade type parameter.
Ability to fetch reboot logs on upgrade_path test
Changed the reboot source fetching logic, to be based not only on the test name
Ran the upgrade test
> Fixed log handling issues on fast/warm upgrade test

- tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
- tests/platform_tests/mellanox/test_psu_power_threshold.py
Enhance test case test_psu_power_threshold - add mock for temperature threshold at the beginning of the test.
The temperature on some setup may exceed the threshold at the begining of the test start, and will cause test failure.
Summary: The temperature on some setup may exceed the threshold at the begining of the test start, and will cause test failure. Enhance test case test_psu_power_threshold with adding mock for temperature threshold  at the beginning of the test
Add mock for temperature threshold to make sure the tempperature will not exceed the threshold.
Test will not fail due to the temperature exceed the threshold.
> [Mellanox] add mock for temperature threshold in psu power threshold 

- docs/testplan/Generic-Hash-test-plan.md
Summary:
Test plan for the new feature Generic Hash.
The HLD of Generic Hash: https://github.com/sonic-net/SONiC/pull/1101
The test implementation is not included in this PR, will open another PR. 
Adding the test plan for the new feature Generic Hash.
The test plan has already been reviewed internally.
> Test plan for feature Generic Hash

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
- tests/snmp/test_snmp_loopback.py
Skip SNMP IPv6 related test cases in 202211,202205 and 202305 branches until the approach to fix IPv6 issue is fixed. PR contains details of the issue and approach sonic-net/SONiC#1457
Skip single asic IPv6 SNMP loopback test case and link local test case in branches with the testcase added.
Tested on 202205 single asic VS image
(cherry picked from commit a72a4db2955f78fbed1acddc85b13265e595f546)
Summary:
> [202205] Skip SNMP IPv6 testcases in 2022xx 2023xx branches (#10097)

- ansible/roles/vm_set/library/ptf_control.py
Summary:
While stopping PTF container, "ptf_control" module is executed to kill all processes in the PTF container.
The original code checks if the PTF container's Pid exists before running command in the PTF container. Unfortunately, this check is not enough. PTF docker container in exited status still has Pid.
This change improved the code for getting PTF container's Pid. When PTF container is not in "running" status, always return None for PTF container's Pid.
> Avoid running command in exited ptf docker container

- tests/acl/test_acl_outer_vlan.py
Summary:
There is no application scenario for test_acl_outer_vlan in m0, no need to run this case.
Remove pytest mark to kip test_acl_outer_vlan for m0/mx.
Run tests.
```
collected 32 items                                                                                                                                                                 
acl/test_acl_outer_vlan.py::TestAclVlanOuter_Ingress::test_tagged_forwarded[ipv4] SKIPPED                                                                                    [  3%]
acl/test_acl_outer_vlan.py::TestAclVlanOuter_Ingress::test_tagged_dropped[ipv4] SKIPPED                                                                                      [  6%]
acl/test_acl_outer_vlan.py::TestAclVlanOuter_Ingress::test_untagged_forwa …
```
> [m0][mx] Skip test_acl_outer_vlan for m0/mx

- tests/platform_tests/daemon/test_chassisd.py
There were issues seen in every test of test_chassisd.py, where before this testcase is entered, pmon was restarted thus chassisd is `STARTING` not `RUNNING`, before we do any action on pmon.
This PR add a check in test setup to wait until all critical processes are running, before we start testing on pmon. The current wait time is 300sec by default.
```
def test_pmon_chassisd_running_status(duthosts, enum_rand_one_per_hwsku_hostname, data_before_restart):
"""
@summary: This test case is to check chassisd status on dut
"""
duthost = duthosts[enum_rand_one_per_hwsku_hostname]
daemon_status, daemon_pid = duthost.get_pmon_daemon_status(daemon_name)
logger.info("{} daemon is {} with pid {}".format(daemon_name, daemon_status, daemon_pid))
pytest_assert(daemon_status == expected_running_status, …
```
> [test_chassisd] wait critical processes to come up in test setup

- tests/acl/test_acl.py
Acl test is flaky in checking syslogs. Test failed even the log was there. Add delay to make sure ACL is applied before checking syslog.
Summary:
- [ x] 202205
> Make acl test more robust in checking syslog

- tests/dut_console/test_console_baud_rate.py
Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/9916
This case doesn't support non-ssh console, skip that type.
Skip connect console when encountering non-ssh console.
Run tests.
> [console] Skip test_console_baud_rate in non-ssh console

- tests/tacacs/utils.py
Fix per-command authorization UT failed because server-side update log delay issue.
Fix per-command authorization UT failed because server-side update log delay issue.
Fix per-command authorization UT failed because server-side update log delay issue.
Retry when log or output not ready.
Pass all UT
> [TACACS] Fix per-command authorization UT failed because server-side update log delay issue.

- tests/common/plugins/conditional_mark/__init__.py
- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
- tests/route/test_route_perf.py
build_version could be like master.362591-ce7145475 which raises
exceptions when evaluating 5 conditions. This change simply adds
a check if the value is digit before casting it. It also changes
the logger level for this case to ease debugging.
This issue can be reproduced when running a Pytest as described
in KVM Testbed Setup [1] (Please note that test_pretest.py and
test_posttest.py are directly called in Gates)
> Protect vs ValueError when casting to int in conditional_mark

- tests/bgp/test_bgpmon_v6.py
Summary:
test_bgpmon_v6 is failing on packet chassis with the below error:
```
pytest_assert(wait_until(MAX_TIME_FOR_BGPMON, 5, 0, bgpmon_peer_connected, duthost, peer_addr),
>                         "BGPMon Peer connection not established")
E                         Failed: BGPMon Peer connection not established
```
Modify test case to use asic router_mac instead of duthost router_mac.
Because the packet was not using the right mac, packet was not coming into the expected interface on the Linecard and the BGP connection was not getting established.
Verified on packet and voq chassis
> Fix test_bgpmon_v6 to use asic router_mac

- tests/pfcwd/test_pfcwd_function.py
Update the tests in tests/pfcwd/test_pfcwd_function.py to use static_th for profiles which use static_th. The default handling was for profiles using dynamic_th.
For interfaces using long links, cisco-8000 enabled static buffer pool and the profiles using this pool has static_th.
The pfcwd tests were developed for profiles with dynamic_th where the alpha was changed in the test case.
This was not applicable to static profiles and enhanced the test to handle the updated pool and profile types.
Verified on cisco-8000 system, on interfaces with long links (120km) that use static_th for profiles and static buffer pool.
A related change to update mmuconfig utility was made in sonic-buildimage via 
https://github.com/sonic-net/sonic-utilities/pull/2775
This change was tested on a T2 platform, …
> enable pfc-wd testing for profiles using static_th

- tests/common/utilities.py
Summary: The first get command may result in a `NoneType` error if there are not that many traffic classes on the switch. Hence, we split the get commands and check for a `None` return type at each step to prevent this error. 
> Bug fix for nonetype error for get_egress_queue_pkt_count

- tests/qos/files/cisco/qos_param_generator.py
When a platform or topo doesn't support paramgen, we should return the existing params read from qos-yaml.
Currently it gives this error:
> Cisco-8000: Return from cisco qos param gen if the current platform doesn't support param gen yet.

- tests/common/dualtor/data_plane_utils.py
- tests/common/dualtor/dual_tor_io.py
- tests/dualtor_io/test_normal_op.py
Summary:
Fixes #10293
Fixes #10294
Fixes #10295
Add three testcases to cover three scenario:
1. active server to standby server
2. active server to active server, then config mux standby
3. active server to standby server, then config mux auto
1. for class `DualTorIO`, add method `_generate_upstream_packet_to_target_duthost` to guarantee that all the server-to-server packets are forwarded to the specified test target `DUT`. So test user could have the knowledge of which ToR receives the packet.
`_generate_upstream_packet_to_target_duthost` basically increments the source port one by one till finding one packet that is hashed to the port that is connected to the specified test target `DUT`. 
``` …
```
> [dualtor-io] Add server to server testcases

- tests/generic_config_updater/conftest.py
Summary:
Bookworm's systemd changes the syntax for services being stopped. Update GCU's ignore list for the dhcp_relay error logs.
Tested on KVM with Bookworm base image. Original failure message (with the new syntax):
```
E               Oct 11 05:05:04.713125 vlab-01 ERR systemd[1]: Failed to start dhcp_relay.service - dhcp_relay container.
E               Oct 11 05:05:43.599634 vlab-01 ERR systemd[1]: Failed to start dhcp_relay.service - dhcp_relay container.
```
> Update GCU loganalyzer list for Bookworm

- .github/PULL_REQUEST_TEMPLATE.md
Summary:
Add 202305 back-port option to PR template
> [github] Add 202305 back-port option to PR template

- tests/arp/test_wr_arp.py
Summary:
Noticed an issue that when test triggers warmboot on DUT and warmboot fails, sanity check couldn't bring testbed back to health. Cause when `config reload` was conducted, warmboot system flag was still set to true, and processes restarted followed the warmboot recover path. 
Introducing a fix to force reset the flag after tests. 
Avoid failing remaining tests. 
Force reset warmboot flag as a teardown step. 
```
23:33:46 test_wr_arp.testWrArp                    L0238 INFO   | Warm-Reboot Control-Plane assist feature
PASSED                                                                   [100%]
```
Flag reset log:
```
------------------------------ live log teardown -------------------------------
23:40:11 …
```
> [dualtor][TestWrArp] force reset  warmboot flag to `false` in test class teardown

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Platform cli PSU test cases should be skipped on DPU for the DPU doesn't have PSUs and tests will fail.
Cases to skip:
tests/platform_tests/cli/test_show_platform.py::test_show_platform_psustatus
tests/platform_tests/cli/test_show_platform.py::test_show_platform_psustatus_json
Skip platform cli PSU test cases on Nvidia DPU
Skip the tests when 'nvda_bf' in platform name.
Run test_show_platform.py on Nvidia DPU setup, PSU cases are skipped.
For Nvidia Bluefield DPU setup.
> [Nvidia] Skip platform cli PSU test cases on Nvidia DPU

- tests/conftest.py
- tests/test_pretest.py
Summary:
This PR is to move a session level auto-used fixture `install_mergecap_on_ptf` to [tests/test_pretest.py](https://github.com/sonic-net/sonic-mgmt/compare/202205...bingwang-ms:mv_install_mergecap_on_ptf_to_pre_test?expand=1#diff-cfd8216a00a276591d127aca331535e2e9fbf3fc444f51528c4ddfc99cfbf106).
We need to do this change because nightly test is running each test module in a single session. There is no need to install the package for each run. 
This PR is to move a session level auto-used fixture `install_mergecap_on_ptf` to tests/test_pretest.py.
Move the auto-used fixture to pretest and change it to a utility test case.
Verified on a physical testbed
``` …
```
> [202205] Move install_mergecap_on_ptf to pre_test script

- tests/common/dualtor/data_plane_utils.py
- tests/common/dualtor/dual_tor_io.py
- tests/dualtor_io/test_normal_op.py
Approach
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/10292 into 202205
Add three testcases to cover three scenario:
1. active server to standby server
2. active server to active server, then config mux standby
3. active server to standby server, then config mux auto
for class DualTorIO, add method _generate_upstream_packet_to_target_duthost to guarantee that all the server-to-server packets are forwarded to the specified test target DUT. So test user could have the knowledge of which ToR receives the packet. _generate_upstream_packet_to_target_duthost basically increments the source port one by one till finding one packet that is hashed to the port that is connected to the …
> [202205][dualtor-io] Add server to server testcases (#10292)

- tests/common/devices/sonic.py
The `minigraph_ptf_indices` structure maps port names to PTF indices. From the code context, it appears that `minigraph_port_indices` was used for this mapping, but multi-dut TBs caused problems with the PTF.
It seems the more reliable way to get the ptf indices is to compose together the port_name->port_index map (`minigraph_port_indices`), and the port_index->ptf_index map (`tbinfo['topo']['ptf_map'][str(dut_index)]`). 
The pre-existing initialization of this composition to include any members of the `port_index->ptf_index` map can leave duplicate ptf_index entries for down ports, especially in dualtor scenarios. See #10139. 
Remove the extra initialization on the composition construction. 
Summary:
Fixes #10139
Verified on dualtor TB for PCBB watermark test cases.
> Set port->ptf_index map empty before construction

- tests/common/platform/device_utils.py
- tests/platform_tests/cli/test_show_platform.py
The LED output is not 'N/A' from Cisco's latest release 202205.2.2.13.
> Revert "Revert "Cisco-8000 psu led support""

- tests/iface_loopback_action/iface_loopback_action_helper.py
Summary:
Warm reboot is not supported when there is empty lag in the config_db. And during the iface_loopback_action reload test, there are empty lags while doing the warm reboot test. Need to remove all empty lags in test setup phase.
Warm reboot is not supported when there is empty lag in the config_db. And during the iface_loopback_action reload test, there are empty lags while doing the warm reboot test. 
Remove all empty lags in test setup phase. 
This check _check_portchannel_member_removed is to make sure the members are actually removed, for there is a delay after the delete member cli.
By running the test on different platforms, all passed.
> [Iface loopback action] Fix loopback action reload test

- ansible/group_vars/sonic/variables
Summary:
The PR is to support HWSKU `Mellanox-SN4700-O8C48`.
The qos_sai_tests are failing without the SKU support
```
>       pytest_assert(dutAsic, "Cannot identify DUT ASIC type")
E       Failed: Cannot identify DUT ASIC type
```
This PR is to support HWSKU `Mellanox-SN4700-O8C48`.
Add the HWSKU to list `mellanox_spc3_hwskus`.
No.
> Support HWSKU Mellanox-SN4700-O8C48

- tests/dualtor_io/test_grpc_server_failure.py
Summary:
As the grpc server failure tests disable the grpc server, the mux flap
check will have grpc unavailable issue.
So let's remove the mux flap check.
```
dualtor_io/test_grpc_server_failure.py::test_grpc_server_failure_config_standby_config_auto_upstream_active[active-standby] SKIPPED [ 25%]
dualtor_io/test_grpc_server_failure.py::test_grpc_server_failure_config_standby_config_auto_upstream_active[active-active] PASSED [ 50%]
dualtor_io/test_grpc_server_failure.py::test_grpc_server_failure_config_standby_config_auto_downstream_standby[active-standby] SKIPPED [ 75%]
dualtor_io/test_grpc_server_failure.py::test_grpc_server_failure_config_standby_config_auto_downstream_standby[active-active] PASSED [100%] …
```
> [dualtor-io] Remove mux flap check for grpc server failure tests

- tests/saitests/py3/sai_qos_tests.py
Summary:
During the extreme memory congestion present in this test, lossy traffic can be dropped. We should not assert that no lossy ingress drops occurred. 
Additionally:
- Reduced/removed unnecessary sleep times to improve test speed.
- Fix redundant counter reads. 
Verified on Cisco-8000 T1. 
This is a Cisco-8000 specific test.
> Fix SharedResSize lossy drop flaky failure

- tests/saitests/py3/sai_qos_tests.py
Update class LossyQueueVoqTest to handle that dst_port in port-channel.
Pick up those udp ports which will use the same egress port in port-channel, and use them to test split-voq. Without this, 2 flows using 2 voq, there are 2 possibilities, one is split-voq taking effect, the other is the 2 flows are using 2 different egress ports.
Summary:
> Update class LossyQueueVoqTest to handle dst_port in port-channel

- tests/snmp/test_snmp_link_local.py
Summary:
Fixes # [(issue)](https://github.com/sonic-net/sonic-mgmt/issues/10344)
test_snmp_link_local_ip : wait for interfaces to be up after config reload 
This issue is in test_snmp_loopback which follows this test test_snmp_link_local_ip in a pipeline run. Since we don't wait for interfaces to be up after a config reload the following tests randomly fail.
Added the additional parameters in config_reload call 
Verified the interfaces come up before starting next test
> test_snmp_link_local_ip : wait for interfaces to be up after config reload 

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Not all structured events code is in 202211 causing tests to fail so we skip that and earlier branches.
Update tests_mark_conditions.yaml
> Skip test_events for 202211 and older branches

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
there is a warm reboot related known issue on the 202305 branch.
xfail the warm reboot related cases on 202305 branch for 7060
remove xfail on master branch, only xfail it on feature branch
platform_tests/test_cont_warm_reboot.py
arp/test_wr_arp.py
pfcwd/test_pfcwd_warm_reboot.py
=================================================================================================================== short test summary info ====================================================================================================================
XFAIL pfcwd/test_pfcwd_warm_reboot.py::TestPfcwdWb::test_pfcwd_wb[no_storm-str3-7060-acs-1]
Warm Reboot is not supported in dualtor and has a known issue on 202305 branch
XFAIL …
> skip warm reboot related cases on 202305 branch for 7060

- tests/voq/test_voq_ipfwd.py
Summary:
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/9363
Add skip to tests when ports to T3 VM's are not available in t2 min topology. 
In the T2 min topolgy as there are less ports per asic, skip the test if we don't have enough ports.
```
jujoseph@d01ac6af286b:/var/src/sonic-mgmt-int/tests$ ./run_tests.sh -c voq/test_voq_ipfwd.py -i '../ansible/str2,../ansible/veos' -n vms29-t2-xxxx-1  -t 't2,any' -u -e "--skip_sanity --disable_loganalyzer"
=== Running tests in groups ===
Running: python2 -m pytest voq/test_voq_ipfwd.py --inventory ../ansible/str2,../ansible/veos --host-pattern str2-xxxx-lc1-1,str2-xxxx-lc2-1,str2-xxxx-sup-1 --testbed vms29-t2-xxxx-1 --testbed_file /var/src/sonic-mgmt-int/ansible/testbed.yaml --log-cli-level warning --log-file-level debug --kube_master unset …
```
> Skip certain voq tests when ports to T3 VM's are not available in t2 min topology

- .azure-pipelines/pr_test_scripts.yaml
- azure-pipelines.yml
- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Following what as done in master and 202205 for macsec type7 changes 
Add the remove first and later revert REF: https://github.com/sonic-net/sonic-mgmt/pull/10132
MSFT ADO : 25261395
> Add macsec skip in 202305

- tests/saitests/py3/sai_qos_tests.py
…for qos tests (#9896)
* Qos_LossyQueueTest fix_adding COUNTER MARGIN
* Adding COUNTER_MARGIN to qos PFCXonTest
* Adding COUNTER_MARGIN to qos PFCTest
* testQosSaiPFCXoffLimit updated with correct check
* Conditional check corrected for LossyQueueTest
Master branch PR #9896
Summary:
> [Cherry-pick] Adding COUNTER_MARGIN to Ingress drop counters …#9896

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
For non t2 DUT, sometimes run into voq related cases, and failed. Add skip condition in the conditional mark file to avoid unnecessary failure and save time to run fixture.
ADO 25516999
For non t2 DUT, sometimes run into voq related cases, and failed. Add skip condition in the conditional mark file to avoid unnecessary failure and save time to run fixture.
To add non t2 check in the skip condition.
N/A
> Skip non t2 for voq test

- tests/generic_config_updater/test_ecn_config_update.py
For Cisco platforms, the command "sonic-db-cli ASIC_DB keys WRED” used in this testcase return 2 WRED object instead of 1 that the script expects. This is because one is the "default” WRED profile that SAI/SDK creates with default setting, while other is the user configured WRED profile that sonic creates.
Summary: This can be fixed by checking which WRED object corresponds to default WRED profile and which one corresponds to user configured WRED profile; then ignoring the default profile and using the user configured profile for the testcase
**Approach**
All 4 testcases in test_ecn_config_update.py fail on all testbeds
Check which one is the default profile and …
> ecn-config-update modifications

- tests/dualtor_io/test_normal_op.py
Summary:
Remove testcase `test_normal_op_server_to_server` as it is replaced by
`test_normal_op_active_server_to_active_server`.
> [202205][dualtor-io] Remove `test_normal_op_server_to_server`

- tests/qos/files/qos_params.pac.yaml
- tests/qos/qos_sai_base.py
- tests/qos/test_qos_sai.py
1, Skip queue watermark cases. Q100 does not support congestion level and thus no queue watermarks.
2, Skip wm_pg_shared_lossy. After eviction to hbm, the sq counter is 0 on Q100 hardware.
Summary:
> Skip queue watermark and wm_pg_shared_lossy for Q100

- tests/qos/files/qos_params.j2c.yaml
- tests/saitests/py3/sai_base_test.py
- tests/saitests/py3/sai_qos_tests.py
… single_asic, single_dut_multi_asic and  multi_dut (#8222) from master to 202205
* QoS tunning for LossyQueueTest
* Recommiting the changes of qos.yml to qos_params_j2c.yml
* tx_enable/disable retry check corrected
* Making check to run only for chassis in LossyQueue
* Adding check for sai_base for tx_enable/disable
Master PR #8222 
Summary:
> [Cherry-pick] Improvising qos tests by tunning the qos params for…#8222

- tests/common/helpers/pfc_gen_t2.py
- tests/common/helpers/pfc_storm.py
- tests/common/templates/pfc_storm_sonic_t2.j2
- tests/common/templates/pfc_storm_stop_sonic_t2.j2
- tests/pfcwd/test_pfcwd_function.py
- tests/pfcwd/test_pfcwd_timer_accuracy.py
**Cherry-Pick** PR for 202205 branch from master #9416 
Summary:
- This PR fixes '_test_pfcwd_timer_accuracy_' test failures for t2-chassis.
- Currently, for 't2' chassis, the timer accuracy test fails w.r.t the issues related to PFC storm detection and restoration on the DUT.
- And also, this PR adds a new pfc_gen file specifically for 't2-chassis' w.r.t '_TestPfcwdFunc_' and '_TestPfcwdAllPortStorm_' test cases.
- PFC storm detection/restoration logic for t2-chassis w.r.t to the existing '_pfc_gen.py_' template is not working as expected.
- Due to this, the '_test_pfcwd_timer_accuracy_' , '_TestPfcwdFunc_' and '_TestPfcwdAllPortStorm_' tests fail for t2 multi-asic dut.
- By introducing a new template file for t2-chassis which does bulk send from leaf fanout instead of …
> [cherry-pick] [PR:9416] PFCWD - Test fixes for t2-chassis (#9416)

- tests/ntp/test_ntp.py
Summary:
Bookworm uses NTPsec instead of NTP, and so the file paths have changed slightly. Update the test case for that.
Tested on Bookworm VS image
> Update NTP longjump test for Bookworm

- tests/pfcwd/test_pfcwd_timer_accuracy.py
Summary:
25074148
The case failure on some devices.
Enlarge the sleep time in case test_pfcwd_timer_accuracy
Verified locally
pfcwd/test_pfcwd_timer_accuracy.py::TestPfcwdAllTimer::test_pfcwd_timer_accuracy[str3-7060-acs-3] PASSED
> enlarge sleep time in test_pfcwd_timer_accuracy

- tests/common/dualtor/mux_simulator_control.py
- tests/qos/qos_sai_base.py
Summary:
The toggle to the lower ToR in the `test_qos_sai` setup failed recently.
Improve the toggle fixture `toggle_all_simulator_ports`:
1. add retry logic.
2. probe those inconsistent mux ports.
Run on dualtor testbed:
```
qos/test_qos_sai.py::TestQosSai::testParameter[single_asic] PASSED                                                                                                                                                                                   [100%]
===================================================================================================================== warnings summary ===================================================================================================================== …
```
> [test_qos_sai] Fix toggle failures on dualtor testbed

- tests/dualtor_io/test_tor_bgp_failure.py
Summary:
Ignore the `bgpmon` syslog error:
```
Oct 22 15:35:20.469660 lab-dev-01 ERR bgp#bgpmon: *ERROR* Failed with rc:1 when execute: ['vtysh', '-c', 'show bgp summary json']
```
Add the the error string pattern to `loganalyzer` ignore list.
```
dualtor_io/test_tor_bgp_failure.py::test_active_tor_kill_bgpd_upstream[active-standby] PASSED                                                                                                                                                        [ 50%]
dualtor_io/test_tor_bgp_failure.py::test_active_tor_kill_bgpd_upstream[active-active] SKIPPED …
```
> [dualtor-io] Ignore BGPMON errors in bgp failure tests

- tests/cacl/test_cacl_application.py
Extract the kernel name eth1-midplane is attached to in the event it's an altname and use that kernel name in the ip rules
Summary:
Fixes #10223 
[x] Bug fix
test_cacl_application.py::test_cacl_application_nondualtor is failing today because it's expecting the wrong ip table rule:
```
(Pdb) set(expected_iptables_rules) - set(actual_iptables_rules)
set(['-A INPUT -i eth1-midplane -j ACCEPT'])
(Pdb) set(actual_iptables_rules) - set(expected_iptables_rules)
set([u'-A INPUT -i br1 -j ACCEPT'])
```
`ip link show <name>` seems to return the same data regardless of whether we pass the kernel name or an altname.
So either way we should cut out the kernel name and use it:
```
root@nfc420:~# ip link show br1
7: br1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT …
```
> Handle eth1-midplane being a kernel intf altname

- tests/common/devices/sonic_asic.py
- tests/crm/test_crm.py
Summary:
Fixes # [(issue)](https://github.com/sonic-net/sonic-mgmt/issues/10341)
Added following checks 
1. Check if the portchannel is part of asic before adding to porthannel list
2. Fix the py3 conversion issue with the common API port_on_asic()
```
crm/test_crm.py::test_crm_route[svcstr-xxxx-lc1-1-0-ipv4] PASSED                                                                                                                                                                                         [  4%]
crm/test_crm.py::test_crm_route[svcstr-xxxx-lc1-1-0-ipv6] PASSED                                                                                                                                                                                         [  9%] …
```
> Fix for test_crm_acl_entry test and py3 fix for API: port_on_asic()

- ansible/roles/test/files/ptftests/py3/copp_tests.py
- tests/copp/test_copp.py
* Rate limits are being set for bgp, lacp, dhcp, lldp, udld and macsec via a copp cfg change via sonic-buildimage PR 
https://github.com/sonic-net/sonic-buildimage/pull/14859. This is the corresponding sonic-mgmt change to make sure that copp tests don't fail with the updated rate limits.
* This change is dependent on the the sonic-buildimage PR above and will be committed after the buildimage PR is merged.
Summary:
Fixes # 17964421
It was observed that a flood of DHCP packets without rate-limiting can cause BGP flaps or lacp keepalive losses.
Enable rate-limiting for all traffic types to prevent such BGP flaps.
By injecting DHCP traffic at a fast enough rate and verifying that they are indeed throttled.
> [tests/copp]: Update copp mgmt tests to support new rate-limits

- ansible/library/announce_routes.py
Summary:
Route Announce/Withdraw in Parallel for T2 topologies.
There are 2 motivations for this.
1. As the route scale and number of neighbors are higher for various T2 topologies, the announce-route script takes longer(6+ mins for T2 topology), which increases the overall time for add-topo. We are coming up with even higher scaled t2 topologies, which would make this even worse.
2. New testcases are being added to verify stress route churns. this change could be reused in those testcases.
Created route sets as part of generate_route code. And used python's Threadpool functionality to create pool of processes to process these sets in parallel.
Also fixed a typo where action was hardcoded("announce") for t2 topologies.
 #### How did you verify/test it?
Executed add-topo script for T2 …
> Enable Parallel announcement/withdrawal of routes for T2 topologies

- ansible/testbed_add_vm_topology.yml
- ansible/testbed_remove_vm_topology.yml
- ansible/testbed_renumber_vm_topology.yml
https://github.com/sonic-net/sonic-mgmt/pull/6303 asked to replace use_own_value to vm_host_xxx which override all ansible connection variables.
see the following lines in ansible/group_vars/all/creds.yml and ansible/group_vars/vm_host/creds.yml
vm_host_user: use_own_value
vm_host_password: use_own_value
vm_host_become_password: use_own_value
and a related task in ansible/testbed_add_vm_topology.yml
- set_fact: ansible_user="{{ vm_host_user }}"
when: vm_host_user is defined
These variables are now compared to default before changing all ansible connection values.
This could make the KVM Testbed configuration simpler (docs/testbed/README.testbed.VsSetup.md) as the configuration could now only ask to set ansible_user for STR-ACS-VSERV-01 (and even this could even been done automatically …
> Stop overriding all ansible connection variables with 'use_own_value'

- tests/pytest.ini
Summary:
When we use python3 env to run tests, it would use latest pytest by default, with junit_family=xunit2, which would not generate "file" and "line" field in test result xml file
Use junit_family=xunit1 by default in pytest.ini file
Run test in python2 and python3 env, difference is only "file" and "line" fields in xml file
> Use xunit1 as default junit family version

- test_reporting/junit_xml_parser.py
Summary:
In test summary, failures += failure + error, but in fact, if a testcase failed with both failure and error, the count of failure and error would both +1, so it's unnecessary to calculate in that way
Let failures += failure
Run a test with both failure and error, and check the test result xml file
> Fix failure case number in test result summary incorrect issue

- ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
NTPsec by default wants to log statistics to a file (or at least check to see that the statistics directory exists, even if no logging is enabled). To match the behavior we had with NTP where no logging is enabled, don't configure the statistics directory for NTPsec, and ignore any errors about it not existing.
Tested on Bookworm image by running `generic_config_updater/test_aaa.py` test suite. This suite was previously failing with loganalyzer errors from ntpd.
> For NTPsec, ignore error about statistics directory not existing

- tests/common/dualtor/dual_tor_utils.py
- tests/dualtor/test_tor_ecn.py
Summary: 
When test_dscp_to_queue_during_encap_on_standby and test_ecn_during_encap_on_standby are run in mixed or A-A topology, while randomly selecting PTF IP to test we sometimes select IP mapped to a port with active-active config.. If we select such PTF IP, we won't see expected behavior. With this PR we have added a check to force A-S if this test case is run.
Second part of the change in related to handling the code flow for test cases in test_tor_ecn.py if SYSTEM_DEFAULTS config is not present.
https://github.com/sonic-net/sonic-mgmt/issues/10078
Type of change
[x ] Test case(new/improvement)
Back port request
202205
Approach
Why I did it
To select PTF IP mapped to a port with active-standby mux config AND to avoid below error when SYSTEM_DEFAULTS is not present. …
> dualtor_test_tor_ecn mixed and a-a topo failure fix

- tests/common/devices/sonic_asic.py
Summary:
As describe in issue https://github.com/sonic-net/sonic-mgmt/issues/10399, the `sonic-cfggen` call from the portchannel_on_asic() method in `tests/common/devices/sonic_asic.py` fails when run on an asic that has no portchannels.  
This PR updates portchannel_on_asic() to handle the error returned by `sonic-cfggen` in this case.
> Fix the portchannel_on_asic() method to handle asic with no portchannels

- ansible/roles/test/files/ptftests/py3/voq.py
Do not set_do_not_care for `id` field because IPv6 header does not have this field. 
```
(Pdb) fields_desc
[<BitField (IPv6,IPerror6).version>, <BitField (IPv6,IPerror6).tc>, <BitField (IPv6,IPerror6).fl>, <ShortField (IPv6,IPerror6).plen>, <ByteEnumField (IPv6,IPerror6).nh>, <ByteField (IPv6,IPerror6).hlim>, <SourceIP6Field (IPv6,IPerror6).src>, <DestIP6Field (IPv6,IPerror6).dst>]
(Pdb) 
```
Fix the name of checksum field, which should be `cksum`, not `chksum`.
```
(Pdb) fields_desc
[<ByteEnumField (ICMPv6Unknown).type>, <ByteField (ICMPv6Unknown).code>, <XShortField (ICMPv6Unknown).cksum>, <StrField (ICMPv6Unknown).msgbody>]
(Pdb) 
```
These issues were there before py3 migration.  But py2 ptf implementation of `set_do_not_care_scapy` does not raise exception for wrong field name. So …
> Fix voq test for py3

- tests/generic_config_updater/test_ntp.py
Summary:
In Bookworm, NTP has been replaced with NTPsec. Add a check to see if NTPsec's config file is present, then use that config file instead of /etc/ntp.conf.
Tested on Bookworm image by manually running `generic_config_updater/test_ntp.py` test case.
> Update GCU's NTP test case for Bookworm

- tests/stress/test_stress_routes.py
this log is expected because its a stress test and can keep the orchagent busy long enough to make this log appear.
Summary:
ADO 25061640
> [testfix] stress_test_routes. Added syslog ignore

- tests/common/plugins/sanity_check/recover.py
Summary:
If a DUT is in an unhealthy state, and `config reload` needs to be done to recover it, then also wait for BGP sessions to come up. This shouldn't add much delay in most cases. However, there was one case where during recovery, orchagent hit a crash which brought down most of the container.
The hopes is that with this additional check, in case orchagent happens to go down again, the testbed health check will wait here before starting the test case execution.
The particular issue for which this PR is made appears to be happening rarely, and since this is all timing-based, it might not be easy to repro.
> When recovering a DUT with config_reload, wait for BGP sessions to be up

- ansible/roles/test/files/ptftests/fib_test.py
- ansible/roles/test/files/ptftests/py3/IP_decap_test.py
- ansible/roles/test/files/ptftests/py3/hash_test.py
Summary:
**This is the manual cherry-pick of PR #10415 for conflict resolving.**
The fib/decap tests occasionally fail on or testbeds due to some random packet is not received by the ptf. After the debugging we found that there may be a big delay(max 0.3s observed on our testbed) between the packet is send by the ptf src port and received by the ptf dst port.
We suspect it could be introduced by the lag on the server side, because we see this failure mostly on the t1-lag/t1-lag-64 topologies.
And in the fib hash test, it looks like sometimes the packet is totally lost on the server(we have checked that there was no packet loss on the dut and fanout).
We have found a way to prevent this failure by:
1. Add a timeout in the ptf verify_packet_any_port method, with the timeout, the ptf adapter …
> [202205] Improve the stability of fib/decap test

- ansible/roles/test/files/ptftests/fib_test.py
- ansible/roles/test/files/ptftests/py3/IP_decap_test.py
- ansible/roles/test/files/ptftests/py3/hash_test.py
Summary:
The fib/decap tests occasionally fail on or testbeds due to some random packet is not received by the ptf. After the debugging we found that there may be a big delay(max 0.3s observed on our testbed) between the packet is send by the ptf src port and received by the ptf dst port.
We suspect it could be introduced by the lag on the server side, because we see this failure mostly on the t1-lag/t1-lag-64 topologies.
And in the fib hash test, it looks like sometimes the packet is totally lost on the server(we have checked that there was no packet loss on the dut and fanout).
We have found a way to prevent this failure by:
1. Add a timeout in the ptf verify_packet_any_port method, with the timeout, the ptf adapter will constantly poll in the dataplane until the timeout elapse.
2. …
> Improve the stability of fib/decap test

- tests/saitests/py3/sai_qos_tests.py
Summary:
Double commit of #10356 to 202205 branch due to anticipated conflicts. 
During the extreme memory congestion present in this test, lossy traffic can be dropped. We should not assert that no lossy ingress drops occurred. 
Additionally:
- Reduced/removed unnecessary sleep times to improve test speed.
- Fix redundant counter reads. 
Verified on Cisco-8000 T1. 
This is a Cisco-8000 specific test.
> Fix SharedResSize lossy drop flaky failure for 202205

- tests/drop_packets/drop_packets.py
- tests/drop_packets/test_drop_counters.py
Summary:
Three issues to be fixed:
1. Add back the missing drop counters cases
Fixes issue https://github.com/sonic-net/sonic-mgmt/issues/10306
Add back the missing drop counters cases which were mistakenly removed by PR#8001.
2. The logic for choosing the fanout in drop counters test is wrong, it always returns the last fanout in the list, which causes the test to fail on dualtor testbed if the lower tor is selected as the dut.
```
def get_fanout_obj(conn_graph_facts, duthost, fanouthosts):
fanout_obj = None
for fanout_name, fanout_obj in list(fanouthosts.items()):
for interface, interface_info in list(conn_graph_facts['device_conn'][duthost.hostname].items()):
if fanout_name == interface_info.get('peerdevice'):
break   - This only breaks the inner loop, the outer loop will continue even …
```
> Fix test issues of drop counters test

- tests/drop_packets/drop_packets.py
- tests/drop_packets/test_drop_counters.py
Summary:
This is to cherry-pick PR https://github.com/sonic-net/sonic-mgmt/pull/10308 to 202205 for conflict resolving.
Two issues to be fixed:
1. The logic for choosing the fanout in drop counters test is wrong, it always returns the last fanout in the list, which causes the test to fail on dualtor testbed if the lower tor is selected as the dut.
```
def get_fanout_obj(conn_graph_facts, duthost, fanouthosts):
fanout_obj = None
for fanout_name, fanout_obj in list(fanouthosts.items()):
for interface, interface_info in list(conn_graph_facts['device_conn'][duthost.hostname].items()):
if fanout_name == interface_info.get('peerdevice'):
break   - This only breaks the inner loop, the outer loop will continue even when the correct fanout is found.
return fanout_obj
```
2. There are 2 test cases …
> [202205] Fix test issues of drop counters test

- tests/read_mac/conftest.py
- tests/read_mac/test_read_mac_metadata.py
Summary:
The test arguments `image1`, `image2` and `iteration` are set to required arguments in test module `test_read_mac_metadata.py` . If the test pipeline doesn't set the argument, an error is thrown
```
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: the following arguments are required: --iteration, --image1, --image2
```
To reduce noise, the arguments are changed to be optional, and the test will be skipped if any of the arguments is missing. 
This PR is to skip test_read_mac_metadata if required parameters are missing.
To reduce noise, the arguments are changed to be optional, and the test will be skipped if any of the arguments is missing. 
The change is verified on a physical testbed. The test is skipped if the argument is not set.
``` …
```
> Skip test_read_mac_metadata if required parameters are missing

- tests/override_config_table/test_override_config_table_masic.py
Summary:
test_override_config_table_masic failed for box testbed
```
{"changed": true, "cmd": "cp /etc/sonic/config_dbNone.json /etc/sonic/config_dbNone.json_before_override",
"delta": "0:00:00.004615",
"end": "2023-10-29 21:47:30.281705",
"failed": true, "msg": "non-zero return code",
"rc": 1, "start": "2023-10-29 21:47:30.277090",
"stderr": "cp: cannot stat '/etc/sonic/config_dbNone.json': No such file or directory",
"stderr_lines": ["cp: cannot stat '/etc/sonic/config_dbNone.json': No such file or directory"], "stdout": "",
"stdout_lines": []}
```
RCA:
need to skip chassis's config backup and restore behavior when asic_id is None
skip chassis's config backup and restore behavior
```
- generated xml file: …
```
> skip box tb in setup of test_override_config_table_masic

- tests/qos/qos_sai_base.py
dutConfig run to error on T0/T1:
```
qos/test_qos_sai.py::TestQosSai::testParameter[single_asic]
-------------------------------- live log setup --------------------------------
08:43:01 __init__._fixture_generator_decorator    L0088 ERROR  |
UnboundLocalError("local variable 'dst_asic' referenced before assignment")
File "/var/src/sonic-mgmt_vms2-t1-7260-7_646f1406735219c3e54440f7/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
res = next(it)
File "/var/src/sonic-mgmt_vms2-t1-7260-7_646f1406735219c3e54440f7/tests/qos/qos_sai_base.py", line 1002, in dutConfig
if dst_asic != src_asic:
UnboundLocalError: local variable 'dst_asic' referenced before assignment
ERROR    
```
Summary:
Issue was introduced by …
> fix dutConfig error on T0/T1

- ansible/library/switch_capabilities_facts.py
Summary:
This is the fix for issue #8666.
In the script ansible/library/switch_capabilities_facts.py, we should only run the method SonicDBConfig.load_sonic_global_db_config() when the dut is multi-asic, otherwise the error in #8666 will be printed.
To fix issue #8666.
Don't run SonicDBConfig.load_sonic_global_db_config() on single asic duts.
Run any test on a single asic dut, the error no longer reproduce.
> Fix for issue #8666

- tests/pfcwd/files/pfcwd_helper.py
- tests/pfcwd/test_pfcwd_all_port_storm.py
- tests/pfcwd/test_pfcwd_function.py
- tests/pfcwd/test_pfcwd_warm_reboot.py
Summary:
Enhance PFC watchdog diagnosis information checking.
Recently, more diagnosis information has been introduced when PFC watchdog is triggered for some vendors.
This is to verify whether the diagnosis information is reported in the syslog.
1. Check diagnosis information in PFC watchdog detection message on a per-vendor basis
2. Move the expected log message pattern to a common file 
3. In warm reboot scenario, the PFC watchdog can be reported based on APPL_DB content instead of counters. In this case, no additional information can be provided. So, do not check  diagnosis information in this case.
4. Do not check it on the branches that it is not supported, like 202211.
Run regression test PFC watchdog
> Enhance PFC watchdog log analyzer to check debug information on a per-vendor basis

- ansible/roles/test/files/ptftests/fib_test.py
- ansible/roles/test/files/ptftests/py3/hash_test.py
In case of chassis-packet switch type, when src port of the traffic is on the same DUT and same asic as destination port, it sends out traffic only on the ports that belong to the same asic. Currently both fib_test and hash_test was set to send out on ports that belonged to different asic causing the balancing test to fail. THis change pertains only to chassis-packet switch type 
Summary:
Fix balancing test for chassis packet switch type
> Select only ports belonging to same asic - chassis-packet

- tests/saitests/py3/sai_base_test.py
- tests/saitests/py3/sai_qos_tests.py
Fix issue: https://github.com/sonic-net/sonic-mgmt/issues/10299
Because the method to generate congestion for Mellanox device is changed from disabling the whole port to disabling the queue one by one, and when we recover the port, we also enable the queue one by one. So, it will cause testQosSaiDwrr to fail. testQosSaiDwrr is to test the function of scheduling queue to send packets, the pre-condition is that all queues should be at the same enabled state, but currently, they are enabled back one by one, so the order to send packets is the same as the order to enable the queue not depending on the scheduling algorithm. So, for this case, we still use the original method to generate congestion.
Summary:
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/10299
Fix issue : …
> [Mellanox] Fix testQosSaiDwrr issue

- tests/common/config_reload.py
Summary:
In the common function `config_reload`, variable `modular_chassis` at Line 135 is a **string** `False` instead of a boolean. It's treated as `True` in the `if` statement at Line 136 and can never hit the `else` section. So the `config_reload` function **always wait at least 4 minutes**.
```
> /home/zhijianli/mgmt/sonic-mgmt-int/tests/common/config_reload.py(136)config_reload()
-> wait = max(wait, 240) if modular_chassis else wait
(Pdb) l
130             cmd = 'config reload -y -l /etc/sonic/running_golden_config.json &>/dev/null'
131             if config_force_option_supported(sonic_host):
132                 cmd = 'config reload -y -f -l /etc/sonic/running_golden_config.json &>/dev/null'
133             sonic_host.shell(cmd, executable="/bin/bash")
134         import pdb; …
```
> [BUGFIX] Fix the wait time for `config_reload` function

- tests/tacacs/test_ro_disk.py
Summary:
The Test Case  tacacs/test_ro_disk.py::test_ro_disk, in finally block a reboot is performed, currently, the condition for reboot to be successful is to check the docker is running, the enhancement done is to wait till all the critical process in the docker are up and the interfaces are also up for all the line cards in case the supervisor is rebooted
The Particular improvement is required due to the changes with respect to PR https://github.com/sonic-net/sonic-buildimage/pull/16213. The Parent PR on Master was merged https://github.com/sonic-net/sonic-mgmt/pull/9893
The Parent Master PR https://github.com/sonic-net/sonic-mgmt/pull/9893
The Particular improvement is required due to the changes with respect to PR https://github.com/sonic-net/sonic-buildimage/pull/16213. 
Assertion …
> [202205] test_ro_disk: Enhancement for reboot of supervisor card

- tests/route/test_route_perf.py
Summary:
This PR is to ignore error log.
```
ERR swss#supervisor-proc-exit-listener: Process 'orchagent' is stuck in namespace 'host' (1.0 minutes).
```
The log is expected during the route performance test.
This PR is to ignore orchagent stuck error log in route perf test.
Add the log pattern into ignore list.
Verified on a SN2700 testbed.
```
collected 2 items                                                                                                                                                                                     
route/test_route_perf.py::test_perf_add_remove_routes[4-str-msn2700-06-None] ^[[C ^HPASSED                                                                                                             [ 50%] …
```
> Ignore orchagent stuck error log in route perf test

- tests/common/devices/sonic.py
- tests/common/dualtor/mux_simulator_control.py
Summary:
Sanity check observed during dualtor nightly in 202305:
1. `monit` check failure.
2. mux config is observed in `manual` mode.
1. Enable verbose mode when check monit status
2. Config save after confg mux auto in mux toggle fixture
run `test_hash` on dualtor testbed.
> [dualtor] Improve sanity check

- tests/show_techsupport/conftest.py
Summary:
25424807
The case failed due to the below error message.
E               Oct 18 21:49:42.847851 str-a7060cx-acs-1 DEBUG systemd[1]: Got message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/dev_2ddisk_2dby_5cx2dlabel_2deos_5fcrash_2edevice interface=org.freedesktop.DBus.Properties member=GetAll cookie=187 reply_cookie=0 signature=s error-name=n/a error-message=n/a
The failure message should be the debug level message, should be a false alarm.
Ignore it
case pass
> ignore DEBUG systemd message in show_techsupport case module

- tests/qos/qos_sai_base.py
- tests/qos/test_qos_sai.py
- tests/saitests/py3/sai_qos_tests.py
Summary:
to fix hdrm size test failure caused by improper qos param, enhance brcm internal qos generator tool
and modified relevant test code 
1) change generator's api, to pass a list of option to generator rather than lots of variable. just in case that api need to change in future
2) skip test if testbed have no enough test port
3) to be compatible with other vendor, introduce new qos parameter 'pkts_num_trig_pfc_multi' to hdrm size test.
to support hdrm size test in dynamic threshold mode in which mode each PR and port have different xoff threashold.
> hdrm size test case changes, after generate new hdrm size test param

- tests/common/plugins/sanity_check/recover.py
Summary:
Currently, sanity check recover would use config db to do config reload, but there could be a risk if config db was changed and saved by previous test
Use golden config to do config reload
> Use golden config to recover testbed when sanity check failed

- tests/saitests/py3/sai_qos_tests.py
Summary:
The issue was introduced by PR https://github.com/sonic-net/sonic-mgmt/pull/8149 .
The wrong variables are used for building testing packet, that results in test failure.
This PR is to fix code bug in ```TunnelDscpToPgMapping```. The test is consistently failing because incorrect DSCP values are used for creating packets.
Fix the code issue.
The change is verified on a dualtor testbed.
```
qos/test_tunnel_qos_remap.py::test_tunnel_decap_dscp_to_pg_mapping  ^H ^HPASSED …
```
> Fix tunnel dscp to pg mapping test

- tests/common/plugins/sanity_check/checks.py
Summary:
There is an issue that the mux status is retrieved only once, the retry
of mux check `_verify_inconsistent_mux_status` is using the result
instead of retrieving the mux status.
1. retrieve the mux status in each retry.
2. wait longer for 60s instead of 30s.
Run dualtor-io tests
> [sanity-check][dualtor] Retrieve the mux status in each retry

- tests/bgp/test_bgp_suppress_fib.py
Summary:
ADO: 25564723
In current test, it will set the bgp suppress to disabled no matter what's the value in the config_db. If it is enabled before the test, it should honor it,  and don't change it after the test. 
In this PR, will add a check logic to restore only it is needed.
To read back the config db before test, then do the restore when it is needed.
1. enable the fib suppress.
2. run bgp suppress fib test. 
3. check the config, if it is same as before.
> Enhance restore_bgp_suppress_fib to check status first

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Original test_override_config_table_masic.py is added on multi-asic platform in https://github.com/sonic-net/sonic-mgmt/pull/9923. 
But fixture `setup` is still getting called on single-asic and had issue with config db backup for single-asic, because of config_db naming.
https://github.com/sonic-net/sonic-mgmt/pull/10363 add skip for whole test if:
```
conditions:
- is_multi_asic == True
```
This condition is always true for chassis. Because if any sup/card is multi-asic, it returns true.
https://github.com/sonic-net/sonic-mgmt/pull/10522 later handles backup of config db in test_override_config_table_masic.py  on when asic exists, in that case backup of single-asic won't happen. 
This PR is to revert the skips added in https://github.com/sonic-net/sonic-mgmt/pull/10363. With the …
> [override_config] Remove skip for override config tests in tests_mark_conditions.yaml

- tests/stress/test_stress_routes.py
Some platforms take a little more time to program routes in HW during this
stress test, so CRM checks may fail. The change here is to give it more time
before checking for CRM counters. With this change, the test seems to pass
consistently on dualtor testbeds with internal image.
Summary:
Fixes # 24468219
Some platforms might need more time for route programming as done in this stress test.
By increasing the sleep time before checking for crm resources
By running this sonic-mgmt tests multiple times on dualtor testbed
> [tests/stress]: Increase sleep time before checking for crm resources

- tests/saitests/py3/sai_base_test.py
Summary:
This PR is to fix KeyError in `get_queue_scheduler_name`
```
ERROR: sai_qos_tests.PCBBPFCTest
File \"saitests/py3/sai_qos_tests.py\", line 4779, in runTest
self.sai_thrift_port_tx_disable(self.dst_client, asic_type, [dst_port_id])
File \"saitests/py3/sai_base_test.py\", line 230, in sai_thrift_port_tx_disable
self.disable_mellanox_egress_data_plane(port_list)
File \"saitests/py3/sai_base_test.py\", line 235, in disable_mellanox_egress_data_plane
self.original_dut_port_queue_scheduler_map = self.get_queue_scheduler_name(ptf_port_list)
File \"saitests/py3/sai_base_test.py\", line 253, in …
```
> Fix key Error in get_queue_scheduler_name

- ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
We will remove telemetry container in public repo, and FEATURE config for telemetry is still enabled.
Therefore, we need ignore syslog error.
Update loganalyzer_common_ignore.txt.
> Ignore telemetry container in loganalyzer check

- tests/drop_packets/drop_packets.py
- tests/drop_packets/test_drop_counters.py
Summary:
This PR is to fix error in `test_drop_counter`.
```
drop_packets/drop_packets.py:763: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
drop_packets/test_drop_counters.py:273: in do_counters_test
exp_pkt = expected_packet_mask(pkt)
drop_packets/drop_packets.py:233: in expected_packet_mask
exp_pkt.set_do_not_care_scapy(packet.IP, 'ttl')
/var/AzDevOps/env-python3/lib/python3.8/site-packages/ptf/mask.py:74: in set_do_not_care_scapy
self.set_do_not_care_packet(hdr_type, field_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
> Fix `Unknown header type` in drop counter test

- tests/ipfwd/test_nhop_group.py
Summary:
Add testcase to validate following scenario:
1) ECMP group create NHG1
2) Route R1 pointing to ECMP NHG1
3) Packet drop based on R1 lookup
4) ECMP member addition to NHG1
5) Packet forward based on the ECMP members.
To validate route pointing to empty ECMP group and ECMP member addition.
1) Add ARP entries.
2) Enable kernel flag not to evict ARP entries when the interface goes down.
3) Bring down the fanout switch ports corresponding to ARP entries.
4) Add a route with ECMP. Sonic orchagent skips the Nexthops with the interface down.
5) Verify packet drop as route points to ECMP with no members.
6) Bring up the fanout switch ports.
7) Now Sonic orchagent adds the Nexthops to the ECMP group.
8) Verify packet forwarding based on the ECMP group.
9) Enable kernel flag to evict ARP …
> Add testcase to validate ECMP with no members and member addition

- tests/qos/qos_sai_base.py
Summary:
Fix the issue that the testcase that runs after `test_qos_sai` fails to toggle to the upper ToR.
The reason is that, in the teardown of `test_qos_sai`, it doesn't start the `mux` container on the upper ToR, and the `mux` feature disable config is saved to `config_db.json` by `enable_container_autorestart`. 
Start the `mux` in teardown.
> [test_qos_sai] Start the mux on the upper ToR in teardown

- tests/common/devices/multi_asic.py
Summary:
`mux` is not verified in `sanity_check` critical process check.
Add `mux` to the critical service list if it is a dualtor device.
> [dualtor] Add `mux` to the critical service list to enable sanity check

- ansible/library/announce_routes.py
Summary:
Route Announce/Withdraw in Parallel for T2 topologies.
- [] 202205
There are 2 motivations for this.
1. As the route scale and number of neighbors are higher for various T2 topologies, the announce-route script takes longer(6+ mins for T2 topology), which increases the overall time for add-topo. We are coming up with even higher scaled t2 topologies, which would make this even worse.
2. New testcases are being added to verify stress route churns. this change could be reused in those testcases.
Created route sets as part of generate_route code. And used python's Threadpool functionality to create pool of processes to process these sets in parallel.
Also fixed a typo where action was hardcoded("announce") for t2 topologies.
 #### How did you verify/test it?
Executed add-topo script …
> Enable parallel advertise/withdraw of routes

- ansible/roles/test/files/ptftests/radv_ipv6_ra_test.py
- ansible/roles/test/files/ptftests/router_adv_mflag_test.py
- tests/dhcp_relay/test_dhcp_pkt_fwd.py
- tests/drop_packets/drop_packets.py
- tests/drop_packets/test_configurable_drop_counters.py
- tests/ecmp/test_fgnhg.py
- tests/everflow/test_everflow_ipv6.py
- tests/everflow/test_everflow_per_interface.py
- tests/mpls/conftest.py
- tests/nat/nat_helpers.py
- tests/nat/test_static_nat.py
- tests/passw_hardening/passw_hardening_utils.py
- tests/pfcwd/test_pfcwd_all_port_storm.py
- tests/pfcwd/test_pfcwd_timer_accuracy.py
- tests/platform_tests/test_auto_negotiation.py
- tests/platform_tests/thermal_control_test_helper.py
- tests/qos/conftest.py
- tests/qos/test_buffer_traditional.py
- tests/qos/test_qos_masic.py
- tests/route/test_route_perf.py
- tests/show_techsupport/test_techsupport.py
- tests/snmp/test_snmp_memory.py
- tests/stress/conftest.py
- tests/stress/utils.py
- tests/vrf/test_vrf.py
Summary:
After ansible version of sonic-mgmt docker image is upgraded to 6.7, some scripts failed with errors like:
global name 'os' is not defined
I don't know the reason why these issues are exposed after ansible upgrade. Anyway, these scripts are using modules before import them and need fix.
This change added missing imports for the modules. What's more, this change also fixed some other undefined name issue.
This change is only for 202205 branch. The master and 202305 branch are protected by pre-commit and do not have this issue.
> [202205] Add missing imports exposed after ansible upgrade

- tests/acl/custom_acl_table/test_custom_acl_table.py
Summary:
This PR is to fix Python3 syntax issue in test_custom_acl_table.py.
The error message is
```
if "dualtor" in tbinfo["topo"]["name"]:
>           vlan_name = mg_facts['minigraph_vlans'].keys()[0]
E           TypeError: 'dict_keys' object is not subscriptable
```
This PR is to fix Python3 syntax issue in test_custom_acl_table.py.
Convert the keys to list explicitly.
Verified by syntax check.
No.
This change is dualtor specific.
> Fix Python3 syntax issue in test_custom_acl_table.py

- tests/common/plugins/sanity_check/recover.py
Summary:
Currently, sanity check recover would use config db to do config reload, but there could be a risk if config db was changed and saved by previous test
PR in master: https://github.com/sonic-net/sonic-mgmt/pull/10608
Use golden config to do config reload
> [202205] Use golden config to recover testbed when sanity check failed

- tests/common/plugins/sanity_check/recover.py
Summary:
Currently, sanity check recover would use config db to do config reload, but there could be a risk if config db was changed and saved by previous test
PR in master: https://github.com/sonic-net/sonic-mgmt/pull/10608
Use golden config to do config reload
> [202305] Use golden config to recover testbed when sanity check failed

- ansible/roles/test/files/ptftests/py3/hash_test.py
Summary:
IPv6 header do not have field 'checksum'
ref PR: https://github.com/sonic-net/sonic-mgmt/pull/6407
Remove mask of checksum field for IPv6 header as this field is no present in IPv6 header
> Remove scapy mask on chksum for IPv6 Header

- tests/common/fixtures/advanced_reboot.py
Summary:
This PR is to force reset warmboot system flag back to `false` as a cleanup step after warmboot tests.
Add an extra step in `AdvanceReboot` teardown function. 
Ran test on a lab device: 
```
01:04:51 __init__._fixture_generator_decorator    L0093 INFO   | -------------------- fixture get_advanced_reboot teardown starts --------------------
01:04:51 advanced_reboot.tearDown                 L0836 INFO   | Running test tear down
01:04:51 advanced_reboot.__checkWarmbootFlag      L0829 INFO   | warmbootFlag: false
01:04:52 advanced_reboot.__runScript              L0301 INFO   | Running script remove_ip.sh on vms28-10
01:04:52 advanced_reboot.tearDown                 L0864 INFO   | Stay in new image
01:04:52 …
```
> [warmboot][teardown] force reset warmboot system flag after warmboot tests

- tests/common/devices/multi_asic.py
https://github.com/sonic-net/sonic-mgmt/pull/10234 introduced a wrapper function `def run_redis_cmd` to call redis command on asic in multi_asic.py, but it does not return the stdout value. This causes failure on some dualtors and the T1 that connects to dualtor.
This PR adds a return in wrapper function that returns the result['stdout'] here: https://github.com/sonic-net/sonic-mgmt/blob/635d4b15979195de92f149319570e17ad27dca14/tests/common/devices/sonic_asic.py#L435
Summary:
before:
```
dual_tor_utils.dualtor_ports             L1493 INFO   | Finish fetching dual ToR info set()
```
after:
```
dual_tor_utils.dualtor_ports             L1417 INFO   | Finish fetching dual ToR info set([u'Ethernet152', u'Ethernet180', u'Ethernet200', u'Ethernet168', u'Ethernet156', …
```
> [dualtor] fix command to get dualtor_ports

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip test_pktgen.py in non-Cisco platform
This case was introduced in: #10164
This testcase failed in non-Cisco platform.
Skip test_pktgen.py in non-Cisco platform
N/A
> Skip test_pktgen.py in non-Cisco platform

- tests/bfd/test_bfd.py
Summary:
Fixes test_fbd.py flaky result
The result of test_bfd.py is flaky.
Increase sleep time before check bfd status.
Run 300 time and 100% pass on Cisco platform
> Fix test_fbd.py flaky result

- ansible/roles/test/files/ptftests/py3/copp_tests.py
- tests/copp/test_copp.py
The ARPTest for COPP involves PTF sending ARP request packets at some high rate and confirming that the DUT punts them to CPU but at configured policed rate of 600 packets/second.  To account for inaccuracies of the policers and the test itself, the test verifier allows a range around this 600 packets/second. The range is 0.9 * 600 = 540 to 1.3 * 600 = 780.
After some experiments by pumping ARP request from TGEN, it was observed that the punted packet was sometimes slightly more than 780.  In the past, when we  have seen this test pass, the punted packet count was slightly below 780 which means, the test was barely passing before. So we need to modify the limit and allow a bit tolerance.
Summary:
> COPP: Update the PPS max limit to allow bit more tolerance

- ansible/roles/test/files/ptftests/IP_decap_test.py
- ansible/roles/test/files/ptftests/fib_test.py
- ansible/roles/test/files/ptftests/hash_test.py
- ansible/roles/test/files/ptftests/voq.py
- tests/container_checker/test_container_checker.py
- tests/route/test_static_route.py
Summary:
IPv6 header do not have field 'checksum', if set do not care 'checksum' would cause failure "MaskException: Field chksum does not exist in frame"
ref PR: https://github.com/sonic-net/sonic-mgmt/pull/6407
> [202012] Remove scapy mask on chksum for IPv6 Header

- tests/common/plugins/sanity_check/recover.py
Summary:
Currently, sanity check recover would use config db to do config reload, but there could be a risk if config db was changed and saved by previous test
PR in master: https://github.com/sonic-net/sonic-mgmt/pull/10608
Use golden config to do config reload
> [202012] Use golden config to recover testbed when sanity check failed

- ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
Fixes sonic-net/sonic-buildimage#17034
When exiting, ntpd from NTPsec logs a message containing ERR at NOTICE level saying that it is exiting because of a signal. This causes loganalyzer to flag the message because ERR is present. This log message happens during graceful termination (such as when systemd is restarting the service). Therefore, ignore it.
This is applicable only to a Bookworm base image.
Add the log message regex (but looking only for signal 15) to the loganalyzer ignore list. If other exits with other signals pop up on loganalyzer, they can be handled or added as needed.
> Ignore NTP exiting "error" message

- tests/platform_tests/mellanox/check_sysfs.py
Summary:
This PR is to fix `TypeError` in `check_sysfs`. The error message is as below.
```
File "/var/src/sonic-mgmt_vms2-4-t0-2700_646f1405735219c3e54440f2/tests/platform_tests/test_reboot.py", line 167, in test_cold_reboot
reboot_and_check(localhost, duthost, conn_graph_facts["device_conn"][duthost.hostname],
File "/var/src/sonic-mgmt_vms2-4-t0-2700_646f1405735219c3e54440f2/tests/platform_tests/test_reboot.py", line 91, in reboot_and_check
check_interfaces_and_services(dut, interfaces, xcvr_skip_list, reboot_type=reboot_type)
File "/var/src/sonic-mgmt_vms2-4-t0-2700_646f1405735219c3e54440f2/tests/platform_tests/test_reboot.py", line 140, in check_interfaces_and_services
check_sysfs(dut)
File "/var/src/sonic-mgmt_vms2-4-t0-2700_646f1405735219c3e54440f2/tests/platform_tests/mellanox/check …
```
> Fix TypeError in check_sysfs

- ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
- tests/common/helpers/gnmi_utils.py
- tests/gnmi/helper.py
- tests/minigraph/test_masked_services.py
- tests/telemetry/conftest.py
- tests/telemetry/telemetry_utils.py
- tests/telemetry/test_telemetry.py
- tests/test_posttest.py
- tests/test_pretest.py
Summary:
Support share image for gnmi and telemetry
Backport https://github.com/sonic-net/sonic-mgmt/pull/10348
We will share docker image to support gnmi and telemetry.
So we need to update minigraph, gnmi and telemetry test to support this change.
For telemetry test, check telemetry container at first, if there's no telemetry container, use gnmi container.
For gnmi test, check gnmi container at first, if there's no gnmi container, use telemetry container.
For minigraph test, check feature status to choose service.
Run minigraph, gnmi and telemetry end to end test.
> [202305] Support share image for gnmi and telemetry

- tests/platform_tests/mellanox/check_sysfs.py
Summary:
This PR is to fix `TypeError` in `check_sysfs`. The error message is as below.
```
File "/var/src/sonic-mgmt_vms2-4-t0-2700_646f1405735219c3e54440f2/tests/platform_tests/test_reboot.py", line 167, in test_cold_reboot
reboot_and_check(localhost, duthost, conn_graph_facts["device_conn"][duthost.hostname],
File "/var/src/sonic-mgmt_vms2-4-t0-2700_646f1405735219c3e54440f2/tests/platform_tests/test_reboot.py", line 91, in reboot_and_check
check_interfaces_and_services(dut, interfaces, xcvr_skip_list, reboot_type=reboot_type)
File "/var/src/sonic-mgmt_vms2-4-t0-2700_646f1405735219c3e54440f2/tests/platform_tests/test_reboot.py", line 140, in check_interfaces_and_services
check_sysfs(dut)
File "/var/src/sonic-mgmt_vms2-4-t0-2700_646f1405735219c3e54440f2/tests/platform_tests/mellanox/check …
```
> [202205] [cherry-pick] Fix TypeError in check_sysfs

- tests/common/dualtor/tor_failure_utils.py
- tests/dualtor_io/test_tor_failure.py
ADO#: 25587797
Summary:
Wait for `pmon` docker to start before verifying `show mux status` output in ToR failure cases. Otherwise, `show mux status` might return error. 
Fix flaky tests. 
Added a `wait_until` checker. 
Ran `test_active_tor_reboot_downstream_standby`, you can tell pmon was up 3 seconds after mux was up. 
```
01:15:49 tor_failure_utils.wait_for_device_reacha L0130 INFO   | Waiting for ssh to startup on str2-7050cx3-acs-08
01:15:59 tor_failure_utils.wait_for_device_reacha L0142 INFO   | SSH started on str2-7050cx3-acs-08
01:16:01 tor_failure_utils.wait_for_mux_container L0182 INFO   | Waiting for mux container to start on str2-7050cx3-acs-08
01:16:02 tor_failure_utils.wait_for_pmon_containe L0203 INFO   | Waiting …
```
> [dualtor_io] wait for `pmon` docker before verification in ToR failure cases 

- ansible/roles/test/files/ptftests/py3/advanced-reboot.py
Summary:
In #10107, when doing a warm reboot with SONiC neighbors, instead of going to the neighbor device to get the LAG flap information, the code was changed to reuse information that was already collected and returned. However, the code to access that information is wrong, and needs to access the `po` key first.
Fix this error by updating the code.
Verfied by doing a warm upgrade from sonic-mgmt with SONiC neighbros and making sure that it succeeded and the LAG flap information was correctly read.
> Fix an error in parsing the neighbor analysis for SONiC neighbors

- ansible/roles/test/files/ptftests/py3/advanced-reboot.py
Summary:
When doing a warm reboot with SONiC neighbors, assuming all images involved support the teamd retry count feature, up to 150 seconds of LACP downtime is allowed. Therefore, bump up the limit to 150 seconds before logging a failure.
Verified in manual runs with this change that >90 of LACP downtime didn't cause a failure.
> Allow 150 seconds of LACP downtime for warm reboot with vSONiC neighbors

- tests/common/dualtor/data_plane_utils.py
- tests/common/dualtor/dual_tor_io.py
- tests/dualtor_io/conftest.py
Summary:
1. Cleanup any pcap files before the sniffer starts.
2. Save the pcap file to the log directory so it could be collected by the nightly for further analysis.
As in the motivation.
Run dualtor-io testcase
> [dualtor-io] cleanup and collect pcap file

- tests/qos/qos_sai_base.py
Summary:
Cherry-pick PR https://github.com/sonic-net/sonic-mgmt/pull/10656 into 202205
> [202205][test_qos_sai] Start the mux on the upper ToR in teardown (#10656)

- tests/saitests/py3/sai_qos_tests.py
Summary:
Fixes specific T0 dualtor test cases that require more than the basic ports to run. ARP was only being performed on the src port and 3 dst ports, but not the rest. This fails tests like SharedResSize and QWatermarkAllPort since they require the ability to send traffic to/from all ports. 
Verified all test_qos_sai.py tests pass on Cisco-8000 dualtor T0 Active-Standby.
> ARP in sai_qos_tests.py for all test port IDs

- tests/qos/files/mellanox/qos_param_generator.py
- tests/qos/qos_sai_base.py
- tests/qos/test_qos_sai.py
Fix issue: https://github.com/sonic-net/sonic-mgmt/issues/10526
1. When calling QosParamMellanox(), the argument dst_dut_index, dst_asic_index oder is not correct. we should exchange them.
2. The Fanout device doesn't match the duthost
3. When topo is not defined in qos_param['mellanox'], we should use the default one
Summary:
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/10526
Fix https://github.com/sonic-net/sonic-mgmt/issues/10526. ,make QoS sai test running on dualtor setup with Mellanox device
1.  Exchange dst_dut_index, dst_asic_index oder in QosParamMellanox
2. Use duthost to get the peer device_info
3. When topo is not defined in qos_param['mellanox'], we should use the default one
Run qos sai tests on dualtor setup with Mellanox device
Mellanox device
> [Mellanox] Fix qos sai issues on dualtor setup

- tests/acl/test_stress_acl.py
Summary:
The stress ACL test has a relatively low probability of failing during execution. The reason could be that the add and delete of ACLs require some time, and occasionally, the short time frame may cause the add and delete operations to not occur promptly, resulting in test case failure.
Add wait_until to check if acl rule added/deleted in state db.
Run test
> Add wait until in stress acl test

- tests/memory_checker/test_memory_checker.py
The test case test_memory_checker consumes a large amount of memory on the telemetry docker and waits for monit to detect the failure. The testcase waits for 80 seconds currently to see if monit fails. This timeout is not enough. In the testcase monit runs every second and since there are an increased number of checks in monit currently, the cpu does not have enough idle cycles for the monit to detect the failure. Therefore, increasing the timeout to 150 seconds.
Increased the monit fail timeout to 150 seconds
Ran the test multiple times to see if the testcase passes.
NA
NA
NA
> [memory_checker/test_memory_checker] - Increase timeout for memory checker test 

- tests/sub_port_interfaces/test_sub_port_interfaces.py
Summary:
25745148
case sub_port_interfaces/test_sub_port_interfaces.py::TestSubPortStress::test_max_numbers_of_sub_ports failure on internal 
enhance the case for python3
collected 2 items                                                                                                                                                                                                                                                                                                                                                   it is now deprecated in cryptography, and will be removed in the next release.
sub_port_interfaces/test_sub_port_interfaces.py::TestSubPortStress::test_max_numbers_of_sub_ports[port] PASSED …
> enhance test_max_numbers_of_sub_ports for python3

- ansible/devutil/devices/ansible_hosts.py
Summary:
The AnsibleHostBase class of devutil is not able to distinguish host unreachable scenario and run ansible module failed scenario.
This change enhanced the AnsibleHostBase class to explicitly raise HostsUnreachable exception when any of the host is unreachable while running ansible module.
This change also added a "reachable" method to the AnsibleHostBase class. This method runs ansible "ping" method to check if SSH connection can be successfully established to the hosts. It returns the test results in a tuple. The first in tuple is a bool explicitly indicating if all the hosts are reachable or not. The second item is a dict of detailed ping test results.
> Gracefully handle hosts unreachable for AnsibleHostBase of devutil

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Skip test_bgp_queue for m0/mx.
**The skip condition is included in this PR was also included in https://github.com/sonic-net/sonic-mgmt/pull/10102, which should not be backport, so manually update it.**
Add skip condition.
Run test.
> [202012][bgp] Skip test_bgp_queue for m0/mx

- tests/common/plugins/sanity_check/checks.py
Summary:
Fix the sanity check failure observed in 202305 branch nightly:
```
def _check_mux_status_helper():
run_result.clear()
duts_parsed_mux_status.clear()
>       err_msg_from_mux_status.clear()
E       AttributeError: 'list' object has no attribute 'clear'
```
Use assignment to empty list to clear.
Run `test_bgp_fact` with sanity check on 202305.
> [sanity check] Fix list clear attribute error

- tests/process_monitoring/test_critical_process_monitoring.py
Add orchagent heartbeat during warm-reboot UT
Add orchagent heartbeat during warm-reboot UT
- Microsoft ADO: 25295846
Fix orchagent stuck error during warm-reboot:
https://github.com/sonic-net/sonic-buildimage/issues/16686
Add new UT, freeze orchanget for warm-reboot then check the process listener not send alert.
Pass all UT
> Add orchagent heartbeat during warm-reboot UT

- tests/saitests/py3/sai_qos_tests.py
Double commit: #10163 
Summary:
Fixes specific T0 dualtor test cases that require more than the basic ports to run. ARP was only being performed on the src port and 3 dst ports, but not the rest. This fails tests like SharedResSize and QWatermarkAllPort since they require the ability to send traffic to/from all ports. 
Verified all test_qos_sai.py tests pass on Cisco-8000 dualtor T0 Active-Standby.
> ARP for all test port IDs - 202205

- tests/dualtor/test_ipinip.py
Port channel fails to come up after the above test. Port channel which
were UP, before the test. The script changes the minimum link from 2 to 1. Then performs
restarts the teamd and all is performed via a single command is likely causing this issue.
All the commands are issued via shell_cmds. Here it executes multiple commands
sequentially. However since multiple command were issued, the previous command may not have completed before
the new command could be executed. This is likely reason for the failure.
**Below is the original PR:**
https://github.com/sonic-net/sonic-mgmt/pull/8417
Summary:
I see this could be timing issue. Failure are seen sometime only. Could not repro the issues. But, looking at the PASS logs, I see messages for min link changes are still running while the next …
> ipinip delay merge conflict 202205

- tests/generic_config_updater/test_incremental_qos.py
Fix issue: https://github.com/sonic-net/sonic-mgmt/issues/10354
1. For mellanox device, it doesn't support removing qos config fields
2. When buffer model is the dynamic model, skip the test. Because for dynamic model, the qos config will be generated automatically and cannot be updated manually.
Summary:
https://github.com/sonic-net/sonic-mgmt/issues/10354
Fix issue: https://github.com/sonic-net/sonic-mgmt/issues/10354
1. For mellanox device, it doesn't support removing qos config fields
2. When buffer model is the dynamic model, skip the test. Because for dynamic model, the qos config will be generated automatically and cannot be updated manually.
Run test_incremental_qos_config_updates on the mellanox device
Mellanox
> [Mellanox] Fix test_incremental_qos_config_updates issue

- tests/dash/conftest.py
Summary:
The test is supported by SONiC now. Enable it by removing the skip.
Enable the dash vnet underlay route test cases.
Remove the skip in dash/conftest.py
Run test cases on Bluefield3 testbed, all passed.
> Remove the skip for underlay route in dash vnet test

- tests/crm/conftest.py
The port macs that connected with PTF directly(not Arista VMs) would be learned by swich from time to time.
And they would ocupy the FDB resources. It would affect the ipv4 route tests.
This PR would add a fixture to shutdown the unused ports before test, and restore them after test.
Summary:
Fixes 
Expected message “IPV4_ROUTE THRESHOLD_CLEAR for TH_FREE” not found issue
Expected message “IPV4_ROUTE THRESHOLD_CLEAR for TH_FREE” not found from time to time.
Add a fixture to shutdown the ports connect direcly with PTF(not the ports connect with Arista VMs) before test, and restore them after test.
Verified the modification by run it over community setups.
No
> Update conftest of crm test

- tests/show_techsupport/tech_support_cmds.py
- tests/show_techsupport/test_techsupport.py
Summary:
Fixes sonic-net/sonic-buildimage#17064
In the Bookworm kernel, /proc/sched_debug has been moved to debugfs. For now, don't collect this file. If this file is needed, and debugfs collection code gets added to techsupport, then this can be updated.
If the device is running on a kernel older than 5.13.0, then look for `/proc/sched_debug` to be present; otherwise, don't look for it.
Tested on a Bookworm KVM device.
> Don't look for /proc/sched_debug for Bookworm

- tests/vxlan/test_vxlan_ecmp.py
MSFT merged the following two issue one after another in same day:
https://github.com/sonic-net/sonic-mgmt/pull/9982
https://github.com/sonic-net/sonic-mgmt/pull/9969
The PR #9969 missed to change the code imported by #9982.
Summary:
Change "self.setup" to "self.vxlan_test_setup"
> fix the self.setup issue in vxlan script

- ansible/ansible.cfg
- ansible/roles/vm_set/tasks/main.yml
Summary:
We suffer from the ansible ssh timeout issue in the add-topo step from time to time:
```
TASK [vm_set : Add docker official GPG key] ************************************
task path: /root/mars/workspace/sonic-mgmt/ansible/roles/vm_set/tasks/docker.yml:1
Wednesday 12 July 2023  19:07:15 +0300 (0:00:00.053)       0:00:38.860 ******** 
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/packaging/os/apt_key.py
Pipelining is enabled.
<mtvr-r640-02> ESTABLISH SSH CONNECTION FOR USER: svc-nbu-sws-sonic
<mtvr-r640-02> SSH: ansible.cfg set ssh_args: (-o)(ControlMaster=auto)(-o)(ControlPersist=120s)(-o)(UserKnownHostsFile=/dev/null)(-o)(StrictHostKeyChecking=no)
<mtvr-r640-02> SSH: ANSIBLE_HOST_KEY_CHECKING/host_key_checking disabled: (-o)(StrictHostKeyChecking=no) …
```
> Fix the ansible timeout issue in the add-topo step

- .azure-pipelines/pr_test_scripts.yaml
- tests/memory_checker/test_memory_checker.py
Summary:
Fixes # (issue)25833282
Update test_memory_checker to dynamically check for gnmi or telemetry container 
Add logic to create correct container name fixture
Pipeline
> Update test_memory_checker to support gnmi and telemetry containers

- tests/pc/test_lag_2.py
Summary:
On dualtor testbed, each parameterized `test_lag_2` test case chooses DUT randomly, so let's ignore the `route_check` error logs on both ToRs.
> [test_lag_2] Ignore `route_check` failure log on all DUTs

- tests/generic_config_updater/test_ntp.py
Summary:
Fixes [#1254](https://github.com/sonic-net/SONiC/issues/1254)
To alignt the tests for new NTP configuration
Add a new test and left the old one as backward compatibility
By running it on the switch
> [NTP] Update tests for new NTP configuration

- tests/dash/proto_utils.py
Add a logic to set RouteRule().vnet only if pa_validation is set to true.
This is to allow a configuration with pa_validation=false which requires vnet field to not be set.
Summary:
> [dash] update proto_utils to allow pa_validation = false

- tests/memory_checker/test_memory_checker.py
Summary:
In Bookworm, when stopping/starting services, systemd will include the service file name in the Stopping/Starting message, along with the service name.
Modify the loganaylzer expected matches string to check to see if it being run on Bookworm; if so, include the service file name in the expected messages.
Manually tested on a Bookworm image, but without the gnmi container (so telemetry was used instead).
> Update test_memory_checker loganalyzer string for Bookworm

- .azure-pipelines/pr_test_scripts.yaml
- azure-pipelines.yml
- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Revert the macsec test skip PR, done earlier via PR #10246
> Remove macsec skip in 202305 added via PR #10246

- tests/qos/files/cisco/qos_param_generator.py
- tests/qos/qos_sai_base.py
Porting code from PR:9752 to 202305.
This PR is porting all the changes done to support cisco-8000 platform in 202205 to qos_sai_base.py to master.
Changes done:
Pick topo-any for single-asic runs and topo-t2 for multi-asic and multi-dut runs, only for cisco-8000.
Apply the change (1) to qos_param generator as well.
Skip clearing ARP and FDB for T2.
Add a new fixture to provide a static routes for every destination ip address for chassis-packet platforms only.
> Porting code from PR:9752 to 202305 - qos_sai_base.py changes to 202305.

- tests/vxlan/test_vxlan_ecmp.py
The PR#9969 fixed part of the issue caused by the python3 migration, but not all, fix the left over.
Summary: Make the test_vxlan_remove_route2  test case could pass
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/10335
Make the test_vxlan_remove_route2   could pass
convert the "setup" to "vxlan_test_setup"
The test case could pass
> [vxlan] Fixed failures caused by python 3 conversion

- tests/vxlan/test_vxlan_crm.py
Add topology marker for test_vxlan_crm script
There is no topology marker in the script of test_vxlan_crm 
Summary:
Lack of topology marker in script of test_vxlan_crm
There is no topology marker in the script of test_vxlan_crm 
Add a topologu marker
Run automation test
T1
>  [Mellanox] Add topology marker for test_vxlan_crm script

- tests/stress/test_stress_routes.py
Summary:
test_stress_routes was skipped for T1 topo, need to enable it.
test_stress_routes was skipped for T1 topo, need to enable it.
add topo t1 in the mark 
run test with T1 TB.
No.
> [stress route] Enable test_stress_routes for T1 topo

- ansible/group_vars/sonic/variables
- tests/dualtor/conftest.py
Summary:
Add Mellanox dualtor hwskus to the ansible variables and dualtor conftest.
Some dualtor tests will be skipped without this. 
Add Mellanox dualtor hwskus
Add the Mellanox-SN4600C-C64 hwsku.
Run dualtor/test_ipinip.py on 4600C dualtor testbed, all passed.
> [Nvidia] Add Mellanox dualtor hwskus

- tests/route/test_route_flap.py
Summary:
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/10811
> [Route flap] add module_ignore_errors to shell command to let it return empty output

- tests/drop_packets/drop_packets.py
Summary:
The PR is to fix syntax error in `drop_packet.py`.
```
>       setattr(pkt[testutils.scapy.scapy.all.IP], pkt_field, value)
E       AttributeError: 'module' object has no attribute 'scapy'
```
The PR is to fix syntax error in `drop_packet.py`.
Backport the change from master branch.
Verified by statically syntax check.
No.
> [202205] Fix syntax error in drop_packet.py

- tests/saitests/py3/sai_base_test.py
- tests/saitests/py3/sai_qos_tests.py
Fix issue: https://github.com/sonic-net/sonic-mgmt/issues/10299
Because the method to generate congestion for Mellanox device is changed from disabling the whole port to disabling the queue one by one, and when we recover the port, we also enable the queue one by one. So, it will cause testQosSaiDwrr to fail. testQosSaiDwrr is to test the function of scheduling queue to send packets, the pre-condition is that all queues should be at the same enabled state, but currently, they are enabled back one by one, so the order to send packets is the same as the order to enable the queue not depending on the scheduling algorithm. So, for this case, we still use the original method to generate congestion.
Summary:
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/10299
Fix issue : …
> [Mellanox|202205] Fix testQosSaiDwrr issue

- tests/common/reboot.py
- tests/platform_tests/test_reload_config.py
With some vendors the device may be slow to come up where the database container that needs to be up before this testcase can run may not be ready with just 60 seconds wait time. And this change will allow eliminating false failure for slower devices.
In addition, some device may not have onboard clock chip and relies on the supervisor to provide the current timestamp so the check under common/reboot.py right after reboot occurred the timestamp may go negative. The check for timestamp to determine if reboot took place may end up concluding incorrectly. So this is also addressed in this PR as well.
Summary:
Fixes # (issue) (did not file issue)
To reduce flaky test results for some slower platforms and device without onboard clock chip.
Before the fix:
```
2023-10-10T22:29:00.6107739Z …
```
> Fix flaky testcase test_reload_configuration_checks so slow device or device without clock chip can pass the test

- tests/system_health/test_watchdog.py
Improve watchdog UT to use LogAnalyzer
Improve watchdog UT to use LogAnalyzer
- Microsoft ADO: 25919530
watchdog UT failed, seems caused by log rotate.
LogAnalyzer can handle log rotate.
Improve watchdog UT to use LogAnalyzer
Pass all UT
> Improve watchdog UT to use LogAnalyzer

- tests/snmp/test_snmp_queue.py
Addresses https://github.com/sonic-net/sonic-mgmt/issues/10099 by adding filtering for the queue interfaces fetched from CONFIG_DB to choose only those on the current linecard.
Summary:
Fixes #10099 10099
Fix [10099](https://github.com/sonic-net/sonic-mgmt/issues/10099)
Filtered interfaces on the current linecard.
Ran updates test against a DUT that has both a single-asic and a multi-asic linecard.
> [sonic-mgmt snmp] Fix test_snmp_queue.py multi-asic support for multiple linecards

- tests/common/reboot.py
- tests/platform_tests/test_power_off_reboot.py
**Summary**
This PR improves the test_power_off_reboot test case's heler `_power_off_reboot_helper` that can help avoid the timing issue during the power off and power on procedure.
**Approach**
Use threading.Event() instead of sleep delay to avoid race condition.
There was nightly test failed due to power off took a while that exceed given delay time. To increase test reliability, we use semaphore way to ensure the time sequence.
Introducing threading.Event(), when we finished shutdown assertion, then can let semaphore release the flag, then power off helper will proceed the power on action as expected.
Put the change into lab device, then inspect the testlog.
**Any platform …
> Add an event to block power on action until power off finished.

- tests/common/mellanox_data.py
- tests/platform_tests/mellanox/check_sysfs.py
- tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
- tests/system_health/mellanox/mellanox_device_mocker.py
**Why I did this**
Some sysfs node names have been changed in production code, this PR is to align the changes based on different hw-management version
**How I did this**
For different hw-management version, sonic-mgmt code should use different sysfs node name.
**How I test it**
Run sonic-mgmt regression test
> Update sysfs node name/path according to production code change

- tests/acl/test_acl_outer_vlan.py
Summary:
test_acl_outer_vlan failed on some testbeds, and root cause is unknown unicast traffic discarded on leaf fanout switch.
Microsoft ADO: 25919519
test_acl_outer_vlan failed on some testbeds, and root cause is unknown unicast traffic discarded on leaf fanout switch.
Send packet to leaf fanout switch to learn MAC address, and then leaf fanout can find destination for unicast traffic.
Run test_acl_outer_vlan test.
> Fix unknown unicast issue

- tests/arp/test_tagged_arp.py
Summary:
test_tagged_arp started to failure since 20220531.45, but I can't reproduce it.
If this case failed, dump current status to verify if SONiC received arp packets.
Run test_tagged_arp
> Dump status to debug test_tagged_arp

- tests/templates/dual_tor_sniffer.conf.j2
Summary:
Fix the following issue:
```
Traffic on server 192.168.0.2 was disrupted after test end, missing 2 packets from the end of the packet flow
```
The reason is that, on `dualtor-120` testbed, `dual_tor_sniffer` sometimes takes around 45+ seconds to be stopped after receiving the `SIGINT`. This is because `dual_tor_sniffer` script captures more packets on `dualtor-120` as it has more vlan members and `dualtor-io` tests are sending more packets. After 30 seconds, `supervisorctl` will kill the `dual_tor_sniffer`, which will result in the loss of packets.
Let's increase the `stopwaitsecs` to 90s.
Run `dualtor-io` tests on `dualtor-120` testbed.
> [dualtor-io] Increase stop wait to 90s

- tests/saitests/py3/sai_qos_tests.py
Summary:
The PR is to fix `TypeError` in `sai_qos_tests.py`.
```
"Traceback (most recent call last):", "  File \"saitests/py3/sai_qos_tests.py\", line 1883, in runTest", "    pkts_num_egr_mem = int(self.test_params['pkts_num_egr_mem'])", "TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'", 
```
The error is because `pkts_num_egr_mem` is `None` in the arguments.
The PR is to fix `TypeError` in `sai_qos_tests.py`.
Check if the value is `None` before converting into `int`.
Verified on a SN2700 testbed.
```
collected 12 items …
```
> Fix TypeError in sai_qos_test

- tests/common/dualtor/mux_simulator_control.py
Summary:
Same purpose as PR: https://github.com/sonic-net/sonic-mgmt/pull/10555.
This is to ensure mux `auto` to save to `config_db.json` to avoid any unwanted modification.
Do a `config save` in teardown.
> [dualtor] Fix mux config manual leftover

- tests/passw_hardening/conftest.py
- tests/passw_hardening/passw_hardening_utils.py
- tests/passw_hardening/sample/passw_hardening_digits/common-password
- tests/passw_hardening/sample/passw_hardening_enable/common-password
- tests/passw_hardening/sample/passw_hardening_history/common-password
- tests/passw_hardening/sample/passw_hardening_lower_letter/common-password
- tests/passw_hardening/sample/passw_hardening_min_len/common-password
- tests/passw_hardening/sample/passw_hardening_reject_user_passw_match/common-password
- tests/passw_hardening/sample/passw_hardening_special_letter/common-password
- tests/passw_hardening/sample/passw_hardening_upper_letter/common-password
- tests/passw_hardening/test_passw_hardening.py
Fix the test to support Debian 12 by replacing cracklib usage with pwquality library
Summary:
Fix as part of Debian 12 support in SONiC
Fix Password Hardening tests to support Debian 12 modifications.
replace usage of pam_cracklib.so with pam_pwquality.so
run these PW hardening tests with the branch 112023 which based Debian 12
no
no
> password hardening: Fix the test to support Debian 12

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary: Added a conditional skip to vnet_route_leak test due to bug https://github.com/sonic-net/sonic-mgmt/issues/8374
> Add conditional skip for the vnet_route_leak by bug

- ansible/roles/fanout/templates/arista_7260cx3_deploy.j2
Summary:
Update EOS config template for Arista-7260cx3 leaf fanout. **Support using Et65/Et66 as trunk port.**
Update EOS config template for Arista-7260cx3 leaf fanout. Support using Et65/Et66 as trunk port.
Update J2 template.
Verified on physical `Arista-7260CX3` fanout switch.
> [Fanout] Update EOS config template for Arista-7260cx3 leaf fanout

- tests/common/plugins/sanity_check/recover.py
Summary:
For `adaptive_recover`, it will reboot if `monit` has failures. But the DUT keeps using the `config_db.json`, which might be corrupted by previous tests in nightly.
Let's reboot with the running golden config for the reboot in `adaptive_recover`.
Override `config_db.json` with the running golden config before reboot.
Run on dualtor testbed with monit service `routeCheck` fails and `config_db.json` is corrupted with mux config `manual`. 
Verify after reboot, monit is recovered and mux config is back to `auto`.
> [sanity_check] Use golden config to reboot for `adaptive_recover`

- tests/route/test_route_flap.py
Summary:
test_route_flap is flaky, sometimes errored out due to missed_frr_routes check, which is a transient log print, we should ignore it during route flap test.
Enhance robust of test_route_flap
Ignore error which is expected.
Run manual test.
03:02:53 test_route_flap.test_route_flap          L0384 INFO   | End
PASSED                                                                                                                                                                                                                                                   [100%]
> Enhance the test route flap

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
The test_vxlan_crm should only be running on select mlnx and Cisco T1 platforms. currently its running and failing on several other platforms.
Ado: 26006993
Updated conditional mark file to restrict the test run.
> Disable Vxlan_crm test for non cisco & mellanox platforms.

- tests/common/devices/sonic.py
Double commit of master PR #10144
The `minigraph_ptf_indices` structure maps port names to PTF indices. From the code context, it appears that `minigraph_port_indices` was used for this mapping, but multi-dut TBs caused problems with the PTF.
It seems the more reliable way to get the ptf indices is to compose together the port_name->port_index map (`minigraph_port_indices`), and the port_index->ptf_index map (`tbinfo['topo']['ptf_map'][str(dut_index)]`). 
The pre-existing initialization of this composition to include any members of the `port_index->ptf_index` map can leave duplicate ptf_index entries for down ports, especially in dualtor scenarios. See #10139. 
Remove the extra initialization on the composition construction. 
Summary:
Fixes #10139
Verified on dualtor TB for PCBB watermark …
> Set port->ptf_index map empty before construction - 202205

- tests/bgp/test_bgp_speaker.py
Sometimes, exabgp http_ready status would be false when test_bgp_speaker.py is running. It was due to default timeout of wait_tcp_connection is 30 seconds. When there is some poor server or some network issue, the exabgp http service would start slower, then the wait_tcp_connection check would return fails due to timeout.
Increase the timeout time would avoid this issue.
Summary:
Http ready check failure when start exabgp for bgp speaker test
Increase the timeout value
No
No
> Fix http_ready false issue

- tests/platform_tests/sfp/test_sfputil.py
Summary:
Update sfp test for [sonic-utilities](https://github.com/sonic-net/sonic-utilities) PR(#2953 ). The output of "not implemented" error is changed in the PR, need to align the test.
Current output:
admin@r-r740-07-bf3-sonic-01:~$ sudo sfputil show error-status --fetch-from-hardware
get_error_description NOT implemented for port Ethernet0
Update sfp test for sonic-utilities PR#2953
Please see the code change.
Run the test on dpu setup, test is skipped as expected.
> Update sfp test for sonic-utilities PR#2953

- ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Summary:
We found this message in the Debian 12 image, this is not an error but was captued by loganalyzer because of the key word "crash". We need to ignore it.
".* sonic systemd.* kdump-tools.service - Kernel crash dump capture service.*"
Add a syslog message to the log analyzer white list.
Add it to loganalyzer_common_ignore.txt.
By running regression.
> Add a syslog message to the log analyzer white list

- tests/fdb/test_fdb.py
Summary:
Reduce the `test_fdb` runtime on `dualtor-120` testbeds for two reasons:
1. it runs over 1h on `dualtor-120` nightly.
2. as it runs over `1h`, fdb is aged sometimes, so the fdb entry number check will fail.
Use dummy mac per port as `2` instead of `10`:
> [dualtor-120] Reduce `test_fdb` runtime

- ansible/roles/test/files/ptftests/fg_ecmp_test.py
- ansible/roles/test/files/ptftests/inner_hash_test.py
- tests/ecmp/inner_hashing/test_inner_hashing.py
- tests/ecmp/inner_hashing/test_inner_hashing_lag.py
- tests/ecmp/inner_hashing/test_wr_inner_hashing.py
- tests/ecmp/inner_hashing/test_wr_inner_hashing_lag.py
- tests/ecmp/test_fgnhg.py
This reverts commit ac802b63e1ce00fb876c78aa1d256c4a7e01c93e.
Summary:
Reverts the python3 migrate PR on 202205 because run_tests.sh is not supporting python3 on 202205.
Will fixing failures on local tests.
> Revert "[python3]migrate ecmp scripts to python3 (#5825)"

- ansible/roles/test/files/ptftests/py3/advanced-reboot.py
Summary:
In some cases, it looks like the tcpdump sniffer thread doesn't exit for whatever reason. This leads to the advanced reboot test case failing because this thread is stuck, even though the warm reboot on the device itself succeeded.
Rework this section of code so that if tcpdump doesn't exit within 5 seconds after SIGINT is sent (or SIGTERM, now), kill it forcefully.
Ran 10 warm reboots, verify that this issue wasn't hit in those 10 warm reboots.
There can still be other failures in infra code, though.
> [advanced-reboot]: Make sure tcpdump sniffer thread exits

- tests/bgp/test_bgp_authentication.py
Summary:
-  The '_test_bgp_authentication_' test fails, when the test selects t2-chassis supervisor as DUT in random.
-  This PR fixes issue the above issue for '_test_bgp_authentication_' test case.
- When a supervisor is selected in random as DUT for _test_bgp_authentication_ test case, test fails with the following error.
`E       Failed: ASIC instance not found for port eth0`
-  Exclude supervisor from the dut list.
- Ran the 'bgp_authentication' tests against a T2 chassis.
> Exclude supervisor from the dut list - BGP/test_bgp_authentication

- tests/ipfwd/test_nhop_group.py
Summary:
We don't need to initialize a new log analyzer instance in the test since the default one is enable on the test.
Remove the redundant log analyzer in next hop group test.
Use the default log analyzer instance initialized by plugin.
Run the test, passed and the syslog is analyzed correctly.
> Remove the redundant log analyzer in next hop group test

- tests/qos/qos_sai_base.py
IPv6 address is removed from docker0 when disabling IPv6 and this causes test_snmp_loopback testcase to fail
ARISTA06T1#bash snmpget -v2c -c public FC00:11::1 .1.3.6.1.2.1.1.1.0 (FC00:11::1 is the ipv6 address of the LC's loopback0)
Timeout: No Response from FC00:11::1.
% 'snmpget -v2c -c public FC00:11::1 .1.3.6.1.2.1.1.1.0' returned error code: 1
bash snmpget -v2c -c public FC00:11::1 .1.3.6.1.2.1.1.1.0 AssertionError: Sysdescr not found in SNMP result from IP FC00:11::1/128)
After enabling IPv6, an IPv6 address should be added to docker0 and a config reload is required.  
Summary:
To restore the docker0's IPv6 address which is removed when IPv6 is disabled
Add IPv6 address do docker0.
Do a config reload
Tested qos and snmp suites against a multi Asics line card on a T2 …
> Add docker0's IPv6 address since it was removed when disabling IPv6

- tests/platform_tests/counterpoll/test_counterpoll_watermark.py
Summary:
Sometime the test_counterpoll_watermark.py will fail due to:
RuntimeError: Sonic database config file doesn't exist at /var/run/redis/sonic-db/database_config.json
This is because test case reloads the config DB or does reboot and does not wait for enough time. Config DB is not ready.
Sometime the test_counterpoll_watermark.py will fail due to:
RuntimeError: Sonic database config file doesn't exist at /var/run/redis/sonic-db/database_config.json
This is because test case reloads the config DB or does reboot and does not wait for enough time. Config DB is not ready.
Add a sleep after config reload
Manually run with testbed
> Make stable for testcase test_counterpoll_watermark.py

- tests/common/devices/sonic_asic.py
- tests/crm/test_crm.py
Cherry-pick of PR #10342 in 202205
> Fix for test_crm_acl_entry test and py3 fix for API: port_on_asic() 

- tests/syslog/test_syslog_rate_limit.py
There is a race condition in the rate-limit-host test code.
Changing the rate limit via the cli triggers hostcfgd to restart rsyslogd. However there is no wait to make sure this actually happens. This leads to some flakyness where loganalyzer.py would try to put a marker while the rsyslog systemd service is being restarted and crash.
Fix flaky test to enhance pass rate reliability.
Reproduced on my testbed, investigated the issue, fixed the issue
Stressed the test overnight without further failure
> Fix issue with test_syslog_rate_limit

- tests/common/devices/sonic.py
- tests/platform_tests/api/test_sfp.py
- tests/platform_tests/sfp/test_sfputil.py
Summary:
1. Revert LPM test, because the implementation has been reverted to the old way.https://github.com/sonic-net/sonic-buildimage/pull/17096
2.  Fix issue of test_check_sfputil_low_power_mode. Previously after setting the lpmode, test checks the value is on or off, which is not correct. we should check if the value of lpmode is the set one.
3. When the cable type is OSPF and the power class is not "Power Class 1", it also supports LPM. So, add a check accordingly. 
Revert lpm test
Revert lpm test
Run lmp test on image inlcuding https://github.com/sonic-net/sonic-buildimage/pull/17096
> Revert LPM test due to design change back and fix some LPM test issues

- ansible/roles/test/files/ptftests/py3/bfd_responder.py
- tests/vxlan/vxlan_ecmp_utils.py
Change bfd_responder to support python3
Update ptf command for running bfd_responder
Change bfd_responder to support python3
Summary:
Change bfd_responder to support python3
Update bfd_responder.py
Change ptf command to support python3
Run it in Nvidia internal regression
No
> [Nvidia] Change bfd_responder support python3

- tests/platform_tests/api/test_sfp.py
1.The new 800G module OSFP-8X shares the same transceiver_info keys as QSFP-DD, add it to the logic for QSFP-DD. 2.host_lane_count does not have any relation with the count of the active_apsel_hostlane, update it to correct one. 
Summary: Update the expected key for the transceiver info test
Fix the failure of the test_get_transceiver_info and test_get_transceiver_threshold_info failure due to the unexpected key found in the transceiver info on the OSPF-8X cable.
Update the expected key for the OSPF-8X
After update the expected, the test case test_get_transceiver_info  and test_get_transceiver_threshold_info  could pass on OSFP-8X cabel
> Update the expected key for the transceiver info test

- tests/common/mellanox_data.py
For the psu capability, the psuX_volt_in_capability can be checked on any kind of platform.
For sn5600, need to check the psuX_volt_out2_capability, but not psuX_volt_out_capability.
Summary: Fix the issue in check sysfs on sn5600 platform
Fixes # (issue) Fix the issue in check sysfs on sn5600 platform
Fix the failure for the test_check_sysfs due to /var/run/hw-management/power/psu1_volt_out_capability not exist on the sn5600 platform
after the change, run the test_check_sysfs , and it could pass
> [Nvidia]Fix the issue in check sysfs on sn5600 platform

- tests/platform_tests/counterpoll/test_counterpoll_watermark.py
This test randomly picks a counter to test out of 3.
One check is only meant to run on one of these counter but ends up running for all counters.
There is another call for this check that is properly gated a few lines above, this fix essentially make sure it works the same.
The check actually works for all counters per my investigation but the delay is not sufficient for some older products. These take longer to properly populate data in COUNTERS_DB.
For this purpose a `wait_until` was introduced instead of an arbitrary sleep value.
Reduce test flakiness to increase passrate reliability
Investigated flaky test, reproduced and looked at the code to understand what went wrong
Ran the flaky test in a loop overnight.
This test seems flaky on slower products
> Fix test_counterpoll_watermark flakiness

- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Summary:  Fix test_show_platform_ssdhealth test for 7050QX-32S
For some reason this test was marked XFAIL though it passes fine on 202305+ It is likely related to enhancements made both to ssdutil and the arista platform library to gracefully handle emmc/eUSB devices
Remove the pytest mark forcing XFAIL on this test for the 7050QX-32S product
Ran the test and check it passed reliably
Only affecting Arista 7050QX-32S
> Fix test_show_platform_ssdhealth test for 7050QX-32S

- tests/platform_tests/api/test_sfp.py
- tests/platform_tests/sfp/test_sfputil.py
Summary:
1. Revert LPM test, because the implementation has been reverted to the old way.https://github.com/sonic-net/sonic-buildimage/pull/17179
2. Fix issue of test_check_sfputil_low_power_mode. Previously after setting the lpmode, test checks the value is on or off, which is not correct. we should check if the value of lpmode is the set one.
Revert lpm test
Revert lpm test
Run lmp test on after merging https://github.com/sonic-net/sonic-buildimage/pull/17179
> [202205] Revert LPM test due to design change back and fix the issue of issue of test_check_sfputil_low_power_mode

- tests/common/devices/sonic.py
- tests/platform_tests/api/test_sfp.py
- tests/platform_tests/sfp/test_sfputil.py
Summary:
1. Revert LPM test, because the implementation has been reverted to the old way.https://github.com/sonic-net/sonic-buildimage/pull/17096
2. Fix issue of test_check_sfputil_low_power_mode. Previously after setting the lpmode, test checks the value is on or off, which is not correct. we should check if the value of lpmode is the set one.
3. When the cable type is OSPF and the power class is not "Power Class 1", it also supports LPM. So, add a check accordingly. 
Revert lpm test
Revert lpm test
Run lmp test on image inlcuding https://github.com/sonic-net/sonic-buildimage/pull/17096
> [202305] Revert LPM test due to design change back and fix some LPM test issue

- ansible/plugins/connection/switch.py
Summary:
PR split # (https://github.com/sonic-net/sonic-mgmt/pull/10282)
When run pfcwd test suite using python3 following error appears:
TypeError: exec_command() got an unexpected keyword argument 'template'  fatal: [XX]: FAILED! => {  "msg": "Unexpected failure during module execution.",  "stdout": ""  } 
Run pfcwd TC using python3
Add fix in swith.py
Run pfcwd TC: /env-python3/bin/python3 -m pytest pfcwd/ --inventory="../ansible/inventory,../ansible/veos" --host-pattern  --module-path                ../ansible/library/ --testbed  --testbed_file ../ansible/testbed.csv                --allow_recover --assert plain --log-cli-level debug --show-capture=no -ra --showlocals -v \ --topology t0,any,util
> Fix python3 error in pfcwd test suite

- tests/bgp/test_bgp_slb.py
Summary:
Dualtor doesn't support the fast reboot, let's skip it on the dualtor testbeds.
```
bgp/test_bgp_slb.py::test_bgp_slb_neighbor_persistence_across_advanced_reboot[warm-str-xxxx-acs-12-default] PASSED [ 50%]
bgp/test_bgp_slb.py::test_bgp_slb_neighbor_persistence_across_advanced_reboot[fast-str-xxxx-acs-12-default] SKIPPED [100%]
```
> [bgp] Skip bgp slb fast reboot test on dualtor

- .azure-pipelines/common.py
- .azure-pipelines/upgrade_image.py
There are some public functions in script `.azure-pipelines/upgrade_image.py`, which will be used by other scripts. In this PR, I move these functions to common file, thus others can share these functions. 
Summary:
There are some public functions in script `.azure-pipelines/upgrade_image.py`, which will be used by other scripts. In this PR, I move these functions to common file, thus others can share these functions. 
I move some public functions to common file, thus others can share these functions.
> Move public functions from `upgrade_image.py` to `common.py`.

- tests/common/devices/sonic.py
- tests/dns/static_dns/conftest.py
- tests/dns/static_dns/static_dns_util.py
- tests/dns/static_dns/test_static_dns.py
4 test cases added to verify the static DNS feature Here PR for the test plan: https://github.com/sonic-net/sonic-mgmt/pull/8436
Summary:  Add new test cases to cover the static dns feature. https://github.com/sonic-net/SONiC/pull/1262
Add test cases to cover the static dns feature
> Add static DNS test cases

- tests/crm/test_crm.py
Fixes #10990 
The conditional added in https://github.com/sonic-net/sonic-mgmt/pull/10342 doesn't work on single-asic systems:
```
(Pdb) asichost.namespace
(Pdb) asichost
<SonicAsic 0>
(Pdb) lagData['namespace']
u''
```
Skip the check on single-asic systems
> crm/test_crm.py: Skip namespace check on single asic systems

- tests/common/devices/sonic_asic.py
Summary:
202205 version of https://github.com/sonic-net/sonic-mgmt/pull/10482
> Fix the portchannel_on_asic() method to handle asic with no portchannels (202205)

- tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
test_decap is not supported for TH2 T1 in 202305 release, skip this test.
Skip test in conditional mark.
Manual verify it.
> [conditional mark] skip test_decap for 7260cx3 in 202305 release

- tests/platform_tests/conftest.py
Summary:
For fast-reboot, it's currently assumed that the number of PORT_READY messages will equal the number of ports that are up; for warm-reboot, there should be 0 PORT_READY messages. However, on some platforms, it seems that there are no PORT_READY messages generated with state changes (i.e. where the port changes from down to up) during fast-reboot.
For now, loosen the check for the number of PORT_READY messages to accept fewer messages.
Change made primarily for Mellanox platforms.
> Allow fewer PORT_READY messages than expected

- ansible/roles/sonic/templates/configdb.j2
Summary:
When bringing up a topology with SONiC neighbors, specify the minimum number of links that must be up for a portchannel to be up. This matches the behavior on cEOS neighbors, specifically on topo configurations with portchannels having 2 or more member links.
Tested on t0-64-32 topo, where port channel links have 2 members.
> vSONiC: Specify minimum number of links for portchannels

- ansible/dualtor/nic_simulator/nic_simulator.py
Summary:
Add `packet_filter` and `drop` to the attribute list.
Run `nic_simulator`
> [nic_simulator] Add missing attribute in the slot

- tests/sub_port_interfaces/conftest.py
sub_port_interfaces/test_sub_port_interfaces.py::TestSubPorts::test_routing_between_sub_ports is using ip address 172.17.0.1/30 and 172.17.0.5/30 on L3 RIF port. This ip is overlapping forced_mgmt_routes: ['172.17.0.1/24'] ip.
Since 172.17.0.x/24 is forced to go over management interface, below test in sub_port module is failing as packet not routed to front panel port 
FAILED sub_port_interfaces/test_sub_port_interfaces.py::TestSubPorts::test_routing_between_sub_ports[port_in_lag-same-TCP-UDP-ICMP]
FAILED sub_port_interfaces/test_sub_port_interfaces.py::TestSubPorts::test_routing_between_sub_ports[port_in_lag-different-TCP-UDP-ICMP]
FAILED sub_port_interfaces/test_sub_port_interfaces.py::TestSubPorts::test_routing_between_sub_ports_and_port[port_in_lag-svi-TCP-UDP-ICMP]
FAILED …
> Change IP address used in sub_port module which is overlapping the forced_mgmt_routes
